package com.smartapp.b.fidhydxcod;

import android.app.Activity;
import android.graphics.Color;
import android.os.Bundle;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.CheckBox;
import android.widget.DatePicker;
import android.widget.EditText;
import android.widget.FrameLayout;
import android.widget.GridView;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ListView;
import android.widget.ProgressBar;
import android.widget.RadioButton;
import android.widget.RatingBar;
import android.widget.RelativeLayout;
import android.widget.ScrollView;
import android.widget.SeekBar;
import android.widget.Spinner;
import android.widget.Switch;
import android.widget.TableLayout;
import android.widget.TextView;
import android.widget.TimePicker;
import android.widget.ToggleButton;
import android.widget.ViewFlipper;
import androidx.constraintlayout.core.motion.utils.TypedValues;
import androidx.core.view.PointerIconCompat;
import androidx.room.RoomDatabase;
import com.baidu.location.BDLocation;
import com.google.android.gms.common.ConnectionResult;
import com.luck.picture.lib.config.PictureConfig;
import com.qcwireless.qcwatch.ui.home.healthy.vm.HealthyViewModel;
import com.realsil.sdk.bbpro.core.protocol.Contract;
import com.realsil.sdk.core.bluetooth.connection.le.GattClient;
import com.realsil.sdk.core.bluetooth.connection.legacy.BluetoothSpp;
import okhttp3.internal.ws.WebSocketProtocol;

/* loaded from: classes4.dex */
public class OcurhpqsnewActivity extends Activity {
    ScrollView afbtsjbohi;
    ProgressBar ahdkybtoum;
    Button akaxlnyonx;
    TextView akihwtdprs;
    FrameLayout alvmoviesh;
    TableLayout amqbtjtbqk;
    TableLayout aqykpjoyxi;
    TableLayout asdlyplbqs;
    LinearLayout atofqlnugn;
    SeekBar atpslfranj;
    Switch atzhpetzyh;
    FrameLayout awjsybfuvr;
    Switch awyvndjxlt;
    FrameLayout axrgxjtagv;
    RadioButton axucfggbvl;
    Spinner axukfzvwjj;
    DatePicker ayethjqbaj;
    RatingBar bbhvbczbxp;
    ViewFlipper bdffobiidt;
    CheckBox bdkxkcqjtp;
    TextView bfuzddzukt;
    ImageView bgryxoxphj;
    GridView biyozoferz;
    TextView bjpivltweb;
    LinearLayout bjtygjaqdg;
    RadioButton bmaxhhaknw;
    ViewFlipper bnimwwcugz;
    Spinner cezenatfub;
    ProgressBar cjxmnnfdic;
    Switch cmitnafxtz;
    RelativeLayout csxthuqxfg;
    Switch ctheimpwxk;
    ScrollView cuzpmhvwsg;
    ProgressBar cvoxkmfyyb;
    DatePicker cwchzsiild;
    RadioButton cwgpkgbfdd;
    LinearLayout cynoagjdgo;
    GridView dayclyvsmr;
    Switch dazpcefopd;
    SeekBar dckdrndxrs;
    RatingBar dcqmhajunk;
    Switch deactyhvco;
    CheckBox dfahunzqep;
    ProgressBar dgflesbjic;
    CheckBox dmeegndsbq;
    TextView dmjlsydagg;
    TableLayout dmyckvrxgx;
    Switch dornwkosuf;
    RelativeLayout drmbtrltrd;
    SeekBar druohdpjsh;
    ToggleButton dvtkkybzny;
    ViewFlipper egveezafim;
    Spinner ekglkndsqp;
    ViewFlipper eobcwdpjdy;
    Spinner esscpaurdk;
    RelativeLayout evduxckozy;
    RatingBar ewecrllsay;
    LinearLayout fdezvpcmtk;
    ToggleButton fecocgmdft;
    FrameLayout fiiwvcdvlw;
    ListView fledeseypw;
    RatingBar fpclipbkhn;
    ScrollView fpeplscvfr;
    TableLayout fuoczmgeni;
    ViewFlipper fvckkeyodn;
    TextView fveqvzvqvf;
    ImageView fybpwqlqox;
    Switch gbjhkjyxvo;
    Switch ggbbonwxns;
    RatingBar ghisyffrue;
    ImageView gmdmouhjfo;
    TextView hadmlsjyxq;
    TextView hchiucxtwb;
    TextView hoyrovhdur;
    Switch hrljjihnyo;
    GridView hvclnnbyxl;
    LinearLayout hxukdhjuoc;
    ViewFlipper ibeaiyyjgh;
    ToggleButton iemegxzyvi;
    LinearLayout ifdtkeeavy;
    EditText ihohxgcfwt;
    RadioButton ihtdwbiihh;
    LinearLayout iiwdmbbdqk;
    EditText iofqazdszs;
    RadioButton iqljslqaaj;
    TimePicker ivzuanexab;
    ViewFlipper izccrobrtb;
    GridView izsgrntkvw;
    Switch jbxirpqgkm;
    ListView jddisnccpl;
    FrameLayout jduovuwmmr;
    LinearLayout jhpqmhgrsu;
    FrameLayout jjdiylryrp;
    TextView jmiyeeadse;
    TableLayout jncbhnfgik;
    ListView jrgcytldob;
    Spinner jzfnxbuszc;
    TableLayout kbpffeukwb;
    TimePicker kebamvwgti;
    TableLayout khbcvgjsvq;
    SeekBar kjtqrftffo;
    ImageView knqkzhtgtt;
    GridView ksivijzhes;
    RadioButton ksqxyielfo;
    ProgressBar kucdkindqc;
    RadioButton kvldzukllf;
    RadioButton kwxygtketv;
    Switch lbyecbnsjk;
    ListView lcqjzpcyel;
    ViewFlipper ldbykrvjty;
    GridView lhcioybnkc;
    RelativeLayout liqpjcgqnz;
    RadioButton ljbqzithqw;
    RadioButton lmpbrvbjms;
    RatingBar lrrksgynuk;
    TimePicker lsptohmghy;
    Switch mcfueaizmy;
    EditText mkfbaeesox;
    DatePicker mpnkpgcijd;
    Button mqvvpiqfey;
    Switch mscqxwaeie;
    ImageView mtyjstvfez;
    TimePicker mvldxjbaox;
    LinearLayout naghkzivcj;
    ToggleButton nekpyxwymy;
    Spinner nfehznxiaz;
    LinearLayout nggalaheej;
    TextView nnulhpbrnd;
    Spinner nohfvkzzgf;
    Button npjignvrsq;
    RadioButton okbrizelcf;
    RelativeLayout olouvdelgx;
    GridView olwdtazgym;
    GridView onhecioids;
    Switch ooledlngnd;
    SeekBar ovdjpbhsuk;
    CheckBox ovlbmrawzn;
    GridView oxyqhhtcpk;
    Button pdrcgwwyst;
    ToggleButton pfcibwxwkv;
    FrameLayout pquxdkaayw;
    ProgressBar ptlyabvxze;
    EditText ptzwdmjsxd;
    TextView puzbfdpqtn;
    ScrollView qafqbjjckb;
    FrameLayout qcmkcnjnna;
    ToggleButton qdhzptnmyr;
    DatePicker qdqvwxwxbg;
    ViewFlipper qfelasvtff;
    ProgressBar qnuaohbmel;
    ScrollView qrmhvvabyv;
    ToggleButton qwlujmaytf;
    TableLayout qxllzpayvr;
    ImageView rabhalopxb;
    ProgressBar rkevhygmvy;
    SeekBar rlyenuolru;
    CheckBox rphdmjwyrh;
    Switch rtruapjvfv;
    TableLayout rxpkmuqdyn;
    RelativeLayout sarqwxoejt;
    ImageView sgowmyjksa;
    DatePicker shkxwojkhn;
    Switch sigryumbka;
    TextView skdefajihz;
    ScrollView sqtqjukjwd;
    ToggleButton srubqnapgd;
    ViewFlipper szjaqrzblw;
    FrameLayout szqschlhmx;
    RelativeLayout tcdjehmrlq;
    ViewFlipper tdiarrngvr;
    RelativeLayout tgrqctxrky;
    GridView tgznqvqsyj;
    RatingBar thjsqttqaj;
    ProgressBar tmiwdqkiwj;
    TextView tpnweeywzz;
    EditText tvtgslptye;
    ListView txpqwxtfpa;
    ScrollView uatwqicada;
    TimePicker ubejfdhrch;
    RelativeLayout ubnpzgvumm;
    GridView ubonejzzuz;
    CheckBox ucxwqgmzmc;
    SeekBar ukdllutzbk;
    TimePicker unmnoawlyy;
    TableLayout urvkbgtqgw;
    ImageView uwfofjwilh;
    ToggleButton uwoadazzlv;
    FrameLayout vdckjmkjmp;
    RatingBar veonghyvpm;
    ViewFlipper vghkaghcht;
    DatePicker vgsqgxxstf;
    LinearLayout vgydxkrobc;
    RelativeLayout vivzrhbrgf;
    FrameLayout vnznweojia;
    SeekBar vrjgudjasc;
    RatingBar vsklvbbedb;
    SeekBar vswrpooqqw;
    SeekBar vudxoecdiw;
    RadioButton wdttskgcpn;
    Switch wezzynkpzt;
    LinearLayout whkqpfuzho;
    ToggleButton wlderxztoo;
    SeekBar wndoorifbj;
    RelativeLayout wppymmjqqg;
    ViewFlipper wribgerezp;
    EditText wzroyvmfon;
    ProgressBar xdpwpehdqc;
    ToggleButton xlinidmysa;
    ViewFlipper xqouvvnoqn;
    ViewFlipper xwkuzpepvo;
    SeekBar xybvcfbfbv;
    TextView xytdpbzcag;
    ImageView xzmfqkfkic;
    RadioButton yeknqcjxwx;
    Spinner yfhsgtcybe;
    RelativeLayout yirupqmedr;
    LinearLayout ypdfkhhenz;
    ScrollView yvpfcvfojx;
    RelativeLayout ywxsmpxkex;
    FrameLayout zcsdzyxnjl;
    TextView zfjtlxrnqf;
    RelativeLayout zgxmydhdih;
    ListView zilnybltls;
    SeekBar zrbdkizdyq;
    Button zsxlsnboii;

    @Override // android.app.Activity
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        LinearLayout linearLayout = new LinearLayout(this);
        setContentView(linearLayout);
        linearLayout.setLayoutParams(new ViewGroup.LayoutParams(-1, -1));
        linearLayout.setOrientation(1);
        linearLayout.setBackgroundColor(Color.parseColor("#5dfef5"));
        Switch r2 = new Switch(this);
        this.lbyecbnsjk = r2;
        r2.setLayoutParams(new LinearLayout.LayoutParams(1982, 1940));
        this.lbyecbnsjk.setPadding(168, 115, 114, 123);
        linearLayout.addView(this.lbyecbnsjk);
        this.lbyecbnsjk.setBackgroundColor(Color.parseColor("#a63846"));
        ListView listView = new ListView(this);
        this.fledeseypw = listView;
        listView.setLayoutParams(new LinearLayout.LayoutParams(1807, 472));
        this.fledeseypw.setPadding(40, 112, 21, 89);
        linearLayout.addView(this.fledeseypw);
        this.fledeseypw.setBackgroundColor(Color.parseColor("#1b0b8a"));
        EditText editText = new EditText(this);
        this.iofqazdszs = editText;
        editText.setLayoutParams(new LinearLayout.LayoutParams(1272, 841));
        this.iofqazdszs.setPadding(4, 104, 81, 182);
        linearLayout.addView(this.iofqazdszs);
        this.iofqazdszs.setBackgroundColor(Color.parseColor("#e25841"));
        GridView gridView = new GridView(this);
        this.tgznqvqsyj = gridView;
        gridView.setLayoutParams(new LinearLayout.LayoutParams(1163, 236));
        this.tgznqvqsyj.setPadding(143, 51, 186, 67);
        linearLayout.addView(this.tgznqvqsyj);
        this.tgznqvqsyj.setBackgroundColor(Color.parseColor("#3c8c67"));
        RadioButton radioButton = new RadioButton(this);
        this.iqljslqaaj = radioButton;
        radioButton.setLayoutParams(new LinearLayout.LayoutParams(1612, 1080));
        this.iqljslqaaj.setPadding(103, 194, 193, 0);
        linearLayout.addView(this.iqljslqaaj);
        this.iqljslqaaj.setBackgroundColor(Color.parseColor("#221ca1"));
        Spinner spinner = new Spinner(this);
        this.yfhsgtcybe = spinner;
        spinner.setLayoutParams(new LinearLayout.LayoutParams(1902, 1990));
        this.yfhsgtcybe.setPadding(124, 73, 129, 156);
        linearLayout.addView(this.yfhsgtcybe);
        this.yfhsgtcybe.setBackgroundColor(Color.parseColor("#21aa88"));
        FrameLayout frameLayout = new FrameLayout(this);
        this.zcsdzyxnjl = frameLayout;
        frameLayout.setLayoutParams(new LinearLayout.LayoutParams(1909, 104));
        this.zcsdzyxnjl.setPadding(39, 122, 70, 145);
        linearLayout.addView(this.zcsdzyxnjl);
        this.zcsdzyxnjl.setBackgroundColor(Color.parseColor("#6e7708"));
        ViewFlipper viewFlipper = new ViewFlipper(this);
        this.egveezafim = viewFlipper;
        viewFlipper.setLayoutParams(new LinearLayout.LayoutParams(975, 275));
        this.egveezafim.setPadding(75, 37, 98, 165);
        linearLayout.addView(this.egveezafim);
        this.egveezafim.setBackground(new Dqccjnjoahn());
        ViewFlipper viewFlipper2 = new ViewFlipper(this);
        this.wribgerezp = viewFlipper2;
        viewFlipper2.setLayoutParams(new LinearLayout.LayoutParams(1810, 1606));
        this.wribgerezp.setPadding(171, 151, 105, 179);
        linearLayout.addView(this.wribgerezp);
        this.wribgerezp.setBackgroundColor(Color.parseColor("#12db6c"));
        GridView gridView2 = new GridView(this);
        this.izsgrntkvw = gridView2;
        gridView2.setLayoutParams(new LinearLayout.LayoutParams(1754, 784));
        this.izsgrntkvw.setPadding(15, 121, 75, 146);
        linearLayout.addView(this.izsgrntkvw);
        this.izsgrntkvw.setBackgroundColor(Color.parseColor("#51b74e"));
        Switch r22 = new Switch(this);
        this.ooledlngnd = r22;
        r22.setLayoutParams(new LinearLayout.LayoutParams(715, 898));
        this.ooledlngnd.setPadding(101, 83, 78, 74);
        linearLayout.addView(this.ooledlngnd);
        this.ooledlngnd.setBackgroundColor(Color.parseColor("#75a379"));
        ToggleButton toggleButton = new ToggleButton(this);
        this.nekpyxwymy = toggleButton;
        toggleButton.setLayoutParams(new LinearLayout.LayoutParams(1971, 932));
        this.nekpyxwymy.setPadding(191, 122, 9, 55);
        linearLayout.addView(this.nekpyxwymy);
        this.nekpyxwymy.setBackgroundColor(Color.parseColor("#d35d1e"));
        ViewFlipper viewFlipper3 = new ViewFlipper(this);
        this.tdiarrngvr = viewFlipper3;
        viewFlipper3.setLayoutParams(new LinearLayout.LayoutParams(1120, 1144));
        this.tdiarrngvr.setPadding(158, 46, 111, 64);
        linearLayout.addView(this.tdiarrngvr);
        this.tdiarrngvr.setBackgroundColor(Color.parseColor("#0aa9fa"));
        Spinner spinner2 = new Spinner(this);
        this.axukfzvwjj = spinner2;
        spinner2.setLayoutParams(new LinearLayout.LayoutParams(28, 218));
        this.axukfzvwjj.setPadding(99, 59, 0, 82);
        linearLayout.addView(this.axukfzvwjj);
        this.axukfzvwjj.setBackgroundColor(Color.parseColor("#26018b"));
        TimePicker timePicker = new TimePicker(this);
        this.mvldxjbaox = timePicker;
        timePicker.setLayoutParams(new LinearLayout.LayoutParams(1823, 891));
        this.mvldxjbaox.setPadding(59, 132, 59, 154);
        linearLayout.addView(this.mvldxjbaox);
        this.mvldxjbaox.setBackgroundColor(Color.parseColor("#7e6b3f"));
        RadioButton radioButton2 = new RadioButton(this);
        this.yeknqcjxwx = radioButton2;
        radioButton2.setLayoutParams(new LinearLayout.LayoutParams(1289, 1845));
        this.yeknqcjxwx.setPadding(46, BDLocation.TypeNetWorkLocation, 35, 76);
        linearLayout.addView(this.yeknqcjxwx);
        this.yeknqcjxwx.setBackgroundColor(Color.parseColor("#a071fa"));
        DatePicker datePicker = new DatePicker(this);
        this.vgsqgxxstf = datePicker;
        datePicker.setLayoutParams(new LinearLayout.LayoutParams(1074, 240));
        this.vgsqgxxstf.setPadding(132, 72, 12, 33);
        linearLayout.addView(this.vgsqgxxstf);
        this.vgsqgxxstf.setBackgroundColor(Color.parseColor("#94d95d"));
        SeekBar seekBar = new SeekBar(this);
        this.rlyenuolru = seekBar;
        seekBar.setLayoutParams(new LinearLayout.LayoutParams(PointerIconCompat.TYPE_TOP_RIGHT_DIAGONAL_DOUBLE_ARROW, 523));
        this.rlyenuolru.setPadding(67, 120, 72, 165);
        linearLayout.addView(this.rlyenuolru);
        this.rlyenuolru.setBackgroundColor(Color.parseColor("#ae3e69"));
        ViewFlipper viewFlipper4 = new ViewFlipper(this);
        this.qfelasvtff = viewFlipper4;
        viewFlipper4.setLayoutParams(new LinearLayout.LayoutParams(1933, 1822));
        this.qfelasvtff.setPadding(80, 169, 10, 149);
        linearLayout.addView(this.qfelasvtff);
        this.qfelasvtff.setBackgroundColor(Color.parseColor("#116f1e"));
        Switch r23 = new Switch(this);
        this.dornwkosuf = r23;
        r23.setLayoutParams(new LinearLayout.LayoutParams(1443, 515));
        this.dornwkosuf.setPadding(57, 64, 55, 103);
        linearLayout.addView(this.dornwkosuf);
        this.dornwkosuf.setBackgroundColor(Color.parseColor("#afcad5"));
        SeekBar seekBar2 = new SeekBar(this);
        this.ovdjpbhsuk = seekBar2;
        seekBar2.setLayoutParams(new LinearLayout.LayoutParams(1181, 1132));
        this.ovdjpbhsuk.setPadding(36, 183, 68, 195);
        linearLayout.addView(this.ovdjpbhsuk);
        this.ovdjpbhsuk.setBackgroundColor(Color.parseColor("#45e58c"));
        CheckBox checkBox = new CheckBox(this);
        this.dfahunzqep = checkBox;
        checkBox.setLayoutParams(new LinearLayout.LayoutParams(891, 1623));
        this.dfahunzqep.setPadding(15, 41, 119, 168);
        linearLayout.addView(this.dfahunzqep);
        this.dfahunzqep.setBackgroundColor(Color.parseColor("#08dd07"));
        ViewFlipper viewFlipper5 = new ViewFlipper(this);
        this.ibeaiyyjgh = viewFlipper5;
        viewFlipper5.setLayoutParams(new LinearLayout.LayoutParams(217, 358));
        this.ibeaiyyjgh.setPadding(19, 187, 54, 137);
        linearLayout.addView(this.ibeaiyyjgh);
        this.ibeaiyyjgh.setBackgroundColor(Color.parseColor("#de5d65"));
        ViewFlipper viewFlipper6 = new ViewFlipper(this);
        this.xwkuzpepvo = viewFlipper6;
        viewFlipper6.setLayoutParams(new LinearLayout.LayoutParams(797, 1732));
        this.xwkuzpepvo.setPadding(135, 95, WebSocketProtocol.PAYLOAD_SHORT, 181);
        linearLayout.addView(this.xwkuzpepvo);
        this.xwkuzpepvo.setBackgroundColor(Color.parseColor("#0b7e7e"));
        RadioButton radioButton3 = new RadioButton(this);
        this.kvldzukllf = radioButton3;
        radioButton3.setLayoutParams(new LinearLayout.LayoutParams(339, 1177));
        this.kvldzukllf.setPadding(30, 91, 90, 181);
        linearLayout.addView(this.kvldzukllf);
        this.kvldzukllf.setBackgroundColor(Color.parseColor("#f9e1fc"));
        LinearLayout linearLayout2 = new LinearLayout(this);
        this.ypdfkhhenz = linearLayout2;
        linearLayout2.setLayoutParams(new LinearLayout.LayoutParams(1631, 1205));
        this.ypdfkhhenz.setPadding(101, 135, 25, 0);
        linearLayout.addView(this.ypdfkhhenz);
        this.ypdfkhhenz.setBackgroundColor(Color.parseColor("#e84c56"));
        ProgressBar progressBar = new ProgressBar(this);
        this.cjxmnnfdic = progressBar;
        progressBar.setLayoutParams(new LinearLayout.LayoutParams(RoomDatabase.MAX_BIND_PARAMETER_CNT, 1331));
        this.cjxmnnfdic.setPadding(84, 84, 138, 18);
        linearLayout.addView(this.cjxmnnfdic);
        this.cjxmnnfdic.setBackgroundColor(Color.parseColor("#74bd98"));
        TextView textView = new TextView(this);
        this.xytdpbzcag = textView;
        textView.setLayoutParams(new LinearLayout.LayoutParams(1954, PictureConfig.CHOOSE_REQUEST));
        this.xytdpbzcag.setPadding(135, 144, 158, 51);
        linearLayout.addView(this.xytdpbzcag);
        this.xytdpbzcag.setBackgroundColor(Color.parseColor("#326094"));
        TextView textView2 = new TextView(this);
        this.skdefajihz = textView2;
        textView2.setLayoutParams(new LinearLayout.LayoutParams(105, 564));
        this.skdefajihz.setPadding(121, 102, 42, 147);
        linearLayout.addView(this.skdefajihz);
        this.skdefajihz.setBackgroundColor(Color.parseColor("#609f4d"));
        Button button = new Button(this);
        this.mqvvpiqfey = button;
        button.setLayoutParams(new LinearLayout.LayoutParams(1440, 730));
        this.mqvvpiqfey.setPadding(21, 172, 0, 99);
        linearLayout.addView(this.mqvvpiqfey);
        this.mqvvpiqfey.setBackgroundColor(Color.parseColor("#32c0dd"));
        TableLayout tableLayout = new TableLayout(this);
        this.rxpkmuqdyn = tableLayout;
        tableLayout.setLayoutParams(new LinearLayout.LayoutParams(1433, 1968));
        this.rxpkmuqdyn.setPadding(BDLocation.TypeServerDecryptError, 165, 65, 7);
        linearLayout.addView(this.rxpkmuqdyn);
        this.rxpkmuqdyn.setBackgroundColor(Color.parseColor("#44c1b9"));
        ProgressBar progressBar2 = new ProgressBar(this);
        this.tmiwdqkiwj = progressBar2;
        progressBar2.setLayoutParams(new LinearLayout.LayoutParams(798, 498));
        this.tmiwdqkiwj.setPadding(153, 69, 58, 87);
        linearLayout.addView(this.tmiwdqkiwj);
        this.tmiwdqkiwj.setBackgroundColor(Color.parseColor("#4a3566"));
        TableLayout tableLayout2 = new TableLayout(this);
        this.jncbhnfgik = tableLayout2;
        tableLayout2.setLayoutParams(new LinearLayout.LayoutParams(1073, 1963));
        this.jncbhnfgik.setPadding(165, 187, 63, 36);
        linearLayout.addView(this.jncbhnfgik);
        this.jncbhnfgik.setBackgroundColor(Color.parseColor("#e4215f"));
        TimePicker timePicker2 = new TimePicker(this);
        this.unmnoawlyy = timePicker2;
        timePicker2.setLayoutParams(new LinearLayout.LayoutParams(1562, 1867));
        this.unmnoawlyy.setPadding(23, 192, 176, 86);
        linearLayout.addView(this.unmnoawlyy);
        this.unmnoawlyy.setBackgroundColor(Color.parseColor("#e96071"));
        ViewFlipper viewFlipper7 = new ViewFlipper(this);
        this.xqouvvnoqn = viewFlipper7;
        viewFlipper7.setLayoutParams(new LinearLayout.LayoutParams(868, 253));
        this.xqouvvnoqn.setPadding(196, 119, 152, PictureConfig.CHOOSE_REQUEST);
        linearLayout.addView(this.xqouvvnoqn);
        this.xqouvvnoqn.setBackgroundColor(Color.parseColor("#1e074b"));
        TextView textView3 = new TextView(this);
        this.akihwtdprs = textView3;
        textView3.setLayoutParams(new LinearLayout.LayoutParams(1693, 12));
        this.akihwtdprs.setPadding(109, 62, 68, 29);
        linearLayout.addView(this.akihwtdprs);
        this.akihwtdprs.setBackgroundColor(Color.parseColor("#8b475b"));
        RelativeLayout relativeLayout = new RelativeLayout(this);
        this.evduxckozy = relativeLayout;
        relativeLayout.setLayoutParams(new LinearLayout.LayoutParams(544, 1308));
        this.evduxckozy.setPadding(BDLocation.TypeServerDecryptError, 193, 134, 4);
        linearLayout.addView(this.evduxckozy);
        this.evduxckozy.setBackgroundColor(Color.parseColor("#a56c74"));
        FrameLayout frameLayout2 = new FrameLayout(this);
        this.szqschlhmx = frameLayout2;
        frameLayout2.setLayoutParams(new LinearLayout.LayoutParams(648, 1566));
        this.szqschlhmx.setPadding(11, 31, 78, 0);
        linearLayout.addView(this.szqschlhmx);
        this.szqschlhmx.setBackgroundColor(Color.parseColor("#e224b1"));
        RelativeLayout relativeLayout2 = new RelativeLayout(this);
        this.sarqwxoejt = relativeLayout2;
        relativeLayout2.setLayoutParams(new LinearLayout.LayoutParams(1916, 869));
        this.sarqwxoejt.setPadding(11, 140, 73, 16);
        linearLayout.addView(this.sarqwxoejt);
        this.sarqwxoejt.setBackgroundColor(Color.parseColor("#bfcafa"));
        ViewFlipper viewFlipper8 = new ViewFlipper(this);
        this.ldbykrvjty = viewFlipper8;
        viewFlipper8.setLayoutParams(new LinearLayout.LayoutParams(1049, TypedValues.MotionType.TYPE_ANIMATE_CIRCLEANGLE_TO));
        this.ldbykrvjty.setPadding(98, 86, 105, 101);
        linearLayout.addView(this.ldbykrvjty);
        this.ldbykrvjty.setBackgroundColor(Color.parseColor("#a1c76c"));
        ToggleButton toggleButton2 = new ToggleButton(this);
        this.wlderxztoo = toggleButton2;
        toggleButton2.setLayoutParams(new LinearLayout.LayoutParams(1161, 68));
        this.wlderxztoo.setPadding(142, 84, 17, 145);
        linearLayout.addView(this.wlderxztoo);
        this.wlderxztoo.setBackgroundColor(Color.parseColor("#4d59e8"));
        Button button2 = new Button(this);
        this.npjignvrsq = button2;
        button2.setLayoutParams(new LinearLayout.LayoutParams(1958, 1977));
        this.npjignvrsq.setPadding(79, 57, 123, 125);
        linearLayout.addView(this.npjignvrsq);
        this.npjignvrsq.setBackgroundColor(Color.parseColor("#f96d3a"));
        FrameLayout frameLayout3 = new FrameLayout(this);
        this.pquxdkaayw = frameLayout3;
        frameLayout3.setLayoutParams(new LinearLayout.LayoutParams(674, 1384));
        this.pquxdkaayw.setPadding(197, 14, 40, 120);
        linearLayout.addView(this.pquxdkaayw);
        this.pquxdkaayw.setBackgroundColor(Color.parseColor("#ce2543"));
        ViewFlipper viewFlipper9 = new ViewFlipper(this);
        this.eobcwdpjdy = viewFlipper9;
        viewFlipper9.setLayoutParams(new LinearLayout.LayoutParams(159, 382));
        this.eobcwdpjdy.setPadding(199, 46, 52, 19);
        linearLayout.addView(this.eobcwdpjdy);
        this.eobcwdpjdy.setBackgroundColor(Color.parseColor("#54eda7"));
        SeekBar seekBar3 = new SeekBar(this);
        this.dckdrndxrs = seekBar3;
        seekBar3.setLayoutParams(new LinearLayout.LayoutParams(1438, 384));
        this.dckdrndxrs.setPadding(18, 156, 116, 169);
        linearLayout.addView(this.dckdrndxrs);
        this.dckdrndxrs.setBackgroundColor(Color.parseColor("#af8281"));
        Switch r24 = new Switch(this);
        this.hrljjihnyo = r24;
        r24.setLayoutParams(new LinearLayout.LayoutParams(1887, BluetoothSpp.STATE_DISCONNECTING));
        this.hrljjihnyo.setPadding(171, 159, 116, 107);
        linearLayout.addView(this.hrljjihnyo);
        this.hrljjihnyo.setBackgroundColor(Color.parseColor("#b936d7"));
        FrameLayout frameLayout4 = new FrameLayout(this);
        this.jduovuwmmr = frameLayout4;
        frameLayout4.setLayoutParams(new LinearLayout.LayoutParams(1836, 1585));
        this.jduovuwmmr.setPadding(42, 150, BDLocation.TypeNetWorkLocation, 89);
        linearLayout.addView(this.jduovuwmmr);
        this.jduovuwmmr.setBackgroundColor(Color.parseColor("#146fc9"));
        TableLayout tableLayout3 = new TableLayout(this);
        this.qxllzpayvr = tableLayout3;
        tableLayout3.setLayoutParams(new LinearLayout.LayoutParams(138, 1250));
        this.qxllzpayvr.setPadding(156, 71, 112, 45);
        linearLayout.addView(this.qxllzpayvr);
        this.qxllzpayvr.setBackgroundColor(Color.parseColor("#551619"));
        CheckBox checkBox2 = new CheckBox(this);
        this.ucxwqgmzmc = checkBox2;
        checkBox2.setLayoutParams(new LinearLayout.LayoutParams(1589, 1487));
        this.ucxwqgmzmc.setPadding(189, 82, BDLocation.TypeServerDecryptError, 121);
        linearLayout.addView(this.ucxwqgmzmc);
        this.ucxwqgmzmc.setBackgroundColor(Color.parseColor("#87cc3a"));
        RadioButton radioButton4 = new RadioButton(this);
        this.ljbqzithqw = radioButton4;
        radioButton4.setLayoutParams(new LinearLayout.LayoutParams(1743, 138));
        this.ljbqzithqw.setPadding(87, 60, 29, 120);
        linearLayout.addView(this.ljbqzithqw);
        this.ljbqzithqw.setBackgroundColor(Color.parseColor("#33c6ed"));
        Spinner spinner3 = new Spinner(this);
        this.esscpaurdk = spinner3;
        spinner3.setLayoutParams(new LinearLayout.LayoutParams(1469, 592));
        this.esscpaurdk.setPadding(154, 54, 127, 194);
        linearLayout.addView(this.esscpaurdk);
        this.esscpaurdk.setBackgroundColor(Color.parseColor("#1e7fad"));
        RatingBar ratingBar = new RatingBar(this);
        this.dcqmhajunk = ratingBar;
        ratingBar.setLayoutParams(new LinearLayout.LayoutParams(1702, 1279));
        this.dcqmhajunk.setPadding(121, 163, 50, 112);
        linearLayout.addView(this.dcqmhajunk);
        this.dcqmhajunk.setBackgroundColor(Color.parseColor("#b39362"));
        ImageView imageView = new ImageView(this);
        this.knqkzhtgtt = imageView;
        imageView.setLayoutParams(new LinearLayout.LayoutParams(1504, 813));
        this.knqkzhtgtt.setPadding(158, 185, 111, 39);
        linearLayout.addView(this.knqkzhtgtt);
        this.knqkzhtgtt.setBackgroundColor(Color.parseColor("#ff7447"));
        ToggleButton toggleButton3 = new ToggleButton(this);
        this.srubqnapgd = toggleButton3;
        toggleButton3.setLayoutParams(new LinearLayout.LayoutParams(1105, 699));
        this.srubqnapgd.setPadding(42, 104, 16, 193);
        linearLayout.addView(this.srubqnapgd);
        this.srubqnapgd.setBackgroundColor(Color.parseColor("#bbaad7"));
        LinearLayout linearLayout3 = new LinearLayout(this);
        this.hxukdhjuoc = linearLayout3;
        linearLayout3.setLayoutParams(new LinearLayout.LayoutParams(1383, 352));
        this.hxukdhjuoc.setPadding(116, 31, 14, 190);
        linearLayout.addView(this.hxukdhjuoc);
        this.hxukdhjuoc.setBackgroundColor(Color.parseColor("#cd69e5"));
        GridView gridView3 = new GridView(this);
        this.ksivijzhes = gridView3;
        gridView3.setLayoutParams(new LinearLayout.LayoutParams(1165, 1274));
        this.ksivijzhes.setPadding(76, 180, 164, 122);
        linearLayout.addView(this.ksivijzhes);
        this.ksivijzhes.setBackgroundColor(Color.parseColor("#691575"));
        ToggleButton toggleButton4 = new ToggleButton(this);
        this.qwlujmaytf = toggleButton4;
        toggleButton4.setLayoutParams(new LinearLayout.LayoutParams(931, 1495));
        this.qwlujmaytf.setPadding(148, 66, 198, 111);
        linearLayout.addView(this.qwlujmaytf);
        this.qwlujmaytf.setBackgroundColor(Color.parseColor("#5bbc16"));
        TimePicker timePicker3 = new TimePicker(this);
        this.ivzuanexab = timePicker3;
        timePicker3.setLayoutParams(new LinearLayout.LayoutParams(384, 234));
        this.ivzuanexab.setPadding(180, 101, 170, 155);
        linearLayout.addView(this.ivzuanexab);
        this.ivzuanexab.setBackgroundColor(Color.parseColor("#6af25d"));
        RadioButton radioButton5 = new RadioButton(this);
        this.wdttskgcpn = radioButton5;
        radioButton5.setLayoutParams(new LinearLayout.LayoutParams(1711, 1361));
        this.wdttskgcpn.setPadding(127, 154, 81, 84);
        linearLayout.addView(this.wdttskgcpn);
        this.wdttskgcpn.setBackgroundColor(Color.parseColor("#e49c6f"));
        GridView gridView4 = new GridView(this);
        this.ubonejzzuz = gridView4;
        gridView4.setLayoutParams(new LinearLayout.LayoutParams(363, 858));
        this.ubonejzzuz.setPadding(94, 115, 130, 88);
        linearLayout.addView(this.ubonejzzuz);
        this.ubonejzzuz.setBackgroundColor(Color.parseColor("#efd38a"));
        Switch r25 = new Switch(this);
        this.deactyhvco = r25;
        r25.setLayoutParams(new LinearLayout.LayoutParams(1137, 285));
        this.deactyhvco.setPadding(128, 158, 52, 137);
        linearLayout.addView(this.deactyhvco);
        this.deactyhvco.setBackgroundColor(Color.parseColor("#f76c2e"));
        RadioButton radioButton6 = new RadioButton(this);
        this.cwgpkgbfdd = radioButton6;
        radioButton6.setLayoutParams(new LinearLayout.LayoutParams(1801, 1580));
        this.cwgpkgbfdd.setPadding(132, 77, 149, 36);
        linearLayout.addView(this.cwgpkgbfdd);
        this.cwgpkgbfdd.setBackgroundColor(Color.parseColor("#7249d1"));
        SeekBar seekBar4 = new SeekBar(this);
        this.vrjgudjasc = seekBar4;
        seekBar4.setLayoutParams(new LinearLayout.LayoutParams(824, WebSocketProtocol.PAYLOAD_SHORT));
        this.vrjgudjasc.setPadding(100, 9, 108, 98);
        linearLayout.addView(this.vrjgudjasc);
        this.vrjgudjasc.setBackgroundColor(Color.parseColor("#023f82"));
        Switch r26 = new Switch(this);
        this.jbxirpqgkm = r26;
        r26.setLayoutParams(new LinearLayout.LayoutParams(781, 1460));
        this.jbxirpqgkm.setPadding(70, 185, 96, 127);
        linearLayout.addView(this.jbxirpqgkm);
        this.jbxirpqgkm.setBackgroundColor(Color.parseColor("#20112b"));
        Switch r27 = new Switch(this);
        this.awyvndjxlt = r27;
        r27.setLayoutParams(new LinearLayout.LayoutParams(30, 1258));
        this.awyvndjxlt.setPadding(9, 151, 51, 96);
        linearLayout.addView(this.awyvndjxlt);
        this.awyvndjxlt.setBackgroundColor(Color.parseColor("#9899fb"));
        ListView listView2 = new ListView(this);
        this.txpqwxtfpa = listView2;
        listView2.setLayoutParams(new LinearLayout.LayoutParams(1862, 1318));
        this.txpqwxtfpa.setPadding(138, 26, 166, 122);
        linearLayout.addView(this.txpqwxtfpa);
        this.txpqwxtfpa.setBackgroundColor(Color.parseColor("#cec4de"));
        ToggleButton toggleButton5 = new ToggleButton(this);
        this.uwoadazzlv = toggleButton5;
        toggleButton5.setLayoutParams(new LinearLayout.LayoutParams(1045, 967));
        this.uwoadazzlv.setPadding(81, 62, 186, 37);
        linearLayout.addView(this.uwoadazzlv);
        this.uwoadazzlv.setBackgroundColor(Color.parseColor("#39f8f3"));
        ScrollView scrollView = new ScrollView(this);
        this.uatwqicada = scrollView;
        scrollView.setLayoutParams(new LinearLayout.LayoutParams(941, 620));
        this.uatwqicada.setPadding(100, 168, 32, 86);
        linearLayout.addView(this.uatwqicada);
        this.uatwqicada.setBackgroundColor(Color.parseColor("#48b36f"));
        ToggleButton toggleButton6 = new ToggleButton(this);
        this.pfcibwxwkv = toggleButton6;
        toggleButton6.setLayoutParams(new LinearLayout.LayoutParams(PointerIconCompat.TYPE_GRABBING, 1949));
        this.pfcibwxwkv.setPadding(47, 150, 6, 156);
        linearLayout.addView(this.pfcibwxwkv);
        this.pfcibwxwkv.setBackgroundColor(Color.parseColor("#dfe011"));
        DatePicker datePicker2 = new DatePicker(this);
        this.ayethjqbaj = datePicker2;
        datePicker2.setLayoutParams(new LinearLayout.LayoutParams(516, 558));
        this.ayethjqbaj.setPadding(29, PictureConfig.CHOOSE_REQUEST, 64, 10);
        linearLayout.addView(this.ayethjqbaj);
        this.ayethjqbaj.setBackgroundColor(Color.parseColor("#e3808e"));
        EditText editText2 = new EditText(this);
        this.ptzwdmjsxd = editText2;
        editText2.setLayoutParams(new LinearLayout.LayoutParams(1003, TypedValues.CycleType.TYPE_WAVE_OFFSET));
        this.ptzwdmjsxd.setPadding(127, 58, 94, 130);
        linearLayout.addView(this.ptzwdmjsxd);
        this.ptzwdmjsxd.setBackgroundColor(Color.parseColor("#b54af9"));
        ProgressBar progressBar3 = new ProgressBar(this);
        this.dgflesbjic = progressBar3;
        progressBar3.setLayoutParams(new LinearLayout.LayoutParams(1511, 1529));
        this.dgflesbjic.setPadding(199, 97, 56, 58);
        linearLayout.addView(this.dgflesbjic);
        this.dgflesbjic.setBackgroundColor(Color.parseColor("#ec6e39"));
        TextView textView4 = new TextView(this);
        this.zfjtlxrnqf = textView4;
        textView4.setLayoutParams(new LinearLayout.LayoutParams(Contract.CMD_SET_VERSION.V1_2, 803));
        this.zfjtlxrnqf.setPadding(64, 133, 35, 88);
        linearLayout.addView(this.zfjtlxrnqf);
        this.zfjtlxrnqf.setBackgroundColor(Color.parseColor("#0d01a8"));
        LinearLayout linearLayout4 = new LinearLayout(this);
        this.vgydxkrobc = linearLayout4;
        linearLayout4.setLayoutParams(new LinearLayout.LayoutParams(1165, 1882));
        this.vgydxkrobc.setPadding(53, 13, 174, 145);
        linearLayout.addView(this.vgydxkrobc);
        this.vgydxkrobc.setBackgroundColor(Color.parseColor("#9f5a1a"));
        RatingBar ratingBar2 = new RatingBar(this);
        this.lrrksgynuk = ratingBar2;
        ratingBar2.setLayoutParams(new LinearLayout.LayoutParams(412, 1294));
        this.lrrksgynuk.setPadding(124, 119, 165, 95);
        linearLayout.addView(this.lrrksgynuk);
        this.lrrksgynuk.setBackgroundColor(Color.parseColor("#047373"));
        TableLayout tableLayout4 = new TableLayout(this);
        this.urvkbgtqgw = tableLayout4;
        tableLayout4.setLayoutParams(new LinearLayout.LayoutParams(182, 1920));
        this.urvkbgtqgw.setPadding(30, 47, 129, 56);
        linearLayout.addView(this.urvkbgtqgw);
        this.urvkbgtqgw.setBackgroundColor(Color.parseColor("#fa5f79"));
        TableLayout tableLayout5 = new TableLayout(this);
        this.aqykpjoyxi = tableLayout5;
        tableLayout5.setLayoutParams(new LinearLayout.LayoutParams(1392, 1961));
        this.aqykpjoyxi.setPadding(117, 118, 179, 139);
        linearLayout.addView(this.aqykpjoyxi);
        this.aqykpjoyxi.setBackgroundColor(Color.parseColor("#c00627"));
        Spinner spinner4 = new Spinner(this);
        this.nfehznxiaz = spinner4;
        spinner4.setLayoutParams(new LinearLayout.LayoutParams(1245, 1438));
        this.nfehznxiaz.setPadding(137, 199, 51, 61);
        linearLayout.addView(this.nfehznxiaz);
        this.nfehznxiaz.setBackgroundColor(Color.parseColor("#f609f4"));
        GridView gridView5 = new GridView(this);
        this.olwdtazgym = gridView5;
        gridView5.setLayoutParams(new LinearLayout.LayoutParams(796, 872));
        this.olwdtazgym.setPadding(64, 37, 25, 169);
        linearLayout.addView(this.olwdtazgym);
        this.olwdtazgym.setBackgroundColor(Color.parseColor("#4adcb0"));
        LinearLayout linearLayout5 = new LinearLayout(this);
        this.fdezvpcmtk = linearLayout5;
        linearLayout5.setLayoutParams(new LinearLayout.LayoutParams(1190, 295));
        this.fdezvpcmtk.setPadding(105, 9, 120, 70);
        linearLayout.addView(this.fdezvpcmtk);
        this.fdezvpcmtk.setBackgroundColor(Color.parseColor("#89fab1"));
        FrameLayout frameLayout5 = new FrameLayout(this);
        this.vdckjmkjmp = frameLayout5;
        frameLayout5.setLayoutParams(new LinearLayout.LayoutParams(1387, 1982));
        this.vdckjmkjmp.setPadding(156, 9, 66, 74);
        linearLayout.addView(this.vdckjmkjmp);
        this.vdckjmkjmp.setBackgroundColor(Color.parseColor("#2452c5"));
        Switch r28 = new Switch(this);
        this.rtruapjvfv = r28;
        r28.setLayoutParams(new LinearLayout.LayoutParams(1744, 1521));
        this.rtruapjvfv.setPadding(57, 195, 196, 180);
        linearLayout.addView(this.rtruapjvfv);
        this.rtruapjvfv.setBackgroundColor(Color.parseColor("#9c84d2"));
        ViewFlipper viewFlipper10 = new ViewFlipper(this);
        this.vghkaghcht = viewFlipper10;
        viewFlipper10.setLayoutParams(new LinearLayout.LayoutParams(1039, 674));
        this.vghkaghcht.setPadding(178, 63, 63, 31);
        linearLayout.addView(this.vghkaghcht);
        this.vghkaghcht.setBackgroundColor(Color.parseColor("#267d00"));
        TableLayout tableLayout6 = new TableLayout(this);
        this.kbpffeukwb = tableLayout6;
        tableLayout6.setLayoutParams(new LinearLayout.LayoutParams(1827, 595));
        this.kbpffeukwb.setPadding(39, 91, 24, BDLocation.TypeNetWorkLocation);
        linearLayout.addView(this.kbpffeukwb);
        this.kbpffeukwb.setBackgroundColor(Color.parseColor("#0e628b"));
        RelativeLayout relativeLayout3 = new RelativeLayout(this);
        this.liqpjcgqnz = relativeLayout3;
        relativeLayout3.setLayoutParams(new LinearLayout.LayoutParams(1654, 1854));
        this.liqpjcgqnz.setPadding(94, 185, 29, 123);
        linearLayout.addView(this.liqpjcgqnz);
        this.liqpjcgqnz.setBackgroundColor(Color.parseColor("#37391a"));
        RadioButton radioButton7 = new RadioButton(this);
        this.okbrizelcf = radioButton7;
        radioButton7.setLayoutParams(new LinearLayout.LayoutParams(1649, 408));
        this.okbrizelcf.setPadding(116, 83, 180, 58);
        linearLayout.addView(this.okbrizelcf);
        this.okbrizelcf.setBackgroundColor(Color.parseColor("#afa05b"));
        Switch r29 = new Switch(this);
        this.wezzynkpzt = r29;
        r29.setLayoutParams(new LinearLayout.LayoutParams(56, 315));
        this.wezzynkpzt.setPadding(35, 191, 105, 20);
        linearLayout.addView(this.wezzynkpzt);
        this.wezzynkpzt.setBackgroundColor(Color.parseColor("#eaa35f"));
        ListView listView3 = new ListView(this);
        this.zilnybltls = listView3;
        listView3.setLayoutParams(new LinearLayout.LayoutParams(1575, 186));
        this.zilnybltls.setPadding(56, 69, 36, 79);
        linearLayout.addView(this.zilnybltls);
        this.zilnybltls.setBackgroundColor(Color.parseColor("#52d8a6"));
        CheckBox checkBox3 = new CheckBox(this);
        this.bdkxkcqjtp = checkBox3;
        checkBox3.setLayoutParams(new LinearLayout.LayoutParams(1845, TypedValues.PositionType.TYPE_PERCENT_WIDTH));
        this.bdkxkcqjtp.setPadding(41, 86, 157, 51);
        linearLayout.addView(this.bdkxkcqjtp);
        this.bdkxkcqjtp.setBackgroundColor(Color.parseColor("#8fd936"));
        LinearLayout linearLayout6 = new LinearLayout(this);
        this.atofqlnugn = linearLayout6;
        linearLayout6.setLayoutParams(new LinearLayout.LayoutParams(1276, 280));
        this.atofqlnugn.setPadding(97, 152, 30, 127);
        linearLayout.addView(this.atofqlnugn);
        this.atofqlnugn.setBackgroundColor(Color.parseColor("#783401"));
        RelativeLayout relativeLayout4 = new RelativeLayout(this);
        this.zgxmydhdih = relativeLayout4;
        relativeLayout4.setLayoutParams(new LinearLayout.LayoutParams(938, 1791));
        this.zgxmydhdih.setPadding(81, 164, 59, 16);
        linearLayout.addView(this.zgxmydhdih);
        this.zgxmydhdih.setBackgroundColor(Color.parseColor("#6157b0"));
        Switch r210 = new Switch(this);
        this.mcfueaizmy = r210;
        r210.setLayoutParams(new LinearLayout.LayoutParams(1567, 97));
        this.mcfueaizmy.setPadding(92, 18, 96, 189);
        linearLayout.addView(this.mcfueaizmy);
        this.mcfueaizmy.setBackgroundColor(Color.parseColor("#9e409c"));
        ImageView imageView2 = new ImageView(this);
        this.mtyjstvfez = imageView2;
        imageView2.setLayoutParams(new LinearLayout.LayoutParams(411, 1078));
        this.mtyjstvfez.setPadding(102, 114, 152, 199);
        linearLayout.addView(this.mtyjstvfez);
        this.mtyjstvfez.setBackgroundColor(Color.parseColor("#830e15"));
        RelativeLayout relativeLayout5 = new RelativeLayout(this);
        this.wppymmjqqg = relativeLayout5;
        relativeLayout5.setLayoutParams(new LinearLayout.LayoutParams(668, 775));
        this.wppymmjqqg.setPadding(65, 60, 158, 78);
        linearLayout.addView(this.wppymmjqqg);
        this.wppymmjqqg.setBackgroundColor(Color.parseColor("#91efba"));
        ImageView imageView3 = new ImageView(this);
        this.bgryxoxphj = imageView3;
        imageView3.setLayoutParams(new LinearLayout.LayoutParams(921, 1981));
        this.bgryxoxphj.setPadding(13, BDLocation.TypeServerDecryptError, 154, WebSocketProtocol.PAYLOAD_SHORT);
        linearLayout.addView(this.bgryxoxphj);
        this.bgryxoxphj.setBackgroundColor(Color.parseColor("#eadcaa"));
        ImageView imageView4 = new ImageView(this);
        this.xzmfqkfkic = imageView4;
        imageView4.setLayoutParams(new LinearLayout.LayoutParams(1126, 189));
        this.xzmfqkfkic.setPadding(10, 185, 64, 129);
        linearLayout.addView(this.xzmfqkfkic);
        this.xzmfqkfkic.setBackgroundColor(Color.parseColor("#664ccf"));
        LinearLayout linearLayout7 = new LinearLayout(this);
        this.iiwdmbbdqk = linearLayout7;
        linearLayout7.setLayoutParams(new LinearLayout.LayoutParams(1309, 761));
        this.iiwdmbbdqk.setPadding(12, 192, 80, 70);
        linearLayout.addView(this.iiwdmbbdqk);
        this.iiwdmbbdqk.setBackgroundColor(Color.parseColor("#b8eb15"));
        TextView textView5 = new TextView(this);
        this.bjpivltweb = textView5;
        textView5.setLayoutParams(new LinearLayout.LayoutParams(1068, 202));
        this.bjpivltweb.setPadding(83, 168, 183, 166);
        linearLayout.addView(this.bjpivltweb);
        this.bjpivltweb.setBackgroundColor(Color.parseColor("#0b0998"));
        Switch r211 = new Switch(this);
        this.atzhpetzyh = r211;
        r211.setLayoutParams(new LinearLayout.LayoutParams(1113, 722));
        this.atzhpetzyh.setPadding(189, 82, 119, 166);
        linearLayout.addView(this.atzhpetzyh);
        this.atzhpetzyh.setBackgroundColor(Color.parseColor("#1e7618"));
        SeekBar seekBar5 = new SeekBar(this);
        this.vswrpooqqw = seekBar5;
        seekBar5.setLayoutParams(new LinearLayout.LayoutParams(551, 1333));
        this.vswrpooqqw.setPadding(66, 174, 63, 184);
        linearLayout.addView(this.vswrpooqqw);
        this.vswrpooqqw.setBackgroundColor(Color.parseColor("#bef671"));
        RatingBar ratingBar3 = new RatingBar(this);
        this.veonghyvpm = ratingBar3;
        ratingBar3.setLayoutParams(new LinearLayout.LayoutParams(1036, 1902));
        this.veonghyvpm.setPadding(42, 48, 65, 52);
        linearLayout.addView(this.veonghyvpm);
        this.veonghyvpm.setBackgroundColor(Color.parseColor("#823507"));
        FrameLayout frameLayout6 = new FrameLayout(this);
        this.jjdiylryrp = frameLayout6;
        frameLayout6.setLayoutParams(new LinearLayout.LayoutParams(873, 295));
        this.jjdiylryrp.setPadding(134, 61, 4, 163);
        linearLayout.addView(this.jjdiylryrp);
        this.jjdiylryrp.setBackgroundColor(Color.parseColor("#bae8c4"));
        SeekBar seekBar6 = new SeekBar(this);
        this.zrbdkizdyq = seekBar6;
        seekBar6.setLayoutParams(new LinearLayout.LayoutParams(1453, 314));
        this.zrbdkizdyq.setPadding(177, 44, 183, 100);
        linearLayout.addView(this.zrbdkizdyq);
        this.zrbdkizdyq.setBackgroundColor(Color.parseColor("#29ddbb"));
        TextView textView6 = new TextView(this);
        this.fveqvzvqvf = textView6;
        textView6.setLayoutParams(new LinearLayout.LayoutParams(1551, 1773));
        this.fveqvzvqvf.setPadding(178, 153, 41, 88);
        linearLayout.addView(this.fveqvzvqvf);
        this.fveqvzvqvf.setBackgroundColor(Color.parseColor("#37a940"));
        EditText editText3 = new EditText(this);
        this.tvtgslptye = editText3;
        editText3.setLayoutParams(new LinearLayout.LayoutParams(1901, 818));
        this.tvtgslptye.setPadding(72, 107, 127, 39);
        linearLayout.addView(this.tvtgslptye);
        this.tvtgslptye.setBackgroundColor(Color.parseColor("#40c192"));
        SeekBar seekBar7 = new SeekBar(this);
        this.vudxoecdiw = seekBar7;
        seekBar7.setLayoutParams(new LinearLayout.LayoutParams(1086, 1156));
        this.vudxoecdiw.setPadding(154, 118, 187, 53);
        linearLayout.addView(this.vudxoecdiw);
        this.vudxoecdiw.setBackgroundColor(Color.parseColor("#26f923"));
        RatingBar ratingBar4 = new RatingBar(this);
        this.bbhvbczbxp = ratingBar4;
        ratingBar4.setLayoutParams(new LinearLayout.LayoutParams(1032, 1093));
        this.bbhvbczbxp.setPadding(193, 11, 157, 166);
        linearLayout.addView(this.bbhvbczbxp);
        this.bbhvbczbxp.setBackgroundColor(Color.parseColor("#0b91e7"));
        ScrollView scrollView2 = new ScrollView(this);
        this.sqtqjukjwd = scrollView2;
        scrollView2.setLayoutParams(new LinearLayout.LayoutParams(327, 1611));
        this.sqtqjukjwd.setPadding(43, 28, 113, 86);
        linearLayout.addView(this.sqtqjukjwd);
        this.sqtqjukjwd.setBackgroundColor(Color.parseColor("#b43773"));
        TextView textView7 = new TextView(this);
        this.bfuzddzukt = textView7;
        textView7.setLayoutParams(new LinearLayout.LayoutParams(468, 243));
        this.bfuzddzukt.setPadding(189, 116, 12, 13);
        linearLayout.addView(this.bfuzddzukt);
        this.bfuzddzukt.setBackgroundColor(Color.parseColor("#742080"));
        DatePicker datePicker3 = new DatePicker(this);
        this.cwchzsiild = datePicker3;
        datePicker3.setLayoutParams(new LinearLayout.LayoutParams(1861, 1861));
        this.cwchzsiild.setPadding(45, PictureConfig.CHOOSE_REQUEST, 92, 175);
        linearLayout.addView(this.cwchzsiild);
        this.cwchzsiild.setBackgroundColor(Color.parseColor("#d8687e"));
        SeekBar seekBar8 = new SeekBar(this);
        this.atpslfranj = seekBar8;
        seekBar8.setLayoutParams(new LinearLayout.LayoutParams(447, 1167));
        this.atpslfranj.setPadding(180, 73, 148, 114);
        linearLayout.addView(this.atpslfranj);
        this.atpslfranj.setBackgroundColor(Color.parseColor("#51287b"));
        ImageView imageView5 = new ImageView(this);
        this.rabhalopxb = imageView5;
        imageView5.setLayoutParams(new LinearLayout.LayoutParams(1693, 869));
        this.rabhalopxb.setPadding(44, 64, 194, 48);
        linearLayout.addView(this.rabhalopxb);
        this.rabhalopxb.setBackgroundColor(Color.parseColor("#6b4227"));
        Spinner spinner5 = new Spinner(this);
        this.cezenatfub = spinner5;
        spinner5.setLayoutParams(new LinearLayout.LayoutParams(1731, 749));
        this.cezenatfub.setPadding(18, 100, 101, 99);
        linearLayout.addView(this.cezenatfub);
        this.cezenatfub.setBackgroundColor(Color.parseColor("#9be760"));
        LinearLayout linearLayout8 = new LinearLayout(this);
        this.ifdtkeeavy = linearLayout8;
        linearLayout8.setLayoutParams(new LinearLayout.LayoutParams(1084, 1457));
        this.ifdtkeeavy.setPadding(89, 23, 174, 144);
        linearLayout.addView(this.ifdtkeeavy);
        this.ifdtkeeavy.setBackgroundColor(Color.parseColor("#0e431e"));
        ImageView imageView6 = new ImageView(this);
        this.uwfofjwilh = imageView6;
        imageView6.setLayoutParams(new LinearLayout.LayoutParams(516, 101));
        this.uwfofjwilh.setPadding(73, 117, 41, 108);
        linearLayout.addView(this.uwfofjwilh);
        this.uwfofjwilh.setBackgroundColor(Color.parseColor("#597d4e"));
        Switch r212 = new Switch(this);
        this.dazpcefopd = r212;
        r212.setLayoutParams(new LinearLayout.LayoutParams(1291, 1456));
        this.dazpcefopd.setPadding(44, 152, 168, 19);
        linearLayout.addView(this.dazpcefopd);
        this.dazpcefopd.setBackgroundColor(Color.parseColor("#b25214"));
        LinearLayout linearLayout9 = new LinearLayout(this);
        this.nggalaheej = linearLayout9;
        linearLayout9.setLayoutParams(new LinearLayout.LayoutParams(143, 143));
        this.nggalaheej.setPadding(140, 196, 189, 87);
        linearLayout.addView(this.nggalaheej);
        this.nggalaheej.setBackgroundColor(Color.parseColor("#fcf630"));
        Spinner spinner6 = new Spinner(this);
        this.jzfnxbuszc = spinner6;
        spinner6.setLayoutParams(new LinearLayout.LayoutParams(1692, 1725));
        this.jzfnxbuszc.setPadding(92, 43, 50, 157);
        linearLayout.addView(this.jzfnxbuszc);
        this.jzfnxbuszc.setBackgroundColor(Color.parseColor("#71c83e"));
        ToggleButton toggleButton7 = new ToggleButton(this);
        this.xlinidmysa = toggleButton7;
        toggleButton7.setLayoutParams(new LinearLayout.LayoutParams(1627, 950));
        this.xlinidmysa.setPadding(129, 11, 103, 107);
        linearLayout.addView(this.xlinidmysa);
        this.xlinidmysa.setBackgroundColor(Color.parseColor("#7430a3"));
        RelativeLayout relativeLayout6 = new RelativeLayout(this);
        this.csxthuqxfg = relativeLayout6;
        relativeLayout6.setLayoutParams(new LinearLayout.LayoutParams(364, 1538));
        this.csxthuqxfg.setPadding(123, 99, 31, 133);
        linearLayout.addView(this.csxthuqxfg);
        this.csxthuqxfg.setBackgroundColor(Color.parseColor("#2ba550"));
        GridView gridView6 = new GridView(this);
        this.onhecioids = gridView6;
        gridView6.setLayoutParams(new LinearLayout.LayoutParams(810, 1382));
        this.onhecioids.setPadding(181, 134, 95, 174);
        linearLayout.addView(this.onhecioids);
        this.onhecioids.setBackgroundColor(Color.parseColor("#ec481d"));
        Button button3 = new Button(this);
        this.pdrcgwwyst = button3;
        button3.setLayoutParams(new LinearLayout.LayoutParams(882, 1470));
        this.pdrcgwwyst.setPadding(45, 23, 4, 115);
        linearLayout.addView(this.pdrcgwwyst);
        this.pdrcgwwyst.setBackgroundColor(Color.parseColor("#93bfb9"));
        LinearLayout linearLayout10 = new LinearLayout(this);
        this.whkqpfuzho = linearLayout10;
        linearLayout10.setLayoutParams(new LinearLayout.LayoutParams(1015, 1390));
        this.whkqpfuzho.setPadding(114, 27, 16, 131);
        linearLayout.addView(this.whkqpfuzho);
        this.whkqpfuzho.setBackgroundColor(Color.parseColor("#284e95"));
        ImageView imageView7 = new ImageView(this);
        this.fybpwqlqox = imageView7;
        imageView7.setLayoutParams(new LinearLayout.LayoutParams(1614, 1360));
        this.fybpwqlqox.setPadding(33, 93, 25, 115);
        linearLayout.addView(this.fybpwqlqox);
        this.fybpwqlqox.setBackgroundColor(Color.parseColor("#475217"));
        DatePicker datePicker4 = new DatePicker(this);
        this.mpnkpgcijd = datePicker4;
        datePicker4.setLayoutParams(new LinearLayout.LayoutParams(1801, 192));
        this.mpnkpgcijd.setPadding(114, 19, 7, 94);
        linearLayout.addView(this.mpnkpgcijd);
        this.mpnkpgcijd.setBackgroundColor(Color.parseColor("#64e47f"));
        DatePicker datePicker5 = new DatePicker(this);
        this.qdqvwxwxbg = datePicker5;
        datePicker5.setLayoutParams(new LinearLayout.LayoutParams(1593, 10));
        this.qdqvwxwxbg.setPadding(181, BDLocation.TypeServerError, 8, 88);
        linearLayout.addView(this.qdqvwxwxbg);
        this.qdqvwxwxbg.setBackgroundColor(Color.parseColor("#db90ad"));
        ScrollView scrollView3 = new ScrollView(this);
        this.yvpfcvfojx = scrollView3;
        scrollView3.setLayoutParams(new LinearLayout.LayoutParams(1741, ConnectionResult.DRIVE_EXTERNAL_STORAGE_REQUIRED));
        this.yvpfcvfojx.setPadding(84, 192, 17, 67);
        linearLayout.addView(this.yvpfcvfojx);
        this.yvpfcvfojx.setBackgroundColor(Color.parseColor("#4a216a"));
        ViewFlipper viewFlipper11 = new ViewFlipper(this);
        this.bnimwwcugz = viewFlipper11;
        viewFlipper11.setLayoutParams(new LinearLayout.LayoutParams(874, 1935));
        this.bnimwwcugz.setPadding(PictureConfig.CHOOSE_REQUEST, 182, 132, 99);
        linearLayout.addView(this.bnimwwcugz);
        this.bnimwwcugz.setBackgroundColor(Color.parseColor("#dcec17"));
        TextView textView8 = new TextView(this);
        this.hchiucxtwb = textView8;
        textView8.setLayoutParams(new LinearLayout.LayoutParams(238, 1705));
        this.hchiucxtwb.setPadding(77, 117, 96, 67);
        linearLayout.addView(this.hchiucxtwb);
        this.hchiucxtwb.setBackgroundColor(Color.parseColor("#c0de14"));
        ToggleButton toggleButton8 = new ToggleButton(this);
        this.qdhzptnmyr = toggleButton8;
        toggleButton8.setLayoutParams(new LinearLayout.LayoutParams(765, 118));
        this.qdhzptnmyr.setPadding(163, 138, 1, 138);
        linearLayout.addView(this.qdhzptnmyr);
        this.qdhzptnmyr.setBackgroundColor(Color.parseColor("#953d95"));
        TextView textView9 = new TextView(this);
        this.tpnweeywzz = textView9;
        textView9.setLayoutParams(new LinearLayout.LayoutParams(943, 1805));
        this.tpnweeywzz.setPadding(159, 34, 110, 104);
        linearLayout.addView(this.tpnweeywzz);
        this.tpnweeywzz.setBackgroundColor(Color.parseColor("#fa02cd"));
        ListView listView4 = new ListView(this);
        this.jddisnccpl = listView4;
        listView4.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.PositionType.TYPE_CURVE_FIT, 1222));
        this.jddisnccpl.setPadding(94, 193, 57, 122);
        linearLayout.addView(this.jddisnccpl);
        this.jddisnccpl.setBackgroundColor(Color.parseColor("#aa05f7"));
        Switch r213 = new Switch(this);
        this.mscqxwaeie = r213;
        r213.setLayoutParams(new LinearLayout.LayoutParams(1534, 1936));
        this.mscqxwaeie.setPadding(20, 166, 55, 93);
        linearLayout.addView(this.mscqxwaeie);
        this.mscqxwaeie.setBackgroundColor(Color.parseColor("#0a22cb"));
        RatingBar ratingBar5 = new RatingBar(this);
        this.thjsqttqaj = ratingBar5;
        ratingBar5.setLayoutParams(new LinearLayout.LayoutParams(1657, 776));
        this.thjsqttqaj.setPadding(125, 179, 76, 22);
        linearLayout.addView(this.thjsqttqaj);
        this.thjsqttqaj.setBackgroundColor(Color.parseColor("#e966f5"));
        RelativeLayout relativeLayout7 = new RelativeLayout(this);
        this.ubnpzgvumm = relativeLayout7;
        relativeLayout7.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.MotionType.TYPE_POLAR_RELATIVETO, 1902));
        this.ubnpzgvumm.setPadding(114, 139, 33, 103);
        linearLayout.addView(this.ubnpzgvumm);
        this.ubnpzgvumm.setBackgroundColor(Color.parseColor("#01c953"));
        ProgressBar progressBar4 = new ProgressBar(this);
        this.qnuaohbmel = progressBar4;
        progressBar4.setLayoutParams(new LinearLayout.LayoutParams(849, 1721));
        this.qnuaohbmel.setPadding(100, 189, 53, 70);
        linearLayout.addView(this.qnuaohbmel);
        this.qnuaohbmel.setBackgroundColor(Color.parseColor("#b0a246"));
        GridView gridView7 = new GridView(this);
        this.hvclnnbyxl = gridView7;
        gridView7.setLayoutParams(new LinearLayout.LayoutParams(955, 1362));
        this.hvclnnbyxl.setPadding(111, 110, WebSocketProtocol.PAYLOAD_SHORT, 183);
        linearLayout.addView(this.hvclnnbyxl);
        this.hvclnnbyxl.setBackgroundColor(Color.parseColor("#f4b645"));
        ProgressBar progressBar5 = new ProgressBar(this);
        this.ahdkybtoum = progressBar5;
        progressBar5.setLayoutParams(new LinearLayout.LayoutParams(GattClient.STATE_DISCOVERY_SERVICE, 1206));
        this.ahdkybtoum.setPadding(157, 76, 138, 73);
        linearLayout.addView(this.ahdkybtoum);
        this.ahdkybtoum.setBackgroundColor(Color.parseColor("#aa9ae3"));
        GridView gridView8 = new GridView(this);
        this.biyozoferz = gridView8;
        gridView8.setLayoutParams(new LinearLayout.LayoutParams(1223, 764));
        this.biyozoferz.setPadding(84, 61, 158, WebSocketProtocol.PAYLOAD_SHORT);
        linearLayout.addView(this.biyozoferz);
        this.biyozoferz.setBackgroundColor(Color.parseColor("#17ab6e"));
        TimePicker timePicker4 = new TimePicker(this);
        this.kebamvwgti = timePicker4;
        timePicker4.setLayoutParams(new LinearLayout.LayoutParams(211, 1262));
        this.kebamvwgti.setPadding(174, 78, 3, 52);
        linearLayout.addView(this.kebamvwgti);
        this.kebamvwgti.setBackgroundColor(Color.parseColor("#c1175d"));
        DatePicker datePicker6 = new DatePicker(this);
        this.shkxwojkhn = datePicker6;
        datePicker6.setLayoutParams(new LinearLayout.LayoutParams(1546, 1533));
        this.shkxwojkhn.setPadding(5, 183, 96, 16);
        linearLayout.addView(this.shkxwojkhn);
        this.shkxwojkhn.setBackgroundColor(Color.parseColor("#08567b"));
        SeekBar seekBar9 = new SeekBar(this);
        this.wndoorifbj = seekBar9;
        seekBar9.setLayoutParams(new LinearLayout.LayoutParams(1096, 1780));
        this.wndoorifbj.setPadding(168, 189, 168, 146);
        linearLayout.addView(this.wndoorifbj);
        this.wndoorifbj.setBackgroundColor(Color.parseColor("#6d60de"));
        GridView gridView9 = new GridView(this);
        this.dayclyvsmr = gridView9;
        gridView9.setLayoutParams(new LinearLayout.LayoutParams(372, 22));
        this.dayclyvsmr.setPadding(70, 88, 1, 163);
        linearLayout.addView(this.dayclyvsmr);
        this.dayclyvsmr.setBackgroundColor(Color.parseColor("#cf1a11"));
        LinearLayout linearLayout11 = new LinearLayout(this);
        this.cynoagjdgo = linearLayout11;
        linearLayout11.setLayoutParams(new LinearLayout.LayoutParams(1758, 1771));
        this.cynoagjdgo.setPadding(101, 4, 102, 58);
        linearLayout.addView(this.cynoagjdgo);
        this.cynoagjdgo.setBackgroundColor(Color.parseColor("#28bf71"));
        EditText editText4 = new EditText(this);
        this.ihohxgcfwt = editText4;
        editText4.setLayoutParams(new LinearLayout.LayoutParams(814, 525));
        this.ihohxgcfwt.setPadding(86, 76, 122, 85);
        linearLayout.addView(this.ihohxgcfwt);
        this.ihohxgcfwt.setBackgroundColor(Color.parseColor("#fddabf"));
        TableLayout tableLayout7 = new TableLayout(this);
        this.asdlyplbqs = tableLayout7;
        tableLayout7.setLayoutParams(new LinearLayout.LayoutParams(1650, 1465));
        this.asdlyplbqs.setPadding(0, 40, 90, 76);
        linearLayout.addView(this.asdlyplbqs);
        this.asdlyplbqs.setBackgroundColor(Color.parseColor("#4f166c"));
        ProgressBar progressBar6 = new ProgressBar(this);
        this.rkevhygmvy = progressBar6;
        progressBar6.setLayoutParams(new LinearLayout.LayoutParams(1835, 921));
        this.rkevhygmvy.setPadding(46, 64, 70, 10);
        linearLayout.addView(this.rkevhygmvy);
        this.rkevhygmvy.setBackgroundColor(Color.parseColor("#af7a6b"));
        ImageView imageView8 = new ImageView(this);
        this.gmdmouhjfo = imageView8;
        imageView8.setLayoutParams(new LinearLayout.LayoutParams(1581, 677));
        this.gmdmouhjfo.setPadding(159, 81, 123, 53);
        linearLayout.addView(this.gmdmouhjfo);
        this.gmdmouhjfo.setBackgroundColor(Color.parseColor("#c0075d"));
        RadioButton radioButton8 = new RadioButton(this);
        this.axucfggbvl = radioButton8;
        radioButton8.setLayoutParams(new LinearLayout.LayoutParams(266, 1505));
        this.axucfggbvl.setPadding(169, 132, 79, 28);
        linearLayout.addView(this.axucfggbvl);
        this.axucfggbvl.setBackgroundColor(Color.parseColor("#9e3516"));
        FrameLayout frameLayout7 = new FrameLayout(this);
        this.fiiwvcdvlw = frameLayout7;
        frameLayout7.setLayoutParams(new LinearLayout.LayoutParams(1841, 250));
        this.fiiwvcdvlw.setPadding(107, 55, 90, 15);
        linearLayout.addView(this.fiiwvcdvlw);
        this.fiiwvcdvlw.setBackgroundColor(Color.parseColor("#32a537"));
        FrameLayout frameLayout8 = new FrameLayout(this);
        this.awjsybfuvr = frameLayout8;
        frameLayout8.setLayoutParams(new LinearLayout.LayoutParams(336, 1009));
        this.awjsybfuvr.setPadding(125, 52, 110, 34);
        linearLayout.addView(this.awjsybfuvr);
        this.awjsybfuvr.setBackgroundColor(Color.parseColor("#60974a"));
        Switch r214 = new Switch(this);
        this.gbjhkjyxvo = r214;
        r214.setLayoutParams(new LinearLayout.LayoutParams(1484, 626));
        this.gbjhkjyxvo.setPadding(172, 38, 60, 35);
        linearLayout.addView(this.gbjhkjyxvo);
        this.gbjhkjyxvo.setBackgroundColor(Color.parseColor("#6b1c3f"));
        ViewFlipper viewFlipper12 = new ViewFlipper(this);
        this.izccrobrtb = viewFlipper12;
        viewFlipper12.setLayoutParams(new LinearLayout.LayoutParams(1217, 1094));
        this.izccrobrtb.setPadding(127, 75, 195, 138);
        linearLayout.addView(this.izccrobrtb);
        this.izccrobrtb.setBackgroundColor(Color.parseColor("#717d8d"));
        TextView textView10 = new TextView(this);
        this.nnulhpbrnd = textView10;
        textView10.setLayoutParams(new LinearLayout.LayoutParams(451, 1948));
        this.nnulhpbrnd.setPadding(104, 35, 77, 192);
        linearLayout.addView(this.nnulhpbrnd);
        this.nnulhpbrnd.setBackgroundColor(Color.parseColor("#71651b"));
        TimePicker timePicker5 = new TimePicker(this);
        this.lsptohmghy = timePicker5;
        timePicker5.setLayoutParams(new LinearLayout.LayoutParams(1639, 974));
        this.lsptohmghy.setPadding(64, 63, 111, 79);
        linearLayout.addView(this.lsptohmghy);
        this.lsptohmghy.setBackgroundColor(Color.parseColor("#43fe16"));
        SeekBar seekBar10 = new SeekBar(this);
        this.druohdpjsh = seekBar10;
        seekBar10.setLayoutParams(new LinearLayout.LayoutParams(791, 823));
        this.druohdpjsh.setPadding(20, 197, 141, 185);
        linearLayout.addView(this.druohdpjsh);
        this.druohdpjsh.setBackgroundColor(Color.parseColor("#b6765b"));
        LinearLayout linearLayout12 = new LinearLayout(this);
        this.naghkzivcj = linearLayout12;
        linearLayout12.setLayoutParams(new LinearLayout.LayoutParams(1816, 1162));
        this.naghkzivcj.setPadding(197, 57, 88, 149);
        linearLayout.addView(this.naghkzivcj);
        this.naghkzivcj.setBackgroundColor(Color.parseColor("#7a2339"));
        GridView gridView10 = new GridView(this);
        this.oxyqhhtcpk = gridView10;
        gridView10.setLayoutParams(new LinearLayout.LayoutParams(1409, 5));
        this.oxyqhhtcpk.setPadding(151, 6, 77, 195);
        linearLayout.addView(this.oxyqhhtcpk);
        this.oxyqhhtcpk.setBackgroundColor(Color.parseColor("#caa1f2"));
        ScrollView scrollView4 = new ScrollView(this);
        this.afbtsjbohi = scrollView4;
        scrollView4.setLayoutParams(new LinearLayout.LayoutParams(323, 908));
        this.afbtsjbohi.setPadding(114, 130, 20, 128);
        linearLayout.addView(this.afbtsjbohi);
        this.afbtsjbohi.setBackgroundColor(Color.parseColor("#dabadb"));
        ScrollView scrollView5 = new ScrollView(this);
        this.cuzpmhvwsg = scrollView5;
        scrollView5.setLayoutParams(new LinearLayout.LayoutParams(1784, 538));
        this.cuzpmhvwsg.setPadding(53, 184, 129, 93);
        linearLayout.addView(this.cuzpmhvwsg);
        this.cuzpmhvwsg.setBackgroundColor(Color.parseColor("#f6a73d"));
        EditText editText5 = new EditText(this);
        this.wzroyvmfon = editText5;
        editText5.setLayoutParams(new LinearLayout.LayoutParams(1378, 1977));
        this.wzroyvmfon.setPadding(109, 47, 171, 26);
        linearLayout.addView(this.wzroyvmfon);
        this.wzroyvmfon.setBackgroundColor(Color.parseColor("#f6754f"));
        ScrollView scrollView6 = new ScrollView(this);
        this.fpeplscvfr = scrollView6;
        scrollView6.setLayoutParams(new LinearLayout.LayoutParams(1577, 554));
        this.fpeplscvfr.setPadding(17, 9, 127, 79);
        linearLayout.addView(this.fpeplscvfr);
        this.fpeplscvfr.setBackgroundColor(Color.parseColor("#34085b"));
        TextView textView11 = new TextView(this);
        this.hoyrovhdur = textView11;
        textView11.setLayoutParams(new LinearLayout.LayoutParams(1656, 1880));
        this.hoyrovhdur.setPadding(71, 15, 72, 18);
        linearLayout.addView(this.hoyrovhdur);
        this.hoyrovhdur.setBackgroundColor(Color.parseColor("#0ef16e"));
        CheckBox checkBox4 = new CheckBox(this);
        this.rphdmjwyrh = checkBox4;
        checkBox4.setLayoutParams(new LinearLayout.LayoutParams(444, 975));
        this.rphdmjwyrh.setPadding(120, 40, 37, 20);
        linearLayout.addView(this.rphdmjwyrh);
        this.rphdmjwyrh.setBackgroundColor(Color.parseColor("#b02736"));
        ImageView imageView9 = new ImageView(this);
        this.sgowmyjksa = imageView9;
        imageView9.setLayoutParams(new LinearLayout.LayoutParams(194, TypedValues.CycleType.TYPE_VISIBILITY));
        this.sgowmyjksa.setPadding(4, 16, 175, 62);
        linearLayout.addView(this.sgowmyjksa);
        this.sgowmyjksa.setBackgroundColor(Color.parseColor("#b27c9a"));
        ProgressBar progressBar7 = new ProgressBar(this);
        this.cvoxkmfyyb = progressBar7;
        progressBar7.setLayoutParams(new LinearLayout.LayoutParams(1812, 1074));
        this.cvoxkmfyyb.setPadding(75, 134, 21, 185);
        linearLayout.addView(this.cvoxkmfyyb);
        this.cvoxkmfyyb.setBackgroundColor(Color.parseColor("#75704e"));
        RadioButton radioButton9 = new RadioButton(this);
        this.ksqxyielfo = radioButton9;
        radioButton9.setLayoutParams(new LinearLayout.LayoutParams(552, 1713));
        this.ksqxyielfo.setPadding(57, 54, 6, 178);
        linearLayout.addView(this.ksqxyielfo);
        this.ksqxyielfo.setBackgroundColor(Color.parseColor("#5dba81"));
        FrameLayout frameLayout9 = new FrameLayout(this);
        this.qcmkcnjnna = frameLayout9;
        frameLayout9.setLayoutParams(new LinearLayout.LayoutParams(798, 718));
        this.qcmkcnjnna.setPadding(4, 150, 91, 132);
        linearLayout.addView(this.qcmkcnjnna);
        this.qcmkcnjnna.setBackgroundColor(Color.parseColor("#60b55f"));
        Button button4 = new Button(this);
        this.zsxlsnboii = button4;
        button4.setLayoutParams(new LinearLayout.LayoutParams(1788, BDLocation.TypeServerDecryptError));
        this.zsxlsnboii.setPadding(36, 61, BDLocation.TypeServerError, 111);
        linearLayout.addView(this.zsxlsnboii);
        this.zsxlsnboii.setBackgroundColor(Color.parseColor("#d6d936"));
        FrameLayout frameLayout10 = new FrameLayout(this);
        this.vnznweojia = frameLayout10;
        frameLayout10.setLayoutParams(new LinearLayout.LayoutParams(1983, 960));
        this.vnznweojia.setPadding(71, 118, 140, 198);
        linearLayout.addView(this.vnznweojia);
        this.vnznweojia.setBackgroundColor(Color.parseColor("#8fdc10"));
        RelativeLayout relativeLayout8 = new RelativeLayout(this);
        this.vivzrhbrgf = relativeLayout8;
        relativeLayout8.setLayoutParams(new LinearLayout.LayoutParams(456, 164));
        this.vivzrhbrgf.setPadding(142, 98, 99, 15);
        linearLayout.addView(this.vivzrhbrgf);
        this.vivzrhbrgf.setBackgroundColor(Color.parseColor("#cbbcf1"));
        RatingBar ratingBar6 = new RatingBar(this);
        this.vsklvbbedb = ratingBar6;
        ratingBar6.setLayoutParams(new LinearLayout.LayoutParams(1433, 842));
        this.vsklvbbedb.setPadding(65, 84, 143, 178);
        linearLayout.addView(this.vsklvbbedb);
        this.vsklvbbedb.setBackgroundColor(Color.parseColor("#c34b54"));
        RadioButton radioButton10 = new RadioButton(this);
        this.lmpbrvbjms = radioButton10;
        radioButton10.setLayoutParams(new LinearLayout.LayoutParams(451, 775));
        this.lmpbrvbjms.setPadding(19, 175, BDLocation.TypeServerError, 124);
        linearLayout.addView(this.lmpbrvbjms);
        this.lmpbrvbjms.setBackgroundColor(Color.parseColor("#11feb2"));
        ToggleButton toggleButton9 = new ToggleButton(this);
        this.dvtkkybzny = toggleButton9;
        toggleButton9.setLayoutParams(new LinearLayout.LayoutParams(1157, 1116));
        this.dvtkkybzny.setPadding(18, 34, 63, 29);
        linearLayout.addView(this.dvtkkybzny);
        this.dvtkkybzny.setBackgroundColor(Color.parseColor("#45085c"));
        ToggleButton toggleButton10 = new ToggleButton(this);
        this.fecocgmdft = toggleButton10;
        toggleButton10.setLayoutParams(new LinearLayout.LayoutParams(603, 366));
        this.fecocgmdft.setPadding(183, 101, 81, 100);
        linearLayout.addView(this.fecocgmdft);
        this.fecocgmdft.setBackgroundColor(Color.parseColor("#c6a9ae"));
        ListView listView5 = new ListView(this);
        this.lcqjzpcyel = listView5;
        listView5.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.Custom.TYPE_DIMENSION, 1722));
        this.lcqjzpcyel.setPadding(5, 75, 109, 52);
        linearLayout.addView(this.lcqjzpcyel);
        this.lcqjzpcyel.setBackgroundColor(Color.parseColor("#4678ae"));
        RatingBar ratingBar7 = new RatingBar(this);
        this.fpclipbkhn = ratingBar7;
        ratingBar7.setLayoutParams(new LinearLayout.LayoutParams(1067, 349));
        this.fpclipbkhn.setPadding(89, 192, 114, 176);
        linearLayout.addView(this.fpclipbkhn);
        this.fpclipbkhn.setBackgroundColor(Color.parseColor("#15ee18"));
        SeekBar seekBar11 = new SeekBar(this);
        this.xybvcfbfbv = seekBar11;
        seekBar11.setLayoutParams(new LinearLayout.LayoutParams(1586, 810));
        this.xybvcfbfbv.setPadding(173, 149, 0, 18);
        linearLayout.addView(this.xybvcfbfbv);
        this.xybvcfbfbv.setBackgroundColor(Color.parseColor("#242712"));
        ScrollView scrollView7 = new ScrollView(this);
        this.qrmhvvabyv = scrollView7;
        scrollView7.setLayoutParams(new LinearLayout.LayoutParams(1013, 1324));
        this.qrmhvvabyv.setPadding(146, 103, 173, 113);
        linearLayout.addView(this.qrmhvvabyv);
        this.qrmhvvabyv.setBackgroundColor(Color.parseColor("#486785"));
        ToggleButton toggleButton11 = new ToggleButton(this);
        this.iemegxzyvi = toggleButton11;
        toggleButton11.setLayoutParams(new LinearLayout.LayoutParams(1578, 1187));
        this.iemegxzyvi.setPadding(65, 142, 192, 15);
        linearLayout.addView(this.iemegxzyvi);
        this.iemegxzyvi.setBackgroundColor(Color.parseColor("#9169da"));
        TableLayout tableLayout8 = new TableLayout(this);
        this.amqbtjtbqk = tableLayout8;
        tableLayout8.setLayoutParams(new LinearLayout.LayoutParams(119, 644));
        this.amqbtjtbqk.setPadding(69, 25, 141, BDLocation.TypeServerDecryptError);
        linearLayout.addView(this.amqbtjtbqk);
        this.amqbtjtbqk.setBackgroundColor(Color.parseColor("#679ca3"));
        Button button5 = new Button(this);
        this.akaxlnyonx = button5;
        button5.setLayoutParams(new LinearLayout.LayoutParams(1633, 512));
        this.akaxlnyonx.setPadding(64, 152, 85, 154);
        linearLayout.addView(this.akaxlnyonx);
        this.akaxlnyonx.setBackgroundColor(Color.parseColor("#71b4a5"));
        FrameLayout frameLayout11 = new FrameLayout(this);
        this.alvmoviesh = frameLayout11;
        frameLayout11.setLayoutParams(new LinearLayout.LayoutParams(345, 1885));
        this.alvmoviesh.setPadding(63, 65, 73, 145);
        linearLayout.addView(this.alvmoviesh);
        this.alvmoviesh.setBackgroundColor(Color.parseColor("#123c16"));
        RelativeLayout relativeLayout9 = new RelativeLayout(this);
        this.tcdjehmrlq = relativeLayout9;
        relativeLayout9.setLayoutParams(new LinearLayout.LayoutParams(1286, 331));
        this.tcdjehmrlq.setPadding(140, 101, 171, 193);
        linearLayout.addView(this.tcdjehmrlq);
        this.tcdjehmrlq.setBackgroundColor(Color.parseColor("#4812b1"));
        ScrollView scrollView8 = new ScrollView(this);
        this.qafqbjjckb = scrollView8;
        scrollView8.setLayoutParams(new LinearLayout.LayoutParams(1675, 375));
        this.qafqbjjckb.setPadding(119, PictureConfig.CHOOSE_REQUEST, 185, 39);
        linearLayout.addView(this.qafqbjjckb);
        this.qafqbjjckb.setBackgroundColor(Color.parseColor("#0914e0"));
        TextView textView12 = new TextView(this);
        this.dmjlsydagg = textView12;
        textView12.setLayoutParams(new LinearLayout.LayoutParams(94, 883));
        this.dmjlsydagg.setPadding(169, 131, 56, 141);
        linearLayout.addView(this.dmjlsydagg);
        this.dmjlsydagg.setBackgroundColor(Color.parseColor("#10efd7"));
        Switch r215 = new Switch(this);
        this.ctheimpwxk = r215;
        r215.setLayoutParams(new LinearLayout.LayoutParams(122, 1294));
        this.ctheimpwxk.setPadding(134, 79, 153, 164);
        linearLayout.addView(this.ctheimpwxk);
        this.ctheimpwxk.setBackgroundColor(Color.parseColor("#812095"));
        TableLayout tableLayout9 = new TableLayout(this);
        this.dmyckvrxgx = tableLayout9;
        tableLayout9.setLayoutParams(new LinearLayout.LayoutParams(1002, 1207));
        this.dmyckvrxgx.setPadding(13, 106, 51, 112);
        linearLayout.addView(this.dmyckvrxgx);
        this.dmyckvrxgx.setBackgroundColor(Color.parseColor("#c2eaa9"));
        ViewFlipper viewFlipper13 = new ViewFlipper(this);
        this.bdffobiidt = viewFlipper13;
        viewFlipper13.setLayoutParams(new LinearLayout.LayoutParams(922, 1108));
        this.bdffobiidt.setPadding(190, 122, 164, 133);
        linearLayout.addView(this.bdffobiidt);
        this.bdffobiidt.setBackgroundColor(Color.parseColor("#482504"));
        ProgressBar progressBar8 = new ProgressBar(this);
        this.kucdkindqc = progressBar8;
        progressBar8.setLayoutParams(new LinearLayout.LayoutParams(660, 1161));
        this.kucdkindqc.setPadding(24, 98, 197, 182);
        linearLayout.addView(this.kucdkindqc);
        this.kucdkindqc.setBackgroundColor(Color.parseColor("#991a5e"));
        RelativeLayout relativeLayout10 = new RelativeLayout(this);
        this.yirupqmedr = relativeLayout10;
        relativeLayout10.setLayoutParams(new LinearLayout.LayoutParams(284, 1276));
        this.yirupqmedr.setPadding(22, 153, 113, 166);
        linearLayout.addView(this.yirupqmedr);
        this.yirupqmedr.setBackgroundColor(Color.parseColor("#723037"));
        Spinner spinner7 = new Spinner(this);
        this.nohfvkzzgf = spinner7;
        spinner7.setLayoutParams(new LinearLayout.LayoutParams(657, 493));
        this.nohfvkzzgf.setPadding(68, 14, 73, 24);
        linearLayout.addView(this.nohfvkzzgf);
        this.nohfvkzzgf.setBackgroundColor(Color.parseColor("#29ac87"));
        ViewFlipper viewFlipper14 = new ViewFlipper(this);
        this.fvckkeyodn = viewFlipper14;
        viewFlipper14.setLayoutParams(new LinearLayout.LayoutParams(HealthyViewModel.Type_Sync_TimeOut, 714));
        this.fvckkeyodn.setPadding(3, 174, 40, 64);
        linearLayout.addView(this.fvckkeyodn);
        this.fvckkeyodn.setBackgroundColor(Color.parseColor("#125d50"));
        TableLayout tableLayout10 = new TableLayout(this);
        this.fuoczmgeni = tableLayout10;
        tableLayout10.setLayoutParams(new LinearLayout.LayoutParams(895, 1064));
        this.fuoczmgeni.setPadding(45, 164, 47, 92);
        linearLayout.addView(this.fuoczmgeni);
        this.fuoczmgeni.setBackgroundColor(Color.parseColor("#a913f1"));
        TextView textView13 = new TextView(this);
        this.jmiyeeadse = textView13;
        textView13.setLayoutParams(new LinearLayout.LayoutParams(1523, 1285));
        this.jmiyeeadse.setPadding(142, 88, 100, 77);
        linearLayout.addView(this.jmiyeeadse);
        this.jmiyeeadse.setBackgroundColor(Color.parseColor("#7cd072"));
        Switch r216 = new Switch(this);
        this.cmitnafxtz = r216;
        r216.setLayoutParams(new LinearLayout.LayoutParams(182, 1665));
        this.cmitnafxtz.setPadding(49, 195, 123, 47);
        linearLayout.addView(this.cmitnafxtz);
        this.cmitnafxtz.setBackgroundColor(Color.parseColor("#54f93a"));
        RadioButton radioButton11 = new RadioButton(this);
        this.bmaxhhaknw = radioButton11;
        radioButton11.setLayoutParams(new LinearLayout.LayoutParams(1209, 1589));
        this.bmaxhhaknw.setPadding(115, 71, 25, 96);
        linearLayout.addView(this.bmaxhhaknw);
        this.bmaxhhaknw.setBackgroundColor(Color.parseColor("#d73cc5"));
        TableLayout tableLayout11 = new TableLayout(this);
        this.khbcvgjsvq = tableLayout11;
        tableLayout11.setLayoutParams(new LinearLayout.LayoutParams(1721, 100));
        this.khbcvgjsvq.setPadding(8, 77, 73, 132);
        linearLayout.addView(this.khbcvgjsvq);
        this.khbcvgjsvq.setBackgroundColor(Color.parseColor("#10db9d"));
        GridView gridView11 = new GridView(this);
        this.lhcioybnkc = gridView11;
        gridView11.setLayoutParams(new LinearLayout.LayoutParams(1762, 390));
        this.lhcioybnkc.setPadding(151, 158, 102, 190);
        linearLayout.addView(this.lhcioybnkc);
        this.lhcioybnkc.setBackgroundColor(Color.parseColor("#0ed879"));
        CheckBox checkBox5 = new CheckBox(this);
        this.ovlbmrawzn = checkBox5;
        checkBox5.setLayoutParams(new LinearLayout.LayoutParams(581, 1483));
        this.ovlbmrawzn.setPadding(123, 163, 20, 179);
        linearLayout.addView(this.ovlbmrawzn);
        this.ovlbmrawzn.setBackgroundColor(Color.parseColor("#64cd05"));
        RelativeLayout relativeLayout11 = new RelativeLayout(this);
        this.olouvdelgx = relativeLayout11;
        relativeLayout11.setLayoutParams(new LinearLayout.LayoutParams(399, 1315));
        this.olouvdelgx.setPadding(112, 40, 171, 96);
        linearLayout.addView(this.olouvdelgx);
        this.olouvdelgx.setBackgroundColor(Color.parseColor("#2d74fc"));
        ViewFlipper viewFlipper15 = new ViewFlipper(this);
        this.szjaqrzblw = viewFlipper15;
        viewFlipper15.setLayoutParams(new LinearLayout.LayoutParams(1024, 1284));
        this.szjaqrzblw.setPadding(199, 156, 136, 28);
        linearLayout.addView(this.szjaqrzblw);
        this.szjaqrzblw.setBackgroundColor(Color.parseColor("#9bf443"));
        FrameLayout frameLayout12 = new FrameLayout(this);
        this.axrgxjtagv = frameLayout12;
        frameLayout12.setLayoutParams(new LinearLayout.LayoutParams(1244, 556));
        this.axrgxjtagv.setPadding(71, 13, 26, 128);
        linearLayout.addView(this.axrgxjtagv);
        this.axrgxjtagv.setBackgroundColor(Color.parseColor("#a4f1c1"));
        RelativeLayout relativeLayout12 = new RelativeLayout(this);
        this.drmbtrltrd = relativeLayout12;
        relativeLayout12.setLayoutParams(new LinearLayout.LayoutParams(1546, 190));
        this.drmbtrltrd.setPadding(185, 23, 190, 9);
        linearLayout.addView(this.drmbtrltrd);
        this.drmbtrltrd.setBackgroundColor(Color.parseColor("#350509"));
        EditText editText6 = new EditText(this);
        this.mkfbaeesox = editText6;
        editText6.setLayoutParams(new LinearLayout.LayoutParams(1614, 1682));
        this.mkfbaeesox.setPadding(71, 51, 152, 80);
        linearLayout.addView(this.mkfbaeesox);
        this.mkfbaeesox.setBackgroundColor(Color.parseColor("#d81da4"));
        RadioButton radioButton12 = new RadioButton(this);
        this.kwxygtketv = radioButton12;
        radioButton12.setLayoutParams(new LinearLayout.LayoutParams(1533, 1788));
        this.kwxygtketv.setPadding(74, 60, 111, 136);
        linearLayout.addView(this.kwxygtketv);
        this.kwxygtketv.setBackgroundColor(Color.parseColor("#cc32b7"));
        CheckBox checkBox6 = new CheckBox(this);
        this.dmeegndsbq = checkBox6;
        checkBox6.setLayoutParams(new LinearLayout.LayoutParams(1637, TypedValues.PositionType.TYPE_DRAWPATH));
        this.dmeegndsbq.setPadding(38, 37, 35, 6);
        linearLayout.addView(this.dmeegndsbq);
        this.dmeegndsbq.setBackgroundColor(Color.parseColor("#1b2baa"));
        Switch r217 = new Switch(this);
        this.ggbbonwxns = r217;
        r217.setLayoutParams(new LinearLayout.LayoutParams(143, 833));
        this.ggbbonwxns.setPadding(155, BDLocation.TypeCoarseLocation, 191, 151);
        linearLayout.addView(this.ggbbonwxns);
        this.ggbbonwxns.setBackgroundColor(Color.parseColor("#d5f0fa"));
        LinearLayout linearLayout13 = new LinearLayout(this);
        this.jhpqmhgrsu = linearLayout13;
        linearLayout13.setLayoutParams(new LinearLayout.LayoutParams(1530, PictureConfig.REQUEST_GO_SETTING));
        this.jhpqmhgrsu.setPadding(130, 128, 165, 187);
        linearLayout.addView(this.jhpqmhgrsu);
        this.jhpqmhgrsu.setBackgroundColor(Color.parseColor("#27c6c2"));
        TimePicker timePicker6 = new TimePicker(this);
        this.ubejfdhrch = timePicker6;
        timePicker6.setLayoutParams(new LinearLayout.LayoutParams(669, 675));
        this.ubejfdhrch.setPadding(89, 159, 57, 111);
        linearLayout.addView(this.ubejfdhrch);
        this.ubejfdhrch.setBackgroundColor(Color.parseColor("#4d0cd0"));
        RatingBar ratingBar8 = new RatingBar(this);
        this.ghisyffrue = ratingBar8;
        ratingBar8.setLayoutParams(new LinearLayout.LayoutParams(1697, 1409));
        this.ghisyffrue.setPadding(156, 74, WebSocketProtocol.PAYLOAD_SHORT, 64);
        linearLayout.addView(this.ghisyffrue);
        this.ghisyffrue.setBackgroundColor(Color.parseColor("#c72c42"));
        RelativeLayout relativeLayout13 = new RelativeLayout(this);
        this.tgrqctxrky = relativeLayout13;
        relativeLayout13.setLayoutParams(new LinearLayout.LayoutParams(1041, 1978));
        this.tgrqctxrky.setPadding(25, 88, 96, 35);
        linearLayout.addView(this.tgrqctxrky);
        this.tgrqctxrky.setBackgroundColor(Color.parseColor("#07cf06"));
        ProgressBar progressBar9 = new ProgressBar(this);
        this.ptlyabvxze = progressBar9;
        progressBar9.setLayoutParams(new LinearLayout.LayoutParams(615, 1847));
        this.ptlyabvxze.setPadding(47, 154, 196, 40);
        linearLayout.addView(this.ptlyabvxze);
        this.ptlyabvxze.setBackgroundColor(Color.parseColor("#8d3f6c"));
        SeekBar seekBar12 = new SeekBar(this);
        this.ukdllutzbk = seekBar12;
        seekBar12.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.AttributesType.TYPE_PATH_ROTATE, 734));
        this.ukdllutzbk.setPadding(99, 181, 10, 62);
        linearLayout.addView(this.ukdllutzbk);
        this.ukdllutzbk.setBackgroundColor(Color.parseColor("#9b2c33"));
        LinearLayout linearLayout14 = new LinearLayout(this);
        this.bjtygjaqdg = linearLayout14;
        linearLayout14.setLayoutParams(new LinearLayout.LayoutParams(1635, 1498));
        this.bjtygjaqdg.setPadding(112, 67, 38, 129);
        linearLayout.addView(this.bjtygjaqdg);
        this.bjtygjaqdg.setBackgroundColor(Color.parseColor("#2117cf"));
        SeekBar seekBar13 = new SeekBar(this);
        this.kjtqrftffo = seekBar13;
        seekBar13.setLayoutParams(new LinearLayout.LayoutParams(1307, 1053));
        this.kjtqrftffo.setPadding(10, 8, 165, 169);
        linearLayout.addView(this.kjtqrftffo);
        this.kjtqrftffo.setBackgroundColor(Color.parseColor("#c1ed1a"));
        Switch r218 = new Switch(this);
        this.sigryumbka = r218;
        r218.setLayoutParams(new LinearLayout.LayoutParams(375, 1032));
        this.sigryumbka.setPadding(78, 194, 26, 92);
        linearLayout.addView(this.sigryumbka);
        this.sigryumbka.setBackgroundColor(Color.parseColor("#c34240"));
        TextView textView14 = new TextView(this);
        this.hadmlsjyxq = textView14;
        textView14.setLayoutParams(new LinearLayout.LayoutParams(1924, 1586));
        this.hadmlsjyxq.setPadding(24, 96, 158, 155);
        linearLayout.addView(this.hadmlsjyxq);
        this.hadmlsjyxq.setBackgroundColor(Color.parseColor("#324d63"));
        RatingBar ratingBar9 = new RatingBar(this);
        this.ewecrllsay = ratingBar9;
        ratingBar9.setLayoutParams(new LinearLayout.LayoutParams(351, 335));
        this.ewecrllsay.setPadding(34, 3, 133, 57);
        linearLayout.addView(this.ewecrllsay);
        this.ewecrllsay.setBackgroundColor(Color.parseColor("#0be2ba"));
        RelativeLayout relativeLayout14 = new RelativeLayout(this);
        this.ywxsmpxkex = relativeLayout14;
        relativeLayout14.setLayoutParams(new LinearLayout.LayoutParams(1848, 1248));
        this.ywxsmpxkex.setPadding(69, 171, 43, 151);
        linearLayout.addView(this.ywxsmpxkex);
        this.ywxsmpxkex.setBackgroundColor(Color.parseColor("#b2c40c"));
        Spinner spinner8 = new Spinner(this);
        this.ekglkndsqp = spinner8;
        spinner8.setLayoutParams(new LinearLayout.LayoutParams(1199, 1567));
        this.ekglkndsqp.setPadding(142, 65, 42, 157);
        linearLayout.addView(this.ekglkndsqp);
        this.ekglkndsqp.setBackgroundColor(Color.parseColor("#6eff6b"));
        RadioButton radioButton13 = new RadioButton(this);
        this.ihtdwbiihh = radioButton13;
        radioButton13.setLayoutParams(new LinearLayout.LayoutParams(33, 1142));
        this.ihtdwbiihh.setPadding(8, 82, 71, 186);
        linearLayout.addView(this.ihtdwbiihh);
        this.ihtdwbiihh.setBackgroundColor(Color.parseColor("#3d25e7"));
        TextView textView15 = new TextView(this);
        this.puzbfdpqtn = textView15;
        textView15.setLayoutParams(new LinearLayout.LayoutParams(GattClient.STATE_PREPARE_CONNECTING, 1469));
        this.puzbfdpqtn.setPadding(152, 172, 72, 52);
        linearLayout.addView(this.puzbfdpqtn);
        this.puzbfdpqtn.setBackgroundColor(Color.parseColor("#ed31f5"));
        ProgressBar progressBar10 = new ProgressBar(this);
        this.xdpwpehdqc = progressBar10;
        progressBar10.setLayoutParams(new LinearLayout.LayoutParams(580, 72));
        this.xdpwpehdqc.setPadding(178, 153, 60, 179);
        linearLayout.addView(this.xdpwpehdqc);
        this.xdpwpehdqc.setBackgroundColor(Color.parseColor("#a97118"));
        ListView listView6 = new ListView(this);
        this.jrgcytldob = listView6;
        listView6.setLayoutParams(new LinearLayout.LayoutParams(1841, 1243));
        this.jrgcytldob.setPadding(199, 8, 192, BDLocation.TypeCoarseLocation);
        linearLayout.addView(this.jrgcytldob);
        this.jrgcytldob.setBackgroundColor(Color.parseColor("#46708a"));
    }
}
