package com.device.watch.com.device.watch.qkztkazqno;

import android.app.Activity;
import android.graphics.Color;
import android.os.Bundle;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.CheckBox;
import android.widget.DatePicker;
import android.widget.EditText;
import android.widget.FrameLayout;
import android.widget.GridView;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ListView;
import android.widget.ProgressBar;
import android.widget.RadioButton;
import android.widget.RatingBar;
import android.widget.RelativeLayout;
import android.widget.ScrollView;
import android.widget.SeekBar;
import android.widget.Spinner;
import android.widget.Switch;
import android.widget.TableLayout;
import android.widget.TextView;
import android.widget.TimePicker;
import android.widget.ToggleButton;
import android.widget.ViewFlipper;
import androidx.constraintlayout.core.motion.utils.TypedValues;
import androidx.core.view.PointerIconCompat;
import com.baidu.location.BDLocation;
import com.king.zxing.util.CodeUtils;
import com.luck.picture.lib.config.PictureConfig;
import com.realsil.sdk.bbpro.core.protocol.Contract;
import com.realsil.sdk.bbpro.equalizer.AudioEq;
import com.realsil.sdk.core.bluetooth.connection.le.GattClient;
import okhttp3.internal.ws.WebSocketProtocol;

/* loaded from: classes2.dex */
public class FzcnqboprulActivity extends Activity {
    SeekBar aaotwgnkql;
    Spinner acunfbkilc;
    SeekBar acydfrklmx;
    DatePicker amtvccugdu;
    ToggleButton auxzqkhndh;
    Switch avxymvtetc;
    ProgressBar aysvzpmxnr;
    EditText azbfcrrlle;
    LinearLayout bampsmvvsu;
    DatePicker bbeviacvbp;
    CheckBox bbmqvrdpyb;
    RelativeLayout bdqqxvowpp;
    EditText befdfygofo;
    CheckBox bertgdbtne;
    ListView bfrcttxtts;
    ViewFlipper bhamdzyrkh;
    RadioButton biiyjpumnc;
    FrameLayout biujbxbshj;
    ViewFlipper bjijepcllq;
    CheckBox cccuaffhdb;
    GridView cdqalxdcww;
    ProgressBar cvcdkbzaqm;
    DatePicker cvdlklebln;
    GridView czjdpromuo;
    ToggleButton czkhxhfyfx;
    ToggleButton dfahwkfftg;
    TimePicker dkmysigdnf;
    TableLayout dsxsvhpyeq;
    ImageView duxkmnlsqz;
    RelativeLayout dvfkrmzfpf;
    Spinner ebegzhebhn;
    TextView ebxvypxhbk;
    GridView eckxwkgpes;
    GridView eogqijejtd;
    RadioButton eraifatkfr;
    ListView etfjzgwdke;
    ToggleButton exyzqdzymj;
    TextView fberklslgk;
    SeekBar fjghvctxol;
    LinearLayout fodmendiiv;
    EditText fpvdbskmkx;
    ListView ftngnefsok;
    EditText fwljcnqcem;
    ImageView gkhclelmen;
    ToggleButton gvujqaezbm;
    ScrollView hbnulwpkfl;
    FrameLayout hdvjfanlwj;
    LinearLayout hhrtpjogtm;
    SeekBar hpfbystman;
    TableLayout httzwvxqgg;
    ImageView hxsaksfrjw;
    EditText iaxmqpeobl;
    ImageView idsolswicx;
    ProgressBar ielishnmhg;
    ProgressBar igxnmdwifn;
    EditText isxzdvzhjs;
    CheckBox itqjxqzvse;
    CheckBox ixwfzefnyh;
    ListView jbxwwjyiff;
    ListView jezeqevzqx;
    LinearLayout jkymciluyk;
    SeekBar jnsoswqtug;
    TimePicker jolhrsnxpb;
    TextView jsjygqjjft;
    CheckBox jwqzowcfzd;
    TimePicker jwskqiomeb;
    Spinner kamwljgyww;
    ToggleButton kbjokjbswp;
    ImageView kegroqpokb;
    ToggleButton kfkbxvciwd;
    RadioButton kgdovzjhxq;
    DatePicker khfhkkfhis;
    EditText kiwqxycbzv;
    TableLayout kmpniditmp;
    ListView kndvxpgigl;
    GridView kqizzpgfll;
    RadioButton kuzlopnjpq;
    ListView kzlluxnatm;
    RadioButton lctjhpxtdg;
    Spinner ldjckqxpof;
    EditText ldrumeajvb;
    LinearLayout leqixbpejb;
    ViewFlipper ljdslgxdpj;
    GridView lphaspfilt;
    FrameLayout lqydntgedx;
    ProgressBar lvjcfmfdpw;
    ImageView lzriamvhdf;
    ProgressBar mbbarawmnv;
    FrameLayout mgjahiutmm;
    TextView mknpfuzvfj;
    TimePicker mphnpnyths;
    Switch msyzfvyvvq;
    RelativeLayout mttovoelao;
    LinearLayout mysxxrfgzi;
    ListView mzuxmsubzd;
    ScrollView naputnpxhv;
    ImageView nhvnsqcjlg;
    Spinner nizixsloke;
    TableLayout nnusuaddvn;
    RatingBar nxfatrbsyh;
    ViewFlipper nxkyjoxoye;
    LinearLayout nzkocthqln;
    Button olpemejqbt;
    Switch otzybczdrg;
    TableLayout ovpyoqamjh;
    ImageView pekgbpdyui;
    RatingBar pjdedhkimj;
    RadioButton pjetsenwwn;
    Switch puamslqncy;
    LinearLayout pwiborpifn;
    GridView pybuulxbjl;
    RadioButton pzbneykttd;
    Spinner qcgfnagcov;
    TimePicker qeczrwsfhm;
    FrameLayout qegzuwlymo;
    LinearLayout qerycsfooz;
    CheckBox qmwydpikdd;
    RelativeLayout qnedvoecxl;
    RadioButton qqntnnpzbj;
    GridView qtchzdbhmw;
    FrameLayout qylqrtvvqc;
    DatePicker rbjysvsaat;
    DatePicker rcjbwbpzwu;
    SeekBar rcmksehyff;
    RelativeLayout rfljfzmuqm;
    ListView rhchevwdxb;
    FrameLayout rhirwgdxps;
    EditText rlzpzwheap;
    ProgressBar rtlgkognev;
    ViewFlipper rvjnvqettz;
    GridView rzeyzvpswl;
    FrameLayout sbiqluyioe;
    LinearLayout sotmmdtjmj;
    Spinner sumcyrblrg;
    ToggleButton sxzaajlxiz;
    SeekBar szsvkmzube;
    Button tauatcpxdl;
    RatingBar tbcihzcagz;
    RelativeLayout tiykcfoajp;
    CheckBox ttoqxdaskf;
    FrameLayout tyuzlabfog;
    CheckBox ucjnuiqkgv;
    RelativeLayout uicdkvymxw;
    RatingBar uuyulhvyta;
    TableLayout uvyhpwabgf;
    EditText uxdcxipkme;
    GridView uyliucmutj;
    ViewFlipper uynobiazrb;
    RelativeLayout vcalyhvpgl;
    CheckBox vdonjugvtb;
    TimePicker vetewzoogf;
    Spinner viqjnartul;
    LinearLayout vknuleoghx;
    ListView vvqyaqtgva;
    GridView wbdybmrgmm;
    GridView wetfraaoqc;
    RatingBar wgpaozkykb;
    CheckBox widvdzappy;
    CheckBox wktcaotgda;
    SeekBar wojwsxqoqn;
    ViewFlipper wqgvwwukkf;
    GridView wszoczlxyr;
    DatePicker wukqveeovr;
    Spinner xfcilhmlbm;
    Button xjuvvjhebp;
    Switch xlbszlypov;
    LinearLayout xltpzswtdv;
    ProgressBar xpzgrswxol;
    TableLayout xtarnifres;
    EditText xwmgofdpwf;
    RatingBar yaakwncdxj;
    FrameLayout ycaocyrjur;
    RadioButton yciwwuaytt;
    TimePicker ydxmfglymi;
    DatePicker yfforiqouf;
    ImageView yhkldcfzuq;
    ScrollView yjqtlmlcft;
    Switch ylwhkattnb;
    ImageView yuwvlincfb;
    ToggleButton yynfqejhdm;
    CheckBox yzrhlokrow;
    TimePicker yzxonlwnvr;
    ProgressBar zehijsytto;
    RelativeLayout zrmvyxprks;
    TimePicker zznznakhcu;

    @Override // android.app.Activity
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        LinearLayout linearLayout = new LinearLayout(this);
        setContentView(linearLayout);
        linearLayout.setLayoutParams(new ViewGroup.LayoutParams(-1, -1));
        linearLayout.setOrientation(1);
        linearLayout.setBackgroundColor(Color.parseColor("#59836f"));
        Switch r2 = new Switch(this);
        this.otzybczdrg = r2;
        r2.setLayoutParams(new LinearLayout.LayoutParams(1023, 1576));
        this.otzybczdrg.setPadding(58, 196, 84, 150);
        linearLayout.addView(this.otzybczdrg);
        this.otzybczdrg.setBackgroundColor(Color.parseColor("#83f7ff"));
        LinearLayout linearLayout2 = new LinearLayout(this);
        this.pwiborpifn = linearLayout2;
        linearLayout2.setLayoutParams(new LinearLayout.LayoutParams(PictureConfig.REQUEST_GO_SETTING, 1926));
        this.pwiborpifn.setPadding(77, 89, 148, 154);
        linearLayout.addView(this.pwiborpifn);
        this.pwiborpifn.setBackgroundColor(Color.parseColor("#72daff"));
        FrameLayout frameLayout = new FrameLayout(this);
        this.qegzuwlymo = frameLayout;
        frameLayout.setLayoutParams(new LinearLayout.LayoutParams(1485, 1282));
        this.qegzuwlymo.setPadding(198, 19, 127, 107);
        linearLayout.addView(this.qegzuwlymo);
        this.qegzuwlymo.setBackgroundColor(Color.parseColor("#9d9aa9"));
        GridView gridView = new GridView(this);
        this.kqizzpgfll = gridView;
        gridView.setLayoutParams(new LinearLayout.LayoutParams(1331, 174));
        this.kqizzpgfll.setPadding(80, 38, 37, 108);
        linearLayout.addView(this.kqizzpgfll);
        this.kqizzpgfll.setBackgroundColor(Color.parseColor("#4d2bd6"));
        ViewFlipper viewFlipper = new ViewFlipper(this);
        this.ljdslgxdpj = viewFlipper;
        viewFlipper.setLayoutParams(new LinearLayout.LayoutParams(447, 369));
        this.ljdslgxdpj.setPadding(50, 36, 28, 111);
        linearLayout.addView(this.ljdslgxdpj);
        this.ljdslgxdpj.setBackgroundColor(Color.parseColor("#9d80bb"));
        RelativeLayout relativeLayout = new RelativeLayout(this);
        this.vcalyhvpgl = relativeLayout;
        relativeLayout.setLayoutParams(new LinearLayout.LayoutParams(1995, 784));
        this.vcalyhvpgl.setPadding(13, 86, 27, 71);
        linearLayout.addView(this.vcalyhvpgl);
        this.vcalyhvpgl.setBackgroundColor(Color.parseColor("#aa815a"));
        CheckBox checkBox = new CheckBox(this);
        this.ixwfzefnyh = checkBox;
        checkBox.setLayoutParams(new LinearLayout.LayoutParams(165, 15));
        this.ixwfzefnyh.setPadding(121, 62, 107, 32);
        linearLayout.addView(this.ixwfzefnyh);
        this.ixwfzefnyh.setBackgroundColor(Color.parseColor("#4a0cd6"));
        ListView listView = new ListView(this);
        this.mzuxmsubzd = listView;
        listView.setLayoutParams(new LinearLayout.LayoutParams(1954, WebSocketProtocol.PAYLOAD_SHORT));
        this.mzuxmsubzd.setPadding(11, 7, 25, 106);
        linearLayout.addView(this.mzuxmsubzd);
        this.mzuxmsubzd.setBackground(new Jpddiesoiiu());
        RelativeLayout relativeLayout2 = new RelativeLayout(this);
        this.rfljfzmuqm = relativeLayout2;
        relativeLayout2.setLayoutParams(new LinearLayout.LayoutParams(1320, 523));
        this.rfljfzmuqm.setPadding(61, 140, 194, 76);
        linearLayout.addView(this.rfljfzmuqm);
        this.rfljfzmuqm.setBackgroundColor(Color.parseColor("#e074f8"));
        SeekBar seekBar = new SeekBar(this);
        this.rcmksehyff = seekBar;
        seekBar.setLayoutParams(new LinearLayout.LayoutParams(1704, 1548));
        this.rcmksehyff.setPadding(90, 68, 30, 61);
        linearLayout.addView(this.rcmksehyff);
        this.rcmksehyff.setBackgroundColor(Color.parseColor("#8190a0"));
        RatingBar ratingBar = new RatingBar(this);
        this.uuyulhvyta = ratingBar;
        ratingBar.setLayoutParams(new LinearLayout.LayoutParams(1476, 1468));
        this.uuyulhvyta.setPadding(165, 55, 10, 147);
        linearLayout.addView(this.uuyulhvyta);
        this.uuyulhvyta.setBackgroundColor(Color.parseColor("#5e7d1c"));
        GridView gridView2 = new GridView(this);
        this.pybuulxbjl = gridView2;
        gridView2.setLayoutParams(new LinearLayout.LayoutParams(1714, 320));
        this.pybuulxbjl.setPadding(BDLocation.TypeServerDecryptError, 52, 145, 67);
        linearLayout.addView(this.pybuulxbjl);
        this.pybuulxbjl.setBackgroundColor(Color.parseColor("#a58fe1"));
        Button button = new Button(this);
        this.xjuvvjhebp = button;
        button.setLayoutParams(new LinearLayout.LayoutParams(AudioEq.SW_EQ_DATA_LENGTH, 1008));
        this.xjuvvjhebp.setPadding(BDLocation.TypeCoarseLocation, 143, 98, BDLocation.TypeNetWorkLocation);
        linearLayout.addView(this.xjuvvjhebp);
        this.xjuvvjhebp.setBackgroundColor(Color.parseColor("#58b14f"));
        CheckBox checkBox2 = new CheckBox(this);
        this.qmwydpikdd = checkBox2;
        checkBox2.setLayoutParams(new LinearLayout.LayoutParams(1331, 1241));
        this.qmwydpikdd.setPadding(180, 21, BDLocation.TypeServerDecryptError, 131);
        linearLayout.addView(this.qmwydpikdd);
        this.qmwydpikdd.setBackgroundColor(Color.parseColor("#6d79f4"));
        ViewFlipper viewFlipper2 = new ViewFlipper(this);
        this.wqgvwwukkf = viewFlipper2;
        viewFlipper2.setLayoutParams(new LinearLayout.LayoutParams(1361, 80));
        this.wqgvwwukkf.setPadding(184, 107, 181, 80);
        linearLayout.addView(this.wqgvwwukkf);
        this.wqgvwwukkf.setBackgroundColor(Color.parseColor("#d2f652"));
        ProgressBar progressBar = new ProgressBar(this);
        this.cvcdkbzaqm = progressBar;
        progressBar.setLayoutParams(new LinearLayout.LayoutParams(1555, 1150));
        this.cvcdkbzaqm.setPadding(32, 132, BDLocation.TypeNetWorkLocation, 62);
        linearLayout.addView(this.cvcdkbzaqm);
        this.cvcdkbzaqm.setBackgroundColor(Color.parseColor("#ebd8a9"));
        ToggleButton toggleButton = new ToggleButton(this);
        this.sxzaajlxiz = toggleButton;
        toggleButton.setLayoutParams(new LinearLayout.LayoutParams(83, 1395));
        this.sxzaajlxiz.setPadding(144, 169, 176, 194);
        linearLayout.addView(this.sxzaajlxiz);
        this.sxzaajlxiz.setBackgroundColor(Color.parseColor("#8d93c3"));
        DatePicker datePicker = new DatePicker(this);
        this.yfforiqouf = datePicker;
        datePicker.setLayoutParams(new LinearLayout.LayoutParams(1573, 59));
        this.yfforiqouf.setPadding(180, 36, 39, 130);
        linearLayout.addView(this.yfforiqouf);
        this.yfforiqouf.setBackgroundColor(Color.parseColor("#57f498"));
        ToggleButton toggleButton2 = new ToggleButton(this);
        this.gvujqaezbm = toggleButton2;
        toggleButton2.setLayoutParams(new LinearLayout.LayoutParams(1117, 1076));
        this.gvujqaezbm.setPadding(92, 158, 23, 151);
        linearLayout.addView(this.gvujqaezbm);
        this.gvujqaezbm.setBackgroundColor(Color.parseColor("#8b477a"));
        ViewFlipper viewFlipper3 = new ViewFlipper(this);
        this.bhamdzyrkh = viewFlipper3;
        viewFlipper3.setLayoutParams(new LinearLayout.LayoutParams(998, 1977));
        this.bhamdzyrkh.setPadding(115, 71, 63, 30);
        linearLayout.addView(this.bhamdzyrkh);
        this.bhamdzyrkh.setBackgroundColor(Color.parseColor("#0bcafa"));
        TimePicker timePicker = new TimePicker(this);
        this.vetewzoogf = timePicker;
        timePicker.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.MotionType.TYPE_QUANTIZE_INTERPOLATOR_TYPE, 1649));
        this.vetewzoogf.setPadding(75, 139, 101, 141);
        linearLayout.addView(this.vetewzoogf);
        this.vetewzoogf.setBackgroundColor(Color.parseColor("#f02677"));
        ViewFlipper viewFlipper4 = new ViewFlipper(this);
        this.uynobiazrb = viewFlipper4;
        viewFlipper4.setLayoutParams(new LinearLayout.LayoutParams(476, 168));
        this.uynobiazrb.setPadding(176, 114, 8, 65);
        linearLayout.addView(this.uynobiazrb);
        this.uynobiazrb.setBackgroundColor(Color.parseColor("#01fd0d"));
        RatingBar ratingBar2 = new RatingBar(this);
        this.wgpaozkykb = ratingBar2;
        ratingBar2.setLayoutParams(new LinearLayout.LayoutParams(1358, 679));
        this.wgpaozkykb.setPadding(15, 65, 163, 46);
        linearLayout.addView(this.wgpaozkykb);
        this.wgpaozkykb.setBackgroundColor(Color.parseColor("#fee48b"));
        SeekBar seekBar2 = new SeekBar(this);
        this.aaotwgnkql = seekBar2;
        seekBar2.setLayoutParams(new LinearLayout.LayoutParams(839, 518));
        this.aaotwgnkql.setPadding(138, 165, 80, 192);
        linearLayout.addView(this.aaotwgnkql);
        this.aaotwgnkql.setBackgroundColor(Color.parseColor("#96e624"));
        TextView textView = new TextView(this);
        this.ebxvypxhbk = textView;
        textView.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.Custom.TYPE_INT, TypedValues.Custom.TYPE_STRING));
        this.ebxvypxhbk.setPadding(114, 95, 63, 38);
        linearLayout.addView(this.ebxvypxhbk);
        this.ebxvypxhbk.setBackgroundColor(Color.parseColor("#0f9173"));
        RatingBar ratingBar3 = new RatingBar(this);
        this.yaakwncdxj = ratingBar3;
        ratingBar3.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.CycleType.TYPE_VISIBILITY, 262));
        this.yaakwncdxj.setPadding(144, 57, 193, 101);
        linearLayout.addView(this.yaakwncdxj);
        this.yaakwncdxj.setBackgroundColor(Color.parseColor("#6fbf5c"));
        RadioButton radioButton = new RadioButton(this);
        this.kuzlopnjpq = radioButton;
        radioButton.setLayoutParams(new LinearLayout.LayoutParams(1173, 1956));
        this.kuzlopnjpq.setPadding(10, 22, 61, 82);
        linearLayout.addView(this.kuzlopnjpq);
        this.kuzlopnjpq.setBackgroundColor(Color.parseColor("#809351"));
        CheckBox checkBox3 = new CheckBox(this);
        this.cccuaffhdb = checkBox3;
        checkBox3.setLayoutParams(new LinearLayout.LayoutParams(1104, 1915));
        this.cccuaffhdb.setPadding(117, 49, 198, 129);
        linearLayout.addView(this.cccuaffhdb);
        this.cccuaffhdb.setBackgroundColor(Color.parseColor("#b06203"));
        EditText editText = new EditText(this);
        this.ldrumeajvb = editText;
        editText.setLayoutParams(new LinearLayout.LayoutParams(491, 1779));
        this.ldrumeajvb.setPadding(124, 197, 0, 26);
        linearLayout.addView(this.ldrumeajvb);
        this.ldrumeajvb.setBackgroundColor(Color.parseColor("#26c5d8"));
        FrameLayout frameLayout2 = new FrameLayout(this);
        this.qylqrtvvqc = frameLayout2;
        frameLayout2.setLayoutParams(new LinearLayout.LayoutParams(930, 1867));
        this.qylqrtvvqc.setPadding(149, 58, 37, 116);
        linearLayout.addView(this.qylqrtvvqc);
        this.qylqrtvvqc.setBackgroundColor(Color.parseColor("#d569af"));
        ViewFlipper viewFlipper5 = new ViewFlipper(this);
        this.rvjnvqettz = viewFlipper5;
        viewFlipper5.setLayoutParams(new LinearLayout.LayoutParams(471, 475));
        this.rvjnvqettz.setPadding(51, 40, 24, 129);
        linearLayout.addView(this.rvjnvqettz);
        this.rvjnvqettz.setBackgroundColor(Color.parseColor("#0522d6"));
        TableLayout tableLayout = new TableLayout(this);
        this.dsxsvhpyeq = tableLayout;
        tableLayout.setLayoutParams(new LinearLayout.LayoutParams(1790, 349));
        this.dsxsvhpyeq.setPadding(124, 187, 61, 144);
        linearLayout.addView(this.dsxsvhpyeq);
        this.dsxsvhpyeq.setBackgroundColor(Color.parseColor("#7d8a28"));
        Spinner spinner = new Spinner(this);
        this.qcgfnagcov = spinner;
        spinner.setLayoutParams(new LinearLayout.LayoutParams(281, 163));
        this.qcgfnagcov.setPadding(40, 199, 91, 193);
        linearLayout.addView(this.qcgfnagcov);
        this.qcgfnagcov.setBackgroundColor(Color.parseColor("#cc1940"));
        TextView textView2 = new TextView(this);
        this.fberklslgk = textView2;
        textView2.setLayoutParams(new LinearLayout.LayoutParams(232, 1451));
        this.fberklslgk.setPadding(28, 23, 96, 195);
        linearLayout.addView(this.fberklslgk);
        this.fberklslgk.setBackgroundColor(Color.parseColor("#596f36"));
        ProgressBar progressBar2 = new ProgressBar(this);
        this.igxnmdwifn = progressBar2;
        progressBar2.setLayoutParams(new LinearLayout.LayoutParams(392, 599));
        this.igxnmdwifn.setPadding(50, WebSocketProtocol.PAYLOAD_SHORT, 8, 152);
        linearLayout.addView(this.igxnmdwifn);
        this.igxnmdwifn.setBackgroundColor(Color.parseColor("#5edecd"));
        FrameLayout frameLayout3 = new FrameLayout(this);
        this.rhirwgdxps = frameLayout3;
        frameLayout3.setLayoutParams(new LinearLayout.LayoutParams(1516, 961));
        this.rhirwgdxps.setPadding(134, 30, 113, 42);
        linearLayout.addView(this.rhirwgdxps);
        this.rhirwgdxps.setBackgroundColor(Color.parseColor("#8c7c2e"));
        CheckBox checkBox4 = new CheckBox(this);
        this.yzrhlokrow = checkBox4;
        checkBox4.setLayoutParams(new LinearLayout.LayoutParams(964, 532));
        this.yzrhlokrow.setPadding(WebSocketProtocol.PAYLOAD_SHORT, 95, 165, 31);
        linearLayout.addView(this.yzrhlokrow);
        this.yzrhlokrow.setBackgroundColor(Color.parseColor("#e9c30f"));
        EditText editText2 = new EditText(this);
        this.azbfcrrlle = editText2;
        editText2.setLayoutParams(new LinearLayout.LayoutParams(1953, 1133));
        this.azbfcrrlle.setPadding(WebSocketProtocol.PAYLOAD_SHORT, 112, 14, 7);
        linearLayout.addView(this.azbfcrrlle);
        this.azbfcrrlle.setBackgroundColor(Color.parseColor("#c9ed2b"));
        EditText editText3 = new EditText(this);
        this.befdfygofo = editText3;
        editText3.setLayoutParams(new LinearLayout.LayoutParams(745, 520));
        this.befdfygofo.setPadding(78, 82, 135, 190);
        linearLayout.addView(this.befdfygofo);
        this.befdfygofo.setBackgroundColor(Color.parseColor("#4663b9"));
        ImageView imageView = new ImageView(this);
        this.kegroqpokb = imageView;
        imageView.setLayoutParams(new LinearLayout.LayoutParams(1606, 78));
        this.kegroqpokb.setPadding(146, 12, 29, 116);
        linearLayout.addView(this.kegroqpokb);
        this.kegroqpokb.setBackgroundColor(Color.parseColor("#aed4f9"));
        DatePicker datePicker2 = new DatePicker(this);
        this.rbjysvsaat = datePicker2;
        datePicker2.setLayoutParams(new LinearLayout.LayoutParams(1181, 1635));
        this.rbjysvsaat.setPadding(61, 103, 10, 41);
        linearLayout.addView(this.rbjysvsaat);
        this.rbjysvsaat.setBackgroundColor(Color.parseColor("#6aae51"));
        ListView listView2 = new ListView(this);
        this.vvqyaqtgva = listView2;
        listView2.setLayoutParams(new LinearLayout.LayoutParams(806, 358));
        this.vvqyaqtgva.setPadding(106, 17, 65, 166);
        linearLayout.addView(this.vvqyaqtgva);
        this.vvqyaqtgva.setBackgroundColor(Color.parseColor("#8a2ac0"));
        CheckBox checkBox5 = new CheckBox(this);
        this.wktcaotgda = checkBox5;
        checkBox5.setLayoutParams(new LinearLayout.LayoutParams(1184, 1273));
        this.wktcaotgda.setPadding(152, 199, 35, 183);
        linearLayout.addView(this.wktcaotgda);
        this.wktcaotgda.setBackgroundColor(Color.parseColor("#a23acd"));
        TimePicker timePicker2 = new TimePicker(this);
        this.qeczrwsfhm = timePicker2;
        timePicker2.setLayoutParams(new LinearLayout.LayoutParams(1014, 1480));
        this.qeczrwsfhm.setPadding(112, 108, 12, 3);
        linearLayout.addView(this.qeczrwsfhm);
        this.qeczrwsfhm.setBackgroundColor(Color.parseColor("#eac054"));
        ScrollView scrollView = new ScrollView(this);
        this.yjqtlmlcft = scrollView;
        scrollView.setLayoutParams(new LinearLayout.LayoutParams(922, 1518));
        this.yjqtlmlcft.setPadding(62, 7, 27, 190);
        linearLayout.addView(this.yjqtlmlcft);
        this.yjqtlmlcft.setBackgroundColor(Color.parseColor("#d222ce"));
        Switch r22 = new Switch(this);
        this.ylwhkattnb = r22;
        r22.setLayoutParams(new LinearLayout.LayoutParams(1524, 1067));
        this.ylwhkattnb.setPadding(120, 146, 165, 53);
        linearLayout.addView(this.ylwhkattnb);
        this.ylwhkattnb.setBackgroundColor(Color.parseColor("#b21b1c"));
        Spinner spinner2 = new Spinner(this);
        this.sumcyrblrg = spinner2;
        spinner2.setLayoutParams(new LinearLayout.LayoutParams(1215, 954));
        this.sumcyrblrg.setPadding(175, 165, 109, 184);
        linearLayout.addView(this.sumcyrblrg);
        this.sumcyrblrg.setBackgroundColor(Color.parseColor("#e00511"));
        Spinner spinner3 = new Spinner(this);
        this.ldjckqxpof = spinner3;
        spinner3.setLayoutParams(new LinearLayout.LayoutParams(1896, 1958));
        this.ldjckqxpof.setPadding(72, BDLocation.TypeServerDecryptError, 131, 46);
        linearLayout.addView(this.ldjckqxpof);
        this.ldjckqxpof.setBackgroundColor(Color.parseColor("#1f3719"));
        Button button2 = new Button(this);
        this.olpemejqbt = button2;
        button2.setLayoutParams(new LinearLayout.LayoutParams(1725, 1923));
        this.olpemejqbt.setPadding(38, 26, WebSocketProtocol.PAYLOAD_SHORT, 82);
        linearLayout.addView(this.olpemejqbt);
        this.olpemejqbt.setBackgroundColor(Color.parseColor("#e7527a"));
        RadioButton radioButton2 = new RadioButton(this);
        this.yciwwuaytt = radioButton2;
        radioButton2.setLayoutParams(new LinearLayout.LayoutParams(1238, 914));
        this.yciwwuaytt.setPadding(24, 140, 142, 131);
        linearLayout.addView(this.yciwwuaytt);
        this.yciwwuaytt.setBackgroundColor(Color.parseColor("#ab9292"));
        ImageView imageView2 = new ImageView(this);
        this.yhkldcfzuq = imageView2;
        imageView2.setLayoutParams(new LinearLayout.LayoutParams(1818, 742));
        this.yhkldcfzuq.setPadding(169, 23, BDLocation.TypeServerDecryptError, 0);
        linearLayout.addView(this.yhkldcfzuq);
        this.yhkldcfzuq.setBackgroundColor(Color.parseColor("#60c404"));
        RelativeLayout relativeLayout3 = new RelativeLayout(this);
        this.bdqqxvowpp = relativeLayout3;
        relativeLayout3.setLayoutParams(new LinearLayout.LayoutParams(9, 1948));
        this.bdqqxvowpp.setPadding(129, 21, 108, 26);
        linearLayout.addView(this.bdqqxvowpp);
        this.bdqqxvowpp.setBackgroundColor(Color.parseColor("#6cfbaf"));
        EditText editText4 = new EditText(this);
        this.xwmgofdpwf = editText4;
        editText4.setLayoutParams(new LinearLayout.LayoutParams(329, 1935));
        this.xwmgofdpwf.setPadding(198, 104, 140, 75);
        linearLayout.addView(this.xwmgofdpwf);
        this.xwmgofdpwf.setBackgroundColor(Color.parseColor("#bf399c"));
        RelativeLayout relativeLayout4 = new RelativeLayout(this);
        this.qnedvoecxl = relativeLayout4;
        relativeLayout4.setLayoutParams(new LinearLayout.LayoutParams(568, 1089));
        this.qnedvoecxl.setPadding(176, 186, 40, 76);
        linearLayout.addView(this.qnedvoecxl);
        this.qnedvoecxl.setBackgroundColor(Color.parseColor("#37f8d2"));
        DatePicker datePicker3 = new DatePicker(this);
        this.amtvccugdu = datePicker3;
        datePicker3.setLayoutParams(new LinearLayout.LayoutParams(1493, 1053));
        this.amtvccugdu.setPadding(143, 77, 102, PictureConfig.CHOOSE_REQUEST);
        linearLayout.addView(this.amtvccugdu);
        this.amtvccugdu.setBackgroundColor(Color.parseColor("#c13e7b"));
        GridView gridView3 = new GridView(this);
        this.wbdybmrgmm = gridView3;
        gridView3.setLayoutParams(new LinearLayout.LayoutParams(963, 1376));
        this.wbdybmrgmm.setPadding(BDLocation.TypeServerDecryptError, 25, 115, 36);
        linearLayout.addView(this.wbdybmrgmm);
        this.wbdybmrgmm.setBackgroundColor(Color.parseColor("#a5ee70"));
        RadioButton radioButton3 = new RadioButton(this);
        this.eraifatkfr = radioButton3;
        radioButton3.setLayoutParams(new LinearLayout.LayoutParams(451, 1327));
        this.eraifatkfr.setPadding(6, 180, 171, 111);
        linearLayout.addView(this.eraifatkfr);
        this.eraifatkfr.setBackgroundColor(Color.parseColor("#2433fa"));
        RelativeLayout relativeLayout5 = new RelativeLayout(this);
        this.dvfkrmzfpf = relativeLayout5;
        relativeLayout5.setLayoutParams(new LinearLayout.LayoutParams(1221, 1372));
        this.dvfkrmzfpf.setPadding(120, 52, 61, 78);
        linearLayout.addView(this.dvfkrmzfpf);
        this.dvfkrmzfpf.setBackgroundColor(Color.parseColor("#96b3de"));
        EditText editText5 = new EditText(this);
        this.isxzdvzhjs = editText5;
        editText5.setLayoutParams(new LinearLayout.LayoutParams(35, 490));
        this.isxzdvzhjs.setPadding(64, 121, 179, 41);
        linearLayout.addView(this.isxzdvzhjs);
        this.isxzdvzhjs.setBackgroundColor(Color.parseColor("#16eb3a"));
        FrameLayout frameLayout4 = new FrameLayout(this);
        this.hdvjfanlwj = frameLayout4;
        frameLayout4.setLayoutParams(new LinearLayout.LayoutParams(2, 792));
        this.hdvjfanlwj.setPadding(131, 39, 139, 114);
        linearLayout.addView(this.hdvjfanlwj);
        this.hdvjfanlwj.setBackgroundColor(Color.parseColor("#a6a02b"));
        ToggleButton toggleButton3 = new ToggleButton(this);
        this.czkhxhfyfx = toggleButton3;
        toggleButton3.setLayoutParams(new LinearLayout.LayoutParams(558, 466));
        this.czkhxhfyfx.setPadding(5, BDLocation.TypeServerError, 125, 75);
        linearLayout.addView(this.czkhxhfyfx);
        this.czkhxhfyfx.setBackgroundColor(Color.parseColor("#0c3a77"));
        GridView gridView4 = new GridView(this);
        this.uyliucmutj = gridView4;
        gridView4.setLayoutParams(new LinearLayout.LayoutParams(601, 1050));
        this.uyliucmutj.setPadding(40, 157, 146, 23);
        linearLayout.addView(this.uyliucmutj);
        this.uyliucmutj.setBackgroundColor(Color.parseColor("#e8440b"));
        TableLayout tableLayout2 = new TableLayout(this);
        this.ovpyoqamjh = tableLayout2;
        tableLayout2.setLayoutParams(new LinearLayout.LayoutParams(1495, 1037));
        this.ovpyoqamjh.setPadding(116, 92, 93, 157);
        linearLayout.addView(this.ovpyoqamjh);
        this.ovpyoqamjh.setBackgroundColor(Color.parseColor("#0cadc4"));
        Spinner spinner4 = new Spinner(this);
        this.xfcilhmlbm = spinner4;
        spinner4.setLayoutParams(new LinearLayout.LayoutParams(737, 457));
        this.xfcilhmlbm.setPadding(20, BDLocation.TypeServerError, 57, 81);
        linearLayout.addView(this.xfcilhmlbm);
        this.xfcilhmlbm.setBackgroundColor(Color.parseColor("#173713"));
        TableLayout tableLayout3 = new TableLayout(this);
        this.httzwvxqgg = tableLayout3;
        tableLayout3.setLayoutParams(new LinearLayout.LayoutParams(861, 1876));
        this.httzwvxqgg.setPadding(2, 90, 174, 101);
        linearLayout.addView(this.httzwvxqgg);
        this.httzwvxqgg.setBackgroundColor(Color.parseColor("#a808f1"));
        Spinner spinner5 = new Spinner(this);
        this.kamwljgyww = spinner5;
        spinner5.setLayoutParams(new LinearLayout.LayoutParams(478, 1183));
        this.kamwljgyww.setPadding(103, 173, 97, 36);
        linearLayout.addView(this.kamwljgyww);
        this.kamwljgyww.setBackgroundColor(Color.parseColor("#4eb114"));
        SeekBar seekBar3 = new SeekBar(this);
        this.acydfrklmx = seekBar3;
        seekBar3.setLayoutParams(new LinearLayout.LayoutParams(1334, 113));
        this.acydfrklmx.setPadding(106, 153, 32, 78);
        linearLayout.addView(this.acydfrklmx);
        this.acydfrklmx.setBackgroundColor(Color.parseColor("#60be47"));
        EditText editText6 = new EditText(this);
        this.iaxmqpeobl = editText6;
        editText6.setLayoutParams(new LinearLayout.LayoutParams(1148, 472));
        this.iaxmqpeobl.setPadding(92, 179, BDLocation.TypeServerError, BDLocation.TypeServerError);
        linearLayout.addView(this.iaxmqpeobl);
        this.iaxmqpeobl.setBackgroundColor(Color.parseColor("#c802ef"));
        ToggleButton toggleButton4 = new ToggleButton(this);
        this.kbjokjbswp = toggleButton4;
        toggleButton4.setLayoutParams(new LinearLayout.LayoutParams(1332, 626));
        this.kbjokjbswp.setPadding(92, 159, 58, 17);
        linearLayout.addView(this.kbjokjbswp);
        this.kbjokjbswp.setBackgroundColor(Color.parseColor("#4be433"));
        TableLayout tableLayout4 = new TableLayout(this);
        this.nnusuaddvn = tableLayout4;
        tableLayout4.setLayoutParams(new LinearLayout.LayoutParams(146, 1618));
        this.nnusuaddvn.setPadding(117, 23, 31, 58);
        linearLayout.addView(this.nnusuaddvn);
        this.nnusuaddvn.setBackgroundColor(Color.parseColor("#19d34a"));
        ListView listView3 = new ListView(this);
        this.etfjzgwdke = listView3;
        listView3.setLayoutParams(new LinearLayout.LayoutParams(1410, 966));
        this.etfjzgwdke.setPadding(170, 136, 191, 64);
        linearLayout.addView(this.etfjzgwdke);
        this.etfjzgwdke.setBackgroundColor(Color.parseColor("#f1d4b9"));
        ImageView imageView3 = new ImageView(this);
        this.lzriamvhdf = imageView3;
        imageView3.setLayoutParams(new LinearLayout.LayoutParams(463, 652));
        this.lzriamvhdf.setPadding(98, 118, 145, 17);
        linearLayout.addView(this.lzriamvhdf);
        this.lzriamvhdf.setBackgroundColor(Color.parseColor("#9a4dd5"));
        LinearLayout linearLayout3 = new LinearLayout(this);
        this.mysxxrfgzi = linearLayout3;
        linearLayout3.setLayoutParams(new LinearLayout.LayoutParams(22, 1756));
        this.mysxxrfgzi.setPadding(5, BDLocation.TypeServerError, 83, 71);
        linearLayout.addView(this.mysxxrfgzi);
        this.mysxxrfgzi.setBackgroundColor(Color.parseColor("#2cda72"));
        ImageView imageView4 = new ImageView(this);
        this.gkhclelmen = imageView4;
        imageView4.setLayoutParams(new LinearLayout.LayoutParams(110, PointerIconCompat.TYPE_TOP_RIGHT_DIAGONAL_DOUBLE_ARROW));
        this.gkhclelmen.setPadding(17, 35, 6, 55);
        linearLayout.addView(this.gkhclelmen);
        this.gkhclelmen.setBackgroundColor(Color.parseColor("#b97084"));
        CheckBox checkBox6 = new CheckBox(this);
        this.bbmqvrdpyb = checkBox6;
        checkBox6.setLayoutParams(new LinearLayout.LayoutParams(1391, 1863));
        this.bbmqvrdpyb.setPadding(34, 140, 134, 90);
        linearLayout.addView(this.bbmqvrdpyb);
        this.bbmqvrdpyb.setBackgroundColor(Color.parseColor("#d86daa"));
        ToggleButton toggleButton5 = new ToggleButton(this);
        this.kfkbxvciwd = toggleButton5;
        toggleButton5.setLayoutParams(new LinearLayout.LayoutParams(1765, 361));
        this.kfkbxvciwd.setPadding(78, 184, 122, 156);
        linearLayout.addView(this.kfkbxvciwd);
        this.kfkbxvciwd.setBackgroundColor(Color.parseColor("#3fc3ae"));
        EditText editText7 = new EditText(this);
        this.uxdcxipkme = editText7;
        editText7.setLayoutParams(new LinearLayout.LayoutParams(1190, 1245));
        this.uxdcxipkme.setPadding(50, 20, 166, 18);
        linearLayout.addView(this.uxdcxipkme);
        this.uxdcxipkme.setBackgroundColor(Color.parseColor("#958e69"));
        RelativeLayout relativeLayout6 = new RelativeLayout(this);
        this.tiykcfoajp = relativeLayout6;
        relativeLayout6.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.TransitionType.TYPE_AUTO_TRANSITION, 1926));
        this.tiykcfoajp.setPadding(139, 163, 19, 145);
        linearLayout.addView(this.tiykcfoajp);
        this.tiykcfoajp.setBackgroundColor(Color.parseColor("#a20346"));
        TimePicker timePicker3 = new TimePicker(this);
        this.jolhrsnxpb = timePicker3;
        timePicker3.setLayoutParams(new LinearLayout.LayoutParams(880, 1860));
        this.jolhrsnxpb.setPadding(12, 13, 16, 65);
        linearLayout.addView(this.jolhrsnxpb);
        this.jolhrsnxpb.setBackgroundColor(Color.parseColor("#bcf706"));
        ScrollView scrollView2 = new ScrollView(this);
        this.naputnpxhv = scrollView2;
        scrollView2.setLayoutParams(new LinearLayout.LayoutParams(1865, 1318));
        this.naputnpxhv.setPadding(7, 75, 199, 183);
        linearLayout.addView(this.naputnpxhv);
        this.naputnpxhv.setBackgroundColor(Color.parseColor("#0ca8ba"));
        GridView gridView5 = new GridView(this);
        this.rzeyzvpswl = gridView5;
        gridView5.setLayoutParams(new LinearLayout.LayoutParams(361, 1988));
        this.rzeyzvpswl.setPadding(59, 103, 78, 146);
        linearLayout.addView(this.rzeyzvpswl);
        this.rzeyzvpswl.setBackgroundColor(Color.parseColor("#c26dd4"));
        ScrollView scrollView3 = new ScrollView(this);
        this.hbnulwpkfl = scrollView3;
        scrollView3.setLayoutParams(new LinearLayout.LayoutParams(1953, 882));
        this.hbnulwpkfl.setPadding(82, 113, 176, 132);
        linearLayout.addView(this.hbnulwpkfl);
        this.hbnulwpkfl.setBackgroundColor(Color.parseColor("#050ed0"));
        ToggleButton toggleButton6 = new ToggleButton(this);
        this.auxzqkhndh = toggleButton6;
        toggleButton6.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.Custom.TYPE_REFERENCE, 1416));
        this.auxzqkhndh.setPadding(125, 140, 80, 74);
        linearLayout.addView(this.auxzqkhndh);
        this.auxzqkhndh.setBackgroundColor(Color.parseColor("#39583b"));
        RelativeLayout relativeLayout7 = new RelativeLayout(this);
        this.zrmvyxprks = relativeLayout7;
        relativeLayout7.setLayoutParams(new LinearLayout.LayoutParams(GattClient.STATE_PREPARE_PAIRING_REQUEST, 1159));
        this.zrmvyxprks.setPadding(174, 49, BDLocation.TypeServerDecryptError, BDLocation.TypeServerError);
        linearLayout.addView(this.zrmvyxprks);
        this.zrmvyxprks.setBackgroundColor(Color.parseColor("#2819c0"));
        ListView listView4 = new ListView(this);
        this.rhchevwdxb = listView4;
        listView4.setLayoutParams(new LinearLayout.LayoutParams(1266, 1454));
        this.rhchevwdxb.setPadding(48, 10, 46, 122);
        linearLayout.addView(this.rhchevwdxb);
        this.rhchevwdxb.setBackgroundColor(Color.parseColor("#831c95"));
        Switch r23 = new Switch(this);
        this.xlbszlypov = r23;
        r23.setLayoutParams(new LinearLayout.LayoutParams(GattClient.STATE_READ_BATTERY_INFO, 1730));
        this.xlbszlypov.setPadding(182, 70, 106, 56);
        linearLayout.addView(this.xlbszlypov);
        this.xlbszlypov.setBackgroundColor(Color.parseColor("#bf57bd"));
        TimePicker timePicker4 = new TimePicker(this);
        this.ydxmfglymi = timePicker4;
        timePicker4.setLayoutParams(new LinearLayout.LayoutParams(415, 1923));
        this.ydxmfglymi.setPadding(102, 77, 59, 27);
        linearLayout.addView(this.ydxmfglymi);
        this.ydxmfglymi.setBackgroundColor(Color.parseColor("#5644a6"));
        TimePicker timePicker5 = new TimePicker(this);
        this.jwskqiomeb = timePicker5;
        timePicker5.setLayoutParams(new LinearLayout.LayoutParams(1402, TypedValues.TransitionType.TYPE_STAGGERED));
        this.jwskqiomeb.setPadding(121, 66, 152, 129);
        linearLayout.addView(this.jwskqiomeb);
        this.jwskqiomeb.setBackgroundColor(Color.parseColor("#21e89a"));
        EditText editText8 = new EditText(this);
        this.kiwqxycbzv = editText8;
        editText8.setLayoutParams(new LinearLayout.LayoutParams(453, 1496));
        this.kiwqxycbzv.setPadding(9, 38, 170, 121);
        linearLayout.addView(this.kiwqxycbzv);
        this.kiwqxycbzv.setBackgroundColor(Color.parseColor("#0b8f35"));
        ListView listView5 = new ListView(this);
        this.kzlluxnatm = listView5;
        listView5.setLayoutParams(new LinearLayout.LayoutParams(291, 218));
        this.kzlluxnatm.setPadding(6, 92, 196, 152);
        linearLayout.addView(this.kzlluxnatm);
        this.kzlluxnatm.setBackgroundColor(Color.parseColor("#0a370e"));
        RadioButton radioButton4 = new RadioButton(this);
        this.pjetsenwwn = radioButton4;
        radioButton4.setLayoutParams(new LinearLayout.LayoutParams(1299, 1441));
        this.pjetsenwwn.setPadding(54, 24, 131, 193);
        linearLayout.addView(this.pjetsenwwn);
        this.pjetsenwwn.setBackgroundColor(Color.parseColor("#86b713"));
        LinearLayout linearLayout4 = new LinearLayout(this);
        this.bampsmvvsu = linearLayout4;
        linearLayout4.setLayoutParams(new LinearLayout.LayoutParams(1710, 1517));
        this.bampsmvvsu.setPadding(120, 113, 98, 123);
        linearLayout.addView(this.bampsmvvsu);
        this.bampsmvvsu.setBackgroundColor(Color.parseColor("#86ec2c"));
        Switch r24 = new Switch(this);
        this.msyzfvyvvq = r24;
        r24.setLayoutParams(new LinearLayout.LayoutParams(803, 1633));
        this.msyzfvyvvq.setPadding(132, 133, 78, 156);
        linearLayout.addView(this.msyzfvyvvq);
        this.msyzfvyvvq.setBackgroundColor(Color.parseColor("#cca978"));
        EditText editText9 = new EditText(this);
        this.rlzpzwheap = editText9;
        editText9.setLayoutParams(new LinearLayout.LayoutParams(1914, 481));
        this.rlzpzwheap.setPadding(58, 69, 65, 179);
        linearLayout.addView(this.rlzpzwheap);
        this.rlzpzwheap.setBackgroundColor(Color.parseColor("#2c68b5"));
        TextView textView3 = new TextView(this);
        this.mknpfuzvfj = textView3;
        textView3.setLayoutParams(new LinearLayout.LayoutParams(1434, 1919));
        this.mknpfuzvfj.setPadding(140, 94, 173, BDLocation.TypeServerDecryptError);
        linearLayout.addView(this.mknpfuzvfj);
        this.mknpfuzvfj.setBackgroundColor(Color.parseColor("#1e2d62"));
        EditText editText10 = new EditText(this);
        this.fpvdbskmkx = editText10;
        editText10.setLayoutParams(new LinearLayout.LayoutParams(142, 813));
        this.fpvdbskmkx.setPadding(170, 127, 70, 58);
        linearLayout.addView(this.fpvdbskmkx);
        this.fpvdbskmkx.setBackgroundColor(Color.parseColor("#50be86"));
        Switch r25 = new Switch(this);
        this.avxymvtetc = r25;
        r25.setLayoutParams(new LinearLayout.LayoutParams(163, 1253));
        this.avxymvtetc.setPadding(98, 145, PictureConfig.CHOOSE_REQUEST, 169);
        linearLayout.addView(this.avxymvtetc);
        this.avxymvtetc.setBackgroundColor(Color.parseColor("#5ebda9"));
        ToggleButton toggleButton7 = new ToggleButton(this);
        this.yynfqejhdm = toggleButton7;
        toggleButton7.setLayoutParams(new LinearLayout.LayoutParams(1599, 908));
        this.yynfqejhdm.setPadding(9, 64, 140, 125);
        linearLayout.addView(this.yynfqejhdm);
        this.yynfqejhdm.setBackgroundColor(Color.parseColor("#09b385"));
        ImageView imageView5 = new ImageView(this);
        this.duxkmnlsqz = imageView5;
        imageView5.setLayoutParams(new LinearLayout.LayoutParams(118, 1276));
        this.duxkmnlsqz.setPadding(169, 129, 11, 68);
        linearLayout.addView(this.duxkmnlsqz);
        this.duxkmnlsqz.setBackgroundColor(Color.parseColor("#9ac18c"));
        SeekBar seekBar4 = new SeekBar(this);
        this.szsvkmzube = seekBar4;
        seekBar4.setLayoutParams(new LinearLayout.LayoutParams(1607, 1496));
        this.szsvkmzube.setPadding(104, 133, 79, 76);
        linearLayout.addView(this.szsvkmzube);
        this.szsvkmzube.setBackgroundColor(Color.parseColor("#4ee5b4"));
        ProgressBar progressBar3 = new ProgressBar(this);
        this.lvjcfmfdpw = progressBar3;
        progressBar3.setLayoutParams(new LinearLayout.LayoutParams(246, 1569));
        this.lvjcfmfdpw.setPadding(153, 2, 49, 4);
        linearLayout.addView(this.lvjcfmfdpw);
        this.lvjcfmfdpw.setBackgroundColor(Color.parseColor("#ece143"));
        TableLayout tableLayout5 = new TableLayout(this);
        this.uvyhpwabgf = tableLayout5;
        tableLayout5.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.TransitionType.TYPE_TO, 672));
        this.uvyhpwabgf.setPadding(171, 49, 146, 182);
        linearLayout.addView(this.uvyhpwabgf);
        this.uvyhpwabgf.setBackgroundColor(Color.parseColor("#9caa2c"));
        DatePicker datePicker4 = new DatePicker(this);
        this.cvdlklebln = datePicker4;
        datePicker4.setLayoutParams(new LinearLayout.LayoutParams(1005, 1652));
        this.cvdlklebln.setPadding(148, 3, 185, 100);
        linearLayout.addView(this.cvdlklebln);
        this.cvdlklebln.setBackgroundColor(Color.parseColor("#92b383"));
        RatingBar ratingBar4 = new RatingBar(this);
        this.nxfatrbsyh = ratingBar4;
        ratingBar4.setLayoutParams(new LinearLayout.LayoutParams(1891, 1699));
        this.nxfatrbsyh.setPadding(152, 5, 191, 54);
        linearLayout.addView(this.nxfatrbsyh);
        this.nxfatrbsyh.setBackgroundColor(Color.parseColor("#5a969c"));
        GridView gridView6 = new GridView(this);
        this.lphaspfilt = gridView6;
        gridView6.setLayoutParams(new LinearLayout.LayoutParams(1392, 693));
        this.lphaspfilt.setPadding(146, 51, 96, 141);
        linearLayout.addView(this.lphaspfilt);
        this.lphaspfilt.setBackgroundColor(Color.parseColor("#945c22"));
        ToggleButton toggleButton8 = new ToggleButton(this);
        this.dfahwkfftg = toggleButton8;
        toggleButton8.setLayoutParams(new LinearLayout.LayoutParams(1330, 18));
        this.dfahwkfftg.setPadding(7, 169, 182, 137);
        linearLayout.addView(this.dfahwkfftg);
        this.dfahwkfftg.setBackgroundColor(Color.parseColor("#ee4e6d"));
        GridView gridView7 = new GridView(this);
        this.qtchzdbhmw = gridView7;
        gridView7.setLayoutParams(new LinearLayout.LayoutParams(1888, 1638));
        this.qtchzdbhmw.setPadding(83, 173, 75, 150);
        linearLayout.addView(this.qtchzdbhmw);
        this.qtchzdbhmw.setBackgroundColor(Color.parseColor("#e1fb54"));
        ProgressBar progressBar4 = new ProgressBar(this);
        this.aysvzpmxnr = progressBar4;
        progressBar4.setLayoutParams(new LinearLayout.LayoutParams(206, 1283));
        this.aysvzpmxnr.setPadding(129, 185, 187, 30);
        linearLayout.addView(this.aysvzpmxnr);
        this.aysvzpmxnr.setBackgroundColor(Color.parseColor("#261790"));
        SeekBar seekBar5 = new SeekBar(this);
        this.wojwsxqoqn = seekBar5;
        seekBar5.setLayoutParams(new LinearLayout.LayoutParams(1109, 348));
        this.wojwsxqoqn.setPadding(164, 36, 44, 168);
        linearLayout.addView(this.wojwsxqoqn);
        this.wojwsxqoqn.setBackgroundColor(Color.parseColor("#9dec26"));
        DatePicker datePicker5 = new DatePicker(this);
        this.rcjbwbpzwu = datePicker5;
        datePicker5.setLayoutParams(new LinearLayout.LayoutParams(1238, 1034));
        this.rcjbwbpzwu.setPadding(124, 185, 43, 101);
        linearLayout.addView(this.rcjbwbpzwu);
        this.rcjbwbpzwu.setBackgroundColor(Color.parseColor("#58a07b"));
        CheckBox checkBox7 = new CheckBox(this);
        this.ucjnuiqkgv = checkBox7;
        checkBox7.setLayoutParams(new LinearLayout.LayoutParams(516, 670));
        this.ucjnuiqkgv.setPadding(143, 152, 100, 26);
        linearLayout.addView(this.ucjnuiqkgv);
        this.ucjnuiqkgv.setBackgroundColor(Color.parseColor("#311e6e"));
        SeekBar seekBar6 = new SeekBar(this);
        this.fjghvctxol = seekBar6;
        seekBar6.setLayoutParams(new LinearLayout.LayoutParams(931, 31));
        this.fjghvctxol.setPadding(13, 169, 78, 97);
        linearLayout.addView(this.fjghvctxol);
        this.fjghvctxol.setBackgroundColor(Color.parseColor("#1d553d"));
        ImageView imageView6 = new ImageView(this);
        this.hxsaksfrjw = imageView6;
        imageView6.setLayoutParams(new LinearLayout.LayoutParams(1641, 1445));
        this.hxsaksfrjw.setPadding(54, 32, 17, 10);
        linearLayout.addView(this.hxsaksfrjw);
        this.hxsaksfrjw.setBackgroundColor(Color.parseColor("#78f9c4"));
        GridView gridView8 = new GridView(this);
        this.eogqijejtd = gridView8;
        gridView8.setLayoutParams(new LinearLayout.LayoutParams(1207, 1483));
        this.eogqijejtd.setPadding(187, 3, 157, 190);
        linearLayout.addView(this.eogqijejtd);
        this.eogqijejtd.setBackgroundColor(Color.parseColor("#473d85"));
        LinearLayout linearLayout5 = new LinearLayout(this);
        this.leqixbpejb = linearLayout5;
        linearLayout5.setLayoutParams(new LinearLayout.LayoutParams(556, TypedValues.PositionType.TYPE_PERCENT_Y));
        this.leqixbpejb.setPadding(135, 151, 192, 196);
        linearLayout.addView(this.leqixbpejb);
        this.leqixbpejb.setBackgroundColor(Color.parseColor("#78af8d"));
        LinearLayout linearLayout6 = new LinearLayout(this);
        this.fodmendiiv = linearLayout6;
        linearLayout6.setLayoutParams(new LinearLayout.LayoutParams(1230, 1931));
        this.fodmendiiv.setPadding(121, 96, 100, 29);
        linearLayout.addView(this.fodmendiiv);
        this.fodmendiiv.setBackgroundColor(Color.parseColor("#44fc5e"));
        FrameLayout frameLayout5 = new FrameLayout(this);
        this.lqydntgedx = frameLayout5;
        frameLayout5.setLayoutParams(new LinearLayout.LayoutParams(254, 381));
        this.lqydntgedx.setPadding(16, BDLocation.TypeCoarseLocation, 90, 145);
        linearLayout.addView(this.lqydntgedx);
        this.lqydntgedx.setBackgroundColor(Color.parseColor("#8b1c5c"));
        ListView listView6 = new ListView(this);
        this.jbxwwjyiff = listView6;
        listView6.setLayoutParams(new LinearLayout.LayoutParams(975, 11));
        this.jbxwwjyiff.setPadding(187, 159, 103, 28);
        linearLayout.addView(this.jbxwwjyiff);
        this.jbxwwjyiff.setBackgroundColor(Color.parseColor("#9a2c46"));
        CheckBox checkBox8 = new CheckBox(this);
        this.vdonjugvtb = checkBox8;
        checkBox8.setLayoutParams(new LinearLayout.LayoutParams(1979, 762));
        this.vdonjugvtb.setPadding(83, 74, 106, 10);
        linearLayout.addView(this.vdonjugvtb);
        this.vdonjugvtb.setBackgroundColor(Color.parseColor("#fff45b"));
        LinearLayout linearLayout7 = new LinearLayout(this);
        this.nzkocthqln = linearLayout7;
        linearLayout7.setLayoutParams(new LinearLayout.LayoutParams(267, 381));
        this.nzkocthqln.setPadding(158, 47, 119, 7);
        linearLayout.addView(this.nzkocthqln);
        this.nzkocthqln.setBackgroundColor(Color.parseColor("#647c60"));
        ProgressBar progressBar5 = new ProgressBar(this);
        this.rtlgkognev = progressBar5;
        progressBar5.setLayoutParams(new LinearLayout.LayoutParams(1160, 626));
        this.rtlgkognev.setPadding(154, 181, 20, 75);
        linearLayout.addView(this.rtlgkognev);
        this.rtlgkognev.setBackgroundColor(Color.parseColor("#d7cbd6"));
        GridView gridView9 = new GridView(this);
        this.wszoczlxyr = gridView9;
        gridView9.setLayoutParams(new LinearLayout.LayoutParams(1563, 433));
        this.wszoczlxyr.setPadding(11, 137, 165, 18);
        linearLayout.addView(this.wszoczlxyr);
        this.wszoczlxyr.setBackgroundColor(Color.parseColor("#509dd8"));
        SeekBar seekBar7 = new SeekBar(this);
        this.hpfbystman = seekBar7;
        seekBar7.setLayoutParams(new LinearLayout.LayoutParams(1493, 1319));
        this.hpfbystman.setPadding(50, 35, 22, 170);
        linearLayout.addView(this.hpfbystman);
        this.hpfbystman.setBackgroundColor(Color.parseColor("#a8386e"));
        LinearLayout linearLayout8 = new LinearLayout(this);
        this.jkymciluyk = linearLayout8;
        linearLayout8.setLayoutParams(new LinearLayout.LayoutParams(740, 1579));
        this.jkymciluyk.setPadding(59, 104, 60, 116);
        linearLayout.addView(this.jkymciluyk);
        this.jkymciluyk.setBackgroundColor(Color.parseColor("#b44ad4"));
        CheckBox checkBox9 = new CheckBox(this);
        this.bertgdbtne = checkBox9;
        checkBox9.setLayoutParams(new LinearLayout.LayoutParams(1884, 352));
        this.bertgdbtne.setPadding(178, 17, 9, 181);
        linearLayout.addView(this.bertgdbtne);
        this.bertgdbtne.setBackgroundColor(Color.parseColor("#5d8768"));
        LinearLayout linearLayout9 = new LinearLayout(this);
        this.hhrtpjogtm = linearLayout9;
        linearLayout9.setLayoutParams(new LinearLayout.LayoutParams(1621, 737));
        this.hhrtpjogtm.setPadding(10, 81, 10, 183);
        linearLayout.addView(this.hhrtpjogtm);
        this.hhrtpjogtm.setBackgroundColor(Color.parseColor("#3ead9d"));
        ProgressBar progressBar6 = new ProgressBar(this);
        this.zehijsytto = progressBar6;
        progressBar6.setLayoutParams(new LinearLayout.LayoutParams(382, 1042));
        this.zehijsytto.setPadding(147, 124, 87, 96);
        linearLayout.addView(this.zehijsytto);
        this.zehijsytto.setBackgroundColor(Color.parseColor("#901da0"));
        RatingBar ratingBar5 = new RatingBar(this);
        this.tbcihzcagz = ratingBar5;
        ratingBar5.setLayoutParams(new LinearLayout.LayoutParams(1238, 42));
        this.tbcihzcagz.setPadding(127, 3, 31, 44);
        linearLayout.addView(this.tbcihzcagz);
        this.tbcihzcagz.setBackgroundColor(Color.parseColor("#2ca6ed"));
        ToggleButton toggleButton9 = new ToggleButton(this);
        this.exyzqdzymj = toggleButton9;
        toggleButton9.setLayoutParams(new LinearLayout.LayoutParams(235, 1558));
        this.exyzqdzymj.setPadding(144, 141, 68, 85);
        linearLayout.addView(this.exyzqdzymj);
        this.exyzqdzymj.setBackgroundColor(Color.parseColor("#5fbeba"));
        CheckBox checkBox10 = new CheckBox(this);
        this.itqjxqzvse = checkBox10;
        checkBox10.setLayoutParams(new LinearLayout.LayoutParams(186, CodeUtils.DEFAULT_REQ_WIDTH));
        this.itqjxqzvse.setPadding(121, 192, 74, 144);
        linearLayout.addView(this.itqjxqzvse);
        this.itqjxqzvse.setBackgroundColor(Color.parseColor("#a9292b"));
        Button button3 = new Button(this);
        this.tauatcpxdl = button3;
        button3.setLayoutParams(new LinearLayout.LayoutParams(745, 1767));
        this.tauatcpxdl.setPadding(183, 53, 0, 139);
        linearLayout.addView(this.tauatcpxdl);
        this.tauatcpxdl.setBackgroundColor(Color.parseColor("#0c2f02"));
        ImageView imageView7 = new ImageView(this);
        this.pekgbpdyui = imageView7;
        imageView7.setLayoutParams(new LinearLayout.LayoutParams(1372, 1824));
        this.pekgbpdyui.setPadding(114, 195, 57, 89);
        linearLayout.addView(this.pekgbpdyui);
        this.pekgbpdyui.setBackgroundColor(Color.parseColor("#026b24"));
        GridView gridView10 = new GridView(this);
        this.czjdpromuo = gridView10;
        gridView10.setLayoutParams(new LinearLayout.LayoutParams(1467, 305));
        this.czjdpromuo.setPadding(189, 99, 123, 48);
        linearLayout.addView(this.czjdpromuo);
        this.czjdpromuo.setBackgroundColor(Color.parseColor("#4158d4"));
        LinearLayout linearLayout10 = new LinearLayout(this);
        this.vknuleoghx = linearLayout10;
        linearLayout10.setLayoutParams(new LinearLayout.LayoutParams(708, 1686));
        this.vknuleoghx.setPadding(47, 1, 57, 106);
        linearLayout.addView(this.vknuleoghx);
        this.vknuleoghx.setBackgroundColor(Color.parseColor("#df86ac"));
        RadioButton radioButton5 = new RadioButton(this);
        this.lctjhpxtdg = radioButton5;
        radioButton5.setLayoutParams(new LinearLayout.LayoutParams(970, 355));
        this.lctjhpxtdg.setPadding(164, 34, 86, 191);
        linearLayout.addView(this.lctjhpxtdg);
        this.lctjhpxtdg.setBackgroundColor(Color.parseColor("#f06b74"));
        ViewFlipper viewFlipper6 = new ViewFlipper(this);
        this.bjijepcllq = viewFlipper6;
        viewFlipper6.setLayoutParams(new LinearLayout.LayoutParams(225, 1426));
        this.bjijepcllq.setPadding(156, 17, 88, 164);
        linearLayout.addView(this.bjijepcllq);
        this.bjijepcllq.setBackgroundColor(Color.parseColor("#117c8f"));
        ViewFlipper viewFlipper7 = new ViewFlipper(this);
        this.nxkyjoxoye = viewFlipper7;
        viewFlipper7.setLayoutParams(new LinearLayout.LayoutParams(877, 1598));
        this.nxkyjoxoye.setPadding(159, 84, 47, 180);
        linearLayout.addView(this.nxkyjoxoye);
        this.nxkyjoxoye.setBackgroundColor(Color.parseColor("#ebbe5c"));
        RadioButton radioButton6 = new RadioButton(this);
        this.kgdovzjhxq = radioButton6;
        radioButton6.setLayoutParams(new LinearLayout.LayoutParams(1967, 117));
        this.kgdovzjhxq.setPadding(194, 172, 153, 91);
        linearLayout.addView(this.kgdovzjhxq);
        this.kgdovzjhxq.setBackgroundColor(Color.parseColor("#3af01e"));
        RadioButton radioButton7 = new RadioButton(this);
        this.biiyjpumnc = radioButton7;
        radioButton7.setLayoutParams(new LinearLayout.LayoutParams(1828, 1605));
        this.biiyjpumnc.setPadding(146, 90, 187, 3);
        linearLayout.addView(this.biiyjpumnc);
        this.biiyjpumnc.setBackgroundColor(Color.parseColor("#c407f0"));
        RelativeLayout relativeLayout8 = new RelativeLayout(this);
        this.mttovoelao = relativeLayout8;
        relativeLayout8.setLayoutParams(new LinearLayout.LayoutParams(1697, 37));
        this.mttovoelao.setPadding(4, 14, 70, 95);
        linearLayout.addView(this.mttovoelao);
        this.mttovoelao.setBackgroundColor(Color.parseColor("#d691cb"));
        DatePicker datePicker6 = new DatePicker(this);
        this.wukqveeovr = datePicker6;
        datePicker6.setLayoutParams(new LinearLayout.LayoutParams(1511, 1404));
        this.wukqveeovr.setPadding(93, 186, 36, 53);
        linearLayout.addView(this.wukqveeovr);
        this.wukqveeovr.setBackgroundColor(Color.parseColor("#3a1b9b"));
        FrameLayout frameLayout6 = new FrameLayout(this);
        this.ycaocyrjur = frameLayout6;
        frameLayout6.setLayoutParams(new LinearLayout.LayoutParams(1751, 726));
        this.ycaocyrjur.setPadding(124, 123, 30, 97);
        linearLayout.addView(this.ycaocyrjur);
        this.ycaocyrjur.setBackgroundColor(Color.parseColor("#2f3fac"));
        ListView listView7 = new ListView(this);
        this.jezeqevzqx = listView7;
        listView7.setLayoutParams(new LinearLayout.LayoutParams(1866, 1210));
        this.jezeqevzqx.setPadding(113, 152, 124, 196);
        linearLayout.addView(this.jezeqevzqx);
        this.jezeqevzqx.setBackgroundColor(Color.parseColor("#de2f33"));
        TimePicker timePicker6 = new TimePicker(this);
        this.dkmysigdnf = timePicker6;
        timePicker6.setLayoutParams(new LinearLayout.LayoutParams(1080, 1152));
        this.dkmysigdnf.setPadding(193, 92, 0, 187);
        linearLayout.addView(this.dkmysigdnf);
        this.dkmysigdnf.setBackgroundColor(Color.parseColor("#14c1b0"));
        RadioButton radioButton8 = new RadioButton(this);
        this.qqntnnpzbj = radioButton8;
        radioButton8.setLayoutParams(new LinearLayout.LayoutParams(1690, 791));
        this.qqntnnpzbj.setPadding(24, 150, 158, 123);
        linearLayout.addView(this.qqntnnpzbj);
        this.qqntnnpzbj.setBackgroundColor(Color.parseColor("#e79dea"));
        FrameLayout frameLayout7 = new FrameLayout(this);
        this.sbiqluyioe = frameLayout7;
        frameLayout7.setLayoutParams(new LinearLayout.LayoutParams(1655, 892));
        this.sbiqluyioe.setPadding(163, 121, 60, 9);
        linearLayout.addView(this.sbiqluyioe);
        this.sbiqluyioe.setBackgroundColor(Color.parseColor("#33161a"));
        CheckBox checkBox11 = new CheckBox(this);
        this.ttoqxdaskf = checkBox11;
        checkBox11.setLayoutParams(new LinearLayout.LayoutParams(1776, 1998));
        this.ttoqxdaskf.setPadding(136, 93, 179, 135);
        linearLayout.addView(this.ttoqxdaskf);
        this.ttoqxdaskf.setBackgroundColor(Color.parseColor("#404482"));
        LinearLayout linearLayout11 = new LinearLayout(this);
        this.xltpzswtdv = linearLayout11;
        linearLayout11.setLayoutParams(new LinearLayout.LayoutParams(1921, 1719));
        this.xltpzswtdv.setPadding(139, 165, 31, 26);
        linearLayout.addView(this.xltpzswtdv);
        this.xltpzswtdv.setBackgroundColor(Color.parseColor("#81e542"));
        TimePicker timePicker7 = new TimePicker(this);
        this.zznznakhcu = timePicker7;
        timePicker7.setLayoutParams(new LinearLayout.LayoutParams(428, 781));
        this.zznznakhcu.setPadding(111, 194, BDLocation.TypeNetWorkLocation, BDLocation.TypeNetWorkLocation);
        linearLayout.addView(this.zznznakhcu);
        this.zznznakhcu.setBackgroundColor(Color.parseColor("#21d551"));
        Switch r26 = new Switch(this);
        this.puamslqncy = r26;
        r26.setLayoutParams(new LinearLayout.LayoutParams(843, 254));
        this.puamslqncy.setPadding(134, 69, 151, 96);
        linearLayout.addView(this.puamslqncy);
        this.puamslqncy.setBackgroundColor(Color.parseColor("#d19dda"));
        GridView gridView11 = new GridView(this);
        this.eckxwkgpes = gridView11;
        gridView11.setLayoutParams(new LinearLayout.LayoutParams(1514, 1617));
        this.eckxwkgpes.setPadding(198, 115, 116, 154);
        linearLayout.addView(this.eckxwkgpes);
        this.eckxwkgpes.setBackgroundColor(Color.parseColor("#dc599a"));
        GridView gridView12 = new GridView(this);
        this.wetfraaoqc = gridView12;
        gridView12.setLayoutParams(new LinearLayout.LayoutParams(1110, 368));
        this.wetfraaoqc.setPadding(98, 121, 177, 45);
        linearLayout.addView(this.wetfraaoqc);
        this.wetfraaoqc.setBackgroundColor(Color.parseColor("#fb4fad"));
        RadioButton radioButton9 = new RadioButton(this);
        this.pzbneykttd = radioButton9;
        radioButton9.setLayoutParams(new LinearLayout.LayoutParams(1167, 1979));
        this.pzbneykttd.setPadding(9, 168, 192, 118);
        linearLayout.addView(this.pzbneykttd);
        this.pzbneykttd.setBackgroundColor(Color.parseColor("#fda80c"));
        FrameLayout frameLayout8 = new FrameLayout(this);
        this.mgjahiutmm = frameLayout8;
        frameLayout8.setLayoutParams(new LinearLayout.LayoutParams(350, 112));
        this.mgjahiutmm.setPadding(158, 154, 25, 141);
        linearLayout.addView(this.mgjahiutmm);
        this.mgjahiutmm.setBackgroundColor(Color.parseColor("#706621"));
        LinearLayout linearLayout12 = new LinearLayout(this);
        this.qerycsfooz = linearLayout12;
        linearLayout12.setLayoutParams(new LinearLayout.LayoutParams(634, 1775));
        this.qerycsfooz.setPadding(148, 59, 139, 179);
        linearLayout.addView(this.qerycsfooz);
        this.qerycsfooz.setBackgroundColor(Color.parseColor("#6bad33"));
        ImageView imageView8 = new ImageView(this);
        this.yuwvlincfb = imageView8;
        imageView8.setLayoutParams(new LinearLayout.LayoutParams(229, 1617));
        this.yuwvlincfb.setPadding(100, 75, 137, 31);
        linearLayout.addView(this.yuwvlincfb);
        this.yuwvlincfb.setBackgroundColor(Color.parseColor("#962a29"));
        TimePicker timePicker8 = new TimePicker(this);
        this.mphnpnyths = timePicker8;
        timePicker8.setLayoutParams(new LinearLayout.LayoutParams(198, 1648));
        this.mphnpnyths.setPadding(86, 0, 6, 47);
        linearLayout.addView(this.mphnpnyths);
        this.mphnpnyths.setBackgroundColor(Color.parseColor("#b52a66"));
        ListView listView8 = new ListView(this);
        this.kndvxpgigl = listView8;
        listView8.setLayoutParams(new LinearLayout.LayoutParams(1595, TypedValues.CycleType.TYPE_WAVE_PHASE));
        this.kndvxpgigl.setPadding(153, 25, 22, 11);
        linearLayout.addView(this.kndvxpgigl);
        this.kndvxpgigl.setBackgroundColor(Color.parseColor("#8845a9"));
        CheckBox checkBox12 = new CheckBox(this);
        this.jwqzowcfzd = checkBox12;
        checkBox12.setLayoutParams(new LinearLayout.LayoutParams(1798, 1637));
        this.jwqzowcfzd.setPadding(144, 94, 43, 142);
        linearLayout.addView(this.jwqzowcfzd);
        this.jwqzowcfzd.setBackgroundColor(Color.parseColor("#bc0e3c"));
        ListView listView9 = new ListView(this);
        this.bfrcttxtts = listView9;
        listView9.setLayoutParams(new LinearLayout.LayoutParams(1160, 943));
        this.bfrcttxtts.setPadding(74, 68, 57, 54);
        linearLayout.addView(this.bfrcttxtts);
        this.bfrcttxtts.setBackgroundColor(Color.parseColor("#6e5ee1"));
        DatePicker datePicker7 = new DatePicker(this);
        this.khfhkkfhis = datePicker7;
        datePicker7.setLayoutParams(new LinearLayout.LayoutParams(262, 1048));
        this.khfhkkfhis.setPadding(38, 141, 23, 90);
        linearLayout.addView(this.khfhkkfhis);
        this.khfhkkfhis.setBackgroundColor(Color.parseColor("#9f58b9"));
        TimePicker timePicker9 = new TimePicker(this);
        this.yzxonlwnvr = timePicker9;
        timePicker9.setLayoutParams(new LinearLayout.LayoutParams(271, 1326));
        this.yzxonlwnvr.setPadding(16, 100, 107, 114);
        linearLayout.addView(this.yzxonlwnvr);
        this.yzxonlwnvr.setBackgroundColor(Color.parseColor("#7fa073"));
        Spinner spinner6 = new Spinner(this);
        this.acunfbkilc = spinner6;
        spinner6.setLayoutParams(new LinearLayout.LayoutParams(415, Contract.CMD_SET_VERSION.V1_2));
        this.acunfbkilc.setPadding(163, 86, 96, 58);
        linearLayout.addView(this.acunfbkilc);
        this.acunfbkilc.setBackgroundColor(Color.parseColor("#ba9da5"));
        ImageView imageView9 = new ImageView(this);
        this.nhvnsqcjlg = imageView9;
        imageView9.setLayoutParams(new LinearLayout.LayoutParams(1836, 1120));
        this.nhvnsqcjlg.setPadding(123, 109, 182, 88);
        linearLayout.addView(this.nhvnsqcjlg);
        this.nhvnsqcjlg.setBackgroundColor(Color.parseColor("#2b4c0e"));
        FrameLayout frameLayout9 = new FrameLayout(this);
        this.biujbxbshj = frameLayout9;
        frameLayout9.setLayoutParams(new LinearLayout.LayoutParams(306, 961));
        this.biujbxbshj.setPadding(BDLocation.TypeServerError, 159, BDLocation.TypeServerError, 132);
        linearLayout.addView(this.biujbxbshj);
        this.biujbxbshj.setBackgroundColor(Color.parseColor("#f71ca9"));
        Spinner spinner7 = new Spinner(this);
        this.nizixsloke = spinner7;
        spinner7.setLayoutParams(new LinearLayout.LayoutParams(1573, 1716));
        this.nizixsloke.setPadding(41, 4, 177, 79);
        linearLayout.addView(this.nizixsloke);
        this.nizixsloke.setBackgroundColor(Color.parseColor("#894c20"));
        RelativeLayout relativeLayout9 = new RelativeLayout(this);
        this.uicdkvymxw = relativeLayout9;
        relativeLayout9.setLayoutParams(new LinearLayout.LayoutParams(346, 1603));
        this.uicdkvymxw.setPadding(35, 85, 125, 163);
        linearLayout.addView(this.uicdkvymxw);
        this.uicdkvymxw.setBackgroundColor(Color.parseColor("#0337e6"));
        GridView gridView13 = new GridView(this);
        this.cdqalxdcww = gridView13;
        gridView13.setLayoutParams(new LinearLayout.LayoutParams(1226, 169));
        this.cdqalxdcww.setPadding(95, 169, 123, 34);
        linearLayout.addView(this.cdqalxdcww);
        this.cdqalxdcww.setBackgroundColor(Color.parseColor("#27630c"));
        FrameLayout frameLayout10 = new FrameLayout(this);
        this.tyuzlabfog = frameLayout10;
        frameLayout10.setLayoutParams(new LinearLayout.LayoutParams(1405, 265));
        this.tyuzlabfog.setPadding(169, 177, 104, 139);
        linearLayout.addView(this.tyuzlabfog);
        this.tyuzlabfog.setBackgroundColor(Color.parseColor("#3c6f9c"));
        Spinner spinner8 = new Spinner(this);
        this.ebegzhebhn = spinner8;
        spinner8.setLayoutParams(new LinearLayout.LayoutParams(1751, 1681));
        this.ebegzhebhn.setPadding(157, 107, 70, 62);
        linearLayout.addView(this.ebegzhebhn);
        this.ebegzhebhn.setBackgroundColor(Color.parseColor("#f24f1e"));
        Spinner spinner9 = new Spinner(this);
        this.viqjnartul = spinner9;
        spinner9.setLayoutParams(new LinearLayout.LayoutParams(682, 1493));
        this.viqjnartul.setPadding(40, 148, 198, 120);
        linearLayout.addView(this.viqjnartul);
        this.viqjnartul.setBackgroundColor(Color.parseColor("#a1c4c5"));
        ImageView imageView10 = new ImageView(this);
        this.idsolswicx = imageView10;
        imageView10.setLayoutParams(new LinearLayout.LayoutParams(1616, 304));
        this.idsolswicx.setPadding(76, 31, 52, 170);
        linearLayout.addView(this.idsolswicx);
        this.idsolswicx.setBackgroundColor(Color.parseColor("#c9c816"));
        DatePicker datePicker8 = new DatePicker(this);
        this.bbeviacvbp = datePicker8;
        datePicker8.setLayoutParams(new LinearLayout.LayoutParams(1755, 1292));
        this.bbeviacvbp.setPadding(125, 52, 143, 172);
        linearLayout.addView(this.bbeviacvbp);
        this.bbeviacvbp.setBackgroundColor(Color.parseColor("#980496"));
        ProgressBar progressBar7 = new ProgressBar(this);
        this.mbbarawmnv = progressBar7;
        progressBar7.setLayoutParams(new LinearLayout.LayoutParams(498, 282));
        this.mbbarawmnv.setPadding(74, 90, 43, 30);
        linearLayout.addView(this.mbbarawmnv);
        this.mbbarawmnv.setBackgroundColor(Color.parseColor("#71b678"));
        SeekBar seekBar8 = new SeekBar(this);
        this.jnsoswqtug = seekBar8;
        seekBar8.setLayoutParams(new LinearLayout.LayoutParams(866, 325));
        this.jnsoswqtug.setPadding(1, 173, 45, 142);
        linearLayout.addView(this.jnsoswqtug);
        this.jnsoswqtug.setBackgroundColor(Color.parseColor("#1be58b"));
        ProgressBar progressBar8 = new ProgressBar(this);
        this.xpzgrswxol = progressBar8;
        progressBar8.setLayoutParams(new LinearLayout.LayoutParams(1704, 1001));
        this.xpzgrswxol.setPadding(91, 43, 20, 69);
        linearLayout.addView(this.xpzgrswxol);
        this.xpzgrswxol.setBackgroundColor(Color.parseColor("#78ace1"));
        TableLayout tableLayout6 = new TableLayout(this);
        this.xtarnifres = tableLayout6;
        tableLayout6.setLayoutParams(new LinearLayout.LayoutParams(431, 809));
        this.xtarnifres.setPadding(113, 73, 118, 108);
        linearLayout.addView(this.xtarnifres);
        this.xtarnifres.setBackgroundColor(Color.parseColor("#edc3a8"));
        CheckBox checkBox13 = new CheckBox(this);
        this.widvdzappy = checkBox13;
        checkBox13.setLayoutParams(new LinearLayout.LayoutParams(962, 358));
        this.widvdzappy.setPadding(168, 179, 86, 28);
        linearLayout.addView(this.widvdzappy);
        this.widvdzappy.setBackgroundColor(Color.parseColor("#2116a4"));
        LinearLayout linearLayout13 = new LinearLayout(this);
        this.sotmmdtjmj = linearLayout13;
        linearLayout13.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.Custom.TYPE_STRING, 338));
        this.sotmmdtjmj.setPadding(47, 129, 184, 114);
        linearLayout.addView(this.sotmmdtjmj);
        this.sotmmdtjmj.setBackgroundColor(Color.parseColor("#a4ff8e"));
        ProgressBar progressBar9 = new ProgressBar(this);
        this.ielishnmhg = progressBar9;
        progressBar9.setLayoutParams(new LinearLayout.LayoutParams(1437, 236));
        this.ielishnmhg.setPadding(115, 125, 174, 177);
        linearLayout.addView(this.ielishnmhg);
        this.ielishnmhg.setBackgroundColor(Color.parseColor("#86aaf5"));
        TableLayout tableLayout7 = new TableLayout(this);
        this.kmpniditmp = tableLayout7;
        tableLayout7.setLayoutParams(new LinearLayout.LayoutParams(PictureConfig.CHOOSE_REQUEST, 1197));
        this.kmpniditmp.setPadding(196, 185, 98, 145);
        linearLayout.addView(this.kmpniditmp);
        this.kmpniditmp.setBackgroundColor(Color.parseColor("#63eeff"));
        ListView listView10 = new ListView(this);
        this.ftngnefsok = listView10;
        listView10.setLayoutParams(new LinearLayout.LayoutParams(1121, 648));
        this.ftngnefsok.setPadding(48, 47, 193, 133);
        linearLayout.addView(this.ftngnefsok);
        this.ftngnefsok.setBackgroundColor(Color.parseColor("#e4dd93"));
        RatingBar ratingBar6 = new RatingBar(this);
        this.pjdedhkimj = ratingBar6;
        ratingBar6.setLayoutParams(new LinearLayout.LayoutParams(GattClient.STATE_READ_DEVICE_INFO, 1353));
        this.pjdedhkimj.setPadding(17, 73, 41, 75);
        linearLayout.addView(this.pjdedhkimj);
        this.pjdedhkimj.setBackgroundColor(Color.parseColor("#2b4c9d"));
        EditText editText11 = new EditText(this);
        this.fwljcnqcem = editText11;
        editText11.setLayoutParams(new LinearLayout.LayoutParams(1005, 1036));
        this.fwljcnqcem.setPadding(172, 175, 30, 35);
        linearLayout.addView(this.fwljcnqcem);
        this.fwljcnqcem.setBackgroundColor(Color.parseColor("#01b38b"));
        TextView textView4 = new TextView(this);
        this.jsjygqjjft = textView4;
        textView4.setLayoutParams(new LinearLayout.LayoutParams(360, 1350));
        this.jsjygqjjft.setPadding(127, 87, BDLocation.TypeServerError, 146);
        linearLayout.addView(this.jsjygqjjft);
        this.jsjygqjjft.setBackgroundColor(Color.parseColor("#20d860"));
    }
}
