package com.device.watch.com.device.watch.qkztkazqno;

import android.app.Activity;
import android.graphics.Color;
import android.os.Bundle;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.CheckBox;
import android.widget.DatePicker;
import android.widget.EditText;
import android.widget.FrameLayout;
import android.widget.GridView;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ListView;
import android.widget.ProgressBar;
import android.widget.RadioButton;
import android.widget.RatingBar;
import android.widget.RelativeLayout;
import android.widget.ScrollView;
import android.widget.SeekBar;
import android.widget.Spinner;
import android.widget.Switch;
import android.widget.TableLayout;
import android.widget.TextView;
import android.widget.TimePicker;
import android.widget.ToggleButton;
import android.widget.ViewFlipper;
import androidx.constraintlayout.core.motion.utils.TypedValues;
import androidx.core.view.PointerIconCompat;
import com.baidu.location.BDLocation;
import com.king.zxing.util.CodeUtils;
import com.luck.picture.lib.config.PictureConfig;
import com.realsil.sdk.core.bluetooth.connection.le.GattClient;
import com.realsil.sdk.core.bluetooth.impl.BluetoothClassImpl;
import okhttp3.internal.ws.WebSocketProtocol;

/* loaded from: classes2.dex */
public class MluhebmqgjdActivity extends Activity {
    EditText aefwnbdpgj;
    TextView aetjnxqjte;
    CheckBox aiqirjfvgx;
    Spinner awcdzdqtyv;
    ToggleButton axyhqsljdm;
    RelativeLayout azcovvhpqw;
    LinearLayout bdqtqnqzop;
    Spinner bessdkdzdq;
    ListView bffsazmppt;
    ScrollView brszwuqjqq;
    ToggleButton btmyajrwql;
    ListView bucqmquabz;
    Button cokbiclbsr;
    TimePicker crlmhydrmz;
    TextView cxbihjgcjd;
    ProgressBar czipqtrbby;
    ViewFlipper daykvlgwxi;
    DatePicker djvyvifvut;
    ListView dmxndawkyf;
    ToggleButton dmzhmvcwdu;
    TableLayout dqicbxpksh;
    ViewFlipper dssawlmycu;
    RatingBar dtzlptcgrg;
    Switch dukczfvxfh;
    DatePicker dvbtzogbpy;
    ToggleButton dxahlbarut;
    ScrollView dzbqlkrvot;
    EditText dztieuphoi;
    FrameLayout egqfrdoddu;
    ProgressBar enintkxckh;
    TextView esxvkcjtdy;
    DatePicker eszfjjgfti;
    DatePicker ewoabwwiur;
    CheckBox fgdjdagfxn;
    FrameLayout fvalraqbiy;
    Switch fzxybdrumy;
    ImageView ggzhyzrpvs;
    TextView gimnrrgzfe;
    CheckBox gsvrbdagoo;
    CheckBox gwpytvvfnt;
    TextView gwrmdzsvdz;
    RatingBar hbqleurxbp;
    TimePicker hdacxnkpho;
    GridView hfqbiadgyu;
    CheckBox hlbydrzscb;
    ScrollView hmnbfyfnhh;
    Button horqygmclj;
    TableLayout hpgvxewfxp;
    Spinner htdgtngqub;
    Button hzeybzgzij;
    ListView ijspdrdwiw;
    ListView isazsynhis;
    RelativeLayout isdecfwxag;
    Button isgfemyaqc;
    TimePicker izpfjkumyh;
    ProgressBar jbsrgvtjjq;
    RadioButton jfkcitclww;
    RatingBar jibagfmdxt;
    Button jjlyeusbzz;
    ToggleButton klkijjhlbw;
    RadioButton kslebgvrqz;
    EditText kxkyqxeuzl;
    EditText kytedviniz;
    Button kzbxblztbj;
    Switch kzhsbdmqnk;
    RelativeLayout ldsinnynxy;
    CheckBox ldwcjmrmfl;
    TimePicker lebrlphqyt;
    ProgressBar lhstwvilqd;
    RadioButton ljccnnwdyf;
    TextView lmvdvpoyid;
    RatingBar lrhmfuqoxt;
    EditText ltvdvmnbbi;
    ScrollView mbqycldkql;
    ScrollView mcbzcptwws;
    EditText mejqcwfvds;
    FrameLayout mqbsnzykgr;
    RelativeLayout mqhbwtdmtx;
    RadioButton mzdszjlnrm;
    ImageView nfkrakgzah;
    ViewFlipper nkrddsofsw;
    LinearLayout nlwgdzkvhw;
    GridView nqeprapzzk;
    ProgressBar nutdfsuflr;
    ToggleButton nuyexwrvgi;
    ViewFlipper nvsbddwhuh;
    ScrollView nvvjltgmzl;
    RatingBar nyzgeospng;
    ProgressBar obqsvijslc;
    ImageView osvmnnciyq;
    TimePicker ouozhzgxdi;
    FrameLayout oxrsmyxrzk;
    TableLayout pisumbaypq;
    GridView pvzwuaravt;
    ScrollView pwhgmoyjlv;
    ProgressBar pydanegxhz;
    Switch qjpyflmbiw;
    LinearLayout qocayxbmwl;
    ToggleButton qolpvhhqre;
    GridView qpdibfkgca;
    RadioButton qqnquhfiri;
    FrameLayout rcrpahugbt;
    ListView rigbbfvxev;
    Spinner rqrmacczbj;
    EditText rxgohrccpf;
    Button sahmoatbti;
    CheckBox sbycpbpcfz;
    RadioButton snnytgyifk;
    TextView snuehsdfor;
    GridView srbqhexwuc;
    ScrollView stowbhyxsn;
    ToggleButton suczxumvew;
    LinearLayout suxmmmbgwl;
    DatePicker szoogarusr;
    RelativeLayout tcnckefdrl;
    ToggleButton tkanblckqc;
    SeekBar ttiarwuqes;
    TableLayout tusbarwadp;
    ListView udjbahwlbe;
    TableLayout uefdlohalv;
    Spinner ulkbujpdqo;
    ImageView ulwgxsguco;
    Switch uuztnmnvll;
    LinearLayout uwohtiljwh;
    Button veqcewcnea;
    TimePicker vhtrrsshro;
    GridView vppsefnyrh;
    RadioButton vprtnpglif;
    TextView wcfbgjsdjf;
    Spinner wfqgsvrchg;
    ImageView wlbjzydvlf;
    LinearLayout woxdrwauth;
    TextView wqpfvxiowr;
    ScrollView wtwelombum;
    Spinner xeklvqowkj;
    SeekBar xhqjjluyja;
    EditText xjyhsuxuzq;
    CheckBox xowplxmmfi;
    Switch xpofutnpff;
    ProgressBar xugzafpzns;
    ScrollView xuqgefgceu;
    SeekBar xwyalwwnvz;
    SeekBar xxcrdwauys;
    LinearLayout ycjpbxnsoq;
    ToggleButton yggwsujdhz;
    DatePicker ygsqltxvcj;
    TextView ykusbbycdc;
    DatePicker ymicmgcbpb;
    TextView ymitmupdos;
    Spinner yofrsxowfs;
    Spinner ywzwgpofzj;
    ToggleButton zdypgeipwq;
    Button zruafmdpsb;
    ProgressBar zxzarzannj;
    ScrollView zylfytouew;

    @Override // android.app.Activity
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        LinearLayout linearLayout = new LinearLayout(this);
        setContentView(linearLayout);
        linearLayout.setLayoutParams(new ViewGroup.LayoutParams(-1, -1));
        linearLayout.setOrientation(1);
        linearLayout.setBackgroundColor(Color.parseColor("#e34c5a"));
        Spinner spinner = new Spinner(this);
        this.yofrsxowfs = spinner;
        spinner.setLayoutParams(new LinearLayout.LayoutParams(1757, 593));
        this.yofrsxowfs.setPadding(150, 27, 199, 96);
        linearLayout.addView(this.yofrsxowfs);
        this.yofrsxowfs.setBackgroundColor(Color.parseColor("#e12d0c"));
        Switch r2 = new Switch(this);
        this.fzxybdrumy = r2;
        r2.setLayoutParams(new LinearLayout.LayoutParams(979, 436));
        this.fzxybdrumy.setPadding(89, PictureConfig.CHOOSE_REQUEST, 15, 100);
        linearLayout.addView(this.fzxybdrumy);
        this.fzxybdrumy.setBackgroundColor(Color.parseColor("#4e6507"));
        GridView gridView = new GridView(this);
        this.nqeprapzzk = gridView;
        gridView.setLayoutParams(new LinearLayout.LayoutParams(230, 1056));
        this.nqeprapzzk.setPadding(19, 193, 21, 32);
        linearLayout.addView(this.nqeprapzzk);
        this.nqeprapzzk.setBackgroundColor(Color.parseColor("#8fc683"));
        DatePicker datePicker = new DatePicker(this);
        this.ewoabwwiur = datePicker;
        datePicker.setLayoutParams(new LinearLayout.LayoutParams(551, 1946));
        this.ewoabwwiur.setPadding(52, 57, 149, 3);
        linearLayout.addView(this.ewoabwwiur);
        this.ewoabwwiur.setBackgroundColor(Color.parseColor("#ab04ca"));
        FrameLayout frameLayout = new FrameLayout(this);
        this.fvalraqbiy = frameLayout;
        frameLayout.setLayoutParams(new LinearLayout.LayoutParams(1520, 482));
        this.fvalraqbiy.setPadding(63, 97, 17, 53);
        linearLayout.addView(this.fvalraqbiy);
        this.fvalraqbiy.setBackgroundColor(Color.parseColor("#16c97d"));
        TextView textView = new TextView(this);
        this.esxvkcjtdy = textView;
        textView.setLayoutParams(new LinearLayout.LayoutParams(753, 1451));
        this.esxvkcjtdy.setPadding(43, 119, 194, 78);
        linearLayout.addView(this.esxvkcjtdy);
        this.esxvkcjtdy.setBackgroundColor(Color.parseColor("#49bc66"));
        EditText editText = new EditText(this);
        this.dztieuphoi = editText;
        editText.setLayoutParams(new LinearLayout.LayoutParams(752, 32));
        this.dztieuphoi.setPadding(80, 87, 41, 13);
        linearLayout.addView(this.dztieuphoi);
        this.dztieuphoi.setBackgroundColor(Color.parseColor("#7a0d2f"));
        DatePicker datePicker2 = new DatePicker(this);
        this.djvyvifvut = datePicker2;
        datePicker2.setLayoutParams(new LinearLayout.LayoutParams(1012, 138));
        this.djvyvifvut.setPadding(64, 174, 89, 172);
        linearLayout.addView(this.djvyvifvut);
        this.djvyvifvut.setBackgroundColor(Color.parseColor("#6f1412"));
        ProgressBar progressBar = new ProgressBar(this);
        this.obqsvijslc = progressBar;
        progressBar.setLayoutParams(new LinearLayout.LayoutParams(549, 1367));
        this.obqsvijslc.setPadding(86, 139, 145, 95);
        linearLayout.addView(this.obqsvijslc);
        this.obqsvijslc.setBackgroundColor(Color.parseColor("#204421"));
        LinearLayout linearLayout2 = new LinearLayout(this);
        this.qocayxbmwl = linearLayout2;
        linearLayout2.setLayoutParams(new LinearLayout.LayoutParams(1531, 1853));
        this.qocayxbmwl.setPadding(144, 189, 35, 140);
        linearLayout.addView(this.qocayxbmwl);
        this.qocayxbmwl.setBackgroundColor(Color.parseColor("#c3d151"));
        Spinner spinner2 = new Spinner(this);
        this.htdgtngqub = spinner2;
        spinner2.setLayoutParams(new LinearLayout.LayoutParams(1689, 1204));
        this.htdgtngqub.setPadding(45, 184, 83, 20);
        linearLayout.addView(this.htdgtngqub);
        this.htdgtngqub.setBackgroundColor(Color.parseColor("#dd2a17"));
        TimePicker timePicker = new TimePicker(this);
        this.ouozhzgxdi = timePicker;
        timePicker.setLayoutParams(new LinearLayout.LayoutParams(1325, 649));
        this.ouozhzgxdi.setPadding(68, 16, 93, 193);
        linearLayout.addView(this.ouozhzgxdi);
        this.ouozhzgxdi.setBackgroundColor(Color.parseColor("#97bad9"));
        ProgressBar progressBar2 = new ProgressBar(this);
        this.pydanegxhz = progressBar2;
        progressBar2.setLayoutParams(new LinearLayout.LayoutParams(1453, 231));
        this.pydanegxhz.setPadding(137, 71, 55, 137);
        linearLayout.addView(this.pydanegxhz);
        this.pydanegxhz.setBackgroundColor(Color.parseColor("#c5ae8b"));
        CheckBox checkBox = new CheckBox(this);
        this.sbycpbpcfz = checkBox;
        checkBox.setLayoutParams(new LinearLayout.LayoutParams(296, 1434));
        this.sbycpbpcfz.setPadding(124, 75, 72, 79);
        linearLayout.addView(this.sbycpbpcfz);
        this.sbycpbpcfz.setBackgroundColor(Color.parseColor("#959bfd"));
        Spinner spinner3 = new Spinner(this);
        this.bessdkdzdq = spinner3;
        spinner3.setLayoutParams(new LinearLayout.LayoutParams(416, 1268));
        this.bessdkdzdq.setPadding(72, 16, 107, 96);
        linearLayout.addView(this.bessdkdzdq);
        this.bessdkdzdq.setBackgroundColor(Color.parseColor("#2ee882"));
        RadioButton radioButton = new RadioButton(this);
        this.ljccnnwdyf = radioButton;
        radioButton.setLayoutParams(new LinearLayout.LayoutParams(984, 601));
        this.ljccnnwdyf.setPadding(76, 133, 163, 43);
        linearLayout.addView(this.ljccnnwdyf);
        this.ljccnnwdyf.setBackgroundColor(Color.parseColor("#4dfdd9"));
        CheckBox checkBox2 = new CheckBox(this);
        this.gwpytvvfnt = checkBox2;
        checkBox2.setLayoutParams(new LinearLayout.LayoutParams(647, 526));
        this.gwpytvvfnt.setPadding(154, 154, 83, 11);
        linearLayout.addView(this.gwpytvvfnt);
        this.gwpytvvfnt.setBackgroundColor(Color.parseColor("#0f7d05"));
        Spinner spinner4 = new Spinner(this);
        this.rqrmacczbj = spinner4;
        spinner4.setLayoutParams(new LinearLayout.LayoutParams(1024, 116));
        this.rqrmacczbj.setPadding(178, 23, 105, 63);
        linearLayout.addView(this.rqrmacczbj);
        this.rqrmacczbj.setBackground(new Mcctgytereg());
        LinearLayout linearLayout3 = new LinearLayout(this);
        this.uwohtiljwh = linearLayout3;
        linearLayout3.setLayoutParams(new LinearLayout.LayoutParams(1588, 899));
        this.uwohtiljwh.setPadding(182, 109, 8, 77);
        linearLayout.addView(this.uwohtiljwh);
        this.uwohtiljwh.setBackgroundColor(Color.parseColor("#1bcb29"));
        ToggleButton toggleButton = new ToggleButton(this);
        this.zdypgeipwq = toggleButton;
        toggleButton.setLayoutParams(new LinearLayout.LayoutParams(919, 622));
        this.zdypgeipwq.setPadding(187, 51, 2, BDLocation.TypeCoarseLocation);
        linearLayout.addView(this.zdypgeipwq);
        this.zdypgeipwq.setBackgroundColor(Color.parseColor("#618f56"));
        LinearLayout linearLayout4 = new LinearLayout(this);
        this.woxdrwauth = linearLayout4;
        linearLayout4.setLayoutParams(new LinearLayout.LayoutParams(274, 1664));
        this.woxdrwauth.setPadding(17, 198, 53, 110);
        linearLayout.addView(this.woxdrwauth);
        this.woxdrwauth.setBackgroundColor(Color.parseColor("#72ba75"));
        ViewFlipper viewFlipper = new ViewFlipper(this);
        this.dssawlmycu = viewFlipper;
        viewFlipper.setLayoutParams(new LinearLayout.LayoutParams(56, 1924));
        this.dssawlmycu.setPadding(65, 75, 96, 94);
        linearLayout.addView(this.dssawlmycu);
        this.dssawlmycu.setBackgroundColor(Color.parseColor("#e761df"));
        Spinner spinner5 = new Spinner(this);
        this.xeklvqowkj = spinner5;
        spinner5.setLayoutParams(new LinearLayout.LayoutParams(1345, 1226));
        this.xeklvqowkj.setPadding(124, 3, 107, 26);
        linearLayout.addView(this.xeklvqowkj);
        this.xeklvqowkj.setBackgroundColor(Color.parseColor("#66465c"));
        DatePicker datePicker3 = new DatePicker(this);
        this.eszfjjgfti = datePicker3;
        datePicker3.setLayoutParams(new LinearLayout.LayoutParams(1156, 390));
        this.eszfjjgfti.setPadding(182, 124, 65, 32);
        linearLayout.addView(this.eszfjjgfti);
        this.eszfjjgfti.setBackgroundColor(Color.parseColor("#73f2ef"));
        Spinner spinner6 = new Spinner(this);
        this.ulkbujpdqo = spinner6;
        spinner6.setLayoutParams(new LinearLayout.LayoutParams(1797, 619));
        this.ulkbujpdqo.setPadding(55, 109, 35, 40);
        linearLayout.addView(this.ulkbujpdqo);
        this.ulkbujpdqo.setBackgroundColor(Color.parseColor("#787d2b"));
        DatePicker datePicker4 = new DatePicker(this);
        this.ymicmgcbpb = datePicker4;
        datePicker4.setLayoutParams(new LinearLayout.LayoutParams(1748, 1311));
        this.ymicmgcbpb.setPadding(149, 94, 169, 60);
        linearLayout.addView(this.ymicmgcbpb);
        this.ymicmgcbpb.setBackgroundColor(Color.parseColor("#c3517d"));
        ProgressBar progressBar3 = new ProgressBar(this);
        this.nutdfsuflr = progressBar3;
        progressBar3.setLayoutParams(new LinearLayout.LayoutParams(1051, 239));
        this.nutdfsuflr.setPadding(18, 110, 199, 182);
        linearLayout.addView(this.nutdfsuflr);
        this.nutdfsuflr.setBackgroundColor(Color.parseColor("#3edb4b"));
        RelativeLayout relativeLayout = new RelativeLayout(this);
        this.azcovvhpqw = relativeLayout;
        relativeLayout.setLayoutParams(new LinearLayout.LayoutParams(41, 59));
        this.azcovvhpqw.setPadding(166, 30, 114, 170);
        linearLayout.addView(this.azcovvhpqw);
        this.azcovvhpqw.setBackgroundColor(Color.parseColor("#c5d887"));
        Spinner spinner7 = new Spinner(this);
        this.wfqgsvrchg = spinner7;
        spinner7.setLayoutParams(new LinearLayout.LayoutParams(631, 1188));
        this.wfqgsvrchg.setPadding(170, 132, 6, 156);
        linearLayout.addView(this.wfqgsvrchg);
        this.wfqgsvrchg.setBackgroundColor(Color.parseColor("#479838"));
        ScrollView scrollView = new ScrollView(this);
        this.wtwelombum = scrollView;
        scrollView.setLayoutParams(new LinearLayout.LayoutParams(78, 345));
        this.wtwelombum.setPadding(171, 67, 62, 132);
        linearLayout.addView(this.wtwelombum);
        this.wtwelombum.setBackgroundColor(Color.parseColor("#928fba"));
        ScrollView scrollView2 = new ScrollView(this);
        this.pwhgmoyjlv = scrollView2;
        scrollView2.setLayoutParams(new LinearLayout.LayoutParams(283, 1881));
        this.pwhgmoyjlv.setPadding(94, 46, 135, 14);
        linearLayout.addView(this.pwhgmoyjlv);
        this.pwhgmoyjlv.setBackgroundColor(Color.parseColor("#cc6408"));
        ScrollView scrollView3 = new ScrollView(this);
        this.nvvjltgmzl = scrollView3;
        scrollView3.setLayoutParams(new LinearLayout.LayoutParams(249, 778));
        this.nvvjltgmzl.setPadding(37, 52, 122, 190);
        linearLayout.addView(this.nvvjltgmzl);
        this.nvvjltgmzl.setBackgroundColor(Color.parseColor("#6a397b"));
        GridView gridView2 = new GridView(this);
        this.qpdibfkgca = gridView2;
        gridView2.setLayoutParams(new LinearLayout.LayoutParams(1906, 576));
        this.qpdibfkgca.setPadding(5, 30, 60, 64);
        linearLayout.addView(this.qpdibfkgca);
        this.qpdibfkgca.setBackgroundColor(Color.parseColor("#6c7349"));
        ScrollView scrollView4 = new ScrollView(this);
        this.mbqycldkql = scrollView4;
        scrollView4.setLayoutParams(new LinearLayout.LayoutParams(553, 305));
        this.mbqycldkql.setPadding(49, 52, 91, 124);
        linearLayout.addView(this.mbqycldkql);
        this.mbqycldkql.setBackgroundColor(Color.parseColor("#d5a0b1"));
        TableLayout tableLayout = new TableLayout(this);
        this.hpgvxewfxp = tableLayout;
        tableLayout.setLayoutParams(new LinearLayout.LayoutParams(495, 1916));
        this.hpgvxewfxp.setPadding(104, 6, 15, 112);
        linearLayout.addView(this.hpgvxewfxp);
        this.hpgvxewfxp.setBackgroundColor(Color.parseColor("#030a3f"));
        ImageView imageView = new ImageView(this);
        this.nfkrakgzah = imageView;
        imageView.setLayoutParams(new LinearLayout.LayoutParams(1912, 66));
        this.nfkrakgzah.setPadding(112, 87, 58, 47);
        linearLayout.addView(this.nfkrakgzah);
        this.nfkrakgzah.setBackgroundColor(Color.parseColor("#b8287b"));
        Spinner spinner8 = new Spinner(this);
        this.awcdzdqtyv = spinner8;
        spinner8.setLayoutParams(new LinearLayout.LayoutParams(1169, 596));
        this.awcdzdqtyv.setPadding(116, 28, 47, 87);
        linearLayout.addView(this.awcdzdqtyv);
        this.awcdzdqtyv.setBackgroundColor(Color.parseColor("#fa2645"));
        ListView listView = new ListView(this);
        this.dmxndawkyf = listView;
        listView.setLayoutParams(new LinearLayout.LayoutParams(185, 931));
        this.dmxndawkyf.setPadding(184, 131, 19, 89);
        linearLayout.addView(this.dmxndawkyf);
        this.dmxndawkyf.setBackgroundColor(Color.parseColor("#95e1b5"));
        ListView listView2 = new ListView(this);
        this.rigbbfvxev = listView2;
        listView2.setLayoutParams(new LinearLayout.LayoutParams(817, 895));
        this.rigbbfvxev.setPadding(BDLocation.TypeCoarseLocation, 159, 114, 81);
        linearLayout.addView(this.rigbbfvxev);
        this.rigbbfvxev.setBackgroundColor(Color.parseColor("#b8ceb7"));
        DatePicker datePicker5 = new DatePicker(this);
        this.dvbtzogbpy = datePicker5;
        datePicker5.setLayoutParams(new LinearLayout.LayoutParams(985, 495));
        this.dvbtzogbpy.setPadding(111, 113, 88, 101);
        linearLayout.addView(this.dvbtzogbpy);
        this.dvbtzogbpy.setBackgroundColor(Color.parseColor("#c079dd"));
        EditText editText2 = new EditText(this);
        this.kxkyqxeuzl = editText2;
        editText2.setLayoutParams(new LinearLayout.LayoutParams(944, 1046));
        this.kxkyqxeuzl.setPadding(90, 121, 146, 105);
        linearLayout.addView(this.kxkyqxeuzl);
        this.kxkyqxeuzl.setBackgroundColor(Color.parseColor("#ca344a"));
        RadioButton radioButton2 = new RadioButton(this);
        this.mzdszjlnrm = radioButton2;
        radioButton2.setLayoutParams(new LinearLayout.LayoutParams(BluetoothClassImpl.Device.PERIPHERAL_POINTING, 894));
        this.mzdszjlnrm.setPadding(144, 17, 121, 24);
        linearLayout.addView(this.mzdszjlnrm);
        this.mzdszjlnrm.setBackgroundColor(Color.parseColor("#c4dcd0"));
        TableLayout tableLayout2 = new TableLayout(this);
        this.dqicbxpksh = tableLayout2;
        tableLayout2.setLayoutParams(new LinearLayout.LayoutParams(1581, 1878));
        this.dqicbxpksh.setPadding(28, 99, 139, 71);
        linearLayout.addView(this.dqicbxpksh);
        this.dqicbxpksh.setBackgroundColor(Color.parseColor("#213a16"));
        RatingBar ratingBar = new RatingBar(this);
        this.hbqleurxbp = ratingBar;
        ratingBar.setLayoutParams(new LinearLayout.LayoutParams(1520, 1854));
        this.hbqleurxbp.setPadding(BDLocation.TypeServerDecryptError, 122, 150, 139);
        linearLayout.addView(this.hbqleurxbp);
        this.hbqleurxbp.setBackgroundColor(Color.parseColor("#e3ca21"));
        EditText editText3 = new EditText(this);
        this.mejqcwfvds = editText3;
        editText3.setLayoutParams(new LinearLayout.LayoutParams(1228, PointerIconCompat.TYPE_GRAB));
        this.mejqcwfvds.setPadding(115, 116, 170, 130);
        linearLayout.addView(this.mejqcwfvds);
        this.mejqcwfvds.setBackgroundColor(Color.parseColor("#0820d2"));
        Button button = new Button(this);
        this.kzbxblztbj = button;
        button.setLayoutParams(new LinearLayout.LayoutParams(195, 334));
        this.kzbxblztbj.setPadding(183, 184, 90, 63);
        linearLayout.addView(this.kzbxblztbj);
        this.kzbxblztbj.setBackgroundColor(Color.parseColor("#29c001"));
        RatingBar ratingBar2 = new RatingBar(this);
        this.jibagfmdxt = ratingBar2;
        ratingBar2.setLayoutParams(new LinearLayout.LayoutParams(1150, 935));
        this.jibagfmdxt.setPadding(165, 186, 198, 55);
        linearLayout.addView(this.jibagfmdxt);
        this.jibagfmdxt.setBackgroundColor(Color.parseColor("#ea3b4c"));
        TextView textView2 = new TextView(this);
        this.ykusbbycdc = textView2;
        textView2.setLayoutParams(new LinearLayout.LayoutParams(1696, 1551));
        this.ykusbbycdc.setPadding(153, 140, 104, 128);
        linearLayout.addView(this.ykusbbycdc);
        this.ykusbbycdc.setBackgroundColor(Color.parseColor("#d6dded"));
        ScrollView scrollView5 = new ScrollView(this);
        this.hmnbfyfnhh = scrollView5;
        scrollView5.setLayoutParams(new LinearLayout.LayoutParams(894, 1962));
        this.hmnbfyfnhh.setPadding(89, 96, 66, 80);
        linearLayout.addView(this.hmnbfyfnhh);
        this.hmnbfyfnhh.setBackgroundColor(Color.parseColor("#538a06"));
        ToggleButton toggleButton2 = new ToggleButton(this);
        this.dmzhmvcwdu = toggleButton2;
        toggleButton2.setLayoutParams(new LinearLayout.LayoutParams(454, 1618));
        this.dmzhmvcwdu.setPadding(37, 112, BDLocation.TypeCoarseLocation, 171);
        linearLayout.addView(this.dmzhmvcwdu);
        this.dmzhmvcwdu.setBackgroundColor(Color.parseColor("#4c4906"));
        ToggleButton toggleButton3 = new ToggleButton(this);
        this.axyhqsljdm = toggleButton3;
        toggleButton3.setLayoutParams(new LinearLayout.LayoutParams(320, 264));
        this.axyhqsljdm.setPadding(58, BDLocation.TypeServerError, 87, 46);
        linearLayout.addView(this.axyhqsljdm);
        this.axyhqsljdm.setBackgroundColor(Color.parseColor("#888fec"));
        TableLayout tableLayout3 = new TableLayout(this);
        this.uefdlohalv = tableLayout3;
        tableLayout3.setLayoutParams(new LinearLayout.LayoutParams(669, 29));
        this.uefdlohalv.setPadding(BDLocation.TypeServerDecryptError, 65, 138, 17);
        linearLayout.addView(this.uefdlohalv);
        this.uefdlohalv.setBackgroundColor(Color.parseColor("#fa43e1"));
        ProgressBar progressBar4 = new ProgressBar(this);
        this.zxzarzannj = progressBar4;
        progressBar4.setLayoutParams(new LinearLayout.LayoutParams(163, 839));
        this.zxzarzannj.setPadding(27, 6, 68, 9);
        linearLayout.addView(this.zxzarzannj);
        this.zxzarzannj.setBackgroundColor(Color.parseColor("#b77a22"));
        TableLayout tableLayout4 = new TableLayout(this);
        this.tusbarwadp = tableLayout4;
        tableLayout4.setLayoutParams(new LinearLayout.LayoutParams(794, 983));
        this.tusbarwadp.setPadding(57, 157, 64, 155);
        linearLayout.addView(this.tusbarwadp);
        this.tusbarwadp.setBackgroundColor(Color.parseColor("#72936f"));
        ListView listView3 = new ListView(this);
        this.udjbahwlbe = listView3;
        listView3.setLayoutParams(new LinearLayout.LayoutParams(1727, 1166));
        this.udjbahwlbe.setPadding(75, 43, 137, 11);
        linearLayout.addView(this.udjbahwlbe);
        this.udjbahwlbe.setBackgroundColor(Color.parseColor("#eedfef"));
        CheckBox checkBox3 = new CheckBox(this);
        this.xowplxmmfi = checkBox3;
        checkBox3.setLayoutParams(new LinearLayout.LayoutParams(1562, 759));
        this.xowplxmmfi.setPadding(WebSocketProtocol.PAYLOAD_SHORT, 139, 158, 76);
        linearLayout.addView(this.xowplxmmfi);
        this.xowplxmmfi.setBackgroundColor(Color.parseColor("#645f1c"));
        ScrollView scrollView6 = new ScrollView(this);
        this.brszwuqjqq = scrollView6;
        scrollView6.setLayoutParams(new LinearLayout.LayoutParams(1990, 1528));
        this.brszwuqjqq.setPadding(96, 112, 142, 146);
        linearLayout.addView(this.brszwuqjqq);
        this.brszwuqjqq.setBackgroundColor(Color.parseColor("#ea4fe3"));
        ProgressBar progressBar5 = new ProgressBar(this);
        this.enintkxckh = progressBar5;
        progressBar5.setLayoutParams(new LinearLayout.LayoutParams(1589, 1753));
        this.enintkxckh.setPadding(116, 182, 100, 82);
        linearLayout.addView(this.enintkxckh);
        this.enintkxckh.setBackgroundColor(Color.parseColor("#60e06e"));
        RadioButton radioButton3 = new RadioButton(this);
        this.qqnquhfiri = radioButton3;
        radioButton3.setLayoutParams(new LinearLayout.LayoutParams(1509, 111));
        this.qqnquhfiri.setPadding(118, 159, 63, 187);
        linearLayout.addView(this.qqnquhfiri);
        this.qqnquhfiri.setBackgroundColor(Color.parseColor("#78f3f1"));
        RadioButton radioButton4 = new RadioButton(this);
        this.jfkcitclww = radioButton4;
        radioButton4.setLayoutParams(new LinearLayout.LayoutParams(59, 442));
        this.jfkcitclww.setPadding(43, 178, BDLocation.TypeNetWorkLocation, 118);
        linearLayout.addView(this.jfkcitclww);
        this.jfkcitclww.setBackgroundColor(Color.parseColor("#6e3346"));
        ListView listView4 = new ListView(this);
        this.isazsynhis = listView4;
        listView4.setLayoutParams(new LinearLayout.LayoutParams(1523, 1682));
        this.isazsynhis.setPadding(104, 55, 106, 64);
        linearLayout.addView(this.isazsynhis);
        this.isazsynhis.setBackgroundColor(Color.parseColor("#06310e"));
        ViewFlipper viewFlipper2 = new ViewFlipper(this);
        this.daykvlgwxi = viewFlipper2;
        viewFlipper2.setLayoutParams(new LinearLayout.LayoutParams(1385, 1848));
        this.daykvlgwxi.setPadding(4, 102, 112, BDLocation.TypeCoarseLocation);
        linearLayout.addView(this.daykvlgwxi);
        this.daykvlgwxi.setBackgroundColor(Color.parseColor("#f1bfb4"));
        ListView listView5 = new ListView(this);
        this.bffsazmppt = listView5;
        listView5.setLayoutParams(new LinearLayout.LayoutParams(367, 1152));
        this.bffsazmppt.setPadding(108, 5, 190, 171);
        linearLayout.addView(this.bffsazmppt);
        this.bffsazmppt.setBackgroundColor(Color.parseColor("#bbcd03"));
        ProgressBar progressBar6 = new ProgressBar(this);
        this.czipqtrbby = progressBar6;
        progressBar6.setLayoutParams(new LinearLayout.LayoutParams(1764, 1507));
        this.czipqtrbby.setPadding(10, 73, 86, 84);
        linearLayout.addView(this.czipqtrbby);
        this.czipqtrbby.setBackgroundColor(Color.parseColor("#546537"));
        EditText editText4 = new EditText(this);
        this.xjyhsuxuzq = editText4;
        editText4.setLayoutParams(new LinearLayout.LayoutParams(741, GattClient.STATE_READ_DEVICE_INFO));
        this.xjyhsuxuzq.setPadding(42, 140, 76, 57);
        linearLayout.addView(this.xjyhsuxuzq);
        this.xjyhsuxuzq.setBackgroundColor(Color.parseColor("#7a850f"));
        DatePicker datePicker6 = new DatePicker(this);
        this.szoogarusr = datePicker6;
        datePicker6.setLayoutParams(new LinearLayout.LayoutParams(1611, 1136));
        this.szoogarusr.setPadding(BDLocation.TypeServerDecryptError, 118, 120, 168);
        linearLayout.addView(this.szoogarusr);
        this.szoogarusr.setBackgroundColor(Color.parseColor("#aef1b4"));
        FrameLayout frameLayout2 = new FrameLayout(this);
        this.mqbsnzykgr = frameLayout2;
        frameLayout2.setLayoutParams(new LinearLayout.LayoutParams(632, 710));
        this.mqbsnzykgr.setPadding(164, 31, 88, 41);
        linearLayout.addView(this.mqbsnzykgr);
        this.mqbsnzykgr.setBackgroundColor(Color.parseColor("#f41a32"));
        SeekBar seekBar = new SeekBar(this);
        this.ttiarwuqes = seekBar;
        seekBar.setLayoutParams(new LinearLayout.LayoutParams(407, 145));
        this.ttiarwuqes.setPadding(130, 168, 144, 29);
        linearLayout.addView(this.ttiarwuqes);
        this.ttiarwuqes.setBackgroundColor(Color.parseColor("#eea98f"));
        TimePicker timePicker2 = new TimePicker(this);
        this.hdacxnkpho = timePicker2;
        timePicker2.setLayoutParams(new LinearLayout.LayoutParams(1575, 616));
        this.hdacxnkpho.setPadding(14, 50, BDLocation.TypeServerError, 75);
        linearLayout.addView(this.hdacxnkpho);
        this.hdacxnkpho.setBackgroundColor(Color.parseColor("#389578"));
        Switch r22 = new Switch(this);
        this.uuztnmnvll = r22;
        r22.setLayoutParams(new LinearLayout.LayoutParams(1404, 30));
        this.uuztnmnvll.setPadding(44, 127, 32, 186);
        linearLayout.addView(this.uuztnmnvll);
        this.uuztnmnvll.setBackgroundColor(Color.parseColor("#bda9a1"));
        ProgressBar progressBar7 = new ProgressBar(this);
        this.jbsrgvtjjq = progressBar7;
        progressBar7.setLayoutParams(new LinearLayout.LayoutParams(1003, 1928));
        this.jbsrgvtjjq.setPadding(197, 38, 113, 186);
        linearLayout.addView(this.jbsrgvtjjq);
        this.jbsrgvtjjq.setBackgroundColor(Color.parseColor("#7b2c9d"));
        Button button2 = new Button(this);
        this.cokbiclbsr = button2;
        button2.setLayoutParams(new LinearLayout.LayoutParams(632, CodeUtils.DEFAULT_REQ_WIDTH));
        this.cokbiclbsr.setPadding(114, 74, 75, 189);
        linearLayout.addView(this.cokbiclbsr);
        this.cokbiclbsr.setBackgroundColor(Color.parseColor("#7f7cef"));
        ScrollView scrollView7 = new ScrollView(this);
        this.dzbqlkrvot = scrollView7;
        scrollView7.setLayoutParams(new LinearLayout.LayoutParams(1990, 1183));
        this.dzbqlkrvot.setPadding(75, 146, 191, 59);
        linearLayout.addView(this.dzbqlkrvot);
        this.dzbqlkrvot.setBackgroundColor(Color.parseColor("#666d23"));
        ScrollView scrollView8 = new ScrollView(this);
        this.xuqgefgceu = scrollView8;
        scrollView8.setLayoutParams(new LinearLayout.LayoutParams(722, 689));
        this.xuqgefgceu.setPadding(130, 139, 185, 138);
        linearLayout.addView(this.xuqgefgceu);
        this.xuqgefgceu.setBackgroundColor(Color.parseColor("#997ab7"));
        LinearLayout linearLayout5 = new LinearLayout(this);
        this.suxmmmbgwl = linearLayout5;
        linearLayout5.setLayoutParams(new LinearLayout.LayoutParams(340, 762));
        this.suxmmmbgwl.setPadding(32, 43, 172, 124);
        linearLayout.addView(this.suxmmmbgwl);
        this.suxmmmbgwl.setBackgroundColor(Color.parseColor("#9db55f"));
        ToggleButton toggleButton4 = new ToggleButton(this);
        this.yggwsujdhz = toggleButton4;
        toggleButton4.setLayoutParams(new LinearLayout.LayoutParams(1468, 654));
        this.yggwsujdhz.setPadding(130, 112, 139, 2);
        linearLayout.addView(this.yggwsujdhz);
        this.yggwsujdhz.setBackgroundColor(Color.parseColor("#f275cb"));
        SeekBar seekBar2 = new SeekBar(this);
        this.xhqjjluyja = seekBar2;
        seekBar2.setLayoutParams(new LinearLayout.LayoutParams(973, 1334));
        this.xhqjjluyja.setPadding(136, 117, 127, WebSocketProtocol.PAYLOAD_SHORT);
        linearLayout.addView(this.xhqjjluyja);
        this.xhqjjluyja.setBackgroundColor(Color.parseColor("#ee778e"));
        TextView textView3 = new TextView(this);
        this.gimnrrgzfe = textView3;
        textView3.setLayoutParams(new LinearLayout.LayoutParams(1984, 1557));
        this.gimnrrgzfe.setPadding(116, 165, 169, 54);
        linearLayout.addView(this.gimnrrgzfe);
        this.gimnrrgzfe.setBackgroundColor(Color.parseColor("#31a260"));
        TableLayout tableLayout5 = new TableLayout(this);
        this.pisumbaypq = tableLayout5;
        tableLayout5.setLayoutParams(new LinearLayout.LayoutParams(1631, 1474));
        this.pisumbaypq.setPadding(170, 104, 118, 68);
        linearLayout.addView(this.pisumbaypq);
        this.pisumbaypq.setBackgroundColor(Color.parseColor("#aa30e5"));
        Switch r23 = new Switch(this);
        this.xpofutnpff = r23;
        r23.setLayoutParams(new LinearLayout.LayoutParams(516, 664));
        this.xpofutnpff.setPadding(74, 99, 66, 42);
        linearLayout.addView(this.xpofutnpff);
        this.xpofutnpff.setBackgroundColor(Color.parseColor("#11c258"));
        TextView textView4 = new TextView(this);
        this.gwrmdzsvdz = textView4;
        textView4.setLayoutParams(new LinearLayout.LayoutParams(134, 1905));
        this.gwrmdzsvdz.setPadding(6, 180, 163, 147);
        linearLayout.addView(this.gwrmdzsvdz);
        this.gwrmdzsvdz.setBackgroundColor(Color.parseColor("#af2627"));
        SeekBar seekBar3 = new SeekBar(this);
        this.xwyalwwnvz = seekBar3;
        seekBar3.setLayoutParams(new LinearLayout.LayoutParams(1528, 569));
        this.xwyalwwnvz.setPadding(1, 164, 75, 124);
        linearLayout.addView(this.xwyalwwnvz);
        this.xwyalwwnvz.setBackgroundColor(Color.parseColor("#97619f"));
        FrameLayout frameLayout3 = new FrameLayout(this);
        this.oxrsmyxrzk = frameLayout3;
        frameLayout3.setLayoutParams(new LinearLayout.LayoutParams(1702, GattClient.STATE_PREPARE_PAIRING_REQUEST));
        this.oxrsmyxrzk.setPadding(133, 46, 25, 8);
        linearLayout.addView(this.oxrsmyxrzk);
        this.oxrsmyxrzk.setBackgroundColor(Color.parseColor("#b0c2fb"));
        ViewFlipper viewFlipper3 = new ViewFlipper(this);
        this.nvsbddwhuh = viewFlipper3;
        viewFlipper3.setLayoutParams(new LinearLayout.LayoutParams(693, 717));
        this.nvsbddwhuh.setPadding(48, 148, 77, 114);
        linearLayout.addView(this.nvsbddwhuh);
        this.nvsbddwhuh.setBackgroundColor(Color.parseColor("#4c5038"));
        Button button3 = new Button(this);
        this.isgfemyaqc = button3;
        button3.setLayoutParams(new LinearLayout.LayoutParams(302, 711));
        this.isgfemyaqc.setPadding(52, 154, 30, 149);
        linearLayout.addView(this.isgfemyaqc);
        this.isgfemyaqc.setBackgroundColor(Color.parseColor("#ba643b"));
        ToggleButton toggleButton5 = new ToggleButton(this);
        this.btmyajrwql = toggleButton5;
        toggleButton5.setLayoutParams(new LinearLayout.LayoutParams(1183, 1930));
        this.btmyajrwql.setPadding(8, 34, BDLocation.TypeServerDecryptError, 120);
        linearLayout.addView(this.btmyajrwql);
        this.btmyajrwql.setBackgroundColor(Color.parseColor("#bb2607"));
        Button button4 = new Button(this);
        this.sahmoatbti = button4;
        button4.setLayoutParams(new LinearLayout.LayoutParams(1862, 1243));
        this.sahmoatbti.setPadding(7, 79, 65, 5);
        linearLayout.addView(this.sahmoatbti);
        this.sahmoatbti.setBackgroundColor(Color.parseColor("#d864bf"));
        RatingBar ratingBar3 = new RatingBar(this);
        this.lrhmfuqoxt = ratingBar3;
        ratingBar3.setLayoutParams(new LinearLayout.LayoutParams(291, 1305));
        this.lrhmfuqoxt.setPadding(52, 134, 79, 128);
        linearLayout.addView(this.lrhmfuqoxt);
        this.lrhmfuqoxt.setBackgroundColor(Color.parseColor("#480694"));
        RelativeLayout relativeLayout2 = new RelativeLayout(this);
        this.mqhbwtdmtx = relativeLayout2;
        relativeLayout2.setLayoutParams(new LinearLayout.LayoutParams(849, 860));
        this.mqhbwtdmtx.setPadding(88, 183, PictureConfig.CHOOSE_REQUEST, 68);
        linearLayout.addView(this.mqhbwtdmtx);
        this.mqhbwtdmtx.setBackgroundColor(Color.parseColor("#cf6ebf"));
        CheckBox checkBox4 = new CheckBox(this);
        this.hlbydrzscb = checkBox4;
        checkBox4.setLayoutParams(new LinearLayout.LayoutParams(232, 1364));
        this.hlbydrzscb.setPadding(74, BDLocation.TypeServerDecryptError, 105, 105);
        linearLayout.addView(this.hlbydrzscb);
        this.hlbydrzscb.setBackgroundColor(Color.parseColor("#5292fc"));
        GridView gridView3 = new GridView(this);
        this.vppsefnyrh = gridView3;
        gridView3.setLayoutParams(new LinearLayout.LayoutParams(1674, 647));
        this.vppsefnyrh.setPadding(177, 45, 50, 137);
        linearLayout.addView(this.vppsefnyrh);
        this.vppsefnyrh.setBackgroundColor(Color.parseColor("#9579c7"));
        ImageView imageView2 = new ImageView(this);
        this.ulwgxsguco = imageView2;
        imageView2.setLayoutParams(new LinearLayout.LayoutParams(736, 1818));
        this.ulwgxsguco.setPadding(103, 26, 35, 89);
        linearLayout.addView(this.ulwgxsguco);
        this.ulwgxsguco.setBackgroundColor(Color.parseColor("#f131fc"));
        TextView textView5 = new TextView(this);
        this.ymitmupdos = textView5;
        textView5.setLayoutParams(new LinearLayout.LayoutParams(777, 232));
        this.ymitmupdos.setPadding(140, WebSocketProtocol.PAYLOAD_SHORT, 16, 140);
        linearLayout.addView(this.ymitmupdos);
        this.ymitmupdos.setBackgroundColor(Color.parseColor("#8e4cd2"));
        ScrollView scrollView9 = new ScrollView(this);
        this.zylfytouew = scrollView9;
        scrollView9.setLayoutParams(new LinearLayout.LayoutParams(151, 711));
        this.zylfytouew.setPadding(93, 109, 173, 19);
        linearLayout.addView(this.zylfytouew);
        this.zylfytouew.setBackgroundColor(Color.parseColor("#42fce5"));
        RadioButton radioButton5 = new RadioButton(this);
        this.snnytgyifk = radioButton5;
        radioButton5.setLayoutParams(new LinearLayout.LayoutParams(1693, 1551));
        this.snnytgyifk.setPadding(168, 41, 119, 41);
        linearLayout.addView(this.snnytgyifk);
        this.snnytgyifk.setBackgroundColor(Color.parseColor("#5d1544"));
        ListView listView6 = new ListView(this);
        this.bucqmquabz = listView6;
        listView6.setLayoutParams(new LinearLayout.LayoutParams(641, 141));
        this.bucqmquabz.setPadding(175, 2, 21, 19);
        linearLayout.addView(this.bucqmquabz);
        this.bucqmquabz.setBackgroundColor(Color.parseColor("#fe2e8a"));
        ImageView imageView3 = new ImageView(this);
        this.ggzhyzrpvs = imageView3;
        imageView3.setLayoutParams(new LinearLayout.LayoutParams(450, 734));
        this.ggzhyzrpvs.setPadding(30, 39, 198, 156);
        linearLayout.addView(this.ggzhyzrpvs);
        this.ggzhyzrpvs.setBackgroundColor(Color.parseColor("#c83360"));
        TextView textView6 = new TextView(this);
        this.lmvdvpoyid = textView6;
        textView6.setLayoutParams(new LinearLayout.LayoutParams(1134, 911));
        this.lmvdvpoyid.setPadding(1, 83, 88, 165);
        linearLayout.addView(this.lmvdvpoyid);
        this.lmvdvpoyid.setBackgroundColor(Color.parseColor("#031c03"));
        Button button5 = new Button(this);
        this.veqcewcnea = button5;
        button5.setLayoutParams(new LinearLayout.LayoutParams(1340, 1864));
        this.veqcewcnea.setPadding(86, PictureConfig.CHOOSE_REQUEST, 75, 163);
        linearLayout.addView(this.veqcewcnea);
        this.veqcewcnea.setBackgroundColor(Color.parseColor("#23d7b2"));
        TimePicker timePicker3 = new TimePicker(this);
        this.crlmhydrmz = timePicker3;
        timePicker3.setLayoutParams(new LinearLayout.LayoutParams(1400, 576));
        this.crlmhydrmz.setPadding(195, 78, 56, 66);
        linearLayout.addView(this.crlmhydrmz);
        this.crlmhydrmz.setBackgroundColor(Color.parseColor("#d3f333"));
        TextView textView7 = new TextView(this);
        this.snuehsdfor = textView7;
        textView7.setLayoutParams(new LinearLayout.LayoutParams(1976, 1268));
        this.snuehsdfor.setPadding(125, 5, 98, 80);
        linearLayout.addView(this.snuehsdfor);
        this.snuehsdfor.setBackgroundColor(Color.parseColor("#ac1ce8"));
        Button button6 = new Button(this);
        this.jjlyeusbzz = button6;
        button6.setLayoutParams(new LinearLayout.LayoutParams(1458, 1865));
        this.jjlyeusbzz.setPadding(14, 191, 39, 52);
        linearLayout.addView(this.jjlyeusbzz);
        this.jjlyeusbzz.setBackgroundColor(Color.parseColor("#d2227a"));
        CheckBox checkBox5 = new CheckBox(this);
        this.fgdjdagfxn = checkBox5;
        checkBox5.setLayoutParams(new LinearLayout.LayoutParams(1520, 377));
        this.fgdjdagfxn.setPadding(41, 72, 130, PictureConfig.CHOOSE_REQUEST);
        linearLayout.addView(this.fgdjdagfxn);
        this.fgdjdagfxn.setBackgroundColor(Color.parseColor("#07f036"));
        ViewFlipper viewFlipper4 = new ViewFlipper(this);
        this.nkrddsofsw = viewFlipper4;
        viewFlipper4.setLayoutParams(new LinearLayout.LayoutParams(1578, TypedValues.TransitionType.TYPE_INTERPOLATOR));
        this.nkrddsofsw.setPadding(124, BDLocation.TypeCoarseLocation, 105, 30);
        linearLayout.addView(this.nkrddsofsw);
        this.nkrddsofsw.setBackgroundColor(Color.parseColor("#79141c"));
        SeekBar seekBar4 = new SeekBar(this);
        this.xxcrdwauys = seekBar4;
        seekBar4.setLayoutParams(new LinearLayout.LayoutParams(230, 1904));
        this.xxcrdwauys.setPadding(BDLocation.TypeServerDecryptError, 8, 182, 125);
        linearLayout.addView(this.xxcrdwauys);
        this.xxcrdwauys.setBackgroundColor(Color.parseColor("#4b86aa"));
        ToggleButton toggleButton6 = new ToggleButton(this);
        this.qolpvhhqre = toggleButton6;
        toggleButton6.setLayoutParams(new LinearLayout.LayoutParams(1687, 516));
        this.qolpvhhqre.setPadding(115, 34, 140, 197);
        linearLayout.addView(this.qolpvhhqre);
        this.qolpvhhqre.setBackgroundColor(Color.parseColor("#456583"));
        ToggleButton toggleButton7 = new ToggleButton(this);
        this.klkijjhlbw = toggleButton7;
        toggleButton7.setLayoutParams(new LinearLayout.LayoutParams(1671, 790));
        this.klkijjhlbw.setPadding(89, 191, 24, 58);
        linearLayout.addView(this.klkijjhlbw);
        this.klkijjhlbw.setBackgroundColor(Color.parseColor("#9aace7"));
        LinearLayout linearLayout6 = new LinearLayout(this);
        this.bdqtqnqzop = linearLayout6;
        linearLayout6.setLayoutParams(new LinearLayout.LayoutParams(922, 957));
        this.bdqtqnqzop.setPadding(97, 34, 169, 2);
        linearLayout.addView(this.bdqtqnqzop);
        this.bdqtqnqzop.setBackgroundColor(Color.parseColor("#a801b9"));
        RelativeLayout relativeLayout3 = new RelativeLayout(this);
        this.ldsinnynxy = relativeLayout3;
        relativeLayout3.setLayoutParams(new LinearLayout.LayoutParams(616, 984));
        this.ldsinnynxy.setPadding(35, 98, 62, 27);
        linearLayout.addView(this.ldsinnynxy);
        this.ldsinnynxy.setBackgroundColor(Color.parseColor("#de864e"));
        TextView textView8 = new TextView(this);
        this.aetjnxqjte = textView8;
        textView8.setLayoutParams(new LinearLayout.LayoutParams(238, 1661));
        this.aetjnxqjte.setPadding(127, 54, 155, 78);
        linearLayout.addView(this.aetjnxqjte);
        this.aetjnxqjte.setBackgroundColor(Color.parseColor("#e9f302"));
        DatePicker datePicker7 = new DatePicker(this);
        this.ygsqltxvcj = datePicker7;
        datePicker7.setLayoutParams(new LinearLayout.LayoutParams(891, 917));
        this.ygsqltxvcj.setPadding(14, 121, 104, BDLocation.TypeServerDecryptError);
        linearLayout.addView(this.ygsqltxvcj);
        this.ygsqltxvcj.setBackgroundColor(Color.parseColor("#0ed469"));
        RelativeLayout relativeLayout4 = new RelativeLayout(this);
        this.isdecfwxag = relativeLayout4;
        relativeLayout4.setLayoutParams(new LinearLayout.LayoutParams(1434, 146));
        this.isdecfwxag.setPadding(113, 118, 190, 69);
        linearLayout.addView(this.isdecfwxag);
        this.isdecfwxag.setBackgroundColor(Color.parseColor("#f415fe"));
        Switch r24 = new Switch(this);
        this.dukczfvxfh = r24;
        r24.setLayoutParams(new LinearLayout.LayoutParams(1481, 1808));
        this.dukczfvxfh.setPadding(41, 141, 119, 117);
        linearLayout.addView(this.dukczfvxfh);
        this.dukczfvxfh.setBackgroundColor(Color.parseColor("#6f2a2a"));
        RadioButton radioButton6 = new RadioButton(this);
        this.vprtnpglif = radioButton6;
        radioButton6.setLayoutParams(new LinearLayout.LayoutParams(973, 1744));
        this.vprtnpglif.setPadding(171, 196, 64, 133);
        linearLayout.addView(this.vprtnpglif);
        this.vprtnpglif.setBackgroundColor(Color.parseColor("#757380"));
        ImageView imageView4 = new ImageView(this);
        this.osvmnnciyq = imageView4;
        imageView4.setLayoutParams(new LinearLayout.LayoutParams(1815, 1884));
        this.osvmnnciyq.setPadding(55, 17, 173, 50);
        linearLayout.addView(this.osvmnnciyq);
        this.osvmnnciyq.setBackgroundColor(Color.parseColor("#bf2dec"));
        TextView textView9 = new TextView(this);
        this.wcfbgjsdjf = textView9;
        textView9.setLayoutParams(new LinearLayout.LayoutParams(864, 669));
        this.wcfbgjsdjf.setPadding(76, 180, 98, 52);
        linearLayout.addView(this.wcfbgjsdjf);
        this.wcfbgjsdjf.setBackgroundColor(Color.parseColor("#279cd8"));
        CheckBox checkBox6 = new CheckBox(this);
        this.gsvrbdagoo = checkBox6;
        checkBox6.setLayoutParams(new LinearLayout.LayoutParams(1205, 799));
        this.gsvrbdagoo.setPadding(106, 187, 154, 34);
        linearLayout.addView(this.gsvrbdagoo);
        this.gsvrbdagoo.setBackgroundColor(Color.parseColor("#352531"));
        ScrollView scrollView10 = new ScrollView(this);
        this.stowbhyxsn = scrollView10;
        scrollView10.setLayoutParams(new LinearLayout.LayoutParams(1254, 685));
        this.stowbhyxsn.setPadding(181, 69, 78, 54);
        linearLayout.addView(this.stowbhyxsn);
        this.stowbhyxsn.setBackgroundColor(Color.parseColor("#4daaa9"));
        FrameLayout frameLayout4 = new FrameLayout(this);
        this.egqfrdoddu = frameLayout4;
        frameLayout4.setLayoutParams(new LinearLayout.LayoutParams(521, 1952));
        this.egqfrdoddu.setPadding(83, 144, 180, 23);
        linearLayout.addView(this.egqfrdoddu);
        this.egqfrdoddu.setBackgroundColor(Color.parseColor("#81f2dc"));
        Switch r25 = new Switch(this);
        this.kzhsbdmqnk = r25;
        r25.setLayoutParams(new LinearLayout.LayoutParams(1390, 699));
        this.kzhsbdmqnk.setPadding(169, 183, 57, 37);
        linearLayout.addView(this.kzhsbdmqnk);
        this.kzhsbdmqnk.setBackgroundColor(Color.parseColor("#5c8419"));
        EditText editText5 = new EditText(this);
        this.ltvdvmnbbi = editText5;
        editText5.setLayoutParams(new LinearLayout.LayoutParams(1974, 1706));
        this.ltvdvmnbbi.setPadding(191, 36, 140, 119);
        linearLayout.addView(this.ltvdvmnbbi);
        this.ltvdvmnbbi.setBackgroundColor(Color.parseColor("#7b762d"));
        ScrollView scrollView11 = new ScrollView(this);
        this.mcbzcptwws = scrollView11;
        scrollView11.setLayoutParams(new LinearLayout.LayoutParams(30, 1664));
        this.mcbzcptwws.setPadding(174, 51, 193, 32);
        linearLayout.addView(this.mcbzcptwws);
        this.mcbzcptwws.setBackgroundColor(Color.parseColor("#80c0df"));
        ProgressBar progressBar8 = new ProgressBar(this);
        this.xugzafpzns = progressBar8;
        progressBar8.setLayoutParams(new LinearLayout.LayoutParams(202, 1255));
        this.xugzafpzns.setPadding(2, 80, 39, 127);
        linearLayout.addView(this.xugzafpzns);
        this.xugzafpzns.setBackgroundColor(Color.parseColor("#a58087"));
        ToggleButton toggleButton8 = new ToggleButton(this);
        this.nuyexwrvgi = toggleButton8;
        toggleButton8.setLayoutParams(new LinearLayout.LayoutParams(584, 890));
        this.nuyexwrvgi.setPadding(57, 191, 183, 85);
        linearLayout.addView(this.nuyexwrvgi);
        this.nuyexwrvgi.setBackgroundColor(Color.parseColor("#f5d8fe"));
        FrameLayout frameLayout5 = new FrameLayout(this);
        this.rcrpahugbt = frameLayout5;
        frameLayout5.setLayoutParams(new LinearLayout.LayoutParams(410, 1718));
        this.rcrpahugbt.setPadding(102, 50, 41, 177);
        linearLayout.addView(this.rcrpahugbt);
        this.rcrpahugbt.setBackgroundColor(Color.parseColor("#1550d0"));
        EditText editText6 = new EditText(this);
        this.aefwnbdpgj = editText6;
        editText6.setLayoutParams(new LinearLayout.LayoutParams(1495, 710));
        this.aefwnbdpgj.setPadding(20, 112, 172, 135);
        linearLayout.addView(this.aefwnbdpgj);
        this.aefwnbdpgj.setBackgroundColor(Color.parseColor("#10b31e"));
        Button button7 = new Button(this);
        this.zruafmdpsb = button7;
        button7.setLayoutParams(new LinearLayout.LayoutParams(566, 966));
        this.zruafmdpsb.setPadding(99, 97, 82, 39);
        linearLayout.addView(this.zruafmdpsb);
        this.zruafmdpsb.setBackgroundColor(Color.parseColor("#480ff2"));
        LinearLayout linearLayout7 = new LinearLayout(this);
        this.ycjpbxnsoq = linearLayout7;
        linearLayout7.setLayoutParams(new LinearLayout.LayoutParams(528, 1799));
        this.ycjpbxnsoq.setPadding(41, 71, 78, BDLocation.TypeServerDecryptError);
        linearLayout.addView(this.ycjpbxnsoq);
        this.ycjpbxnsoq.setBackgroundColor(Color.parseColor("#ce5737"));
        Spinner spinner9 = new Spinner(this);
        this.ywzwgpofzj = spinner9;
        spinner9.setLayoutParams(new LinearLayout.LayoutParams(1946, 1161));
        this.ywzwgpofzj.setPadding(96, 119, 155, 151);
        linearLayout.addView(this.ywzwgpofzj);
        this.ywzwgpofzj.setBackgroundColor(Color.parseColor("#e2d776"));
        RatingBar ratingBar4 = new RatingBar(this);
        this.nyzgeospng = ratingBar4;
        ratingBar4.setLayoutParams(new LinearLayout.LayoutParams(661, 1710));
        this.nyzgeospng.setPadding(183, 21, 99, 186);
        linearLayout.addView(this.nyzgeospng);
        this.nyzgeospng.setBackgroundColor(Color.parseColor("#88fbe1"));
        TimePicker timePicker4 = new TimePicker(this);
        this.lebrlphqyt = timePicker4;
        timePicker4.setLayoutParams(new LinearLayout.LayoutParams(1466, 1475));
        this.lebrlphqyt.setPadding(15, 70, 65, 21);
        linearLayout.addView(this.lebrlphqyt);
        this.lebrlphqyt.setBackgroundColor(Color.parseColor("#6a6bff"));
        TextView textView10 = new TextView(this);
        this.cxbihjgcjd = textView10;
        textView10.setLayoutParams(new LinearLayout.LayoutParams(1660, 1377));
        this.cxbihjgcjd.setPadding(107, 15, 11, 129);
        linearLayout.addView(this.cxbihjgcjd);
        this.cxbihjgcjd.setBackgroundColor(Color.parseColor("#f3363c"));
        TimePicker timePicker5 = new TimePicker(this);
        this.izpfjkumyh = timePicker5;
        timePicker5.setLayoutParams(new LinearLayout.LayoutParams(1795, 568));
        this.izpfjkumyh.setPadding(123, PictureConfig.CHOOSE_REQUEST, 7, 148);
        linearLayout.addView(this.izpfjkumyh);
        this.izpfjkumyh.setBackgroundColor(Color.parseColor("#6b8389"));
        ToggleButton toggleButton9 = new ToggleButton(this);
        this.dxahlbarut = toggleButton9;
        toggleButton9.setLayoutParams(new LinearLayout.LayoutParams(683, 1205));
        this.dxahlbarut.setPadding(6, 12, 57, 110);
        linearLayout.addView(this.dxahlbarut);
        this.dxahlbarut.setBackgroundColor(Color.parseColor("#629df5"));
        GridView gridView4 = new GridView(this);
        this.pvzwuaravt = gridView4;
        gridView4.setLayoutParams(new LinearLayout.LayoutParams(864, 674));
        this.pvzwuaravt.setPadding(PictureConfig.CHOOSE_REQUEST, 151, 166, 31);
        linearLayout.addView(this.pvzwuaravt);
        this.pvzwuaravt.setBackgroundColor(Color.parseColor("#b2514d"));
        ImageView imageView5 = new ImageView(this);
        this.wlbjzydvlf = imageView5;
        imageView5.setLayoutParams(new LinearLayout.LayoutParams(782, 548));
        this.wlbjzydvlf.setPadding(28, 66, 193, 87);
        linearLayout.addView(this.wlbjzydvlf);
        this.wlbjzydvlf.setBackgroundColor(Color.parseColor("#8e834e"));
        Button button8 = new Button(this);
        this.horqygmclj = button8;
        button8.setLayoutParams(new LinearLayout.LayoutParams(129, 650));
        this.horqygmclj.setPadding(72, 66, 48, 104);
        linearLayout.addView(this.horqygmclj);
        this.horqygmclj.setBackgroundColor(Color.parseColor("#17a399"));
        ToggleButton toggleButton10 = new ToggleButton(this);
        this.tkanblckqc = toggleButton10;
        toggleButton10.setLayoutParams(new LinearLayout.LayoutParams(1613, 1496));
        this.tkanblckqc.setPadding(66, 93, 17, 88);
        linearLayout.addView(this.tkanblckqc);
        this.tkanblckqc.setBackgroundColor(Color.parseColor("#9362c5"));
        TextView textView11 = new TextView(this);
        this.wqpfvxiowr = textView11;
        textView11.setLayoutParams(new LinearLayout.LayoutParams(1492, 1595));
        this.wqpfvxiowr.setPadding(122, 56, 134, 72);
        linearLayout.addView(this.wqpfvxiowr);
        this.wqpfvxiowr.setBackgroundColor(Color.parseColor("#11cb97"));
        Switch r26 = new Switch(this);
        this.qjpyflmbiw = r26;
        r26.setLayoutParams(new LinearLayout.LayoutParams(250, 1006));
        this.qjpyflmbiw.setPadding(54, 137, 163, 2);
        linearLayout.addView(this.qjpyflmbiw);
        this.qjpyflmbiw.setBackgroundColor(Color.parseColor("#7541ac"));
        GridView gridView5 = new GridView(this);
        this.hfqbiadgyu = gridView5;
        gridView5.setLayoutParams(new LinearLayout.LayoutParams(1454, BDLocation.TypeServerDecryptError));
        this.hfqbiadgyu.setPadding(181, 4, 80, 72);
        linearLayout.addView(this.hfqbiadgyu);
        this.hfqbiadgyu.setBackgroundColor(Color.parseColor("#55b8c5"));
        CheckBox checkBox7 = new CheckBox(this);
        this.aiqirjfvgx = checkBox7;
        checkBox7.setLayoutParams(new LinearLayout.LayoutParams(1440, 580));
        this.aiqirjfvgx.setPadding(129, 60, 72, 15);
        linearLayout.addView(this.aiqirjfvgx);
        this.aiqirjfvgx.setBackgroundColor(Color.parseColor("#bc3805"));
        GridView gridView6 = new GridView(this);
        this.srbqhexwuc = gridView6;
        gridView6.setLayoutParams(new LinearLayout.LayoutParams(721, 1713));
        this.srbqhexwuc.setPadding(40, 32, 117, 177);
        linearLayout.addView(this.srbqhexwuc);
        this.srbqhexwuc.setBackgroundColor(Color.parseColor("#e5f215"));
        ListView listView7 = new ListView(this);
        this.ijspdrdwiw = listView7;
        listView7.setLayoutParams(new LinearLayout.LayoutParams(1939, 1644));
        this.ijspdrdwiw.setPadding(31, 173, 21, 153);
        linearLayout.addView(this.ijspdrdwiw);
        this.ijspdrdwiw.setBackgroundColor(Color.parseColor("#667422"));
        RelativeLayout relativeLayout5 = new RelativeLayout(this);
        this.tcnckefdrl = relativeLayout5;
        relativeLayout5.setLayoutParams(new LinearLayout.LayoutParams(1046, 1048));
        this.tcnckefdrl.setPadding(139, 115, 133, 192);
        linearLayout.addView(this.tcnckefdrl);
        this.tcnckefdrl.setBackgroundColor(Color.parseColor("#c9b5cf"));
        LinearLayout linearLayout8 = new LinearLayout(this);
        this.nlwgdzkvhw = linearLayout8;
        linearLayout8.setLayoutParams(new LinearLayout.LayoutParams(197, 1752));
        this.nlwgdzkvhw.setPadding(PictureConfig.CHOOSE_REQUEST, 144, 136, 70);
        linearLayout.addView(this.nlwgdzkvhw);
        this.nlwgdzkvhw.setBackgroundColor(Color.parseColor("#7e9a84"));
        ToggleButton toggleButton11 = new ToggleButton(this);
        this.suczxumvew = toggleButton11;
        toggleButton11.setLayoutParams(new LinearLayout.LayoutParams(1443, 1115));
        this.suczxumvew.setPadding(119, 33, 172, 37);
        linearLayout.addView(this.suczxumvew);
        this.suczxumvew.setBackgroundColor(Color.parseColor("#a7e12f"));
        Button button9 = new Button(this);
        this.hzeybzgzij = button9;
        button9.setLayoutParams(new LinearLayout.LayoutParams(1997, 1229));
        this.hzeybzgzij.setPadding(103, 32, 2, 135);
        linearLayout.addView(this.hzeybzgzij);
        this.hzeybzgzij.setBackgroundColor(Color.parseColor("#d06eee"));
        ProgressBar progressBar9 = new ProgressBar(this);
        this.lhstwvilqd = progressBar9;
        progressBar9.setLayoutParams(new LinearLayout.LayoutParams(933, 720));
        this.lhstwvilqd.setPadding(128, 112, 81, 183);
        linearLayout.addView(this.lhstwvilqd);
        this.lhstwvilqd.setBackgroundColor(Color.parseColor("#d2cf20"));
        RatingBar ratingBar5 = new RatingBar(this);
        this.dtzlptcgrg = ratingBar5;
        ratingBar5.setLayoutParams(new LinearLayout.LayoutParams(1360, 369));
        this.dtzlptcgrg.setPadding(185, 172, 69, 117);
        linearLayout.addView(this.dtzlptcgrg);
        this.dtzlptcgrg.setBackgroundColor(Color.parseColor("#2c3363"));
        TimePicker timePicker6 = new TimePicker(this);
        this.vhtrrsshro = timePicker6;
        timePicker6.setLayoutParams(new LinearLayout.LayoutParams(565, 1790));
        this.vhtrrsshro.setPadding(164, 102, 129, 26);
        linearLayout.addView(this.vhtrrsshro);
        this.vhtrrsshro.setBackgroundColor(Color.parseColor("#5dc9b6"));
        EditText editText7 = new EditText(this);
        this.rxgohrccpf = editText7;
        editText7.setLayoutParams(new LinearLayout.LayoutParams(1707, 845));
        this.rxgohrccpf.setPadding(61, 19, 118, 75);
        linearLayout.addView(this.rxgohrccpf);
        this.rxgohrccpf.setBackgroundColor(Color.parseColor("#d574b8"));
        EditText editText8 = new EditText(this);
        this.kytedviniz = editText8;
        editText8.setLayoutParams(new LinearLayout.LayoutParams(598, 1488));
        this.kytedviniz.setPadding(180, 52, 191, 138);
        linearLayout.addView(this.kytedviniz);
        this.kytedviniz.setBackgroundColor(Color.parseColor("#df18b2"));
        RadioButton radioButton7 = new RadioButton(this);
        this.kslebgvrqz = radioButton7;
        radioButton7.setLayoutParams(new LinearLayout.LayoutParams(550, 460));
        this.kslebgvrqz.setPadding(88, 153, 4, 39);
        linearLayout.addView(this.kslebgvrqz);
        this.kslebgvrqz.setBackgroundColor(Color.parseColor("#919175"));
        CheckBox checkBox8 = new CheckBox(this);
        this.ldwcjmrmfl = checkBox8;
        checkBox8.setLayoutParams(new LinearLayout.LayoutParams(1796, 1392));
        this.ldwcjmrmfl.setPadding(129, 71, 95, 166);
        linearLayout.addView(this.ldwcjmrmfl);
        this.ldwcjmrmfl.setBackgroundColor(Color.parseColor("#58f419"));
    }
}
