package com.smartapp.b.mattqajkje;

import android.app.Activity;
import android.graphics.Color;
import android.os.Bundle;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.CheckBox;
import android.widget.DatePicker;
import android.widget.EditText;
import android.widget.FrameLayout;
import android.widget.GridView;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ListView;
import android.widget.ProgressBar;
import android.widget.RadioButton;
import android.widget.RatingBar;
import android.widget.RelativeLayout;
import android.widget.ScrollView;
import android.widget.SeekBar;
import android.widget.Spinner;
import android.widget.Switch;
import android.widget.TableLayout;
import android.widget.TextView;
import android.widget.TimePicker;
import android.widget.ToggleButton;
import android.widget.ViewFlipper;
import androidx.constraintlayout.core.motion.utils.TypedValues;
import androidx.core.view.PointerIconCompat;
import com.baidu.location.BDLocation;
import com.luck.picture.lib.config.PictureConfig;
import com.realsil.sdk.audioconnect.localplayback.LocalPlaybackConstants;
import okhttp3.internal.ws.WebSocketProtocol;

/* loaded from: classes4.dex */
public class AkgmzsebqviActivity extends Activity {
    CheckBox aiyhittwlt;
    FrameLayout ajsrczcosw;
    RadioButton aledjfyglc;
    ProgressBar alelfjeads;
    RatingBar artwtpmpdr;
    Switch awofnuteon;
    ViewFlipper bcnvgdabeq;
    SeekBar bdxsyiltpj;
    SeekBar bnusqzllrx;
    ListView bpmlifosqr;
    RelativeLayout bqqhdtjoyk;
    CheckBox brkqtbwqlk;
    Spinner bsgmaeldxu;
    CheckBox bsyghjablv;
    ToggleButton cctcfzuqqs;
    Spinner cdkjozvxib;
    LinearLayout cekjhprapt;
    DatePicker cgbophjsxv;
    RatingBar cgqaskzsmi;
    FrameLayout cidunggdjm;
    RatingBar cllfzlwmsc;
    RelativeLayout cnohzvrmtj;
    Spinner cqkxbwqatk;
    Spinner crcqbhmovu;
    DatePicker crqyqyypnx;
    EditText daysuvvuyr;
    Spinner ddebygwahk;
    ToggleButton dflxtldtfb;
    DatePicker dknkotowfn;
    ScrollView dmcktxelxm;
    RadioButton dmsixcqjzd;
    GridView dplkkrrvfh;
    GridView dvbwcdmuut;
    ListView dzteclaeji;
    Button eeqtrloavo;
    ViewFlipper efsygffcsm;
    TimePicker eucculxtjw;
    ProgressBar evskhhvlnf;
    ToggleButton exndtsbidw;
    RadioButton exvtzfzhof;
    GridView fbyifznawu;
    Spinner fcsugiatxh;
    ListView fjxspqhdms;
    Switch fkwuszivko;
    TextView fllgprnjnw;
    Button fomywqqrek;
    Button fqmwgacxdl;
    ListView fuuuqorrka;
    ProgressBar fvehkqbvpq;
    ViewFlipper fyfcvzrekm;
    SeekBar fzmsvcgmvk;
    GridView fzobmajlby;
    ScrollView gfyuiltrnr;
    Button gkrpavbdkh;
    FrameLayout gmyshpwhlp;
    TimePicker gozggdbdgu;
    Button gpdvylguez;
    Button gwrutwmxdj;
    ProgressBar hfnsnbuldi;
    ToggleButton hjlewjpflv;
    DatePicker hooumbpylg;
    Spinner hsiwuhpshm;
    RatingBar hterbnthwc;
    ListView htjaskjnab;
    SeekBar htqvvntdgo;
    Button hxakiremod;
    CheckBox icgcnxargp;
    ToggleButton idbeobqisn;
    TextView ihnpvanmam;
    RadioButton iigjimppiw;
    DatePicker ikvfotzcyg;
    RatingBar imvsqcbkvo;
    RelativeLayout iothogwpgz;
    TextView iplugxblmx;
    SeekBar isxxiznixj;
    Button ixzrzsiplf;
    FrameLayout iykqunmtvm;
    RelativeLayout jdzzmpfoqs;
    ListView jiyicovgks;
    Spinner jkvchjetag;
    LinearLayout jlmiqbwtkf;
    EditText jlnwuiblmk;
    CheckBox jrvmuemigx;
    ViewFlipper kbzlzusfgd;
    ListView kffuaxdzuo;
    TimePicker kgiqlsvrgp;
    DatePicker kihvrlkmcm;
    LinearLayout koybjkfjon;
    SeekBar krhkncntxy;
    DatePicker ksuuipddom;
    EditText kykxkhlcyd;
    ImageView larbxzcyhc;
    LinearLayout lauzxxadat;
    ListView lbynipvokf;
    SeekBar lchforyeum;
    ImageView lfpdkbvnoo;
    Spinner lgasrltqcr;
    ImageView lixzteglvk;
    DatePicker lkgaezuqtr;
    Button llsxtvjbjf;
    TableLayout losxxnikan;
    CheckBox lqskbuflrq;
    TextView ltahhglmrh;
    CheckBox lunlrcuypu;
    ScrollView lwwpyvgxch;
    ListView lywhjodaad;
    RelativeLayout mizmioaeyh;
    ScrollView mntrqhquaj;
    LinearLayout mpcsnhtyai;
    RelativeLayout mzltafyqip;
    TextView nisodtrxdf;
    Switch njcwlthapy;
    TimePicker njthwulbox;
    TextView nlzujdwbxm;
    Button nokfcrhomu;
    ViewFlipper npetphixfe;
    RadioButton nruosplwzg;
    RelativeLayout nvqcciqzwc;
    SeekBar nwzrvdwiuo;
    ProgressBar odnckacwww;
    ProgressBar oeeakdcrsc;
    ToggleButton ofpzmhsxcm;
    ViewFlipper owlgvxnqsd;
    ScrollView owtbympsuj;
    ImageView oxfvsujqcc;
    RatingBar pdzsnkzzjm;
    ToggleButton pflqszojyd;
    EditText piedrqdwyn;
    RadioButton pozjgqiilv;
    ListView ppvnofynuj;
    RatingBar pqdwoiqczc;
    ImageView pssxmfskuu;
    Button ptyjiiwxms;
    EditText pwmllmqmzl;
    Spinner pxwmqgdcve;
    RatingBar pyvtejkfrc;
    ProgressBar pzdliwjhov;
    TimePicker qavunaaiso;
    ListView qksljaliaa;
    Switch qlizqrhcov;
    RatingBar qostqibwlu;
    TimePicker qvhfwtzdul;
    DatePicker rbgfhyvdxi;
    RatingBar rcympsjllh;
    ViewFlipper rjerttjcos;
    LinearLayout rjsxwrhpsi;
    Spinner rkaawdalxj;
    ImageView rkqfmfpwfj;
    ImageView rllguoxtoc;
    Switch rmdhddrdmr;
    DatePicker rrhtizmzee;
    TimePicker rtmpxozzmg;
    GridView sizqedkvll;
    RadioButton slorwgwhya;
    Spinner snybqxhkrz;
    ViewFlipper sohtblwbax;
    LinearLayout sqfeguyibl;
    ScrollView sqwptyxmix;
    DatePicker stgjlnjpld;
    RelativeLayout stqzkhrqvh;
    ProgressBar syzalsbsld;
    ScrollView szdnqwerex;
    SeekBar tcvxohcthe;
    SeekBar tdwtfrlvae;
    TextView tkdggbrlql;
    SeekBar tknrujjdsc;
    ToggleButton tnjppbfkpw;
    ImageView tnkywhsmeo;
    SeekBar tnvbroneks;
    GridView tpsuqyygod;
    FrameLayout tvcjkayfoa;
    ToggleButton uaqrjxogqx;
    ToggleButton uboapkvmnz;
    Spinner ubytesxrgl;
    CheckBox ugzevbjqen;
    EditText uikzlfxeca;
    DatePicker ulofzvlhnz;
    FrameLayout upcubwlcej;
    TableLayout uqkjgoybfd;
    DatePicker utgkpsaycs;
    DatePicker uubowtmxpd;
    RatingBar uvqqazwldw;
    GridView uwsilflhcb;
    CheckBox uyeoptgjxi;
    DatePicker varniadnar;
    RatingBar vcodhdvgbf;
    SeekBar vdcxhxbobt;
    DatePicker vedgthohhd;
    ToggleButton vhxqwsbhuk;
    RelativeLayout vipszwdenj;
    Switch vkhequuuie;
    ScrollView vkisbglotx;
    ImageView vknjaupqgp;
    ListView vrjlwaaiuv;
    TableLayout vrjrhcvaaf;
    RelativeLayout vrpafvlmmi;
    Button vrpufdfpry;
    EditText vuqmyldhid;
    RatingBar vwyoupazoe;
    TextView vxuejeanmh;
    LinearLayout wbbgmhzhox;
    RadioButton wcgeqcttxc;
    LinearLayout wehzqmcbns;
    ImageView whslffersy;
    ViewFlipper wjsljmshsa;
    FrameLayout wnnregctpz;
    ProgressBar wqywospdag;
    ScrollView wzdcuxqwoh;
    ViewFlipper xikiqyiumz;
    RelativeLayout xiwhmdwuef;
    SeekBar xjxhbczsrs;
    RelativeLayout xmxzszzrza;
    TimePicker xntowruoer;
    TextView xrfeqslvlj;
    GridView xsomubwyff;
    TextView xspiiajvvv;
    FrameLayout xtjhchgvtv;
    ProgressBar xurfyochjn;
    LinearLayout xvyhtdfxui;
    ProgressBar xwebikitgd;
    ToggleButton yagqqvvugv;
    DatePicker yawznmnwje;
    ProgressBar ybufkizbod;
    ProgressBar ycdnnvtgny;
    ViewFlipper ycsvstttpj;
    ToggleButton ymlkqyazep;
    RadioButton ymqefciusl;
    DatePicker ytbqusqxoa;
    ToggleButton yvuhdfetfa;
    DatePicker zampvujtld;
    TimePicker zbxujwveeh;
    SeekBar zfqymjmmur;
    TableLayout zgowfcgjia;
    CheckBox zjimyffozz;
    RelativeLayout zjyuntjfdy;
    TableLayout zlbbulxtqh;
    TimePicker zpivibhjgx;
    TextView zvjkyrfjej;

    @Override // android.app.Activity
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        LinearLayout linearLayout = new LinearLayout(this);
        setContentView(linearLayout);
        linearLayout.setLayoutParams(new ViewGroup.LayoutParams(-1, -1));
        linearLayout.setOrientation(1);
        linearLayout.setBackgroundColor(Color.parseColor("#4c1fc4"));
        ViewFlipper viewFlipper = new ViewFlipper(this);
        this.npetphixfe = viewFlipper;
        viewFlipper.setLayoutParams(new LinearLayout.LayoutParams(1926, 1485));
        this.npetphixfe.setPadding(55, 18, 148, 98);
        linearLayout.addView(this.npetphixfe);
        this.npetphixfe.setBackgroundColor(Color.parseColor("#1fe284"));
        ScrollView scrollView = new ScrollView(this);
        this.mntrqhquaj = scrollView;
        scrollView.setLayoutParams(new LinearLayout.LayoutParams(64, 196));
        this.mntrqhquaj.setPadding(140, 118, 13, 25);
        linearLayout.addView(this.mntrqhquaj);
        this.mntrqhquaj.setBackgroundColor(Color.parseColor("#f7bd19"));
        RelativeLayout relativeLayout = new RelativeLayout(this);
        this.vrpafvlmmi = relativeLayout;
        relativeLayout.setLayoutParams(new LinearLayout.LayoutParams(1272, 1230));
        this.vrpafvlmmi.setPadding(197, 8, 107, 58);
        linearLayout.addView(this.vrpafvlmmi);
        this.vrpafvlmmi.setBackgroundColor(Color.parseColor("#4bde9c"));
        Button button = new Button(this);
        this.hxakiremod = button;
        button.setLayoutParams(new LinearLayout.LayoutParams(1103, 1255));
        this.hxakiremod.setPadding(197, 73, 112, 12);
        linearLayout.addView(this.hxakiremod);
        this.hxakiremod.setBackgroundColor(Color.parseColor("#f71c56"));
        RadioButton radioButton = new RadioButton(this);
        this.iigjimppiw = radioButton;
        radioButton.setLayoutParams(new LinearLayout.LayoutParams(1042, 597));
        this.iigjimppiw.setPadding(38, 100, 27, 194);
        linearLayout.addView(this.iigjimppiw);
        this.iigjimppiw.setBackgroundColor(Color.parseColor("#df514f"));
        DatePicker datePicker = new DatePicker(this);
        this.ksuuipddom = datePicker;
        datePicker.setLayoutParams(new LinearLayout.LayoutParams(438, 1660));
        this.ksuuipddom.setPadding(102, 91, 164, 13);
        linearLayout.addView(this.ksuuipddom);
        this.ksuuipddom.setBackgroundColor(Color.parseColor("#e520a1"));
        ViewFlipper viewFlipper2 = new ViewFlipper(this);
        this.kbzlzusfgd = viewFlipper2;
        viewFlipper2.setLayoutParams(new LinearLayout.LayoutParams(772, 1431));
        this.kbzlzusfgd.setPadding(127, 18, 26, 89);
        linearLayout.addView(this.kbzlzusfgd);
        this.kbzlzusfgd.setBackgroundColor(Color.parseColor("#226164"));
        TimePicker timePicker = new TimePicker(this);
        this.njthwulbox = timePicker;
        timePicker.setLayoutParams(new LinearLayout.LayoutParams(1082, 1531));
        this.njthwulbox.setPadding(168, 172, 107, 93);
        linearLayout.addView(this.njthwulbox);
        this.njthwulbox.setBackground(new Ycgtfoksant());
        Spinner spinner = new Spinner(this);
        this.crcqbhmovu = spinner;
        spinner.setLayoutParams(new LinearLayout.LayoutParams(1164, 1239));
        this.crcqbhmovu.setPadding(194, 86, 61, 74);
        linearLayout.addView(this.crcqbhmovu);
        this.crcqbhmovu.setBackgroundColor(Color.parseColor("#4a39eb"));
        Spinner spinner2 = new Spinner(this);
        this.lgasrltqcr = spinner2;
        spinner2.setLayoutParams(new LinearLayout.LayoutParams(1635, 563));
        this.lgasrltqcr.setPadding(141, 104, 199, 44);
        linearLayout.addView(this.lgasrltqcr);
        this.lgasrltqcr.setBackgroundColor(Color.parseColor("#9d26e0"));
        GridView gridView = new GridView(this);
        this.fzobmajlby = gridView;
        gridView.setLayoutParams(new LinearLayout.LayoutParams(1326, 112));
        this.fzobmajlby.setPadding(80, 56, 64, 184);
        linearLayout.addView(this.fzobmajlby);
        this.fzobmajlby.setBackgroundColor(Color.parseColor("#44fa36"));
        SeekBar seekBar = new SeekBar(this);
        this.bnusqzllrx = seekBar;
        seekBar.setLayoutParams(new LinearLayout.LayoutParams(1753, 1509));
        this.bnusqzllrx.setPadding(92, 143, 25, 85);
        linearLayout.addView(this.bnusqzllrx);
        this.bnusqzllrx.setBackgroundColor(Color.parseColor("#a7f597"));
        ViewFlipper viewFlipper3 = new ViewFlipper(this);
        this.xikiqyiumz = viewFlipper3;
        viewFlipper3.setLayoutParams(new LinearLayout.LayoutParams(1467, 1156));
        this.xikiqyiumz.setPadding(196, 101, 12, 185);
        linearLayout.addView(this.xikiqyiumz);
        this.xikiqyiumz.setBackgroundColor(Color.parseColor("#1b14df"));
        RelativeLayout relativeLayout2 = new RelativeLayout(this);
        this.zjyuntjfdy = relativeLayout2;
        relativeLayout2.setLayoutParams(new LinearLayout.LayoutParams(315, 893));
        this.zjyuntjfdy.setPadding(173, 57, 73, 24);
        linearLayout.addView(this.zjyuntjfdy);
        this.zjyuntjfdy.setBackgroundColor(Color.parseColor("#9c8ce0"));
        ScrollView scrollView2 = new ScrollView(this);
        this.sqwptyxmix = scrollView2;
        scrollView2.setLayoutParams(new LinearLayout.LayoutParams(1432, 1721));
        this.sqwptyxmix.setPadding(180, 42, 174, 86);
        linearLayout.addView(this.sqwptyxmix);
        this.sqwptyxmix.setBackgroundColor(Color.parseColor("#a78fec"));
        EditText editText = new EditText(this);
        this.vuqmyldhid = editText;
        editText.setLayoutParams(new LinearLayout.LayoutParams(267, 811));
        this.vuqmyldhid.setPadding(164, 194, 129, 146);
        linearLayout.addView(this.vuqmyldhid);
        this.vuqmyldhid.setBackgroundColor(Color.parseColor("#e30574"));
        Switch r2 = new Switch(this);
        this.vkhequuuie = r2;
        r2.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.Custom.TYPE_INT, 954));
        this.vkhequuuie.setPadding(155, BDLocation.TypeServerDecryptError, 93, 195);
        linearLayout.addView(this.vkhequuuie);
        this.vkhequuuie.setBackgroundColor(Color.parseColor("#4fd33c"));
        CheckBox checkBox = new CheckBox(this);
        this.brkqtbwqlk = checkBox;
        checkBox.setLayoutParams(new LinearLayout.LayoutParams(647, 1058));
        this.brkqtbwqlk.setPadding(71, 8, 166, 39);
        linearLayout.addView(this.brkqtbwqlk);
        this.brkqtbwqlk.setBackgroundColor(Color.parseColor("#fed0ab"));
        Switch r22 = new Switch(this);
        this.rmdhddrdmr = r22;
        r22.setLayoutParams(new LinearLayout.LayoutParams(618, 288));
        this.rmdhddrdmr.setPadding(51, 173, 42, 159);
        linearLayout.addView(this.rmdhddrdmr);
        this.rmdhddrdmr.setBackgroundColor(Color.parseColor("#1950dc"));
        ImageView imageView = new ImageView(this);
        this.lixzteglvk = imageView;
        imageView.setLayoutParams(new LinearLayout.LayoutParams(1781, 1733));
        this.lixzteglvk.setPadding(168, 155, 182, 23);
        linearLayout.addView(this.lixzteglvk);
        this.lixzteglvk.setBackgroundColor(Color.parseColor("#3be443"));
        TableLayout tableLayout = new TableLayout(this);
        this.uqkjgoybfd = tableLayout;
        tableLayout.setLayoutParams(new LinearLayout.LayoutParams(1181, 795));
        this.uqkjgoybfd.setPadding(18, 171, BDLocation.TypeCoarseLocation, 89);
        linearLayout.addView(this.uqkjgoybfd);
        this.uqkjgoybfd.setBackgroundColor(Color.parseColor("#ed327b"));
        TableLayout tableLayout2 = new TableLayout(this);
        this.vrjrhcvaaf = tableLayout2;
        tableLayout2.setLayoutParams(new LinearLayout.LayoutParams(1206, 43));
        this.vrjrhcvaaf.setPadding(120, 196, BDLocation.TypeServerError, 194);
        linearLayout.addView(this.vrjrhcvaaf);
        this.vrjrhcvaaf.setBackgroundColor(Color.parseColor("#28d688"));
        ScrollView scrollView3 = new ScrollView(this);
        this.gfyuiltrnr = scrollView3;
        scrollView3.setLayoutParams(new LinearLayout.LayoutParams(1997, 936));
        this.gfyuiltrnr.setPadding(47, 7, 84, 117);
        linearLayout.addView(this.gfyuiltrnr);
        this.gfyuiltrnr.setBackgroundColor(Color.parseColor("#456fa4"));
        DatePicker datePicker2 = new DatePicker(this);
        this.varniadnar = datePicker2;
        datePicker2.setLayoutParams(new LinearLayout.LayoutParams(1190, 301));
        this.varniadnar.setPadding(164, 166, 53, 196);
        linearLayout.addView(this.varniadnar);
        this.varniadnar.setBackgroundColor(Color.parseColor("#1d6ed6"));
        RelativeLayout relativeLayout3 = new RelativeLayout(this);
        this.jdzzmpfoqs = relativeLayout3;
        relativeLayout3.setLayoutParams(new LinearLayout.LayoutParams(831, 665));
        this.jdzzmpfoqs.setPadding(197, 53, 30, 133);
        linearLayout.addView(this.jdzzmpfoqs);
        this.jdzzmpfoqs.setBackgroundColor(Color.parseColor("#f54bf1"));
        ToggleButton toggleButton = new ToggleButton(this);
        this.idbeobqisn = toggleButton;
        toggleButton.setLayoutParams(new LinearLayout.LayoutParams(105, 1731));
        this.idbeobqisn.setPadding(27, 153, 187, 130);
        linearLayout.addView(this.idbeobqisn);
        this.idbeobqisn.setBackgroundColor(Color.parseColor("#813470"));
        Spinner spinner3 = new Spinner(this);
        this.cqkxbwqatk = spinner3;
        spinner3.setLayoutParams(new LinearLayout.LayoutParams(1607, 961));
        this.cqkxbwqatk.setPadding(149, 60, 44, 121);
        linearLayout.addView(this.cqkxbwqatk);
        this.cqkxbwqatk.setBackgroundColor(Color.parseColor("#b454f4"));
        Button button2 = new Button(this);
        this.gkrpavbdkh = button2;
        button2.setLayoutParams(new LinearLayout.LayoutParams(558, 1643));
        this.gkrpavbdkh.setPadding(196, 98, WebSocketProtocol.PAYLOAD_SHORT, 19);
        linearLayout.addView(this.gkrpavbdkh);
        this.gkrpavbdkh.setBackgroundColor(Color.parseColor("#01ccfd"));
        ListView listView = new ListView(this);
        this.dzteclaeji = listView;
        listView.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.MotionType.TYPE_POLAR_RELATIVETO, 1973));
        this.dzteclaeji.setPadding(15, 101, 84, 65);
        linearLayout.addView(this.dzteclaeji);
        this.dzteclaeji.setBackgroundColor(Color.parseColor("#9f34c1"));
        Spinner spinner4 = new Spinner(this);
        this.bsgmaeldxu = spinner4;
        spinner4.setLayoutParams(new LinearLayout.LayoutParams(638, 354));
        this.bsgmaeldxu.setPadding(106, 196, 144, 128);
        linearLayout.addView(this.bsgmaeldxu);
        this.bsgmaeldxu.setBackgroundColor(Color.parseColor("#ff33b6"));
        Button button3 = new Button(this);
        this.gpdvylguez = button3;
        button3.setLayoutParams(new LinearLayout.LayoutParams(1489, 828));
        this.gpdvylguez.setPadding(8, 138, 194, 30);
        linearLayout.addView(this.gpdvylguez);
        this.gpdvylguez.setBackgroundColor(Color.parseColor("#0667a3"));
        RadioButton radioButton2 = new RadioButton(this);
        this.exvtzfzhof = radioButton2;
        radioButton2.setLayoutParams(new LinearLayout.LayoutParams(1133, 1193));
        this.exvtzfzhof.setPadding(115, 131, 82, 173);
        linearLayout.addView(this.exvtzfzhof);
        this.exvtzfzhof.setBackgroundColor(Color.parseColor("#b1286c"));
        RadioButton radioButton3 = new RadioButton(this);
        this.aledjfyglc = radioButton3;
        radioButton3.setLayoutParams(new LinearLayout.LayoutParams(1593, 1873));
        this.aledjfyglc.setPadding(148, 73, 92, 61);
        linearLayout.addView(this.aledjfyglc);
        this.aledjfyglc.setBackgroundColor(Color.parseColor("#af89bb"));
        TextView textView = new TextView(this);
        this.nlzujdwbxm = textView;
        textView.setLayoutParams(new LinearLayout.LayoutParams(342, 1410));
        this.nlzujdwbxm.setPadding(171, 84, 152, 191);
        linearLayout.addView(this.nlzujdwbxm);
        this.nlzujdwbxm.setBackgroundColor(Color.parseColor("#4ef6ca"));
        ListView listView2 = new ListView(this);
        this.jiyicovgks = listView2;
        listView2.setLayoutParams(new LinearLayout.LayoutParams(1698, 572));
        this.jiyicovgks.setPadding(4, 32, 35, 76);
        linearLayout.addView(this.jiyicovgks);
        this.jiyicovgks.setBackgroundColor(Color.parseColor("#0bd622"));
        CheckBox checkBox2 = new CheckBox(this);
        this.jrvmuemigx = checkBox2;
        checkBox2.setLayoutParams(new LinearLayout.LayoutParams(1137, 385));
        this.jrvmuemigx.setPadding(68, 15, 199, 148);
        linearLayout.addView(this.jrvmuemigx);
        this.jrvmuemigx.setBackgroundColor(Color.parseColor("#c4dd87"));
        ProgressBar progressBar = new ProgressBar(this);
        this.syzalsbsld = progressBar;
        progressBar.setLayoutParams(new LinearLayout.LayoutParams(113, 1517));
        this.syzalsbsld.setPadding(159, 23, PictureConfig.CHOOSE_REQUEST, 147);
        linearLayout.addView(this.syzalsbsld);
        this.syzalsbsld.setBackgroundColor(Color.parseColor("#080557"));
        ToggleButton toggleButton2 = new ToggleButton(this);
        this.tnjppbfkpw = toggleButton2;
        toggleButton2.setLayoutParams(new LinearLayout.LayoutParams(1903, 1373));
        this.tnjppbfkpw.setPadding(159, 182, 104, 63);
        linearLayout.addView(this.tnjppbfkpw);
        this.tnjppbfkpw.setBackgroundColor(Color.parseColor("#f07589"));
        RatingBar ratingBar = new RatingBar(this);
        this.vwyoupazoe = ratingBar;
        ratingBar.setLayoutParams(new LinearLayout.LayoutParams(1970, TypedValues.MotionType.TYPE_QUANTIZE_INTERPOLATOR_TYPE));
        this.vwyoupazoe.setPadding(180, 97, 145, 197);
        linearLayout.addView(this.vwyoupazoe);
        this.vwyoupazoe.setBackgroundColor(Color.parseColor("#d0ff1d"));
        RadioButton radioButton4 = new RadioButton(this);
        this.slorwgwhya = radioButton4;
        radioButton4.setLayoutParams(new LinearLayout.LayoutParams(1674, 829));
        this.slorwgwhya.setPadding(139, 156, 5, 10);
        linearLayout.addView(this.slorwgwhya);
        this.slorwgwhya.setBackgroundColor(Color.parseColor("#6d067b"));
        RelativeLayout relativeLayout4 = new RelativeLayout(this);
        this.xmxzszzrza = relativeLayout4;
        relativeLayout4.setLayoutParams(new LinearLayout.LayoutParams(1742, 1437));
        this.xmxzszzrza.setPadding(164, 11, 187, 142);
        linearLayout.addView(this.xmxzszzrza);
        this.xmxzszzrza.setBackgroundColor(Color.parseColor("#55a366"));
        ImageView imageView2 = new ImageView(this);
        this.tnkywhsmeo = imageView2;
        imageView2.setLayoutParams(new LinearLayout.LayoutParams(9, 1644));
        this.tnkywhsmeo.setPadding(172, 199, 90, 59);
        linearLayout.addView(this.tnkywhsmeo);
        this.tnkywhsmeo.setBackgroundColor(Color.parseColor("#5b2246"));
        Button button4 = new Button(this);
        this.ixzrzsiplf = button4;
        button4.setLayoutParams(new LinearLayout.LayoutParams(1208, 1520));
        this.ixzrzsiplf.setPadding(131, 164, 11, 179);
        linearLayout.addView(this.ixzrzsiplf);
        this.ixzrzsiplf.setBackgroundColor(Color.parseColor("#13388a"));
        ImageView imageView3 = new ImageView(this);
        this.oxfvsujqcc = imageView3;
        imageView3.setLayoutParams(new LinearLayout.LayoutParams(569, 453));
        this.oxfvsujqcc.setPadding(131, 39, 20, 184);
        linearLayout.addView(this.oxfvsujqcc);
        this.oxfvsujqcc.setBackgroundColor(Color.parseColor("#2f1957"));
        RelativeLayout relativeLayout5 = new RelativeLayout(this);
        this.nvqcciqzwc = relativeLayout5;
        relativeLayout5.setLayoutParams(new LinearLayout.LayoutParams(1114, 1057));
        this.nvqcciqzwc.setPadding(190, 77, 59, 61);
        linearLayout.addView(this.nvqcciqzwc);
        this.nvqcciqzwc.setBackgroundColor(Color.parseColor("#dd4cbf"));
        Button button5 = new Button(this);
        this.fomywqqrek = button5;
        button5.setLayoutParams(new LinearLayout.LayoutParams(1364, 1928));
        this.fomywqqrek.setPadding(75, WebSocketProtocol.PAYLOAD_SHORT, 59, 59);
        linearLayout.addView(this.fomywqqrek);
        this.fomywqqrek.setBackgroundColor(Color.parseColor("#55e380"));
        ScrollView scrollView4 = new ScrollView(this);
        this.vkisbglotx = scrollView4;
        scrollView4.setLayoutParams(new LinearLayout.LayoutParams(715, 1831));
        this.vkisbglotx.setPadding(77, 119, 23, 159);
        linearLayout.addView(this.vkisbglotx);
        this.vkisbglotx.setBackgroundColor(Color.parseColor("#48565c"));
        CheckBox checkBox3 = new CheckBox(this);
        this.bsyghjablv = checkBox3;
        checkBox3.setLayoutParams(new LinearLayout.LayoutParams(524, 132));
        this.bsyghjablv.setPadding(152, 190, 18, 87);
        linearLayout.addView(this.bsyghjablv);
        this.bsyghjablv.setBackgroundColor(Color.parseColor("#f3363a"));
        GridView gridView2 = new GridView(this);
        this.tpsuqyygod = gridView2;
        gridView2.setLayoutParams(new LinearLayout.LayoutParams(874, 1275));
        this.tpsuqyygod.setPadding(25, 112, 128, 116);
        linearLayout.addView(this.tpsuqyygod);
        this.tpsuqyygod.setBackgroundColor(Color.parseColor("#21da06"));
        ProgressBar progressBar2 = new ProgressBar(this);
        this.pzdliwjhov = progressBar2;
        progressBar2.setLayoutParams(new LinearLayout.LayoutParams(1870, 1708));
        this.pzdliwjhov.setPadding(145, 46, 53, 105);
        linearLayout.addView(this.pzdliwjhov);
        this.pzdliwjhov.setBackgroundColor(Color.parseColor("#e74f22"));
        ListView listView3 = new ListView(this);
        this.kffuaxdzuo = listView3;
        listView3.setLayoutParams(new LinearLayout.LayoutParams(1075, 680));
        this.kffuaxdzuo.setPadding(158, 134, 103, 146);
        linearLayout.addView(this.kffuaxdzuo);
        this.kffuaxdzuo.setBackgroundColor(Color.parseColor("#7658de"));
        TimePicker timePicker2 = new TimePicker(this);
        this.rtmpxozzmg = timePicker2;
        timePicker2.setLayoutParams(new LinearLayout.LayoutParams(418, 931));
        this.rtmpxozzmg.setPadding(70, 30, 184, 137);
        linearLayout.addView(this.rtmpxozzmg);
        this.rtmpxozzmg.setBackgroundColor(Color.parseColor("#c69770"));
        FrameLayout frameLayout = new FrameLayout(this);
        this.iykqunmtvm = frameLayout;
        frameLayout.setLayoutParams(new LinearLayout.LayoutParams(1064, 1051));
        this.iykqunmtvm.setPadding(40, 195, 189, 19);
        linearLayout.addView(this.iykqunmtvm);
        this.iykqunmtvm.setBackgroundColor(Color.parseColor("#16a246"));
        CheckBox checkBox4 = new CheckBox(this);
        this.icgcnxargp = checkBox4;
        checkBox4.setLayoutParams(new LinearLayout.LayoutParams(985, 688));
        this.icgcnxargp.setPadding(185, 71, 29, 199);
        linearLayout.addView(this.icgcnxargp);
        this.icgcnxargp.setBackgroundColor(Color.parseColor("#3d0b05"));
        FrameLayout frameLayout2 = new FrameLayout(this);
        this.cidunggdjm = frameLayout2;
        frameLayout2.setLayoutParams(new LinearLayout.LayoutParams(1703, 1493));
        this.cidunggdjm.setPadding(80, 0, 192, 175);
        linearLayout.addView(this.cidunggdjm);
        this.cidunggdjm.setBackgroundColor(Color.parseColor("#699602"));
        RelativeLayout relativeLayout6 = new RelativeLayout(this);
        this.vipszwdenj = relativeLayout6;
        relativeLayout6.setLayoutParams(new LinearLayout.LayoutParams(1149, 299));
        this.vipszwdenj.setPadding(135, 20, 69, 96);
        linearLayout.addView(this.vipszwdenj);
        this.vipszwdenj.setBackgroundColor(Color.parseColor("#3a91da"));
        TextView textView2 = new TextView(this);
        this.xrfeqslvlj = textView2;
        textView2.setLayoutParams(new LinearLayout.LayoutParams(889, 1685));
        this.xrfeqslvlj.setPadding(143, 186, 143, 171);
        linearLayout.addView(this.xrfeqslvlj);
        this.xrfeqslvlj.setBackgroundColor(Color.parseColor("#d71b6a"));
        RatingBar ratingBar2 = new RatingBar(this);
        this.pqdwoiqczc = ratingBar2;
        ratingBar2.setLayoutParams(new LinearLayout.LayoutParams(1074, 30));
        this.pqdwoiqczc.setPadding(103, 68, 109, BDLocation.TypeServerError);
        linearLayout.addView(this.pqdwoiqczc);
        this.pqdwoiqczc.setBackgroundColor(Color.parseColor("#150179"));
        LinearLayout linearLayout2 = new LinearLayout(this);
        this.sqfeguyibl = linearLayout2;
        linearLayout2.setLayoutParams(new LinearLayout.LayoutParams(1856, 1487));
        this.sqfeguyibl.setPadding(121, 81, 83, 46);
        linearLayout.addView(this.sqfeguyibl);
        this.sqfeguyibl.setBackgroundColor(Color.parseColor("#0fe192"));
        Button button6 = new Button(this);
        this.gwrutwmxdj = button6;
        button6.setLayoutParams(new LinearLayout.LayoutParams(1689, 1653));
        this.gwrutwmxdj.setPadding(32, 71, 105, 148);
        linearLayout.addView(this.gwrutwmxdj);
        this.gwrutwmxdj.setBackgroundColor(Color.parseColor("#ab676f"));
        TableLayout tableLayout3 = new TableLayout(this);
        this.zgowfcgjia = tableLayout3;
        tableLayout3.setLayoutParams(new LinearLayout.LayoutParams(1655, 1560));
        this.zgowfcgjia.setPadding(194, 37, 86, 95);
        linearLayout.addView(this.zgowfcgjia);
        this.zgowfcgjia.setBackgroundColor(Color.parseColor("#c17891"));
        ProgressBar progressBar3 = new ProgressBar(this);
        this.ybufkizbod = progressBar3;
        progressBar3.setLayoutParams(new LinearLayout.LayoutParams(1355, 463));
        this.ybufkizbod.setPadding(38, 149, 98, 73);
        linearLayout.addView(this.ybufkizbod);
        this.ybufkizbod.setBackgroundColor(Color.parseColor("#64732e"));
        Button button7 = new Button(this);
        this.vrpufdfpry = button7;
        button7.setLayoutParams(new LinearLayout.LayoutParams(1716, 1576));
        this.vrpufdfpry.setPadding(114, 96, 23, 17);
        linearLayout.addView(this.vrpufdfpry);
        this.vrpufdfpry.setBackgroundColor(Color.parseColor("#ec9217"));
        ListView listView4 = new ListView(this);
        this.vrjlwaaiuv = listView4;
        listView4.setLayoutParams(new LinearLayout.LayoutParams(617, 1260));
        this.vrjlwaaiuv.setPadding(172, 171, 90, 144);
        linearLayout.addView(this.vrjlwaaiuv);
        this.vrjlwaaiuv.setBackgroundColor(Color.parseColor("#ac3a1c"));
        ListView listView5 = new ListView(this);
        this.qksljaliaa = listView5;
        listView5.setLayoutParams(new LinearLayout.LayoutParams(1095, 392));
        this.qksljaliaa.setPadding(155, 119, 147, 112);
        linearLayout.addView(this.qksljaliaa);
        this.qksljaliaa.setBackgroundColor(Color.parseColor("#a8085e"));
        RadioButton radioButton5 = new RadioButton(this);
        this.ymqefciusl = radioButton5;
        radioButton5.setLayoutParams(new LinearLayout.LayoutParams(1601, 686));
        this.ymqefciusl.setPadding(74, 190, 197, 55);
        linearLayout.addView(this.ymqefciusl);
        this.ymqefciusl.setBackgroundColor(Color.parseColor("#8ad2e6"));
        TextView textView3 = new TextView(this);
        this.ihnpvanmam = textView3;
        textView3.setLayoutParams(new LinearLayout.LayoutParams(395, 1506));
        this.ihnpvanmam.setPadding(BDLocation.TypeCoarseLocation, 1, 179, 66);
        linearLayout.addView(this.ihnpvanmam);
        this.ihnpvanmam.setBackgroundColor(Color.parseColor("#e5f42a"));
        DatePicker datePicker3 = new DatePicker(this);
        this.rrhtizmzee = datePicker3;
        datePicker3.setLayoutParams(new LinearLayout.LayoutParams(1658, 1625));
        this.rrhtizmzee.setPadding(87, 30, 33, 101);
        linearLayout.addView(this.rrhtizmzee);
        this.rrhtizmzee.setBackgroundColor(Color.parseColor("#6a4690"));
        DatePicker datePicker4 = new DatePicker(this);
        this.rbgfhyvdxi = datePicker4;
        datePicker4.setLayoutParams(new LinearLayout.LayoutParams(1602, 1572));
        this.rbgfhyvdxi.setPadding(14, 198, 92, 31);
        linearLayout.addView(this.rbgfhyvdxi);
        this.rbgfhyvdxi.setBackgroundColor(Color.parseColor("#bfa827"));
        Button button8 = new Button(this);
        this.fqmwgacxdl = button8;
        button8.setLayoutParams(new LinearLayout.LayoutParams(1861, 676));
        this.fqmwgacxdl.setPadding(54, 61, 174, 187);
        linearLayout.addView(this.fqmwgacxdl);
        this.fqmwgacxdl.setBackgroundColor(Color.parseColor("#a8f524"));
        ImageView imageView4 = new ImageView(this);
        this.rkqfmfpwfj = imageView4;
        imageView4.setLayoutParams(new LinearLayout.LayoutParams(1772, 1134));
        this.rkqfmfpwfj.setPadding(150, 82, 168, 10);
        linearLayout.addView(this.rkqfmfpwfj);
        this.rkqfmfpwfj.setBackgroundColor(Color.parseColor("#71db38"));
        DatePicker datePicker5 = new DatePicker(this);
        this.vedgthohhd = datePicker5;
        datePicker5.setLayoutParams(new LinearLayout.LayoutParams(76, 1717));
        this.vedgthohhd.setPadding(3, 54, 117, 180);
        linearLayout.addView(this.vedgthohhd);
        this.vedgthohhd.setBackgroundColor(Color.parseColor("#04de09"));
        FrameLayout frameLayout3 = new FrameLayout(this);
        this.upcubwlcej = frameLayout3;
        frameLayout3.setLayoutParams(new LinearLayout.LayoutParams(BDLocation.TypeCoarseLocation, 767));
        this.upcubwlcej.setPadding(56, 137, 56, 102);
        linearLayout.addView(this.upcubwlcej);
        this.upcubwlcej.setBackgroundColor(Color.parseColor("#9a0abf"));
        ViewFlipper viewFlipper4 = new ViewFlipper(this);
        this.fyfcvzrekm = viewFlipper4;
        viewFlipper4.setLayoutParams(new LinearLayout.LayoutParams(822, 1257));
        this.fyfcvzrekm.setPadding(133, 88, 115, 46);
        linearLayout.addView(this.fyfcvzrekm);
        this.fyfcvzrekm.setBackgroundColor(Color.parseColor("#fe547f"));
        CheckBox checkBox5 = new CheckBox(this);
        this.ugzevbjqen = checkBox5;
        checkBox5.setLayoutParams(new LinearLayout.LayoutParams(1999, 1533));
        this.ugzevbjqen.setPadding(95, 154, 28, 34);
        linearLayout.addView(this.ugzevbjqen);
        this.ugzevbjqen.setBackgroundColor(Color.parseColor("#f52b28"));
        Switch r23 = new Switch(this);
        this.fkwuszivko = r23;
        r23.setLayoutParams(new LinearLayout.LayoutParams(1951, 1754));
        this.fkwuszivko.setPadding(69, 177, 53, 88);
        linearLayout.addView(this.fkwuszivko);
        this.fkwuszivko.setBackgroundColor(Color.parseColor("#fb0680"));
        FrameLayout frameLayout4 = new FrameLayout(this);
        this.ajsrczcosw = frameLayout4;
        frameLayout4.setLayoutParams(new LinearLayout.LayoutParams(1367, 1659));
        this.ajsrczcosw.setPadding(82, 45, 112, 15);
        linearLayout.addView(this.ajsrczcosw);
        this.ajsrczcosw.setBackgroundColor(Color.parseColor("#8fbbe6"));
        Button button9 = new Button(this);
        this.llsxtvjbjf = button9;
        button9.setLayoutParams(new LinearLayout.LayoutParams(1715, 616));
        this.llsxtvjbjf.setPadding(12, 51, PictureConfig.CHOOSE_REQUEST, 26);
        linearLayout.addView(this.llsxtvjbjf);
        this.llsxtvjbjf.setBackgroundColor(Color.parseColor("#325542"));
        EditText editText2 = new EditText(this);
        this.piedrqdwyn = editText2;
        editText2.setLayoutParams(new LinearLayout.LayoutParams(476, 785));
        this.piedrqdwyn.setPadding(192, 20, 64, 101);
        linearLayout.addView(this.piedrqdwyn);
        this.piedrqdwyn.setBackgroundColor(Color.parseColor("#0ca456"));
        ViewFlipper viewFlipper5 = new ViewFlipper(this);
        this.efsygffcsm = viewFlipper5;
        viewFlipper5.setLayoutParams(new LinearLayout.LayoutParams(387, 1650));
        this.efsygffcsm.setPadding(111, 154, 146, 56);
        linearLayout.addView(this.efsygffcsm);
        this.efsygffcsm.setBackgroundColor(Color.parseColor("#949db4"));
        RadioButton radioButton6 = new RadioButton(this);
        this.pozjgqiilv = radioButton6;
        radioButton6.setLayoutParams(new LinearLayout.LayoutParams(1199, 104));
        this.pozjgqiilv.setPadding(82, 22, 147, 2);
        linearLayout.addView(this.pozjgqiilv);
        this.pozjgqiilv.setBackgroundColor(Color.parseColor("#53745d"));
        RelativeLayout relativeLayout7 = new RelativeLayout(this);
        this.mzltafyqip = relativeLayout7;
        relativeLayout7.setLayoutParams(new LinearLayout.LayoutParams(1181, 1274));
        this.mzltafyqip.setPadding(5, 93, 42, 24);
        linearLayout.addView(this.mzltafyqip);
        this.mzltafyqip.setBackgroundColor(Color.parseColor("#34cc5c"));
        GridView gridView3 = new GridView(this);
        this.dvbwcdmuut = gridView3;
        gridView3.setLayoutParams(new LinearLayout.LayoutParams(74, 1259));
        this.dvbwcdmuut.setPadding(99, 48, 186, 83);
        linearLayout.addView(this.dvbwcdmuut);
        this.dvbwcdmuut.setBackgroundColor(Color.parseColor("#f8b00a"));
        Spinner spinner5 = new Spinner(this);
        this.hsiwuhpshm = spinner5;
        spinner5.setLayoutParams(new LinearLayout.LayoutParams(407, 1493));
        this.hsiwuhpshm.setPadding(150, 97, 10, 24);
        linearLayout.addView(this.hsiwuhpshm);
        this.hsiwuhpshm.setBackgroundColor(Color.parseColor("#c4aade"));
        ViewFlipper viewFlipper6 = new ViewFlipper(this);
        this.bcnvgdabeq = viewFlipper6;
        viewFlipper6.setLayoutParams(new LinearLayout.LayoutParams(1040, 1304));
        this.bcnvgdabeq.setPadding(169, 91, 144, 129);
        linearLayout.addView(this.bcnvgdabeq);
        this.bcnvgdabeq.setBackgroundColor(Color.parseColor("#91e3ba"));
        GridView gridView4 = new GridView(this);
        this.fbyifznawu = gridView4;
        gridView4.setLayoutParams(new LinearLayout.LayoutParams(482, 1688));
        this.fbyifznawu.setPadding(125, 26, 146, 130);
        linearLayout.addView(this.fbyifznawu);
        this.fbyifznawu.setBackgroundColor(Color.parseColor("#1bd1a1"));
        SeekBar seekBar2 = new SeekBar(this);
        this.isxxiznixj = seekBar2;
        seekBar2.setLayoutParams(new LinearLayout.LayoutParams(352, 958));
        this.isxxiznixj.setPadding(180, 193, 74, 94);
        linearLayout.addView(this.isxxiznixj);
        this.isxxiznixj.setBackgroundColor(Color.parseColor("#404257"));
        LinearLayout linearLayout3 = new LinearLayout(this);
        this.xvyhtdfxui = linearLayout3;
        linearLayout3.setLayoutParams(new LinearLayout.LayoutParams(282, 749));
        this.xvyhtdfxui.setPadding(173, 115, 164, 0);
        linearLayout.addView(this.xvyhtdfxui);
        this.xvyhtdfxui.setBackgroundColor(Color.parseColor("#1c05da"));
        ListView listView6 = new ListView(this);
        this.bpmlifosqr = listView6;
        listView6.setLayoutParams(new LinearLayout.LayoutParams(658, 1549));
        this.bpmlifosqr.setPadding(189, 144, 175, 102);
        linearLayout.addView(this.bpmlifosqr);
        this.bpmlifosqr.setBackgroundColor(Color.parseColor("#2891d7"));
        DatePicker datePicker6 = new DatePicker(this);
        this.kihvrlkmcm = datePicker6;
        datePicker6.setLayoutParams(new LinearLayout.LayoutParams(1170, 1101));
        this.kihvrlkmcm.setPadding(WebSocketProtocol.PAYLOAD_SHORT, 57, 29, BDLocation.TypeNetWorkLocation);
        linearLayout.addView(this.kihvrlkmcm);
        this.kihvrlkmcm.setBackgroundColor(Color.parseColor("#bc2bd6"));
        ScrollView scrollView5 = new ScrollView(this);
        this.owtbympsuj = scrollView5;
        scrollView5.setLayoutParams(new LinearLayout.LayoutParams(775, 234));
        this.owtbympsuj.setPadding(183, 151, 144, 40);
        linearLayout.addView(this.owtbympsuj);
        this.owtbympsuj.setBackgroundColor(Color.parseColor("#ec17f9"));
        ToggleButton toggleButton3 = new ToggleButton(this);
        this.ofpzmhsxcm = toggleButton3;
        toggleButton3.setLayoutParams(new LinearLayout.LayoutParams(59, 1556));
        this.ofpzmhsxcm.setPadding(151, 36, 186, 82);
        linearLayout.addView(this.ofpzmhsxcm);
        this.ofpzmhsxcm.setBackgroundColor(Color.parseColor("#2e628a"));
        ToggleButton toggleButton4 = new ToggleButton(this);
        this.yagqqvvugv = toggleButton4;
        toggleButton4.setLayoutParams(new LinearLayout.LayoutParams(875, 1560));
        this.yagqqvvugv.setPadding(191, 77, 135, 83);
        linearLayout.addView(this.yagqqvvugv);
        this.yagqqvvugv.setBackgroundColor(Color.parseColor("#ad94ee"));
        DatePicker datePicker7 = new DatePicker(this);
        this.crqyqyypnx = datePicker7;
        datePicker7.setLayoutParams(new LinearLayout.LayoutParams(157, 1873));
        this.crqyqyypnx.setPadding(164, 151, 194, 70);
        linearLayout.addView(this.crqyqyypnx);
        this.crqyqyypnx.setBackgroundColor(Color.parseColor("#5c5034"));
        Spinner spinner6 = new Spinner(this);
        this.snybqxhkrz = spinner6;
        spinner6.setLayoutParams(new LinearLayout.LayoutParams(436, 1361));
        this.snybqxhkrz.setPadding(22, 197, 34, 113);
        linearLayout.addView(this.snybqxhkrz);
        this.snybqxhkrz.setBackgroundColor(Color.parseColor("#f2b5b6"));
        SeekBar seekBar3 = new SeekBar(this);
        this.tdwtfrlvae = seekBar3;
        seekBar3.setLayoutParams(new LinearLayout.LayoutParams(1787, 1796));
        this.tdwtfrlvae.setPadding(33, 28, 33, 96);
        linearLayout.addView(this.tdwtfrlvae);
        this.tdwtfrlvae.setBackgroundColor(Color.parseColor("#df0bb1"));
        TimePicker timePicker3 = new TimePicker(this);
        this.zpivibhjgx = timePicker3;
        timePicker3.setLayoutParams(new LinearLayout.LayoutParams(323, 1851));
        this.zpivibhjgx.setPadding(5, 29, 88, 176);
        linearLayout.addView(this.zpivibhjgx);
        this.zpivibhjgx.setBackgroundColor(Color.parseColor("#8e4779"));
        ScrollView scrollView6 = new ScrollView(this);
        this.szdnqwerex = scrollView6;
        scrollView6.setLayoutParams(new LinearLayout.LayoutParams(594, 1279));
        this.szdnqwerex.setPadding(163, 177, 33, 116);
        linearLayout.addView(this.szdnqwerex);
        this.szdnqwerex.setBackgroundColor(Color.parseColor("#2526c1"));
        RelativeLayout relativeLayout8 = new RelativeLayout(this);
        this.mizmioaeyh = relativeLayout8;
        relativeLayout8.setLayoutParams(new LinearLayout.LayoutParams(1601, 788));
        this.mizmioaeyh.setPadding(103, 123, 90, 157);
        linearLayout.addView(this.mizmioaeyh);
        this.mizmioaeyh.setBackgroundColor(Color.parseColor("#98defe"));
        LinearLayout linearLayout4 = new LinearLayout(this);
        this.wehzqmcbns = linearLayout4;
        linearLayout4.setLayoutParams(new LinearLayout.LayoutParams(265, 85));
        this.wehzqmcbns.setPadding(PictureConfig.CHOOSE_REQUEST, 30, 74, 34);
        linearLayout.addView(this.wehzqmcbns);
        this.wehzqmcbns.setBackgroundColor(Color.parseColor("#552194"));
        ToggleButton toggleButton5 = new ToggleButton(this);
        this.hjlewjpflv = toggleButton5;
        toggleButton5.setLayoutParams(new LinearLayout.LayoutParams(1682, 855));
        this.hjlewjpflv.setPadding(49, 87, 106, 168);
        linearLayout.addView(this.hjlewjpflv);
        this.hjlewjpflv.setBackgroundColor(Color.parseColor("#bcb096"));
        TableLayout tableLayout4 = new TableLayout(this);
        this.losxxnikan = tableLayout4;
        tableLayout4.setLayoutParams(new LinearLayout.LayoutParams(401, 1983));
        this.losxxnikan.setPadding(150, 13, 114, 155);
        linearLayout.addView(this.losxxnikan);
        this.losxxnikan.setBackgroundColor(Color.parseColor("#f9e656"));
        ScrollView scrollView7 = new ScrollView(this);
        this.dmcktxelxm = scrollView7;
        scrollView7.setLayoutParams(new LinearLayout.LayoutParams(1748, 1845));
        this.dmcktxelxm.setPadding(147, 196, 5, 115);
        linearLayout.addView(this.dmcktxelxm);
        this.dmcktxelxm.setBackgroundColor(Color.parseColor("#797805"));
        ToggleButton toggleButton6 = new ToggleButton(this);
        this.exndtsbidw = toggleButton6;
        toggleButton6.setLayoutParams(new LinearLayout.LayoutParams(1236, 1026));
        this.exndtsbidw.setPadding(142, 153, 195, 11);
        linearLayout.addView(this.exndtsbidw);
        this.exndtsbidw.setBackgroundColor(Color.parseColor("#fce1a7"));
        ProgressBar progressBar4 = new ProgressBar(this);
        this.odnckacwww = progressBar4;
        progressBar4.setLayoutParams(new LinearLayout.LayoutParams(656, 1470));
        this.odnckacwww.setPadding(6, 104, 171, 83);
        linearLayout.addView(this.odnckacwww);
        this.odnckacwww.setBackgroundColor(Color.parseColor("#08f16a"));
        SeekBar seekBar4 = new SeekBar(this);
        this.tcvxohcthe = seekBar4;
        seekBar4.setLayoutParams(new LinearLayout.LayoutParams(1721, 186));
        this.tcvxohcthe.setPadding(169, 184, 163, 198);
        linearLayout.addView(this.tcvxohcthe);
        this.tcvxohcthe.setBackgroundColor(Color.parseColor("#7179bc"));
        ImageView imageView5 = new ImageView(this);
        this.larbxzcyhc = imageView5;
        imageView5.setLayoutParams(new LinearLayout.LayoutParams(182, 1094));
        this.larbxzcyhc.setPadding(127, 72, 68, 6);
        linearLayout.addView(this.larbxzcyhc);
        this.larbxzcyhc.setBackgroundColor(Color.parseColor("#58b116"));
        ToggleButton toggleButton7 = new ToggleButton(this);
        this.pflqszojyd = toggleButton7;
        toggleButton7.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.MotionType.TYPE_ANIMATE_RELATIVE_TO, 1828));
        this.pflqszojyd.setPadding(97, 50, 166, 28);
        linearLayout.addView(this.pflqszojyd);
        this.pflqszojyd.setBackgroundColor(Color.parseColor("#553c95"));
        CheckBox checkBox6 = new CheckBox(this);
        this.zjimyffozz = checkBox6;
        checkBox6.setLayoutParams(new LinearLayout.LayoutParams(1523, 1649));
        this.zjimyffozz.setPadding(177, 149, 148, 76);
        linearLayout.addView(this.zjimyffozz);
        this.zjimyffozz.setBackgroundColor(Color.parseColor("#f7bef1"));
        ToggleButton toggleButton8 = new ToggleButton(this);
        this.uaqrjxogqx = toggleButton8;
        toggleButton8.setLayoutParams(new LinearLayout.LayoutParams(1209, 140));
        this.uaqrjxogqx.setPadding(79, 65, 68, 21);
        linearLayout.addView(this.uaqrjxogqx);
        this.uaqrjxogqx.setBackgroundColor(Color.parseColor("#6d2843"));
        TimePicker timePicker4 = new TimePicker(this);
        this.kgiqlsvrgp = timePicker4;
        timePicker4.setLayoutParams(new LinearLayout.LayoutParams(1836, 376));
        this.kgiqlsvrgp.setPadding(181, 82, 103, 143);
        linearLayout.addView(this.kgiqlsvrgp);
        this.kgiqlsvrgp.setBackgroundColor(Color.parseColor("#e42d6c"));
        RatingBar ratingBar3 = new RatingBar(this);
        this.uvqqazwldw = ratingBar3;
        ratingBar3.setLayoutParams(new LinearLayout.LayoutParams(17, 1908));
        this.uvqqazwldw.setPadding(137, 143, 16, 174);
        linearLayout.addView(this.uvqqazwldw);
        this.uvqqazwldw.setBackgroundColor(Color.parseColor("#44095d"));
        CheckBox checkBox7 = new CheckBox(this);
        this.lunlrcuypu = checkBox7;
        checkBox7.setLayoutParams(new LinearLayout.LayoutParams(1379, 274));
        this.lunlrcuypu.setPadding(61, 124, 20, 108);
        linearLayout.addView(this.lunlrcuypu);
        this.lunlrcuypu.setBackgroundColor(Color.parseColor("#9690c2"));
        RadioButton radioButton7 = new RadioButton(this);
        this.dmsixcqjzd = radioButton7;
        radioButton7.setLayoutParams(new LinearLayout.LayoutParams(369, 525));
        this.dmsixcqjzd.setPadding(36, 107, 173, 171);
        linearLayout.addView(this.dmsixcqjzd);
        this.dmsixcqjzd.setBackgroundColor(Color.parseColor("#441f3f"));
        DatePicker datePicker8 = new DatePicker(this);
        this.dknkotowfn = datePicker8;
        datePicker8.setLayoutParams(new LinearLayout.LayoutParams(1584, 412));
        this.dknkotowfn.setPadding(51, 82, 148, 136);
        linearLayout.addView(this.dknkotowfn);
        this.dknkotowfn.setBackgroundColor(Color.parseColor("#854482"));
        CheckBox checkBox8 = new CheckBox(this);
        this.aiyhittwlt = checkBox8;
        checkBox8.setLayoutParams(new LinearLayout.LayoutParams(1969, 43));
        this.aiyhittwlt.setPadding(41, 117, 1, 59);
        linearLayout.addView(this.aiyhittwlt);
        this.aiyhittwlt.setBackgroundColor(Color.parseColor("#37d25b"));
        GridView gridView5 = new GridView(this);
        this.sizqedkvll = gridView5;
        gridView5.setLayoutParams(new LinearLayout.LayoutParams(152, 594));
        this.sizqedkvll.setPadding(69, 195, 178, 116);
        linearLayout.addView(this.sizqedkvll);
        this.sizqedkvll.setBackgroundColor(Color.parseColor("#4a14f9"));
        ProgressBar progressBar5 = new ProgressBar(this);
        this.oeeakdcrsc = progressBar5;
        progressBar5.setLayoutParams(new LinearLayout.LayoutParams(1554, 1350));
        this.oeeakdcrsc.setPadding(19, 158, 181, 48);
        linearLayout.addView(this.oeeakdcrsc);
        this.oeeakdcrsc.setBackgroundColor(Color.parseColor("#2b26da"));
        Spinner spinner7 = new Spinner(this);
        this.pxwmqgdcve = spinner7;
        spinner7.setLayoutParams(new LinearLayout.LayoutParams(1848, 164));
        this.pxwmqgdcve.setPadding(106, 59, 186, 81);
        linearLayout.addView(this.pxwmqgdcve);
        this.pxwmqgdcve.setBackgroundColor(Color.parseColor("#ec5aac"));
        DatePicker datePicker9 = new DatePicker(this);
        this.zampvujtld = datePicker9;
        datePicker9.setLayoutParams(new LinearLayout.LayoutParams(1725, 1316));
        this.zampvujtld.setPadding(61, 122, 18, 165);
        linearLayout.addView(this.zampvujtld);
        this.zampvujtld.setBackgroundColor(Color.parseColor("#6b1cce"));
        Spinner spinner8 = new Spinner(this);
        this.cdkjozvxib = spinner8;
        spinner8.setLayoutParams(new LinearLayout.LayoutParams(1737, 290));
        this.cdkjozvxib.setPadding(20, 183, 53, 189);
        linearLayout.addView(this.cdkjozvxib);
        this.cdkjozvxib.setBackgroundColor(Color.parseColor("#14a027"));
        DatePicker datePicker10 = new DatePicker(this);
        this.ikvfotzcyg = datePicker10;
        datePicker10.setLayoutParams(new LinearLayout.LayoutParams(1945, 577));
        this.ikvfotzcyg.setPadding(111, 78, 68, 199);
        linearLayout.addView(this.ikvfotzcyg);
        this.ikvfotzcyg.setBackgroundColor(Color.parseColor("#a759df"));
        RelativeLayout relativeLayout9 = new RelativeLayout(this);
        this.iothogwpgz = relativeLayout9;
        relativeLayout9.setLayoutParams(new LinearLayout.LayoutParams(1468, LocalPlaybackConstants.BUFFER_A_CAN_USE_FLAG));
        this.iothogwpgz.setPadding(191, 69, 83, 14);
        linearLayout.addView(this.iothogwpgz);
        this.iothogwpgz.setBackgroundColor(Color.parseColor("#6f5fe8"));
        RatingBar ratingBar4 = new RatingBar(this);
        this.vcodhdvgbf = ratingBar4;
        ratingBar4.setLayoutParams(new LinearLayout.LayoutParams(1732, 1208));
        this.vcodhdvgbf.setPadding(65, 106, 17, 21);
        linearLayout.addView(this.vcodhdvgbf);
        this.vcodhdvgbf.setBackgroundColor(Color.parseColor("#61847a"));
        TimePicker timePicker5 = new TimePicker(this);
        this.zbxujwveeh = timePicker5;
        timePicker5.setLayoutParams(new LinearLayout.LayoutParams(926, 21));
        this.zbxujwveeh.setPadding(175, 197, 30, 35);
        linearLayout.addView(this.zbxujwveeh);
        this.zbxujwveeh.setBackgroundColor(Color.parseColor("#26d122"));
        RatingBar ratingBar5 = new RatingBar(this);
        this.pyvtejkfrc = ratingBar5;
        ratingBar5.setLayoutParams(new LinearLayout.LayoutParams(1462, 1640));
        this.pyvtejkfrc.setPadding(37, 25, 169, 136);
        linearLayout.addView(this.pyvtejkfrc);
        this.pyvtejkfrc.setBackgroundColor(Color.parseColor("#d7fab3"));
        ScrollView scrollView8 = new ScrollView(this);
        this.wzdcuxqwoh = scrollView8;
        scrollView8.setLayoutParams(new LinearLayout.LayoutParams(916, 1670));
        this.wzdcuxqwoh.setPadding(85, 123, 101, 94);
        linearLayout.addView(this.wzdcuxqwoh);
        this.wzdcuxqwoh.setBackgroundColor(Color.parseColor("#f17a41"));
        EditText editText3 = new EditText(this);
        this.kykxkhlcyd = editText3;
        editText3.setLayoutParams(new LinearLayout.LayoutParams(708, 1360));
        this.kykxkhlcyd.setPadding(87, 181, 94, 4);
        linearLayout.addView(this.kykxkhlcyd);
        this.kykxkhlcyd.setBackgroundColor(Color.parseColor("#99d75b"));
        ImageView imageView6 = new ImageView(this);
        this.pssxmfskuu = imageView6;
        imageView6.setLayoutParams(new LinearLayout.LayoutParams(478, 60));
        this.pssxmfskuu.setPadding(73, PictureConfig.CHOOSE_REQUEST, 100, 124);
        linearLayout.addView(this.pssxmfskuu);
        this.pssxmfskuu.setBackgroundColor(Color.parseColor("#da7781"));
        LinearLayout linearLayout5 = new LinearLayout(this);
        this.jlmiqbwtkf = linearLayout5;
        linearLayout5.setLayoutParams(new LinearLayout.LayoutParams(346, 660));
        this.jlmiqbwtkf.setPadding(47, 36, 4, 101);
        linearLayout.addView(this.jlmiqbwtkf);
        this.jlmiqbwtkf.setBackgroundColor(Color.parseColor("#d1178a"));
        TextView textView4 = new TextView(this);
        this.iplugxblmx = textView4;
        textView4.setLayoutParams(new LinearLayout.LayoutParams(1526, 1426));
        this.iplugxblmx.setPadding(136, 109, 135, 100);
        linearLayout.addView(this.iplugxblmx);
        this.iplugxblmx.setBackgroundColor(Color.parseColor("#675f86"));
        ProgressBar progressBar6 = new ProgressBar(this);
        this.xwebikitgd = progressBar6;
        progressBar6.setLayoutParams(new LinearLayout.LayoutParams(447, 1734));
        this.xwebikitgd.setPadding(12, 78, 33, 116);
        linearLayout.addView(this.xwebikitgd);
        this.xwebikitgd.setBackgroundColor(Color.parseColor("#39ad2f"));
        FrameLayout frameLayout5 = new FrameLayout(this);
        this.tvcjkayfoa = frameLayout5;
        frameLayout5.setLayoutParams(new LinearLayout.LayoutParams(1409, 103));
        this.tvcjkayfoa.setPadding(77, 55, 7, 173);
        linearLayout.addView(this.tvcjkayfoa);
        this.tvcjkayfoa.setBackgroundColor(Color.parseColor("#837323"));
        EditText editText4 = new EditText(this);
        this.uikzlfxeca = editText4;
        editText4.setLayoutParams(new LinearLayout.LayoutParams(196, 1886));
        this.uikzlfxeca.setPadding(105, 69, 148, 128);
        linearLayout.addView(this.uikzlfxeca);
        this.uikzlfxeca.setBackgroundColor(Color.parseColor("#b98c93"));
        SeekBar seekBar5 = new SeekBar(this);
        this.tnvbroneks = seekBar5;
        seekBar5.setLayoutParams(new LinearLayout.LayoutParams(1419, 473));
        this.tnvbroneks.setPadding(BDLocation.TypeServerDecryptError, 62, 97, 169);
        linearLayout.addView(this.tnvbroneks);
        this.tnvbroneks.setBackgroundColor(Color.parseColor("#e09927"));
        DatePicker datePicker11 = new DatePicker(this);
        this.yawznmnwje = datePicker11;
        datePicker11.setLayoutParams(new LinearLayout.LayoutParams(659, 1603));
        this.yawznmnwje.setPadding(187, 4, BDLocation.TypeCoarseLocation, 142);
        linearLayout.addView(this.yawznmnwje);
        this.yawznmnwje.setBackgroundColor(Color.parseColor("#83dc0a"));
        Button button10 = new Button(this);
        this.ptyjiiwxms = button10;
        button10.setLayoutParams(new LinearLayout.LayoutParams(686, 1098));
        this.ptyjiiwxms.setPadding(63, 86, 173, 77);
        linearLayout.addView(this.ptyjiiwxms);
        this.ptyjiiwxms.setBackgroundColor(Color.parseColor("#6d58ef"));
        Spinner spinner9 = new Spinner(this);
        this.rkaawdalxj = spinner9;
        spinner9.setLayoutParams(new LinearLayout.LayoutParams(1234, 1393));
        this.rkaawdalxj.setPadding(48, 154, 153, 147);
        linearLayout.addView(this.rkaawdalxj);
        this.rkaawdalxj.setBackgroundColor(Color.parseColor("#1062d5"));
        SeekBar seekBar6 = new SeekBar(this);
        this.nwzrvdwiuo = seekBar6;
        seekBar6.setLayoutParams(new LinearLayout.LayoutParams(538, 923));
        this.nwzrvdwiuo.setPadding(0, 182, 139, 166);
        linearLayout.addView(this.nwzrvdwiuo);
        this.nwzrvdwiuo.setBackgroundColor(Color.parseColor("#6f7f3c"));
        RatingBar ratingBar6 = new RatingBar(this);
        this.imvsqcbkvo = ratingBar6;
        ratingBar6.setLayoutParams(new LinearLayout.LayoutParams(1936, 1362));
        this.imvsqcbkvo.setPadding(95, 45, 44, 189);
        linearLayout.addView(this.imvsqcbkvo);
        this.imvsqcbkvo.setBackgroundColor(Color.parseColor("#e14c9f"));
        ImageView imageView7 = new ImageView(this);
        this.lfpdkbvnoo = imageView7;
        imageView7.setLayoutParams(new LinearLayout.LayoutParams(1325, 1988));
        this.lfpdkbvnoo.setPadding(122, 174, 54, 142);
        linearLayout.addView(this.lfpdkbvnoo);
        this.lfpdkbvnoo.setBackgroundColor(Color.parseColor("#0655dc"));
        SeekBar seekBar7 = new SeekBar(this);
        this.krhkncntxy = seekBar7;
        seekBar7.setLayoutParams(new LinearLayout.LayoutParams(1141, 1381));
        this.krhkncntxy.setPadding(189, 111, 50, 158);
        linearLayout.addView(this.krhkncntxy);
        this.krhkncntxy.setBackgroundColor(Color.parseColor("#28f173"));
        ListView listView7 = new ListView(this);
        this.fjxspqhdms = listView7;
        listView7.setLayoutParams(new LinearLayout.LayoutParams(379, 603));
        this.fjxspqhdms.setPadding(189, 121, 156, 38);
        linearLayout.addView(this.fjxspqhdms);
        this.fjxspqhdms.setBackgroundColor(Color.parseColor("#648875"));
        EditText editText5 = new EditText(this);
        this.jlnwuiblmk = editText5;
        editText5.setLayoutParams(new LinearLayout.LayoutParams(837, 698));
        this.jlnwuiblmk.setPadding(141, 164, 44, 8);
        linearLayout.addView(this.jlnwuiblmk);
        this.jlnwuiblmk.setBackgroundColor(Color.parseColor("#97b041"));
        SeekBar seekBar8 = new SeekBar(this);
        this.tknrujjdsc = seekBar8;
        seekBar8.setLayoutParams(new LinearLayout.LayoutParams(453, 1592));
        this.tknrujjdsc.setPadding(74, 107, 171, 18);
        linearLayout.addView(this.tknrujjdsc);
        this.tknrujjdsc.setBackgroundColor(Color.parseColor("#4c1e9d"));
        ProgressBar progressBar7 = new ProgressBar(this);
        this.alelfjeads = progressBar7;
        progressBar7.setLayoutParams(new LinearLayout.LayoutParams(765, 1172));
        this.alelfjeads.setPadding(141, 19, 159, 187);
        linearLayout.addView(this.alelfjeads);
        this.alelfjeads.setBackgroundColor(Color.parseColor("#05bca4"));
        TimePicker timePicker6 = new TimePicker(this);
        this.qavunaaiso = timePicker6;
        timePicker6.setLayoutParams(new LinearLayout.LayoutParams(404, 56));
        this.qavunaaiso.setPadding(157, 156, 164, 9);
        linearLayout.addView(this.qavunaaiso);
        this.qavunaaiso.setBackgroundColor(Color.parseColor("#8da14f"));
        ViewFlipper viewFlipper7 = new ViewFlipper(this);
        this.rjerttjcos = viewFlipper7;
        viewFlipper7.setLayoutParams(new LinearLayout.LayoutParams(195, 694));
        this.rjerttjcos.setPadding(142, 169, 168, 59);
        linearLayout.addView(this.rjerttjcos);
        this.rjerttjcos.setBackgroundColor(Color.parseColor("#61ecf3"));
        Switch r24 = new Switch(this);
        this.awofnuteon = r24;
        r24.setLayoutParams(new LinearLayout.LayoutParams(1437, 1496));
        this.awofnuteon.setPadding(91, 84, 146, 187);
        linearLayout.addView(this.awofnuteon);
        this.awofnuteon.setBackgroundColor(Color.parseColor("#3c8591"));
        DatePicker datePicker12 = new DatePicker(this);
        this.hooumbpylg = datePicker12;
        datePicker12.setLayoutParams(new LinearLayout.LayoutParams(344, 1559));
        this.hooumbpylg.setPadding(99, 66, 15, 196);
        linearLayout.addView(this.hooumbpylg);
        this.hooumbpylg.setBackgroundColor(Color.parseColor("#2e58a0"));
        ImageView imageView8 = new ImageView(this);
        this.vknjaupqgp = imageView8;
        imageView8.setLayoutParams(new LinearLayout.LayoutParams(206, 1142));
        this.vknjaupqgp.setPadding(131, 14, 129, 169);
        linearLayout.addView(this.vknjaupqgp);
        this.vknjaupqgp.setBackgroundColor(Color.parseColor("#8e981b"));
        DatePicker datePicker13 = new DatePicker(this);
        this.ytbqusqxoa = datePicker13;
        datePicker13.setLayoutParams(new LinearLayout.LayoutParams(1511, 1248));
        this.ytbqusqxoa.setPadding(0, 129, 198, 55);
        linearLayout.addView(this.ytbqusqxoa);
        this.ytbqusqxoa.setBackgroundColor(Color.parseColor("#10a891"));
        CheckBox checkBox9 = new CheckBox(this);
        this.uyeoptgjxi = checkBox9;
        checkBox9.setLayoutParams(new LinearLayout.LayoutParams(990, 116));
        this.uyeoptgjxi.setPadding(143, 38, 18, 193);
        linearLayout.addView(this.uyeoptgjxi);
        this.uyeoptgjxi.setBackgroundColor(Color.parseColor("#304085"));
        TextView textView5 = new TextView(this);
        this.fllgprnjnw = textView5;
        textView5.setLayoutParams(new LinearLayout.LayoutParams(678, 1929));
        this.fllgprnjnw.setPadding(3, 147, BDLocation.TypeServerDecryptError, 10);
        linearLayout.addView(this.fllgprnjnw);
        this.fllgprnjnw.setBackgroundColor(Color.parseColor("#d8aaae"));
        DatePicker datePicker14 = new DatePicker(this);
        this.uubowtmxpd = datePicker14;
        datePicker14.setLayoutParams(new LinearLayout.LayoutParams(1456, 789));
        this.uubowtmxpd.setPadding(BDLocation.TypeServerDecryptError, 27, 197, 152);
        linearLayout.addView(this.uubowtmxpd);
        this.uubowtmxpd.setBackgroundColor(Color.parseColor("#44fda0"));
        ViewFlipper viewFlipper8 = new ViewFlipper(this);
        this.owlgvxnqsd = viewFlipper8;
        viewFlipper8.setLayoutParams(new LinearLayout.LayoutParams(1202, 1168));
        this.owlgvxnqsd.setPadding(69, 105, BDLocation.TypeServerError, 196);
        linearLayout.addView(this.owlgvxnqsd);
        this.owlgvxnqsd.setBackgroundColor(Color.parseColor("#e5cae7"));
        DatePicker datePicker15 = new DatePicker(this);
        this.lkgaezuqtr = datePicker15;
        datePicker15.setLayoutParams(new LinearLayout.LayoutParams(255, TypedValues.MotionType.TYPE_ANIMATE_CIRCLEANGLE_TO));
        this.lkgaezuqtr.setPadding(98, 6, 60, 55);
        linearLayout.addView(this.lkgaezuqtr);
        this.lkgaezuqtr.setBackgroundColor(Color.parseColor("#d84911"));
        Switch r25 = new Switch(this);
        this.njcwlthapy = r25;
        r25.setLayoutParams(new LinearLayout.LayoutParams(1990, 883));
        this.njcwlthapy.setPadding(80, 3, 143, 110);
        linearLayout.addView(this.njcwlthapy);
        this.njcwlthapy.setBackgroundColor(Color.parseColor("#dce1b5"));
        SeekBar seekBar9 = new SeekBar(this);
        this.fzmsvcgmvk = seekBar9;
        seekBar9.setLayoutParams(new LinearLayout.LayoutParams(1585, 183));
        this.fzmsvcgmvk.setPadding(182, 58, 197, 71);
        linearLayout.addView(this.fzmsvcgmvk);
        this.fzmsvcgmvk.setBackgroundColor(Color.parseColor("#3bdffc"));
        LinearLayout linearLayout6 = new LinearLayout(this);
        this.rjsxwrhpsi = linearLayout6;
        linearLayout6.setLayoutParams(new LinearLayout.LayoutParams(324, 1841));
        this.rjsxwrhpsi.setPadding(40, 150, 18, 12);
        linearLayout.addView(this.rjsxwrhpsi);
        this.rjsxwrhpsi.setBackgroundColor(Color.parseColor("#796dec"));
        ProgressBar progressBar8 = new ProgressBar(this);
        this.wqywospdag = progressBar8;
        progressBar8.setLayoutParams(new LinearLayout.LayoutParams(1287, 792));
        this.wqywospdag.setPadding(72, 27, 87, 45);
        linearLayout.addView(this.wqywospdag);
        this.wqywospdag.setBackgroundColor(Color.parseColor("#fcc2ad"));
        RatingBar ratingBar7 = new RatingBar(this);
        this.hterbnthwc = ratingBar7;
        ratingBar7.setLayoutParams(new LinearLayout.LayoutParams(1913, PictureConfig.REQUEST_CAMERA));
        this.hterbnthwc.setPadding(117, 40, 165, 19);
        linearLayout.addView(this.hterbnthwc);
        this.hterbnthwc.setBackgroundColor(Color.parseColor("#76786c"));
        ToggleButton toggleButton9 = new ToggleButton(this);
        this.vhxqwsbhuk = toggleButton9;
        toggleButton9.setLayoutParams(new LinearLayout.LayoutParams(266, 1837));
        this.vhxqwsbhuk.setPadding(59, 95, 98, 64);
        linearLayout.addView(this.vhxqwsbhuk);
        this.vhxqwsbhuk.setBackgroundColor(Color.parseColor("#767820"));
        TimePicker timePicker7 = new TimePicker(this);
        this.qvhfwtzdul = timePicker7;
        timePicker7.setLayoutParams(new LinearLayout.LayoutParams(1692, 923));
        this.qvhfwtzdul.setPadding(103, 47, 94, 130);
        linearLayout.addView(this.qvhfwtzdul);
        this.qvhfwtzdul.setBackgroundColor(Color.parseColor("#e47a8f"));
        ProgressBar progressBar9 = new ProgressBar(this);
        this.xurfyochjn = progressBar9;
        progressBar9.setLayoutParams(new LinearLayout.LayoutParams(1662, 339));
        this.xurfyochjn.setPadding(21, 153, 42, 158);
        linearLayout.addView(this.xurfyochjn);
        this.xurfyochjn.setBackgroundColor(Color.parseColor("#a651d0"));
        LinearLayout linearLayout7 = new LinearLayout(this);
        this.lauzxxadat = linearLayout7;
        linearLayout7.setLayoutParams(new LinearLayout.LayoutParams(349, 1282));
        this.lauzxxadat.setPadding(31, 30, 109, 194);
        linearLayout.addView(this.lauzxxadat);
        this.lauzxxadat.setBackgroundColor(Color.parseColor("#9fc66e"));
        RatingBar ratingBar8 = new RatingBar(this);
        this.qostqibwlu = ratingBar8;
        ratingBar8.setLayoutParams(new LinearLayout.LayoutParams(1233, 874));
        this.qostqibwlu.setPadding(180, 121, 131, 163);
        linearLayout.addView(this.qostqibwlu);
        this.qostqibwlu.setBackgroundColor(Color.parseColor("#122919"));
        TimePicker timePicker8 = new TimePicker(this);
        this.xntowruoer = timePicker8;
        timePicker8.setLayoutParams(new LinearLayout.LayoutParams(1064, TypedValues.CycleType.TYPE_WAVE_PHASE));
        this.xntowruoer.setPadding(27, 168, 180, 150);
        linearLayout.addView(this.xntowruoer);
        this.xntowruoer.setBackgroundColor(Color.parseColor("#e460ed"));
        TextView textView6 = new TextView(this);
        this.vxuejeanmh = textView6;
        textView6.setLayoutParams(new LinearLayout.LayoutParams(907, 1537));
        this.vxuejeanmh.setPadding(139, WebSocketProtocol.PAYLOAD_SHORT, 189, 115);
        linearLayout.addView(this.vxuejeanmh);
        this.vxuejeanmh.setBackgroundColor(Color.parseColor("#4eaafa"));
        ToggleButton toggleButton10 = new ToggleButton(this);
        this.yvuhdfetfa = toggleButton10;
        toggleButton10.setLayoutParams(new LinearLayout.LayoutParams(1874, 747));
        this.yvuhdfetfa.setPadding(81, 163, 62, 116);
        linearLayout.addView(this.yvuhdfetfa);
        this.yvuhdfetfa.setBackgroundColor(Color.parseColor("#8d7736"));
        ToggleButton toggleButton11 = new ToggleButton(this);
        this.dflxtldtfb = toggleButton11;
        toggleButton11.setLayoutParams(new LinearLayout.LayoutParams(30, 206));
        this.dflxtldtfb.setPadding(84, 61, 80, 67);
        linearLayout.addView(this.dflxtldtfb);
        this.dflxtldtfb.setBackgroundColor(Color.parseColor("#eb5995"));
        ViewFlipper viewFlipper9 = new ViewFlipper(this);
        this.sohtblwbax = viewFlipper9;
        viewFlipper9.setLayoutParams(new LinearLayout.LayoutParams(218, 1236));
        this.sohtblwbax.setPadding(72, 47, 65, 58);
        linearLayout.addView(this.sohtblwbax);
        this.sohtblwbax.setBackgroundColor(Color.parseColor("#1682c7"));
        FrameLayout frameLayout6 = new FrameLayout(this);
        this.xtjhchgvtv = frameLayout6;
        frameLayout6.setLayoutParams(new LinearLayout.LayoutParams(837, 947));
        this.xtjhchgvtv.setPadding(62, 23, 31, 101);
        linearLayout.addView(this.xtjhchgvtv);
        this.xtjhchgvtv.setBackgroundColor(Color.parseColor("#c297c9"));
        SeekBar seekBar10 = new SeekBar(this);
        this.lchforyeum = seekBar10;
        seekBar10.setLayoutParams(new LinearLayout.LayoutParams(1608, 1058));
        this.lchforyeum.setPadding(45, 142, 63, 26);
        linearLayout.addView(this.lchforyeum);
        this.lchforyeum.setBackgroundColor(Color.parseColor("#63f23d"));
        ViewFlipper viewFlipper10 = new ViewFlipper(this);
        this.ycsvstttpj = viewFlipper10;
        viewFlipper10.setLayoutParams(new LinearLayout.LayoutParams(1672, 1994));
        this.ycsvstttpj.setPadding(64, 23, 128, 137);
        linearLayout.addView(this.ycsvstttpj);
        this.ycsvstttpj.setBackgroundColor(Color.parseColor("#ae45ce"));
        ToggleButton toggleButton12 = new ToggleButton(this);
        this.ymlkqyazep = toggleButton12;
        toggleButton12.setLayoutParams(new LinearLayout.LayoutParams(1824, 37));
        this.ymlkqyazep.setPadding(139, 34, 15, 23);
        linearLayout.addView(this.ymlkqyazep);
        this.ymlkqyazep.setBackgroundColor(Color.parseColor("#cb02d5"));
        SeekBar seekBar11 = new SeekBar(this);
        this.zfqymjmmur = seekBar11;
        seekBar11.setLayoutParams(new LinearLayout.LayoutParams(1573, 587));
        this.zfqymjmmur.setPadding(91, 195, 73, 21);
        linearLayout.addView(this.zfqymjmmur);
        this.zfqymjmmur.setBackgroundColor(Color.parseColor("#2cb10d"));
        SeekBar seekBar12 = new SeekBar(this);
        this.htqvvntdgo = seekBar12;
        seekBar12.setLayoutParams(new LinearLayout.LayoutParams(1279, 1087));
        this.htqvvntdgo.setPadding(136, 146, 15, 135);
        linearLayout.addView(this.htqvvntdgo);
        this.htqvvntdgo.setBackgroundColor(Color.parseColor("#3fe139"));
        Button button11 = new Button(this);
        this.eeqtrloavo = button11;
        button11.setLayoutParams(new LinearLayout.LayoutParams(39, 98));
        this.eeqtrloavo.setPadding(42, 183, 178, 183);
        linearLayout.addView(this.eeqtrloavo);
        this.eeqtrloavo.setBackgroundColor(Color.parseColor("#3e0a56"));
        TextView textView7 = new TextView(this);
        this.ltahhglmrh = textView7;
        textView7.setLayoutParams(new LinearLayout.LayoutParams(250, 1670));
        this.ltahhglmrh.setPadding(142, 134, 5, 88);
        linearLayout.addView(this.ltahhglmrh);
        this.ltahhglmrh.setBackgroundColor(Color.parseColor("#0b2e6b"));
        LinearLayout linearLayout8 = new LinearLayout(this);
        this.koybjkfjon = linearLayout8;
        linearLayout8.setLayoutParams(new LinearLayout.LayoutParams(1346, 1738));
        this.koybjkfjon.setPadding(195, 102, 56, 182);
        linearLayout.addView(this.koybjkfjon);
        this.koybjkfjon.setBackgroundColor(Color.parseColor("#d1ba90"));
        ImageView imageView9 = new ImageView(this);
        this.rllguoxtoc = imageView9;
        imageView9.setLayoutParams(new LinearLayout.LayoutParams(164, 1822));
        this.rllguoxtoc.setPadding(174, 23, 71, 83);
        linearLayout.addView(this.rllguoxtoc);
        this.rllguoxtoc.setBackgroundColor(Color.parseColor("#f4323d"));
        RadioButton radioButton8 = new RadioButton(this);
        this.wcgeqcttxc = radioButton8;
        radioButton8.setLayoutParams(new LinearLayout.LayoutParams(483, 741));
        this.wcgeqcttxc.setPadding(86, 49, 103, 46);
        linearLayout.addView(this.wcgeqcttxc);
        this.wcgeqcttxc.setBackgroundColor(Color.parseColor("#4e1154"));
        LinearLayout linearLayout9 = new LinearLayout(this);
        this.cekjhprapt = linearLayout9;
        linearLayout9.setLayoutParams(new LinearLayout.LayoutParams(615, 816));
        this.cekjhprapt.setPadding(189, 1, 129, 92);
        linearLayout.addView(this.cekjhprapt);
        this.cekjhprapt.setBackgroundColor(Color.parseColor("#c7e54a"));
        ListView listView8 = new ListView(this);
        this.lbynipvokf = listView8;
        listView8.setLayoutParams(new LinearLayout.LayoutParams(1603, 562));
        this.lbynipvokf.setPadding(84, 157, 174, 105);
        linearLayout.addView(this.lbynipvokf);
        this.lbynipvokf.setBackgroundColor(Color.parseColor("#372089"));
        TextView textView8 = new TextView(this);
        this.zvjkyrfjej = textView8;
        textView8.setLayoutParams(new LinearLayout.LayoutParams(185, 262));
        this.zvjkyrfjej.setPadding(65, 97, 94, 17);
        linearLayout.addView(this.zvjkyrfjej);
        this.zvjkyrfjej.setBackgroundColor(Color.parseColor("#a8ac9f"));
        ViewFlipper viewFlipper11 = new ViewFlipper(this);
        this.wjsljmshsa = viewFlipper11;
        viewFlipper11.setLayoutParams(new LinearLayout.LayoutParams(1843, 309));
        this.wjsljmshsa.setPadding(79, 42, 77, 143);
        linearLayout.addView(this.wjsljmshsa);
        this.wjsljmshsa.setBackgroundColor(Color.parseColor("#ea17a6"));
        ListView listView9 = new ListView(this);
        this.fuuuqorrka = listView9;
        listView9.setLayoutParams(new LinearLayout.LayoutParams(1800, 381));
        this.fuuuqorrka.setPadding(131, 40, 147, 71);
        linearLayout.addView(this.fuuuqorrka);
        this.fuuuqorrka.setBackgroundColor(Color.parseColor("#61e3ed"));
        EditText editText6 = new EditText(this);
        this.pwmllmqmzl = editText6;
        editText6.setLayoutParams(new LinearLayout.LayoutParams(1215, 804));
        this.pwmllmqmzl.setPadding(175, 80, 48, 184);
        linearLayout.addView(this.pwmllmqmzl);
        this.pwmllmqmzl.setBackgroundColor(Color.parseColor("#c3985d"));
        Switch r26 = new Switch(this);
        this.qlizqrhcov = r26;
        r26.setLayoutParams(new LinearLayout.LayoutParams(460, 1170));
        this.qlizqrhcov.setPadding(189, 46, 138, 65);
        linearLayout.addView(this.qlizqrhcov);
        this.qlizqrhcov.setBackgroundColor(Color.parseColor("#90815d"));
        CheckBox checkBox10 = new CheckBox(this);
        this.lqskbuflrq = checkBox10;
        checkBox10.setLayoutParams(new LinearLayout.LayoutParams(1326, 389));
        this.lqskbuflrq.setPadding(122, 25, 44, 165);
        linearLayout.addView(this.lqskbuflrq);
        this.lqskbuflrq.setBackgroundColor(Color.parseColor("#93f2d3"));
        Spinner spinner10 = new Spinner(this);
        this.fcsugiatxh = spinner10;
        spinner10.setLayoutParams(new LinearLayout.LayoutParams(1210, 246));
        this.fcsugiatxh.setPadding(100, 48, 44, 193);
        linearLayout.addView(this.fcsugiatxh);
        this.fcsugiatxh.setBackgroundColor(Color.parseColor("#0fa998"));
        RelativeLayout relativeLayout10 = new RelativeLayout(this);
        this.stqzkhrqvh = relativeLayout10;
        relativeLayout10.setLayoutParams(new LinearLayout.LayoutParams(1823, 1761));
        this.stqzkhrqvh.setPadding(170, 18, 176, 131);
        linearLayout.addView(this.stqzkhrqvh);
        this.stqzkhrqvh.setBackgroundColor(Color.parseColor("#47d253"));
        SeekBar seekBar13 = new SeekBar(this);
        this.bdxsyiltpj = seekBar13;
        seekBar13.setLayoutParams(new LinearLayout.LayoutParams(430, 283));
        this.bdxsyiltpj.setPadding(142, 108, 157, 190);
        linearLayout.addView(this.bdxsyiltpj);
        this.bdxsyiltpj.setBackgroundColor(Color.parseColor("#91252b"));
        Button button12 = new Button(this);
        this.nokfcrhomu = button12;
        button12.setLayoutParams(new LinearLayout.LayoutParams(492, 53));
        this.nokfcrhomu.setPadding(33, 35, 28, 96);
        linearLayout.addView(this.nokfcrhomu);
        this.nokfcrhomu.setBackgroundColor(Color.parseColor("#8a3319"));
        RelativeLayout relativeLayout11 = new RelativeLayout(this);
        this.xiwhmdwuef = relativeLayout11;
        relativeLayout11.setLayoutParams(new LinearLayout.LayoutParams(1422, 549));
        this.xiwhmdwuef.setPadding(100, 80, 194, 85);
        linearLayout.addView(this.xiwhmdwuef);
        this.xiwhmdwuef.setBackgroundColor(Color.parseColor("#238713"));
        ToggleButton toggleButton13 = new ToggleButton(this);
        this.uboapkvmnz = toggleButton13;
        toggleButton13.setLayoutParams(new LinearLayout.LayoutParams(1129, 492));
        this.uboapkvmnz.setPadding(54, 42, 36, 68);
        linearLayout.addView(this.uboapkvmnz);
        this.uboapkvmnz.setBackgroundColor(Color.parseColor("#12c79c"));
        DatePicker datePicker16 = new DatePicker(this);
        this.ulofzvlhnz = datePicker16;
        datePicker16.setLayoutParams(new LinearLayout.LayoutParams(685, 1643));
        this.ulofzvlhnz.setPadding(143, 71, 5, 120);
        linearLayout.addView(this.ulofzvlhnz);
        this.ulofzvlhnz.setBackgroundColor(Color.parseColor("#66110f"));
        RadioButton radioButton9 = new RadioButton(this);
        this.nruosplwzg = radioButton9;
        radioButton9.setLayoutParams(new LinearLayout.LayoutParams(85, 295));
        this.nruosplwzg.setPadding(32, 108, 196, 18);
        linearLayout.addView(this.nruosplwzg);
        this.nruosplwzg.setBackgroundColor(Color.parseColor("#37c079"));
        SeekBar seekBar14 = new SeekBar(this);
        this.vdcxhxbobt = seekBar14;
        seekBar14.setLayoutParams(new LinearLayout.LayoutParams(196, 1924));
        this.vdcxhxbobt.setPadding(149, 116, 142, 146);
        linearLayout.addView(this.vdcxhxbobt);
        this.vdcxhxbobt.setBackgroundColor(Color.parseColor("#d26e2c"));
        RatingBar ratingBar9 = new RatingBar(this);
        this.cgqaskzsmi = ratingBar9;
        ratingBar9.setLayoutParams(new LinearLayout.LayoutParams(1638, 1702));
        this.cgqaskzsmi.setPadding(177, 125, 36, 141);
        linearLayout.addView(this.cgqaskzsmi);
        this.cgqaskzsmi.setBackgroundColor(Color.parseColor("#a02a5b"));
        ToggleButton toggleButton14 = new ToggleButton(this);
        this.cctcfzuqqs = toggleButton14;
        toggleButton14.setLayoutParams(new LinearLayout.LayoutParams(1481, 362));
        this.cctcfzuqqs.setPadding(12, 61, 145, 33);
        linearLayout.addView(this.cctcfzuqqs);
        this.cctcfzuqqs.setBackgroundColor(Color.parseColor("#9f6fd8"));
        FrameLayout frameLayout7 = new FrameLayout(this);
        this.wnnregctpz = frameLayout7;
        frameLayout7.setLayoutParams(new LinearLayout.LayoutParams(1311, 204));
        this.wnnregctpz.setPadding(147, 76, 28, PictureConfig.CHOOSE_REQUEST);
        linearLayout.addView(this.wnnregctpz);
        this.wnnregctpz.setBackgroundColor(Color.parseColor("#653940"));
        ListView listView10 = new ListView(this);
        this.lywhjodaad = listView10;
        listView10.setLayoutParams(new LinearLayout.LayoutParams(875, 907));
        this.lywhjodaad.setPadding(100, 154, 61, 196);
        linearLayout.addView(this.lywhjodaad);
        this.lywhjodaad.setBackgroundColor(Color.parseColor("#e9f6ee"));
        Spinner spinner11 = new Spinner(this);
        this.ubytesxrgl = spinner11;
        spinner11.setLayoutParams(new LinearLayout.LayoutParams(PointerIconCompat.TYPE_GRAB, 79));
        this.ubytesxrgl.setPadding(109, 17, 191, 112);
        linearLayout.addView(this.ubytesxrgl);
        this.ubytesxrgl.setBackgroundColor(Color.parseColor("#efa84e"));
        DatePicker datePicker17 = new DatePicker(this);
        this.stgjlnjpld = datePicker17;
        datePicker17.setLayoutParams(new LinearLayout.LayoutParams(850, 595));
        this.stgjlnjpld.setPadding(32, 53, 130, 3);
        linearLayout.addView(this.stgjlnjpld);
        this.stgjlnjpld.setBackgroundColor(Color.parseColor("#270891"));
        TimePicker timePicker9 = new TimePicker(this);
        this.eucculxtjw = timePicker9;
        timePicker9.setLayoutParams(new LinearLayout.LayoutParams(787, 1350));
        this.eucculxtjw.setPadding(21, 135, 178, 17);
        linearLayout.addView(this.eucculxtjw);
        this.eucculxtjw.setBackgroundColor(Color.parseColor("#4b7609"));
        TextView textView9 = new TextView(this);
        this.nisodtrxdf = textView9;
        textView9.setLayoutParams(new LinearLayout.LayoutParams(18, 436));
        this.nisodtrxdf.setPadding(148, 152, 73, 83);
        linearLayout.addView(this.nisodtrxdf);
        this.nisodtrxdf.setBackgroundColor(Color.parseColor("#44f375"));
        GridView gridView6 = new GridView(this);
        this.dplkkrrvfh = gridView6;
        gridView6.setLayoutParams(new LinearLayout.LayoutParams(932, 1771));
        this.dplkkrrvfh.setPadding(77, 98, 197, 101);
        linearLayout.addView(this.dplkkrrvfh);
        this.dplkkrrvfh.setBackgroundColor(Color.parseColor("#8cb5db"));
        DatePicker datePicker18 = new DatePicker(this);
        this.utgkpsaycs = datePicker18;
        datePicker18.setLayoutParams(new LinearLayout.LayoutParams(1047, 800));
        this.utgkpsaycs.setPadding(31, 19, 78, 103);
        linearLayout.addView(this.utgkpsaycs);
        this.utgkpsaycs.setBackgroundColor(Color.parseColor("#0f5652"));
        EditText editText7 = new EditText(this);
        this.daysuvvuyr = editText7;
        editText7.setLayoutParams(new LinearLayout.LayoutParams(1272, 1927));
        this.daysuvvuyr.setPadding(121, BDLocation.TypeServerDecryptError, 96, 185);
        linearLayout.addView(this.daysuvvuyr);
        this.daysuvvuyr.setBackgroundColor(Color.parseColor("#70c49b"));
        RatingBar ratingBar10 = new RatingBar(this);
        this.pdzsnkzzjm = ratingBar10;
        ratingBar10.setLayoutParams(new LinearLayout.LayoutParams(264, 42));
        this.pdzsnkzzjm.setPadding(24, 44, 168, 65);
        linearLayout.addView(this.pdzsnkzzjm);
        this.pdzsnkzzjm.setBackgroundColor(Color.parseColor("#cf337c"));
        RatingBar ratingBar11 = new RatingBar(this);
        this.rcympsjllh = ratingBar11;
        ratingBar11.setLayoutParams(new LinearLayout.LayoutParams(1716, 297));
        this.rcympsjllh.setPadding(54, 103, 61, 63);
        linearLayout.addView(this.rcympsjllh);
        this.rcympsjllh.setBackgroundColor(Color.parseColor("#a4f356"));
        RatingBar ratingBar12 = new RatingBar(this);
        this.cllfzlwmsc = ratingBar12;
        ratingBar12.setLayoutParams(new LinearLayout.LayoutParams(599, 936));
        this.cllfzlwmsc.setPadding(171, 45, 134, 159);
        linearLayout.addView(this.cllfzlwmsc);
        this.cllfzlwmsc.setBackgroundColor(Color.parseColor("#b37601"));
        ListView listView11 = new ListView(this);
        this.ppvnofynuj = listView11;
        listView11.setLayoutParams(new LinearLayout.LayoutParams(1350, 720));
        this.ppvnofynuj.setPadding(92, 132, 51, 87);
        linearLayout.addView(this.ppvnofynuj);
        this.ppvnofynuj.setBackgroundColor(Color.parseColor("#977aee"));
        ListView listView12 = new ListView(this);
        this.htjaskjnab = listView12;
        listView12.setLayoutParams(new LinearLayout.LayoutParams(1358, 1236));
        this.htjaskjnab.setPadding(76, 105, 18, 71);
        linearLayout.addView(this.htjaskjnab);
        this.htjaskjnab.setBackgroundColor(Color.parseColor("#6348f6"));
        TableLayout tableLayout5 = new TableLayout(this);
        this.zlbbulxtqh = tableLayout5;
        tableLayout5.setLayoutParams(new LinearLayout.LayoutParams(821, 1645));
        this.zlbbulxtqh.setPadding(51, 46, 32, WebSocketProtocol.PAYLOAD_SHORT);
        linearLayout.addView(this.zlbbulxtqh);
        this.zlbbulxtqh.setBackgroundColor(Color.parseColor("#f16117"));
        LinearLayout linearLayout10 = new LinearLayout(this);
        this.mpcsnhtyai = linearLayout10;
        linearLayout10.setLayoutParams(new LinearLayout.LayoutParams(1811, 1879));
        this.mpcsnhtyai.setPadding(BDLocation.TypeServerDecryptError, 144, 112, 149);
        linearLayout.addView(this.mpcsnhtyai);
        this.mpcsnhtyai.setBackgroundColor(Color.parseColor("#3670f6"));
        Spinner spinner12 = new Spinner(this);
        this.ddebygwahk = spinner12;
        spinner12.setLayoutParams(new LinearLayout.LayoutParams(1892, 834));
        this.ddebygwahk.setPadding(7, 50, 52, 155);
        linearLayout.addView(this.ddebygwahk);
        this.ddebygwahk.setBackgroundColor(Color.parseColor("#7d5ac3"));
        ProgressBar progressBar10 = new ProgressBar(this);
        this.hfnsnbuldi = progressBar10;
        progressBar10.setLayoutParams(new LinearLayout.LayoutParams(1731, 910));
        this.hfnsnbuldi.setPadding(172, 71, 38, 7);
        linearLayout.addView(this.hfnsnbuldi);
        this.hfnsnbuldi.setBackgroundColor(Color.parseColor("#2750d5"));
        TextView textView10 = new TextView(this);
        this.xspiiajvvv = textView10;
        textView10.setLayoutParams(new LinearLayout.LayoutParams(989, 1078));
        this.xspiiajvvv.setPadding(39, 10, 59, 21);
        linearLayout.addView(this.xspiiajvvv);
        this.xspiiajvvv.setBackgroundColor(Color.parseColor("#6e70a6"));
        TextView textView11 = new TextView(this);
        this.tkdggbrlql = textView11;
        textView11.setLayoutParams(new LinearLayout.LayoutParams(1641, 550));
        this.tkdggbrlql.setPadding(53, 58, 173, 0);
        linearLayout.addView(this.tkdggbrlql);
        this.tkdggbrlql.setBackgroundColor(Color.parseColor("#34d181"));
        TimePicker timePicker10 = new TimePicker(this);
        this.gozggdbdgu = timePicker10;
        timePicker10.setLayoutParams(new LinearLayout.LayoutParams(1337, 1567));
        this.gozggdbdgu.setPadding(112, 129, 106, 143);
        linearLayout.addView(this.gozggdbdgu);
        this.gozggdbdgu.setBackgroundColor(Color.parseColor("#8a0e48"));
        ImageView imageView10 = new ImageView(this);
        this.whslffersy = imageView10;
        imageView10.setLayoutParams(new LinearLayout.LayoutParams(1623, 624));
        this.whslffersy.setPadding(154, 107, 173, 195);
        linearLayout.addView(this.whslffersy);
        this.whslffersy.setBackgroundColor(Color.parseColor("#0a616b"));
        SeekBar seekBar15 = new SeekBar(this);
        this.xjxhbczsrs = seekBar15;
        seekBar15.setLayoutParams(new LinearLayout.LayoutParams(1781, 359));
        this.xjxhbczsrs.setPadding(141, 59, 72, 44);
        linearLayout.addView(this.xjxhbczsrs);
        this.xjxhbczsrs.setBackgroundColor(Color.parseColor("#3bd4ba"));
        GridView gridView7 = new GridView(this);
        this.uwsilflhcb = gridView7;
        gridView7.setLayoutParams(new LinearLayout.LayoutParams(1865, 653));
        this.uwsilflhcb.setPadding(2, 128, 131, 116);
        linearLayout.addView(this.uwsilflhcb);
        this.uwsilflhcb.setBackgroundColor(Color.parseColor("#f771a7"));
        ProgressBar progressBar11 = new ProgressBar(this);
        this.ycdnnvtgny = progressBar11;
        progressBar11.setLayoutParams(new LinearLayout.LayoutParams(157, 1817));
        this.ycdnnvtgny.setPadding(194, 78, 189, 108);
        linearLayout.addView(this.ycdnnvtgny);
        this.ycdnnvtgny.setBackgroundColor(Color.parseColor("#192df9"));
        DatePicker datePicker19 = new DatePicker(this);
        this.cgbophjsxv = datePicker19;
        datePicker19.setLayoutParams(new LinearLayout.LayoutParams(216, 899));
        this.cgbophjsxv.setPadding(19, 169, 93, 172);
        linearLayout.addView(this.cgbophjsxv);
        this.cgbophjsxv.setBackgroundColor(Color.parseColor("#ceced0"));
        Spinner spinner13 = new Spinner(this);
        this.jkvchjetag = spinner13;
        spinner13.setLayoutParams(new LinearLayout.LayoutParams(771, 785));
        this.jkvchjetag.setPadding(75, 101, 84, 46);
        linearLayout.addView(this.jkvchjetag);
        this.jkvchjetag.setBackgroundColor(Color.parseColor("#a4fcbc"));
        ProgressBar progressBar12 = new ProgressBar(this);
        this.fvehkqbvpq = progressBar12;
        progressBar12.setLayoutParams(new LinearLayout.LayoutParams(851, 1048));
        this.fvehkqbvpq.setPadding(138, 120, 139, 10);
        linearLayout.addView(this.fvehkqbvpq);
        this.fvehkqbvpq.setBackgroundColor(Color.parseColor("#a0d171"));
        ProgressBar progressBar13 = new ProgressBar(this);
        this.evskhhvlnf = progressBar13;
        progressBar13.setLayoutParams(new LinearLayout.LayoutParams(247, 1824));
        this.evskhhvlnf.setPadding(111, 152, 67, 45);
        linearLayout.addView(this.evskhhvlnf);
        this.evskhhvlnf.setBackgroundColor(Color.parseColor("#9bdab0"));
        RatingBar ratingBar13 = new RatingBar(this);
        this.artwtpmpdr = ratingBar13;
        ratingBar13.setLayoutParams(new LinearLayout.LayoutParams(166, 722));
        this.artwtpmpdr.setPadding(74, 49, 30, 35);
        linearLayout.addView(this.artwtpmpdr);
        this.artwtpmpdr.setBackgroundColor(Color.parseColor("#d24b61"));
        RelativeLayout relativeLayout12 = new RelativeLayout(this);
        this.cnohzvrmtj = relativeLayout12;
        relativeLayout12.setLayoutParams(new LinearLayout.LayoutParams(736, 86));
        this.cnohzvrmtj.setPadding(57, 142, 113, 100);
        linearLayout.addView(this.cnohzvrmtj);
        this.cnohzvrmtj.setBackgroundColor(Color.parseColor("#942205"));
        RelativeLayout relativeLayout13 = new RelativeLayout(this);
        this.bqqhdtjoyk = relativeLayout13;
        relativeLayout13.setLayoutParams(new LinearLayout.LayoutParams(326, 622));
        this.bqqhdtjoyk.setPadding(10, 192, 11, 75);
        linearLayout.addView(this.bqqhdtjoyk);
        this.bqqhdtjoyk.setBackgroundColor(Color.parseColor("#87d32a"));
        FrameLayout frameLayout8 = new FrameLayout(this);
        this.gmyshpwhlp = frameLayout8;
        frameLayout8.setLayoutParams(new LinearLayout.LayoutParams(1311, 711));
        this.gmyshpwhlp.setPadding(164, 196, 6, 50);
        linearLayout.addView(this.gmyshpwhlp);
        this.gmyshpwhlp.setBackgroundColor(Color.parseColor("#14e071"));
        ScrollView scrollView9 = new ScrollView(this);
        this.lwwpyvgxch = scrollView9;
        scrollView9.setLayoutParams(new LinearLayout.LayoutParams(1586, 1734));
        this.lwwpyvgxch.setPadding(98, 54, 87, 122);
        linearLayout.addView(this.lwwpyvgxch);
        this.lwwpyvgxch.setBackgroundColor(Color.parseColor("#346207"));
        LinearLayout linearLayout11 = new LinearLayout(this);
        this.wbbgmhzhox = linearLayout11;
        linearLayout11.setLayoutParams(new LinearLayout.LayoutParams(1602, 664));
        this.wbbgmhzhox.setPadding(189, 139, 5, 135);
        linearLayout.addView(this.wbbgmhzhox);
        this.wbbgmhzhox.setBackgroundColor(Color.parseColor("#5af027"));
        GridView gridView8 = new GridView(this);
        this.xsomubwyff = gridView8;
        gridView8.setLayoutParams(new LinearLayout.LayoutParams(1410, 970));
        this.xsomubwyff.setPadding(109, 37, 139, 97);
        linearLayout.addView(this.xsomubwyff);
        this.xsomubwyff.setBackgroundColor(Color.parseColor("#eeeae1"));
    }
}
