package com.device.watch.com.device.watch.yntrbskhiq;

import android.app.Activity;
import android.graphics.Color;
import android.os.Bundle;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.CheckBox;
import android.widget.DatePicker;
import android.widget.EditText;
import android.widget.FrameLayout;
import android.widget.GridView;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ListView;
import android.widget.ProgressBar;
import android.widget.RadioButton;
import android.widget.RatingBar;
import android.widget.RelativeLayout;
import android.widget.ScrollView;
import android.widget.SeekBar;
import android.widget.Spinner;
import android.widget.Switch;
import android.widget.TableLayout;
import android.widget.TextView;
import android.widget.TimePicker;
import android.widget.ToggleButton;
import android.widget.ViewFlipper;
import androidx.constraintlayout.core.motion.utils.TypedValues;
import androidx.core.app.FrameMetricsAggregator;
import androidx.core.view.PointerIconCompat;
import com.baidu.location.BDLocation;
import com.king.zxing.util.CodeUtils;
import com.luck.picture.lib.config.PictureConfig;
import com.qcwireless.qcwatch.ui.base.imagepicker.cropper.CropImage;
import com.realsil.sdk.audioconnect.localplayback.LocalPlaybackConstants;
import com.realsil.sdk.core.bluetooth.connection.le.GattClient;
import okhttp3.internal.ws.WebSocketProtocol;

/* loaded from: classes2.dex */
public class KkubmujsuxcActivity extends Activity {
    Spinner adndzmcquv;
    RelativeLayout adozuhvjko;
    Button adyjfrtkrk;
    GridView afcrvsjgcw;
    LinearLayout akmijveyak;
    Button bheeotpvad;
    TextView bkbhbpkjup;
    ListView dyrupunsdg;
    DatePicker dywhcuvmjq;
    TimePicker equbjdcvfq;
    RadioButton eyoyqxfojl;
    GridView fdnzatfvqn;
    TableLayout fkqkkmoamf;
    ImageView fofrlktqqr;
    ProgressBar gkxhwqfnki;
    DatePicker gonuyqjhsj;
    Switch gypoootmrj;
    ToggleButton hsrjptvbmu;
    RelativeLayout iarjsupxsj;
    Switch ibtyeiwyth;
    RelativeLayout imwylndntt;
    ToggleButton iorylrgtav;
    LinearLayout iswbhbnqif;
    ViewFlipper jcrtqjafss;
    FrameLayout jnauwqkuju;
    EditText jpnsnqqpdb;
    ListView jsvgvdwztm;
    SeekBar jxxwzjzouz;
    SeekBar kgpdgxgjsp;
    DatePicker khvosloifc;
    ScrollView kzlpkivmyg;
    RadioButton lbqfhhcfcj;
    GridView lbrtgrkhoy;
    TimePicker lgtmtjaquv;
    CheckBox lyfhcctvfu;
    ListView mkskycxllw;
    RelativeLayout mwtbmjnure;
    ListView nawggrfdbh;
    TableLayout nmbbdpqrgm;
    Spinner nnfklkpqqq;
    ToggleButton nvrefhjizl;
    SeekBar nwrvbospsq;
    ProgressBar ohlcfilmsj;
    ToggleButton oynwkadzkx;
    Switch pwlhtwrllc;
    RatingBar pzjpqvueye;
    GridView qbnhsbrshd;
    CheckBox qhqysffgto;
    SeekBar qpoypnnirf;
    Spinner qxnicbycwd;
    Switch rehbuvtpra;
    Button reoazjasow;
    ListView rlfxoutswu;
    CheckBox rrhzgdxwgb;
    TableLayout rvvigfrkiu;
    EditText rwwwissrih;
    RelativeLayout ryhtaaumnl;
    SeekBar sczrwirbea;
    Switch sfgdolxdxg;
    ProgressBar sjyhimkkee;
    LinearLayout ssntsazcrf;
    RadioButton svmgrrxljx;
    FrameLayout tzvbbljdel;
    RatingBar ukqhbrrllq;
    Button umukeohrqa;
    CheckBox uoyxzakjgw;
    EditText vnmbgxixtd;
    RadioButton wmgctvrych;
    ProgressBar xaxsjpflor;
    ViewFlipper xdojrwsmzu;
    Spinner yukepcxvlb;
    DatePicker zotoajlmkv;

    @Override // android.app.Activity
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        LinearLayout linearLayout = new LinearLayout(this);
        setContentView(linearLayout);
        linearLayout.setLayoutParams(new ViewGroup.LayoutParams(-1, -1));
        linearLayout.setOrientation(1);
        linearLayout.setBackgroundColor(Color.parseColor("#6a63f2"));
        CheckBox checkBox = new CheckBox(this);
        this.rrhzgdxwgb = checkBox;
        checkBox.setLayoutParams(new LinearLayout.LayoutParams(105, 916));
        this.rrhzgdxwgb.setPadding(55, 143, 59, 0);
        linearLayout.addView(this.rrhzgdxwgb);
        this.rrhzgdxwgb.setBackgroundColor(Color.parseColor("#29f693"));
        Switch r3 = new Switch(this);
        this.sfgdolxdxg = r3;
        r3.setLayoutParams(new LinearLayout.LayoutParams(1424, 1004));
        this.sfgdolxdxg.setPadding(PictureConfig.CHOOSE_REQUEST, 176, 189, 74);
        linearLayout.addView(this.sfgdolxdxg);
        this.sfgdolxdxg.setBackgroundColor(Color.parseColor("#839779"));
        Switch r32 = new Switch(this);
        this.pwlhtwrllc = r32;
        r32.setLayoutParams(new LinearLayout.LayoutParams(939, 739));
        this.pwlhtwrllc.setPadding(175, 81, 0, 117);
        linearLayout.addView(this.pwlhtwrllc);
        this.pwlhtwrllc.setBackgroundColor(Color.parseColor("#89e798"));
        ScrollView scrollView = new ScrollView(this);
        this.kzlpkivmyg = scrollView;
        scrollView.setLayoutParams(new LinearLayout.LayoutParams(1517, 233));
        this.kzlpkivmyg.setPadding(123, 105, 72, 103);
        linearLayout.addView(this.kzlpkivmyg);
        this.kzlpkivmyg.setBackgroundColor(Color.parseColor("#7ba819"));
        RadioButton radioButton = new RadioButton(this);
        this.lbqfhhcfcj = radioButton;
        radioButton.setLayoutParams(new LinearLayout.LayoutParams(689, 319));
        this.lbqfhhcfcj.setPadding(84, 190, 13, 70);
        linearLayout.addView(this.lbqfhhcfcj);
        this.lbqfhhcfcj.setBackground(new Wvttaycmmeh());
        DatePicker datePicker = new DatePicker(this);
        this.gonuyqjhsj = datePicker;
        datePicker.setLayoutParams(new LinearLayout.LayoutParams(247, 372));
        this.gonuyqjhsj.setPadding(30, 104, BDLocation.TypeCoarseLocation, 26);
        linearLayout.addView(this.gonuyqjhsj);
        this.gonuyqjhsj.setBackgroundColor(Color.parseColor("#94add7"));
        RelativeLayout relativeLayout = new RelativeLayout(this);
        this.iarjsupxsj = relativeLayout;
        relativeLayout.setLayoutParams(new LinearLayout.LayoutParams(713, 1131));
        this.iarjsupxsj.setPadding(97, 89, 61, 144);
        linearLayout.addView(this.iarjsupxsj);
        this.iarjsupxsj.setBackgroundColor(Color.parseColor("#ec4dc2"));
        ViewFlipper viewFlipper = new ViewFlipper(this);
        this.jcrtqjafss = viewFlipper;
        viewFlipper.setLayoutParams(new LinearLayout.LayoutParams(1008, 442));
        this.jcrtqjafss.setPadding(106, 144, 175, 92);
        linearLayout.addView(this.jcrtqjafss);
        this.jcrtqjafss.setBackgroundColor(Color.parseColor("#35b440"));
        Spinner spinner = new Spinner(this);
        this.qxnicbycwd = spinner;
        spinner.setLayoutParams(new LinearLayout.LayoutParams(321, 1033));
        this.qxnicbycwd.setPadding(9, 85, 119, 192);
        linearLayout.addView(this.qxnicbycwd);
        this.qxnicbycwd.setBackgroundColor(Color.parseColor("#4481c2"));
        ProgressBar progressBar = new ProgressBar(this);
        this.ohlcfilmsj = progressBar;
        progressBar.setLayoutParams(new LinearLayout.LayoutParams(1991, 142));
        this.ohlcfilmsj.setPadding(129, 181, 186, 180);
        linearLayout.addView(this.ohlcfilmsj);
        this.ohlcfilmsj.setBackgroundColor(Color.parseColor("#183bc2"));
        LinearLayout linearLayout2 = new LinearLayout(this);
        this.ssntsazcrf = linearLayout2;
        linearLayout2.setLayoutParams(new LinearLayout.LayoutParams(1882, 451));
        this.ssntsazcrf.setPadding(39, 170, 153, 65);
        linearLayout.addView(this.ssntsazcrf);
        this.ssntsazcrf.setBackgroundColor(Color.parseColor("#dda345"));
        SeekBar seekBar = new SeekBar(this);
        this.jxxwzjzouz = seekBar;
        seekBar.setLayoutParams(new LinearLayout.LayoutParams(LocalPlaybackConstants.BUFFER_B_CAN_USE_FLAG, 333));
        this.jxxwzjzouz.setPadding(33, 72, 140, 147);
        linearLayout.addView(this.jxxwzjzouz);
        this.jxxwzjzouz.setBackgroundColor(Color.parseColor("#f0f5b1"));
        Button button = new Button(this);
        this.reoazjasow = button;
        button.setLayoutParams(new LinearLayout.LayoutParams(643, 176));
        this.reoazjasow.setPadding(103, 16, 82, 198);
        linearLayout.addView(this.reoazjasow);
        this.reoazjasow.setBackgroundColor(Color.parseColor("#85b1ca"));
        GridView gridView = new GridView(this);
        this.fdnzatfvqn = gridView;
        gridView.setLayoutParams(new LinearLayout.LayoutParams(573, 982));
        this.fdnzatfvqn.setPadding(32, 189, 153, 113);
        linearLayout.addView(this.fdnzatfvqn);
        this.fdnzatfvqn.setBackgroundColor(Color.parseColor("#afd773"));
        SeekBar seekBar2 = new SeekBar(this);
        this.kgpdgxgjsp = seekBar2;
        seekBar2.setLayoutParams(new LinearLayout.LayoutParams(360, 551));
        this.kgpdgxgjsp.setPadding(20, 92, 149, 25);
        linearLayout.addView(this.kgpdgxgjsp);
        this.kgpdgxgjsp.setBackgroundColor(Color.parseColor("#757186"));
        Switch r33 = new Switch(this);
        this.gypoootmrj = r33;
        r33.setLayoutParams(new LinearLayout.LayoutParams(1138, 1307));
        this.gypoootmrj.setPadding(1, 96, 72, 173);
        linearLayout.addView(this.gypoootmrj);
        this.gypoootmrj.setBackgroundColor(Color.parseColor("#e00216"));
        RatingBar ratingBar = new RatingBar(this);
        this.pzjpqvueye = ratingBar;
        ratingBar.setLayoutParams(new LinearLayout.LayoutParams(WebSocketProtocol.PAYLOAD_SHORT, 1139));
        this.pzjpqvueye.setPadding(69, 51, 110, 0);
        linearLayout.addView(this.pzjpqvueye);
        this.pzjpqvueye.setBackgroundColor(Color.parseColor("#8d42e1"));
        CheckBox checkBox2 = new CheckBox(this);
        this.lyfhcctvfu = checkBox2;
        checkBox2.setLayoutParams(new LinearLayout.LayoutParams(817, 526));
        this.lyfhcctvfu.setPadding(87, 24, 131, 35);
        linearLayout.addView(this.lyfhcctvfu);
        this.lyfhcctvfu.setBackgroundColor(Color.parseColor("#97b774"));
        GridView gridView2 = new GridView(this);
        this.lbrtgrkhoy = gridView2;
        gridView2.setLayoutParams(new LinearLayout.LayoutParams(227, 1888));
        this.lbrtgrkhoy.setPadding(146, 20, 187, 113);
        linearLayout.addView(this.lbrtgrkhoy);
        this.lbrtgrkhoy.setBackgroundColor(Color.parseColor("#be931c"));
        FrameLayout frameLayout = new FrameLayout(this);
        this.jnauwqkuju = frameLayout;
        frameLayout.setLayoutParams(new LinearLayout.LayoutParams(952, 405));
        this.jnauwqkuju.setPadding(23, 189, 156, 173);
        linearLayout.addView(this.jnauwqkuju);
        this.jnauwqkuju.setBackgroundColor(Color.parseColor("#a138ce"));
        LinearLayout linearLayout3 = new LinearLayout(this);
        this.iswbhbnqif = linearLayout3;
        linearLayout3.setLayoutParams(new LinearLayout.LayoutParams(1745, 395));
        this.iswbhbnqif.setPadding(102, 154, BDLocation.TypeServerDecryptError, 182);
        linearLayout.addView(this.iswbhbnqif);
        this.iswbhbnqif.setBackgroundColor(Color.parseColor("#a7d6b6"));
        EditText editText = new EditText(this);
        this.rwwwissrih = editText;
        editText.setLayoutParams(new LinearLayout.LayoutParams(491, 1191));
        this.rwwwissrih.setPadding(129, 17, 88, 91);
        linearLayout.addView(this.rwwwissrih);
        this.rwwwissrih.setBackgroundColor(Color.parseColor("#b93df0"));
        ToggleButton toggleButton = new ToggleButton(this);
        this.nvrefhjizl = toggleButton;
        toggleButton.setLayoutParams(new LinearLayout.LayoutParams(1707, 1334));
        this.nvrefhjizl.setPadding(117, 64, 0, 66);
        linearLayout.addView(this.nvrefhjizl);
        this.nvrefhjizl.setBackgroundColor(Color.parseColor("#136b22"));
        RadioButton radioButton2 = new RadioButton(this);
        this.wmgctvrych = radioButton2;
        radioButton2.setLayoutParams(new LinearLayout.LayoutParams(299, 860));
        this.wmgctvrych.setPadding(118, 115, 6, 172);
        linearLayout.addView(this.wmgctvrych);
        this.wmgctvrych.setBackgroundColor(Color.parseColor("#46d653"));
        ToggleButton toggleButton2 = new ToggleButton(this);
        this.iorylrgtav = toggleButton2;
        toggleButton2.setLayoutParams(new LinearLayout.LayoutParams(1101, 627));
        this.iorylrgtav.setPadding(53, 60, 54, 123);
        linearLayout.addView(this.iorylrgtav);
        this.iorylrgtav.setBackgroundColor(Color.parseColor("#97a2ce"));
        RelativeLayout relativeLayout2 = new RelativeLayout(this);
        this.imwylndntt = relativeLayout2;
        relativeLayout2.setLayoutParams(new LinearLayout.LayoutParams(1826, 690));
        this.imwylndntt.setPadding(177, BDLocation.TypeCoarseLocation, 88, 91);
        linearLayout.addView(this.imwylndntt);
        this.imwylndntt.setBackgroundColor(Color.parseColor("#4c2c21"));
        Spinner spinner2 = new Spinner(this);
        this.nnfklkpqqq = spinner2;
        spinner2.setLayoutParams(new LinearLayout.LayoutParams(958, 581));
        this.nnfklkpqqq.setPadding(0, 173, 196, 6);
        linearLayout.addView(this.nnfklkpqqq);
        this.nnfklkpqqq.setBackgroundColor(Color.parseColor("#5c7e43"));
        GridView gridView3 = new GridView(this);
        this.qbnhsbrshd = gridView3;
        gridView3.setLayoutParams(new LinearLayout.LayoutParams(1891, 1827));
        this.qbnhsbrshd.setPadding(129, 1, 55, 106);
        linearLayout.addView(this.qbnhsbrshd);
        this.qbnhsbrshd.setBackgroundColor(Color.parseColor("#626e15"));
        RadioButton radioButton3 = new RadioButton(this);
        this.eyoyqxfojl = radioButton3;
        radioButton3.setLayoutParams(new LinearLayout.LayoutParams(1072, 963));
        this.eyoyqxfojl.setPadding(191, 157, 34, 127);
        linearLayout.addView(this.eyoyqxfojl);
        this.eyoyqxfojl.setBackgroundColor(Color.parseColor("#014a75"));
        ViewFlipper viewFlipper2 = new ViewFlipper(this);
        this.xdojrwsmzu = viewFlipper2;
        viewFlipper2.setLayoutParams(new LinearLayout.LayoutParams(1357, LocalPlaybackConstants.BUFFER_A_CAN_USE_FLAG));
        this.xdojrwsmzu.setPadding(36, 16, 114, 172);
        linearLayout.addView(this.xdojrwsmzu);
        this.xdojrwsmzu.setBackgroundColor(Color.parseColor("#8a3dc8"));
        FrameLayout frameLayout2 = new FrameLayout(this);
        this.tzvbbljdel = frameLayout2;
        frameLayout2.setLayoutParams(new LinearLayout.LayoutParams(1901, 1797));
        this.tzvbbljdel.setPadding(183, 89, 40, 47);
        linearLayout.addView(this.tzvbbljdel);
        this.tzvbbljdel.setBackgroundColor(Color.parseColor("#d39450"));
        RelativeLayout relativeLayout3 = new RelativeLayout(this);
        this.adozuhvjko = relativeLayout3;
        relativeLayout3.setLayoutParams(new LinearLayout.LayoutParams(103, 1851));
        this.adozuhvjko.setPadding(155, 44, 30, 107);
        linearLayout.addView(this.adozuhvjko);
        this.adozuhvjko.setBackgroundColor(Color.parseColor("#0af5e0"));
        ListView listView = new ListView(this);
        this.mkskycxllw = listView;
        listView.setLayoutParams(new LinearLayout.LayoutParams(1802, 997));
        this.mkskycxllw.setPadding(55, 52, 75, 100);
        linearLayout.addView(this.mkskycxllw);
        this.mkskycxllw.setBackgroundColor(Color.parseColor("#cf5954"));
        CheckBox checkBox3 = new CheckBox(this);
        this.uoyxzakjgw = checkBox3;
        checkBox3.setLayoutParams(new LinearLayout.LayoutParams(244, 885));
        this.uoyxzakjgw.setPadding(132, 89, 133, 23);
        linearLayout.addView(this.uoyxzakjgw);
        this.uoyxzakjgw.setBackgroundColor(Color.parseColor("#4a78e7"));
        ListView listView2 = new ListView(this);
        this.rlfxoutswu = listView2;
        listView2.setLayoutParams(new LinearLayout.LayoutParams(22, 1088));
        this.rlfxoutswu.setPadding(38, 168, 98, 174);
        linearLayout.addView(this.rlfxoutswu);
        this.rlfxoutswu.setBackgroundColor(Color.parseColor("#8dd964"));
        DatePicker datePicker2 = new DatePicker(this);
        this.khvosloifc = datePicker2;
        datePicker2.setLayoutParams(new LinearLayout.LayoutParams(1679, 1477));
        this.khvosloifc.setPadding(9, 185, 10, 79);
        linearLayout.addView(this.khvosloifc);
        this.khvosloifc.setBackgroundColor(Color.parseColor("#86f2ca"));
        ListView listView3 = new ListView(this);
        this.dyrupunsdg = listView3;
        listView3.setLayoutParams(new LinearLayout.LayoutParams(GattClient.STATE_READ_DEVICE_INFO, 1523));
        this.dyrupunsdg.setPadding(79, 78, 108, 133);
        linearLayout.addView(this.dyrupunsdg);
        this.dyrupunsdg.setBackgroundColor(Color.parseColor("#096299"));
        SeekBar seekBar3 = new SeekBar(this);
        this.sczrwirbea = seekBar3;
        seekBar3.setLayoutParams(new LinearLayout.LayoutParams(415, 1809));
        this.sczrwirbea.setPadding(117, 7, 114, 54);
        linearLayout.addView(this.sczrwirbea);
        this.sczrwirbea.setBackgroundColor(Color.parseColor("#7aedf7"));
        TextView textView = new TextView(this);
        this.bkbhbpkjup = textView;
        textView.setLayoutParams(new LinearLayout.LayoutParams(PointerIconCompat.TYPE_ZOOM_IN, FrameMetricsAggregator.EVERY_DURATION));
        this.bkbhbpkjup.setPadding(87, 50, 26, 52);
        linearLayout.addView(this.bkbhbpkjup);
        this.bkbhbpkjup.setBackgroundColor(Color.parseColor("#a41b73"));
        EditText editText2 = new EditText(this);
        this.vnmbgxixtd = editText2;
        editText2.setLayoutParams(new LinearLayout.LayoutParams(290, 1170));
        this.vnmbgxixtd.setPadding(134, 70, 91, 8);
        linearLayout.addView(this.vnmbgxixtd);
        this.vnmbgxixtd.setBackgroundColor(Color.parseColor("#23b844"));
        TableLayout tableLayout = new TableLayout(this);
        this.fkqkkmoamf = tableLayout;
        tableLayout.setLayoutParams(new LinearLayout.LayoutParams(49, 438));
        this.fkqkkmoamf.setPadding(117, 120, 193, 185);
        linearLayout.addView(this.fkqkkmoamf);
        this.fkqkkmoamf.setBackgroundColor(Color.parseColor("#949bdf"));
        ProgressBar progressBar2 = new ProgressBar(this);
        this.xaxsjpflor = progressBar2;
        progressBar2.setLayoutParams(new LinearLayout.LayoutParams(1604, 1732));
        this.xaxsjpflor.setPadding(42, 23, 23, 99);
        linearLayout.addView(this.xaxsjpflor);
        this.xaxsjpflor.setBackgroundColor(Color.parseColor("#10917d"));
        Button button2 = new Button(this);
        this.adyjfrtkrk = button2;
        button2.setLayoutParams(new LinearLayout.LayoutParams(1096, 60));
        this.adyjfrtkrk.setPadding(7, 2, 40, 155);
        linearLayout.addView(this.adyjfrtkrk);
        this.adyjfrtkrk.setBackgroundColor(Color.parseColor("#631749"));
        ListView listView4 = new ListView(this);
        this.jsvgvdwztm = listView4;
        listView4.setLayoutParams(new LinearLayout.LayoutParams(1192, 485));
        this.jsvgvdwztm.setPadding(61, BDLocation.TypeNetWorkLocation, 112, 7);
        linearLayout.addView(this.jsvgvdwztm);
        this.jsvgvdwztm.setBackgroundColor(Color.parseColor("#4f66dd"));
        Button button3 = new Button(this);
        this.umukeohrqa = button3;
        button3.setLayoutParams(new LinearLayout.LayoutParams(1838, 935));
        this.umukeohrqa.setPadding(42, 80, 109, 3);
        linearLayout.addView(this.umukeohrqa);
        this.umukeohrqa.setBackgroundColor(Color.parseColor("#5cac63"));
        DatePicker datePicker3 = new DatePicker(this);
        this.zotoajlmkv = datePicker3;
        datePicker3.setLayoutParams(new LinearLayout.LayoutParams(1852, 1554));
        this.zotoajlmkv.setPadding(88, 192, 20, 47);
        linearLayout.addView(this.zotoajlmkv);
        this.zotoajlmkv.setBackgroundColor(Color.parseColor("#85b750"));
        TableLayout tableLayout2 = new TableLayout(this);
        this.rvvigfrkiu = tableLayout2;
        tableLayout2.setLayoutParams(new LinearLayout.LayoutParams(1503, 1856));
        this.rvvigfrkiu.setPadding(73, 79, 82, 140);
        linearLayout.addView(this.rvvigfrkiu);
        this.rvvigfrkiu.setBackgroundColor(Color.parseColor("#1db586"));
        ProgressBar progressBar3 = new ProgressBar(this);
        this.sjyhimkkee = progressBar3;
        progressBar3.setLayoutParams(new LinearLayout.LayoutParams(1816, 1054));
        this.sjyhimkkee.setPadding(98, 127, 194, 159);
        linearLayout.addView(this.sjyhimkkee);
        this.sjyhimkkee.setBackgroundColor(Color.parseColor("#a96e5e"));
        ListView listView5 = new ListView(this);
        this.nawggrfdbh = listView5;
        listView5.setLayoutParams(new LinearLayout.LayoutParams(1167, 945));
        this.nawggrfdbh.setPadding(171, 20, 68, 20);
        linearLayout.addView(this.nawggrfdbh);
        this.nawggrfdbh.setBackgroundColor(Color.parseColor("#4b6e0e"));
        Spinner spinner3 = new Spinner(this);
        this.yukepcxvlb = spinner3;
        spinner3.setLayoutParams(new LinearLayout.LayoutParams(238, 1724));
        this.yukepcxvlb.setPadding(65, 6, 145, 124);
        linearLayout.addView(this.yukepcxvlb);
        this.yukepcxvlb.setBackgroundColor(Color.parseColor("#5f29b3"));
        EditText editText3 = new EditText(this);
        this.jpnsnqqpdb = editText3;
        editText3.setLayoutParams(new LinearLayout.LayoutParams(FrameMetricsAggregator.EVERY_DURATION, 373));
        this.jpnsnqqpdb.setPadding(129, 174, 145, 26);
        linearLayout.addView(this.jpnsnqqpdb);
        this.jpnsnqqpdb.setBackgroundColor(Color.parseColor("#877c51"));
        ImageView imageView = new ImageView(this);
        this.fofrlktqqr = imageView;
        imageView.setLayoutParams(new LinearLayout.LayoutParams(122, 816));
        this.fofrlktqqr.setPadding(80, 109, 38, 159);
        linearLayout.addView(this.fofrlktqqr);
        this.fofrlktqqr.setBackgroundColor(Color.parseColor("#805c07"));
        Button button4 = new Button(this);
        this.bheeotpvad = button4;
        button4.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.Custom.TYPE_COLOR, 1708));
        this.bheeotpvad.setPadding(12, 16, 176, 118);
        linearLayout.addView(this.bheeotpvad);
        this.bheeotpvad.setBackgroundColor(Color.parseColor("#76b444"));
        DatePicker datePicker4 = new DatePicker(this);
        this.dywhcuvmjq = datePicker4;
        datePicker4.setLayoutParams(new LinearLayout.LayoutParams(114, 1298));
        this.dywhcuvmjq.setPadding(17, 0, 125, 82);
        linearLayout.addView(this.dywhcuvmjq);
        this.dywhcuvmjq.setBackgroundColor(Color.parseColor("#283341"));
        ToggleButton toggleButton3 = new ToggleButton(this);
        this.hsrjptvbmu = toggleButton3;
        toggleButton3.setLayoutParams(new LinearLayout.LayoutParams(71, 37));
        this.hsrjptvbmu.setPadding(BDLocation.TypeNetWorkLocation, 53, 76, 141);
        linearLayout.addView(this.hsrjptvbmu);
        this.hsrjptvbmu.setBackgroundColor(Color.parseColor("#d225de"));
        ProgressBar progressBar4 = new ProgressBar(this);
        this.gkxhwqfnki = progressBar4;
        progressBar4.setLayoutParams(new LinearLayout.LayoutParams(1557, 1755));
        this.gkxhwqfnki.setPadding(91, 178, 198, 66);
        linearLayout.addView(this.gkxhwqfnki);
        this.gkxhwqfnki.setBackgroundColor(Color.parseColor("#a071f9"));
        LinearLayout linearLayout4 = new LinearLayout(this);
        this.akmijveyak = linearLayout4;
        linearLayout4.setLayoutParams(new LinearLayout.LayoutParams(976, 1234));
        this.akmijveyak.setPadding(103, 51, 104, 74);
        linearLayout.addView(this.akmijveyak);
        this.akmijveyak.setBackgroundColor(Color.parseColor("#ce716b"));
        GridView gridView4 = new GridView(this);
        this.afcrvsjgcw = gridView4;
        gridView4.setLayoutParams(new LinearLayout.LayoutParams(638, 918));
        this.afcrvsjgcw.setPadding(76, 90, 72, 156);
        linearLayout.addView(this.afcrvsjgcw);
        this.afcrvsjgcw.setBackgroundColor(Color.parseColor("#cf35ec"));
        ToggleButton toggleButton4 = new ToggleButton(this);
        this.oynwkadzkx = toggleButton4;
        toggleButton4.setLayoutParams(new LinearLayout.LayoutParams(199, 104));
        this.oynwkadzkx.setPadding(109, 81, 19, 22);
        linearLayout.addView(this.oynwkadzkx);
        this.oynwkadzkx.setBackgroundColor(Color.parseColor("#68e309"));
        TableLayout tableLayout3 = new TableLayout(this);
        this.nmbbdpqrgm = tableLayout3;
        tableLayout3.setLayoutParams(new LinearLayout.LayoutParams(1665, 1809));
        this.nmbbdpqrgm.setPadding(127, 26, 127, 50);
        linearLayout.addView(this.nmbbdpqrgm);
        this.nmbbdpqrgm.setBackgroundColor(Color.parseColor("#90e0d0"));
        Spinner spinner4 = new Spinner(this);
        this.adndzmcquv = spinner4;
        spinner4.setLayoutParams(new LinearLayout.LayoutParams(334, 685));
        this.adndzmcquv.setPadding(104, 154, 99, 74);
        linearLayout.addView(this.adndzmcquv);
        this.adndzmcquv.setBackgroundColor(Color.parseColor("#adf50d"));
        RelativeLayout relativeLayout4 = new RelativeLayout(this);
        this.ryhtaaumnl = relativeLayout4;
        relativeLayout4.setLayoutParams(new LinearLayout.LayoutParams(CropImage.CROP_IMAGE_ACTIVITY_REQUEST_CODE, 251));
        this.ryhtaaumnl.setPadding(124, 3, 57, PictureConfig.CHOOSE_REQUEST);
        linearLayout.addView(this.ryhtaaumnl);
        this.ryhtaaumnl.setBackgroundColor(Color.parseColor("#a387bc"));
        RelativeLayout relativeLayout5 = new RelativeLayout(this);
        this.mwtbmjnure = relativeLayout5;
        relativeLayout5.setLayoutParams(new LinearLayout.LayoutParams(943, 793));
        this.mwtbmjnure.setPadding(98, 72, 76, 33);
        linearLayout.addView(this.mwtbmjnure);
        this.mwtbmjnure.setBackgroundColor(Color.parseColor("#77c965"));
        SeekBar seekBar4 = new SeekBar(this);
        this.qpoypnnirf = seekBar4;
        seekBar4.setLayoutParams(new LinearLayout.LayoutParams(1157, 1156));
        this.qpoypnnirf.setPadding(6, 27, 83, 31);
        linearLayout.addView(this.qpoypnnirf);
        this.qpoypnnirf.setBackgroundColor(Color.parseColor("#f6657d"));
        TimePicker timePicker = new TimePicker(this);
        this.lgtmtjaquv = timePicker;
        timePicker.setLayoutParams(new LinearLayout.LayoutParams(1503, 774));
        this.lgtmtjaquv.setPadding(58, 90, 105, 119);
        linearLayout.addView(this.lgtmtjaquv);
        this.lgtmtjaquv.setBackgroundColor(Color.parseColor("#e1377b"));
        RadioButton radioButton4 = new RadioButton(this);
        this.svmgrrxljx = radioButton4;
        radioButton4.setLayoutParams(new LinearLayout.LayoutParams(1264, 305));
        this.svmgrrxljx.setPadding(143, 63, 71, 26);
        linearLayout.addView(this.svmgrrxljx);
        this.svmgrrxljx.setBackgroundColor(Color.parseColor("#31a703"));
        SeekBar seekBar5 = new SeekBar(this);
        this.nwrvbospsq = seekBar5;
        seekBar5.setLayoutParams(new LinearLayout.LayoutParams(941, CodeUtils.DEFAULT_REQ_HEIGHT));
        this.nwrvbospsq.setPadding(82, 135, 192, 141);
        linearLayout.addView(this.nwrvbospsq);
        this.nwrvbospsq.setBackgroundColor(Color.parseColor("#89ad38"));
        Switch r2 = new Switch(this);
        this.ibtyeiwyth = r2;
        r2.setLayoutParams(new LinearLayout.LayoutParams(1241, 1590));
        this.ibtyeiwyth.setPadding(108, 74, 192, 156);
        linearLayout.addView(this.ibtyeiwyth);
        this.ibtyeiwyth.setBackgroundColor(Color.parseColor("#ee501c"));
        TimePicker timePicker2 = new TimePicker(this);
        this.equbjdcvfq = timePicker2;
        timePicker2.setLayoutParams(new LinearLayout.LayoutParams(1874, TypedValues.Custom.TYPE_COLOR));
        this.equbjdcvfq.setPadding(154, 113, 89, 179);
        linearLayout.addView(this.equbjdcvfq);
        this.equbjdcvfq.setBackgroundColor(Color.parseColor("#ecd630"));
        Switch r22 = new Switch(this);
        this.rehbuvtpra = r22;
        r22.setLayoutParams(new LinearLayout.LayoutParams(4, 170));
        this.rehbuvtpra.setPadding(182, 117, 170, 135);
        linearLayout.addView(this.rehbuvtpra);
        this.rehbuvtpra.setBackgroundColor(Color.parseColor("#4fae94"));
        RatingBar ratingBar2 = new RatingBar(this);
        this.ukqhbrrllq = ratingBar2;
        ratingBar2.setLayoutParams(new LinearLayout.LayoutParams(1890, 520));
        this.ukqhbrrllq.setPadding(49, 51, 46, 180);
        linearLayout.addView(this.ukqhbrrllq);
        this.ukqhbrrllq.setBackgroundColor(Color.parseColor("#b063c7"));
        CheckBox checkBox4 = new CheckBox(this);
        this.qhqysffgto = checkBox4;
        checkBox4.setLayoutParams(new LinearLayout.LayoutParams(419, 919));
        this.qhqysffgto.setPadding(37, 13, 14, 41);
        linearLayout.addView(this.qhqysffgto);
        this.qhqysffgto.setBackgroundColor(Color.parseColor("#d80965"));
    }
}
