package com.device.watch.com.device.watch.tkmtkwgmvf;

import android.app.Activity;
import android.graphics.Color;
import android.os.Bundle;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.CheckBox;
import android.widget.DatePicker;
import android.widget.EditText;
import android.widget.FrameLayout;
import android.widget.GridView;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ListView;
import android.widget.ProgressBar;
import android.widget.RadioButton;
import android.widget.RatingBar;
import android.widget.RelativeLayout;
import android.widget.ScrollView;
import android.widget.SeekBar;
import android.widget.Spinner;
import android.widget.Switch;
import android.widget.TableLayout;
import android.widget.TextView;
import android.widget.TimePicker;
import android.widget.ToggleButton;
import android.widget.ViewFlipper;
import androidx.constraintlayout.core.motion.utils.TypedValues;
import androidx.core.view.PointerIconCompat;
import com.baidu.location.BDLocation;
import com.google.android.gms.common.ConnectionResult;
import com.google.zxing.pdf417.PDF417Common;
import com.luck.picture.lib.config.PictureConfig;
import com.realsil.sdk.bbpro.equalizer.AudioEq;
import com.realsil.sdk.core.bluetooth.impl.BluetoothClassImpl;

/* loaded from: classes2.dex */
public class YzhmcacziqcActivity extends Activity {
    DatePicker aicphrbgmi;
    ListView alfemkamzx;
    ListView bmuenzkhog;
    CheckBox bojdegylfv;
    Switch buuqdsazgy;
    Spinner cdoqowgdkf;
    RatingBar cipchbdxqh;
    Spinner cypdtiazak;
    RadioButton dnnrbxhyyx;
    Spinner dzakmtvpjt;
    ProgressBar eveyqluilg;
    Spinner ewlcvznxek;
    GridView ezpxonpklb;
    EditText fcbxfggwlz;
    ImageView fgizoawtnd;
    TableLayout fgtqvpkcrx;
    Switch fiqvdpbizs;
    ViewFlipper fljjixqqtz;
    ImageView gdqurwdajr;
    TimePicker ggfqyklrfw;
    ScrollView gkwbceobtn;
    Spinner gmlwovmsoz;
    EditText gocmtctxem;
    LinearLayout gpagkpuprg;
    GridView hcaohlmnrt;
    ScrollView hhiqobgkpm;
    EditText hlwyrfbetb;
    ImageView htpjddjqml;
    ViewFlipper hundegedaz;
    GridView hwmfhdfpdh;
    TextView imqllnopwy;
    ScrollView iogphfbvan;
    Switch izzdyfdlix;
    Button jjgbaioere;
    TimePicker jkuowsgaxs;
    FrameLayout jnfyrrrhcf;
    TextView jvcpyjvqsn;
    FrameLayout jvmsaidtlq;
    DatePicker jwnfzxxrlm;
    Switch kckgutwtto;
    EditText kgmljssdvb;
    RelativeLayout kysbgdwedw;
    DatePicker labsofmyxd;
    TextView ldlcwismtl;
    ProgressBar leinqwmtlp;
    DatePicker llyfietouw;
    RelativeLayout lmtnzscxrn;
    ToggleButton lobvlzmovx;
    EditText luneswoejf;
    Button lwbscrjett;
    LinearLayout lxisrklgld;
    CheckBox modaufuwai;
    RelativeLayout mzmhjngtqk;
    Button nckdxmlkeg;
    GridView nitkuhhsio;
    TextView nkvwuerkmq;
    TimePicker nrejeglaqt;
    DatePicker nsdtueiavz;
    RelativeLayout ntspdfdgjp;
    SeekBar ojjapqjznd;
    CheckBox pbyaecalrr;
    ListView psxpqqpkdb;
    Spinner pznojgljpb;
    TableLayout qjuufibfda;
    RelativeLayout qpyqwtsqcg;
    TableLayout qszqptaeau;
    ImageView rbcgphemkv;
    ImageView rfsmevkntc;
    RadioButton rwbuajcqvo;
    RelativeLayout sduzamoevs;
    SeekBar sotmwqiatz;
    RatingBar szzdngwisb;
    CheckBox thnwhdqidw;
    Switch tkklgxwqwl;
    Button tqekwqwmtn;
    TableLayout vcikzytjlc;
    ToggleButton vgscwmbjfh;
    RatingBar vlmmpazced;
    ListView vqlqxszjur;
    ToggleButton vysmiovscb;
    ListView warzkhaape;
    ScrollView weephsjjgq;
    TimePicker wutsqfufmh;
    TimePicker xcdhuobnmf;
    RelativeLayout xepalqddqs;
    Spinner yhcovdedyf;
    Spinner ymvtldbwcq;

    @Override // android.app.Activity
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        LinearLayout linearLayout = new LinearLayout(this);
        setContentView(linearLayout);
        linearLayout.setLayoutParams(new ViewGroup.LayoutParams(-1, -1));
        linearLayout.setOrientation(1);
        linearLayout.setBackgroundColor(Color.parseColor("#2d799b"));
        ListView listView = new ListView(this);
        this.psxpqqpkdb = listView;
        listView.setLayoutParams(new LinearLayout.LayoutParams(896, 1509));
        this.psxpqqpkdb.setPadding(48, 185, 149, 196);
        linearLayout.addView(this.psxpqqpkdb);
        this.psxpqqpkdb.setBackgroundColor(Color.parseColor("#2f911c"));
        ListView listView2 = new ListView(this);
        this.alfemkamzx = listView2;
        listView2.setLayoutParams(new LinearLayout.LayoutParams(385, 308));
        this.alfemkamzx.setPadding(16, 69, 189, 89);
        linearLayout.addView(this.alfemkamzx);
        this.alfemkamzx.setBackgroundColor(Color.parseColor("#006414"));
        TableLayout tableLayout = new TableLayout(this);
        this.qjuufibfda = tableLayout;
        tableLayout.setLayoutParams(new LinearLayout.LayoutParams(166, 465));
        this.qjuufibfda.setPadding(123, 171, 99, 80);
        linearLayout.addView(this.qjuufibfda);
        this.qjuufibfda.setBackgroundColor(Color.parseColor("#aa174e"));
        EditText editText = new EditText(this);
        this.kgmljssdvb = editText;
        editText.setLayoutParams(new LinearLayout.LayoutParams(334, 193));
        this.kgmljssdvb.setPadding(3, 183, 9, 9);
        linearLayout.addView(this.kgmljssdvb);
        this.kgmljssdvb.setBackgroundColor(Color.parseColor("#572fe5"));
        Button button = new Button(this);
        this.nckdxmlkeg = button;
        button.setLayoutParams(new LinearLayout.LayoutParams(ConnectionResult.DRIVE_EXTERNAL_STORAGE_REQUIRED, 257));
        this.nckdxmlkeg.setPadding(101, 137, 179, 144);
        linearLayout.addView(this.nckdxmlkeg);
        this.nckdxmlkeg.setBackgroundColor(Color.parseColor("#c74ddd"));
        TextView textView = new TextView(this);
        this.ldlcwismtl = textView;
        textView.setLayoutParams(new LinearLayout.LayoutParams(812, 581));
        this.ldlcwismtl.setPadding(197, 35, 196, 110);
        linearLayout.addView(this.ldlcwismtl);
        this.ldlcwismtl.setBackgroundColor(Color.parseColor("#331a7d"));
        ViewFlipper viewFlipper = new ViewFlipper(this);
        this.hundegedaz = viewFlipper;
        viewFlipper.setLayoutParams(new LinearLayout.LayoutParams(1471, 791));
        this.hundegedaz.setPadding(125, 168, BDLocation.TypeCoarseLocation, 143);
        linearLayout.addView(this.hundegedaz);
        this.hundegedaz.setBackgroundColor(Color.parseColor("#6babb5"));
        SeekBar seekBar = new SeekBar(this);
        this.sotmwqiatz = seekBar;
        seekBar.setLayoutParams(new LinearLayout.LayoutParams(1398, 1309));
        this.sotmwqiatz.setPadding(66, 6, 166, 134);
        linearLayout.addView(this.sotmwqiatz);
        this.sotmwqiatz.setBackgroundColor(Color.parseColor("#9fc4ab"));
        GridView gridView = new GridView(this);
        this.ezpxonpklb = gridView;
        gridView.setLayoutParams(new LinearLayout.LayoutParams(516, 518));
        this.ezpxonpklb.setPadding(83, 49, 152, 149);
        linearLayout.addView(this.ezpxonpklb);
        this.ezpxonpklb.setBackgroundColor(Color.parseColor("#b6094e"));
        ImageView imageView = new ImageView(this);
        this.htpjddjqml = imageView;
        imageView.setLayoutParams(new LinearLayout.LayoutParams(1389, 166));
        this.htpjddjqml.setPadding(191, 0, 154, 186);
        linearLayout.addView(this.htpjddjqml);
        this.htpjddjqml.setBackground(new Fcnxvytbfzn());
        RelativeLayout relativeLayout = new RelativeLayout(this);
        this.ntspdfdgjp = relativeLayout;
        relativeLayout.setLayoutParams(new LinearLayout.LayoutParams(931, 522));
        this.ntspdfdgjp.setPadding(101, 127, 28, 6);
        linearLayout.addView(this.ntspdfdgjp);
        this.ntspdfdgjp.setBackgroundColor(Color.parseColor("#509b57"));
        Spinner spinner = new Spinner(this);
        this.pznojgljpb = spinner;
        spinner.setLayoutParams(new LinearLayout.LayoutParams(297, 1042));
        this.pznojgljpb.setPadding(17, 19, 184, 50);
        linearLayout.addView(this.pznojgljpb);
        this.pznojgljpb.setBackgroundColor(Color.parseColor("#871df9"));
        Spinner spinner2 = new Spinner(this);
        this.dzakmtvpjt = spinner2;
        spinner2.setLayoutParams(new LinearLayout.LayoutParams(630, 234));
        this.dzakmtvpjt.setPadding(22, 20, 62, 69);
        linearLayout.addView(this.dzakmtvpjt);
        this.dzakmtvpjt.setBackgroundColor(Color.parseColor("#cbe8d0"));
        Switch r2 = new Switch(this);
        this.buuqdsazgy = r2;
        r2.setLayoutParams(new LinearLayout.LayoutParams(410, 1397));
        this.buuqdsazgy.setPadding(154, 147, 35, 197);
        linearLayout.addView(this.buuqdsazgy);
        this.buuqdsazgy.setBackgroundColor(Color.parseColor("#9d4a97"));
        Spinner spinner3 = new Spinner(this);
        this.ewlcvznxek = spinner3;
        spinner3.setLayoutParams(new LinearLayout.LayoutParams(1197, 1159));
        this.ewlcvznxek.setPadding(197, 0, 172, 18);
        linearLayout.addView(this.ewlcvznxek);
        this.ewlcvznxek.setBackgroundColor(Color.parseColor("#42f9d7"));
        ToggleButton toggleButton = new ToggleButton(this);
        this.lobvlzmovx = toggleButton;
        toggleButton.setLayoutParams(new LinearLayout.LayoutParams(370, 620));
        this.lobvlzmovx.setPadding(96, 0, 194, 181);
        linearLayout.addView(this.lobvlzmovx);
        this.lobvlzmovx.setBackgroundColor(Color.parseColor("#486dbc"));
        ImageView imageView2 = new ImageView(this);
        this.fgizoawtnd = imageView2;
        imageView2.setLayoutParams(new LinearLayout.LayoutParams(251, 1660));
        this.fgizoawtnd.setPadding(154, 70, 45, 48);
        linearLayout.addView(this.fgizoawtnd);
        this.fgizoawtnd.setBackgroundColor(Color.parseColor("#6b390b"));
        RelativeLayout relativeLayout2 = new RelativeLayout(this);
        this.sduzamoevs = relativeLayout2;
        relativeLayout2.setLayoutParams(new LinearLayout.LayoutParams(599, 1010));
        this.sduzamoevs.setPadding(143, 171, 68, 8);
        linearLayout.addView(this.sduzamoevs);
        this.sduzamoevs.setBackgroundColor(Color.parseColor("#a5fc72"));
        TextView textView2 = new TextView(this);
        this.nkvwuerkmq = textView2;
        textView2.setLayoutParams(new LinearLayout.LayoutParams(973, 244));
        this.nkvwuerkmq.setPadding(70, 121, 6, 31);
        linearLayout.addView(this.nkvwuerkmq);
        this.nkvwuerkmq.setBackgroundColor(Color.parseColor("#72a1c2"));
        RadioButton radioButton = new RadioButton(this);
        this.dnnrbxhyyx = radioButton;
        radioButton.setLayoutParams(new LinearLayout.LayoutParams(412, 1045));
        this.dnnrbxhyyx.setPadding(127, 16, 144, 118);
        linearLayout.addView(this.dnnrbxhyyx);
        this.dnnrbxhyyx.setBackgroundColor(Color.parseColor("#c68eb3"));
        Button button2 = new Button(this);
        this.lwbscrjett = button2;
        button2.setLayoutParams(new LinearLayout.LayoutParams(1593, 1773));
        this.lwbscrjett.setPadding(151, 4, 44, 38);
        linearLayout.addView(this.lwbscrjett);
        this.lwbscrjett.setBackgroundColor(Color.parseColor("#3fe672"));
        ImageView imageView3 = new ImageView(this);
        this.gdqurwdajr = imageView3;
        imageView3.setLayoutParams(new LinearLayout.LayoutParams(PointerIconCompat.TYPE_GRAB, 1714));
        this.gdqurwdajr.setPadding(48, 39, 27, 199);
        linearLayout.addView(this.gdqurwdajr);
        this.gdqurwdajr.setBackgroundColor(Color.parseColor("#8f23e2"));
        EditText editText2 = new EditText(this);
        this.fcbxfggwlz = editText2;
        editText2.setLayoutParams(new LinearLayout.LayoutParams(687, 1671));
        this.fcbxfggwlz.setPadding(136, 120, 143, 50);
        linearLayout.addView(this.fcbxfggwlz);
        this.fcbxfggwlz.setBackgroundColor(Color.parseColor("#768e5f"));
        Switch r22 = new Switch(this);
        this.tkklgxwqwl = r22;
        r22.setLayoutParams(new LinearLayout.LayoutParams(1564, 666));
        this.tkklgxwqwl.setPadding(117, 198, 63, 97);
        linearLayout.addView(this.tkklgxwqwl);
        this.tkklgxwqwl.setBackgroundColor(Color.parseColor("#12b5b3"));
        ImageView imageView4 = new ImageView(this);
        this.rfsmevkntc = imageView4;
        imageView4.setLayoutParams(new LinearLayout.LayoutParams(377, 1284));
        this.rfsmevkntc.setPadding(91, 31, 87, 198);
        linearLayout.addView(this.rfsmevkntc);
        this.rfsmevkntc.setBackgroundColor(Color.parseColor("#fc7d7e"));
        LinearLayout linearLayout2 = new LinearLayout(this);
        this.gpagkpuprg = linearLayout2;
        linearLayout2.setLayoutParams(new LinearLayout.LayoutParams(171, 561));
        this.gpagkpuprg.setPadding(140, 193, 179, 48);
        linearLayout.addView(this.gpagkpuprg);
        this.gpagkpuprg.setBackgroundColor(Color.parseColor("#47343a"));
        ViewFlipper viewFlipper2 = new ViewFlipper(this);
        this.fljjixqqtz = viewFlipper2;
        viewFlipper2.setLayoutParams(new LinearLayout.LayoutParams(269, 342));
        this.fljjixqqtz.setPadding(82, 138, 169, 113);
        linearLayout.addView(this.fljjixqqtz);
        this.fljjixqqtz.setBackgroundColor(Color.parseColor("#6e149e"));
        TimePicker timePicker = new TimePicker(this);
        this.wutsqfufmh = timePicker;
        timePicker.setLayoutParams(new LinearLayout.LayoutParams(1988, 698));
        this.wutsqfufmh.setPadding(42, 59, 185, 36);
        linearLayout.addView(this.wutsqfufmh);
        this.wutsqfufmh.setBackgroundColor(Color.parseColor("#dd3cbe"));
        ListView listView3 = new ListView(this);
        this.bmuenzkhog = listView3;
        listView3.setLayoutParams(new LinearLayout.LayoutParams(73, 869));
        this.bmuenzkhog.setPadding(32, 151, 154, 155);
        linearLayout.addView(this.bmuenzkhog);
        this.bmuenzkhog.setBackgroundColor(Color.parseColor("#130041"));
        Switch r23 = new Switch(this);
        this.kckgutwtto = r23;
        r23.setLayoutParams(new LinearLayout.LayoutParams(1849, 268));
        this.kckgutwtto.setPadding(50, 123, 185, 47);
        linearLayout.addView(this.kckgutwtto);
        this.kckgutwtto.setBackgroundColor(Color.parseColor("#ba8487"));
        ListView listView4 = new ListView(this);
        this.warzkhaape = listView4;
        listView4.setLayoutParams(new LinearLayout.LayoutParams(1156, 38));
        this.warzkhaape.setPadding(171, 134, 64, 177);
        linearLayout.addView(this.warzkhaape);
        this.warzkhaape.setBackgroundColor(Color.parseColor("#6219dd"));
        TimePicker timePicker2 = new TimePicker(this);
        this.jkuowsgaxs = timePicker2;
        timePicker2.setLayoutParams(new LinearLayout.LayoutParams(56, 1169));
        this.jkuowsgaxs.setPadding(22, 96, 41, 116);
        linearLayout.addView(this.jkuowsgaxs);
        this.jkuowsgaxs.setBackgroundColor(Color.parseColor("#dae62a"));
        TimePicker timePicker3 = new TimePicker(this);
        this.xcdhuobnmf = timePicker3;
        timePicker3.setLayoutParams(new LinearLayout.LayoutParams(1138, 1765));
        this.xcdhuobnmf.setPadding(156, 176, 15, 61);
        linearLayout.addView(this.xcdhuobnmf);
        this.xcdhuobnmf.setBackgroundColor(Color.parseColor("#a42267"));
        DatePicker datePicker = new DatePicker(this);
        this.nsdtueiavz = datePicker;
        datePicker.setLayoutParams(new LinearLayout.LayoutParams(1145, 786));
        this.nsdtueiavz.setPadding(67, 141, 24, 50);
        linearLayout.addView(this.nsdtueiavz);
        this.nsdtueiavz.setBackgroundColor(Color.parseColor("#757ee6"));
        TableLayout tableLayout2 = new TableLayout(this);
        this.vcikzytjlc = tableLayout2;
        tableLayout2.setLayoutParams(new LinearLayout.LayoutParams(1487, 573));
        this.vcikzytjlc.setPadding(156, 175, 72, 95);
        linearLayout.addView(this.vcikzytjlc);
        this.vcikzytjlc.setBackgroundColor(Color.parseColor("#dad410"));
        TableLayout tableLayout3 = new TableLayout(this);
        this.fgtqvpkcrx = tableLayout3;
        tableLayout3.setLayoutParams(new LinearLayout.LayoutParams(925, 1005));
        this.fgtqvpkcrx.setPadding(159, 79, 117, 8);
        linearLayout.addView(this.fgtqvpkcrx);
        this.fgtqvpkcrx.setBackgroundColor(Color.parseColor("#f022f5"));
        Spinner spinner4 = new Spinner(this);
        this.gmlwovmsoz = spinner4;
        spinner4.setLayoutParams(new LinearLayout.LayoutParams(PDF417Common.NUMBER_OF_CODEWORDS, 1099));
        this.gmlwovmsoz.setPadding(198, 65, BDLocation.TypeServerDecryptError, 88);
        linearLayout.addView(this.gmlwovmsoz);
        this.gmlwovmsoz.setBackgroundColor(Color.parseColor("#3c96a0"));
        RelativeLayout relativeLayout3 = new RelativeLayout(this);
        this.kysbgdwedw = relativeLayout3;
        relativeLayout3.setLayoutParams(new LinearLayout.LayoutParams(1375, 1439));
        this.kysbgdwedw.setPadding(101, 123, 146, 184);
        linearLayout.addView(this.kysbgdwedw);
        this.kysbgdwedw.setBackgroundColor(Color.parseColor("#a12517"));
        DatePicker datePicker2 = new DatePicker(this);
        this.llyfietouw = datePicker2;
        datePicker2.setLayoutParams(new LinearLayout.LayoutParams(921, BluetoothClassImpl.Device.PERIPHERAL_POINTING));
        this.llyfietouw.setPadding(34, 158, 156, 99);
        linearLayout.addView(this.llyfietouw);
        this.llyfietouw.setBackgroundColor(Color.parseColor("#878766"));
        Spinner spinner5 = new Spinner(this);
        this.ymvtldbwcq = spinner5;
        spinner5.setLayoutParams(new LinearLayout.LayoutParams(756, 1259));
        this.ymvtldbwcq.setPadding(22, 57, 190, 53);
        linearLayout.addView(this.ymvtldbwcq);
        this.ymvtldbwcq.setBackgroundColor(Color.parseColor("#c876da"));
        RelativeLayout relativeLayout4 = new RelativeLayout(this);
        this.qpyqwtsqcg = relativeLayout4;
        relativeLayout4.setLayoutParams(new LinearLayout.LayoutParams(1810, 1900));
        this.qpyqwtsqcg.setPadding(39, 118, 39, 123);
        linearLayout.addView(this.qpyqwtsqcg);
        this.qpyqwtsqcg.setBackgroundColor(Color.parseColor("#1b5f17"));
        FrameLayout frameLayout = new FrameLayout(this);
        this.jvmsaidtlq = frameLayout;
        frameLayout.setLayoutParams(new LinearLayout.LayoutParams(525, 594));
        this.jvmsaidtlq.setPadding(88, 196, 117, 117);
        linearLayout.addView(this.jvmsaidtlq);
        this.jvmsaidtlq.setBackgroundColor(Color.parseColor("#4551c3"));
        Button button3 = new Button(this);
        this.tqekwqwmtn = button3;
        button3.setLayoutParams(new LinearLayout.LayoutParams(1918, 644));
        this.tqekwqwmtn.setPadding(71, 100, 87, 183);
        linearLayout.addView(this.tqekwqwmtn);
        this.tqekwqwmtn.setBackgroundColor(Color.parseColor("#b2866e"));
        RelativeLayout relativeLayout5 = new RelativeLayout(this);
        this.mzmhjngtqk = relativeLayout5;
        relativeLayout5.setLayoutParams(new LinearLayout.LayoutParams(1027, 1210));
        this.mzmhjngtqk.setPadding(154, 96, 0, 184);
        linearLayout.addView(this.mzmhjngtqk);
        this.mzmhjngtqk.setBackgroundColor(Color.parseColor("#602194"));
        RatingBar ratingBar = new RatingBar(this);
        this.cipchbdxqh = ratingBar;
        ratingBar.setLayoutParams(new LinearLayout.LayoutParams(462, 1918));
        this.cipchbdxqh.setPadding(6, 62, 153, 154);
        linearLayout.addView(this.cipchbdxqh);
        this.cipchbdxqh.setBackgroundColor(Color.parseColor("#285810"));
        DatePicker datePicker3 = new DatePicker(this);
        this.jwnfzxxrlm = datePicker3;
        datePicker3.setLayoutParams(new LinearLayout.LayoutParams(1401, 472));
        this.jwnfzxxrlm.setPadding(132, 43, 90, 39);
        linearLayout.addView(this.jwnfzxxrlm);
        this.jwnfzxxrlm.setBackgroundColor(Color.parseColor("#8cade2"));
        CheckBox checkBox = new CheckBox(this);
        this.pbyaecalrr = checkBox;
        checkBox.setLayoutParams(new LinearLayout.LayoutParams(1274, 1232));
        this.pbyaecalrr.setPadding(129, 155, 149, 92);
        linearLayout.addView(this.pbyaecalrr);
        this.pbyaecalrr.setBackgroundColor(Color.parseColor("#358946"));
        RadioButton radioButton2 = new RadioButton(this);
        this.rwbuajcqvo = radioButton2;
        radioButton2.setLayoutParams(new LinearLayout.LayoutParams(1196, 390));
        this.rwbuajcqvo.setPadding(186, 166, 191, 46);
        linearLayout.addView(this.rwbuajcqvo);
        this.rwbuajcqvo.setBackgroundColor(Color.parseColor("#916380"));
        ToggleButton toggleButton2 = new ToggleButton(this);
        this.vysmiovscb = toggleButton2;
        toggleButton2.setLayoutParams(new LinearLayout.LayoutParams(1428, 1717));
        this.vysmiovscb.setPadding(17, 76, 4, 130);
        linearLayout.addView(this.vysmiovscb);
        this.vysmiovscb.setBackgroundColor(Color.parseColor("#a2c10c"));
        GridView gridView2 = new GridView(this);
        this.hcaohlmnrt = gridView2;
        gridView2.setLayoutParams(new LinearLayout.LayoutParams(AudioEq.PARSE_EQ_DATA_LENGTH, 494));
        this.hcaohlmnrt.setPadding(16, 17, 102, 51);
        linearLayout.addView(this.hcaohlmnrt);
        this.hcaohlmnrt.setBackgroundColor(Color.parseColor("#1d4d84"));
        EditText editText3 = new EditText(this);
        this.gocmtctxem = editText3;
        editText3.setLayoutParams(new LinearLayout.LayoutParams(568, 760));
        this.gocmtctxem.setPadding(152, 69, 106, 53);
        linearLayout.addView(this.gocmtctxem);
        this.gocmtctxem.setBackgroundColor(Color.parseColor("#ebd455"));
        Switch r24 = new Switch(this);
        this.izzdyfdlix = r24;
        r24.setLayoutParams(new LinearLayout.LayoutParams(370, 445));
        this.izzdyfdlix.setPadding(6, 187, 191, 29);
        linearLayout.addView(this.izzdyfdlix);
        this.izzdyfdlix.setBackgroundColor(Color.parseColor("#03e206"));
        GridView gridView3 = new GridView(this);
        this.hwmfhdfpdh = gridView3;
        gridView3.setLayoutParams(new LinearLayout.LayoutParams(844, 1175));
        this.hwmfhdfpdh.setPadding(18, BDLocation.TypeServerDecryptError, 4, 51);
        linearLayout.addView(this.hwmfhdfpdh);
        this.hwmfhdfpdh.setBackgroundColor(Color.parseColor("#ed82b5"));
        Spinner spinner6 = new Spinner(this);
        this.yhcovdedyf = spinner6;
        spinner6.setLayoutParams(new LinearLayout.LayoutParams(226, 1169));
        this.yhcovdedyf.setPadding(92, 88, 165, 31);
        linearLayout.addView(this.yhcovdedyf);
        this.yhcovdedyf.setBackgroundColor(Color.parseColor("#0a4814"));
        ListView listView5 = new ListView(this);
        this.vqlqxszjur = listView5;
        listView5.setLayoutParams(new LinearLayout.LayoutParams(1730, 147));
        this.vqlqxszjur.setPadding(44, BDLocation.TypeServerDecryptError, 49, 16);
        linearLayout.addView(this.vqlqxszjur);
        this.vqlqxszjur.setBackgroundColor(Color.parseColor("#ec5106"));
        GridView gridView4 = new GridView(this);
        this.nitkuhhsio = gridView4;
        gridView4.setLayoutParams(new LinearLayout.LayoutParams(314, 1836));
        this.nitkuhhsio.setPadding(181, 25, 139, 67);
        linearLayout.addView(this.nitkuhhsio);
        this.nitkuhhsio.setBackgroundColor(Color.parseColor("#447d57"));
        ScrollView scrollView = new ScrollView(this);
        this.weephsjjgq = scrollView;
        scrollView.setLayoutParams(new LinearLayout.LayoutParams(1844, 1739));
        this.weephsjjgq.setPadding(95, 88, 11, 32);
        linearLayout.addView(this.weephsjjgq);
        this.weephsjjgq.setBackgroundColor(Color.parseColor("#4f1c6e"));
        ProgressBar progressBar = new ProgressBar(this);
        this.leinqwmtlp = progressBar;
        progressBar.setLayoutParams(new LinearLayout.LayoutParams(1272, 1984));
        this.leinqwmtlp.setPadding(190, 185, 9, 88);
        linearLayout.addView(this.leinqwmtlp);
        this.leinqwmtlp.setBackgroundColor(Color.parseColor("#b5b880"));
        RatingBar ratingBar2 = new RatingBar(this);
        this.vlmmpazced = ratingBar2;
        ratingBar2.setLayoutParams(new LinearLayout.LayoutParams(342, 1429));
        this.vlmmpazced.setPadding(36, 197, 182, 155);
        linearLayout.addView(this.vlmmpazced);
        this.vlmmpazced.setBackgroundColor(Color.parseColor("#274985"));
        TextView textView3 = new TextView(this);
        this.imqllnopwy = textView3;
        textView3.setLayoutParams(new LinearLayout.LayoutParams(1287, 1922));
        this.imqllnopwy.setPadding(63, 67, 86, 166);
        linearLayout.addView(this.imqllnopwy);
        this.imqllnopwy.setBackgroundColor(Color.parseColor("#515aa3"));
        ScrollView scrollView2 = new ScrollView(this);
        this.gkwbceobtn = scrollView2;
        scrollView2.setLayoutParams(new LinearLayout.LayoutParams(103, 1733));
        this.gkwbceobtn.setPadding(103, 136, 110, 16);
        linearLayout.addView(this.gkwbceobtn);
        this.gkwbceobtn.setBackgroundColor(Color.parseColor("#c92863"));
        RelativeLayout relativeLayout6 = new RelativeLayout(this);
        this.xepalqddqs = relativeLayout6;
        relativeLayout6.setLayoutParams(new LinearLayout.LayoutParams(1752, 56));
        this.xepalqddqs.setPadding(BDLocation.TypeServerError, 133, 22, 173);
        linearLayout.addView(this.xepalqddqs);
        this.xepalqddqs.setBackgroundColor(Color.parseColor("#76619c"));
        CheckBox checkBox2 = new CheckBox(this);
        this.modaufuwai = checkBox2;
        checkBox2.setLayoutParams(new LinearLayout.LayoutParams(1838, 1188));
        this.modaufuwai.setPadding(31, 183, 195, 155);
        linearLayout.addView(this.modaufuwai);
        this.modaufuwai.setBackgroundColor(Color.parseColor("#f5cd01"));
        TextView textView4 = new TextView(this);
        this.jvcpyjvqsn = textView4;
        textView4.setLayoutParams(new LinearLayout.LayoutParams(667, 1371));
        this.jvcpyjvqsn.setPadding(59, 144, 172, 138);
        linearLayout.addView(this.jvcpyjvqsn);
        this.jvcpyjvqsn.setBackgroundColor(Color.parseColor("#40a8ef"));
        ScrollView scrollView3 = new ScrollView(this);
        this.hhiqobgkpm = scrollView3;
        scrollView3.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.TransitionType.TYPE_AUTO_TRANSITION, 1083));
        this.hhiqobgkpm.setPadding(187, 44, 15, 24);
        linearLayout.addView(this.hhiqobgkpm);
        this.hhiqobgkpm.setBackgroundColor(Color.parseColor("#86140e"));
        TimePicker timePicker4 = new TimePicker(this);
        this.nrejeglaqt = timePicker4;
        timePicker4.setLayoutParams(new LinearLayout.LayoutParams(1591, 21));
        this.nrejeglaqt.setPadding(127, 70, 32, 66);
        linearLayout.addView(this.nrejeglaqt);
        this.nrejeglaqt.setBackgroundColor(Color.parseColor("#bf7861"));
        CheckBox checkBox3 = new CheckBox(this);
        this.thnwhdqidw = checkBox3;
        checkBox3.setLayoutParams(new LinearLayout.LayoutParams(1671, 1877));
        this.thnwhdqidw.setPadding(125, 90, 61, 78);
        linearLayout.addView(this.thnwhdqidw);
        this.thnwhdqidw.setBackgroundColor(Color.parseColor("#f23ee0"));
        Spinner spinner7 = new Spinner(this);
        this.cdoqowgdkf = spinner7;
        spinner7.setLayoutParams(new LinearLayout.LayoutParams(1916, 1397));
        this.cdoqowgdkf.setPadding(41, 164, 33, 52);
        linearLayout.addView(this.cdoqowgdkf);
        this.cdoqowgdkf.setBackgroundColor(Color.parseColor("#21f56e"));
        EditText editText4 = new EditText(this);
        this.hlwyrfbetb = editText4;
        editText4.setLayoutParams(new LinearLayout.LayoutParams(874, 1874));
        this.hlwyrfbetb.setPadding(41, 93, 83, 77);
        linearLayout.addView(this.hlwyrfbetb);
        this.hlwyrfbetb.setBackgroundColor(Color.parseColor("#9857bc"));
        ToggleButton toggleButton3 = new ToggleButton(this);
        this.vgscwmbjfh = toggleButton3;
        toggleButton3.setLayoutParams(new LinearLayout.LayoutParams(327, 1159));
        this.vgscwmbjfh.setPadding(20, 22, 2, 28);
        linearLayout.addView(this.vgscwmbjfh);
        this.vgscwmbjfh.setBackgroundColor(Color.parseColor("#fc95a7"));
        TimePicker timePicker5 = new TimePicker(this);
        this.ggfqyklrfw = timePicker5;
        timePicker5.setLayoutParams(new LinearLayout.LayoutParams(1834, 1887));
        this.ggfqyklrfw.setPadding(69, 198, 119, 49);
        linearLayout.addView(this.ggfqyklrfw);
        this.ggfqyklrfw.setBackgroundColor(Color.parseColor("#c0fb66"));
        ScrollView scrollView4 = new ScrollView(this);
        this.iogphfbvan = scrollView4;
        scrollView4.setLayoutParams(new LinearLayout.LayoutParams(1276, 1053));
        this.iogphfbvan.setPadding(49, 182, BDLocation.TypeServerError, 164);
        linearLayout.addView(this.iogphfbvan);
        this.iogphfbvan.setBackgroundColor(Color.parseColor("#83530c"));
        LinearLayout linearLayout3 = new LinearLayout(this);
        this.lxisrklgld = linearLayout3;
        linearLayout3.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.CycleType.TYPE_VISIBILITY, 672));
        this.lxisrklgld.setPadding(89, 13, 92, 94);
        linearLayout.addView(this.lxisrklgld);
        this.lxisrklgld.setBackgroundColor(Color.parseColor("#deb129"));
        DatePicker datePicker4 = new DatePicker(this);
        this.aicphrbgmi = datePicker4;
        datePicker4.setLayoutParams(new LinearLayout.LayoutParams(476, 1434));
        this.aicphrbgmi.setPadding(182, 70, 31, 170);
        linearLayout.addView(this.aicphrbgmi);
        this.aicphrbgmi.setBackgroundColor(Color.parseColor("#485a44"));
        ProgressBar progressBar2 = new ProgressBar(this);
        this.eveyqluilg = progressBar2;
        progressBar2.setLayoutParams(new LinearLayout.LayoutParams(741, 1015));
        this.eveyqluilg.setPadding(128, 166, 5, 106);
        linearLayout.addView(this.eveyqluilg);
        this.eveyqluilg.setBackgroundColor(Color.parseColor("#248b42"));
        Button button4 = new Button(this);
        this.jjgbaioere = button4;
        button4.setLayoutParams(new LinearLayout.LayoutParams(1375, 1010));
        this.jjgbaioere.setPadding(97, 98, 155, 142);
        linearLayout.addView(this.jjgbaioere);
        this.jjgbaioere.setBackgroundColor(Color.parseColor("#7aa9a7"));
        RatingBar ratingBar3 = new RatingBar(this);
        this.szzdngwisb = ratingBar3;
        ratingBar3.setLayoutParams(new LinearLayout.LayoutParams(226, 1930));
        this.szzdngwisb.setPadding(116, 29, 87, 150);
        linearLayout.addView(this.szzdngwisb);
        this.szzdngwisb.setBackgroundColor(Color.parseColor("#728752"));
        DatePicker datePicker5 = new DatePicker(this);
        this.labsofmyxd = datePicker5;
        datePicker5.setLayoutParams(new LinearLayout.LayoutParams(825, 779));
        this.labsofmyxd.setPadding(53, 40, 180, 73);
        linearLayout.addView(this.labsofmyxd);
        this.labsofmyxd.setBackgroundColor(Color.parseColor("#6c0bf3"));
        RelativeLayout relativeLayout7 = new RelativeLayout(this);
        this.lmtnzscxrn = relativeLayout7;
        relativeLayout7.setLayoutParams(new LinearLayout.LayoutParams(322, 1298));
        this.lmtnzscxrn.setPadding(PictureConfig.CHOOSE_REQUEST, 194, 1, 118);
        linearLayout.addView(this.lmtnzscxrn);
        this.lmtnzscxrn.setBackgroundColor(Color.parseColor("#bc26a1"));
        CheckBox checkBox4 = new CheckBox(this);
        this.bojdegylfv = checkBox4;
        checkBox4.setLayoutParams(new LinearLayout.LayoutParams(1656, 1488));
        this.bojdegylfv.setPadding(122, 0, 23, 63);
        linearLayout.addView(this.bojdegylfv);
        this.bojdegylfv.setBackgroundColor(Color.parseColor("#c48157"));
        SeekBar seekBar2 = new SeekBar(this);
        this.ojjapqjznd = seekBar2;
        seekBar2.setLayoutParams(new LinearLayout.LayoutParams(726, 1990));
        this.ojjapqjznd.setPadding(47, 55, 14, 21);
        linearLayout.addView(this.ojjapqjznd);
        this.ojjapqjznd.setBackgroundColor(Color.parseColor("#84323e"));
        Spinner spinner8 = new Spinner(this);
        this.cypdtiazak = spinner8;
        spinner8.setLayoutParams(new LinearLayout.LayoutParams(627, 409));
        this.cypdtiazak.setPadding(79, 109, 3, 86);
        linearLayout.addView(this.cypdtiazak);
        this.cypdtiazak.setBackgroundColor(Color.parseColor("#446cc0"));
        FrameLayout frameLayout2 = new FrameLayout(this);
        this.jnfyrrrhcf = frameLayout2;
        frameLayout2.setLayoutParams(new LinearLayout.LayoutParams(1516, 1589));
        this.jnfyrrrhcf.setPadding(41, 141, 89, 19);
        linearLayout.addView(this.jnfyrrrhcf);
        this.jnfyrrrhcf.setBackgroundColor(Color.parseColor("#bb78a3"));
        Switch r25 = new Switch(this);
        this.fiqvdpbizs = r25;
        r25.setLayoutParams(new LinearLayout.LayoutParams(843, 565));
        this.fiqvdpbizs.setPadding(131, 18, 24, 134);
        linearLayout.addView(this.fiqvdpbizs);
        this.fiqvdpbizs.setBackgroundColor(Color.parseColor("#a0a395"));
        ImageView imageView5 = new ImageView(this);
        this.rbcgphemkv = imageView5;
        imageView5.setLayoutParams(new LinearLayout.LayoutParams(138, 234));
        this.rbcgphemkv.setPadding(140, 148, 150, 136);
        linearLayout.addView(this.rbcgphemkv);
        this.rbcgphemkv.setBackgroundColor(Color.parseColor("#799684"));
        TableLayout tableLayout4 = new TableLayout(this);
        this.qszqptaeau = tableLayout4;
        tableLayout4.setLayoutParams(new LinearLayout.LayoutParams(1660, 1713));
        this.qszqptaeau.setPadding(102, 78, 97, 151);
        linearLayout.addView(this.qszqptaeau);
        this.qszqptaeau.setBackgroundColor(Color.parseColor("#1cd042"));
        EditText editText5 = new EditText(this);
        this.luneswoejf = editText5;
        editText5.setLayoutParams(new LinearLayout.LayoutParams(1745, 1766));
        this.luneswoejf.setPadding(70, 57, 78, 94);
        linearLayout.addView(this.luneswoejf);
        this.luneswoejf.setBackgroundColor(Color.parseColor("#99f093"));
    }
}
