package com.smartapp.b.pmfyhglpoj;

import android.app.Activity;
import android.graphics.Color;
import android.os.Bundle;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.CheckBox;
import android.widget.DatePicker;
import android.widget.EditText;
import android.widget.FrameLayout;
import android.widget.GridView;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ListView;
import android.widget.ProgressBar;
import android.widget.RadioButton;
import android.widget.RatingBar;
import android.widget.RelativeLayout;
import android.widget.ScrollView;
import android.widget.SeekBar;
import android.widget.Spinner;
import android.widget.Switch;
import android.widget.TableLayout;
import android.widget.TextView;
import android.widget.TimePicker;
import android.widget.ToggleButton;
import android.widget.ViewFlipper;
import androidx.constraintlayout.core.motion.utils.TypedValues;
import com.baidu.location.BDLocation;
import com.luck.picture.lib.config.PictureConfig;
import com.qcwireless.qcwatch.ui.base.imagepicker.cropper.CropImage;
import com.realsil.sdk.audioconnect.localplayback.LocalPlaybackConstants;
import com.realsil.sdk.bbpro.equalizer.AudioEq;
import com.realsil.sdk.core.bluetooth.connection.le.GattClient;
import com.realsil.sdk.core.bluetooth.impl.BluetoothClassImpl;
import okhttp3.internal.ws.WebSocketProtocol;

/* loaded from: classes4.dex */
public class BikbbandnirActivity extends Activity {
    RatingBar aatnpgckzf;
    ToggleButton ahojjuidzc;
    GridView anqncrhxif;
    ListView aojlttasgh;
    SeekBar aokxgqmdis;
    EditText apcyetygbo;
    ScrollView apwpudevyr;
    FrameLayout atdozqmwal;
    ListView aybmxsycnt;
    ToggleButton ayjsettwan;
    ViewFlipper beoonlmcwe;
    CheckBox bimzxjkipy;
    TableLayout bjbmotdubz;
    DatePicker bnackliptp;
    SeekBar bqqgkxdxdb;
    DatePicker bsubidelpx;
    Switch bunxlrermv;
    CheckBox byvcnxlrez;
    SeekBar cgkuubglyh;
    SeekBar cmcbptyieq;
    FrameLayout cnjbkkpdny;
    TimePicker cpebpkitjh;
    TableLayout dglhvclkde;
    RelativeLayout dpbpoaxgrv;
    RelativeLayout dpfhavmbuw;
    EditText dtgktbxdrx;
    ScrollView dwughffigy;
    Button dyskztslja;
    EditText efwtmeexud;
    Spinner egtpeucxhr;
    FrameLayout emnnnlygvc;
    RatingBar enowxqfmgz;
    FrameLayout excpzdsuxt;
    Switch eyvbgjeezo;
    GridView fdcucmjobo;
    RelativeLayout fhbupcjlwi;
    TimePicker fiuivlsjwg;
    ToggleButton fqgyricogu;
    Spinner ftmmyjwzlf;
    TableLayout ftqvkvfyqb;
    CheckBox gbpwsfjdyu;
    RatingBar gcsrwyvyyu;
    CheckBox gkplbclhqz;
    TimePicker gnrbsncfnz;
    FrameLayout grslaucvnu;
    RadioButton gsbkadvdbs;
    TableLayout gwzdthfiaq;
    RelativeLayout gxunrqditb;
    ScrollView hbtqclmeij;
    TableLayout hejnvvpqat;
    EditText hfepulevbd;
    ProgressBar hfnrvtmdzb;
    TextView hfyybnqlop;
    ProgressBar hkhbuibvcu;
    SeekBar hoyhxdmvln;
    Button httelazwzk;
    RelativeLayout hxogmyrahp;
    TimePicker iadpbnjdjv;
    Switch icpqxlvnvc;
    RelativeLayout ifwgknfcrx;
    ToggleButton igpjashyqg;
    TimePicker igrfquubdt;
    TableLayout inzlmbfzsi;
    FrameLayout ipxomjcrvm;
    ImageView ismjxakkfz;
    ScrollView izxqrawikb;
    SeekBar jbzrcsvkdr;
    TableLayout jcddkozguv;
    DatePicker jcfzrpntuj;
    Spinner jsdgvstaxq;
    ToggleButton jtkqwbqsoj;
    RelativeLayout kdrvcthwqd;
    FrameLayout kgeunbirzb;
    RelativeLayout kgfwqwdxeo;
    ViewFlipper kiuhxlejbn;
    SeekBar kvztzxsmwd;
    ToggleButton liooyduwvx;
    ToggleButton lmkecfzsty;
    ProgressBar lmnnnquhui;
    SeekBar lmsxgxomsj;
    EditText lrhgyhkiql;
    CheckBox lygsitnoyn;
    DatePicker mkrqssizbo;
    ViewFlipper mmulmmlola;
    Button mtqnhnmbhx;
    Switch mtsawmiyyr;
    TimePicker muohqoqmav;
    Switch mwfbrolryh;
    ScrollView nahetbxjxr;
    CheckBox ndigcieptd;
    FrameLayout nlmcylqhct;
    TextView nuqvrpvvzd;
    Button oavzgittbf;
    RelativeLayout ofmvmtoyhi;
    ListView oibqlswahg;
    RadioButton oqlnngfbra;
    LinearLayout orqrdetchm;
    LinearLayout pacbrxrrqv;
    SeekBar pblhnrcmjn;
    LinearLayout peofyyfqud;
    ProgressBar pijhbcyvue;
    ToggleButton plqqnjokuf;
    GridView pqccxgwrgk;
    DatePicker prglcqjrja;
    FrameLayout pscvvciygg;
    ToggleButton pxinbdisam;
    GridView pynbrlhhyq;
    RelativeLayout pzebzqpczt;
    ListView qwgrkrjigc;
    ToggleButton qwklwmqykj;
    RatingBar qxxqexcyzg;
    ViewFlipper qzwoiwzhsp;
    FrameLayout rassjeiujx;
    Button rbxhjsjiwv;
    ListView rjieowurdq;
    ScrollView rmqybmljga;
    RadioButton rrkcjnwfhd;
    LinearLayout rsujrssbva;
    ViewFlipper rtanqponte;
    Spinner ruzmmuhrkj;
    TimePicker rvyuovpfwb;
    FrameLayout rzdufavduu;
    ProgressBar skjbcybmnt;
    ScrollView smqjhpjlvn;
    Switch sovgojceri;
    LinearLayout stgtnesjno;
    TimePicker stvyqcqhpp;
    TableLayout surscdkfel;
    RelativeLayout tgweikyqxu;
    RadioButton trjvfzslio;
    RadioButton tsbsamqicz;
    ViewFlipper ucjsmnwlmo;
    TableLayout ugttclfbka;
    DatePicker umrtbhixex;
    ViewFlipper unryljfbpg;
    TextView upadtrrlkg;
    RelativeLayout uqcwxifusu;
    FrameLayout uutkpusnyw;
    DatePicker uymwjqanup;
    EditText vgffbdvefn;
    Spinner vgfzhoxwpq;
    RadioButton vgqibpgref;
    RadioButton vphoxgykhf;
    Switch vpscmtojzj;
    LinearLayout vwguvfptdj;
    DatePicker whflweljnd;
    RelativeLayout wsymmwjspt;
    GridView xbgamubdmo;
    CheckBox xlxudnuuyg;
    ToggleButton xmdehzzxcw;
    LinearLayout xutvcvgpnc;
    Button xxeiitkrfj;
    RelativeLayout ymrjdfuwfi;
    TableLayout yrkxaqpsmt;
    GridView yrqorefutt;
    SeekBar yxvvngpnbb;
    FrameLayout zcwskrjckp;
    RadioButton zerpfysmax;
    ToggleButton zfwxtbsonh;
    RatingBar zihwwrcssk;
    RatingBar zltpzuktmz;
    SeekBar zochsqqeei;
    RelativeLayout zrladvzdzh;
    GridView ztwywrjjmv;

    @Override // android.app.Activity
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        LinearLayout linearLayout = new LinearLayout(this);
        setContentView(linearLayout);
        linearLayout.setLayoutParams(new ViewGroup.LayoutParams(-1, -1));
        linearLayout.setOrientation(1);
        linearLayout.setBackgroundColor(Color.parseColor("#9f3f4f"));
        CheckBox checkBox = new CheckBox(this);
        this.byvcnxlrez = checkBox;
        checkBox.setLayoutParams(new LinearLayout.LayoutParams(1684, 960));
        this.byvcnxlrez.setPadding(31, 177, 73, 192);
        linearLayout.addView(this.byvcnxlrez);
        this.byvcnxlrez.setBackgroundColor(Color.parseColor("#aacb9d"));
        Spinner spinner = new Spinner(this);
        this.egtpeucxhr = spinner;
        spinner.setLayoutParams(new LinearLayout.LayoutParams(1851, BDLocation.TypeCoarseLocation));
        this.egtpeucxhr.setPadding(96, 75, 28, 184);
        linearLayout.addView(this.egtpeucxhr);
        this.egtpeucxhr.setBackgroundColor(Color.parseColor("#c04b72"));
        ViewFlipper viewFlipper = new ViewFlipper(this);
        this.rtanqponte = viewFlipper;
        viewFlipper.setLayoutParams(new LinearLayout.LayoutParams(1777, 124));
        this.rtanqponte.setPadding(140, 171, 3, 0);
        linearLayout.addView(this.rtanqponte);
        this.rtanqponte.setBackgroundColor(Color.parseColor("#e03aeb"));
        TextView textView = new TextView(this);
        this.hfyybnqlop = textView;
        textView.setLayoutParams(new LinearLayout.LayoutParams(71, 746));
        this.hfyybnqlop.setPadding(155, 74, 32, 29);
        linearLayout.addView(this.hfyybnqlop);
        this.hfyybnqlop.setBackgroundColor(Color.parseColor("#75091f"));
        TableLayout tableLayout = new TableLayout(this);
        this.ugttclfbka = tableLayout;
        tableLayout.setLayoutParams(new LinearLayout.LayoutParams(110, 722));
        this.ugttclfbka.setPadding(74, 84, 23, 2);
        linearLayout.addView(this.ugttclfbka);
        this.ugttclfbka.setBackgroundColor(Color.parseColor("#77ee6b"));
        Switch r2 = new Switch(this);
        this.sovgojceri = r2;
        r2.setLayoutParams(new LinearLayout.LayoutParams(1038, 695));
        this.sovgojceri.setPadding(65, 59, 21, 54);
        linearLayout.addView(this.sovgojceri);
        this.sovgojceri.setBackgroundColor(Color.parseColor("#c35b4f"));
        ListView listView = new ListView(this);
        this.oibqlswahg = listView;
        listView.setLayoutParams(new LinearLayout.LayoutParams(54, 937));
        this.oibqlswahg.setPadding(89, 106, 197, 7);
        linearLayout.addView(this.oibqlswahg);
        this.oibqlswahg.setBackgroundColor(Color.parseColor("#b5271a"));
        ViewFlipper viewFlipper2 = new ViewFlipper(this);
        this.mmulmmlola = viewFlipper2;
        viewFlipper2.setLayoutParams(new LinearLayout.LayoutParams(381, 1181));
        this.mmulmmlola.setPadding(121, 91, 43, 140);
        linearLayout.addView(this.mmulmmlola);
        this.mmulmmlola.setBackgroundColor(Color.parseColor("#7350a9"));
        RatingBar ratingBar = new RatingBar(this);
        this.enowxqfmgz = ratingBar;
        ratingBar.setLayoutParams(new LinearLayout.LayoutParams(1100, 1541));
        this.enowxqfmgz.setPadding(115, 115, BDLocation.TypeServerError, 96);
        linearLayout.addView(this.enowxqfmgz);
        this.enowxqfmgz.setBackground(new Aoeqdsatuzh());
        RadioButton radioButton = new RadioButton(this);
        this.zerpfysmax = radioButton;
        radioButton.setLayoutParams(new LinearLayout.LayoutParams(1927, 1154));
        this.zerpfysmax.setPadding(143, 132, 10, 187);
        linearLayout.addView(this.zerpfysmax);
        this.zerpfysmax.setBackgroundColor(Color.parseColor("#508b6c"));
        RelativeLayout relativeLayout = new RelativeLayout(this);
        this.gxunrqditb = relativeLayout;
        relativeLayout.setLayoutParams(new LinearLayout.LayoutParams(74, 412));
        this.gxunrqditb.setPadding(24, 109, 32, 101);
        linearLayout.addView(this.gxunrqditb);
        this.gxunrqditb.setBackgroundColor(Color.parseColor("#20b174"));
        TimePicker timePicker = new TimePicker(this);
        this.fiuivlsjwg = timePicker;
        timePicker.setLayoutParams(new LinearLayout.LayoutParams(1896, 336));
        this.fiuivlsjwg.setPadding(123, 31, 184, 174);
        linearLayout.addView(this.fiuivlsjwg);
        this.fiuivlsjwg.setBackgroundColor(Color.parseColor("#2c4607"));
        GridView gridView = new GridView(this);
        this.ztwywrjjmv = gridView;
        gridView.setLayoutParams(new LinearLayout.LayoutParams(1911, 977));
        this.ztwywrjjmv.setPadding(145, 168, 118, 33);
        linearLayout.addView(this.ztwywrjjmv);
        this.ztwywrjjmv.setBackgroundColor(Color.parseColor("#9d3750"));
        ScrollView scrollView = new ScrollView(this);
        this.apwpudevyr = scrollView;
        scrollView.setLayoutParams(new LinearLayout.LayoutParams(524, 1677));
        this.apwpudevyr.setPadding(181, 140, 192, 128);
        linearLayout.addView(this.apwpudevyr);
        this.apwpudevyr.setBackgroundColor(Color.parseColor("#709f6e"));
        ToggleButton toggleButton = new ToggleButton(this);
        this.lmkecfzsty = toggleButton;
        toggleButton.setLayoutParams(new LinearLayout.LayoutParams(1752, 498));
        this.lmkecfzsty.setPadding(85, 172, 163, 12);
        linearLayout.addView(this.lmkecfzsty);
        this.lmkecfzsty.setBackgroundColor(Color.parseColor("#ee7a15"));
        Button button = new Button(this);
        this.rbxhjsjiwv = button;
        button.setLayoutParams(new LinearLayout.LayoutParams(168, 194));
        this.rbxhjsjiwv.setPadding(141, 4, 47, 28);
        linearLayout.addView(this.rbxhjsjiwv);
        this.rbxhjsjiwv.setBackgroundColor(Color.parseColor("#47403b"));
        DatePicker datePicker = new DatePicker(this);
        this.prglcqjrja = datePicker;
        datePicker.setLayoutParams(new LinearLayout.LayoutParams(337, 1133));
        this.prglcqjrja.setPadding(184, 3, 17, 131);
        linearLayout.addView(this.prglcqjrja);
        this.prglcqjrja.setBackgroundColor(Color.parseColor("#dfece9"));
        EditText editText = new EditText(this);
        this.efwtmeexud = editText;
        editText.setLayoutParams(new LinearLayout.LayoutParams(173, 294));
        this.efwtmeexud.setPadding(180, 45, 157, 100);
        linearLayout.addView(this.efwtmeexud);
        this.efwtmeexud.setBackgroundColor(Color.parseColor("#e94b8c"));
        TimePicker timePicker2 = new TimePicker(this);
        this.cpebpkitjh = timePicker2;
        timePicker2.setLayoutParams(new LinearLayout.LayoutParams(30, 647));
        this.cpebpkitjh.setPadding(17, 45, 53, 50);
        linearLayout.addView(this.cpebpkitjh);
        this.cpebpkitjh.setBackgroundColor(Color.parseColor("#1fd7f1"));
        ScrollView scrollView2 = new ScrollView(this);
        this.rmqybmljga = scrollView2;
        scrollView2.setLayoutParams(new LinearLayout.LayoutParams(629, 1110));
        this.rmqybmljga.setPadding(77, 190, 33, 105);
        linearLayout.addView(this.rmqybmljga);
        this.rmqybmljga.setBackgroundColor(Color.parseColor("#229f74"));
        RelativeLayout relativeLayout2 = new RelativeLayout(this);
        this.uqcwxifusu = relativeLayout2;
        relativeLayout2.setLayoutParams(new LinearLayout.LayoutParams(1062, 433));
        this.uqcwxifusu.setPadding(168, 63, 92, 25);
        linearLayout.addView(this.uqcwxifusu);
        this.uqcwxifusu.setBackgroundColor(Color.parseColor("#3a1a26"));
        ToggleButton toggleButton2 = new ToggleButton(this);
        this.igpjashyqg = toggleButton2;
        toggleButton2.setLayoutParams(new LinearLayout.LayoutParams(451, 1694));
        this.igpjashyqg.setPadding(95, 38, 144, 177);
        linearLayout.addView(this.igpjashyqg);
        this.igpjashyqg.setBackgroundColor(Color.parseColor("#7acdc0"));
        CheckBox checkBox2 = new CheckBox(this);
        this.ndigcieptd = checkBox2;
        checkBox2.setLayoutParams(new LinearLayout.LayoutParams(CropImage.CROP_IMAGE_ACTIVITY_REQUEST_CODE, 1956));
        this.ndigcieptd.setPadding(111, 53, 143, 104);
        linearLayout.addView(this.ndigcieptd);
        this.ndigcieptd.setBackgroundColor(Color.parseColor("#b6fb78"));
        TableLayout tableLayout2 = new TableLayout(this);
        this.hejnvvpqat = tableLayout2;
        tableLayout2.setLayoutParams(new LinearLayout.LayoutParams(1174, 158));
        this.hejnvvpqat.setPadding(40, 66, 62, 78);
        linearLayout.addView(this.hejnvvpqat);
        this.hejnvvpqat.setBackgroundColor(Color.parseColor("#7b6db5"));
        CheckBox checkBox3 = new CheckBox(this);
        this.xlxudnuuyg = checkBox3;
        checkBox3.setLayoutParams(new LinearLayout.LayoutParams(1815, 1383));
        this.xlxudnuuyg.setPadding(171, 18, 158, 75);
        linearLayout.addView(this.xlxudnuuyg);
        this.xlxudnuuyg.setBackgroundColor(Color.parseColor("#2a5c92"));
        Button button2 = new Button(this);
        this.mtqnhnmbhx = button2;
        button2.setLayoutParams(new LinearLayout.LayoutParams(230, 679));
        this.mtqnhnmbhx.setPadding(82, 157, 57, 191);
        linearLayout.addView(this.mtqnhnmbhx);
        this.mtqnhnmbhx.setBackgroundColor(Color.parseColor("#ad9342"));
        Switch r22 = new Switch(this);
        this.mwfbrolryh = r22;
        r22.setLayoutParams(new LinearLayout.LayoutParams(1375, 1059));
        this.mwfbrolryh.setPadding(147, 100, 103, WebSocketProtocol.PAYLOAD_SHORT);
        linearLayout.addView(this.mwfbrolryh);
        this.mwfbrolryh.setBackgroundColor(Color.parseColor("#8585a4"));
        FrameLayout frameLayout = new FrameLayout(this);
        this.ipxomjcrvm = frameLayout;
        frameLayout.setLayoutParams(new LinearLayout.LayoutParams(1876, 908));
        this.ipxomjcrvm.setPadding(40, 37, 67, 79);
        linearLayout.addView(this.ipxomjcrvm);
        this.ipxomjcrvm.setBackgroundColor(Color.parseColor("#c46a2a"));
        ToggleButton toggleButton3 = new ToggleButton(this);
        this.zfwxtbsonh = toggleButton3;
        toggleButton3.setLayoutParams(new LinearLayout.LayoutParams(579, 1575));
        this.zfwxtbsonh.setPadding(118, 129, 182, 51);
        linearLayout.addView(this.zfwxtbsonh);
        this.zfwxtbsonh.setBackgroundColor(Color.parseColor("#b071d1"));
        FrameLayout frameLayout2 = new FrameLayout(this);
        this.atdozqmwal = frameLayout2;
        frameLayout2.setLayoutParams(new LinearLayout.LayoutParams(1100, 1602));
        this.atdozqmwal.setPadding(128, 141, 47, 120);
        linearLayout.addView(this.atdozqmwal);
        this.atdozqmwal.setBackgroundColor(Color.parseColor("#315cde"));
        ProgressBar progressBar = new ProgressBar(this);
        this.hfnrvtmdzb = progressBar;
        progressBar.setLayoutParams(new LinearLayout.LayoutParams(474, WebSocketProtocol.PAYLOAD_SHORT));
        this.hfnrvtmdzb.setPadding(0, 125, 69, 136);
        linearLayout.addView(this.hfnrvtmdzb);
        this.hfnrvtmdzb.setBackgroundColor(Color.parseColor("#ee261a"));
        RadioButton radioButton2 = new RadioButton(this);
        this.oqlnngfbra = radioButton2;
        radioButton2.setLayoutParams(new LinearLayout.LayoutParams(1972, 1377));
        this.oqlnngfbra.setPadding(33, 142, 66, 28);
        linearLayout.addView(this.oqlnngfbra);
        this.oqlnngfbra.setBackgroundColor(Color.parseColor("#b5e27c"));
        LinearLayout linearLayout2 = new LinearLayout(this);
        this.orqrdetchm = linearLayout2;
        linearLayout2.setLayoutParams(new LinearLayout.LayoutParams(1001, 1179));
        this.orqrdetchm.setPadding(108, 90, 13, 50);
        linearLayout.addView(this.orqrdetchm);
        this.orqrdetchm.setBackgroundColor(Color.parseColor("#e93338"));
        DatePicker datePicker2 = new DatePicker(this);
        this.whflweljnd = datePicker2;
        datePicker2.setLayoutParams(new LinearLayout.LayoutParams(1389, 1905));
        this.whflweljnd.setPadding(125, 14, 19, WebSocketProtocol.PAYLOAD_SHORT);
        linearLayout.addView(this.whflweljnd);
        this.whflweljnd.setBackgroundColor(Color.parseColor("#e9375e"));
        ListView listView2 = new ListView(this);
        this.rjieowurdq = listView2;
        listView2.setLayoutParams(new LinearLayout.LayoutParams(27, 1279));
        this.rjieowurdq.setPadding(177, 174, 57, 14);
        linearLayout.addView(this.rjieowurdq);
        this.rjieowurdq.setBackgroundColor(Color.parseColor("#8f7c70"));
        RelativeLayout relativeLayout3 = new RelativeLayout(this);
        this.ymrjdfuwfi = relativeLayout3;
        relativeLayout3.setLayoutParams(new LinearLayout.LayoutParams(256, 894));
        this.ymrjdfuwfi.setPadding(87, 130, 2, WebSocketProtocol.PAYLOAD_SHORT);
        linearLayout.addView(this.ymrjdfuwfi);
        this.ymrjdfuwfi.setBackgroundColor(Color.parseColor("#68f2bf"));
        ToggleButton toggleButton4 = new ToggleButton(this);
        this.xmdehzzxcw = toggleButton4;
        toggleButton4.setLayoutParams(new LinearLayout.LayoutParams(777, 1773));
        this.xmdehzzxcw.setPadding(128, 194, 113, 186);
        linearLayout.addView(this.xmdehzzxcw);
        this.xmdehzzxcw.setBackgroundColor(Color.parseColor("#d16b19"));
        ScrollView scrollView3 = new ScrollView(this);
        this.hbtqclmeij = scrollView3;
        scrollView3.setLayoutParams(new LinearLayout.LayoutParams(BDLocation.TypeNetWorkLocation, 1669));
        this.hbtqclmeij.setPadding(173, 100, 138, 107);
        linearLayout.addView(this.hbtqclmeij);
        this.hbtqclmeij.setBackgroundColor(Color.parseColor("#1d407b"));
        GridView gridView2 = new GridView(this);
        this.yrqorefutt = gridView2;
        gridView2.setLayoutParams(new LinearLayout.LayoutParams(994, 1485));
        this.yrqorefutt.setPadding(3, 102, 75, 113);
        linearLayout.addView(this.yrqorefutt);
        this.yrqorefutt.setBackgroundColor(Color.parseColor("#f9f497"));
        Spinner spinner2 = new Spinner(this);
        this.vgfzhoxwpq = spinner2;
        spinner2.setLayoutParams(new LinearLayout.LayoutParams(95, 645));
        this.vgfzhoxwpq.setPadding(149, 30, 57, 23);
        linearLayout.addView(this.vgfzhoxwpq);
        this.vgfzhoxwpq.setBackgroundColor(Color.parseColor("#49fc81"));
        RelativeLayout relativeLayout4 = new RelativeLayout(this);
        this.dpfhavmbuw = relativeLayout4;
        relativeLayout4.setLayoutParams(new LinearLayout.LayoutParams(738, 743));
        this.dpfhavmbuw.setPadding(38, 46, BDLocation.TypeNetWorkLocation, 93);
        linearLayout.addView(this.dpfhavmbuw);
        this.dpfhavmbuw.setBackgroundColor(Color.parseColor("#987873"));
        ToggleButton toggleButton5 = new ToggleButton(this);
        this.jtkqwbqsoj = toggleButton5;
        toggleButton5.setLayoutParams(new LinearLayout.LayoutParams(464, TypedValues.MotionType.TYPE_DRAW_PATH));
        this.jtkqwbqsoj.setPadding(BDLocation.TypeServerDecryptError, 77, 142, 111);
        linearLayout.addView(this.jtkqwbqsoj);
        this.jtkqwbqsoj.setBackgroundColor(Color.parseColor("#edfc46"));
        LinearLayout linearLayout3 = new LinearLayout(this);
        this.xutvcvgpnc = linearLayout3;
        linearLayout3.setLayoutParams(new LinearLayout.LayoutParams(1070, 1012));
        this.xutvcvgpnc.setPadding(176, 88, 177, 99);
        linearLayout.addView(this.xutvcvgpnc);
        this.xutvcvgpnc.setBackgroundColor(Color.parseColor("#3b3710"));
        TimePicker timePicker3 = new TimePicker(this);
        this.gnrbsncfnz = timePicker3;
        timePicker3.setLayoutParams(new LinearLayout.LayoutParams(1767, 1368));
        this.gnrbsncfnz.setPadding(166, 104, 153, 129);
        linearLayout.addView(this.gnrbsncfnz);
        this.gnrbsncfnz.setBackgroundColor(Color.parseColor("#ff72ac"));
        TextView textView2 = new TextView(this);
        this.nuqvrpvvzd = textView2;
        textView2.setLayoutParams(new LinearLayout.LayoutParams(1652, 1201));
        this.nuqvrpvvzd.setPadding(BDLocation.TypeServerDecryptError, 156, 15, 59);
        linearLayout.addView(this.nuqvrpvvzd);
        this.nuqvrpvvzd.setBackgroundColor(Color.parseColor("#b0152b"));
        Button button3 = new Button(this);
        this.oavzgittbf = button3;
        button3.setLayoutParams(new LinearLayout.LayoutParams(464, 1650));
        this.oavzgittbf.setPadding(64, 199, 93, 4);
        linearLayout.addView(this.oavzgittbf);
        this.oavzgittbf.setBackgroundColor(Color.parseColor("#32142d"));
        DatePicker datePicker3 = new DatePicker(this);
        this.uymwjqanup = datePicker3;
        datePicker3.setLayoutParams(new LinearLayout.LayoutParams(1694, 620));
        this.uymwjqanup.setPadding(5, 28, 35, 110);
        linearLayout.addView(this.uymwjqanup);
        this.uymwjqanup.setBackgroundColor(Color.parseColor("#561b0b"));
        ProgressBar progressBar2 = new ProgressBar(this);
        this.hkhbuibvcu = progressBar2;
        progressBar2.setLayoutParams(new LinearLayout.LayoutParams(737, 1159));
        this.hkhbuibvcu.setPadding(71, 93, 55, 68);
        linearLayout.addView(this.hkhbuibvcu);
        this.hkhbuibvcu.setBackgroundColor(Color.parseColor("#7b96ac"));
        Spinner spinner3 = new Spinner(this);
        this.ruzmmuhrkj = spinner3;
        spinner3.setLayoutParams(new LinearLayout.LayoutParams(1823, TypedValues.CycleType.TYPE_CUSTOM_WAVE_SHAPE));
        this.ruzmmuhrkj.setPadding(166, 146, 88, 56);
        linearLayout.addView(this.ruzmmuhrkj);
        this.ruzmmuhrkj.setBackgroundColor(Color.parseColor("#6e3157"));
        LinearLayout linearLayout4 = new LinearLayout(this);
        this.stgtnesjno = linearLayout4;
        linearLayout4.setLayoutParams(new LinearLayout.LayoutParams(745, 1183));
        this.stgtnesjno.setPadding(123, 174, 22, 149);
        linearLayout.addView(this.stgtnesjno);
        this.stgtnesjno.setBackgroundColor(Color.parseColor("#e0f31c"));
        TableLayout tableLayout3 = new TableLayout(this);
        this.jcddkozguv = tableLayout3;
        tableLayout3.setLayoutParams(new LinearLayout.LayoutParams(1187, 1120));
        this.jcddkozguv.setPadding(12, 174, 73, 28);
        linearLayout.addView(this.jcddkozguv);
        this.jcddkozguv.setBackgroundColor(Color.parseColor("#546961"));
        ScrollView scrollView4 = new ScrollView(this);
        this.izxqrawikb = scrollView4;
        scrollView4.setLayoutParams(new LinearLayout.LayoutParams(99, 1397));
        this.izxqrawikb.setPadding(186, 146, 60, 68);
        linearLayout.addView(this.izxqrawikb);
        this.izxqrawikb.setBackgroundColor(Color.parseColor("#327fd5"));
        Switch r23 = new Switch(this);
        this.vpscmtojzj = r23;
        r23.setLayoutParams(new LinearLayout.LayoutParams(81, 910));
        this.vpscmtojzj.setPadding(175, 86, 172, 155);
        linearLayout.addView(this.vpscmtojzj);
        this.vpscmtojzj.setBackgroundColor(Color.parseColor("#97167a"));
        EditText editText2 = new EditText(this);
        this.apcyetygbo = editText2;
        editText2.setLayoutParams(new LinearLayout.LayoutParams(435, 806));
        this.apcyetygbo.setPadding(119, 185, 178, 114);
        linearLayout.addView(this.apcyetygbo);
        this.apcyetygbo.setBackgroundColor(Color.parseColor("#39852a"));
        TableLayout tableLayout4 = new TableLayout(this);
        this.yrkxaqpsmt = tableLayout4;
        tableLayout4.setLayoutParams(new LinearLayout.LayoutParams(1291, 392));
        this.yrkxaqpsmt.setPadding(193, 164, 98, 13);
        linearLayout.addView(this.yrkxaqpsmt);
        this.yrkxaqpsmt.setBackgroundColor(Color.parseColor("#833f29"));
        SeekBar seekBar = new SeekBar(this);
        this.aokxgqmdis = seekBar;
        seekBar.setLayoutParams(new LinearLayout.LayoutParams(1318, 1667));
        this.aokxgqmdis.setPadding(59, 190, 63, 80);
        linearLayout.addView(this.aokxgqmdis);
        this.aokxgqmdis.setBackgroundColor(Color.parseColor("#7babf0"));
        Spinner spinner4 = new Spinner(this);
        this.ftmmyjwzlf = spinner4;
        spinner4.setLayoutParams(new LinearLayout.LayoutParams(731, 1044));
        this.ftmmyjwzlf.setPadding(72, 44, 20, 86);
        linearLayout.addView(this.ftmmyjwzlf);
        this.ftmmyjwzlf.setBackgroundColor(Color.parseColor("#3e9251"));
        FrameLayout frameLayout3 = new FrameLayout(this);
        this.rassjeiujx = frameLayout3;
        frameLayout3.setLayoutParams(new LinearLayout.LayoutParams(405, 395));
        this.rassjeiujx.setPadding(102, WebSocketProtocol.PAYLOAD_SHORT, 72, 60);
        linearLayout.addView(this.rassjeiujx);
        this.rassjeiujx.setBackgroundColor(Color.parseColor("#f8dcb6"));
        SeekBar seekBar2 = new SeekBar(this);
        this.hoyhxdmvln = seekBar2;
        seekBar2.setLayoutParams(new LinearLayout.LayoutParams(742, 638));
        this.hoyhxdmvln.setPadding(96, 83, 6, 35);
        linearLayout.addView(this.hoyhxdmvln);
        this.hoyhxdmvln.setBackgroundColor(Color.parseColor("#039e78"));
        RelativeLayout relativeLayout5 = new RelativeLayout(this);
        this.kdrvcthwqd = relativeLayout5;
        relativeLayout5.setLayoutParams(new LinearLayout.LayoutParams(354, 1522));
        this.kdrvcthwqd.setPadding(157, 46, 39, 43);
        linearLayout.addView(this.kdrvcthwqd);
        this.kdrvcthwqd.setBackgroundColor(Color.parseColor("#13ddca"));
        SeekBar seekBar3 = new SeekBar(this);
        this.kvztzxsmwd = seekBar3;
        seekBar3.setLayoutParams(new LinearLayout.LayoutParams(860, 1121));
        this.kvztzxsmwd.setPadding(12, 106, 30, 116);
        linearLayout.addView(this.kvztzxsmwd);
        this.kvztzxsmwd.setBackgroundColor(Color.parseColor("#db63df"));
        ViewFlipper viewFlipper3 = new ViewFlipper(this);
        this.qzwoiwzhsp = viewFlipper3;
        viewFlipper3.setLayoutParams(new LinearLayout.LayoutParams(1207, 765));
        this.qzwoiwzhsp.setPadding(149, 128, 191, 38);
        linearLayout.addView(this.qzwoiwzhsp);
        this.qzwoiwzhsp.setBackgroundColor(Color.parseColor("#7fd724"));
        CheckBox checkBox4 = new CheckBox(this);
        this.lygsitnoyn = checkBox4;
        checkBox4.setLayoutParams(new LinearLayout.LayoutParams(4, 299));
        this.lygsitnoyn.setPadding(21, 97, 20, 88);
        linearLayout.addView(this.lygsitnoyn);
        this.lygsitnoyn.setBackgroundColor(Color.parseColor("#b505bf"));
        ToggleButton toggleButton6 = new ToggleButton(this);
        this.ahojjuidzc = toggleButton6;
        toggleButton6.setLayoutParams(new LinearLayout.LayoutParams(1948, 1796));
        this.ahojjuidzc.setPadding(181, 15, 133, 31);
        linearLayout.addView(this.ahojjuidzc);
        this.ahojjuidzc.setBackgroundColor(Color.parseColor("#f78a81"));
        RatingBar ratingBar2 = new RatingBar(this);
        this.aatnpgckzf = ratingBar2;
        ratingBar2.setLayoutParams(new LinearLayout.LayoutParams(1219, 974));
        this.aatnpgckzf.setPadding(143, 173, 98, 116);
        linearLayout.addView(this.aatnpgckzf);
        this.aatnpgckzf.setBackgroundColor(Color.parseColor("#91222f"));
        ListView listView3 = new ListView(this);
        this.qwgrkrjigc = listView3;
        listView3.setLayoutParams(new LinearLayout.LayoutParams(1792, 400));
        this.qwgrkrjigc.setPadding(174, 151, 39, 57);
        linearLayout.addView(this.qwgrkrjigc);
        this.qwgrkrjigc.setBackgroundColor(Color.parseColor("#881e15"));
        SeekBar seekBar4 = new SeekBar(this);
        this.cmcbptyieq = seekBar4;
        seekBar4.setLayoutParams(new LinearLayout.LayoutParams(36, 1226));
        this.cmcbptyieq.setPadding(98, 148, 52, 149);
        linearLayout.addView(this.cmcbptyieq);
        this.cmcbptyieq.setBackgroundColor(Color.parseColor("#f70ade"));
        TimePicker timePicker4 = new TimePicker(this);
        this.iadpbnjdjv = timePicker4;
        timePicker4.setLayoutParams(new LinearLayout.LayoutParams(782, 299));
        this.iadpbnjdjv.setPadding(117, 31, 39, 75);
        linearLayout.addView(this.iadpbnjdjv);
        this.iadpbnjdjv.setBackgroundColor(Color.parseColor("#eaa093"));
        FrameLayout frameLayout4 = new FrameLayout(this);
        this.pscvvciygg = frameLayout4;
        frameLayout4.setLayoutParams(new LinearLayout.LayoutParams(223, 117));
        this.pscvvciygg.setPadding(181, 116, 144, 82);
        linearLayout.addView(this.pscvvciygg);
        this.pscvvciygg.setBackgroundColor(Color.parseColor("#3f6f8e"));
        SeekBar seekBar5 = new SeekBar(this);
        this.jbzrcsvkdr = seekBar5;
        seekBar5.setLayoutParams(new LinearLayout.LayoutParams(GattClient.STATE_PENDDING_DISCOVERY_SERVICE, 947));
        this.jbzrcsvkdr.setPadding(158, 183, 0, 62);
        linearLayout.addView(this.jbzrcsvkdr);
        this.jbzrcsvkdr.setBackgroundColor(Color.parseColor("#abd090"));
        ListView listView4 = new ListView(this);
        this.aojlttasgh = listView4;
        listView4.setLayoutParams(new LinearLayout.LayoutParams(950, 1139));
        this.aojlttasgh.setPadding(19, 176, 142, 196);
        linearLayout.addView(this.aojlttasgh);
        this.aojlttasgh.setBackgroundColor(Color.parseColor("#1f43bf"));
        ScrollView scrollView5 = new ScrollView(this);
        this.nahetbxjxr = scrollView5;
        scrollView5.setLayoutParams(new LinearLayout.LayoutParams(526, 72));
        this.nahetbxjxr.setPadding(185, 83, 54, 91);
        linearLayout.addView(this.nahetbxjxr);
        this.nahetbxjxr.setBackgroundColor(Color.parseColor("#622235"));
        LinearLayout linearLayout5 = new LinearLayout(this);
        this.rsujrssbva = linearLayout5;
        linearLayout5.setLayoutParams(new LinearLayout.LayoutParams(545, 159));
        this.rsujrssbva.setPadding(88, 52, 95, 31);
        linearLayout.addView(this.rsujrssbva);
        this.rsujrssbva.setBackgroundColor(Color.parseColor("#eed123"));
        RadioButton radioButton3 = new RadioButton(this);
        this.tsbsamqicz = radioButton3;
        radioButton3.setLayoutParams(new LinearLayout.LayoutParams(1223, 585));
        this.tsbsamqicz.setPadding(119, 14, 40, 183);
        linearLayout.addView(this.tsbsamqicz);
        this.tsbsamqicz.setBackgroundColor(Color.parseColor("#2267ef"));
        RelativeLayout relativeLayout6 = new RelativeLayout(this);
        this.kgfwqwdxeo = relativeLayout6;
        relativeLayout6.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.PositionType.TYPE_PERCENT_HEIGHT, 145));
        this.kgfwqwdxeo.setPadding(123, 76, 119, 6);
        linearLayout.addView(this.kgfwqwdxeo);
        this.kgfwqwdxeo.setBackgroundColor(Color.parseColor("#186ad2"));
        TableLayout tableLayout5 = new TableLayout(this);
        this.inzlmbfzsi = tableLayout5;
        tableLayout5.setLayoutParams(new LinearLayout.LayoutParams(1108, 748));
        this.inzlmbfzsi.setPadding(45, 48, 16, 47);
        linearLayout.addView(this.inzlmbfzsi);
        this.inzlmbfzsi.setBackgroundColor(Color.parseColor("#90a8c0"));
        RelativeLayout relativeLayout7 = new RelativeLayout(this);
        this.wsymmwjspt = relativeLayout7;
        relativeLayout7.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.PositionType.TYPE_PERCENT_HEIGHT, 518));
        this.wsymmwjspt.setPadding(21, 41, 22, 83);
        linearLayout.addView(this.wsymmwjspt);
        this.wsymmwjspt.setBackgroundColor(Color.parseColor("#638934"));
        ToggleButton toggleButton7 = new ToggleButton(this);
        this.pxinbdisam = toggleButton7;
        toggleButton7.setLayoutParams(new LinearLayout.LayoutParams(1362, 260));
        this.pxinbdisam.setPadding(118, 138, 56, 13);
        linearLayout.addView(this.pxinbdisam);
        this.pxinbdisam.setBackgroundColor(Color.parseColor("#3479ea"));
        ToggleButton toggleButton8 = new ToggleButton(this);
        this.ayjsettwan = toggleButton8;
        toggleButton8.setLayoutParams(new LinearLayout.LayoutParams(1099, 92));
        this.ayjsettwan.setPadding(79, 165, 146, 93);
        linearLayout.addView(this.ayjsettwan);
        this.ayjsettwan.setBackgroundColor(Color.parseColor("#c10260"));
        ToggleButton toggleButton9 = new ToggleButton(this);
        this.liooyduwvx = toggleButton9;
        toggleButton9.setLayoutParams(new LinearLayout.LayoutParams(1752, 1737));
        this.liooyduwvx.setPadding(139, 94, 45, 170);
        linearLayout.addView(this.liooyduwvx);
        this.liooyduwvx.setBackgroundColor(Color.parseColor("#74ba7e"));
        RadioButton radioButton4 = new RadioButton(this);
        this.rrkcjnwfhd = radioButton4;
        radioButton4.setLayoutParams(new LinearLayout.LayoutParams(1572, 1347));
        this.rrkcjnwfhd.setPadding(103, 66, 85, 168);
        linearLayout.addView(this.rrkcjnwfhd);
        this.rrkcjnwfhd.setBackgroundColor(Color.parseColor("#6461ad"));
        FrameLayout frameLayout5 = new FrameLayout(this);
        this.cnjbkkpdny = frameLayout5;
        frameLayout5.setLayoutParams(new LinearLayout.LayoutParams(1907, 1012));
        this.cnjbkkpdny.setPadding(46, 88, 134, 82);
        linearLayout.addView(this.cnjbkkpdny);
        this.cnjbkkpdny.setBackgroundColor(Color.parseColor("#249117"));
        EditText editText3 = new EditText(this);
        this.lrhgyhkiql = editText3;
        editText3.setLayoutParams(new LinearLayout.LayoutParams(1615, 1837));
        this.lrhgyhkiql.setPadding(114, 136, 115, 114);
        linearLayout.addView(this.lrhgyhkiql);
        this.lrhgyhkiql.setBackgroundColor(Color.parseColor("#222ab1"));
        Button button4 = new Button(this);
        this.dyskztslja = button4;
        button4.setLayoutParams(new LinearLayout.LayoutParams(752, BDLocation.TypeCoarseLocation));
        this.dyskztslja.setPadding(104, 151, 84, 116);
        linearLayout.addView(this.dyskztslja);
        this.dyskztslja.setBackgroundColor(Color.parseColor("#8cefcd"));
        TableLayout tableLayout6 = new TableLayout(this);
        this.gwzdthfiaq = tableLayout6;
        tableLayout6.setLayoutParams(new LinearLayout.LayoutParams(1155, 1696));
        this.gwzdthfiaq.setPadding(145, 173, 27, 145);
        linearLayout.addView(this.gwzdthfiaq);
        this.gwzdthfiaq.setBackgroundColor(Color.parseColor("#9f39f7"));
        DatePicker datePicker4 = new DatePicker(this);
        this.bnackliptp = datePicker4;
        datePicker4.setLayoutParams(new LinearLayout.LayoutParams(481, 523));
        this.bnackliptp.setPadding(177, 109, 147, 135);
        linearLayout.addView(this.bnackliptp);
        this.bnackliptp.setBackgroundColor(Color.parseColor("#be4cd7"));
        Switch r24 = new Switch(this);
        this.mtsawmiyyr = r24;
        r24.setLayoutParams(new LinearLayout.LayoutParams(322, 1392));
        this.mtsawmiyyr.setPadding(118, 51, 124, 143);
        linearLayout.addView(this.mtsawmiyyr);
        this.mtsawmiyyr.setBackgroundColor(Color.parseColor("#fd65fd"));
        FrameLayout frameLayout6 = new FrameLayout(this);
        this.grslaucvnu = frameLayout6;
        frameLayout6.setLayoutParams(new LinearLayout.LayoutParams(421, 1044));
        this.grslaucvnu.setPadding(96, 99, 14, 87);
        linearLayout.addView(this.grslaucvnu);
        this.grslaucvnu.setBackgroundColor(Color.parseColor("#4627fe"));
        GridView gridView3 = new GridView(this);
        this.pqccxgwrgk = gridView3;
        gridView3.setLayoutParams(new LinearLayout.LayoutParams(1606, 774));
        this.pqccxgwrgk.setPadding(127, 14, 105, 150);
        linearLayout.addView(this.pqccxgwrgk);
        this.pqccxgwrgk.setBackgroundColor(Color.parseColor("#dd34ec"));
        EditText editText4 = new EditText(this);
        this.vgffbdvefn = editText4;
        editText4.setLayoutParams(new LinearLayout.LayoutParams(1619, 1611));
        this.vgffbdvefn.setPadding(181, 47, 189, 151);
        linearLayout.addView(this.vgffbdvefn);
        this.vgffbdvefn.setBackgroundColor(Color.parseColor("#b1803e"));
        LinearLayout linearLayout6 = new LinearLayout(this);
        this.vwguvfptdj = linearLayout6;
        linearLayout6.setLayoutParams(new LinearLayout.LayoutParams(484, 285));
        this.vwguvfptdj.setPadding(97, 35, 76, 4);
        linearLayout.addView(this.vwguvfptdj);
        this.vwguvfptdj.setBackgroundColor(Color.parseColor("#06e9ab"));
        Button button5 = new Button(this);
        this.httelazwzk = button5;
        button5.setLayoutParams(new LinearLayout.LayoutParams(1518, 1812));
        this.httelazwzk.setPadding(85, 135, 34, 108);
        linearLayout.addView(this.httelazwzk);
        this.httelazwzk.setBackgroundColor(Color.parseColor("#05daf4"));
        RelativeLayout relativeLayout8 = new RelativeLayout(this);
        this.tgweikyqxu = relativeLayout8;
        relativeLayout8.setLayoutParams(new LinearLayout.LayoutParams(1835, 271));
        this.tgweikyqxu.setPadding(28, 75, 21, 17);
        linearLayout.addView(this.tgweikyqxu);
        this.tgweikyqxu.setBackgroundColor(Color.parseColor("#3a93d8"));
        DatePicker datePicker5 = new DatePicker(this);
        this.umrtbhixex = datePicker5;
        datePicker5.setLayoutParams(new LinearLayout.LayoutParams(81, 757));
        this.umrtbhixex.setPadding(92, 20, 133, 65);
        linearLayout.addView(this.umrtbhixex);
        this.umrtbhixex.setBackgroundColor(Color.parseColor("#0761f7"));
        GridView gridView4 = new GridView(this);
        this.anqncrhxif = gridView4;
        gridView4.setLayoutParams(new LinearLayout.LayoutParams(564, 1677));
        this.anqncrhxif.setPadding(156, 142, 170, 101);
        linearLayout.addView(this.anqncrhxif);
        this.anqncrhxif.setBackgroundColor(Color.parseColor("#7c34d1"));
        RatingBar ratingBar3 = new RatingBar(this);
        this.zihwwrcssk = ratingBar3;
        ratingBar3.setLayoutParams(new LinearLayout.LayoutParams(1795, 1108));
        this.zihwwrcssk.setPadding(18, 80, 142, 54);
        linearLayout.addView(this.zihwwrcssk);
        this.zihwwrcssk.setBackgroundColor(Color.parseColor("#68a74a"));
        ViewFlipper viewFlipper4 = new ViewFlipper(this);
        this.kiuhxlejbn = viewFlipper4;
        viewFlipper4.setLayoutParams(new LinearLayout.LayoutParams(291, 485));
        this.kiuhxlejbn.setPadding(109, 177, 39, 36);
        linearLayout.addView(this.kiuhxlejbn);
        this.kiuhxlejbn.setBackgroundColor(Color.parseColor("#fa90cd"));
        GridView gridView5 = new GridView(this);
        this.xbgamubdmo = gridView5;
        gridView5.setLayoutParams(new LinearLayout.LayoutParams(1714, TypedValues.PositionType.TYPE_PERCENT_Y));
        this.xbgamubdmo.setPadding(90, BDLocation.TypeNetWorkLocation, 114, 176);
        linearLayout.addView(this.xbgamubdmo);
        this.xbgamubdmo.setBackgroundColor(Color.parseColor("#85c127"));
        RelativeLayout relativeLayout9 = new RelativeLayout(this);
        this.ifwgknfcrx = relativeLayout9;
        relativeLayout9.setLayoutParams(new LinearLayout.LayoutParams(1651, 186));
        this.ifwgknfcrx.setPadding(164, 26, 38, 34);
        linearLayout.addView(this.ifwgknfcrx);
        this.ifwgknfcrx.setBackgroundColor(Color.parseColor("#260521"));
        LinearLayout linearLayout7 = new LinearLayout(this);
        this.pacbrxrrqv = linearLayout7;
        linearLayout7.setLayoutParams(new LinearLayout.LayoutParams(890, 516));
        this.pacbrxrrqv.setPadding(69, 12, 99, 165);
        linearLayout.addView(this.pacbrxrrqv);
        this.pacbrxrrqv.setBackgroundColor(Color.parseColor("#ec5312"));
        DatePicker datePicker6 = new DatePicker(this);
        this.jcfzrpntuj = datePicker6;
        datePicker6.setLayoutParams(new LinearLayout.LayoutParams(236, 512));
        this.jcfzrpntuj.setPadding(164, 199, 142, 23);
        linearLayout.addView(this.jcfzrpntuj);
        this.jcfzrpntuj.setBackgroundColor(Color.parseColor("#69a242"));
        TableLayout tableLayout7 = new TableLayout(this);
        this.dglhvclkde = tableLayout7;
        tableLayout7.setLayoutParams(new LinearLayout.LayoutParams(1758, 254));
        this.dglhvclkde.setPadding(106, 187, 148, 94);
        linearLayout.addView(this.dglhvclkde);
        this.dglhvclkde.setBackgroundColor(Color.parseColor("#0f5189"));
        ProgressBar progressBar3 = new ProgressBar(this);
        this.pijhbcyvue = progressBar3;
        progressBar3.setLayoutParams(new LinearLayout.LayoutParams(79, 1374));
        this.pijhbcyvue.setPadding(197, 19, 111, 148);
        linearLayout.addView(this.pijhbcyvue);
        this.pijhbcyvue.setBackgroundColor(Color.parseColor("#ccc314"));
        ScrollView scrollView6 = new ScrollView(this);
        this.smqjhpjlvn = scrollView6;
        scrollView6.setLayoutParams(new LinearLayout.LayoutParams(268, 695));
        this.smqjhpjlvn.setPadding(BDLocation.TypeServerError, 192, 0, 36);
        linearLayout.addView(this.smqjhpjlvn);
        this.smqjhpjlvn.setBackgroundColor(Color.parseColor("#634ec7"));
        FrameLayout frameLayout7 = new FrameLayout(this);
        this.zcwskrjckp = frameLayout7;
        frameLayout7.setLayoutParams(new LinearLayout.LayoutParams(7, 123));
        this.zcwskrjckp.setPadding(52, 10, 90, 5);
        linearLayout.addView(this.zcwskrjckp);
        this.zcwskrjckp.setBackgroundColor(Color.parseColor("#a6ffce"));
        ToggleButton toggleButton10 = new ToggleButton(this);
        this.plqqnjokuf = toggleButton10;
        toggleButton10.setLayoutParams(new LinearLayout.LayoutParams(1724, BluetoothClassImpl.Device.PERIPHERAL_NON_KEYBOARD_NON_POINTING));
        this.plqqnjokuf.setPadding(47, 184, 25, 179);
        linearLayout.addView(this.plqqnjokuf);
        this.plqqnjokuf.setBackgroundColor(Color.parseColor("#969acd"));
        LinearLayout linearLayout8 = new LinearLayout(this);
        this.peofyyfqud = linearLayout8;
        linearLayout8.setLayoutParams(new LinearLayout.LayoutParams(281, 802));
        this.peofyyfqud.setPadding(65, 16, 29, 38);
        linearLayout.addView(this.peofyyfqud);
        this.peofyyfqud.setBackgroundColor(Color.parseColor("#ad2829"));
        RadioButton radioButton5 = new RadioButton(this);
        this.trjvfzslio = radioButton5;
        radioButton5.setLayoutParams(new LinearLayout.LayoutParams(1440, 1596));
        this.trjvfzslio.setPadding(53, 50, 117, 131);
        linearLayout.addView(this.trjvfzslio);
        this.trjvfzslio.setBackgroundColor(Color.parseColor("#6e83a1"));
        RatingBar ratingBar4 = new RatingBar(this);
        this.zltpzuktmz = ratingBar4;
        ratingBar4.setLayoutParams(new LinearLayout.LayoutParams(1139, 1646));
        this.zltpzuktmz.setPadding(19, 6, 115, 199);
        linearLayout.addView(this.zltpzuktmz);
        this.zltpzuktmz.setBackgroundColor(Color.parseColor("#c337c2"));
        FrameLayout frameLayout8 = new FrameLayout(this);
        this.rzdufavduu = frameLayout8;
        frameLayout8.setLayoutParams(new LinearLayout.LayoutParams(AudioEq.PARSE_EQ_DATA_LENGTH, 754));
        this.rzdufavduu.setPadding(38, 134, 169, 146);
        linearLayout.addView(this.rzdufavduu);
        this.rzdufavduu.setBackgroundColor(Color.parseColor("#ce3fdf"));
        Spinner spinner5 = new Spinner(this);
        this.jsdgvstaxq = spinner5;
        spinner5.setLayoutParams(new LinearLayout.LayoutParams(1311, 303));
        this.jsdgvstaxq.setPadding(156, 54, 159, 136);
        linearLayout.addView(this.jsdgvstaxq);
        this.jsdgvstaxq.setBackgroundColor(Color.parseColor("#cf471e"));
        ScrollView scrollView7 = new ScrollView(this);
        this.dwughffigy = scrollView7;
        scrollView7.setLayoutParams(new LinearLayout.LayoutParams(749, 583));
        this.dwughffigy.setPadding(114, 7, 73, 116);
        linearLayout.addView(this.dwughffigy);
        this.dwughffigy.setBackgroundColor(Color.parseColor("#6bb94d"));
        Switch r25 = new Switch(this);
        this.icpqxlvnvc = r25;
        r25.setLayoutParams(new LinearLayout.LayoutParams(1439, 596));
        this.icpqxlvnvc.setPadding(66, 147, 0, 174);
        linearLayout.addView(this.icpqxlvnvc);
        this.icpqxlvnvc.setBackgroundColor(Color.parseColor("#6fcdb6"));
        ViewFlipper viewFlipper5 = new ViewFlipper(this);
        this.unryljfbpg = viewFlipper5;
        viewFlipper5.setLayoutParams(new LinearLayout.LayoutParams(956, 1461));
        this.unryljfbpg.setPadding(98, 58, 60, 172);
        linearLayout.addView(this.unryljfbpg);
        this.unryljfbpg.setBackgroundColor(Color.parseColor("#c4427a"));
        RelativeLayout relativeLayout10 = new RelativeLayout(this);
        this.fhbupcjlwi = relativeLayout10;
        relativeLayout10.setLayoutParams(new LinearLayout.LayoutParams(945, 1568));
        this.fhbupcjlwi.setPadding(154, 106, 92, 125);
        linearLayout.addView(this.fhbupcjlwi);
        this.fhbupcjlwi.setBackgroundColor(Color.parseColor("#1280bf"));
        CheckBox checkBox5 = new CheckBox(this);
        this.gkplbclhqz = checkBox5;
        checkBox5.setLayoutParams(new LinearLayout.LayoutParams(843, 1944));
        this.gkplbclhqz.setPadding(74, 197, 4, 64);
        linearLayout.addView(this.gkplbclhqz);
        this.gkplbclhqz.setBackgroundColor(Color.parseColor("#75838d"));
        TableLayout tableLayout8 = new TableLayout(this);
        this.ftqvkvfyqb = tableLayout8;
        tableLayout8.setLayoutParams(new LinearLayout.LayoutParams(CropImage.CROP_IMAGE_ACTIVITY_REQUEST_CODE, 1190));
        this.ftqvkvfyqb.setPadding(53, 44, 73, 196);
        linearLayout.addView(this.ftqvkvfyqb);
        this.ftqvkvfyqb.setBackgroundColor(Color.parseColor("#5426e1"));
        ToggleButton toggleButton11 = new ToggleButton(this);
        this.fqgyricogu = toggleButton11;
        toggleButton11.setLayoutParams(new LinearLayout.LayoutParams(1422, 812));
        this.fqgyricogu.setPadding(WebSocketProtocol.PAYLOAD_SHORT, 105, 58, 154);
        linearLayout.addView(this.fqgyricogu);
        this.fqgyricogu.setBackgroundColor(Color.parseColor("#ce0c49"));
        SeekBar seekBar6 = new SeekBar(this);
        this.bqqgkxdxdb = seekBar6;
        seekBar6.setLayoutParams(new LinearLayout.LayoutParams(175, 1085));
        this.bqqgkxdxdb.setPadding(46, 106, 13, 37);
        linearLayout.addView(this.bqqgkxdxdb);
        this.bqqgkxdxdb.setBackgroundColor(Color.parseColor("#fff521"));
        RelativeLayout relativeLayout11 = new RelativeLayout(this);
        this.dpbpoaxgrv = relativeLayout11;
        relativeLayout11.setLayoutParams(new LinearLayout.LayoutParams(930, 1793));
        this.dpbpoaxgrv.setPadding(119, 89, 52, 146);
        linearLayout.addView(this.dpbpoaxgrv);
        this.dpbpoaxgrv.setBackgroundColor(Color.parseColor("#9dc18d"));
        SeekBar seekBar7 = new SeekBar(this);
        this.yxvvngpnbb = seekBar7;
        seekBar7.setLayoutParams(new LinearLayout.LayoutParams(1415, 381));
        this.yxvvngpnbb.setPadding(64, 32, 180, 35);
        linearLayout.addView(this.yxvvngpnbb);
        this.yxvvngpnbb.setBackgroundColor(Color.parseColor("#9dbe75"));
        RelativeLayout relativeLayout12 = new RelativeLayout(this);
        this.hxogmyrahp = relativeLayout12;
        relativeLayout12.setLayoutParams(new LinearLayout.LayoutParams(1888, 1159));
        this.hxogmyrahp.setPadding(62, 73, 1, 69);
        linearLayout.addView(this.hxogmyrahp);
        this.hxogmyrahp.setBackgroundColor(Color.parseColor("#7a1ffe"));
        SeekBar seekBar8 = new SeekBar(this);
        this.cgkuubglyh = seekBar8;
        seekBar8.setLayoutParams(new LinearLayout.LayoutParams(1576, 720));
        this.cgkuubglyh.setPadding(59, 27, 97, 178);
        linearLayout.addView(this.cgkuubglyh);
        this.cgkuubglyh.setBackgroundColor(Color.parseColor("#15cfa3"));
        RatingBar ratingBar5 = new RatingBar(this);
        this.gcsrwyvyyu = ratingBar5;
        ratingBar5.setLayoutParams(new LinearLayout.LayoutParams(1065, 851));
        this.gcsrwyvyyu.setPadding(62, BDLocation.TypeNetWorkLocation, 114, 106);
        linearLayout.addView(this.gcsrwyvyyu);
        this.gcsrwyvyyu.setBackgroundColor(Color.parseColor("#e89220"));
        GridView gridView6 = new GridView(this);
        this.pynbrlhhyq = gridView6;
        gridView6.setLayoutParams(new LinearLayout.LayoutParams(1585, 1186));
        this.pynbrlhhyq.setPadding(159, 36, 146, 139);
        linearLayout.addView(this.pynbrlhhyq);
        this.pynbrlhhyq.setBackgroundColor(Color.parseColor("#f22163"));
        Switch r26 = new Switch(this);
        this.eyvbgjeezo = r26;
        r26.setLayoutParams(new LinearLayout.LayoutParams(506, 1977));
        this.eyvbgjeezo.setPadding(69, 120, 178, 16);
        linearLayout.addView(this.eyvbgjeezo);
        this.eyvbgjeezo.setBackgroundColor(Color.parseColor("#300f83"));
        FrameLayout frameLayout9 = new FrameLayout(this);
        this.uutkpusnyw = frameLayout9;
        frameLayout9.setLayoutParams(new LinearLayout.LayoutParams(1947, 1107));
        this.uutkpusnyw.setPadding(110, 44, 39, 166);
        linearLayout.addView(this.uutkpusnyw);
        this.uutkpusnyw.setBackgroundColor(Color.parseColor("#56d60a"));
        RelativeLayout relativeLayout13 = new RelativeLayout(this);
        this.pzebzqpczt = relativeLayout13;
        relativeLayout13.setLayoutParams(new LinearLayout.LayoutParams(1095, 1041));
        this.pzebzqpczt.setPadding(107, 58, 134, 154);
        linearLayout.addView(this.pzebzqpczt);
        this.pzebzqpczt.setBackgroundColor(Color.parseColor("#56546d"));
        ListView listView5 = new ListView(this);
        this.aybmxsycnt = listView5;
        listView5.setLayoutParams(new LinearLayout.LayoutParams(617, 417));
        this.aybmxsycnt.setPadding(157, WebSocketProtocol.PAYLOAD_SHORT, 105, 127);
        linearLayout.addView(this.aybmxsycnt);
        this.aybmxsycnt.setBackgroundColor(Color.parseColor("#a6c44a"));
        RadioButton radioButton6 = new RadioButton(this);
        this.vphoxgykhf = radioButton6;
        radioButton6.setLayoutParams(new LinearLayout.LayoutParams(1282, 1971));
        this.vphoxgykhf.setPadding(127, 115, 156, 28);
        linearLayout.addView(this.vphoxgykhf);
        this.vphoxgykhf.setBackgroundColor(Color.parseColor("#816028"));
        Switch r27 = new Switch(this);
        this.bunxlrermv = r27;
        r27.setLayoutParams(new LinearLayout.LayoutParams(313, TypedValues.PositionType.TYPE_POSITION_TYPE));
        this.bunxlrermv.setPadding(26, 104, 62, 131);
        linearLayout.addView(this.bunxlrermv);
        this.bunxlrermv.setBackgroundColor(Color.parseColor("#878123"));
        EditText editText5 = new EditText(this);
        this.hfepulevbd = editText5;
        editText5.setLayoutParams(new LinearLayout.LayoutParams(629, 1978));
        this.hfepulevbd.setPadding(151, 178, 158, 132);
        linearLayout.addView(this.hfepulevbd);
        this.hfepulevbd.setBackgroundColor(Color.parseColor("#aecdc0"));
        SeekBar seekBar9 = new SeekBar(this);
        this.zochsqqeei = seekBar9;
        seekBar9.setLayoutParams(new LinearLayout.LayoutParams(1696, 1760));
        this.zochsqqeei.setPadding(37, 27, 195, 8);
        linearLayout.addView(this.zochsqqeei);
        this.zochsqqeei.setBackgroundColor(Color.parseColor("#49c850"));
        ProgressBar progressBar4 = new ProgressBar(this);
        this.skjbcybmnt = progressBar4;
        progressBar4.setLayoutParams(new LinearLayout.LayoutParams(1698, 693));
        this.skjbcybmnt.setPadding(40, 79, 110, 82);
        linearLayout.addView(this.skjbcybmnt);
        this.skjbcybmnt.setBackgroundColor(Color.parseColor("#9a9949"));
        FrameLayout frameLayout10 = new FrameLayout(this);
        this.excpzdsuxt = frameLayout10;
        frameLayout10.setLayoutParams(new LinearLayout.LayoutParams(896, 1837));
        this.excpzdsuxt.setPadding(17, 47, 119, 105);
        linearLayout.addView(this.excpzdsuxt);
        this.excpzdsuxt.setBackgroundColor(Color.parseColor("#e0afbc"));
        RadioButton radioButton7 = new RadioButton(this);
        this.gsbkadvdbs = radioButton7;
        radioButton7.setLayoutParams(new LinearLayout.LayoutParams(1992, 530));
        this.gsbkadvdbs.setPadding(136, 78, 138, 81);
        linearLayout.addView(this.gsbkadvdbs);
        this.gsbkadvdbs.setBackgroundColor(Color.parseColor("#7c3c4d"));
        Button button6 = new Button(this);
        this.xxeiitkrfj = button6;
        button6.setLayoutParams(new LinearLayout.LayoutParams(755, 1628));
        this.xxeiitkrfj.setPadding(83, 120, 69, 79);
        linearLayout.addView(this.xxeiitkrfj);
        this.xxeiitkrfj.setBackgroundColor(Color.parseColor("#346ddd"));
        FrameLayout frameLayout11 = new FrameLayout(this);
        this.kgeunbirzb = frameLayout11;
        frameLayout11.setLayoutParams(new LinearLayout.LayoutParams(1920, 1186));
        this.kgeunbirzb.setPadding(58, 146, 48, PictureConfig.CHOOSE_REQUEST);
        linearLayout.addView(this.kgeunbirzb);
        this.kgeunbirzb.setBackgroundColor(Color.parseColor("#1f60af"));
        FrameLayout frameLayout12 = new FrameLayout(this);
        this.emnnnlygvc = frameLayout12;
        frameLayout12.setLayoutParams(new LinearLayout.LayoutParams(1520, 263));
        this.emnnnlygvc.setPadding(9, 117, 16, 74);
        linearLayout.addView(this.emnnnlygvc);
        this.emnnnlygvc.setBackgroundColor(Color.parseColor("#10f52e"));
        TableLayout tableLayout9 = new TableLayout(this);
        this.surscdkfel = tableLayout9;
        tableLayout9.setLayoutParams(new LinearLayout.LayoutParams(42, 633));
        this.surscdkfel.setPadding(40, 4, 33, 42);
        linearLayout.addView(this.surscdkfel);
        this.surscdkfel.setBackgroundColor(Color.parseColor("#1f8dbd"));
        ImageView imageView = new ImageView(this);
        this.ismjxakkfz = imageView;
        imageView.setLayoutParams(new LinearLayout.LayoutParams(84, 1932));
        this.ismjxakkfz.setPadding(91, 36, 192, 39);
        linearLayout.addView(this.ismjxakkfz);
        this.ismjxakkfz.setBackgroundColor(Color.parseColor("#d8f1a6"));
        RatingBar ratingBar6 = new RatingBar(this);
        this.qxxqexcyzg = ratingBar6;
        ratingBar6.setLayoutParams(new LinearLayout.LayoutParams(963, 1180));
        this.qxxqexcyzg.setPadding(33, 82, 121, 172);
        linearLayout.addView(this.qxxqexcyzg);
        this.qxxqexcyzg.setBackgroundColor(Color.parseColor("#34ffe0"));
        ToggleButton toggleButton12 = new ToggleButton(this);
        this.qwklwmqykj = toggleButton12;
        toggleButton12.setLayoutParams(new LinearLayout.LayoutParams(521, 807));
        this.qwklwmqykj.setPadding(195, 80, 50, 176);
        linearLayout.addView(this.qwklwmqykj);
        this.qwklwmqykj.setBackgroundColor(Color.parseColor("#788075"));
        DatePicker datePicker7 = new DatePicker(this);
        this.bsubidelpx = datePicker7;
        datePicker7.setLayoutParams(new LinearLayout.LayoutParams(1297, 1905));
        this.bsubidelpx.setPadding(28, 105, 36, 18);
        linearLayout.addView(this.bsubidelpx);
        this.bsubidelpx.setBackgroundColor(Color.parseColor("#12c5b2"));
        TimePicker timePicker5 = new TimePicker(this);
        this.stvyqcqhpp = timePicker5;
        timePicker5.setLayoutParams(new LinearLayout.LayoutParams(177, 1514));
        this.stvyqcqhpp.setPadding(55, 139, 146, 144);
        linearLayout.addView(this.stvyqcqhpp);
        this.stvyqcqhpp.setBackgroundColor(Color.parseColor("#9c3c6f"));
        TableLayout tableLayout10 = new TableLayout(this);
        this.bjbmotdubz = tableLayout10;
        tableLayout10.setLayoutParams(new LinearLayout.LayoutParams(1348, 419));
        this.bjbmotdubz.setPadding(145, 60, 49, 26);
        linearLayout.addView(this.bjbmotdubz);
        this.bjbmotdubz.setBackgroundColor(Color.parseColor("#5a62be"));
        FrameLayout frameLayout13 = new FrameLayout(this);
        this.nlmcylqhct = frameLayout13;
        frameLayout13.setLayoutParams(new LinearLayout.LayoutParams(90, 374));
        this.nlmcylqhct.setPadding(180, 157, 4, 124);
        linearLayout.addView(this.nlmcylqhct);
        this.nlmcylqhct.setBackgroundColor(Color.parseColor("#4e5feb"));
        SeekBar seekBar10 = new SeekBar(this);
        this.pblhnrcmjn = seekBar10;
        seekBar10.setLayoutParams(new LinearLayout.LayoutParams(677, 652));
        this.pblhnrcmjn.setPadding(182, 19, 81, 33);
        linearLayout.addView(this.pblhnrcmjn);
        this.pblhnrcmjn.setBackgroundColor(Color.parseColor("#bbcd5c"));
        TextView textView3 = new TextView(this);
        this.upadtrrlkg = textView3;
        textView3.setLayoutParams(new LinearLayout.LayoutParams(1754, 688));
        this.upadtrrlkg.setPadding(92, 164, 148, 179);
        linearLayout.addView(this.upadtrrlkg);
        this.upadtrrlkg.setBackgroundColor(Color.parseColor("#95f7fd"));
        RelativeLayout relativeLayout14 = new RelativeLayout(this);
        this.ofmvmtoyhi = relativeLayout14;
        relativeLayout14.setLayoutParams(new LinearLayout.LayoutParams(1193, 1113));
        this.ofmvmtoyhi.setPadding(190, 133, 120, 192);
        linearLayout.addView(this.ofmvmtoyhi);
        this.ofmvmtoyhi.setBackgroundColor(Color.parseColor("#644b78"));
        TimePicker timePicker6 = new TimePicker(this);
        this.muohqoqmav = timePicker6;
        timePicker6.setLayoutParams(new LinearLayout.LayoutParams(LocalPlaybackConstants.BUFFER_B_CAN_USE_FLAG, 1294));
        this.muohqoqmav.setPadding(32, 98, 180, 0);
        linearLayout.addView(this.muohqoqmav);
        this.muohqoqmav.setBackgroundColor(Color.parseColor("#be8716"));
        SeekBar seekBar11 = new SeekBar(this);
        this.lmsxgxomsj = seekBar11;
        seekBar11.setLayoutParams(new LinearLayout.LayoutParams(622, 1963));
        this.lmsxgxomsj.setPadding(129, 191, 145, 89);
        linearLayout.addView(this.lmsxgxomsj);
        this.lmsxgxomsj.setBackgroundColor(Color.parseColor("#d33689"));
        TimePicker timePicker7 = new TimePicker(this);
        this.rvyuovpfwb = timePicker7;
        timePicker7.setLayoutParams(new LinearLayout.LayoutParams(1070, 1368));
        this.rvyuovpfwb.setPadding(181, 35, 69, 43);
        linearLayout.addView(this.rvyuovpfwb);
        this.rvyuovpfwb.setBackgroundColor(Color.parseColor("#549446"));
        RelativeLayout relativeLayout15 = new RelativeLayout(this);
        this.zrladvzdzh = relativeLayout15;
        relativeLayout15.setLayoutParams(new LinearLayout.LayoutParams(1947, 225));
        this.zrladvzdzh.setPadding(26, 172, 148, 80);
        linearLayout.addView(this.zrladvzdzh);
        this.zrladvzdzh.setBackgroundColor(Color.parseColor("#c5215e"));
        CheckBox checkBox6 = new CheckBox(this);
        this.gbpwsfjdyu = checkBox6;
        checkBox6.setLayoutParams(new LinearLayout.LayoutParams(466, 616));
        this.gbpwsfjdyu.setPadding(177, 108, 84, 124);
        linearLayout.addView(this.gbpwsfjdyu);
        this.gbpwsfjdyu.setBackgroundColor(Color.parseColor("#0afbae"));
        ViewFlipper viewFlipper6 = new ViewFlipper(this);
        this.beoonlmcwe = viewFlipper6;
        viewFlipper6.setLayoutParams(new LinearLayout.LayoutParams(1267, 943));
        this.beoonlmcwe.setPadding(67, 67, 170, 92);
        linearLayout.addView(this.beoonlmcwe);
        this.beoonlmcwe.setBackgroundColor(Color.parseColor("#976b0f"));
        TimePicker timePicker8 = new TimePicker(this);
        this.igrfquubdt = timePicker8;
        timePicker8.setLayoutParams(new LinearLayout.LayoutParams(365, 138));
        this.igrfquubdt.setPadding(37, WebSocketProtocol.PAYLOAD_SHORT, 189, 74);
        linearLayout.addView(this.igrfquubdt);
        this.igrfquubdt.setBackgroundColor(Color.parseColor("#fba329"));
        ProgressBar progressBar5 = new ProgressBar(this);
        this.lmnnnquhui = progressBar5;
        progressBar5.setLayoutParams(new LinearLayout.LayoutParams(1568, 1322));
        this.lmnnnquhui.setPadding(170, 53, 157, 20);
        linearLayout.addView(this.lmnnnquhui);
        this.lmnnnquhui.setBackgroundColor(Color.parseColor("#eba69a"));
        GridView gridView7 = new GridView(this);
        this.fdcucmjobo = gridView7;
        gridView7.setLayoutParams(new LinearLayout.LayoutParams(584, 205));
        this.fdcucmjobo.setPadding(11, 74, 153, 36);
        linearLayout.addView(this.fdcucmjobo);
        this.fdcucmjobo.setBackgroundColor(Color.parseColor("#b8cd94"));
        EditText editText6 = new EditText(this);
        this.dtgktbxdrx = editText6;
        editText6.setLayoutParams(new LinearLayout.LayoutParams(523, 41));
        this.dtgktbxdrx.setPadding(45, 156, 84, 131);
        linearLayout.addView(this.dtgktbxdrx);
        this.dtgktbxdrx.setBackgroundColor(Color.parseColor("#a7193d"));
        ViewFlipper viewFlipper7 = new ViewFlipper(this);
        this.ucjsmnwlmo = viewFlipper7;
        viewFlipper7.setLayoutParams(new LinearLayout.LayoutParams(518, 321));
        this.ucjsmnwlmo.setPadding(48, 187, 155, 159);
        linearLayout.addView(this.ucjsmnwlmo);
        this.ucjsmnwlmo.setBackgroundColor(Color.parseColor("#c42365"));
        DatePicker datePicker8 = new DatePicker(this);
        this.mkrqssizbo = datePicker8;
        datePicker8.setLayoutParams(new LinearLayout.LayoutParams(369, 1495));
        this.mkrqssizbo.setPadding(16, 181, 196, 132);
        linearLayout.addView(this.mkrqssizbo);
        this.mkrqssizbo.setBackgroundColor(Color.parseColor("#19d7d5"));
        RadioButton radioButton8 = new RadioButton(this);
        this.vgqibpgref = radioButton8;
        radioButton8.setLayoutParams(new LinearLayout.LayoutParams(421, 807));
        this.vgqibpgref.setPadding(26, 79, 45, 104);
        linearLayout.addView(this.vgqibpgref);
        this.vgqibpgref.setBackgroundColor(Color.parseColor("#d7e1ab"));
        CheckBox checkBox7 = new CheckBox(this);
        this.bimzxjkipy = checkBox7;
        checkBox7.setLayoutParams(new LinearLayout.LayoutParams(1262, TypedValues.TransitionType.TYPE_FROM));
        this.bimzxjkipy.setPadding(44, 8, 7, 79);
        linearLayout.addView(this.bimzxjkipy);
        this.bimzxjkipy.setBackgroundColor(Color.parseColor("#19fd15"));
    }
}
