package com.smartapp.b.pmfyhglpoj;

import android.app.Activity;
import android.graphics.Color;
import android.os.Bundle;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.CheckBox;
import android.widget.DatePicker;
import android.widget.EditText;
import android.widget.FrameLayout;
import android.widget.GridView;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ListView;
import android.widget.ProgressBar;
import android.widget.RadioButton;
import android.widget.RatingBar;
import android.widget.RelativeLayout;
import android.widget.ScrollView;
import android.widget.SeekBar;
import android.widget.Spinner;
import android.widget.Switch;
import android.widget.TableLayout;
import android.widget.TextView;
import android.widget.TimePicker;
import android.widget.ToggleButton;
import android.widget.ViewFlipper;
import androidx.constraintlayout.core.motion.utils.TypedValues;
import androidx.core.view.PointerIconCompat;
import androidx.room.RoomDatabase;
import com.baidu.location.BDLocation;
import com.king.zxing.util.CodeUtils;
import com.luck.picture.lib.config.PictureConfig;
import com.realsil.sdk.bbpro.core.protocol.Contract;
import com.realsil.sdk.core.bluetooth.connection.le.GattClient;
import com.realsil.sdk.core.bluetooth.impl.BluetoothClassImpl;
import okhttp3.internal.ws.WebSocketProtocol;

/* loaded from: classes4.dex */
public class SlpiswzsssuActivity extends Activity {
    RatingBar aakvbwxkmy;
    Button abhxjbwccj;
    SeekBar admbadenxw;
    RatingBar aemzjmbuqk;
    Button aeyekkmpel;
    RelativeLayout aknnhkivij;
    DatePicker amtypfzqer;
    TableLayout amudaszhsl;
    RelativeLayout aoxglekqzk;
    Switch appqayhunz;
    GridView apqudglwic;
    TableLayout atceyebadd;
    SeekBar atjtazoncc;
    CheckBox aubzxqbadl;
    Spinner avxewfowgk;
    CheckBox axhvedsagb;
    ToggleButton azvlyulhku;
    TableLayout bblicveyup;
    CheckBox begyysjjmw;
    ViewFlipper bhjowujxub;
    ScrollView bokiqdmnfy;
    RelativeLayout bqekwlbyye;
    TableLayout broykvffnd;
    Switch cbtbcinkak;
    Spinner cfrervtqes;
    Switch chgaadkila;
    LinearLayout chgvijvbtd;
    LinearLayout cjqhascwne;
    EditText ckyhumgavo;
    ProgressBar cosaekvgme;
    ListView crovylsxxz;
    TimePicker csbdnkmape;
    RatingBar cumjhkrkqq;
    SeekBar cvqoiyzmvu;
    ToggleButton cywkniudpl;
    Spinner czzyndmgkt;
    RatingBar dhibfiupkv;
    SeekBar dhryfluyzt;
    ScrollView dhsgwcsayw;
    RadioButton dmkljlgvfp;
    TextView dmpumzfhgv;
    Spinner dprdmrzogi;
    ImageView dqbxquhpkv;
    ImageView droflidmkx;
    CheckBox drqdjjrtfv;
    ToggleButton dsmopqzwhl;
    CheckBox dtajxrvhqi;
    ProgressBar dxsgohmefv;
    Button eacarovjym;
    GridView ecfqbdijml;
    Switch efhkjstami;
    FrameLayout egigqszzdr;
    Button eldpupoesh;
    EditText elhgvsmqtk;
    TextView etzvxirfaz;
    ListView evoyoiwmwp;
    TextView fbjdhusqef;
    ToggleButton fddrzgxsbx;
    ImageView fgxdbufzpl;
    TimePicker frkxvjpdoj;
    Spinner fwaxpwofbo;
    GridView fxlflzxilw;
    ListView fzfwskzbzu;
    CheckBox gcgyzqfrch;
    SeekBar gkopvnirqh;
    DatePicker glegksvekl;
    ScrollView glzzulrkwq;
    DatePicker gowwtxpmfm;
    CheckBox goxptnbfjs;
    Spinner gywdxcjyvo;
    LinearLayout gzleqhtmcy;
    SeekBar hdpavhuxfq;
    ProgressBar hegjdxseio;
    GridView hfgyvvfcyd;
    Button hhtcysbkvp;
    SeekBar hknpturtod;
    RadioButton hnksreizsj;
    TableLayout hnnxzwomwl;
    ViewFlipper hqiixbdewn;
    ListView hqtoqlxrpt;
    ToggleButton hvqattbghz;
    Switch hxlolltazv;
    GridView iczhvkrwvk;
    ImageView ifrrqdmslz;
    Switch igcleqwqyk;
    ToggleButton iidyixehqq;
    RatingBar ijdhpuljpy;
    EditText ijxuetzpel;
    SeekBar iuqgucocek;
    ViewFlipper iygzxhgkkv;
    RelativeLayout jaapwdptnm;
    Spinner jlohveifzd;
    RelativeLayout jthpuynfvy;
    ViewFlipper juuqbwvcdi;
    RatingBar juybxqkplg;
    ProgressBar jzskqyqakp;
    LinearLayout kdyeyqobkc;
    DatePicker kkzcgxsely;
    DatePicker klovlvytzu;
    ToggleButton kquikvfqsj;
    Switch krkwxlsuga;
    ListView ktkemnnywy;
    ImageView ktrfzukheh;
    Switch kxnpzmwrlq;
    CheckBox kznamddyvw;
    ImageView lggacjyiev;
    FrameLayout lhguygymgj;
    ScrollView ljnrkdsxkh;
    Spinner lkzimblenh;
    Switch llblvcjjer;
    ScrollView lqtnsmgyoz;
    FrameLayout lvbwntzbid;
    LinearLayout lxxepqjsbg;
    ViewFlipper lyjberawes;
    LinearLayout mcmonntelk;
    SeekBar mgienqbnww;
    ToggleButton mipmkylyjr;
    FrameLayout mkgkzrngag;
    ListView mkofznlojf;
    FrameLayout mmimxstcfj;
    ImageView mumgthakyw;
    EditText mvrgrbrhdb;
    RelativeLayout mvwxstxsmd;
    ProgressBar mwhbfgzbcq;
    DatePicker ngarcgpfrf;
    Switch nludtlctmb;
    ImageView nmnarpsywe;
    LinearLayout oalgdablmb;
    RatingBar oaxtnhdszc;
    ProgressBar obexcstzhh;
    ProgressBar odmqskeqiz;
    FrameLayout ojcheewehb;
    ImageView ojvoybwgtb;
    ToggleButton ovgstmxmub;
    RelativeLayout owqegevssf;
    GridView oxsrethntl;
    ProgressBar paxtoitvqb;
    Spinner pbxaknnqft;
    RelativeLayout pctuwmjfze;
    GridView pexifdqhfy;
    RadioButton phpvjmprpx;
    FrameLayout ppzrgblbmr;
    TimePicker pqsdnilomw;
    Button ptbdseabbr;
    GridView qehyivwkuq;
    FrameLayout qfotuohhfy;
    ToggleButton qkbxwbfhsv;
    Spinner qkvtunzrji;
    DatePicker qppvdlziuw;
    ImageView qvfttmfoky;
    TimePicker rgzjyhvtji;
    TableLayout rqsderssgd;
    RelativeLayout rsxacbuwte;
    CheckBox ryawzfdtyd;
    EditText rypwiemyrt;
    RelativeLayout saegeijifx;
    CheckBox scdsoghubs;
    RelativeLayout sdkufazosd;
    LinearLayout sicendienu;
    TableLayout silkzvicog;
    TimePicker skyasuwzah;
    ScrollView sqiauxryug;
    TextView sqjcvkprhh;
    ToggleButton sqqqgxhnfp;
    TextView szoljldsyf;
    SeekBar teizfhuifk;
    ListView tgvirazgir;
    TimePicker tiqevkpwol;
    ViewFlipper tmyuuhymdq;
    EditText tqzozxgveg;
    RadioButton tsgueyjjvt;
    CheckBox tsuwfynldr;
    RatingBar tuvobpffhp;
    ProgressBar uflflgfbzc;
    LinearLayout ugwauftrlg;
    ListView uihjdctptl;
    RadioButton uksfrarkng;
    ToggleButton ulbplmyvou;
    LinearLayout unyolclhxd;
    ListView uobyytbymn;
    RelativeLayout uvizualgxi;
    EditText uwadbyvpxz;
    ListView uwsvuqnrdt;
    RatingBar uxudxjywfv;
    TextView vdqgsolqhr;
    ScrollView vjnljvdiao;
    ScrollView vkhptbzrly;
    SeekBar vlavosowcf;
    RelativeLayout vqxqessomy;
    RadioButton vrhhrppgxi;
    ListView vtrttcbwlh;
    TextView vucbnmvnnj;
    ListView vvjdypweig;
    ImageView vxsxnuhtwn;
    Button wdeffcjhzt;
    TimePicker wdgcomyhmc;
    ToggleButton wfqwanqjdk;
    ProgressBar woyczffwxb;
    LinearLayout wufkxhrqst;
    TextView wxtvlwsdpi;
    ScrollView wyrznlxhfn;
    Button xccwydunei;
    Button xelqsfaszq;
    ToggleButton xgwkaecwig;
    ListView xhpqnelmsm;
    ImageView xhxghmhkmx;
    RadioButton xiczxodhby;
    ProgressBar xizzvlljec;
    LinearLayout xlphcibdhv;
    TableLayout xphfczygbx;
    EditText xqyrdzgmyh;
    CheckBox xwjmazfphd;
    ToggleButton xxtxupatdo;
    ViewFlipper ybazllzabm;
    CheckBox yfmzhfzhsj;
    ImageView ykhmgjigtk;
    Switch ypemgektpx;
    RadioButton zdamedvjxm;
    GridView zgbqicqnka;
    TextView zyzfoteetk;

    @Override // android.app.Activity
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        LinearLayout linearLayout = new LinearLayout(this);
        setContentView(linearLayout);
        linearLayout.setLayoutParams(new ViewGroup.LayoutParams(-1, -1));
        linearLayout.setOrientation(1);
        linearLayout.setBackgroundColor(Color.parseColor("#0e5a84"));
        SeekBar seekBar = new SeekBar(this);
        this.gkopvnirqh = seekBar;
        seekBar.setLayoutParams(new LinearLayout.LayoutParams(198, 1973));
        this.gkopvnirqh.setPadding(83, 36, 189, 121);
        linearLayout.addView(this.gkopvnirqh);
        this.gkopvnirqh.setBackgroundColor(Color.parseColor("#b51a81"));
        Button button = new Button(this);
        this.ptbdseabbr = button;
        button.setLayoutParams(new LinearLayout.LayoutParams(994, 28));
        this.ptbdseabbr.setPadding(138, 177, 170, 113);
        linearLayout.addView(this.ptbdseabbr);
        this.ptbdseabbr.setBackgroundColor(Color.parseColor("#2a82fb"));
        DatePicker datePicker = new DatePicker(this);
        this.glegksvekl = datePicker;
        datePicker.setLayoutParams(new LinearLayout.LayoutParams(489, 1788));
        this.glegksvekl.setPadding(111, 76, 133, 165);
        linearLayout.addView(this.glegksvekl);
        this.glegksvekl.setBackgroundColor(Color.parseColor("#69b9f2"));
        TimePicker timePicker = new TimePicker(this);
        this.wdgcomyhmc = timePicker;
        timePicker.setLayoutParams(new LinearLayout.LayoutParams(983, 1538));
        this.wdgcomyhmc.setPadding(65, 59, 18, 48);
        linearLayout.addView(this.wdgcomyhmc);
        this.wdgcomyhmc.setBackgroundColor(Color.parseColor("#99edb7"));
        RelativeLayout relativeLayout = new RelativeLayout(this);
        this.saegeijifx = relativeLayout;
        relativeLayout.setLayoutParams(new LinearLayout.LayoutParams(838, 1805));
        this.saegeijifx.setPadding(PictureConfig.CHOOSE_REQUEST, BDLocation.TypeServerError, 150, BDLocation.TypeServerDecryptError);
        linearLayout.addView(this.saegeijifx);
        this.saegeijifx.setBackgroundColor(Color.parseColor("#bd08a7"));
        ToggleButton toggleButton = new ToggleButton(this);
        this.wfqwanqjdk = toggleButton;
        toggleButton.setLayoutParams(new LinearLayout.LayoutParams(1092, TypedValues.TransitionType.TYPE_TO));
        this.wfqwanqjdk.setPadding(3, 29, 182, 52);
        linearLayout.addView(this.wfqwanqjdk);
        this.wfqwanqjdk.setBackgroundColor(Color.parseColor("#6bb5dc"));
        RelativeLayout relativeLayout2 = new RelativeLayout(this);
        this.jthpuynfvy = relativeLayout2;
        relativeLayout2.setLayoutParams(new LinearLayout.LayoutParams(1432, 1494));
        this.jthpuynfvy.setPadding(139, 72, 193, 123);
        linearLayout.addView(this.jthpuynfvy);
        this.jthpuynfvy.setBackgroundColor(Color.parseColor("#d5a132"));
        ToggleButton toggleButton2 = new ToggleButton(this);
        this.qkbxwbfhsv = toggleButton2;
        toggleButton2.setLayoutParams(new LinearLayout.LayoutParams(189, 386));
        this.qkbxwbfhsv.setPadding(177, 61, 0, 68);
        linearLayout.addView(this.qkbxwbfhsv);
        this.qkbxwbfhsv.setBackgroundColor(Color.parseColor("#c18bc6"));
        EditText editText = new EditText(this);
        this.rypwiemyrt = editText;
        editText.setLayoutParams(new LinearLayout.LayoutParams(96, 1549));
        this.rypwiemyrt.setPadding(46, 147, 103, 41);
        linearLayout.addView(this.rypwiemyrt);
        this.rypwiemyrt.setBackgroundColor(Color.parseColor("#8f819b"));
        TextView textView = new TextView(this);
        this.vdqgsolqhr = textView;
        textView.setLayoutParams(new LinearLayout.LayoutParams(1916, 971));
        this.vdqgsolqhr.setPadding(136, 182, 148, 166);
        linearLayout.addView(this.vdqgsolqhr);
        this.vdqgsolqhr.setBackgroundColor(Color.parseColor("#4c1020"));
        ImageView imageView = new ImageView(this);
        this.vxsxnuhtwn = imageView;
        imageView.setLayoutParams(new LinearLayout.LayoutParams(750, 1973));
        this.vxsxnuhtwn.setPadding(105, 168, 124, 26);
        linearLayout.addView(this.vxsxnuhtwn);
        this.vxsxnuhtwn.setBackgroundColor(Color.parseColor("#85886b"));
        DatePicker datePicker2 = new DatePicker(this);
        this.gowwtxpmfm = datePicker2;
        datePicker2.setLayoutParams(new LinearLayout.LayoutParams(1515, 1502));
        this.gowwtxpmfm.setPadding(157, 115, 38, 5);
        linearLayout.addView(this.gowwtxpmfm);
        this.gowwtxpmfm.setBackgroundColor(Color.parseColor("#b75bd7"));
        ScrollView scrollView = new ScrollView(this);
        this.vjnljvdiao = scrollView;
        scrollView.setLayoutParams(new LinearLayout.LayoutParams(GattClient.STATE_PREPARE_PAIRING_REQUEST, 265));
        this.vjnljvdiao.setPadding(60, 71, 96, 42);
        linearLayout.addView(this.vjnljvdiao);
        this.vjnljvdiao.setBackgroundColor(Color.parseColor("#9a9492"));
        SeekBar seekBar2 = new SeekBar(this);
        this.teizfhuifk = seekBar2;
        seekBar2.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.Custom.TYPE_COLOR, 1756));
        this.teizfhuifk.setPadding(176, 123, 94, 169);
        linearLayout.addView(this.teizfhuifk);
        this.teizfhuifk.setBackgroundColor(Color.parseColor("#7fbaba"));
        RadioButton radioButton = new RadioButton(this);
        this.xiczxodhby = radioButton;
        radioButton.setLayoutParams(new LinearLayout.LayoutParams(PictureConfig.CHOOSE_REQUEST, 670));
        this.xiczxodhby.setPadding(152, 163, 121, 189);
        linearLayout.addView(this.xiczxodhby);
        this.xiczxodhby.setBackgroundColor(Color.parseColor("#a05e7d"));
        ListView listView = new ListView(this);
        this.uihjdctptl = listView;
        listView.setLayoutParams(new LinearLayout.LayoutParams(843, 1089));
        this.uihjdctptl.setPadding(98, 78, 116, 173);
        linearLayout.addView(this.uihjdctptl);
        this.uihjdctptl.setBackgroundColor(Color.parseColor("#2054e6"));
        CheckBox checkBox = new CheckBox(this);
        this.axhvedsagb = checkBox;
        checkBox.setLayoutParams(new LinearLayout.LayoutParams(249, TypedValues.Custom.TYPE_INT));
        this.axhvedsagb.setPadding(15, 97, 163, 49);
        linearLayout.addView(this.axhvedsagb);
        this.axhvedsagb.setBackgroundColor(Color.parseColor("#ec0d05"));
        ToggleButton toggleButton3 = new ToggleButton(this);
        this.iidyixehqq = toggleButton3;
        toggleButton3.setLayoutParams(new LinearLayout.LayoutParams(1754, 911));
        this.iidyixehqq.setPadding(143, 181, 53, 35);
        linearLayout.addView(this.iidyixehqq);
        this.iidyixehqq.setBackground(new Pjqkzqsczke());
        EditText editText2 = new EditText(this);
        this.elhgvsmqtk = editText2;
        editText2.setLayoutParams(new LinearLayout.LayoutParams(1858, 461));
        this.elhgvsmqtk.setPadding(42, 159, 4, BDLocation.TypeNetWorkLocation);
        linearLayout.addView(this.elhgvsmqtk);
        this.elhgvsmqtk.setBackgroundColor(Color.parseColor("#c9157d"));
        ListView listView2 = new ListView(this);
        this.evoyoiwmwp = listView2;
        listView2.setLayoutParams(new LinearLayout.LayoutParams(8, 145));
        this.evoyoiwmwp.setPadding(9, 169, 86, 115);
        linearLayout.addView(this.evoyoiwmwp);
        this.evoyoiwmwp.setBackgroundColor(Color.parseColor("#3af3de"));
        RatingBar ratingBar = new RatingBar(this);
        this.oaxtnhdszc = ratingBar;
        ratingBar.setLayoutParams(new LinearLayout.LayoutParams(1320, 1513));
        this.oaxtnhdszc.setPadding(154, 144, 65, 86);
        linearLayout.addView(this.oaxtnhdszc);
        this.oaxtnhdszc.setBackgroundColor(Color.parseColor("#6006aa"));
        ToggleButton toggleButton4 = new ToggleButton(this);
        this.dsmopqzwhl = toggleButton4;
        toggleButton4.setLayoutParams(new LinearLayout.LayoutParams(BluetoothClassImpl.Device.PERIPHERAL_KEYBOARD, 1299));
        this.dsmopqzwhl.setPadding(20, 140, 144, 153);
        linearLayout.addView(this.dsmopqzwhl);
        this.dsmopqzwhl.setBackgroundColor(Color.parseColor("#c105fb"));
        ProgressBar progressBar = new ProgressBar(this);
        this.xizzvlljec = progressBar;
        progressBar.setLayoutParams(new LinearLayout.LayoutParams(1598, 642));
        this.xizzvlljec.setPadding(50, 121, 125, 132);
        linearLayout.addView(this.xizzvlljec);
        this.xizzvlljec.setBackgroundColor(Color.parseColor("#2d134e"));
        GridView gridView = new GridView(this);
        this.oxsrethntl = gridView;
        gridView.setLayoutParams(new LinearLayout.LayoutParams(1481, 1995));
        this.oxsrethntl.setPadding(2, 16, 20, 135);
        linearLayout.addView(this.oxsrethntl);
        this.oxsrethntl.setBackgroundColor(Color.parseColor("#2e413a"));
        ImageView imageView2 = new ImageView(this);
        this.mumgthakyw = imageView2;
        imageView2.setLayoutParams(new LinearLayout.LayoutParams(584, 1462));
        this.mumgthakyw.setPadding(176, 130, BDLocation.TypeCoarseLocation, 17);
        linearLayout.addView(this.mumgthakyw);
        this.mumgthakyw.setBackgroundColor(Color.parseColor("#ad1055"));
        ToggleButton toggleButton5 = new ToggleButton(this);
        this.kquikvfqsj = toggleButton5;
        toggleButton5.setLayoutParams(new LinearLayout.LayoutParams(1015, 1591));
        this.kquikvfqsj.setPadding(64, 50, 80, 143);
        linearLayout.addView(this.kquikvfqsj);
        this.kquikvfqsj.setBackgroundColor(Color.parseColor("#3d0dc7"));
        ImageView imageView3 = new ImageView(this);
        this.qvfttmfoky = imageView3;
        imageView3.setLayoutParams(new LinearLayout.LayoutParams(1260, 351));
        this.qvfttmfoky.setPadding(168, 190, 180, 174);
        linearLayout.addView(this.qvfttmfoky);
        this.qvfttmfoky.setBackgroundColor(Color.parseColor("#a0ae0d"));
        ToggleButton toggleButton6 = new ToggleButton(this);
        this.xxtxupatdo = toggleButton6;
        toggleButton6.setLayoutParams(new LinearLayout.LayoutParams(801, PointerIconCompat.TYPE_ZOOM_OUT));
        this.xxtxupatdo.setPadding(PictureConfig.CHOOSE_REQUEST, 82, BDLocation.TypeCoarseLocation, 47);
        linearLayout.addView(this.xxtxupatdo);
        this.xxtxupatdo.setBackgroundColor(Color.parseColor("#64c3b2"));
        GridView gridView2 = new GridView(this);
        this.hfgyvvfcyd = gridView2;
        gridView2.setLayoutParams(new LinearLayout.LayoutParams(20, 992));
        this.hfgyvvfcyd.setPadding(156, 41, 67, 77);
        linearLayout.addView(this.hfgyvvfcyd);
        this.hfgyvvfcyd.setBackgroundColor(Color.parseColor("#18aa1c"));
        ImageView imageView4 = new ImageView(this);
        this.fgxdbufzpl = imageView4;
        imageView4.setLayoutParams(new LinearLayout.LayoutParams(1219, 552));
        this.fgxdbufzpl.setPadding(41, 105, 146, 124);
        linearLayout.addView(this.fgxdbufzpl);
        this.fgxdbufzpl.setBackgroundColor(Color.parseColor("#74c772"));
        LinearLayout linearLayout2 = new LinearLayout(this);
        this.chgvijvbtd = linearLayout2;
        linearLayout2.setLayoutParams(new LinearLayout.LayoutParams(331, 949));
        this.chgvijvbtd.setPadding(53, 138, 5, 176);
        linearLayout.addView(this.chgvijvbtd);
        this.chgvijvbtd.setBackgroundColor(Color.parseColor("#cceb2f"));
        TextView textView2 = new TextView(this);
        this.dmpumzfhgv = textView2;
        textView2.setLayoutParams(new LinearLayout.LayoutParams(726, 744));
        this.dmpumzfhgv.setPadding(128, 107, 42, 17);
        linearLayout.addView(this.dmpumzfhgv);
        this.dmpumzfhgv.setBackgroundColor(Color.parseColor("#067a22"));
        EditText editText3 = new EditText(this);
        this.mvrgrbrhdb = editText3;
        editText3.setLayoutParams(new LinearLayout.LayoutParams(1356, 613));
        this.mvrgrbrhdb.setPadding(24, 17, 192, 111);
        linearLayout.addView(this.mvrgrbrhdb);
        this.mvrgrbrhdb.setBackgroundColor(Color.parseColor("#727ecc"));
        ScrollView scrollView2 = new ScrollView(this);
        this.glzzulrkwq = scrollView2;
        scrollView2.setLayoutParams(new LinearLayout.LayoutParams(1002, 975));
        this.glzzulrkwq.setPadding(1, 132, 179, 15);
        linearLayout.addView(this.glzzulrkwq);
        this.glzzulrkwq.setBackgroundColor(Color.parseColor("#23a04a"));
        ImageView imageView5 = new ImageView(this);
        this.ifrrqdmslz = imageView5;
        imageView5.setLayoutParams(new LinearLayout.LayoutParams(1799, 98));
        this.ifrrqdmslz.setPadding(90, 184, 86, 74);
        linearLayout.addView(this.ifrrqdmslz);
        this.ifrrqdmslz.setBackgroundColor(Color.parseColor("#223bf0"));
        SeekBar seekBar3 = new SeekBar(this);
        this.hdpavhuxfq = seekBar3;
        seekBar3.setLayoutParams(new LinearLayout.LayoutParams(93, 1930));
        this.hdpavhuxfq.setPadding(81, 157, 22, 117);
        linearLayout.addView(this.hdpavhuxfq);
        this.hdpavhuxfq.setBackgroundColor(Color.parseColor("#7d1d41"));
        TextView textView3 = new TextView(this);
        this.sqjcvkprhh = textView3;
        textView3.setLayoutParams(new LinearLayout.LayoutParams(716, 1094));
        this.sqjcvkprhh.setPadding(141, 92, 34, 65);
        linearLayout.addView(this.sqjcvkprhh);
        this.sqjcvkprhh.setBackgroundColor(Color.parseColor("#2792a1"));
        LinearLayout linearLayout3 = new LinearLayout(this);
        this.wufkxhrqst = linearLayout3;
        linearLayout3.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.MotionType.TYPE_QUANTIZE_MOTIONSTEPS, 1905));
        this.wufkxhrqst.setPadding(2, 39, 113, 128);
        linearLayout.addView(this.wufkxhrqst);
        this.wufkxhrqst.setBackgroundColor(Color.parseColor("#d51416"));
        RadioButton radioButton2 = new RadioButton(this);
        this.phpvjmprpx = radioButton2;
        radioButton2.setLayoutParams(new LinearLayout.LayoutParams(1247, 1047));
        this.phpvjmprpx.setPadding(154, 76, 76, BDLocation.TypeServerDecryptError);
        linearLayout.addView(this.phpvjmprpx);
        this.phpvjmprpx.setBackgroundColor(Color.parseColor("#a8d9bd"));
        EditText editText4 = new EditText(this);
        this.tqzozxgveg = editText4;
        editText4.setLayoutParams(new LinearLayout.LayoutParams(300, 39));
        this.tqzozxgveg.setPadding(38, 85, 106, 43);
        linearLayout.addView(this.tqzozxgveg);
        this.tqzozxgveg.setBackgroundColor(Color.parseColor("#f9f876"));
        ProgressBar progressBar2 = new ProgressBar(this);
        this.hegjdxseio = progressBar2;
        progressBar2.setLayoutParams(new LinearLayout.LayoutParams(467, 1506));
        this.hegjdxseio.setPadding(189, 39, 89, 42);
        linearLayout.addView(this.hegjdxseio);
        this.hegjdxseio.setBackgroundColor(Color.parseColor("#87f1bc"));
        TimePicker timePicker2 = new TimePicker(this);
        this.skyasuwzah = timePicker2;
        timePicker2.setLayoutParams(new LinearLayout.LayoutParams(753, 151));
        this.skyasuwzah.setPadding(61, 141, 65, 7);
        linearLayout.addView(this.skyasuwzah);
        this.skyasuwzah.setBackgroundColor(Color.parseColor("#a0e97c"));
        FrameLayout frameLayout = new FrameLayout(this);
        this.ppzrgblbmr = frameLayout;
        frameLayout.setLayoutParams(new LinearLayout.LayoutParams(63, 1890));
        this.ppzrgblbmr.setPadding(69, 41, 189, 32);
        linearLayout.addView(this.ppzrgblbmr);
        this.ppzrgblbmr.setBackgroundColor(Color.parseColor("#7f95b2"));
        CheckBox checkBox2 = new CheckBox(this);
        this.scdsoghubs = checkBox2;
        checkBox2.setLayoutParams(new LinearLayout.LayoutParams(408, 1368));
        this.scdsoghubs.setPadding(123, 159, 11, 66);
        linearLayout.addView(this.scdsoghubs);
        this.scdsoghubs.setBackgroundColor(Color.parseColor("#f86551"));
        TextView textView4 = new TextView(this);
        this.szoljldsyf = textView4;
        textView4.setLayoutParams(new LinearLayout.LayoutParams(381, 1176));
        this.szoljldsyf.setPadding(177, 141, BDLocation.TypeServerDecryptError, 176);
        linearLayout.addView(this.szoljldsyf);
        this.szoljldsyf.setBackgroundColor(Color.parseColor("#2eba52"));
        ImageView imageView6 = new ImageView(this);
        this.nmnarpsywe = imageView6;
        imageView6.setLayoutParams(new LinearLayout.LayoutParams(139, 601));
        this.nmnarpsywe.setPadding(171, 122, 170, 122);
        linearLayout.addView(this.nmnarpsywe);
        this.nmnarpsywe.setBackgroundColor(Color.parseColor("#1962ab"));
        TextView textView5 = new TextView(this);
        this.vucbnmvnnj = textView5;
        textView5.setLayoutParams(new LinearLayout.LayoutParams(1206, 483));
        this.vucbnmvnnj.setPadding(149, 18, 118, 28);
        linearLayout.addView(this.vucbnmvnnj);
        this.vucbnmvnnj.setBackgroundColor(Color.parseColor("#bdff1b"));
        Spinner spinner = new Spinner(this);
        this.cfrervtqes = spinner;
        spinner.setLayoutParams(new LinearLayout.LayoutParams(1718, 1732));
        this.cfrervtqes.setPadding(144, 20, 14, 137);
        linearLayout.addView(this.cfrervtqes);
        this.cfrervtqes.setBackgroundColor(Color.parseColor("#69c572"));
        Switch r2 = new Switch(this);
        this.kxnpzmwrlq = r2;
        r2.setLayoutParams(new LinearLayout.LayoutParams(1655, 968));
        this.kxnpzmwrlq.setPadding(196, 185, 146, 12);
        linearLayout.addView(this.kxnpzmwrlq);
        this.kxnpzmwrlq.setBackgroundColor(Color.parseColor("#1f5c48"));
        ProgressBar progressBar3 = new ProgressBar(this);
        this.dxsgohmefv = progressBar3;
        progressBar3.setLayoutParams(new LinearLayout.LayoutParams(1959, 1117));
        this.dxsgohmefv.setPadding(15, 138, 80, 74);
        linearLayout.addView(this.dxsgohmefv);
        this.dxsgohmefv.setBackgroundColor(Color.parseColor("#11d7de"));
        TextView textView6 = new TextView(this);
        this.wxtvlwsdpi = textView6;
        textView6.setLayoutParams(new LinearLayout.LayoutParams(32, 1929));
        this.wxtvlwsdpi.setPadding(164, 84, 78, 6);
        linearLayout.addView(this.wxtvlwsdpi);
        this.wxtvlwsdpi.setBackgroundColor(Color.parseColor("#79c632"));
        ScrollView scrollView3 = new ScrollView(this);
        this.vkhptbzrly = scrollView3;
        scrollView3.setLayoutParams(new LinearLayout.LayoutParams(1133, 626));
        this.vkhptbzrly.setPadding(199, 98, 194, 137);
        linearLayout.addView(this.vkhptbzrly);
        this.vkhptbzrly.setBackgroundColor(Color.parseColor("#64e617"));
        ProgressBar progressBar4 = new ProgressBar(this);
        this.woyczffwxb = progressBar4;
        progressBar4.setLayoutParams(new LinearLayout.LayoutParams(225, 1857));
        this.woyczffwxb.setPadding(181, 111, 158, 197);
        linearLayout.addView(this.woyczffwxb);
        this.woyczffwxb.setBackgroundColor(Color.parseColor("#f3804e"));
        Button button2 = new Button(this);
        this.eacarovjym = button2;
        button2.setLayoutParams(new LinearLayout.LayoutParams(282, 1867));
        this.eacarovjym.setPadding(122, 31, 73, 37);
        linearLayout.addView(this.eacarovjym);
        this.eacarovjym.setBackgroundColor(Color.parseColor("#8ee217"));
        TimePicker timePicker3 = new TimePicker(this);
        this.frkxvjpdoj = timePicker3;
        timePicker3.setLayoutParams(new LinearLayout.LayoutParams(PictureConfig.CHOOSE_REQUEST, 261));
        this.frkxvjpdoj.setPadding(146, 106, 121, 172);
        linearLayout.addView(this.frkxvjpdoj);
        this.frkxvjpdoj.setBackgroundColor(Color.parseColor("#8b6240"));
        DatePicker datePicker3 = new DatePicker(this);
        this.ngarcgpfrf = datePicker3;
        datePicker3.setLayoutParams(new LinearLayout.LayoutParams(433, 1162));
        this.ngarcgpfrf.setPadding(146, 172, 100, 168);
        linearLayout.addView(this.ngarcgpfrf);
        this.ngarcgpfrf.setBackgroundColor(Color.parseColor("#4b162d"));
        TableLayout tableLayout = new TableLayout(this);
        this.atceyebadd = tableLayout;
        tableLayout.setLayoutParams(new LinearLayout.LayoutParams(118, 36));
        this.atceyebadd.setPadding(103, 171, 5, 186);
        linearLayout.addView(this.atceyebadd);
        this.atceyebadd.setBackgroundColor(Color.parseColor("#e28ce2"));
        LinearLayout linearLayout4 = new LinearLayout(this);
        this.mcmonntelk = linearLayout4;
        linearLayout4.setLayoutParams(new LinearLayout.LayoutParams(297, 763));
        this.mcmonntelk.setPadding(77, 37, 107, 84);
        linearLayout.addView(this.mcmonntelk);
        this.mcmonntelk.setBackgroundColor(Color.parseColor("#b57eed"));
        ListView listView3 = new ListView(this);
        this.tgvirazgir = listView3;
        listView3.setLayoutParams(new LinearLayout.LayoutParams(1270, 806));
        this.tgvirazgir.setPadding(171, 118, 60, 54);
        linearLayout.addView(this.tgvirazgir);
        this.tgvirazgir.setBackgroundColor(Color.parseColor("#576651"));
        TimePicker timePicker4 = new TimePicker(this);
        this.pqsdnilomw = timePicker4;
        timePicker4.setLayoutParams(new LinearLayout.LayoutParams(377, 1828));
        this.pqsdnilomw.setPadding(113, 100, 169, 198);
        linearLayout.addView(this.pqsdnilomw);
        this.pqsdnilomw.setBackgroundColor(Color.parseColor("#7a3181"));
        ViewFlipper viewFlipper = new ViewFlipper(this);
        this.hqiixbdewn = viewFlipper;
        viewFlipper.setLayoutParams(new LinearLayout.LayoutParams(1845, 942));
        this.hqiixbdewn.setPadding(124, 127, 99, 123);
        linearLayout.addView(this.hqiixbdewn);
        this.hqiixbdewn.setBackgroundColor(Color.parseColor("#9b4a31"));
        TableLayout tableLayout2 = new TableLayout(this);
        this.silkzvicog = tableLayout2;
        tableLayout2.setLayoutParams(new LinearLayout.LayoutParams(1306, 708));
        this.silkzvicog.setPadding(177, 97, 59, 37);
        linearLayout.addView(this.silkzvicog);
        this.silkzvicog.setBackgroundColor(Color.parseColor("#6daec9"));
        ImageView imageView7 = new ImageView(this);
        this.ktrfzukheh = imageView7;
        imageView7.setLayoutParams(new LinearLayout.LayoutParams(1373, 1162));
        this.ktrfzukheh.setPadding(WebSocketProtocol.PAYLOAD_SHORT, 21, 174, 132);
        linearLayout.addView(this.ktrfzukheh);
        this.ktrfzukheh.setBackgroundColor(Color.parseColor("#8a333f"));
        ScrollView scrollView4 = new ScrollView(this);
        this.ljnrkdsxkh = scrollView4;
        scrollView4.setLayoutParams(new LinearLayout.LayoutParams(585, 774));
        this.ljnrkdsxkh.setPadding(159, 127, 23, 3);
        linearLayout.addView(this.ljnrkdsxkh);
        this.ljnrkdsxkh.setBackgroundColor(Color.parseColor("#af18fd"));
        TextView textView7 = new TextView(this);
        this.zyzfoteetk = textView7;
        textView7.setLayoutParams(new LinearLayout.LayoutParams(1323, 561));
        this.zyzfoteetk.setPadding(125, 144, 22, 96);
        linearLayout.addView(this.zyzfoteetk);
        this.zyzfoteetk.setBackgroundColor(Color.parseColor("#ddd9dc"));
        ListView listView4 = new ListView(this);
        this.mkofznlojf = listView4;
        listView4.setLayoutParams(new LinearLayout.LayoutParams(1971, 1694));
        this.mkofznlojf.setPadding(9, 116, 110, 41);
        linearLayout.addView(this.mkofznlojf);
        this.mkofznlojf.setBackgroundColor(Color.parseColor("#7fe745"));
        RatingBar ratingBar2 = new RatingBar(this);
        this.cumjhkrkqq = ratingBar2;
        ratingBar2.setLayoutParams(new LinearLayout.LayoutParams(445, 178));
        this.cumjhkrkqq.setPadding(94, 139, 52, 13);
        linearLayout.addView(this.cumjhkrkqq);
        this.cumjhkrkqq.setBackgroundColor(Color.parseColor("#c05c08"));
        CheckBox checkBox3 = new CheckBox(this);
        this.goxptnbfjs = checkBox3;
        checkBox3.setLayoutParams(new LinearLayout.LayoutParams(631, 618));
        this.goxptnbfjs.setPadding(109, 144, 3, 166);
        linearLayout.addView(this.goxptnbfjs);
        this.goxptnbfjs.setBackgroundColor(Color.parseColor("#a94667"));
        Switch r22 = new Switch(this);
        this.krkwxlsuga = r22;
        r22.setLayoutParams(new LinearLayout.LayoutParams(373, 1498));
        this.krkwxlsuga.setPadding(82, 89, 44, 63);
        linearLayout.addView(this.krkwxlsuga);
        this.krkwxlsuga.setBackgroundColor(Color.parseColor("#b5b4ce"));
        RadioButton radioButton3 = new RadioButton(this);
        this.vrhhrppgxi = radioButton3;
        radioButton3.setLayoutParams(new LinearLayout.LayoutParams(680, 1825));
        this.vrhhrppgxi.setPadding(181, 19, 18, 183);
        linearLayout.addView(this.vrhhrppgxi);
        this.vrhhrppgxi.setBackgroundColor(Color.parseColor("#f451e2"));
        Switch r23 = new Switch(this);
        this.appqayhunz = r23;
        r23.setLayoutParams(new LinearLayout.LayoutParams(1653, 1582));
        this.appqayhunz.setPadding(76, 34, 27, 121);
        linearLayout.addView(this.appqayhunz);
        this.appqayhunz.setBackgroundColor(Color.parseColor("#c2737b"));
        FrameLayout frameLayout2 = new FrameLayout(this);
        this.lhguygymgj = frameLayout2;
        frameLayout2.setLayoutParams(new LinearLayout.LayoutParams(1721, 533));
        this.lhguygymgj.setPadding(180, 50, 154, 118);
        linearLayout.addView(this.lhguygymgj);
        this.lhguygymgj.setBackgroundColor(Color.parseColor("#ec3911"));
        RatingBar ratingBar3 = new RatingBar(this);
        this.dhibfiupkv = ratingBar3;
        ratingBar3.setLayoutParams(new LinearLayout.LayoutParams(1441, 1899));
        this.dhibfiupkv.setPadding(119, 141, 50, 90);
        linearLayout.addView(this.dhibfiupkv);
        this.dhibfiupkv.setBackgroundColor(Color.parseColor("#355a8a"));
        Spinner spinner2 = new Spinner(this);
        this.fwaxpwofbo = spinner2;
        spinner2.setLayoutParams(new LinearLayout.LayoutParams(0, 1571));
        this.fwaxpwofbo.setPadding(104, 10, 189, 6);
        linearLayout.addView(this.fwaxpwofbo);
        this.fwaxpwofbo.setBackgroundColor(Color.parseColor("#5cd0ab"));
        CheckBox checkBox4 = new CheckBox(this);
        this.xwjmazfphd = checkBox4;
        checkBox4.setLayoutParams(new LinearLayout.LayoutParams(1073, 1739));
        this.xwjmazfphd.setPadding(138, 158, 81, 88);
        linearLayout.addView(this.xwjmazfphd);
        this.xwjmazfphd.setBackgroundColor(Color.parseColor("#ebcdaa"));
        CheckBox checkBox5 = new CheckBox(this);
        this.yfmzhfzhsj = checkBox5;
        checkBox5.setLayoutParams(new LinearLayout.LayoutParams(1380, 1199));
        this.yfmzhfzhsj.setPadding(118, 34, 43, 52);
        linearLayout.addView(this.yfmzhfzhsj);
        this.yfmzhfzhsj.setBackgroundColor(Color.parseColor("#579b44"));
        Spinner spinner3 = new Spinner(this);
        this.dprdmrzogi = spinner3;
        spinner3.setLayoutParams(new LinearLayout.LayoutParams(1613, 1810));
        this.dprdmrzogi.setPadding(196, 48, 22, 86);
        linearLayout.addView(this.dprdmrzogi);
        this.dprdmrzogi.setBackgroundColor(Color.parseColor("#e3383f"));
        ToggleButton toggleButton7 = new ToggleButton(this);
        this.sqqqgxhnfp = toggleButton7;
        toggleButton7.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.MotionType.TYPE_PATHMOTION_ARC, 1148));
        this.sqqqgxhnfp.setPadding(130, 163, 107, 199);
        linearLayout.addView(this.sqqqgxhnfp);
        this.sqqqgxhnfp.setBackgroundColor(Color.parseColor("#e5c3a1"));
        SeekBar seekBar4 = new SeekBar(this);
        this.iuqgucocek = seekBar4;
        seekBar4.setLayoutParams(new LinearLayout.LayoutParams(32, 1083));
        this.iuqgucocek.setPadding(184, 171, 100, 112);
        linearLayout.addView(this.iuqgucocek);
        this.iuqgucocek.setBackgroundColor(Color.parseColor("#504888"));
        TableLayout tableLayout3 = new TableLayout(this);
        this.broykvffnd = tableLayout3;
        tableLayout3.setLayoutParams(new LinearLayout.LayoutParams(237, 497));
        this.broykvffnd.setPadding(13, 98, 67, 110);
        linearLayout.addView(this.broykvffnd);
        this.broykvffnd.setBackgroundColor(Color.parseColor("#f0a984"));
        RadioButton radioButton4 = new RadioButton(this);
        this.hnksreizsj = radioButton4;
        radioButton4.setLayoutParams(new LinearLayout.LayoutParams(1222, 431));
        this.hnksreizsj.setPadding(131, 54, 100, 179);
        linearLayout.addView(this.hnksreizsj);
        this.hnksreizsj.setBackgroundColor(Color.parseColor("#b4118f"));
        ImageView imageView8 = new ImageView(this);
        this.ykhmgjigtk = imageView8;
        imageView8.setLayoutParams(new LinearLayout.LayoutParams(428, 436));
        this.ykhmgjigtk.setPadding(85, 171, 91, 191);
        linearLayout.addView(this.ykhmgjigtk);
        this.ykhmgjigtk.setBackgroundColor(Color.parseColor("#654fb2"));
        TextView textView8 = new TextView(this);
        this.etzvxirfaz = textView8;
        textView8.setLayoutParams(new LinearLayout.LayoutParams(1534, 1309));
        this.etzvxirfaz.setPadding(146, 12, 176, 25);
        linearLayout.addView(this.etzvxirfaz);
        this.etzvxirfaz.setBackgroundColor(Color.parseColor("#51bb05"));
        EditText editText5 = new EditText(this);
        this.ckyhumgavo = editText5;
        editText5.setLayoutParams(new LinearLayout.LayoutParams(683, BDLocation.TypeNetWorkLocation));
        this.ckyhumgavo.setPadding(170, 78, 191, 77);
        linearLayout.addView(this.ckyhumgavo);
        this.ckyhumgavo.setBackgroundColor(Color.parseColor("#3d3de0"));
        TableLayout tableLayout4 = new TableLayout(this);
        this.rqsderssgd = tableLayout4;
        tableLayout4.setLayoutParams(new LinearLayout.LayoutParams(1721, 193));
        this.rqsderssgd.setPadding(69, 17, 36, 50);
        linearLayout.addView(this.rqsderssgd);
        this.rqsderssgd.setBackgroundColor(Color.parseColor("#7f2f7b"));
        RatingBar ratingBar4 = new RatingBar(this);
        this.tuvobpffhp = ratingBar4;
        ratingBar4.setLayoutParams(new LinearLayout.LayoutParams(684, 338));
        this.tuvobpffhp.setPadding(44, 69, 43, 15);
        linearLayout.addView(this.tuvobpffhp);
        this.tuvobpffhp.setBackgroundColor(Color.parseColor("#dd63aa"));
        SeekBar seekBar5 = new SeekBar(this);
        this.dhryfluyzt = seekBar5;
        seekBar5.setLayoutParams(new LinearLayout.LayoutParams(922, 303));
        this.dhryfluyzt.setPadding(111, 189, 124, 123);
        linearLayout.addView(this.dhryfluyzt);
        this.dhryfluyzt.setBackgroundColor(Color.parseColor("#6ab49f"));
        RelativeLayout relativeLayout3 = new RelativeLayout(this);
        this.sdkufazosd = relativeLayout3;
        relativeLayout3.setLayoutParams(new LinearLayout.LayoutParams(306, 775));
        this.sdkufazosd.setPadding(86, 98, 117, 63);
        linearLayout.addView(this.sdkufazosd);
        this.sdkufazosd.setBackgroundColor(Color.parseColor("#a853ac"));
        ToggleButton toggleButton8 = new ToggleButton(this);
        this.ovgstmxmub = toggleButton8;
        toggleButton8.setLayoutParams(new LinearLayout.LayoutParams(1237, 456));
        this.ovgstmxmub.setPadding(76, 54, 105, 145);
        linearLayout.addView(this.ovgstmxmub);
        this.ovgstmxmub.setBackgroundColor(Color.parseColor("#16b771"));
        EditText editText6 = new EditText(this);
        this.uwadbyvpxz = editText6;
        editText6.setLayoutParams(new LinearLayout.LayoutParams(1444, 222));
        this.uwadbyvpxz.setPadding(78, 83, 62, 183);
        linearLayout.addView(this.uwadbyvpxz);
        this.uwadbyvpxz.setBackgroundColor(Color.parseColor("#68ab01"));
        ImageView imageView9 = new ImageView(this);
        this.lggacjyiev = imageView9;
        imageView9.setLayoutParams(new LinearLayout.LayoutParams(256, 147));
        this.lggacjyiev.setPadding(58, 40, 125, 125);
        linearLayout.addView(this.lggacjyiev);
        this.lggacjyiev.setBackgroundColor(Color.parseColor("#ab2239"));
        SeekBar seekBar6 = new SeekBar(this);
        this.atjtazoncc = seekBar6;
        seekBar6.setLayoutParams(new LinearLayout.LayoutParams(1705, 763));
        this.atjtazoncc.setPadding(163, 16, 186, 132);
        linearLayout.addView(this.atjtazoncc);
        this.atjtazoncc.setBackgroundColor(Color.parseColor("#763e01"));
        LinearLayout linearLayout5 = new LinearLayout(this);
        this.kdyeyqobkc = linearLayout5;
        linearLayout5.setLayoutParams(new LinearLayout.LayoutParams(1925, 499));
        this.kdyeyqobkc.setPadding(25, 0, 99, 80);
        linearLayout.addView(this.kdyeyqobkc);
        this.kdyeyqobkc.setBackgroundColor(Color.parseColor("#ac210b"));
        ViewFlipper viewFlipper2 = new ViewFlipper(this);
        this.bhjowujxub = viewFlipper2;
        viewFlipper2.setLayoutParams(new LinearLayout.LayoutParams(1738, 303));
        this.bhjowujxub.setPadding(70, 67, 108, 141);
        linearLayout.addView(this.bhjowujxub);
        this.bhjowujxub.setBackgroundColor(Color.parseColor("#dff9e4"));
        GridView gridView3 = new GridView(this);
        this.pexifdqhfy = gridView3;
        gridView3.setLayoutParams(new LinearLayout.LayoutParams(751, 438));
        this.pexifdqhfy.setPadding(132, 75, 136, 183);
        linearLayout.addView(this.pexifdqhfy);
        this.pexifdqhfy.setBackgroundColor(Color.parseColor("#55fc47"));
        SeekBar seekBar7 = new SeekBar(this);
        this.cvqoiyzmvu = seekBar7;
        seekBar7.setLayoutParams(new LinearLayout.LayoutParams(1892, 1763));
        this.cvqoiyzmvu.setPadding(98, 22, 84, 148);
        linearLayout.addView(this.cvqoiyzmvu);
        this.cvqoiyzmvu.setBackgroundColor(Color.parseColor("#88747e"));
        FrameLayout frameLayout3 = new FrameLayout(this);
        this.egigqszzdr = frameLayout3;
        frameLayout3.setLayoutParams(new LinearLayout.LayoutParams(1513, 1090));
        this.egigqszzdr.setPadding(190, 130, 45, 175);
        linearLayout.addView(this.egigqszzdr);
        this.egigqszzdr.setBackgroundColor(Color.parseColor("#03cfc6"));
        ToggleButton toggleButton9 = new ToggleButton(this);
        this.azvlyulhku = toggleButton9;
        toggleButton9.setLayoutParams(new LinearLayout.LayoutParams(68, 1885));
        this.azvlyulhku.setPadding(61, 135, 89, 74);
        linearLayout.addView(this.azvlyulhku);
        this.azvlyulhku.setBackgroundColor(Color.parseColor("#e5d207"));
        Spinner spinner4 = new Spinner(this);
        this.gywdxcjyvo = spinner4;
        spinner4.setLayoutParams(new LinearLayout.LayoutParams(339, 1049));
        this.gywdxcjyvo.setPadding(158, 104, 171, 144);
        linearLayout.addView(this.gywdxcjyvo);
        this.gywdxcjyvo.setBackgroundColor(Color.parseColor("#d84350"));
        LinearLayout linearLayout6 = new LinearLayout(this);
        this.lxxepqjsbg = linearLayout6;
        linearLayout6.setLayoutParams(new LinearLayout.LayoutParams(457, 360));
        this.lxxepqjsbg.setPadding(6, 53, 136, 77);
        linearLayout.addView(this.lxxepqjsbg);
        this.lxxepqjsbg.setBackgroundColor(Color.parseColor("#5b5602"));
        Spinner spinner5 = new Spinner(this);
        this.czzyndmgkt = spinner5;
        spinner5.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.MotionType.TYPE_ANIMATE_CIRCLEANGLE_TO, 1557));
        this.czzyndmgkt.setPadding(108, 32, 166, 116);
        linearLayout.addView(this.czzyndmgkt);
        this.czzyndmgkt.setBackgroundColor(Color.parseColor("#31aab8"));
        ScrollView scrollView5 = new ScrollView(this);
        this.bokiqdmnfy = scrollView5;
        scrollView5.setLayoutParams(new LinearLayout.LayoutParams(550, 1327));
        this.bokiqdmnfy.setPadding(29, 82, 11, 173);
        linearLayout.addView(this.bokiqdmnfy);
        this.bokiqdmnfy.setBackgroundColor(Color.parseColor("#38d3e2"));
        Spinner spinner6 = new Spinner(this);
        this.pbxaknnqft = spinner6;
        spinner6.setLayoutParams(new LinearLayout.LayoutParams(43, 619));
        this.pbxaknnqft.setPadding(83, 146, 43, 47);
        linearLayout.addView(this.pbxaknnqft);
        this.pbxaknnqft.setBackgroundColor(Color.parseColor("#0c8f9d"));
        RelativeLayout relativeLayout4 = new RelativeLayout(this);
        this.rsxacbuwte = relativeLayout4;
        relativeLayout4.setLayoutParams(new LinearLayout.LayoutParams(1774, 1761));
        this.rsxacbuwte.setPadding(31, 194, 99, 105);
        linearLayout.addView(this.rsxacbuwte);
        this.rsxacbuwte.setBackgroundColor(Color.parseColor("#f8cc42"));
        Spinner spinner7 = new Spinner(this);
        this.avxewfowgk = spinner7;
        spinner7.setLayoutParams(new LinearLayout.LayoutParams(1136, 1130));
        this.avxewfowgk.setPadding(190, 30, 171, 8);
        linearLayout.addView(this.avxewfowgk);
        this.avxewfowgk.setBackgroundColor(Color.parseColor("#b8790d"));
        CheckBox checkBox6 = new CheckBox(this);
        this.kznamddyvw = checkBox6;
        checkBox6.setLayoutParams(new LinearLayout.LayoutParams(1047, 716));
        this.kznamddyvw.setPadding(175, 137, 32, 77);
        linearLayout.addView(this.kznamddyvw);
        this.kznamddyvw.setBackgroundColor(Color.parseColor("#26dbff"));
        RadioButton radioButton5 = new RadioButton(this);
        this.tsgueyjjvt = radioButton5;
        radioButton5.setLayoutParams(new LinearLayout.LayoutParams(884, 12));
        this.tsgueyjjvt.setPadding(99, 110, 70, 157);
        linearLayout.addView(this.tsgueyjjvt);
        this.tsgueyjjvt.setBackgroundColor(Color.parseColor("#519620"));
        RadioButton radioButton6 = new RadioButton(this);
        this.zdamedvjxm = radioButton6;
        radioButton6.setLayoutParams(new LinearLayout.LayoutParams(8, 182));
        this.zdamedvjxm.setPadding(WebSocketProtocol.PAYLOAD_SHORT, 120, 92, 125);
        linearLayout.addView(this.zdamedvjxm);
        this.zdamedvjxm.setBackgroundColor(Color.parseColor("#d714cf"));
        ScrollView scrollView6 = new ScrollView(this);
        this.sqiauxryug = scrollView6;
        scrollView6.setLayoutParams(new LinearLayout.LayoutParams(1022, 1522));
        this.sqiauxryug.setPadding(195, 158, 178, 58);
        linearLayout.addView(this.sqiauxryug);
        this.sqiauxryug.setBackgroundColor(Color.parseColor("#f9cb9c"));
        Switch r24 = new Switch(this);
        this.cbtbcinkak = r24;
        r24.setLayoutParams(new LinearLayout.LayoutParams(940, 925));
        this.cbtbcinkak.setPadding(37, 95, 61, 26);
        linearLayout.addView(this.cbtbcinkak);
        this.cbtbcinkak.setBackgroundColor(Color.parseColor("#15c370"));
        CheckBox checkBox7 = new CheckBox(this);
        this.tsuwfynldr = checkBox7;
        checkBox7.setLayoutParams(new LinearLayout.LayoutParams(938, 1930));
        this.tsuwfynldr.setPadding(96, 86, 146, 41);
        linearLayout.addView(this.tsuwfynldr);
        this.tsuwfynldr.setBackgroundColor(Color.parseColor("#453d9e"));
        ImageView imageView10 = new ImageView(this);
        this.xhxghmhkmx = imageView10;
        imageView10.setLayoutParams(new LinearLayout.LayoutParams(253, 397));
        this.xhxghmhkmx.setPadding(7, 50, 32, 138);
        linearLayout.addView(this.xhxghmhkmx);
        this.xhxghmhkmx.setBackgroundColor(Color.parseColor("#e7448a"));
        Spinner spinner8 = new Spinner(this);
        this.qkvtunzrji = spinner8;
        spinner8.setLayoutParams(new LinearLayout.LayoutParams(341, 44));
        this.qkvtunzrji.setPadding(62, 61, 151, 33);
        linearLayout.addView(this.qkvtunzrji);
        this.qkvtunzrji.setBackgroundColor(Color.parseColor("#7f1c48"));
        ToggleButton toggleButton10 = new ToggleButton(this);
        this.fddrzgxsbx = toggleButton10;
        toggleButton10.setLayoutParams(new LinearLayout.LayoutParams(1434, 1641));
        this.fddrzgxsbx.setPadding(120, 111, 7, 51);
        linearLayout.addView(this.fddrzgxsbx);
        this.fddrzgxsbx.setBackgroundColor(Color.parseColor("#4430b5"));
        RelativeLayout relativeLayout5 = new RelativeLayout(this);
        this.mvwxstxsmd = relativeLayout5;
        relativeLayout5.setLayoutParams(new LinearLayout.LayoutParams(1997, 679));
        this.mvwxstxsmd.setPadding(108, 150, 44, 82);
        linearLayout.addView(this.mvwxstxsmd);
        this.mvwxstxsmd.setBackgroundColor(Color.parseColor("#5ffb44"));
        CheckBox checkBox8 = new CheckBox(this);
        this.ryawzfdtyd = checkBox8;
        checkBox8.setLayoutParams(new LinearLayout.LayoutParams(1218, 703));
        this.ryawzfdtyd.setPadding(145, 164, 196, 120);
        linearLayout.addView(this.ryawzfdtyd);
        this.ryawzfdtyd.setBackgroundColor(Color.parseColor("#a32054"));
        TimePicker timePicker5 = new TimePicker(this);
        this.tiqevkpwol = timePicker5;
        timePicker5.setLayoutParams(new LinearLayout.LayoutParams(850, 758));
        this.tiqevkpwol.setPadding(137, 70, 122, WebSocketProtocol.PAYLOAD_SHORT);
        linearLayout.addView(this.tiqevkpwol);
        this.tiqevkpwol.setBackgroundColor(Color.parseColor("#261b95"));
        LinearLayout linearLayout7 = new LinearLayout(this);
        this.sicendienu = linearLayout7;
        linearLayout7.setLayoutParams(new LinearLayout.LayoutParams(1030, 1255));
        this.sicendienu.setPadding(18, 173, 172, 168);
        linearLayout.addView(this.sicendienu);
        this.sicendienu.setBackgroundColor(Color.parseColor("#a67acc"));
        Switch r25 = new Switch(this);
        this.nludtlctmb = r25;
        r25.setLayoutParams(new LinearLayout.LayoutParams(1000, 1312));
        this.nludtlctmb.setPadding(192, 122, 128, 80);
        linearLayout.addView(this.nludtlctmb);
        this.nludtlctmb.setBackgroundColor(Color.parseColor("#c132a8"));
        RelativeLayout relativeLayout6 = new RelativeLayout(this);
        this.aknnhkivij = relativeLayout6;
        relativeLayout6.setLayoutParams(new LinearLayout.LayoutParams(972, 1203));
        this.aknnhkivij.setPadding(110, 106, 14, 100);
        linearLayout.addView(this.aknnhkivij);
        this.aknnhkivij.setBackgroundColor(Color.parseColor("#a32662"));
        Switch r26 = new Switch(this);
        this.igcleqwqyk = r26;
        r26.setLayoutParams(new LinearLayout.LayoutParams(580, 562));
        this.igcleqwqyk.setPadding(85, 4, 63, 71);
        linearLayout.addView(this.igcleqwqyk);
        this.igcleqwqyk.setBackgroundColor(Color.parseColor("#4fe384"));
        GridView gridView4 = new GridView(this);
        this.qehyivwkuq = gridView4;
        gridView4.setLayoutParams(new LinearLayout.LayoutParams(1496, 927));
        this.qehyivwkuq.setPadding(60, 76, 2, 184);
        linearLayout.addView(this.qehyivwkuq);
        this.qehyivwkuq.setBackgroundColor(Color.parseColor("#a29697"));
        RatingBar ratingBar5 = new RatingBar(this);
        this.ijdhpuljpy = ratingBar5;
        ratingBar5.setLayoutParams(new LinearLayout.LayoutParams(1195, 710));
        this.ijdhpuljpy.setPadding(173, 165, 190, 122);
        linearLayout.addView(this.ijdhpuljpy);
        this.ijdhpuljpy.setBackgroundColor(Color.parseColor("#20bdd8"));
        Switch r27 = new Switch(this);
        this.ypemgektpx = r27;
        r27.setLayoutParams(new LinearLayout.LayoutParams(1681, 1616));
        this.ypemgektpx.setPadding(57, BDLocation.TypeServerError, 67, 192);
        linearLayout.addView(this.ypemgektpx);
        this.ypemgektpx.setBackgroundColor(Color.parseColor("#879cd4"));
        CheckBox checkBox9 = new CheckBox(this);
        this.aubzxqbadl = checkBox9;
        checkBox9.setLayoutParams(new LinearLayout.LayoutParams(1143, 1278));
        this.aubzxqbadl.setPadding(130, 11, 67, 187);
        linearLayout.addView(this.aubzxqbadl);
        this.aubzxqbadl.setBackgroundColor(Color.parseColor("#e45bc3"));
        TableLayout tableLayout5 = new TableLayout(this);
        this.bblicveyup = tableLayout5;
        tableLayout5.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.CycleType.TYPE_ALPHA, 360));
        this.bblicveyup.setPadding(143, 111, 54, 60);
        linearLayout.addView(this.bblicveyup);
        this.bblicveyup.setBackgroundColor(Color.parseColor("#61e4df"));
        ToggleButton toggleButton11 = new ToggleButton(this);
        this.xgwkaecwig = toggleButton11;
        toggleButton11.setLayoutParams(new LinearLayout.LayoutParams(466, 1752));
        this.xgwkaecwig.setPadding(190, 35, 66, 159);
        linearLayout.addView(this.xgwkaecwig);
        this.xgwkaecwig.setBackgroundColor(Color.parseColor("#dc7b68"));
        RelativeLayout relativeLayout7 = new RelativeLayout(this);
        this.bqekwlbyye = relativeLayout7;
        relativeLayout7.setLayoutParams(new LinearLayout.LayoutParams(1256, 815));
        this.bqekwlbyye.setPadding(98, 151, 73, 43);
        linearLayout.addView(this.bqekwlbyye);
        this.bqekwlbyye.setBackgroundColor(Color.parseColor("#31f9d1"));
        LinearLayout linearLayout8 = new LinearLayout(this);
        this.oalgdablmb = linearLayout8;
        linearLayout8.setLayoutParams(new LinearLayout.LayoutParams(1321, 586));
        this.oalgdablmb.setPadding(44, 30, 148, 108);
        linearLayout.addView(this.oalgdablmb);
        this.oalgdablmb.setBackgroundColor(Color.parseColor("#15bef8"));
        EditText editText7 = new EditText(this);
        this.xqyrdzgmyh = editText7;
        editText7.setLayoutParams(new LinearLayout.LayoutParams(1421, 697));
        this.xqyrdzgmyh.setPadding(166, 84, 189, 33);
        linearLayout.addView(this.xqyrdzgmyh);
        this.xqyrdzgmyh.setBackgroundColor(Color.parseColor("#057ba7"));
        Button button3 = new Button(this);
        this.abhxjbwccj = button3;
        button3.setLayoutParams(new LinearLayout.LayoutParams(90, 1526));
        this.abhxjbwccj.setPadding(67, 95, 82, 80);
        linearLayout.addView(this.abhxjbwccj);
        this.abhxjbwccj.setBackgroundColor(Color.parseColor("#027820"));
        TableLayout tableLayout6 = new TableLayout(this);
        this.xphfczygbx = tableLayout6;
        tableLayout6.setLayoutParams(new LinearLayout.LayoutParams(1332, 806));
        this.xphfczygbx.setPadding(43, 117, 181, 19);
        linearLayout.addView(this.xphfczygbx);
        this.xphfczygbx.setBackgroundColor(Color.parseColor("#184b37"));
        TimePicker timePicker6 = new TimePicker(this);
        this.csbdnkmape = timePicker6;
        timePicker6.setLayoutParams(new LinearLayout.LayoutParams(39, 710));
        this.csbdnkmape.setPadding(107, 178, 176, 143);
        linearLayout.addView(this.csbdnkmape);
        this.csbdnkmape.setBackgroundColor(Color.parseColor("#b01430"));
        ToggleButton toggleButton12 = new ToggleButton(this);
        this.ulbplmyvou = toggleButton12;
        toggleButton12.setLayoutParams(new LinearLayout.LayoutParams(1661, 1099));
        this.ulbplmyvou.setPadding(66, 115, 181, 97);
        linearLayout.addView(this.ulbplmyvou);
        this.ulbplmyvou.setBackgroundColor(Color.parseColor("#5e3b69"));
        DatePicker datePicker4 = new DatePicker(this);
        this.amtypfzqer = datePicker4;
        datePicker4.setLayoutParams(new LinearLayout.LayoutParams(Contract.CMD_SET_VERSION.V1_2, 1775));
        this.amtypfzqer.setPadding(94, 133, 148, 52);
        linearLayout.addView(this.amtypfzqer);
        this.amtypfzqer.setBackgroundColor(Color.parseColor("#489e4d"));
        SeekBar seekBar8 = new SeekBar(this);
        this.vlavosowcf = seekBar8;
        seekBar8.setLayoutParams(new LinearLayout.LayoutParams(972, 620));
        this.vlavosowcf.setPadding(77, 76, 61, 50);
        linearLayout.addView(this.vlavosowcf);
        this.vlavosowcf.setBackgroundColor(Color.parseColor("#5ea7fc"));
        Button button4 = new Button(this);
        this.xccwydunei = button4;
        button4.setLayoutParams(new LinearLayout.LayoutParams(224, 1744));
        this.xccwydunei.setPadding(89, 129, 172, 93);
        linearLayout.addView(this.xccwydunei);
        this.xccwydunei.setBackgroundColor(Color.parseColor("#2ff549"));
        ProgressBar progressBar5 = new ProgressBar(this);
        this.paxtoitvqb = progressBar5;
        progressBar5.setLayoutParams(new LinearLayout.LayoutParams(823, 453));
        this.paxtoitvqb.setPadding(11, 75, 132, 185);
        linearLayout.addView(this.paxtoitvqb);
        this.paxtoitvqb.setBackgroundColor(Color.parseColor("#09e31d"));
        LinearLayout linearLayout9 = new LinearLayout(this);
        this.gzleqhtmcy = linearLayout9;
        linearLayout9.setLayoutParams(new LinearLayout.LayoutParams(582, 1138));
        this.gzleqhtmcy.setPadding(1, 56, 92, 34);
        linearLayout.addView(this.gzleqhtmcy);
        this.gzleqhtmcy.setBackgroundColor(Color.parseColor("#5b0f02"));
        ToggleButton toggleButton13 = new ToggleButton(this);
        this.hvqattbghz = toggleButton13;
        toggleButton13.setLayoutParams(new LinearLayout.LayoutParams(1781, 155));
        this.hvqattbghz.setPadding(187, 40, 86, 13);
        linearLayout.addView(this.hvqattbghz);
        this.hvqattbghz.setBackgroundColor(Color.parseColor("#9bc167"));
        ProgressBar progressBar6 = new ProgressBar(this);
        this.odmqskeqiz = progressBar6;
        progressBar6.setLayoutParams(new LinearLayout.LayoutParams(719, 825));
        this.odmqskeqiz.setPadding(55, 150, 118, 13);
        linearLayout.addView(this.odmqskeqiz);
        this.odmqskeqiz.setBackgroundColor(Color.parseColor("#fbcc15"));
        RelativeLayout relativeLayout8 = new RelativeLayout(this);
        this.pctuwmjfze = relativeLayout8;
        relativeLayout8.setLayoutParams(new LinearLayout.LayoutParams(1184, 1086));
        this.pctuwmjfze.setPadding(181, 117, 191, 131);
        linearLayout.addView(this.pctuwmjfze);
        this.pctuwmjfze.setBackgroundColor(Color.parseColor("#b90d70"));
        RelativeLayout relativeLayout9 = new RelativeLayout(this);
        this.uvizualgxi = relativeLayout9;
        relativeLayout9.setLayoutParams(new LinearLayout.LayoutParams(1317, 1696));
        this.uvizualgxi.setPadding(189, 171, 49, 89);
        linearLayout.addView(this.uvizualgxi);
        this.uvizualgxi.setBackgroundColor(Color.parseColor("#6a6c6d"));
        DatePicker datePicker5 = new DatePicker(this);
        this.klovlvytzu = datePicker5;
        datePicker5.setLayoutParams(new LinearLayout.LayoutParams(21, 1976));
        this.klovlvytzu.setPadding(69, 45, 78, 37);
        linearLayout.addView(this.klovlvytzu);
        this.klovlvytzu.setBackgroundColor(Color.parseColor("#319384"));
        TimePicker timePicker7 = new TimePicker(this);
        this.rgzjyhvtji = timePicker7;
        timePicker7.setLayoutParams(new LinearLayout.LayoutParams(1700, 1151));
        this.rgzjyhvtji.setPadding(BDLocation.TypeServerError, 198, 155, 158);
        linearLayout.addView(this.rgzjyhvtji);
        this.rgzjyhvtji.setBackgroundColor(Color.parseColor("#3c4fee"));
        SeekBar seekBar9 = new SeekBar(this);
        this.admbadenxw = seekBar9;
        seekBar9.setLayoutParams(new LinearLayout.LayoutParams(159, 333));
        this.admbadenxw.setPadding(111, 77, 179, 85);
        linearLayout.addView(this.admbadenxw);
        this.admbadenxw.setBackgroundColor(Color.parseColor("#993077"));
        Spinner spinner9 = new Spinner(this);
        this.jlohveifzd = spinner9;
        spinner9.setLayoutParams(new LinearLayout.LayoutParams(1916, 135));
        this.jlohveifzd.setPadding(99, 131, 95, 82);
        linearLayout.addView(this.jlohveifzd);
        this.jlohveifzd.setBackgroundColor(Color.parseColor("#e76774"));
        FrameLayout frameLayout4 = new FrameLayout(this);
        this.ojcheewehb = frameLayout4;
        frameLayout4.setLayoutParams(new LinearLayout.LayoutParams(1009, 1772));
        this.ojcheewehb.setPadding(156, 165, 186, 41);
        linearLayout.addView(this.ojcheewehb);
        this.ojcheewehb.setBackgroundColor(Color.parseColor("#33dafa"));
        LinearLayout linearLayout10 = new LinearLayout(this);
        this.ugwauftrlg = linearLayout10;
        linearLayout10.setLayoutParams(new LinearLayout.LayoutParams(348, 3));
        this.ugwauftrlg.setPadding(154, 196, 33, 88);
        linearLayout.addView(this.ugwauftrlg);
        this.ugwauftrlg.setBackgroundColor(Color.parseColor("#2ce561"));
        ViewFlipper viewFlipper3 = new ViewFlipper(this);
        this.lyjberawes = viewFlipper3;
        viewFlipper3.setLayoutParams(new LinearLayout.LayoutParams(1001, 651));
        this.lyjberawes.setPadding(181, 47, 159, 55);
        linearLayout.addView(this.lyjberawes);
        this.lyjberawes.setBackgroundColor(Color.parseColor("#fd11b8"));
        RelativeLayout relativeLayout10 = new RelativeLayout(this);
        this.vqxqessomy = relativeLayout10;
        relativeLayout10.setLayoutParams(new LinearLayout.LayoutParams(344, 343));
        this.vqxqessomy.setPadding(70, 170, 85, 180);
        linearLayout.addView(this.vqxqessomy);
        this.vqxqessomy.setBackgroundColor(Color.parseColor("#09035e"));
        ListView listView5 = new ListView(this);
        this.uobyytbymn = listView5;
        listView5.setLayoutParams(new LinearLayout.LayoutParams(1774, 221));
        this.uobyytbymn.setPadding(52, 118, 96, 193);
        linearLayout.addView(this.uobyytbymn);
        this.uobyytbymn.setBackgroundColor(Color.parseColor("#26f7dd"));
        TextView textView9 = new TextView(this);
        this.fbjdhusqef = textView9;
        textView9.setLayoutParams(new LinearLayout.LayoutParams(147, 291));
        this.fbjdhusqef.setPadding(154, 92, 84, 155);
        linearLayout.addView(this.fbjdhusqef);
        this.fbjdhusqef.setBackgroundColor(Color.parseColor("#b9d243"));
        ListView listView6 = new ListView(this);
        this.vtrttcbwlh = listView6;
        listView6.setLayoutParams(new LinearLayout.LayoutParams(1668, 910));
        this.vtrttcbwlh.setPadding(6, 166, 110, 40);
        linearLayout.addView(this.vtrttcbwlh);
        this.vtrttcbwlh.setBackgroundColor(Color.parseColor("#08328b"));
        Switch r28 = new Switch(this);
        this.llblvcjjer = r28;
        r28.setLayoutParams(new LinearLayout.LayoutParams(1254, 1216));
        this.llblvcjjer.setPadding(70, 157, 88, 197);
        linearLayout.addView(this.llblvcjjer);
        this.llblvcjjer.setBackgroundColor(Color.parseColor("#6e4036"));
        Button button5 = new Button(this);
        this.aeyekkmpel = button5;
        button5.setLayoutParams(new LinearLayout.LayoutParams(1811, 100));
        this.aeyekkmpel.setPadding(116, 1, 141, 59);
        linearLayout.addView(this.aeyekkmpel);
        this.aeyekkmpel.setBackgroundColor(Color.parseColor("#d5511b"));
        GridView gridView5 = new GridView(this);
        this.fxlflzxilw = gridView5;
        gridView5.setLayoutParams(new LinearLayout.LayoutParams(1960, 496));
        this.fxlflzxilw.setPadding(104, 88, 28, 5);
        linearLayout.addView(this.fxlflzxilw);
        this.fxlflzxilw.setBackgroundColor(Color.parseColor("#961c01"));
        RelativeLayout relativeLayout11 = new RelativeLayout(this);
        this.jaapwdptnm = relativeLayout11;
        relativeLayout11.setLayoutParams(new LinearLayout.LayoutParams(1140, 1007));
        this.jaapwdptnm.setPadding(173, 143, 152, 8);
        linearLayout.addView(this.jaapwdptnm);
        this.jaapwdptnm.setBackgroundColor(Color.parseColor("#0eede2"));
        FrameLayout frameLayout5 = new FrameLayout(this);
        this.qfotuohhfy = frameLayout5;
        frameLayout5.setLayoutParams(new LinearLayout.LayoutParams(741, 1249));
        this.qfotuohhfy.setPadding(21, 14, 181, 191);
        linearLayout.addView(this.qfotuohhfy);
        this.qfotuohhfy.setBackgroundColor(Color.parseColor("#f9099a"));
        DatePicker datePicker6 = new DatePicker(this);
        this.qppvdlziuw = datePicker6;
        datePicker6.setLayoutParams(new LinearLayout.LayoutParams(772, 729));
        this.qppvdlziuw.setPadding(182, 19, 135, 33);
        linearLayout.addView(this.qppvdlziuw);
        this.qppvdlziuw.setBackgroundColor(Color.parseColor("#d59112"));
        GridView gridView6 = new GridView(this);
        this.iczhvkrwvk = gridView6;
        gridView6.setLayoutParams(new LinearLayout.LayoutParams(1672, 1689));
        this.iczhvkrwvk.setPadding(15, 165, 116, 136);
        linearLayout.addView(this.iczhvkrwvk);
        this.iczhvkrwvk.setBackgroundColor(Color.parseColor("#bde13a"));
        Button button6 = new Button(this);
        this.eldpupoesh = button6;
        button6.setLayoutParams(new LinearLayout.LayoutParams(320, 1093));
        this.eldpupoesh.setPadding(52, 83, 10, 135);
        linearLayout.addView(this.eldpupoesh);
        this.eldpupoesh.setBackgroundColor(Color.parseColor("#f1e4c4"));
        Button button7 = new Button(this);
        this.hhtcysbkvp = button7;
        button7.setLayoutParams(new LinearLayout.LayoutParams(530, 586));
        this.hhtcysbkvp.setPadding(44, 177, 98, 16);
        linearLayout.addView(this.hhtcysbkvp);
        this.hhtcysbkvp.setBackgroundColor(Color.parseColor("#b71072"));
        ViewFlipper viewFlipper4 = new ViewFlipper(this);
        this.tmyuuhymdq = viewFlipper4;
        viewFlipper4.setLayoutParams(new LinearLayout.LayoutParams(RoomDatabase.MAX_BIND_PARAMETER_CNT, 225));
        this.tmyuuhymdq.setPadding(133, 7, 27, 0);
        linearLayout.addView(this.tmyuuhymdq);
        this.tmyuuhymdq.setBackgroundColor(Color.parseColor("#a554bc"));
        ListView listView7 = new ListView(this);
        this.uwsvuqnrdt = listView7;
        listView7.setLayoutParams(new LinearLayout.LayoutParams(993, 1629));
        this.uwsvuqnrdt.setPadding(110, 150, 131, 113);
        linearLayout.addView(this.uwsvuqnrdt);
        this.uwsvuqnrdt.setBackgroundColor(Color.parseColor("#83a0f3"));
        RelativeLayout relativeLayout12 = new RelativeLayout(this);
        this.aoxglekqzk = relativeLayout12;
        relativeLayout12.setLayoutParams(new LinearLayout.LayoutParams(1212, 1254));
        this.aoxglekqzk.setPadding(115, 143, 80, 115);
        linearLayout.addView(this.aoxglekqzk);
        this.aoxglekqzk.setBackgroundColor(Color.parseColor("#224e5d"));
        RatingBar ratingBar6 = new RatingBar(this);
        this.uxudxjywfv = ratingBar6;
        ratingBar6.setLayoutParams(new LinearLayout.LayoutParams(1977, 1081));
        this.uxudxjywfv.setPadding(134, 138, 181, 71);
        linearLayout.addView(this.uxudxjywfv);
        this.uxudxjywfv.setBackgroundColor(Color.parseColor("#d9dcf3"));
        FrameLayout frameLayout6 = new FrameLayout(this);
        this.mmimxstcfj = frameLayout6;
        frameLayout6.setLayoutParams(new LinearLayout.LayoutParams(386, 582));
        this.mmimxstcfj.setPadding(185, 88, 39, 129);
        linearLayout.addView(this.mmimxstcfj);
        this.mmimxstcfj.setBackgroundColor(Color.parseColor("#17807e"));
        LinearLayout linearLayout11 = new LinearLayout(this);
        this.unyolclhxd = linearLayout11;
        linearLayout11.setLayoutParams(new LinearLayout.LayoutParams(31, 1756));
        this.unyolclhxd.setPadding(16, 198, 62, 120);
        linearLayout.addView(this.unyolclhxd);
        this.unyolclhxd.setBackgroundColor(Color.parseColor("#eb8dd6"));
        ViewFlipper viewFlipper5 = new ViewFlipper(this);
        this.juuqbwvcdi = viewFlipper5;
        viewFlipper5.setLayoutParams(new LinearLayout.LayoutParams(1583, 1836));
        this.juuqbwvcdi.setPadding(52, 55, 193, 77);
        linearLayout.addView(this.juuqbwvcdi);
        this.juuqbwvcdi.setBackgroundColor(Color.parseColor("#e4c1c0"));
        GridView gridView7 = new GridView(this);
        this.apqudglwic = gridView7;
        gridView7.setLayoutParams(new LinearLayout.LayoutParams(1978, 1135));
        this.apqudglwic.setPadding(163, 132, 10, 69);
        linearLayout.addView(this.apqudglwic);
        this.apqudglwic.setBackgroundColor(Color.parseColor("#d85409"));
        ImageView imageView11 = new ImageView(this);
        this.dqbxquhpkv = imageView11;
        imageView11.setLayoutParams(new LinearLayout.LayoutParams(1178, 286));
        this.dqbxquhpkv.setPadding(12, 67, 40, 75);
        linearLayout.addView(this.dqbxquhpkv);
        this.dqbxquhpkv.setBackgroundColor(Color.parseColor("#5d2ea9"));
        FrameLayout frameLayout7 = new FrameLayout(this);
        this.lvbwntzbid = frameLayout7;
        frameLayout7.setLayoutParams(new LinearLayout.LayoutParams(1105, 150));
        this.lvbwntzbid.setPadding(103, 121, 91, 54);
        linearLayout.addView(this.lvbwntzbid);
        this.lvbwntzbid.setBackgroundColor(Color.parseColor("#fc5924"));
        ListView listView8 = new ListView(this);
        this.vvjdypweig = listView8;
        listView8.setLayoutParams(new LinearLayout.LayoutParams(1310, 172));
        this.vvjdypweig.setPadding(105, 197, 146, 51);
        linearLayout.addView(this.vvjdypweig);
        this.vvjdypweig.setBackgroundColor(Color.parseColor("#0ce9de"));
        ProgressBar progressBar7 = new ProgressBar(this);
        this.cosaekvgme = progressBar7;
        progressBar7.setLayoutParams(new LinearLayout.LayoutParams(1313, 124));
        this.cosaekvgme.setPadding(WebSocketProtocol.PAYLOAD_SHORT, 123, 152, 56);
        linearLayout.addView(this.cosaekvgme);
        this.cosaekvgme.setBackgroundColor(Color.parseColor("#553aa7"));
        TableLayout tableLayout7 = new TableLayout(this);
        this.hnnxzwomwl = tableLayout7;
        tableLayout7.setLayoutParams(new LinearLayout.LayoutParams(1317, 993));
        this.hnnxzwomwl.setPadding(183, 138, 36, 30);
        linearLayout.addView(this.hnnxzwomwl);
        this.hnnxzwomwl.setBackgroundColor(Color.parseColor("#c8576f"));
        CheckBox checkBox10 = new CheckBox(this);
        this.drqdjjrtfv = checkBox10;
        checkBox10.setLayoutParams(new LinearLayout.LayoutParams(1765, 1081));
        this.drqdjjrtfv.setPadding(59, 66, 191, 177);
        linearLayout.addView(this.drqdjjrtfv);
        this.drqdjjrtfv.setBackgroundColor(Color.parseColor("#520fd7"));
        SeekBar seekBar10 = new SeekBar(this);
        this.mgienqbnww = seekBar10;
        seekBar10.setLayoutParams(new LinearLayout.LayoutParams(1694, 1504));
        this.mgienqbnww.setPadding(179, 62, 80, 150);
        linearLayout.addView(this.mgienqbnww);
        this.mgienqbnww.setBackgroundColor(Color.parseColor("#b809e1"));
        ProgressBar progressBar8 = new ProgressBar(this);
        this.jzskqyqakp = progressBar8;
        progressBar8.setLayoutParams(new LinearLayout.LayoutParams(427, 1838));
        this.jzskqyqakp.setPadding(79, 106, 75, 1);
        linearLayout.addView(this.jzskqyqakp);
        this.jzskqyqakp.setBackgroundColor(Color.parseColor("#6f72b5"));
        ImageView imageView12 = new ImageView(this);
        this.ojvoybwgtb = imageView12;
        imageView12.setLayoutParams(new LinearLayout.LayoutParams(1400, 1030));
        this.ojvoybwgtb.setPadding(156, 1, 96, 9);
        linearLayout.addView(this.ojvoybwgtb);
        this.ojvoybwgtb.setBackgroundColor(Color.parseColor("#f8ad4b"));
        RatingBar ratingBar7 = new RatingBar(this);
        this.juybxqkplg = ratingBar7;
        ratingBar7.setLayoutParams(new LinearLayout.LayoutParams(1590, 1685));
        this.juybxqkplg.setPadding(135, 142, 112, 17);
        linearLayout.addView(this.juybxqkplg);
        this.juybxqkplg.setBackgroundColor(Color.parseColor("#8584fd"));
        ViewFlipper viewFlipper6 = new ViewFlipper(this);
        this.ybazllzabm = viewFlipper6;
        viewFlipper6.setLayoutParams(new LinearLayout.LayoutParams(949, 157));
        this.ybazllzabm.setPadding(172, 92, 9, 117);
        linearLayout.addView(this.ybazllzabm);
        this.ybazllzabm.setBackgroundColor(Color.parseColor("#fcebf5"));
        LinearLayout linearLayout12 = new LinearLayout(this);
        this.xlphcibdhv = linearLayout12;
        linearLayout12.setLayoutParams(new LinearLayout.LayoutParams(1479, 533));
        this.xlphcibdhv.setPadding(192, 149, 82, 134);
        linearLayout.addView(this.xlphcibdhv);
        this.xlphcibdhv.setBackgroundColor(Color.parseColor("#fb4cba"));
        FrameLayout frameLayout8 = new FrameLayout(this);
        this.mkgkzrngag = frameLayout8;
        frameLayout8.setLayoutParams(new LinearLayout.LayoutParams(1353, 54));
        this.mkgkzrngag.setPadding(197, 115, 18, 83);
        linearLayout.addView(this.mkgkzrngag);
        this.mkgkzrngag.setBackgroundColor(Color.parseColor("#2034f5"));
        ScrollView scrollView7 = new ScrollView(this);
        this.lqtnsmgyoz = scrollView7;
        scrollView7.setLayoutParams(new LinearLayout.LayoutParams(596, 427));
        this.lqtnsmgyoz.setPadding(4, 15, 195, 45);
        linearLayout.addView(this.lqtnsmgyoz);
        this.lqtnsmgyoz.setBackgroundColor(Color.parseColor("#98e5b5"));
        ListView listView9 = new ListView(this);
        this.fzfwskzbzu = listView9;
        listView9.setLayoutParams(new LinearLayout.LayoutParams(712, 333));
        this.fzfwskzbzu.setPadding(157, 36, 91, 103);
        linearLayout.addView(this.fzfwskzbzu);
        this.fzfwskzbzu.setBackgroundColor(Color.parseColor("#efccc7"));
        ToggleButton toggleButton14 = new ToggleButton(this);
        this.mipmkylyjr = toggleButton14;
        toggleButton14.setLayoutParams(new LinearLayout.LayoutParams(1682, 1633));
        this.mipmkylyjr.setPadding(194, 30, 194, 39);
        linearLayout.addView(this.mipmkylyjr);
        this.mipmkylyjr.setBackgroundColor(Color.parseColor("#bd4433"));
        DatePicker datePicker7 = new DatePicker(this);
        this.kkzcgxsely = datePicker7;
        datePicker7.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.PositionType.TYPE_CURVE_FIT, 775));
        this.kkzcgxsely.setPadding(115, 53, 55, 157);
        linearLayout.addView(this.kkzcgxsely);
        this.kkzcgxsely.setBackgroundColor(Color.parseColor("#3b9f1f"));
        RatingBar ratingBar8 = new RatingBar(this);
        this.aakvbwxkmy = ratingBar8;
        ratingBar8.setLayoutParams(new LinearLayout.LayoutParams(187, 665));
        this.aakvbwxkmy.setPadding(51, 16, 37, 38);
        linearLayout.addView(this.aakvbwxkmy);
        this.aakvbwxkmy.setBackgroundColor(Color.parseColor("#9097f9"));
        Button button8 = new Button(this);
        this.wdeffcjhzt = button8;
        button8.setLayoutParams(new LinearLayout.LayoutParams(622, 997));
        this.wdeffcjhzt.setPadding(96, 88, 195, 140);
        linearLayout.addView(this.wdeffcjhzt);
        this.wdeffcjhzt.setBackgroundColor(Color.parseColor("#b5af3c"));
        RatingBar ratingBar9 = new RatingBar(this);
        this.aemzjmbuqk = ratingBar9;
        ratingBar9.setLayoutParams(new LinearLayout.LayoutParams(1673, CodeUtils.DEFAULT_REQ_HEIGHT));
        this.aemzjmbuqk.setPadding(168, 75, 104, 13);
        linearLayout.addView(this.aemzjmbuqk);
        this.aemzjmbuqk.setBackgroundColor(Color.parseColor("#7bf743"));
        Button button9 = new Button(this);
        this.xelqsfaszq = button9;
        button9.setLayoutParams(new LinearLayout.LayoutParams(792, 577));
        this.xelqsfaszq.setPadding(39, 137, 53, 117);
        linearLayout.addView(this.xelqsfaszq);
        this.xelqsfaszq.setBackgroundColor(Color.parseColor("#d480d5"));
        Switch r29 = new Switch(this);
        this.efhkjstami = r29;
        r29.setLayoutParams(new LinearLayout.LayoutParams(1977, 750));
        this.efhkjstami.setPadding(46, 158, 100, 50);
        linearLayout.addView(this.efhkjstami);
        this.efhkjstami.setBackgroundColor(Color.parseColor("#c27ed1"));
        RadioButton radioButton7 = new RadioButton(this);
        this.uksfrarkng = radioButton7;
        radioButton7.setLayoutParams(new LinearLayout.LayoutParams(1866, 414));
        this.uksfrarkng.setPadding(182, 181, BDLocation.TypeServerError, 131);
        linearLayout.addView(this.uksfrarkng);
        this.uksfrarkng.setBackgroundColor(Color.parseColor("#4c31bd"));
        ListView listView10 = new ListView(this);
        this.hqtoqlxrpt = listView10;
        listView10.setLayoutParams(new LinearLayout.LayoutParams(9, 1172));
        this.hqtoqlxrpt.setPadding(186, 45, 179, 149);
        linearLayout.addView(this.hqtoqlxrpt);
        this.hqtoqlxrpt.setBackgroundColor(Color.parseColor("#70321e"));
        ScrollView scrollView8 = new ScrollView(this);
        this.wyrznlxhfn = scrollView8;
        scrollView8.setLayoutParams(new LinearLayout.LayoutParams(771, 1851));
        this.wyrznlxhfn.setPadding(75, 187, 186, 115);
        linearLayout.addView(this.wyrznlxhfn);
        this.wyrznlxhfn.setBackgroundColor(Color.parseColor("#b34665"));
        ViewFlipper viewFlipper7 = new ViewFlipper(this);
        this.iygzxhgkkv = viewFlipper7;
        viewFlipper7.setLayoutParams(new LinearLayout.LayoutParams(1723, 619));
        this.iygzxhgkkv.setPadding(WebSocketProtocol.PAYLOAD_SHORT, 180, 95, 17);
        linearLayout.addView(this.iygzxhgkkv);
        this.iygzxhgkkv.setBackgroundColor(Color.parseColor("#c8dbec"));
        CheckBox checkBox11 = new CheckBox(this);
        this.gcgyzqfrch = checkBox11;
        checkBox11.setLayoutParams(new LinearLayout.LayoutParams(932, 848));
        this.gcgyzqfrch.setPadding(64, 94, 19, 28);
        linearLayout.addView(this.gcgyzqfrch);
        this.gcgyzqfrch.setBackgroundColor(Color.parseColor("#a3fab5"));
        LinearLayout linearLayout13 = new LinearLayout(this);
        this.cjqhascwne = linearLayout13;
        linearLayout13.setLayoutParams(new LinearLayout.LayoutParams(961, 794));
        this.cjqhascwne.setPadding(10, 130, 174, 104);
        linearLayout.addView(this.cjqhascwne);
        this.cjqhascwne.setBackgroundColor(Color.parseColor("#cba634"));
        ListView listView11 = new ListView(this);
        this.xhpqnelmsm = listView11;
        listView11.setLayoutParams(new LinearLayout.LayoutParams(1361, 270));
        this.xhpqnelmsm.setPadding(105, 175, 58, 103);
        linearLayout.addView(this.xhpqnelmsm);
        this.xhpqnelmsm.setBackgroundColor(Color.parseColor("#f2586d"));
        CheckBox checkBox12 = new CheckBox(this);
        this.dtajxrvhqi = checkBox12;
        checkBox12.setLayoutParams(new LinearLayout.LayoutParams(544, 1759));
        this.dtajxrvhqi.setPadding(12, 22, 1, 178);
        linearLayout.addView(this.dtajxrvhqi);
        this.dtajxrvhqi.setBackgroundColor(Color.parseColor("#b2eb4f"));
        GridView gridView8 = new GridView(this);
        this.zgbqicqnka = gridView8;
        gridView8.setLayoutParams(new LinearLayout.LayoutParams(32, 801));
        this.zgbqicqnka.setPadding(89, 133, 190, 70);
        linearLayout.addView(this.zgbqicqnka);
        this.zgbqicqnka.setBackgroundColor(Color.parseColor("#db6759"));
        CheckBox checkBox13 = new CheckBox(this);
        this.begyysjjmw = checkBox13;
        checkBox13.setLayoutParams(new LinearLayout.LayoutParams(1022, 1763));
        this.begyysjjmw.setPadding(BDLocation.TypeServerDecryptError, 139, 184, 182);
        linearLayout.addView(this.begyysjjmw);
        this.begyysjjmw.setBackgroundColor(Color.parseColor("#6e369d"));
        RelativeLayout relativeLayout13 = new RelativeLayout(this);
        this.owqegevssf = relativeLayout13;
        relativeLayout13.setLayoutParams(new LinearLayout.LayoutParams(1976, 1056));
        this.owqegevssf.setPadding(153, 80, 11, 16);
        linearLayout.addView(this.owqegevssf);
        this.owqegevssf.setBackgroundColor(Color.parseColor("#caf716"));
        EditText editText8 = new EditText(this);
        this.ijxuetzpel = editText8;
        editText8.setLayoutParams(new LinearLayout.LayoutParams(1812, 953));
        this.ijxuetzpel.setPadding(84, 62, 57, 190);
        linearLayout.addView(this.ijxuetzpel);
        this.ijxuetzpel.setBackgroundColor(Color.parseColor("#413641"));
        Switch r210 = new Switch(this);
        this.chgaadkila = r210;
        r210.setLayoutParams(new LinearLayout.LayoutParams(564, 1993));
        this.chgaadkila.setPadding(114, 184, 13, 146);
        linearLayout.addView(this.chgaadkila);
        this.chgaadkila.setBackgroundColor(Color.parseColor("#460a3b"));
        ToggleButton toggleButton15 = new ToggleButton(this);
        this.cywkniudpl = toggleButton15;
        toggleButton15.setLayoutParams(new LinearLayout.LayoutParams(1357, 1374));
        this.cywkniudpl.setPadding(163, 13, 119, 85);
        linearLayout.addView(this.cywkniudpl);
        this.cywkniudpl.setBackgroundColor(Color.parseColor("#7b549c"));
        ImageView imageView13 = new ImageView(this);
        this.droflidmkx = imageView13;
        imageView13.setLayoutParams(new LinearLayout.LayoutParams(1966, 185));
        this.droflidmkx.setPadding(30, 113, 51, 93);
        linearLayout.addView(this.droflidmkx);
        this.droflidmkx.setBackgroundColor(Color.parseColor("#9aafec"));
        Spinner spinner10 = new Spinner(this);
        this.lkzimblenh = spinner10;
        spinner10.setLayoutParams(new LinearLayout.LayoutParams(181, 1193));
        this.lkzimblenh.setPadding(61, 153, 92, 130);
        linearLayout.addView(this.lkzimblenh);
        this.lkzimblenh.setBackgroundColor(Color.parseColor("#180b65"));
        SeekBar seekBar11 = new SeekBar(this);
        this.hknpturtod = seekBar11;
        seekBar11.setLayoutParams(new LinearLayout.LayoutParams(613, TypedValues.TransitionType.TYPE_INTERPOLATOR));
        this.hknpturtod.setPadding(27, 145, 141, 109);
        linearLayout.addView(this.hknpturtod);
        this.hknpturtod.setBackgroundColor(Color.parseColor("#6de811"));
        ProgressBar progressBar9 = new ProgressBar(this);
        this.uflflgfbzc = progressBar9;
        progressBar9.setLayoutParams(new LinearLayout.LayoutParams(955, 411));
        this.uflflgfbzc.setPadding(39, 76, 32, 54);
        linearLayout.addView(this.uflflgfbzc);
        this.uflflgfbzc.setBackgroundColor(Color.parseColor("#b6d1f0"));
        ProgressBar progressBar10 = new ProgressBar(this);
        this.obexcstzhh = progressBar10;
        progressBar10.setLayoutParams(new LinearLayout.LayoutParams(280, 1456));
        this.obexcstzhh.setPadding(113, 23, 55, 71);
        linearLayout.addView(this.obexcstzhh);
        this.obexcstzhh.setBackgroundColor(Color.parseColor("#79e714"));
        Switch r211 = new Switch(this);
        this.hxlolltazv = r211;
        r211.setLayoutParams(new LinearLayout.LayoutParams(481, 1871));
        this.hxlolltazv.setPadding(105, 98, 79, 24);
        linearLayout.addView(this.hxlolltazv);
        this.hxlolltazv.setBackgroundColor(Color.parseColor("#975c37"));
        GridView gridView9 = new GridView(this);
        this.ecfqbdijml = gridView9;
        gridView9.setLayoutParams(new LinearLayout.LayoutParams(1961, 1342));
        this.ecfqbdijml.setPadding(0, 12, 93, BDLocation.TypeNetWorkLocation);
        linearLayout.addView(this.ecfqbdijml);
        this.ecfqbdijml.setBackgroundColor(Color.parseColor("#c5e8ea"));
        TableLayout tableLayout8 = new TableLayout(this);
        this.amudaszhsl = tableLayout8;
        tableLayout8.setLayoutParams(new LinearLayout.LayoutParams(1079, 681));
        this.amudaszhsl.setPadding(158, 57, 152, 95);
        linearLayout.addView(this.amudaszhsl);
        this.amudaszhsl.setBackgroundColor(Color.parseColor("#7402ba"));
        ListView listView12 = new ListView(this);
        this.ktkemnnywy = listView12;
        listView12.setLayoutParams(new LinearLayout.LayoutParams(652, 77));
        this.ktkemnnywy.setPadding(43, 12, 85, 148);
        linearLayout.addView(this.ktkemnnywy);
        this.ktkemnnywy.setBackgroundColor(Color.parseColor("#c92e51"));
        RadioButton radioButton8 = new RadioButton(this);
        this.dmkljlgvfp = radioButton8;
        radioButton8.setLayoutParams(new LinearLayout.LayoutParams(180, 1001));
        this.dmkljlgvfp.setPadding(90, 36, 57, 199);
        linearLayout.addView(this.dmkljlgvfp);
        this.dmkljlgvfp.setBackgroundColor(Color.parseColor("#282448"));
        ScrollView scrollView9 = new ScrollView(this);
        this.dhsgwcsayw = scrollView9;
        scrollView9.setLayoutParams(new LinearLayout.LayoutParams(1093, 1465));
        this.dhsgwcsayw.setPadding(112, 100, BDLocation.TypeNetWorkLocation, 20);
        linearLayout.addView(this.dhsgwcsayw);
        this.dhsgwcsayw.setBackgroundColor(Color.parseColor("#95c978"));
        ProgressBar progressBar11 = new ProgressBar(this);
        this.mwhbfgzbcq = progressBar11;
        progressBar11.setLayoutParams(new LinearLayout.LayoutParams(PictureConfig.REQUEST_GO_SETTING, 759));
        this.mwhbfgzbcq.setPadding(59, 139, 37, 96);
        linearLayout.addView(this.mwhbfgzbcq);
        this.mwhbfgzbcq.setBackgroundColor(Color.parseColor("#3b8852"));
        ListView listView13 = new ListView(this);
        this.crovylsxxz = listView13;
        listView13.setLayoutParams(new LinearLayout.LayoutParams(1982, 1272));
        this.crovylsxxz.setPadding(86, 43, 10, 189);
        linearLayout.addView(this.crovylsxxz);
        this.crovylsxxz.setBackgroundColor(Color.parseColor("#3a0156"));
    }
}
