package com.smartapp.b.alndtaddqq;

import android.app.Activity;
import android.graphics.Color;
import android.os.Bundle;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.CheckBox;
import android.widget.DatePicker;
import android.widget.EditText;
import android.widget.FrameLayout;
import android.widget.GridView;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ListView;
import android.widget.ProgressBar;
import android.widget.RadioButton;
import android.widget.RatingBar;
import android.widget.RelativeLayout;
import android.widget.ScrollView;
import android.widget.SeekBar;
import android.widget.Spinner;
import android.widget.Switch;
import android.widget.TableLayout;
import android.widget.TextView;
import android.widget.TimePicker;
import android.widget.ToggleButton;
import android.widget.ViewFlipper;
import androidx.constraintlayout.core.motion.utils.TypedValues;
import androidx.core.view.PointerIconCompat;
import com.baidu.location.BDLocation;
import com.google.android.gms.common.ConnectionResult;
import com.haibin.calendarview.BuildConfig;
import com.luck.picture.lib.config.PictureConfig;
import com.realsil.sdk.core.bluetooth.connection.le.GattClient;

/* loaded from: classes3.dex */
public class XflqtxutoshActivity extends Activity {
    RatingBar aouasmzevk;
    Button atlmqjwgpg;
    TableLayout auvftjweir;
    TextView bgzirakgur;
    Spinner bjchevhhqf;
    CheckBox borcxfaqku;
    EditText bpbifjhavf;
    DatePicker cbzyabsjcq;
    ProgressBar cibtpxzwtj;
    ProgressBar cndevrefel;
    CheckBox cqouaxyuju;
    TimePicker ddvslsxusz;
    ViewFlipper dkavymlphp;
    RatingBar dmxmtyhosh;
    ImageView dnwedqlctc;
    ProgressBar dorifxsezh;
    ListView eclkwjwwbv;
    FrameLayout efppvjojni;
    TableLayout ffcwnprdzb;
    DatePicker fqjeysxzwm;
    Button gbkzmjfdse;
    ScrollView gtnqzvigjr;
    ImageView gylgznyrft;
    TextView hbgykjytpz;
    ScrollView hmtxndmpkl;
    EditText hxewcmlgsq;
    ViewFlipper ifrttmlgph;
    TextView iltrmssfvc;
    RelativeLayout isqomtzchv;
    TextView iujfewmqfi;
    Switch jdhmustkaz;
    SeekBar jdodbmfonh;
    SeekBar jhomztzjye;
    RelativeLayout jprfeztmtb;
    ImageView jytssqetme;
    ProgressBar kkypjkfwdi;
    Button kyrtscaelj;
    RelativeLayout lgnmoxcwkn;
    RadioButton lhfcfxxqju;
    EditText lhsbbjgloo;
    ToggleButton lpzohqllpr;
    ToggleButton mdrhbrhzah;
    CheckBox mgsywlrcfe;
    CheckBox mohgeweiti;
    RatingBar mtzpxzafrn;
    EditText mxfmhwsosa;
    ListView ngkyvhdvcc;
    EditText ogpnqzrfqi;
    TextView oojexeprwk;
    SeekBar ovwjvjlmmm;
    ListView oymfkwkgnq;
    Button pflgumnvkv;
    ImageView pposkhjbim;
    ProgressBar praompsiud;
    TimePicker pupuhwzokh;
    RadioButton pydqvuvtft;
    FrameLayout qzfxxdkljm;
    ViewFlipper rgvnleubkx;
    Spinner rhrftfvqxg;
    GridView rkpvmibkfs;
    LinearLayout sbztfpfybs;
    RelativeLayout svndeulufr;
    RatingBar swhahumxbo;
    RadioButton trtgomhwmi;
    GridView tvrwohnmlo;
    LinearLayout uhnybmhmbd;
    ImageView umiddnwdub;
    TableLayout xicvteurdh;
    FrameLayout xqsxtclwgc;
    GridView xtwlyusrrc;
    GridView xumgwgvuat;
    Spinner xuoclksmoi;
    CheckBox xvcfbjszho;
    ProgressBar yhiljaciwn;
    CheckBox ykgwsgpwmr;
    ToggleButton ykykilnoaz;
    EditText ylyopxhafp;
    ToggleButton yopnwdjpxm;
    TimePicker ytzdidaspe;
    Spinner ywgbntlxoa;
    GridView ywpmxjnopk;
    RelativeLayout zcnnptiaxm;

    @Override // android.app.Activity
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        LinearLayout linearLayout = new LinearLayout(this);
        setContentView(linearLayout);
        linearLayout.setLayoutParams(new ViewGroup.LayoutParams(-1, -1));
        linearLayout.setOrientation(1);
        linearLayout.setBackgroundColor(Color.parseColor("#06b37c"));
        RatingBar ratingBar = new RatingBar(this);
        this.dmxmtyhosh = ratingBar;
        ratingBar.setLayoutParams(new LinearLayout.LayoutParams(783, 1158));
        this.dmxmtyhosh.setPadding(12, 145, 30, BDLocation.TypeServerError);
        linearLayout.addView(this.dmxmtyhosh);
        this.dmxmtyhosh.setBackgroundColor(Color.parseColor("#a5d07f"));
        CheckBox checkBox = new CheckBox(this);
        this.ykgwsgpwmr = checkBox;
        checkBox.setLayoutParams(new LinearLayout.LayoutParams(972, 1728));
        this.ykgwsgpwmr.setPadding(153, BDLocation.TypeNetWorkLocation, 141, 25);
        linearLayout.addView(this.ykgwsgpwmr);
        this.ykgwsgpwmr.setBackgroundColor(Color.parseColor("#da5409"));
        RelativeLayout relativeLayout = new RelativeLayout(this);
        this.zcnnptiaxm = relativeLayout;
        relativeLayout.setLayoutParams(new LinearLayout.LayoutParams(712, 1479));
        this.zcnnptiaxm.setPadding(169, 190, 111, 51);
        linearLayout.addView(this.zcnnptiaxm);
        this.zcnnptiaxm.setBackgroundColor(Color.parseColor("#ea1cdf"));
        GridView gridView = new GridView(this);
        this.xtwlyusrrc = gridView;
        gridView.setLayoutParams(new LinearLayout.LayoutParams(1891, 1914));
        this.xtwlyusrrc.setPadding(92, 84, 78, 47);
        linearLayout.addView(this.xtwlyusrrc);
        this.xtwlyusrrc.setBackgroundColor(Color.parseColor("#cc8949"));
        ListView listView = new ListView(this);
        this.eclkwjwwbv = listView;
        listView.setLayoutParams(new LinearLayout.LayoutParams(1424, 1477));
        this.eclkwjwwbv.setPadding(169, 55, 146, 70);
        linearLayout.addView(this.eclkwjwwbv);
        this.eclkwjwwbv.setBackgroundColor(Color.parseColor("#e5c7fc"));
        EditText editText = new EditText(this);
        this.hxewcmlgsq = editText;
        editText.setLayoutParams(new LinearLayout.LayoutParams(1851, 989));
        this.hxewcmlgsq.setPadding(99, 114, 53, 3);
        linearLayout.addView(this.hxewcmlgsq);
        this.hxewcmlgsq.setBackgroundColor(Color.parseColor("#33b237"));
        LinearLayout linearLayout2 = new LinearLayout(this);
        this.uhnybmhmbd = linearLayout2;
        linearLayout2.setLayoutParams(new LinearLayout.LayoutParams(57, 874));
        this.uhnybmhmbd.setPadding(141, 55, 189, 17);
        linearLayout.addView(this.uhnybmhmbd);
        this.uhnybmhmbd.setBackgroundColor(Color.parseColor("#18303c"));
        EditText editText2 = new EditText(this);
        this.mxfmhwsosa = editText2;
        editText2.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.Custom.TYPE_STRING, 813));
        this.mxfmhwsosa.setPadding(199, 48, 120, 178);
        linearLayout.addView(this.mxfmhwsosa);
        this.mxfmhwsosa.setBackgroundColor(Color.parseColor("#2b0456"));
        TableLayout tableLayout = new TableLayout(this);
        this.xicvteurdh = tableLayout;
        tableLayout.setLayoutParams(new LinearLayout.LayoutParams(631, 311));
        this.xicvteurdh.setPadding(121, 145, 181, 69);
        linearLayout.addView(this.xicvteurdh);
        this.xicvteurdh.setBackgroundColor(Color.parseColor("#296bc1"));
        GridView gridView2 = new GridView(this);
        this.ywpmxjnopk = gridView2;
        gridView2.setLayoutParams(new LinearLayout.LayoutParams(1661, 954));
        this.ywpmxjnopk.setPadding(77, 112, 22, 66);
        linearLayout.addView(this.ywpmxjnopk);
        this.ywpmxjnopk.setBackgroundColor(Color.parseColor("#bde8c8"));
        ImageView imageView = new ImageView(this);
        this.umiddnwdub = imageView;
        imageView.setLayoutParams(new LinearLayout.LayoutParams(191, 1032));
        this.umiddnwdub.setPadding(66, BDLocation.TypeServerDecryptError, 131, 148);
        linearLayout.addView(this.umiddnwdub);
        this.umiddnwdub.setBackground(new Obzrtasiesq());
        ToggleButton toggleButton = new ToggleButton(this);
        this.ykykilnoaz = toggleButton;
        toggleButton.setLayoutParams(new LinearLayout.LayoutParams(523, 681));
        this.ykykilnoaz.setPadding(4, 139, 189, 152);
        linearLayout.addView(this.ykykilnoaz);
        this.ykykilnoaz.setBackgroundColor(Color.parseColor("#215e0e"));
        FrameLayout frameLayout = new FrameLayout(this);
        this.xqsxtclwgc = frameLayout;
        frameLayout.setLayoutParams(new LinearLayout.LayoutParams(975, 1100));
        this.xqsxtclwgc.setPadding(36, 107, 85, 157);
        linearLayout.addView(this.xqsxtclwgc);
        this.xqsxtclwgc.setBackgroundColor(Color.parseColor("#3fd7f4"));
        ProgressBar progressBar = new ProgressBar(this);
        this.cibtpxzwtj = progressBar;
        progressBar.setLayoutParams(new LinearLayout.LayoutParams(474, 0));
        this.cibtpxzwtj.setPadding(197, 189, 109, 166);
        linearLayout.addView(this.cibtpxzwtj);
        this.cibtpxzwtj.setBackgroundColor(Color.parseColor("#0e1e13"));
        RelativeLayout relativeLayout2 = new RelativeLayout(this);
        this.isqomtzchv = relativeLayout2;
        relativeLayout2.setLayoutParams(new LinearLayout.LayoutParams(332, 80));
        this.isqomtzchv.setPadding(130, 100, 40, 44);
        linearLayout.addView(this.isqomtzchv);
        this.isqomtzchv.setBackgroundColor(Color.parseColor("#d2da33"));
        Button button = new Button(this);
        this.gbkzmjfdse = button;
        button.setLayoutParams(new LinearLayout.LayoutParams(1259, 327));
        this.gbkzmjfdse.setPadding(125, 9, 41, 134);
        linearLayout.addView(this.gbkzmjfdse);
        this.gbkzmjfdse.setBackgroundColor(Color.parseColor("#3c13e5"));
        TextView textView = new TextView(this);
        this.bgzirakgur = textView;
        textView.setLayoutParams(new LinearLayout.LayoutParams(198, 1522));
        this.bgzirakgur.setPadding(43, 83, 55, 194);
        linearLayout.addView(this.bgzirakgur);
        this.bgzirakgur.setBackgroundColor(Color.parseColor("#7f1976"));
        EditText editText3 = new EditText(this);
        this.ogpnqzrfqi = editText3;
        editText3.setLayoutParams(new LinearLayout.LayoutParams(1709, 1513));
        this.ogpnqzrfqi.setPadding(24, 72, 187, 153);
        linearLayout.addView(this.ogpnqzrfqi);
        this.ogpnqzrfqi.setBackgroundColor(Color.parseColor("#6fbfe7"));
        ProgressBar progressBar2 = new ProgressBar(this);
        this.praompsiud = progressBar2;
        progressBar2.setLayoutParams(new LinearLayout.LayoutParams(1013, 97));
        this.praompsiud.setPadding(50, 12, 101, 22);
        linearLayout.addView(this.praompsiud);
        this.praompsiud.setBackgroundColor(Color.parseColor("#a25000"));
        RatingBar ratingBar2 = new RatingBar(this);
        this.swhahumxbo = ratingBar2;
        ratingBar2.setLayoutParams(new LinearLayout.LayoutParams(1104, 1464));
        this.swhahumxbo.setPadding(152, 173, 133, 43);
        linearLayout.addView(this.swhahumxbo);
        this.swhahumxbo.setBackgroundColor(Color.parseColor("#7271a1"));
        RelativeLayout relativeLayout3 = new RelativeLayout(this);
        this.lgnmoxcwkn = relativeLayout3;
        relativeLayout3.setLayoutParams(new LinearLayout.LayoutParams(369, 982));
        this.lgnmoxcwkn.setPadding(138, 175, 181, 113);
        linearLayout.addView(this.lgnmoxcwkn);
        this.lgnmoxcwkn.setBackgroundColor(Color.parseColor("#44d665"));
        ProgressBar progressBar3 = new ProgressBar(this);
        this.kkypjkfwdi = progressBar3;
        progressBar3.setLayoutParams(new LinearLayout.LayoutParams(21, 53));
        this.kkypjkfwdi.setPadding(164, 98, 36, 81);
        linearLayout.addView(this.kkypjkfwdi);
        this.kkypjkfwdi.setBackgroundColor(Color.parseColor("#c4dfe0"));
        TimePicker timePicker = new TimePicker(this);
        this.ytzdidaspe = timePicker;
        timePicker.setLayoutParams(new LinearLayout.LayoutParams(614, 1702));
        this.ytzdidaspe.setPadding(20, 181, 159, 196);
        linearLayout.addView(this.ytzdidaspe);
        this.ytzdidaspe.setBackgroundColor(Color.parseColor("#be1d12"));
        Spinner spinner = new Spinner(this);
        this.rhrftfvqxg = spinner;
        spinner.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.CycleType.TYPE_VISIBILITY, 168));
        this.rhrftfvqxg.setPadding(130, 22, 57, 123);
        linearLayout.addView(this.rhrftfvqxg);
        this.rhrftfvqxg.setBackgroundColor(Color.parseColor("#b75bc9"));
        CheckBox checkBox2 = new CheckBox(this);
        this.xvcfbjszho = checkBox2;
        checkBox2.setLayoutParams(new LinearLayout.LayoutParams(769, 1597));
        this.xvcfbjszho.setPadding(142, 48, 114, 108);
        linearLayout.addView(this.xvcfbjszho);
        this.xvcfbjszho.setBackgroundColor(Color.parseColor("#a8078f"));
        ToggleButton toggleButton2 = new ToggleButton(this);
        this.yopnwdjpxm = toggleButton2;
        toggleButton2.setLayoutParams(new LinearLayout.LayoutParams(668, 1586));
        this.yopnwdjpxm.setPadding(13, BDLocation.TypeCoarseLocation, 12, 10);
        linearLayout.addView(this.yopnwdjpxm);
        this.yopnwdjpxm.setBackgroundColor(Color.parseColor("#45b290"));
        Spinner spinner2 = new Spinner(this);
        this.ywgbntlxoa = spinner2;
        spinner2.setLayoutParams(new LinearLayout.LayoutParams(770, 1987));
        this.ywgbntlxoa.setPadding(134, 62, 185, 48);
        linearLayout.addView(this.ywgbntlxoa);
        this.ywgbntlxoa.setBackgroundColor(Color.parseColor("#724e20"));
        Switch r2 = new Switch(this);
        this.jdhmustkaz = r2;
        r2.setLayoutParams(new LinearLayout.LayoutParams(268, 801));
        this.jdhmustkaz.setPadding(89, 148, 184, 154);
        linearLayout.addView(this.jdhmustkaz);
        this.jdhmustkaz.setBackgroundColor(Color.parseColor("#5f0c97"));
        GridView gridView3 = new GridView(this);
        this.rkpvmibkfs = gridView3;
        gridView3.setLayoutParams(new LinearLayout.LayoutParams(1736, 505));
        this.rkpvmibkfs.setPadding(110, 13, 71, 136);
        linearLayout.addView(this.rkpvmibkfs);
        this.rkpvmibkfs.setBackgroundColor(Color.parseColor("#8dbaaa"));
        SeekBar seekBar = new SeekBar(this);
        this.jdodbmfonh = seekBar;
        seekBar.setLayoutParams(new LinearLayout.LayoutParams(603, 187));
        this.jdodbmfonh.setPadding(194, 140, 147, 144);
        linearLayout.addView(this.jdodbmfonh);
        this.jdodbmfonh.setBackgroundColor(Color.parseColor("#3c837a"));
        ListView listView2 = new ListView(this);
        this.ngkyvhdvcc = listView2;
        listView2.setLayoutParams(new LinearLayout.LayoutParams(344, 987));
        this.ngkyvhdvcc.setPadding(94, 70, 131, 78);
        linearLayout.addView(this.ngkyvhdvcc);
        this.ngkyvhdvcc.setBackgroundColor(Color.parseColor("#078b11"));
        DatePicker datePicker = new DatePicker(this);
        this.fqjeysxzwm = datePicker;
        datePicker.setLayoutParams(new LinearLayout.LayoutParams(1814, 1264));
        this.fqjeysxzwm.setPadding(153, 110, 11, 99);
        linearLayout.addView(this.fqjeysxzwm);
        this.fqjeysxzwm.setBackgroundColor(Color.parseColor("#c26ac7"));
        CheckBox checkBox3 = new CheckBox(this);
        this.borcxfaqku = checkBox3;
        checkBox3.setLayoutParams(new LinearLayout.LayoutParams(1735, 655));
        this.borcxfaqku.setPadding(198, 53, 29, 143);
        linearLayout.addView(this.borcxfaqku);
        this.borcxfaqku.setBackgroundColor(Color.parseColor("#0d6a4c"));
        RelativeLayout relativeLayout4 = new RelativeLayout(this);
        this.jprfeztmtb = relativeLayout4;
        relativeLayout4.setLayoutParams(new LinearLayout.LayoutParams(1628, 859));
        this.jprfeztmtb.setPadding(16, 3, 106, 101);
        linearLayout.addView(this.jprfeztmtb);
        this.jprfeztmtb.setBackgroundColor(Color.parseColor("#68cdda"));
        SeekBar seekBar2 = new SeekBar(this);
        this.ovwjvjlmmm = seekBar2;
        seekBar2.setLayoutParams(new LinearLayout.LayoutParams(796, 1459));
        this.ovwjvjlmmm.setPadding(17, 142, 71, 122);
        linearLayout.addView(this.ovwjvjlmmm);
        this.ovwjvjlmmm.setBackgroundColor(Color.parseColor("#d2487c"));
        ListView listView3 = new ListView(this);
        this.oymfkwkgnq = listView3;
        listView3.setLayoutParams(new LinearLayout.LayoutParams(1435, 1328));
        this.oymfkwkgnq.setPadding(98, 29, 147, 89);
        linearLayout.addView(this.oymfkwkgnq);
        this.oymfkwkgnq.setBackgroundColor(Color.parseColor("#e612f6"));
        CheckBox checkBox4 = new CheckBox(this);
        this.cqouaxyuju = checkBox4;
        checkBox4.setLayoutParams(new LinearLayout.LayoutParams(1216, 1169));
        this.cqouaxyuju.setPadding(92, 144, 85, 70);
        linearLayout.addView(this.cqouaxyuju);
        this.cqouaxyuju.setBackgroundColor(Color.parseColor("#d514b1"));
        ImageView imageView2 = new ImageView(this);
        this.jytssqetme = imageView2;
        imageView2.setLayoutParams(new LinearLayout.LayoutParams(391, PointerIconCompat.TYPE_GRABBING));
        this.jytssqetme.setPadding(148, 119, 84, 149);
        linearLayout.addView(this.jytssqetme);
        this.jytssqetme.setBackgroundColor(Color.parseColor("#d0ae84"));
        Button button2 = new Button(this);
        this.pflgumnvkv = button2;
        button2.setLayoutParams(new LinearLayout.LayoutParams(1550, 1805));
        this.pflgumnvkv.setPadding(45, PictureConfig.CHOOSE_REQUEST, 150, 159);
        linearLayout.addView(this.pflgumnvkv);
        this.pflgumnvkv.setBackgroundColor(Color.parseColor("#cef072"));
        CheckBox checkBox5 = new CheckBox(this);
        this.mgsywlrcfe = checkBox5;
        checkBox5.setLayoutParams(new LinearLayout.LayoutParams(1684, 1100));
        this.mgsywlrcfe.setPadding(87, 87, 59, 128);
        linearLayout.addView(this.mgsywlrcfe);
        this.mgsywlrcfe.setBackgroundColor(Color.parseColor("#6e199c"));
        RatingBar ratingBar3 = new RatingBar(this);
        this.aouasmzevk = ratingBar3;
        ratingBar3.setLayoutParams(new LinearLayout.LayoutParams(836, 1620));
        this.aouasmzevk.setPadding(133, 133, 154, BDLocation.TypeCoarseLocation);
        linearLayout.addView(this.aouasmzevk);
        this.aouasmzevk.setBackgroundColor(Color.parseColor("#fa98d9"));
        ImageView imageView3 = new ImageView(this);
        this.gylgznyrft = imageView3;
        imageView3.setLayoutParams(new LinearLayout.LayoutParams(1416, 1726));
        this.gylgznyrft.setPadding(76, 5, 9, 132);
        linearLayout.addView(this.gylgznyrft);
        this.gylgznyrft.setBackgroundColor(Color.parseColor("#847aba"));
        TimePicker timePicker2 = new TimePicker(this);
        this.ddvslsxusz = timePicker2;
        timePicker2.setLayoutParams(new LinearLayout.LayoutParams(976, 1629));
        this.ddvslsxusz.setPadding(175, 112, 179, 9);
        linearLayout.addView(this.ddvslsxusz);
        this.ddvslsxusz.setBackgroundColor(Color.parseColor("#5532b8"));
        ProgressBar progressBar4 = new ProgressBar(this);
        this.cndevrefel = progressBar4;
        progressBar4.setLayoutParams(new LinearLayout.LayoutParams(90, 560));
        this.cndevrefel.setPadding(79, 28, BDLocation.TypeServerDecryptError, 76);
        linearLayout.addView(this.cndevrefel);
        this.cndevrefel.setBackgroundColor(Color.parseColor("#c428bb"));
        TextView textView2 = new TextView(this);
        this.oojexeprwk = textView2;
        textView2.setLayoutParams(new LinearLayout.LayoutParams(1220, 555));
        this.oojexeprwk.setPadding(103, 116, 77, 104);
        linearLayout.addView(this.oojexeprwk);
        this.oojexeprwk.setBackgroundColor(Color.parseColor("#c0bce2"));
        ScrollView scrollView = new ScrollView(this);
        this.hmtxndmpkl = scrollView;
        scrollView.setLayoutParams(new LinearLayout.LayoutParams(454, 1608));
        this.hmtxndmpkl.setPadding(150, 198, 36, 158);
        linearLayout.addView(this.hmtxndmpkl);
        this.hmtxndmpkl.setBackgroundColor(Color.parseColor("#11d9da"));
        RadioButton radioButton = new RadioButton(this);
        this.lhfcfxxqju = radioButton;
        radioButton.setLayoutParams(new LinearLayout.LayoutParams(1044, 135));
        this.lhfcfxxqju.setPadding(37, BDLocation.TypeServerDecryptError, 134, 130);
        linearLayout.addView(this.lhfcfxxqju);
        this.lhfcfxxqju.setBackgroundColor(Color.parseColor("#095b3b"));
        ViewFlipper viewFlipper = new ViewFlipper(this);
        this.ifrttmlgph = viewFlipper;
        viewFlipper.setLayoutParams(new LinearLayout.LayoutParams(1399, 1511));
        this.ifrttmlgph.setPadding(16, 147, 172, 184);
        linearLayout.addView(this.ifrttmlgph);
        this.ifrttmlgph.setBackgroundColor(Color.parseColor("#b972d7"));
        TextView textView3 = new TextView(this);
        this.hbgykjytpz = textView3;
        textView3.setLayoutParams(new LinearLayout.LayoutParams(1891, 72));
        this.hbgykjytpz.setPadding(96, 133, 111, 83);
        linearLayout.addView(this.hbgykjytpz);
        this.hbgykjytpz.setBackgroundColor(Color.parseColor("#9923a9"));
        ProgressBar progressBar5 = new ProgressBar(this);
        this.yhiljaciwn = progressBar5;
        progressBar5.setLayoutParams(new LinearLayout.LayoutParams(ConnectionResult.DRIVE_EXTERNAL_STORAGE_REQUIRED, 344));
        this.yhiljaciwn.setPadding(46, 50, 13, 141);
        linearLayout.addView(this.yhiljaciwn);
        this.yhiljaciwn.setBackgroundColor(Color.parseColor("#2411ed"));
        TextView textView4 = new TextView(this);
        this.iltrmssfvc = textView4;
        textView4.setLayoutParams(new LinearLayout.LayoutParams(954, 206));
        this.iltrmssfvc.setPadding(124, 177, 178, 8);
        linearLayout.addView(this.iltrmssfvc);
        this.iltrmssfvc.setBackgroundColor(Color.parseColor("#74441c"));
        TextView textView5 = new TextView(this);
        this.iujfewmqfi = textView5;
        textView5.setLayoutParams(new LinearLayout.LayoutParams(564, 1630));
        this.iujfewmqfi.setPadding(110, 4, 193, 112);
        linearLayout.addView(this.iujfewmqfi);
        this.iujfewmqfi.setBackgroundColor(Color.parseColor("#883759"));
        Button button3 = new Button(this);
        this.kyrtscaelj = button3;
        button3.setLayoutParams(new LinearLayout.LayoutParams(722, 273));
        this.kyrtscaelj.setPadding(189, 54, 90, 194);
        linearLayout.addView(this.kyrtscaelj);
        this.kyrtscaelj.setBackgroundColor(Color.parseColor("#cad3cf"));
        SeekBar seekBar3 = new SeekBar(this);
        this.jhomztzjye = seekBar3;
        seekBar3.setLayoutParams(new LinearLayout.LayoutParams(1987, 1624));
        this.jhomztzjye.setPadding(155, 39, 102, 158);
        linearLayout.addView(this.jhomztzjye);
        this.jhomztzjye.setBackgroundColor(Color.parseColor("#af8839"));
        ToggleButton toggleButton3 = new ToggleButton(this);
        this.mdrhbrhzah = toggleButton3;
        toggleButton3.setLayoutParams(new LinearLayout.LayoutParams(1989, 1397));
        this.mdrhbrhzah.setPadding(106, 141, 151, 117);
        linearLayout.addView(this.mdrhbrhzah);
        this.mdrhbrhzah.setBackgroundColor(Color.parseColor("#25073e"));
        Spinner spinner3 = new Spinner(this);
        this.bjchevhhqf = spinner3;
        spinner3.setLayoutParams(new LinearLayout.LayoutParams(763, 1918));
        this.bjchevhhqf.setPadding(127, 47, 179, 46);
        linearLayout.addView(this.bjchevhhqf);
        this.bjchevhhqf.setBackgroundColor(Color.parseColor("#401563"));
        ProgressBar progressBar6 = new ProgressBar(this);
        this.dorifxsezh = progressBar6;
        progressBar6.setLayoutParams(new LinearLayout.LayoutParams(1842, 1656));
        this.dorifxsezh.setPadding(180, 16, 80, 75);
        linearLayout.addView(this.dorifxsezh);
        this.dorifxsezh.setBackgroundColor(Color.parseColor("#9a52c3"));
        CheckBox checkBox6 = new CheckBox(this);
        this.mohgeweiti = checkBox6;
        checkBox6.setLayoutParams(new LinearLayout.LayoutParams(1188, 228));
        this.mohgeweiti.setPadding(194, 5, 137, 11);
        linearLayout.addView(this.mohgeweiti);
        this.mohgeweiti.setBackgroundColor(Color.parseColor("#03a015"));
        TimePicker timePicker3 = new TimePicker(this);
        this.pupuhwzokh = timePicker3;
        timePicker3.setLayoutParams(new LinearLayout.LayoutParams(470, 833));
        this.pupuhwzokh.setPadding(164, 36, 199, 28);
        linearLayout.addView(this.pupuhwzokh);
        this.pupuhwzokh.setBackgroundColor(Color.parseColor("#bd4a81"));
        Button button4 = new Button(this);
        this.atlmqjwgpg = button4;
        button4.setLayoutParams(new LinearLayout.LayoutParams(1222, 485));
        this.atlmqjwgpg.setPadding(176, 83, 12, 119);
        linearLayout.addView(this.atlmqjwgpg);
        this.atlmqjwgpg.setBackgroundColor(Color.parseColor("#ce8a1b"));
        RadioButton radioButton2 = new RadioButton(this);
        this.pydqvuvtft = radioButton2;
        radioButton2.setLayoutParams(new LinearLayout.LayoutParams(1172, 897));
        this.pydqvuvtft.setPadding(25, 25, 81, 16);
        linearLayout.addView(this.pydqvuvtft);
        this.pydqvuvtft.setBackgroundColor(Color.parseColor("#204b39"));
        ViewFlipper viewFlipper2 = new ViewFlipper(this);
        this.dkavymlphp = viewFlipper2;
        viewFlipper2.setLayoutParams(new LinearLayout.LayoutParams(202, 104));
        this.dkavymlphp.setPadding(40, 108, 104, 169);
        linearLayout.addView(this.dkavymlphp);
        this.dkavymlphp.setBackgroundColor(Color.parseColor("#10834c"));
        RelativeLayout relativeLayout5 = new RelativeLayout(this);
        this.svndeulufr = relativeLayout5;
        relativeLayout5.setLayoutParams(new LinearLayout.LayoutParams(GattClient.STATE_READ_BATTERY_INFO, 1892));
        this.svndeulufr.setPadding(88, 87, 75, 169);
        linearLayout.addView(this.svndeulufr);
        this.svndeulufr.setBackgroundColor(Color.parseColor("#c87fdb"));
        ImageView imageView4 = new ImageView(this);
        this.dnwedqlctc = imageView4;
        imageView4.setLayoutParams(new LinearLayout.LayoutParams(349, 1517));
        this.dnwedqlctc.setPadding(176, 7, 156, 46);
        linearLayout.addView(this.dnwedqlctc);
        this.dnwedqlctc.setBackgroundColor(Color.parseColor("#deacd1"));
        ViewFlipper viewFlipper3 = new ViewFlipper(this);
        this.rgvnleubkx = viewFlipper3;
        viewFlipper3.setLayoutParams(new LinearLayout.LayoutParams(987, 1423));
        this.rgvnleubkx.setPadding(19, 154, 143, 157);
        linearLayout.addView(this.rgvnleubkx);
        this.rgvnleubkx.setBackgroundColor(Color.parseColor("#5d5a72"));
        RadioButton radioButton3 = new RadioButton(this);
        this.trtgomhwmi = radioButton3;
        radioButton3.setLayoutParams(new LinearLayout.LayoutParams(1629, 1375));
        this.trtgomhwmi.setPadding(11, PictureConfig.CHOOSE_REQUEST, 67, BDLocation.TypeServerDecryptError);
        linearLayout.addView(this.trtgomhwmi);
        this.trtgomhwmi.setBackgroundColor(Color.parseColor("#f0b06c"));
        GridView gridView4 = new GridView(this);
        this.xumgwgvuat = gridView4;
        gridView4.setLayoutParams(new LinearLayout.LayoutParams(320, 1041));
        this.xumgwgvuat.setPadding(132, 38, 158, 65);
        linearLayout.addView(this.xumgwgvuat);
        this.xumgwgvuat.setBackgroundColor(Color.parseColor("#11e8ed"));
        FrameLayout frameLayout2 = new FrameLayout(this);
        this.qzfxxdkljm = frameLayout2;
        frameLayout2.setLayoutParams(new LinearLayout.LayoutParams(346, 98));
        this.qzfxxdkljm.setPadding(180, 164, 182, 103);
        linearLayout.addView(this.qzfxxdkljm);
        this.qzfxxdkljm.setBackgroundColor(Color.parseColor("#f536a2"));
        EditText editText4 = new EditText(this);
        this.bpbifjhavf = editText4;
        editText4.setLayoutParams(new LinearLayout.LayoutParams(1671, 741));
        this.bpbifjhavf.setPadding(79, 178, 140, 197);
        linearLayout.addView(this.bpbifjhavf);
        this.bpbifjhavf.setBackgroundColor(Color.parseColor("#40dbda"));
        ToggleButton toggleButton4 = new ToggleButton(this);
        this.lpzohqllpr = toggleButton4;
        toggleButton4.setLayoutParams(new LinearLayout.LayoutParams(1751, 1605));
        this.lpzohqllpr.setPadding(96, 99, 108, 115);
        linearLayout.addView(this.lpzohqllpr);
        this.lpzohqllpr.setBackgroundColor(Color.parseColor("#a74539"));
        FrameLayout frameLayout3 = new FrameLayout(this);
        this.efppvjojni = frameLayout3;
        frameLayout3.setLayoutParams(new LinearLayout.LayoutParams(1275, 1454));
        this.efppvjojni.setPadding(172, 135, 96, 69);
        linearLayout.addView(this.efppvjojni);
        this.efppvjojni.setBackgroundColor(Color.parseColor("#ab5cd5"));
        DatePicker datePicker2 = new DatePicker(this);
        this.cbzyabsjcq = datePicker2;
        datePicker2.setLayoutParams(new LinearLayout.LayoutParams(1288, 32));
        this.cbzyabsjcq.setPadding(176, 135, 91, 157);
        linearLayout.addView(this.cbzyabsjcq);
        this.cbzyabsjcq.setBackgroundColor(Color.parseColor("#a595ee"));
        TableLayout tableLayout2 = new TableLayout(this);
        this.ffcwnprdzb = tableLayout2;
        tableLayout2.setLayoutParams(new LinearLayout.LayoutParams(1322, 1305));
        this.ffcwnprdzb.setPadding(139, 120, 146, 108);
        linearLayout.addView(this.ffcwnprdzb);
        this.ffcwnprdzb.setBackgroundColor(Color.parseColor("#f3df57"));
        ImageView imageView5 = new ImageView(this);
        this.pposkhjbim = imageView5;
        imageView5.setLayoutParams(new LinearLayout.LayoutParams(1026, 357));
        this.pposkhjbim.setPadding(53, 153, 197, 46);
        linearLayout.addView(this.pposkhjbim);
        this.pposkhjbim.setBackgroundColor(Color.parseColor("#eb69b2"));
        EditText editText5 = new EditText(this);
        this.lhsbbjgloo = editText5;
        editText5.setLayoutParams(new LinearLayout.LayoutParams(BuildConfig.VERSION_CODE, 876));
        this.lhsbbjgloo.setPadding(38, 74, 148, 18);
        linearLayout.addView(this.lhsbbjgloo);
        this.lhsbbjgloo.setBackgroundColor(Color.parseColor("#692b38"));
        GridView gridView5 = new GridView(this);
        this.tvrwohnmlo = gridView5;
        gridView5.setLayoutParams(new LinearLayout.LayoutParams(206, 657));
        this.tvrwohnmlo.setPadding(171, 66, 172, 131);
        linearLayout.addView(this.tvrwohnmlo);
        this.tvrwohnmlo.setBackgroundColor(Color.parseColor("#86fe3c"));
        ScrollView scrollView2 = new ScrollView(this);
        this.gtnqzvigjr = scrollView2;
        scrollView2.setLayoutParams(new LinearLayout.LayoutParams(1303, 1739));
        this.gtnqzvigjr.setPadding(115, 68, 1, 86);
        linearLayout.addView(this.gtnqzvigjr);
        this.gtnqzvigjr.setBackgroundColor(Color.parseColor("#963228"));
        EditText editText6 = new EditText(this);
        this.ylyopxhafp = editText6;
        editText6.setLayoutParams(new LinearLayout.LayoutParams(807, 74));
        this.ylyopxhafp.setPadding(8, 134, 119, 192);
        linearLayout.addView(this.ylyopxhafp);
        this.ylyopxhafp.setBackgroundColor(Color.parseColor("#d52422"));
        RatingBar ratingBar4 = new RatingBar(this);
        this.mtzpxzafrn = ratingBar4;
        ratingBar4.setLayoutParams(new LinearLayout.LayoutParams(264, 113));
        this.mtzpxzafrn.setPadding(168, 94, 137, 147);
        linearLayout.addView(this.mtzpxzafrn);
        this.mtzpxzafrn.setBackgroundColor(Color.parseColor("#d17319"));
        LinearLayout linearLayout3 = new LinearLayout(this);
        this.sbztfpfybs = linearLayout3;
        linearLayout3.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.Custom.TYPE_BOOLEAN, 370));
        this.sbztfpfybs.setPadding(107, 75, 68, 133);
        linearLayout.addView(this.sbztfpfybs);
        this.sbztfpfybs.setBackgroundColor(Color.parseColor("#3556f5"));
        TableLayout tableLayout3 = new TableLayout(this);
        this.auvftjweir = tableLayout3;
        tableLayout3.setLayoutParams(new LinearLayout.LayoutParams(PointerIconCompat.TYPE_GRABBING, 818));
        this.auvftjweir.setPadding(190, 29, 36, 134);
        linearLayout.addView(this.auvftjweir);
        this.auvftjweir.setBackgroundColor(Color.parseColor("#2df445"));
        Spinner spinner4 = new Spinner(this);
        this.xuoclksmoi = spinner4;
        spinner4.setLayoutParams(new LinearLayout.LayoutParams(1599, 513));
        this.xuoclksmoi.setPadding(13, 194, 84, 132);
        linearLayout.addView(this.xuoclksmoi);
        this.xuoclksmoi.setBackgroundColor(Color.parseColor("#52d576"));
    }
}
