package com.device.watch.com.device.watch.azqrvjzmai;

import android.app.Activity;
import android.graphics.Color;
import android.os.Bundle;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.CheckBox;
import android.widget.DatePicker;
import android.widget.EditText;
import android.widget.FrameLayout;
import android.widget.GridView;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ListView;
import android.widget.ProgressBar;
import android.widget.RadioButton;
import android.widget.RatingBar;
import android.widget.RelativeLayout;
import android.widget.ScrollView;
import android.widget.SeekBar;
import android.widget.Spinner;
import android.widget.Switch;
import android.widget.TableLayout;
import android.widget.TextView;
import android.widget.TimePicker;
import android.widget.ToggleButton;
import android.widget.ViewFlipper;
import androidx.constraintlayout.core.motion.utils.TypedValues;
import androidx.core.app.FrameMetricsAggregator;
import androidx.core.view.PointerIconCompat;
import com.baidu.location.BDLocation;
import com.luck.picture.lib.config.PictureConfig;
import com.realsil.sdk.bbpro.core.protocol.Contract;
import com.realsil.sdk.core.bluetooth.connection.le.GattClient;
import okhttp3.internal.ws.WebSocketProtocol;

/* loaded from: classes.dex */
public class DnwakdfqmdvActivity extends Activity {
    TableLayout aonjbipzxw;
    Switch ayevcmfuqs;
    ListView banhdxlooi;
    Switch bbxtjwnxia;
    ProgressBar bcioxbmfxa;
    Switch bdcrlursel;
    Button boqlzfyasw;
    GridView bulodpicuc;
    TableLayout cagfdlstdk;
    ToggleButton capaouprkh;
    ListView cawixoxlxb;
    GridView csefdxulvq;
    Button ctcfrrapwm;
    TimePicker declbfgihv;
    RelativeLayout dqyxlsiika;
    Button dxsqzipxbk;
    Button egzdfghutu;
    ListView ekddpytthk;
    Button euwqurmcne;
    GridView evbyswieyl;
    ImageView ewqfdrebms;
    TableLayout fagfniikwg;
    ScrollView fgrbjdbkiz;
    GridView fheddpnjyf;
    ViewFlipper frxbsnbsmw;
    ListView fzolbbvksx;
    ImageView gdeuauxuwq;
    RelativeLayout gkczxrktlg;
    RadioButton gkmeaxtybm;
    CheckBox gnwufdckan;
    ImageView guspvbsphw;
    EditText hlfdenstig;
    Switch hncrrmrivy;
    LinearLayout hrqqqjcuox;
    SeekBar htfqraocex;
    RelativeLayout htvcfahlos;
    TimePicker hxlutewboe;
    FrameLayout hxoxfzwqvb;
    RatingBar hyhnokdlpm;
    RelativeLayout imvqadgkky;
    RatingBar iniwahiiea;
    EditText inznwstgcv;
    ListView iubozitniv;
    CheckBox ivcgiaoyul;
    Button ivxgqcjdkf;
    TableLayout ixiwsnluyh;
    ViewFlipper iygrlpzkvs;
    RatingBar jdjohpopmn;
    TimePicker jggkuhcumi;
    TextView jkeehkzjez;
    ImageView jqbwhyporf;
    LinearLayout juxneumuqp;
    RatingBar kgcsqlumto;
    RadioButton khmqluakop;
    RelativeLayout khtnkufmrb;
    TimePicker kkxhxbodrw;
    TextView klmxdtodkc;
    EditText klyrngskoh;
    FrameLayout knwudooaam;
    RadioButton kontfgaeem;
    TextView ktsqfxmiac;
    TableLayout kvterlecgm;
    ProgressBar lbacilwrjl;
    TimePicker lnqqyztkkr;
    SeekBar lnzgzmipoo;
    TableLayout lssitdvonm;
    ImageView lzyawjfcvi;
    CheckBox mchcthotuc;
    RadioButton mcizjnjuar;
    EditText miigjyawwi;
    ListView mlywqqvhjm;
    ViewFlipper myklwiyrqk;
    ListView nhgpgxxvme;
    RelativeLayout njnctgyvtu;
    LinearLayout obcvakrkyb;
    Button ogteizawth;
    LinearLayout ohdakvgxuw;
    ToggleButton ojmwdimopc;
    TimePicker oodnztgsoo;
    ProgressBar pjxngosgdk;
    GridView pmkcvosdsk;
    GridView pyjsuwguqf;
    Button pzznbexkxv;
    GridView qkrgjkbnae;
    EditText qmhmjzxoic;
    Button rbggfbsffm;
    ToggleButton rkewmuftsd;
    ToggleButton rkfaegsfqj;
    SeekBar rlsvapvmpk;
    Spinner rmusankmds;
    ProgressBar scetacqswy;
    Spinner scnxsahzjd;
    ListView sqsmpvordc;
    ListView timbhhjojz;
    Button tltimqitrs;
    ScrollView tmtijwatcr;
    ScrollView toiytohjlf;
    GridView trkvgmawhs;
    GridView uehhckmzcq;
    CheckBox upsiwlnbpn;
    RadioButton usxqpbsawf;
    LinearLayout uwayzpnrqx;
    DatePicker uwfmnqpdqe;
    TableLayout vbddziairr;
    ProgressBar vcczhrzwpe;
    TimePicker vfiyalxbov;
    FrameLayout vkgklmjfsf;
    GridView vllcsiczqa;
    RatingBar vngtcltmpn;
    GridView vtvpjpehal;
    EditText vuyhllhbcc;
    ViewFlipper vztjcankzf;
    ToggleButton wabgcafhol;
    TableLayout wmzjzdujxu;
    CheckBox wnzedtgqaz;
    ListView wpddqqrjwx;
    TextView wuyulckphp;
    ImageView wyauargurf;
    ListView wzwdqwtbft;
    RelativeLayout xhcbjihxgr;
    GridView xhylbnyxsb;
    TableLayout xkraapzkoe;
    Button xnxwwcxewg;
    CheckBox yafodzjefq;
    DatePicker ybjhzozauq;
    EditText yeqntqomoj;
    Button yfijxpyesk;
    Spinner yiswaqxvbp;
    ViewFlipper ymhgtecagc;
    RatingBar yysuegadpc;
    LinearLayout zcdudvadih;
    ScrollView zoaipoufgs;
    TimePicker zpcleenzcm;
    FrameLayout zqzadukxhs;
    EditText zzxjbjlbbc;

    @Override // android.app.Activity
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        LinearLayout linearLayout = new LinearLayout(this);
        setContentView(linearLayout);
        linearLayout.setLayoutParams(new ViewGroup.LayoutParams(-1, -1));
        linearLayout.setOrientation(1);
        linearLayout.setBackgroundColor(Color.parseColor("#15140a"));
        RatingBar ratingBar = new RatingBar(this);
        this.jdjohpopmn = ratingBar;
        ratingBar.setLayoutParams(new LinearLayout.LayoutParams(1153, 1966));
        this.jdjohpopmn.setPadding(20, 142, 76, 16);
        linearLayout.addView(this.jdjohpopmn);
        this.jdjohpopmn.setBackgroundColor(Color.parseColor("#b897e6"));
        EditText editText = new EditText(this);
        this.hlfdenstig = editText;
        editText.setLayoutParams(new LinearLayout.LayoutParams(FrameMetricsAggregator.EVERY_DURATION, 1625));
        this.hlfdenstig.setPadding(124, 104, 136, 117);
        linearLayout.addView(this.hlfdenstig);
        this.hlfdenstig.setBackgroundColor(Color.parseColor("#7d41d6"));
        GridView gridView = new GridView(this);
        this.vtvpjpehal = gridView;
        gridView.setLayoutParams(new LinearLayout.LayoutParams(1070, 632));
        this.vtvpjpehal.setPadding(61, 19, 147, 156);
        linearLayout.addView(this.vtvpjpehal);
        this.vtvpjpehal.setBackgroundColor(Color.parseColor("#01ad01"));
        RadioButton radioButton = new RadioButton(this);
        this.mcizjnjuar = radioButton;
        radioButton.setLayoutParams(new LinearLayout.LayoutParams(1730, 1614));
        this.mcizjnjuar.setPadding(57, 148, 152, 132);
        linearLayout.addView(this.mcizjnjuar);
        this.mcizjnjuar.setBackgroundColor(Color.parseColor("#3a1871"));
        CheckBox checkBox = new CheckBox(this);
        this.mchcthotuc = checkBox;
        checkBox.setLayoutParams(new LinearLayout.LayoutParams(1385, 579));
        this.mchcthotuc.setPadding(115, 187, 45, 43);
        linearLayout.addView(this.mchcthotuc);
        this.mchcthotuc.setBackgroundColor(Color.parseColor("#99abd7"));
        Button button = new Button(this);
        this.tltimqitrs = button;
        button.setLayoutParams(new LinearLayout.LayoutParams(461, 1220));
        this.tltimqitrs.setPadding(91, 8, 179, 159);
        linearLayout.addView(this.tltimqitrs);
        this.tltimqitrs.setBackgroundColor(Color.parseColor("#6e49ac"));
        RelativeLayout relativeLayout = new RelativeLayout(this);
        this.htvcfahlos = relativeLayout;
        relativeLayout.setLayoutParams(new LinearLayout.LayoutParams(1917, 239));
        this.htvcfahlos.setPadding(28, 91, PictureConfig.CHOOSE_REQUEST, 151);
        linearLayout.addView(this.htvcfahlos);
        this.htvcfahlos.setBackgroundColor(Color.parseColor("#fc09aa"));
        ToggleButton toggleButton = new ToggleButton(this);
        this.ojmwdimopc = toggleButton;
        toggleButton.setLayoutParams(new LinearLayout.LayoutParams(1572, 1922));
        this.ojmwdimopc.setPadding(196, 15, 106, 123);
        linearLayout.addView(this.ojmwdimopc);
        this.ojmwdimopc.setBackgroundColor(Color.parseColor("#175c4d"));
        ProgressBar progressBar = new ProgressBar(this);
        this.lbacilwrjl = progressBar;
        progressBar.setLayoutParams(new LinearLayout.LayoutParams(650, 7));
        this.lbacilwrjl.setPadding(18, 76, 128, 159);
        linearLayout.addView(this.lbacilwrjl);
        this.lbacilwrjl.setBackgroundColor(Color.parseColor("#8e4028"));
        RelativeLayout relativeLayout2 = new RelativeLayout(this);
        this.imvqadgkky = relativeLayout2;
        relativeLayout2.setLayoutParams(new LinearLayout.LayoutParams(767, 1142));
        this.imvqadgkky.setPadding(102, 38, 192, 31);
        linearLayout.addView(this.imvqadgkky);
        this.imvqadgkky.setBackgroundColor(Color.parseColor("#df4e46"));
        CheckBox checkBox2 = new CheckBox(this);
        this.yafodzjefq = checkBox2;
        checkBox2.setLayoutParams(new LinearLayout.LayoutParams(1839, 47));
        this.yafodzjefq.setPadding(58, 103, 155, 23);
        linearLayout.addView(this.yafodzjefq);
        this.yafodzjefq.setBackgroundColor(Color.parseColor("#ba7380"));
        ViewFlipper viewFlipper = new ViewFlipper(this);
        this.vztjcankzf = viewFlipper;
        viewFlipper.setLayoutParams(new LinearLayout.LayoutParams(519, 26));
        this.vztjcankzf.setPadding(190, 141, 63, 83);
        linearLayout.addView(this.vztjcankzf);
        this.vztjcankzf.setBackground(new Kcznfqiqycu());
        ToggleButton toggleButton2 = new ToggleButton(this);
        this.capaouprkh = toggleButton2;
        toggleButton2.setLayoutParams(new LinearLayout.LayoutParams(1759, 1854));
        this.capaouprkh.setPadding(143, 0, 187, 51);
        linearLayout.addView(this.capaouprkh);
        this.capaouprkh.setBackgroundColor(Color.parseColor("#3323f8"));
        Button button2 = new Button(this);
        this.yfijxpyesk = button2;
        button2.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.CycleType.TYPE_WAVE_OFFSET, 1802));
        this.yfijxpyesk.setPadding(122, 193, 5, 54);
        linearLayout.addView(this.yfijxpyesk);
        this.yfijxpyesk.setBackgroundColor(Color.parseColor("#dba4ff"));
        TableLayout tableLayout = new TableLayout(this);
        this.xkraapzkoe = tableLayout;
        tableLayout.setLayoutParams(new LinearLayout.LayoutParams(348, 1542));
        this.xkraapzkoe.setPadding(111, 159, 47, 48);
        linearLayout.addView(this.xkraapzkoe);
        this.xkraapzkoe.setBackgroundColor(Color.parseColor("#633b64"));
        RelativeLayout relativeLayout3 = new RelativeLayout(this);
        this.dqyxlsiika = relativeLayout3;
        relativeLayout3.setLayoutParams(new LinearLayout.LayoutParams(1377, 876));
        this.dqyxlsiika.setPadding(191, 185, 82, 70);
        linearLayout.addView(this.dqyxlsiika);
        this.dqyxlsiika.setBackgroundColor(Color.parseColor("#bb8640"));
        EditText editText2 = new EditText(this);
        this.klyrngskoh = editText2;
        editText2.setLayoutParams(new LinearLayout.LayoutParams(839, 1099));
        this.klyrngskoh.setPadding(88, 102, 154, 59);
        linearLayout.addView(this.klyrngskoh);
        this.klyrngskoh.setBackgroundColor(Color.parseColor("#9214e5"));
        RatingBar ratingBar2 = new RatingBar(this);
        this.yysuegadpc = ratingBar2;
        ratingBar2.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.MotionType.TYPE_QUANTIZE_INTERPOLATOR, 1856));
        this.yysuegadpc.setPadding(WebSocketProtocol.PAYLOAD_SHORT, 192, 179, 60);
        linearLayout.addView(this.yysuegadpc);
        this.yysuegadpc.setBackgroundColor(Color.parseColor("#91d84d"));
        EditText editText3 = new EditText(this);
        this.vuyhllhbcc = editText3;
        editText3.setLayoutParams(new LinearLayout.LayoutParams(661, 1368));
        this.vuyhllhbcc.setPadding(142, BDLocation.TypeNetWorkLocation, 139, 46);
        linearLayout.addView(this.vuyhllhbcc);
        this.vuyhllhbcc.setBackgroundColor(Color.parseColor("#a6d392"));
        ListView listView = new ListView(this);
        this.cawixoxlxb = listView;
        listView.setLayoutParams(new LinearLayout.LayoutParams(192, 526));
        this.cawixoxlxb.setPadding(118, 159, 195, 15);
        linearLayout.addView(this.cawixoxlxb);
        this.cawixoxlxb.setBackgroundColor(Color.parseColor("#56fbc1"));
        ListView listView2 = new ListView(this);
        this.iubozitniv = listView2;
        listView2.setLayoutParams(new LinearLayout.LayoutParams(1934, 1893));
        this.iubozitniv.setPadding(9, 87, 159, 135);
        linearLayout.addView(this.iubozitniv);
        this.iubozitniv.setBackgroundColor(Color.parseColor("#ce843e"));
        TableLayout tableLayout2 = new TableLayout(this);
        this.aonjbipzxw = tableLayout2;
        tableLayout2.setLayoutParams(new LinearLayout.LayoutParams(1605, 1098));
        this.aonjbipzxw.setPadding(63, PictureConfig.CHOOSE_REQUEST, 69, 41);
        linearLayout.addView(this.aonjbipzxw);
        this.aonjbipzxw.setBackgroundColor(Color.parseColor("#7dbf02"));
        RadioButton radioButton2 = new RadioButton(this);
        this.khmqluakop = radioButton2;
        radioButton2.setLayoutParams(new LinearLayout.LayoutParams(843, 1200));
        this.khmqluakop.setPadding(51, 155, 65, 139);
        linearLayout.addView(this.khmqluakop);
        this.khmqluakop.setBackgroundColor(Color.parseColor("#904d83"));
        EditText editText4 = new EditText(this);
        this.inznwstgcv = editText4;
        editText4.setLayoutParams(new LinearLayout.LayoutParams(1655, 992));
        this.inznwstgcv.setPadding(132, 132, 143, 103);
        linearLayout.addView(this.inznwstgcv);
        this.inznwstgcv.setBackgroundColor(Color.parseColor("#dc3709"));
        TextView textView = new TextView(this);
        this.klmxdtodkc = textView;
        textView.setLayoutParams(new LinearLayout.LayoutParams(1993, 1460));
        this.klmxdtodkc.setPadding(189, 71, 121, 5);
        linearLayout.addView(this.klmxdtodkc);
        this.klmxdtodkc.setBackgroundColor(Color.parseColor("#6a5db1"));
        GridView gridView2 = new GridView(this);
        this.pyjsuwguqf = gridView2;
        gridView2.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.MotionType.TYPE_QUANTIZE_MOTIONSTEPS, 215));
        this.pyjsuwguqf.setPadding(169, 73, 176, 198);
        linearLayout.addView(this.pyjsuwguqf);
        this.pyjsuwguqf.setBackgroundColor(Color.parseColor("#bd3f39"));
        TimePicker timePicker = new TimePicker(this);
        this.hxlutewboe = timePicker;
        timePicker.setLayoutParams(new LinearLayout.LayoutParams(581, 1428));
        this.hxlutewboe.setPadding(190, 9, 87, 143);
        linearLayout.addView(this.hxlutewboe);
        this.hxlutewboe.setBackgroundColor(Color.parseColor("#61e894"));
        Switch r2 = new Switch(this);
        this.bdcrlursel = r2;
        r2.setLayoutParams(new LinearLayout.LayoutParams(404, 1681));
        this.bdcrlursel.setPadding(19, PictureConfig.CHOOSE_REQUEST, 18, 143);
        linearLayout.addView(this.bdcrlursel);
        this.bdcrlursel.setBackgroundColor(Color.parseColor("#30ee5a"));
        RelativeLayout relativeLayout4 = new RelativeLayout(this);
        this.gkczxrktlg = relativeLayout4;
        relativeLayout4.setLayoutParams(new LinearLayout.LayoutParams(1183, 175));
        this.gkczxrktlg.setPadding(181, 17, 134, 157);
        linearLayout.addView(this.gkczxrktlg);
        this.gkczxrktlg.setBackgroundColor(Color.parseColor("#93ec17"));
        ViewFlipper viewFlipper2 = new ViewFlipper(this);
        this.ymhgtecagc = viewFlipper2;
        viewFlipper2.setLayoutParams(new LinearLayout.LayoutParams(175, 8));
        this.ymhgtecagc.setPadding(180, 177, 1, 10);
        linearLayout.addView(this.ymhgtecagc);
        this.ymhgtecagc.setBackgroundColor(Color.parseColor("#77f789"));
        CheckBox checkBox3 = new CheckBox(this);
        this.upsiwlnbpn = checkBox3;
        checkBox3.setLayoutParams(new LinearLayout.LayoutParams(1896, 1245));
        this.upsiwlnbpn.setPadding(67, 31, 194, 24);
        linearLayout.addView(this.upsiwlnbpn);
        this.upsiwlnbpn.setBackgroundColor(Color.parseColor("#aa1149"));
        Switch r22 = new Switch(this);
        this.ayevcmfuqs = r22;
        r22.setLayoutParams(new LinearLayout.LayoutParams(164, 1554));
        this.ayevcmfuqs.setPadding(85, 32, 187, 13);
        linearLayout.addView(this.ayevcmfuqs);
        this.ayevcmfuqs.setBackgroundColor(Color.parseColor("#1e1a10"));
        Button button3 = new Button(this);
        this.ctcfrrapwm = button3;
        button3.setLayoutParams(new LinearLayout.LayoutParams(741, 127));
        this.ctcfrrapwm.setPadding(114, 32, 106, 87);
        linearLayout.addView(this.ctcfrrapwm);
        this.ctcfrrapwm.setBackgroundColor(Color.parseColor("#474234"));
        RatingBar ratingBar3 = new RatingBar(this);
        this.hyhnokdlpm = ratingBar3;
        ratingBar3.setLayoutParams(new LinearLayout.LayoutParams(1402, 1932));
        this.hyhnokdlpm.setPadding(66, 113, 23, 77);
        linearLayout.addView(this.hyhnokdlpm);
        this.hyhnokdlpm.setBackgroundColor(Color.parseColor("#1b9fa9"));
        ViewFlipper viewFlipper3 = new ViewFlipper(this);
        this.frxbsnbsmw = viewFlipper3;
        viewFlipper3.setLayoutParams(new LinearLayout.LayoutParams(1546, 625));
        this.frxbsnbsmw.setPadding(57, 64, 175, 118);
        linearLayout.addView(this.frxbsnbsmw);
        this.frxbsnbsmw.setBackgroundColor(Color.parseColor("#8f2291"));
        Button button4 = new Button(this);
        this.dxsqzipxbk = button4;
        button4.setLayoutParams(new LinearLayout.LayoutParams(1989, 801));
        this.dxsqzipxbk.setPadding(9, 62, 87, 178);
        linearLayout.addView(this.dxsqzipxbk);
        this.dxsqzipxbk.setBackgroundColor(Color.parseColor("#171323"));
        RelativeLayout relativeLayout5 = new RelativeLayout(this);
        this.xhcbjihxgr = relativeLayout5;
        relativeLayout5.setLayoutParams(new LinearLayout.LayoutParams(383, 1114));
        this.xhcbjihxgr.setPadding(79, 96, 140, 26);
        linearLayout.addView(this.xhcbjihxgr);
        this.xhcbjihxgr.setBackgroundColor(Color.parseColor("#ae5bb9"));
        CheckBox checkBox4 = new CheckBox(this);
        this.ivcgiaoyul = checkBox4;
        checkBox4.setLayoutParams(new LinearLayout.LayoutParams(64, 514));
        this.ivcgiaoyul.setPadding(148, 68, 150, 29);
        linearLayout.addView(this.ivcgiaoyul);
        this.ivcgiaoyul.setBackgroundColor(Color.parseColor("#8a9d29"));
        GridView gridView3 = new GridView(this);
        this.evbyswieyl = gridView3;
        gridView3.setLayoutParams(new LinearLayout.LayoutParams(495, 137));
        this.evbyswieyl.setPadding(132, 25, PictureConfig.CHOOSE_REQUEST, 2);
        linearLayout.addView(this.evbyswieyl);
        this.evbyswieyl.setBackgroundColor(Color.parseColor("#befce5"));
        FrameLayout frameLayout = new FrameLayout(this);
        this.knwudooaam = frameLayout;
        frameLayout.setLayoutParams(new LinearLayout.LayoutParams(677, 1422));
        this.knwudooaam.setPadding(171, 145, 59, 28);
        linearLayout.addView(this.knwudooaam);
        this.knwudooaam.setBackgroundColor(Color.parseColor("#b15ba8"));
        EditText editText5 = new EditText(this);
        this.yeqntqomoj = editText5;
        editText5.setLayoutParams(new LinearLayout.LayoutParams(1988, 1496));
        this.yeqntqomoj.setPadding(91, 53, 80, 94);
        linearLayout.addView(this.yeqntqomoj);
        this.yeqntqomoj.setBackgroundColor(Color.parseColor("#73f44c"));
        ProgressBar progressBar2 = new ProgressBar(this);
        this.vcczhrzwpe = progressBar2;
        progressBar2.setLayoutParams(new LinearLayout.LayoutParams(495, 1035));
        this.vcczhrzwpe.setPadding(139, 38, 68, 115);
        linearLayout.addView(this.vcczhrzwpe);
        this.vcczhrzwpe.setBackgroundColor(Color.parseColor("#a512bd"));
        TimePicker timePicker2 = new TimePicker(this);
        this.zpcleenzcm = timePicker2;
        timePicker2.setLayoutParams(new LinearLayout.LayoutParams(1837, 1739));
        this.zpcleenzcm.setPadding(179, 27, 191, 1);
        linearLayout.addView(this.zpcleenzcm);
        this.zpcleenzcm.setBackgroundColor(Color.parseColor("#6526db"));
        TimePicker timePicker3 = new TimePicker(this);
        this.declbfgihv = timePicker3;
        timePicker3.setLayoutParams(new LinearLayout.LayoutParams(1871, 217));
        this.declbfgihv.setPadding(195, 180, 117, 3);
        linearLayout.addView(this.declbfgihv);
        this.declbfgihv.setBackgroundColor(Color.parseColor("#d7e64b"));
        GridView gridView4 = new GridView(this);
        this.vllcsiczqa = gridView4;
        gridView4.setLayoutParams(new LinearLayout.LayoutParams(1321, 1296));
        this.vllcsiczqa.setPadding(90, 186, 109, 185);
        linearLayout.addView(this.vllcsiczqa);
        this.vllcsiczqa.setBackgroundColor(Color.parseColor("#59e772"));
        Button button5 = new Button(this);
        this.ivxgqcjdkf = button5;
        button5.setLayoutParams(new LinearLayout.LayoutParams(405, 452));
        this.ivxgqcjdkf.setPadding(171, 105, 95, 86);
        linearLayout.addView(this.ivxgqcjdkf);
        this.ivxgqcjdkf.setBackgroundColor(Color.parseColor("#ea9299"));
        ViewFlipper viewFlipper4 = new ViewFlipper(this);
        this.myklwiyrqk = viewFlipper4;
        viewFlipper4.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.PositionType.TYPE_PERCENT_Y, 1727));
        this.myklwiyrqk.setPadding(81, 11, 173, 37);
        linearLayout.addView(this.myklwiyrqk);
        this.myklwiyrqk.setBackgroundColor(Color.parseColor("#c12ac9"));
        TextView textView2 = new TextView(this);
        this.wuyulckphp = textView2;
        textView2.setLayoutParams(new LinearLayout.LayoutParams(1860, 1073));
        this.wuyulckphp.setPadding(52, 179, 26, 192);
        linearLayout.addView(this.wuyulckphp);
        this.wuyulckphp.setBackgroundColor(Color.parseColor("#33a81d"));
        GridView gridView5 = new GridView(this);
        this.fheddpnjyf = gridView5;
        gridView5.setLayoutParams(new LinearLayout.LayoutParams(1556, 1258));
        this.fheddpnjyf.setPadding(100, 131, 175, 181);
        linearLayout.addView(this.fheddpnjyf);
        this.fheddpnjyf.setBackgroundColor(Color.parseColor("#0ecae4"));
        CheckBox checkBox5 = new CheckBox(this);
        this.gnwufdckan = checkBox5;
        checkBox5.setLayoutParams(new LinearLayout.LayoutParams(1599, 1166));
        this.gnwufdckan.setPadding(59, 106, 12, 182);
        linearLayout.addView(this.gnwufdckan);
        this.gnwufdckan.setBackgroundColor(Color.parseColor("#68573a"));
        Button button6 = new Button(this);
        this.pzznbexkxv = button6;
        button6.setLayoutParams(new LinearLayout.LayoutParams(1612, 1277));
        this.pzznbexkxv.setPadding(16, 125, 27, 44);
        linearLayout.addView(this.pzznbexkxv);
        this.pzznbexkxv.setBackgroundColor(Color.parseColor("#fd4be4"));
        TableLayout tableLayout3 = new TableLayout(this);
        this.lssitdvonm = tableLayout3;
        tableLayout3.setLayoutParams(new LinearLayout.LayoutParams(287, 1797));
        this.lssitdvonm.setPadding(150, 136, 8, 24);
        linearLayout.addView(this.lssitdvonm);
        this.lssitdvonm.setBackgroundColor(Color.parseColor("#5e41b1"));
        SeekBar seekBar = new SeekBar(this);
        this.rlsvapvmpk = seekBar;
        seekBar.setLayoutParams(new LinearLayout.LayoutParams(1226, 1326));
        this.rlsvapvmpk.setPadding(131, 74, 132, 55);
        linearLayout.addView(this.rlsvapvmpk);
        this.rlsvapvmpk.setBackgroundColor(Color.parseColor("#98febe"));
        LinearLayout linearLayout2 = new LinearLayout(this);
        this.ohdakvgxuw = linearLayout2;
        linearLayout2.setLayoutParams(new LinearLayout.LayoutParams(1467, 473));
        this.ohdakvgxuw.setPadding(5, 43, 57, 33);
        linearLayout.addView(this.ohdakvgxuw);
        this.ohdakvgxuw.setBackgroundColor(Color.parseColor("#cd1120"));
        GridView gridView6 = new GridView(this);
        this.qkrgjkbnae = gridView6;
        gridView6.setLayoutParams(new LinearLayout.LayoutParams(936, 1085));
        this.qkrgjkbnae.setPadding(168, 75, 175, 134);
        linearLayout.addView(this.qkrgjkbnae);
        this.qkrgjkbnae.setBackgroundColor(Color.parseColor("#0b4100"));
        TimePicker timePicker4 = new TimePicker(this);
        this.vfiyalxbov = timePicker4;
        timePicker4.setLayoutParams(new LinearLayout.LayoutParams(558, 1606));
        this.vfiyalxbov.setPadding(51, 81, 37, 132);
        linearLayout.addView(this.vfiyalxbov);
        this.vfiyalxbov.setBackgroundColor(Color.parseColor("#23e14e"));
        ListView listView3 = new ListView(this);
        this.banhdxlooi = listView3;
        listView3.setLayoutParams(new LinearLayout.LayoutParams(305, 1123));
        this.banhdxlooi.setPadding(129, 196, 67, 104);
        linearLayout.addView(this.banhdxlooi);
        this.banhdxlooi.setBackgroundColor(Color.parseColor("#808ba4"));
        Button button7 = new Button(this);
        this.ogteizawth = button7;
        button7.setLayoutParams(new LinearLayout.LayoutParams(165, 1235));
        this.ogteizawth.setPadding(67, 81, 179, 152);
        linearLayout.addView(this.ogteizawth);
        this.ogteizawth.setBackgroundColor(Color.parseColor("#202319"));
        ToggleButton toggleButton3 = new ToggleButton(this);
        this.wabgcafhol = toggleButton3;
        toggleButton3.setLayoutParams(new LinearLayout.LayoutParams(1059, 693));
        this.wabgcafhol.setPadding(107, 194, 55, BDLocation.TypeServerDecryptError);
        linearLayout.addView(this.wabgcafhol);
        this.wabgcafhol.setBackgroundColor(Color.parseColor("#15ed13"));
        ListView listView4 = new ListView(this);
        this.mlywqqvhjm = listView4;
        listView4.setLayoutParams(new LinearLayout.LayoutParams(447, 1266));
        this.mlywqqvhjm.setPadding(148, 39, 165, 68);
        linearLayout.addView(this.mlywqqvhjm);
        this.mlywqqvhjm.setBackgroundColor(Color.parseColor("#acbc98"));
        TextView textView3 = new TextView(this);
        this.jkeehkzjez = textView3;
        textView3.setLayoutParams(new LinearLayout.LayoutParams(1694, 1728));
        this.jkeehkzjez.setPadding(38, 20, 183, 71);
        linearLayout.addView(this.jkeehkzjez);
        this.jkeehkzjez.setBackgroundColor(Color.parseColor("#4322f4"));
        TimePicker timePicker5 = new TimePicker(this);
        this.jggkuhcumi = timePicker5;
        timePicker5.setLayoutParams(new LinearLayout.LayoutParams(1708, 109));
        this.jggkuhcumi.setPadding(158, 87, 40, BDLocation.TypeServerDecryptError);
        linearLayout.addView(this.jggkuhcumi);
        this.jggkuhcumi.setBackgroundColor(Color.parseColor("#19868b"));
        ScrollView scrollView = new ScrollView(this);
        this.tmtijwatcr = scrollView;
        scrollView.setLayoutParams(new LinearLayout.LayoutParams(243, 1517));
        this.tmtijwatcr.setPadding(3, 68, BDLocation.TypeCoarseLocation, BDLocation.TypeCoarseLocation);
        linearLayout.addView(this.tmtijwatcr);
        this.tmtijwatcr.setBackgroundColor(Color.parseColor("#5f5a85"));
        ViewFlipper viewFlipper5 = new ViewFlipper(this);
        this.iygrlpzkvs = viewFlipper5;
        viewFlipper5.setLayoutParams(new LinearLayout.LayoutParams(799, 1626));
        this.iygrlpzkvs.setPadding(92, 79, 191, 46);
        linearLayout.addView(this.iygrlpzkvs);
        this.iygrlpzkvs.setBackgroundColor(Color.parseColor("#5db7e0"));
        FrameLayout frameLayout2 = new FrameLayout(this);
        this.hxoxfzwqvb = frameLayout2;
        frameLayout2.setLayoutParams(new LinearLayout.LayoutParams(1878, 798));
        this.hxoxfzwqvb.setPadding(173, 6, 168, 140);
        linearLayout.addView(this.hxoxfzwqvb);
        this.hxoxfzwqvb.setBackgroundColor(Color.parseColor("#028ae7"));
        RadioButton radioButton3 = new RadioButton(this);
        this.kontfgaeem = radioButton3;
        radioButton3.setLayoutParams(new LinearLayout.LayoutParams(429, 1494));
        this.kontfgaeem.setPadding(185, 120, 124, WebSocketProtocol.PAYLOAD_SHORT);
        linearLayout.addView(this.kontfgaeem);
        this.kontfgaeem.setBackgroundColor(Color.parseColor("#02f8c2"));
        FrameLayout frameLayout3 = new FrameLayout(this);
        this.vkgklmjfsf = frameLayout3;
        frameLayout3.setLayoutParams(new LinearLayout.LayoutParams(1245, 1053));
        this.vkgklmjfsf.setPadding(65, 158, 31, 103);
        linearLayout.addView(this.vkgklmjfsf);
        this.vkgklmjfsf.setBackgroundColor(Color.parseColor("#4f6bc1"));
        Switch r23 = new Switch(this);
        this.hncrrmrivy = r23;
        r23.setLayoutParams(new LinearLayout.LayoutParams(428, 668));
        this.hncrrmrivy.setPadding(19, 133, 0, 138);
        linearLayout.addView(this.hncrrmrivy);
        this.hncrrmrivy.setBackgroundColor(Color.parseColor("#fe6a15"));
        ListView listView5 = new ListView(this);
        this.ekddpytthk = listView5;
        listView5.setLayoutParams(new LinearLayout.LayoutParams(320, 498));
        this.ekddpytthk.setPadding(159, 13, 41, 102);
        linearLayout.addView(this.ekddpytthk);
        this.ekddpytthk.setBackgroundColor(Color.parseColor("#50ca1c"));
        TimePicker timePicker6 = new TimePicker(this);
        this.kkxhxbodrw = timePicker6;
        timePicker6.setLayoutParams(new LinearLayout.LayoutParams(1302, 413));
        this.kkxhxbodrw.setPadding(67, 48, 39, 164);
        linearLayout.addView(this.kkxhxbodrw);
        this.kkxhxbodrw.setBackgroundColor(Color.parseColor("#033100"));
        ScrollView scrollView2 = new ScrollView(this);
        this.fgrbjdbkiz = scrollView2;
        scrollView2.setLayoutParams(new LinearLayout.LayoutParams(1960, 1325));
        this.fgrbjdbkiz.setPadding(111, 67, 179, 95);
        linearLayout.addView(this.fgrbjdbkiz);
        this.fgrbjdbkiz.setBackgroundColor(Color.parseColor("#f5fd48"));
        TableLayout tableLayout4 = new TableLayout(this);
        this.wmzjzdujxu = tableLayout4;
        tableLayout4.setLayoutParams(new LinearLayout.LayoutParams(1636, PointerIconCompat.TYPE_TOP_RIGHT_DIAGONAL_DOUBLE_ARROW));
        this.wmzjzdujxu.setPadding(163, 11, 133, 56);
        linearLayout.addView(this.wmzjzdujxu);
        this.wmzjzdujxu.setBackgroundColor(Color.parseColor("#758910"));
        ToggleButton toggleButton4 = new ToggleButton(this);
        this.rkewmuftsd = toggleButton4;
        toggleButton4.setLayoutParams(new LinearLayout.LayoutParams(1760, 838));
        this.rkewmuftsd.setPadding(45, 116, 50, 116);
        linearLayout.addView(this.rkewmuftsd);
        this.rkewmuftsd.setBackgroundColor(Color.parseColor("#2df79e"));
        RadioButton radioButton4 = new RadioButton(this);
        this.usxqpbsawf = radioButton4;
        radioButton4.setLayoutParams(new LinearLayout.LayoutParams(723, 1986));
        this.usxqpbsawf.setPadding(112, 115, 116, 92);
        linearLayout.addView(this.usxqpbsawf);
        this.usxqpbsawf.setBackgroundColor(Color.parseColor("#505cd8"));
        TableLayout tableLayout5 = new TableLayout(this);
        this.fagfniikwg = tableLayout5;
        tableLayout5.setLayoutParams(new LinearLayout.LayoutParams(759, 1123));
        this.fagfniikwg.setPadding(182, 109, 55, 96);
        linearLayout.addView(this.fagfniikwg);
        this.fagfniikwg.setBackgroundColor(Color.parseColor("#f1a2f3"));
        Button button8 = new Button(this);
        this.boqlzfyasw = button8;
        button8.setLayoutParams(new LinearLayout.LayoutParams(1331, 333));
        this.boqlzfyasw.setPadding(134, 165, 116, 47);
        linearLayout.addView(this.boqlzfyasw);
        this.boqlzfyasw.setBackgroundColor(Color.parseColor("#0c23be"));
        ImageView imageView = new ImageView(this);
        this.ewqfdrebms = imageView;
        imageView.setLayoutParams(new LinearLayout.LayoutParams(1308, 144));
        this.ewqfdrebms.setPadding(34, 71, 190, 111);
        linearLayout.addView(this.ewqfdrebms);
        this.ewqfdrebms.setBackgroundColor(Color.parseColor("#4fc9c4"));
        EditText editText6 = new EditText(this);
        this.zzxjbjlbbc = editText6;
        editText6.setLayoutParams(new LinearLayout.LayoutParams(1123, 1924));
        this.zzxjbjlbbc.setPadding(39, 84, 114, 85);
        linearLayout.addView(this.zzxjbjlbbc);
        this.zzxjbjlbbc.setBackgroundColor(Color.parseColor("#8bdbb8"));
        GridView gridView7 = new GridView(this);
        this.pmkcvosdsk = gridView7;
        gridView7.setLayoutParams(new LinearLayout.LayoutParams(Contract.CMD_SET_VERSION.V1_2, 1159));
        this.pmkcvosdsk.setPadding(0, 58, 3, 104);
        linearLayout.addView(this.pmkcvosdsk);
        this.pmkcvosdsk.setBackgroundColor(Color.parseColor("#ae84b4"));
        TimePicker timePicker7 = new TimePicker(this);
        this.lnqqyztkkr = timePicker7;
        timePicker7.setLayoutParams(new LinearLayout.LayoutParams(231, 1404));
        this.lnqqyztkkr.setPadding(77, 191, 3, 159);
        linearLayout.addView(this.lnqqyztkkr);
        this.lnqqyztkkr.setBackgroundColor(Color.parseColor("#c371b3"));
        ProgressBar progressBar3 = new ProgressBar(this);
        this.bcioxbmfxa = progressBar3;
        progressBar3.setLayoutParams(new LinearLayout.LayoutParams(170, 1353));
        this.bcioxbmfxa.setPadding(29, 98, 133, 125);
        linearLayout.addView(this.bcioxbmfxa);
        this.bcioxbmfxa.setBackgroundColor(Color.parseColor("#aa4a45"));
        LinearLayout linearLayout3 = new LinearLayout(this);
        this.hrqqqjcuox = linearLayout3;
        linearLayout3.setLayoutParams(new LinearLayout.LayoutParams(163, TypedValues.TransitionType.TYPE_TRANSITION_FLAGS));
        this.hrqqqjcuox.setPadding(4, 198, 70, 94);
        linearLayout.addView(this.hrqqqjcuox);
        this.hrqqqjcuox.setBackgroundColor(Color.parseColor("#887eeb"));
        DatePicker datePicker = new DatePicker(this);
        this.uwfmnqpdqe = datePicker;
        datePicker.setLayoutParams(new LinearLayout.LayoutParams(796, 1489));
        this.uwfmnqpdqe.setPadding(110, 156, 164, 136);
        linearLayout.addView(this.uwfmnqpdqe);
        this.uwfmnqpdqe.setBackgroundColor(Color.parseColor("#cd7d29"));
        ScrollView scrollView3 = new ScrollView(this);
        this.zoaipoufgs = scrollView3;
        scrollView3.setLayoutParams(new LinearLayout.LayoutParams(14, 1347));
        this.zoaipoufgs.setPadding(82, 155, 22, 96);
        linearLayout.addView(this.zoaipoufgs);
        this.zoaipoufgs.setBackgroundColor(Color.parseColor("#4222bb"));
        ListView listView6 = new ListView(this);
        this.sqsmpvordc = listView6;
        listView6.setLayoutParams(new LinearLayout.LayoutParams(1615, 1190));
        this.sqsmpvordc.setPadding(10, 64, 66, 102);
        linearLayout.addView(this.sqsmpvordc);
        this.sqsmpvordc.setBackgroundColor(Color.parseColor("#f0eb5d"));
        RelativeLayout relativeLayout6 = new RelativeLayout(this);
        this.njnctgyvtu = relativeLayout6;
        relativeLayout6.setLayoutParams(new LinearLayout.LayoutParams(800, 991));
        this.njnctgyvtu.setPadding(183, 93, 190, 95);
        linearLayout.addView(this.njnctgyvtu);
        this.njnctgyvtu.setBackgroundColor(Color.parseColor("#eaf456"));
        ImageView imageView2 = new ImageView(this);
        this.gdeuauxuwq = imageView2;
        imageView2.setLayoutParams(new LinearLayout.LayoutParams(221, 1112));
        this.gdeuauxuwq.setPadding(194, 198, 38, 14);
        linearLayout.addView(this.gdeuauxuwq);
        this.gdeuauxuwq.setBackgroundColor(Color.parseColor("#1dbd26"));
        FrameLayout frameLayout4 = new FrameLayout(this);
        this.zqzadukxhs = frameLayout4;
        frameLayout4.setLayoutParams(new LinearLayout.LayoutParams(1781, 1875));
        this.zqzadukxhs.setPadding(37, 63, 60, 96);
        linearLayout.addView(this.zqzadukxhs);
        this.zqzadukxhs.setBackgroundColor(Color.parseColor("#a3172d"));
        Spinner spinner = new Spinner(this);
        this.yiswaqxvbp = spinner;
        spinner.setLayoutParams(new LinearLayout.LayoutParams(513, 513));
        this.yiswaqxvbp.setPadding(49, 36, 157, 66);
        linearLayout.addView(this.yiswaqxvbp);
        this.yiswaqxvbp.setBackgroundColor(Color.parseColor("#ea359e"));
        TableLayout tableLayout6 = new TableLayout(this);
        this.cagfdlstdk = tableLayout6;
        tableLayout6.setLayoutParams(new LinearLayout.LayoutParams(1481, 1910));
        this.cagfdlstdk.setPadding(145, 44, 47, 184);
        linearLayout.addView(this.cagfdlstdk);
        this.cagfdlstdk.setBackgroundColor(Color.parseColor("#a1ff60"));
        Spinner spinner2 = new Spinner(this);
        this.scnxsahzjd = spinner2;
        spinner2.setLayoutParams(new LinearLayout.LayoutParams(1817, 1860));
        this.scnxsahzjd.setPadding(117, 13, 16, 131);
        linearLayout.addView(this.scnxsahzjd);
        this.scnxsahzjd.setBackgroundColor(Color.parseColor("#f5b4fe"));
        CheckBox checkBox6 = new CheckBox(this);
        this.wnzedtgqaz = checkBox6;
        checkBox6.setLayoutParams(new LinearLayout.LayoutParams(106, 922));
        this.wnzedtgqaz.setPadding(65, 29, 145, 143);
        linearLayout.addView(this.wnzedtgqaz);
        this.wnzedtgqaz.setBackgroundColor(Color.parseColor("#68f0ec"));
        ImageView imageView3 = new ImageView(this);
        this.jqbwhyporf = imageView3;
        imageView3.setLayoutParams(new LinearLayout.LayoutParams(661, 1056));
        this.jqbwhyporf.setPadding(116, 34, 73, 8);
        linearLayout.addView(this.jqbwhyporf);
        this.jqbwhyporf.setBackgroundColor(Color.parseColor("#23b655"));
        TableLayout tableLayout7 = new TableLayout(this);
        this.vbddziairr = tableLayout7;
        tableLayout7.setLayoutParams(new LinearLayout.LayoutParams(346, 825));
        this.vbddziairr.setPadding(157, 95, 175, BDLocation.TypeServerError);
        linearLayout.addView(this.vbddziairr);
        this.vbddziairr.setBackgroundColor(Color.parseColor("#8b7d90"));
        Button button9 = new Button(this);
        this.rbggfbsffm = button9;
        button9.setLayoutParams(new LinearLayout.LayoutParams(70, 1004));
        this.rbggfbsffm.setPadding(104, 132, BDLocation.TypeServerError, 94);
        linearLayout.addView(this.rbggfbsffm);
        this.rbggfbsffm.setBackgroundColor(Color.parseColor("#053549"));
        SeekBar seekBar2 = new SeekBar(this);
        this.lnzgzmipoo = seekBar2;
        seekBar2.setLayoutParams(new LinearLayout.LayoutParams(1867, 792));
        this.lnzgzmipoo.setPadding(32, 64, 108, 149);
        linearLayout.addView(this.lnzgzmipoo);
        this.lnzgzmipoo.setBackgroundColor(Color.parseColor("#ff6f01"));
        TableLayout tableLayout8 = new TableLayout(this);
        this.kvterlecgm = tableLayout8;
        tableLayout8.setLayoutParams(new LinearLayout.LayoutParams(1553, 331));
        this.kvterlecgm.setPadding(125, 166, 70, 7);
        linearLayout.addView(this.kvterlecgm);
        this.kvterlecgm.setBackgroundColor(Color.parseColor("#cf5055"));
        Button button10 = new Button(this);
        this.euwqurmcne = button10;
        button10.setLayoutParams(new LinearLayout.LayoutParams(1473, 1878));
        this.euwqurmcne.setPadding(12, 2, 42, 181);
        linearLayout.addView(this.euwqurmcne);
        this.euwqurmcne.setBackgroundColor(Color.parseColor("#f070a4"));
        LinearLayout linearLayout4 = new LinearLayout(this);
        this.juxneumuqp = linearLayout4;
        linearLayout4.setLayoutParams(new LinearLayout.LayoutParams(410, 1240));
        this.juxneumuqp.setPadding(110, 54, 24, 86);
        linearLayout.addView(this.juxneumuqp);
        this.juxneumuqp.setBackgroundColor(Color.parseColor("#7648ca"));
        Button button11 = new Button(this);
        this.xnxwwcxewg = button11;
        button11.setLayoutParams(new LinearLayout.LayoutParams(1236, 509));
        this.xnxwwcxewg.setPadding(89, 181, 74, 121);
        linearLayout.addView(this.xnxwwcxewg);
        this.xnxwwcxewg.setBackgroundColor(Color.parseColor("#1b6749"));
        ImageView imageView4 = new ImageView(this);
        this.wyauargurf = imageView4;
        imageView4.setLayoutParams(new LinearLayout.LayoutParams(1209, 458));
        this.wyauargurf.setPadding(92, 35, 103, 168);
        linearLayout.addView(this.wyauargurf);
        this.wyauargurf.setBackgroundColor(Color.parseColor("#65aa02"));
        ListView listView7 = new ListView(this);
        this.timbhhjojz = listView7;
        listView7.setLayoutParams(new LinearLayout.LayoutParams(1084, TypedValues.AttributesType.TYPE_PIVOT_TARGET));
        this.timbhhjojz.setPadding(191, 127, 152, 129);
        linearLayout.addView(this.timbhhjojz);
        this.timbhhjojz.setBackgroundColor(Color.parseColor("#f9e07c"));
        GridView gridView8 = new GridView(this);
        this.bulodpicuc = gridView8;
        gridView8.setLayoutParams(new LinearLayout.LayoutParams(1385, 399));
        this.bulodpicuc.setPadding(88, 23, 25, 147);
        linearLayout.addView(this.bulodpicuc);
        this.bulodpicuc.setBackgroundColor(Color.parseColor("#0d28d7"));
        ImageView imageView5 = new ImageView(this);
        this.guspvbsphw = imageView5;
        imageView5.setLayoutParams(new LinearLayout.LayoutParams(691, 1448));
        this.guspvbsphw.setPadding(32, 38, 48, 83);
        linearLayout.addView(this.guspvbsphw);
        this.guspvbsphw.setBackgroundColor(Color.parseColor("#29d810"));
        Switch r24 = new Switch(this);
        this.bbxtjwnxia = r24;
        r24.setLayoutParams(new LinearLayout.LayoutParams(660, 1299));
        this.bbxtjwnxia.setPadding(156, 5, 196, 185);
        linearLayout.addView(this.bbxtjwnxia);
        this.bbxtjwnxia.setBackgroundColor(Color.parseColor("#baa21d"));
        ImageView imageView6 = new ImageView(this);
        this.lzyawjfcvi = imageView6;
        imageView6.setLayoutParams(new LinearLayout.LayoutParams(1239, 1200));
        this.lzyawjfcvi.setPadding(168, 163, 156, 131);
        linearLayout.addView(this.lzyawjfcvi);
        this.lzyawjfcvi.setBackgroundColor(Color.parseColor("#777365"));
        RatingBar ratingBar4 = new RatingBar(this);
        this.iniwahiiea = ratingBar4;
        ratingBar4.setLayoutParams(new LinearLayout.LayoutParams(1242, 1033));
        this.iniwahiiea.setPadding(30, 26, 184, 125);
        linearLayout.addView(this.iniwahiiea);
        this.iniwahiiea.setBackgroundColor(Color.parseColor("#f2a153"));
        Button button12 = new Button(this);
        this.egzdfghutu = button12;
        button12.setLayoutParams(new LinearLayout.LayoutParams(886, 1176));
        this.egzdfghutu.setPadding(70, 72, 116, 138);
        linearLayout.addView(this.egzdfghutu);
        this.egzdfghutu.setBackgroundColor(Color.parseColor("#94f5f3"));
        ListView listView8 = new ListView(this);
        this.nhgpgxxvme = listView8;
        listView8.setLayoutParams(new LinearLayout.LayoutParams(GattClient.STATE_PENDDING_DISCOVERY_SERVICE, 943));
        this.nhgpgxxvme.setPadding(6, 102, 33, 186);
        linearLayout.addView(this.nhgpgxxvme);
        this.nhgpgxxvme.setBackgroundColor(Color.parseColor("#45d93f"));
        RadioButton radioButton5 = new RadioButton(this);
        this.gkmeaxtybm = radioButton5;
        radioButton5.setLayoutParams(new LinearLayout.LayoutParams(273, 187));
        this.gkmeaxtybm.setPadding(193, 9, 133, 193);
        linearLayout.addView(this.gkmeaxtybm);
        this.gkmeaxtybm.setBackgroundColor(Color.parseColor("#e52052"));
        EditText editText7 = new EditText(this);
        this.qmhmjzxoic = editText7;
        editText7.setLayoutParams(new LinearLayout.LayoutParams(577, 1693));
        this.qmhmjzxoic.setPadding(100, 179, 58, 10);
        linearLayout.addView(this.qmhmjzxoic);
        this.qmhmjzxoic.setBackgroundColor(Color.parseColor("#628c29"));
        RatingBar ratingBar5 = new RatingBar(this);
        this.kgcsqlumto = ratingBar5;
        ratingBar5.setLayoutParams(new LinearLayout.LayoutParams(459, 766));
        this.kgcsqlumto.setPadding(43, 189, PictureConfig.CHOOSE_REQUEST, 38);
        linearLayout.addView(this.kgcsqlumto);
        this.kgcsqlumto.setBackgroundColor(Color.parseColor("#b21d1b"));
        LinearLayout linearLayout5 = new LinearLayout(this);
        this.zcdudvadih = linearLayout5;
        linearLayout5.setLayoutParams(new LinearLayout.LayoutParams(681, 533));
        this.zcdudvadih.setPadding(179, 147, 67, 155);
        linearLayout.addView(this.zcdudvadih);
        this.zcdudvadih.setBackgroundColor(Color.parseColor("#02c389"));
        ProgressBar progressBar4 = new ProgressBar(this);
        this.pjxngosgdk = progressBar4;
        progressBar4.setLayoutParams(new LinearLayout.LayoutParams(1687, 47));
        this.pjxngosgdk.setPadding(146, 12, 0, 4);
        linearLayout.addView(this.pjxngosgdk);
        this.pjxngosgdk.setBackgroundColor(Color.parseColor("#3931a8"));
        GridView gridView9 = new GridView(this);
        this.xhylbnyxsb = gridView9;
        gridView9.setLayoutParams(new LinearLayout.LayoutParams(1589, 83));
        this.xhylbnyxsb.setPadding(129, 149, 180, 66);
        linearLayout.addView(this.xhylbnyxsb);
        this.xhylbnyxsb.setBackgroundColor(Color.parseColor("#3f5577"));
        TextView textView4 = new TextView(this);
        this.ktsqfxmiac = textView4;
        textView4.setLayoutParams(new LinearLayout.LayoutParams(1182, 776));
        this.ktsqfxmiac.setPadding(186, 49, PictureConfig.CHOOSE_REQUEST, 22);
        linearLayout.addView(this.ktsqfxmiac);
        this.ktsqfxmiac.setBackgroundColor(Color.parseColor("#7badd4"));
        EditText editText8 = new EditText(this);
        this.miigjyawwi = editText8;
        editText8.setLayoutParams(new LinearLayout.LayoutParams(1821, 1373));
        this.miigjyawwi.setPadding(117, 128, 153, 187);
        linearLayout.addView(this.miigjyawwi);
        this.miigjyawwi.setBackgroundColor(Color.parseColor("#6631e0"));
        LinearLayout linearLayout6 = new LinearLayout(this);
        this.obcvakrkyb = linearLayout6;
        linearLayout6.setLayoutParams(new LinearLayout.LayoutParams(919, 171));
        this.obcvakrkyb.setPadding(13, 80, 43, 43);
        linearLayout.addView(this.obcvakrkyb);
        this.obcvakrkyb.setBackgroundColor(Color.parseColor("#b7ac60"));
        RelativeLayout relativeLayout7 = new RelativeLayout(this);
        this.khtnkufmrb = relativeLayout7;
        relativeLayout7.setLayoutParams(new LinearLayout.LayoutParams(475, 2));
        this.khtnkufmrb.setPadding(56, 4, 189, 102);
        linearLayout.addView(this.khtnkufmrb);
        this.khtnkufmrb.setBackgroundColor(Color.parseColor("#a00e1f"));
        SeekBar seekBar3 = new SeekBar(this);
        this.htfqraocex = seekBar3;
        seekBar3.setLayoutParams(new LinearLayout.LayoutParams(45, 1718));
        this.htfqraocex.setPadding(117, 128, 11, 33);
        linearLayout.addView(this.htfqraocex);
        this.htfqraocex.setBackgroundColor(Color.parseColor("#f83bd7"));
        TableLayout tableLayout9 = new TableLayout(this);
        this.ixiwsnluyh = tableLayout9;
        tableLayout9.setLayoutParams(new LinearLayout.LayoutParams(1866, 77));
        this.ixiwsnluyh.setPadding(158, 182, 143, 106);
        linearLayout.addView(this.ixiwsnluyh);
        this.ixiwsnluyh.setBackgroundColor(Color.parseColor("#548979"));
        Spinner spinner3 = new Spinner(this);
        this.rmusankmds = spinner3;
        spinner3.setLayoutParams(new LinearLayout.LayoutParams(1533, 1823));
        this.rmusankmds.setPadding(68, 1, 83, 198);
        linearLayout.addView(this.rmusankmds);
        this.rmusankmds.setBackgroundColor(Color.parseColor("#cb8571"));
        ListView listView9 = new ListView(this);
        this.wzwdqwtbft = listView9;
        listView9.setLayoutParams(new LinearLayout.LayoutParams(1064, 1234));
        this.wzwdqwtbft.setPadding(155, 99, 49, 195);
        linearLayout.addView(this.wzwdqwtbft);
        this.wzwdqwtbft.setBackgroundColor(Color.parseColor("#c718a3"));
        GridView gridView10 = new GridView(this);
        this.trkvgmawhs = gridView10;
        gridView10.setLayoutParams(new LinearLayout.LayoutParams(774, 1672));
        this.trkvgmawhs.setPadding(155, 85, 86, 64);
        linearLayout.addView(this.trkvgmawhs);
        this.trkvgmawhs.setBackgroundColor(Color.parseColor("#b9ae28"));
        RatingBar ratingBar6 = new RatingBar(this);
        this.vngtcltmpn = ratingBar6;
        ratingBar6.setLayoutParams(new LinearLayout.LayoutParams(885, 462));
        this.vngtcltmpn.setPadding(70, 43, 148, 55);
        linearLayout.addView(this.vngtcltmpn);
        this.vngtcltmpn.setBackgroundColor(Color.parseColor("#aa4946"));
        ListView listView10 = new ListView(this);
        this.fzolbbvksx = listView10;
        listView10.setLayoutParams(new LinearLayout.LayoutParams(680, 619));
        this.fzolbbvksx.setPadding(9, 66, 22, 131);
        linearLayout.addView(this.fzolbbvksx);
        this.fzolbbvksx.setBackgroundColor(Color.parseColor("#7f9148"));
        ProgressBar progressBar5 = new ProgressBar(this);
        this.scetacqswy = progressBar5;
        progressBar5.setLayoutParams(new LinearLayout.LayoutParams(450, 474));
        this.scetacqswy.setPadding(10, 166, 54, 195);
        linearLayout.addView(this.scetacqswy);
        this.scetacqswy.setBackgroundColor(Color.parseColor("#209a88"));
        ListView listView11 = new ListView(this);
        this.wpddqqrjwx = listView11;
        listView11.setLayoutParams(new LinearLayout.LayoutParams(1287, 1613));
        this.wpddqqrjwx.setPadding(48, 52, 26, 122);
        linearLayout.addView(this.wpddqqrjwx);
        this.wpddqqrjwx.setBackgroundColor(Color.parseColor("#ccc849"));
        GridView gridView11 = new GridView(this);
        this.uehhckmzcq = gridView11;
        gridView11.setLayoutParams(new LinearLayout.LayoutParams(1891, 1175));
        this.uehhckmzcq.setPadding(96, 9, 140, 113);
        linearLayout.addView(this.uehhckmzcq);
        this.uehhckmzcq.setBackgroundColor(Color.parseColor("#57b76a"));
        ScrollView scrollView4 = new ScrollView(this);
        this.toiytohjlf = scrollView4;
        scrollView4.setLayoutParams(new LinearLayout.LayoutParams(1621, 1357));
        this.toiytohjlf.setPadding(116, 30, 185, 139);
        linearLayout.addView(this.toiytohjlf);
        this.toiytohjlf.setBackgroundColor(Color.parseColor("#2ce297"));
        LinearLayout linearLayout7 = new LinearLayout(this);
        this.uwayzpnrqx = linearLayout7;
        linearLayout7.setLayoutParams(new LinearLayout.LayoutParams(734, 1234));
        this.uwayzpnrqx.setPadding(15, 177, 25, 172);
        linearLayout.addView(this.uwayzpnrqx);
        this.uwayzpnrqx.setBackgroundColor(Color.parseColor("#0ba7a9"));
        DatePicker datePicker2 = new DatePicker(this);
        this.ybjhzozauq = datePicker2;
        datePicker2.setLayoutParams(new LinearLayout.LayoutParams(1644, 260));
        this.ybjhzozauq.setPadding(44, 16, 21, 190);
        linearLayout.addView(this.ybjhzozauq);
        this.ybjhzozauq.setBackgroundColor(Color.parseColor("#b2cebd"));
        ToggleButton toggleButton5 = new ToggleButton(this);
        this.rkfaegsfqj = toggleButton5;
        toggleButton5.setLayoutParams(new LinearLayout.LayoutParams(1851, 400));
        this.rkfaegsfqj.setPadding(37, 85, 46, 65);
        linearLayout.addView(this.rkfaegsfqj);
        this.rkfaegsfqj.setBackgroundColor(Color.parseColor("#cd2e24"));
        GridView gridView12 = new GridView(this);
        this.csefdxulvq = gridView12;
        gridView12.setLayoutParams(new LinearLayout.LayoutParams(914, 1590));
        this.csefdxulvq.setPadding(104, 152, 41, 37);
        linearLayout.addView(this.csefdxulvq);
        this.csefdxulvq.setBackgroundColor(Color.parseColor("#02dc19"));
        TimePicker timePicker8 = new TimePicker(this);
        this.oodnztgsoo = timePicker8;
        timePicker8.setLayoutParams(new LinearLayout.LayoutParams(547, 33));
        this.oodnztgsoo.setPadding(132, 38, 24, 174);
        linearLayout.addView(this.oodnztgsoo);
        this.oodnztgsoo.setBackgroundColor(Color.parseColor("#77519f"));
    }
}
