package com.device.watch.com.device.watch.jmwecqarun;

import android.app.Activity;
import android.graphics.Color;
import android.os.Bundle;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.CheckBox;
import android.widget.DatePicker;
import android.widget.EditText;
import android.widget.FrameLayout;
import android.widget.GridView;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ListView;
import android.widget.ProgressBar;
import android.widget.RadioButton;
import android.widget.RatingBar;
import android.widget.RelativeLayout;
import android.widget.ScrollView;
import android.widget.SeekBar;
import android.widget.Spinner;
import android.widget.Switch;
import android.widget.TableLayout;
import android.widget.TextView;
import android.widget.TimePicker;
import android.widget.ToggleButton;
import android.widget.ViewFlipper;
import androidx.constraintlayout.core.motion.utils.TypedValues;
import androidx.core.view.PointerIconCompat;
import androidx.room.RoomDatabase;
import com.baidu.location.BDLocation;
import com.luck.picture.lib.config.PictureConfig;
import com.qcwireless.qcwatch.ui.base.imagepicker.cropper.CropImage;
import com.realsil.sdk.bbpro.equalizer.AudioEq;
import com.realsil.sdk.core.bluetooth.connection.le.GattClient;
import com.realsil.sdk.core.bluetooth.impl.BluetoothClassImpl;
import okhttp3.internal.ws.WebSocketProtocol;

/* loaded from: classes2.dex */
public class FxyzdaudbvxActivity extends Activity {
    GridView aaqtnxxzao;
    ListView apqghhzpor;
    Switch apzidnzmep;
    Spinner axcutjokxi;
    LinearLayout bakfirbrjs;
    ScrollView bfnhzalxtn;
    GridView bforukjlgf;
    ToggleButton bmoitjlyoo;
    Button boxygdmqdp;
    TableLayout buabbchvdr;
    ToggleButton canzvzmcja;
    EditText cetajilixm;
    Spinner ckqvwzxalj;
    DatePicker cmejkarmos;
    ProgressBar cpjmqhkcaa;
    RatingBar csmqvvmrme;
    RatingBar ctvcsghszh;
    RelativeLayout ctwkuqnoar;
    Switch cwbhbuhivf;
    ToggleButton cwluvqiijz;
    DatePicker dahuigvrri;
    Switch dcmvhcckgv;
    EditText dgpkbfwzqb;
    RatingBar djetpjcsmk;
    TimePicker dngafhuffi;
    DatePicker dohdvkjkuv;
    CheckBox dotapmxcny;
    Spinner dserncxeel;
    Spinner dsluyatcce;
    Button dtkjdjtvzx;
    ScrollView dvhtkfratw;
    TimePicker eahyzpazcw;
    GridView eengfdrskt;
    ToggleButton ejjqqvswln;
    Switch emphcdqcoe;
    DatePicker eoauwoswnx;
    LinearLayout epckedcphm;
    ListView eqbthbrmhw;
    LinearLayout eqswpevhoz;
    EditText esnpgpgbji;
    RelativeLayout etvphmqkef;
    LinearLayout evuqskibiq;
    GridView exeeoerweq;
    LinearLayout fcyywmsnyd;
    ImageView fdbjgwgyfa;
    RatingBar feabxfwaoe;
    RelativeLayout fgkjgvyfsp;
    TextView fgndbcauxz;
    ViewFlipper fhfyulturw;
    TextView fhszpqhmhg;
    RadioButton fimskhvppz;
    RadioButton fiswqndtsm;
    Switch fjhwmkyeyp;
    DatePicker flxuepalds;
    ToggleButton frxadwszpt;
    ScrollView ftpxbnftuc;
    RelativeLayout ftydugoite;
    TextView fyqppjjuqk;
    GridView gdayfexgrj;
    ListView gjaskzlwsu;
    Spinner gjkkewmwdi;
    TimePicker gmdatfmpyx;
    TimePicker gseoztqyyg;
    TextView gulxfkpgii;
    SeekBar hcevclakfy;
    LinearLayout hdoklpilcs;
    RadioButton herjnbdeak;
    ScrollView hkwmztzzwy;
    TimePicker hmrcjfpgvs;
    GridView hmwgjuwfry;
    CheckBox hmzrxpjqyw;
    ProgressBar hrravtpfie;
    TimePicker hvyiwhbjnb;
    ScrollView hwgcyowjnc;
    ViewFlipper hxuiovyggc;
    GridView hzaqqzktwh;
    RatingBar hzqxkexqez;
    Button ibdqjvodxi;
    RatingBar ibromnutew;
    TextView iecveqlnaw;
    EditText iftzeogcug;
    ProgressBar igftqilcoe;
    RatingBar ikyutygdxp;
    EditText indxdxhvog;
    GridView ipoqumbopz;
    DatePicker iqmzztptdw;
    Switch iwhglyytve;
    Spinner iykzotdefq;
    EditText jgbiphwwrt;
    LinearLayout jgcouujwiz;
    TimePicker jgkxjxlvxx;
    Spinner jkgojdvkov;
    ScrollView jlvtxtqtdj;
    Spinner jskuvnjkku;
    Button jsopdzgrac;
    Switch jwcbdtqxvc;
    LinearLayout jyfxijmwlj;
    RelativeLayout jzsglfuwqa;
    ToggleButton kgsmessnuk;
    SeekBar kgyzsfwesf;
    ViewFlipper khmpetsshz;
    ScrollView khscbyycoa;
    RelativeLayout kixtqdpphp;
    ScrollView kkdnnyschm;
    DatePicker koofauwaub;
    RatingBar krjikdrkat;
    RatingBar krnlokpoqm;
    ProgressBar ktwihaafuh;
    ListView kwiepcuigo;
    TimePicker lbtquhsukh;
    TimePicker lciqchughk;
    GridView lcxmnjhnxr;
    ViewFlipper lczmchwexe;
    EditText levlbhcnnr;
    TimePicker lfruqbzhcm;
    CheckBox lfspaepblc;
    ImageView lgumsabdcv;
    RadioButton lhompczitg;
    RadioButton llrunlzenc;
    DatePicker llykawtjyj;
    TimePicker lmrdttoqdk;
    GridView lnovxzaodw;
    RelativeLayout lnoztldwxx;
    ViewFlipper lonkcvyrja;
    RelativeLayout loziodlael;
    TextView lpbgmrzpve;
    RadioButton lqllqdrjmn;
    LinearLayout lqpzhtfegf;
    RadioButton lwfilkkgdn;
    ViewFlipper lxilbyuzny;
    TextView lxvyrlvvqs;
    TextView lyhhtpjafv;
    LinearLayout lynytxldej;
    RelativeLayout lzgmcjtfmv;
    FrameLayout makljoddiu;
    GridView manhcrwivp;
    Switch mdqvxhryyv;
    RatingBar mfgglrmido;
    LinearLayout miyfwtkfhg;
    ScrollView modzltzdih;
    TimePicker nexoophmhr;
    ProgressBar nfdknpboam;
    ViewFlipper nykrfzgmna;
    RelativeLayout oevwleuzus;
    RadioButton oghrzungad;
    TableLayout ohiwdhvdjq;
    RadioButton okhzuppcya;
    ListView okvpdkffvr;
    TableLayout opjnhpqgqx;
    ListView otdeetksri;
    RadioButton oulcunwije;
    TimePicker ovizpqmqrp;
    FrameLayout pcrmvnsbbi;
    Switch pjsbgqitih;
    ToggleButton pooknalphl;
    TimePicker pqvcvnuzeg;
    Spinner ptdclhcfvw;
    GridView pymwqrqzbm;
    GridView pywiyhruua;
    TimePicker qbneeygfwd;
    ViewFlipper qctqwvslzl;
    DatePicker qkcmqpndar;
    TableLayout qnwyzcaoko;
    GridView qqykapiukj;
    ScrollView qrkdzbuvdo;
    Switch qsarhzeqdt;
    RelativeLayout qvriytctba;
    ProgressBar qzmrkolmjp;
    Switch reddygurfl;
    TextView reflblehdy;
    TableLayout rhnfhcpzdg;
    FrameLayout ricwkpyxal;
    TableLayout rncagmvbld;
    Button rqmkpfiddm;
    ViewFlipper rtbabelbej;
    RatingBar rurmevdotj;
    Switch rvfksqkltj;
    FrameLayout rvylknwqym;
    Spinner rwxjfddcnt;
    ImageView rxflyqhqvh;
    Spinner scptiizmgt;
    ListView sddrafsdyj;
    RelativeLayout sebzmjurgg;
    RelativeLayout sgprmbxhmk;
    ScrollView snwtnrdmsy;
    Button sqxfwubipq;
    DatePicker stasjwemex;
    TextView swnpsuicgh;
    Button tbpwjghhth;
    RelativeLayout tbpyrtpezk;
    Button tebtpcvtgd;
    RadioButton tksdlbxwpf;
    RelativeLayout tsspzpzokz;
    RelativeLayout txvojgpepr;
    TextView tyoydoouun;
    GridView ubmzuybztx;
    TableLayout uiavkzvzhp;
    Spinner uicdchkcyw;
    SeekBar uldambdoxn;
    RatingBar uldeklnxku;
    SeekBar upgwdgnqko;
    RatingBar uqellxzbpq;
    ProgressBar uruzlfhrak;
    RelativeLayout urzjusximo;
    ListView usadmlsgah;
    TableLayout usdqboqzas;
    ScrollView uwqxczkfsi;
    GridView uybsgbqfib;
    LinearLayout vatpgiabgq;
    ListView vrarmhvesw;
    RadioButton vyoopjzmez;
    Spinner wdcdsioatz;
    Spinner wftiqtglzo;
    ToggleButton wgivgrngea;
    ScrollView wkeuzquqne;
    RadioButton wlvmujfhkr;
    TableLayout wmzwalgred;
    ProgressBar wnwfjlrvmt;
    RadioButton wqdtsfjyyn;
    SeekBar wvzgosjkkn;
    TextView xisoomneca;
    ScrollView xmexpjodpt;
    FrameLayout xmnwjqtwby;
    Button xoaphawefx;
    SeekBar xobubllglj;
    ScrollView xusnbbazzy;
    GridView xwyegejhpk;
    ScrollView xxruuiqraq;
    RatingBar ybczkgifqo;
    ViewFlipper yfwgroqdrx;
    ProgressBar yieihcoadp;
    LinearLayout ysbfdlnzft;
    GridView yscqkguzuq;
    ListView yslzjgoxca;
    ListView ytupltglhx;
    ProgressBar ywfcevlqig;
    CheckBox zkyclfkipq;
    FrameLayout znyjcviylb;
    Spinner zpborjzgld;
    RatingBar ztvjxnuuoi;
    TableLayout zvofiflerr;
    TableLayout zwdersjqha;
    TableLayout zxjzubgvme;

    @Override // android.app.Activity
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        LinearLayout linearLayout = new LinearLayout(this);
        setContentView(linearLayout);
        linearLayout.setLayoutParams(new ViewGroup.LayoutParams(-1, -1));
        linearLayout.setOrientation(1);
        linearLayout.setBackgroundColor(Color.parseColor("#2a1e85"));
        LinearLayout linearLayout2 = new LinearLayout(this);
        this.bakfirbrjs = linearLayout2;
        linearLayout2.setLayoutParams(new LinearLayout.LayoutParams(10, 620));
        this.bakfirbrjs.setPadding(40, 49, 125, 53);
        linearLayout.addView(this.bakfirbrjs);
        this.bakfirbrjs.setBackgroundColor(Color.parseColor("#ea5d73"));
        RatingBar ratingBar = new RatingBar(this);
        this.ikyutygdxp = ratingBar;
        ratingBar.setLayoutParams(new LinearLayout.LayoutParams(1811, 954));
        this.ikyutygdxp.setPadding(44, 49, 91, 31);
        linearLayout.addView(this.ikyutygdxp);
        this.ikyutygdxp.setBackgroundColor(Color.parseColor("#fcee9f"));
        ViewFlipper viewFlipper = new ViewFlipper(this);
        this.lonkcvyrja = viewFlipper;
        viewFlipper.setLayoutParams(new LinearLayout.LayoutParams(957, 1795));
        this.lonkcvyrja.setPadding(125, 15, 129, 132);
        linearLayout.addView(this.lonkcvyrja);
        this.lonkcvyrja.setBackground(new Bgakptlmtiv());
        RadioButton radioButton = new RadioButton(this);
        this.llrunlzenc = radioButton;
        radioButton.setLayoutParams(new LinearLayout.LayoutParams(584, 25));
        this.llrunlzenc.setPadding(45, 190, 5, 119);
        linearLayout.addView(this.llrunlzenc);
        this.llrunlzenc.setBackgroundColor(Color.parseColor("#7eece6"));
        RelativeLayout relativeLayout = new RelativeLayout(this);
        this.ctwkuqnoar = relativeLayout;
        relativeLayout.setLayoutParams(new LinearLayout.LayoutParams(828, 341));
        this.ctwkuqnoar.setPadding(34, 49, 19, 125);
        linearLayout.addView(this.ctwkuqnoar);
        this.ctwkuqnoar.setBackgroundColor(Color.parseColor("#3ff2f1"));
        ScrollView scrollView = new ScrollView(this);
        this.xmexpjodpt = scrollView;
        scrollView.setLayoutParams(new LinearLayout.LayoutParams(73, 1578));
        this.xmexpjodpt.setPadding(184, 163, 58, 17);
        linearLayout.addView(this.xmexpjodpt);
        this.xmexpjodpt.setBackgroundColor(Color.parseColor("#242846"));
        RatingBar ratingBar2 = new RatingBar(this);
        this.csmqvvmrme = ratingBar2;
        ratingBar2.setLayoutParams(new LinearLayout.LayoutParams(77, TypedValues.TransitionType.TYPE_DURATION));
        this.csmqvvmrme.setPadding(108, 138, 108, 40);
        linearLayout.addView(this.csmqvvmrme);
        this.csmqvvmrme.setBackgroundColor(Color.parseColor("#21e483"));
        TableLayout tableLayout = new TableLayout(this);
        this.rncagmvbld = tableLayout;
        tableLayout.setLayoutParams(new LinearLayout.LayoutParams(788, 1075));
        this.rncagmvbld.setPadding(BDLocation.TypeServerError, BDLocation.TypeNetWorkLocation, 24, 158);
        linearLayout.addView(this.rncagmvbld);
        this.rncagmvbld.setBackgroundColor(Color.parseColor("#18efde"));
        Switch r2 = new Switch(this);
        this.mdqvxhryyv = r2;
        r2.setLayoutParams(new LinearLayout.LayoutParams(816, 199));
        this.mdqvxhryyv.setPadding(92, 139, 88, 166);
        linearLayout.addView(this.mdqvxhryyv);
        this.mdqvxhryyv.setBackgroundColor(Color.parseColor("#ac0c81"));
        Switch r22 = new Switch(this);
        this.apzidnzmep = r22;
        r22.setLayoutParams(new LinearLayout.LayoutParams(1547, 1197));
        this.apzidnzmep.setPadding(172, 92, 103, 64);
        linearLayout.addView(this.apzidnzmep);
        this.apzidnzmep.setBackgroundColor(Color.parseColor("#81fc8e"));
        Spinner spinner = new Spinner(this);
        this.jskuvnjkku = spinner;
        spinner.setLayoutParams(new LinearLayout.LayoutParams(1859, 1751));
        this.jskuvnjkku.setPadding(56, 179, 141, 197);
        linearLayout.addView(this.jskuvnjkku);
        this.jskuvnjkku.setBackgroundColor(Color.parseColor("#46c3e7"));
        Button button = new Button(this);
        this.sqxfwubipq = button;
        button.setLayoutParams(new LinearLayout.LayoutParams(887, 1362));
        this.sqxfwubipq.setPadding(179, 27, 144, 15);
        linearLayout.addView(this.sqxfwubipq);
        this.sqxfwubipq.setBackgroundColor(Color.parseColor("#d36a70"));
        Spinner spinner2 = new Spinner(this);
        this.dsluyatcce = spinner2;
        spinner2.setLayoutParams(new LinearLayout.LayoutParams(411, 866));
        this.dsluyatcce.setPadding(73, 96, 135, 100);
        linearLayout.addView(this.dsluyatcce);
        this.dsluyatcce.setBackgroundColor(Color.parseColor("#71c02c"));
        RatingBar ratingBar3 = new RatingBar(this);
        this.uqellxzbpq = ratingBar3;
        ratingBar3.setLayoutParams(new LinearLayout.LayoutParams(108, 993));
        this.uqellxzbpq.setPadding(95, 134, 29, 74);
        linearLayout.addView(this.uqellxzbpq);
        this.uqellxzbpq.setBackgroundColor(Color.parseColor("#d35c9c"));
        RadioButton radioButton2 = new RadioButton(this);
        this.lqllqdrjmn = radioButton2;
        radioButton2.setLayoutParams(new LinearLayout.LayoutParams(1433, 1100));
        this.lqllqdrjmn.setPadding(65, 118, 55, 53);
        linearLayout.addView(this.lqllqdrjmn);
        this.lqllqdrjmn.setBackgroundColor(Color.parseColor("#96ae3d"));
        Spinner spinner3 = new Spinner(this);
        this.gjkkewmwdi = spinner3;
        spinner3.setLayoutParams(new LinearLayout.LayoutParams(249, 647));
        this.gjkkewmwdi.setPadding(98, 41, 59, 75);
        linearLayout.addView(this.gjkkewmwdi);
        this.gjkkewmwdi.setBackgroundColor(Color.parseColor("#a67015"));
        RelativeLayout relativeLayout2 = new RelativeLayout(this);
        this.sebzmjurgg = relativeLayout2;
        relativeLayout2.setLayoutParams(new LinearLayout.LayoutParams(794, 688));
        this.sebzmjurgg.setPadding(180, WebSocketProtocol.PAYLOAD_SHORT, 175, 81);
        linearLayout.addView(this.sebzmjurgg);
        this.sebzmjurgg.setBackgroundColor(Color.parseColor("#87e126"));
        ProgressBar progressBar = new ProgressBar(this);
        this.hrravtpfie = progressBar;
        progressBar.setLayoutParams(new LinearLayout.LayoutParams(1300, 1959));
        this.hrravtpfie.setPadding(116, 32, 2, 183);
        linearLayout.addView(this.hrravtpfie);
        this.hrravtpfie.setBackgroundColor(Color.parseColor("#432c23"));
        Switch r23 = new Switch(this);
        this.fjhwmkyeyp = r23;
        r23.setLayoutParams(new LinearLayout.LayoutParams(1, TypedValues.Custom.TYPE_COLOR));
        this.fjhwmkyeyp.setPadding(BDLocation.TypeCoarseLocation, 8, 82, 127);
        linearLayout.addView(this.fjhwmkyeyp);
        this.fjhwmkyeyp.setBackgroundColor(Color.parseColor("#9d2c5f"));
        Switch r24 = new Switch(this);
        this.iwhglyytve = r24;
        r24.setLayoutParams(new LinearLayout.LayoutParams(400, 804));
        this.iwhglyytve.setPadding(1, 177, 194, 52);
        linearLayout.addView(this.iwhglyytve);
        this.iwhglyytve.setBackgroundColor(Color.parseColor("#d9bc8b"));
        ListView listView = new ListView(this);
        this.sddrafsdyj = listView;
        listView.setLayoutParams(new LinearLayout.LayoutParams(686, 347));
        this.sddrafsdyj.setPadding(136, 114, 119, 117);
        linearLayout.addView(this.sddrafsdyj);
        this.sddrafsdyj.setBackgroundColor(Color.parseColor("#012a4d"));
        SeekBar seekBar = new SeekBar(this);
        this.uldambdoxn = seekBar;
        seekBar.setLayoutParams(new LinearLayout.LayoutParams(697, 1106));
        this.uldambdoxn.setPadding(86, 86, 143, 49);
        linearLayout.addView(this.uldambdoxn);
        this.uldambdoxn.setBackgroundColor(Color.parseColor("#5466c7"));
        TextView textView = new TextView(this);
        this.fyqppjjuqk = textView;
        textView.setLayoutParams(new LinearLayout.LayoutParams(1354, 1485));
        this.fyqppjjuqk.setPadding(180, 30, 30, 62);
        linearLayout.addView(this.fyqppjjuqk);
        this.fyqppjjuqk.setBackgroundColor(Color.parseColor("#3b979e"));
        RelativeLayout relativeLayout3 = new RelativeLayout(this);
        this.urzjusximo = relativeLayout3;
        relativeLayout3.setLayoutParams(new LinearLayout.LayoutParams(277, 185));
        this.urzjusximo.setPadding(115, 128, 189, 170);
        linearLayout.addView(this.urzjusximo);
        this.urzjusximo.setBackgroundColor(Color.parseColor("#f07913"));
        ViewFlipper viewFlipper2 = new ViewFlipper(this);
        this.khmpetsshz = viewFlipper2;
        viewFlipper2.setLayoutParams(new LinearLayout.LayoutParams(1671, 1853));
        this.khmpetsshz.setPadding(49, 145, 136, 107);
        linearLayout.addView(this.khmpetsshz);
        this.khmpetsshz.setBackgroundColor(Color.parseColor("#d03ac2"));
        Button button2 = new Button(this);
        this.dtkjdjtvzx = button2;
        button2.setLayoutParams(new LinearLayout.LayoutParams(51, 1202));
        this.dtkjdjtvzx.setPadding(89, 142, 27, 171);
        linearLayout.addView(this.dtkjdjtvzx);
        this.dtkjdjtvzx.setBackgroundColor(Color.parseColor("#ca54d9"));
        ProgressBar progressBar2 = new ProgressBar(this);
        this.igftqilcoe = progressBar2;
        progressBar2.setLayoutParams(new LinearLayout.LayoutParams(1986, 1211));
        this.igftqilcoe.setPadding(197, 0, 121, 187);
        linearLayout.addView(this.igftqilcoe);
        this.igftqilcoe.setBackgroundColor(Color.parseColor("#5c2321"));
        ScrollView scrollView2 = new ScrollView(this);
        this.snwtnrdmsy = scrollView2;
        scrollView2.setLayoutParams(new LinearLayout.LayoutParams(1934, 1113));
        this.snwtnrdmsy.setPadding(179, 132, 170, 24);
        linearLayout.addView(this.snwtnrdmsy);
        this.snwtnrdmsy.setBackgroundColor(Color.parseColor("#e34024"));
        RadioButton radioButton3 = new RadioButton(this);
        this.lhompczitg = radioButton3;
        radioButton3.setLayoutParams(new LinearLayout.LayoutParams(1347, 670));
        this.lhompczitg.setPadding(106, 82, 183, 124);
        linearLayout.addView(this.lhompczitg);
        this.lhompczitg.setBackgroundColor(Color.parseColor("#d5052c"));
        ToggleButton toggleButton = new ToggleButton(this);
        this.kgsmessnuk = toggleButton;
        toggleButton.setLayoutParams(new LinearLayout.LayoutParams(1370, 1418));
        this.kgsmessnuk.setPadding(BDLocation.TypeCoarseLocation, 45, 53, 100);
        linearLayout.addView(this.kgsmessnuk);
        this.kgsmessnuk.setBackgroundColor(Color.parseColor("#2cd3df"));
        EditText editText = new EditText(this);
        this.indxdxhvog = editText;
        editText.setLayoutParams(new LinearLayout.LayoutParams(1530, 74));
        this.indxdxhvog.setPadding(145, 177, 19, 0);
        linearLayout.addView(this.indxdxhvog);
        this.indxdxhvog.setBackgroundColor(Color.parseColor("#f846d0"));
        RadioButton radioButton4 = new RadioButton(this);
        this.tksdlbxwpf = radioButton4;
        radioButton4.setLayoutParams(new LinearLayout.LayoutParams(1269, 1044));
        this.tksdlbxwpf.setPadding(94, 43, 57, 176);
        linearLayout.addView(this.tksdlbxwpf);
        this.tksdlbxwpf.setBackgroundColor(Color.parseColor("#063ac7"));
        Spinner spinner4 = new Spinner(this);
        this.rwxjfddcnt = spinner4;
        spinner4.setLayoutParams(new LinearLayout.LayoutParams(1715, 24));
        this.rwxjfddcnt.setPadding(79, 105, 134, 2);
        linearLayout.addView(this.rwxjfddcnt);
        this.rwxjfddcnt.setBackgroundColor(Color.parseColor("#f1b8d8"));
        RatingBar ratingBar4 = new RatingBar(this);
        this.krnlokpoqm = ratingBar4;
        ratingBar4.setLayoutParams(new LinearLayout.LayoutParams(1510, 1914));
        this.krnlokpoqm.setPadding(23, 146, 69, 56);
        linearLayout.addView(this.krnlokpoqm);
        this.krnlokpoqm.setBackgroundColor(Color.parseColor("#b70199"));
        TextView textView2 = new TextView(this);
        this.tyoydoouun = textView2;
        textView2.setLayoutParams(new LinearLayout.LayoutParams(418, 227));
        this.tyoydoouun.setPadding(99, 8, 140, 62);
        linearLayout.addView(this.tyoydoouun);
        this.tyoydoouun.setBackgroundColor(Color.parseColor("#d2220c"));
        RadioButton radioButton5 = new RadioButton(this);
        this.okhzuppcya = radioButton5;
        radioButton5.setLayoutParams(new LinearLayout.LayoutParams(1119, 765));
        this.okhzuppcya.setPadding(182, 177, 81, 138);
        linearLayout.addView(this.okhzuppcya);
        this.okhzuppcya.setBackgroundColor(Color.parseColor("#9fa59e"));
        RadioButton radioButton6 = new RadioButton(this);
        this.vyoopjzmez = radioButton6;
        radioButton6.setLayoutParams(new LinearLayout.LayoutParams(1894, 630));
        this.vyoopjzmez.setPadding(180, 172, 171, 197);
        linearLayout.addView(this.vyoopjzmez);
        this.vyoopjzmez.setBackgroundColor(Color.parseColor("#843777"));
        ScrollView scrollView3 = new ScrollView(this);
        this.modzltzdih = scrollView3;
        scrollView3.setLayoutParams(new LinearLayout.LayoutParams(1533, 20));
        this.modzltzdih.setPadding(169, 193, 66, 22);
        linearLayout.addView(this.modzltzdih);
        this.modzltzdih.setBackgroundColor(Color.parseColor("#6a19b9"));
        TextView textView3 = new TextView(this);
        this.gulxfkpgii = textView3;
        textView3.setLayoutParams(new LinearLayout.LayoutParams(1992, 975));
        this.gulxfkpgii.setPadding(14, 57, 147, 159);
        linearLayout.addView(this.gulxfkpgii);
        this.gulxfkpgii.setBackgroundColor(Color.parseColor("#dddf91"));
        RelativeLayout relativeLayout4 = new RelativeLayout(this);
        this.tsspzpzokz = relativeLayout4;
        relativeLayout4.setLayoutParams(new LinearLayout.LayoutParams(1845, 213));
        this.tsspzpzokz.setPadding(55, 172, 115, 24);
        linearLayout.addView(this.tsspzpzokz);
        this.tsspzpzokz.setBackgroundColor(Color.parseColor("#dba26d"));
        TextView textView4 = new TextView(this);
        this.fgndbcauxz = textView4;
        textView4.setLayoutParams(new LinearLayout.LayoutParams(859, 0));
        this.fgndbcauxz.setPadding(92, 73, 103, BDLocation.TypeServerError);
        linearLayout.addView(this.fgndbcauxz);
        this.fgndbcauxz.setBackgroundColor(Color.parseColor("#588548"));
        ScrollView scrollView4 = new ScrollView(this);
        this.bfnhzalxtn = scrollView4;
        scrollView4.setLayoutParams(new LinearLayout.LayoutParams(1479, 1002));
        this.bfnhzalxtn.setPadding(66, 144, 108, 130);
        linearLayout.addView(this.bfnhzalxtn);
        this.bfnhzalxtn.setBackgroundColor(Color.parseColor("#6f1b00"));
        LinearLayout linearLayout3 = new LinearLayout(this);
        this.jgcouujwiz = linearLayout3;
        linearLayout3.setLayoutParams(new LinearLayout.LayoutParams(844, 1625));
        this.jgcouujwiz.setPadding(157, 147, 192, 124);
        linearLayout.addView(this.jgcouujwiz);
        this.jgcouujwiz.setBackgroundColor(Color.parseColor("#5a3489"));
        DatePicker datePicker = new DatePicker(this);
        this.flxuepalds = datePicker;
        datePicker.setLayoutParams(new LinearLayout.LayoutParams(221, 1342));
        this.flxuepalds.setPadding(189, 58, 165, 171);
        linearLayout.addView(this.flxuepalds);
        this.flxuepalds.setBackgroundColor(Color.parseColor("#58dcf1"));
        TableLayout tableLayout2 = new TableLayout(this);
        this.usdqboqzas = tableLayout2;
        tableLayout2.setLayoutParams(new LinearLayout.LayoutParams(561, 543));
        this.usdqboqzas.setPadding(90, 101, 111, 35);
        linearLayout.addView(this.usdqboqzas);
        this.usdqboqzas.setBackgroundColor(Color.parseColor("#e9631c"));
        Button button3 = new Button(this);
        this.jsopdzgrac = button3;
        button3.setLayoutParams(new LinearLayout.LayoutParams(876, 45));
        this.jsopdzgrac.setPadding(45, 36, 26, 164);
        linearLayout.addView(this.jsopdzgrac);
        this.jsopdzgrac.setBackgroundColor(Color.parseColor("#2984f8"));
        EditText editText2 = new EditText(this);
        this.cetajilixm = editText2;
        editText2.setLayoutParams(new LinearLayout.LayoutParams(1965, 1529));
        this.cetajilixm.setPadding(141, 139, 3, 158);
        linearLayout.addView(this.cetajilixm);
        this.cetajilixm.setBackgroundColor(Color.parseColor("#8ef046"));
        ImageView imageView = new ImageView(this);
        this.fdbjgwgyfa = imageView;
        imageView.setLayoutParams(new LinearLayout.LayoutParams(32, 936));
        this.fdbjgwgyfa.setPadding(90, 136, 72, 30);
        linearLayout.addView(this.fdbjgwgyfa);
        this.fdbjgwgyfa.setBackgroundColor(Color.parseColor("#51162b"));
        Button button4 = new Button(this);
        this.ibdqjvodxi = button4;
        button4.setLayoutParams(new LinearLayout.LayoutParams(682, 782));
        this.ibdqjvodxi.setPadding(BDLocation.TypeServerDecryptError, 134, 53, 113);
        linearLayout.addView(this.ibdqjvodxi);
        this.ibdqjvodxi.setBackgroundColor(Color.parseColor("#891acb"));
        ScrollView scrollView5 = new ScrollView(this);
        this.xxruuiqraq = scrollView5;
        scrollView5.setLayoutParams(new LinearLayout.LayoutParams(723, 1343));
        this.xxruuiqraq.setPadding(142, 20, 133, 173);
        linearLayout.addView(this.xxruuiqraq);
        this.xxruuiqraq.setBackgroundColor(Color.parseColor("#a6648b"));
        ToggleButton toggleButton2 = new ToggleButton(this);
        this.canzvzmcja = toggleButton2;
        toggleButton2.setLayoutParams(new LinearLayout.LayoutParams(1948, 1129));
        this.canzvzmcja.setPadding(16, 190, 194, 64);
        linearLayout.addView(this.canzvzmcja);
        this.canzvzmcja.setBackgroundColor(Color.parseColor("#a81972"));
        ScrollView scrollView6 = new ScrollView(this);
        this.hwgcyowjnc = scrollView6;
        scrollView6.setLayoutParams(new LinearLayout.LayoutParams(1254, 822));
        this.hwgcyowjnc.setPadding(4, PictureConfig.CHOOSE_REQUEST, 66, 65);
        linearLayout.addView(this.hwgcyowjnc);
        this.hwgcyowjnc.setBackgroundColor(Color.parseColor("#e38f11"));
        ListView listView2 = new ListView(this);
        this.kwiepcuigo = listView2;
        listView2.setLayoutParams(new LinearLayout.LayoutParams(1203, 102));
        this.kwiepcuigo.setPadding(127, 9, 23, 171);
        linearLayout.addView(this.kwiepcuigo);
        this.kwiepcuigo.setBackgroundColor(Color.parseColor("#8f4e6a"));
        TimePicker timePicker = new TimePicker(this);
        this.gseoztqyyg = timePicker;
        timePicker.setLayoutParams(new LinearLayout.LayoutParams(1956, 626));
        this.gseoztqyyg.setPadding(64, 132, 146, 168);
        linearLayout.addView(this.gseoztqyyg);
        this.gseoztqyyg.setBackgroundColor(Color.parseColor("#fcea07"));
        TextView textView5 = new TextView(this);
        this.fhszpqhmhg = textView5;
        textView5.setLayoutParams(new LinearLayout.LayoutParams(RoomDatabase.MAX_BIND_PARAMETER_CNT, 1763));
        this.fhszpqhmhg.setPadding(178, 114, 109, 115);
        linearLayout.addView(this.fhszpqhmhg);
        this.fhszpqhmhg.setBackgroundColor(Color.parseColor("#2ab1a8"));
        ImageView imageView2 = new ImageView(this);
        this.rxflyqhqvh = imageView2;
        imageView2.setLayoutParams(new LinearLayout.LayoutParams(116, 1753));
        this.rxflyqhqvh.setPadding(20, 180, 59, 38);
        linearLayout.addView(this.rxflyqhqvh);
        this.rxflyqhqvh.setBackgroundColor(Color.parseColor("#0b9895"));
        TableLayout tableLayout3 = new TableLayout(this);
        this.ohiwdhvdjq = tableLayout3;
        tableLayout3.setLayoutParams(new LinearLayout.LayoutParams(1788, 1808));
        this.ohiwdhvdjq.setPadding(94, 140, 77, 187);
        linearLayout.addView(this.ohiwdhvdjq);
        this.ohiwdhvdjq.setBackgroundColor(Color.parseColor("#420839"));
        LinearLayout linearLayout4 = new LinearLayout(this);
        this.miyfwtkfhg = linearLayout4;
        linearLayout4.setLayoutParams(new LinearLayout.LayoutParams(38, 245));
        this.miyfwtkfhg.setPadding(112, 82, 179, 134);
        linearLayout.addView(this.miyfwtkfhg);
        this.miyfwtkfhg.setBackgroundColor(Color.parseColor("#da58ac"));
        Button button5 = new Button(this);
        this.xoaphawefx = button5;
        button5.setLayoutParams(new LinearLayout.LayoutParams(143, 1616));
        this.xoaphawefx.setPadding(103, 28, 36, 16);
        linearLayout.addView(this.xoaphawefx);
        this.xoaphawefx.setBackgroundColor(Color.parseColor("#08d3e4"));
        ViewFlipper viewFlipper3 = new ViewFlipper(this);
        this.qctqwvslzl = viewFlipper3;
        viewFlipper3.setLayoutParams(new LinearLayout.LayoutParams(276, 834));
        this.qctqwvslzl.setPadding(175, 12, 171, 191);
        linearLayout.addView(this.qctqwvslzl);
        this.qctqwvslzl.setBackgroundColor(Color.parseColor("#95a5d8"));
        ToggleButton toggleButton3 = new ToggleButton(this);
        this.bmoitjlyoo = toggleButton3;
        toggleButton3.setLayoutParams(new LinearLayout.LayoutParams(1589, 1078));
        this.bmoitjlyoo.setPadding(32, 187, 175, 1);
        linearLayout.addView(this.bmoitjlyoo);
        this.bmoitjlyoo.setBackgroundColor(Color.parseColor("#a9c4de"));
        Spinner spinner5 = new Spinner(this);
        this.zpborjzgld = spinner5;
        spinner5.setLayoutParams(new LinearLayout.LayoutParams(1473, 285));
        this.zpborjzgld.setPadding(143, 155, 14, 176);
        linearLayout.addView(this.zpborjzgld);
        this.zpborjzgld.setBackgroundColor(Color.parseColor("#1a0aee"));
        LinearLayout linearLayout5 = new LinearLayout(this);
        this.fcyywmsnyd = linearLayout5;
        linearLayout5.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.CycleType.TYPE_VISIBILITY, 697));
        this.fcyywmsnyd.setPadding(139, 106, 190, 176);
        linearLayout.addView(this.fcyywmsnyd);
        this.fcyywmsnyd.setBackgroundColor(Color.parseColor("#59fd17"));
        RatingBar ratingBar5 = new RatingBar(this);
        this.feabxfwaoe = ratingBar5;
        ratingBar5.setLayoutParams(new LinearLayout.LayoutParams(1900, 451));
        this.feabxfwaoe.setPadding(120, 146, BDLocation.TypeNetWorkLocation, 53);
        linearLayout.addView(this.feabxfwaoe);
        this.feabxfwaoe.setBackgroundColor(Color.parseColor("#ec8af9"));
        ViewFlipper viewFlipper4 = new ViewFlipper(this);
        this.lczmchwexe = viewFlipper4;
        viewFlipper4.setLayoutParams(new LinearLayout.LayoutParams(62, 737));
        this.lczmchwexe.setPadding(123, 197, 131, 8);
        linearLayout.addView(this.lczmchwexe);
        this.lczmchwexe.setBackgroundColor(Color.parseColor("#c1f65a"));
        RelativeLayout relativeLayout5 = new RelativeLayout(this);
        this.fgkjgvyfsp = relativeLayout5;
        relativeLayout5.setLayoutParams(new LinearLayout.LayoutParams(636, 1672));
        this.fgkjgvyfsp.setPadding(50, 86, 99, 120);
        linearLayout.addView(this.fgkjgvyfsp);
        this.fgkjgvyfsp.setBackgroundColor(Color.parseColor("#8e22b2"));
        LinearLayout linearLayout6 = new LinearLayout(this);
        this.hdoklpilcs = linearLayout6;
        linearLayout6.setLayoutParams(new LinearLayout.LayoutParams(528, 408));
        this.hdoklpilcs.setPadding(56, 98, 131, WebSocketProtocol.PAYLOAD_SHORT);
        linearLayout.addView(this.hdoklpilcs);
        this.hdoklpilcs.setBackgroundColor(Color.parseColor("#b5b5df"));
        TimePicker timePicker2 = new TimePicker(this);
        this.dngafhuffi = timePicker2;
        timePicker2.setLayoutParams(new LinearLayout.LayoutParams(276, 1342));
        this.dngafhuffi.setPadding(82, 148, 84, 153);
        linearLayout.addView(this.dngafhuffi);
        this.dngafhuffi.setBackgroundColor(Color.parseColor("#3196b8"));
        TimePicker timePicker3 = new TimePicker(this);
        this.qbneeygfwd = timePicker3;
        timePicker3.setLayoutParams(new LinearLayout.LayoutParams(853, 587));
        this.qbneeygfwd.setPadding(129, 32, 122, 25);
        linearLayout.addView(this.qbneeygfwd);
        this.qbneeygfwd.setBackgroundColor(Color.parseColor("#d6b065"));
        ListView listView3 = new ListView(this);
        this.vrarmhvesw = listView3;
        listView3.setLayoutParams(new LinearLayout.LayoutParams(895, 1898));
        this.vrarmhvesw.setPadding(165, 7, 113, 24);
        linearLayout.addView(this.vrarmhvesw);
        this.vrarmhvesw.setBackgroundColor(Color.parseColor("#ada758"));
        TimePicker timePicker4 = new TimePicker(this);
        this.nexoophmhr = timePicker4;
        timePicker4.setLayoutParams(new LinearLayout.LayoutParams(1896, 1223));
        this.nexoophmhr.setPadding(26, 97, 82, 114);
        linearLayout.addView(this.nexoophmhr);
        this.nexoophmhr.setBackgroundColor(Color.parseColor("#d77ab5"));
        Switch r25 = new Switch(this);
        this.cwbhbuhivf = r25;
        r25.setLayoutParams(new LinearLayout.LayoutParams(1971, 1604));
        this.cwbhbuhivf.setPadding(65, 96, 13, 118);
        linearLayout.addView(this.cwbhbuhivf);
        this.cwbhbuhivf.setBackgroundColor(Color.parseColor("#58fc44"));
        ScrollView scrollView7 = new ScrollView(this);
        this.dvhtkfratw = scrollView7;
        scrollView7.setLayoutParams(new LinearLayout.LayoutParams(GattClient.STATE_READ_DEVICE_INFO, 1373));
        this.dvhtkfratw.setPadding(30, 128, 67, 157);
        linearLayout.addView(this.dvhtkfratw);
        this.dvhtkfratw.setBackgroundColor(Color.parseColor("#ac8f8c"));
        Spinner spinner6 = new Spinner(this);
        this.scptiizmgt = spinner6;
        spinner6.setLayoutParams(new LinearLayout.LayoutParams(961, 660));
        this.scptiizmgt.setPadding(154, 36, 184, 176);
        linearLayout.addView(this.scptiizmgt);
        this.scptiizmgt.setBackgroundColor(Color.parseColor("#4f3e82"));
        ListView listView4 = new ListView(this);
        this.usadmlsgah = listView4;
        listView4.setLayoutParams(new LinearLayout.LayoutParams(11, 1519));
        this.usadmlsgah.setPadding(180, 51, 187, 127);
        linearLayout.addView(this.usadmlsgah);
        this.usadmlsgah.setBackgroundColor(Color.parseColor("#373fca"));
        FrameLayout frameLayout = new FrameLayout(this);
        this.pcrmvnsbbi = frameLayout;
        frameLayout.setLayoutParams(new LinearLayout.LayoutParams(674, 1862));
        this.pcrmvnsbbi.setPadding(145, BDLocation.TypeServerDecryptError, 130, 132);
        linearLayout.addView(this.pcrmvnsbbi);
        this.pcrmvnsbbi.setBackgroundColor(Color.parseColor("#fd792b"));
        RatingBar ratingBar6 = new RatingBar(this);
        this.ybczkgifqo = ratingBar6;
        ratingBar6.setLayoutParams(new LinearLayout.LayoutParams(1295, 17));
        this.ybczkgifqo.setPadding(93, 171, 22, 102);
        linearLayout.addView(this.ybczkgifqo);
        this.ybczkgifqo.setBackgroundColor(Color.parseColor("#bec157"));
        ScrollView scrollView8 = new ScrollView(this);
        this.qrkdzbuvdo = scrollView8;
        scrollView8.setLayoutParams(new LinearLayout.LayoutParams(362, 215));
        this.qrkdzbuvdo.setPadding(85, BDLocation.TypeServerDecryptError, 183, 98);
        linearLayout.addView(this.qrkdzbuvdo);
        this.qrkdzbuvdo.setBackgroundColor(Color.parseColor("#ca4b54"));
        ProgressBar progressBar3 = new ProgressBar(this);
        this.wnwfjlrvmt = progressBar3;
        progressBar3.setLayoutParams(new LinearLayout.LayoutParams(120, 1610));
        this.wnwfjlrvmt.setPadding(155, 176, 13, 85);
        linearLayout.addView(this.wnwfjlrvmt);
        this.wnwfjlrvmt.setBackgroundColor(Color.parseColor("#ab23a9"));
        ViewFlipper viewFlipper5 = new ViewFlipper(this);
        this.nykrfzgmna = viewFlipper5;
        viewFlipper5.setLayoutParams(new LinearLayout.LayoutParams(1047, 86));
        this.nykrfzgmna.setPadding(173, 152, 3, 133);
        linearLayout.addView(this.nykrfzgmna);
        this.nykrfzgmna.setBackgroundColor(Color.parseColor("#ad9c70"));
        SeekBar seekBar2 = new SeekBar(this);
        this.hcevclakfy = seekBar2;
        seekBar2.setLayoutParams(new LinearLayout.LayoutParams(512, 1617));
        this.hcevclakfy.setPadding(195, 183, 121, 54);
        linearLayout.addView(this.hcevclakfy);
        this.hcevclakfy.setBackgroundColor(Color.parseColor("#ce2932"));
        ScrollView scrollView9 = new ScrollView(this);
        this.uwqxczkfsi = scrollView9;
        scrollView9.setLayoutParams(new LinearLayout.LayoutParams(1057, 68));
        this.uwqxczkfsi.setPadding(59, 16, 94, 80);
        linearLayout.addView(this.uwqxczkfsi);
        this.uwqxczkfsi.setBackgroundColor(Color.parseColor("#568aa5"));
        TableLayout tableLayout4 = new TableLayout(this);
        this.wmzwalgred = tableLayout4;
        tableLayout4.setLayoutParams(new LinearLayout.LayoutParams(1853, 1489));
        this.wmzwalgred.setPadding(154, 28, 47, 102);
        linearLayout.addView(this.wmzwalgred);
        this.wmzwalgred.setBackgroundColor(Color.parseColor("#b30c45"));
        DatePicker datePicker2 = new DatePicker(this);
        this.eoauwoswnx = datePicker2;
        datePicker2.setLayoutParams(new LinearLayout.LayoutParams(794, 1413));
        this.eoauwoswnx.setPadding(113, 192, 64, 131);
        linearLayout.addView(this.eoauwoswnx);
        this.eoauwoswnx.setBackgroundColor(Color.parseColor("#e65f00"));
        Spinner spinner7 = new Spinner(this);
        this.iykzotdefq = spinner7;
        spinner7.setLayoutParams(new LinearLayout.LayoutParams(142, 277));
        this.iykzotdefq.setPadding(41, 97, 109, 133);
        linearLayout.addView(this.iykzotdefq);
        this.iykzotdefq.setBackgroundColor(Color.parseColor("#f04d42"));
        RelativeLayout relativeLayout6 = new RelativeLayout(this);
        this.etvphmqkef = relativeLayout6;
        relativeLayout6.setLayoutParams(new LinearLayout.LayoutParams(1006, 1518));
        this.etvphmqkef.setPadding(125, 114, 20, 180);
        linearLayout.addView(this.etvphmqkef);
        this.etvphmqkef.setBackgroundColor(Color.parseColor("#686761"));
        ScrollView scrollView10 = new ScrollView(this);
        this.ftpxbnftuc = scrollView10;
        scrollView10.setLayoutParams(new LinearLayout.LayoutParams(1275, 1805));
        this.ftpxbnftuc.setPadding(156, 22, BDLocation.TypeServerDecryptError, 172);
        linearLayout.addView(this.ftpxbnftuc);
        this.ftpxbnftuc.setBackgroundColor(Color.parseColor("#2ef41b"));
        DatePicker datePicker3 = new DatePicker(this);
        this.llykawtjyj = datePicker3;
        datePicker3.setLayoutParams(new LinearLayout.LayoutParams(834, 758));
        this.llykawtjyj.setPadding(183, 192, 88, WebSocketProtocol.PAYLOAD_SHORT);
        linearLayout.addView(this.llykawtjyj);
        this.llykawtjyj.setBackgroundColor(Color.parseColor("#6426b7"));
        Button button6 = new Button(this);
        this.boxygdmqdp = button6;
        button6.setLayoutParams(new LinearLayout.LayoutParams(376, 1432));
        this.boxygdmqdp.setPadding(37, 94, 121, 7);
        linearLayout.addView(this.boxygdmqdp);
        this.boxygdmqdp.setBackgroundColor(Color.parseColor("#8f1b30"));
        ProgressBar progressBar4 = new ProgressBar(this);
        this.qzmrkolmjp = progressBar4;
        progressBar4.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.Custom.TYPE_BOOLEAN, 1173));
        this.qzmrkolmjp.setPadding(73, 94, 186, 102);
        linearLayout.addView(this.qzmrkolmjp);
        this.qzmrkolmjp.setBackgroundColor(Color.parseColor("#db8660"));
        RelativeLayout relativeLayout7 = new RelativeLayout(this);
        this.tbpyrtpezk = relativeLayout7;
        relativeLayout7.setLayoutParams(new LinearLayout.LayoutParams(1201, 1112));
        this.tbpyrtpezk.setPadding(164, 153, 93, 145);
        linearLayout.addView(this.tbpyrtpezk);
        this.tbpyrtpezk.setBackgroundColor(Color.parseColor("#03b84f"));
        LinearLayout linearLayout7 = new LinearLayout(this);
        this.vatpgiabgq = linearLayout7;
        linearLayout7.setLayoutParams(new LinearLayout.LayoutParams(1032, 1720));
        this.vatpgiabgq.setPadding(61, 84, 179, 42);
        linearLayout.addView(this.vatpgiabgq);
        this.vatpgiabgq.setBackgroundColor(Color.parseColor("#46dba7"));
        TextView textView6 = new TextView(this);
        this.xisoomneca = textView6;
        textView6.setLayoutParams(new LinearLayout.LayoutParams(1086, 2));
        this.xisoomneca.setPadding(129, 53, 164, 195);
        linearLayout.addView(this.xisoomneca);
        this.xisoomneca.setBackgroundColor(Color.parseColor("#28a62d"));
        Button button7 = new Button(this);
        this.rqmkpfiddm = button7;
        button7.setLayoutParams(new LinearLayout.LayoutParams(1366, 204));
        this.rqmkpfiddm.setPadding(80, 58, 77, 49);
        linearLayout.addView(this.rqmkpfiddm);
        this.rqmkpfiddm.setBackgroundColor(Color.parseColor("#9fddbd"));
        GridView gridView = new GridView(this);
        this.ubmzuybztx = gridView;
        gridView.setLayoutParams(new LinearLayout.LayoutParams(1631, 1196));
        this.ubmzuybztx.setPadding(23, 156, 175, 181);
        linearLayout.addView(this.ubmzuybztx);
        this.ubmzuybztx.setBackgroundColor(Color.parseColor("#19e509"));
        TextView textView7 = new TextView(this);
        this.swnpsuicgh = textView7;
        textView7.setLayoutParams(new LinearLayout.LayoutParams(386, 1903));
        this.swnpsuicgh.setPadding(100, 170, 191, 6);
        linearLayout.addView(this.swnpsuicgh);
        this.swnpsuicgh.setBackgroundColor(Color.parseColor("#d25794"));
        ScrollView scrollView11 = new ScrollView(this);
        this.hkwmztzzwy = scrollView11;
        scrollView11.setLayoutParams(new LinearLayout.LayoutParams(639, 734));
        this.hkwmztzzwy.setPadding(129, 138, 7, 3);
        linearLayout.addView(this.hkwmztzzwy);
        this.hkwmztzzwy.setBackgroundColor(Color.parseColor("#9a0a8d"));
        ListView listView5 = new ListView(this);
        this.okvpdkffvr = listView5;
        listView5.setLayoutParams(new LinearLayout.LayoutParams(1233, 1779));
        this.okvpdkffvr.setPadding(40, 26, 15, 189);
        linearLayout.addView(this.okvpdkffvr);
        this.okvpdkffvr.setBackgroundColor(Color.parseColor("#766255"));
        RatingBar ratingBar7 = new RatingBar(this);
        this.ibromnutew = ratingBar7;
        ratingBar7.setLayoutParams(new LinearLayout.LayoutParams(1572, 418));
        this.ibromnutew.setPadding(151, 125, 136, 130);
        linearLayout.addView(this.ibromnutew);
        this.ibromnutew.setBackgroundColor(Color.parseColor("#6620ce"));
        CheckBox checkBox = new CheckBox(this);
        this.dotapmxcny = checkBox;
        checkBox.setLayoutParams(new LinearLayout.LayoutParams(1991, 891));
        this.dotapmxcny.setPadding(0, 112, 30, 157);
        linearLayout.addView(this.dotapmxcny);
        this.dotapmxcny.setBackgroundColor(Color.parseColor("#af76ed"));
        ListView listView6 = new ListView(this);
        this.eqbthbrmhw = listView6;
        listView6.setLayoutParams(new LinearLayout.LayoutParams(1788, 1269));
        this.eqbthbrmhw.setPadding(104, PictureConfig.CHOOSE_REQUEST, 32, 193);
        linearLayout.addView(this.eqbthbrmhw);
        this.eqbthbrmhw.setBackgroundColor(Color.parseColor("#7ee17b"));
        TimePicker timePicker5 = new TimePicker(this);
        this.hvyiwhbjnb = timePicker5;
        timePicker5.setLayoutParams(new LinearLayout.LayoutParams(576, 1869));
        this.hvyiwhbjnb.setPadding(123, 117, 158, 181);
        linearLayout.addView(this.hvyiwhbjnb);
        this.hvyiwhbjnb.setBackgroundColor(Color.parseColor("#9a438a"));
        ScrollView scrollView12 = new ScrollView(this);
        this.xusnbbazzy = scrollView12;
        scrollView12.setLayoutParams(new LinearLayout.LayoutParams(992, 580));
        this.xusnbbazzy.setPadding(192, 185, 143, 50);
        linearLayout.addView(this.xusnbbazzy);
        this.xusnbbazzy.setBackgroundColor(Color.parseColor("#104f41"));
        CheckBox checkBox2 = new CheckBox(this);
        this.zkyclfkipq = checkBox2;
        checkBox2.setLayoutParams(new LinearLayout.LayoutParams(1985, 1647));
        this.zkyclfkipq.setPadding(182, 124, 133, 24);
        linearLayout.addView(this.zkyclfkipq);
        this.zkyclfkipq.setBackgroundColor(Color.parseColor("#2c6a29"));
        Switch r26 = new Switch(this);
        this.reddygurfl = r26;
        r26.setLayoutParams(new LinearLayout.LayoutParams(98, 1984));
        this.reddygurfl.setPadding(27, 175, 46, 15);
        linearLayout.addView(this.reddygurfl);
        this.reddygurfl.setBackgroundColor(Color.parseColor("#bc3476"));
        ToggleButton toggleButton4 = new ToggleButton(this);
        this.frxadwszpt = toggleButton4;
        toggleButton4.setLayoutParams(new LinearLayout.LayoutParams(1498, 1578));
        this.frxadwszpt.setPadding(4, 113, 74, 26);
        linearLayout.addView(this.frxadwszpt);
        this.frxadwszpt.setBackgroundColor(Color.parseColor("#8126eb"));
        TableLayout tableLayout5 = new TableLayout(this);
        this.zxjzubgvme = tableLayout5;
        tableLayout5.setLayoutParams(new LinearLayout.LayoutParams(1857, 826));
        this.zxjzubgvme.setPadding(70, 5, 163, 110);
        linearLayout.addView(this.zxjzubgvme);
        this.zxjzubgvme.setBackgroundColor(Color.parseColor("#826636"));
        TableLayout tableLayout6 = new TableLayout(this);
        this.opjnhpqgqx = tableLayout6;
        tableLayout6.setLayoutParams(new LinearLayout.LayoutParams(485, 1770));
        this.opjnhpqgqx.setPadding(0, 154, 181, 145);
        linearLayout.addView(this.opjnhpqgqx);
        this.opjnhpqgqx.setBackgroundColor(Color.parseColor("#b3e1a8"));
        GridView gridView2 = new GridView(this);
        this.uybsgbqfib = gridView2;
        gridView2.setLayoutParams(new LinearLayout.LayoutParams(1139, 1672));
        this.uybsgbqfib.setPadding(163, 1, 179, 94);
        linearLayout.addView(this.uybsgbqfib);
        this.uybsgbqfib.setBackgroundColor(Color.parseColor("#dda73d"));
        ScrollView scrollView13 = new ScrollView(this);
        this.kkdnnyschm = scrollView13;
        scrollView13.setLayoutParams(new LinearLayout.LayoutParams(1766, 1180));
        this.kkdnnyschm.setPadding(88, 121, 146, 109);
        linearLayout.addView(this.kkdnnyschm);
        this.kkdnnyschm.setBackgroundColor(Color.parseColor("#56b244"));
        Spinner spinner8 = new Spinner(this);
        this.ptdclhcfvw = spinner8;
        spinner8.setLayoutParams(new LinearLayout.LayoutParams(24, 1935));
        this.ptdclhcfvw.setPadding(45, 94, 109, 56);
        linearLayout.addView(this.ptdclhcfvw);
        this.ptdclhcfvw.setBackgroundColor(Color.parseColor("#c13fd4"));
        TextView textView8 = new TextView(this);
        this.lxvyrlvvqs = textView8;
        textView8.setLayoutParams(new LinearLayout.LayoutParams(860, 128));
        this.lxvyrlvvqs.setPadding(123, 120, 53, BDLocation.TypeNetWorkLocation);
        linearLayout.addView(this.lxvyrlvvqs);
        this.lxvyrlvvqs.setBackgroundColor(Color.parseColor("#28515c"));
        RelativeLayout relativeLayout8 = new RelativeLayout(this);
        this.lzgmcjtfmv = relativeLayout8;
        relativeLayout8.setLayoutParams(new LinearLayout.LayoutParams(1933, 8));
        this.lzgmcjtfmv.setPadding(62, 96, 28, 39);
        linearLayout.addView(this.lzgmcjtfmv);
        this.lzgmcjtfmv.setBackgroundColor(Color.parseColor("#a6f9bc"));
        Switch r27 = new Switch(this);
        this.rvfksqkltj = r27;
        r27.setLayoutParams(new LinearLayout.LayoutParams(205, 86));
        this.rvfksqkltj.setPadding(10, 53, 110, 112);
        linearLayout.addView(this.rvfksqkltj);
        this.rvfksqkltj.setBackgroundColor(Color.parseColor("#4c8554"));
        DatePicker datePicker4 = new DatePicker(this);
        this.dahuigvrri = datePicker4;
        datePicker4.setLayoutParams(new LinearLayout.LayoutParams(1333, PointerIconCompat.TYPE_GRABBING));
        this.dahuigvrri.setPadding(110, 28, 60, 129);
        linearLayout.addView(this.dahuigvrri);
        this.dahuigvrri.setBackgroundColor(Color.parseColor("#bb77af"));
        RadioButton radioButton7 = new RadioButton(this);
        this.fimskhvppz = radioButton7;
        radioButton7.setLayoutParams(new LinearLayout.LayoutParams(1981, 1361));
        this.fimskhvppz.setPadding(121, 109, 85, 25);
        linearLayout.addView(this.fimskhvppz);
        this.fimskhvppz.setBackgroundColor(Color.parseColor("#e84101"));
        Switch r28 = new Switch(this);
        this.pjsbgqitih = r28;
        r28.setLayoutParams(new LinearLayout.LayoutParams(975, 1433));
        this.pjsbgqitih.setPadding(86, 65, 66, 52);
        linearLayout.addView(this.pjsbgqitih);
        this.pjsbgqitih.setBackgroundColor(Color.parseColor("#329529"));
        GridView gridView3 = new GridView(this);
        this.pywiyhruua = gridView3;
        gridView3.setLayoutParams(new LinearLayout.LayoutParams(230, 1431));
        this.pywiyhruua.setPadding(125, 1, 149, 60);
        linearLayout.addView(this.pywiyhruua);
        this.pywiyhruua.setBackgroundColor(Color.parseColor("#08b298"));
        GridView gridView4 = new GridView(this);
        this.xwyegejhpk = gridView4;
        gridView4.setLayoutParams(new LinearLayout.LayoutParams(1846, 1356));
        this.xwyegejhpk.setPadding(175, 2, 38, 155);
        linearLayout.addView(this.xwyegejhpk);
        this.xwyegejhpk.setBackgroundColor(Color.parseColor("#24ad05"));
        ProgressBar progressBar5 = new ProgressBar(this);
        this.cpjmqhkcaa = progressBar5;
        progressBar5.setLayoutParams(new LinearLayout.LayoutParams(1615, 895));
        this.cpjmqhkcaa.setPadding(37, 140, 123, 171);
        linearLayout.addView(this.cpjmqhkcaa);
        this.cpjmqhkcaa.setBackgroundColor(Color.parseColor("#7b101e"));
        RatingBar ratingBar8 = new RatingBar(this);
        this.ztvjxnuuoi = ratingBar8;
        ratingBar8.setLayoutParams(new LinearLayout.LayoutParams(730, 644));
        this.ztvjxnuuoi.setPadding(79, 10, 52, 15);
        linearLayout.addView(this.ztvjxnuuoi);
        this.ztvjxnuuoi.setBackgroundColor(Color.parseColor("#19e9f9"));
        SeekBar seekBar3 = new SeekBar(this);
        this.wvzgosjkkn = seekBar3;
        seekBar3.setLayoutParams(new LinearLayout.LayoutParams(984, 1474));
        this.wvzgosjkkn.setPadding(100, 131, 31, 147);
        linearLayout.addView(this.wvzgosjkkn);
        this.wvzgosjkkn.setBackgroundColor(Color.parseColor("#dfb097"));
        GridView gridView5 = new GridView(this);
        this.pymwqrqzbm = gridView5;
        gridView5.setLayoutParams(new LinearLayout.LayoutParams(251, 1653));
        this.pymwqrqzbm.setPadding(43, 22, 149, 166);
        linearLayout.addView(this.pymwqrqzbm);
        this.pymwqrqzbm.setBackgroundColor(Color.parseColor("#b7e779"));
        TimePicker timePicker6 = new TimePicker(this);
        this.lciqchughk = timePicker6;
        timePicker6.setLayoutParams(new LinearLayout.LayoutParams(970, CropImage.CROP_IMAGE_ACTIVITY_REQUEST_CODE));
        this.lciqchughk.setPadding(149, 124, 137, 153);
        linearLayout.addView(this.lciqchughk);
        this.lciqchughk.setBackgroundColor(Color.parseColor("#da771a"));
        RadioButton radioButton8 = new RadioButton(this);
        this.oghrzungad = radioButton8;
        radioButton8.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.MotionType.TYPE_ANIMATE_RELATIVE_TO, 643));
        this.oghrzungad.setPadding(52, 95, 153, 72);
        linearLayout.addView(this.oghrzungad);
        this.oghrzungad.setBackgroundColor(Color.parseColor("#d868b6"));
        RatingBar ratingBar9 = new RatingBar(this);
        this.ctvcsghszh = ratingBar9;
        ratingBar9.setLayoutParams(new LinearLayout.LayoutParams(1226, 1480));
        this.ctvcsghszh.setPadding(140, 65, 68, 14);
        linearLayout.addView(this.ctvcsghszh);
        this.ctvcsghszh.setBackgroundColor(Color.parseColor("#bdf89b"));
        Switch r29 = new Switch(this);
        this.emphcdqcoe = r29;
        r29.setLayoutParams(new LinearLayout.LayoutParams(755, 132));
        this.emphcdqcoe.setPadding(21, 63, 191, 46);
        linearLayout.addView(this.emphcdqcoe);
        this.emphcdqcoe.setBackgroundColor(Color.parseColor("#60445a"));
        FrameLayout frameLayout2 = new FrameLayout(this);
        this.znyjcviylb = frameLayout2;
        frameLayout2.setLayoutParams(new LinearLayout.LayoutParams(1782, 1816));
        this.znyjcviylb.setPadding(2, 187, 4, 124);
        linearLayout.addView(this.znyjcviylb);
        this.znyjcviylb.setBackgroundColor(Color.parseColor("#39595e"));
        Spinner spinner9 = new Spinner(this);
        this.uicdchkcyw = spinner9;
        spinner9.setLayoutParams(new LinearLayout.LayoutParams(23, 368));
        this.uicdchkcyw.setPadding(170, 88, 89, 170);
        linearLayout.addView(this.uicdchkcyw);
        this.uicdchkcyw.setBackgroundColor(Color.parseColor("#fe43e5"));
        RadioButton radioButton9 = new RadioButton(this);
        this.lwfilkkgdn = radioButton9;
        radioButton9.setLayoutParams(new LinearLayout.LayoutParams(549, 1867));
        this.lwfilkkgdn.setPadding(64, 71, 186, 71);
        linearLayout.addView(this.lwfilkkgdn);
        this.lwfilkkgdn.setBackgroundColor(Color.parseColor("#3c51c3"));
        ViewFlipper viewFlipper6 = new ViewFlipper(this);
        this.yfwgroqdrx = viewFlipper6;
        viewFlipper6.setLayoutParams(new LinearLayout.LayoutParams(559, 1536));
        this.yfwgroqdrx.setPadding(17, 0, 75, 91);
        linearLayout.addView(this.yfwgroqdrx);
        this.yfwgroqdrx.setBackgroundColor(Color.parseColor("#7e82dd"));
        ProgressBar progressBar6 = new ProgressBar(this);
        this.nfdknpboam = progressBar6;
        progressBar6.setLayoutParams(new LinearLayout.LayoutParams(953, 245));
        this.nfdknpboam.setPadding(177, 117, 149, 166);
        linearLayout.addView(this.nfdknpboam);
        this.nfdknpboam.setBackgroundColor(Color.parseColor("#715d0a"));
        TimePicker timePicker7 = new TimePicker(this);
        this.gmdatfmpyx = timePicker7;
        timePicker7.setLayoutParams(new LinearLayout.LayoutParams(1897, 1187));
        this.gmdatfmpyx.setPadding(42, 24, 156, 22);
        linearLayout.addView(this.gmdatfmpyx);
        this.gmdatfmpyx.setBackgroundColor(Color.parseColor("#1bb663"));
        LinearLayout linearLayout8 = new LinearLayout(this);
        this.eqswpevhoz = linearLayout8;
        linearLayout8.setLayoutParams(new LinearLayout.LayoutParams(1951, 364));
        this.eqswpevhoz.setPadding(75, 125, 74, 56);
        linearLayout.addView(this.eqswpevhoz);
        this.eqswpevhoz.setBackgroundColor(Color.parseColor("#34ebcf"));
        RadioButton radioButton10 = new RadioButton(this);
        this.wlvmujfhkr = radioButton10;
        radioButton10.setLayoutParams(new LinearLayout.LayoutParams(1357, 53));
        this.wlvmujfhkr.setPadding(65, 9, 82, 38);
        linearLayout.addView(this.wlvmujfhkr);
        this.wlvmujfhkr.setBackgroundColor(Color.parseColor("#f71668"));
        FrameLayout frameLayout3 = new FrameLayout(this);
        this.rvylknwqym = frameLayout3;
        frameLayout3.setLayoutParams(new LinearLayout.LayoutParams(1261, 1446));
        this.rvylknwqym.setPadding(37, 0, 172, 23);
        linearLayout.addView(this.rvylknwqym);
        this.rvylknwqym.setBackgroundColor(Color.parseColor("#3dc38d"));
        TableLayout tableLayout7 = new TableLayout(this);
        this.zwdersjqha = tableLayout7;
        tableLayout7.setLayoutParams(new LinearLayout.LayoutParams(BluetoothClassImpl.Device.PERIPHERAL_KEYBOARD, 982));
        this.zwdersjqha.setPadding(138, 30, 48, 46);
        linearLayout.addView(this.zwdersjqha);
        this.zwdersjqha.setBackgroundColor(Color.parseColor("#cb3206"));
        GridView gridView6 = new GridView(this);
        this.exeeoerweq = gridView6;
        gridView6.setLayoutParams(new LinearLayout.LayoutParams(1345, 349));
        this.exeeoerweq.setPadding(9, 174, 130, 137);
        linearLayout.addView(this.exeeoerweq);
        this.exeeoerweq.setBackgroundColor(Color.parseColor("#313075"));
        CheckBox checkBox3 = new CheckBox(this);
        this.lfspaepblc = checkBox3;
        checkBox3.setLayoutParams(new LinearLayout.LayoutParams(782, 890));
        this.lfspaepblc.setPadding(139, 150, 10, 154);
        linearLayout.addView(this.lfspaepblc);
        this.lfspaepblc.setBackgroundColor(Color.parseColor("#94de83"));
        GridView gridView7 = new GridView(this);
        this.qqykapiukj = gridView7;
        gridView7.setLayoutParams(new LinearLayout.LayoutParams(1415, PointerIconCompat.TYPE_ZOOM_OUT));
        this.qqykapiukj.setPadding(42, 83, 158, 122);
        linearLayout.addView(this.qqykapiukj);
        this.qqykapiukj.setBackgroundColor(Color.parseColor("#fad232"));
        DatePicker datePicker5 = new DatePicker(this);
        this.iqmzztptdw = datePicker5;
        datePicker5.setLayoutParams(new LinearLayout.LayoutParams(1197, 323));
        this.iqmzztptdw.setPadding(124, 48, 54, 170);
        linearLayout.addView(this.iqmzztptdw);
        this.iqmzztptdw.setBackgroundColor(Color.parseColor("#5223a3"));
        Button button8 = new Button(this);
        this.tbpwjghhth = button8;
        button8.setLayoutParams(new LinearLayout.LayoutParams(1505, 479));
        this.tbpwjghhth.setPadding(197, 0, 171, 180);
        linearLayout.addView(this.tbpwjghhth);
        this.tbpwjghhth.setBackgroundColor(Color.parseColor("#20e947"));
        RadioButton radioButton11 = new RadioButton(this);
        this.wqdtsfjyyn = radioButton11;
        radioButton11.setLayoutParams(new LinearLayout.LayoutParams(464, 1449));
        this.wqdtsfjyyn.setPadding(80, 173, 100, 183);
        linearLayout.addView(this.wqdtsfjyyn);
        this.wqdtsfjyyn.setBackgroundColor(Color.parseColor("#c810d9"));
        RadioButton radioButton12 = new RadioButton(this);
        this.oulcunwije = radioButton12;
        radioButton12.setLayoutParams(new LinearLayout.LayoutParams(303, 678));
        this.oulcunwije.setPadding(187, 193, 53, 41);
        linearLayout.addView(this.oulcunwije);
        this.oulcunwije.setBackgroundColor(Color.parseColor("#0780a0"));
        SeekBar seekBar4 = new SeekBar(this);
        this.kgyzsfwesf = seekBar4;
        seekBar4.setLayoutParams(new LinearLayout.LayoutParams(1200, 356));
        this.kgyzsfwesf.setPadding(196, 154, 197, 45);
        linearLayout.addView(this.kgyzsfwesf);
        this.kgyzsfwesf.setBackgroundColor(Color.parseColor("#bc2a47"));
        ListView listView7 = new ListView(this);
        this.otdeetksri = listView7;
        listView7.setLayoutParams(new LinearLayout.LayoutParams(200, 1379));
        this.otdeetksri.setPadding(43, 146, 28, 180);
        linearLayout.addView(this.otdeetksri);
        this.otdeetksri.setBackgroundColor(Color.parseColor("#0ddd64"));
        Spinner spinner10 = new Spinner(this);
        this.jkgojdvkov = spinner10;
        spinner10.setLayoutParams(new LinearLayout.LayoutParams(1267, 1133));
        this.jkgojdvkov.setPadding(101, 107, 78, 40);
        linearLayout.addView(this.jkgojdvkov);
        this.jkgojdvkov.setBackgroundColor(Color.parseColor("#dff5bd"));
        Spinner spinner11 = new Spinner(this);
        this.ckqvwzxalj = spinner11;
        spinner11.setLayoutParams(new LinearLayout.LayoutParams(526, 185));
        this.ckqvwzxalj.setPadding(35, 25, 104, 68);
        linearLayout.addView(this.ckqvwzxalj);
        this.ckqvwzxalj.setBackgroundColor(Color.parseColor("#8a5e95"));
        SeekBar seekBar5 = new SeekBar(this);
        this.xobubllglj = seekBar5;
        seekBar5.setLayoutParams(new LinearLayout.LayoutParams(263, 833));
        this.xobubllglj.setPadding(125, BDLocation.TypeServerDecryptError, 101, 88);
        linearLayout.addView(this.xobubllglj);
        this.xobubllglj.setBackgroundColor(Color.parseColor("#d30452"));
        TableLayout tableLayout8 = new TableLayout(this);
        this.uiavkzvzhp = tableLayout8;
        tableLayout8.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.AttributesType.TYPE_PATH_ROTATE, 1132));
        this.uiavkzvzhp.setPadding(94, 144, 108, 128);
        linearLayout.addView(this.uiavkzvzhp);
        this.uiavkzvzhp.setBackgroundColor(Color.parseColor("#f5c952"));
        RatingBar ratingBar10 = new RatingBar(this);
        this.hzqxkexqez = ratingBar10;
        ratingBar10.setLayoutParams(new LinearLayout.LayoutParams(1511, 47));
        this.hzqxkexqez.setPadding(94, 23, 33, 13);
        linearLayout.addView(this.hzqxkexqez);
        this.hzqxkexqez.setBackgroundColor(Color.parseColor("#7938b6"));
        GridView gridView8 = new GridView(this);
        this.lnovxzaodw = gridView8;
        gridView8.setLayoutParams(new LinearLayout.LayoutParams(1850, 1140));
        this.lnovxzaodw.setPadding(6, 121, 37, 21);
        linearLayout.addView(this.lnovxzaodw);
        this.lnovxzaodw.setBackgroundColor(Color.parseColor("#bd004a"));
        LinearLayout linearLayout9 = new LinearLayout(this);
        this.lqpzhtfegf = linearLayout9;
        linearLayout9.setLayoutParams(new LinearLayout.LayoutParams(1331, 1749));
        this.lqpzhtfegf.setPadding(163, 5, 61, 116);
        linearLayout.addView(this.lqpzhtfegf);
        this.lqpzhtfegf.setBackgroundColor(Color.parseColor("#7be08e"));
        TextView textView9 = new TextView(this);
        this.reflblehdy = textView9;
        textView9.setLayoutParams(new LinearLayout.LayoutParams(1302, 1515));
        this.reflblehdy.setPadding(3, 88, 75, 100);
        linearLayout.addView(this.reflblehdy);
        this.reflblehdy.setBackgroundColor(Color.parseColor("#012b6b"));
        RelativeLayout relativeLayout9 = new RelativeLayout(this);
        this.oevwleuzus = relativeLayout9;
        relativeLayout9.setLayoutParams(new LinearLayout.LayoutParams(1834, 1863));
        this.oevwleuzus.setPadding(189, 84, 35, 145);
        linearLayout.addView(this.oevwleuzus);
        this.oevwleuzus.setBackgroundColor(Color.parseColor("#474159"));
        ListView listView8 = new ListView(this);
        this.gjaskzlwsu = listView8;
        listView8.setLayoutParams(new LinearLayout.LayoutParams(1899, 154));
        this.gjaskzlwsu.setPadding(120, 13, 190, 181);
        linearLayout.addView(this.gjaskzlwsu);
        this.gjaskzlwsu.setBackgroundColor(Color.parseColor("#a79c78"));
        GridView gridView9 = new GridView(this);
        this.ipoqumbopz = gridView9;
        gridView9.setLayoutParams(new LinearLayout.LayoutParams(627, 825));
        this.ipoqumbopz.setPadding(130, 26, 12, 59);
        linearLayout.addView(this.ipoqumbopz);
        this.ipoqumbopz.setBackgroundColor(Color.parseColor("#46f0cd"));
        ViewFlipper viewFlipper7 = new ViewFlipper(this);
        this.lxilbyuzny = viewFlipper7;
        viewFlipper7.setLayoutParams(new LinearLayout.LayoutParams(620, 1377));
        this.lxilbyuzny.setPadding(131, 16, 136, 64);
        linearLayout.addView(this.lxilbyuzny);
        this.lxilbyuzny.setBackgroundColor(Color.parseColor("#51a1e9"));
        Switch r210 = new Switch(this);
        this.dcmvhcckgv = r210;
        r210.setLayoutParams(new LinearLayout.LayoutParams(1054, 544));
        this.dcmvhcckgv.setPadding(22, 186, 77, 84);
        linearLayout.addView(this.dcmvhcckgv);
        this.dcmvhcckgv.setBackgroundColor(Color.parseColor("#797f7d"));
        Switch r211 = new Switch(this);
        this.jwcbdtqxvc = r211;
        r211.setLayoutParams(new LinearLayout.LayoutParams(872, 172));
        this.jwcbdtqxvc.setPadding(195, 4, 32, 199);
        linearLayout.addView(this.jwcbdtqxvc);
        this.jwcbdtqxvc.setBackgroundColor(Color.parseColor("#0a7409"));
        RatingBar ratingBar11 = new RatingBar(this);
        this.djetpjcsmk = ratingBar11;
        ratingBar11.setLayoutParams(new LinearLayout.LayoutParams(1958, 358));
        this.djetpjcsmk.setPadding(101, 38, 154, 14);
        linearLayout.addView(this.djetpjcsmk);
        this.djetpjcsmk.setBackgroundColor(Color.parseColor("#f63f63"));
        TimePicker timePicker8 = new TimePicker(this);
        this.hmrcjfpgvs = timePicker8;
        timePicker8.setLayoutParams(new LinearLayout.LayoutParams(135, 1999));
        this.hmrcjfpgvs.setPadding(99, 37, 123, 13);
        linearLayout.addView(this.hmrcjfpgvs);
        this.hmrcjfpgvs.setBackgroundColor(Color.parseColor("#43dc9d"));
        RelativeLayout relativeLayout10 = new RelativeLayout(this);
        this.ftydugoite = relativeLayout10;
        relativeLayout10.setLayoutParams(new LinearLayout.LayoutParams(1312, 1427));
        this.ftydugoite.setPadding(133, 108, 149, 24);
        linearLayout.addView(this.ftydugoite);
        this.ftydugoite.setBackgroundColor(Color.parseColor("#7ffde0"));
        ProgressBar progressBar7 = new ProgressBar(this);
        this.uruzlfhrak = progressBar7;
        progressBar7.setLayoutParams(new LinearLayout.LayoutParams(10, 140));
        this.uruzlfhrak.setPadding(5, 146, 108, 107);
        linearLayout.addView(this.uruzlfhrak);
        this.uruzlfhrak.setBackgroundColor(Color.parseColor("#a0e5a1"));
        TimePicker timePicker9 = new TimePicker(this);
        this.lfruqbzhcm = timePicker9;
        timePicker9.setLayoutParams(new LinearLayout.LayoutParams(1436, 101));
        this.lfruqbzhcm.setPadding(127, 165, 78, 128);
        linearLayout.addView(this.lfruqbzhcm);
        this.lfruqbzhcm.setBackgroundColor(Color.parseColor("#26de0c"));
        RelativeLayout relativeLayout11 = new RelativeLayout(this);
        this.lnoztldwxx = relativeLayout11;
        relativeLayout11.setLayoutParams(new LinearLayout.LayoutParams(637, 1096));
        this.lnoztldwxx.setPadding(38, 52, 108, 150);
        linearLayout.addView(this.lnoztldwxx);
        this.lnoztldwxx.setBackgroundColor(Color.parseColor("#65b4e8"));
        EditText editText3 = new EditText(this);
        this.iftzeogcug = editText3;
        editText3.setLayoutParams(new LinearLayout.LayoutParams(1057, 1610));
        this.iftzeogcug.setPadding(149, 50, 92, 135);
        linearLayout.addView(this.iftzeogcug);
        this.iftzeogcug.setBackgroundColor(Color.parseColor("#f7a6da"));
        LinearLayout linearLayout10 = new LinearLayout(this);
        this.evuqskibiq = linearLayout10;
        linearLayout10.setLayoutParams(new LinearLayout.LayoutParams(1847, 1962));
        this.evuqskibiq.setPadding(31, 166, 57, 11);
        linearLayout.addView(this.evuqskibiq);
        this.evuqskibiq.setBackgroundColor(Color.parseColor("#b37bb6"));
        DatePicker datePicker6 = new DatePicker(this);
        this.dohdvkjkuv = datePicker6;
        datePicker6.setLayoutParams(new LinearLayout.LayoutParams(292, 1393));
        this.dohdvkjkuv.setPadding(60, 110, 152, 137);
        linearLayout.addView(this.dohdvkjkuv);
        this.dohdvkjkuv.setBackgroundColor(Color.parseColor("#9295bf"));
        ScrollView scrollView14 = new ScrollView(this);
        this.jlvtxtqtdj = scrollView14;
        scrollView14.setLayoutParams(new LinearLayout.LayoutParams(1735, 1900));
        this.jlvtxtqtdj.setPadding(41, 163, 65, 68);
        linearLayout.addView(this.jlvtxtqtdj);
        this.jlvtxtqtdj.setBackgroundColor(Color.parseColor("#d0fb49"));
        ToggleButton toggleButton5 = new ToggleButton(this);
        this.wgivgrngea = toggleButton5;
        toggleButton5.setLayoutParams(new LinearLayout.LayoutParams(1601, 798));
        this.wgivgrngea.setPadding(58, 136, 128, 114);
        linearLayout.addView(this.wgivgrngea);
        this.wgivgrngea.setBackgroundColor(Color.parseColor("#011741"));
        FrameLayout frameLayout4 = new FrameLayout(this);
        this.ricwkpyxal = frameLayout4;
        frameLayout4.setLayoutParams(new LinearLayout.LayoutParams(1671, 1337));
        this.ricwkpyxal.setPadding(150, 68, 6, 169);
        linearLayout.addView(this.ricwkpyxal);
        this.ricwkpyxal.setBackgroundColor(Color.parseColor("#88433d"));
        Spinner spinner12 = new Spinner(this);
        this.wdcdsioatz = spinner12;
        spinner12.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.MotionType.TYPE_ANIMATE_CIRCLEANGLE_TO, 547));
        this.wdcdsioatz.setPadding(111, 47, 152, 131);
        linearLayout.addView(this.wdcdsioatz);
        this.wdcdsioatz.setBackgroundColor(Color.parseColor("#66f603"));
        SeekBar seekBar6 = new SeekBar(this);
        this.upgwdgnqko = seekBar6;
        seekBar6.setLayoutParams(new LinearLayout.LayoutParams(971, 1245));
        this.upgwdgnqko.setPadding(157, 168, 123, 176);
        linearLayout.addView(this.upgwdgnqko);
        this.upgwdgnqko.setBackgroundColor(Color.parseColor("#907e54"));
        LinearLayout linearLayout11 = new LinearLayout(this);
        this.jyfxijmwlj = linearLayout11;
        linearLayout11.setLayoutParams(new LinearLayout.LayoutParams(926, 184));
        this.jyfxijmwlj.setPadding(22, 36, 1, 163);
        linearLayout.addView(this.jyfxijmwlj);
        this.jyfxijmwlj.setBackgroundColor(Color.parseColor("#a02be0"));
        DatePicker datePicker7 = new DatePicker(this);
        this.cmejkarmos = datePicker7;
        datePicker7.setLayoutParams(new LinearLayout.LayoutParams(289, CropImage.PICK_IMAGE_PERMISSIONS_REQUEST_CODE));
        this.cmejkarmos.setPadding(93, 123, 116, 173);
        linearLayout.addView(this.cmejkarmos);
        this.cmejkarmos.setBackgroundColor(Color.parseColor("#2de122"));
        FrameLayout frameLayout5 = new FrameLayout(this);
        this.makljoddiu = frameLayout5;
        frameLayout5.setLayoutParams(new LinearLayout.LayoutParams(522, 676));
        this.makljoddiu.setPadding(4, 108, 109, 135);
        linearLayout.addView(this.makljoddiu);
        this.makljoddiu.setBackgroundColor(Color.parseColor("#fa0293"));
        Spinner spinner13 = new Spinner(this);
        this.axcutjokxi = spinner13;
        spinner13.setLayoutParams(new LinearLayout.LayoutParams(1313, 1470));
        this.axcutjokxi.setPadding(71, 120, BDLocation.TypeNetWorkLocation, 12);
        linearLayout.addView(this.axcutjokxi);
        this.axcutjokxi.setBackgroundColor(Color.parseColor("#423015"));
        ToggleButton toggleButton6 = new ToggleButton(this);
        this.pooknalphl = toggleButton6;
        toggleButton6.setLayoutParams(new LinearLayout.LayoutParams(791, 930));
        this.pooknalphl.setPadding(159, 20, 120, 131);
        linearLayout.addView(this.pooknalphl);
        this.pooknalphl.setBackgroundColor(Color.parseColor("#ba5fba"));
        TableLayout tableLayout9 = new TableLayout(this);
        this.zvofiflerr = tableLayout9;
        tableLayout9.setLayoutParams(new LinearLayout.LayoutParams(174, 1182));
        this.zvofiflerr.setPadding(47, 87, 17, 51);
        linearLayout.addView(this.zvofiflerr);
        this.zvofiflerr.setBackgroundColor(Color.parseColor("#8b448f"));
        ToggleButton toggleButton7 = new ToggleButton(this);
        this.cwluvqiijz = toggleButton7;
        toggleButton7.setLayoutParams(new LinearLayout.LayoutParams(54, 1422));
        this.cwluvqiijz.setPadding(63, 155, 55, 119);
        linearLayout.addView(this.cwluvqiijz);
        this.cwluvqiijz.setBackgroundColor(Color.parseColor("#45811c"));
        RatingBar ratingBar12 = new RatingBar(this);
        this.mfgglrmido = ratingBar12;
        ratingBar12.setLayoutParams(new LinearLayout.LayoutParams(130, 1774));
        this.mfgglrmido.setPadding(67, 16, 73, 89);
        linearLayout.addView(this.mfgglrmido);
        this.mfgglrmido.setBackgroundColor(Color.parseColor("#e6dc3b"));
        RelativeLayout relativeLayout12 = new RelativeLayout(this);
        this.qvriytctba = relativeLayout12;
        relativeLayout12.setLayoutParams(new LinearLayout.LayoutParams(494, 134));
        this.qvriytctba.setPadding(119, 44, 178, PictureConfig.CHOOSE_REQUEST);
        linearLayout.addView(this.qvriytctba);
        this.qvriytctba.setBackgroundColor(Color.parseColor("#f9beb2"));
        TableLayout tableLayout10 = new TableLayout(this);
        this.qnwyzcaoko = tableLayout10;
        tableLayout10.setLayoutParams(new LinearLayout.LayoutParams(1475, 551));
        this.qnwyzcaoko.setPadding(105, 6, 182, 2);
        linearLayout.addView(this.qnwyzcaoko);
        this.qnwyzcaoko.setBackgroundColor(Color.parseColor("#d39df1"));
        GridView gridView10 = new GridView(this);
        this.gdayfexgrj = gridView10;
        gridView10.setLayoutParams(new LinearLayout.LayoutParams(595, 411));
        this.gdayfexgrj.setPadding(154, 90, 172, 117);
        linearLayout.addView(this.gdayfexgrj);
        this.gdayfexgrj.setBackgroundColor(Color.parseColor("#3cc872"));
        TimePicker timePicker10 = new TimePicker(this);
        this.lbtquhsukh = timePicker10;
        timePicker10.setLayoutParams(new LinearLayout.LayoutParams(147, 1808));
        this.lbtquhsukh.setPadding(123, 54, 61, 90);
        linearLayout.addView(this.lbtquhsukh);
        this.lbtquhsukh.setBackgroundColor(Color.parseColor("#ae3a04"));
        ImageView imageView3 = new ImageView(this);
        this.lgumsabdcv = imageView3;
        imageView3.setLayoutParams(new LinearLayout.LayoutParams(113, 1421));
        this.lgumsabdcv.setPadding(177, 42, 144, 183);
        linearLayout.addView(this.lgumsabdcv);
        this.lgumsabdcv.setBackgroundColor(Color.parseColor("#bd72e6"));
        TimePicker timePicker11 = new TimePicker(this);
        this.lmrdttoqdk = timePicker11;
        timePicker11.setLayoutParams(new LinearLayout.LayoutParams(1834, 390));
        this.lmrdttoqdk.setPadding(165, BDLocation.TypeServerError, 121, 85);
        linearLayout.addView(this.lmrdttoqdk);
        this.lmrdttoqdk.setBackgroundColor(Color.parseColor("#4e1977"));
        TimePicker timePicker12 = new TimePicker(this);
        this.eahyzpazcw = timePicker12;
        timePicker12.setLayoutParams(new LinearLayout.LayoutParams(223, 1619));
        this.eahyzpazcw.setPadding(BDLocation.TypeServerDecryptError, WebSocketProtocol.PAYLOAD_SHORT, 157, 138);
        linearLayout.addView(this.eahyzpazcw);
        this.eahyzpazcw.setBackgroundColor(Color.parseColor("#c52bed"));
        Button button9 = new Button(this);
        this.tebtpcvtgd = button9;
        button9.setLayoutParams(new LinearLayout.LayoutParams(1085, 454));
        this.tebtpcvtgd.setPadding(148, 128, 115, 62);
        linearLayout.addView(this.tebtpcvtgd);
        this.tebtpcvtgd.setBackgroundColor(Color.parseColor("#53c80b"));
        GridView gridView11 = new GridView(this);
        this.hzaqqzktwh = gridView11;
        gridView11.setLayoutParams(new LinearLayout.LayoutParams(1823, 465));
        this.hzaqqzktwh.setPadding(57, 85, 170, 198);
        linearLayout.addView(this.hzaqqzktwh);
        this.hzaqqzktwh.setBackgroundColor(Color.parseColor("#3747d8"));
        RatingBar ratingBar13 = new RatingBar(this);
        this.uldeklnxku = ratingBar13;
        ratingBar13.setLayoutParams(new LinearLayout.LayoutParams(282, 30));
        this.uldeklnxku.setPadding(55, 61, 138, 125);
        linearLayout.addView(this.uldeklnxku);
        this.uldeklnxku.setBackgroundColor(Color.parseColor("#23513d"));
        TimePicker timePicker13 = new TimePicker(this);
        this.ovizpqmqrp = timePicker13;
        timePicker13.setLayoutParams(new LinearLayout.LayoutParams(571, 1232));
        this.ovizpqmqrp.setPadding(2, PictureConfig.CHOOSE_REQUEST, 89, 7);
        linearLayout.addView(this.ovizpqmqrp);
        this.ovizpqmqrp.setBackgroundColor(Color.parseColor("#52e5c0"));
        TableLayout tableLayout11 = new TableLayout(this);
        this.rhnfhcpzdg = tableLayout11;
        tableLayout11.setLayoutParams(new LinearLayout.LayoutParams(183, 528));
        this.rhnfhcpzdg.setPadding(88, 11, 131, 176);
        linearLayout.addView(this.rhnfhcpzdg);
        this.rhnfhcpzdg.setBackgroundColor(Color.parseColor("#eec1e1"));
        TextView textView10 = new TextView(this);
        this.lyhhtpjafv = textView10;
        textView10.setLayoutParams(new LinearLayout.LayoutParams(1112, 171));
        this.lyhhtpjafv.setPadding(116, 177, 102, 106);
        linearLayout.addView(this.lyhhtpjafv);
        this.lyhhtpjafv.setBackgroundColor(Color.parseColor("#23d576"));
        EditText editText4 = new EditText(this);
        this.dgpkbfwzqb = editText4;
        editText4.setLayoutParams(new LinearLayout.LayoutParams(153, 1422));
        this.dgpkbfwzqb.setPadding(139, 8, 33, 100);
        linearLayout.addView(this.dgpkbfwzqb);
        this.dgpkbfwzqb.setBackgroundColor(Color.parseColor("#67b17b"));
        GridView gridView12 = new GridView(this);
        this.eengfdrskt = gridView12;
        gridView12.setLayoutParams(new LinearLayout.LayoutParams(934, 236));
        this.eengfdrskt.setPadding(134, 43, 79, 22);
        linearLayout.addView(this.eengfdrskt);
        this.eengfdrskt.setBackgroundColor(Color.parseColor("#750c06"));
        LinearLayout linearLayout12 = new LinearLayout(this);
        this.ysbfdlnzft = linearLayout12;
        linearLayout12.setLayoutParams(new LinearLayout.LayoutParams(1418, AudioEq.SW_EQ_DATA_LENGTH));
        this.ysbfdlnzft.setPadding(132, 196, 69, 186);
        linearLayout.addView(this.ysbfdlnzft);
        this.ysbfdlnzft.setBackgroundColor(Color.parseColor("#63ab84"));
        RatingBar ratingBar14 = new RatingBar(this);
        this.krjikdrkat = ratingBar14;
        ratingBar14.setLayoutParams(new LinearLayout.LayoutParams(1484, 1748));
        this.krjikdrkat.setPadding(179, 132, 76, PictureConfig.CHOOSE_REQUEST);
        linearLayout.addView(this.krjikdrkat);
        this.krjikdrkat.setBackgroundColor(Color.parseColor("#ca7119"));
        DatePicker datePicker8 = new DatePicker(this);
        this.stasjwemex = datePicker8;
        datePicker8.setLayoutParams(new LinearLayout.LayoutParams(1744, 1514));
        this.stasjwemex.setPadding(83, 99, 36, 179);
        linearLayout.addView(this.stasjwemex);
        this.stasjwemex.setBackgroundColor(Color.parseColor("#e68ac4"));
        LinearLayout linearLayout13 = new LinearLayout(this);
        this.lynytxldej = linearLayout13;
        linearLayout13.setLayoutParams(new LinearLayout.LayoutParams(1327, 1089));
        this.lynytxldej.setPadding(48, 55, 39, BDLocation.TypeCoarseLocation);
        linearLayout.addView(this.lynytxldej);
        this.lynytxldej.setBackgroundColor(Color.parseColor("#db599d"));
        ListView listView9 = new ListView(this);
        this.ytupltglhx = listView9;
        listView9.setLayoutParams(new LinearLayout.LayoutParams(859, 296));
        this.ytupltglhx.setPadding(66, 114, 87, 108);
        linearLayout.addView(this.ytupltglhx);
        this.ytupltglhx.setBackgroundColor(Color.parseColor("#adeaf7"));
        GridView gridView13 = new GridView(this);
        this.bforukjlgf = gridView13;
        gridView13.setLayoutParams(new LinearLayout.LayoutParams(890, 1654));
        this.bforukjlgf.setPadding(139, 187, 12, 31);
        linearLayout.addView(this.bforukjlgf);
        this.bforukjlgf.setBackgroundColor(Color.parseColor("#33c8f2"));
        EditText editText5 = new EditText(this);
        this.jgbiphwwrt = editText5;
        editText5.setLayoutParams(new LinearLayout.LayoutParams(485, 1619));
        this.jgbiphwwrt.setPadding(101, 190, 157, 107);
        linearLayout.addView(this.jgbiphwwrt);
        this.jgbiphwwrt.setBackgroundColor(Color.parseColor("#368ef0"));
        DatePicker datePicker9 = new DatePicker(this);
        this.qkcmqpndar = datePicker9;
        datePicker9.setLayoutParams(new LinearLayout.LayoutParams(1766, 7));
        this.qkcmqpndar.setPadding(28, 190, 177, 56);
        linearLayout.addView(this.qkcmqpndar);
        this.qkcmqpndar.setBackgroundColor(Color.parseColor("#62ac3b"));
        CheckBox checkBox4 = new CheckBox(this);
        this.hmzrxpjqyw = checkBox4;
        checkBox4.setLayoutParams(new LinearLayout.LayoutParams(515, 1129));
        this.hmzrxpjqyw.setPadding(151, 56, 17, 33);
        linearLayout.addView(this.hmzrxpjqyw);
        this.hmzrxpjqyw.setBackgroundColor(Color.parseColor("#7749af"));
        RelativeLayout relativeLayout13 = new RelativeLayout(this);
        this.sgprmbxhmk = relativeLayout13;
        relativeLayout13.setLayoutParams(new LinearLayout.LayoutParams(354, 939));
        this.sgprmbxhmk.setPadding(39, 60, 109, 28);
        linearLayout.addView(this.sgprmbxhmk);
        this.sgprmbxhmk.setBackgroundColor(Color.parseColor("#7f34e6"));
        FrameLayout frameLayout6 = new FrameLayout(this);
        this.xmnwjqtwby = frameLayout6;
        frameLayout6.setLayoutParams(new LinearLayout.LayoutParams(386, 457));
        this.xmnwjqtwby.setPadding(58, 116, 177, 71);
        linearLayout.addView(this.xmnwjqtwby);
        this.xmnwjqtwby.setBackgroundColor(Color.parseColor("#2245d6"));
        ProgressBar progressBar8 = new ProgressBar(this);
        this.ktwihaafuh = progressBar8;
        progressBar8.setLayoutParams(new LinearLayout.LayoutParams(698, 1577));
        this.ktwihaafuh.setPadding(103, 198, 116, 182);
        linearLayout.addView(this.ktwihaafuh);
        this.ktwihaafuh.setBackgroundColor(Color.parseColor("#aa15ce"));
        ScrollView scrollView15 = new ScrollView(this);
        this.wkeuzquqne = scrollView15;
        scrollView15.setLayoutParams(new LinearLayout.LayoutParams(1097, 1620));
        this.wkeuzquqne.setPadding(22, 166, 92, 145);
        linearLayout.addView(this.wkeuzquqne);
        this.wkeuzquqne.setBackgroundColor(Color.parseColor("#2e19c1"));
        RelativeLayout relativeLayout14 = new RelativeLayout(this);
        this.txvojgpepr = relativeLayout14;
        relativeLayout14.setLayoutParams(new LinearLayout.LayoutParams(1811, PictureConfig.CHOOSE_REQUEST));
        this.txvojgpepr.setPadding(11, 20, 79, 107);
        linearLayout.addView(this.txvojgpepr);
        this.txvojgpepr.setBackgroundColor(Color.parseColor("#40a428"));
        ViewFlipper viewFlipper8 = new ViewFlipper(this);
        this.rtbabelbej = viewFlipper8;
        viewFlipper8.setLayoutParams(new LinearLayout.LayoutParams(572, 335));
        this.rtbabelbej.setPadding(95, 29, 137, 23);
        linearLayout.addView(this.rtbabelbej);
        this.rtbabelbej.setBackgroundColor(Color.parseColor("#2a4dde"));
        EditText editText6 = new EditText(this);
        this.esnpgpgbji = editText6;
        editText6.setLayoutParams(new LinearLayout.LayoutParams(1931, 1152));
        this.esnpgpgbji.setPadding(139, 157, 127, 4);
        linearLayout.addView(this.esnpgpgbji);
        this.esnpgpgbji.setBackgroundColor(Color.parseColor("#bccda9"));
        GridView gridView14 = new GridView(this);
        this.aaqtnxxzao = gridView14;
        gridView14.setLayoutParams(new LinearLayout.LayoutParams(933, 44));
        this.aaqtnxxzao.setPadding(122, 56, 53, 151);
        linearLayout.addView(this.aaqtnxxzao);
        this.aaqtnxxzao.setBackgroundColor(Color.parseColor("#0fabcb"));
        GridView gridView15 = new GridView(this);
        this.hmwgjuwfry = gridView15;
        gridView15.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.MotionType.TYPE_QUANTIZE_INTERPOLATOR, 66));
        this.hmwgjuwfry.setPadding(66, 138, 146, 8);
        linearLayout.addView(this.hmwgjuwfry);
        this.hmwgjuwfry.setBackgroundColor(Color.parseColor("#cd63a1"));
        TextView textView11 = new TextView(this);
        this.iecveqlnaw = textView11;
        textView11.setLayoutParams(new LinearLayout.LayoutParams(1435, 469));
        this.iecveqlnaw.setPadding(54, 68, 133, 13);
        linearLayout.addView(this.iecveqlnaw);
        this.iecveqlnaw.setBackgroundColor(Color.parseColor("#a55975"));
        TextView textView12 = new TextView(this);
        this.lpbgmrzpve = textView12;
        textView12.setLayoutParams(new LinearLayout.LayoutParams(680, 981));
        this.lpbgmrzpve.setPadding(124, 174, 122, 91);
        linearLayout.addView(this.lpbgmrzpve);
        this.lpbgmrzpve.setBackgroundColor(Color.parseColor("#bf6ce6"));
        LinearLayout linearLayout14 = new LinearLayout(this);
        this.epckedcphm = linearLayout14;
        linearLayout14.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.TransitionType.TYPE_TO, TypedValues.CycleType.TYPE_VISIBILITY));
        this.epckedcphm.setPadding(102, 149, 158, 68);
        linearLayout.addView(this.epckedcphm);
        this.epckedcphm.setBackgroundColor(Color.parseColor("#1f0154"));
        ListView listView10 = new ListView(this);
        this.apqghhzpor = listView10;
        listView10.setLayoutParams(new LinearLayout.LayoutParams(1853, 392));
        this.apqghhzpor.setPadding(143, 89, 44, 114);
        linearLayout.addView(this.apqghhzpor);
        this.apqghhzpor.setBackgroundColor(Color.parseColor("#afffdb"));
        RelativeLayout relativeLayout15 = new RelativeLayout(this);
        this.loziodlael = relativeLayout15;
        relativeLayout15.setLayoutParams(new LinearLayout.LayoutParams(1576, 1230));
        this.loziodlael.setPadding(13, 41, 66, 114);
        linearLayout.addView(this.loziodlael);
        this.loziodlael.setBackgroundColor(Color.parseColor("#97657b"));
        ToggleButton toggleButton8 = new ToggleButton(this);
        this.ejjqqvswln = toggleButton8;
        toggleButton8.setLayoutParams(new LinearLayout.LayoutParams(1218, 81));
        this.ejjqqvswln.setPadding(149, 9, 165, 101);
        linearLayout.addView(this.ejjqqvswln);
        this.ejjqqvswln.setBackgroundColor(Color.parseColor("#916a3e"));
        GridView gridView16 = new GridView(this);
        this.yscqkguzuq = gridView16;
        gridView16.setLayoutParams(new LinearLayout.LayoutParams(1404, 295));
        this.yscqkguzuq.setPadding(103, 73, 69, 25);
        linearLayout.addView(this.yscqkguzuq);
        this.yscqkguzuq.setBackgroundColor(Color.parseColor("#364169"));
        ProgressBar progressBar9 = new ProgressBar(this);
        this.ywfcevlqig = progressBar9;
        progressBar9.setLayoutParams(new LinearLayout.LayoutParams(1254, 1414));
        this.ywfcevlqig.setPadding(199, 81, 21, 133);
        linearLayout.addView(this.ywfcevlqig);
        this.ywfcevlqig.setBackgroundColor(Color.parseColor("#8537c2"));
        ViewFlipper viewFlipper9 = new ViewFlipper(this);
        this.fhfyulturw = viewFlipper9;
        viewFlipper9.setLayoutParams(new LinearLayout.LayoutParams(1401, 315));
        this.fhfyulturw.setPadding(29, 15, 58, 113);
        linearLayout.addView(this.fhfyulturw);
        this.fhfyulturw.setBackgroundColor(Color.parseColor("#cd4f3c"));
        Switch r212 = new Switch(this);
        this.qsarhzeqdt = r212;
        r212.setLayoutParams(new LinearLayout.LayoutParams(1606, 655));
        this.qsarhzeqdt.setPadding(58, 163, 166, 148);
        linearLayout.addView(this.qsarhzeqdt);
        this.qsarhzeqdt.setBackgroundColor(Color.parseColor("#3b0548"));
        RelativeLayout relativeLayout16 = new RelativeLayout(this);
        this.jzsglfuwqa = relativeLayout16;
        relativeLayout16.setLayoutParams(new LinearLayout.LayoutParams(343, 301));
        this.jzsglfuwqa.setPadding(152, 33, 2, 15);
        linearLayout.addView(this.jzsglfuwqa);
        this.jzsglfuwqa.setBackgroundColor(Color.parseColor("#4bc42e"));
        GridView gridView17 = new GridView(this);
        this.lcxmnjhnxr = gridView17;
        gridView17.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.PositionType.TYPE_PERCENT_WIDTH, 1478));
        this.lcxmnjhnxr.setPadding(149, 190, 53, 128);
        linearLayout.addView(this.lcxmnjhnxr);
        this.lcxmnjhnxr.setBackgroundColor(Color.parseColor("#6f2f95"));
        TimePicker timePicker14 = new TimePicker(this);
        this.jgkxjxlvxx = timePicker14;
        timePicker14.setLayoutParams(new LinearLayout.LayoutParams(38, 1854));
        this.jgkxjxlvxx.setPadding(59, 38, 124, 130);
        linearLayout.addView(this.jgkxjxlvxx);
        this.jgkxjxlvxx.setBackgroundColor(Color.parseColor("#4523c9"));
        RelativeLayout relativeLayout17 = new RelativeLayout(this);
        this.kixtqdpphp = relativeLayout17;
        relativeLayout17.setLayoutParams(new LinearLayout.LayoutParams(70, 1720));
        this.kixtqdpphp.setPadding(111, 65, 62, 64);
        linearLayout.addView(this.kixtqdpphp);
        this.kixtqdpphp.setBackgroundColor(Color.parseColor("#581448"));
        Spinner spinner14 = new Spinner(this);
        this.wftiqtglzo = spinner14;
        spinner14.setLayoutParams(new LinearLayout.LayoutParams(4, 132));
        this.wftiqtglzo.setPadding(28, 61, 180, 25);
        linearLayout.addView(this.wftiqtglzo);
        this.wftiqtglzo.setBackgroundColor(Color.parseColor("#2b5de4"));
        ViewFlipper viewFlipper10 = new ViewFlipper(this);
        this.hxuiovyggc = viewFlipper10;
        viewFlipper10.setLayoutParams(new LinearLayout.LayoutParams(1405, 578));
        this.hxuiovyggc.setPadding(51, 198, 27, 142);
        linearLayout.addView(this.hxuiovyggc);
        this.hxuiovyggc.setBackgroundColor(Color.parseColor("#5b9526"));
        ProgressBar progressBar10 = new ProgressBar(this);
        this.yieihcoadp = progressBar10;
        progressBar10.setLayoutParams(new LinearLayout.LayoutParams(71, 583));
        this.yieihcoadp.setPadding(58, 9, 143, 55);
        linearLayout.addView(this.yieihcoadp);
        this.yieihcoadp.setBackgroundColor(Color.parseColor("#153241"));
        TimePicker timePicker15 = new TimePicker(this);
        this.pqvcvnuzeg = timePicker15;
        timePicker15.setLayoutParams(new LinearLayout.LayoutParams(1488, 1173));
        this.pqvcvnuzeg.setPadding(BDLocation.TypeServerError, 192, 100, 76);
        linearLayout.addView(this.pqvcvnuzeg);
        this.pqvcvnuzeg.setBackgroundColor(Color.parseColor("#75457f"));
        RatingBar ratingBar15 = new RatingBar(this);
        this.rurmevdotj = ratingBar15;
        ratingBar15.setLayoutParams(new LinearLayout.LayoutParams(334, 1648));
        this.rurmevdotj.setPadding(159, 32, 59, 16);
        linearLayout.addView(this.rurmevdotj);
        this.rurmevdotj.setBackgroundColor(Color.parseColor("#5f5fa1"));
        RadioButton radioButton13 = new RadioButton(this);
        this.fiswqndtsm = radioButton13;
        radioButton13.setLayoutParams(new LinearLayout.LayoutParams(1386, 1315));
        this.fiswqndtsm.setPadding(23, 62, 23, 137);
        linearLayout.addView(this.fiswqndtsm);
        this.fiswqndtsm.setBackgroundColor(Color.parseColor("#e291f3"));
        EditText editText7 = new EditText(this);
        this.levlbhcnnr = editText7;
        editText7.setLayoutParams(new LinearLayout.LayoutParams(1282, 1545));
        this.levlbhcnnr.setPadding(190, 32, 42, 18);
        linearLayout.addView(this.levlbhcnnr);
        this.levlbhcnnr.setBackgroundColor(Color.parseColor("#64d65f"));
        DatePicker datePicker10 = new DatePicker(this);
        this.koofauwaub = datePicker10;
        datePicker10.setLayoutParams(new LinearLayout.LayoutParams(1908, 544));
        this.koofauwaub.setPadding(172, 31, BDLocation.TypeCoarseLocation, 66);
        linearLayout.addView(this.koofauwaub);
        this.koofauwaub.setBackgroundColor(Color.parseColor("#e4c0a0"));
        TableLayout tableLayout12 = new TableLayout(this);
        this.buabbchvdr = tableLayout12;
        tableLayout12.setLayoutParams(new LinearLayout.LayoutParams(617, 736));
        this.buabbchvdr.setPadding(84, 105, 22, 118);
        linearLayout.addView(this.buabbchvdr);
        this.buabbchvdr.setBackgroundColor(Color.parseColor("#df40db"));
        Spinner spinner15 = new Spinner(this);
        this.dserncxeel = spinner15;
        spinner15.setLayoutParams(new LinearLayout.LayoutParams(141, 1907));
        this.dserncxeel.setPadding(58, PictureConfig.CHOOSE_REQUEST, 128, 113);
        linearLayout.addView(this.dserncxeel);
        this.dserncxeel.setBackgroundColor(Color.parseColor("#55e5d3"));
        GridView gridView18 = new GridView(this);
        this.manhcrwivp = gridView18;
        gridView18.setLayoutParams(new LinearLayout.LayoutParams(1040, 1413));
        this.manhcrwivp.setPadding(153, 71, 101, 28);
        linearLayout.addView(this.manhcrwivp);
        this.manhcrwivp.setBackgroundColor(Color.parseColor("#138476"));
        ListView listView11 = new ListView(this);
        this.yslzjgoxca = listView11;
        listView11.setLayoutParams(new LinearLayout.LayoutParams(1633, 1346));
        this.yslzjgoxca.setPadding(116, 122, 168, 105);
        linearLayout.addView(this.yslzjgoxca);
        this.yslzjgoxca.setBackgroundColor(Color.parseColor("#591aaa"));
        ScrollView scrollView16 = new ScrollView(this);
        this.khscbyycoa = scrollView16;
        scrollView16.setLayoutParams(new LinearLayout.LayoutParams(1440, 584));
        this.khscbyycoa.setPadding(55, 125, 61, 99);
        linearLayout.addView(this.khscbyycoa);
        this.khscbyycoa.setBackgroundColor(Color.parseColor("#fdb41a"));
        RadioButton radioButton14 = new RadioButton(this);
        this.herjnbdeak = radioButton14;
        radioButton14.setLayoutParams(new LinearLayout.LayoutParams(932, 1146));
        this.herjnbdeak.setPadding(81, 181, 62, 192);
        linearLayout.addView(this.herjnbdeak);
        this.herjnbdeak.setBackgroundColor(Color.parseColor("#0edd7d"));
    }
}
