package com.device.watch.com.device.watch.jcnkdozxuj;

import android.app.Activity;
import android.graphics.Color;
import android.os.Bundle;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.CheckBox;
import android.widget.DatePicker;
import android.widget.EditText;
import android.widget.FrameLayout;
import android.widget.GridView;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ListView;
import android.widget.ProgressBar;
import android.widget.RadioButton;
import android.widget.RatingBar;
import android.widget.RelativeLayout;
import android.widget.ScrollView;
import android.widget.SeekBar;
import android.widget.Spinner;
import android.widget.Switch;
import android.widget.TableLayout;
import android.widget.TextView;
import android.widget.TimePicker;
import android.widget.ToggleButton;
import android.widget.ViewFlipper;
import androidx.constraintlayout.core.motion.utils.TypedValues;
import androidx.core.view.PointerIconCompat;
import com.baidu.location.BDLocation;
import com.luck.picture.lib.config.Crop;
import com.luck.picture.lib.config.PictureConfig;
import com.realsil.sdk.core.bluetooth.impl.BluetoothClassImpl;
import okhttp3.internal.ws.WebSocketProtocol;

/* loaded from: classes.dex */
public class MzlfdillshhActivity extends Activity {
    ViewFlipper ablolhjusm;
    ListView acvmlbhote;
    RadioButton aehqrpviey;
    ProgressBar agvrakklui;
    CheckBox amiyxtusfo;
    ToggleButton apvlvqoxxd;
    ListView arbaxfvayj;
    RadioButton aymczxkulz;
    ScrollView ayxwatfzdv;
    RatingBar bfdukjvkxh;
    CheckBox bgkxhmzvgg;
    ToggleButton bhoxvyhnuw;
    ListView bnusuxjcrw;
    TableLayout bvocizeivy;
    CheckBox byrngiagho;
    LinearLayout cbqhvxklhf;
    Button cddlkwqakw;
    TextView cfklqsxkmc;
    RadioButton cjdinmllrk;
    Button cswcbvelhx;
    ProgressBar curyklvekm;
    ViewFlipper cwnvaibkfe;
    CheckBox dpbqhowhmd;
    ImageView duwswniezx;
    TimePicker dxksjwiavp;
    Spinner ecjalzeayg;
    ListView ejxgmcpraw;
    TableLayout enyaaflxyj;
    GridView eouxhdyjsh;
    RatingBar etiyzxnmbt;
    DatePicker exxjhcxtci;
    EditText fgbvpulgxt;
    FrameLayout ficdsqifgx;
    CheckBox fjkughlkhu;
    Button fnpmdlyqrf;
    TableLayout foqwwsmswi;
    CheckBox fsuruwzyph;
    ListView fxwkyhebib;
    ImageView gbrrayeows;
    ToggleButton ghkifablyl;
    ToggleButton ghyqldwpxz;
    EditText gnlyfwgmmj;
    DatePicker gtjtihrvwv;
    TextView gxtkjwixdk;
    LinearLayout hctwcggubv;
    ScrollView hdvuvinsli;
    Switch hffwkjebmt;
    LinearLayout hqcfuubtgf;
    TimePicker htcxjxrnwu;
    Button hykreixasb;
    TimePicker ibbzzmackr;
    ToggleButton ibeojocixz;
    FrameLayout ibjdswpxyn;
    TableLayout ibuxanwyfg;
    ProgressBar iinxxilphy;
    ImageView iipreomenj;
    TimePicker iqcchgbshb;
    CheckBox iuxyrtiped;
    ListView iwiffyqmju;
    EditText jcnylzuose;
    TextView jmcudpbazg;
    ToggleButton kcwpmfcveu;
    Switch kriyyopeny;
    SeekBar ktqnourteg;
    ViewFlipper kujyegpstw;
    DatePicker kuktfngmlk;
    ListView kxlpiykkfh;
    Switch kyhattxjua;
    ProgressBar ljqhqlzrjs;
    EditText lkxpwtmmfo;
    RatingBar lkxrkzhtkp;
    Button loiwvxycdn;
    ListView lqunrtlhmd;
    LinearLayout ltxnhqbufd;
    FrameLayout mbpvuneyeo;
    Button mkapsaszfl;
    ScrollView mwkrjuovtf;
    ViewFlipper mxasiabqos;
    ListView mxmllqckhw;
    SeekBar nchvusheft;
    Switch nepqequqxp;
    ViewFlipper njntmuekwa;
    TimePicker njpylblemu;
    ScrollView nkkvdpeksh;
    SeekBar nppiljciwr;
    TextView nuwbeqrfeq;
    CheckBox okhzmdowvz;
    Spinner ooglpafmzu;
    TableLayout ospxtmnsoo;
    LinearLayout otasqiisrf;
    LinearLayout ovqoaootfz;
    ProgressBar pfjsvfytqm;
    RadioButton pnoqwefgtt;
    ViewFlipper pzadqgduqx;
    Button qbfqkrbutx;
    ProgressBar qoqxjbdlda;
    ImageView qqvhalhkpx;
    ToggleButton qtaaphqbpd;
    GridView qztcsckdpj;
    GridView rmrtwmarbt;
    ImageView scadgzxwxn;
    EditText sfulzrmjsj;
    Switch sipekggiil;
    Button sswoxacwyq;
    Spinner tafesgtzpr;
    RelativeLayout thlatwqocy;
    ScrollView tmbnrqgvyg;
    LinearLayout ulweccnilo;
    EditText upnhbvdvij;
    Switch utwpzgudff;
    Button uxyxyecwqw;
    CheckBox uzfvbqkkdp;
    TextView vktbrtqoif;
    ScrollView vroyvrjrgg;
    LinearLayout vvyqklfkxk;
    ImageView vyjgmvjqse;
    Spinner wanqejytiy;
    RelativeLayout wifhltdslz;
    ViewFlipper wjivmzvhbl;
    ListView wkeikjvkek;
    RelativeLayout wnazmrzjne;
    ToggleButton xgzpjxdxsm;
    CheckBox xnitbpswpy;
    TextView xohsixtzuk;
    ScrollView xsjeqnapdr;
    ProgressBar xtbobhunjh;
    Button xwgfadietx;
    ScrollView ycikigsiel;
    Button ykwvjinypb;
    CheckBox yoccomqciq;
    RadioButton yvjkbjuhdv;
    TimePicker zelaadhvgf;
    RelativeLayout zlaxjifyfr;
    ProgressBar zvnismsdvq;

    @Override // android.app.Activity
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        LinearLayout linearLayout = new LinearLayout(this);
        setContentView(linearLayout);
        linearLayout.setLayoutParams(new ViewGroup.LayoutParams(-1, -1));
        linearLayout.setOrientation(1);
        linearLayout.setBackgroundColor(Color.parseColor("#dc7acf"));
        ViewFlipper viewFlipper = new ViewFlipper(this);
        this.kujyegpstw = viewFlipper;
        viewFlipper.setLayoutParams(new LinearLayout.LayoutParams(1944, 1156));
        this.kujyegpstw.setPadding(109, 42, 63, 152);
        linearLayout.addView(this.kujyegpstw);
        this.kujyegpstw.setBackgroundColor(Color.parseColor("#109ffd"));
        ScrollView scrollView = new ScrollView(this);
        this.ycikigsiel = scrollView;
        scrollView.setLayoutParams(new LinearLayout.LayoutParams(1354, 293));
        this.ycikigsiel.setPadding(190, 21, 74, 165);
        linearLayout.addView(this.ycikigsiel);
        this.ycikigsiel.setBackgroundColor(Color.parseColor("#8391e3"));
        ProgressBar progressBar = new ProgressBar(this);
        this.ljqhqlzrjs = progressBar;
        progressBar.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.TransitionType.TYPE_AUTO_TRANSITION, 1299));
        this.ljqhqlzrjs.setPadding(63, 125, 27, 185);
        linearLayout.addView(this.ljqhqlzrjs);
        this.ljqhqlzrjs.setBackgroundColor(Color.parseColor("#3420f8"));
        ToggleButton toggleButton = new ToggleButton(this);
        this.apvlvqoxxd = toggleButton;
        toggleButton.setLayoutParams(new LinearLayout.LayoutParams(1162, 848));
        this.apvlvqoxxd.setPadding(110, 70, BDLocation.TypeCoarseLocation, 176);
        linearLayout.addView(this.apvlvqoxxd);
        this.apvlvqoxxd.setBackgroundColor(Color.parseColor("#21a509"));
        ScrollView scrollView2 = new ScrollView(this);
        this.ayxwatfzdv = scrollView2;
        scrollView2.setLayoutParams(new LinearLayout.LayoutParams(1707, 757));
        this.ayxwatfzdv.setPadding(182, 56, 72, 171);
        linearLayout.addView(this.ayxwatfzdv);
        this.ayxwatfzdv.setBackgroundColor(Color.parseColor("#2ad679"));
        TableLayout tableLayout = new TableLayout(this);
        this.bvocizeivy = tableLayout;
        tableLayout.setLayoutParams(new LinearLayout.LayoutParams(509, 538));
        this.bvocizeivy.setPadding(99, 135, 10, 169);
        linearLayout.addView(this.bvocizeivy);
        this.bvocizeivy.setBackgroundColor(Color.parseColor("#ac1662"));
        Spinner spinner = new Spinner(this);
        this.ooglpafmzu = spinner;
        spinner.setLayoutParams(new LinearLayout.LayoutParams(PointerIconCompat.TYPE_GRAB, 953));
        this.ooglpafmzu.setPadding(172, 106, 32, 75);
        linearLayout.addView(this.ooglpafmzu);
        this.ooglpafmzu.setBackgroundColor(Color.parseColor("#a5f129"));
        ToggleButton toggleButton2 = new ToggleButton(this);
        this.bhoxvyhnuw = toggleButton2;
        toggleButton2.setLayoutParams(new LinearLayout.LayoutParams(1432, 109));
        this.bhoxvyhnuw.setPadding(3, 69, 33, 139);
        linearLayout.addView(this.bhoxvyhnuw);
        this.bhoxvyhnuw.setBackgroundColor(Color.parseColor("#a3b49d"));
        EditText editText = new EditText(this);
        this.upnhbvdvij = editText;
        editText.setLayoutParams(new LinearLayout.LayoutParams(139, 1769));
        this.upnhbvdvij.setPadding(177, 53, BDLocation.TypeServerDecryptError, 113);
        linearLayout.addView(this.upnhbvdvij);
        this.upnhbvdvij.setBackgroundColor(Color.parseColor("#353be2"));
        LinearLayout linearLayout2 = new LinearLayout(this);
        this.cbqhvxklhf = linearLayout2;
        linearLayout2.setLayoutParams(new LinearLayout.LayoutParams(1699, 1968));
        this.cbqhvxklhf.setPadding(69, 8, 78, 131);
        linearLayout.addView(this.cbqhvxklhf);
        this.cbqhvxklhf.setBackgroundColor(Color.parseColor("#71b5b8"));
        Switch r2 = new Switch(this);
        this.sipekggiil = r2;
        r2.setLayoutParams(new LinearLayout.LayoutParams(1873, PointerIconCompat.TYPE_TOP_RIGHT_DIAGONAL_DOUBLE_ARROW));
        this.sipekggiil.setPadding(171, 102, 36, 56);
        linearLayout.addView(this.sipekggiil);
        this.sipekggiil.setBackgroundColor(Color.parseColor("#468143"));
        TableLayout tableLayout2 = new TableLayout(this);
        this.ospxtmnsoo = tableLayout2;
        tableLayout2.setLayoutParams(new LinearLayout.LayoutParams(151, 1475));
        this.ospxtmnsoo.setPadding(130, 185, 31, 9);
        linearLayout.addView(this.ospxtmnsoo);
        this.ospxtmnsoo.setBackgroundColor(Color.parseColor("#63e869"));
        ToggleButton toggleButton3 = new ToggleButton(this);
        this.kcwpmfcveu = toggleButton3;
        toggleButton3.setLayoutParams(new LinearLayout.LayoutParams(633, 115));
        this.kcwpmfcveu.setPadding(71, 85, 115, 44);
        linearLayout.addView(this.kcwpmfcveu);
        this.kcwpmfcveu.setBackgroundColor(Color.parseColor("#fdb973"));
        ScrollView scrollView3 = new ScrollView(this);
        this.xsjeqnapdr = scrollView3;
        scrollView3.setLayoutParams(new LinearLayout.LayoutParams(1985, 1263));
        this.xsjeqnapdr.setPadding(53, 195, 90, 125);
        linearLayout.addView(this.xsjeqnapdr);
        this.xsjeqnapdr.setBackgroundColor(Color.parseColor("#6d92ff"));
        Button button = new Button(this);
        this.sswoxacwyq = button;
        button.setLayoutParams(new LinearLayout.LayoutParams(30, 1711));
        this.sswoxacwyq.setPadding(166, 64, 182, 42);
        linearLayout.addView(this.sswoxacwyq);
        this.sswoxacwyq.setBackground(new Veqbdxrsrid());
        CheckBox checkBox = new CheckBox(this);
        this.yoccomqciq = checkBox;
        checkBox.setLayoutParams(new LinearLayout.LayoutParams(1975, 1756));
        this.yoccomqciq.setPadding(68, 111, 75, 185);
        linearLayout.addView(this.yoccomqciq);
        this.yoccomqciq.setBackgroundColor(Color.parseColor("#88971b"));
        ListView listView = new ListView(this);
        this.lqunrtlhmd = listView;
        listView.setLayoutParams(new LinearLayout.LayoutParams(925, 1350));
        this.lqunrtlhmd.setPadding(133, 66, 69, 20);
        linearLayout.addView(this.lqunrtlhmd);
        this.lqunrtlhmd.setBackgroundColor(Color.parseColor("#88adbc"));
        ListView listView2 = new ListView(this);
        this.arbaxfvayj = listView2;
        listView2.setLayoutParams(new LinearLayout.LayoutParams(86, 1259));
        this.arbaxfvayj.setPadding(112, 153, 68, 29);
        linearLayout.addView(this.arbaxfvayj);
        this.arbaxfvayj.setBackgroundColor(Color.parseColor("#fe7443"));
        RatingBar ratingBar = new RatingBar(this);
        this.bfdukjvkxh = ratingBar;
        ratingBar.setLayoutParams(new LinearLayout.LayoutParams(437, 943));
        this.bfdukjvkxh.setPadding(3, 82, 132, 23);
        linearLayout.addView(this.bfdukjvkxh);
        this.bfdukjvkxh.setBackgroundColor(Color.parseColor("#29009a"));
        ToggleButton toggleButton4 = new ToggleButton(this);
        this.ghkifablyl = toggleButton4;
        toggleButton4.setLayoutParams(new LinearLayout.LayoutParams(781, 857));
        this.ghkifablyl.setPadding(28, 101, 116, 32);
        linearLayout.addView(this.ghkifablyl);
        this.ghkifablyl.setBackgroundColor(Color.parseColor("#bde930"));
        RelativeLayout relativeLayout = new RelativeLayout(this);
        this.wnazmrzjne = relativeLayout;
        relativeLayout.setLayoutParams(new LinearLayout.LayoutParams(1794, 1379));
        this.wnazmrzjne.setPadding(82, 174, 182, 36);
        linearLayout.addView(this.wnazmrzjne);
        this.wnazmrzjne.setBackgroundColor(Color.parseColor("#0306fc"));
        RadioButton radioButton = new RadioButton(this);
        this.yvjkbjuhdv = radioButton;
        radioButton.setLayoutParams(new LinearLayout.LayoutParams(439, 1765));
        this.yvjkbjuhdv.setPadding(118, 195, 179, 111);
        linearLayout.addView(this.yvjkbjuhdv);
        this.yvjkbjuhdv.setBackgroundColor(Color.parseColor("#cc1caf"));
        Switch r22 = new Switch(this);
        this.hffwkjebmt = r22;
        r22.setLayoutParams(new LinearLayout.LayoutParams(1659, 1462));
        this.hffwkjebmt.setPadding(PictureConfig.CHOOSE_REQUEST, 199, 77, 108);
        linearLayout.addView(this.hffwkjebmt);
        this.hffwkjebmt.setBackgroundColor(Color.parseColor("#635fb8"));
        ProgressBar progressBar2 = new ProgressBar(this);
        this.zvnismsdvq = progressBar2;
        progressBar2.setLayoutParams(new LinearLayout.LayoutParams(1285, 471));
        this.zvnismsdvq.setPadding(52, 187, 36, 23);
        linearLayout.addView(this.zvnismsdvq);
        this.zvnismsdvq.setBackgroundColor(Color.parseColor("#634d2a"));
        LinearLayout linearLayout3 = new LinearLayout(this);
        this.vvyqklfkxk = linearLayout3;
        linearLayout3.setLayoutParams(new LinearLayout.LayoutParams(295, 339));
        this.vvyqklfkxk.setPadding(13, 143, 122, 59);
        linearLayout.addView(this.vvyqklfkxk);
        this.vvyqklfkxk.setBackgroundColor(Color.parseColor("#dc1e62"));
        RelativeLayout relativeLayout2 = new RelativeLayout(this);
        this.thlatwqocy = relativeLayout2;
        relativeLayout2.setLayoutParams(new LinearLayout.LayoutParams(1478, 1550));
        this.thlatwqocy.setPadding(159, 169, 90, 97);
        linearLayout.addView(this.thlatwqocy);
        this.thlatwqocy.setBackgroundColor(Color.parseColor("#69436e"));
        ProgressBar progressBar3 = new ProgressBar(this);
        this.xtbobhunjh = progressBar3;
        progressBar3.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.TransitionType.TYPE_AUTO_TRANSITION, 353));
        this.xtbobhunjh.setPadding(113, 154, 44, 134);
        linearLayout.addView(this.xtbobhunjh);
        this.xtbobhunjh.setBackgroundColor(Color.parseColor("#849f05"));
        DatePicker datePicker = new DatePicker(this);
        this.kuktfngmlk = datePicker;
        datePicker.setLayoutParams(new LinearLayout.LayoutParams(176, 871));
        this.kuktfngmlk.setPadding(145, 144, 133, 143);
        linearLayout.addView(this.kuktfngmlk);
        this.kuktfngmlk.setBackgroundColor(Color.parseColor("#fbd63e"));
        ViewFlipper viewFlipper2 = new ViewFlipper(this);
        this.wjivmzvhbl = viewFlipper2;
        viewFlipper2.setLayoutParams(new LinearLayout.LayoutParams(1332, 592));
        this.wjivmzvhbl.setPadding(17, 189, 17, 44);
        linearLayout.addView(this.wjivmzvhbl);
        this.wjivmzvhbl.setBackgroundColor(Color.parseColor("#a4e89c"));
        CheckBox checkBox2 = new CheckBox(this);
        this.uzfvbqkkdp = checkBox2;
        checkBox2.setLayoutParams(new LinearLayout.LayoutParams(86, 1768));
        this.uzfvbqkkdp.setPadding(33, 98, 139, 14);
        linearLayout.addView(this.uzfvbqkkdp);
        this.uzfvbqkkdp.setBackgroundColor(Color.parseColor("#5e4099"));
        ScrollView scrollView4 = new ScrollView(this);
        this.mwkrjuovtf = scrollView4;
        scrollView4.setLayoutParams(new LinearLayout.LayoutParams(1680, 747));
        this.mwkrjuovtf.setPadding(54, 49, 124, 39);
        linearLayout.addView(this.mwkrjuovtf);
        this.mwkrjuovtf.setBackgroundColor(Color.parseColor("#52af86"));
        CheckBox checkBox3 = new CheckBox(this);
        this.byrngiagho = checkBox3;
        checkBox3.setLayoutParams(new LinearLayout.LayoutParams(192, 799));
        this.byrngiagho.setPadding(66, 77, 31, 77);
        linearLayout.addView(this.byrngiagho);
        this.byrngiagho.setBackgroundColor(Color.parseColor("#f980af"));
        DatePicker datePicker2 = new DatePicker(this);
        this.gtjtihrvwv = datePicker2;
        datePicker2.setLayoutParams(new LinearLayout.LayoutParams(148, 1190));
        this.gtjtihrvwv.setPadding(85, 135, 134, 146);
        linearLayout.addView(this.gtjtihrvwv);
        this.gtjtihrvwv.setBackgroundColor(Color.parseColor("#706a5a"));
        ViewFlipper viewFlipper3 = new ViewFlipper(this);
        this.njntmuekwa = viewFlipper3;
        viewFlipper3.setLayoutParams(new LinearLayout.LayoutParams(1335, 614));
        this.njntmuekwa.setPadding(136, 38, 70, 51);
        linearLayout.addView(this.njntmuekwa);
        this.njntmuekwa.setBackgroundColor(Color.parseColor("#fdefaf"));
        FrameLayout frameLayout = new FrameLayout(this);
        this.ibjdswpxyn = frameLayout;
        frameLayout.setLayoutParams(new LinearLayout.LayoutParams(386, 1071));
        this.ibjdswpxyn.setPadding(170, 83, 62, 156);
        linearLayout.addView(this.ibjdswpxyn);
        this.ibjdswpxyn.setBackgroundColor(Color.parseColor("#824525"));
        ImageView imageView = new ImageView(this);
        this.qqvhalhkpx = imageView;
        imageView.setLayoutParams(new LinearLayout.LayoutParams(1639, 897));
        this.qqvhalhkpx.setPadding(83, 0, 14, 108);
        linearLayout.addView(this.qqvhalhkpx);
        this.qqvhalhkpx.setBackgroundColor(Color.parseColor("#4dd178"));
        TextView textView = new TextView(this);
        this.nuwbeqrfeq = textView;
        textView.setLayoutParams(new LinearLayout.LayoutParams(1743, 1888));
        this.nuwbeqrfeq.setPadding(22, 196, 2, 50);
        linearLayout.addView(this.nuwbeqrfeq);
        this.nuwbeqrfeq.setBackgroundColor(Color.parseColor("#268455"));
        Button button2 = new Button(this);
        this.mkapsaszfl = button2;
        button2.setLayoutParams(new LinearLayout.LayoutParams(1388, 1069));
        this.mkapsaszfl.setPadding(44, 189, 134, 147);
        linearLayout.addView(this.mkapsaszfl);
        this.mkapsaszfl.setBackgroundColor(Color.parseColor("#8d6b24"));
        TimePicker timePicker = new TimePicker(this);
        this.dxksjwiavp = timePicker;
        timePicker.setLayoutParams(new LinearLayout.LayoutParams(1521, 362));
        this.dxksjwiavp.setPadding(154, 17, 84, 95);
        linearLayout.addView(this.dxksjwiavp);
        this.dxksjwiavp.setBackgroundColor(Color.parseColor("#b099b4"));
        RadioButton radioButton2 = new RadioButton(this);
        this.aymczxkulz = radioButton2;
        radioButton2.setLayoutParams(new LinearLayout.LayoutParams(918, 418));
        this.aymczxkulz.setPadding(59, 9, 97, 136);
        linearLayout.addView(this.aymczxkulz);
        this.aymczxkulz.setBackgroundColor(Color.parseColor("#a22405"));
        ListView listView3 = new ListView(this);
        this.bnusuxjcrw = listView3;
        listView3.setLayoutParams(new LinearLayout.LayoutParams(BluetoothClassImpl.Device.PERIPHERAL_NON_KEYBOARD_NON_POINTING, 1450));
        this.bnusuxjcrw.setPadding(42, 68, 87, 86);
        linearLayout.addView(this.bnusuxjcrw);
        this.bnusuxjcrw.setBackgroundColor(Color.parseColor("#51c48d"));
        Button button3 = new Button(this);
        this.uxyxyecwqw = button3;
        button3.setLayoutParams(new LinearLayout.LayoutParams(1317, 976));
        this.uxyxyecwqw.setPadding(24, 157, 195, 130);
        linearLayout.addView(this.uxyxyecwqw);
        this.uxyxyecwqw.setBackgroundColor(Color.parseColor("#06b701"));
        Button button4 = new Button(this);
        this.fnpmdlyqrf = button4;
        button4.setLayoutParams(new LinearLayout.LayoutParams(1734, 1558));
        this.fnpmdlyqrf.setPadding(83, 1, 39, PictureConfig.CHOOSE_REQUEST);
        linearLayout.addView(this.fnpmdlyqrf);
        this.fnpmdlyqrf.setBackgroundColor(Color.parseColor("#c4544a"));
        ScrollView scrollView5 = new ScrollView(this);
        this.vroyvrjrgg = scrollView5;
        scrollView5.setLayoutParams(new LinearLayout.LayoutParams(1998, 388));
        this.vroyvrjrgg.setPadding(175, 24, 3, 196);
        linearLayout.addView(this.vroyvrjrgg);
        this.vroyvrjrgg.setBackgroundColor(Color.parseColor("#d230c4"));
        RadioButton radioButton3 = new RadioButton(this);
        this.pnoqwefgtt = radioButton3;
        radioButton3.setLayoutParams(new LinearLayout.LayoutParams(111, 688));
        this.pnoqwefgtt.setPadding(190, 54, 69, 66);
        linearLayout.addView(this.pnoqwefgtt);
        this.pnoqwefgtt.setBackgroundColor(Color.parseColor("#535eab"));
        EditText editText2 = new EditText(this);
        this.gnlyfwgmmj = editText2;
        editText2.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.Custom.TYPE_FLOAT, 290));
        this.gnlyfwgmmj.setPadding(42, 191, 32, 58);
        linearLayout.addView(this.gnlyfwgmmj);
        this.gnlyfwgmmj.setBackgroundColor(Color.parseColor("#4818d0"));
        TextView textView2 = new TextView(this);
        this.xohsixtzuk = textView2;
        textView2.setLayoutParams(new LinearLayout.LayoutParams(1002, TypedValues.MotionType.TYPE_DRAW_PATH));
        this.xohsixtzuk.setPadding(171, 196, 73, 168);
        linearLayout.addView(this.xohsixtzuk);
        this.xohsixtzuk.setBackgroundColor(Color.parseColor("#62de07"));
        EditText editText3 = new EditText(this);
        this.jcnylzuose = editText3;
        editText3.setLayoutParams(new LinearLayout.LayoutParams(1665, 506));
        this.jcnylzuose.setPadding(60, 180, 197, 179);
        linearLayout.addView(this.jcnylzuose);
        this.jcnylzuose.setBackgroundColor(Color.parseColor("#303db8"));
        LinearLayout linearLayout4 = new LinearLayout(this);
        this.otasqiisrf = linearLayout4;
        linearLayout4.setLayoutParams(new LinearLayout.LayoutParams(1031, 1068));
        this.otasqiisrf.setPadding(175, 67, 15, 2);
        linearLayout.addView(this.otasqiisrf);
        this.otasqiisrf.setBackgroundColor(Color.parseColor("#53d544"));
        CheckBox checkBox4 = new CheckBox(this);
        this.iuxyrtiped = checkBox4;
        checkBox4.setLayoutParams(new LinearLayout.LayoutParams(684, 1911));
        this.iuxyrtiped.setPadding(73, 49, 166, 72);
        linearLayout.addView(this.iuxyrtiped);
        this.iuxyrtiped.setBackgroundColor(Color.parseColor("#f34578"));
        CheckBox checkBox5 = new CheckBox(this);
        this.fsuruwzyph = checkBox5;
        checkBox5.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.CycleType.TYPE_WAVE_OFFSET, 914));
        this.fsuruwzyph.setPadding(64, 32, 195, 189);
        linearLayout.addView(this.fsuruwzyph);
        this.fsuruwzyph.setBackgroundColor(Color.parseColor("#db1c77"));
        ImageView imageView2 = new ImageView(this);
        this.vyjgmvjqse = imageView2;
        imageView2.setLayoutParams(new LinearLayout.LayoutParams(1025, 1146));
        this.vyjgmvjqse.setPadding(143, 165, 1, 194);
        linearLayout.addView(this.vyjgmvjqse);
        this.vyjgmvjqse.setBackgroundColor(Color.parseColor("#705981"));
        ScrollView scrollView6 = new ScrollView(this);
        this.nkkvdpeksh = scrollView6;
        scrollView6.setLayoutParams(new LinearLayout.LayoutParams(737, 91));
        this.nkkvdpeksh.setPadding(116, 89, 166, 80);
        linearLayout.addView(this.nkkvdpeksh);
        this.nkkvdpeksh.setBackgroundColor(Color.parseColor("#27b6fd"));
        FrameLayout frameLayout2 = new FrameLayout(this);
        this.mbpvuneyeo = frameLayout2;
        frameLayout2.setLayoutParams(new LinearLayout.LayoutParams(940, 1122));
        this.mbpvuneyeo.setPadding(57, 28, 38, 119);
        linearLayout.addView(this.mbpvuneyeo);
        this.mbpvuneyeo.setBackgroundColor(Color.parseColor("#14aa07"));
        EditText editText4 = new EditText(this);
        this.sfulzrmjsj = editText4;
        editText4.setLayoutParams(new LinearLayout.LayoutParams(1768, 1129));
        this.sfulzrmjsj.setPadding(70, 173, 127, 62);
        linearLayout.addView(this.sfulzrmjsj);
        this.sfulzrmjsj.setBackgroundColor(Color.parseColor("#243d0a"));
        ToggleButton toggleButton5 = new ToggleButton(this);
        this.ghyqldwpxz = toggleButton5;
        toggleButton5.setLayoutParams(new LinearLayout.LayoutParams(862, 1317));
        this.ghyqldwpxz.setPadding(87, 58, 191, 172);
        linearLayout.addView(this.ghyqldwpxz);
        this.ghyqldwpxz.setBackgroundColor(Color.parseColor("#6efd7d"));
        Button button5 = new Button(this);
        this.qbfqkrbutx = button5;
        button5.setLayoutParams(new LinearLayout.LayoutParams(214, Crop.REQUEST_EDIT_CROP));
        this.qbfqkrbutx.setPadding(17, 40, 67, 17);
        linearLayout.addView(this.qbfqkrbutx);
        this.qbfqkrbutx.setBackgroundColor(Color.parseColor("#e0bb02"));
        ListView listView4 = new ListView(this);
        this.wkeikjvkek = listView4;
        listView4.setLayoutParams(new LinearLayout.LayoutParams(359, 1415));
        this.wkeikjvkek.setPadding(168, 54, 177, 74);
        linearLayout.addView(this.wkeikjvkek);
        this.wkeikjvkek.setBackgroundColor(Color.parseColor("#62422e"));
        EditText editText5 = new EditText(this);
        this.fgbvpulgxt = editText5;
        editText5.setLayoutParams(new LinearLayout.LayoutParams(1412, 1423));
        this.fgbvpulgxt.setPadding(52, 92, 46, 168);
        linearLayout.addView(this.fgbvpulgxt);
        this.fgbvpulgxt.setBackgroundColor(Color.parseColor("#953ae4"));
        LinearLayout linearLayout5 = new LinearLayout(this);
        this.ulweccnilo = linearLayout5;
        linearLayout5.setLayoutParams(new LinearLayout.LayoutParams(1979, 1328));
        this.ulweccnilo.setPadding(105, BDLocation.TypeServerDecryptError, 146, 131);
        linearLayout.addView(this.ulweccnilo);
        this.ulweccnilo.setBackgroundColor(Color.parseColor("#f3ed1e"));
        ViewFlipper viewFlipper4 = new ViewFlipper(this);
        this.cwnvaibkfe = viewFlipper4;
        viewFlipper4.setLayoutParams(new LinearLayout.LayoutParams(1343, 1822));
        this.cwnvaibkfe.setPadding(149, 39, 64, 121);
        linearLayout.addView(this.cwnvaibkfe);
        this.cwnvaibkfe.setBackgroundColor(Color.parseColor("#544b1b"));
        CheckBox checkBox6 = new CheckBox(this);
        this.dpbqhowhmd = checkBox6;
        checkBox6.setLayoutParams(new LinearLayout.LayoutParams(1262, 473));
        this.dpbqhowhmd.setPadding(115, 112, 66, 157);
        linearLayout.addView(this.dpbqhowhmd);
        this.dpbqhowhmd.setBackgroundColor(Color.parseColor("#d44a76"));
        ListView listView5 = new ListView(this);
        this.acvmlbhote = listView5;
        listView5.setLayoutParams(new LinearLayout.LayoutParams(1254, 1120));
        this.acvmlbhote.setPadding(78, 26, 25, 93);
        linearLayout.addView(this.acvmlbhote);
        this.acvmlbhote.setBackgroundColor(Color.parseColor("#51f33c"));
        ToggleButton toggleButton6 = new ToggleButton(this);
        this.xgzpjxdxsm = toggleButton6;
        toggleButton6.setLayoutParams(new LinearLayout.LayoutParams(393, 1871));
        this.xgzpjxdxsm.setPadding(114, 190, 92, 109);
        linearLayout.addView(this.xgzpjxdxsm);
        this.xgzpjxdxsm.setBackgroundColor(Color.parseColor("#964eca"));
        Switch r23 = new Switch(this);
        this.kriyyopeny = r23;
        r23.setLayoutParams(new LinearLayout.LayoutParams(487, 873));
        this.kriyyopeny.setPadding(4, 79, 14, 113);
        linearLayout.addView(this.kriyyopeny);
        this.kriyyopeny.setBackgroundColor(Color.parseColor("#5e83f0"));
        TimePicker timePicker2 = new TimePicker(this);
        this.zelaadhvgf = timePicker2;
        timePicker2.setLayoutParams(new LinearLayout.LayoutParams(3, 972));
        this.zelaadhvgf.setPadding(145, 89, 130, 155);
        linearLayout.addView(this.zelaadhvgf);
        this.zelaadhvgf.setBackgroundColor(Color.parseColor("#b86d4f"));
        Button button6 = new Button(this);
        this.xwgfadietx = button6;
        button6.setLayoutParams(new LinearLayout.LayoutParams(1383, 1336));
        this.xwgfadietx.setPadding(195, 64, 187, 58);
        linearLayout.addView(this.xwgfadietx);
        this.xwgfadietx.setBackgroundColor(Color.parseColor("#465dff"));
        TimePicker timePicker3 = new TimePicker(this);
        this.njpylblemu = timePicker3;
        timePicker3.setLayoutParams(new LinearLayout.LayoutParams(1417, 1619));
        this.njpylblemu.setPadding(111, 4, 37, 139);
        linearLayout.addView(this.njpylblemu);
        this.njpylblemu.setBackgroundColor(Color.parseColor("#10beb3"));
        RelativeLayout relativeLayout3 = new RelativeLayout(this);
        this.wifhltdslz = relativeLayout3;
        relativeLayout3.setLayoutParams(new LinearLayout.LayoutParams(711, 549));
        this.wifhltdslz.setPadding(156, 174, 0, 7);
        linearLayout.addView(this.wifhltdslz);
        this.wifhltdslz.setBackgroundColor(Color.parseColor("#bed252"));
        ImageView imageView3 = new ImageView(this);
        this.scadgzxwxn = imageView3;
        imageView3.setLayoutParams(new LinearLayout.LayoutParams(8, 1219));
        this.scadgzxwxn.setPadding(150, 0, 11, 185);
        linearLayout.addView(this.scadgzxwxn);
        this.scadgzxwxn.setBackgroundColor(Color.parseColor("#520b4e"));
        LinearLayout linearLayout6 = new LinearLayout(this);
        this.hctwcggubv = linearLayout6;
        linearLayout6.setLayoutParams(new LinearLayout.LayoutParams(816, 530));
        this.hctwcggubv.setPadding(32, 86, 37, 66);
        linearLayout.addView(this.hctwcggubv);
        this.hctwcggubv.setBackgroundColor(Color.parseColor("#d897ac"));
        CheckBox checkBox7 = new CheckBox(this);
        this.xnitbpswpy = checkBox7;
        checkBox7.setLayoutParams(new LinearLayout.LayoutParams(334, 322));
        this.xnitbpswpy.setPadding(151, 140, 119, 186);
        linearLayout.addView(this.xnitbpswpy);
        this.xnitbpswpy.setBackgroundColor(Color.parseColor("#2c3b4c"));
        CheckBox checkBox8 = new CheckBox(this);
        this.bgkxhmzvgg = checkBox8;
        checkBox8.setLayoutParams(new LinearLayout.LayoutParams(1097, 1676));
        this.bgkxhmzvgg.setPadding(163, 115, 166, 141);
        linearLayout.addView(this.bgkxhmzvgg);
        this.bgkxhmzvgg.setBackgroundColor(Color.parseColor("#d6edf2"));
        Spinner spinner2 = new Spinner(this);
        this.ecjalzeayg = spinner2;
        spinner2.setLayoutParams(new LinearLayout.LayoutParams(1676, 1170));
        this.ecjalzeayg.setPadding(0, 93, 45, 24);
        linearLayout.addView(this.ecjalzeayg);
        this.ecjalzeayg.setBackgroundColor(Color.parseColor("#d5fbb4"));
        DatePicker datePicker3 = new DatePicker(this);
        this.exxjhcxtci = datePicker3;
        datePicker3.setLayoutParams(new LinearLayout.LayoutParams(444, 1962));
        this.exxjhcxtci.setPadding(2, 146, 32, 56);
        linearLayout.addView(this.exxjhcxtci);
        this.exxjhcxtci.setBackgroundColor(Color.parseColor("#9131a0"));
        SeekBar seekBar = new SeekBar(this);
        this.nchvusheft = seekBar;
        seekBar.setLayoutParams(new LinearLayout.LayoutParams(887, 1038));
        this.nchvusheft.setPadding(95, 134, 67, WebSocketProtocol.PAYLOAD_SHORT);
        linearLayout.addView(this.nchvusheft);
        this.nchvusheft.setBackgroundColor(Color.parseColor("#a03911"));
        TextView textView3 = new TextView(this);
        this.gxtkjwixdk = textView3;
        textView3.setLayoutParams(new LinearLayout.LayoutParams(757, 107));
        this.gxtkjwixdk.setPadding(78, 64, 114, 16);
        linearLayout.addView(this.gxtkjwixdk);
        this.gxtkjwixdk.setBackgroundColor(Color.parseColor("#e6ff4c"));
        ProgressBar progressBar4 = new ProgressBar(this);
        this.pfjsvfytqm = progressBar4;
        progressBar4.setLayoutParams(new LinearLayout.LayoutParams(1155, 300));
        this.pfjsvfytqm.setPadding(37, 64, BDLocation.TypeServerDecryptError, 70);
        linearLayout.addView(this.pfjsvfytqm);
        this.pfjsvfytqm.setBackgroundColor(Color.parseColor("#2f4ee8"));
        SeekBar seekBar2 = new SeekBar(this);
        this.nppiljciwr = seekBar2;
        seekBar2.setLayoutParams(new LinearLayout.LayoutParams(1123, 58));
        this.nppiljciwr.setPadding(7, 4, 13, 87);
        linearLayout.addView(this.nppiljciwr);
        this.nppiljciwr.setBackgroundColor(Color.parseColor("#68c61e"));
        TableLayout tableLayout3 = new TableLayout(this);
        this.ibuxanwyfg = tableLayout3;
        tableLayout3.setLayoutParams(new LinearLayout.LayoutParams(808, 1755));
        this.ibuxanwyfg.setPadding(140, 121, 140, 80);
        linearLayout.addView(this.ibuxanwyfg);
        this.ibuxanwyfg.setBackgroundColor(Color.parseColor("#1790ab"));
        CheckBox checkBox9 = new CheckBox(this);
        this.fjkughlkhu = checkBox9;
        checkBox9.setLayoutParams(new LinearLayout.LayoutParams(533, 1005));
        this.fjkughlkhu.setPadding(BDLocation.TypeServerDecryptError, 194, 37, 58);
        linearLayout.addView(this.fjkughlkhu);
        this.fjkughlkhu.setBackgroundColor(Color.parseColor("#e4dfe9"));
        ProgressBar progressBar5 = new ProgressBar(this);
        this.iinxxilphy = progressBar5;
        progressBar5.setLayoutParams(new LinearLayout.LayoutParams(142, 1653));
        this.iinxxilphy.setPadding(41, 119, 36, 61);
        linearLayout.addView(this.iinxxilphy);
        this.iinxxilphy.setBackgroundColor(Color.parseColor("#84e8bd"));
        ProgressBar progressBar6 = new ProgressBar(this);
        this.curyklvekm = progressBar6;
        progressBar6.setLayoutParams(new LinearLayout.LayoutParams(1007, 1712));
        this.curyklvekm.setPadding(149, 93, 23, 60);
        linearLayout.addView(this.curyklvekm);
        this.curyklvekm.setBackgroundColor(Color.parseColor("#5bf0b3"));
        ProgressBar progressBar7 = new ProgressBar(this);
        this.agvrakklui = progressBar7;
        progressBar7.setLayoutParams(new LinearLayout.LayoutParams(1057, 205));
        this.agvrakklui.setPadding(60, 156, 18, 47);
        linearLayout.addView(this.agvrakklui);
        this.agvrakklui.setBackgroundColor(Color.parseColor("#1010f9"));
        TableLayout tableLayout4 = new TableLayout(this);
        this.foqwwsmswi = tableLayout4;
        tableLayout4.setLayoutParams(new LinearLayout.LayoutParams(1331, 877));
        this.foqwwsmswi.setPadding(14, 122, 33, 119);
        linearLayout.addView(this.foqwwsmswi);
        this.foqwwsmswi.setBackgroundColor(Color.parseColor("#c46b5e"));
        ToggleButton toggleButton7 = new ToggleButton(this);
        this.qtaaphqbpd = toggleButton7;
        toggleButton7.setLayoutParams(new LinearLayout.LayoutParams(174, 1296));
        this.qtaaphqbpd.setPadding(195, 131, 77, 145);
        linearLayout.addView(this.qtaaphqbpd);
        this.qtaaphqbpd.setBackgroundColor(Color.parseColor("#267d86"));
        GridView gridView = new GridView(this);
        this.qztcsckdpj = gridView;
        gridView.setLayoutParams(new LinearLayout.LayoutParams(1593, 726));
        this.qztcsckdpj.setPadding(16, 170, 54, 2);
        linearLayout.addView(this.qztcsckdpj);
        this.qztcsckdpj.setBackgroundColor(Color.parseColor("#29d858"));
        ListView listView6 = new ListView(this);
        this.ejxgmcpraw = listView6;
        listView6.setLayoutParams(new LinearLayout.LayoutParams(756, 55));
        this.ejxgmcpraw.setPadding(196, 104, 175, 155);
        linearLayout.addView(this.ejxgmcpraw);
        this.ejxgmcpraw.setBackgroundColor(Color.parseColor("#8e1687"));
        ProgressBar progressBar8 = new ProgressBar(this);
        this.qoqxjbdlda = progressBar8;
        progressBar8.setLayoutParams(new LinearLayout.LayoutParams(729, 1111));
        this.qoqxjbdlda.setPadding(142, 199, 112, 154);
        linearLayout.addView(this.qoqxjbdlda);
        this.qoqxjbdlda.setBackgroundColor(Color.parseColor("#a89714"));
        ScrollView scrollView7 = new ScrollView(this);
        this.hdvuvinsli = scrollView7;
        scrollView7.setLayoutParams(new LinearLayout.LayoutParams(245, 1218));
        this.hdvuvinsli.setPadding(41, 138, 61, 150);
        linearLayout.addView(this.hdvuvinsli);
        this.hdvuvinsli.setBackgroundColor(Color.parseColor("#04c6c7"));
        TextView textView4 = new TextView(this);
        this.vktbrtqoif = textView4;
        textView4.setLayoutParams(new LinearLayout.LayoutParams(1324, 327));
        this.vktbrtqoif.setPadding(159, 172, 164, 28);
        linearLayout.addView(this.vktbrtqoif);
        this.vktbrtqoif.setBackgroundColor(Color.parseColor("#3f4860"));
        Button button7 = new Button(this);
        this.cddlkwqakw = button7;
        button7.setLayoutParams(new LinearLayout.LayoutParams(1507, 124));
        this.cddlkwqakw.setPadding(25, 99, 5, 146);
        linearLayout.addView(this.cddlkwqakw);
        this.cddlkwqakw.setBackgroundColor(Color.parseColor("#6d774e"));
        GridView gridView2 = new GridView(this);
        this.eouxhdyjsh = gridView2;
        gridView2.setLayoutParams(new LinearLayout.LayoutParams(1343, 1879));
        this.eouxhdyjsh.setPadding(97, 128, 35, 112);
        linearLayout.addView(this.eouxhdyjsh);
        this.eouxhdyjsh.setBackgroundColor(Color.parseColor("#15ca90"));
        LinearLayout linearLayout7 = new LinearLayout(this);
        this.ltxnhqbufd = linearLayout7;
        linearLayout7.setLayoutParams(new LinearLayout.LayoutParams(1827, 476));
        this.ltxnhqbufd.setPadding(110, 61, 103, 86);
        linearLayout.addView(this.ltxnhqbufd);
        this.ltxnhqbufd.setBackgroundColor(Color.parseColor("#9a822b"));
        LinearLayout linearLayout8 = new LinearLayout(this);
        this.ovqoaootfz = linearLayout8;
        linearLayout8.setLayoutParams(new LinearLayout.LayoutParams(1696, 1072));
        this.ovqoaootfz.setPadding(150, 42, 124, 86);
        linearLayout.addView(this.ovqoaootfz);
        this.ovqoaootfz.setBackgroundColor(Color.parseColor("#7c5ec6"));
        ListView listView7 = new ListView(this);
        this.iwiffyqmju = listView7;
        listView7.setLayoutParams(new LinearLayout.LayoutParams(1230, 1441));
        this.iwiffyqmju.setPadding(74, 133, 165, 55);
        linearLayout.addView(this.iwiffyqmju);
        this.iwiffyqmju.setBackgroundColor(Color.parseColor("#b33add"));
        TimePicker timePicker4 = new TimePicker(this);
        this.ibbzzmackr = timePicker4;
        timePicker4.setLayoutParams(new LinearLayout.LayoutParams(BluetoothClassImpl.Device.PERIPHERAL_KEYBOARD_POINTING, 1879));
        this.ibbzzmackr.setPadding(11, 189, 131, 67);
        linearLayout.addView(this.ibbzzmackr);
        this.ibbzzmackr.setBackgroundColor(Color.parseColor("#f0ffbc"));
        TableLayout tableLayout5 = new TableLayout(this);
        this.enyaaflxyj = tableLayout5;
        tableLayout5.setLayoutParams(new LinearLayout.LayoutParams(684, 1059));
        this.enyaaflxyj.setPadding(194, 139, 75, 78);
        linearLayout.addView(this.enyaaflxyj);
        this.enyaaflxyj.setBackgroundColor(Color.parseColor("#67c861"));
        Switch r24 = new Switch(this);
        this.kyhattxjua = r24;
        r24.setLayoutParams(new LinearLayout.LayoutParams(912, 1707));
        this.kyhattxjua.setPadding(92, 156, 197, 67);
        linearLayout.addView(this.kyhattxjua);
        this.kyhattxjua.setBackgroundColor(Color.parseColor("#80afdd"));
        Spinner spinner3 = new Spinner(this);
        this.tafesgtzpr = spinner3;
        spinner3.setLayoutParams(new LinearLayout.LayoutParams(1416, 1255));
        this.tafesgtzpr.setPadding(164, 14, 80, 13);
        linearLayout.addView(this.tafesgtzpr);
        this.tafesgtzpr.setBackgroundColor(Color.parseColor("#73c037"));
        SeekBar seekBar3 = new SeekBar(this);
        this.ktqnourteg = seekBar3;
        seekBar3.setLayoutParams(new LinearLayout.LayoutParams(20, 1668));
        this.ktqnourteg.setPadding(138, 166, 106, 39);
        linearLayout.addView(this.ktqnourteg);
        this.ktqnourteg.setBackgroundColor(Color.parseColor("#7c5894"));
        TextView textView5 = new TextView(this);
        this.cfklqsxkmc = textView5;
        textView5.setLayoutParams(new LinearLayout.LayoutParams(656, 1787));
        this.cfklqsxkmc.setPadding(105, 114, 140, 8);
        linearLayout.addView(this.cfklqsxkmc);
        this.cfklqsxkmc.setBackgroundColor(Color.parseColor("#12f37b"));
        Button button8 = new Button(this);
        this.cswcbvelhx = button8;
        button8.setLayoutParams(new LinearLayout.LayoutParams(1108, 1684));
        this.cswcbvelhx.setPadding(118, 154, 130, 63);
        linearLayout.addView(this.cswcbvelhx);
        this.cswcbvelhx.setBackgroundColor(Color.parseColor("#c26482"));
        ToggleButton toggleButton8 = new ToggleButton(this);
        this.ibeojocixz = toggleButton8;
        toggleButton8.setLayoutParams(new LinearLayout.LayoutParams(1730, 1492));
        this.ibeojocixz.setPadding(100, 109, 64, 151);
        linearLayout.addView(this.ibeojocixz);
        this.ibeojocixz.setBackgroundColor(Color.parseColor("#f1bcd0"));
        EditText editText6 = new EditText(this);
        this.lkxpwtmmfo = editText6;
        editText6.setLayoutParams(new LinearLayout.LayoutParams(646, 105));
        this.lkxpwtmmfo.setPadding(148, 9, 153, 80);
        linearLayout.addView(this.lkxpwtmmfo);
        this.lkxpwtmmfo.setBackgroundColor(Color.parseColor("#662aad"));
        ImageView imageView4 = new ImageView(this);
        this.gbrrayeows = imageView4;
        imageView4.setLayoutParams(new LinearLayout.LayoutParams(BDLocation.TypeCoarseLocation, 646));
        this.gbrrayeows.setPadding(1, 52, 34, 193);
        linearLayout.addView(this.gbrrayeows);
        this.gbrrayeows.setBackgroundColor(Color.parseColor("#6acc26"));
        Button button9 = new Button(this);
        this.loiwvxycdn = button9;
        button9.setLayoutParams(new LinearLayout.LayoutParams(1814, 1159));
        this.loiwvxycdn.setPadding(106, 194, 4, 53);
        linearLayout.addView(this.loiwvxycdn);
        this.loiwvxycdn.setBackgroundColor(Color.parseColor("#4417c9"));
        ListView listView8 = new ListView(this);
        this.kxlpiykkfh = listView8;
        listView8.setLayoutParams(new LinearLayout.LayoutParams(157, 1035));
        this.kxlpiykkfh.setPadding(96, 146, 144, 178);
        linearLayout.addView(this.kxlpiykkfh);
        this.kxlpiykkfh.setBackgroundColor(Color.parseColor("#f4ad10"));
        TimePicker timePicker5 = new TimePicker(this);
        this.iqcchgbshb = timePicker5;
        timePicker5.setLayoutParams(new LinearLayout.LayoutParams(1311, 897));
        this.iqcchgbshb.setPadding(174, 40, 43, 80);
        linearLayout.addView(this.iqcchgbshb);
        this.iqcchgbshb.setBackgroundColor(Color.parseColor("#e8fc74"));
        CheckBox checkBox10 = new CheckBox(this);
        this.amiyxtusfo = checkBox10;
        checkBox10.setLayoutParams(new LinearLayout.LayoutParams(78, 1561));
        this.amiyxtusfo.setPadding(112, 72, 16, 28);
        linearLayout.addView(this.amiyxtusfo);
        this.amiyxtusfo.setBackgroundColor(Color.parseColor("#9fce3f"));
        ListView listView9 = new ListView(this);
        this.fxwkyhebib = listView9;
        listView9.setLayoutParams(new LinearLayout.LayoutParams(1023, 1600));
        this.fxwkyhebib.setPadding(52, 140, 165, 137);
        linearLayout.addView(this.fxwkyhebib);
        this.fxwkyhebib.setBackgroundColor(Color.parseColor("#8ad606"));
        FrameLayout frameLayout3 = new FrameLayout(this);
        this.ficdsqifgx = frameLayout3;
        frameLayout3.setLayoutParams(new LinearLayout.LayoutParams(939, 78));
        this.ficdsqifgx.setPadding(141, 179, 103, 24);
        linearLayout.addView(this.ficdsqifgx);
        this.ficdsqifgx.setBackgroundColor(Color.parseColor("#d62dd4"));
        Switch r25 = new Switch(this);
        this.utwpzgudff = r25;
        r25.setLayoutParams(new LinearLayout.LayoutParams(1400, 360));
        this.utwpzgudff.setPadding(14, 88, 199, 12);
        linearLayout.addView(this.utwpzgudff);
        this.utwpzgudff.setBackgroundColor(Color.parseColor("#0396ff"));
        ImageView imageView5 = new ImageView(this);
        this.iipreomenj = imageView5;
        imageView5.setLayoutParams(new LinearLayout.LayoutParams(1917, 262));
        this.iipreomenj.setPadding(114, 164, 47, 13);
        linearLayout.addView(this.iipreomenj);
        this.iipreomenj.setBackgroundColor(Color.parseColor("#a5c5bb"));
        RatingBar ratingBar2 = new RatingBar(this);
        this.lkxrkzhtkp = ratingBar2;
        ratingBar2.setLayoutParams(new LinearLayout.LayoutParams(218, 1720));
        this.lkxrkzhtkp.setPadding(10, 16, 134, 39);
        linearLayout.addView(this.lkxrkzhtkp);
        this.lkxrkzhtkp.setBackgroundColor(Color.parseColor("#a75115"));
        RelativeLayout relativeLayout4 = new RelativeLayout(this);
        this.zlaxjifyfr = relativeLayout4;
        relativeLayout4.setLayoutParams(new LinearLayout.LayoutParams(1006, 1571));
        this.zlaxjifyfr.setPadding(112, 186, 63, 197);
        linearLayout.addView(this.zlaxjifyfr);
        this.zlaxjifyfr.setBackgroundColor(Color.parseColor("#2d7bdc"));
        ScrollView scrollView8 = new ScrollView(this);
        this.tmbnrqgvyg = scrollView8;
        scrollView8.setLayoutParams(new LinearLayout.LayoutParams(75, 377));
        this.tmbnrqgvyg.setPadding(121, 65, 153, 24);
        linearLayout.addView(this.tmbnrqgvyg);
        this.tmbnrqgvyg.setBackgroundColor(Color.parseColor("#cf442e"));
        RadioButton radioButton4 = new RadioButton(this);
        this.cjdinmllrk = radioButton4;
        radioButton4.setLayoutParams(new LinearLayout.LayoutParams(876, 978));
        this.cjdinmllrk.setPadding(31, 80, 16, 22);
        linearLayout.addView(this.cjdinmllrk);
        this.cjdinmllrk.setBackgroundColor(Color.parseColor("#7a9f14"));
        LinearLayout linearLayout9 = new LinearLayout(this);
        this.hqcfuubtgf = linearLayout9;
        linearLayout9.setLayoutParams(new LinearLayout.LayoutParams(927, 1325));
        this.hqcfuubtgf.setPadding(51, 53, 145, 193);
        linearLayout.addView(this.hqcfuubtgf);
        this.hqcfuubtgf.setBackgroundColor(Color.parseColor("#035f53"));
        Button button10 = new Button(this);
        this.ykwvjinypb = button10;
        button10.setLayoutParams(new LinearLayout.LayoutParams(1799, 587));
        this.ykwvjinypb.setPadding(64, 52, 163, 69);
        linearLayout.addView(this.ykwvjinypb);
        this.ykwvjinypb.setBackgroundColor(Color.parseColor("#da75e5"));
        Switch r26 = new Switch(this);
        this.nepqequqxp = r26;
        r26.setLayoutParams(new LinearLayout.LayoutParams(785, 321));
        this.nepqequqxp.setPadding(132, 164, 122, 197);
        linearLayout.addView(this.nepqequqxp);
        this.nepqequqxp.setBackgroundColor(Color.parseColor("#f3d984"));
        Button button11 = new Button(this);
        this.hykreixasb = button11;
        button11.setLayoutParams(new LinearLayout.LayoutParams(1710, 1711));
        this.hykreixasb.setPadding(90, 156, 45, 100);
        linearLayout.addView(this.hykreixasb);
        this.hykreixasb.setBackgroundColor(Color.parseColor("#6b1ea0"));
        ListView listView10 = new ListView(this);
        this.mxmllqckhw = listView10;
        listView10.setLayoutParams(new LinearLayout.LayoutParams(265, 666));
        this.mxmllqckhw.setPadding(67, 99, 15, 83);
        linearLayout.addView(this.mxmllqckhw);
        this.mxmllqckhw.setBackgroundColor(Color.parseColor("#3ec402"));
        RadioButton radioButton5 = new RadioButton(this);
        this.aehqrpviey = radioButton5;
        radioButton5.setLayoutParams(new LinearLayout.LayoutParams(775, 730));
        this.aehqrpviey.setPadding(82, 186, 139, 132);
        linearLayout.addView(this.aehqrpviey);
        this.aehqrpviey.setBackgroundColor(Color.parseColor("#87a941"));
        ImageView imageView6 = new ImageView(this);
        this.duwswniezx = imageView6;
        imageView6.setLayoutParams(new LinearLayout.LayoutParams(948, 1514));
        this.duwswniezx.setPadding(94, 23, 74, 137);
        linearLayout.addView(this.duwswniezx);
        this.duwswniezx.setBackgroundColor(Color.parseColor("#ca9bae"));
        GridView gridView3 = new GridView(this);
        this.rmrtwmarbt = gridView3;
        gridView3.setLayoutParams(new LinearLayout.LayoutParams(181, 370));
        this.rmrtwmarbt.setPadding(74, 32, 79, 113);
        linearLayout.addView(this.rmrtwmarbt);
        this.rmrtwmarbt.setBackgroundColor(Color.parseColor("#1036a5"));
        ViewFlipper viewFlipper5 = new ViewFlipper(this);
        this.mxasiabqos = viewFlipper5;
        viewFlipper5.setLayoutParams(new LinearLayout.LayoutParams(1568, PointerIconCompat.TYPE_ZOOM_IN));
        this.mxasiabqos.setPadding(127, 193, 26, 177);
        linearLayout.addView(this.mxasiabqos);
        this.mxasiabqos.setBackgroundColor(Color.parseColor("#ff2332"));
        TimePicker timePicker6 = new TimePicker(this);
        this.htcxjxrnwu = timePicker6;
        timePicker6.setLayoutParams(new LinearLayout.LayoutParams(864, 1653));
        this.htcxjxrnwu.setPadding(139, 115, 26, 28);
        linearLayout.addView(this.htcxjxrnwu);
        this.htcxjxrnwu.setBackgroundColor(Color.parseColor("#b225e2"));
        RatingBar ratingBar3 = new RatingBar(this);
        this.etiyzxnmbt = ratingBar3;
        ratingBar3.setLayoutParams(new LinearLayout.LayoutParams(973, 623));
        this.etiyzxnmbt.setPadding(91, 122, 155, 135);
        linearLayout.addView(this.etiyzxnmbt);
        this.etiyzxnmbt.setBackgroundColor(Color.parseColor("#c803dc"));
        ViewFlipper viewFlipper6 = new ViewFlipper(this);
        this.pzadqgduqx = viewFlipper6;
        viewFlipper6.setLayoutParams(new LinearLayout.LayoutParams(769, 45));
        this.pzadqgduqx.setPadding(91, 130, 8, 195);
        linearLayout.addView(this.pzadqgduqx);
        this.pzadqgduqx.setBackgroundColor(Color.parseColor("#175204"));
        CheckBox checkBox11 = new CheckBox(this);
        this.okhzmdowvz = checkBox11;
        checkBox11.setLayoutParams(new LinearLayout.LayoutParams(1390, 1433));
        this.okhzmdowvz.setPadding(WebSocketProtocol.PAYLOAD_SHORT, 39, 155, BDLocation.TypeServerError);
        linearLayout.addView(this.okhzmdowvz);
        this.okhzmdowvz.setBackgroundColor(Color.parseColor("#a3fa92"));
        Spinner spinner4 = new Spinner(this);
        this.wanqejytiy = spinner4;
        spinner4.setLayoutParams(new LinearLayout.LayoutParams(1731, 814));
        this.wanqejytiy.setPadding(113, 175, 88, 193);
        linearLayout.addView(this.wanqejytiy);
        this.wanqejytiy.setBackgroundColor(Color.parseColor("#79e65d"));
        ViewFlipper viewFlipper7 = new ViewFlipper(this);
        this.ablolhjusm = viewFlipper7;
        viewFlipper7.setLayoutParams(new LinearLayout.LayoutParams(1926, 830));
        this.ablolhjusm.setPadding(177, 93, 0, BDLocation.TypeNetWorkLocation);
        linearLayout.addView(this.ablolhjusm);
        this.ablolhjusm.setBackgroundColor(Color.parseColor("#ca964b"));
        TextView textView6 = new TextView(this);
        this.jmcudpbazg = textView6;
        textView6.setLayoutParams(new LinearLayout.LayoutParams(1252, 1397));
        this.jmcudpbazg.setPadding(60, 139, 97, 179);
        linearLayout.addView(this.jmcudpbazg);
        this.jmcudpbazg.setBackgroundColor(Color.parseColor("#79d5d5"));
    }
}
