package com.device.watch.com.device.watch.tsmihfhjrs;

import android.app.Activity;
import android.graphics.Color;
import android.os.Bundle;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.CheckBox;
import android.widget.DatePicker;
import android.widget.EditText;
import android.widget.FrameLayout;
import android.widget.GridView;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ListView;
import android.widget.ProgressBar;
import android.widget.RadioButton;
import android.widget.RatingBar;
import android.widget.RelativeLayout;
import android.widget.ScrollView;
import android.widget.SeekBar;
import android.widget.Spinner;
import android.widget.Switch;
import android.widget.TableLayout;
import android.widget.TextView;
import android.widget.TimePicker;
import android.widget.ToggleButton;
import android.widget.ViewFlipper;
import androidx.constraintlayout.core.motion.utils.TypedValues;
import androidx.core.view.PointerIconCompat;
import androidx.room.RoomDatabase;
import com.baidu.location.BDLocation;
import com.luck.picture.lib.config.PictureConfig;
import com.qcwireless.qcwatch.ui.base.imagepicker.cropper.CropImage;
import com.realsil.sdk.audioconnect.localplayback.LocalPlaybackConstants;
import com.realsil.sdk.core.bluetooth.connection.le.GattClient;
import okhttp3.internal.ws.WebSocketProtocol;

/* loaded from: classes2.dex */
public class TnzxpoptszfActivity extends Activity {
    CheckBox afxfeccaer;
    Spinner ajnuutxmed;
    LinearLayout aqycjbwmep;
    TextView asmanbxvdo;
    ListView bdjttmhdiq;
    RelativeLayout bkglsnaokp;
    DatePicker bqlocdmavy;
    LinearLayout bwdhsirzgf;
    Switch bzmnexylco;
    Spinner chkdnszheb;
    Switch cmigyzyxxx;
    TimePicker cmlprfgnai;
    ImageView cniflvruwz;
    RelativeLayout cpoxqfeevx;
    ViewFlipper cprdywgxom;
    DatePicker cqvlgcbxye;
    FrameLayout csrowbwtir;
    Spinner cvuraeorzl;
    ListView cvyakebxya;
    DatePicker cwepfcbxqk;
    DatePicker cwpadnfpnc;
    Switch cwxcthlzky;
    RadioButton dafwmgxwze;
    ViewFlipper dgxfrlcgkt;
    ListView dihdjvusad;
    RatingBar dillkwxlai;
    GridView djksfzzcgi;
    RelativeLayout dtlxpelhfy;
    TableLayout dwouqyjyzh;
    RadioButton dxfxdplqkw;
    SeekBar ebirlzycsx;
    ListView ebqhrpcnbx;
    SeekBar ecfemfdnag;
    CheckBox ehdqihmbfr;
    RadioButton eikyrytjlo;
    TextView ejlbznwfnx;
    SeekBar ekmmtirfen;
    Switch ellagozjfm;
    LinearLayout eqrdisward;
    RadioButton eqzbrpdzmn;
    DatePicker erugtnjolf;
    Switch etvsgtdgmr;
    TableLayout exdxasdnqr;
    GridView fewdmcmtvq;
    Switch fibrtamdpn;
    ViewFlipper fmitqoufnh;
    ProgressBar fmlazkgwnm;
    ProgressBar fmmvmiydmm;
    ViewFlipper fonzilhopp;
    RelativeLayout fsnldmhzzc;
    ToggleButton ftarbumvje;
    LinearLayout fxqphmiero;
    ListView fzfbmjqjlo;
    Switch gbwyxapmdj;
    ViewFlipper gdqrhiafbs;
    EditText ggzqhxwthe;
    Spinner giaeekuefa;
    DatePicker gibsshbhoy;
    EditText gimzgxlsri;
    ListView glsecqvukw;
    ViewFlipper gnyffsdrrx;
    ToggleButton gvzhszomsv;
    Spinner gzdnsvuukg;
    TextView hahojciakt;
    ViewFlipper hmtccnjrsh;
    Button hopvvvmuzp;
    Button hvgvdhofso;
    EditText hybxagonhr;
    Button ibgdgbvfcc;
    TextView ibkffsmati;
    LinearLayout ibocommyez;
    SeekBar ibscpupksl;
    EditText icrgfkehsp;
    LinearLayout iffbsecflo;
    RatingBar igouwpcisi;
    CheckBox iijpeolzii;
    FrameLayout imfykqczen;
    Switch iobervlyrb;
    CheckBox isezoqbhdu;
    ToggleButton iwmwmzrrjj;
    Spinner jctgnwgryt;
    RatingBar jgsgzzsaxn;
    FrameLayout jinauwkemy;
    FrameLayout jttqpokxwx;
    SeekBar jufduvgjzn;
    RelativeLayout juzpymepln;
    RatingBar jyedzmdhit;
    TableLayout jywlwykull;
    DatePicker jzqtcaqlan;
    RadioButton kbkomnjxhc;
    TextView kcstcxnjih;
    CheckBox keymvfzbqy;
    RelativeLayout kjmmjsmync;
    SeekBar kmaueakxjf;
    Switch kprcaheyrp;
    RelativeLayout krueggaqgy;
    DatePicker kselwotlqz;
    Switch kvzzqvisvc;
    ListView kynvurekyi;
    Switch kzuqnyhxgo;
    ViewFlipper lbtntoielq;
    TextView lchchgnhko;
    ListView lfmdtsmhpz;
    CheckBox lkdbqusuew;
    Button lltocvsikk;
    ImageView lltsnfebgy;
    ListView loxtbizpzg;
    GridView lubpnrtejh;
    ListView mcctpqsdmy;
    Spinner mdwobvxjck;
    ToggleButton mnqmpwmttd;
    EditText moofrwmmny;
    TextView mrnudynshk;
    FrameLayout msoiydmutv;
    SeekBar mtrckbatgx;
    Spinner mvkskjszvy;
    CheckBox mvoszyxnbk;
    ScrollView nfvyicnbkh;
    EditText nkxvisvlfd;
    RatingBar nnoievbyod;
    RatingBar nrtfldotlo;
    Button ntkhwcvtqh;
    ScrollView nvmoxvsuug;
    ListView nwmqcatgti;
    TextView nxmexfwnca;
    Switch nxnuoddesa;
    RelativeLayout owjsirkzxi;
    ImageView oxfsxpqipu;
    FrameLayout oxqqcqkldk;
    Spinner oypgxvofwk;
    ViewFlipper pgezowlzxq;
    TextView pgvnzrmbnv;
    RadioButton pgxdvocrvw;
    Spinner phwqrzjwtl;
    TextView pkozkhjdhq;
    ScrollView pnatynrlae;
    CheckBox pqwofugcdh;
    TimePicker puntymwzhl;
    TableLayout pxrraeeqln;
    SeekBar pxznkzkdfv;
    Button qcvcdayqsm;
    Spinner qdxzeprkqf;
    DatePicker qhyuegswih;
    ScrollView qicdpgnvno;
    EditText qlzxjtqaqu;
    RatingBar qnqyrzxibg;
    TableLayout qnzpxivtvm;
    LinearLayout qoxfwsuqig;
    ListView qsxtahobuh;
    RadioButton qtqondxrzn;
    EditText qylbjmlsob;
    TimePicker qzsvgbeazw;
    Spinner rhupmiyrto;
    LinearLayout rjdctcfqzb;
    ScrollView rxmpyqqoyd;
    RelativeLayout saaglafwtr;
    TimePicker scfbcoxkft;
    ListView scmxdptcsn;
    RelativeLayout seamycqtkw;
    ImageView secgrinzgb;
    RadioButton sgmtmmwudl;
    ScrollView sgybhcadjs;
    GridView slcefwrssd;
    RadioButton sldixtokki;
    TextView slttwhuvtk;
    RatingBar slyrxspoef;
    TextView slytliqxwi;
    ImageView smdkndtdrn;
    TextView srfffnlqks;
    CheckBox sumyblxwmu;
    TextView swlnpulnoh;
    DatePicker sxqzntlims;
    TimePicker tfzksqvzit;
    TextView thhnmzyfbp;
    GridView thhqhtnbvr;
    TextView tmurcoupjx;
    Button trqirefvef;
    TextView txgebszemw;
    DatePicker uatmyysebc;
    SeekBar ubakjbergo;
    CheckBox ukqdaxklkg;
    LinearLayout uomsrafmjs;
    ListView uoqizrvjgr;
    RatingBar uqvjgjbmap;
    LinearLayout urawxsntnb;
    CheckBox vajlcolcom;
    ImageView vezowcmqoc;
    RelativeLayout vjeetlkloi;
    ScrollView vlfknnfpzv;
    RatingBar vnpgntkgmz;
    LinearLayout vpfeykxuop;
    FrameLayout vvxndnroqz;
    TableLayout wclgxitrbq;
    TextView wdrzqsjuhk;
    TextView weyeaoikrq;
    ToggleButton wfjeetqrid;
    ListView wgtdofikii;
    FrameLayout wicfmxlwoy;
    LinearLayout wijfrcvlgf;
    ListView wlvcejxmzi;
    ProgressBar wmlownrgsp;
    ListView wtpdpwwyxk;
    SeekBar wvnuspadad;
    ViewFlipper wwmriczyhl;
    ImageView xafrkiahel;
    RatingBar xdhvaixjzm;
    EditText xeaxlyrjmk;
    ProgressBar xenlkdqprk;
    TimePicker xgrznkmokl;
    RelativeLayout xisegsvswn;
    Button xmligarggd;
    EditText xnmrqgndwb;
    ScrollView xrijurukts;
    ProgressBar xtamqgrmnv;
    ImageView xxgbxvxhoi;
    ToggleButton yccqsmjiyi;
    ListView ydzcgxxhla;
    CheckBox yiwiqvenau;
    TimePicker ylwjijhucc;
    FrameLayout yoteosbkjc;
    ViewFlipper yrtjqzihps;
    DatePicker yurbeqltlf;
    ViewFlipper zalnnnbouo;
    RatingBar zbdplhoqbd;
    ToggleButton zbotrjgyux;
    Spinner zczwqpcgdn;
    Button zfaomllbyr;
    LinearLayout zmkdhbqxcx;
    FrameLayout znahihnsnc;
    SeekBar znwrkmgayk;
    FrameLayout zqbyjabaht;
    LinearLayout zsdlsfpfjg;
    CheckBox zwxvslfasz;
    LinearLayout zybsckaqat;
    ImageView zyqumasyyk;
    RatingBar zzmekoghtz;

    @Override // android.app.Activity
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        LinearLayout linearLayout = new LinearLayout(this);
        setContentView(linearLayout);
        linearLayout.setLayoutParams(new ViewGroup.LayoutParams(-1, -1));
        linearLayout.setOrientation(1);
        linearLayout.setBackgroundColor(Color.parseColor("#565b60"));
        SeekBar seekBar = new SeekBar(this);
        this.jufduvgjzn = seekBar;
        seekBar.setLayoutParams(new LinearLayout.LayoutParams(1732, 234));
        this.jufduvgjzn.setPadding(194, 133, 29, 29);
        linearLayout.addView(this.jufduvgjzn);
        this.jufduvgjzn.setBackgroundColor(Color.parseColor("#f05d2c"));
        ImageView imageView = new ImageView(this);
        this.xxgbxvxhoi = imageView;
        imageView.setLayoutParams(new LinearLayout.LayoutParams(1461, 1509));
        this.xxgbxvxhoi.setPadding(157, 108, 42, 187);
        linearLayout.addView(this.xxgbxvxhoi);
        this.xxgbxvxhoi.setBackgroundColor(Color.parseColor("#1c84ca"));
        RelativeLayout relativeLayout = new RelativeLayout(this);
        this.seamycqtkw = relativeLayout;
        relativeLayout.setLayoutParams(new LinearLayout.LayoutParams(484, 1196));
        this.seamycqtkw.setPadding(133, 192, 131, 64);
        linearLayout.addView(this.seamycqtkw);
        this.seamycqtkw.setBackgroundColor(Color.parseColor("#26f314"));
        DatePicker datePicker = new DatePicker(this);
        this.sxqzntlims = datePicker;
        datePicker.setLayoutParams(new LinearLayout.LayoutParams(260, 25));
        this.sxqzntlims.setPadding(87, 20, 166, 10);
        linearLayout.addView(this.sxqzntlims);
        this.sxqzntlims.setBackgroundColor(Color.parseColor("#5ca9d1"));
        CheckBox checkBox = new CheckBox(this);
        this.sumyblxwmu = checkBox;
        checkBox.setLayoutParams(new LinearLayout.LayoutParams(1254, 1180));
        this.sumyblxwmu.setPadding(27, 187, 152, 1);
        linearLayout.addView(this.sumyblxwmu);
        this.sumyblxwmu.setBackgroundColor(Color.parseColor("#e5c36f"));
        FrameLayout frameLayout = new FrameLayout(this);
        this.msoiydmutv = frameLayout;
        frameLayout.setLayoutParams(new LinearLayout.LayoutParams(171, 628));
        this.msoiydmutv.setPadding(150, 17, 72, 124);
        linearLayout.addView(this.msoiydmutv);
        this.msoiydmutv.setBackgroundColor(Color.parseColor("#3784e5"));
        TextView textView = new TextView(this);
        this.pgvnzrmbnv = textView;
        textView.setLayoutParams(new LinearLayout.LayoutParams(1072, 3));
        this.pgvnzrmbnv.setPadding(65, 138, 50, WebSocketProtocol.PAYLOAD_SHORT);
        linearLayout.addView(this.pgvnzrmbnv);
        this.pgvnzrmbnv.setBackgroundColor(Color.parseColor("#8c275d"));
        FrameLayout frameLayout2 = new FrameLayout(this);
        this.zqbyjabaht = frameLayout2;
        frameLayout2.setLayoutParams(new LinearLayout.LayoutParams(713, 227));
        this.zqbyjabaht.setPadding(74, 135, 13, 38);
        linearLayout.addView(this.zqbyjabaht);
        this.zqbyjabaht.setBackgroundColor(Color.parseColor("#c9cc3d"));
        ToggleButton toggleButton = new ToggleButton(this);
        this.mnqmpwmttd = toggleButton;
        toggleButton.setLayoutParams(new LinearLayout.LayoutParams(67, 1823));
        this.mnqmpwmttd.setPadding(70, 176, 178, 61);
        linearLayout.addView(this.mnqmpwmttd);
        this.mnqmpwmttd.setBackground(new Llhrpmsnplz());
        RatingBar ratingBar = new RatingBar(this);
        this.dillkwxlai = ratingBar;
        ratingBar.setLayoutParams(new LinearLayout.LayoutParams(1202, 1032));
        this.dillkwxlai.setPadding(0, 164, 55, BDLocation.TypeNetWorkLocation);
        linearLayout.addView(this.dillkwxlai);
        this.dillkwxlai.setBackgroundColor(Color.parseColor("#901558"));
        TextView textView2 = new TextView(this);
        this.ejlbznwfnx = textView2;
        textView2.setLayoutParams(new LinearLayout.LayoutParams(1291, 1790));
        this.ejlbznwfnx.setPadding(164, 12, 170, 152);
        linearLayout.addView(this.ejlbznwfnx);
        this.ejlbznwfnx.setBackgroundColor(Color.parseColor("#2eee9d"));
        ProgressBar progressBar = new ProgressBar(this);
        this.wmlownrgsp = progressBar;
        progressBar.setLayoutParams(new LinearLayout.LayoutParams(1458, 220));
        this.wmlownrgsp.setPadding(180, 37, 0, 157);
        linearLayout.addView(this.wmlownrgsp);
        this.wmlownrgsp.setBackgroundColor(Color.parseColor("#3e1217"));
        TableLayout tableLayout = new TableLayout(this);
        this.exdxasdnqr = tableLayout;
        tableLayout.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.TransitionType.TYPE_TO, 1109));
        this.exdxasdnqr.setPadding(124, 36, 148, 195);
        linearLayout.addView(this.exdxasdnqr);
        this.exdxasdnqr.setBackgroundColor(Color.parseColor("#420b79"));
        ListView listView = new ListView(this);
        this.loxtbizpzg = listView;
        listView.setLayoutParams(new LinearLayout.LayoutParams(570, 1177));
        this.loxtbizpzg.setPadding(1, 148, 46, 84);
        linearLayout.addView(this.loxtbizpzg);
        this.loxtbizpzg.setBackgroundColor(Color.parseColor("#3e6f6f"));
        TableLayout tableLayout2 = new TableLayout(this);
        this.wclgxitrbq = tableLayout2;
        tableLayout2.setLayoutParams(new LinearLayout.LayoutParams(1554, 1516));
        this.wclgxitrbq.setPadding(89, 91, 88, 19);
        linearLayout.addView(this.wclgxitrbq);
        this.wclgxitrbq.setBackgroundColor(Color.parseColor("#1b86fe"));
        ViewFlipper viewFlipper = new ViewFlipper(this);
        this.cprdywgxom = viewFlipper;
        viewFlipper.setLayoutParams(new LinearLayout.LayoutParams(1855, 1565));
        this.cprdywgxom.setPadding(180, 8, 28, 140);
        linearLayout.addView(this.cprdywgxom);
        this.cprdywgxom.setBackgroundColor(Color.parseColor("#a42d29"));
        ProgressBar progressBar2 = new ProgressBar(this);
        this.xenlkdqprk = progressBar2;
        progressBar2.setLayoutParams(new LinearLayout.LayoutParams(1480, 1049));
        this.xenlkdqprk.setPadding(69, 172, 165, 73);
        linearLayout.addView(this.xenlkdqprk);
        this.xenlkdqprk.setBackgroundColor(Color.parseColor("#31ac27"));
        LinearLayout linearLayout2 = new LinearLayout(this);
        this.zsdlsfpfjg = linearLayout2;
        linearLayout2.setLayoutParams(new LinearLayout.LayoutParams(351, 1814));
        this.zsdlsfpfjg.setPadding(68, 125, 143, 121);
        linearLayout.addView(this.zsdlsfpfjg);
        this.zsdlsfpfjg.setBackgroundColor(Color.parseColor("#e085ac"));
        TableLayout tableLayout3 = new TableLayout(this);
        this.qnzpxivtvm = tableLayout3;
        tableLayout3.setLayoutParams(new LinearLayout.LayoutParams(1132, 1396));
        this.qnzpxivtvm.setPadding(43, 18, 141, 129);
        linearLayout.addView(this.qnzpxivtvm);
        this.qnzpxivtvm.setBackgroundColor(Color.parseColor("#449547"));
        DatePicker datePicker2 = new DatePicker(this);
        this.uatmyysebc = datePicker2;
        datePicker2.setLayoutParams(new LinearLayout.LayoutParams(1649, 54));
        this.uatmyysebc.setPadding(91, 16, 62, 149);
        linearLayout.addView(this.uatmyysebc);
        this.uatmyysebc.setBackgroundColor(Color.parseColor("#860e7b"));
        CheckBox checkBox2 = new CheckBox(this);
        this.iijpeolzii = checkBox2;
        checkBox2.setLayoutParams(new LinearLayout.LayoutParams(514, 1447));
        this.iijpeolzii.setPadding(107, 26, 60, 32);
        linearLayout.addView(this.iijpeolzii);
        this.iijpeolzii.setBackgroundColor(Color.parseColor("#1319dc"));
        RadioButton radioButton = new RadioButton(this);
        this.dxfxdplqkw = radioButton;
        radioButton.setLayoutParams(new LinearLayout.LayoutParams(1975, 992));
        this.dxfxdplqkw.setPadding(140, 190, BDLocation.TypeServerDecryptError, 144);
        linearLayout.addView(this.dxfxdplqkw);
        this.dxfxdplqkw.setBackgroundColor(Color.parseColor("#63f772"));
        LinearLayout linearLayout3 = new LinearLayout(this);
        this.zybsckaqat = linearLayout3;
        linearLayout3.setLayoutParams(new LinearLayout.LayoutParams(73, 1279));
        this.zybsckaqat.setPadding(180, 84, 168, 142);
        linearLayout.addView(this.zybsckaqat);
        this.zybsckaqat.setBackgroundColor(Color.parseColor("#c6a757"));
        FrameLayout frameLayout3 = new FrameLayout(this);
        this.oxqqcqkldk = frameLayout3;
        frameLayout3.setLayoutParams(new LinearLayout.LayoutParams(1294, 1274));
        this.oxqqcqkldk.setPadding(29, 154, 22, 65);
        linearLayout.addView(this.oxqqcqkldk);
        this.oxqqcqkldk.setBackgroundColor(Color.parseColor("#2f83e2"));
        Spinner spinner = new Spinner(this);
        this.chkdnszheb = spinner;
        spinner.setLayoutParams(new LinearLayout.LayoutParams(298, 1849));
        this.chkdnszheb.setPadding(34, 147, BDLocation.TypeServerDecryptError, 50);
        linearLayout.addView(this.chkdnszheb);
        this.chkdnszheb.setBackgroundColor(Color.parseColor("#826008"));
        Spinner spinner2 = new Spinner(this);
        this.gzdnsvuukg = spinner2;
        spinner2.setLayoutParams(new LinearLayout.LayoutParams(1931, 1274));
        this.gzdnsvuukg.setPadding(70, 125, 166, 131);
        linearLayout.addView(this.gzdnsvuukg);
        this.gzdnsvuukg.setBackgroundColor(Color.parseColor("#424328"));
        TextView textView3 = new TextView(this);
        this.weyeaoikrq = textView3;
        textView3.setLayoutParams(new LinearLayout.LayoutParams(1672, 1526));
        this.weyeaoikrq.setPadding(24, 33, 42, 178);
        linearLayout.addView(this.weyeaoikrq);
        this.weyeaoikrq.setBackgroundColor(Color.parseColor("#e16c28"));
        RadioButton radioButton2 = new RadioButton(this);
        this.dafwmgxwze = radioButton2;
        radioButton2.setLayoutParams(new LinearLayout.LayoutParams(975, 1001));
        this.dafwmgxwze.setPadding(94, 84, 194, 18);
        linearLayout.addView(this.dafwmgxwze);
        this.dafwmgxwze.setBackgroundColor(Color.parseColor("#be2192"));
        ViewFlipper viewFlipper2 = new ViewFlipper(this);
        this.fonzilhopp = viewFlipper2;
        viewFlipper2.setLayoutParams(new LinearLayout.LayoutParams(1760, 408));
        this.fonzilhopp.setPadding(13, 76, 141, 81);
        linearLayout.addView(this.fonzilhopp);
        this.fonzilhopp.setBackgroundColor(Color.parseColor("#8e01f7"));
        SeekBar seekBar2 = new SeekBar(this);
        this.ebirlzycsx = seekBar2;
        seekBar2.setLayoutParams(new LinearLayout.LayoutParams(1026, 19));
        this.ebirlzycsx.setPadding(27, 198, 115, 140);
        linearLayout.addView(this.ebirlzycsx);
        this.ebirlzycsx.setBackgroundColor(Color.parseColor("#1ddc9f"));
        SeekBar seekBar3 = new SeekBar(this);
        this.pxznkzkdfv = seekBar3;
        seekBar3.setLayoutParams(new LinearLayout.LayoutParams(233, 1667));
        this.pxznkzkdfv.setPadding(114, 100, 73, 94);
        linearLayout.addView(this.pxznkzkdfv);
        this.pxznkzkdfv.setBackgroundColor(Color.parseColor("#d2b398"));
        RatingBar ratingBar2 = new RatingBar(this);
        this.jgsgzzsaxn = ratingBar2;
        ratingBar2.setLayoutParams(new LinearLayout.LayoutParams(PointerIconCompat.TYPE_ZOOM_IN, 1638));
        this.jgsgzzsaxn.setPadding(50, 20, 3, 97);
        linearLayout.addView(this.jgsgzzsaxn);
        this.jgsgzzsaxn.setBackgroundColor(Color.parseColor("#783eab"));
        EditText editText = new EditText(this);
        this.xnmrqgndwb = editText;
        editText.setLayoutParams(new LinearLayout.LayoutParams(1588, 829));
        this.xnmrqgndwb.setPadding(49, 179, 141, 84);
        linearLayout.addView(this.xnmrqgndwb);
        this.xnmrqgndwb.setBackgroundColor(Color.parseColor("#ad0f61"));
        DatePicker datePicker3 = new DatePicker(this);
        this.gibsshbhoy = datePicker3;
        datePicker3.setLayoutParams(new LinearLayout.LayoutParams(1843, 751));
        this.gibsshbhoy.setPadding(1, 24, 136, 91);
        linearLayout.addView(this.gibsshbhoy);
        this.gibsshbhoy.setBackgroundColor(Color.parseColor("#66c02f"));
        Button button = new Button(this);
        this.trqirefvef = button;
        button.setLayoutParams(new LinearLayout.LayoutParams(1068, 1647));
        this.trqirefvef.setPadding(102, 12, 189, 174);
        linearLayout.addView(this.trqirefvef);
        this.trqirefvef.setBackgroundColor(Color.parseColor("#6a13bf"));
        Switch r3 = new Switch(this);
        this.ellagozjfm = r3;
        r3.setLayoutParams(new LinearLayout.LayoutParams(BDLocation.TypeServerError, 545));
        this.ellagozjfm.setPadding(59, 79, 192, 112);
        linearLayout.addView(this.ellagozjfm);
        this.ellagozjfm.setBackgroundColor(Color.parseColor("#01a7ef"));
        ScrollView scrollView = new ScrollView(this);
        this.pnatynrlae = scrollView;
        scrollView.setLayoutParams(new LinearLayout.LayoutParams(213, 1778));
        this.pnatynrlae.setPadding(97, 29, 51, BDLocation.TypeCoarseLocation);
        linearLayout.addView(this.pnatynrlae);
        this.pnatynrlae.setBackgroundColor(Color.parseColor("#ccad87"));
        TableLayout tableLayout4 = new TableLayout(this);
        this.jywlwykull = tableLayout4;
        tableLayout4.setLayoutParams(new LinearLayout.LayoutParams(103, 1406));
        this.jywlwykull.setPadding(83, 71, 68, 116);
        linearLayout.addView(this.jywlwykull);
        this.jywlwykull.setBackgroundColor(Color.parseColor("#27a5b7"));
        FrameLayout frameLayout4 = new FrameLayout(this);
        this.csrowbwtir = frameLayout4;
        frameLayout4.setLayoutParams(new LinearLayout.LayoutParams(1983, 4));
        this.csrowbwtir.setPadding(32, WebSocketProtocol.PAYLOAD_SHORT, 101, 121);
        linearLayout.addView(this.csrowbwtir);
        this.csrowbwtir.setBackgroundColor(Color.parseColor("#974ff4"));
        TextView textView4 = new TextView(this);
        this.txgebszemw = textView4;
        textView4.setLayoutParams(new LinearLayout.LayoutParams(686, 460));
        this.txgebszemw.setPadding(174, 74, 120, 104);
        linearLayout.addView(this.txgebszemw);
        this.txgebszemw.setBackgroundColor(Color.parseColor("#bf63bf"));
        DatePicker datePicker4 = new DatePicker(this);
        this.cwpadnfpnc = datePicker4;
        datePicker4.setLayoutParams(new LinearLayout.LayoutParams(1923, 433));
        this.cwpadnfpnc.setPadding(63, 112, 76, 123);
        linearLayout.addView(this.cwpadnfpnc);
        this.cwpadnfpnc.setBackgroundColor(Color.parseColor("#d3c961"));
        TableLayout tableLayout5 = new TableLayout(this);
        this.dwouqyjyzh = tableLayout5;
        tableLayout5.setLayoutParams(new LinearLayout.LayoutParams(1604, 1746));
        this.dwouqyjyzh.setPadding(91, 186, 71, 166);
        linearLayout.addView(this.dwouqyjyzh);
        this.dwouqyjyzh.setBackgroundColor(Color.parseColor("#6d66a5"));
        Switch r32 = new Switch(this);
        this.gbwyxapmdj = r32;
        r32.setLayoutParams(new LinearLayout.LayoutParams(1107, 1099));
        this.gbwyxapmdj.setPadding(19, 40, 177, 130);
        linearLayout.addView(this.gbwyxapmdj);
        this.gbwyxapmdj.setBackgroundColor(Color.parseColor("#46ddce"));
        SeekBar seekBar4 = new SeekBar(this);
        this.ubakjbergo = seekBar4;
        seekBar4.setLayoutParams(new LinearLayout.LayoutParams(679, 921));
        this.ubakjbergo.setPadding(149, 43, 186, 115);
        linearLayout.addView(this.ubakjbergo);
        this.ubakjbergo.setBackgroundColor(Color.parseColor("#d39a55"));
        ScrollView scrollView2 = new ScrollView(this);
        this.rxmpyqqoyd = scrollView2;
        scrollView2.setLayoutParams(new LinearLayout.LayoutParams(1692, 131));
        this.rxmpyqqoyd.setPadding(97, 2, 1, 193);
        linearLayout.addView(this.rxmpyqqoyd);
        this.rxmpyqqoyd.setBackgroundColor(Color.parseColor("#791aa8"));
        ViewFlipper viewFlipper3 = new ViewFlipper(this);
        this.yrtjqzihps = viewFlipper3;
        viewFlipper3.setLayoutParams(new LinearLayout.LayoutParams(306, 1789));
        this.yrtjqzihps.setPadding(174, 77, 121, 12);
        linearLayout.addView(this.yrtjqzihps);
        this.yrtjqzihps.setBackgroundColor(Color.parseColor("#f789df"));
        ListView listView2 = new ListView(this);
        this.ydzcgxxhla = listView2;
        listView2.setLayoutParams(new LinearLayout.LayoutParams(1750, 1694));
        this.ydzcgxxhla.setPadding(114, 87, 33, 113);
        linearLayout.addView(this.ydzcgxxhla);
        this.ydzcgxxhla.setBackgroundColor(Color.parseColor("#55a3e8"));
        CheckBox checkBox3 = new CheckBox(this);
        this.isezoqbhdu = checkBox3;
        checkBox3.setLayoutParams(new LinearLayout.LayoutParams(568, 1290));
        this.isezoqbhdu.setPadding(117, 56, 31, 82);
        linearLayout.addView(this.isezoqbhdu);
        this.isezoqbhdu.setBackgroundColor(Color.parseColor("#2402ef"));
        ListView listView3 = new ListView(this);
        this.wgtdofikii = listView3;
        listView3.setLayoutParams(new LinearLayout.LayoutParams(1553, 642));
        this.wgtdofikii.setPadding(8, 168, 41, 59);
        linearLayout.addView(this.wgtdofikii);
        this.wgtdofikii.setBackgroundColor(Color.parseColor("#ab8385"));
        LinearLayout linearLayout4 = new LinearLayout(this);
        this.bwdhsirzgf = linearLayout4;
        linearLayout4.setLayoutParams(new LinearLayout.LayoutParams(1512, 991));
        this.bwdhsirzgf.setPadding(152, 103, 193, 151);
        linearLayout.addView(this.bwdhsirzgf);
        this.bwdhsirzgf.setBackgroundColor(Color.parseColor("#f230c0"));
        RadioButton radioButton3 = new RadioButton(this);
        this.eqzbrpdzmn = radioButton3;
        radioButton3.setLayoutParams(new LinearLayout.LayoutParams(1481, 1767));
        this.eqzbrpdzmn.setPadding(104, 128, 172, 178);
        linearLayout.addView(this.eqzbrpdzmn);
        this.eqzbrpdzmn.setBackgroundColor(Color.parseColor("#d51200"));
        Button button2 = new Button(this);
        this.qcvcdayqsm = button2;
        button2.setLayoutParams(new LinearLayout.LayoutParams(1209, 111));
        this.qcvcdayqsm.setPadding(32, 22, 150, 72);
        linearLayout.addView(this.qcvcdayqsm);
        this.qcvcdayqsm.setBackgroundColor(Color.parseColor("#84dd2d"));
        RelativeLayout relativeLayout2 = new RelativeLayout(this);
        this.krueggaqgy = relativeLayout2;
        relativeLayout2.setLayoutParams(new LinearLayout.LayoutParams(1634, 759));
        this.krueggaqgy.setPadding(BDLocation.TypeNetWorkLocation, 182, 149, 170);
        linearLayout.addView(this.krueggaqgy);
        this.krueggaqgy.setBackgroundColor(Color.parseColor("#5e5674"));
        TimePicker timePicker = new TimePicker(this);
        this.qzsvgbeazw = timePicker;
        timePicker.setLayoutParams(new LinearLayout.LayoutParams(1998, 843));
        this.qzsvgbeazw.setPadding(58, 92, 183, 145);
        linearLayout.addView(this.qzsvgbeazw);
        this.qzsvgbeazw.setBackgroundColor(Color.parseColor("#8fcf62"));
        Spinner spinner3 = new Spinner(this);
        this.qdxzeprkqf = spinner3;
        spinner3.setLayoutParams(new LinearLayout.LayoutParams(1435, 1182));
        this.qdxzeprkqf.setPadding(131, 114, 113, 60);
        linearLayout.addView(this.qdxzeprkqf);
        this.qdxzeprkqf.setBackgroundColor(Color.parseColor("#dba8dd"));
        ProgressBar progressBar3 = new ProgressBar(this);
        this.fmmvmiydmm = progressBar3;
        progressBar3.setLayoutParams(new LinearLayout.LayoutParams(658, 1722));
        this.fmmvmiydmm.setPadding(35, 82, 71, 140);
        linearLayout.addView(this.fmmvmiydmm);
        this.fmmvmiydmm.setBackgroundColor(Color.parseColor("#e404b8"));
        ScrollView scrollView3 = new ScrollView(this);
        this.sgybhcadjs = scrollView3;
        scrollView3.setLayoutParams(new LinearLayout.LayoutParams(733, 1659));
        this.sgybhcadjs.setPadding(16, 28, 26, 104);
        linearLayout.addView(this.sgybhcadjs);
        this.sgybhcadjs.setBackgroundColor(Color.parseColor("#2e657a"));
        ListView listView4 = new ListView(this);
        this.mcctpqsdmy = listView4;
        listView4.setLayoutParams(new LinearLayout.LayoutParams(1004, 738));
        this.mcctpqsdmy.setPadding(50, 139, BDLocation.TypeServerDecryptError, 3);
        linearLayout.addView(this.mcctpqsdmy);
        this.mcctpqsdmy.setBackgroundColor(Color.parseColor("#dc1c01"));
        ListView listView5 = new ListView(this);
        this.ebqhrpcnbx = listView5;
        listView5.setLayoutParams(new LinearLayout.LayoutParams(1339, 1806));
        this.ebqhrpcnbx.setPadding(52, 137, 129, 129);
        linearLayout.addView(this.ebqhrpcnbx);
        this.ebqhrpcnbx.setBackgroundColor(Color.parseColor("#93b080"));
        DatePicker datePicker5 = new DatePicker(this);
        this.bqlocdmavy = datePicker5;
        datePicker5.setLayoutParams(new LinearLayout.LayoutParams(187, 173));
        this.bqlocdmavy.setPadding(56, 170, 80, 146);
        linearLayout.addView(this.bqlocdmavy);
        this.bqlocdmavy.setBackgroundColor(Color.parseColor("#3ed37c"));
        ImageView imageView2 = new ImageView(this);
        this.smdkndtdrn = imageView2;
        imageView2.setLayoutParams(new LinearLayout.LayoutParams(114, TypedValues.Custom.TYPE_BOOLEAN));
        this.smdkndtdrn.setPadding(23, 118, 73, 53);
        linearLayout.addView(this.smdkndtdrn);
        this.smdkndtdrn.setBackgroundColor(Color.parseColor("#abf786"));
        ScrollView scrollView4 = new ScrollView(this);
        this.nvmoxvsuug = scrollView4;
        scrollView4.setLayoutParams(new LinearLayout.LayoutParams(921, 1509));
        this.nvmoxvsuug.setPadding(178, 152, 177, 38);
        linearLayout.addView(this.nvmoxvsuug);
        this.nvmoxvsuug.setBackgroundColor(Color.parseColor("#05c909"));
        Switch r33 = new Switch(this);
        this.bzmnexylco = r33;
        r33.setLayoutParams(new LinearLayout.LayoutParams(1529, 927));
        this.bzmnexylco.setPadding(0, 100, 169, 84);
        linearLayout.addView(this.bzmnexylco);
        this.bzmnexylco.setBackgroundColor(Color.parseColor("#167098"));
        Spinner spinner4 = new Spinner(this);
        this.mdwobvxjck = spinner4;
        spinner4.setLayoutParams(new LinearLayout.LayoutParams(138, 969));
        this.mdwobvxjck.setPadding(116, 172, 65, 97);
        linearLayout.addView(this.mdwobvxjck);
        this.mdwobvxjck.setBackgroundColor(Color.parseColor("#bde1ec"));
        LinearLayout linearLayout5 = new LinearLayout(this);
        this.urawxsntnb = linearLayout5;
        linearLayout5.setLayoutParams(new LinearLayout.LayoutParams(1648, 1240));
        this.urawxsntnb.setPadding(18, 58, 169, 85);
        linearLayout.addView(this.urawxsntnb);
        this.urawxsntnb.setBackgroundColor(Color.parseColor("#c3e2a4"));
        EditText editText2 = new EditText(this);
        this.nkxvisvlfd = editText2;
        editText2.setLayoutParams(new LinearLayout.LayoutParams(1420, 919));
        this.nkxvisvlfd.setPadding(182, 34, 141, 197);
        linearLayout.addView(this.nkxvisvlfd);
        this.nkxvisvlfd.setBackgroundColor(Color.parseColor("#20414d"));
        LinearLayout linearLayout6 = new LinearLayout(this);
        this.uomsrafmjs = linearLayout6;
        linearLayout6.setLayoutParams(new LinearLayout.LayoutParams(1460, 1660));
        this.uomsrafmjs.setPadding(113, 159, 107, 21);
        linearLayout.addView(this.uomsrafmjs);
        this.uomsrafmjs.setBackgroundColor(Color.parseColor("#07b9a1"));
        CheckBox checkBox4 = new CheckBox(this);
        this.mvoszyxnbk = checkBox4;
        checkBox4.setLayoutParams(new LinearLayout.LayoutParams(1815, 1120));
        this.mvoszyxnbk.setPadding(106, 109, 179, 173);
        linearLayout.addView(this.mvoszyxnbk);
        this.mvoszyxnbk.setBackgroundColor(Color.parseColor("#6486fc"));
        RatingBar ratingBar3 = new RatingBar(this);
        this.igouwpcisi = ratingBar3;
        ratingBar3.setLayoutParams(new LinearLayout.LayoutParams(GattClient.STATE_PENDDING_DISCOVERY_SERVICE, 596));
        this.igouwpcisi.setPadding(45, 102, 34, 192);
        linearLayout.addView(this.igouwpcisi);
        this.igouwpcisi.setBackgroundColor(Color.parseColor("#9f79d4"));
        Button button3 = new Button(this);
        this.lltocvsikk = button3;
        button3.setLayoutParams(new LinearLayout.LayoutParams(509, 807));
        this.lltocvsikk.setPadding(90, 45, 60, 176);
        linearLayout.addView(this.lltocvsikk);
        this.lltocvsikk.setBackgroundColor(Color.parseColor("#b11cb9"));
        Spinner spinner5 = new Spinner(this);
        this.ajnuutxmed = spinner5;
        spinner5.setLayoutParams(new LinearLayout.LayoutParams(1372, 1181));
        this.ajnuutxmed.setPadding(148, 24, 141, 165);
        linearLayout.addView(this.ajnuutxmed);
        this.ajnuutxmed.setBackgroundColor(Color.parseColor("#5b9cf1"));
        LinearLayout linearLayout7 = new LinearLayout(this);
        this.zmkdhbqxcx = linearLayout7;
        linearLayout7.setLayoutParams(new LinearLayout.LayoutParams(1002, 1107));
        this.zmkdhbqxcx.setPadding(141, 2, 83, 118);
        linearLayout.addView(this.zmkdhbqxcx);
        this.zmkdhbqxcx.setBackgroundColor(Color.parseColor("#f496f1"));
        Spinner spinner6 = new Spinner(this);
        this.giaeekuefa = spinner6;
        spinner6.setLayoutParams(new LinearLayout.LayoutParams(1801, 453));
        this.giaeekuefa.setPadding(19, 54, 124, 191);
        linearLayout.addView(this.giaeekuefa);
        this.giaeekuefa.setBackgroundColor(Color.parseColor("#a9e420"));
        SeekBar seekBar5 = new SeekBar(this);
        this.ekmmtirfen = seekBar5;
        seekBar5.setLayoutParams(new LinearLayout.LayoutParams(308, 409));
        this.ekmmtirfen.setPadding(137, 16, 118, 73);
        linearLayout.addView(this.ekmmtirfen);
        this.ekmmtirfen.setBackgroundColor(Color.parseColor("#05146d"));
        FrameLayout frameLayout5 = new FrameLayout(this);
        this.imfykqczen = frameLayout5;
        frameLayout5.setLayoutParams(new LinearLayout.LayoutParams(1601, 893));
        this.imfykqczen.setPadding(116, 189, 63, 32);
        linearLayout.addView(this.imfykqczen);
        this.imfykqczen.setBackgroundColor(Color.parseColor("#036c7e"));
        GridView gridView = new GridView(this);
        this.djksfzzcgi = gridView;
        gridView.setLayoutParams(new LinearLayout.LayoutParams(298, 851));
        this.djksfzzcgi.setPadding(112, 98, 131, 93);
        linearLayout.addView(this.djksfzzcgi);
        this.djksfzzcgi.setBackgroundColor(Color.parseColor("#624881"));
        Switch r34 = new Switch(this);
        this.cwxcthlzky = r34;
        r34.setLayoutParams(new LinearLayout.LayoutParams(1537, 310));
        this.cwxcthlzky.setPadding(119, 177, 156, 69);
        linearLayout.addView(this.cwxcthlzky);
        this.cwxcthlzky.setBackgroundColor(Color.parseColor("#249fe4"));
        CheckBox checkBox5 = new CheckBox(this);
        this.pqwofugcdh = checkBox5;
        checkBox5.setLayoutParams(new LinearLayout.LayoutParams(263, 621));
        this.pqwofugcdh.setPadding(22, 47, 131, 41);
        linearLayout.addView(this.pqwofugcdh);
        this.pqwofugcdh.setBackgroundColor(Color.parseColor("#21d627"));
        TimePicker timePicker2 = new TimePicker(this);
        this.cmlprfgnai = timePicker2;
        timePicker2.setLayoutParams(new LinearLayout.LayoutParams(833, 1189));
        this.cmlprfgnai.setPadding(84, 83, 1, 69);
        linearLayout.addView(this.cmlprfgnai);
        this.cmlprfgnai.setBackgroundColor(Color.parseColor("#5ca081"));
        LinearLayout linearLayout8 = new LinearLayout(this);
        this.vpfeykxuop = linearLayout8;
        linearLayout8.setLayoutParams(new LinearLayout.LayoutParams(1919, 1235));
        this.vpfeykxuop.setPadding(24, BDLocation.TypeNetWorkLocation, 89, 5);
        linearLayout.addView(this.vpfeykxuop);
        this.vpfeykxuop.setBackgroundColor(Color.parseColor("#5d0634"));
        FrameLayout frameLayout6 = new FrameLayout(this);
        this.vvxndnroqz = frameLayout6;
        frameLayout6.setLayoutParams(new LinearLayout.LayoutParams(881, 671));
        this.vvxndnroqz.setPadding(38, 59, 165, 194);
        linearLayout.addView(this.vvxndnroqz);
        this.vvxndnroqz.setBackgroundColor(Color.parseColor("#b2b1cb"));
        ListView listView6 = new ListView(this);
        this.bdjttmhdiq = listView6;
        listView6.setLayoutParams(new LinearLayout.LayoutParams(1328, 517));
        this.bdjttmhdiq.setPadding(150, 137, 42, 99);
        linearLayout.addView(this.bdjttmhdiq);
        this.bdjttmhdiq.setBackgroundColor(Color.parseColor("#b7cf4b"));
        TextView textView5 = new TextView(this);
        this.mrnudynshk = textView5;
        textView5.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.TransitionType.TYPE_DURATION, 1310));
        this.mrnudynshk.setPadding(97, 47, 130, 127);
        linearLayout.addView(this.mrnudynshk);
        this.mrnudynshk.setBackgroundColor(Color.parseColor("#96090c"));
        Button button4 = new Button(this);
        this.zfaomllbyr = button4;
        button4.setLayoutParams(new LinearLayout.LayoutParams(576, 964));
        this.zfaomllbyr.setPadding(32, 36, 117, 39);
        linearLayout.addView(this.zfaomllbyr);
        this.zfaomllbyr.setBackgroundColor(Color.parseColor("#29fb29"));
        LinearLayout linearLayout9 = new LinearLayout(this);
        this.ibocommyez = linearLayout9;
        linearLayout9.setLayoutParams(new LinearLayout.LayoutParams(1848, 1994));
        this.ibocommyez.setPadding(2, 3, 36, 8);
        linearLayout.addView(this.ibocommyez);
        this.ibocommyez.setBackgroundColor(Color.parseColor("#884177"));
        RadioButton radioButton4 = new RadioButton(this);
        this.qtqondxrzn = radioButton4;
        radioButton4.setLayoutParams(new LinearLayout.LayoutParams(1492, 19));
        this.qtqondxrzn.setPadding(75, 26, 2, 135);
        linearLayout.addView(this.qtqondxrzn);
        this.qtqondxrzn.setBackgroundColor(Color.parseColor("#777dd9"));
        RelativeLayout relativeLayout3 = new RelativeLayout(this);
        this.fsnldmhzzc = relativeLayout3;
        relativeLayout3.setLayoutParams(new LinearLayout.LayoutParams(291, 1650));
        this.fsnldmhzzc.setPadding(92, 176, 25, 190);
        linearLayout.addView(this.fsnldmhzzc);
        this.fsnldmhzzc.setBackgroundColor(Color.parseColor("#8f5f02"));
        TimePicker timePicker3 = new TimePicker(this);
        this.puntymwzhl = timePicker3;
        timePicker3.setLayoutParams(new LinearLayout.LayoutParams(1077, 23));
        this.puntymwzhl.setPadding(51, 35, 46, 44);
        linearLayout.addView(this.puntymwzhl);
        this.puntymwzhl.setBackgroundColor(Color.parseColor("#408f47"));
        GridView gridView2 = new GridView(this);
        this.fewdmcmtvq = gridView2;
        gridView2.setLayoutParams(new LinearLayout.LayoutParams(262, 1473));
        this.fewdmcmtvq.setPadding(96, 166, 41, 17);
        linearLayout.addView(this.fewdmcmtvq);
        this.fewdmcmtvq.setBackgroundColor(Color.parseColor("#267d95"));
        ToggleButton toggleButton2 = new ToggleButton(this);
        this.iwmwmzrrjj = toggleButton2;
        toggleButton2.setLayoutParams(new LinearLayout.LayoutParams(1451, 983));
        this.iwmwmzrrjj.setPadding(89, 97, 172, 64);
        linearLayout.addView(this.iwmwmzrrjj);
        this.iwmwmzrrjj.setBackgroundColor(Color.parseColor("#965317"));
        ListView listView7 = new ListView(this);
        this.dihdjvusad = listView7;
        listView7.setLayoutParams(new LinearLayout.LayoutParams(1668, 1482));
        this.dihdjvusad.setPadding(163, 138, 134, 197);
        linearLayout.addView(this.dihdjvusad);
        this.dihdjvusad.setBackgroundColor(Color.parseColor("#bff2fc"));
        ListView listView8 = new ListView(this);
        this.cvyakebxya = listView8;
        listView8.setLayoutParams(new LinearLayout.LayoutParams(1013, 45));
        this.cvyakebxya.setPadding(157, 153, 148, 86);
        linearLayout.addView(this.cvyakebxya);
        this.cvyakebxya.setBackgroundColor(Color.parseColor("#144c51"));
        ListView listView9 = new ListView(this);
        this.nwmqcatgti = listView9;
        listView9.setLayoutParams(new LinearLayout.LayoutParams(1082, 461));
        this.nwmqcatgti.setPadding(194, 9, 92, BDLocation.TypeServerError);
        linearLayout.addView(this.nwmqcatgti);
        this.nwmqcatgti.setBackgroundColor(Color.parseColor("#6e294f"));
        SeekBar seekBar6 = new SeekBar(this);
        this.znwrkmgayk = seekBar6;
        seekBar6.setLayoutParams(new LinearLayout.LayoutParams(862, 1892));
        this.znwrkmgayk.setPadding(107, 114, 6, 125);
        linearLayout.addView(this.znwrkmgayk);
        this.znwrkmgayk.setBackgroundColor(Color.parseColor("#200f77"));
        ProgressBar progressBar4 = new ProgressBar(this);
        this.fmlazkgwnm = progressBar4;
        progressBar4.setLayoutParams(new LinearLayout.LayoutParams(1471, 32));
        this.fmlazkgwnm.setPadding(0, 156, 8, 21);
        linearLayout.addView(this.fmlazkgwnm);
        this.fmlazkgwnm.setBackgroundColor(Color.parseColor("#d6fe20"));
        CheckBox checkBox6 = new CheckBox(this);
        this.vajlcolcom = checkBox6;
        checkBox6.setLayoutParams(new LinearLayout.LayoutParams(1496, 1513));
        this.vajlcolcom.setPadding(81, 197, 94, 94);
        linearLayout.addView(this.vajlcolcom);
        this.vajlcolcom.setBackgroundColor(Color.parseColor("#50c05b"));
        RelativeLayout relativeLayout4 = new RelativeLayout(this);
        this.vjeetlkloi = relativeLayout4;
        relativeLayout4.setLayoutParams(new LinearLayout.LayoutParams(1171, 1176));
        this.vjeetlkloi.setPadding(13, 147, 164, BDLocation.TypeServerDecryptError);
        linearLayout.addView(this.vjeetlkloi);
        this.vjeetlkloi.setBackgroundColor(Color.parseColor("#745f56"));
        GridView gridView3 = new GridView(this);
        this.thhqhtnbvr = gridView3;
        gridView3.setLayoutParams(new LinearLayout.LayoutParams(819, CropImage.CROP_IMAGE_ACTIVITY_REQUEST_CODE));
        this.thhqhtnbvr.setPadding(46, 100, 1, 50);
        linearLayout.addView(this.thhqhtnbvr);
        this.thhqhtnbvr.setBackgroundColor(Color.parseColor("#e968dc"));
        CheckBox checkBox7 = new CheckBox(this);
        this.lkdbqusuew = checkBox7;
        checkBox7.setLayoutParams(new LinearLayout.LayoutParams(1379, 973));
        this.lkdbqusuew.setPadding(23, 114, 96, 48);
        linearLayout.addView(this.lkdbqusuew);
        this.lkdbqusuew.setBackgroundColor(Color.parseColor("#657227"));
        ToggleButton toggleButton3 = new ToggleButton(this);
        this.gvzhszomsv = toggleButton3;
        toggleButton3.setLayoutParams(new LinearLayout.LayoutParams(1285, 955));
        this.gvzhszomsv.setPadding(179, 76, 140, 110);
        linearLayout.addView(this.gvzhszomsv);
        this.gvzhszomsv.setBackgroundColor(Color.parseColor("#a3bb86"));
        DatePicker datePicker6 = new DatePicker(this);
        this.cwepfcbxqk = datePicker6;
        datePicker6.setLayoutParams(new LinearLayout.LayoutParams(1122, 10));
        this.cwepfcbxqk.setPadding(43, 111, 33, 140);
        linearLayout.addView(this.cwepfcbxqk);
        this.cwepfcbxqk.setBackgroundColor(Color.parseColor("#eec1f4"));
        ViewFlipper viewFlipper4 = new ViewFlipper(this);
        this.lbtntoielq = viewFlipper4;
        viewFlipper4.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.CycleType.TYPE_VISIBILITY, 77));
        this.lbtntoielq.setPadding(164, 163, 131, 80);
        linearLayout.addView(this.lbtntoielq);
        this.lbtntoielq.setBackgroundColor(Color.parseColor("#b33aa6"));
        CheckBox checkBox8 = new CheckBox(this);
        this.afxfeccaer = checkBox8;
        checkBox8.setLayoutParams(new LinearLayout.LayoutParams(688, 1259));
        this.afxfeccaer.setPadding(107, 82, 84, 174);
        linearLayout.addView(this.afxfeccaer);
        this.afxfeccaer.setBackgroundColor(Color.parseColor("#8cd84d"));
        DatePicker datePicker7 = new DatePicker(this);
        this.jzqtcaqlan = datePicker7;
        datePicker7.setLayoutParams(new LinearLayout.LayoutParams(276, 854));
        this.jzqtcaqlan.setPadding(182, 139, 150, 24);
        linearLayout.addView(this.jzqtcaqlan);
        this.jzqtcaqlan.setBackgroundColor(Color.parseColor("#108713"));
        Button button5 = new Button(this);
        this.ibgdgbvfcc = button5;
        button5.setLayoutParams(new LinearLayout.LayoutParams(1237, 1694));
        this.ibgdgbvfcc.setPadding(0, 92, 138, 55);
        linearLayout.addView(this.ibgdgbvfcc);
        this.ibgdgbvfcc.setBackgroundColor(Color.parseColor("#9e4966"));
        EditText editText3 = new EditText(this);
        this.gimzgxlsri = editText3;
        editText3.setLayoutParams(new LinearLayout.LayoutParams(130, 204));
        this.gimzgxlsri.setPadding(73, 110, 164, 135);
        linearLayout.addView(this.gimzgxlsri);
        this.gimzgxlsri.setBackgroundColor(Color.parseColor("#1c3c3e"));
        LinearLayout linearLayout10 = new LinearLayout(this);
        this.iffbsecflo = linearLayout10;
        linearLayout10.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.Custom.TYPE_FLOAT, 211));
        this.iffbsecflo.setPadding(88, 74, 172, 146);
        linearLayout.addView(this.iffbsecflo);
        this.iffbsecflo.setBackgroundColor(Color.parseColor("#b29d38"));
        ViewFlipper viewFlipper5 = new ViewFlipper(this);
        this.zalnnnbouo = viewFlipper5;
        viewFlipper5.setLayoutParams(new LinearLayout.LayoutParams(1644, 1946));
        this.zalnnnbouo.setPadding(30, 25, 122, 76);
        linearLayout.addView(this.zalnnnbouo);
        this.zalnnnbouo.setBackgroundColor(Color.parseColor("#6c507c"));
        ImageView imageView3 = new ImageView(this);
        this.cniflvruwz = imageView3;
        imageView3.setLayoutParams(new LinearLayout.LayoutParams(972, 253));
        this.cniflvruwz.setPadding(72, 104, 158, 140);
        linearLayout.addView(this.cniflvruwz);
        this.cniflvruwz.setBackgroundColor(Color.parseColor("#ebfc15"));
        ViewFlipper viewFlipper6 = new ViewFlipper(this);
        this.hmtccnjrsh = viewFlipper6;
        viewFlipper6.setLayoutParams(new LinearLayout.LayoutParams(476, PointerIconCompat.TYPE_ZOOM_IN));
        this.hmtccnjrsh.setPadding(137, 170, 11, 27);
        linearLayout.addView(this.hmtccnjrsh);
        this.hmtccnjrsh.setBackgroundColor(Color.parseColor("#7b58d9"));
        RatingBar ratingBar4 = new RatingBar(this);
        this.xdhvaixjzm = ratingBar4;
        ratingBar4.setLayoutParams(new LinearLayout.LayoutParams(1058, 416));
        this.xdhvaixjzm.setPadding(18, 79, 135, 29);
        linearLayout.addView(this.xdhvaixjzm);
        this.xdhvaixjzm.setBackgroundColor(Color.parseColor("#f945e8"));
        SeekBar seekBar7 = new SeekBar(this);
        this.kmaueakxjf = seekBar7;
        seekBar7.setLayoutParams(new LinearLayout.LayoutParams(1477, 457));
        this.kmaueakxjf.setPadding(54, 186, 169, 12);
        linearLayout.addView(this.kmaueakxjf);
        this.kmaueakxjf.setBackgroundColor(Color.parseColor("#6dfc20"));
        ListView listView10 = new ListView(this);
        this.uoqizrvjgr = listView10;
        listView10.setLayoutParams(new LinearLayout.LayoutParams(311, 273));
        this.uoqizrvjgr.setPadding(6, 8, 198, 93);
        linearLayout.addView(this.uoqizrvjgr);
        this.uoqizrvjgr.setBackgroundColor(Color.parseColor("#8a7fea"));
        LinearLayout linearLayout11 = new LinearLayout(this);
        this.rjdctcfqzb = linearLayout11;
        linearLayout11.setLayoutParams(new LinearLayout.LayoutParams(102, TypedValues.Custom.TYPE_STRING));
        this.rjdctcfqzb.setPadding(30, 179, 97, 3);
        linearLayout.addView(this.rjdctcfqzb);
        this.rjdctcfqzb.setBackgroundColor(Color.parseColor("#926fd0"));
        Switch r35 = new Switch(this);
        this.kprcaheyrp = r35;
        r35.setLayoutParams(new LinearLayout.LayoutParams(230, 873));
        this.kprcaheyrp.setPadding(139, 127, 14, 168);
        linearLayout.addView(this.kprcaheyrp);
        this.kprcaheyrp.setBackgroundColor(Color.parseColor("#1a0656"));
        Switch r36 = new Switch(this);
        this.cmigyzyxxx = r36;
        r36.setLayoutParams(new LinearLayout.LayoutParams(438, 597));
        this.cmigyzyxxx.setPadding(90, 131, 66, 163);
        linearLayout.addView(this.cmigyzyxxx);
        this.cmigyzyxxx.setBackgroundColor(Color.parseColor("#ebc222"));
        EditText editText4 = new EditText(this);
        this.hybxagonhr = editText4;
        editText4.setLayoutParams(new LinearLayout.LayoutParams(197, 227));
        this.hybxagonhr.setPadding(46, 121, 41, 51);
        linearLayout.addView(this.hybxagonhr);
        this.hybxagonhr.setBackgroundColor(Color.parseColor("#4cf24f"));
        TextView textView6 = new TextView(this);
        this.thhnmzyfbp = textView6;
        textView6.setLayoutParams(new LinearLayout.LayoutParams(1560, 1926));
        this.thhnmzyfbp.setPadding(150, 17, 76, 50);
        linearLayout.addView(this.thhnmzyfbp);
        this.thhnmzyfbp.setBackgroundColor(Color.parseColor("#26caa1"));
        RatingBar ratingBar5 = new RatingBar(this);
        this.zbdplhoqbd = ratingBar5;
        ratingBar5.setLayoutParams(new LinearLayout.LayoutParams(898, 1546));
        this.zbdplhoqbd.setPadding(128, 110, 55, 189);
        linearLayout.addView(this.zbdplhoqbd);
        this.zbdplhoqbd.setBackgroundColor(Color.parseColor("#1973ae"));
        TextView textView7 = new TextView(this);
        this.nxmexfwnca = textView7;
        textView7.setLayoutParams(new LinearLayout.LayoutParams(1879, 1968));
        this.nxmexfwnca.setPadding(182, 108, 44, 80);
        linearLayout.addView(this.nxmexfwnca);
        this.nxmexfwnca.setBackgroundColor(Color.parseColor("#0e701e"));
        Button button6 = new Button(this);
        this.hopvvvmuzp = button6;
        button6.setLayoutParams(new LinearLayout.LayoutParams(1014, 364));
        this.hopvvvmuzp.setPadding(171, 9, 158, 8);
        linearLayout.addView(this.hopvvvmuzp);
        this.hopvvvmuzp.setBackgroundColor(Color.parseColor("#eb0592"));
        Spinner spinner7 = new Spinner(this);
        this.jctgnwgryt = spinner7;
        spinner7.setLayoutParams(new LinearLayout.LayoutParams(1993, 1464));
        this.jctgnwgryt.setPadding(154, BDLocation.TypeServerError, 181, 73);
        linearLayout.addView(this.jctgnwgryt);
        this.jctgnwgryt.setBackgroundColor(Color.parseColor("#f38d38"));
        TextView textView8 = new TextView(this);
        this.hahojciakt = textView8;
        textView8.setLayoutParams(new LinearLayout.LayoutParams(1012, 394));
        this.hahojciakt.setPadding(180, 20, 137, 102);
        linearLayout.addView(this.hahojciakt);
        this.hahojciakt.setBackgroundColor(Color.parseColor("#8cea91"));
        Button button7 = new Button(this);
        this.ntkhwcvtqh = button7;
        button7.setLayoutParams(new LinearLayout.LayoutParams(415, 522));
        this.ntkhwcvtqh.setPadding(4, 104, 110, 127);
        linearLayout.addView(this.ntkhwcvtqh);
        this.ntkhwcvtqh.setBackgroundColor(Color.parseColor("#c10b1f"));
        Spinner spinner8 = new Spinner(this);
        this.oypgxvofwk = spinner8;
        spinner8.setLayoutParams(new LinearLayout.LayoutParams(1128, 55));
        this.oypgxvofwk.setPadding(89, 181, 133, 101);
        linearLayout.addView(this.oypgxvofwk);
        this.oypgxvofwk.setBackgroundColor(Color.parseColor("#5848be"));
        RadioButton radioButton5 = new RadioButton(this);
        this.sgmtmmwudl = radioButton5;
        radioButton5.setLayoutParams(new LinearLayout.LayoutParams(881, 1007));
        this.sgmtmmwudl.setPadding(111, 5, 98, 169);
        linearLayout.addView(this.sgmtmmwudl);
        this.sgmtmmwudl.setBackgroundColor(Color.parseColor("#af03f1"));
        ScrollView scrollView5 = new ScrollView(this);
        this.vlfknnfpzv = scrollView5;
        scrollView5.setLayoutParams(new LinearLayout.LayoutParams(251, 581));
        this.vlfknnfpzv.setPadding(186, 4, 158, 67);
        linearLayout.addView(this.vlfknnfpzv);
        this.vlfknnfpzv.setBackgroundColor(Color.parseColor("#c9fbe0"));
        ImageView imageView4 = new ImageView(this);
        this.lltsnfebgy = imageView4;
        imageView4.setLayoutParams(new LinearLayout.LayoutParams(1557, 421));
        this.lltsnfebgy.setPadding(56, 30, 50, 0);
        linearLayout.addView(this.lltsnfebgy);
        this.lltsnfebgy.setBackgroundColor(Color.parseColor("#e6ae84"));
        Spinner spinner9 = new Spinner(this);
        this.zczwqpcgdn = spinner9;
        spinner9.setLayoutParams(new LinearLayout.LayoutParams(669, 780));
        this.zczwqpcgdn.setPadding(171, 51, 133, 83);
        linearLayout.addView(this.zczwqpcgdn);
        this.zczwqpcgdn.setBackgroundColor(Color.parseColor("#0fe10a"));
        ListView listView11 = new ListView(this);
        this.fzfbmjqjlo = listView11;
        listView11.setLayoutParams(new LinearLayout.LayoutParams(1368, 1883));
        this.fzfbmjqjlo.setPadding(120, 47, 11, 101);
        linearLayout.addView(this.fzfbmjqjlo);
        this.fzfbmjqjlo.setBackgroundColor(Color.parseColor("#0ba500"));
        Spinner spinner10 = new Spinner(this);
        this.mvkskjszvy = spinner10;
        spinner10.setLayoutParams(new LinearLayout.LayoutParams(1304, 1811));
        this.mvkskjszvy.setPadding(190, 149, 59, 7);
        linearLayout.addView(this.mvkskjszvy);
        this.mvkskjszvy.setBackgroundColor(Color.parseColor("#34ee4d"));
        DatePicker datePicker8 = new DatePicker(this);
        this.erugtnjolf = datePicker8;
        datePicker8.setLayoutParams(new LinearLayout.LayoutParams(1410, 1011));
        this.erugtnjolf.setPadding(134, 59, 165, 156);
        linearLayout.addView(this.erugtnjolf);
        this.erugtnjolf.setBackgroundColor(Color.parseColor("#623710"));
        RelativeLayout relativeLayout5 = new RelativeLayout(this);
        this.bkglsnaokp = relativeLayout5;
        relativeLayout5.setLayoutParams(new LinearLayout.LayoutParams(1186, 1493));
        this.bkglsnaokp.setPadding(76, 41, 53, 157);
        linearLayout.addView(this.bkglsnaokp);
        this.bkglsnaokp.setBackgroundColor(Color.parseColor("#229874"));
        ListView listView12 = new ListView(this);
        this.kynvurekyi = listView12;
        listView12.setLayoutParams(new LinearLayout.LayoutParams(325, 879));
        this.kynvurekyi.setPadding(168, 186, 80, 189);
        linearLayout.addView(this.kynvurekyi);
        this.kynvurekyi.setBackgroundColor(Color.parseColor("#316831"));
        FrameLayout frameLayout7 = new FrameLayout(this);
        this.znahihnsnc = frameLayout7;
        frameLayout7.setLayoutParams(new LinearLayout.LayoutParams(1258, 1773));
        this.znahihnsnc.setPadding(92, 197, 137, 115);
        linearLayout.addView(this.znahihnsnc);
        this.znahihnsnc.setBackgroundColor(Color.parseColor("#560b52"));
        LinearLayout linearLayout12 = new LinearLayout(this);
        this.wijfrcvlgf = linearLayout12;
        linearLayout12.setLayoutParams(new LinearLayout.LayoutParams(157, 805));
        this.wijfrcvlgf.setPadding(90, 77, 127, 62);
        linearLayout.addView(this.wijfrcvlgf);
        this.wijfrcvlgf.setBackgroundColor(Color.parseColor("#fa921e"));
        RelativeLayout relativeLayout6 = new RelativeLayout(this);
        this.juzpymepln = relativeLayout6;
        relativeLayout6.setLayoutParams(new LinearLayout.LayoutParams(1736, 123));
        this.juzpymepln.setPadding(137, 99, 30, 84);
        linearLayout.addView(this.juzpymepln);
        this.juzpymepln.setBackgroundColor(Color.parseColor("#2ae7bd"));
        RatingBar ratingBar6 = new RatingBar(this);
        this.jyedzmdhit = ratingBar6;
        ratingBar6.setLayoutParams(new LinearLayout.LayoutParams(1871, 732));
        this.jyedzmdhit.setPadding(147, 93, 128, 155);
        linearLayout.addView(this.jyedzmdhit);
        this.jyedzmdhit.setBackgroundColor(Color.parseColor("#e5b2ee"));
        Switch r37 = new Switch(this);
        this.etvsgtdgmr = r37;
        r37.setLayoutParams(new LinearLayout.LayoutParams(1744, 1022));
        this.etvsgtdgmr.setPadding(22, 32, 127, 17);
        linearLayout.addView(this.etvsgtdgmr);
        this.etvsgtdgmr.setBackgroundColor(Color.parseColor("#29cd73"));
        Switch r38 = new Switch(this);
        this.fibrtamdpn = r38;
        r38.setLayoutParams(new LinearLayout.LayoutParams(749, 157));
        this.fibrtamdpn.setPadding(14, 88, 88, 7);
        linearLayout.addView(this.fibrtamdpn);
        this.fibrtamdpn.setBackgroundColor(Color.parseColor("#baf91c"));
        RelativeLayout relativeLayout7 = new RelativeLayout(this);
        this.cpoxqfeevx = relativeLayout7;
        relativeLayout7.setLayoutParams(new LinearLayout.LayoutParams(670, 489));
        this.cpoxqfeevx.setPadding(PictureConfig.CHOOSE_REQUEST, 120, 7, 48);
        linearLayout.addView(this.cpoxqfeevx);
        this.cpoxqfeevx.setBackgroundColor(Color.parseColor("#0c7b0a"));
        LinearLayout linearLayout13 = new LinearLayout(this);
        this.fxqphmiero = linearLayout13;
        linearLayout13.setLayoutParams(new LinearLayout.LayoutParams(383, 307));
        this.fxqphmiero.setPadding(85, 92, 10, 97);
        linearLayout.addView(this.fxqphmiero);
        this.fxqphmiero.setBackgroundColor(Color.parseColor("#2397a5"));
        ToggleButton toggleButton4 = new ToggleButton(this);
        this.yccqsmjiyi = toggleButton4;
        toggleButton4.setLayoutParams(new LinearLayout.LayoutParams(1242, 1551));
        this.yccqsmjiyi.setPadding(129, 164, 12, 33);
        linearLayout.addView(this.yccqsmjiyi);
        this.yccqsmjiyi.setBackgroundColor(Color.parseColor("#ae8701"));
        ToggleButton toggleButton5 = new ToggleButton(this);
        this.zbotrjgyux = toggleButton5;
        toggleButton5.setLayoutParams(new LinearLayout.LayoutParams(1625, 1756));
        this.zbotrjgyux.setPadding(63, 11, 184, 96);
        linearLayout.addView(this.zbotrjgyux);
        this.zbotrjgyux.setBackgroundColor(Color.parseColor("#fdce8a"));
        ToggleButton toggleButton6 = new ToggleButton(this);
        this.wfjeetqrid = toggleButton6;
        toggleButton6.setLayoutParams(new LinearLayout.LayoutParams(916, 1607));
        this.wfjeetqrid.setPadding(97, 157, 95, 45);
        linearLayout.addView(this.wfjeetqrid);
        this.wfjeetqrid.setBackgroundColor(Color.parseColor("#df844c"));
        ImageView imageView5 = new ImageView(this);
        this.oxfsxpqipu = imageView5;
        imageView5.setLayoutParams(new LinearLayout.LayoutParams(1770, 774));
        this.oxfsxpqipu.setPadding(25, 14, 118, 151);
        linearLayout.addView(this.oxfsxpqipu);
        this.oxfsxpqipu.setBackgroundColor(Color.parseColor("#ecccd8"));
        GridView gridView4 = new GridView(this);
        this.slcefwrssd = gridView4;
        gridView4.setLayoutParams(new LinearLayout.LayoutParams(807, 329));
        this.slcefwrssd.setPadding(8, 46, 32, 102);
        linearLayout.addView(this.slcefwrssd);
        this.slcefwrssd.setBackgroundColor(Color.parseColor("#a65437"));
        ImageView imageView6 = new ImageView(this);
        this.xafrkiahel = imageView6;
        imageView6.setLayoutParams(new LinearLayout.LayoutParams(1322, 323));
        this.xafrkiahel.setPadding(79, 195, 53, 187);
        linearLayout.addView(this.xafrkiahel);
        this.xafrkiahel.setBackgroundColor(Color.parseColor("#b56897"));
        CheckBox checkBox9 = new CheckBox(this);
        this.zwxvslfasz = checkBox9;
        checkBox9.setLayoutParams(new LinearLayout.LayoutParams(552, 512));
        this.zwxvslfasz.setPadding(76, 79, 133, 50);
        linearLayout.addView(this.zwxvslfasz);
        this.zwxvslfasz.setBackgroundColor(Color.parseColor("#abc769"));
        RatingBar ratingBar7 = new RatingBar(this);
        this.slyrxspoef = ratingBar7;
        ratingBar7.setLayoutParams(new LinearLayout.LayoutParams(186, 71));
        this.slyrxspoef.setPadding(163, 72, 101, 177);
        linearLayout.addView(this.slyrxspoef);
        this.slyrxspoef.setBackgroundColor(Color.parseColor("#2c41e6"));
        RelativeLayout relativeLayout8 = new RelativeLayout(this);
        this.owjsirkzxi = relativeLayout8;
        relativeLayout8.setLayoutParams(new LinearLayout.LayoutParams(1639, 1766));
        this.owjsirkzxi.setPadding(WebSocketProtocol.PAYLOAD_SHORT, 189, 99, 1);
        linearLayout.addView(this.owjsirkzxi);
        this.owjsirkzxi.setBackgroundColor(Color.parseColor("#e9d1fe"));
        TimePicker timePicker4 = new TimePicker(this);
        this.xgrznkmokl = timePicker4;
        timePicker4.setLayoutParams(new LinearLayout.LayoutParams(RoomDatabase.MAX_BIND_PARAMETER_CNT, 821));
        this.xgrznkmokl.setPadding(187, 117, 144, 193);
        linearLayout.addView(this.xgrznkmokl);
        this.xgrznkmokl.setBackgroundColor(Color.parseColor("#6de856"));
        FrameLayout frameLayout8 = new FrameLayout(this);
        this.yoteosbkjc = frameLayout8;
        frameLayout8.setLayoutParams(new LinearLayout.LayoutParams(1468, 556));
        this.yoteosbkjc.setPadding(153, 28, 138, 171);
        linearLayout.addView(this.yoteosbkjc);
        this.yoteosbkjc.setBackgroundColor(Color.parseColor("#8b56c6"));
        Button button8 = new Button(this);
        this.xmligarggd = button8;
        button8.setLayoutParams(new LinearLayout.LayoutParams(389, 1094));
        this.xmligarggd.setPadding(158, BDLocation.TypeServerError, 12, 54);
        linearLayout.addView(this.xmligarggd);
        this.xmligarggd.setBackgroundColor(Color.parseColor("#1639f8"));
        RatingBar ratingBar8 = new RatingBar(this);
        this.nrtfldotlo = ratingBar8;
        ratingBar8.setLayoutParams(new LinearLayout.LayoutParams(1706, 1152));
        this.nrtfldotlo.setPadding(128, 158, 60, 43);
        linearLayout.addView(this.nrtfldotlo);
        this.nrtfldotlo.setBackgroundColor(Color.parseColor("#4142c0"));
        TextView textView9 = new TextView(this);
        this.kcstcxnjih = textView9;
        textView9.setLayoutParams(new LinearLayout.LayoutParams(1046, 387));
        this.kcstcxnjih.setPadding(61, 32, 104, 60);
        linearLayout.addView(this.kcstcxnjih);
        this.kcstcxnjih.setBackgroundColor(Color.parseColor("#f83da2"));
        ImageView imageView7 = new ImageView(this);
        this.secgrinzgb = imageView7;
        imageView7.setLayoutParams(new LinearLayout.LayoutParams(797, 596));
        this.secgrinzgb.setPadding(146, 73, 124, 55);
        linearLayout.addView(this.secgrinzgb);
        this.secgrinzgb.setBackgroundColor(Color.parseColor("#9f3ba4"));
        FrameLayout frameLayout9 = new FrameLayout(this);
        this.jttqpokxwx = frameLayout9;
        frameLayout9.setLayoutParams(new LinearLayout.LayoutParams(531, 310));
        this.jttqpokxwx.setPadding(93, 64, 108, 65);
        linearLayout.addView(this.jttqpokxwx);
        this.jttqpokxwx.setBackgroundColor(Color.parseColor("#9a246b"));
        TextView textView10 = new TextView(this);
        this.ibkffsmati = textView10;
        textView10.setLayoutParams(new LinearLayout.LayoutParams(1406, 127));
        this.ibkffsmati.setPadding(63, 5, 186, 110);
        linearLayout.addView(this.ibkffsmati);
        this.ibkffsmati.setBackgroundColor(Color.parseColor("#153227"));
        FrameLayout frameLayout10 = new FrameLayout(this);
        this.wicfmxlwoy = frameLayout10;
        frameLayout10.setLayoutParams(new LinearLayout.LayoutParams(LocalPlaybackConstants.BUFFER_A_CAN_USE_FLAG, 398));
        this.wicfmxlwoy.setPadding(114, 176, 59, 157);
        linearLayout.addView(this.wicfmxlwoy);
        this.wicfmxlwoy.setBackgroundColor(Color.parseColor("#ca7e2e"));
        RadioButton radioButton6 = new RadioButton(this);
        this.kbkomnjxhc = radioButton6;
        radioButton6.setLayoutParams(new LinearLayout.LayoutParams(668, 1124));
        this.kbkomnjxhc.setPadding(75, 116, 172, 41);
        linearLayout.addView(this.kbkomnjxhc);
        this.kbkomnjxhc.setBackgroundColor(Color.parseColor("#f92208"));
        TableLayout tableLayout6 = new TableLayout(this);
        this.pxrraeeqln = tableLayout6;
        tableLayout6.setLayoutParams(new LinearLayout.LayoutParams(1900, 1688));
        this.pxrraeeqln.setPadding(28, 50, 12, 67);
        linearLayout.addView(this.pxrraeeqln);
        this.pxrraeeqln.setBackgroundColor(Color.parseColor("#000410"));
        TimePicker timePicker5 = new TimePicker(this);
        this.tfzksqvzit = timePicker5;
        timePicker5.setLayoutParams(new LinearLayout.LayoutParams(388, PictureConfig.REQUEST_CAMERA));
        this.tfzksqvzit.setPadding(121, 50, 13, PictureConfig.CHOOSE_REQUEST);
        linearLayout.addView(this.tfzksqvzit);
        this.tfzksqvzit.setBackgroundColor(Color.parseColor("#13d9d1"));
        RadioButton radioButton7 = new RadioButton(this);
        this.pgxdvocrvw = radioButton7;
        radioButton7.setLayoutParams(new LinearLayout.LayoutParams(93, 1975));
        this.pgxdvocrvw.setPadding(12, 3, 123, 159);
        linearLayout.addView(this.pgxdvocrvw);
        this.pgxdvocrvw.setBackgroundColor(Color.parseColor("#1980e2"));
        ProgressBar progressBar5 = new ProgressBar(this);
        this.xtamqgrmnv = progressBar5;
        progressBar5.setLayoutParams(new LinearLayout.LayoutParams(1977, 1460));
        this.xtamqgrmnv.setPadding(BDLocation.TypeCoarseLocation, 3, 137, 195);
        linearLayout.addView(this.xtamqgrmnv);
        this.xtamqgrmnv.setBackgroundColor(Color.parseColor("#cdc35e"));
        Spinner spinner11 = new Spinner(this);
        this.phwqrzjwtl = spinner11;
        spinner11.setLayoutParams(new LinearLayout.LayoutParams(1815, 254));
        this.phwqrzjwtl.setPadding(15, 74, 51, 78);
        linearLayout.addView(this.phwqrzjwtl);
        this.phwqrzjwtl.setBackgroundColor(Color.parseColor("#c1f312"));
        EditText editText5 = new EditText(this);
        this.icrgfkehsp = editText5;
        editText5.setLayoutParams(new LinearLayout.LayoutParams(266, 1780));
        this.icrgfkehsp.setPadding(192, 32, 109, 69);
        linearLayout.addView(this.icrgfkehsp);
        this.icrgfkehsp.setBackgroundColor(Color.parseColor("#5a2700"));
        ScrollView scrollView6 = new ScrollView(this);
        this.nfvyicnbkh = scrollView6;
        scrollView6.setLayoutParams(new LinearLayout.LayoutParams(836, 289));
        this.nfvyicnbkh.setPadding(168, WebSocketProtocol.PAYLOAD_SHORT, 86, 97);
        linearLayout.addView(this.nfvyicnbkh);
        this.nfvyicnbkh.setBackgroundColor(Color.parseColor("#c66e22"));
        TextView textView11 = new TextView(this);
        this.asmanbxvdo = textView11;
        textView11.setLayoutParams(new LinearLayout.LayoutParams(1649, 1117));
        this.asmanbxvdo.setPadding(83, 178, 105, 29);
        linearLayout.addView(this.asmanbxvdo);
        this.asmanbxvdo.setBackgroundColor(Color.parseColor("#10a727"));
        RelativeLayout relativeLayout9 = new RelativeLayout(this);
        this.dtlxpelhfy = relativeLayout9;
        relativeLayout9.setLayoutParams(new LinearLayout.LayoutParams(1835, 1272));
        this.dtlxpelhfy.setPadding(16, 196, 74, 115);
        linearLayout.addView(this.dtlxpelhfy);
        this.dtlxpelhfy.setBackgroundColor(Color.parseColor("#480cf6"));
        TextView textView12 = new TextView(this);
        this.srfffnlqks = textView12;
        textView12.setLayoutParams(new LinearLayout.LayoutParams(225, 142));
        this.srfffnlqks.setPadding(55, 22, 152, 84);
        linearLayout.addView(this.srfffnlqks);
        this.srfffnlqks.setBackgroundColor(Color.parseColor("#55dcaa"));
        EditText editText6 = new EditText(this);
        this.qylbjmlsob = editText6;
        editText6.setLayoutParams(new LinearLayout.LayoutParams(1388, 124));
        this.qylbjmlsob.setPadding(129, 88, 156, 118);
        linearLayout.addView(this.qylbjmlsob);
        this.qylbjmlsob.setBackgroundColor(Color.parseColor("#d1c5b4"));
        ViewFlipper viewFlipper7 = new ViewFlipper(this);
        this.gnyffsdrrx = viewFlipper7;
        viewFlipper7.setLayoutParams(new LinearLayout.LayoutParams(822, 793));
        this.gnyffsdrrx.setPadding(194, 64, 174, 57);
        linearLayout.addView(this.gnyffsdrrx);
        this.gnyffsdrrx.setBackgroundColor(Color.parseColor("#8d8247"));
        Switch r39 = new Switch(this);
        this.nxnuoddesa = r39;
        r39.setLayoutParams(new LinearLayout.LayoutParams(352, 9));
        this.nxnuoddesa.setPadding(77, 152, 191, 83);
        linearLayout.addView(this.nxnuoddesa);
        this.nxnuoddesa.setBackgroundColor(Color.parseColor("#437c04"));
        Switch r310 = new Switch(this);
        this.kzuqnyhxgo = r310;
        r310.setLayoutParams(new LinearLayout.LayoutParams(1976, 1267));
        this.kzuqnyhxgo.setPadding(116, 89, 23, 178);
        linearLayout.addView(this.kzuqnyhxgo);
        this.kzuqnyhxgo.setBackgroundColor(Color.parseColor("#bf2ab6"));
        CheckBox checkBox10 = new CheckBox(this);
        this.keymvfzbqy = checkBox10;
        checkBox10.setLayoutParams(new LinearLayout.LayoutParams(732, 235));
        this.keymvfzbqy.setPadding(114, 189, 141, 72);
        linearLayout.addView(this.keymvfzbqy);
        this.keymvfzbqy.setBackgroundColor(Color.parseColor("#aa2049"));
        ImageView imageView8 = new ImageView(this);
        this.vezowcmqoc = imageView8;
        imageView8.setLayoutParams(new LinearLayout.LayoutParams(1687, 722));
        this.vezowcmqoc.setPadding(7, 178, 125, 177);
        linearLayout.addView(this.vezowcmqoc);
        this.vezowcmqoc.setBackgroundColor(Color.parseColor("#4f7191"));
        SeekBar seekBar8 = new SeekBar(this);
        this.ecfemfdnag = seekBar8;
        seekBar8.setLayoutParams(new LinearLayout.LayoutParams(238, 17));
        this.ecfemfdnag.setPadding(95, 194, 11, 120);
        linearLayout.addView(this.ecfemfdnag);
        this.ecfemfdnag.setBackgroundColor(Color.parseColor("#2daf64"));
        EditText editText7 = new EditText(this);
        this.qlzxjtqaqu = editText7;
        editText7.setLayoutParams(new LinearLayout.LayoutParams(158, 1550));
        this.qlzxjtqaqu.setPadding(64, 87, 177, 96);
        linearLayout.addView(this.qlzxjtqaqu);
        this.qlzxjtqaqu.setBackgroundColor(Color.parseColor("#c433cc"));
        SeekBar seekBar9 = new SeekBar(this);
        this.wvnuspadad = seekBar9;
        seekBar9.setLayoutParams(new LinearLayout.LayoutParams(1949, 286));
        this.wvnuspadad.setPadding(102, 171, 103, 112);
        linearLayout.addView(this.wvnuspadad);
        this.wvnuspadad.setBackgroundColor(Color.parseColor("#a140d6"));
        ToggleButton toggleButton7 = new ToggleButton(this);
        this.ftarbumvje = toggleButton7;
        toggleButton7.setLayoutParams(new LinearLayout.LayoutParams(1314, 1105));
        this.ftarbumvje.setPadding(77, 61, 192, 110);
        linearLayout.addView(this.ftarbumvje);
        this.ftarbumvje.setBackgroundColor(Color.parseColor("#4dcb4a"));
        EditText editText8 = new EditText(this);
        this.moofrwmmny = editText8;
        editText8.setLayoutParams(new LinearLayout.LayoutParams(571, 1316));
        this.moofrwmmny.setPadding(75, 71, 67, 140);
        linearLayout.addView(this.moofrwmmny);
        this.moofrwmmny.setBackgroundColor(Color.parseColor("#c5e32a"));
        Button button9 = new Button(this);
        this.hvgvdhofso = button9;
        button9.setLayoutParams(new LinearLayout.LayoutParams(483, 1271));
        this.hvgvdhofso.setPadding(183, 37, 166, 9);
        linearLayout.addView(this.hvgvdhofso);
        this.hvgvdhofso.setBackgroundColor(Color.parseColor("#eab68a"));
        ViewFlipper viewFlipper8 = new ViewFlipper(this);
        this.fmitqoufnh = viewFlipper8;
        viewFlipper8.setLayoutParams(new LinearLayout.LayoutParams(853, 471));
        this.fmitqoufnh.setPadding(138, 144, 19, 182);
        linearLayout.addView(this.fmitqoufnh);
        this.fmitqoufnh.setBackgroundColor(Color.parseColor("#d72e76"));
        RatingBar ratingBar9 = new RatingBar(this);
        this.qnqyrzxibg = ratingBar9;
        ratingBar9.setLayoutParams(new LinearLayout.LayoutParams(1097, 1343));
        this.qnqyrzxibg.setPadding(105, 95, 76, 186);
        linearLayout.addView(this.qnqyrzxibg);
        this.qnqyrzxibg.setBackgroundColor(Color.parseColor("#9f4146"));
        RelativeLayout relativeLayout10 = new RelativeLayout(this);
        this.xisegsvswn = relativeLayout10;
        relativeLayout10.setLayoutParams(new LinearLayout.LayoutParams(1776, 1633));
        this.xisegsvswn.setPadding(196, 86, 194, 128);
        linearLayout.addView(this.xisegsvswn);
        this.xisegsvswn.setBackgroundColor(Color.parseColor("#70eb81"));
        LinearLayout linearLayout14 = new LinearLayout(this);
        this.aqycjbwmep = linearLayout14;
        linearLayout14.setLayoutParams(new LinearLayout.LayoutParams(1414, 105));
        this.aqycjbwmep.setPadding(70, 48, 132, 93);
        linearLayout.addView(this.aqycjbwmep);
        this.aqycjbwmep.setBackgroundColor(Color.parseColor("#47de97"));
        Spinner spinner12 = new Spinner(this);
        this.cvuraeorzl = spinner12;
        spinner12.setLayoutParams(new LinearLayout.LayoutParams(1836, 1513));
        this.cvuraeorzl.setPadding(49, 128, 135, 102);
        linearLayout.addView(this.cvuraeorzl);
        this.cvuraeorzl.setBackgroundColor(Color.parseColor("#2b55fc"));
        TextView textView13 = new TextView(this);
        this.wdrzqsjuhk = textView13;
        textView13.setLayoutParams(new LinearLayout.LayoutParams(1113, 1207));
        this.wdrzqsjuhk.setPadding(117, 182, 98, 158);
        linearLayout.addView(this.wdrzqsjuhk);
        this.wdrzqsjuhk.setBackgroundColor(Color.parseColor("#9f1335"));
        ViewFlipper viewFlipper9 = new ViewFlipper(this);
        this.pgezowlzxq = viewFlipper9;
        viewFlipper9.setLayoutParams(new LinearLayout.LayoutParams(1348, 26));
        this.pgezowlzxq.setPadding(85, PictureConfig.CHOOSE_REQUEST, 108, 182);
        linearLayout.addView(this.pgezowlzxq);
        this.pgezowlzxq.setBackgroundColor(Color.parseColor("#754218"));
        SeekBar seekBar10 = new SeekBar(this);
        this.ibscpupksl = seekBar10;
        seekBar10.setLayoutParams(new LinearLayout.LayoutParams(215, 205));
        this.ibscpupksl.setPadding(119, 111, 36, 13);
        linearLayout.addView(this.ibscpupksl);
        this.ibscpupksl.setBackgroundColor(Color.parseColor("#699949"));
        Switch r311 = new Switch(this);
        this.kvzzqvisvc = r311;
        r311.setLayoutParams(new LinearLayout.LayoutParams(91, 1443));
        this.kvzzqvisvc.setPadding(46, 98, 76, 64);
        linearLayout.addView(this.kvzzqvisvc);
        this.kvzzqvisvc.setBackgroundColor(Color.parseColor("#cabb08"));
        Switch r312 = new Switch(this);
        this.iobervlyrb = r312;
        r312.setLayoutParams(new LinearLayout.LayoutParams(931, 1297));
        this.iobervlyrb.setPadding(93, 86, 18, 164);
        linearLayout.addView(this.iobervlyrb);
        this.iobervlyrb.setBackgroundColor(Color.parseColor("#7c42ac"));
        RadioButton radioButton8 = new RadioButton(this);
        this.eikyrytjlo = radioButton8;
        radioButton8.setLayoutParams(new LinearLayout.LayoutParams(1919, 130));
        this.eikyrytjlo.setPadding(163, 30, 195, 14);
        linearLayout.addView(this.eikyrytjlo);
        this.eikyrytjlo.setBackgroundColor(Color.parseColor("#56462b"));
        ViewFlipper viewFlipper10 = new ViewFlipper(this);
        this.gdqrhiafbs = viewFlipper10;
        viewFlipper10.setLayoutParams(new LinearLayout.LayoutParams(1798, 492));
        this.gdqrhiafbs.setPadding(158, 30, 77, 20);
        linearLayout.addView(this.gdqrhiafbs);
        this.gdqrhiafbs.setBackgroundColor(Color.parseColor("#fd85cc"));
        ListView listView13 = new ListView(this);
        this.qsxtahobuh = listView13;
        listView13.setLayoutParams(new LinearLayout.LayoutParams(1127, 1528));
        this.qsxtahobuh.setPadding(141, 99, 72, 14);
        linearLayout.addView(this.qsxtahobuh);
        this.qsxtahobuh.setBackgroundColor(Color.parseColor("#9897ca"));
        EditText editText9 = new EditText(this);
        this.xeaxlyrjmk = editText9;
        editText9.setLayoutParams(new LinearLayout.LayoutParams(1526, 1895));
        this.xeaxlyrjmk.setPadding(29, 6, 26, 157);
        linearLayout.addView(this.xeaxlyrjmk);
        this.xeaxlyrjmk.setBackgroundColor(Color.parseColor("#b6d451"));
        ListView listView14 = new ListView(this);
        this.scmxdptcsn = listView14;
        listView14.setLayoutParams(new LinearLayout.LayoutParams(1735, 1417));
        this.scmxdptcsn.setPadding(128, 33, 125, 172);
        linearLayout.addView(this.scmxdptcsn);
        this.scmxdptcsn.setBackgroundColor(Color.parseColor("#de1337"));
        TextView textView14 = new TextView(this);
        this.slytliqxwi = textView14;
        textView14.setLayoutParams(new LinearLayout.LayoutParams(801, 592));
        this.slytliqxwi.setPadding(150, 140, 143, 139);
        linearLayout.addView(this.slytliqxwi);
        this.slytliqxwi.setBackgroundColor(Color.parseColor("#1806ab"));
        FrameLayout frameLayout11 = new FrameLayout(this);
        this.jinauwkemy = frameLayout11;
        frameLayout11.setLayoutParams(new LinearLayout.LayoutParams(1274, 1657));
        this.jinauwkemy.setPadding(145, BDLocation.TypeNetWorkLocation, 156, 137);
        linearLayout.addView(this.jinauwkemy);
        this.jinauwkemy.setBackgroundColor(Color.parseColor("#53b8c2"));
        RatingBar ratingBar10 = new RatingBar(this);
        this.vnpgntkgmz = ratingBar10;
        ratingBar10.setLayoutParams(new LinearLayout.LayoutParams(225, 1603));
        this.vnpgntkgmz.setPadding(17, 194, 187, 170);
        linearLayout.addView(this.vnpgntkgmz);
        this.vnpgntkgmz.setBackgroundColor(Color.parseColor("#902d75"));
        GridView gridView5 = new GridView(this);
        this.lubpnrtejh = gridView5;
        gridView5.setLayoutParams(new LinearLayout.LayoutParams(1461, 1233));
        this.lubpnrtejh.setPadding(64, 116, 11, 199);
        linearLayout.addView(this.lubpnrtejh);
        this.lubpnrtejh.setBackgroundColor(Color.parseColor("#8ff3ea"));
        TextView textView15 = new TextView(this);
        this.pkozkhjdhq = textView15;
        textView15.setLayoutParams(new LinearLayout.LayoutParams(1145, 674));
        this.pkozkhjdhq.setPadding(195, 165, 96, 44);
        linearLayout.addView(this.pkozkhjdhq);
        this.pkozkhjdhq.setBackgroundColor(Color.parseColor("#d05f45"));
        TimePicker timePicker6 = new TimePicker(this);
        this.scfbcoxkft = timePicker6;
        timePicker6.setLayoutParams(new LinearLayout.LayoutParams(1785, 1624));
        this.scfbcoxkft.setPadding(6, 152, 159, 59);
        linearLayout.addView(this.scfbcoxkft);
        this.scfbcoxkft.setBackgroundColor(Color.parseColor("#a385ce"));
        ListView listView15 = new ListView(this);
        this.lfmdtsmhpz = listView15;
        listView15.setLayoutParams(new LinearLayout.LayoutParams(357, 1518));
        this.lfmdtsmhpz.setPadding(99, 49, 123, 158);
        linearLayout.addView(this.lfmdtsmhpz);
        this.lfmdtsmhpz.setBackgroundColor(Color.parseColor("#0ceb3b"));
        SeekBar seekBar11 = new SeekBar(this);
        this.mtrckbatgx = seekBar11;
        seekBar11.setLayoutParams(new LinearLayout.LayoutParams(1552, 1339));
        this.mtrckbatgx.setPadding(174, 116, 187, 194);
        linearLayout.addView(this.mtrckbatgx);
        this.mtrckbatgx.setBackgroundColor(Color.parseColor("#97b09f"));
        LinearLayout linearLayout15 = new LinearLayout(this);
        this.eqrdisward = linearLayout15;
        linearLayout15.setLayoutParams(new LinearLayout.LayoutParams(269, 412));
        this.eqrdisward.setPadding(0, 127, 89, 63);
        linearLayout.addView(this.eqrdisward);
        this.eqrdisward.setBackgroundColor(Color.parseColor("#168aac"));
        TextView textView16 = new TextView(this);
        this.slttwhuvtk = textView16;
        textView16.setLayoutParams(new LinearLayout.LayoutParams(1485, 454));
        this.slttwhuvtk.setPadding(151, 71, 152, 93);
        linearLayout.addView(this.slttwhuvtk);
        this.slttwhuvtk.setBackgroundColor(Color.parseColor("#6f7409"));
        ScrollView scrollView7 = new ScrollView(this);
        this.qicdpgnvno = scrollView7;
        scrollView7.setLayoutParams(new LinearLayout.LayoutParams(992, 1345));
        this.qicdpgnvno.setPadding(31, 8, 194, 146);
        linearLayout.addView(this.qicdpgnvno);
        this.qicdpgnvno.setBackgroundColor(Color.parseColor("#ffdfc4"));
        ViewFlipper viewFlipper11 = new ViewFlipper(this);
        this.dgxfrlcgkt = viewFlipper11;
        viewFlipper11.setLayoutParams(new LinearLayout.LayoutParams(895, 1289));
        this.dgxfrlcgkt.setPadding(143, 38, 117, 54);
        linearLayout.addView(this.dgxfrlcgkt);
        this.dgxfrlcgkt.setBackgroundColor(Color.parseColor("#dbd96b"));
        RelativeLayout relativeLayout11 = new RelativeLayout(this);
        this.saaglafwtr = relativeLayout11;
        relativeLayout11.setLayoutParams(new LinearLayout.LayoutParams(1403, 679));
        this.saaglafwtr.setPadding(146, 96, 145, 135);
        linearLayout.addView(this.saaglafwtr);
        this.saaglafwtr.setBackgroundColor(Color.parseColor("#b7bb23"));
        LinearLayout linearLayout16 = new LinearLayout(this);
        this.qoxfwsuqig = linearLayout16;
        linearLayout16.setLayoutParams(new LinearLayout.LayoutParams(974, 1317));
        this.qoxfwsuqig.setPadding(64, 156, 144, 73);
        linearLayout.addView(this.qoxfwsuqig);
        this.qoxfwsuqig.setBackgroundColor(Color.parseColor("#ee05fa"));
        ScrollView scrollView8 = new ScrollView(this);
        this.xrijurukts = scrollView8;
        scrollView8.setLayoutParams(new LinearLayout.LayoutParams(515, 551));
        this.xrijurukts.setPadding(120, 100, 89, 38);
        linearLayout.addView(this.xrijurukts);
        this.xrijurukts.setBackgroundColor(Color.parseColor("#221959"));
        RatingBar ratingBar11 = new RatingBar(this);
        this.zzmekoghtz = ratingBar11;
        ratingBar11.setLayoutParams(new LinearLayout.LayoutParams(891, 925));
        this.zzmekoghtz.setPadding(37, 151, 97, 172);
        linearLayout.addView(this.zzmekoghtz);
        this.zzmekoghtz.setBackgroundColor(Color.parseColor("#d3aff8"));
        DatePicker datePicker9 = new DatePicker(this);
        this.cqvlgcbxye = datePicker9;
        datePicker9.setLayoutParams(new LinearLayout.LayoutParams(1029, 1821));
        this.cqvlgcbxye.setPadding(131, 197, 7, 141);
        linearLayout.addView(this.cqvlgcbxye);
        this.cqvlgcbxye.setBackgroundColor(Color.parseColor("#20fc33"));
        ListView listView16 = new ListView(this);
        this.wlvcejxmzi = listView16;
        listView16.setLayoutParams(new LinearLayout.LayoutParams(562, 694));
        this.wlvcejxmzi.setPadding(196, 170, 68, 40);
        linearLayout.addView(this.wlvcejxmzi);
        this.wlvcejxmzi.setBackgroundColor(Color.parseColor("#8a78d6"));
        TextView textView17 = new TextView(this);
        this.lchchgnhko = textView17;
        textView17.setLayoutParams(new LinearLayout.LayoutParams(172, 184));
        this.lchchgnhko.setPadding(75, 187, 69, 22);
        linearLayout.addView(this.lchchgnhko);
        this.lchchgnhko.setBackgroundColor(Color.parseColor("#50f163"));
        TextView textView18 = new TextView(this);
        this.swlnpulnoh = textView18;
        textView18.setLayoutParams(new LinearLayout.LayoutParams(1721, 1304));
        this.swlnpulnoh.setPadding(125, 46, 94, 135);
        linearLayout.addView(this.swlnpulnoh);
        this.swlnpulnoh.setBackgroundColor(Color.parseColor("#44bcb7"));
        ViewFlipper viewFlipper12 = new ViewFlipper(this);
        this.wwmriczyhl = viewFlipper12;
        viewFlipper12.setLayoutParams(new LinearLayout.LayoutParams(233, 327));
        this.wwmriczyhl.setPadding(87, 67, 132, 11);
        linearLayout.addView(this.wwmriczyhl);
        this.wwmriczyhl.setBackgroundColor(Color.parseColor("#dced53"));
        EditText editText10 = new EditText(this);
        this.ggzqhxwthe = editText10;
        editText10.setLayoutParams(new LinearLayout.LayoutParams(561, 603));
        this.ggzqhxwthe.setPadding(15, 1, 189, 28);
        linearLayout.addView(this.ggzqhxwthe);
        this.ggzqhxwthe.setBackgroundColor(Color.parseColor("#b0f0f0"));
        ListView listView17 = new ListView(this);
        this.glsecqvukw = listView17;
        listView17.setLayoutParams(new LinearLayout.LayoutParams(1979, 654));
        this.glsecqvukw.setPadding(99, 91, 127, 73);
        linearLayout.addView(this.glsecqvukw);
        this.glsecqvukw.setBackgroundColor(Color.parseColor("#4e63bc"));
        RelativeLayout relativeLayout12 = new RelativeLayout(this);
        this.kjmmjsmync = relativeLayout12;
        relativeLayout12.setLayoutParams(new LinearLayout.LayoutParams(1539, 1595));
        this.kjmmjsmync.setPadding(144, 72, 83, 31);
        linearLayout.addView(this.kjmmjsmync);
        this.kjmmjsmync.setBackgroundColor(Color.parseColor("#80d537"));
        ListView listView18 = new ListView(this);
        this.wtpdpwwyxk = listView18;
        listView18.setLayoutParams(new LinearLayout.LayoutParams(103, 1072));
        this.wtpdpwwyxk.setPadding(105, 89, 141, 177);
        linearLayout.addView(this.wtpdpwwyxk);
        this.wtpdpwwyxk.setBackgroundColor(Color.parseColor("#186040"));
        CheckBox checkBox11 = new CheckBox(this);
        this.ukqdaxklkg = checkBox11;
        checkBox11.setLayoutParams(new LinearLayout.LayoutParams(1443, 821));
        this.ukqdaxklkg.setPadding(125, 69, 27, 7);
        linearLayout.addView(this.ukqdaxklkg);
        this.ukqdaxklkg.setBackgroundColor(Color.parseColor("#7e582d"));
        RadioButton radioButton9 = new RadioButton(this);
        this.sldixtokki = radioButton9;
        radioButton9.setLayoutParams(new LinearLayout.LayoutParams(32, 1971));
        this.sldixtokki.setPadding(115, 64, 86, 123);
        linearLayout.addView(this.sldixtokki);
        this.sldixtokki.setBackgroundColor(Color.parseColor("#d8bb99"));
        DatePicker datePicker10 = new DatePicker(this);
        this.kselwotlqz = datePicker10;
        datePicker10.setLayoutParams(new LinearLayout.LayoutParams(879, 472));
        this.kselwotlqz.setPadding(28, 90, 193, 142);
        linearLayout.addView(this.kselwotlqz);
        this.kselwotlqz.setBackgroundColor(Color.parseColor("#59656c"));
        ImageView imageView9 = new ImageView(this);
        this.zyqumasyyk = imageView9;
        imageView9.setLayoutParams(new LinearLayout.LayoutParams(767, 1599));
        this.zyqumasyyk.setPadding(157, 11, 36, 34);
        linearLayout.addView(this.zyqumasyyk);
        this.zyqumasyyk.setBackgroundColor(Color.parseColor("#e0ecf9"));
        DatePicker datePicker11 = new DatePicker(this);
        this.qhyuegswih = datePicker11;
        datePicker11.setLayoutParams(new LinearLayout.LayoutParams(1120, 677));
        this.qhyuegswih.setPadding(96, 44, 52, 145);
        linearLayout.addView(this.qhyuegswih);
        this.qhyuegswih.setBackgroundColor(Color.parseColor("#b63b1f"));
        TextView textView19 = new TextView(this);
        this.tmurcoupjx = textView19;
        textView19.setLayoutParams(new LinearLayout.LayoutParams(585, 31));
        this.tmurcoupjx.setPadding(182, 65, 43, 107);
        linearLayout.addView(this.tmurcoupjx);
        this.tmurcoupjx.setBackgroundColor(Color.parseColor("#de5d8a"));
        CheckBox checkBox12 = new CheckBox(this);
        this.yiwiqvenau = checkBox12;
        checkBox12.setLayoutParams(new LinearLayout.LayoutParams(1686, 1376));
        this.yiwiqvenau.setPadding(99, 154, 174, 174);
        linearLayout.addView(this.yiwiqvenau);
        this.yiwiqvenau.setBackgroundColor(Color.parseColor("#4c8d23"));
        CheckBox checkBox13 = new CheckBox(this);
        this.ehdqihmbfr = checkBox13;
        checkBox13.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.MotionType.TYPE_PATHMOTION_ARC, 751));
        this.ehdqihmbfr.setPadding(142, 120, 183, 46);
        linearLayout.addView(this.ehdqihmbfr);
        this.ehdqihmbfr.setBackgroundColor(Color.parseColor("#46a7b3"));
        TimePicker timePicker7 = new TimePicker(this);
        this.ylwjijhucc = timePicker7;
        timePicker7.setLayoutParams(new LinearLayout.LayoutParams(1774, 1902));
        this.ylwjijhucc.setPadding(28, 148, 25, 29);
        linearLayout.addView(this.ylwjijhucc);
        this.ylwjijhucc.setBackgroundColor(Color.parseColor("#9f459d"));
        RatingBar ratingBar12 = new RatingBar(this);
        this.uqvjgjbmap = ratingBar12;
        ratingBar12.setLayoutParams(new LinearLayout.LayoutParams(8, 222));
        this.uqvjgjbmap.setPadding(121, 170, 43, 140);
        linearLayout.addView(this.uqvjgjbmap);
        this.uqvjgjbmap.setBackgroundColor(Color.parseColor("#db6090"));
        RatingBar ratingBar13 = new RatingBar(this);
        this.nnoievbyod = ratingBar13;
        ratingBar13.setLayoutParams(new LinearLayout.LayoutParams(1789, 1062));
        this.nnoievbyod.setPadding(58, 133, 138, 88);
        linearLayout.addView(this.nnoievbyod);
        this.nnoievbyod.setBackgroundColor(Color.parseColor("#8c29c7"));
        Spinner spinner13 = new Spinner(this);
        this.rhupmiyrto = spinner13;
        spinner13.setLayoutParams(new LinearLayout.LayoutParams(1703, 282));
        this.rhupmiyrto.setPadding(17, PictureConfig.CHOOSE_REQUEST, 159, 8);
        linearLayout.addView(this.rhupmiyrto);
        this.rhupmiyrto.setBackgroundColor(Color.parseColor("#3deab1"));
        DatePicker datePicker12 = new DatePicker(this);
        this.yurbeqltlf = datePicker12;
        datePicker12.setLayoutParams(new LinearLayout.LayoutParams(5, 1073));
        this.yurbeqltlf.setPadding(158, 177, 113, 123);
        linearLayout.addView(this.yurbeqltlf);
        this.yurbeqltlf.setBackgroundColor(Color.parseColor("#52fe03"));
    }
}
