package com.device.watch.com.device.watch.turvtuudzw;

import android.app.Activity;
import android.graphics.Color;
import android.os.Bundle;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.CheckBox;
import android.widget.DatePicker;
import android.widget.FrameLayout;
import android.widget.GridView;
import android.widget.LinearLayout;
import android.widget.ProgressBar;
import android.widget.RatingBar;
import android.widget.RelativeLayout;
import android.widget.ScrollView;
import android.widget.SeekBar;
import android.widget.Spinner;
import android.widget.Switch;
import android.widget.TableLayout;
import android.widget.TextView;
import android.widget.TimePicker;
import android.widget.ToggleButton;
import android.widget.ViewFlipper;
import androidx.constraintlayout.core.motion.utils.TypedValues;
import com.baidu.location.BDLocation;
import com.king.zxing.util.CodeUtils;
import com.luck.picture.lib.config.PictureConfig;
import com.realsil.sdk.core.bluetooth.connection.le.GattClient;

/* loaded from: classes2.dex */
public class WvneyonnyofActivity extends Activity {
    GridView anxotaxqvp;
    GridView axearesucg;
    DatePicker bdqibpxnts;
    SeekBar btnykmgzxb;
    CheckBox cpliwqbsiq;
    ScrollView crptixsbvw;
    TableLayout cvltvixtrx;
    DatePicker dsoodltfue;
    Switch gxjusipuuq;
    TableLayout hiqmkrebxu;
    DatePicker iazgvqtimn;
    SeekBar imlxgkfcrb;
    ProgressBar jelgcjtrbj;
    RatingBar kardpoowos;
    RatingBar kevnqwvoxb;
    TextView lfwlsobvoa;
    ProgressBar mqdhirvgfs;
    ViewFlipper najtfgbsdz;
    TimePicker owkqnvpjov;
    ViewFlipper qcpchhwufc;
    Spinner qghqgoazvr;
    FrameLayout quhowsqvhw;
    TableLayout rdfjctfbea;
    Switch rgkbkvsxuo;
    ToggleButton stqipepwew;
    ProgressBar tvkaufknta;
    Button uzylaoaoeh;
    Button xpsqyvtygq;
    RelativeLayout yzviolkqce;

    @Override // android.app.Activity
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        LinearLayout linearLayout = new LinearLayout(this);
        setContentView(linearLayout);
        linearLayout.setLayoutParams(new ViewGroup.LayoutParams(-1, -1));
        linearLayout.setOrientation(1);
        linearLayout.setBackgroundColor(Color.parseColor("#75ec52"));
        RelativeLayout relativeLayout = new RelativeLayout(this);
        this.yzviolkqce = relativeLayout;
        relativeLayout.setLayoutParams(new LinearLayout.LayoutParams(1372, GattClient.STATE_DISCOVERY_SERVICE));
        this.yzviolkqce.setPadding(56, 83, 175, 70);
        linearLayout.addView(this.yzviolkqce);
        this.yzviolkqce.setBackgroundColor(Color.parseColor("#8fd503"));
        SeekBar seekBar = new SeekBar(this);
        this.imlxgkfcrb = seekBar;
        seekBar.setLayoutParams(new LinearLayout.LayoutParams(CodeUtils.DEFAULT_REQ_HEIGHT, 1603));
        this.imlxgkfcrb.setPadding(142, 57, 196, 195);
        linearLayout.addView(this.imlxgkfcrb);
        this.imlxgkfcrb.setBackgroundColor(Color.parseColor("#9e304f"));
        ProgressBar progressBar = new ProgressBar(this);
        this.tvkaufknta = progressBar;
        progressBar.setLayoutParams(new LinearLayout.LayoutParams(756, 1554));
        this.tvkaufknta.setPadding(55, 136, 193, 71);
        linearLayout.addView(this.tvkaufknta);
        this.tvkaufknta.setBackgroundColor(Color.parseColor("#d2ed31"));
        GridView gridView = new GridView(this);
        this.anxotaxqvp = gridView;
        gridView.setLayoutParams(new LinearLayout.LayoutParams(1057, 757));
        this.anxotaxqvp.setPadding(27, 18, 197, 109);
        linearLayout.addView(this.anxotaxqvp);
        this.anxotaxqvp.setBackgroundColor(Color.parseColor("#68e8d6"));
        TimePicker timePicker = new TimePicker(this);
        this.owkqnvpjov = timePicker;
        timePicker.setLayoutParams(new LinearLayout.LayoutParams(1052, 1982));
        this.owkqnvpjov.setPadding(11, 146, 134, 44);
        linearLayout.addView(this.owkqnvpjov);
        this.owkqnvpjov.setBackgroundColor(Color.parseColor("#6118d3"));
        DatePicker datePicker = new DatePicker(this);
        this.iazgvqtimn = datePicker;
        datePicker.setLayoutParams(new LinearLayout.LayoutParams(1911, 560));
        this.iazgvqtimn.setPadding(198, 120, 125, 197);
        linearLayout.addView(this.iazgvqtimn);
        this.iazgvqtimn.setBackgroundColor(Color.parseColor("#f85165"));
        TableLayout tableLayout = new TableLayout(this);
        this.cvltvixtrx = tableLayout;
        tableLayout.setLayoutParams(new LinearLayout.LayoutParams(1114, 506));
        this.cvltvixtrx.setPadding(110, 144, 76, BDLocation.TypeNetWorkLocation);
        linearLayout.addView(this.cvltvixtrx);
        this.cvltvixtrx.setBackgroundColor(Color.parseColor("#051b72"));
        CheckBox checkBox = new CheckBox(this);
        this.cpliwqbsiq = checkBox;
        checkBox.setLayoutParams(new LinearLayout.LayoutParams(1816, 1324));
        this.cpliwqbsiq.setPadding(13, 46, 87, 176);
        linearLayout.addView(this.cpliwqbsiq);
        this.cpliwqbsiq.setBackgroundColor(Color.parseColor("#ea9e1d"));
        Button button = new Button(this);
        this.xpsqyvtygq = button;
        button.setLayoutParams(new LinearLayout.LayoutParams(278, 1692));
        this.xpsqyvtygq.setPadding(146, 184, 176, 25);
        linearLayout.addView(this.xpsqyvtygq);
        this.xpsqyvtygq.setBackgroundColor(Color.parseColor("#e7f8bd"));
        ViewFlipper viewFlipper = new ViewFlipper(this);
        this.qcpchhwufc = viewFlipper;
        viewFlipper.setLayoutParams(new LinearLayout.LayoutParams(15, 477));
        this.qcpchhwufc.setPadding(57, 0, 47, 59);
        linearLayout.addView(this.qcpchhwufc);
        this.qcpchhwufc.setBackground(new Rovfcbfdmbg());
        Switch r2 = new Switch(this);
        this.gxjusipuuq = r2;
        r2.setLayoutParams(new LinearLayout.LayoutParams(1680, 777));
        this.gxjusipuuq.setPadding(30, 115, PictureConfig.CHOOSE_REQUEST, 130);
        linearLayout.addView(this.gxjusipuuq);
        this.gxjusipuuq.setBackgroundColor(Color.parseColor("#76c549"));
        TableLayout tableLayout2 = new TableLayout(this);
        this.hiqmkrebxu = tableLayout2;
        tableLayout2.setLayoutParams(new LinearLayout.LayoutParams(807, 1343));
        this.hiqmkrebxu.setPadding(111, 11, 134, 0);
        linearLayout.addView(this.hiqmkrebxu);
        this.hiqmkrebxu.setBackgroundColor(Color.parseColor("#861282"));
        FrameLayout frameLayout = new FrameLayout(this);
        this.quhowsqvhw = frameLayout;
        frameLayout.setLayoutParams(new LinearLayout.LayoutParams(557, 863));
        this.quhowsqvhw.setPadding(63, 111, 8, 87);
        linearLayout.addView(this.quhowsqvhw);
        this.quhowsqvhw.setBackgroundColor(Color.parseColor("#02f862"));
        ViewFlipper viewFlipper2 = new ViewFlipper(this);
        this.najtfgbsdz = viewFlipper2;
        viewFlipper2.setLayoutParams(new LinearLayout.LayoutParams(354, 1314));
        this.najtfgbsdz.setPadding(128, 22, 131, 136);
        linearLayout.addView(this.najtfgbsdz);
        this.najtfgbsdz.setBackgroundColor(Color.parseColor("#f89be5"));
        RatingBar ratingBar = new RatingBar(this);
        this.kardpoowos = ratingBar;
        ratingBar.setLayoutParams(new LinearLayout.LayoutParams(251, 1582));
        this.kardpoowos.setPadding(81, 106, 111, 78);
        linearLayout.addView(this.kardpoowos);
        this.kardpoowos.setBackgroundColor(Color.parseColor("#d67859"));
        SeekBar seekBar2 = new SeekBar(this);
        this.btnykmgzxb = seekBar2;
        seekBar2.setLayoutParams(new LinearLayout.LayoutParams(618, 65));
        this.btnykmgzxb.setPadding(83, 74, 156, 26);
        linearLayout.addView(this.btnykmgzxb);
        this.btnykmgzxb.setBackgroundColor(Color.parseColor("#0a1643"));
        RatingBar ratingBar2 = new RatingBar(this);
        this.kevnqwvoxb = ratingBar2;
        ratingBar2.setLayoutParams(new LinearLayout.LayoutParams(291, 384));
        this.kevnqwvoxb.setPadding(114, 19, 93, 7);
        linearLayout.addView(this.kevnqwvoxb);
        this.kevnqwvoxb.setBackgroundColor(Color.parseColor("#cb39bb"));
        DatePicker datePicker2 = new DatePicker(this);
        this.dsoodltfue = datePicker2;
        datePicker2.setLayoutParams(new LinearLayout.LayoutParams(49, 1224));
        this.dsoodltfue.setPadding(60, 138, 135, 117);
        linearLayout.addView(this.dsoodltfue);
        this.dsoodltfue.setBackgroundColor(Color.parseColor("#736df2"));
        ToggleButton toggleButton = new ToggleButton(this);
        this.stqipepwew = toggleButton;
        toggleButton.setLayoutParams(new LinearLayout.LayoutParams(1967, 1929));
        this.stqipepwew.setPadding(136, 74, 79, 140);
        linearLayout.addView(this.stqipepwew);
        this.stqipepwew.setBackgroundColor(Color.parseColor("#a29245"));
        ProgressBar progressBar2 = new ProgressBar(this);
        this.jelgcjtrbj = progressBar2;
        progressBar2.setLayoutParams(new LinearLayout.LayoutParams(939, 1202));
        this.jelgcjtrbj.setPadding(93, 190, 171, 24);
        linearLayout.addView(this.jelgcjtrbj);
        this.jelgcjtrbj.setBackgroundColor(Color.parseColor("#7d2918"));
        ProgressBar progressBar3 = new ProgressBar(this);
        this.mqdhirvgfs = progressBar3;
        progressBar3.setLayoutParams(new LinearLayout.LayoutParams(1309, 436));
        this.mqdhirvgfs.setPadding(27, 75, 72, 147);
        linearLayout.addView(this.mqdhirvgfs);
        this.mqdhirvgfs.setBackgroundColor(Color.parseColor("#13dc94"));
        TextView textView = new TextView(this);
        this.lfwlsobvoa = textView;
        textView.setLayoutParams(new LinearLayout.LayoutParams(1502, 271));
        this.lfwlsobvoa.setPadding(118, 180, 16, 67);
        linearLayout.addView(this.lfwlsobvoa);
        this.lfwlsobvoa.setBackgroundColor(Color.parseColor("#c6608c"));
        ScrollView scrollView = new ScrollView(this);
        this.crptixsbvw = scrollView;
        scrollView.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.MotionType.TYPE_QUANTIZE_INTERPOLATOR, 955));
        this.crptixsbvw.setPadding(166, 122, 87, BDLocation.TypeServerDecryptError);
        linearLayout.addView(this.crptixsbvw);
        this.crptixsbvw.setBackgroundColor(Color.parseColor("#aee9d4"));
        GridView gridView2 = new GridView(this);
        this.axearesucg = gridView2;
        gridView2.setLayoutParams(new LinearLayout.LayoutParams(547, 924));
        this.axearesucg.setPadding(132, 191, 156, 196);
        linearLayout.addView(this.axearesucg);
        this.axearesucg.setBackgroundColor(Color.parseColor("#f8b6d0"));
        TableLayout tableLayout3 = new TableLayout(this);
        this.rdfjctfbea = tableLayout3;
        tableLayout3.setLayoutParams(new LinearLayout.LayoutParams(222, TypedValues.PositionType.TYPE_POSITION_TYPE));
        this.rdfjctfbea.setPadding(14, 15, 154, 88);
        linearLayout.addView(this.rdfjctfbea);
        this.rdfjctfbea.setBackgroundColor(Color.parseColor("#44ed41"));
        Button button2 = new Button(this);
        this.uzylaoaoeh = button2;
        button2.setLayoutParams(new LinearLayout.LayoutParams(723, 1665));
        this.uzylaoaoeh.setPadding(163, 139, 153, 134);
        linearLayout.addView(this.uzylaoaoeh);
        this.uzylaoaoeh.setBackgroundColor(Color.parseColor("#2eab2e"));
        Switch r22 = new Switch(this);
        this.rgkbkvsxuo = r22;
        r22.setLayoutParams(new LinearLayout.LayoutParams(933, 1721));
        this.rgkbkvsxuo.setPadding(154, 58, 15, 81);
        linearLayout.addView(this.rgkbkvsxuo);
        this.rgkbkvsxuo.setBackgroundColor(Color.parseColor("#63b330"));
        DatePicker datePicker3 = new DatePicker(this);
        this.bdqibpxnts = datePicker3;
        datePicker3.setLayoutParams(new LinearLayout.LayoutParams(124, 412));
        this.bdqibpxnts.setPadding(45, 45, 105, 178);
        linearLayout.addView(this.bdqibpxnts);
        this.bdqibpxnts.setBackgroundColor(Color.parseColor("#d1b7cb"));
        Spinner spinner = new Spinner(this);
        this.qghqgoazvr = spinner;
        spinner.setLayoutParams(new LinearLayout.LayoutParams(39, 369));
        this.qghqgoazvr.setPadding(139, 86, 95, 65);
        linearLayout.addView(this.qghqgoazvr);
        this.qghqgoazvr.setBackgroundColor(Color.parseColor("#2583fe"));
    }
}
