package com.smartapp.b.fxqukyurem;

import android.app.Activity;
import android.graphics.Color;
import android.os.Bundle;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.CheckBox;
import android.widget.DatePicker;
import android.widget.EditText;
import android.widget.FrameLayout;
import android.widget.GridView;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ListView;
import android.widget.ProgressBar;
import android.widget.RadioButton;
import android.widget.RatingBar;
import android.widget.RelativeLayout;
import android.widget.ScrollView;
import android.widget.SeekBar;
import android.widget.Spinner;
import android.widget.Switch;
import android.widget.TableLayout;
import android.widget.TextView;
import android.widget.TimePicker;
import android.widget.ToggleButton;
import android.widget.ViewFlipper;
import androidx.constraintlayout.core.motion.utils.TypedValues;
import androidx.room.RoomDatabase;
import com.baidu.location.BDLocation;
import com.google.android.gms.common.ConnectionResult;
import com.qcwireless.qcwatch.ui.base.imagepicker.cropper.CropImage;
import com.realsil.sdk.bbpro.equalizer.AudioEq;
import com.realsil.sdk.core.bluetooth.connection.le.GattClient;
import okhttp3.internal.ws.WebSocketProtocol;

/* loaded from: classes4.dex */
public class MaiyluiqixcActivity extends Activity {
    SeekBar altrazzjeh;
    LinearLayout avcinlhjst;
    LinearLayout azrqyxdbcr;
    TableLayout bbpvzjhvfc;
    LinearLayout byuugokhac;
    RadioButton cdozflssje;
    LinearLayout cesxfthasn;
    CheckBox cezdaqtlsh;
    ListView ciuuuofesp;
    ViewFlipper csmgstpdkv;
    Button czggnigdqy;
    EditText dqhfngnvwz;
    ListView dubqwyrgid;
    ListView dwpkpnkkuk;
    Spinner dyulzierel;
    FrameLayout ermuqtdqjh;
    ListView fviyqidjau;
    TextView gwbrtmlpdi;
    ViewFlipper gzvurdolir;
    ProgressBar hoghcsjlwd;
    TextView hwoupajgqx;
    FrameLayout hwpoiufnvn;
    Spinner jbkhofdkpg;
    FrameLayout jbsdkxmmgt;
    Spinner jdsdcrpfzf;
    GridView jesvunutsl;
    ScrollView jfdmqmilhs;
    EditText jwwjjwfgiy;
    Spinner kaqraikujx;
    RelativeLayout kqwzlymmlh;
    FrameLayout ktkogbqmcd;
    FrameLayout lvxmssytec;
    ScrollView lzshhcvppb;
    TimePicker mdptkwfkrm;
    SeekBar medmcuqyop;
    TableLayout mhcynwjjnn;
    EditText mjiglvazwn;
    FrameLayout mjyrtxpwpv;
    Spinner mpbxkfoxxa;
    GridView mprqlothwz;
    ViewFlipper mtbuvlnwpr;
    GridView nvrrlhudfj;
    ScrollView olaresdpsc;
    TimePicker ooowkbxdia;
    FrameLayout pagefegblp;
    ToggleButton pbzlymllma;
    ViewFlipper ppdwjticcm;
    RatingBar pqxaenjjne;
    FrameLayout pwspbckutb;
    TimePicker qbczjegkjd;
    TableLayout qbwthooafz;
    Switch qfdqggtrmq;
    RatingBar qscmsvsgsq;
    ScrollView qvmcystkxt;
    RatingBar qwgdlgouqp;
    CheckBox qzlarpqokf;
    EditText qzswruytkl;
    ScrollView rhmrebnyqz;
    GridView rxxntuxlti;
    ToggleButton sqpvgprsad;
    CheckBox thuvvlgzzm;
    GridView tlnfzmtkeu;
    ScrollView tnhycuzqvl;
    FrameLayout tobduvudrr;
    RadioButton tsuhjohbgk;
    ToggleButton tvbqpltaqf;
    RatingBar txnzdyvybf;
    GridView tzeiiunwje;
    DatePicker udsdtkkubq;
    Spinner ufrdovspzg;
    LinearLayout uomlwrsjkc;
    Spinner vfsltxpejt;
    EditText vhgenyxvzm;
    TimePicker vhpddwqrqn;
    SeekBar vnthrshqte;
    ProgressBar vtrzgqssga;
    TimePicker vwdowthpzk;
    ImageView whfepukrkw;
    ProgressBar wucjxdgvhd;
    DatePicker wuiauojkph;
    ProgressBar xcgfitffse;
    TextView xnjemcxxpc;
    ScrollView xwvproojix;
    ViewFlipper xxckmemtkn;
    CheckBox yhmikrdtqo;
    ListView ykkybvshej;
    RatingBar ymtqwqfyyn;
    CheckBox yqcudmdxhy;
    ProgressBar yufgkxyuzh;
    TableLayout yusjhjcclu;
    ListView yzwakdmxad;
    RelativeLayout zoojscpiwo;

    @Override // android.app.Activity
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        LinearLayout linearLayout = new LinearLayout(this);
        setContentView(linearLayout);
        linearLayout.setLayoutParams(new ViewGroup.LayoutParams(-1, -1));
        linearLayout.setOrientation(1);
        linearLayout.setBackgroundColor(Color.parseColor("#555df6"));
        Spinner spinner = new Spinner(this);
        this.dyulzierel = spinner;
        spinner.setLayoutParams(new LinearLayout.LayoutParams(1870, 1694));
        this.dyulzierel.setPadding(87, 13, 187, 88);
        linearLayout.addView(this.dyulzierel);
        this.dyulzierel.setBackgroundColor(Color.parseColor("#378db8"));
        SeekBar seekBar = new SeekBar(this);
        this.altrazzjeh = seekBar;
        seekBar.setLayoutParams(new LinearLayout.LayoutParams(1289, 1895));
        this.altrazzjeh.setPadding(68, 46, 82, 145);
        linearLayout.addView(this.altrazzjeh);
        this.altrazzjeh.setBackgroundColor(Color.parseColor("#2ec3f1"));
        EditText editText = new EditText(this);
        this.vhgenyxvzm = editText;
        editText.setLayoutParams(new LinearLayout.LayoutParams(95, 1427));
        this.vhgenyxvzm.setPadding(55, 137, 63, 111);
        linearLayout.addView(this.vhgenyxvzm);
        this.vhgenyxvzm.setBackgroundColor(Color.parseColor("#0a8a37"));
        Spinner spinner2 = new Spinner(this);
        this.ufrdovspzg = spinner2;
        spinner2.setLayoutParams(new LinearLayout.LayoutParams(59, 218));
        this.ufrdovspzg.setPadding(166, 193, 28, 175);
        linearLayout.addView(this.ufrdovspzg);
        this.ufrdovspzg.setBackgroundColor(Color.parseColor("#75bdbf"));
        ToggleButton toggleButton = new ToggleButton(this);
        this.sqpvgprsad = toggleButton;
        toggleButton.setLayoutParams(new LinearLayout.LayoutParams(1215, 785));
        this.sqpvgprsad.setPadding(109, 64, 131, 66);
        linearLayout.addView(this.sqpvgprsad);
        this.sqpvgprsad.setBackgroundColor(Color.parseColor("#ac74a9"));
        ListView listView = new ListView(this);
        this.ciuuuofesp = listView;
        listView.setLayoutParams(new LinearLayout.LayoutParams(726, 956));
        this.ciuuuofesp.setPadding(143, 7, 153, 100);
        linearLayout.addView(this.ciuuuofesp);
        this.ciuuuofesp.setBackgroundColor(Color.parseColor("#87dc80"));
        Spinner spinner3 = new Spinner(this);
        this.vfsltxpejt = spinner3;
        spinner3.setLayoutParams(new LinearLayout.LayoutParams(1598, 232));
        this.vfsltxpejt.setPadding(155, 2, 96, 199);
        linearLayout.addView(this.vfsltxpejt);
        this.vfsltxpejt.setBackgroundColor(Color.parseColor("#fb57de"));
        ViewFlipper viewFlipper = new ViewFlipper(this);
        this.ppdwjticcm = viewFlipper;
        viewFlipper.setLayoutParams(new LinearLayout.LayoutParams(843, CropImage.PICK_IMAGE_PERMISSIONS_REQUEST_CODE));
        this.ppdwjticcm.setPadding(135, 54, 179, 153);
        linearLayout.addView(this.ppdwjticcm);
        this.ppdwjticcm.setBackgroundColor(Color.parseColor("#b26448"));
        Switch r2 = new Switch(this);
        this.qfdqggtrmq = r2;
        r2.setLayoutParams(new LinearLayout.LayoutParams(1613, 285));
        this.qfdqggtrmq.setPadding(193, 95, 52, 93);
        linearLayout.addView(this.qfdqggtrmq);
        this.qfdqggtrmq.setBackgroundColor(Color.parseColor("#8c0e6f"));
        RatingBar ratingBar = new RatingBar(this);
        this.qscmsvsgsq = ratingBar;
        ratingBar.setLayoutParams(new LinearLayout.LayoutParams(1371, 533));
        this.qscmsvsgsq.setPadding(40, 90, 185, 154);
        linearLayout.addView(this.qscmsvsgsq);
        this.qscmsvsgsq.setBackgroundColor(Color.parseColor("#ee6676"));
        DatePicker datePicker = new DatePicker(this);
        this.wuiauojkph = datePicker;
        datePicker.setLayoutParams(new LinearLayout.LayoutParams(881, 1333));
        this.wuiauojkph.setPadding(49, 84, 69, 78);
        linearLayout.addView(this.wuiauojkph);
        this.wuiauojkph.setBackgroundColor(Color.parseColor("#54ba54"));
        ScrollView scrollView = new ScrollView(this);
        this.qvmcystkxt = scrollView;
        scrollView.setLayoutParams(new LinearLayout.LayoutParams(1980, TypedValues.MotionType.TYPE_DRAW_PATH));
        this.qvmcystkxt.setPadding(102, 13, 26, 5);
        linearLayout.addView(this.qvmcystkxt);
        this.qvmcystkxt.setBackgroundColor(Color.parseColor("#80cadd"));
        GridView gridView = new GridView(this);
        this.tzeiiunwje = gridView;
        gridView.setLayoutParams(new LinearLayout.LayoutParams(1054, 1177));
        this.tzeiiunwje.setPadding(42, 150, 123, 2);
        linearLayout.addView(this.tzeiiunwje);
        this.tzeiiunwje.setBackgroundColor(Color.parseColor("#46d387"));
        CheckBox checkBox = new CheckBox(this);
        this.qzlarpqokf = checkBox;
        checkBox.setLayoutParams(new LinearLayout.LayoutParams(804, 353));
        this.qzlarpqokf.setPadding(40, 98, 8, BDLocation.TypeServerDecryptError);
        linearLayout.addView(this.qzlarpqokf);
        this.qzlarpqokf.setBackgroundColor(Color.parseColor("#c18b3c"));
        FrameLayout frameLayout = new FrameLayout(this);
        this.pwspbckutb = frameLayout;
        frameLayout.setLayoutParams(new LinearLayout.LayoutParams(1564, 1969));
        this.pwspbckutb.setPadding(130, 11, 138, 33);
        linearLayout.addView(this.pwspbckutb);
        this.pwspbckutb.setBackground(new Awihxsrpubj());
        ViewFlipper viewFlipper2 = new ViewFlipper(this);
        this.gzvurdolir = viewFlipper2;
        viewFlipper2.setLayoutParams(new LinearLayout.LayoutParams(1002, 80));
        this.gzvurdolir.setPadding(176, 144, 147, 63);
        linearLayout.addView(this.gzvurdolir);
        this.gzvurdolir.setBackgroundColor(Color.parseColor("#bb42bd"));
        LinearLayout linearLayout2 = new LinearLayout(this);
        this.cesxfthasn = linearLayout2;
        linearLayout2.setLayoutParams(new LinearLayout.LayoutParams(1789, 1147));
        this.cesxfthasn.setPadding(110, 179, 73, 170);
        linearLayout.addView(this.cesxfthasn);
        this.cesxfthasn.setBackgroundColor(Color.parseColor("#db3d9b"));
        FrameLayout frameLayout2 = new FrameLayout(this);
        this.tobduvudrr = frameLayout2;
        frameLayout2.setLayoutParams(new LinearLayout.LayoutParams(1263, 790));
        this.tobduvudrr.setPadding(87, 84, 13, 103);
        linearLayout.addView(this.tobduvudrr);
        this.tobduvudrr.setBackgroundColor(Color.parseColor("#520fc2"));
        ListView listView2 = new ListView(this);
        this.ykkybvshej = listView2;
        listView2.setLayoutParams(new LinearLayout.LayoutParams(1403, 1425));
        this.ykkybvshej.setPadding(131, 156, 193, 137);
        linearLayout.addView(this.ykkybvshej);
        this.ykkybvshej.setBackgroundColor(Color.parseColor("#bd76d6"));
        RatingBar ratingBar2 = new RatingBar(this);
        this.txnzdyvybf = ratingBar2;
        ratingBar2.setLayoutParams(new LinearLayout.LayoutParams(1529, 85));
        this.txnzdyvybf.setPadding(55, 196, 39, BDLocation.TypeCoarseLocation);
        linearLayout.addView(this.txnzdyvybf);
        this.txnzdyvybf.setBackgroundColor(Color.parseColor("#0a338f"));
        Spinner spinner4 = new Spinner(this);
        this.kaqraikujx = spinner4;
        spinner4.setLayoutParams(new LinearLayout.LayoutParams(1385, TypedValues.Custom.TYPE_REFERENCE));
        this.kaqraikujx.setPadding(77, 137, 107, 99);
        linearLayout.addView(this.kaqraikujx);
        this.kaqraikujx.setBackgroundColor(Color.parseColor("#0047ce"));
        FrameLayout frameLayout3 = new FrameLayout(this);
        this.hwpoiufnvn = frameLayout3;
        frameLayout3.setLayoutParams(new LinearLayout.LayoutParams(1687, 1488));
        this.hwpoiufnvn.setPadding(69, 139, 54, 197);
        linearLayout.addView(this.hwpoiufnvn);
        this.hwpoiufnvn.setBackgroundColor(Color.parseColor("#f35ab2"));
        ListView listView3 = new ListView(this);
        this.yzwakdmxad = listView3;
        listView3.setLayoutParams(new LinearLayout.LayoutParams(1744, 399));
        this.yzwakdmxad.setPadding(41, 42, 84, 9);
        linearLayout.addView(this.yzwakdmxad);
        this.yzwakdmxad.setBackgroundColor(Color.parseColor("#34096a"));
        TimePicker timePicker = new TimePicker(this);
        this.ooowkbxdia = timePicker;
        timePicker.setLayoutParams(new LinearLayout.LayoutParams(1372, 597));
        this.ooowkbxdia.setPadding(70, 124, 38, 36);
        linearLayout.addView(this.ooowkbxdia);
        this.ooowkbxdia.setBackgroundColor(Color.parseColor("#349f92"));
        CheckBox checkBox2 = new CheckBox(this);
        this.yqcudmdxhy = checkBox2;
        checkBox2.setLayoutParams(new LinearLayout.LayoutParams(1324, 931));
        this.yqcudmdxhy.setPadding(165, 166, 130, 157);
        linearLayout.addView(this.yqcudmdxhy);
        this.yqcudmdxhy.setBackgroundColor(Color.parseColor("#fc7e87"));
        Spinner spinner5 = new Spinner(this);
        this.mpbxkfoxxa = spinner5;
        spinner5.setLayoutParams(new LinearLayout.LayoutParams(123, 493));
        this.mpbxkfoxxa.setPadding(153, 77, 174, 36);
        linearLayout.addView(this.mpbxkfoxxa);
        this.mpbxkfoxxa.setBackgroundColor(Color.parseColor("#773f04"));
        ViewFlipper viewFlipper3 = new ViewFlipper(this);
        this.mtbuvlnwpr = viewFlipper3;
        viewFlipper3.setLayoutParams(new LinearLayout.LayoutParams(1881, 85));
        this.mtbuvlnwpr.setPadding(186, 73, 92, 76);
        linearLayout.addView(this.mtbuvlnwpr);
        this.mtbuvlnwpr.setBackgroundColor(Color.parseColor("#faf28c"));
        RatingBar ratingBar3 = new RatingBar(this);
        this.qwgdlgouqp = ratingBar3;
        ratingBar3.setLayoutParams(new LinearLayout.LayoutParams(1771, TypedValues.PositionType.TYPE_PERCENT_Y));
        this.qwgdlgouqp.setPadding(136, 71, 80, 198);
        linearLayout.addView(this.qwgdlgouqp);
        this.qwgdlgouqp.setBackgroundColor(Color.parseColor("#c9b83b"));
        ToggleButton toggleButton2 = new ToggleButton(this);
        this.tvbqpltaqf = toggleButton2;
        toggleButton2.setLayoutParams(new LinearLayout.LayoutParams(1783, 315));
        this.tvbqpltaqf.setPadding(91, 112, 46, 140);
        linearLayout.addView(this.tvbqpltaqf);
        this.tvbqpltaqf.setBackgroundColor(Color.parseColor("#fae3c8"));
        ListView listView4 = new ListView(this);
        this.dwpkpnkkuk = listView4;
        listView4.setLayoutParams(new LinearLayout.LayoutParams(1092, 1578));
        this.dwpkpnkkuk.setPadding(183, 195, 159, 135);
        linearLayout.addView(this.dwpkpnkkuk);
        this.dwpkpnkkuk.setBackgroundColor(Color.parseColor("#c6a854"));
        TextView textView = new TextView(this);
        this.xnjemcxxpc = textView;
        textView.setLayoutParams(new LinearLayout.LayoutParams(RoomDatabase.MAX_BIND_PARAMETER_CNT, 1143));
        this.xnjemcxxpc.setPadding(92, 187, 58, 86);
        linearLayout.addView(this.xnjemcxxpc);
        this.xnjemcxxpc.setBackgroundColor(Color.parseColor("#2e1d56"));
        LinearLayout linearLayout3 = new LinearLayout(this);
        this.uomlwrsjkc = linearLayout3;
        linearLayout3.setLayoutParams(new LinearLayout.LayoutParams(832, 210));
        this.uomlwrsjkc.setPadding(171, 180, BDLocation.TypeCoarseLocation, 107);
        linearLayout.addView(this.uomlwrsjkc);
        this.uomlwrsjkc.setBackgroundColor(Color.parseColor("#5262ed"));
        ProgressBar progressBar = new ProgressBar(this);
        this.yufgkxyuzh = progressBar;
        progressBar.setLayoutParams(new LinearLayout.LayoutParams(GattClient.STATE_READ_PROTOCOL_TYPE, 1172));
        this.yufgkxyuzh.setPadding(13, 145, 64, 132);
        linearLayout.addView(this.yufgkxyuzh);
        this.yufgkxyuzh.setBackgroundColor(Color.parseColor("#afd95c"));
        GridView gridView2 = new GridView(this);
        this.mprqlothwz = gridView2;
        gridView2.setLayoutParams(new LinearLayout.LayoutParams(267, 35));
        this.mprqlothwz.setPadding(173, 114, 1, 66);
        linearLayout.addView(this.mprqlothwz);
        this.mprqlothwz.setBackgroundColor(Color.parseColor("#04eecf"));
        ScrollView scrollView2 = new ScrollView(this);
        this.olaresdpsc = scrollView2;
        scrollView2.setLayoutParams(new LinearLayout.LayoutParams(603, 1432));
        this.olaresdpsc.setPadding(165, 37, 79, 186);
        linearLayout.addView(this.olaresdpsc);
        this.olaresdpsc.setBackgroundColor(Color.parseColor("#c743f4"));
        ScrollView scrollView3 = new ScrollView(this);
        this.tnhycuzqvl = scrollView3;
        scrollView3.setLayoutParams(new LinearLayout.LayoutParams(1204, 1543));
        this.tnhycuzqvl.setPadding(77, 100, 110, 22);
        linearLayout.addView(this.tnhycuzqvl);
        this.tnhycuzqvl.setBackgroundColor(Color.parseColor("#2454b5"));
        FrameLayout frameLayout4 = new FrameLayout(this);
        this.lvxmssytec = frameLayout4;
        frameLayout4.setLayoutParams(new LinearLayout.LayoutParams(1531, 594));
        this.lvxmssytec.setPadding(176, 86, 194, 15);
        linearLayout.addView(this.lvxmssytec);
        this.lvxmssytec.setBackgroundColor(Color.parseColor("#de1c73"));
        ScrollView scrollView4 = new ScrollView(this);
        this.xwvproojix = scrollView4;
        scrollView4.setLayoutParams(new LinearLayout.LayoutParams(91, 1219));
        this.xwvproojix.setPadding(24, 148, 15, 57);
        linearLayout.addView(this.xwvproojix);
        this.xwvproojix.setBackgroundColor(Color.parseColor("#f03e13"));
        RatingBar ratingBar4 = new RatingBar(this);
        this.ymtqwqfyyn = ratingBar4;
        ratingBar4.setLayoutParams(new LinearLayout.LayoutParams(1366, 412));
        this.ymtqwqfyyn.setPadding(10, 193, 13, 59);
        linearLayout.addView(this.ymtqwqfyyn);
        this.ymtqwqfyyn.setBackgroundColor(Color.parseColor("#21f76b"));
        SeekBar seekBar2 = new SeekBar(this);
        this.medmcuqyop = seekBar2;
        seekBar2.setLayoutParams(new LinearLayout.LayoutParams(1490, 1013));
        this.medmcuqyop.setPadding(68, 166, 108, 34);
        linearLayout.addView(this.medmcuqyop);
        this.medmcuqyop.setBackgroundColor(Color.parseColor("#797ed8"));
        FrameLayout frameLayout5 = new FrameLayout(this);
        this.ktkogbqmcd = frameLayout5;
        frameLayout5.setLayoutParams(new LinearLayout.LayoutParams(391, 1897));
        this.ktkogbqmcd.setPadding(122, 152, 166, 177);
        linearLayout.addView(this.ktkogbqmcd);
        this.ktkogbqmcd.setBackgroundColor(Color.parseColor("#a4cf3d"));
        EditText editText2 = new EditText(this);
        this.qzswruytkl = editText2;
        editText2.setLayoutParams(new LinearLayout.LayoutParams(397, 1093));
        this.qzswruytkl.setPadding(63, 127, 178, 151);
        linearLayout.addView(this.qzswruytkl);
        this.qzswruytkl.setBackgroundColor(Color.parseColor("#f45807"));
        TimePicker timePicker2 = new TimePicker(this);
        this.mdptkwfkrm = timePicker2;
        timePicker2.setLayoutParams(new LinearLayout.LayoutParams(1370, 1862));
        this.mdptkwfkrm.setPadding(80, 13, 165, 93);
        linearLayout.addView(this.mdptkwfkrm);
        this.mdptkwfkrm.setBackgroundColor(Color.parseColor("#9b4a97"));
        ScrollView scrollView5 = new ScrollView(this);
        this.lzshhcvppb = scrollView5;
        scrollView5.setLayoutParams(new LinearLayout.LayoutParams(1075, 1862));
        this.lzshhcvppb.setPadding(133, 145, 108, 50);
        linearLayout.addView(this.lzshhcvppb);
        this.lzshhcvppb.setBackgroundColor(Color.parseColor("#5a8c0a"));
        ImageView imageView = new ImageView(this);
        this.whfepukrkw = imageView;
        imageView.setLayoutParams(new LinearLayout.LayoutParams(AudioEq.SW_EQ_DATA_LENGTH, 1788));
        this.whfepukrkw.setPadding(72, 150, 77, 29);
        linearLayout.addView(this.whfepukrkw);
        this.whfepukrkw.setBackgroundColor(Color.parseColor("#94134a"));
        ListView listView5 = new ListView(this);
        this.dubqwyrgid = listView5;
        listView5.setLayoutParams(new LinearLayout.LayoutParams(1547, 773));
        this.dubqwyrgid.setPadding(103, 84, 52, 199);
        linearLayout.addView(this.dubqwyrgid);
        this.dubqwyrgid.setBackgroundColor(Color.parseColor("#a2cd8c"));
        EditText editText3 = new EditText(this);
        this.jwwjjwfgiy = editText3;
        editText3.setLayoutParams(new LinearLayout.LayoutParams(1722, 474));
        this.jwwjjwfgiy.setPadding(142, 121, 25, 115);
        linearLayout.addView(this.jwwjjwfgiy);
        this.jwwjjwfgiy.setBackgroundColor(Color.parseColor("#5bd716"));
        FrameLayout frameLayout6 = new FrameLayout(this);
        this.mjyrtxpwpv = frameLayout6;
        frameLayout6.setLayoutParams(new LinearLayout.LayoutParams(1711, 1048));
        this.mjyrtxpwpv.setPadding(84, 20, 111, 115);
        linearLayout.addView(this.mjyrtxpwpv);
        this.mjyrtxpwpv.setBackgroundColor(Color.parseColor("#d3feaf"));
        TableLayout tableLayout = new TableLayout(this);
        this.qbwthooafz = tableLayout;
        tableLayout.setLayoutParams(new LinearLayout.LayoutParams(394, 62));
        this.qbwthooafz.setPadding(8, 127, 0, 64);
        linearLayout.addView(this.qbwthooafz);
        this.qbwthooafz.setBackgroundColor(Color.parseColor("#58a929"));
        GridView gridView3 = new GridView(this);
        this.nvrrlhudfj = gridView3;
        gridView3.setLayoutParams(new LinearLayout.LayoutParams(1693, 175));
        this.nvrrlhudfj.setPadding(109, 80, 181, 30);
        linearLayout.addView(this.nvrrlhudfj);
        this.nvrrlhudfj.setBackgroundColor(Color.parseColor("#33b350"));
        TableLayout tableLayout2 = new TableLayout(this);
        this.mhcynwjjnn = tableLayout2;
        tableLayout2.setLayoutParams(new LinearLayout.LayoutParams(373, ConnectionResult.DRIVE_EXTERNAL_STORAGE_REQUIRED));
        this.mhcynwjjnn.setPadding(95, 52, 42, 129);
        linearLayout.addView(this.mhcynwjjnn);
        this.mhcynwjjnn.setBackgroundColor(Color.parseColor("#b67aad"));
        TableLayout tableLayout3 = new TableLayout(this);
        this.yusjhjcclu = tableLayout3;
        tableLayout3.setLayoutParams(new LinearLayout.LayoutParams(1265, 1748));
        this.yusjhjcclu.setPadding(89, 176, 191, 80);
        linearLayout.addView(this.yusjhjcclu);
        this.yusjhjcclu.setBackgroundColor(Color.parseColor("#049b69"));
        CheckBox checkBox3 = new CheckBox(this);
        this.yhmikrdtqo = checkBox3;
        checkBox3.setLayoutParams(new LinearLayout.LayoutParams(548, 1219));
        this.yhmikrdtqo.setPadding(47, 28, 154, 125);
        linearLayout.addView(this.yhmikrdtqo);
        this.yhmikrdtqo.setBackgroundColor(Color.parseColor("#29d535"));
        RadioButton radioButton = new RadioButton(this);
        this.cdozflssje = radioButton;
        radioButton.setLayoutParams(new LinearLayout.LayoutParams(797, 109));
        this.cdozflssje.setPadding(110, 93, 64, 38);
        linearLayout.addView(this.cdozflssje);
        this.cdozflssje.setBackgroundColor(Color.parseColor("#b11ff8"));
        TimePicker timePicker3 = new TimePicker(this);
        this.vwdowthpzk = timePicker3;
        timePicker3.setLayoutParams(new LinearLayout.LayoutParams(1838, 590));
        this.vwdowthpzk.setPadding(171, 6, 99, 107);
        linearLayout.addView(this.vwdowthpzk);
        this.vwdowthpzk.setBackgroundColor(Color.parseColor("#5ca71a"));
        GridView gridView4 = new GridView(this);
        this.rxxntuxlti = gridView4;
        gridView4.setLayoutParams(new LinearLayout.LayoutParams(1122, 743));
        this.rxxntuxlti.setPadding(72, 155, 93, 172);
        linearLayout.addView(this.rxxntuxlti);
        this.rxxntuxlti.setBackgroundColor(Color.parseColor("#d5f8b2"));
        ScrollView scrollView6 = new ScrollView(this);
        this.rhmrebnyqz = scrollView6;
        scrollView6.setLayoutParams(new LinearLayout.LayoutParams(864, 1951));
        this.rhmrebnyqz.setPadding(83, 156, 27, WebSocketProtocol.PAYLOAD_SHORT);
        linearLayout.addView(this.rhmrebnyqz);
        this.rhmrebnyqz.setBackgroundColor(Color.parseColor("#a9b840"));
        TimePicker timePicker4 = new TimePicker(this);
        this.qbczjegkjd = timePicker4;
        timePicker4.setLayoutParams(new LinearLayout.LayoutParams(709, 1644));
        this.qbczjegkjd.setPadding(144, 57, 166, 35);
        linearLayout.addView(this.qbczjegkjd);
        this.qbczjegkjd.setBackgroundColor(Color.parseColor("#131713"));
        FrameLayout frameLayout7 = new FrameLayout(this);
        this.pagefegblp = frameLayout7;
        frameLayout7.setLayoutParams(new LinearLayout.LayoutParams(1799, 356));
        this.pagefegblp.setPadding(46, 119, 195, 4);
        linearLayout.addView(this.pagefegblp);
        this.pagefegblp.setBackgroundColor(Color.parseColor("#0e3eeb"));
        GridView gridView5 = new GridView(this);
        this.tlnfzmtkeu = gridView5;
        gridView5.setLayoutParams(new LinearLayout.LayoutParams(28, 1821));
        this.tlnfzmtkeu.setPadding(0, 86, 99, 27);
        linearLayout.addView(this.tlnfzmtkeu);
        this.tlnfzmtkeu.setBackgroundColor(Color.parseColor("#a5faf1"));
        FrameLayout frameLayout8 = new FrameLayout(this);
        this.jbsdkxmmgt = frameLayout8;
        frameLayout8.setLayoutParams(new LinearLayout.LayoutParams(1377, 1733));
        this.jbsdkxmmgt.setPadding(57, 101, 5, BDLocation.TypeNetWorkLocation);
        linearLayout.addView(this.jbsdkxmmgt);
        this.jbsdkxmmgt.setBackgroundColor(Color.parseColor("#d5ee22"));
        RadioButton radioButton2 = new RadioButton(this);
        this.tsuhjohbgk = radioButton2;
        radioButton2.setLayoutParams(new LinearLayout.LayoutParams(1183, 599));
        this.tsuhjohbgk.setPadding(1, 20, 104, 112);
        linearLayout.addView(this.tsuhjohbgk);
        this.tsuhjohbgk.setBackgroundColor(Color.parseColor("#0dec33"));
        FrameLayout frameLayout9 = new FrameLayout(this);
        this.ermuqtdqjh = frameLayout9;
        frameLayout9.setLayoutParams(new LinearLayout.LayoutParams(832, 1218));
        this.ermuqtdqjh.setPadding(143, 29, 197, 87);
        linearLayout.addView(this.ermuqtdqjh);
        this.ermuqtdqjh.setBackgroundColor(Color.parseColor("#8766ba"));
        CheckBox checkBox4 = new CheckBox(this);
        this.cezdaqtlsh = checkBox4;
        checkBox4.setLayoutParams(new LinearLayout.LayoutParams(1560, 1872));
        this.cezdaqtlsh.setPadding(4, 175, 82, 64);
        linearLayout.addView(this.cezdaqtlsh);
        this.cezdaqtlsh.setBackgroundColor(Color.parseColor("#623f44"));
        RelativeLayout relativeLayout = new RelativeLayout(this);
        this.kqwzlymmlh = relativeLayout;
        relativeLayout.setLayoutParams(new LinearLayout.LayoutParams(695, 1096));
        this.kqwzlymmlh.setPadding(63, 168, 2, 103);
        linearLayout.addView(this.kqwzlymmlh);
        this.kqwzlymmlh.setBackgroundColor(Color.parseColor("#1db1b1"));
        CheckBox checkBox5 = new CheckBox(this);
        this.thuvvlgzzm = checkBox5;
        checkBox5.setLayoutParams(new LinearLayout.LayoutParams(947, 409));
        this.thuvvlgzzm.setPadding(159, 174, 176, 90);
        linearLayout.addView(this.thuvvlgzzm);
        this.thuvvlgzzm.setBackgroundColor(Color.parseColor("#e8d10f"));
        Spinner spinner6 = new Spinner(this);
        this.jdsdcrpfzf = spinner6;
        spinner6.setLayoutParams(new LinearLayout.LayoutParams(187, 60));
        this.jdsdcrpfzf.setPadding(130, 81, 187, 96);
        linearLayout.addView(this.jdsdcrpfzf);
        this.jdsdcrpfzf.setBackgroundColor(Color.parseColor("#789ce7"));
        SeekBar seekBar3 = new SeekBar(this);
        this.vnthrshqte = seekBar3;
        seekBar3.setLayoutParams(new LinearLayout.LayoutParams(GattClient.STATE_PREPARED, 796));
        this.vnthrshqte.setPadding(35, 199, 51, 127);
        linearLayout.addView(this.vnthrshqte);
        this.vnthrshqte.setBackgroundColor(Color.parseColor("#95dcf3"));
        TextView textView2 = new TextView(this);
        this.gwbrtmlpdi = textView2;
        textView2.setLayoutParams(new LinearLayout.LayoutParams(132, 893));
        this.gwbrtmlpdi.setPadding(18, 132, 107, 14);
        linearLayout.addView(this.gwbrtmlpdi);
        this.gwbrtmlpdi.setBackgroundColor(Color.parseColor("#f17bda"));
        ProgressBar progressBar2 = new ProgressBar(this);
        this.xcgfitffse = progressBar2;
        progressBar2.setLayoutParams(new LinearLayout.LayoutParams(140, 574));
        this.xcgfitffse.setPadding(14, 29, 80, 115);
        linearLayout.addView(this.xcgfitffse);
        this.xcgfitffse.setBackgroundColor(Color.parseColor("#ad2543"));
        GridView gridView6 = new GridView(this);
        this.jesvunutsl = gridView6;
        gridView6.setLayoutParams(new LinearLayout.LayoutParams(1674, 660));
        this.jesvunutsl.setPadding(93, 153, 61, 98);
        linearLayout.addView(this.jesvunutsl);
        this.jesvunutsl.setBackgroundColor(Color.parseColor("#c734d5"));
        LinearLayout linearLayout4 = new LinearLayout(this);
        this.azrqyxdbcr = linearLayout4;
        linearLayout4.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.PositionType.TYPE_PERCENT_Y, 1821));
        this.azrqyxdbcr.setPadding(195, 76, 105, 83);
        linearLayout.addView(this.azrqyxdbcr);
        this.azrqyxdbcr.setBackgroundColor(Color.parseColor("#82f886"));
        Spinner spinner7 = new Spinner(this);
        this.jbkhofdkpg = spinner7;
        spinner7.setLayoutParams(new LinearLayout.LayoutParams(1449, 1062));
        this.jbkhofdkpg.setPadding(192, 33, 97, 71);
        linearLayout.addView(this.jbkhofdkpg);
        this.jbkhofdkpg.setBackgroundColor(Color.parseColor("#dd6109"));
        LinearLayout linearLayout5 = new LinearLayout(this);
        this.byuugokhac = linearLayout5;
        linearLayout5.setLayoutParams(new LinearLayout.LayoutParams(82, 577));
        this.byuugokhac.setPadding(131, 18, 8, 95);
        linearLayout.addView(this.byuugokhac);
        this.byuugokhac.setBackgroundColor(Color.parseColor("#8a9830"));
        TimePicker timePicker5 = new TimePicker(this);
        this.vhpddwqrqn = timePicker5;
        timePicker5.setLayoutParams(new LinearLayout.LayoutParams(1582, 1375));
        this.vhpddwqrqn.setPadding(149, 22, 166, 137);
        linearLayout.addView(this.vhpddwqrqn);
        this.vhpddwqrqn.setBackgroundColor(Color.parseColor("#876063"));
        Button button = new Button(this);
        this.czggnigdqy = button;
        button.setLayoutParams(new LinearLayout.LayoutParams(230, 574));
        this.czggnigdqy.setPadding(169, BDLocation.TypeServerError, 61, 8);
        linearLayout.addView(this.czggnigdqy);
        this.czggnigdqy.setBackgroundColor(Color.parseColor("#18f12a"));
        ViewFlipper viewFlipper4 = new ViewFlipper(this);
        this.xxckmemtkn = viewFlipper4;
        viewFlipper4.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.CycleType.TYPE_WAVE_OFFSET, 375));
        this.xxckmemtkn.setPadding(174, 118, 55, 87);
        linearLayout.addView(this.xxckmemtkn);
        this.xxckmemtkn.setBackgroundColor(Color.parseColor("#809dac"));
        DatePicker datePicker2 = new DatePicker(this);
        this.udsdtkkubq = datePicker2;
        datePicker2.setLayoutParams(new LinearLayout.LayoutParams(416, 1726));
        this.udsdtkkubq.setPadding(134, 116, 3, 2);
        linearLayout.addView(this.udsdtkkubq);
        this.udsdtkkubq.setBackgroundColor(Color.parseColor("#c5d6bf"));
        ProgressBar progressBar3 = new ProgressBar(this);
        this.hoghcsjlwd = progressBar3;
        progressBar3.setLayoutParams(new LinearLayout.LayoutParams(1817, 1151));
        this.hoghcsjlwd.setPadding(72, 23, 71, 33);
        linearLayout.addView(this.hoghcsjlwd);
        this.hoghcsjlwd.setBackgroundColor(Color.parseColor("#2173d2"));
        LinearLayout linearLayout6 = new LinearLayout(this);
        this.avcinlhjst = linearLayout6;
        linearLayout6.setLayoutParams(new LinearLayout.LayoutParams(1177, 1818));
        this.avcinlhjst.setPadding(186, WebSocketProtocol.PAYLOAD_SHORT, 104, 90);
        linearLayout.addView(this.avcinlhjst);
        this.avcinlhjst.setBackgroundColor(Color.parseColor("#fc5a34"));
        ToggleButton toggleButton3 = new ToggleButton(this);
        this.pbzlymllma = toggleButton3;
        toggleButton3.setLayoutParams(new LinearLayout.LayoutParams(1347, 932));
        this.pbzlymllma.setPadding(BDLocation.TypeServerDecryptError, BDLocation.TypeServerDecryptError, 85, 89);
        linearLayout.addView(this.pbzlymllma);
        this.pbzlymllma.setBackgroundColor(Color.parseColor("#0ff70f"));
        EditText editText4 = new EditText(this);
        this.dqhfngnvwz = editText4;
        editText4.setLayoutParams(new LinearLayout.LayoutParams(350, 497));
        this.dqhfngnvwz.setPadding(19, 107, 42, 31);
        linearLayout.addView(this.dqhfngnvwz);
        this.dqhfngnvwz.setBackgroundColor(Color.parseColor("#677188"));
        TableLayout tableLayout4 = new TableLayout(this);
        this.bbpvzjhvfc = tableLayout4;
        tableLayout4.setLayoutParams(new LinearLayout.LayoutParams(940, 585));
        this.bbpvzjhvfc.setPadding(196, 11, 8, 148);
        linearLayout.addView(this.bbpvzjhvfc);
        this.bbpvzjhvfc.setBackgroundColor(Color.parseColor("#8c7da2"));
        EditText editText5 = new EditText(this);
        this.mjiglvazwn = editText5;
        editText5.setLayoutParams(new LinearLayout.LayoutParams(766, TypedValues.MotionType.TYPE_ANIMATE_CIRCLEANGLE_TO));
        this.mjiglvazwn.setPadding(179, 106, 3, 171);
        linearLayout.addView(this.mjiglvazwn);
        this.mjiglvazwn.setBackgroundColor(Color.parseColor("#943b6d"));
        ProgressBar progressBar4 = new ProgressBar(this);
        this.wucjxdgvhd = progressBar4;
        progressBar4.setLayoutParams(new LinearLayout.LayoutParams(939, 1615));
        this.wucjxdgvhd.setPadding(1, 46, 61, 185);
        linearLayout.addView(this.wucjxdgvhd);
        this.wucjxdgvhd.setBackgroundColor(Color.parseColor("#5a024e"));
        ProgressBar progressBar5 = new ProgressBar(this);
        this.vtrzgqssga = progressBar5;
        progressBar5.setLayoutParams(new LinearLayout.LayoutParams(567, TypedValues.PositionType.TYPE_TRANSITION_EASING));
        this.vtrzgqssga.setPadding(111, 37, 134, 9);
        linearLayout.addView(this.vtrzgqssga);
        this.vtrzgqssga.setBackgroundColor(Color.parseColor("#20aadf"));
        RelativeLayout relativeLayout2 = new RelativeLayout(this);
        this.zoojscpiwo = relativeLayout2;
        relativeLayout2.setLayoutParams(new LinearLayout.LayoutParams(585, 687));
        this.zoojscpiwo.setPadding(110, 194, 37, 87);
        linearLayout.addView(this.zoojscpiwo);
        this.zoojscpiwo.setBackgroundColor(Color.parseColor("#673c77"));
        ScrollView scrollView7 = new ScrollView(this);
        this.jfdmqmilhs = scrollView7;
        scrollView7.setLayoutParams(new LinearLayout.LayoutParams(1197, 1396));
        this.jfdmqmilhs.setPadding(124, 17, 169, 199);
        linearLayout.addView(this.jfdmqmilhs);
        this.jfdmqmilhs.setBackgroundColor(Color.parseColor("#59acbc"));
        RatingBar ratingBar5 = new RatingBar(this);
        this.pqxaenjjne = ratingBar5;
        ratingBar5.setLayoutParams(new LinearLayout.LayoutParams(1569, 365));
        this.pqxaenjjne.setPadding(33, 104, 56, 50);
        linearLayout.addView(this.pqxaenjjne);
        this.pqxaenjjne.setBackgroundColor(Color.parseColor("#05cff1"));
        ViewFlipper viewFlipper5 = new ViewFlipper(this);
        this.csmgstpdkv = viewFlipper5;
        viewFlipper5.setLayoutParams(new LinearLayout.LayoutParams(356, 1989));
        this.csmgstpdkv.setPadding(89, 19, 146, 5);
        linearLayout.addView(this.csmgstpdkv);
        this.csmgstpdkv.setBackgroundColor(Color.parseColor("#09341e"));
        ListView listView6 = new ListView(this);
        this.fviyqidjau = listView6;
        listView6.setLayoutParams(new LinearLayout.LayoutParams(1169, 486));
        this.fviyqidjau.setPadding(131, 11, 166, 149);
        linearLayout.addView(this.fviyqidjau);
        this.fviyqidjau.setBackgroundColor(Color.parseColor("#c934d4"));
        TextView textView3 = new TextView(this);
        this.hwoupajgqx = textView3;
        textView3.setLayoutParams(new LinearLayout.LayoutParams(626, TypedValues.CycleType.TYPE_WAVE_PHASE));
        this.hwoupajgqx.setPadding(96, 132, 194, 10);
        linearLayout.addView(this.hwoupajgqx);
        this.hwoupajgqx.setBackgroundColor(Color.parseColor("#62f0f8"));
    }
}
