package com.smartapp.b.idnfcrfmaw;

import android.app.Activity;
import android.graphics.Color;
import android.os.Bundle;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.CheckBox;
import android.widget.DatePicker;
import android.widget.EditText;
import android.widget.FrameLayout;
import android.widget.GridView;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ListView;
import android.widget.ProgressBar;
import android.widget.RadioButton;
import android.widget.RatingBar;
import android.widget.RelativeLayout;
import android.widget.ScrollView;
import android.widget.SeekBar;
import android.widget.Spinner;
import android.widget.Switch;
import android.widget.TableLayout;
import android.widget.TextView;
import android.widget.TimePicker;
import android.widget.ToggleButton;
import android.widget.ViewFlipper;
import androidx.constraintlayout.core.motion.utils.TypedValues;
import androidx.core.view.PointerIconCompat;
import com.baidu.location.BDLocation;
import com.google.android.gms.common.ConnectionResult;
import com.google.zxing.pdf417.PDF417Common;
import com.luck.picture.lib.config.PictureConfig;
import com.realsil.sdk.core.bluetooth.connection.legacy.BluetoothSpp;
import okhttp3.internal.ws.WebSocketProtocol;

/* loaded from: classes4.dex */
public class GwufmdugvflActivity extends Activity {
    DatePicker ahhdglajtp;
    ProgressBar ahlpozeazn;
    RatingBar akxhcuczbt;
    TextView amemugenbt;
    GridView avsffvwkiy;
    ViewFlipper bejferkxdf;
    LinearLayout bgdmvukbno;
    GridView cavvmbdwxa;
    RelativeLayout chwielgzqp;
    RatingBar cnesvwozyj;
    EditText cozrebgika;
    ImageView cphydmiqqq;
    ViewFlipper cpyxswtmys;
    RelativeLayout cugefodjtn;
    ImageView dljskaxvjh;
    EditText dszqrtelca;
    SeekBar ecrmsjnnem;
    ToggleButton egbfmhihkq;
    TextView ehwzfftfju;
    RelativeLayout ejcmksltza;
    SeekBar ejqzkrwhmh;
    CheckBox ekpqovtbzs;
    Switch eleereidhg;
    TextView epramrechk;
    Switch eqkxnydewn;
    ListView eucqdvduim;
    Switch evhrkwgdks;
    GridView fgsrlykzwj;
    ScrollView fiobyamnug;
    RelativeLayout ftjrtpfgap;
    EditText gdpynszmgi;
    EditText gfgnywyylq;
    ImageView gfjcrjmskv;
    TimePicker gmkkkavtdp;
    ScrollView gozlcixeke;
    GridView gwcmdgjlmg;
    RelativeLayout gyupyehewq;
    EditText hainwkopph;
    LinearLayout hjvqznjcxg;
    EditText hmnivoqeux;
    Switch hngnewotlo;
    RelativeLayout hokvbliwga;
    Spinner hqtmpuompe;
    ImageView hzfvmvlzoh;
    CheckBox icjshpgtra;
    EditText ijocdziipx;
    GridView ijxxpivxlz;
    ScrollView inmpnwfknd;
    CheckBox irhqxjbpzt;
    DatePicker irordbqbep;
    Switch isczodzxoc;
    RelativeLayout iuwmucemoq;
    RatingBar jsuhlrqsou;
    ViewFlipper jwctstlefh;
    SeekBar jwxdmvpkve;
    TextView keexfgqpqh;
    CheckBox kefgathnes;
    ToggleButton kfbhwwvffx;
    ToggleButton kluqauprfi;
    ListView kmjhgxhewu;
    TableLayout knlnxzhicc;
    ScrollView kymsraadpc;
    DatePicker lckazjnihd;
    LinearLayout ldswdrfnqm;
    GridView lhyaegcvdv;
    RelativeLayout lohzlbxzyy;
    TimePicker lpdwqrldxn;
    Button lpzjrghpyl;
    TimePicker lqnmwfrcds;
    GridView lvcbggkqlp;
    SeekBar lviwpbhmic;
    ScrollView marlrajkxy;
    CheckBox mbqmcqatrh;
    TimePicker mbwuhlcjwe;
    SeekBar mcftwviruw;
    GridView mckpascxdo;
    ScrollView melxsizawk;
    TimePicker mfsbgyeguu;
    Switch mlpwhmdyuc;
    ProgressBar mqmpqlfppm;
    EditText mrdmkyxrud;
    DatePicker msqfhtrwnv;
    EditText mtfaeesntn;
    FrameLayout nbhrgvhnyc;
    ListView niyhwtfoan;
    ImageView npdmiysnfb;
    TextView nsqpurerfc;
    RatingBar nunikehxpd;
    CheckBox nvzbeidpqz;
    RadioButton nzvdaoraad;
    Spinner ocjtgomhvn;
    LinearLayout odmcewitvw;
    RatingBar oearqlfzuw;
    RadioButton ogsigseveo;
    ListView ogstnutpqm;
    ProgressBar oluaulyblw;
    RadioButton owghemkcmv;
    FrameLayout oyzcpbhzxl;
    Switch ozhtgfhanb;
    Button pakqgotrqu;
    LinearLayout pifounkzmk;
    TimePicker pinmlizxmu;
    DatePicker ppsmlazval;
    GridView pqoutrwnwc;
    RelativeLayout puusjrjmfw;
    RadioButton qbkgoddooa;
    RelativeLayout qbrfgwnduf;
    ImageView qckylullcs;
    RadioButton qjyprnydar;
    Button qnlvydsoyc;
    TextView qnwwjihnfv;
    CheckBox qocaisiqyb;
    ScrollView qsuuqsbwwn;
    RelativeLayout rddjbqnygj;
    ListView ribbisswzj;
    Spinner rjwmlamjix;
    ListView rlbepldjqj;
    TimePicker rmdengomak;
    DatePicker ryhxiwpykk;
    RadioButton rzmqfcuyhw;
    TableLayout srfryoopjf;
    Spinner srsvibtvcb;
    ImageView srwflbamet;
    CheckBox sryjuxasxe;
    RelativeLayout syivynnjyo;
    Button syqgxifdsf;
    Button szixeyudaj;
    Switch sztpfwwxfm;
    Button tdmkcveblz;
    GridView tdyjruxobi;
    TimePicker tfbwkogbeo;
    ListView tgbqjeyyug;
    FrameLayout tklglzwhny;
    RelativeLayout tnkabbjjeg;
    CheckBox tolxpgtuyb;
    GridView trrdwbhtis;
    LinearLayout tsbcqrkfwm;
    LinearLayout tsikpdlyoo;
    RelativeLayout uetaxpghkm;
    DatePicker ufmxckglib;
    TextView ujjgcmrmvd;
    SeekBar unpemgknli;
    RadioButton uobfjkrovl;
    ScrollView uqecsxpmia;
    FrameLayout urkkenlvji;
    RelativeLayout utsxfhqrxe;
    CheckBox uvvoafmvth;
    TableLayout uwhagijqft;
    RatingBar vbxqoberxe;
    ListView vcuodsunxf;
    GridView vfrsylizbi;
    SeekBar vjaufrxvpk;
    ScrollView vplacyztcm;
    GridView vsskovvbfh;
    ProgressBar vtfjbvqgot;
    CheckBox vvfoxgqwez;
    ListView vvsfkkpfph;
    Switch wcgjymkokj;
    ProgressBar wdojofmkpw;
    ScrollView wjwefpphfn;
    TimePicker wlpkjurvpk;
    ProgressBar wwmazuovle;
    Switch wzytlorhxo;
    ScrollView xjjmpzqcdu;
    ListView xjmvfhvhqe;
    ScrollView xpframguou;
    CheckBox xqfbviovxf;
    ScrollView xsnsahbncn;
    Button xvkdizspsi;
    Spinner xvvpqwqoto;
    SeekBar xyhhwymqxx;
    SeekBar ycwihsajeb;
    GridView yegfpnknec;
    SeekBar yehqkkyaai;
    GridView yluuhwtfqo;
    EditText ymipibuccg;
    ImageView ynnnxegnvq;
    ScrollView yrkwbijcqs;
    EditText yspjxtxbdf;
    ProgressBar yuooebknzj;
    ToggleButton yupqztvlsm;
    RadioButton yvlqskqyuh;
    FrameLayout yyxutatvqj;
    TableLayout zclcojicgn;
    SeekBar zdkibznkvt;
    EditText zgdqgcixgf;
    FrameLayout zijmuswjtl;
    TextView zksquiizaq;
    Spinner zlbkmbmpeo;
    TimePicker zoolcnoghd;
    RadioButton zoyrwxhlkv;
    TableLayout zplmedmneh;
    ToggleButton zvyrncasma;
    LinearLayout zwplnuiimk;
    TimePicker zwzeaidslz;
    TimePicker zzmqcxxijn;

    @Override // android.app.Activity
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        LinearLayout linearLayout = new LinearLayout(this);
        setContentView(linearLayout);
        linearLayout.setLayoutParams(new ViewGroup.LayoutParams(-1, -1));
        linearLayout.setOrientation(1);
        linearLayout.setBackgroundColor(Color.parseColor("#dada04"));
        LinearLayout linearLayout2 = new LinearLayout(this);
        this.zwplnuiimk = linearLayout2;
        linearLayout2.setLayoutParams(new LinearLayout.LayoutParams(1990, 1803));
        this.zwplnuiimk.setPadding(BDLocation.TypeNetWorkLocation, 60, 87, 41);
        linearLayout.addView(this.zwplnuiimk);
        this.zwplnuiimk.setBackgroundColor(Color.parseColor("#0a213d"));
        ToggleButton toggleButton = new ToggleButton(this);
        this.egbfmhihkq = toggleButton;
        toggleButton.setLayoutParams(new LinearLayout.LayoutParams(1449, 1332));
        this.egbfmhihkq.setPadding(123, 54, 114, 57);
        linearLayout.addView(this.egbfmhihkq);
        this.egbfmhihkq.setBackgroundColor(Color.parseColor("#3847c3"));
        ScrollView scrollView = new ScrollView(this);
        this.yrkwbijcqs = scrollView;
        scrollView.setLayoutParams(new LinearLayout.LayoutParams(1311, 1920));
        this.yrkwbijcqs.setPadding(185, 122, 85, 0);
        linearLayout.addView(this.yrkwbijcqs);
        this.yrkwbijcqs.setBackgroundColor(Color.parseColor("#a839af"));
        SeekBar seekBar = new SeekBar(this);
        this.ycwihsajeb = seekBar;
        seekBar.setLayoutParams(new LinearLayout.LayoutParams(1882, 957));
        this.ycwihsajeb.setPadding(157, 119, 121, 178);
        linearLayout.addView(this.ycwihsajeb);
        this.ycwihsajeb.setBackgroundColor(Color.parseColor("#494409"));
        ProgressBar progressBar = new ProgressBar(this);
        this.ahlpozeazn = progressBar;
        progressBar.setLayoutParams(new LinearLayout.LayoutParams(1239, 742));
        this.ahlpozeazn.setPadding(122, 149, 144, 53);
        linearLayout.addView(this.ahlpozeazn);
        this.ahlpozeazn.setBackgroundColor(Color.parseColor("#9af3c8"));
        CheckBox checkBox = new CheckBox(this);
        this.xqfbviovxf = checkBox;
        checkBox.setLayoutParams(new LinearLayout.LayoutParams(151, 680));
        this.xqfbviovxf.setPadding(140, 21, 189, 39);
        linearLayout.addView(this.xqfbviovxf);
        this.xqfbviovxf.setBackgroundColor(Color.parseColor("#b15056"));
        RatingBar ratingBar = new RatingBar(this);
        this.akxhcuczbt = ratingBar;
        ratingBar.setLayoutParams(new LinearLayout.LayoutParams(722, 664));
        this.akxhcuczbt.setPadding(10, 99, 67, 140);
        linearLayout.addView(this.akxhcuczbt);
        this.akxhcuczbt.setBackgroundColor(Color.parseColor("#492c11"));
        ProgressBar progressBar2 = new ProgressBar(this);
        this.oluaulyblw = progressBar2;
        progressBar2.setLayoutParams(new LinearLayout.LayoutParams(1890, TypedValues.CycleType.TYPE_WAVE_PHASE));
        this.oluaulyblw.setPadding(BDLocation.TypeServerDecryptError, 198, 15, 37);
        linearLayout.addView(this.oluaulyblw);
        this.oluaulyblw.setBackground(new Rfzqcgztzai());
        TableLayout tableLayout = new TableLayout(this);
        this.uwhagijqft = tableLayout;
        tableLayout.setLayoutParams(new LinearLayout.LayoutParams(416, 404));
        this.uwhagijqft.setPadding(107, 44, 118, 187);
        linearLayout.addView(this.uwhagijqft);
        this.uwhagijqft.setBackgroundColor(Color.parseColor("#da2904"));
        ScrollView scrollView2 = new ScrollView(this);
        this.gozlcixeke = scrollView2;
        scrollView2.setLayoutParams(new LinearLayout.LayoutParams(1104, 1153));
        this.gozlcixeke.setPadding(117, 156, 181, 172);
        linearLayout.addView(this.gozlcixeke);
        this.gozlcixeke.setBackgroundColor(Color.parseColor("#d96e83"));
        EditText editText = new EditText(this);
        this.yspjxtxbdf = editText;
        editText.setLayoutParams(new LinearLayout.LayoutParams(971, 664));
        this.yspjxtxbdf.setPadding(29, 84, 158, 81);
        linearLayout.addView(this.yspjxtxbdf);
        this.yspjxtxbdf.setBackgroundColor(Color.parseColor("#3f7205"));
        LinearLayout linearLayout3 = new LinearLayout(this);
        this.ldswdrfnqm = linearLayout3;
        linearLayout3.setLayoutParams(new LinearLayout.LayoutParams(410, 1696));
        this.ldswdrfnqm.setPadding(140, 174, 112, 111);
        linearLayout.addView(this.ldswdrfnqm);
        this.ldswdrfnqm.setBackgroundColor(Color.parseColor("#6e5a96"));
        ImageView imageView = new ImageView(this);
        this.srwflbamet = imageView;
        imageView.setLayoutParams(new LinearLayout.LayoutParams(364, 243));
        this.srwflbamet.setPadding(187, 39, 38, BDLocation.TypeServerError);
        linearLayout.addView(this.srwflbamet);
        this.srwflbamet.setBackgroundColor(Color.parseColor("#0884b1"));
        Spinner spinner = new Spinner(this);
        this.zlbkmbmpeo = spinner;
        spinner.setLayoutParams(new LinearLayout.LayoutParams(1123, 311));
        this.zlbkmbmpeo.setPadding(156, 171, 180, 43);
        linearLayout.addView(this.zlbkmbmpeo);
        this.zlbkmbmpeo.setBackgroundColor(Color.parseColor("#67c030"));
        ImageView imageView2 = new ImageView(this);
        this.npdmiysnfb = imageView2;
        imageView2.setLayoutParams(new LinearLayout.LayoutParams(787, 804));
        this.npdmiysnfb.setPadding(97, 124, 111, 198);
        linearLayout.addView(this.npdmiysnfb);
        this.npdmiysnfb.setBackgroundColor(Color.parseColor("#72bedc"));
        ToggleButton toggleButton2 = new ToggleButton(this);
        this.yupqztvlsm = toggleButton2;
        toggleButton2.setLayoutParams(new LinearLayout.LayoutParams(1567, 1319));
        this.yupqztvlsm.setPadding(104, 1, 118, 140);
        linearLayout.addView(this.yupqztvlsm);
        this.yupqztvlsm.setBackgroundColor(Color.parseColor("#181df1"));
        SeekBar seekBar2 = new SeekBar(this);
        this.xyhhwymqxx = seekBar2;
        seekBar2.setLayoutParams(new LinearLayout.LayoutParams(217, 1677));
        this.xyhhwymqxx.setPadding(80, 36, 137, 66);
        linearLayout.addView(this.xyhhwymqxx);
        this.xyhhwymqxx.setBackgroundColor(Color.parseColor("#489340"));
        ScrollView scrollView3 = new ScrollView(this);
        this.kymsraadpc = scrollView3;
        scrollView3.setLayoutParams(new LinearLayout.LayoutParams(1582, 899));
        this.kymsraadpc.setPadding(101, 117, 148, 81);
        linearLayout.addView(this.kymsraadpc);
        this.kymsraadpc.setBackgroundColor(Color.parseColor("#d7b0ec"));
        Spinner spinner2 = new Spinner(this);
        this.ocjtgomhvn = spinner2;
        spinner2.setLayoutParams(new LinearLayout.LayoutParams(885, TypedValues.TransitionType.TYPE_INTERPOLATOR));
        this.ocjtgomhvn.setPadding(131, 3, 183, 115);
        linearLayout.addView(this.ocjtgomhvn);
        this.ocjtgomhvn.setBackgroundColor(Color.parseColor("#ef851a"));
        ListView listView = new ListView(this);
        this.kmjhgxhewu = listView;
        listView.setLayoutParams(new LinearLayout.LayoutParams(1467, 1423));
        this.kmjhgxhewu.setPadding(153, 25, 109, 96);
        linearLayout.addView(this.kmjhgxhewu);
        this.kmjhgxhewu.setBackgroundColor(Color.parseColor("#26cf16"));
        RelativeLayout relativeLayout = new RelativeLayout(this);
        this.puusjrjmfw = relativeLayout;
        relativeLayout.setLayoutParams(new LinearLayout.LayoutParams(979, 1399));
        this.puusjrjmfw.setPadding(60, 6, 64, 90);
        linearLayout.addView(this.puusjrjmfw);
        this.puusjrjmfw.setBackgroundColor(Color.parseColor("#463776"));
        GridView gridView = new GridView(this);
        this.gwcmdgjlmg = gridView;
        gridView.setLayoutParams(new LinearLayout.LayoutParams(631, 1762));
        this.gwcmdgjlmg.setPadding(38, 69, 14, 11);
        linearLayout.addView(this.gwcmdgjlmg);
        this.gwcmdgjlmg.setBackgroundColor(Color.parseColor("#7ad3ac"));
        EditText editText2 = new EditText(this);
        this.ymipibuccg = editText2;
        editText2.setLayoutParams(new LinearLayout.LayoutParams(1037, 806));
        this.ymipibuccg.setPadding(130, 187, 98, 25);
        linearLayout.addView(this.ymipibuccg);
        this.ymipibuccg.setBackgroundColor(Color.parseColor("#a2044e"));
        RelativeLayout relativeLayout2 = new RelativeLayout(this);
        this.uetaxpghkm = relativeLayout2;
        relativeLayout2.setLayoutParams(new LinearLayout.LayoutParams(BluetoothSpp.STATE_DISCONNECTING, 1412));
        this.uetaxpghkm.setPadding(78, 40, 74, 103);
        linearLayout.addView(this.uetaxpghkm);
        this.uetaxpghkm.setBackgroundColor(Color.parseColor("#7b7c77"));
        RadioButton radioButton = new RadioButton(this);
        this.uobfjkrovl = radioButton;
        radioButton.setLayoutParams(new LinearLayout.LayoutParams(1285, 360));
        this.uobfjkrovl.setPadding(165, 125, 192, 100);
        linearLayout.addView(this.uobfjkrovl);
        this.uobfjkrovl.setBackgroundColor(Color.parseColor("#cf18d3"));
        TimePicker timePicker = new TimePicker(this);
        this.lqnmwfrcds = timePicker;
        timePicker.setLayoutParams(new LinearLayout.LayoutParams(1279, 0));
        this.lqnmwfrcds.setPadding(38, 196, 79, 81);
        linearLayout.addView(this.lqnmwfrcds);
        this.lqnmwfrcds.setBackgroundColor(Color.parseColor("#469aee"));
        SeekBar seekBar3 = new SeekBar(this);
        this.lviwpbhmic = seekBar3;
        seekBar3.setLayoutParams(new LinearLayout.LayoutParams(1128, 1863));
        this.lviwpbhmic.setPadding(134, 182, 196, 42);
        linearLayout.addView(this.lviwpbhmic);
        this.lviwpbhmic.setBackgroundColor(Color.parseColor("#2f33b0"));
        RelativeLayout relativeLayout3 = new RelativeLayout(this);
        this.hokvbliwga = relativeLayout3;
        relativeLayout3.setLayoutParams(new LinearLayout.LayoutParams(996, 1812));
        this.hokvbliwga.setPadding(135, 86, 183, 64);
        linearLayout.addView(this.hokvbliwga);
        this.hokvbliwga.setBackgroundColor(Color.parseColor("#7754b0"));
        FrameLayout frameLayout = new FrameLayout(this);
        this.nbhrgvhnyc = frameLayout;
        frameLayout.setLayoutParams(new LinearLayout.LayoutParams(1851, 1219));
        this.nbhrgvhnyc.setPadding(98, 3, 21, 5);
        linearLayout.addView(this.nbhrgvhnyc);
        this.nbhrgvhnyc.setBackgroundColor(Color.parseColor("#46288a"));
        EditText editText3 = new EditText(this);
        this.gfgnywyylq = editText3;
        editText3.setLayoutParams(new LinearLayout.LayoutParams(1355, 1133));
        this.gfgnywyylq.setPadding(151, 76, 170, 118);
        linearLayout.addView(this.gfgnywyylq);
        this.gfgnywyylq.setBackgroundColor(Color.parseColor("#0a7f58"));
        CheckBox checkBox2 = new CheckBox(this);
        this.tolxpgtuyb = checkBox2;
        checkBox2.setLayoutParams(new LinearLayout.LayoutParams(BDLocation.TypeCoarseLocation, 1451));
        this.tolxpgtuyb.setPadding(95, 4, 176, 143);
        linearLayout.addView(this.tolxpgtuyb);
        this.tolxpgtuyb.setBackgroundColor(Color.parseColor("#6cb3b1"));
        DatePicker datePicker = new DatePicker(this);
        this.msqfhtrwnv = datePicker;
        datePicker.setLayoutParams(new LinearLayout.LayoutParams(1769, 1388));
        this.msqfhtrwnv.setPadding(3, 166, 135, 15);
        linearLayout.addView(this.msqfhtrwnv);
        this.msqfhtrwnv.setBackgroundColor(Color.parseColor("#40c5b3"));
        ListView listView2 = new ListView(this);
        this.niyhwtfoan = listView2;
        listView2.setLayoutParams(new LinearLayout.LayoutParams(1984, 1040));
        this.niyhwtfoan.setPadding(116, 50, 65, 35);
        linearLayout.addView(this.niyhwtfoan);
        this.niyhwtfoan.setBackgroundColor(Color.parseColor("#df51d3"));
        TextView textView = new TextView(this);
        this.epramrechk = textView;
        textView.setLayoutParams(new LinearLayout.LayoutParams(PointerIconCompat.TYPE_GRABBING, 597));
        this.epramrechk.setPadding(79, 189, 59, 0);
        linearLayout.addView(this.epramrechk);
        this.epramrechk.setBackgroundColor(Color.parseColor("#bf5e0c"));
        ToggleButton toggleButton3 = new ToggleButton(this);
        this.zvyrncasma = toggleButton3;
        toggleButton3.setLayoutParams(new LinearLayout.LayoutParams(1521, 918));
        this.zvyrncasma.setPadding(163, 64, 58, 59);
        linearLayout.addView(this.zvyrncasma);
        this.zvyrncasma.setBackgroundColor(Color.parseColor("#7bee9e"));
        EditText editText4 = new EditText(this);
        this.mrdmkyxrud = editText4;
        editText4.setLayoutParams(new LinearLayout.LayoutParams(1154, 1579));
        this.mrdmkyxrud.setPadding(BDLocation.TypeServerDecryptError, 88, 151, 26);
        linearLayout.addView(this.mrdmkyxrud);
        this.mrdmkyxrud.setBackgroundColor(Color.parseColor("#2461cf"));
        Button button = new Button(this);
        this.qnlvydsoyc = button;
        button.setLayoutParams(new LinearLayout.LayoutParams(192, 19));
        this.qnlvydsoyc.setPadding(113, 124, 16, 116);
        linearLayout.addView(this.qnlvydsoyc);
        this.qnlvydsoyc.setBackgroundColor(Color.parseColor("#9b4550"));
        LinearLayout linearLayout4 = new LinearLayout(this);
        this.bgdmvukbno = linearLayout4;
        linearLayout4.setLayoutParams(new LinearLayout.LayoutParams(635, 1029));
        this.bgdmvukbno.setPadding(85, 27, 6, 197);
        linearLayout.addView(this.bgdmvukbno);
        this.bgdmvukbno.setBackgroundColor(Color.parseColor("#317b86"));
        ScrollView scrollView4 = new ScrollView(this);
        this.inmpnwfknd = scrollView4;
        scrollView4.setLayoutParams(new LinearLayout.LayoutParams(1926, 1566));
        this.inmpnwfknd.setPadding(27, 163, 140, 4);
        linearLayout.addView(this.inmpnwfknd);
        this.inmpnwfknd.setBackgroundColor(Color.parseColor("#acb00d"));
        EditText editText5 = new EditText(this);
        this.mtfaeesntn = editText5;
        editText5.setLayoutParams(new LinearLayout.LayoutParams(628, 1565));
        this.mtfaeesntn.setPadding(131, 14, 154, 47);
        linearLayout.addView(this.mtfaeesntn);
        this.mtfaeesntn.setBackgroundColor(Color.parseColor("#82ee70"));
        RatingBar ratingBar2 = new RatingBar(this);
        this.oearqlfzuw = ratingBar2;
        ratingBar2.setLayoutParams(new LinearLayout.LayoutParams(1573, 1585));
        this.oearqlfzuw.setPadding(74, 8, 71, 117);
        linearLayout.addView(this.oearqlfzuw);
        this.oearqlfzuw.setBackgroundColor(Color.parseColor("#3cba91"));
        SeekBar seekBar4 = new SeekBar(this);
        this.jwxdmvpkve = seekBar4;
        seekBar4.setLayoutParams(new LinearLayout.LayoutParams(1814, 1068));
        this.jwxdmvpkve.setPadding(129, 149, 156, 83);
        linearLayout.addView(this.jwxdmvpkve);
        this.jwxdmvpkve.setBackgroundColor(Color.parseColor("#cf386f"));
        RadioButton radioButton2 = new RadioButton(this);
        this.owghemkcmv = radioButton2;
        radioButton2.setLayoutParams(new LinearLayout.LayoutParams(1195, 1257));
        this.owghemkcmv.setPadding(38, 119, 131, 192);
        linearLayout.addView(this.owghemkcmv);
        this.owghemkcmv.setBackgroundColor(Color.parseColor("#003d8c"));
        ScrollView scrollView5 = new ScrollView(this);
        this.wjwefpphfn = scrollView5;
        scrollView5.setLayoutParams(new LinearLayout.LayoutParams(1138, 1616));
        this.wjwefpphfn.setPadding(158, 115, 124, 11);
        linearLayout.addView(this.wjwefpphfn);
        this.wjwefpphfn.setBackgroundColor(Color.parseColor("#973dc8"));
        ListView listView3 = new ListView(this);
        this.xjmvfhvhqe = listView3;
        listView3.setLayoutParams(new LinearLayout.LayoutParams(1613, 33));
        this.xjmvfhvhqe.setPadding(189, 155, 47, 132);
        linearLayout.addView(this.xjmvfhvhqe);
        this.xjmvfhvhqe.setBackgroundColor(Color.parseColor("#8ffc67"));
        GridView gridView2 = new GridView(this);
        this.yluuhwtfqo = gridView2;
        gridView2.setLayoutParams(new LinearLayout.LayoutParams(1139, 1799));
        this.yluuhwtfqo.setPadding(123, 142, 59, 159);
        linearLayout.addView(this.yluuhwtfqo);
        this.yluuhwtfqo.setBackgroundColor(Color.parseColor("#616277"));
        GridView gridView3 = new GridView(this);
        this.vfrsylizbi = gridView3;
        gridView3.setLayoutParams(new LinearLayout.LayoutParams(1164, 523));
        this.vfrsylizbi.setPadding(PictureConfig.CHOOSE_REQUEST, 68, BDLocation.TypeServerDecryptError, 20);
        linearLayout.addView(this.vfrsylizbi);
        this.vfrsylizbi.setBackgroundColor(Color.parseColor("#df5f03"));
        Switch r2 = new Switch(this);
        this.evhrkwgdks = r2;
        r2.setLayoutParams(new LinearLayout.LayoutParams(735, 690));
        this.evhrkwgdks.setPadding(99, 63, 23, 35);
        linearLayout.addView(this.evhrkwgdks);
        this.evhrkwgdks.setBackgroundColor(Color.parseColor("#fd922a"));
        GridView gridView4 = new GridView(this);
        this.tdyjruxobi = gridView4;
        gridView4.setLayoutParams(new LinearLayout.LayoutParams(657, 1624));
        this.tdyjruxobi.setPadding(11, 155, 54, 37);
        linearLayout.addView(this.tdyjruxobi);
        this.tdyjruxobi.setBackgroundColor(Color.parseColor("#67efd8"));
        TextView textView2 = new TextView(this);
        this.nsqpurerfc = textView2;
        textView2.setLayoutParams(new LinearLayout.LayoutParams(1413, 1011));
        this.nsqpurerfc.setPadding(138, 175, 166, 150);
        linearLayout.addView(this.nsqpurerfc);
        this.nsqpurerfc.setBackgroundColor(Color.parseColor("#ca035d"));
        Switch r22 = new Switch(this);
        this.eqkxnydewn = r22;
        r22.setLayoutParams(new LinearLayout.LayoutParams(227, 1564));
        this.eqkxnydewn.setPadding(163, 37, 157, 86);
        linearLayout.addView(this.eqkxnydewn);
        this.eqkxnydewn.setBackgroundColor(Color.parseColor("#80d59f"));
        TextView textView3 = new TextView(this);
        this.ehwzfftfju = textView3;
        textView3.setLayoutParams(new LinearLayout.LayoutParams(798, 1151));
        this.ehwzfftfju.setPadding(32, 195, 112, 6);
        linearLayout.addView(this.ehwzfftfju);
        this.ehwzfftfju.setBackgroundColor(Color.parseColor("#fee40c"));
        RatingBar ratingBar3 = new RatingBar(this);
        this.vbxqoberxe = ratingBar3;
        ratingBar3.setLayoutParams(new LinearLayout.LayoutParams(623, 1660));
        this.vbxqoberxe.setPadding(42, 5, 141, 159);
        linearLayout.addView(this.vbxqoberxe);
        this.vbxqoberxe.setBackgroundColor(Color.parseColor("#4076a3"));
        RelativeLayout relativeLayout4 = new RelativeLayout(this);
        this.chwielgzqp = relativeLayout4;
        relativeLayout4.setLayoutParams(new LinearLayout.LayoutParams(671, 157));
        this.chwielgzqp.setPadding(174, 66, 96, 150);
        linearLayout.addView(this.chwielgzqp);
        this.chwielgzqp.setBackgroundColor(Color.parseColor("#053dcd"));
        ProgressBar progressBar3 = new ProgressBar(this);
        this.wdojofmkpw = progressBar3;
        progressBar3.setLayoutParams(new LinearLayout.LayoutParams(1885, 1584));
        this.wdojofmkpw.setPadding(108, 98, 110, 147);
        linearLayout.addView(this.wdojofmkpw);
        this.wdojofmkpw.setBackgroundColor(Color.parseColor("#7f7bd4"));
        Button button2 = new Button(this);
        this.tdmkcveblz = button2;
        button2.setLayoutParams(new LinearLayout.LayoutParams(1636, 998));
        this.tdmkcveblz.setPadding(158, 146, 122, 96);
        linearLayout.addView(this.tdmkcveblz);
        this.tdmkcveblz.setBackgroundColor(Color.parseColor("#759ea4"));
        SeekBar seekBar5 = new SeekBar(this);
        this.ejqzkrwhmh = seekBar5;
        seekBar5.setLayoutParams(new LinearLayout.LayoutParams(1456, 1617));
        this.ejqzkrwhmh.setPadding(147, 15, 114, 159);
        linearLayout.addView(this.ejqzkrwhmh);
        this.ejqzkrwhmh.setBackgroundColor(Color.parseColor("#26f380"));
        GridView gridView5 = new GridView(this);
        this.yegfpnknec = gridView5;
        gridView5.setLayoutParams(new LinearLayout.LayoutParams(742, 580));
        this.yegfpnknec.setPadding(38, 79, 108, 100);
        linearLayout.addView(this.yegfpnknec);
        this.yegfpnknec.setBackgroundColor(Color.parseColor("#5daffb"));
        FrameLayout frameLayout2 = new FrameLayout(this);
        this.urkkenlvji = frameLayout2;
        frameLayout2.setLayoutParams(new LinearLayout.LayoutParams(1381, 1132));
        this.urkkenlvji.setPadding(174, 14, 123, 153);
        linearLayout.addView(this.urkkenlvji);
        this.urkkenlvji.setBackgroundColor(Color.parseColor("#523510"));
        GridView gridView6 = new GridView(this);
        this.lvcbggkqlp = gridView6;
        gridView6.setLayoutParams(new LinearLayout.LayoutParams(1812, 532));
        this.lvcbggkqlp.setPadding(92, 101, 128, 40);
        linearLayout.addView(this.lvcbggkqlp);
        this.lvcbggkqlp.setBackgroundColor(Color.parseColor("#d159e8"));
        RatingBar ratingBar4 = new RatingBar(this);
        this.jsuhlrqsou = ratingBar4;
        ratingBar4.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.MotionType.TYPE_POLAR_RELATIVETO, 670));
        this.jsuhlrqsou.setPadding(148, 125, 135, 66);
        linearLayout.addView(this.jsuhlrqsou);
        this.jsuhlrqsou.setBackgroundColor(Color.parseColor("#b86f82"));
        RatingBar ratingBar5 = new RatingBar(this);
        this.nunikehxpd = ratingBar5;
        ratingBar5.setLayoutParams(new LinearLayout.LayoutParams(444, 1733));
        this.nunikehxpd.setPadding(25, 186, 127, 182);
        linearLayout.addView(this.nunikehxpd);
        this.nunikehxpd.setBackgroundColor(Color.parseColor("#bdd642"));
        RelativeLayout relativeLayout5 = new RelativeLayout(this);
        this.syivynnjyo = relativeLayout5;
        relativeLayout5.setLayoutParams(new LinearLayout.LayoutParams(134, 1174));
        this.syivynnjyo.setPadding(97, 43, 69, 197);
        linearLayout.addView(this.syivynnjyo);
        this.syivynnjyo.setBackgroundColor(Color.parseColor("#72ec2d"));
        FrameLayout frameLayout3 = new FrameLayout(this);
        this.oyzcpbhzxl = frameLayout3;
        frameLayout3.setLayoutParams(new LinearLayout.LayoutParams(753, 1319));
        this.oyzcpbhzxl.setPadding(25, 61, 158, 130);
        linearLayout.addView(this.oyzcpbhzxl);
        this.oyzcpbhzxl.setBackgroundColor(Color.parseColor("#a25991"));
        Switch r23 = new Switch(this);
        this.mlpwhmdyuc = r23;
        r23.setLayoutParams(new LinearLayout.LayoutParams(1453, 231));
        this.mlpwhmdyuc.setPadding(133, 192, 135, 175);
        linearLayout.addView(this.mlpwhmdyuc);
        this.mlpwhmdyuc.setBackgroundColor(Color.parseColor("#c65b5b"));
        ImageView imageView3 = new ImageView(this);
        this.hzfvmvlzoh = imageView3;
        imageView3.setLayoutParams(new LinearLayout.LayoutParams(1269, 1309));
        this.hzfvmvlzoh.setPadding(184, 66, 91, 114);
        linearLayout.addView(this.hzfvmvlzoh);
        this.hzfvmvlzoh.setBackgroundColor(Color.parseColor("#53972a"));
        DatePicker datePicker2 = new DatePicker(this);
        this.ppsmlazval = datePicker2;
        datePicker2.setLayoutParams(new LinearLayout.LayoutParams(732, 1716));
        this.ppsmlazval.setPadding(59, 8, 9, 197);
        linearLayout.addView(this.ppsmlazval);
        this.ppsmlazval.setBackgroundColor(Color.parseColor("#85eda6"));
        ScrollView scrollView6 = new ScrollView(this);
        this.uqecsxpmia = scrollView6;
        scrollView6.setLayoutParams(new LinearLayout.LayoutParams(1535, 795));
        this.uqecsxpmia.setPadding(5, 116, 31, 100);
        linearLayout.addView(this.uqecsxpmia);
        this.uqecsxpmia.setBackgroundColor(Color.parseColor("#63c453"));
        Switch r24 = new Switch(this);
        this.eleereidhg = r24;
        r24.setLayoutParams(new LinearLayout.LayoutParams(1008, 1171));
        this.eleereidhg.setPadding(159, 81, 127, 65);
        linearLayout.addView(this.eleereidhg);
        this.eleereidhg.setBackgroundColor(Color.parseColor("#8cfd64"));
        FrameLayout frameLayout4 = new FrameLayout(this);
        this.zijmuswjtl = frameLayout4;
        frameLayout4.setLayoutParams(new LinearLayout.LayoutParams(1988, 1593));
        this.zijmuswjtl.setPadding(65, 146, 149, 100);
        linearLayout.addView(this.zijmuswjtl);
        this.zijmuswjtl.setBackgroundColor(Color.parseColor("#c9d8bc"));
        CheckBox checkBox3 = new CheckBox(this);
        this.vvfoxgqwez = checkBox3;
        checkBox3.setLayoutParams(new LinearLayout.LayoutParams(339, 748));
        this.vvfoxgqwez.setPadding(189, 185, 113, 38);
        linearLayout.addView(this.vvfoxgqwez);
        this.vvfoxgqwez.setBackgroundColor(Color.parseColor("#695513"));
        EditText editText6 = new EditText(this);
        this.zgdqgcixgf = editText6;
        editText6.setLayoutParams(new LinearLayout.LayoutParams(146, 655));
        this.zgdqgcixgf.setPadding(191, 123, BDLocation.TypeCoarseLocation, 76);
        linearLayout.addView(this.zgdqgcixgf);
        this.zgdqgcixgf.setBackgroundColor(Color.parseColor("#125b3d"));
        ListView listView4 = new ListView(this);
        this.tgbqjeyyug = listView4;
        listView4.setLayoutParams(new LinearLayout.LayoutParams(1333, 1959));
        this.tgbqjeyyug.setPadding(47, BDLocation.TypeNetWorkLocation, 50, 192);
        linearLayout.addView(this.tgbqjeyyug);
        this.tgbqjeyyug.setBackgroundColor(Color.parseColor("#2559e4"));
        SeekBar seekBar6 = new SeekBar(this);
        this.mcftwviruw = seekBar6;
        seekBar6.setLayoutParams(new LinearLayout.LayoutParams(1518, 8));
        this.mcftwviruw.setPadding(76, 99, 39, 83);
        linearLayout.addView(this.mcftwviruw);
        this.mcftwviruw.setBackgroundColor(Color.parseColor("#b0399c"));
        Switch r25 = new Switch(this);
        this.wzytlorhxo = r25;
        r25.setLayoutParams(new LinearLayout.LayoutParams(1701, 1762));
        this.wzytlorhxo.setPadding(14, 38, 91, 182);
        linearLayout.addView(this.wzytlorhxo);
        this.wzytlorhxo.setBackgroundColor(Color.parseColor("#918881"));
        RelativeLayout relativeLayout6 = new RelativeLayout(this);
        this.lohzlbxzyy = relativeLayout6;
        relativeLayout6.setLayoutParams(new LinearLayout.LayoutParams(299, 1617));
        this.lohzlbxzyy.setPadding(31, 68, 138, 71);
        linearLayout.addView(this.lohzlbxzyy);
        this.lohzlbxzyy.setBackgroundColor(Color.parseColor("#833b19"));
        DatePicker datePicker3 = new DatePicker(this);
        this.irordbqbep = datePicker3;
        datePicker3.setLayoutParams(new LinearLayout.LayoutParams(776, 952));
        this.irordbqbep.setPadding(190, 171, 74, 65);
        linearLayout.addView(this.irordbqbep);
        this.irordbqbep.setBackgroundColor(Color.parseColor("#a00f07"));
        ViewFlipper viewFlipper = new ViewFlipper(this);
        this.cpyxswtmys = viewFlipper;
        viewFlipper.setLayoutParams(new LinearLayout.LayoutParams(869, 231));
        this.cpyxswtmys.setPadding(49, 166, 109, 19);
        linearLayout.addView(this.cpyxswtmys);
        this.cpyxswtmys.setBackgroundColor(Color.parseColor("#51ca12"));
        Spinner spinner3 = new Spinner(this);
        this.rjwmlamjix = spinner3;
        spinner3.setLayoutParams(new LinearLayout.LayoutParams(1919, 1515));
        this.rjwmlamjix.setPadding(45, 184, 168, 27);
        linearLayout.addView(this.rjwmlamjix);
        this.rjwmlamjix.setBackgroundColor(Color.parseColor("#8e8a7a"));
        EditText editText7 = new EditText(this);
        this.dszqrtelca = editText7;
        editText7.setLayoutParams(new LinearLayout.LayoutParams(1473, 1932));
        this.dszqrtelca.setPadding(12, 73, 147, 3);
        linearLayout.addView(this.dszqrtelca);
        this.dszqrtelca.setBackgroundColor(Color.parseColor("#486b40"));
        TimePicker timePicker2 = new TimePicker(this);
        this.mbwuhlcjwe = timePicker2;
        timePicker2.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.CycleType.TYPE_EASING, ConnectionResult.DRIVE_EXTERNAL_STORAGE_REQUIRED));
        this.mbwuhlcjwe.setPadding(116, 191, 53, 104);
        linearLayout.addView(this.mbwuhlcjwe);
        this.mbwuhlcjwe.setBackgroundColor(Color.parseColor("#8ea13b"));
        ImageView imageView4 = new ImageView(this);
        this.dljskaxvjh = imageView4;
        imageView4.setLayoutParams(new LinearLayout.LayoutParams(1245, 1907));
        this.dljskaxvjh.setPadding(38, 102, 195, 35);
        linearLayout.addView(this.dljskaxvjh);
        this.dljskaxvjh.setBackgroundColor(Color.parseColor("#8faa07"));
        TimePicker timePicker3 = new TimePicker(this);
        this.rmdengomak = timePicker3;
        timePicker3.setLayoutParams(new LinearLayout.LayoutParams(1372, 591));
        this.rmdengomak.setPadding(139, 35, 157, 41);
        linearLayout.addView(this.rmdengomak);
        this.rmdengomak.setBackgroundColor(Color.parseColor("#a6bc32"));
        SeekBar seekBar7 = new SeekBar(this);
        this.yehqkkyaai = seekBar7;
        seekBar7.setLayoutParams(new LinearLayout.LayoutParams(1157, 1824));
        this.yehqkkyaai.setPadding(198, BDLocation.TypeServerDecryptError, 85, 125);
        linearLayout.addView(this.yehqkkyaai);
        this.yehqkkyaai.setBackgroundColor(Color.parseColor("#3647be"));
        RelativeLayout relativeLayout7 = new RelativeLayout(this);
        this.gyupyehewq = relativeLayout7;
        relativeLayout7.setLayoutParams(new LinearLayout.LayoutParams(933, 329));
        this.gyupyehewq.setPadding(47, 80, 197, 76);
        linearLayout.addView(this.gyupyehewq);
        this.gyupyehewq.setBackgroundColor(Color.parseColor("#2597a9"));
        ProgressBar progressBar4 = new ProgressBar(this);
        this.wwmazuovle = progressBar4;
        progressBar4.setLayoutParams(new LinearLayout.LayoutParams(1866, 1290));
        this.wwmazuovle.setPadding(77, 19, 20, 40);
        linearLayout.addView(this.wwmazuovle);
        this.wwmazuovle.setBackgroundColor(Color.parseColor("#043c24"));
        Spinner spinner4 = new Spinner(this);
        this.xvvpqwqoto = spinner4;
        spinner4.setLayoutParams(new LinearLayout.LayoutParams(807, 930));
        this.xvvpqwqoto.setPadding(45, 86, 133, 190);
        linearLayout.addView(this.xvvpqwqoto);
        this.xvvpqwqoto.setBackgroundColor(Color.parseColor("#32b547"));
        ImageView imageView5 = new ImageView(this);
        this.qckylullcs = imageView5;
        imageView5.setLayoutParams(new LinearLayout.LayoutParams(1419, 1753));
        this.qckylullcs.setPadding(69, 81, 28, 18);
        linearLayout.addView(this.qckylullcs);
        this.qckylullcs.setBackgroundColor(Color.parseColor("#0504f1"));
        GridView gridView7 = new GridView(this);
        this.pqoutrwnwc = gridView7;
        gridView7.setLayoutParams(new LinearLayout.LayoutParams(1333, 1091));
        this.pqoutrwnwc.setPadding(191, 102, 110, 130);
        linearLayout.addView(this.pqoutrwnwc);
        this.pqoutrwnwc.setBackgroundColor(Color.parseColor("#586820"));
        ImageView imageView6 = new ImageView(this);
        this.cphydmiqqq = imageView6;
        imageView6.setLayoutParams(new LinearLayout.LayoutParams(1343, 632));
        this.cphydmiqqq.setPadding(12, 71, 116, 104);
        linearLayout.addView(this.cphydmiqqq);
        this.cphydmiqqq.setBackgroundColor(Color.parseColor("#9ee2d7"));
        TextView textView4 = new TextView(this);
        this.zksquiizaq = textView4;
        textView4.setLayoutParams(new LinearLayout.LayoutParams(924, 617));
        this.zksquiizaq.setPadding(21, 156, 27, 40);
        linearLayout.addView(this.zksquiizaq);
        this.zksquiizaq.setBackgroundColor(Color.parseColor("#64fddd"));
        RadioButton radioButton3 = new RadioButton(this);
        this.qbkgoddooa = radioButton3;
        radioButton3.setLayoutParams(new LinearLayout.LayoutParams(711, 869));
        this.qbkgoddooa.setPadding(143, 192, 108, 177);
        linearLayout.addView(this.qbkgoddooa);
        this.qbkgoddooa.setBackgroundColor(Color.parseColor("#6a27bc"));
        TimePicker timePicker4 = new TimePicker(this);
        this.zwzeaidslz = timePicker4;
        timePicker4.setLayoutParams(new LinearLayout.LayoutParams(818, 1153));
        this.zwzeaidslz.setPadding(172, 60, 179, 56);
        linearLayout.addView(this.zwzeaidslz);
        this.zwzeaidslz.setBackgroundColor(Color.parseColor("#44fb53"));
        ListView listView5 = new ListView(this);
        this.ribbisswzj = listView5;
        listView5.setLayoutParams(new LinearLayout.LayoutParams(1551, 397));
        this.ribbisswzj.setPadding(50, 172, 174, 191);
        linearLayout.addView(this.ribbisswzj);
        this.ribbisswzj.setBackgroundColor(Color.parseColor("#aab83f"));
        ProgressBar progressBar5 = new ProgressBar(this);
        this.vtfjbvqgot = progressBar5;
        progressBar5.setLayoutParams(new LinearLayout.LayoutParams(279, 395));
        this.vtfjbvqgot.setPadding(34, 77, 44, 20);
        linearLayout.addView(this.vtfjbvqgot);
        this.vtfjbvqgot.setBackgroundColor(Color.parseColor("#9994e9"));
        Spinner spinner5 = new Spinner(this);
        this.hqtmpuompe = spinner5;
        spinner5.setLayoutParams(new LinearLayout.LayoutParams(477, 786));
        this.hqtmpuompe.setPadding(133, 113, 111, 38);
        linearLayout.addView(this.hqtmpuompe);
        this.hqtmpuompe.setBackgroundColor(Color.parseColor("#edaa49"));
        DatePicker datePicker4 = new DatePicker(this);
        this.lckazjnihd = datePicker4;
        datePicker4.setLayoutParams(new LinearLayout.LayoutParams(1573, 1432));
        this.lckazjnihd.setPadding(197, 18, 144, 98);
        linearLayout.addView(this.lckazjnihd);
        this.lckazjnihd.setBackgroundColor(Color.parseColor("#42bb3a"));
        ScrollView scrollView7 = new ScrollView(this);
        this.qsuuqsbwwn = scrollView7;
        scrollView7.setLayoutParams(new LinearLayout.LayoutParams(575, 1317));
        this.qsuuqsbwwn.setPadding(199, 19, 69, 19);
        linearLayout.addView(this.qsuuqsbwwn);
        this.qsuuqsbwwn.setBackgroundColor(Color.parseColor("#c87ed7"));
        GridView gridView8 = new GridView(this);
        this.fgsrlykzwj = gridView8;
        gridView8.setLayoutParams(new LinearLayout.LayoutParams(482, 332));
        this.fgsrlykzwj.setPadding(194, 140, 106, 144);
        linearLayout.addView(this.fgsrlykzwj);
        this.fgsrlykzwj.setBackgroundColor(Color.parseColor("#fcd4d7"));
        TimePicker timePicker5 = new TimePicker(this);
        this.wlpkjurvpk = timePicker5;
        timePicker5.setLayoutParams(new LinearLayout.LayoutParams(1807, 1212));
        this.wlpkjurvpk.setPadding(150, 157, 18, 135);
        linearLayout.addView(this.wlpkjurvpk);
        this.wlpkjurvpk.setBackgroundColor(Color.parseColor("#2bcad4"));
        LinearLayout linearLayout5 = new LinearLayout(this);
        this.tsbcqrkfwm = linearLayout5;
        linearLayout5.setLayoutParams(new LinearLayout.LayoutParams(1659, 253));
        this.tsbcqrkfwm.setPadding(170, 66, 0, 55);
        linearLayout.addView(this.tsbcqrkfwm);
        this.tsbcqrkfwm.setBackgroundColor(Color.parseColor("#35bfb4"));
        CheckBox checkBox4 = new CheckBox(this);
        this.mbqmcqatrh = checkBox4;
        checkBox4.setLayoutParams(new LinearLayout.LayoutParams(561, 1390));
        this.mbqmcqatrh.setPadding(107, 69, 150, 51);
        linearLayout.addView(this.mbqmcqatrh);
        this.mbqmcqatrh.setBackgroundColor(Color.parseColor("#cf22d3"));
        EditText editText8 = new EditText(this);
        this.hainwkopph = editText8;
        editText8.setLayoutParams(new LinearLayout.LayoutParams(1530, 1794));
        this.hainwkopph.setPadding(61, 139, 49, 89);
        linearLayout.addView(this.hainwkopph);
        this.hainwkopph.setBackgroundColor(Color.parseColor("#58db75"));
        ProgressBar progressBar6 = new ProgressBar(this);
        this.mqmpqlfppm = progressBar6;
        progressBar6.setLayoutParams(new LinearLayout.LayoutParams(321, 514));
        this.mqmpqlfppm.setPadding(81, 76, 87, 138);
        linearLayout.addView(this.mqmpqlfppm);
        this.mqmpqlfppm.setBackgroundColor(Color.parseColor("#c0ce44"));
        Button button3 = new Button(this);
        this.lpzjrghpyl = button3;
        button3.setLayoutParams(new LinearLayout.LayoutParams(1136, 22));
        this.lpzjrghpyl.setPadding(107, 78, 87, 44);
        linearLayout.addView(this.lpzjrghpyl);
        this.lpzjrghpyl.setBackgroundColor(Color.parseColor("#9d7a13"));
        CheckBox checkBox5 = new CheckBox(this);
        this.nvzbeidpqz = checkBox5;
        checkBox5.setLayoutParams(new LinearLayout.LayoutParams(873, 1605));
        this.nvzbeidpqz.setPadding(101, 109, 92, 11);
        linearLayout.addView(this.nvzbeidpqz);
        this.nvzbeidpqz.setBackgroundColor(Color.parseColor("#c5deb9"));
        SeekBar seekBar8 = new SeekBar(this);
        this.vjaufrxvpk = seekBar8;
        seekBar8.setLayoutParams(new LinearLayout.LayoutParams(1946, 851));
        this.vjaufrxvpk.setPadding(36, 25, 69, 166);
        linearLayout.addView(this.vjaufrxvpk);
        this.vjaufrxvpk.setBackgroundColor(Color.parseColor("#e33208"));
        Switch r26 = new Switch(this);
        this.ozhtgfhanb = r26;
        r26.setLayoutParams(new LinearLayout.LayoutParams(488, 626));
        this.ozhtgfhanb.setPadding(14, 34, 3, 28);
        linearLayout.addView(this.ozhtgfhanb);
        this.ozhtgfhanb.setBackgroundColor(Color.parseColor("#970a3c"));
        GridView gridView9 = new GridView(this);
        this.cavvmbdwxa = gridView9;
        gridView9.setLayoutParams(new LinearLayout.LayoutParams(1966, 1512));
        this.cavvmbdwxa.setPadding(22, 80, 48, 79);
        linearLayout.addView(this.cavvmbdwxa);
        this.cavvmbdwxa.setBackgroundColor(Color.parseColor("#c22fa0"));
        TableLayout tableLayout2 = new TableLayout(this);
        this.srfryoopjf = tableLayout2;
        tableLayout2.setLayoutParams(new LinearLayout.LayoutParams(1978, 1288));
        this.srfryoopjf.setPadding(132, 139, 193, 185);
        linearLayout.addView(this.srfryoopjf);
        this.srfryoopjf.setBackgroundColor(Color.parseColor("#1c62eb"));
        RadioButton radioButton4 = new RadioButton(this);
        this.qjyprnydar = radioButton4;
        radioButton4.setLayoutParams(new LinearLayout.LayoutParams(1085, 1124));
        this.qjyprnydar.setPadding(125, 25, 112, BDLocation.TypeServerDecryptError);
        linearLayout.addView(this.qjyprnydar);
        this.qjyprnydar.setBackgroundColor(Color.parseColor("#010736"));
        ImageView imageView7 = new ImageView(this);
        this.ynnnxegnvq = imageView7;
        imageView7.setLayoutParams(new LinearLayout.LayoutParams(1717, 1095));
        this.ynnnxegnvq.setPadding(36, 39, 41, 19);
        linearLayout.addView(this.ynnnxegnvq);
        this.ynnnxegnvq.setBackgroundColor(Color.parseColor("#e77a97"));
        TimePicker timePicker6 = new TimePicker(this);
        this.lpdwqrldxn = timePicker6;
        timePicker6.setLayoutParams(new LinearLayout.LayoutParams(353, 393));
        this.lpdwqrldxn.setPadding(155, 72, 7, 156);
        linearLayout.addView(this.lpdwqrldxn);
        this.lpdwqrldxn.setBackgroundColor(Color.parseColor("#61b05e"));
        EditText editText9 = new EditText(this);
        this.gdpynszmgi = editText9;
        editText9.setLayoutParams(new LinearLayout.LayoutParams(873, 1428));
        this.gdpynszmgi.setPadding(81, 57, 130, 82);
        linearLayout.addView(this.gdpynszmgi);
        this.gdpynszmgi.setBackgroundColor(Color.parseColor("#b71b9c"));
        Switch r27 = new Switch(this);
        this.wcgjymkokj = r27;
        r27.setLayoutParams(new LinearLayout.LayoutParams(1887, 1947));
        this.wcgjymkokj.setPadding(112, 117, 80, 140);
        linearLayout.addView(this.wcgjymkokj);
        this.wcgjymkokj.setBackgroundColor(Color.parseColor("#0b584b"));
        ListView listView6 = new ListView(this);
        this.eucqdvduim = listView6;
        listView6.setLayoutParams(new LinearLayout.LayoutParams(222, 1505));
        this.eucqdvduim.setPadding(139, 77, 125, 68);
        linearLayout.addView(this.eucqdvduim);
        this.eucqdvduim.setBackgroundColor(Color.parseColor("#6acaf0"));
        DatePicker datePicker5 = new DatePicker(this);
        this.ufmxckglib = datePicker5;
        datePicker5.setLayoutParams(new LinearLayout.LayoutParams(1525, 735));
        this.ufmxckglib.setPadding(18, 48, 199, 34);
        linearLayout.addView(this.ufmxckglib);
        this.ufmxckglib.setBackgroundColor(Color.parseColor("#c86741"));
        RadioButton radioButton5 = new RadioButton(this);
        this.ogsigseveo = radioButton5;
        radioButton5.setLayoutParams(new LinearLayout.LayoutParams(344, TypedValues.CycleType.TYPE_CUSTOM_WAVE_SHAPE));
        this.ogsigseveo.setPadding(146, 80, 83, 132);
        linearLayout.addView(this.ogsigseveo);
        this.ogsigseveo.setBackgroundColor(Color.parseColor("#1c5c55"));
        TableLayout tableLayout3 = new TableLayout(this);
        this.zclcojicgn = tableLayout3;
        tableLayout3.setLayoutParams(new LinearLayout.LayoutParams(1595, 348));
        this.zclcojicgn.setPadding(5, 6, 142, 121);
        linearLayout.addView(this.zclcojicgn);
        this.zclcojicgn.setBackgroundColor(Color.parseColor("#1c6c0b"));
        CheckBox checkBox6 = new CheckBox(this);
        this.qocaisiqyb = checkBox6;
        checkBox6.setLayoutParams(new LinearLayout.LayoutParams(1844, 1452));
        this.qocaisiqyb.setPadding(122, 181, 177, 44);
        linearLayout.addView(this.qocaisiqyb);
        this.qocaisiqyb.setBackgroundColor(Color.parseColor("#a5dd09"));
        ListView listView7 = new ListView(this);
        this.ogstnutpqm = listView7;
        listView7.setLayoutParams(new LinearLayout.LayoutParams(5, 990));
        this.ogstnutpqm.setPadding(10, 18, 141, 182);
        linearLayout.addView(this.ogstnutpqm);
        this.ogstnutpqm.setBackgroundColor(Color.parseColor("#d62ea7"));
        CheckBox checkBox7 = new CheckBox(this);
        this.kefgathnes = checkBox7;
        checkBox7.setLayoutParams(new LinearLayout.LayoutParams(363, 333));
        this.kefgathnes.setPadding(24, 91, WebSocketProtocol.PAYLOAD_SHORT, 36);
        linearLayout.addView(this.kefgathnes);
        this.kefgathnes.setBackgroundColor(Color.parseColor("#97fe1d"));
        ScrollView scrollView8 = new ScrollView(this);
        this.marlrajkxy = scrollView8;
        scrollView8.setLayoutParams(new LinearLayout.LayoutParams(1614, 687));
        this.marlrajkxy.setPadding(91, 53, 119, 15);
        linearLayout.addView(this.marlrajkxy);
        this.marlrajkxy.setBackgroundColor(Color.parseColor("#7b9cdf"));
        EditText editText10 = new EditText(this);
        this.ijocdziipx = editText10;
        editText10.setLayoutParams(new LinearLayout.LayoutParams(1453, 1286));
        this.ijocdziipx.setPadding(18, 24, 130, 194);
        linearLayout.addView(this.ijocdziipx);
        this.ijocdziipx.setBackgroundColor(Color.parseColor("#31122a"));
        Button button4 = new Button(this);
        this.xvkdizspsi = button4;
        button4.setLayoutParams(new LinearLayout.LayoutParams(413, 1613));
        this.xvkdizspsi.setPadding(75, 95, 146, 78);
        linearLayout.addView(this.xvkdizspsi);
        this.xvkdizspsi.setBackgroundColor(Color.parseColor("#ee3e18"));
        LinearLayout linearLayout6 = new LinearLayout(this);
        this.tsikpdlyoo = linearLayout6;
        linearLayout6.setLayoutParams(new LinearLayout.LayoutParams(310, 1910));
        this.tsikpdlyoo.setPadding(57, 3, 55, 88);
        linearLayout.addView(this.tsikpdlyoo);
        this.tsikpdlyoo.setBackgroundColor(Color.parseColor("#6e46a1"));
        ListView listView8 = new ListView(this);
        this.rlbepldjqj = listView8;
        listView8.setLayoutParams(new LinearLayout.LayoutParams(898, 135));
        this.rlbepldjqj.setPadding(49, 21, 190, 172);
        linearLayout.addView(this.rlbepldjqj);
        this.rlbepldjqj.setBackgroundColor(Color.parseColor("#dab214"));
        RelativeLayout relativeLayout8 = new RelativeLayout(this);
        this.cugefodjtn = relativeLayout8;
        relativeLayout8.setLayoutParams(new LinearLayout.LayoutParams(267, 1309));
        this.cugefodjtn.setPadding(112, 2, 67, 2);
        linearLayout.addView(this.cugefodjtn);
        this.cugefodjtn.setBackgroundColor(Color.parseColor("#e6f4a1"));
        ScrollView scrollView9 = new ScrollView(this);
        this.xpframguou = scrollView9;
        scrollView9.setLayoutParams(new LinearLayout.LayoutParams(1527, 1520));
        this.xpframguou.setPadding(164, 56, 155, 38);
        linearLayout.addView(this.xpframguou);
        this.xpframguou.setBackgroundColor(Color.parseColor("#b0689d"));
        DatePicker datePicker6 = new DatePicker(this);
        this.ahhdglajtp = datePicker6;
        datePicker6.setLayoutParams(new LinearLayout.LayoutParams(1211, 1934));
        this.ahhdglajtp.setPadding(133, 40, 130, WebSocketProtocol.PAYLOAD_SHORT);
        linearLayout.addView(this.ahhdglajtp);
        this.ahhdglajtp.setBackgroundColor(Color.parseColor("#470ebf"));
        LinearLayout linearLayout7 = new LinearLayout(this);
        this.hjvqznjcxg = linearLayout7;
        linearLayout7.setLayoutParams(new LinearLayout.LayoutParams(114, 1804));
        this.hjvqznjcxg.setPadding(199, 93, 70, 68);
        linearLayout.addView(this.hjvqznjcxg);
        this.hjvqznjcxg.setBackgroundColor(Color.parseColor("#61b27d"));
        ProgressBar progressBar7 = new ProgressBar(this);
        this.yuooebknzj = progressBar7;
        progressBar7.setLayoutParams(new LinearLayout.LayoutParams(657, 1758));
        this.yuooebknzj.setPadding(142, 154, 71, 51);
        linearLayout.addView(this.yuooebknzj);
        this.yuooebknzj.setBackgroundColor(Color.parseColor("#d6efec"));
        GridView gridView10 = new GridView(this);
        this.lhyaegcvdv = gridView10;
        gridView10.setLayoutParams(new LinearLayout.LayoutParams(1889, 366));
        this.lhyaegcvdv.setPadding(133, 152, 196, 133);
        linearLayout.addView(this.lhyaegcvdv);
        this.lhyaegcvdv.setBackgroundColor(Color.parseColor("#318925"));
        TimePicker timePicker7 = new TimePicker(this);
        this.zzmqcxxijn = timePicker7;
        timePicker7.setLayoutParams(new LinearLayout.LayoutParams(864, 275));
        this.zzmqcxxijn.setPadding(108, 61, 130, 2);
        linearLayout.addView(this.zzmqcxxijn);
        this.zzmqcxxijn.setBackgroundColor(Color.parseColor("#1228e3"));
        ViewFlipper viewFlipper2 = new ViewFlipper(this);
        this.bejferkxdf = viewFlipper2;
        viewFlipper2.setLayoutParams(new LinearLayout.LayoutParams(1148, 1633));
        this.bejferkxdf.setPadding(100, 105, 35, 29);
        linearLayout.addView(this.bejferkxdf);
        this.bejferkxdf.setBackgroundColor(Color.parseColor("#26ee23"));
        GridView gridView11 = new GridView(this);
        this.trrdwbhtis = gridView11;
        gridView11.setLayoutParams(new LinearLayout.LayoutParams(1028, 982));
        this.trrdwbhtis.setPadding(154, 34, 170, 33);
        linearLayout.addView(this.trrdwbhtis);
        this.trrdwbhtis.setBackgroundColor(Color.parseColor("#433074"));
        SeekBar seekBar9 = new SeekBar(this);
        this.zdkibznkvt = seekBar9;
        seekBar9.setLayoutParams(new LinearLayout.LayoutParams(677, 732));
        this.zdkibznkvt.setPadding(141, 64, 23, 168);
        linearLayout.addView(this.zdkibznkvt);
        this.zdkibznkvt.setBackgroundColor(Color.parseColor("#542b62"));
        Switch r28 = new Switch(this);
        this.sztpfwwxfm = r28;
        r28.setLayoutParams(new LinearLayout.LayoutParams(1318, 1666));
        this.sztpfwwxfm.setPadding(68, 91, 179, 67);
        linearLayout.addView(this.sztpfwwxfm);
        this.sztpfwwxfm.setBackgroundColor(Color.parseColor("#0f768a"));
        TableLayout tableLayout4 = new TableLayout(this);
        this.zplmedmneh = tableLayout4;
        tableLayout4.setLayoutParams(new LinearLayout.LayoutParams(1465, 77));
        this.zplmedmneh.setPadding(65, 25, 57, 157);
        linearLayout.addView(this.zplmedmneh);
        this.zplmedmneh.setBackgroundColor(Color.parseColor("#2e74bf"));
        RelativeLayout relativeLayout9 = new RelativeLayout(this);
        this.tnkabbjjeg = relativeLayout9;
        relativeLayout9.setLayoutParams(new LinearLayout.LayoutParams(135, 1235));
        this.tnkabbjjeg.setPadding(195, 180, 79, 2);
        linearLayout.addView(this.tnkabbjjeg);
        this.tnkabbjjeg.setBackgroundColor(Color.parseColor("#0d8c9e"));
        ScrollView scrollView10 = new ScrollView(this);
        this.vplacyztcm = scrollView10;
        scrollView10.setLayoutParams(new LinearLayout.LayoutParams(782, 1136));
        this.vplacyztcm.setPadding(180, 169, 152, 133);
        linearLayout.addView(this.vplacyztcm);
        this.vplacyztcm.setBackgroundColor(Color.parseColor("#1a4090"));
        Switch r29 = new Switch(this);
        this.isczodzxoc = r29;
        r29.setLayoutParams(new LinearLayout.LayoutParams(370, 713));
        this.isczodzxoc.setPadding(87, 100, 48, 54);
        linearLayout.addView(this.isczodzxoc);
        this.isczodzxoc.setBackgroundColor(Color.parseColor("#857545"));
        RelativeLayout relativeLayout10 = new RelativeLayout(this);
        this.ftjrtpfgap = relativeLayout10;
        relativeLayout10.setLayoutParams(new LinearLayout.LayoutParams(1285, 773));
        this.ftjrtpfgap.setPadding(196, 23, 179, 42);
        linearLayout.addView(this.ftjrtpfgap);
        this.ftjrtpfgap.setBackgroundColor(Color.parseColor("#38219b"));
        GridView gridView12 = new GridView(this);
        this.vsskovvbfh = gridView12;
        gridView12.setLayoutParams(new LinearLayout.LayoutParams(572, 291));
        this.vsskovvbfh.setPadding(10, 146, 26, 124);
        linearLayout.addView(this.vsskovvbfh);
        this.vsskovvbfh.setBackgroundColor(Color.parseColor("#bbcb90"));
        CheckBox checkBox8 = new CheckBox(this);
        this.uvvoafmvth = checkBox8;
        checkBox8.setLayoutParams(new LinearLayout.LayoutParams(233, TypedValues.MotionType.TYPE_ANIMATE_CIRCLEANGLE_TO));
        this.uvvoafmvth.setPadding(17, 52, 68, 16);
        linearLayout.addView(this.uvvoafmvth);
        this.uvvoafmvth.setBackgroundColor(Color.parseColor("#d058e8"));
        RelativeLayout relativeLayout11 = new RelativeLayout(this);
        this.iuwmucemoq = relativeLayout11;
        relativeLayout11.setLayoutParams(new LinearLayout.LayoutParams(1990, 1445));
        this.iuwmucemoq.setPadding(18, 104, 180, 16);
        linearLayout.addView(this.iuwmucemoq);
        this.iuwmucemoq.setBackgroundColor(Color.parseColor("#5de17c"));
        RadioButton radioButton6 = new RadioButton(this);
        this.rzmqfcuyhw = radioButton6;
        radioButton6.setLayoutParams(new LinearLayout.LayoutParams(61, 1743));
        this.rzmqfcuyhw.setPadding(197, 164, 77, 176);
        linearLayout.addView(this.rzmqfcuyhw);
        this.rzmqfcuyhw.setBackgroundColor(Color.parseColor("#d158c9"));
        Switch r210 = new Switch(this);
        this.hngnewotlo = r210;
        r210.setLayoutParams(new LinearLayout.LayoutParams(1545, 1395));
        this.hngnewotlo.setPadding(86, 132, 103, 172);
        linearLayout.addView(this.hngnewotlo);
        this.hngnewotlo.setBackgroundColor(Color.parseColor("#119c87"));
        ToggleButton toggleButton4 = new ToggleButton(this);
        this.kfbhwwvffx = toggleButton4;
        toggleButton4.setLayoutParams(new LinearLayout.LayoutParams(1056, 1453));
        this.kfbhwwvffx.setPadding(99, 44, 28, 120);
        linearLayout.addView(this.kfbhwwvffx);
        this.kfbhwwvffx.setBackgroundColor(Color.parseColor("#779573"));
        ScrollView scrollView11 = new ScrollView(this);
        this.fiobyamnug = scrollView11;
        scrollView11.setLayoutParams(new LinearLayout.LayoutParams(1064, 1267));
        this.fiobyamnug.setPadding(70, 179, 84, 111);
        linearLayout.addView(this.fiobyamnug);
        this.fiobyamnug.setBackgroundColor(Color.parseColor("#286e49"));
        Button button5 = new Button(this);
        this.pakqgotrqu = button5;
        button5.setLayoutParams(new LinearLayout.LayoutParams(394, 1855));
        this.pakqgotrqu.setPadding(123, 131, 25, 157);
        linearLayout.addView(this.pakqgotrqu);
        this.pakqgotrqu.setBackgroundColor(Color.parseColor("#6a71a2"));
        TableLayout tableLayout5 = new TableLayout(this);
        this.knlnxzhicc = tableLayout5;
        tableLayout5.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.MotionType.TYPE_DRAW_PATH, 880));
        this.knlnxzhicc.setPadding(30, 53, 121, 135);
        linearLayout.addView(this.knlnxzhicc);
        this.knlnxzhicc.setBackgroundColor(Color.parseColor("#1c31c9"));
        TextView textView5 = new TextView(this);
        this.ujjgcmrmvd = textView5;
        textView5.setLayoutParams(new LinearLayout.LayoutParams(975, 1953));
        this.ujjgcmrmvd.setPadding(11, 10, 22, 43);
        linearLayout.addView(this.ujjgcmrmvd);
        this.ujjgcmrmvd.setBackgroundColor(Color.parseColor("#5c0ff7"));
        FrameLayout frameLayout5 = new FrameLayout(this);
        this.yyxutatvqj = frameLayout5;
        frameLayout5.setLayoutParams(new LinearLayout.LayoutParams(697, 1155));
        this.yyxutatvqj.setPadding(107, 68, 123, 49);
        linearLayout.addView(this.yyxutatvqj);
        this.yyxutatvqj.setBackgroundColor(Color.parseColor("#26e38b"));
        TextView textView6 = new TextView(this);
        this.keexfgqpqh = textView6;
        textView6.setLayoutParams(new LinearLayout.LayoutParams(426, 1917));
        this.keexfgqpqh.setPadding(190, 84, 141, 47);
        linearLayout.addView(this.keexfgqpqh);
        this.keexfgqpqh.setBackgroundColor(Color.parseColor("#6ebfcf"));
        LinearLayout linearLayout8 = new LinearLayout(this);
        this.pifounkzmk = linearLayout8;
        linearLayout8.setLayoutParams(new LinearLayout.LayoutParams(293, 1800));
        this.pifounkzmk.setPadding(98, 69, 11, 172);
        linearLayout.addView(this.pifounkzmk);
        this.pifounkzmk.setBackgroundColor(Color.parseColor("#6a9492"));
        CheckBox checkBox9 = new CheckBox(this);
        this.ekpqovtbzs = checkBox9;
        checkBox9.setLayoutParams(new LinearLayout.LayoutParams(738, 1409));
        this.ekpqovtbzs.setPadding(112, 62, 43, 124);
        linearLayout.addView(this.ekpqovtbzs);
        this.ekpqovtbzs.setBackgroundColor(Color.parseColor("#4d6758"));
        Spinner spinner6 = new Spinner(this);
        this.srsvibtvcb = spinner6;
        spinner6.setLayoutParams(new LinearLayout.LayoutParams(958, 1647));
        this.srsvibtvcb.setPadding(134, 102, 155, 58);
        linearLayout.addView(this.srsvibtvcb);
        this.srsvibtvcb.setBackgroundColor(Color.parseColor("#05e99e"));
        Button button6 = new Button(this);
        this.szixeyudaj = button6;
        button6.setLayoutParams(new LinearLayout.LayoutParams(279, 1533));
        this.szixeyudaj.setPadding(110, 192, 74, 116);
        linearLayout.addView(this.szixeyudaj);
        this.szixeyudaj.setBackgroundColor(Color.parseColor("#74156f"));
        GridView gridView13 = new GridView(this);
        this.avsffvwkiy = gridView13;
        gridView13.setLayoutParams(new LinearLayout.LayoutParams(1035, 1769));
        this.avsffvwkiy.setPadding(26, 31, 65, 39);
        linearLayout.addView(this.avsffvwkiy);
        this.avsffvwkiy.setBackgroundColor(Color.parseColor("#6cc68e"));
        ListView listView9 = new ListView(this);
        this.vcuodsunxf = listView9;
        listView9.setLayoutParams(new LinearLayout.LayoutParams(1348, 562));
        this.vcuodsunxf.setPadding(49, 164, BDLocation.TypeNetWorkLocation, 115);
        linearLayout.addView(this.vcuodsunxf);
        this.vcuodsunxf.setBackgroundColor(Color.parseColor("#db5c47"));
        TimePicker timePicker8 = new TimePicker(this);
        this.zoolcnoghd = timePicker8;
        timePicker8.setLayoutParams(new LinearLayout.LayoutParams(186, 1031));
        this.zoolcnoghd.setPadding(153, 50, 137, 129);
        linearLayout.addView(this.zoolcnoghd);
        this.zoolcnoghd.setBackgroundColor(Color.parseColor("#0968e4"));
        ScrollView scrollView12 = new ScrollView(this);
        this.xsnsahbncn = scrollView12;
        scrollView12.setLayoutParams(new LinearLayout.LayoutParams(381, 100));
        this.xsnsahbncn.setPadding(178, 91, 92, 192);
        linearLayout.addView(this.xsnsahbncn);
        this.xsnsahbncn.setBackgroundColor(Color.parseColor("#571ca9"));
        TimePicker timePicker9 = new TimePicker(this);
        this.pinmlizxmu = timePicker9;
        timePicker9.setLayoutParams(new LinearLayout.LayoutParams(1302, 144));
        this.pinmlizxmu.setPadding(36, 91, 182, BDLocation.TypeServerError);
        linearLayout.addView(this.pinmlizxmu);
        this.pinmlizxmu.setBackgroundColor(Color.parseColor("#857281"));
        RelativeLayout relativeLayout12 = new RelativeLayout(this);
        this.qbrfgwnduf = relativeLayout12;
        relativeLayout12.setLayoutParams(new LinearLayout.LayoutParams(753, 1961));
        this.qbrfgwnduf.setPadding(78, 131, 138, 100);
        linearLayout.addView(this.qbrfgwnduf);
        this.qbrfgwnduf.setBackgroundColor(Color.parseColor("#a16b56"));
        SeekBar seekBar10 = new SeekBar(this);
        this.unpemgknli = seekBar10;
        seekBar10.setLayoutParams(new LinearLayout.LayoutParams(369, 488));
        this.unpemgknli.setPadding(195, 169, 185, 106);
        linearLayout.addView(this.unpemgknli);
        this.unpemgknli.setBackgroundColor(Color.parseColor("#5cf3ac"));
        ListView listView10 = new ListView(this);
        this.vvsfkkpfph = listView10;
        listView10.setLayoutParams(new LinearLayout.LayoutParams(1288, 1144));
        this.vvsfkkpfph.setPadding(98, 164, 0, 193);
        linearLayout.addView(this.vvsfkkpfph);
        this.vvsfkkpfph.setBackgroundColor(Color.parseColor("#33ac8d"));
        ScrollView scrollView13 = new ScrollView(this);
        this.xjjmpzqcdu = scrollView13;
        scrollView13.setLayoutParams(new LinearLayout.LayoutParams(169, 314));
        this.xjjmpzqcdu.setPadding(185, 116, 150, 128);
        linearLayout.addView(this.xjjmpzqcdu);
        this.xjjmpzqcdu.setBackgroundColor(Color.parseColor("#68dae3"));
        RatingBar ratingBar6 = new RatingBar(this);
        this.cnesvwozyj = ratingBar6;
        ratingBar6.setLayoutParams(new LinearLayout.LayoutParams(580, 1932));
        this.cnesvwozyj.setPadding(22, 94, 153, 77);
        linearLayout.addView(this.cnesvwozyj);
        this.cnesvwozyj.setBackgroundColor(Color.parseColor("#584aea"));
        GridView gridView14 = new GridView(this);
        this.ijxxpivxlz = gridView14;
        gridView14.setLayoutParams(new LinearLayout.LayoutParams(741, 415));
        this.ijxxpivxlz.setPadding(154, 78, 197, 116);
        linearLayout.addView(this.ijxxpivxlz);
        this.ijxxpivxlz.setBackgroundColor(Color.parseColor("#0fe8e4"));
        ViewFlipper viewFlipper3 = new ViewFlipper(this);
        this.jwctstlefh = viewFlipper3;
        viewFlipper3.setLayoutParams(new LinearLayout.LayoutParams(1842, 1231));
        this.jwctstlefh.setPadding(164, 133, 72, 149);
        linearLayout.addView(this.jwctstlefh);
        this.jwctstlefh.setBackgroundColor(Color.parseColor("#a3bd1b"));
        CheckBox checkBox10 = new CheckBox(this);
        this.icjshpgtra = checkBox10;
        checkBox10.setLayoutParams(new LinearLayout.LayoutParams(472, 1237));
        this.icjshpgtra.setPadding(143, 83, 181, 56);
        linearLayout.addView(this.icjshpgtra);
        this.icjshpgtra.setBackgroundColor(Color.parseColor("#2fdde0"));
        ToggleButton toggleButton5 = new ToggleButton(this);
        this.kluqauprfi = toggleButton5;
        toggleButton5.setLayoutParams(new LinearLayout.LayoutParams(1689, PDF417Common.MAX_CODEWORDS_IN_BARCODE));
        this.kluqauprfi.setPadding(48, 119, 139, 180);
        linearLayout.addView(this.kluqauprfi);
        this.kluqauprfi.setBackgroundColor(Color.parseColor("#0bc96c"));
        SeekBar seekBar11 = new SeekBar(this);
        this.ecrmsjnnem = seekBar11;
        seekBar11.setLayoutParams(new LinearLayout.LayoutParams(1148, 74));
        this.ecrmsjnnem.setPadding(80, 73, 113, 180);
        linearLayout.addView(this.ecrmsjnnem);
        this.ecrmsjnnem.setBackgroundColor(Color.parseColor("#75e5a1"));
        ScrollView scrollView14 = new ScrollView(this);
        this.melxsizawk = scrollView14;
        scrollView14.setLayoutParams(new LinearLayout.LayoutParams(168, 1326));
        this.melxsizawk.setPadding(9, 97, 9, 58);
        linearLayout.addView(this.melxsizawk);
        this.melxsizawk.setBackgroundColor(Color.parseColor("#e6fb11"));
        TimePicker timePicker10 = new TimePicker(this);
        this.tfbwkogbeo = timePicker10;
        timePicker10.setLayoutParams(new LinearLayout.LayoutParams(86, 287));
        this.tfbwkogbeo.setPadding(135, 25, 30, 149);
        linearLayout.addView(this.tfbwkogbeo);
        this.tfbwkogbeo.setBackgroundColor(Color.parseColor("#2a2234"));
        ImageView imageView8 = new ImageView(this);
        this.gfjcrjmskv = imageView8;
        imageView8.setLayoutParams(new LinearLayout.LayoutParams(1659, 1835));
        this.gfjcrjmskv.setPadding(189, 166, 123, 45);
        linearLayout.addView(this.gfjcrjmskv);
        this.gfjcrjmskv.setBackgroundColor(Color.parseColor("#c3576f"));
        TextView textView7 = new TextView(this);
        this.amemugenbt = textView7;
        textView7.setLayoutParams(new LinearLayout.LayoutParams(455, 1510));
        this.amemugenbt.setPadding(114, 196, 49, 8);
        linearLayout.addView(this.amemugenbt);
        this.amemugenbt.setBackgroundColor(Color.parseColor("#ec7cbd"));
        GridView gridView15 = new GridView(this);
        this.mckpascxdo = gridView15;
        gridView15.setLayoutParams(new LinearLayout.LayoutParams(1685, 1995));
        this.mckpascxdo.setPadding(191, 40, 5, 108);
        linearLayout.addView(this.mckpascxdo);
        this.mckpascxdo.setBackgroundColor(Color.parseColor("#b99eb4"));
        RelativeLayout relativeLayout13 = new RelativeLayout(this);
        this.rddjbqnygj = relativeLayout13;
        relativeLayout13.setLayoutParams(new LinearLayout.LayoutParams(455, 1013));
        this.rddjbqnygj.setPadding(64, 40, 124, 12);
        linearLayout.addView(this.rddjbqnygj);
        this.rddjbqnygj.setBackgroundColor(Color.parseColor("#975b0b"));
        TextView textView8 = new TextView(this);
        this.qnwwjihnfv = textView8;
        textView8.setLayoutParams(new LinearLayout.LayoutParams(117, 963));
        this.qnwwjihnfv.setPadding(172, 69, 84, 159);
        linearLayout.addView(this.qnwwjihnfv);
        this.qnwwjihnfv.setBackgroundColor(Color.parseColor("#15509c"));
        TimePicker timePicker11 = new TimePicker(this);
        this.gmkkkavtdp = timePicker11;
        timePicker11.setLayoutParams(new LinearLayout.LayoutParams(74, 97));
        this.gmkkkavtdp.setPadding(73, 97, 120, 124);
        linearLayout.addView(this.gmkkkavtdp);
        this.gmkkkavtdp.setBackgroundColor(Color.parseColor("#14f11b"));
        RelativeLayout relativeLayout14 = new RelativeLayout(this);
        this.ejcmksltza = relativeLayout14;
        relativeLayout14.setLayoutParams(new LinearLayout.LayoutParams(1300, 1563));
        this.ejcmksltza.setPadding(72, 12, 143, 90);
        linearLayout.addView(this.ejcmksltza);
        this.ejcmksltza.setBackgroundColor(Color.parseColor("#321f75"));
        RadioButton radioButton7 = new RadioButton(this);
        this.yvlqskqyuh = radioButton7;
        radioButton7.setLayoutParams(new LinearLayout.LayoutParams(1854, 1476));
        this.yvlqskqyuh.setPadding(41, 153, 115, 107);
        linearLayout.addView(this.yvlqskqyuh);
        this.yvlqskqyuh.setBackgroundColor(Color.parseColor("#455c0a"));
        EditText editText11 = new EditText(this);
        this.cozrebgika = editText11;
        editText11.setLayoutParams(new LinearLayout.LayoutParams(356, 1709));
        this.cozrebgika.setPadding(75, 158, 33, 199);
        linearLayout.addView(this.cozrebgika);
        this.cozrebgika.setBackgroundColor(Color.parseColor("#ba05b2"));
        RelativeLayout relativeLayout15 = new RelativeLayout(this);
        this.utsxfhqrxe = relativeLayout15;
        relativeLayout15.setLayoutParams(new LinearLayout.LayoutParams(1466, 808));
        this.utsxfhqrxe.setPadding(108, 129, 98, 174);
        linearLayout.addView(this.utsxfhqrxe);
        this.utsxfhqrxe.setBackgroundColor(Color.parseColor("#c7e43b"));
        LinearLayout linearLayout9 = new LinearLayout(this);
        this.odmcewitvw = linearLayout9;
        linearLayout9.setLayoutParams(new LinearLayout.LayoutParams(1537, 1860));
        this.odmcewitvw.setPadding(41, 6, 189, 72);
        linearLayout.addView(this.odmcewitvw);
        this.odmcewitvw.setBackgroundColor(Color.parseColor("#c14eea"));
        CheckBox checkBox11 = new CheckBox(this);
        this.irhqxjbpzt = checkBox11;
        checkBox11.setLayoutParams(new LinearLayout.LayoutParams(1647, 1274));
        this.irhqxjbpzt.setPadding(73, 94, 158, 30);
        linearLayout.addView(this.irhqxjbpzt);
        this.irhqxjbpzt.setBackgroundColor(Color.parseColor("#90c93b"));
        Button button7 = new Button(this);
        this.syqgxifdsf = button7;
        button7.setLayoutParams(new LinearLayout.LayoutParams(1570, 1790));
        this.syqgxifdsf.setPadding(60, 90, 47, 75);
        linearLayout.addView(this.syqgxifdsf);
        this.syqgxifdsf.setBackgroundColor(Color.parseColor("#61a79c"));
        CheckBox checkBox12 = new CheckBox(this);
        this.sryjuxasxe = checkBox12;
        checkBox12.setLayoutParams(new LinearLayout.LayoutParams(473, 169));
        this.sryjuxasxe.setPadding(130, 142, 34, 197);
        linearLayout.addView(this.sryjuxasxe);
        this.sryjuxasxe.setBackgroundColor(Color.parseColor("#a6893e"));
        TimePicker timePicker12 = new TimePicker(this);
        this.mfsbgyeguu = timePicker12;
        timePicker12.setLayoutParams(new LinearLayout.LayoutParams(775, 250));
        this.mfsbgyeguu.setPadding(186, 73, 48, 108);
        linearLayout.addView(this.mfsbgyeguu);
        this.mfsbgyeguu.setBackgroundColor(Color.parseColor("#ec0b22"));
        FrameLayout frameLayout6 = new FrameLayout(this);
        this.tklglzwhny = frameLayout6;
        frameLayout6.setLayoutParams(new LinearLayout.LayoutParams(238, 293));
        this.tklglzwhny.setPadding(18, 192, 41, 181);
        linearLayout.addView(this.tklglzwhny);
        this.tklglzwhny.setBackgroundColor(Color.parseColor("#a0b2c9"));
        RadioButton radioButton8 = new RadioButton(this);
        this.nzvdaoraad = radioButton8;
        radioButton8.setLayoutParams(new LinearLayout.LayoutParams(108, 811));
        this.nzvdaoraad.setPadding(157, 123, 49, 176);
        linearLayout.addView(this.nzvdaoraad);
        this.nzvdaoraad.setBackgroundColor(Color.parseColor("#8e5dfb"));
        RadioButton radioButton9 = new RadioButton(this);
        this.zoyrwxhlkv = radioButton9;
        radioButton9.setLayoutParams(new LinearLayout.LayoutParams(796, 1521));
        this.zoyrwxhlkv.setPadding(44, 16, 67, 132);
        linearLayout.addView(this.zoyrwxhlkv);
        this.zoyrwxhlkv.setBackgroundColor(Color.parseColor("#d5037f"));
        DatePicker datePicker7 = new DatePicker(this);
        this.ryhxiwpykk = datePicker7;
        datePicker7.setLayoutParams(new LinearLayout.LayoutParams(1987, 1829));
        this.ryhxiwpykk.setPadding(76, 12, 109, 76);
        linearLayout.addView(this.ryhxiwpykk);
        this.ryhxiwpykk.setBackgroundColor(Color.parseColor("#44df4f"));
        EditText editText12 = new EditText(this);
        this.hmnivoqeux = editText12;
        editText12.setLayoutParams(new LinearLayout.LayoutParams(1037, 50));
        this.hmnivoqeux.setPadding(57, 9, 56, 179);
        linearLayout.addView(this.hmnivoqeux);
        this.hmnivoqeux.setBackgroundColor(Color.parseColor("#193e3f"));
    }
}
