package com.smartapp.b.idnfcrfmaw;

import android.app.Activity;
import android.graphics.Color;
import android.os.Bundle;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.CheckBox;
import android.widget.DatePicker;
import android.widget.EditText;
import android.widget.FrameLayout;
import android.widget.GridView;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ListView;
import android.widget.ProgressBar;
import android.widget.RadioButton;
import android.widget.RatingBar;
import android.widget.RelativeLayout;
import android.widget.ScrollView;
import android.widget.SeekBar;
import android.widget.Spinner;
import android.widget.Switch;
import android.widget.TableLayout;
import android.widget.TextView;
import android.widget.TimePicker;
import android.widget.ToggleButton;
import android.widget.ViewFlipper;
import androidx.constraintlayout.core.motion.utils.TypedValues;
import androidx.core.view.PointerIconCompat;
import com.baidu.location.BDLocation;
import com.luck.picture.lib.config.Crop;
import com.luck.picture.lib.config.PictureConfig;
import com.realsil.sdk.core.bluetooth.connection.le.GattClient;
import com.realsil.sdk.core.bluetooth.impl.BluetoothClassImpl;
import okhttp3.internal.ws.WebSocketProtocol;

/* loaded from: classes4.dex */
public class SwgmfkakrvzActivity extends Activity {
    TextView afzqiyfthi;
    FrameLayout ajtonwtjea;
    Button akjomzxzoh;
    FrameLayout amwsodggbd;
    LinearLayout anbeextmce;
    RatingBar auizwegwnw;
    Spinner bauhtupvnn;
    TextView brjyjinejx;
    RadioButton byqjalmwrj;
    EditText carmgptqgj;
    RadioButton cdaftfdkcc;
    RelativeLayout chijeajxcz;
    ListView cjnybuhknq;
    Switch cjrteirgmo;
    LinearLayout cpdjpoajon;
    RatingBar dczipdmemf;
    TextView dfoidciiax;
    RelativeLayout dghgnyddjs;
    RadioButton diatnmxltt;
    Switch diibmbpipq;
    Switch dmpqwyzxru;
    RadioButton dnnwynmmrm;
    ProgressBar dvpprkrbhl;
    RatingBar dwhtbaajdv;
    LinearLayout eelfrhcspk;
    RadioButton egzefsdhwx;
    CheckBox eibdmzydsv;
    TimePicker ejwlkyrivb;
    FrameLayout elfeywsyav;
    RatingBar emxzqaakfb;
    DatePicker eubelvlbcd;
    ViewFlipper fgdvmgplqf;
    DatePicker fgqcqcghbx;
    LinearLayout fkadugjsov;
    EditText fmbjgxjvin;
    SeekBar foondwzozu;
    SeekBar foxxnneltk;
    RatingBar fpulbhcpux;
    TextView fpxuqfoqvf;
    EditText fsupuzvalf;
    GridView fvjiwciqlo;
    TableLayout fymdfyhbft;
    ViewFlipper gdysvmqmuq;
    LinearLayout gfkhmhqvml;
    ImageView gfleflojsc;
    ScrollView ggjeoayqmn;
    DatePicker gocltnhbcd;
    FrameLayout gqnxrytsag;
    ProgressBar gscsbtohmm;
    FrameLayout gszowwirwv;
    ProgressBar hfoptugsiz;
    SeekBar hgozglbmxs;
    EditText hhezixtdff;
    Button hldonerjfc;
    Spinner hofxmmwrwh;
    LinearLayout hpjlzdifac;
    TextView hrhufrvomx;
    DatePicker htcsnchjaj;
    GridView huhsjqsfma;
    Switch hvypxlgimt;
    LinearLayout hzaxjxxxqm;
    TextView hzhcmqogdl;
    ListView ibvuwmmbnw;
    GridView icaxupproa;
    EditText ieccldnida;
    RelativeLayout iftsfydhnx;
    Button iisqbonyho;
    DatePicker iljimcjsld;
    Switch iplqbxnsbv;
    ViewFlipper iqeyzzqkgk;
    ToggleButton ivkhtxvalx;
    TableLayout iyexzzcphh;
    SeekBar jirlewxskf;
    Switch jjvskmpirj;
    ImageView jnoyprpskw;
    FrameLayout jqhmhobmyz;
    ToggleButton jvrcljnksc;
    Button kfmrgcdjax;
    LinearLayout khpyvnnpmg;
    TableLayout kldvimyvcz;
    TextView klkzvzgvoi;
    ScrollView kmwkjewgze;
    ToggleButton kogcoirllu;
    GridView kokkvrwkda;
    ListView krxmelpzlk;
    TableLayout kuypfhbhpt;
    ToggleButton lbakgomdxw;
    ProgressBar ljsjnmfhsi;
    CheckBox lkawmdvznv;
    ViewFlipper lznfzsgekz;
    LinearLayout mbvqcslyou;
    ToggleButton mmevyymegt;
    SeekBar mrgnvxoeqq;
    Spinner mxyhgcvvyy;
    CheckBox mygrkpleva;
    RadioButton nacnxwehzj;
    EditText nchdsjwmjx;
    RadioButton ndnjtyidkx;
    TextView nhlrygcpxz;
    ProgressBar nikkvxkzqe;
    ViewFlipper nimrvypjsc;
    DatePicker nrjdkefajn;
    DatePicker nzoepioryo;
    ScrollView obklocjfqd;
    RatingBar oekskdycqb;
    RadioButton ofxkkntghx;
    RadioButton ojjfrohmbb;
    ProgressBar orkdcdghal;
    RatingBar otfeivudfp;
    ScrollView ouxdvvosru;
    LinearLayout ovwhntvifn;
    FrameLayout owiidhomwx;
    TimePicker pfxrnqehtj;
    RelativeLayout podggbaksd;
    CheckBox pslhewjfzw;
    ToggleButton qaekqarybh;
    RatingBar qcvpureqlf;
    EditText qffzexkbia;
    ViewFlipper qhbdcqezqd;
    DatePicker qhlbkzynuc;
    SeekBar qiuhzinkvy;
    LinearLayout qrbvqlwdtx;
    ScrollView rngcmzylpo;
    ToggleButton rogycbbksu;
    ToggleButton rpjeyyicqb;
    ProgressBar rvnbqorqpi;
    ScrollView rvwbdqwsux;
    Button siobthzvyl;
    EditText snhsfktjzc;
    RatingBar snjvqhhozi;
    ListView soushyrgoa;
    RelativeLayout strgntpauo;
    CheckBox swtykmfgbm;
    FrameLayout sxufbljfrn;
    LinearLayout syhrcyjfuc;
    LinearLayout sytkyjblzm;
    RelativeLayout tcpmkbqssy;
    EditText tfussemgub;
    RelativeLayout tghkfspmgv;
    TableLayout tlfjhgrtlc;
    ViewFlipper trrmcknbse;
    RelativeLayout tuemdkdajz;
    Button ubfvvthgio;
    ScrollView udfmcvflln;
    EditText uirqylwria;
    DatePicker uswkqeicwv;
    RadioButton utzrmrpokp;
    ProgressBar uuxgpgavvv;
    ScrollView uyedqwozrf;
    ToggleButton veumazybqs;
    GridView vfmtcrodui;
    FrameLayout vfpfhqlokh;
    DatePicker vgotrwhrwa;
    ListView vjfqtsmvax;
    ViewFlipper vnpwflxxva;
    ImageView vpqxxllaaj;
    CheckBox vqdekbpuvl;
    RadioButton vvicsfwmyq;
    CheckBox vvsqgioslt;
    ToggleButton vvvzxkoptf;
    CheckBox webyecffjx;
    RelativeLayout wmtvqcirgh;
    TextView wpkzvokxjb;
    Switch wteadtttmr;
    ListView wygfbfgiml;
    LinearLayout xdejcyzoem;
    RelativeLayout ximdfzysxs;
    EditText xpqicqzafn;
    FrameLayout xsysistoaq;
    DatePicker xucmhctgeu;
    FrameLayout xughnhzwyy;
    EditText xyoayyrkcr;
    CheckBox yaahegyksy;
    Spinner yccbxopuze;
    TimePicker yjosbgusme;
    ScrollView ymyycxbiqy;
    TimePicker yrceqytvfe;
    ToggleButton zprjfhezkb;
    TableLayout zxaqbxxxhc;

    @Override // android.app.Activity
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        LinearLayout linearLayout = new LinearLayout(this);
        setContentView(linearLayout);
        linearLayout.setLayoutParams(new ViewGroup.LayoutParams(-1, -1));
        linearLayout.setOrientation(1);
        linearLayout.setBackgroundColor(Color.parseColor("#eae8a4"));
        ListView listView = new ListView(this);
        this.wygfbfgiml = listView;
        listView.setLayoutParams(new LinearLayout.LayoutParams(519, 762));
        this.wygfbfgiml.setPadding(37, 171, 23, 68);
        linearLayout.addView(this.wygfbfgiml);
        this.wygfbfgiml.setBackgroundColor(Color.parseColor("#2a37e4"));
        EditText editText = new EditText(this);
        this.xyoayyrkcr = editText;
        editText.setLayoutParams(new LinearLayout.LayoutParams(37, 1180));
        this.xyoayyrkcr.setPadding(153, 61, 65, 55);
        linearLayout.addView(this.xyoayyrkcr);
        this.xyoayyrkcr.setBackgroundColor(Color.parseColor("#3e190c"));
        EditText editText2 = new EditText(this);
        this.snhsfktjzc = editText2;
        editText2.setLayoutParams(new LinearLayout.LayoutParams(1188, 1989));
        this.snhsfktjzc.setPadding(169, 73, 122, 142);
        linearLayout.addView(this.snhsfktjzc);
        this.snhsfktjzc.setBackgroundColor(Color.parseColor("#aad4fb"));
        LinearLayout linearLayout2 = new LinearLayout(this);
        this.khpyvnnpmg = linearLayout2;
        linearLayout2.setLayoutParams(new LinearLayout.LayoutParams(335, 91));
        this.khpyvnnpmg.setPadding(40, 169, 122, 148);
        linearLayout.addView(this.khpyvnnpmg);
        this.khpyvnnpmg.setBackgroundColor(Color.parseColor("#efeaee"));
        ToggleButton toggleButton = new ToggleButton(this);
        this.zprjfhezkb = toggleButton;
        toggleButton.setLayoutParams(new LinearLayout.LayoutParams(1555, 1110));
        this.zprjfhezkb.setPadding(190, 143, 21, 174);
        linearLayout.addView(this.zprjfhezkb);
        this.zprjfhezkb.setBackgroundColor(Color.parseColor("#fd29e7"));
        ProgressBar progressBar = new ProgressBar(this);
        this.uuxgpgavvv = progressBar;
        progressBar.setLayoutParams(new LinearLayout.LayoutParams(1968, 28));
        this.uuxgpgavvv.setPadding(133, 192, 123, 13);
        linearLayout.addView(this.uuxgpgavvv);
        this.uuxgpgavvv.setBackgroundColor(Color.parseColor("#636450"));
        ToggleButton toggleButton2 = new ToggleButton(this);
        this.kogcoirllu = toggleButton2;
        toggleButton2.setLayoutParams(new LinearLayout.LayoutParams(1538, 622));
        this.kogcoirllu.setPadding(129, 1, 58, 117);
        linearLayout.addView(this.kogcoirllu);
        this.kogcoirllu.setBackgroundColor(Color.parseColor("#8aa4d2"));
        DatePicker datePicker = new DatePicker(this);
        this.uswkqeicwv = datePicker;
        datePicker.setLayoutParams(new LinearLayout.LayoutParams(1687, 60));
        this.uswkqeicwv.setPadding(106, 129, 69, 72);
        linearLayout.addView(this.uswkqeicwv);
        this.uswkqeicwv.setBackgroundColor(Color.parseColor("#f44ac0"));
        FrameLayout frameLayout = new FrameLayout(this);
        this.ajtonwtjea = frameLayout;
        frameLayout.setLayoutParams(new LinearLayout.LayoutParams(1843, 457));
        this.ajtonwtjea.setPadding(68, 139, 173, 35);
        linearLayout.addView(this.ajtonwtjea);
        this.ajtonwtjea.setBackgroundColor(Color.parseColor("#a1e60c"));
        TimePicker timePicker = new TimePicker(this);
        this.yjosbgusme = timePicker;
        timePicker.setLayoutParams(new LinearLayout.LayoutParams(615, 131));
        this.yjosbgusme.setPadding(118, 14, 109, 28);
        linearLayout.addView(this.yjosbgusme);
        this.yjosbgusme.setBackgroundColor(Color.parseColor("#c002c1"));
        ToggleButton toggleButton3 = new ToggleButton(this);
        this.vvvzxkoptf = toggleButton3;
        toggleButton3.setLayoutParams(new LinearLayout.LayoutParams(744, 587));
        this.vvvzxkoptf.setPadding(175, 196, 123, 158);
        linearLayout.addView(this.vvvzxkoptf);
        this.vvvzxkoptf.setBackgroundColor(Color.parseColor("#20fe1a"));
        RadioButton radioButton = new RadioButton(this);
        this.egzefsdhwx = radioButton;
        radioButton.setLayoutParams(new LinearLayout.LayoutParams(547, 516));
        this.egzefsdhwx.setPadding(181, 11, 187, 178);
        linearLayout.addView(this.egzefsdhwx);
        this.egzefsdhwx.setBackgroundColor(Color.parseColor("#55fbb9"));
        RatingBar ratingBar = new RatingBar(this);
        this.emxzqaakfb = ratingBar;
        ratingBar.setLayoutParams(new LinearLayout.LayoutParams(918, 1059));
        this.emxzqaakfb.setPadding(81, 91, 85, 11);
        linearLayout.addView(this.emxzqaakfb);
        this.emxzqaakfb.setBackgroundColor(Color.parseColor("#8f4a23"));
        EditText editText3 = new EditText(this);
        this.carmgptqgj = editText3;
        editText3.setLayoutParams(new LinearLayout.LayoutParams(497, 1946));
        this.carmgptqgj.setPadding(77, 44, 70, 92);
        linearLayout.addView(this.carmgptqgj);
        this.carmgptqgj.setBackgroundColor(Color.parseColor("#d55a79"));
        FrameLayout frameLayout2 = new FrameLayout(this);
        this.xsysistoaq = frameLayout2;
        frameLayout2.setLayoutParams(new LinearLayout.LayoutParams(1571, 90));
        this.xsysistoaq.setPadding(141, 147, 140, 49);
        linearLayout.addView(this.xsysistoaq);
        this.xsysistoaq.setBackgroundColor(Color.parseColor("#970664"));
        Spinner spinner = new Spinner(this);
        this.mxyhgcvvyy = spinner;
        spinner.setLayoutParams(new LinearLayout.LayoutParams(1033, 1644));
        this.mxyhgcvvyy.setPadding(140, 177, 26, 169);
        linearLayout.addView(this.mxyhgcvvyy);
        this.mxyhgcvvyy.setBackground(new Cpggtqqhvaf());
        Spinner spinner2 = new Spinner(this);
        this.hofxmmwrwh = spinner2;
        spinner2.setLayoutParams(new LinearLayout.LayoutParams(787, 1539));
        this.hofxmmwrwh.setPadding(116, 71, 95, 155);
        linearLayout.addView(this.hofxmmwrwh);
        this.hofxmmwrwh.setBackgroundColor(Color.parseColor("#8e0bd9"));
        TimePicker timePicker2 = new TimePicker(this);
        this.pfxrnqehtj = timePicker2;
        timePicker2.setLayoutParams(new LinearLayout.LayoutParams(459, 363));
        this.pfxrnqehtj.setPadding(182, BDLocation.TypeNetWorkLocation, 127, 56);
        linearLayout.addView(this.pfxrnqehtj);
        this.pfxrnqehtj.setBackgroundColor(Color.parseColor("#e6bc10"));
        Switch r2 = new Switch(this);
        this.dmpqwyzxru = r2;
        r2.setLayoutParams(new LinearLayout.LayoutParams(1156, 590));
        this.dmpqwyzxru.setPadding(196, 28, 95, 34);
        linearLayout.addView(this.dmpqwyzxru);
        this.dmpqwyzxru.setBackgroundColor(Color.parseColor("#d69b50"));
        ToggleButton toggleButton4 = new ToggleButton(this);
        this.rogycbbksu = toggleButton4;
        toggleButton4.setLayoutParams(new LinearLayout.LayoutParams(1480, 809));
        this.rogycbbksu.setPadding(BDLocation.TypeCoarseLocation, 168, 170, 155);
        linearLayout.addView(this.rogycbbksu);
        this.rogycbbksu.setBackgroundColor(Color.parseColor("#da14a5"));
        RatingBar ratingBar2 = new RatingBar(this);
        this.oekskdycqb = ratingBar2;
        ratingBar2.setLayoutParams(new LinearLayout.LayoutParams(976, 280));
        this.oekskdycqb.setPadding(30, 134, 129, 11);
        linearLayout.addView(this.oekskdycqb);
        this.oekskdycqb.setBackgroundColor(Color.parseColor("#be1894"));
        ScrollView scrollView = new ScrollView(this);
        this.ggjeoayqmn = scrollView;
        scrollView.setLayoutParams(new LinearLayout.LayoutParams(1181, 1586));
        this.ggjeoayqmn.setPadding(182, 147, 95, 33);
        linearLayout.addView(this.ggjeoayqmn);
        this.ggjeoayqmn.setBackgroundColor(Color.parseColor("#8547e7"));
        LinearLayout linearLayout3 = new LinearLayout(this);
        this.mbvqcslyou = linearLayout3;
        linearLayout3.setLayoutParams(new LinearLayout.LayoutParams(1913, 1078));
        this.mbvqcslyou.setPadding(76, 62, 150, 15);
        linearLayout.addView(this.mbvqcslyou);
        this.mbvqcslyou.setBackgroundColor(Color.parseColor("#ca0b77"));
        SeekBar seekBar = new SeekBar(this);
        this.foxxnneltk = seekBar;
        seekBar.setLayoutParams(new LinearLayout.LayoutParams(515, 1790));
        this.foxxnneltk.setPadding(183, 193, 99, 66);
        linearLayout.addView(this.foxxnneltk);
        this.foxxnneltk.setBackgroundColor(Color.parseColor("#218b46"));
        Switch r22 = new Switch(this);
        this.cjrteirgmo = r22;
        r22.setLayoutParams(new LinearLayout.LayoutParams(1424, 599));
        this.cjrteirgmo.setPadding(13, 65, 53, 14);
        linearLayout.addView(this.cjrteirgmo);
        this.cjrteirgmo.setBackgroundColor(Color.parseColor("#e2ec47"));
        Button button = new Button(this);
        this.kfmrgcdjax = button;
        button.setLayoutParams(new LinearLayout.LayoutParams(1909, 419));
        this.kfmrgcdjax.setPadding(64, 27, 3, 187);
        linearLayout.addView(this.kfmrgcdjax);
        this.kfmrgcdjax.setBackgroundColor(Color.parseColor("#5e8ac8"));
        CheckBox checkBox = new CheckBox(this);
        this.pslhewjfzw = checkBox;
        checkBox.setLayoutParams(new LinearLayout.LayoutParams(922, 1667));
        this.pslhewjfzw.setPadding(17, 180, 140, 158);
        linearLayout.addView(this.pslhewjfzw);
        this.pslhewjfzw.setBackgroundColor(Color.parseColor("#73a932"));
        ScrollView scrollView2 = new ScrollView(this);
        this.uyedqwozrf = scrollView2;
        scrollView2.setLayoutParams(new LinearLayout.LayoutParams(433, 1852));
        this.uyedqwozrf.setPadding(50, 132, 192, 165);
        linearLayout.addView(this.uyedqwozrf);
        this.uyedqwozrf.setBackgroundColor(Color.parseColor("#268115"));
        RelativeLayout relativeLayout = new RelativeLayout(this);
        this.ximdfzysxs = relativeLayout;
        relativeLayout.setLayoutParams(new LinearLayout.LayoutParams(157, 1437));
        this.ximdfzysxs.setPadding(129, 184, 125, 184);
        linearLayout.addView(this.ximdfzysxs);
        this.ximdfzysxs.setBackgroundColor(Color.parseColor("#addf3c"));
        SeekBar seekBar2 = new SeekBar(this);
        this.mrgnvxoeqq = seekBar2;
        seekBar2.setLayoutParams(new LinearLayout.LayoutParams(1126, 818));
        this.mrgnvxoeqq.setPadding(39, 153, 164, 41);
        linearLayout.addView(this.mrgnvxoeqq);
        this.mrgnvxoeqq.setBackgroundColor(Color.parseColor("#ef8b41"));
        GridView gridView = new GridView(this);
        this.kokkvrwkda = gridView;
        gridView.setLayoutParams(new LinearLayout.LayoutParams(1905, 256));
        this.kokkvrwkda.setPadding(16, 149, 10, 144);
        linearLayout.addView(this.kokkvrwkda);
        this.kokkvrwkda.setBackgroundColor(Color.parseColor("#0ef988"));
        RatingBar ratingBar3 = new RatingBar(this);
        this.snjvqhhozi = ratingBar3;
        ratingBar3.setLayoutParams(new LinearLayout.LayoutParams(1108, 181));
        this.snjvqhhozi.setPadding(109, 105, 68, 150);
        linearLayout.addView(this.snjvqhhozi);
        this.snjvqhhozi.setBackgroundColor(Color.parseColor("#8f7cce"));
        RelativeLayout relativeLayout2 = new RelativeLayout(this);
        this.iftsfydhnx = relativeLayout2;
        relativeLayout2.setLayoutParams(new LinearLayout.LayoutParams(1152, 484));
        this.iftsfydhnx.setPadding(86, 73, 129, 196);
        linearLayout.addView(this.iftsfydhnx);
        this.iftsfydhnx.setBackgroundColor(Color.parseColor("#ee8edb"));
        EditText editText4 = new EditText(this);
        this.nchdsjwmjx = editText4;
        editText4.setLayoutParams(new LinearLayout.LayoutParams(720, 1138));
        this.nchdsjwmjx.setPadding(67, 93, 76, 96);
        linearLayout.addView(this.nchdsjwmjx);
        this.nchdsjwmjx.setBackgroundColor(Color.parseColor("#3a225f"));
        TextView textView = new TextView(this);
        this.nhlrygcpxz = textView;
        textView.setLayoutParams(new LinearLayout.LayoutParams(822, 585));
        this.nhlrygcpxz.setPadding(24, 64, 90, 139);
        linearLayout.addView(this.nhlrygcpxz);
        this.nhlrygcpxz.setBackgroundColor(Color.parseColor("#291d68"));
        FrameLayout frameLayout3 = new FrameLayout(this);
        this.vfpfhqlokh = frameLayout3;
        frameLayout3.setLayoutParams(new LinearLayout.LayoutParams(989, 430));
        this.vfpfhqlokh.setPadding(184, 55, 118, 26);
        linearLayout.addView(this.vfpfhqlokh);
        this.vfpfhqlokh.setBackgroundColor(Color.parseColor("#9adc69"));
        RelativeLayout relativeLayout3 = new RelativeLayout(this);
        this.strgntpauo = relativeLayout3;
        relativeLayout3.setLayoutParams(new LinearLayout.LayoutParams(1570, 1832));
        this.strgntpauo.setPadding(129, 76, 77, 22);
        linearLayout.addView(this.strgntpauo);
        this.strgntpauo.setBackgroundColor(Color.parseColor("#e19436"));
        DatePicker datePicker2 = new DatePicker(this);
        this.qhlbkzynuc = datePicker2;
        datePicker2.setLayoutParams(new LinearLayout.LayoutParams(645, 1448));
        this.qhlbkzynuc.setPadding(191, 21, 36, 178);
        linearLayout.addView(this.qhlbkzynuc);
        this.qhlbkzynuc.setBackgroundColor(Color.parseColor("#77e1e3"));
        TimePicker timePicker3 = new TimePicker(this);
        this.yrceqytvfe = timePicker3;
        timePicker3.setLayoutParams(new LinearLayout.LayoutParams(19, 472));
        this.yrceqytvfe.setPadding(13, 182, 142, 89);
        linearLayout.addView(this.yrceqytvfe);
        this.yrceqytvfe.setBackgroundColor(Color.parseColor("#67816c"));
        RelativeLayout relativeLayout4 = new RelativeLayout(this);
        this.tghkfspmgv = relativeLayout4;
        relativeLayout4.setLayoutParams(new LinearLayout.LayoutParams(1262, 1994));
        this.tghkfspmgv.setPadding(WebSocketProtocol.PAYLOAD_SHORT, 174, 81, 2);
        linearLayout.addView(this.tghkfspmgv);
        this.tghkfspmgv.setBackgroundColor(Color.parseColor("#0927af"));
        RelativeLayout relativeLayout5 = new RelativeLayout(this);
        this.wmtvqcirgh = relativeLayout5;
        relativeLayout5.setLayoutParams(new LinearLayout.LayoutParams(1373, 1381));
        this.wmtvqcirgh.setPadding(10, 17, 73, 58);
        linearLayout.addView(this.wmtvqcirgh);
        this.wmtvqcirgh.setBackgroundColor(Color.parseColor("#cb4656"));
        Switch r23 = new Switch(this);
        this.iplqbxnsbv = r23;
        r23.setLayoutParams(new LinearLayout.LayoutParams(1334, 582));
        this.iplqbxnsbv.setPadding(3, 163, 149, 12);
        linearLayout.addView(this.iplqbxnsbv);
        this.iplqbxnsbv.setBackgroundColor(Color.parseColor("#8017c5"));
        TableLayout tableLayout = new TableLayout(this);
        this.kldvimyvcz = tableLayout;
        tableLayout.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.CycleType.TYPE_ALPHA, 1817));
        this.kldvimyvcz.setPadding(166, 156, WebSocketProtocol.PAYLOAD_SHORT, 47);
        linearLayout.addView(this.kldvimyvcz);
        this.kldvimyvcz.setBackgroundColor(Color.parseColor("#d35624"));
        RatingBar ratingBar4 = new RatingBar(this);
        this.otfeivudfp = ratingBar4;
        ratingBar4.setLayoutParams(new LinearLayout.LayoutParams(1960, 1579));
        this.otfeivudfp.setPadding(78, 118, BDLocation.TypeServerError, 180);
        linearLayout.addView(this.otfeivudfp);
        this.otfeivudfp.setBackgroundColor(Color.parseColor("#49a6b1"));
        ViewFlipper viewFlipper = new ViewFlipper(this);
        this.iqeyzzqkgk = viewFlipper;
        viewFlipper.setLayoutParams(new LinearLayout.LayoutParams(939, 1735));
        this.iqeyzzqkgk.setPadding(12, 159, 6, 74);
        linearLayout.addView(this.iqeyzzqkgk);
        this.iqeyzzqkgk.setBackgroundColor(Color.parseColor("#5d932e"));
        CheckBox checkBox2 = new CheckBox(this);
        this.swtykmfgbm = checkBox2;
        checkBox2.setLayoutParams(new LinearLayout.LayoutParams(325, 849));
        this.swtykmfgbm.setPadding(138, 68, 146, 16);
        linearLayout.addView(this.swtykmfgbm);
        this.swtykmfgbm.setBackgroundColor(Color.parseColor("#6c5306"));
        ScrollView scrollView3 = new ScrollView(this);
        this.udfmcvflln = scrollView3;
        scrollView3.setLayoutParams(new LinearLayout.LayoutParams(1166, 1257));
        this.udfmcvflln.setPadding(7, 180, 117, 199);
        linearLayout.addView(this.udfmcvflln);
        this.udfmcvflln.setBackgroundColor(Color.parseColor("#c5d2d6"));
        RadioButton radioButton2 = new RadioButton(this);
        this.byqjalmwrj = radioButton2;
        radioButton2.setLayoutParams(new LinearLayout.LayoutParams(957, 1559));
        this.byqjalmwrj.setPadding(61, 85, 33, 113);
        linearLayout.addView(this.byqjalmwrj);
        this.byqjalmwrj.setBackgroundColor(Color.parseColor("#e31068"));
        SeekBar seekBar3 = new SeekBar(this);
        this.qiuhzinkvy = seekBar3;
        seekBar3.setLayoutParams(new LinearLayout.LayoutParams(1269, 1991));
        this.qiuhzinkvy.setPadding(21, 38, 183, 147);
        linearLayout.addView(this.qiuhzinkvy);
        this.qiuhzinkvy.setBackgroundColor(Color.parseColor("#9f62cf"));
        ProgressBar progressBar2 = new ProgressBar(this);
        this.orkdcdghal = progressBar2;
        progressBar2.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.CycleType.TYPE_EASING, 1114));
        this.orkdcdghal.setPadding(132, 138, 195, 98);
        linearLayout.addView(this.orkdcdghal);
        this.orkdcdghal.setBackgroundColor(Color.parseColor("#f7b37d"));
        Button button2 = new Button(this);
        this.ubfvvthgio = button2;
        button2.setLayoutParams(new LinearLayout.LayoutParams(893, 962));
        this.ubfvvthgio.setPadding(46, 196, 44, 101);
        linearLayout.addView(this.ubfvvthgio);
        this.ubfvvthgio.setBackgroundColor(Color.parseColor("#564f5f"));
        RadioButton radioButton3 = new RadioButton(this);
        this.ojjfrohmbb = radioButton3;
        radioButton3.setLayoutParams(new LinearLayout.LayoutParams(302, BluetoothClassImpl.Device.PERIPHERAL_KEYBOARD));
        this.ojjfrohmbb.setPadding(80, 76, 7, 7);
        linearLayout.addView(this.ojjfrohmbb);
        this.ojjfrohmbb.setBackgroundColor(Color.parseColor("#538ef3"));
        RatingBar ratingBar5 = new RatingBar(this);
        this.dwhtbaajdv = ratingBar5;
        ratingBar5.setLayoutParams(new LinearLayout.LayoutParams(1860, 1507));
        this.dwhtbaajdv.setPadding(139, 150, 44, 39);
        linearLayout.addView(this.dwhtbaajdv);
        this.dwhtbaajdv.setBackgroundColor(Color.parseColor("#072fee"));
        EditText editText5 = new EditText(this);
        this.xpqicqzafn = editText5;
        editText5.setLayoutParams(new LinearLayout.LayoutParams(115, 1671));
        this.xpqicqzafn.setPadding(PictureConfig.CHOOSE_REQUEST, 186, 42, 78);
        linearLayout.addView(this.xpqicqzafn);
        this.xpqicqzafn.setBackgroundColor(Color.parseColor("#32cd67"));
        SeekBar seekBar4 = new SeekBar(this);
        this.jirlewxskf = seekBar4;
        seekBar4.setLayoutParams(new LinearLayout.LayoutParams(1643, 560));
        this.jirlewxskf.setPadding(185, 100, 196, PictureConfig.CHOOSE_REQUEST);
        linearLayout.addView(this.jirlewxskf);
        this.jirlewxskf.setBackgroundColor(Color.parseColor("#8d27b0"));
        CheckBox checkBox3 = new CheckBox(this);
        this.mygrkpleva = checkBox3;
        checkBox3.setLayoutParams(new LinearLayout.LayoutParams(781, 810));
        this.mygrkpleva.setPadding(157, 82, 5, 96);
        linearLayout.addView(this.mygrkpleva);
        this.mygrkpleva.setBackgroundColor(Color.parseColor("#e8f671"));
        ProgressBar progressBar3 = new ProgressBar(this);
        this.nikkvxkzqe = progressBar3;
        progressBar3.setLayoutParams(new LinearLayout.LayoutParams(1987, 1558));
        this.nikkvxkzqe.setPadding(100, 141, 64, 186);
        linearLayout.addView(this.nikkvxkzqe);
        this.nikkvxkzqe.setBackgroundColor(Color.parseColor("#6d69b8"));
        LinearLayout linearLayout4 = new LinearLayout(this);
        this.fkadugjsov = linearLayout4;
        linearLayout4.setLayoutParams(new LinearLayout.LayoutParams(1718, 1995));
        this.fkadugjsov.setPadding(66, 101, 112, 128);
        linearLayout.addView(this.fkadugjsov);
        this.fkadugjsov.setBackgroundColor(Color.parseColor("#4f6509"));
        LinearLayout linearLayout5 = new LinearLayout(this);
        this.eelfrhcspk = linearLayout5;
        linearLayout5.setLayoutParams(new LinearLayout.LayoutParams(577, 1822));
        this.eelfrhcspk.setPadding(13, 68, 143, 129);
        linearLayout.addView(this.eelfrhcspk);
        this.eelfrhcspk.setBackgroundColor(Color.parseColor("#f57223"));
        TableLayout tableLayout2 = new TableLayout(this);
        this.iyexzzcphh = tableLayout2;
        tableLayout2.setLayoutParams(new LinearLayout.LayoutParams(1803, 295));
        this.iyexzzcphh.setPadding(66, 134, 171, 0);
        linearLayout.addView(this.iyexzzcphh);
        this.iyexzzcphh.setBackgroundColor(Color.parseColor("#6fa794"));
        LinearLayout linearLayout6 = new LinearLayout(this);
        this.hpjlzdifac = linearLayout6;
        linearLayout6.setLayoutParams(new LinearLayout.LayoutParams(602, 1579));
        this.hpjlzdifac.setPadding(157, 91, 171, 169);
        linearLayout.addView(this.hpjlzdifac);
        this.hpjlzdifac.setBackgroundColor(Color.parseColor("#016412"));
        TextView textView2 = new TextView(this);
        this.dfoidciiax = textView2;
        textView2.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.PositionType.TYPE_CURVE_FIT, 520));
        this.dfoidciiax.setPadding(73, 57, 112, 81);
        linearLayout.addView(this.dfoidciiax);
        this.dfoidciiax.setBackgroundColor(Color.parseColor("#4dffbf"));
        ViewFlipper viewFlipper2 = new ViewFlipper(this);
        this.fgdvmgplqf = viewFlipper2;
        viewFlipper2.setLayoutParams(new LinearLayout.LayoutParams(1736, 104));
        this.fgdvmgplqf.setPadding(79, 35, 183, 118);
        linearLayout.addView(this.fgdvmgplqf);
        this.fgdvmgplqf.setBackgroundColor(Color.parseColor("#a0123f"));
        DatePicker datePicker3 = new DatePicker(this);
        this.iljimcjsld = datePicker3;
        datePicker3.setLayoutParams(new LinearLayout.LayoutParams(1209, 1677));
        this.iljimcjsld.setPadding(196, 191, 35, 171);
        linearLayout.addView(this.iljimcjsld);
        this.iljimcjsld.setBackgroundColor(Color.parseColor("#d13487"));
        ToggleButton toggleButton5 = new ToggleButton(this);
        this.veumazybqs = toggleButton5;
        toggleButton5.setLayoutParams(new LinearLayout.LayoutParams(1027, PointerIconCompat.TYPE_GRABBING));
        this.veumazybqs.setPadding(19, 80, 80, 77);
        linearLayout.addView(this.veumazybqs);
        this.veumazybqs.setBackgroundColor(Color.parseColor("#5d7cb8"));
        DatePicker datePicker4 = new DatePicker(this);
        this.fgqcqcghbx = datePicker4;
        datePicker4.setLayoutParams(new LinearLayout.LayoutParams(1239, 195));
        this.fgqcqcghbx.setPadding(145, 64, 122, 15);
        linearLayout.addView(this.fgqcqcghbx);
        this.fgqcqcghbx.setBackgroundColor(Color.parseColor("#a0eccd"));
        Switch r24 = new Switch(this);
        this.jjvskmpirj = r24;
        r24.setLayoutParams(new LinearLayout.LayoutParams(1673, 826));
        this.jjvskmpirj.setPadding(94, 72, 109, 143);
        linearLayout.addView(this.jjvskmpirj);
        this.jjvskmpirj.setBackgroundColor(Color.parseColor("#ae2a52"));
        TableLayout tableLayout3 = new TableLayout(this);
        this.tlfjhgrtlc = tableLayout3;
        tableLayout3.setLayoutParams(new LinearLayout.LayoutParams(1802, 1582));
        this.tlfjhgrtlc.setPadding(40, 182, 62, 99);
        linearLayout.addView(this.tlfjhgrtlc);
        this.tlfjhgrtlc.setBackgroundColor(Color.parseColor("#7e9bcf"));
        RelativeLayout relativeLayout6 = new RelativeLayout(this);
        this.podggbaksd = relativeLayout6;
        relativeLayout6.setLayoutParams(new LinearLayout.LayoutParams(PointerIconCompat.TYPE_TOP_RIGHT_DIAGONAL_DOUBLE_ARROW, 153));
        this.podggbaksd.setPadding(163, 3, 111, 132);
        linearLayout.addView(this.podggbaksd);
        this.podggbaksd.setBackgroundColor(Color.parseColor("#15651a"));
        RadioButton radioButton4 = new RadioButton(this);
        this.utzrmrpokp = radioButton4;
        radioButton4.setLayoutParams(new LinearLayout.LayoutParams(249, 1807));
        this.utzrmrpokp.setPadding(157, 128, 104, 117);
        linearLayout.addView(this.utzrmrpokp);
        this.utzrmrpokp.setBackgroundColor(Color.parseColor("#20ab9e"));
        CheckBox checkBox4 = new CheckBox(this);
        this.eibdmzydsv = checkBox4;
        checkBox4.setLayoutParams(new LinearLayout.LayoutParams(176, 1279));
        this.eibdmzydsv.setPadding(62, 3, 2, 184);
        linearLayout.addView(this.eibdmzydsv);
        this.eibdmzydsv.setBackgroundColor(Color.parseColor("#ff9dd7"));
        ListView listView2 = new ListView(this);
        this.soushyrgoa = listView2;
        listView2.setLayoutParams(new LinearLayout.LayoutParams(1838, 574));
        this.soushyrgoa.setPadding(61, 146, 30, 141);
        linearLayout.addView(this.soushyrgoa);
        this.soushyrgoa.setBackgroundColor(Color.parseColor("#c2b0a2"));
        TableLayout tableLayout4 = new TableLayout(this);
        this.zxaqbxxxhc = tableLayout4;
        tableLayout4.setLayoutParams(new LinearLayout.LayoutParams(386, 777));
        this.zxaqbxxxhc.setPadding(197, 44, 2, 40);
        linearLayout.addView(this.zxaqbxxxhc);
        this.zxaqbxxxhc.setBackgroundColor(Color.parseColor("#861be8"));
        TextView textView3 = new TextView(this);
        this.afzqiyfthi = textView3;
        textView3.setLayoutParams(new LinearLayout.LayoutParams(436, 319));
        this.afzqiyfthi.setPadding(197, 48, 140, 158);
        linearLayout.addView(this.afzqiyfthi);
        this.afzqiyfthi.setBackgroundColor(Color.parseColor("#04c106"));
        TextView textView4 = new TextView(this);
        this.brjyjinejx = textView4;
        textView4.setLayoutParams(new LinearLayout.LayoutParams(884, 1985));
        this.brjyjinejx.setPadding(190, 43, 48, 35);
        linearLayout.addView(this.brjyjinejx);
        this.brjyjinejx.setBackgroundColor(Color.parseColor("#a52507"));
        GridView gridView2 = new GridView(this);
        this.vfmtcrodui = gridView2;
        gridView2.setLayoutParams(new LinearLayout.LayoutParams(120, 864));
        this.vfmtcrodui.setPadding(159, 147, 36, 20);
        linearLayout.addView(this.vfmtcrodui);
        this.vfmtcrodui.setBackgroundColor(Color.parseColor("#2c6ca9"));
        TimePicker timePicker4 = new TimePicker(this);
        this.ejwlkyrivb = timePicker4;
        timePicker4.setLayoutParams(new LinearLayout.LayoutParams(1946, 1322));
        this.ejwlkyrivb.setPadding(116, 26, 43, 12);
        linearLayout.addView(this.ejwlkyrivb);
        this.ejwlkyrivb.setBackgroundColor(Color.parseColor("#d2fad3"));
        ProgressBar progressBar4 = new ProgressBar(this);
        this.rvnbqorqpi = progressBar4;
        progressBar4.setLayoutParams(new LinearLayout.LayoutParams(41, 984));
        this.rvnbqorqpi.setPadding(109, 192, 135, 166);
        linearLayout.addView(this.rvnbqorqpi);
        this.rvnbqorqpi.setBackgroundColor(Color.parseColor("#aee51c"));
        LinearLayout linearLayout7 = new LinearLayout(this);
        this.syhrcyjfuc = linearLayout7;
        linearLayout7.setLayoutParams(new LinearLayout.LayoutParams(79, 1134));
        this.syhrcyjfuc.setPadding(178, 137, 48, 54);
        linearLayout.addView(this.syhrcyjfuc);
        this.syhrcyjfuc.setBackgroundColor(Color.parseColor("#67b3f3"));
        ImageView imageView = new ImageView(this);
        this.jnoyprpskw = imageView;
        imageView.setLayoutParams(new LinearLayout.LayoutParams(1320, 1496));
        this.jnoyprpskw.setPadding(123, 79, 170, 11);
        linearLayout.addView(this.jnoyprpskw);
        this.jnoyprpskw.setBackgroundColor(Color.parseColor("#bd4b86"));
        ToggleButton toggleButton6 = new ToggleButton(this);
        this.jvrcljnksc = toggleButton6;
        toggleButton6.setLayoutParams(new LinearLayout.LayoutParams(75, 150));
        this.jvrcljnksc.setPadding(WebSocketProtocol.PAYLOAD_SHORT, 37, 100, 85);
        linearLayout.addView(this.jvrcljnksc);
        this.jvrcljnksc.setBackgroundColor(Color.parseColor("#d2ea4a"));
        FrameLayout frameLayout4 = new FrameLayout(this);
        this.amwsodggbd = frameLayout4;
        frameLayout4.setLayoutParams(new LinearLayout.LayoutParams(1497, 748));
        this.amwsodggbd.setPadding(2, 88, 187, 111);
        linearLayout.addView(this.amwsodggbd);
        this.amwsodggbd.setBackgroundColor(Color.parseColor("#438e07"));
        EditText editText6 = new EditText(this);
        this.qffzexkbia = editText6;
        editText6.setLayoutParams(new LinearLayout.LayoutParams(603, 1073));
        this.qffzexkbia.setPadding(32, 155, 189, 18);
        linearLayout.addView(this.qffzexkbia);
        this.qffzexkbia.setBackgroundColor(Color.parseColor("#53f7fe"));
        RelativeLayout relativeLayout7 = new RelativeLayout(this);
        this.dghgnyddjs = relativeLayout7;
        relativeLayout7.setLayoutParams(new LinearLayout.LayoutParams(17, 777));
        this.dghgnyddjs.setPadding(17, 7, 9, 70);
        linearLayout.addView(this.dghgnyddjs);
        this.dghgnyddjs.setBackgroundColor(Color.parseColor("#fca12b"));
        TextView textView5 = new TextView(this);
        this.hzhcmqogdl = textView5;
        textView5.setLayoutParams(new LinearLayout.LayoutParams(509, 1497));
        this.hzhcmqogdl.setPadding(50, 52, 108, 158);
        linearLayout.addView(this.hzhcmqogdl);
        this.hzhcmqogdl.setBackgroundColor(Color.parseColor("#400656"));
        ViewFlipper viewFlipper3 = new ViewFlipper(this);
        this.gdysvmqmuq = viewFlipper3;
        viewFlipper3.setLayoutParams(new LinearLayout.LayoutParams(1447, 1439));
        this.gdysvmqmuq.setPadding(131, 7, 48, 7);
        linearLayout.addView(this.gdysvmqmuq);
        this.gdysvmqmuq.setBackgroundColor(Color.parseColor("#e3eb48"));
        ScrollView scrollView4 = new ScrollView(this);
        this.rngcmzylpo = scrollView4;
        scrollView4.setLayoutParams(new LinearLayout.LayoutParams(49, 564));
        this.rngcmzylpo.setPadding(14, 129, 22, 196);
        linearLayout.addView(this.rngcmzylpo);
        this.rngcmzylpo.setBackgroundColor(Color.parseColor("#00e6e1"));
        DatePicker datePicker5 = new DatePicker(this);
        this.xucmhctgeu = datePicker5;
        datePicker5.setLayoutParams(new LinearLayout.LayoutParams(1123, 1575));
        this.xucmhctgeu.setPadding(172, 105, 100, 73);
        linearLayout.addView(this.xucmhctgeu);
        this.xucmhctgeu.setBackgroundColor(Color.parseColor("#eedea0"));
        FrameLayout frameLayout5 = new FrameLayout(this);
        this.elfeywsyav = frameLayout5;
        frameLayout5.setLayoutParams(new LinearLayout.LayoutParams(1994, 399));
        this.elfeywsyav.setPadding(107, 158, 192, 113);
        linearLayout.addView(this.elfeywsyav);
        this.elfeywsyav.setBackgroundColor(Color.parseColor("#c52aaf"));
        Switch r25 = new Switch(this);
        this.wteadtttmr = r25;
        r25.setLayoutParams(new LinearLayout.LayoutParams(722, 1125));
        this.wteadtttmr.setPadding(100, 165, 26, 79);
        linearLayout.addView(this.wteadtttmr);
        this.wteadtttmr.setBackgroundColor(Color.parseColor("#1ba5b4"));
        ScrollView scrollView5 = new ScrollView(this);
        this.ymyycxbiqy = scrollView5;
        scrollView5.setLayoutParams(new LinearLayout.LayoutParams(1340, 1155));
        this.ymyycxbiqy.setPadding(49, 154, 103, 55);
        linearLayout.addView(this.ymyycxbiqy);
        this.ymyycxbiqy.setBackgroundColor(Color.parseColor("#71df22"));
        Switch r26 = new Switch(this);
        this.hvypxlgimt = r26;
        r26.setLayoutParams(new LinearLayout.LayoutParams(417, 1525));
        this.hvypxlgimt.setPadding(67, 150, 122, 182);
        linearLayout.addView(this.hvypxlgimt);
        this.hvypxlgimt.setBackgroundColor(Color.parseColor("#28ac06"));
        FrameLayout frameLayout6 = new FrameLayout(this);
        this.owiidhomwx = frameLayout6;
        frameLayout6.setLayoutParams(new LinearLayout.LayoutParams(1756, 723));
        this.owiidhomwx.setPadding(193, 196, 46, 52);
        linearLayout.addView(this.owiidhomwx);
        this.owiidhomwx.setBackgroundColor(Color.parseColor("#5e05d4"));
        TableLayout tableLayout5 = new TableLayout(this);
        this.kuypfhbhpt = tableLayout5;
        tableLayout5.setLayoutParams(new LinearLayout.LayoutParams(862, 1473));
        this.kuypfhbhpt.setPadding(172, 41, 168, 164);
        linearLayout.addView(this.kuypfhbhpt);
        this.kuypfhbhpt.setBackgroundColor(Color.parseColor("#f8410f"));
        ToggleButton toggleButton7 = new ToggleButton(this);
        this.ivkhtxvalx = toggleButton7;
        toggleButton7.setLayoutParams(new LinearLayout.LayoutParams(35, 1755));
        this.ivkhtxvalx.setPadding(143, 87, 96, 182);
        linearLayout.addView(this.ivkhtxvalx);
        this.ivkhtxvalx.setBackgroundColor(Color.parseColor("#186f5d"));
        Button button3 = new Button(this);
        this.akjomzxzoh = button3;
        button3.setLayoutParams(new LinearLayout.LayoutParams(1643, 312));
        this.akjomzxzoh.setPadding(59, 180, 95, 26);
        linearLayout.addView(this.akjomzxzoh);
        this.akjomzxzoh.setBackgroundColor(Color.parseColor("#8c33ff"));
        ViewFlipper viewFlipper4 = new ViewFlipper(this);
        this.vnpwflxxva = viewFlipper4;
        viewFlipper4.setLayoutParams(new LinearLayout.LayoutParams(1756, 1217));
        this.vnpwflxxva.setPadding(104, 61, 74, 193);
        linearLayout.addView(this.vnpwflxxva);
        this.vnpwflxxva.setBackgroundColor(Color.parseColor("#7ad75b"));
        ProgressBar progressBar5 = new ProgressBar(this);
        this.gscsbtohmm = progressBar5;
        progressBar5.setLayoutParams(new LinearLayout.LayoutParams(27, 1830));
        this.gscsbtohmm.setPadding(15, 114, 173, 10);
        linearLayout.addView(this.gscsbtohmm);
        this.gscsbtohmm.setBackgroundColor(Color.parseColor("#1e2c7a"));
        RatingBar ratingBar6 = new RatingBar(this);
        this.fpulbhcpux = ratingBar6;
        ratingBar6.setLayoutParams(new LinearLayout.LayoutParams(1154, 1238));
        this.fpulbhcpux.setPadding(124, 46, 140, 109);
        linearLayout.addView(this.fpulbhcpux);
        this.fpulbhcpux.setBackgroundColor(Color.parseColor("#4cb6db"));
        LinearLayout linearLayout8 = new LinearLayout(this);
        this.anbeextmce = linearLayout8;
        linearLayout8.setLayoutParams(new LinearLayout.LayoutParams(1571, TypedValues.TransitionType.TYPE_INTERPOLATOR));
        this.anbeextmce.setPadding(130, 20, 66, 112);
        linearLayout.addView(this.anbeextmce);
        this.anbeextmce.setBackgroundColor(Color.parseColor("#5b4507"));
        RatingBar ratingBar7 = new RatingBar(this);
        this.dczipdmemf = ratingBar7;
        ratingBar7.setLayoutParams(new LinearLayout.LayoutParams(1731, 1956));
        this.dczipdmemf.setPadding(38, 72, 117, 28);
        linearLayout.addView(this.dczipdmemf);
        this.dczipdmemf.setBackgroundColor(Color.parseColor("#e7c081"));
        ListView listView3 = new ListView(this);
        this.ibvuwmmbnw = listView3;
        listView3.setLayoutParams(new LinearLayout.LayoutParams(811, Crop.REQUEST_EDIT_CROP));
        this.ibvuwmmbnw.setPadding(60, 168, 41, 163);
        linearLayout.addView(this.ibvuwmmbnw);
        this.ibvuwmmbnw.setBackgroundColor(Color.parseColor("#5590e3"));
        CheckBox checkBox5 = new CheckBox(this);
        this.yaahegyksy = checkBox5;
        checkBox5.setLayoutParams(new LinearLayout.LayoutParams(1424, 896));
        this.yaahegyksy.setPadding(128, 70, 42, 88);
        linearLayout.addView(this.yaahegyksy);
        this.yaahegyksy.setBackgroundColor(Color.parseColor("#99e0b0"));
        DatePicker datePicker6 = new DatePicker(this);
        this.nrjdkefajn = datePicker6;
        datePicker6.setLayoutParams(new LinearLayout.LayoutParams(971, 181));
        this.nrjdkefajn.setPadding(76, 197, 87, 59);
        linearLayout.addView(this.nrjdkefajn);
        this.nrjdkefajn.setBackgroundColor(Color.parseColor("#e7ef27"));
        ProgressBar progressBar6 = new ProgressBar(this);
        this.ljsjnmfhsi = progressBar6;
        progressBar6.setLayoutParams(new LinearLayout.LayoutParams(523, 56));
        this.ljsjnmfhsi.setPadding(56, 85, 176, 176);
        linearLayout.addView(this.ljsjnmfhsi);
        this.ljsjnmfhsi.setBackgroundColor(Color.parseColor("#e9bec6"));
        CheckBox checkBox6 = new CheckBox(this);
        this.lkawmdvznv = checkBox6;
        checkBox6.setLayoutParams(new LinearLayout.LayoutParams(GattClient.STATE_PREPARED, 1035));
        this.lkawmdvznv.setPadding(144, 99, 64, 83);
        linearLayout.addView(this.lkawmdvznv);
        this.lkawmdvznv.setBackgroundColor(Color.parseColor("#3b375b"));
        FrameLayout frameLayout7 = new FrameLayout(this);
        this.gqnxrytsag = frameLayout7;
        frameLayout7.setLayoutParams(new LinearLayout.LayoutParams(1353, TypedValues.MotionType.TYPE_QUANTIZE_INTERPOLATOR_ID));
        this.gqnxrytsag.setPadding(38, 81, 174, 74);
        linearLayout.addView(this.gqnxrytsag);
        this.gqnxrytsag.setBackgroundColor(Color.parseColor("#02f690"));
        Button button4 = new Button(this);
        this.hldonerjfc = button4;
        button4.setLayoutParams(new LinearLayout.LayoutParams(116, 311));
        this.hldonerjfc.setPadding(96, 14, 45, BDLocation.TypeServerError);
        linearLayout.addView(this.hldonerjfc);
        this.hldonerjfc.setBackgroundColor(Color.parseColor("#0216e0"));
        LinearLayout linearLayout9 = new LinearLayout(this);
        this.cpdjpoajon = linearLayout9;
        linearLayout9.setLayoutParams(new LinearLayout.LayoutParams(1982, 743));
        this.cpdjpoajon.setPadding(100, 187, 61, 1);
        linearLayout.addView(this.cpdjpoajon);
        this.cpdjpoajon.setBackgroundColor(Color.parseColor("#26c318"));
        ListView listView4 = new ListView(this);
        this.vjfqtsmvax = listView4;
        listView4.setLayoutParams(new LinearLayout.LayoutParams(1354, 866));
        this.vjfqtsmvax.setPadding(191, 50, 121, 78);
        linearLayout.addView(this.vjfqtsmvax);
        this.vjfqtsmvax.setBackgroundColor(Color.parseColor("#6e137a"));
        FrameLayout frameLayout8 = new FrameLayout(this);
        this.jqhmhobmyz = frameLayout8;
        frameLayout8.setLayoutParams(new LinearLayout.LayoutParams(1893, 30));
        this.jqhmhobmyz.setPadding(102, 44, 64, 183);
        linearLayout.addView(this.jqhmhobmyz);
        this.jqhmhobmyz.setBackgroundColor(Color.parseColor("#dc5dee"));
        DatePicker datePicker7 = new DatePicker(this);
        this.eubelvlbcd = datePicker7;
        datePicker7.setLayoutParams(new LinearLayout.LayoutParams(1072, 1644));
        this.eubelvlbcd.setPadding(75, 111, 56, 119);
        linearLayout.addView(this.eubelvlbcd);
        this.eubelvlbcd.setBackgroundColor(Color.parseColor("#2b8706"));
        ImageView imageView2 = new ImageView(this);
        this.vpqxxllaaj = imageView2;
        imageView2.setLayoutParams(new LinearLayout.LayoutParams(1142, 111));
        this.vpqxxllaaj.setPadding(112, 113, 13, 42);
        linearLayout.addView(this.vpqxxllaaj);
        this.vpqxxllaaj.setBackgroundColor(Color.parseColor("#3c2799"));
        ToggleButton toggleButton8 = new ToggleButton(this);
        this.rpjeyyicqb = toggleButton8;
        toggleButton8.setLayoutParams(new LinearLayout.LayoutParams(1195, 1152));
        this.rpjeyyicqb.setPadding(129, 133, 176, 15);
        linearLayout.addView(this.rpjeyyicqb);
        this.rpjeyyicqb.setBackgroundColor(Color.parseColor("#e062e1"));
        DatePicker datePicker8 = new DatePicker(this);
        this.vgotrwhrwa = datePicker8;
        datePicker8.setLayoutParams(new LinearLayout.LayoutParams(397, PointerIconCompat.TYPE_ZOOM_IN));
        this.vgotrwhrwa.setPadding(91, 88, 130, 65);
        linearLayout.addView(this.vgotrwhrwa);
        this.vgotrwhrwa.setBackgroundColor(Color.parseColor("#167fde"));
        RadioButton radioButton5 = new RadioButton(this);
        this.ofxkkntghx = radioButton5;
        radioButton5.setLayoutParams(new LinearLayout.LayoutParams(1680, 277));
        this.ofxkkntghx.setPadding(82, 72, 88, 152);
        linearLayout.addView(this.ofxkkntghx);
        this.ofxkkntghx.setBackgroundColor(Color.parseColor("#a8902c"));
        RatingBar ratingBar8 = new RatingBar(this);
        this.qcvpureqlf = ratingBar8;
        ratingBar8.setLayoutParams(new LinearLayout.LayoutParams(1338, 1593));
        this.qcvpureqlf.setPadding(BDLocation.TypeCoarseLocation, 152, 137, 119);
        linearLayout.addView(this.qcvpureqlf);
        this.qcvpureqlf.setBackgroundColor(Color.parseColor("#d0c1ff"));
        EditText editText7 = new EditText(this);
        this.tfussemgub = editText7;
        editText7.setLayoutParams(new LinearLayout.LayoutParams(1894, 618));
        this.tfussemgub.setPadding(146, 51, 12, 33);
        linearLayout.addView(this.tfussemgub);
        this.tfussemgub.setBackgroundColor(Color.parseColor("#794a74"));
        Spinner spinner3 = new Spinner(this);
        this.bauhtupvnn = spinner3;
        spinner3.setLayoutParams(new LinearLayout.LayoutParams(12, 754));
        this.bauhtupvnn.setPadding(68, 44, 85, 38);
        linearLayout.addView(this.bauhtupvnn);
        this.bauhtupvnn.setBackgroundColor(Color.parseColor("#bdf311"));
        ViewFlipper viewFlipper5 = new ViewFlipper(this);
        this.qhbdcqezqd = viewFlipper5;
        viewFlipper5.setLayoutParams(new LinearLayout.LayoutParams(486, 231));
        this.qhbdcqezqd.setPadding(44, 151, 135, 164);
        linearLayout.addView(this.qhbdcqezqd);
        this.qhbdcqezqd.setBackgroundColor(Color.parseColor("#a7a55b"));
        ToggleButton toggleButton9 = new ToggleButton(this);
        this.qaekqarybh = toggleButton9;
        toggleButton9.setLayoutParams(new LinearLayout.LayoutParams(758, 83));
        this.qaekqarybh.setPadding(27, 23, 52, 115);
        linearLayout.addView(this.qaekqarybh);
        this.qaekqarybh.setBackgroundColor(Color.parseColor("#548cea"));
        SeekBar seekBar5 = new SeekBar(this);
        this.hgozglbmxs = seekBar5;
        seekBar5.setLayoutParams(new LinearLayout.LayoutParams(1707, 274));
        this.hgozglbmxs.setPadding(111, 3, 143, 145);
        linearLayout.addView(this.hgozglbmxs);
        this.hgozglbmxs.setBackgroundColor(Color.parseColor("#1dc2fc"));
        LinearLayout linearLayout10 = new LinearLayout(this);
        this.sytkyjblzm = linearLayout10;
        linearLayout10.setLayoutParams(new LinearLayout.LayoutParams(283, 163));
        this.sytkyjblzm.setPadding(14, 47, 156, 47);
        linearLayout.addView(this.sytkyjblzm);
        this.sytkyjblzm.setBackgroundColor(Color.parseColor("#b175b1"));
        ImageView imageView3 = new ImageView(this);
        this.gfleflojsc = imageView3;
        imageView3.setLayoutParams(new LinearLayout.LayoutParams(643, 134));
        this.gfleflojsc.setPadding(13, 52, 182, 134);
        linearLayout.addView(this.gfleflojsc);
        this.gfleflojsc.setBackgroundColor(Color.parseColor("#a5d443"));
        ScrollView scrollView6 = new ScrollView(this);
        this.rvwbdqwsux = scrollView6;
        scrollView6.setLayoutParams(new LinearLayout.LayoutParams(786, 1430));
        this.rvwbdqwsux.setPadding(118, 21, 150, 154);
        linearLayout.addView(this.rvwbdqwsux);
        this.rvwbdqwsux.setBackgroundColor(Color.parseColor("#4a68be"));
        RadioButton radioButton6 = new RadioButton(this);
        this.diatnmxltt = radioButton6;
        radioButton6.setLayoutParams(new LinearLayout.LayoutParams(1789, 1452));
        this.diatnmxltt.setPadding(135, 198, 180, 42);
        linearLayout.addView(this.diatnmxltt);
        this.diatnmxltt.setBackgroundColor(Color.parseColor("#9163b6"));
        RadioButton radioButton7 = new RadioButton(this);
        this.ndnjtyidkx = radioButton7;
        radioButton7.setLayoutParams(new LinearLayout.LayoutParams(147, 1064));
        this.ndnjtyidkx.setPadding(119, 57, 22, 96);
        linearLayout.addView(this.ndnjtyidkx);
        this.ndnjtyidkx.setBackgroundColor(Color.parseColor("#069b22"));
        RadioButton radioButton8 = new RadioButton(this);
        this.cdaftfdkcc = radioButton8;
        radioButton8.setLayoutParams(new LinearLayout.LayoutParams(569, 260));
        this.cdaftfdkcc.setPadding(147, 104, 63, 51);
        linearLayout.addView(this.cdaftfdkcc);
        this.cdaftfdkcc.setBackgroundColor(Color.parseColor("#8a0a53"));
        EditText editText8 = new EditText(this);
        this.hhezixtdff = editText8;
        editText8.setLayoutParams(new LinearLayout.LayoutParams(680, 591));
        this.hhezixtdff.setPadding(6, 1, 58, 71);
        linearLayout.addView(this.hhezixtdff);
        this.hhezixtdff.setBackgroundColor(Color.parseColor("#f767a9"));
        RelativeLayout relativeLayout8 = new RelativeLayout(this);
        this.tuemdkdajz = relativeLayout8;
        relativeLayout8.setLayoutParams(new LinearLayout.LayoutParams(603, 427));
        this.tuemdkdajz.setPadding(134, 186, 52, 150);
        linearLayout.addView(this.tuemdkdajz);
        this.tuemdkdajz.setBackgroundColor(Color.parseColor("#05c5ff"));
        Spinner spinner4 = new Spinner(this);
        this.yccbxopuze = spinner4;
        spinner4.setLayoutParams(new LinearLayout.LayoutParams(670, TypedValues.TransitionType.TYPE_DURATION));
        this.yccbxopuze.setPadding(51, 26, 79, 78);
        linearLayout.addView(this.yccbxopuze);
        this.yccbxopuze.setBackgroundColor(Color.parseColor("#1b6e0f"));
        TableLayout tableLayout6 = new TableLayout(this);
        this.fymdfyhbft = tableLayout6;
        tableLayout6.setLayoutParams(new LinearLayout.LayoutParams(1337, 1558));
        this.fymdfyhbft.setPadding(59, 176, 123, 135);
        linearLayout.addView(this.fymdfyhbft);
        this.fymdfyhbft.setBackgroundColor(Color.parseColor("#0acb90"));
        Switch r27 = new Switch(this);
        this.diibmbpipq = r27;
        r27.setLayoutParams(new LinearLayout.LayoutParams(1154, 1050));
        this.diibmbpipq.setPadding(177, 68, 112, 118);
        linearLayout.addView(this.diibmbpipq);
        this.diibmbpipq.setBackgroundColor(Color.parseColor("#77fc50"));
        ViewFlipper viewFlipper6 = new ViewFlipper(this);
        this.trrmcknbse = viewFlipper6;
        viewFlipper6.setLayoutParams(new LinearLayout.LayoutParams(1833, 1380));
        this.trrmcknbse.setPadding(195, 71, 39, 163);
        linearLayout.addView(this.trrmcknbse);
        this.trrmcknbse.setBackgroundColor(Color.parseColor("#678f5c"));
        RadioButton radioButton9 = new RadioButton(this);
        this.dnnwynmmrm = radioButton9;
        radioButton9.setLayoutParams(new LinearLayout.LayoutParams(757, 747));
        this.dnnwynmmrm.setPadding(82, 57, 95, 155);
        linearLayout.addView(this.dnnwynmmrm);
        this.dnnwynmmrm.setBackgroundColor(Color.parseColor("#5e7a7b"));
        RadioButton radioButton10 = new RadioButton(this);
        this.vvicsfwmyq = radioButton10;
        radioButton10.setLayoutParams(new LinearLayout.LayoutParams(1204, 1934));
        this.vvicsfwmyq.setPadding(156, 46, 124, 59);
        linearLayout.addView(this.vvicsfwmyq);
        this.vvicsfwmyq.setBackgroundColor(Color.parseColor("#141289"));
        ListView listView5 = new ListView(this);
        this.krxmelpzlk = listView5;
        listView5.setLayoutParams(new LinearLayout.LayoutParams(1305, TypedValues.MotionType.TYPE_DRAW_PATH));
        this.krxmelpzlk.setPadding(4, 148, 50, 171);
        linearLayout.addView(this.krxmelpzlk);
        this.krxmelpzlk.setBackgroundColor(Color.parseColor("#20c180"));
        DatePicker datePicker9 = new DatePicker(this);
        this.gocltnhbcd = datePicker9;
        datePicker9.setLayoutParams(new LinearLayout.LayoutParams(935, 1401));
        this.gocltnhbcd.setPadding(195, 85, 168, 34);
        linearLayout.addView(this.gocltnhbcd);
        this.gocltnhbcd.setBackgroundColor(Color.parseColor("#66dcbf"));
        EditText editText9 = new EditText(this);
        this.uirqylwria = editText9;
        editText9.setLayoutParams(new LinearLayout.LayoutParams(83, 561));
        this.uirqylwria.setPadding(144, 149, 8, 92);
        linearLayout.addView(this.uirqylwria);
        this.uirqylwria.setBackgroundColor(Color.parseColor("#779f80"));
        EditText editText10 = new EditText(this);
        this.ieccldnida = editText10;
        editText10.setLayoutParams(new LinearLayout.LayoutParams(637, 209));
        this.ieccldnida.setPadding(50, 40, 195, 132);
        linearLayout.addView(this.ieccldnida);
        this.ieccldnida.setBackgroundColor(Color.parseColor("#b42bf8"));
        EditText editText11 = new EditText(this);
        this.fmbjgxjvin = editText11;
        editText11.setLayoutParams(new LinearLayout.LayoutParams(1303, 1536));
        this.fmbjgxjvin.setPadding(173, 114, 139, 144);
        linearLayout.addView(this.fmbjgxjvin);
        this.fmbjgxjvin.setBackgroundColor(Color.parseColor("#217d96"));
        LinearLayout linearLayout11 = new LinearLayout(this);
        this.xdejcyzoem = linearLayout11;
        linearLayout11.setLayoutParams(new LinearLayout.LayoutParams(87, 1838));
        this.xdejcyzoem.setPadding(11, 147, 104, 40);
        linearLayout.addView(this.xdejcyzoem);
        this.xdejcyzoem.setBackgroundColor(Color.parseColor("#abb81c"));
        FrameLayout frameLayout9 = new FrameLayout(this);
        this.sxufbljfrn = frameLayout9;
        frameLayout9.setLayoutParams(new LinearLayout.LayoutParams(1695, 760));
        this.sxufbljfrn.setPadding(170, 190, 4, 115);
        linearLayout.addView(this.sxufbljfrn);
        this.sxufbljfrn.setBackgroundColor(Color.parseColor("#c360ea"));
        FrameLayout frameLayout10 = new FrameLayout(this);
        this.xughnhzwyy = frameLayout10;
        frameLayout10.setLayoutParams(new LinearLayout.LayoutParams(1925, 1762));
        this.xughnhzwyy.setPadding(139, 46, 187, 190);
        linearLayout.addView(this.xughnhzwyy);
        this.xughnhzwyy.setBackgroundColor(Color.parseColor("#672b29"));
        TextView textView6 = new TextView(this);
        this.fpxuqfoqvf = textView6;
        textView6.setLayoutParams(new LinearLayout.LayoutParams(53, 1602));
        this.fpxuqfoqvf.setPadding(138, 5, 42, 81);
        linearLayout.addView(this.fpxuqfoqvf);
        this.fpxuqfoqvf.setBackgroundColor(Color.parseColor("#def20a"));
        FrameLayout frameLayout11 = new FrameLayout(this);
        this.gszowwirwv = frameLayout11;
        frameLayout11.setLayoutParams(new LinearLayout.LayoutParams(1338, 567));
        this.gszowwirwv.setPadding(104, 89, 97, 49);
        linearLayout.addView(this.gszowwirwv);
        this.gszowwirwv.setBackgroundColor(Color.parseColor("#73c3c0"));
        GridView gridView3 = new GridView(this);
        this.icaxupproa = gridView3;
        gridView3.setLayoutParams(new LinearLayout.LayoutParams(1668, 1805));
        this.icaxupproa.setPadding(70, 28, 132, 36);
        linearLayout.addView(this.icaxupproa);
        this.icaxupproa.setBackgroundColor(Color.parseColor("#1255f8"));
        ScrollView scrollView7 = new ScrollView(this);
        this.kmwkjewgze = scrollView7;
        scrollView7.setLayoutParams(new LinearLayout.LayoutParams(220, 579));
        this.kmwkjewgze.setPadding(156, 135, 35, 156);
        linearLayout.addView(this.kmwkjewgze);
        this.kmwkjewgze.setBackgroundColor(Color.parseColor("#158e4c"));
        EditText editText12 = new EditText(this);
        this.fsupuzvalf = editText12;
        editText12.setLayoutParams(new LinearLayout.LayoutParams(876, 676));
        this.fsupuzvalf.setPadding(152, 3, 26, 195);
        linearLayout.addView(this.fsupuzvalf);
        this.fsupuzvalf.setBackgroundColor(Color.parseColor("#a91e17"));
        ToggleButton toggleButton10 = new ToggleButton(this);
        this.lbakgomdxw = toggleButton10;
        toggleButton10.setLayoutParams(new LinearLayout.LayoutParams(1858, 247));
        this.lbakgomdxw.setPadding(177, 109, 4, 31);
        linearLayout.addView(this.lbakgomdxw);
        this.lbakgomdxw.setBackgroundColor(Color.parseColor("#4e6c68"));
        CheckBox checkBox7 = new CheckBox(this);
        this.vqdekbpuvl = checkBox7;
        checkBox7.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.AttributesType.TYPE_PATH_ROTATE, 1835));
        this.vqdekbpuvl.setPadding(26, 149, 33, 130);
        linearLayout.addView(this.vqdekbpuvl);
        this.vqdekbpuvl.setBackgroundColor(Color.parseColor("#894b9f"));
        ViewFlipper viewFlipper7 = new ViewFlipper(this);
        this.nimrvypjsc = viewFlipper7;
        viewFlipper7.setLayoutParams(new LinearLayout.LayoutParams(390, 1082));
        this.nimrvypjsc.setPadding(20, 99, 198, 105);
        linearLayout.addView(this.nimrvypjsc);
        this.nimrvypjsc.setBackgroundColor(Color.parseColor("#90a898"));
        TextView textView7 = new TextView(this);
        this.wpkzvokxjb = textView7;
        textView7.setLayoutParams(new LinearLayout.LayoutParams(1078, 513));
        this.wpkzvokxjb.setPadding(51, 62, 36, 159);
        linearLayout.addView(this.wpkzvokxjb);
        this.wpkzvokxjb.setBackgroundColor(Color.parseColor("#eaa39b"));
        SeekBar seekBar6 = new SeekBar(this);
        this.foondwzozu = seekBar6;
        seekBar6.setLayoutParams(new LinearLayout.LayoutParams(593, 385));
        this.foondwzozu.setPadding(75, 113, 170, 86);
        linearLayout.addView(this.foondwzozu);
        this.foondwzozu.setBackgroundColor(Color.parseColor("#2723be"));
        ToggleButton toggleButton11 = new ToggleButton(this);
        this.mmevyymegt = toggleButton11;
        toggleButton11.setLayoutParams(new LinearLayout.LayoutParams(1327, 1421));
        this.mmevyymegt.setPadding(51, 122, 93, 194);
        linearLayout.addView(this.mmevyymegt);
        this.mmevyymegt.setBackgroundColor(Color.parseColor("#c859b4"));
        DatePicker datePicker10 = new DatePicker(this);
        this.nzoepioryo = datePicker10;
        datePicker10.setLayoutParams(new LinearLayout.LayoutParams(450, 1081));
        this.nzoepioryo.setPadding(87, 113, 198, 121);
        linearLayout.addView(this.nzoepioryo);
        this.nzoepioryo.setBackgroundColor(Color.parseColor("#6635ad"));
        Button button5 = new Button(this);
        this.iisqbonyho = button5;
        button5.setLayoutParams(new LinearLayout.LayoutParams(1453, 228));
        this.iisqbonyho.setPadding(43, 139, 114, 26);
        linearLayout.addView(this.iisqbonyho);
        this.iisqbonyho.setBackgroundColor(Color.parseColor("#c80530"));
        RelativeLayout relativeLayout9 = new RelativeLayout(this);
        this.chijeajxcz = relativeLayout9;
        relativeLayout9.setLayoutParams(new LinearLayout.LayoutParams(1560, 1369));
        this.chijeajxcz.setPadding(90, 122, 77, 74);
        linearLayout.addView(this.chijeajxcz);
        this.chijeajxcz.setBackgroundColor(Color.parseColor("#abacb7"));
        ViewFlipper viewFlipper8 = new ViewFlipper(this);
        this.lznfzsgekz = viewFlipper8;
        viewFlipper8.setLayoutParams(new LinearLayout.LayoutParams(120, 32));
        this.lznfzsgekz.setPadding(15, 26, 105, 22);
        linearLayout.addView(this.lznfzsgekz);
        this.lznfzsgekz.setBackgroundColor(Color.parseColor("#85f065"));
        CheckBox checkBox8 = new CheckBox(this);
        this.vvsqgioslt = checkBox8;
        checkBox8.setLayoutParams(new LinearLayout.LayoutParams(1923, 724));
        this.vvsqgioslt.setPadding(67, 146, 108, 64);
        linearLayout.addView(this.vvsqgioslt);
        this.vvsqgioslt.setBackgroundColor(Color.parseColor("#b958b1"));
        CheckBox checkBox9 = new CheckBox(this);
        this.webyecffjx = checkBox9;
        checkBox9.setLayoutParams(new LinearLayout.LayoutParams(1402, 568));
        this.webyecffjx.setPadding(28, 148, 173, 40);
        linearLayout.addView(this.webyecffjx);
        this.webyecffjx.setBackgroundColor(Color.parseColor("#02d515"));
        RatingBar ratingBar9 = new RatingBar(this);
        this.auizwegwnw = ratingBar9;
        ratingBar9.setLayoutParams(new LinearLayout.LayoutParams(440, 499));
        this.auizwegwnw.setPadding(134, 113, 15, 5);
        linearLayout.addView(this.auizwegwnw);
        this.auizwegwnw.setBackgroundColor(Color.parseColor("#ec01eb"));
        GridView gridView4 = new GridView(this);
        this.fvjiwciqlo = gridView4;
        gridView4.setLayoutParams(new LinearLayout.LayoutParams(991, 45));
        this.fvjiwciqlo.setPadding(11, 69, 119, 130);
        linearLayout.addView(this.fvjiwciqlo);
        this.fvjiwciqlo.setBackgroundColor(Color.parseColor("#bcb705"));
        ScrollView scrollView8 = new ScrollView(this);
        this.obklocjfqd = scrollView8;
        scrollView8.setLayoutParams(new LinearLayout.LayoutParams(1819, WebSocketProtocol.PAYLOAD_SHORT));
        this.obklocjfqd.setPadding(101, 43, 136, 72);
        linearLayout.addView(this.obklocjfqd);
        this.obklocjfqd.setBackgroundColor(Color.parseColor("#f78fd5"));
        Button button6 = new Button(this);
        this.siobthzvyl = button6;
        button6.setLayoutParams(new LinearLayout.LayoutParams(1558, 1642));
        this.siobthzvyl.setPadding(52, 6, 47, 35);
        linearLayout.addView(this.siobthzvyl);
        this.siobthzvyl.setBackgroundColor(Color.parseColor("#c3a0c1"));
        ProgressBar progressBar7 = new ProgressBar(this);
        this.dvpprkrbhl = progressBar7;
        progressBar7.setLayoutParams(new LinearLayout.LayoutParams(19, 914));
        this.dvpprkrbhl.setPadding(43, 165, 185, 149);
        linearLayout.addView(this.dvpprkrbhl);
        this.dvpprkrbhl.setBackgroundColor(Color.parseColor("#aa5baa"));
        LinearLayout linearLayout12 = new LinearLayout(this);
        this.gfkhmhqvml = linearLayout12;
        linearLayout12.setLayoutParams(new LinearLayout.LayoutParams(1967, 338));
        this.gfkhmhqvml.setPadding(156, 145, 25, 25);
        linearLayout.addView(this.gfkhmhqvml);
        this.gfkhmhqvml.setBackgroundColor(Color.parseColor("#7aebcd"));
        LinearLayout linearLayout13 = new LinearLayout(this);
        this.hzaxjxxxqm = linearLayout13;
        linearLayout13.setLayoutParams(new LinearLayout.LayoutParams(1466, 1770));
        this.hzaxjxxxqm.setPadding(12, 182, 94, 150);
        linearLayout.addView(this.hzaxjxxxqm);
        this.hzaxjxxxqm.setBackgroundColor(Color.parseColor("#fd0240"));
        TextView textView8 = new TextView(this);
        this.klkzvzgvoi = textView8;
        textView8.setLayoutParams(new LinearLayout.LayoutParams(1756, 1284));
        this.klkzvzgvoi.setPadding(73, 99, 57, 184);
        linearLayout.addView(this.klkzvzgvoi);
        this.klkzvzgvoi.setBackgroundColor(Color.parseColor("#1eabc8"));
        LinearLayout linearLayout14 = new LinearLayout(this);
        this.ovwhntvifn = linearLayout14;
        linearLayout14.setLayoutParams(new LinearLayout.LayoutParams(459, 458));
        this.ovwhntvifn.setPadding(15, 182, 117, 140);
        linearLayout.addView(this.ovwhntvifn);
        this.ovwhntvifn.setBackgroundColor(Color.parseColor("#c10b16"));
        ProgressBar progressBar8 = new ProgressBar(this);
        this.hfoptugsiz = progressBar8;
        progressBar8.setLayoutParams(new LinearLayout.LayoutParams(1681, 521));
        this.hfoptugsiz.setPadding(33, 47, 136, 24);
        linearLayout.addView(this.hfoptugsiz);
        this.hfoptugsiz.setBackgroundColor(Color.parseColor("#4173ef"));
        GridView gridView5 = new GridView(this);
        this.huhsjqsfma = gridView5;
        gridView5.setLayoutParams(new LinearLayout.LayoutParams(482, 1869));
        this.huhsjqsfma.setPadding(140, BDLocation.TypeCoarseLocation, 54, 108);
        linearLayout.addView(this.huhsjqsfma);
        this.huhsjqsfma.setBackgroundColor(Color.parseColor("#495af4"));
        LinearLayout linearLayout15 = new LinearLayout(this);
        this.qrbvqlwdtx = linearLayout15;
        linearLayout15.setLayoutParams(new LinearLayout.LayoutParams(180, 1826));
        this.qrbvqlwdtx.setPadding(39, 40, 189, 2);
        linearLayout.addView(this.qrbvqlwdtx);
        this.qrbvqlwdtx.setBackgroundColor(Color.parseColor("#08e1fd"));
        ListView listView6 = new ListView(this);
        this.cjnybuhknq = listView6;
        listView6.setLayoutParams(new LinearLayout.LayoutParams(1312, 1213));
        this.cjnybuhknq.setPadding(182, 187, 179, 29);
        linearLayout.addView(this.cjnybuhknq);
        this.cjnybuhknq.setBackgroundColor(Color.parseColor("#c0ee7e"));
        RadioButton radioButton11 = new RadioButton(this);
        this.nacnxwehzj = radioButton11;
        radioButton11.setLayoutParams(new LinearLayout.LayoutParams(62, 1677));
        this.nacnxwehzj.setPadding(102, 6, 197, BDLocation.TypeNetWorkLocation);
        linearLayout.addView(this.nacnxwehzj);
        this.nacnxwehzj.setBackgroundColor(Color.parseColor("#e36ab0"));
        RelativeLayout relativeLayout10 = new RelativeLayout(this);
        this.tcpmkbqssy = relativeLayout10;
        relativeLayout10.setLayoutParams(new LinearLayout.LayoutParams(1173, 1050));
        this.tcpmkbqssy.setPadding(3, 35, 50, 47);
        linearLayout.addView(this.tcpmkbqssy);
        this.tcpmkbqssy.setBackgroundColor(Color.parseColor("#4ce4aa"));
        DatePicker datePicker11 = new DatePicker(this);
        this.htcsnchjaj = datePicker11;
        datePicker11.setLayoutParams(new LinearLayout.LayoutParams(1608, 1824));
        this.htcsnchjaj.setPadding(101, 94, 156, 75);
        linearLayout.addView(this.htcsnchjaj);
        this.htcsnchjaj.setBackgroundColor(Color.parseColor("#740f34"));
        ScrollView scrollView9 = new ScrollView(this);
        this.ouxdvvosru = scrollView9;
        scrollView9.setLayoutParams(new LinearLayout.LayoutParams(1333, 192));
        this.ouxdvvosru.setPadding(56, 3, 87, 109);
        linearLayout.addView(this.ouxdvvosru);
        this.ouxdvvosru.setBackgroundColor(Color.parseColor("#b0ca67"));
        TextView textView9 = new TextView(this);
        this.hrhufrvomx = textView9;
        textView9.setLayoutParams(new LinearLayout.LayoutParams(1008, 492));
        this.hrhufrvomx.setPadding(58, 86, 122, 88);
        linearLayout.addView(this.hrhufrvomx);
        this.hrhufrvomx.setBackgroundColor(Color.parseColor("#e76186"));
    }
}
