package com.smartapp.b.phlralecvk;

import android.app.Activity;
import android.graphics.Color;
import android.os.Bundle;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.CheckBox;
import android.widget.DatePicker;
import android.widget.EditText;
import android.widget.GridView;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ListView;
import android.widget.ProgressBar;
import android.widget.RadioButton;
import android.widget.RatingBar;
import android.widget.RelativeLayout;
import android.widget.ScrollView;
import android.widget.SeekBar;
import android.widget.Spinner;
import android.widget.Switch;
import android.widget.TableLayout;
import android.widget.TextView;
import android.widget.TimePicker;
import android.widget.ToggleButton;
import android.widget.ViewFlipper;
import androidx.core.app.FrameMetricsAggregator;
import com.baidu.location.BDLocation;
import com.haibin.calendarview.BuildConfig;
import com.king.zxing.util.CodeUtils;
import com.luck.picture.lib.config.Crop;
import com.luck.picture.lib.config.PictureConfig;
import com.realsil.sdk.core.bluetooth.connection.le.GattClient;
import com.realsil.sdk.core.bluetooth.impl.BluetoothClassImpl;
import okhttp3.internal.ws.WebSocketProtocol;

/* loaded from: classes4.dex */
public class HazouvnhxrdActivity extends Activity {
    EditText ammybogbvf;
    Button amwfhtjyky;
    RatingBar atgxngzera;
    CheckBox aycuetgthf;
    Button cbanjouvnu;
    ImageView cbmruepcvr;
    Switch cpuhoewlrj;
    TimePicker cudydtprlq;
    TableLayout dqltffuadw;
    ListView dsaxovhwbl;
    TextView eaboqchdff;
    ViewFlipper ebhlclzavk;
    RadioButton ebvzbenlwc;
    TableLayout ebzrfpbcrd;
    DatePicker eqggdnfpwy;
    ViewFlipper ghflhvheoj;
    TableLayout gidcomznjl;
    Spinner gpwkofdtld;
    RadioButton gxefsmzxjh;
    RatingBar hcrysniioe;
    RelativeLayout hdmzrvmenz;
    DatePicker hkzsykujze;
    RadioButton hmftxdjapr;
    CheckBox hnmlgispek;
    ScrollView hyaufveurk;
    Button ihquqktdjt;
    TimePicker ivoufefajg;
    CheckBox jaxvalzxhg;
    TableLayout jhbwozbcgv;
    CheckBox jipmilddaw;
    SeekBar jjmhrwivwb;
    TimePicker jmstaubqna;
    Button jvjfgudqjm;
    RelativeLayout kgeuwwvbzv;
    SeekBar kmooaflbcb;
    ProgressBar kuzlfmvehn;
    ScrollView kvrowzcqbq;
    TableLayout lxapvckdwz;
    DatePicker lzfcdfppai;
    GridView mduybjlboc;
    ProgressBar mqnvzyfdqx;
    DatePicker nfjhjwsjwl;
    GridView nulxocskjw;
    Spinner ofvutbsrcj;
    ProgressBar oselffilvs;
    RelativeLayout owewuwxkpk;
    ProgressBar pavyzdrkzu;
    Button piohdbxqpb;
    RatingBar purvqtgfzo;
    Spinner qamaoffdkw;
    RadioButton qchnxstopy;
    LinearLayout qfyfezxixi;
    ViewFlipper qqtgjxdblu;
    RelativeLayout qymwuvdgyw;
    ScrollView rlvmbxqnwx;
    TableLayout rybecprbwm;
    RadioButton ryrmjkdeag;
    EditText sqvlnjfsbm;
    ImageView swyxzxbqdv;
    CheckBox tqgqrrqakh;
    Button txixywixuq;
    ProgressBar tyxunygabl;
    Button uksbrwgbbz;
    DatePicker urbbqfxlem;
    TextView uyywvwdlhq;
    LinearLayout uzeloniowm;
    LinearLayout vnuercmnvu;
    ViewFlipper vovwaqkblk;
    TableLayout vytjzbexhx;
    CheckBox wbesxsjcfj;
    TimePicker wbyaomfqkr;
    Switch wpfgdxsmgv;
    RadioButton wtjpayqyzj;
    EditText wynjhhrqqx;
    ImageView xfvirqgjhv;
    ToggleButton xkybdthpiu;
    RelativeLayout xnzzrymsuq;
    RadioButton xpsnfkdjrj;
    RelativeLayout xuaihezphu;
    ScrollView xwwzvwgjhn;
    TextView yagbftlrks;
    TableLayout ybubekdolr;
    TableLayout yypucmmyey;
    ViewFlipper yzirlzzmts;
    RelativeLayout zkqsicmkvp;
    RelativeLayout ztyswsgpbo;
    Switch zuyestwrdb;
    TextView zwidduxobk;

    @Override // android.app.Activity
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        LinearLayout linearLayout = new LinearLayout(this);
        setContentView(linearLayout);
        linearLayout.setLayoutParams(new ViewGroup.LayoutParams(-1, -1));
        linearLayout.setOrientation(1);
        linearLayout.setBackgroundColor(Color.parseColor("#f75575"));
        TextView textView = new TextView(this);
        this.uyywvwdlhq = textView;
        textView.setLayoutParams(new LinearLayout.LayoutParams(1979, 460));
        this.uyywvwdlhq.setPadding(123, 16, BDLocation.TypeNetWorkLocation, 26);
        linearLayout.addView(this.uyywvwdlhq);
        this.uyywvwdlhq.setBackgroundColor(Color.parseColor("#b95c5e"));
        RadioButton radioButton = new RadioButton(this);
        this.wtjpayqyzj = radioButton;
        radioButton.setLayoutParams(new LinearLayout.LayoutParams(90, 1830));
        this.wtjpayqyzj.setPadding(107, 178, 96, 38);
        linearLayout.addView(this.wtjpayqyzj);
        this.wtjpayqyzj.setBackgroundColor(Color.parseColor("#38afeb"));
        TableLayout tableLayout = new TableLayout(this);
        this.vytjzbexhx = tableLayout;
        tableLayout.setLayoutParams(new LinearLayout.LayoutParams(1566, 1104));
        this.vytjzbexhx.setPadding(65, 39, 179, 44);
        linearLayout.addView(this.vytjzbexhx);
        this.vytjzbexhx.setBackgroundColor(Color.parseColor("#fc42e6"));
        TableLayout tableLayout2 = new TableLayout(this);
        this.lxapvckdwz = tableLayout2;
        tableLayout2.setLayoutParams(new LinearLayout.LayoutParams(1023, 1232));
        this.lxapvckdwz.setPadding(113, 175, 110, 21);
        linearLayout.addView(this.lxapvckdwz);
        this.lxapvckdwz.setBackgroundColor(Color.parseColor("#7eb04a"));
        DatePicker datePicker = new DatePicker(this);
        this.urbbqfxlem = datePicker;
        datePicker.setLayoutParams(new LinearLayout.LayoutParams(1929, 1929));
        this.urbbqfxlem.setPadding(81, 56, 127, BDLocation.TypeNetWorkLocation);
        linearLayout.addView(this.urbbqfxlem);
        this.urbbqfxlem.setBackground(new Cyjtloebehf());
        ImageView imageView = new ImageView(this);
        this.cbmruepcvr = imageView;
        imageView.setLayoutParams(new LinearLayout.LayoutParams(995, GattClient.STATE_READ_PROTOCOL_TYPE));
        this.cbmruepcvr.setPadding(189, 60, 77, 54);
        linearLayout.addView(this.cbmruepcvr);
        this.cbmruepcvr.setBackgroundColor(Color.parseColor("#4a11c4"));
        Button button = new Button(this);
        this.ihquqktdjt = button;
        button.setLayoutParams(new LinearLayout.LayoutParams(53, 93));
        this.ihquqktdjt.setPadding(67, 52, BDLocation.TypeServerError, 122);
        linearLayout.addView(this.ihquqktdjt);
        this.ihquqktdjt.setBackgroundColor(Color.parseColor("#40e60d"));
        CheckBox checkBox = new CheckBox(this);
        this.aycuetgthf = checkBox;
        checkBox.setLayoutParams(new LinearLayout.LayoutParams(852, 1014));
        this.aycuetgthf.setPadding(73, 35, 134, 197);
        linearLayout.addView(this.aycuetgthf);
        this.aycuetgthf.setBackgroundColor(Color.parseColor("#5e4285"));
        RatingBar ratingBar = new RatingBar(this);
        this.atgxngzera = ratingBar;
        ratingBar.setLayoutParams(new LinearLayout.LayoutParams(85, 815));
        this.atgxngzera.setPadding(33, 158, 0, 56);
        linearLayout.addView(this.atgxngzera);
        this.atgxngzera.setBackgroundColor(Color.parseColor("#6cd58b"));
        Button button2 = new Button(this);
        this.jvjfgudqjm = button2;
        button2.setLayoutParams(new LinearLayout.LayoutParams(1100, 310));
        this.jvjfgudqjm.setPadding(190, 117, 71, 2);
        linearLayout.addView(this.jvjfgudqjm);
        this.jvjfgudqjm.setBackgroundColor(Color.parseColor("#3dfe95"));
        GridView gridView = new GridView(this);
        this.nulxocskjw = gridView;
        gridView.setLayoutParams(new LinearLayout.LayoutParams(677, 1536));
        this.nulxocskjw.setPadding(51, 197, 74, 196);
        linearLayout.addView(this.nulxocskjw);
        this.nulxocskjw.setBackgroundColor(Color.parseColor("#883caf"));
        ToggleButton toggleButton = new ToggleButton(this);
        this.xkybdthpiu = toggleButton;
        toggleButton.setLayoutParams(new LinearLayout.LayoutParams(1253, 1745));
        this.xkybdthpiu.setPadding(163, 95, 185, 11);
        linearLayout.addView(this.xkybdthpiu);
        this.xkybdthpiu.setBackgroundColor(Color.parseColor("#65297b"));
        Button button3 = new Button(this);
        this.piohdbxqpb = button3;
        button3.setLayoutParams(new LinearLayout.LayoutParams(1526, 660));
        this.piohdbxqpb.setPadding(171, 166, 4, 73);
        linearLayout.addView(this.piohdbxqpb);
        this.piohdbxqpb.setBackgroundColor(Color.parseColor("#4779b7"));
        Button button4 = new Button(this);
        this.amwfhtjyky = button4;
        button4.setLayoutParams(new LinearLayout.LayoutParams(1011, 205));
        this.amwfhtjyky.setPadding(58, 79, 39, 60);
        linearLayout.addView(this.amwfhtjyky);
        this.amwfhtjyky.setBackgroundColor(Color.parseColor("#f76dd9"));
        ProgressBar progressBar = new ProgressBar(this);
        this.oselffilvs = progressBar;
        progressBar.setLayoutParams(new LinearLayout.LayoutParams(574, 739));
        this.oselffilvs.setPadding(49, 113, 11, 40);
        linearLayout.addView(this.oselffilvs);
        this.oselffilvs.setBackgroundColor(Color.parseColor("#70ab92"));
        RatingBar ratingBar2 = new RatingBar(this);
        this.purvqtgfzo = ratingBar2;
        ratingBar2.setLayoutParams(new LinearLayout.LayoutParams(596, 451));
        this.purvqtgfzo.setPadding(84, 180, 132, 64);
        linearLayout.addView(this.purvqtgfzo);
        this.purvqtgfzo.setBackgroundColor(Color.parseColor("#6245b6"));
        RelativeLayout relativeLayout = new RelativeLayout(this);
        this.hdmzrvmenz = relativeLayout;
        relativeLayout.setLayoutParams(new LinearLayout.LayoutParams(1377, Crop.REQUEST_EDIT_CROP));
        this.hdmzrvmenz.setPadding(29, 150, 90, 166);
        linearLayout.addView(this.hdmzrvmenz);
        this.hdmzrvmenz.setBackgroundColor(Color.parseColor("#edbc7f"));
        TextView textView2 = new TextView(this);
        this.zwidduxobk = textView2;
        textView2.setLayoutParams(new LinearLayout.LayoutParams(237, 1582));
        this.zwidduxobk.setPadding(128, 33, BDLocation.TypeServerError, 75);
        linearLayout.addView(this.zwidduxobk);
        this.zwidduxobk.setBackgroundColor(Color.parseColor("#98d3f5"));
        SeekBar seekBar = new SeekBar(this);
        this.jjmhrwivwb = seekBar;
        seekBar.setLayoutParams(new LinearLayout.LayoutParams(458, 269));
        this.jjmhrwivwb.setPadding(31, 121, 20, 18);
        linearLayout.addView(this.jjmhrwivwb);
        this.jjmhrwivwb.setBackgroundColor(Color.parseColor("#92f823"));
        RelativeLayout relativeLayout2 = new RelativeLayout(this);
        this.kgeuwwvbzv = relativeLayout2;
        relativeLayout2.setLayoutParams(new LinearLayout.LayoutParams(1873, 955));
        this.kgeuwwvbzv.setPadding(83, 154, 16, 151);
        linearLayout.addView(this.kgeuwwvbzv);
        this.kgeuwwvbzv.setBackgroundColor(Color.parseColor("#f948c9"));
        ScrollView scrollView = new ScrollView(this);
        this.xwwzvwgjhn = scrollView;
        scrollView.setLayoutParams(new LinearLayout.LayoutParams(785, 1889));
        this.xwwzvwgjhn.setPadding(133, 191, 7, 165);
        linearLayout.addView(this.xwwzvwgjhn);
        this.xwwzvwgjhn.setBackgroundColor(Color.parseColor("#849af1"));
        RelativeLayout relativeLayout3 = new RelativeLayout(this);
        this.qymwuvdgyw = relativeLayout3;
        relativeLayout3.setLayoutParams(new LinearLayout.LayoutParams(1948, 791));
        this.qymwuvdgyw.setPadding(BDLocation.TypeCoarseLocation, 6, 3, 69);
        linearLayout.addView(this.qymwuvdgyw);
        this.qymwuvdgyw.setBackgroundColor(Color.parseColor("#edffcd"));
        TableLayout tableLayout3 = new TableLayout(this);
        this.dqltffuadw = tableLayout3;
        tableLayout3.setLayoutParams(new LinearLayout.LayoutParams(310, 1988));
        this.dqltffuadw.setPadding(83, 168, 18, 169);
        linearLayout.addView(this.dqltffuadw);
        this.dqltffuadw.setBackgroundColor(Color.parseColor("#f881e2"));
        RadioButton radioButton2 = new RadioButton(this);
        this.xpsnfkdjrj = radioButton2;
        radioButton2.setLayoutParams(new LinearLayout.LayoutParams(1875, 1685));
        this.xpsnfkdjrj.setPadding(56, 148, 91, 23);
        linearLayout.addView(this.xpsnfkdjrj);
        this.xpsnfkdjrj.setBackgroundColor(Color.parseColor("#7be3a3"));
        TableLayout tableLayout4 = new TableLayout(this);
        this.jhbwozbcgv = tableLayout4;
        tableLayout4.setLayoutParams(new LinearLayout.LayoutParams(BuildConfig.VERSION_CODE, 1590));
        this.jhbwozbcgv.setPadding(171, 83, 198, 123);
        linearLayout.addView(this.jhbwozbcgv);
        this.jhbwozbcgv.setBackgroundColor(Color.parseColor("#55d73e"));
        TextView textView3 = new TextView(this);
        this.yagbftlrks = textView3;
        textView3.setLayoutParams(new LinearLayout.LayoutParams(1028, 1494));
        this.yagbftlrks.setPadding(112, 87, 87, 125);
        linearLayout.addView(this.yagbftlrks);
        this.yagbftlrks.setBackgroundColor(Color.parseColor("#e14491"));
        ViewFlipper viewFlipper = new ViewFlipper(this);
        this.ghflhvheoj = viewFlipper;
        viewFlipper.setLayoutParams(new LinearLayout.LayoutParams(1933, 524));
        this.ghflhvheoj.setPadding(150, 53, 54, 57);
        linearLayout.addView(this.ghflhvheoj);
        this.ghflhvheoj.setBackgroundColor(Color.parseColor("#ec01c3"));
        RelativeLayout relativeLayout4 = new RelativeLayout(this);
        this.zkqsicmkvp = relativeLayout4;
        relativeLayout4.setLayoutParams(new LinearLayout.LayoutParams(778, 1823));
        this.zkqsicmkvp.setPadding(9, 34, 31, 37);
        linearLayout.addView(this.zkqsicmkvp);
        this.zkqsicmkvp.setBackgroundColor(Color.parseColor("#fb2958"));
        ScrollView scrollView2 = new ScrollView(this);
        this.rlvmbxqnwx = scrollView2;
        scrollView2.setLayoutParams(new LinearLayout.LayoutParams(145, 1387));
        this.rlvmbxqnwx.setPadding(103, 3, 17, 101);
        linearLayout.addView(this.rlvmbxqnwx);
        this.rlvmbxqnwx.setBackgroundColor(Color.parseColor("#d20e86"));
        RadioButton radioButton3 = new RadioButton(this);
        this.ryrmjkdeag = radioButton3;
        radioButton3.setLayoutParams(new LinearLayout.LayoutParams(1785, 1399));
        this.ryrmjkdeag.setPadding(10, 189, 62, 34);
        linearLayout.addView(this.ryrmjkdeag);
        this.ryrmjkdeag.setBackgroundColor(Color.parseColor("#bb42c1"));
        RelativeLayout relativeLayout5 = new RelativeLayout(this);
        this.xuaihezphu = relativeLayout5;
        relativeLayout5.setLayoutParams(new LinearLayout.LayoutParams(1962, 619));
        this.xuaihezphu.setPadding(93, 132, 22, 193);
        linearLayout.addView(this.xuaihezphu);
        this.xuaihezphu.setBackgroundColor(Color.parseColor("#87338d"));
        ViewFlipper viewFlipper2 = new ViewFlipper(this);
        this.qqtgjxdblu = viewFlipper2;
        viewFlipper2.setLayoutParams(new LinearLayout.LayoutParams(1037, 1942));
        this.qqtgjxdblu.setPadding(86, 87, 8, 31);
        linearLayout.addView(this.qqtgjxdblu);
        this.qqtgjxdblu.setBackgroundColor(Color.parseColor("#a6bfcd"));
        TableLayout tableLayout5 = new TableLayout(this);
        this.rybecprbwm = tableLayout5;
        tableLayout5.setLayoutParams(new LinearLayout.LayoutParams(1512, 1397));
        this.rybecprbwm.setPadding(8, 33, 94, 10);
        linearLayout.addView(this.rybecprbwm);
        this.rybecprbwm.setBackgroundColor(Color.parseColor("#3c8f2b"));
        ImageView imageView2 = new ImageView(this);
        this.xfvirqgjhv = imageView2;
        imageView2.setLayoutParams(new LinearLayout.LayoutParams(334, 1256));
        this.xfvirqgjhv.setPadding(107, 27, 19, 58);
        linearLayout.addView(this.xfvirqgjhv);
        this.xfvirqgjhv.setBackgroundColor(Color.parseColor("#873048"));
        ViewFlipper viewFlipper3 = new ViewFlipper(this);
        this.ebhlclzavk = viewFlipper3;
        viewFlipper3.setLayoutParams(new LinearLayout.LayoutParams(1177, 742));
        this.ebhlclzavk.setPadding(26, 141, 165, 125);
        linearLayout.addView(this.ebhlclzavk);
        this.ebhlclzavk.setBackgroundColor(Color.parseColor("#23fdf3"));
        TableLayout tableLayout6 = new TableLayout(this);
        this.gidcomznjl = tableLayout6;
        tableLayout6.setLayoutParams(new LinearLayout.LayoutParams(1565, 1625));
        this.gidcomznjl.setPadding(56, 196, 49, 26);
        linearLayout.addView(this.gidcomznjl);
        this.gidcomznjl.setBackgroundColor(Color.parseColor("#17daf8"));
        EditText editText = new EditText(this);
        this.ammybogbvf = editText;
        editText.setLayoutParams(new LinearLayout.LayoutParams(738, 1868));
        this.ammybogbvf.setPadding(46, 6, BDLocation.TypeServerError, 13);
        linearLayout.addView(this.ammybogbvf);
        this.ammybogbvf.setBackgroundColor(Color.parseColor("#58db11"));
        Button button5 = new Button(this);
        this.cbanjouvnu = button5;
        button5.setLayoutParams(new LinearLayout.LayoutParams(1398, 1079));
        this.cbanjouvnu.setPadding(164, 49, 107, 18);
        linearLayout.addView(this.cbanjouvnu);
        this.cbanjouvnu.setBackgroundColor(Color.parseColor("#e26271"));
        TimePicker timePicker = new TimePicker(this);
        this.cudydtprlq = timePicker;
        timePicker.setLayoutParams(new LinearLayout.LayoutParams(549, 404));
        this.cudydtprlq.setPadding(147, 42, 5, 92);
        linearLayout.addView(this.cudydtprlq);
        this.cudydtprlq.setBackgroundColor(Color.parseColor("#af588b"));
        Switch r2 = new Switch(this);
        this.zuyestwrdb = r2;
        r2.setLayoutParams(new LinearLayout.LayoutParams(GattClient.STATE_READ_BATTERY_INFO, 4));
        this.zuyestwrdb.setPadding(68, 146, 62, 44);
        linearLayout.addView(this.zuyestwrdb);
        this.zuyestwrdb.setBackgroundColor(Color.parseColor("#3fe449"));
        TableLayout tableLayout7 = new TableLayout(this);
        this.ebzrfpbcrd = tableLayout7;
        tableLayout7.setLayoutParams(new LinearLayout.LayoutParams(1692, 963));
        this.ebzrfpbcrd.setPadding(168, 75, 48, 102);
        linearLayout.addView(this.ebzrfpbcrd);
        this.ebzrfpbcrd.setBackgroundColor(Color.parseColor("#54eb3c"));
        TableLayout tableLayout8 = new TableLayout(this);
        this.yypucmmyey = tableLayout8;
        tableLayout8.setLayoutParams(new LinearLayout.LayoutParams(1301, 1617));
        this.yypucmmyey.setPadding(140, 17, 153, WebSocketProtocol.PAYLOAD_SHORT);
        linearLayout.addView(this.yypucmmyey);
        this.yypucmmyey.setBackgroundColor(Color.parseColor("#80dc38"));
        Button button6 = new Button(this);
        this.uksbrwgbbz = button6;
        button6.setLayoutParams(new LinearLayout.LayoutParams(746, 1226));
        this.uksbrwgbbz.setPadding(24, 125, 99, 83);
        linearLayout.addView(this.uksbrwgbbz);
        this.uksbrwgbbz.setBackgroundColor(Color.parseColor("#227211"));
        ScrollView scrollView3 = new ScrollView(this);
        this.kvrowzcqbq = scrollView3;
        scrollView3.setLayoutParams(new LinearLayout.LayoutParams(436, 133));
        this.kvrowzcqbq.setPadding(156, 99, 43, 89);
        linearLayout.addView(this.kvrowzcqbq);
        this.kvrowzcqbq.setBackgroundColor(Color.parseColor("#aef340"));
        ViewFlipper viewFlipper4 = new ViewFlipper(this);
        this.vovwaqkblk = viewFlipper4;
        viewFlipper4.setLayoutParams(new LinearLayout.LayoutParams(1184, 1952));
        this.vovwaqkblk.setPadding(134, 131, 28, 2);
        linearLayout.addView(this.vovwaqkblk);
        this.vovwaqkblk.setBackgroundColor(Color.parseColor("#cd05d5"));
        RadioButton radioButton4 = new RadioButton(this);
        this.qchnxstopy = radioButton4;
        radioButton4.setLayoutParams(new LinearLayout.LayoutParams(1679, 4));
        this.qchnxstopy.setPadding(107, 5, 87, 94);
        linearLayout.addView(this.qchnxstopy);
        this.qchnxstopy.setBackgroundColor(Color.parseColor("#e0cc8d"));
        RelativeLayout relativeLayout6 = new RelativeLayout(this);
        this.xnzzrymsuq = relativeLayout6;
        relativeLayout6.setLayoutParams(new LinearLayout.LayoutParams(1236, 108));
        this.xnzzrymsuq.setPadding(121, 102, 170, 134);
        linearLayout.addView(this.xnzzrymsuq);
        this.xnzzrymsuq.setBackgroundColor(Color.parseColor("#983c6b"));
        ScrollView scrollView4 = new ScrollView(this);
        this.hyaufveurk = scrollView4;
        scrollView4.setLayoutParams(new LinearLayout.LayoutParams(2, 1657));
        this.hyaufveurk.setPadding(118, 16, 178, 129);
        linearLayout.addView(this.hyaufveurk);
        this.hyaufveurk.setBackgroundColor(Color.parseColor("#904019"));
        LinearLayout linearLayout2 = new LinearLayout(this);
        this.qfyfezxixi = linearLayout2;
        linearLayout2.setLayoutParams(new LinearLayout.LayoutParams(1706, 825));
        this.qfyfezxixi.setPadding(7, 23, 143, 53);
        linearLayout.addView(this.qfyfezxixi);
        this.qfyfezxixi.setBackgroundColor(Color.parseColor("#75f779"));
        RadioButton radioButton5 = new RadioButton(this);
        this.gxefsmzxjh = radioButton5;
        radioButton5.setLayoutParams(new LinearLayout.LayoutParams(199, 1870));
        this.gxefsmzxjh.setPadding(120, 166, 82, 95);
        linearLayout.addView(this.gxefsmzxjh);
        this.gxefsmzxjh.setBackgroundColor(Color.parseColor("#bbe970"));
        CheckBox checkBox2 = new CheckBox(this);
        this.jaxvalzxhg = checkBox2;
        checkBox2.setLayoutParams(new LinearLayout.LayoutParams(1774, 498));
        this.jaxvalzxhg.setPadding(68, 192, 181, 173);
        linearLayout.addView(this.jaxvalzxhg);
        this.jaxvalzxhg.setBackgroundColor(Color.parseColor("#ffb3f2"));
        GridView gridView2 = new GridView(this);
        this.mduybjlboc = gridView2;
        gridView2.setLayoutParams(new LinearLayout.LayoutParams(13, 271));
        this.mduybjlboc.setPadding(153, 27, 72, 55);
        linearLayout.addView(this.mduybjlboc);
        this.mduybjlboc.setBackgroundColor(Color.parseColor("#0d2766"));
        Button button7 = new Button(this);
        this.txixywixuq = button7;
        button7.setLayoutParams(new LinearLayout.LayoutParams(1894, 1124));
        this.txixywixuq.setPadding(179, 87, 28, 94);
        linearLayout.addView(this.txixywixuq);
        this.txixywixuq.setBackgroundColor(Color.parseColor("#8d89f9"));
        Spinner spinner = new Spinner(this);
        this.qamaoffdkw = spinner;
        spinner.setLayoutParams(new LinearLayout.LayoutParams(CodeUtils.DEFAULT_REQ_HEIGHT, 331));
        this.qamaoffdkw.setPadding(10, 5, 110, 101);
        linearLayout.addView(this.qamaoffdkw);
        this.qamaoffdkw.setBackgroundColor(Color.parseColor("#50d44c"));
        Spinner spinner2 = new Spinner(this);
        this.gpwkofdtld = spinner2;
        spinner2.setLayoutParams(new LinearLayout.LayoutParams(1059, 1535));
        this.gpwkofdtld.setPadding(74, 124, 169, 91);
        linearLayout.addView(this.gpwkofdtld);
        this.gpwkofdtld.setBackgroundColor(Color.parseColor("#b29f77"));
        EditText editText2 = new EditText(this);
        this.sqvlnjfsbm = editText2;
        editText2.setLayoutParams(new LinearLayout.LayoutParams(694, 739));
        this.sqvlnjfsbm.setPadding(142, 165, 176, 50);
        linearLayout.addView(this.sqvlnjfsbm);
        this.sqvlnjfsbm.setBackgroundColor(Color.parseColor("#f5da21"));
        ListView listView = new ListView(this);
        this.dsaxovhwbl = listView;
        listView.setLayoutParams(new LinearLayout.LayoutParams(GattClient.STATE_PREPARED, 869));
        this.dsaxovhwbl.setPadding(1, 143, 103, 130);
        linearLayout.addView(this.dsaxovhwbl);
        this.dsaxovhwbl.setBackgroundColor(Color.parseColor("#8fd147"));
        Switch r22 = new Switch(this);
        this.cpuhoewlrj = r22;
        r22.setLayoutParams(new LinearLayout.LayoutParams(334, 217));
        this.cpuhoewlrj.setPadding(10, 133, 69, 182);
        linearLayout.addView(this.cpuhoewlrj);
        this.cpuhoewlrj.setBackgroundColor(Color.parseColor("#6379cc"));
        ProgressBar progressBar2 = new ProgressBar(this);
        this.pavyzdrkzu = progressBar2;
        progressBar2.setLayoutParams(new LinearLayout.LayoutParams(463, 1290));
        this.pavyzdrkzu.setPadding(BDLocation.TypeServerDecryptError, 11, 184, 88);
        linearLayout.addView(this.pavyzdrkzu);
        this.pavyzdrkzu.setBackgroundColor(Color.parseColor("#c45239"));
        CheckBox checkBox3 = new CheckBox(this);
        this.tqgqrrqakh = checkBox3;
        checkBox3.setLayoutParams(new LinearLayout.LayoutParams(626, 963));
        this.tqgqrrqakh.setPadding(164, 192, 53, 96);
        linearLayout.addView(this.tqgqrrqakh);
        this.tqgqrrqakh.setBackgroundColor(Color.parseColor("#9698cb"));
        RatingBar ratingBar3 = new RatingBar(this);
        this.hcrysniioe = ratingBar3;
        ratingBar3.setLayoutParams(new LinearLayout.LayoutParams(1729, 1011));
        this.hcrysniioe.setPadding(97, 22, 163, 174);
        linearLayout.addView(this.hcrysniioe);
        this.hcrysniioe.setBackgroundColor(Color.parseColor("#63d533"));
        ProgressBar progressBar3 = new ProgressBar(this);
        this.kuzlfmvehn = progressBar3;
        progressBar3.setLayoutParams(new LinearLayout.LayoutParams(677, 918));
        this.kuzlfmvehn.setPadding(70, 102, 3, 33);
        linearLayout.addView(this.kuzlfmvehn);
        this.kuzlfmvehn.setBackgroundColor(Color.parseColor("#63747e"));
        LinearLayout linearLayout3 = new LinearLayout(this);
        this.uzeloniowm = linearLayout3;
        linearLayout3.setLayoutParams(new LinearLayout.LayoutParams(1677, 1448));
        this.uzeloniowm.setPadding(44, 175, 86, 111);
        linearLayout.addView(this.uzeloniowm);
        this.uzeloniowm.setBackgroundColor(Color.parseColor("#3689b8"));
        EditText editText3 = new EditText(this);
        this.wynjhhrqqx = editText3;
        editText3.setLayoutParams(new LinearLayout.LayoutParams(197, 1932));
        this.wynjhhrqqx.setPadding(35, 30, 180, 29);
        linearLayout.addView(this.wynjhhrqqx);
        this.wynjhhrqqx.setBackgroundColor(Color.parseColor("#4d8c5e"));
        DatePicker datePicker2 = new DatePicker(this);
        this.eqggdnfpwy = datePicker2;
        datePicker2.setLayoutParams(new LinearLayout.LayoutParams(663, 323));
        this.eqggdnfpwy.setPadding(178, 63, 100, 120);
        linearLayout.addView(this.eqggdnfpwy);
        this.eqggdnfpwy.setBackgroundColor(Color.parseColor("#bf0684"));
        RelativeLayout relativeLayout7 = new RelativeLayout(this);
        this.ztyswsgpbo = relativeLayout7;
        relativeLayout7.setLayoutParams(new LinearLayout.LayoutParams(984, BluetoothClassImpl.Device.PERIPHERAL_KEYBOARD));
        this.ztyswsgpbo.setPadding(134, 138, 132, BDLocation.TypeNetWorkLocation);
        linearLayout.addView(this.ztyswsgpbo);
        this.ztyswsgpbo.setBackgroundColor(Color.parseColor("#459308"));
        TimePicker timePicker2 = new TimePicker(this);
        this.jmstaubqna = timePicker2;
        timePicker2.setLayoutParams(new LinearLayout.LayoutParams(234, 767));
        this.jmstaubqna.setPadding(174, 154, 111, BDLocation.TypeCoarseLocation);
        linearLayout.addView(this.jmstaubqna);
        this.jmstaubqna.setBackgroundColor(Color.parseColor("#810c78"));
        DatePicker datePicker3 = new DatePicker(this);
        this.lzfcdfppai = datePicker3;
        datePicker3.setLayoutParams(new LinearLayout.LayoutParams(1425, 1789));
        this.lzfcdfppai.setPadding(145, 191, WebSocketProtocol.PAYLOAD_SHORT, 127);
        linearLayout.addView(this.lzfcdfppai);
        this.lzfcdfppai.setBackgroundColor(Color.parseColor("#ced619"));
        CheckBox checkBox4 = new CheckBox(this);
        this.jipmilddaw = checkBox4;
        checkBox4.setLayoutParams(new LinearLayout.LayoutParams(1788, 1066));
        this.jipmilddaw.setPadding(92, 132, 117, 174);
        linearLayout.addView(this.jipmilddaw);
        this.jipmilddaw.setBackgroundColor(Color.parseColor("#0758bf"));
        ProgressBar progressBar4 = new ProgressBar(this);
        this.tyxunygabl = progressBar4;
        progressBar4.setLayoutParams(new LinearLayout.LayoutParams(GattClient.STATE_READ_DEVICE_INFO, 803));
        this.tyxunygabl.setPadding(106, 99, 67, 6);
        linearLayout.addView(this.tyxunygabl);
        this.tyxunygabl.setBackgroundColor(Color.parseColor("#0b33ef"));
        RelativeLayout relativeLayout8 = new RelativeLayout(this);
        this.owewuwxkpk = relativeLayout8;
        relativeLayout8.setLayoutParams(new LinearLayout.LayoutParams(1455, 132));
        this.owewuwxkpk.setPadding(17, 180, 158, 199);
        linearLayout.addView(this.owewuwxkpk);
        this.owewuwxkpk.setBackgroundColor(Color.parseColor("#a6e44b"));
        CheckBox checkBox5 = new CheckBox(this);
        this.hnmlgispek = checkBox5;
        checkBox5.setLayoutParams(new LinearLayout.LayoutParams(379, 1282));
        this.hnmlgispek.setPadding(6, 93, 49, 59);
        linearLayout.addView(this.hnmlgispek);
        this.hnmlgispek.setBackgroundColor(Color.parseColor("#a64ff3"));
        DatePicker datePicker4 = new DatePicker(this);
        this.hkzsykujze = datePicker4;
        datePicker4.setLayoutParams(new LinearLayout.LayoutParams(333, 1822));
        this.hkzsykujze.setPadding(102, 53, 122, 117);
        linearLayout.addView(this.hkzsykujze);
        this.hkzsykujze.setBackgroundColor(Color.parseColor("#a729bc"));
        TableLayout tableLayout9 = new TableLayout(this);
        this.ybubekdolr = tableLayout9;
        tableLayout9.setLayoutParams(new LinearLayout.LayoutParams(576, 1453));
        this.ybubekdolr.setPadding(25, 169, 76, 20);
        linearLayout.addView(this.ybubekdolr);
        this.ybubekdolr.setBackgroundColor(Color.parseColor("#3f0a81"));
        CheckBox checkBox6 = new CheckBox(this);
        this.wbesxsjcfj = checkBox6;
        checkBox6.setLayoutParams(new LinearLayout.LayoutParams(154, 1549));
        this.wbesxsjcfj.setPadding(124, 24, 54, 113);
        linearLayout.addView(this.wbesxsjcfj);
        this.wbesxsjcfj.setBackgroundColor(Color.parseColor("#80ff31"));
        RadioButton radioButton6 = new RadioButton(this);
        this.hmftxdjapr = radioButton6;
        radioButton6.setLayoutParams(new LinearLayout.LayoutParams(1797, 1593));
        this.hmftxdjapr.setPadding(BDLocation.TypeServerDecryptError, 27, 95, 64);
        linearLayout.addView(this.hmftxdjapr);
        this.hmftxdjapr.setBackgroundColor(Color.parseColor("#f99cbe"));
        Spinner spinner3 = new Spinner(this);
        this.ofvutbsrcj = spinner3;
        spinner3.setLayoutParams(new LinearLayout.LayoutParams(628, 1621));
        this.ofvutbsrcj.setPadding(128, 100, 30, 43);
        linearLayout.addView(this.ofvutbsrcj);
        this.ofvutbsrcj.setBackgroundColor(Color.parseColor("#8ae43b"));
        Switch r23 = new Switch(this);
        this.wpfgdxsmgv = r23;
        r23.setLayoutParams(new LinearLayout.LayoutParams(861, 892));
        this.wpfgdxsmgv.setPadding(67, 192, 146, 9);
        linearLayout.addView(this.wpfgdxsmgv);
        this.wpfgdxsmgv.setBackgroundColor(Color.parseColor("#89d1f4"));
        RadioButton radioButton7 = new RadioButton(this);
        this.ebvzbenlwc = radioButton7;
        radioButton7.setLayoutParams(new LinearLayout.LayoutParams(789, 1470));
        this.ebvzbenlwc.setPadding(174, 159, 195, 157);
        linearLayout.addView(this.ebvzbenlwc);
        this.ebvzbenlwc.setBackgroundColor(Color.parseColor("#529bb4"));
        ProgressBar progressBar5 = new ProgressBar(this);
        this.mqnvzyfdqx = progressBar5;
        progressBar5.setLayoutParams(new LinearLayout.LayoutParams(340, 1984));
        this.mqnvzyfdqx.setPadding(181, 41, 51, 66);
        linearLayout.addView(this.mqnvzyfdqx);
        this.mqnvzyfdqx.setBackgroundColor(Color.parseColor("#d23181"));
        SeekBar seekBar2 = new SeekBar(this);
        this.kmooaflbcb = seekBar2;
        seekBar2.setLayoutParams(new LinearLayout.LayoutParams(1678, 307));
        this.kmooaflbcb.setPadding(33, 195, 5, PictureConfig.CHOOSE_REQUEST);
        linearLayout.addView(this.kmooaflbcb);
        this.kmooaflbcb.setBackgroundColor(Color.parseColor("#a97705"));
        TimePicker timePicker3 = new TimePicker(this);
        this.ivoufefajg = timePicker3;
        timePicker3.setLayoutParams(new LinearLayout.LayoutParams(899, 1326));
        this.ivoufefajg.setPadding(198, 127, 121, 42);
        linearLayout.addView(this.ivoufefajg);
        this.ivoufefajg.setBackgroundColor(Color.parseColor("#9d7249"));
        ImageView imageView3 = new ImageView(this);
        this.swyxzxbqdv = imageView3;
        imageView3.setLayoutParams(new LinearLayout.LayoutParams(1836, FrameMetricsAggregator.EVERY_DURATION));
        this.swyxzxbqdv.setPadding(40, 35, 137, 55);
        linearLayout.addView(this.swyxzxbqdv);
        this.swyxzxbqdv.setBackgroundColor(Color.parseColor("#c957a1"));
        TextView textView4 = new TextView(this);
        this.eaboqchdff = textView4;
        textView4.setLayoutParams(new LinearLayout.LayoutParams(714, 307));
        this.eaboqchdff.setPadding(WebSocketProtocol.PAYLOAD_SHORT, 192, 147, 96);
        linearLayout.addView(this.eaboqchdff);
        this.eaboqchdff.setBackgroundColor(Color.parseColor("#545134"));
        LinearLayout linearLayout4 = new LinearLayout(this);
        this.vnuercmnvu = linearLayout4;
        linearLayout4.setLayoutParams(new LinearLayout.LayoutParams(597, 159));
        this.vnuercmnvu.setPadding(176, 155, 195, 15);
        linearLayout.addView(this.vnuercmnvu);
        this.vnuercmnvu.setBackgroundColor(Color.parseColor("#b40503"));
        ViewFlipper viewFlipper5 = new ViewFlipper(this);
        this.yzirlzzmts = viewFlipper5;
        viewFlipper5.setLayoutParams(new LinearLayout.LayoutParams(518, 1807));
        this.yzirlzzmts.setPadding(20, 185, 140, 157);
        linearLayout.addView(this.yzirlzzmts);
        this.yzirlzzmts.setBackgroundColor(Color.parseColor("#837be6"));
        DatePicker datePicker5 = new DatePicker(this);
        this.nfjhjwsjwl = datePicker5;
        datePicker5.setLayoutParams(new LinearLayout.LayoutParams(1354, 1187));
        this.nfjhjwsjwl.setPadding(8, 20, 115, 198);
        linearLayout.addView(this.nfjhjwsjwl);
        this.nfjhjwsjwl.setBackgroundColor(Color.parseColor("#50d766"));
        TimePicker timePicker4 = new TimePicker(this);
        this.wbyaomfqkr = timePicker4;
        timePicker4.setLayoutParams(new LinearLayout.LayoutParams(460, 481));
        this.wbyaomfqkr.setPadding(20, 179, 16, 158);
        linearLayout.addView(this.wbyaomfqkr);
        this.wbyaomfqkr.setBackgroundColor(Color.parseColor("#83baff"));
    }
}
