package com.smartapp.b.obfsjhzadn;

import android.app.Activity;
import android.graphics.Color;
import android.os.Bundle;
import android.view.ViewGroup;
import android.widget.CheckBox;
import android.widget.DatePicker;
import android.widget.EditText;
import android.widget.FrameLayout;
import android.widget.GridView;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ListView;
import android.widget.ProgressBar;
import android.widget.RadioButton;
import android.widget.RatingBar;
import android.widget.RelativeLayout;
import android.widget.ScrollView;
import android.widget.SeekBar;
import android.widget.Spinner;
import android.widget.Switch;
import android.widget.TableLayout;
import android.widget.TextView;
import android.widget.TimePicker;
import android.widget.ToggleButton;
import android.widget.ViewFlipper;
import androidx.constraintlayout.core.motion.utils.TypedValues;
import com.baidu.location.BDLocation;
import com.luck.picture.lib.config.PictureConfig;
import okhttp3.internal.ws.WebSocketProtocol;

/* loaded from: classes4.dex */
public class DnnfkymtybzActivity extends Activity {
    Spinner aaazykymuv;
    RadioButton afzelekjrg;
    Switch amxrmhphni;
    TimePicker aqqxvclxvi;
    Spinner crsbknwtju;
    GridView ebdbevynhf;
    ToggleButton eukxppjdhh;
    DatePicker ezzlbahgnd;
    RelativeLayout fjkdjqnfzk;
    SeekBar fpmhnhubfv;
    RelativeLayout hroaingiff;
    Switch icwxdwbzss;
    ProgressBar ikepelbizh;
    ScrollView iqlfbsorig;
    RatingBar irqexqtwzb;
    ScrollView izwucqewmt;
    TextView jssfhevlcc;
    ListView kizedposjj;
    SeekBar ktzslcbffk;
    ImageView llrldelazb;
    RatingBar lnrmbqisft;
    ListView lptuncjxec;
    DatePicker mkrcfnfmgs;
    SeekBar mquiueoebu;
    CheckBox ngbmrvazre;
    ListView noqdtsndmw;
    GridView ntifimzefa;
    TextView pczfbzwjsf;
    TextView pecxgyiicn;
    ListView qlfncgnwov;
    RatingBar rixrnzetye;
    TimePicker rtrbmnywsb;
    ViewFlipper rwitilqigl;
    Spinner smdffhqwgx;
    ImageView ubdfqivwlg;
    RatingBar ufwjhflbbn;
    FrameLayout vdrriwtcmv;
    GridView vfmjtxvhhe;
    ImageView vnsftklato;
    DatePicker vnusmkqjsi;
    FrameLayout wawypmpjwk;
    ProgressBar wegrlteqjw;
    DatePicker wvlaqtshmd;
    TimePicker xfedjssxcf;
    TableLayout xhcaudtvsa;
    EditText xsbzewtpbx;
    FrameLayout ycxbnhjcyt;
    RelativeLayout zjmkngnjbc;
    Switch zrkaqeqhpx;
    TextView zyovqozqur;

    @Override // android.app.Activity
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        LinearLayout linearLayout = new LinearLayout(this);
        setContentView(linearLayout);
        linearLayout.setLayoutParams(new ViewGroup.LayoutParams(-1, -1));
        linearLayout.setOrientation(1);
        linearLayout.setBackgroundColor(Color.parseColor("#8683c4"));
        ToggleButton toggleButton = new ToggleButton(this);
        this.eukxppjdhh = toggleButton;
        toggleButton.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.Custom.TYPE_STRING, 1345));
        this.eukxppjdhh.setPadding(165, 114, 76, 147);
        linearLayout.addView(this.eukxppjdhh);
        this.eukxppjdhh.setBackgroundColor(Color.parseColor("#a757ee"));
        ProgressBar progressBar = new ProgressBar(this);
        this.wegrlteqjw = progressBar;
        progressBar.setLayoutParams(new LinearLayout.LayoutParams(1676, 1276));
        this.wegrlteqjw.setPadding(26, 142, 90, 74);
        linearLayout.addView(this.wegrlteqjw);
        this.wegrlteqjw.setBackgroundColor(Color.parseColor("#e96b43"));
        ScrollView scrollView = new ScrollView(this);
        this.iqlfbsorig = scrollView;
        scrollView.setLayoutParams(new LinearLayout.LayoutParams(1494, 1619));
        this.iqlfbsorig.setPadding(101, 106, 34, 68);
        linearLayout.addView(this.iqlfbsorig);
        this.iqlfbsorig.setBackgroundColor(Color.parseColor("#9fcd47"));
        RelativeLayout relativeLayout = new RelativeLayout(this);
        this.zjmkngnjbc = relativeLayout;
        relativeLayout.setLayoutParams(new LinearLayout.LayoutParams(947, 1173));
        this.zjmkngnjbc.setPadding(104, 23, 183, 109);
        linearLayout.addView(this.zjmkngnjbc);
        this.zjmkngnjbc.setBackgroundColor(Color.parseColor("#ed5041"));
        Switch r3 = new Switch(this);
        this.zrkaqeqhpx = r3;
        r3.setLayoutParams(new LinearLayout.LayoutParams(759, 830));
        this.zrkaqeqhpx.setPadding(18, 46, 119, 52);
        linearLayout.addView(this.zrkaqeqhpx);
        this.zrkaqeqhpx.setBackgroundColor(Color.parseColor("#69309a"));
        TextView textView = new TextView(this);
        this.pczfbzwjsf = textView;
        textView.setLayoutParams(new LinearLayout.LayoutParams(1538, 1256));
        this.pczfbzwjsf.setPadding(176, 72, 186, 14);
        linearLayout.addView(this.pczfbzwjsf);
        this.pczfbzwjsf.setBackgroundColor(Color.parseColor("#0d2d0e"));
        ImageView imageView = new ImageView(this);
        this.vnsftklato = imageView;
        imageView.setLayoutParams(new LinearLayout.LayoutParams(1396, 408));
        this.vnsftklato.setPadding(157, 62, 110, 18);
        linearLayout.addView(this.vnsftklato);
        this.vnsftklato.setBackgroundColor(Color.parseColor("#18d26f"));
        TimePicker timePicker = new TimePicker(this);
        this.xfedjssxcf = timePicker;
        timePicker.setLayoutParams(new LinearLayout.LayoutParams(851, 1194));
        this.xfedjssxcf.setPadding(193, 30, 40, 102);
        linearLayout.addView(this.xfedjssxcf);
        this.xfedjssxcf.setBackgroundColor(Color.parseColor("#eb7406"));
        DatePicker datePicker = new DatePicker(this);
        this.ezzlbahgnd = datePicker;
        datePicker.setLayoutParams(new LinearLayout.LayoutParams(213, 1777));
        this.ezzlbahgnd.setPadding(62, 51, 68, 140);
        linearLayout.addView(this.ezzlbahgnd);
        this.ezzlbahgnd.setBackgroundColor(Color.parseColor("#03afa6"));
        ViewFlipper viewFlipper = new ViewFlipper(this);
        this.rwitilqigl = viewFlipper;
        viewFlipper.setLayoutParams(new LinearLayout.LayoutParams(1664, 1765));
        this.rwitilqigl.setPadding(118, 136, 13, 73);
        linearLayout.addView(this.rwitilqigl);
        this.rwitilqigl.setBackgroundColor(Color.parseColor("#0076d4"));
        ListView listView = new ListView(this);
        this.noqdtsndmw = listView;
        listView.setLayoutParams(new LinearLayout.LayoutParams(982, 1858));
        this.noqdtsndmw.setPadding(8, 193, 63, 75);
        linearLayout.addView(this.noqdtsndmw);
        this.noqdtsndmw.setBackgroundColor(Color.parseColor("#c67f44"));
        RatingBar ratingBar = new RatingBar(this);
        this.lnrmbqisft = ratingBar;
        ratingBar.setLayoutParams(new LinearLayout.LayoutParams(1014, 322));
        this.lnrmbqisft.setPadding(10, 149, 138, 142);
        linearLayout.addView(this.lnrmbqisft);
        this.lnrmbqisft.setBackgroundColor(Color.parseColor("#5b9dd6"));
        TimePicker timePicker2 = new TimePicker(this);
        this.rtrbmnywsb = timePicker2;
        timePicker2.setLayoutParams(new LinearLayout.LayoutParams(1078, 176));
        this.rtrbmnywsb.setPadding(33, 28, 169, 123);
        linearLayout.addView(this.rtrbmnywsb);
        this.rtrbmnywsb.setBackgroundColor(Color.parseColor("#adba98"));
        FrameLayout frameLayout = new FrameLayout(this);
        this.wawypmpjwk = frameLayout;
        frameLayout.setLayoutParams(new LinearLayout.LayoutParams(724, 850));
        this.wawypmpjwk.setPadding(116, 90, 7, 172);
        linearLayout.addView(this.wawypmpjwk);
        this.wawypmpjwk.setBackgroundColor(Color.parseColor("#49ae31"));
        DatePicker datePicker2 = new DatePicker(this);
        this.mkrcfnfmgs = datePicker2;
        datePicker2.setLayoutParams(new LinearLayout.LayoutParams(1203, 857));
        this.mkrcfnfmgs.setPadding(63, 45, 163, 135);
        linearLayout.addView(this.mkrcfnfmgs);
        this.mkrcfnfmgs.setBackground(new Mpxbimtonik());
        GridView gridView = new GridView(this);
        this.ntifimzefa = gridView;
        gridView.setLayoutParams(new LinearLayout.LayoutParams(961, 816));
        this.ntifimzefa.setPadding(96, 11, 53, 4);
        linearLayout.addView(this.ntifimzefa);
        this.ntifimzefa.setBackgroundColor(Color.parseColor("#b6a2e5"));
        FrameLayout frameLayout2 = new FrameLayout(this);
        this.vdrriwtcmv = frameLayout2;
        frameLayout2.setLayoutParams(new LinearLayout.LayoutParams(1224, 41));
        this.vdrriwtcmv.setPadding(128, 115, 133, BDLocation.TypeServerError);
        linearLayout.addView(this.vdrriwtcmv);
        this.vdrriwtcmv.setBackgroundColor(Color.parseColor("#b14ec3"));
        ImageView imageView2 = new ImageView(this);
        this.ubdfqivwlg = imageView2;
        imageView2.setLayoutParams(new LinearLayout.LayoutParams(738, 1303));
        this.ubdfqivwlg.setPadding(137, 70, 152, 94);
        linearLayout.addView(this.ubdfqivwlg);
        this.ubdfqivwlg.setBackgroundColor(Color.parseColor("#d213cb"));
        RadioButton radioButton = new RadioButton(this);
        this.afzelekjrg = radioButton;
        radioButton.setLayoutParams(new LinearLayout.LayoutParams(1332, 1895));
        this.afzelekjrg.setPadding(46, 108, 18, 138);
        linearLayout.addView(this.afzelekjrg);
        this.afzelekjrg.setBackgroundColor(Color.parseColor("#33517b"));
        RatingBar ratingBar2 = new RatingBar(this);
        this.irqexqtwzb = ratingBar2;
        ratingBar2.setLayoutParams(new LinearLayout.LayoutParams(1138, 1731));
        this.irqexqtwzb.setPadding(31, 181, 138, 10);
        linearLayout.addView(this.irqexqtwzb);
        this.irqexqtwzb.setBackgroundColor(Color.parseColor("#7655c2"));
        RelativeLayout relativeLayout2 = new RelativeLayout(this);
        this.fjkdjqnfzk = relativeLayout2;
        relativeLayout2.setLayoutParams(new LinearLayout.LayoutParams(1655, 81));
        this.fjkdjqnfzk.setPadding(73, 37, 37, 157);
        linearLayout.addView(this.fjkdjqnfzk);
        this.fjkdjqnfzk.setBackgroundColor(Color.parseColor("#e7184c"));
        GridView gridView2 = new GridView(this);
        this.ebdbevynhf = gridView2;
        gridView2.setLayoutParams(new LinearLayout.LayoutParams(920, 1585));
        this.ebdbevynhf.setPadding(87, 26, 198, 92);
        linearLayout.addView(this.ebdbevynhf);
        this.ebdbevynhf.setBackgroundColor(Color.parseColor("#b41ba5"));
        ListView listView2 = new ListView(this);
        this.kizedposjj = listView2;
        listView2.setLayoutParams(new LinearLayout.LayoutParams(1600, 1769));
        this.kizedposjj.setPadding(102, PictureConfig.CHOOSE_REQUEST, 31, 58);
        linearLayout.addView(this.kizedposjj);
        this.kizedposjj.setBackgroundColor(Color.parseColor("#9f6090"));
        Spinner spinner = new Spinner(this);
        this.crsbknwtju = spinner;
        spinner.setLayoutParams(new LinearLayout.LayoutParams(1279, 1174));
        this.crsbknwtju.setPadding(30, 16, 2, 57);
        linearLayout.addView(this.crsbknwtju);
        this.crsbknwtju.setBackgroundColor(Color.parseColor("#279dc1"));
        Switch r32 = new Switch(this);
        this.amxrmhphni = r32;
        r32.setLayoutParams(new LinearLayout.LayoutParams(645, 1049));
        this.amxrmhphni.setPadding(179, 98, 1, 194);
        linearLayout.addView(this.amxrmhphni);
        this.amxrmhphni.setBackgroundColor(Color.parseColor("#d0f3b6"));
        RelativeLayout relativeLayout3 = new RelativeLayout(this);
        this.hroaingiff = relativeLayout3;
        relativeLayout3.setLayoutParams(new LinearLayout.LayoutParams(1795, 52));
        this.hroaingiff.setPadding(83, 54, 132, 24);
        linearLayout.addView(this.hroaingiff);
        this.hroaingiff.setBackgroundColor(Color.parseColor("#d1c48a"));
        TableLayout tableLayout = new TableLayout(this);
        this.xhcaudtvsa = tableLayout;
        tableLayout.setLayoutParams(new LinearLayout.LayoutParams(761, 40));
        this.xhcaudtvsa.setPadding(106, 131, 17, 26);
        linearLayout.addView(this.xhcaudtvsa);
        this.xhcaudtvsa.setBackgroundColor(Color.parseColor("#536819"));
        RatingBar ratingBar3 = new RatingBar(this);
        this.rixrnzetye = ratingBar3;
        ratingBar3.setLayoutParams(new LinearLayout.LayoutParams(674, 1076));
        this.rixrnzetye.setPadding(129, 180, 39, 67);
        linearLayout.addView(this.rixrnzetye);
        this.rixrnzetye.setBackgroundColor(Color.parseColor("#29d3fa"));
        DatePicker datePicker3 = new DatePicker(this);
        this.vnusmkqjsi = datePicker3;
        datePicker3.setLayoutParams(new LinearLayout.LayoutParams(787, 724));
        this.vnusmkqjsi.setPadding(101, 195, 139, 0);
        linearLayout.addView(this.vnusmkqjsi);
        this.vnusmkqjsi.setBackgroundColor(Color.parseColor("#960548"));
        TextView textView2 = new TextView(this);
        this.zyovqozqur = textView2;
        textView2.setLayoutParams(new LinearLayout.LayoutParams(828, 556));
        this.zyovqozqur.setPadding(59, 187, 140, 190);
        linearLayout.addView(this.zyovqozqur);
        this.zyovqozqur.setBackgroundColor(Color.parseColor("#c6f40e"));
        ImageView imageView3 = new ImageView(this);
        this.llrldelazb = imageView3;
        imageView3.setLayoutParams(new LinearLayout.LayoutParams(1230, 680));
        this.llrldelazb.setPadding(73, 89, 34, 61);
        linearLayout.addView(this.llrldelazb);
        this.llrldelazb.setBackgroundColor(Color.parseColor("#a9990d"));
        Switch r2 = new Switch(this);
        this.icwxdwbzss = r2;
        r2.setLayoutParams(new LinearLayout.LayoutParams(1300, 649));
        this.icwxdwbzss.setPadding(23, 127, 177, 173);
        linearLayout.addView(this.icwxdwbzss);
        this.icwxdwbzss.setBackgroundColor(Color.parseColor("#592dc7"));
        SeekBar seekBar = new SeekBar(this);
        this.mquiueoebu = seekBar;
        seekBar.setLayoutParams(new LinearLayout.LayoutParams(1973, 1670));
        this.mquiueoebu.setPadding(172, 54, 45, 139);
        linearLayout.addView(this.mquiueoebu);
        this.mquiueoebu.setBackgroundColor(Color.parseColor("#aa2b94"));
        SeekBar seekBar2 = new SeekBar(this);
        this.fpmhnhubfv = seekBar2;
        seekBar2.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.AttributesType.TYPE_EASING, 1380));
        this.fpmhnhubfv.setPadding(117, 143, 118, 9);
        linearLayout.addView(this.fpmhnhubfv);
        this.fpmhnhubfv.setBackgroundColor(Color.parseColor("#5c5ccd"));
        RatingBar ratingBar4 = new RatingBar(this);
        this.ufwjhflbbn = ratingBar4;
        ratingBar4.setLayoutParams(new LinearLayout.LayoutParams(148, 1372));
        this.ufwjhflbbn.setPadding(71, 189, 123, 15);
        linearLayout.addView(this.ufwjhflbbn);
        this.ufwjhflbbn.setBackgroundColor(Color.parseColor("#93c418"));
        TimePicker timePicker3 = new TimePicker(this);
        this.aqqxvclxvi = timePicker3;
        timePicker3.setLayoutParams(new LinearLayout.LayoutParams(1614, 1312));
        this.aqqxvclxvi.setPadding(197, 122, 140, 106);
        linearLayout.addView(this.aqqxvclxvi);
        this.aqqxvclxvi.setBackgroundColor(Color.parseColor("#c3d8c9"));
        TextView textView3 = new TextView(this);
        this.pecxgyiicn = textView3;
        textView3.setLayoutParams(new LinearLayout.LayoutParams(1370, 1073));
        this.pecxgyiicn.setPadding(21, 179, BDLocation.TypeCoarseLocation, 184);
        linearLayout.addView(this.pecxgyiicn);
        this.pecxgyiicn.setBackgroundColor(Color.parseColor("#65f869"));
        CheckBox checkBox = new CheckBox(this);
        this.ngbmrvazre = checkBox;
        checkBox.setLayoutParams(new LinearLayout.LayoutParams(383, 1257));
        this.ngbmrvazre.setPadding(76, 66, 37, 124);
        linearLayout.addView(this.ngbmrvazre);
        this.ngbmrvazre.setBackgroundColor(Color.parseColor("#3b10e4"));
        ProgressBar progressBar2 = new ProgressBar(this);
        this.ikepelbizh = progressBar2;
        progressBar2.setLayoutParams(new LinearLayout.LayoutParams(841, 1720));
        this.ikepelbizh.setPadding(42, 31, WebSocketProtocol.PAYLOAD_SHORT, 156);
        linearLayout.addView(this.ikepelbizh);
        this.ikepelbizh.setBackgroundColor(Color.parseColor("#febd6f"));
        EditText editText = new EditText(this);
        this.xsbzewtpbx = editText;
        editText.setLayoutParams(new LinearLayout.LayoutParams(139, 181));
        this.xsbzewtpbx.setPadding(72, 147, 8, 125);
        linearLayout.addView(this.xsbzewtpbx);
        this.xsbzewtpbx.setBackgroundColor(Color.parseColor("#95ace6"));
        TextView textView4 = new TextView(this);
        this.jssfhevlcc = textView4;
        textView4.setLayoutParams(new LinearLayout.LayoutParams(1045, 619));
        this.jssfhevlcc.setPadding(141, 98, 109, 16);
        linearLayout.addView(this.jssfhevlcc);
        this.jssfhevlcc.setBackgroundColor(Color.parseColor("#3fcb7a"));
        ListView listView3 = new ListView(this);
        this.lptuncjxec = listView3;
        listView3.setLayoutParams(new LinearLayout.LayoutParams(365, 309));
        this.lptuncjxec.setPadding(104, 59, 82, 11);
        linearLayout.addView(this.lptuncjxec);
        this.lptuncjxec.setBackgroundColor(Color.parseColor("#ea08de"));
        ScrollView scrollView2 = new ScrollView(this);
        this.izwucqewmt = scrollView2;
        scrollView2.setLayoutParams(new LinearLayout.LayoutParams(529, 191));
        this.izwucqewmt.setPadding(136, 182, 117, 143);
        linearLayout.addView(this.izwucqewmt);
        this.izwucqewmt.setBackgroundColor(Color.parseColor("#5dc938"));
        DatePicker datePicker4 = new DatePicker(this);
        this.wvlaqtshmd = datePicker4;
        datePicker4.setLayoutParams(new LinearLayout.LayoutParams(1315, TypedValues.CycleType.TYPE_ALPHA));
        this.wvlaqtshmd.setPadding(38, 10, 158, 33);
        linearLayout.addView(this.wvlaqtshmd);
        this.wvlaqtshmd.setBackgroundColor(Color.parseColor("#154539"));
        ListView listView4 = new ListView(this);
        this.qlfncgnwov = listView4;
        listView4.setLayoutParams(new LinearLayout.LayoutParams(1142, 965));
        this.qlfncgnwov.setPadding(27, 98, 111, 48);
        linearLayout.addView(this.qlfncgnwov);
        this.qlfncgnwov.setBackgroundColor(Color.parseColor("#10ad74"));
        GridView gridView3 = new GridView(this);
        this.vfmjtxvhhe = gridView3;
        gridView3.setLayoutParams(new LinearLayout.LayoutParams(1118, 1284));
        this.vfmjtxvhhe.setPadding(102, 42, 118, 66);
        linearLayout.addView(this.vfmjtxvhhe);
        this.vfmjtxvhhe.setBackgroundColor(Color.parseColor("#ff0ea2"));
        Spinner spinner2 = new Spinner(this);
        this.smdffhqwgx = spinner2;
        spinner2.setLayoutParams(new LinearLayout.LayoutParams(509, 1061));
        this.smdffhqwgx.setPadding(133, 83, 176, 27);
        linearLayout.addView(this.smdffhqwgx);
        this.smdffhqwgx.setBackgroundColor(Color.parseColor("#0e4e0e"));
        SeekBar seekBar3 = new SeekBar(this);
        this.ktzslcbffk = seekBar3;
        seekBar3.setLayoutParams(new LinearLayout.LayoutParams(416, 949));
        this.ktzslcbffk.setPadding(165, 103, 129, 139);
        linearLayout.addView(this.ktzslcbffk);
        this.ktzslcbffk.setBackgroundColor(Color.parseColor("#0f7e35"));
        FrameLayout frameLayout3 = new FrameLayout(this);
        this.ycxbnhjcyt = frameLayout3;
        frameLayout3.setLayoutParams(new LinearLayout.LayoutParams(849, 788));
        this.ycxbnhjcyt.setPadding(164, 42, 94, 115);
        linearLayout.addView(this.ycxbnhjcyt);
        this.ycxbnhjcyt.setBackgroundColor(Color.parseColor("#d9258b"));
        Spinner spinner3 = new Spinner(this);
        this.aaazykymuv = spinner3;
        spinner3.setLayoutParams(new LinearLayout.LayoutParams(861, 1057));
        this.aaazykymuv.setPadding(155, 39, 172, 164);
        linearLayout.addView(this.aaazykymuv);
        this.aaazykymuv.setBackgroundColor(Color.parseColor("#e161d8"));
    }
}
