package com.device.watch.com.device.watch.tmzjvlerof;

import android.app.Activity;
import android.graphics.Color;
import android.os.Bundle;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.CheckBox;
import android.widget.DatePicker;
import android.widget.EditText;
import android.widget.FrameLayout;
import android.widget.GridView;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ListView;
import android.widget.ProgressBar;
import android.widget.RadioButton;
import android.widget.RatingBar;
import android.widget.RelativeLayout;
import android.widget.ScrollView;
import android.widget.SeekBar;
import android.widget.Spinner;
import android.widget.Switch;
import android.widget.TableLayout;
import android.widget.TextView;
import android.widget.TimePicker;
import android.widget.ToggleButton;
import android.widget.ViewFlipper;
import androidx.constraintlayout.core.motion.utils.TypedValues;
import androidx.core.view.PointerIconCompat;
import com.baidu.location.BDLocation;
import com.king.zxing.util.CodeUtils;
import com.luck.picture.lib.config.PictureConfig;
import com.qcwireless.qcwatch.ui.base.imagepicker.cropper.CropImage;
import com.realsil.sdk.bbpro.equalizer.AudioEq;
import com.realsil.sdk.core.bluetooth.connection.le.GattClient;
import okhttp3.internal.ws.WebSocketProtocol;
import org.java_websocket.WebSocketImpl;

/* loaded from: classes2.dex */
public class EkofpcjdxnzActivity extends Activity {
    ScrollView adnvzfekdj;
    Switch afqechshpo;
    DatePicker afwfzxhsri;
    TimePicker ahswgxwseu;
    DatePicker aqakqqfhxb;
    FrameLayout aripomywcz;
    ImageView atfourjjdy;
    GridView axcnjkmudo;
    SeekBar azickiejtp;
    TimePicker azkmkglfkp;
    RadioButton bcadvcrwqz;
    RelativeLayout bciefrqeos;
    RatingBar bewtmotqjg;
    ViewFlipper bfvkrxucha;
    ListView bhixwviibw;
    LinearLayout biyhiadrax;
    EditText bkvdynojsm;
    RatingBar bnlmrlnypa;
    RelativeLayout bvxgrroyfp;
    FrameLayout bzmvoyroje;
    ScrollView bzqzmsyseb;
    GridView cbunreuzkt;
    RadioButton ccommxnqkt;
    ImageView cfcjsrxiqd;
    SeekBar cfmlmlqjuk;
    TextView chudffthqg;
    ProgressBar cihxqbbgmr;
    TextView cilvlfderw;
    ViewFlipper ctwboasaen;
    LinearLayout cuxtudmbum;
    ViewFlipper cxgoqsviwn;
    Switch dalpwryqjs;
    ScrollView dbhgrqtzif;
    SeekBar ddgblbsful;
    GridView dhcvlvumuq;
    Spinner dkcrgwqsik;
    Spinner dkvxrjbmho;
    RatingBar dnuiywmbsy;
    ViewFlipper doygzfadmp;
    GridView dpmtcdtoka;
    RatingBar dqxrocchuc;
    ToggleButton dtuyjmclnv;
    FrameLayout dywwcpcrim;
    SeekBar eayhbrmhcr;
    ImageView ebwjybrgyc;
    RatingBar edooymcevd;
    ToggleButton eepjtvhbom;
    GridView ekbkdoagnn;
    RelativeLayout elomokefll;
    TableLayout erzghhrvmv;
    ImageView eurljwgwpw;
    RatingBar eveecfarpg;
    EditText exewopphpd;
    TimePicker exleypoixr;
    EditText ezrnajeutf;
    Spinner ezyxjxgajj;
    ProgressBar fctihgvbug;
    SeekBar fdcxtvxnmk;
    EditText fnwkkgsnct;
    EditText fpgowgosvw;
    GridView frhzzxsumt;
    Switch fvxsxgyrje;
    RadioButton fycfwagnpq;
    DatePicker ggszbquyea;
    TableLayout gsthweuede;
    TimePicker hbmajynyfu;
    TextView hbsglbakit;
    ProgressBar hdtwftdlbc;
    TextView hkomaswuxz;
    Button hxaviqlymv;
    ListView iczoitlzkh;
    RelativeLayout igejutdraq;
    CheckBox iijqlazsiu;
    CheckBox ijqqrvdlgh;
    RelativeLayout inliqhdlou;
    ScrollView iuvrkgwalt;
    GridView jbdasaxovs;
    ImageView jfchoivyny;
    CheckBox jgimttspoo;
    RatingBar jgmrutfeay;
    ProgressBar jhmnlhffny;
    ImageView jhrkjdxfyy;
    RatingBar jmjuunhdfc;
    ImageView jmvqvtolfy;
    ViewFlipper jogkivrcpz;
    Switch juuhagzeid;
    Button jvorqymyup;
    LinearLayout jwfplddlzy;
    RelativeLayout jytsokwhng;
    ProgressBar jzizzvrxbr;
    TimePicker kabjylczds;
    ScrollView kfzcbvupzp;
    LinearLayout kpfycdfiwz;
    Button krocpncexa;
    LinearLayout kvhpsjecsp;
    DatePicker kwlsgvdsaf;
    ImageView kxihjmwlqg;
    Switch ldtpgnltcg;
    RelativeLayout ljerivaaof;
    GridView lowkumamce;
    SeekBar mcateyvgxx;
    TimePicker mesovzdjob;
    DatePicker mfuoqsoomv;
    ProgressBar mlxuhculah;
    CheckBox mnfudiedls;
    ListView nalsbhirzm;
    FrameLayout ndrlzjpihq;
    EditText nidyafkqls;
    RelativeLayout nitcnfntwh;
    FrameLayout nnzpboqcqg;
    ToggleButton nvtqbkfasa;
    FrameLayout nxmmtmnmvy;
    Button obvzytrqnl;
    ViewFlipper ofmlgnbsoj;
    RatingBar ohsujdariz;
    ViewFlipper onvdsqhwre;
    Switch oolgvtubqd;
    CheckBox ovjlcoslxg;
    TimePicker oxmgpogdba;
    TextView oxtcalsasr;
    ViewFlipper ozighxeefy;
    Switch piziohxwsh;
    TimePicker pjgipbyjsp;
    ListView plqofgglfn;
    LinearLayout pojrymsuxw;
    GridView pravffimwq;
    ProgressBar pruudewukq;
    RadioButton ptprtmfcqy;
    DatePicker qcxqpgtqhe;
    RatingBar qdsyryohfr;
    Switch qduhzmlbff;
    DatePicker qdulmjchye;
    ListView qktxpuxedn;
    ScrollView qlmpwrezgs;
    DatePicker qpvhacobvz;
    RelativeLayout rdolkgusvx;
    RatingBar rjnarijmnp;
    RadioButton rklhsxkxzu;
    RelativeLayout rkojgzwdfl;
    Button rktuuwxcum;
    ListView roxqelbqar;
    RatingBar rtnzgldlym;
    ToggleButton rumsgvnjvw;
    FrameLayout rxlefyajyb;
    EditText sihtqslaus;
    TextView skaexddbti;
    ListView slrqaoqvba;
    TableLayout sofuoaudsh;
    LinearLayout sotgwnwzdv;
    GridView sovqezppph;
    ImageView sxzytjdlwg;
    ProgressBar szaipxnlau;
    TimePicker tidxszxpda;
    RadioButton timqsjcvic;
    ToggleButton tjgqmgddrz;
    EditText tkqjemiosm;
    TableLayout tlyfhsxbgj;
    ProgressBar toufcawdua;
    RelativeLayout tozxuovsoa;
    ScrollView tqxgmxkxkp;
    ToggleButton trccboxatt;
    EditText trtupguoap;
    EditText trzdahqccm;
    Button ttpujkfgvm;
    ToggleButton ttuwfsyowe;
    ProgressBar ttyvpppcaj;
    RatingBar twbsbbuull;
    ProgressBar ubmefprvac;
    RatingBar udkyuczpxg;
    FrameLayout uewihwggyq;
    RelativeLayout uirrezpebe;
    DatePicker uknzkklicy;
    Switch umhfbfnorb;
    Spinner upvvcozsxd;
    RadioButton upzaaygocj;
    TimePicker urhdujvpdf;
    ProgressBar usyinrazmk;
    CheckBox uuiyhdefwm;
    FrameLayout uzsafcprsy;
    SeekBar vczqacxwam;
    ToggleButton vgwdnvkahc;
    ProgressBar vjnnnfxeof;
    ScrollView vjoqvksfro;
    DatePicker vjqpdlzchc;
    RatingBar vnhqhtictr;
    ImageView vsdrtxanue;
    LinearLayout vsmadsmook;
    GridView vsnwqkizqg;
    RadioButton vswhrtlgdt;
    TableLayout vtzqdsatwn;
    TableLayout vuyjbdnlts;
    RelativeLayout vyspyqnfru;
    DatePicker vzkgryhnei;
    RatingBar wapxxjfdtt;
    GridView wjiaaxickv;
    GridView wkksjjbfsl;
    CheckBox wnsqdznkeq;
    ToggleButton wovqeafhgh;
    RadioButton wrcsjnoelr;
    Button wrdaatsfya;
    TableLayout wyydukkhcs;
    RadioButton wzcdevnhxr;
    ToggleButton xahrnnlhkv;
    ToggleButton xeajcyxrij;
    Button xkrugsejwl;
    DatePicker xocxtfcvni;
    TextView xrkpkozilk;
    ImageView xtunpxbgtc;
    TimePicker xucqxzrzrv;
    RatingBar xuzwvfwzcl;
    ListView xvsqbgguif;
    RadioButton xzwjkayrnf;
    RadioButton yczhcvtdrw;
    ToggleButton yhxlnhrhmy;
    ViewFlipper yltyzufzod;
    EditText ynalmvfcqf;
    ListView ypvhvzjiyh;
    TextView yrlfdwrbye;
    TextView yuaeoskujj;
    ProgressBar yuylpijnkt;
    TimePicker ywltzgovlg;
    ToggleButton yxplmhehlg;
    Spinner yyizgjwuyb;
    RadioButton yzuwhrmuqo;
    TableLayout zamdwapklk;
    TableLayout zbbkxhvxzi;
    CheckBox zjampkkzod;
    TableLayout zlaohsdczc;
    ImageView zmgtyuwhmy;
    GridView zmptpoaqsm;
    EditText zpdeiotmbe;
    ListView zqsijnmmkt;
    CheckBox zrmrjvcqul;
    TableLayout zyxgkntsvx;

    @Override // android.app.Activity
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        LinearLayout linearLayout = new LinearLayout(this);
        setContentView(linearLayout);
        linearLayout.setLayoutParams(new ViewGroup.LayoutParams(-1, -1));
        linearLayout.setOrientation(1);
        linearLayout.setBackgroundColor(Color.parseColor("#aa6a99"));
        Switch r2 = new Switch(this);
        this.oolgvtubqd = r2;
        r2.setLayoutParams(new LinearLayout.LayoutParams(183, 399));
        this.oolgvtubqd.setPadding(143, 45, 56, 79);
        linearLayout.addView(this.oolgvtubqd);
        this.oolgvtubqd.setBackgroundColor(Color.parseColor("#7e270c"));
        ProgressBar progressBar = new ProgressBar(this);
        this.fctihgvbug = progressBar;
        progressBar.setLayoutParams(new LinearLayout.LayoutParams(579, 1503));
        this.fctihgvbug.setPadding(110, 4, 67, 133);
        linearLayout.addView(this.fctihgvbug);
        this.fctihgvbug.setBackgroundColor(Color.parseColor("#fa533b"));
        GridView gridView = new GridView(this);
        this.vsnwqkizqg = gridView;
        gridView.setLayoutParams(new LinearLayout.LayoutParams(1414, 106));
        this.vsnwqkizqg.setPadding(110, 156, 54, 163);
        linearLayout.addView(this.vsnwqkizqg);
        this.vsnwqkizqg.setBackgroundColor(Color.parseColor("#c457bc"));
        TimePicker timePicker = new TimePicker(this);
        this.azkmkglfkp = timePicker;
        timePicker.setLayoutParams(new LinearLayout.LayoutParams(1199, 1976));
        this.azkmkglfkp.setPadding(186, 84, 159, 174);
        linearLayout.addView(this.azkmkglfkp);
        this.azkmkglfkp.setBackgroundColor(Color.parseColor("#450d28"));
        ToggleButton toggleButton = new ToggleButton(this);
        this.eepjtvhbom = toggleButton;
        toggleButton.setLayoutParams(new LinearLayout.LayoutParams(381, 1531));
        this.eepjtvhbom.setPadding(86, 184, 166, 87);
        linearLayout.addView(this.eepjtvhbom);
        this.eepjtvhbom.setBackground(new Vksfnsskdfb());
        ScrollView scrollView = new ScrollView(this);
        this.vjoqvksfro = scrollView;
        scrollView.setLayoutParams(new LinearLayout.LayoutParams(1278, 232));
        this.vjoqvksfro.setPadding(182, 70, 30, 23);
        linearLayout.addView(this.vjoqvksfro);
        this.vjoqvksfro.setBackgroundColor(Color.parseColor("#139e27"));
        DatePicker datePicker = new DatePicker(this);
        this.uknzkklicy = datePicker;
        datePicker.setLayoutParams(new LinearLayout.LayoutParams(1127, 1659));
        this.uknzkklicy.setPadding(59, 78, 171, 183);
        linearLayout.addView(this.uknzkklicy);
        this.uknzkklicy.setBackgroundColor(Color.parseColor("#3489bc"));
        RatingBar ratingBar = new RatingBar(this);
        this.jgmrutfeay = ratingBar;
        ratingBar.setLayoutParams(new LinearLayout.LayoutParams(727, 761));
        this.jgmrutfeay.setPadding(59, 168, 32, 156);
        linearLayout.addView(this.jgmrutfeay);
        this.jgmrutfeay.setBackgroundColor(Color.parseColor("#2d84a1"));
        ToggleButton toggleButton2 = new ToggleButton(this);
        this.yhxlnhrhmy = toggleButton2;
        toggleButton2.setLayoutParams(new LinearLayout.LayoutParams(11, 1570));
        this.yhxlnhrhmy.setPadding(120, 25, 194, 89);
        linearLayout.addView(this.yhxlnhrhmy);
        this.yhxlnhrhmy.setBackgroundColor(Color.parseColor("#2ce4c5"));
        ProgressBar progressBar2 = new ProgressBar(this);
        this.pruudewukq = progressBar2;
        progressBar2.setLayoutParams(new LinearLayout.LayoutParams(1205, 1157));
        this.pruudewukq.setPadding(118, 22, 45, 115);
        linearLayout.addView(this.pruudewukq);
        this.pruudewukq.setBackgroundColor(Color.parseColor("#c67b27"));
        SeekBar seekBar = new SeekBar(this);
        this.eayhbrmhcr = seekBar;
        seekBar.setLayoutParams(new LinearLayout.LayoutParams(1525, 778));
        this.eayhbrmhcr.setPadding(51, 118, 22, 38);
        linearLayout.addView(this.eayhbrmhcr);
        this.eayhbrmhcr.setBackgroundColor(Color.parseColor("#8e3ccc"));
        RadioButton radioButton = new RadioButton(this);
        this.ptprtmfcqy = radioButton;
        radioButton.setLayoutParams(new LinearLayout.LayoutParams(1546, 646));
        this.ptprtmfcqy.setPadding(65, 122, 112, 32);
        linearLayout.addView(this.ptprtmfcqy);
        this.ptprtmfcqy.setBackgroundColor(Color.parseColor("#95f3b3"));
        FrameLayout frameLayout = new FrameLayout(this);
        this.bzmvoyroje = frameLayout;
        frameLayout.setLayoutParams(new LinearLayout.LayoutParams(1327, 1119));
        this.bzmvoyroje.setPadding(88, 37, 37, 51);
        linearLayout.addView(this.bzmvoyroje);
        this.bzmvoyroje.setBackgroundColor(Color.parseColor("#c2bc2f"));
        LinearLayout linearLayout2 = new LinearLayout(this);
        this.pojrymsuxw = linearLayout2;
        linearLayout2.setLayoutParams(new LinearLayout.LayoutParams(1253, 1815));
        this.pojrymsuxw.setPadding(155, 32, 139, 107);
        linearLayout.addView(this.pojrymsuxw);
        this.pojrymsuxw.setBackgroundColor(Color.parseColor("#7f9eca"));
        LinearLayout linearLayout3 = new LinearLayout(this);
        this.sotgwnwzdv = linearLayout3;
        linearLayout3.setLayoutParams(new LinearLayout.LayoutParams(392, 413));
        this.sotgwnwzdv.setPadding(158, 69, 88, 71);
        linearLayout.addView(this.sotgwnwzdv);
        this.sotgwnwzdv.setBackgroundColor(Color.parseColor("#72f6f9"));
        ProgressBar progressBar3 = new ProgressBar(this);
        this.ubmefprvac = progressBar3;
        progressBar3.setLayoutParams(new LinearLayout.LayoutParams(106, 774));
        this.ubmefprvac.setPadding(11, 140, 68, 172);
        linearLayout.addView(this.ubmefprvac);
        this.ubmefprvac.setBackgroundColor(Color.parseColor("#f54d5e"));
        ToggleButton toggleButton3 = new ToggleButton(this);
        this.ttuwfsyowe = toggleButton3;
        toggleButton3.setLayoutParams(new LinearLayout.LayoutParams(1310, 1954));
        this.ttuwfsyowe.setPadding(31, 74, 146, 100);
        linearLayout.addView(this.ttuwfsyowe);
        this.ttuwfsyowe.setBackgroundColor(Color.parseColor("#a27d6a"));
        ProgressBar progressBar4 = new ProgressBar(this);
        this.usyinrazmk = progressBar4;
        progressBar4.setLayoutParams(new LinearLayout.LayoutParams(155, 674));
        this.usyinrazmk.setPadding(13, 38, 130, 134);
        linearLayout.addView(this.usyinrazmk);
        this.usyinrazmk.setBackgroundColor(Color.parseColor("#a8fca7"));
        RatingBar ratingBar2 = new RatingBar(this);
        this.udkyuczpxg = ratingBar2;
        ratingBar2.setLayoutParams(new LinearLayout.LayoutParams(997, 960));
        this.udkyuczpxg.setPadding(69, 182, 7, 14);
        linearLayout.addView(this.udkyuczpxg);
        this.udkyuczpxg.setBackgroundColor(Color.parseColor("#4268e0"));
        FrameLayout frameLayout2 = new FrameLayout(this);
        this.aripomywcz = frameLayout2;
        frameLayout2.setLayoutParams(new LinearLayout.LayoutParams(33, 463));
        this.aripomywcz.setPadding(25, 102, 112, 101);
        linearLayout.addView(this.aripomywcz);
        this.aripomywcz.setBackgroundColor(Color.parseColor("#ac766d"));
        ToggleButton toggleButton4 = new ToggleButton(this);
        this.nvtqbkfasa = toggleButton4;
        toggleButton4.setLayoutParams(new LinearLayout.LayoutParams(1341, 328));
        this.nvtqbkfasa.setPadding(150, BDLocation.TypeServerDecryptError, 125, 27);
        linearLayout.addView(this.nvtqbkfasa);
        this.nvtqbkfasa.setBackgroundColor(Color.parseColor("#84041f"));
        TableLayout tableLayout = new TableLayout(this);
        this.zlaohsdczc = tableLayout;
        tableLayout.setLayoutParams(new LinearLayout.LayoutParams(1665, 1582));
        this.zlaohsdczc.setPadding(18, 105, 56, 136);
        linearLayout.addView(this.zlaohsdczc);
        this.zlaohsdczc.setBackgroundColor(Color.parseColor("#fdf22b"));
        ListView listView = new ListView(this);
        this.xvsqbgguif = listView;
        listView.setLayoutParams(new LinearLayout.LayoutParams(1391, 144));
        this.xvsqbgguif.setPadding(BDLocation.TypeServerError, 186, 133, 50);
        linearLayout.addView(this.xvsqbgguif);
        this.xvsqbgguif.setBackgroundColor(Color.parseColor("#5e32da"));
        TextView textView = new TextView(this);
        this.xrkpkozilk = textView;
        textView.setLayoutParams(new LinearLayout.LayoutParams(1770, 166));
        this.xrkpkozilk.setPadding(20, 107, 95, 80);
        linearLayout.addView(this.xrkpkozilk);
        this.xrkpkozilk.setBackgroundColor(Color.parseColor("#3b6171"));
        TimePicker timePicker2 = new TimePicker(this);
        this.ywltzgovlg = timePicker2;
        timePicker2.setLayoutParams(new LinearLayout.LayoutParams(1166, 47));
        this.ywltzgovlg.setPadding(35, 124, 193, 13);
        linearLayout.addView(this.ywltzgovlg);
        this.ywltzgovlg.setBackgroundColor(Color.parseColor("#97c3b8"));
        RelativeLayout relativeLayout = new RelativeLayout(this);
        this.uirrezpebe = relativeLayout;
        relativeLayout.setLayoutParams(new LinearLayout.LayoutParams(916, 750));
        this.uirrezpebe.setPadding(67, 91, 190, 183);
        linearLayout.addView(this.uirrezpebe);
        this.uirrezpebe.setBackgroundColor(Color.parseColor("#73b5d9"));
        TimePicker timePicker3 = new TimePicker(this);
        this.urhdujvpdf = timePicker3;
        timePicker3.setLayoutParams(new LinearLayout.LayoutParams(GattClient.STATE_PENDDING_DISCOVERY_SERVICE, TypedValues.TransitionType.TYPE_FROM));
        this.urhdujvpdf.setPadding(156, 34, 118, 87);
        linearLayout.addView(this.urhdujvpdf);
        this.urhdujvpdf.setBackgroundColor(Color.parseColor("#10547a"));
        TableLayout tableLayout2 = new TableLayout(this);
        this.gsthweuede = tableLayout2;
        tableLayout2.setLayoutParams(new LinearLayout.LayoutParams(818, 1777));
        this.gsthweuede.setPadding(17, 163, 102, 59);
        linearLayout.addView(this.gsthweuede);
        this.gsthweuede.setBackgroundColor(Color.parseColor("#073202"));
        RatingBar ratingBar3 = new RatingBar(this);
        this.dnuiywmbsy = ratingBar3;
        ratingBar3.setLayoutParams(new LinearLayout.LayoutParams(517, 1444));
        this.dnuiywmbsy.setPadding(86, 164, 66, 63);
        linearLayout.addView(this.dnuiywmbsy);
        this.dnuiywmbsy.setBackgroundColor(Color.parseColor("#3915cd"));
        RadioButton radioButton2 = new RadioButton(this);
        this.rklhsxkxzu = radioButton2;
        radioButton2.setLayoutParams(new LinearLayout.LayoutParams(943, 1913));
        this.rklhsxkxzu.setPadding(15, 118, 129, 154);
        linearLayout.addView(this.rklhsxkxzu);
        this.rklhsxkxzu.setBackgroundColor(Color.parseColor("#446507"));
        GridView gridView2 = new GridView(this);
        this.jbdasaxovs = gridView2;
        gridView2.setLayoutParams(new LinearLayout.LayoutParams(GattClient.STATE_PREPARE_PAIRING_REQUEST, 1714));
        this.jbdasaxovs.setPadding(114, 71, 21, 68);
        linearLayout.addView(this.jbdasaxovs);
        this.jbdasaxovs.setBackgroundColor(Color.parseColor("#db0212"));
        ProgressBar progressBar5 = new ProgressBar(this);
        this.toufcawdua = progressBar5;
        progressBar5.setLayoutParams(new LinearLayout.LayoutParams(531, 1957));
        this.toufcawdua.setPadding(25, 121, 166, 84);
        linearLayout.addView(this.toufcawdua);
        this.toufcawdua.setBackgroundColor(Color.parseColor("#c76e39"));
        Switch r22 = new Switch(this);
        this.qduhzmlbff = r22;
        r22.setLayoutParams(new LinearLayout.LayoutParams(358, 1045));
        this.qduhzmlbff.setPadding(95, 66, 138, 79);
        linearLayout.addView(this.qduhzmlbff);
        this.qduhzmlbff.setBackgroundColor(Color.parseColor("#b0ee88"));
        DatePicker datePicker2 = new DatePicker(this);
        this.mfuoqsoomv = datePicker2;
        datePicker2.setLayoutParams(new LinearLayout.LayoutParams(46, 117));
        this.mfuoqsoomv.setPadding(182, 179, 164, 116);
        linearLayout.addView(this.mfuoqsoomv);
        this.mfuoqsoomv.setBackgroundColor(Color.parseColor("#c33ea2"));
        ToggleButton toggleButton5 = new ToggleButton(this);
        this.tjgqmgddrz = toggleButton5;
        toggleButton5.setLayoutParams(new LinearLayout.LayoutParams(1051, 750));
        this.tjgqmgddrz.setPadding(25, 189, 30, 5);
        linearLayout.addView(this.tjgqmgddrz);
        this.tjgqmgddrz.setBackgroundColor(Color.parseColor("#ccddd4"));
        ProgressBar progressBar6 = new ProgressBar(this);
        this.cihxqbbgmr = progressBar6;
        progressBar6.setLayoutParams(new LinearLayout.LayoutParams(1434, 1145));
        this.cihxqbbgmr.setPadding(60, 165, 36, 24);
        linearLayout.addView(this.cihxqbbgmr);
        this.cihxqbbgmr.setBackgroundColor(Color.parseColor("#6492ae"));
        ImageView imageView = new ImageView(this);
        this.vsdrtxanue = imageView;
        imageView.setLayoutParams(new LinearLayout.LayoutParams(1140, 864));
        this.vsdrtxanue.setPadding(69, 145, 95, 122);
        linearLayout.addView(this.vsdrtxanue);
        this.vsdrtxanue.setBackgroundColor(Color.parseColor("#44b895"));
        RadioButton radioButton3 = new RadioButton(this);
        this.xzwjkayrnf = radioButton3;
        radioButton3.setLayoutParams(new LinearLayout.LayoutParams(955, 1414));
        this.xzwjkayrnf.setPadding(158, 171, 122, 77);
        linearLayout.addView(this.xzwjkayrnf);
        this.xzwjkayrnf.setBackgroundColor(Color.parseColor("#939927"));
        RatingBar ratingBar4 = new RatingBar(this);
        this.bnlmrlnypa = ratingBar4;
        ratingBar4.setLayoutParams(new LinearLayout.LayoutParams(1818, 382));
        this.bnlmrlnypa.setPadding(97, 67, 93, 32);
        linearLayout.addView(this.bnlmrlnypa);
        this.bnlmrlnypa.setBackgroundColor(Color.parseColor("#1d6456"));
        Button button = new Button(this);
        this.hxaviqlymv = button;
        button.setLayoutParams(new LinearLayout.LayoutParams(449, 721));
        this.hxaviqlymv.setPadding(56, 137, 52, 116);
        linearLayout.addView(this.hxaviqlymv);
        this.hxaviqlymv.setBackgroundColor(Color.parseColor("#b6dd48"));
        ScrollView scrollView2 = new ScrollView(this);
        this.adnvzfekdj = scrollView2;
        scrollView2.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.CycleType.TYPE_VISIBILITY, 384));
        this.adnvzfekdj.setPadding(0, 41, 163, 71);
        linearLayout.addView(this.adnvzfekdj);
        this.adnvzfekdj.setBackgroundColor(Color.parseColor("#f2f48c"));
        RelativeLayout relativeLayout2 = new RelativeLayout(this);
        this.tozxuovsoa = relativeLayout2;
        relativeLayout2.setLayoutParams(new LinearLayout.LayoutParams(755, 1586));
        this.tozxuovsoa.setPadding(32, 168, 136, 184);
        linearLayout.addView(this.tozxuovsoa);
        this.tozxuovsoa.setBackgroundColor(Color.parseColor("#7d179f"));
        ToggleButton toggleButton6 = new ToggleButton(this);
        this.dtuyjmclnv = toggleButton6;
        toggleButton6.setLayoutParams(new LinearLayout.LayoutParams(776, 287));
        this.dtuyjmclnv.setPadding(90, 107, 164, 10);
        linearLayout.addView(this.dtuyjmclnv);
        this.dtuyjmclnv.setBackgroundColor(Color.parseColor("#00b70b"));
        RadioButton radioButton4 = new RadioButton(this);
        this.yzuwhrmuqo = radioButton4;
        radioButton4.setLayoutParams(new LinearLayout.LayoutParams(1476, 1618));
        this.yzuwhrmuqo.setPadding(190, BDLocation.TypeCoarseLocation, 192, 78);
        linearLayout.addView(this.yzuwhrmuqo);
        this.yzuwhrmuqo.setBackgroundColor(Color.parseColor("#bb61df"));
        ToggleButton toggleButton7 = new ToggleButton(this);
        this.trccboxatt = toggleButton7;
        toggleButton7.setLayoutParams(new LinearLayout.LayoutParams(676, 822));
        this.trccboxatt.setPadding(182, 132, 97, 113);
        linearLayout.addView(this.trccboxatt);
        this.trccboxatt.setBackgroundColor(Color.parseColor("#b222ff"));
        SeekBar seekBar2 = new SeekBar(this);
        this.fdcxtvxnmk = seekBar2;
        seekBar2.setLayoutParams(new LinearLayout.LayoutParams(1185, 1694));
        this.fdcxtvxnmk.setPadding(171, 123, 192, 45);
        linearLayout.addView(this.fdcxtvxnmk);
        this.fdcxtvxnmk.setBackgroundColor(Color.parseColor("#38b4aa"));
        ScrollView scrollView3 = new ScrollView(this);
        this.kfzcbvupzp = scrollView3;
        scrollView3.setLayoutParams(new LinearLayout.LayoutParams(952, 592));
        this.kfzcbvupzp.setPadding(139, 23, 40, 18);
        linearLayout.addView(this.kfzcbvupzp);
        this.kfzcbvupzp.setBackgroundColor(Color.parseColor("#0182cf"));
        RatingBar ratingBar5 = new RatingBar(this);
        this.rjnarijmnp = ratingBar5;
        ratingBar5.setLayoutParams(new LinearLayout.LayoutParams(1487, 339));
        this.rjnarijmnp.setPadding(76, 65, 29, 132);
        linearLayout.addView(this.rjnarijmnp);
        this.rjnarijmnp.setBackgroundColor(Color.parseColor("#c8f65d"));
        ImageView imageView2 = new ImageView(this);
        this.kxihjmwlqg = imageView2;
        imageView2.setLayoutParams(new LinearLayout.LayoutParams(GattClient.STATE_READ_BATTERY_INFO, 1229));
        this.kxihjmwlqg.setPadding(0, 179, 165, 16);
        linearLayout.addView(this.kxihjmwlqg);
        this.kxihjmwlqg.setBackgroundColor(Color.parseColor("#0682c3"));
        TimePicker timePicker4 = new TimePicker(this);
        this.mesovzdjob = timePicker4;
        timePicker4.setLayoutParams(new LinearLayout.LayoutParams(1728, 1393));
        this.mesovzdjob.setPadding(46, 47, 62, 39);
        linearLayout.addView(this.mesovzdjob);
        this.mesovzdjob.setBackgroundColor(Color.parseColor("#1ec7d3"));
        ListView listView2 = new ListView(this);
        this.ypvhvzjiyh = listView2;
        listView2.setLayoutParams(new LinearLayout.LayoutParams(1837, 509));
        this.ypvhvzjiyh.setPadding(98, 120, 172, 5);
        linearLayout.addView(this.ypvhvzjiyh);
        this.ypvhvzjiyh.setBackgroundColor(Color.parseColor("#0cd1bc"));
        GridView gridView3 = new GridView(this);
        this.zmptpoaqsm = gridView3;
        gridView3.setLayoutParams(new LinearLayout.LayoutParams(925, 185));
        this.zmptpoaqsm.setPadding(BDLocation.TypeServerDecryptError, 55, 157, 123);
        linearLayout.addView(this.zmptpoaqsm);
        this.zmptpoaqsm.setBackgroundColor(Color.parseColor("#2d7a83"));
        ImageView imageView3 = new ImageView(this);
        this.xtunpxbgtc = imageView3;
        imageView3.setLayoutParams(new LinearLayout.LayoutParams(467, 1875));
        this.xtunpxbgtc.setPadding(198, 137, 132, 96);
        linearLayout.addView(this.xtunpxbgtc);
        this.xtunpxbgtc.setBackgroundColor(Color.parseColor("#16b3b9"));
        Switch r23 = new Switch(this);
        this.umhfbfnorb = r23;
        r23.setLayoutParams(new LinearLayout.LayoutParams(1548, TypedValues.TransitionType.TYPE_AUTO_TRANSITION));
        this.umhfbfnorb.setPadding(49, 52, 54, 29);
        linearLayout.addView(this.umhfbfnorb);
        this.umhfbfnorb.setBackgroundColor(Color.parseColor("#927700"));
        GridView gridView4 = new GridView(this);
        this.cbunreuzkt = gridView4;
        gridView4.setLayoutParams(new LinearLayout.LayoutParams(1115, 1428));
        this.cbunreuzkt.setPadding(153, 65, 140, 192);
        linearLayout.addView(this.cbunreuzkt);
        this.cbunreuzkt.setBackgroundColor(Color.parseColor("#b01b17"));
        EditText editText = new EditText(this);
        this.fnwkkgsnct = editText;
        editText.setLayoutParams(new LinearLayout.LayoutParams(986, 1610));
        this.fnwkkgsnct.setPadding(176, 171, 93, 96);
        linearLayout.addView(this.fnwkkgsnct);
        this.fnwkkgsnct.setBackgroundColor(Color.parseColor("#4ffd55"));
        FrameLayout frameLayout3 = new FrameLayout(this);
        this.uewihwggyq = frameLayout3;
        frameLayout3.setLayoutParams(new LinearLayout.LayoutParams(1735, 886));
        this.uewihwggyq.setPadding(110, 94, 103, 38);
        linearLayout.addView(this.uewihwggyq);
        this.uewihwggyq.setBackgroundColor(Color.parseColor("#f8a43b"));
        DatePicker datePicker3 = new DatePicker(this);
        this.qdulmjchye = datePicker3;
        datePicker3.setLayoutParams(new LinearLayout.LayoutParams(1424, 1823));
        this.qdulmjchye.setPadding(84, 108, 50, 181);
        linearLayout.addView(this.qdulmjchye);
        this.qdulmjchye.setBackgroundColor(Color.parseColor("#c7d3dd"));
        RelativeLayout relativeLayout3 = new RelativeLayout(this);
        this.elomokefll = relativeLayout3;
        relativeLayout3.setLayoutParams(new LinearLayout.LayoutParams(1269, 1618));
        this.elomokefll.setPadding(54, 25, 42, 128);
        linearLayout.addView(this.elomokefll);
        this.elomokefll.setBackgroundColor(Color.parseColor("#dbb295"));
        RatingBar ratingBar6 = new RatingBar(this);
        this.eveecfarpg = ratingBar6;
        ratingBar6.setLayoutParams(new LinearLayout.LayoutParams(1329, 1914));
        this.eveecfarpg.setPadding(77, 159, 7, 153);
        linearLayout.addView(this.eveecfarpg);
        this.eveecfarpg.setBackgroundColor(Color.parseColor("#d95ca1"));
        ViewFlipper viewFlipper = new ViewFlipper(this);
        this.cxgoqsviwn = viewFlipper;
        viewFlipper.setLayoutParams(new LinearLayout.LayoutParams(1436, 1379));
        this.cxgoqsviwn.setPadding(BDLocation.TypeCoarseLocation, 140, 27, 186);
        linearLayout.addView(this.cxgoqsviwn);
        this.cxgoqsviwn.setBackgroundColor(Color.parseColor("#9db34e"));
        ProgressBar progressBar7 = new ProgressBar(this);
        this.szaipxnlau = progressBar7;
        progressBar7.setLayoutParams(new LinearLayout.LayoutParams(1801, 1253));
        this.szaipxnlau.setPadding(86, BDLocation.TypeCoarseLocation, 88, 147);
        linearLayout.addView(this.szaipxnlau);
        this.szaipxnlau.setBackgroundColor(Color.parseColor("#768c14"));
        ListView listView3 = new ListView(this);
        this.nalsbhirzm = listView3;
        listView3.setLayoutParams(new LinearLayout.LayoutParams(623, 102));
        this.nalsbhirzm.setPadding(BDLocation.TypeNetWorkLocation, 132, 3, 171);
        linearLayout.addView(this.nalsbhirzm);
        this.nalsbhirzm.setBackgroundColor(Color.parseColor("#cb27aa"));
        Spinner spinner = new Spinner(this);
        this.yyizgjwuyb = spinner;
        spinner.setLayoutParams(new LinearLayout.LayoutParams(1806, 831));
        this.yyizgjwuyb.setPadding(89, 68, 16, 12);
        linearLayout.addView(this.yyizgjwuyb);
        this.yyizgjwuyb.setBackgroundColor(Color.parseColor("#330dab"));
        DatePicker datePicker4 = new DatePicker(this);
        this.qcxqpgtqhe = datePicker4;
        datePicker4.setLayoutParams(new LinearLayout.LayoutParams(1799, 440));
        this.qcxqpgtqhe.setPadding(91, 141, 35, 103);
        linearLayout.addView(this.qcxqpgtqhe);
        this.qcxqpgtqhe.setBackgroundColor(Color.parseColor("#5389ac"));
        TextView textView2 = new TextView(this);
        this.hbsglbakit = textView2;
        textView2.setLayoutParams(new LinearLayout.LayoutParams(1360, 120));
        this.hbsglbakit.setPadding(54, 130, 89, 174);
        linearLayout.addView(this.hbsglbakit);
        this.hbsglbakit.setBackgroundColor(Color.parseColor("#081083"));
        TimePicker timePicker5 = new TimePicker(this);
        this.tidxszxpda = timePicker5;
        timePicker5.setLayoutParams(new LinearLayout.LayoutParams(1052, 1644));
        this.tidxszxpda.setPadding(145, 113, 41, 159);
        linearLayout.addView(this.tidxszxpda);
        this.tidxszxpda.setBackgroundColor(Color.parseColor("#abb78e"));
        ProgressBar progressBar8 = new ProgressBar(this);
        this.mlxuhculah = progressBar8;
        progressBar8.setLayoutParams(new LinearLayout.LayoutParams(619, CodeUtils.DEFAULT_REQ_HEIGHT));
        this.mlxuhculah.setPadding(116, 156, 131, WebSocketProtocol.PAYLOAD_SHORT);
        linearLayout.addView(this.mlxuhculah);
        this.mlxuhculah.setBackgroundColor(Color.parseColor("#239ba3"));
        ViewFlipper viewFlipper2 = new ViewFlipper(this);
        this.jogkivrcpz = viewFlipper2;
        viewFlipper2.setLayoutParams(new LinearLayout.LayoutParams(43, 1587));
        this.jogkivrcpz.setPadding(192, 98, 27, 51);
        linearLayout.addView(this.jogkivrcpz);
        this.jogkivrcpz.setBackgroundColor(Color.parseColor("#eca43c"));
        ToggleButton toggleButton8 = new ToggleButton(this);
        this.wovqeafhgh = toggleButton8;
        toggleButton8.setLayoutParams(new LinearLayout.LayoutParams(1811, 1148));
        this.wovqeafhgh.setPadding(140, 180, 170, 10);
        linearLayout.addView(this.wovqeafhgh);
        this.wovqeafhgh.setBackgroundColor(Color.parseColor("#3e168f"));
        TextView textView3 = new TextView(this);
        this.oxtcalsasr = textView3;
        textView3.setLayoutParams(new LinearLayout.LayoutParams(336, 226));
        this.oxtcalsasr.setPadding(183, 20, 65, 185);
        linearLayout.addView(this.oxtcalsasr);
        this.oxtcalsasr.setBackgroundColor(Color.parseColor("#f737a0"));
        Button button2 = new Button(this);
        this.rktuuwxcum = button2;
        button2.setLayoutParams(new LinearLayout.LayoutParams(1414, 1889));
        this.rktuuwxcum.setPadding(PictureConfig.CHOOSE_REQUEST, 64, 11, 92);
        linearLayout.addView(this.rktuuwxcum);
        this.rktuuwxcum.setBackgroundColor(Color.parseColor("#d75adf"));
        CheckBox checkBox = new CheckBox(this);
        this.wnsqdznkeq = checkBox;
        checkBox.setLayoutParams(new LinearLayout.LayoutParams(28, 368));
        this.wnsqdznkeq.setPadding(142, 13, 174, 60);
        linearLayout.addView(this.wnsqdznkeq);
        this.wnsqdznkeq.setBackgroundColor(Color.parseColor("#89422d"));
        RadioButton radioButton5 = new RadioButton(this);
        this.bcadvcrwqz = radioButton5;
        radioButton5.setLayoutParams(new LinearLayout.LayoutParams(524, 1623));
        this.bcadvcrwqz.setPadding(32, 151, 133, 182);
        linearLayout.addView(this.bcadvcrwqz);
        this.bcadvcrwqz.setBackgroundColor(Color.parseColor("#9ad015"));
        ProgressBar progressBar9 = new ProgressBar(this);
        this.vjnnnfxeof = progressBar9;
        progressBar9.setLayoutParams(new LinearLayout.LayoutParams(1438, 1365));
        this.vjnnnfxeof.setPadding(BDLocation.TypeCoarseLocation, 117, 110, 199);
        linearLayout.addView(this.vjnnnfxeof);
        this.vjnnnfxeof.setBackgroundColor(Color.parseColor("#4879aa"));
        RatingBar ratingBar7 = new RatingBar(this);
        this.wapxxjfdtt = ratingBar7;
        ratingBar7.setLayoutParams(new LinearLayout.LayoutParams(1256, 471));
        this.wapxxjfdtt.setPadding(97, 25, 139, 85);
        linearLayout.addView(this.wapxxjfdtt);
        this.wapxxjfdtt.setBackgroundColor(Color.parseColor("#aa18ff"));
        RadioButton radioButton6 = new RadioButton(this);
        this.wrcsjnoelr = radioButton6;
        radioButton6.setLayoutParams(new LinearLayout.LayoutParams(797, 797));
        this.wrcsjnoelr.setPadding(155, 150, 24, 136);
        linearLayout.addView(this.wrcsjnoelr);
        this.wrcsjnoelr.setBackgroundColor(Color.parseColor("#f707c2"));
        LinearLayout linearLayout4 = new LinearLayout(this);
        this.biyhiadrax = linearLayout4;
        linearLayout4.setLayoutParams(new LinearLayout.LayoutParams(1607, 991));
        this.biyhiadrax.setPadding(137, 140, 152, 87);
        linearLayout.addView(this.biyhiadrax);
        this.biyhiadrax.setBackgroundColor(Color.parseColor("#ecd677"));
        Button button3 = new Button(this);
        this.wrdaatsfya = button3;
        button3.setLayoutParams(new LinearLayout.LayoutParams(42, 1060));
        this.wrdaatsfya.setPadding(157, 142, 67, 142);
        linearLayout.addView(this.wrdaatsfya);
        this.wrdaatsfya.setBackgroundColor(Color.parseColor("#571b2d"));
        RadioButton radioButton7 = new RadioButton(this);
        this.fycfwagnpq = radioButton7;
        radioButton7.setLayoutParams(new LinearLayout.LayoutParams(223, 266));
        this.fycfwagnpq.setPadding(99, 50, 0, 172);
        linearLayout.addView(this.fycfwagnpq);
        this.fycfwagnpq.setBackgroundColor(Color.parseColor("#8b1ed6"));
        RatingBar ratingBar8 = new RatingBar(this);
        this.ohsujdariz = ratingBar8;
        ratingBar8.setLayoutParams(new LinearLayout.LayoutParams(721, 1608));
        this.ohsujdariz.setPadding(152, 121, 83, 148);
        linearLayout.addView(this.ohsujdariz);
        this.ohsujdariz.setBackgroundColor(Color.parseColor("#5a2b14"));
        RatingBar ratingBar9 = new RatingBar(this);
        this.bewtmotqjg = ratingBar9;
        ratingBar9.setLayoutParams(new LinearLayout.LayoutParams(1935, 600));
        this.bewtmotqjg.setPadding(182, 125, 172, 97);
        linearLayout.addView(this.bewtmotqjg);
        this.bewtmotqjg.setBackgroundColor(Color.parseColor("#4e0832"));
        RelativeLayout relativeLayout4 = new RelativeLayout(this);
        this.ljerivaaof = relativeLayout4;
        relativeLayout4.setLayoutParams(new LinearLayout.LayoutParams(1047, 363));
        this.ljerivaaof.setPadding(94, 136, 148, 100);
        linearLayout.addView(this.ljerivaaof);
        this.ljerivaaof.setBackgroundColor(Color.parseColor("#0ac7ae"));
        GridView gridView5 = new GridView(this);
        this.pravffimwq = gridView5;
        gridView5.setLayoutParams(new LinearLayout.LayoutParams(356, 1133));
        this.pravffimwq.setPadding(97, PictureConfig.CHOOSE_REQUEST, 181, 89);
        linearLayout.addView(this.pravffimwq);
        this.pravffimwq.setBackgroundColor(Color.parseColor("#76409f"));
        CheckBox checkBox2 = new CheckBox(this);
        this.zjampkkzod = checkBox2;
        checkBox2.setLayoutParams(new LinearLayout.LayoutParams(1836, 238));
        this.zjampkkzod.setPadding(36, 77, 77, 181);
        linearLayout.addView(this.zjampkkzod);
        this.zjampkkzod.setBackgroundColor(Color.parseColor("#6a0637"));
        Spinner spinner2 = new Spinner(this);
        this.dkvxrjbmho = spinner2;
        spinner2.setLayoutParams(new LinearLayout.LayoutParams(1825, 1354));
        this.dkvxrjbmho.setPadding(111, 75, WebSocketProtocol.PAYLOAD_SHORT, 148);
        linearLayout.addView(this.dkvxrjbmho);
        this.dkvxrjbmho.setBackgroundColor(Color.parseColor("#60f180"));
        ToggleButton toggleButton9 = new ToggleButton(this);
        this.xahrnnlhkv = toggleButton9;
        toggleButton9.setLayoutParams(new LinearLayout.LayoutParams(457, 136));
        this.xahrnnlhkv.setPadding(153, 148, 101, 150);
        linearLayout.addView(this.xahrnnlhkv);
        this.xahrnnlhkv.setBackgroundColor(Color.parseColor("#88005e"));
        GridView gridView6 = new GridView(this);
        this.wjiaaxickv = gridView6;
        gridView6.setLayoutParams(new LinearLayout.LayoutParams(1348, 1606));
        this.wjiaaxickv.setPadding(11, 96, 149, 9);
        linearLayout.addView(this.wjiaaxickv);
        this.wjiaaxickv.setBackgroundColor(Color.parseColor("#39874d"));
        Switch r24 = new Switch(this);
        this.juuhagzeid = r24;
        r24.setLayoutParams(new LinearLayout.LayoutParams(1362, 1437));
        this.juuhagzeid.setPadding(39, 93, 31, 80);
        linearLayout.addView(this.juuhagzeid);
        this.juuhagzeid.setBackgroundColor(Color.parseColor("#d27d65"));
        TextView textView4 = new TextView(this);
        this.skaexddbti = textView4;
        textView4.setLayoutParams(new LinearLayout.LayoutParams(1766, 601));
        this.skaexddbti.setPadding(67, 177, BDLocation.TypeNetWorkLocation, 147);
        linearLayout.addView(this.skaexddbti);
        this.skaexddbti.setBackgroundColor(Color.parseColor("#207f05"));
        TableLayout tableLayout3 = new TableLayout(this);
        this.zyxgkntsvx = tableLayout3;
        tableLayout3.setLayoutParams(new LinearLayout.LayoutParams(1908, 1288));
        this.zyxgkntsvx.setPadding(111, 181, 193, 41);
        linearLayout.addView(this.zyxgkntsvx);
        this.zyxgkntsvx.setBackgroundColor(Color.parseColor("#6156d6"));
        EditText editText2 = new EditText(this);
        this.exewopphpd = editText2;
        editText2.setLayoutParams(new LinearLayout.LayoutParams(682, 715));
        this.exewopphpd.setPadding(144, 87, 92, 8);
        linearLayout.addView(this.exewopphpd);
        this.exewopphpd.setBackgroundColor(Color.parseColor("#b90131"));
        RadioButton radioButton8 = new RadioButton(this);
        this.ccommxnqkt = radioButton8;
        radioButton8.setLayoutParams(new LinearLayout.LayoutParams(1062, 1075));
        this.ccommxnqkt.setPadding(80, 137, 87, 85);
        linearLayout.addView(this.ccommxnqkt);
        this.ccommxnqkt.setBackgroundColor(Color.parseColor("#b63c5e"));
        DatePicker datePicker5 = new DatePicker(this);
        this.ggszbquyea = datePicker5;
        datePicker5.setLayoutParams(new LinearLayout.LayoutParams(1676, 1738));
        this.ggszbquyea.setPadding(75, 6, 17, 22);
        linearLayout.addView(this.ggszbquyea);
        this.ggszbquyea.setBackgroundColor(Color.parseColor("#c0bc32"));
        ImageView imageView4 = new ImageView(this);
        this.jhrkjdxfyy = imageView4;
        imageView4.setLayoutParams(new LinearLayout.LayoutParams(1258, 1322));
        this.jhrkjdxfyy.setPadding(159, 12, 11, 59);
        linearLayout.addView(this.jhrkjdxfyy);
        this.jhrkjdxfyy.setBackgroundColor(Color.parseColor("#a4d865"));
        TimePicker timePicker6 = new TimePicker(this);
        this.xucqxzrzrv = timePicker6;
        timePicker6.setLayoutParams(new LinearLayout.LayoutParams(1730, 914));
        this.xucqxzrzrv.setPadding(8, 68, 141, 189);
        linearLayout.addView(this.xucqxzrzrv);
        this.xucqxzrzrv.setBackgroundColor(Color.parseColor("#a5f3eb"));
        RadioButton radioButton9 = new RadioButton(this);
        this.timqsjcvic = radioButton9;
        radioButton9.setLayoutParams(new LinearLayout.LayoutParams(427, 1036));
        this.timqsjcvic.setPadding(46, 125, 190, 111);
        linearLayout.addView(this.timqsjcvic);
        this.timqsjcvic.setBackgroundColor(Color.parseColor("#eab642"));
        TableLayout tableLayout4 = new TableLayout(this);
        this.wyydukkhcs = tableLayout4;
        tableLayout4.setLayoutParams(new LinearLayout.LayoutParams(1181, 739));
        this.wyydukkhcs.setPadding(69, 38, 48, 152);
        linearLayout.addView(this.wyydukkhcs);
        this.wyydukkhcs.setBackgroundColor(Color.parseColor("#882950"));
        GridView gridView7 = new GridView(this);
        this.sovqezppph = gridView7;
        gridView7.setLayoutParams(new LinearLayout.LayoutParams(1615, 1386));
        this.sovqezppph.setPadding(104, 163, 110, 154);
        linearLayout.addView(this.sovqezppph);
        this.sovqezppph.setBackgroundColor(Color.parseColor("#185152"));
        RelativeLayout relativeLayout5 = new RelativeLayout(this);
        this.nitcnfntwh = relativeLayout5;
        relativeLayout5.setLayoutParams(new LinearLayout.LayoutParams(1975, 271));
        this.nitcnfntwh.setPadding(18, 111, 84, 157);
        linearLayout.addView(this.nitcnfntwh);
        this.nitcnfntwh.setBackgroundColor(Color.parseColor("#ed0db6"));
        Button button4 = new Button(this);
        this.xkrugsejwl = button4;
        button4.setLayoutParams(new LinearLayout.LayoutParams(758, 1366));
        this.xkrugsejwl.setPadding(154, 16, 33, 52);
        linearLayout.addView(this.xkrugsejwl);
        this.xkrugsejwl.setBackgroundColor(Color.parseColor("#bcb42e"));
        ViewFlipper viewFlipper3 = new ViewFlipper(this);
        this.ofmlgnbsoj = viewFlipper3;
        viewFlipper3.setLayoutParams(new LinearLayout.LayoutParams(517, PointerIconCompat.TYPE_ZOOM_IN));
        this.ofmlgnbsoj.setPadding(81, 2, 171, 153);
        linearLayout.addView(this.ofmlgnbsoj);
        this.ofmlgnbsoj.setBackgroundColor(Color.parseColor("#22ec43"));
        ToggleButton toggleButton10 = new ToggleButton(this);
        this.yxplmhehlg = toggleButton10;
        toggleButton10.setLayoutParams(new LinearLayout.LayoutParams(1448, 1910));
        this.yxplmhehlg.setPadding(90, 26, BDLocation.TypeCoarseLocation, 196);
        linearLayout.addView(this.yxplmhehlg);
        this.yxplmhehlg.setBackgroundColor(Color.parseColor("#ec2ef7"));
        EditText editText3 = new EditText(this);
        this.bkvdynojsm = editText3;
        editText3.setLayoutParams(new LinearLayout.LayoutParams(677, TypedValues.CycleType.TYPE_WAVE_PHASE));
        this.bkvdynojsm.setPadding(174, 35, 76, 61);
        linearLayout.addView(this.bkvdynojsm);
        this.bkvdynojsm.setBackgroundColor(Color.parseColor("#f27966"));
        RelativeLayout relativeLayout6 = new RelativeLayout(this);
        this.rdolkgusvx = relativeLayout6;
        relativeLayout6.setLayoutParams(new LinearLayout.LayoutParams(889, 1503));
        this.rdolkgusvx.setPadding(194, 197, 4, 123);
        linearLayout.addView(this.rdolkgusvx);
        this.rdolkgusvx.setBackgroundColor(Color.parseColor("#60d4d5"));
        DatePicker datePicker6 = new DatePicker(this);
        this.kwlsgvdsaf = datePicker6;
        datePicker6.setLayoutParams(new LinearLayout.LayoutParams(1216, 84));
        this.kwlsgvdsaf.setPadding(39, 98, 5, 196);
        linearLayout.addView(this.kwlsgvdsaf);
        this.kwlsgvdsaf.setBackgroundColor(Color.parseColor("#1e4aa5"));
        EditText editText4 = new EditText(this);
        this.sihtqslaus = editText4;
        editText4.setLayoutParams(new LinearLayout.LayoutParams(1974, 1403));
        this.sihtqslaus.setPadding(68, 75, 106, 141);
        linearLayout.addView(this.sihtqslaus);
        this.sihtqslaus.setBackgroundColor(Color.parseColor("#8dd942"));
        EditText editText5 = new EditText(this);
        this.ezrnajeutf = editText5;
        editText5.setLayoutParams(new LinearLayout.LayoutParams(1255, 629));
        this.ezrnajeutf.setPadding(75, 192, 193, 140);
        linearLayout.addView(this.ezrnajeutf);
        this.ezrnajeutf.setBackgroundColor(Color.parseColor("#a74ee7"));
        ImageView imageView5 = new ImageView(this);
        this.sxzytjdlwg = imageView5;
        imageView5.setLayoutParams(new LinearLayout.LayoutParams(872, 805));
        this.sxzytjdlwg.setPadding(6, 158, 185, 135);
        linearLayout.addView(this.sxzytjdlwg);
        this.sxzytjdlwg.setBackgroundColor(Color.parseColor("#975c79"));
        Button button5 = new Button(this);
        this.ttpujkfgvm = button5;
        button5.setLayoutParams(new LinearLayout.LayoutParams(920, TypedValues.PositionType.TYPE_PERCENT_WIDTH));
        this.ttpujkfgvm.setPadding(165, 8, 34, 185);
        linearLayout.addView(this.ttpujkfgvm);
        this.ttpujkfgvm.setBackgroundColor(Color.parseColor("#211015"));
        ToggleButton toggleButton11 = new ToggleButton(this);
        this.xeajcyxrij = toggleButton11;
        toggleButton11.setLayoutParams(new LinearLayout.LayoutParams(1391, 1032));
        this.xeajcyxrij.setPadding(166, BDLocation.TypeCoarseLocation, 96, 67);
        linearLayout.addView(this.xeajcyxrij);
        this.xeajcyxrij.setBackgroundColor(Color.parseColor("#fb2054"));
        DatePicker datePicker7 = new DatePicker(this);
        this.vzkgryhnei = datePicker7;
        datePicker7.setLayoutParams(new LinearLayout.LayoutParams(1305, 1512));
        this.vzkgryhnei.setPadding(137, 24, 102, 77);
        linearLayout.addView(this.vzkgryhnei);
        this.vzkgryhnei.setBackgroundColor(Color.parseColor("#531110"));
        CheckBox checkBox3 = new CheckBox(this);
        this.ijqqrvdlgh = checkBox3;
        checkBox3.setLayoutParams(new LinearLayout.LayoutParams(1590, 276));
        this.ijqqrvdlgh.setPadding(118, 26, 140, 40);
        linearLayout.addView(this.ijqqrvdlgh);
        this.ijqqrvdlgh.setBackgroundColor(Color.parseColor("#418128"));
        RatingBar ratingBar10 = new RatingBar(this);
        this.dqxrocchuc = ratingBar10;
        ratingBar10.setLayoutParams(new LinearLayout.LayoutParams(1434, 1400));
        this.dqxrocchuc.setPadding(116, 103, 197, 164);
        linearLayout.addView(this.dqxrocchuc);
        this.dqxrocchuc.setBackgroundColor(Color.parseColor("#17e6c6"));
        RatingBar ratingBar11 = new RatingBar(this);
        this.rtnzgldlym = ratingBar11;
        ratingBar11.setLayoutParams(new LinearLayout.LayoutParams(1332, 1161));
        this.rtnzgldlym.setPadding(168, 35, 15, 35);
        linearLayout.addView(this.rtnzgldlym);
        this.rtnzgldlym.setBackgroundColor(Color.parseColor("#c3ebde"));
        ScrollView scrollView4 = new ScrollView(this);
        this.bzqzmsyseb = scrollView4;
        scrollView4.setLayoutParams(new LinearLayout.LayoutParams(757, 1288));
        this.bzqzmsyseb.setPadding(183, 93, 103, 152);
        linearLayout.addView(this.bzqzmsyseb);
        this.bzqzmsyseb.setBackgroundColor(Color.parseColor("#690a41"));
        DatePicker datePicker8 = new DatePicker(this);
        this.xocxtfcvni = datePicker8;
        datePicker8.setLayoutParams(new LinearLayout.LayoutParams(88, 234));
        this.xocxtfcvni.setPadding(65, 133, 65, 50);
        linearLayout.addView(this.xocxtfcvni);
        this.xocxtfcvni.setBackgroundColor(Color.parseColor("#cd1618"));
        RatingBar ratingBar12 = new RatingBar(this);
        this.jmjuunhdfc = ratingBar12;
        ratingBar12.setLayoutParams(new LinearLayout.LayoutParams(880, 1773));
        this.jmjuunhdfc.setPadding(171, 183, 1, 26);
        linearLayout.addView(this.jmjuunhdfc);
        this.jmjuunhdfc.setBackgroundColor(Color.parseColor("#8faf3c"));
        Switch r25 = new Switch(this);
        this.dalpwryqjs = r25;
        r25.setLayoutParams(new LinearLayout.LayoutParams(1307, 156));
        this.dalpwryqjs.setPadding(168, 140, 41, 164);
        linearLayout.addView(this.dalpwryqjs);
        this.dalpwryqjs.setBackgroundColor(Color.parseColor("#69a3e4"));
        TextView textView5 = new TextView(this);
        this.yrlfdwrbye = textView5;
        textView5.setLayoutParams(new LinearLayout.LayoutParams(921, 1515));
        this.yrlfdwrbye.setPadding(36, BDLocation.TypeNetWorkLocation, 128, 106);
        linearLayout.addView(this.yrlfdwrbye);
        this.yrlfdwrbye.setBackgroundColor(Color.parseColor("#61b4fe"));
        ImageView imageView6 = new ImageView(this);
        this.zmgtyuwhmy = imageView6;
        imageView6.setLayoutParams(new LinearLayout.LayoutParams(784, 1285));
        this.zmgtyuwhmy.setPadding(127, 199, 107, 187);
        linearLayout.addView(this.zmgtyuwhmy);
        this.zmgtyuwhmy.setBackgroundColor(Color.parseColor("#aba80a"));
        TextView textView6 = new TextView(this);
        this.yuaeoskujj = textView6;
        textView6.setLayoutParams(new LinearLayout.LayoutParams(1383, 1098));
        this.yuaeoskujj.setPadding(177, 194, 58, 178);
        linearLayout.addView(this.yuaeoskujj);
        this.yuaeoskujj.setBackgroundColor(Color.parseColor("#fae9a1"));
        TimePicker timePicker7 = new TimePicker(this);
        this.ahswgxwseu = timePicker7;
        timePicker7.setLayoutParams(new LinearLayout.LayoutParams(1877, 1119));
        this.ahswgxwseu.setPadding(199, 70, 154, 58);
        linearLayout.addView(this.ahswgxwseu);
        this.ahswgxwseu.setBackgroundColor(Color.parseColor("#cd6c38"));
        TextView textView7 = new TextView(this);
        this.cilvlfderw = textView7;
        textView7.setLayoutParams(new LinearLayout.LayoutParams(1438, 1429));
        this.cilvlfderw.setPadding(81, 132, 75, 143);
        linearLayout.addView(this.cilvlfderw);
        this.cilvlfderw.setBackgroundColor(Color.parseColor("#3e659e"));
        ImageView imageView7 = new ImageView(this);
        this.atfourjjdy = imageView7;
        imageView7.setLayoutParams(new LinearLayout.LayoutParams(850, 819));
        this.atfourjjdy.setPadding(62, 27, 37, 152);
        linearLayout.addView(this.atfourjjdy);
        this.atfourjjdy.setBackgroundColor(Color.parseColor("#146406"));
        TableLayout tableLayout5 = new TableLayout(this);
        this.zbbkxhvxzi = tableLayout5;
        tableLayout5.setLayoutParams(new LinearLayout.LayoutParams(826, 775));
        this.zbbkxhvxzi.setPadding(127, 169, 76, 184);
        linearLayout.addView(this.zbbkxhvxzi);
        this.zbbkxhvxzi.setBackgroundColor(Color.parseColor("#ea5f75"));
        Switch r26 = new Switch(this);
        this.piziohxwsh = r26;
        r26.setLayoutParams(new LinearLayout.LayoutParams(1544, 670));
        this.piziohxwsh.setPadding(84, 170, 165, 84);
        linearLayout.addView(this.piziohxwsh);
        this.piziohxwsh.setBackgroundColor(Color.parseColor("#1f3c94"));
        RadioButton radioButton10 = new RadioButton(this);
        this.upzaaygocj = radioButton10;
        radioButton10.setLayoutParams(new LinearLayout.LayoutParams(1489, 1421));
        this.upzaaygocj.setPadding(21, 88, 12, 158);
        linearLayout.addView(this.upzaaygocj);
        this.upzaaygocj.setBackgroundColor(Color.parseColor("#e4b40a"));
        EditText editText6 = new EditText(this);
        this.trtupguoap = editText6;
        editText6.setLayoutParams(new LinearLayout.LayoutParams(1426, 1984));
        this.trtupguoap.setPadding(48, 89, 164, 183);
        linearLayout.addView(this.trtupguoap);
        this.trtupguoap.setBackgroundColor(Color.parseColor("#0b8253"));
        ProgressBar progressBar10 = new ProgressBar(this);
        this.hdtwftdlbc = progressBar10;
        progressBar10.setLayoutParams(new LinearLayout.LayoutParams(1365, TypedValues.Custom.TYPE_STRING));
        this.hdtwftdlbc.setPadding(42, 47, 74, 115);
        linearLayout.addView(this.hdtwftdlbc);
        this.hdtwftdlbc.setBackgroundColor(Color.parseColor("#4c6908"));
        SeekBar seekBar3 = new SeekBar(this);
        this.cfmlmlqjuk = seekBar3;
        seekBar3.setLayoutParams(new LinearLayout.LayoutParams(278, 104));
        this.cfmlmlqjuk.setPadding(141, 57, 198, 30);
        linearLayout.addView(this.cfmlmlqjuk);
        this.cfmlmlqjuk.setBackgroundColor(Color.parseColor("#4f1924"));
        ProgressBar progressBar11 = new ProgressBar(this);
        this.ttyvpppcaj = progressBar11;
        progressBar11.setLayoutParams(new LinearLayout.LayoutParams(814, 1575));
        this.ttyvpppcaj.setPadding(151, 87, 159, 116);
        linearLayout.addView(this.ttyvpppcaj);
        this.ttyvpppcaj.setBackgroundColor(Color.parseColor("#b3f6f9"));
        RatingBar ratingBar13 = new RatingBar(this);
        this.twbsbbuull = ratingBar13;
        ratingBar13.setLayoutParams(new LinearLayout.LayoutParams(1346, 1882));
        this.twbsbbuull.setPadding(170, 139, 170, 38);
        linearLayout.addView(this.twbsbbuull);
        this.twbsbbuull.setBackgroundColor(Color.parseColor("#794ced"));
        GridView gridView8 = new GridView(this);
        this.ekbkdoagnn = gridView8;
        gridView8.setLayoutParams(new LinearLayout.LayoutParams(1282, 353));
        this.ekbkdoagnn.setPadding(180, PictureConfig.CHOOSE_REQUEST, 144, 64);
        linearLayout.addView(this.ekbkdoagnn);
        this.ekbkdoagnn.setBackgroundColor(Color.parseColor("#4a0a60"));
        CheckBox checkBox4 = new CheckBox(this);
        this.jgimttspoo = checkBox4;
        checkBox4.setLayoutParams(new LinearLayout.LayoutParams(962, 139));
        this.jgimttspoo.setPadding(180, 196, 1, 46);
        linearLayout.addView(this.jgimttspoo);
        this.jgimttspoo.setBackgroundColor(Color.parseColor("#759d9f"));
        EditText editText7 = new EditText(this);
        this.tkqjemiosm = editText7;
        editText7.setLayoutParams(new LinearLayout.LayoutParams(95, 1642));
        this.tkqjemiosm.setPadding(79, 186, 192, 95);
        linearLayout.addView(this.tkqjemiosm);
        this.tkqjemiosm.setBackgroundColor(Color.parseColor("#37015e"));
        Button button6 = new Button(this);
        this.krocpncexa = button6;
        button6.setLayoutParams(new LinearLayout.LayoutParams(1576, 240));
        this.krocpncexa.setPadding(77, 155, 196, 65);
        linearLayout.addView(this.krocpncexa);
        this.krocpncexa.setBackgroundColor(Color.parseColor("#81c6c6"));
        GridView gridView9 = new GridView(this);
        this.dpmtcdtoka = gridView9;
        gridView9.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.TransitionType.TYPE_TO, 554));
        this.dpmtcdtoka.setPadding(84, 33, 144, 11);
        linearLayout.addView(this.dpmtcdtoka);
        this.dpmtcdtoka.setBackgroundColor(Color.parseColor("#3240da"));
        ViewFlipper viewFlipper4 = new ViewFlipper(this);
        this.bfvkrxucha = viewFlipper4;
        viewFlipper4.setLayoutParams(new LinearLayout.LayoutParams(1745, 1410));
        this.bfvkrxucha.setPadding(111, 62, 136, 10);
        linearLayout.addView(this.bfvkrxucha);
        this.bfvkrxucha.setBackgroundColor(Color.parseColor("#959d7c"));
        CheckBox checkBox5 = new CheckBox(this);
        this.iijqlazsiu = checkBox5;
        checkBox5.setLayoutParams(new LinearLayout.LayoutParams(1776, WebSocketImpl.DEFAULT_WSS_PORT));
        this.iijqlazsiu.setPadding(51, 131, 9, 147);
        linearLayout.addView(this.iijqlazsiu);
        this.iijqlazsiu.setBackgroundColor(Color.parseColor("#4129c5"));
        GridView gridView10 = new GridView(this);
        this.lowkumamce = gridView10;
        gridView10.setLayoutParams(new LinearLayout.LayoutParams(1221, 1693));
        this.lowkumamce.setPadding(144, BDLocation.TypeNetWorkLocation, 180, 143);
        linearLayout.addView(this.lowkumamce);
        this.lowkumamce.setBackgroundColor(Color.parseColor("#669d75"));
        ProgressBar progressBar12 = new ProgressBar(this);
        this.jhmnlhffny = progressBar12;
        progressBar12.setLayoutParams(new LinearLayout.LayoutParams(1811, 440));
        this.jhmnlhffny.setPadding(144, 170, 199, 12);
        linearLayout.addView(this.jhmnlhffny);
        this.jhmnlhffny.setBackgroundColor(Color.parseColor("#8db397"));
        EditText editText8 = new EditText(this);
        this.fpgowgosvw = editText8;
        editText8.setLayoutParams(new LinearLayout.LayoutParams(38, 1533));
        this.fpgowgosvw.setPadding(62, 56, 32, 135);
        linearLayout.addView(this.fpgowgosvw);
        this.fpgowgosvw.setBackgroundColor(Color.parseColor("#c35e76"));
        EditText editText9 = new EditText(this);
        this.trzdahqccm = editText9;
        editText9.setLayoutParams(new LinearLayout.LayoutParams(893, 63));
        this.trzdahqccm.setPadding(85, 139, 87, 79);
        linearLayout.addView(this.trzdahqccm);
        this.trzdahqccm.setBackgroundColor(Color.parseColor("#5713ef"));
        FrameLayout frameLayout4 = new FrameLayout(this);
        this.dywwcpcrim = frameLayout4;
        frameLayout4.setLayoutParams(new LinearLayout.LayoutParams(1838, 912));
        this.dywwcpcrim.setPadding(35, 17, 127, 141);
        linearLayout.addView(this.dywwcpcrim);
        this.dywwcpcrim.setBackgroundColor(Color.parseColor("#52c7c0"));
        RelativeLayout relativeLayout7 = new RelativeLayout(this);
        this.bciefrqeos = relativeLayout7;
        relativeLayout7.setLayoutParams(new LinearLayout.LayoutParams(1678, AudioEq.SW_EQ_DATA_LENGTH));
        this.bciefrqeos.setPadding(65, 94, 112, 47);
        linearLayout.addView(this.bciefrqeos);
        this.bciefrqeos.setBackgroundColor(Color.parseColor("#bf3986"));
        ScrollView scrollView5 = new ScrollView(this);
        this.dbhgrqtzif = scrollView5;
        scrollView5.setLayoutParams(new LinearLayout.LayoutParams(1092, 1048));
        this.dbhgrqtzif.setPadding(56, 123, 84, 155);
        linearLayout.addView(this.dbhgrqtzif);
        this.dbhgrqtzif.setBackgroundColor(Color.parseColor("#092a98"));
        TableLayout tableLayout6 = new TableLayout(this);
        this.tlyfhsxbgj = tableLayout6;
        tableLayout6.setLayoutParams(new LinearLayout.LayoutParams(225, TypedValues.AttributesType.TYPE_EASING));
        this.tlyfhsxbgj.setPadding(27, 68, 36, BDLocation.TypeCoarseLocation);
        linearLayout.addView(this.tlyfhsxbgj);
        this.tlyfhsxbgj.setBackgroundColor(Color.parseColor("#02c78c"));
        ListView listView4 = new ListView(this);
        this.plqofgglfn = listView4;
        listView4.setLayoutParams(new LinearLayout.LayoutParams(950, 87));
        this.plqofgglfn.setPadding(140, 106, 183, 168);
        linearLayout.addView(this.plqofgglfn);
        this.plqofgglfn.setBackgroundColor(Color.parseColor("#a8a8a4"));
        TimePicker timePicker8 = new TimePicker(this);
        this.exleypoixr = timePicker8;
        timePicker8.setLayoutParams(new LinearLayout.LayoutParams(266, 920));
        this.exleypoixr.setPadding(117, 159, 47, 113);
        linearLayout.addView(this.exleypoixr);
        this.exleypoixr.setBackgroundColor(Color.parseColor("#5af9fd"));
        ImageView imageView8 = new ImageView(this);
        this.jfchoivyny = imageView8;
        imageView8.setLayoutParams(new LinearLayout.LayoutParams(190, 1009));
        this.jfchoivyny.setPadding(6, 153, 79, 75);
        linearLayout.addView(this.jfchoivyny);
        this.jfchoivyny.setBackgroundColor(Color.parseColor("#1e666c"));
        RadioButton radioButton11 = new RadioButton(this);
        this.yczhcvtdrw = radioButton11;
        radioButton11.setLayoutParams(new LinearLayout.LayoutParams(1544, 296));
        this.yczhcvtdrw.setPadding(44, 54, 29, 19);
        linearLayout.addView(this.yczhcvtdrw);
        this.yczhcvtdrw.setBackgroundColor(Color.parseColor("#fb4059"));
        RelativeLayout relativeLayout8 = new RelativeLayout(this);
        this.bvxgrroyfp = relativeLayout8;
        relativeLayout8.setLayoutParams(new LinearLayout.LayoutParams(1568, 1950));
        this.bvxgrroyfp.setPadding(61, BDLocation.TypeServerError, 48, 158);
        linearLayout.addView(this.bvxgrroyfp);
        this.bvxgrroyfp.setBackgroundColor(Color.parseColor("#915142"));
        LinearLayout linearLayout5 = new LinearLayout(this);
        this.jwfplddlzy = linearLayout5;
        linearLayout5.setLayoutParams(new LinearLayout.LayoutParams(387, 245));
        this.jwfplddlzy.setPadding(94, 128, 190, 81);
        linearLayout.addView(this.jwfplddlzy);
        this.jwfplddlzy.setBackgroundColor(Color.parseColor("#f46a81"));
        GridView gridView11 = new GridView(this);
        this.axcnjkmudo = gridView11;
        gridView11.setLayoutParams(new LinearLayout.LayoutParams(1097, 838));
        this.axcnjkmudo.setPadding(93, 99, 77, 92);
        linearLayout.addView(this.axcnjkmudo);
        this.axcnjkmudo.setBackgroundColor(Color.parseColor("#a7996b"));
        CheckBox checkBox6 = new CheckBox(this);
        this.zrmrjvcqul = checkBox6;
        checkBox6.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.MotionType.TYPE_ANIMATE_RELATIVE_TO, 1495));
        this.zrmrjvcqul.setPadding(25, 133, 4, 95);
        linearLayout.addView(this.zrmrjvcqul);
        this.zrmrjvcqul.setBackgroundColor(Color.parseColor("#66f688"));
        FrameLayout frameLayout5 = new FrameLayout(this);
        this.nxmmtmnmvy = frameLayout5;
        frameLayout5.setLayoutParams(new LinearLayout.LayoutParams(1873, 163));
        this.nxmmtmnmvy.setPadding(83, 33, 22, 60);
        linearLayout.addView(this.nxmmtmnmvy);
        this.nxmmtmnmvy.setBackgroundColor(Color.parseColor("#e61a11"));
        TimePicker timePicker9 = new TimePicker(this);
        this.kabjylczds = timePicker9;
        timePicker9.setLayoutParams(new LinearLayout.LayoutParams(835, 1916));
        this.kabjylczds.setPadding(33, 1, 154, 28);
        linearLayout.addView(this.kabjylczds);
        this.kabjylczds.setBackgroundColor(Color.parseColor("#162b80"));
        ToggleButton toggleButton12 = new ToggleButton(this);
        this.vgwdnvkahc = toggleButton12;
        toggleButton12.setLayoutParams(new LinearLayout.LayoutParams(1608, 899));
        this.vgwdnvkahc.setPadding(190, 43, 2, 141);
        linearLayout.addView(this.vgwdnvkahc);
        this.vgwdnvkahc.setBackgroundColor(Color.parseColor("#91819e"));
        EditText editText10 = new EditText(this);
        this.nidyafkqls = editText10;
        editText10.setLayoutParams(new LinearLayout.LayoutParams(651, AudioEq.SW_EQ_DATA_LENGTH));
        this.nidyafkqls.setPadding(152, 113, 134, 112);
        linearLayout.addView(this.nidyafkqls);
        this.nidyafkqls.setBackgroundColor(Color.parseColor("#c4fe73"));
        ViewFlipper viewFlipper5 = new ViewFlipper(this);
        this.ctwboasaen = viewFlipper5;
        viewFlipper5.setLayoutParams(new LinearLayout.LayoutParams(1643, 405));
        this.ctwboasaen.setPadding(127, 9, 140, 8);
        linearLayout.addView(this.ctwboasaen);
        this.ctwboasaen.setBackgroundColor(Color.parseColor("#91860c"));
        SeekBar seekBar4 = new SeekBar(this);
        this.azickiejtp = seekBar4;
        seekBar4.setLayoutParams(new LinearLayout.LayoutParams(1014, 532));
        this.azickiejtp.setPadding(22, 156, WebSocketProtocol.PAYLOAD_SHORT, 102);
        linearLayout.addView(this.azickiejtp);
        this.azickiejtp.setBackgroundColor(Color.parseColor("#1c82e2"));
        Spinner spinner3 = new Spinner(this);
        this.dkcrgwqsik = spinner3;
        spinner3.setLayoutParams(new LinearLayout.LayoutParams(926, 1192));
        this.dkcrgwqsik.setPadding(41, 51, 89, 122);
        linearLayout.addView(this.dkcrgwqsik);
        this.dkcrgwqsik.setBackgroundColor(Color.parseColor("#511164"));
        RatingBar ratingBar14 = new RatingBar(this);
        this.edooymcevd = ratingBar14;
        ratingBar14.setLayoutParams(new LinearLayout.LayoutParams(383, 680));
        this.edooymcevd.setPadding(90, 43, 173, 140);
        linearLayout.addView(this.edooymcevd);
        this.edooymcevd.setBackgroundColor(Color.parseColor("#428b9c"));
        Switch r27 = new Switch(this);
        this.ldtpgnltcg = r27;
        r27.setLayoutParams(new LinearLayout.LayoutParams(1554, 639));
        this.ldtpgnltcg.setPadding(65, 114, 150, 24);
        linearLayout.addView(this.ldtpgnltcg);
        this.ldtpgnltcg.setBackgroundColor(Color.parseColor("#9a5ce7"));
        Spinner spinner4 = new Spinner(this);
        this.ezyxjxgajj = spinner4;
        spinner4.setLayoutParams(new LinearLayout.LayoutParams(633, 1697));
        this.ezyxjxgajj.setPadding(110, 138, 78, 127);
        linearLayout.addView(this.ezyxjxgajj);
        this.ezyxjxgajj.setBackgroundColor(Color.parseColor("#2fce4f"));
        RelativeLayout relativeLayout9 = new RelativeLayout(this);
        this.inliqhdlou = relativeLayout9;
        relativeLayout9.setLayoutParams(new LinearLayout.LayoutParams(1631, 192));
        this.inliqhdlou.setPadding(197, 43, 100, 10);
        linearLayout.addView(this.inliqhdlou);
        this.inliqhdlou.setBackgroundColor(Color.parseColor("#1f011c"));
        ImageView imageView9 = new ImageView(this);
        this.ebwjybrgyc = imageView9;
        imageView9.setLayoutParams(new LinearLayout.LayoutParams(275, 1956));
        this.ebwjybrgyc.setPadding(94, 46, 38, 8);
        linearLayout.addView(this.ebwjybrgyc);
        this.ebwjybrgyc.setBackgroundColor(Color.parseColor("#d854cd"));
        RelativeLayout relativeLayout10 = new RelativeLayout(this);
        this.vyspyqnfru = relativeLayout10;
        relativeLayout10.setLayoutParams(new LinearLayout.LayoutParams(1993, 1728));
        this.vyspyqnfru.setPadding(38, PictureConfig.CHOOSE_REQUEST, 151, 9);
        linearLayout.addView(this.vyspyqnfru);
        this.vyspyqnfru.setBackgroundColor(Color.parseColor("#25c665"));
        GridView gridView12 = new GridView(this);
        this.wkksjjbfsl = gridView12;
        gridView12.setLayoutParams(new LinearLayout.LayoutParams(1974, 1913));
        this.wkksjjbfsl.setPadding(31, 86, 181, 147);
        linearLayout.addView(this.wkksjjbfsl);
        this.wkksjjbfsl.setBackgroundColor(Color.parseColor("#6eac17"));
        ListView listView5 = new ListView(this);
        this.iczoitlzkh = listView5;
        listView5.setLayoutParams(new LinearLayout.LayoutParams(1262, 249));
        this.iczoitlzkh.setPadding(BDLocation.TypeNetWorkLocation, 30, 1, 193);
        linearLayout.addView(this.iczoitlzkh);
        this.iczoitlzkh.setBackgroundColor(Color.parseColor("#dbec9c"));
        RelativeLayout relativeLayout11 = new RelativeLayout(this);
        this.rkojgzwdfl = relativeLayout11;
        relativeLayout11.setLayoutParams(new LinearLayout.LayoutParams(1492, 666));
        this.rkojgzwdfl.setPadding(66, 170, 76, 123);
        linearLayout.addView(this.rkojgzwdfl);
        this.rkojgzwdfl.setBackgroundColor(Color.parseColor("#afe6aa"));
        TextView textView8 = new TextView(this);
        this.hkomaswuxz = textView8;
        textView8.setLayoutParams(new LinearLayout.LayoutParams(1205, 806));
        this.hkomaswuxz.setPadding(184, 89, 130, 71);
        linearLayout.addView(this.hkomaswuxz);
        this.hkomaswuxz.setBackgroundColor(Color.parseColor("#68f6c9"));
        TimePicker timePicker10 = new TimePicker(this);
        this.hbmajynyfu = timePicker10;
        timePicker10.setLayoutParams(new LinearLayout.LayoutParams(633, 594));
        this.hbmajynyfu.setPadding(73, 71, 30, 143);
        linearLayout.addView(this.hbmajynyfu);
        this.hbmajynyfu.setBackgroundColor(Color.parseColor("#e544c5"));
        EditText editText11 = new EditText(this);
        this.zpdeiotmbe = editText11;
        editText11.setLayoutParams(new LinearLayout.LayoutParams(351, 338));
        this.zpdeiotmbe.setPadding(84, 20, 91, 21);
        linearLayout.addView(this.zpdeiotmbe);
        this.zpdeiotmbe.setBackgroundColor(Color.parseColor("#93acc3"));
        ViewFlipper viewFlipper6 = new ViewFlipper(this);
        this.ozighxeefy = viewFlipper6;
        viewFlipper6.setLayoutParams(new LinearLayout.LayoutParams(1100, 1343));
        this.ozighxeefy.setPadding(104, 170, 42, 49);
        linearLayout.addView(this.ozighxeefy);
        this.ozighxeefy.setBackgroundColor(Color.parseColor("#681278"));
        RatingBar ratingBar15 = new RatingBar(this);
        this.qdsyryohfr = ratingBar15;
        ratingBar15.setLayoutParams(new LinearLayout.LayoutParams(1240, 1693));
        this.qdsyryohfr.setPadding(134, 83, 180, 58);
        linearLayout.addView(this.qdsyryohfr);
        this.qdsyryohfr.setBackgroundColor(Color.parseColor("#6c6dff"));
        GridView gridView13 = new GridView(this);
        this.dhcvlvumuq = gridView13;
        gridView13.setLayoutParams(new LinearLayout.LayoutParams(61, 1169));
        this.dhcvlvumuq.setPadding(180, 153, 46, 106);
        linearLayout.addView(this.dhcvlvumuq);
        this.dhcvlvumuq.setBackgroundColor(Color.parseColor("#14512f"));
        FrameLayout frameLayout6 = new FrameLayout(this);
        this.nnzpboqcqg = frameLayout6;
        frameLayout6.setLayoutParams(new LinearLayout.LayoutParams(1029, 1431));
        this.nnzpboqcqg.setPadding(159, 176, 180, 76);
        linearLayout.addView(this.nnzpboqcqg);
        this.nnzpboqcqg.setBackgroundColor(Color.parseColor("#231d88"));
        Switch r28 = new Switch(this);
        this.fvxsxgyrje = r28;
        r28.setLayoutParams(new LinearLayout.LayoutParams(1063, 1033));
        this.fvxsxgyrje.setPadding(13, 62, 51, 88);
        linearLayout.addView(this.fvxsxgyrje);
        this.fvxsxgyrje.setBackgroundColor(Color.parseColor("#353d3b"));
        DatePicker datePicker9 = new DatePicker(this);
        this.qpvhacobvz = datePicker9;
        datePicker9.setLayoutParams(new LinearLayout.LayoutParams(70, 20));
        this.qpvhacobvz.setPadding(22, 179, 104, 6);
        linearLayout.addView(this.qpvhacobvz);
        this.qpvhacobvz.setBackgroundColor(Color.parseColor("#88c18c"));
        FrameLayout frameLayout7 = new FrameLayout(this);
        this.ndrlzjpihq = frameLayout7;
        frameLayout7.setLayoutParams(new LinearLayout.LayoutParams(1007, 412));
        this.ndrlzjpihq.setPadding(14, 164, 190, 145);
        linearLayout.addView(this.ndrlzjpihq);
        this.ndrlzjpihq.setBackgroundColor(Color.parseColor("#8e6e8d"));
        LinearLayout linearLayout6 = new LinearLayout(this);
        this.vsmadsmook = linearLayout6;
        linearLayout6.setLayoutParams(new LinearLayout.LayoutParams(884, 87));
        this.vsmadsmook.setPadding(177, 138, 120, 2);
        linearLayout.addView(this.vsmadsmook);
        this.vsmadsmook.setBackgroundColor(Color.parseColor("#61de80"));
        ImageView imageView10 = new ImageView(this);
        this.jmvqvtolfy = imageView10;
        imageView10.setLayoutParams(new LinearLayout.LayoutParams(673, 1982));
        this.jmvqvtolfy.setPadding(83, 105, 44, 173);
        linearLayout.addView(this.jmvqvtolfy);
        this.jmvqvtolfy.setBackgroundColor(Color.parseColor("#0adddf"));
        ViewFlipper viewFlipper7 = new ViewFlipper(this);
        this.onvdsqhwre = viewFlipper7;
        viewFlipper7.setLayoutParams(new LinearLayout.LayoutParams(963, 1127));
        this.onvdsqhwre.setPadding(98, 3, 152, 9);
        linearLayout.addView(this.onvdsqhwre);
        this.onvdsqhwre.setBackgroundColor(Color.parseColor("#a70a88"));
        ViewFlipper viewFlipper8 = new ViewFlipper(this);
        this.yltyzufzod = viewFlipper8;
        viewFlipper8.setLayoutParams(new LinearLayout.LayoutParams(936, 1832));
        this.yltyzufzod.setPadding(144, 178, 12, 121);
        linearLayout.addView(this.yltyzufzod);
        this.yltyzufzod.setBackgroundColor(Color.parseColor("#4f4de3"));
        SeekBar seekBar5 = new SeekBar(this);
        this.mcateyvgxx = seekBar5;
        seekBar5.setLayoutParams(new LinearLayout.LayoutParams(0, 269));
        this.mcateyvgxx.setPadding(26, 45, 84, 39);
        linearLayout.addView(this.mcateyvgxx);
        this.mcateyvgxx.setBackgroundColor(Color.parseColor("#d24a96"));
        ProgressBar progressBar13 = new ProgressBar(this);
        this.yuylpijnkt = progressBar13;
        progressBar13.setLayoutParams(new LinearLayout.LayoutParams(1126, 1202));
        this.yuylpijnkt.setPadding(55, 83, 64, 151);
        linearLayout.addView(this.yuylpijnkt);
        this.yuylpijnkt.setBackgroundColor(Color.parseColor("#39b5de"));
        ListView listView6 = new ListView(this);
        this.qktxpuxedn = listView6;
        listView6.setLayoutParams(new LinearLayout.LayoutParams(1074, 276));
        this.qktxpuxedn.setPadding(119, 123, 169, 169);
        linearLayout.addView(this.qktxpuxedn);
        this.qktxpuxedn.setBackgroundColor(Color.parseColor("#10fee9"));
        RelativeLayout relativeLayout12 = new RelativeLayout(this);
        this.jytsokwhng = relativeLayout12;
        relativeLayout12.setLayoutParams(new LinearLayout.LayoutParams(1398, 1034));
        this.jytsokwhng.setPadding(49, 141, 91, 127);
        linearLayout.addView(this.jytsokwhng);
        this.jytsokwhng.setBackgroundColor(Color.parseColor("#57ecf1"));
        RatingBar ratingBar16 = new RatingBar(this);
        this.vnhqhtictr = ratingBar16;
        ratingBar16.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.PositionType.TYPE_PERCENT_Y, 105));
        this.vnhqhtictr.setPadding(48, 130, BDLocation.TypeServerDecryptError, 103);
        linearLayout.addView(this.vnhqhtictr);
        this.vnhqhtictr.setBackgroundColor(Color.parseColor("#95b7ad"));
        TableLayout tableLayout7 = new TableLayout(this);
        this.zamdwapklk = tableLayout7;
        tableLayout7.setLayoutParams(new LinearLayout.LayoutParams(1359, 428));
        this.zamdwapklk.setPadding(19, 62, 154, 26);
        linearLayout.addView(this.zamdwapklk);
        this.zamdwapklk.setBackgroundColor(Color.parseColor("#e57e0e"));
        ListView listView7 = new ListView(this);
        this.roxqelbqar = listView7;
        listView7.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.Custom.TYPE_COLOR, 330));
        this.roxqelbqar.setPadding(118, 198, 15, 146);
        linearLayout.addView(this.roxqelbqar);
        this.roxqelbqar.setBackgroundColor(Color.parseColor("#4099fe"));
        ScrollView scrollView6 = new ScrollView(this);
        this.tqxgmxkxkp = scrollView6;
        scrollView6.setLayoutParams(new LinearLayout.LayoutParams(803, 1417));
        this.tqxgmxkxkp.setPadding(145, 85, 45, 26);
        linearLayout.addView(this.tqxgmxkxkp);
        this.tqxgmxkxkp.setBackgroundColor(Color.parseColor("#4f845e"));
        ImageView imageView11 = new ImageView(this);
        this.cfcjsrxiqd = imageView11;
        imageView11.setLayoutParams(new LinearLayout.LayoutParams(1113, 1191));
        this.cfcjsrxiqd.setPadding(187, BDLocation.TypeServerDecryptError, 117, 23);
        linearLayout.addView(this.cfcjsrxiqd);
        this.cfcjsrxiqd.setBackgroundColor(Color.parseColor("#fd2fb6"));
        RadioButton radioButton12 = new RadioButton(this);
        this.wzcdevnhxr = radioButton12;
        radioButton12.setLayoutParams(new LinearLayout.LayoutParams(298, 17));
        this.wzcdevnhxr.setPadding(124, 100, 158, 196);
        linearLayout.addView(this.wzcdevnhxr);
        this.wzcdevnhxr.setBackgroundColor(Color.parseColor("#2d28a1"));
        FrameLayout frameLayout8 = new FrameLayout(this);
        this.uzsafcprsy = frameLayout8;
        frameLayout8.setLayoutParams(new LinearLayout.LayoutParams(1059, 964));
        this.uzsafcprsy.setPadding(110, 86, 132, 147);
        linearLayout.addView(this.uzsafcprsy);
        this.uzsafcprsy.setBackgroundColor(Color.parseColor("#bc07df"));
        TableLayout tableLayout8 = new TableLayout(this);
        this.erzghhrvmv = tableLayout8;
        tableLayout8.setLayoutParams(new LinearLayout.LayoutParams(CropImage.CROP_IMAGE_ACTIVITY_REQUEST_CODE, 169));
        this.erzghhrvmv.setPadding(190, 13, 199, 151);
        linearLayout.addView(this.erzghhrvmv);
        this.erzghhrvmv.setBackgroundColor(Color.parseColor("#8e9099"));
        ProgressBar progressBar14 = new ProgressBar(this);
        this.jzizzvrxbr = progressBar14;
        progressBar14.setLayoutParams(new LinearLayout.LayoutParams(110, 1573));
        this.jzizzvrxbr.setPadding(60, 102, 99, 69);
        linearLayout.addView(this.jzizzvrxbr);
        this.jzizzvrxbr.setBackgroundColor(Color.parseColor("#1d3283"));
        TimePicker timePicker11 = new TimePicker(this);
        this.pjgipbyjsp = timePicker11;
        timePicker11.setLayoutParams(new LinearLayout.LayoutParams(306, 1766));
        this.pjgipbyjsp.setPadding(195, 54, 143, 51);
        linearLayout.addView(this.pjgipbyjsp);
        this.pjgipbyjsp.setBackgroundColor(Color.parseColor("#fe21b3"));
        TimePicker timePicker12 = new TimePicker(this);
        this.oxmgpogdba = timePicker12;
        timePicker12.setLayoutParams(new LinearLayout.LayoutParams(1501, 1714));
        this.oxmgpogdba.setPadding(94, 114, 68, 0);
        linearLayout.addView(this.oxmgpogdba);
        this.oxmgpogdba.setBackgroundColor(Color.parseColor("#9979b9"));
        Switch r29 = new Switch(this);
        this.afqechshpo = r29;
        r29.setLayoutParams(new LinearLayout.LayoutParams(169, CodeUtils.DEFAULT_REQ_HEIGHT));
        this.afqechshpo.setPadding(145, 134, 52, 51);
        linearLayout.addView(this.afqechshpo);
        this.afqechshpo.setBackgroundColor(Color.parseColor("#e03f9b"));
        DatePicker datePicker10 = new DatePicker(this);
        this.aqakqqfhxb = datePicker10;
        datePicker10.setLayoutParams(new LinearLayout.LayoutParams(1502, 1233));
        this.aqakqqfhxb.setPadding(72, 98, 5, 191);
        linearLayout.addView(this.aqakqqfhxb);
        this.aqakqqfhxb.setBackgroundColor(Color.parseColor("#a30165"));
        ScrollView scrollView7 = new ScrollView(this);
        this.qlmpwrezgs = scrollView7;
        scrollView7.setLayoutParams(new LinearLayout.LayoutParams(930, 1105));
        this.qlmpwrezgs.setPadding(88, 150, 25, 179);
        linearLayout.addView(this.qlmpwrezgs);
        this.qlmpwrezgs.setBackgroundColor(Color.parseColor("#de9350"));
        TextView textView9 = new TextView(this);
        this.chudffthqg = textView9;
        textView9.setLayoutParams(new LinearLayout.LayoutParams(295, 1519));
        this.chudffthqg.setPadding(191, WebSocketProtocol.PAYLOAD_SHORT, 107, 80);
        linearLayout.addView(this.chudffthqg);
        this.chudffthqg.setBackgroundColor(Color.parseColor("#8a3447"));
        Button button7 = new Button(this);
        this.obvzytrqnl = button7;
        button7.setLayoutParams(new LinearLayout.LayoutParams(889, 1700));
        this.obvzytrqnl.setPadding(169, 137, 136, 115);
        linearLayout.addView(this.obvzytrqnl);
        this.obvzytrqnl.setBackgroundColor(Color.parseColor("#3852d2"));
        RelativeLayout relativeLayout13 = new RelativeLayout(this);
        this.igejutdraq = relativeLayout13;
        relativeLayout13.setLayoutParams(new LinearLayout.LayoutParams(1931, 216));
        this.igejutdraq.setPadding(73, 196, 79, 155);
        linearLayout.addView(this.igejutdraq);
        this.igejutdraq.setBackgroundColor(Color.parseColor("#c933c4"));
        CheckBox checkBox7 = new CheckBox(this);
        this.mnfudiedls = checkBox7;
        checkBox7.setLayoutParams(new LinearLayout.LayoutParams(182, 39));
        this.mnfudiedls.setPadding(41, 125, 151, 91);
        linearLayout.addView(this.mnfudiedls);
        this.mnfudiedls.setBackgroundColor(Color.parseColor("#f683fa"));
        LinearLayout linearLayout7 = new LinearLayout(this);
        this.cuxtudmbum = linearLayout7;
        linearLayout7.setLayoutParams(new LinearLayout.LayoutParams(1733, 714));
        this.cuxtudmbum.setPadding(143, 163, 60, 80);
        linearLayout.addView(this.cuxtudmbum);
        this.cuxtudmbum.setBackgroundColor(Color.parseColor("#8ed256"));
        ViewFlipper viewFlipper9 = new ViewFlipper(this);
        this.doygzfadmp = viewFlipper9;
        viewFlipper9.setLayoutParams(new LinearLayout.LayoutParams(1991, 330));
        this.doygzfadmp.setPadding(77, 177, 46, 86);
        linearLayout.addView(this.doygzfadmp);
        this.doygzfadmp.setBackgroundColor(Color.parseColor("#0721ef"));
        ScrollView scrollView8 = new ScrollView(this);
        this.iuvrkgwalt = scrollView8;
        scrollView8.setLayoutParams(new LinearLayout.LayoutParams(522, 1815));
        this.iuvrkgwalt.setPadding(45, 121, 78, 4);
        linearLayout.addView(this.iuvrkgwalt);
        this.iuvrkgwalt.setBackgroundColor(Color.parseColor("#3c9fd8"));
        TableLayout tableLayout9 = new TableLayout(this);
        this.vuyjbdnlts = tableLayout9;
        tableLayout9.setLayoutParams(new LinearLayout.LayoutParams(1864, 1823));
        this.vuyjbdnlts.setPadding(134, 93, 45, 136);
        linearLayout.addView(this.vuyjbdnlts);
        this.vuyjbdnlts.setBackgroundColor(Color.parseColor("#9b9fc4"));
        LinearLayout linearLayout8 = new LinearLayout(this);
        this.kpfycdfiwz = linearLayout8;
        linearLayout8.setLayoutParams(new LinearLayout.LayoutParams(809, 1553));
        this.kpfycdfiwz.setPadding(127, 41, 11, 165);
        linearLayout.addView(this.kpfycdfiwz);
        this.kpfycdfiwz.setBackgroundColor(Color.parseColor("#6546b5"));
        ListView listView8 = new ListView(this);
        this.zqsijnmmkt = listView8;
        listView8.setLayoutParams(new LinearLayout.LayoutParams(1918, 1768));
        this.zqsijnmmkt.setPadding(142, 190, 73, 1);
        linearLayout.addView(this.zqsijnmmkt);
        this.zqsijnmmkt.setBackgroundColor(Color.parseColor("#98b848"));
        LinearLayout linearLayout9 = new LinearLayout(this);
        this.kvhpsjecsp = linearLayout9;
        linearLayout9.setLayoutParams(new LinearLayout.LayoutParams(1485, 1948));
        this.kvhpsjecsp.setPadding(4, 168, 180, BDLocation.TypeServerDecryptError);
        linearLayout.addView(this.kvhpsjecsp);
        this.kvhpsjecsp.setBackgroundColor(Color.parseColor("#800211"));
        ToggleButton toggleButton13 = new ToggleButton(this);
        this.rumsgvnjvw = toggleButton13;
        toggleButton13.setLayoutParams(new LinearLayout.LayoutParams(166, 444));
        this.rumsgvnjvw.setPadding(184, 55, 14, 168);
        linearLayout.addView(this.rumsgvnjvw);
        this.rumsgvnjvw.setBackgroundColor(Color.parseColor("#09e994"));
        TableLayout tableLayout10 = new TableLayout(this);
        this.sofuoaudsh = tableLayout10;
        tableLayout10.setLayoutParams(new LinearLayout.LayoutParams(616, 1872));
        this.sofuoaudsh.setPadding(13, 195, 171, 149);
        linearLayout.addView(this.sofuoaudsh);
        this.sofuoaudsh.setBackgroundColor(Color.parseColor("#392ca4"));
        GridView gridView14 = new GridView(this);
        this.frhzzxsumt = gridView14;
        gridView14.setLayoutParams(new LinearLayout.LayoutParams(489, 99));
        this.frhzzxsumt.setPadding(18, 73, 173, 65);
        linearLayout.addView(this.frhzzxsumt);
        this.frhzzxsumt.setBackgroundColor(Color.parseColor("#ccfc32"));
        RadioButton radioButton13 = new RadioButton(this);
        this.vswhrtlgdt = radioButton13;
        radioButton13.setLayoutParams(new LinearLayout.LayoutParams(137, 389));
        this.vswhrtlgdt.setPadding(37, 179, 132, 58);
        linearLayout.addView(this.vswhrtlgdt);
        this.vswhrtlgdt.setBackgroundColor(Color.parseColor("#494bdf"));
        ListView listView9 = new ListView(this);
        this.slrqaoqvba = listView9;
        listView9.setLayoutParams(new LinearLayout.LayoutParams(73, 1862));
        this.slrqaoqvba.setPadding(28, 93, 183, 152);
        linearLayout.addView(this.slrqaoqvba);
        this.slrqaoqvba.setBackgroundColor(Color.parseColor("#4025bf"));
        Spinner spinner5 = new Spinner(this);
        this.upvvcozsxd = spinner5;
        spinner5.setLayoutParams(new LinearLayout.LayoutParams(933, 1478));
        this.upvvcozsxd.setPadding(49, 130, 31, 46);
        linearLayout.addView(this.upvvcozsxd);
        this.upvvcozsxd.setBackgroundColor(Color.parseColor("#f2a1d6"));
        CheckBox checkBox8 = new CheckBox(this);
        this.ovjlcoslxg = checkBox8;
        checkBox8.setLayoutParams(new LinearLayout.LayoutParams(1699, 624));
        this.ovjlcoslxg.setPadding(120, 77, WebSocketProtocol.PAYLOAD_SHORT, 187);
        linearLayout.addView(this.ovjlcoslxg);
        this.ovjlcoslxg.setBackgroundColor(Color.parseColor("#b57144"));
        RatingBar ratingBar17 = new RatingBar(this);
        this.xuzwvfwzcl = ratingBar17;
        ratingBar17.setLayoutParams(new LinearLayout.LayoutParams(240, 1375));
        this.xuzwvfwzcl.setPadding(192, 60, 20, 121);
        linearLayout.addView(this.xuzwvfwzcl);
        this.xuzwvfwzcl.setBackgroundColor(Color.parseColor("#1e18ec"));
        ListView listView10 = new ListView(this);
        this.bhixwviibw = listView10;
        listView10.setLayoutParams(new LinearLayout.LayoutParams(414, 1649));
        this.bhixwviibw.setPadding(11, 32, 81, 5);
        linearLayout.addView(this.bhixwviibw);
        this.bhixwviibw.setBackgroundColor(Color.parseColor("#c44045"));
        FrameLayout frameLayout9 = new FrameLayout(this);
        this.rxlefyajyb = frameLayout9;
        frameLayout9.setLayoutParams(new LinearLayout.LayoutParams(1668, 591));
        this.rxlefyajyb.setPadding(195, 80, 76, 148);
        linearLayout.addView(this.rxlefyajyb);
        this.rxlefyajyb.setBackgroundColor(Color.parseColor("#413445"));
        DatePicker datePicker11 = new DatePicker(this);
        this.vjqpdlzchc = datePicker11;
        datePicker11.setLayoutParams(new LinearLayout.LayoutParams(218, 1526));
        this.vjqpdlzchc.setPadding(130, 75, 23, 54);
        linearLayout.addView(this.vjqpdlzchc);
        this.vjqpdlzchc.setBackgroundColor(Color.parseColor("#84f96d"));
        EditText editText12 = new EditText(this);
        this.ynalmvfcqf = editText12;
        editText12.setLayoutParams(new LinearLayout.LayoutParams(1015, 1687));
        this.ynalmvfcqf.setPadding(100, 149, 69, 148);
        linearLayout.addView(this.ynalmvfcqf);
        this.ynalmvfcqf.setBackgroundColor(Color.parseColor("#6192a5"));
        Button button8 = new Button(this);
        this.jvorqymyup = button8;
        button8.setLayoutParams(new LinearLayout.LayoutParams(33, 146));
        this.jvorqymyup.setPadding(84, 145, 121, 21);
        linearLayout.addView(this.jvorqymyup);
        this.jvorqymyup.setBackgroundColor(Color.parseColor("#ac5261"));
        SeekBar seekBar6 = new SeekBar(this);
        this.vczqacxwam = seekBar6;
        seekBar6.setLayoutParams(new LinearLayout.LayoutParams(1848, 250));
        this.vczqacxwam.setPadding(185, 174, 156, WebSocketProtocol.PAYLOAD_SHORT);
        linearLayout.addView(this.vczqacxwam);
        this.vczqacxwam.setBackgroundColor(Color.parseColor("#78bc1e"));
        DatePicker datePicker12 = new DatePicker(this);
        this.afwfzxhsri = datePicker12;
        datePicker12.setLayoutParams(new LinearLayout.LayoutParams(919, 1641));
        this.afwfzxhsri.setPadding(61, 29, 131, 47);
        linearLayout.addView(this.afwfzxhsri);
        this.afwfzxhsri.setBackgroundColor(Color.parseColor("#5dd931"));
        TableLayout tableLayout11 = new TableLayout(this);
        this.vtzqdsatwn = tableLayout11;
        tableLayout11.setLayoutParams(new LinearLayout.LayoutParams(32, 1548));
        this.vtzqdsatwn.setPadding(17, 22, 139, 34);
        linearLayout.addView(this.vtzqdsatwn);
        this.vtzqdsatwn.setBackgroundColor(Color.parseColor("#45c2b2"));
        SeekBar seekBar7 = new SeekBar(this);
        this.ddgblbsful = seekBar7;
        seekBar7.setLayoutParams(new LinearLayout.LayoutParams(1596, 1521));
        this.ddgblbsful.setPadding(183, 155, 42, 150);
        linearLayout.addView(this.ddgblbsful);
        this.ddgblbsful.setBackgroundColor(Color.parseColor("#539120"));
        ImageView imageView12 = new ImageView(this);
        this.eurljwgwpw = imageView12;
        imageView12.setLayoutParams(new LinearLayout.LayoutParams(1396, 883));
        this.eurljwgwpw.setPadding(133, 149, 20, 33);
        linearLayout.addView(this.eurljwgwpw);
        this.eurljwgwpw.setBackgroundColor(Color.parseColor("#e63d24"));
        CheckBox checkBox9 = new CheckBox(this);
        this.uuiyhdefwm = checkBox9;
        checkBox9.setLayoutParams(new LinearLayout.LayoutParams(55, 48));
        this.uuiyhdefwm.setPadding(26, 123, 198, 43);
        linearLayout.addView(this.uuiyhdefwm);
        this.uuiyhdefwm.setBackgroundColor(Color.parseColor("#5edc28"));
    }
}
