package com.device.watch.com.device.watch.tmzjvlerof;

import android.app.Activity;
import android.graphics.Color;
import android.os.Bundle;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.CheckBox;
import android.widget.DatePicker;
import android.widget.EditText;
import android.widget.FrameLayout;
import android.widget.GridView;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ListView;
import android.widget.ProgressBar;
import android.widget.RadioButton;
import android.widget.RatingBar;
import android.widget.RelativeLayout;
import android.widget.ScrollView;
import android.widget.SeekBar;
import android.widget.Spinner;
import android.widget.Switch;
import android.widget.TableLayout;
import android.widget.TextView;
import android.widget.TimePicker;
import android.widget.ToggleButton;
import androidx.constraintlayout.core.motion.utils.TypedValues;
import com.baidu.location.BDLocation;
import com.luck.picture.lib.config.PictureConfig;
import com.realsil.sdk.core.bluetooth.connection.le.GattClient;
import okhttp3.internal.ws.WebSocketProtocol;

/* loaded from: classes2.dex */
public class YqzvqnxwreyActivity extends Activity {
    TimePicker batepzjbwp;
    RatingBar bdlnrjzmxm;
    RatingBar bmilxqfffz;
    RadioButton bmvkjmgztp;
    Switch bxhbcldbhg;
    ImageView cpufmuzwka;
    CheckBox ctbpejdkog;
    TableLayout ddtawxqjox;
    Button dnvxbrqrbv;
    EditText dxxpxptyoa;
    RatingBar ejkswiwsst;
    CheckBox ejvinnbbgt;
    ScrollView eyrfsokiaa;
    SeekBar eyrhhkmnad;
    LinearLayout ezlvljlupo;
    RelativeLayout fsljnpjewz;
    RelativeLayout gdrsnkmzta;
    TextView glcwiiddlq;
    CheckBox gphvriltqv;
    TimePicker gpozzbviwn;
    SeekBar hzwkwzxeys;
    TableLayout idpaowshxb;
    FrameLayout ifdnrezmow;
    FrameLayout ighdehxtev;
    RatingBar ilpqswownf;
    ScrollView ilrpbuhiez;
    TimePicker iukhoputdr;
    TableLayout iyislcajem;
    TimePicker jowelqhbia;
    RelativeLayout jvcgwfinpd;
    Button jwvioabwoo;
    RelativeLayout jzakxvssqa;
    LinearLayout kbkljfbdvo;
    ImageView kcvxvwbgnz;
    DatePicker klvkgojxhc;
    EditText kvnfdhonff;
    Spinner kvrbxxzmkn;
    GridView lfzvynzxgu;
    ScrollView lrskhfjdts;
    ProgressBar ltzgpoujhw;
    ProgressBar mblxcpxstg;
    Switch mdhmalyved;
    ListView mkkijwsmro;
    RatingBar mljlopfdys;
    SeekBar mvqrgyqurd;
    CheckBox nmhfogxtol;
    TableLayout npfzitcsgs;
    TextView nzokboevpx;
    TextView ocxffyuijv;
    ToggleButton omevxaaank;
    TableLayout orzukihvai;
    ImageView padfuzqxks;
    ListView pdgxhemdyc;
    LinearLayout qalvtzjsde;
    DatePicker qbdtrgjplk;
    TextView qbsaocouhi;
    DatePicker qekqzzkqqi;
    ToggleButton qgxjrdrxdg;
    EditText qiyclkrrsy;
    GridView rbnxzhhydo;
    Spinner rmxbhjkgcy;
    DatePicker rnpxnpjtgu;
    ToggleButton ryazopvxnm;
    GridView smvrolujfl;
    SeekBar tdozbjkhwr;
    TableLayout tkbgkazfnz;
    GridView trmnmenzqs;
    FrameLayout trughzdixi;
    RadioButton tykqtmcuzb;
    ListView tyrrfupsaj;
    ProgressBar ubcuhmucif;
    TimePicker ubgkrgtllj;
    LinearLayout uhxhmpapjm;
    DatePicker uxzwggguoj;
    DatePicker uzfqzduafz;
    TimePicker vemyuqloao;
    ImageView vkyiqvunar;
    GridView vorfqemjhl;
    RatingBar vuuihxsljj;
    ToggleButton vzbmjpqceh;
    ScrollView wbkxjchjxq;
    DatePicker wsgpheljfi;
    EditText wvgccvowbq;
    Switch xjmcfoshmh;
    EditText xpeqnpawmt;
    FrameLayout ycaubcktjw;
    EditText yfygiwchjl;
    CheckBox yjbnwsultt;
    RelativeLayout yxzoldvbld;
    RatingBar zfqzorxqum;
    ImageView zhwxwydtjs;

    @Override // android.app.Activity
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        LinearLayout linearLayout = new LinearLayout(this);
        setContentView(linearLayout);
        linearLayout.setLayoutParams(new ViewGroup.LayoutParams(-1, -1));
        linearLayout.setOrientation(1);
        linearLayout.setBackgroundColor(Color.parseColor("#fe7c3a"));
        ScrollView scrollView = new ScrollView(this);
        this.eyrfsokiaa = scrollView;
        scrollView.setLayoutParams(new LinearLayout.LayoutParams(803, 54));
        this.eyrfsokiaa.setPadding(77, 140, 171, 106);
        linearLayout.addView(this.eyrfsokiaa);
        this.eyrfsokiaa.setBackgroundColor(Color.parseColor("#c9cbe9"));
        RatingBar ratingBar = new RatingBar(this);
        this.zfqzorxqum = ratingBar;
        ratingBar.setLayoutParams(new LinearLayout.LayoutParams(1469, 1046));
        this.zfqzorxqum.setPadding(107, 110, 0, 117);
        linearLayout.addView(this.zfqzorxqum);
        this.zfqzorxqum.setBackground(new Qgaararikpd());
        FrameLayout frameLayout = new FrameLayout(this);
        this.ycaubcktjw = frameLayout;
        frameLayout.setLayoutParams(new LinearLayout.LayoutParams(244, 4));
        this.ycaubcktjw.setPadding(1, 68, 166, 189);
        linearLayout.addView(this.ycaubcktjw);
        this.ycaubcktjw.setBackgroundColor(Color.parseColor("#0a8993"));
        TextView textView = new TextView(this);
        this.qbsaocouhi = textView;
        textView.setLayoutParams(new LinearLayout.LayoutParams(1792, 526));
        this.qbsaocouhi.setPadding(180, 9, 37, 89);
        linearLayout.addView(this.qbsaocouhi);
        this.qbsaocouhi.setBackgroundColor(Color.parseColor("#ab0586"));
        Spinner spinner = new Spinner(this);
        this.kvrbxxzmkn = spinner;
        spinner.setLayoutParams(new LinearLayout.LayoutParams(1494, 482));
        this.kvrbxxzmkn.setPadding(38, 141, 136, 124);
        linearLayout.addView(this.kvrbxxzmkn);
        this.kvrbxxzmkn.setBackgroundColor(Color.parseColor("#f84688"));
        ProgressBar progressBar = new ProgressBar(this);
        this.ltzgpoujhw = progressBar;
        progressBar.setLayoutParams(new LinearLayout.LayoutParams(182, TypedValues.Custom.TYPE_DIMENSION));
        this.ltzgpoujhw.setPadding(177, 102, 99, 66);
        linearLayout.addView(this.ltzgpoujhw);
        this.ltzgpoujhw.setBackgroundColor(Color.parseColor("#50b029"));
        LinearLayout linearLayout2 = new LinearLayout(this);
        this.uhxhmpapjm = linearLayout2;
        linearLayout2.setLayoutParams(new LinearLayout.LayoutParams(916, 1103));
        this.uhxhmpapjm.setPadding(146, PictureConfig.CHOOSE_REQUEST, 151, 136);
        linearLayout.addView(this.uhxhmpapjm);
        this.uhxhmpapjm.setBackgroundColor(Color.parseColor("#80318b"));
        EditText editText = new EditText(this);
        this.qiyclkrrsy = editText;
        editText.setLayoutParams(new LinearLayout.LayoutParams(1956, 359));
        this.qiyclkrrsy.setPadding(67, 11, 98, 14);
        linearLayout.addView(this.qiyclkrrsy);
        this.qiyclkrrsy.setBackgroundColor(Color.parseColor("#c4343c"));
        DatePicker datePicker = new DatePicker(this);
        this.qekqzzkqqi = datePicker;
        datePicker.setLayoutParams(new LinearLayout.LayoutParams(1872, 787));
        this.qekqzzkqqi.setPadding(37, 16, 18, 17);
        linearLayout.addView(this.qekqzzkqqi);
        this.qekqzzkqqi.setBackgroundColor(Color.parseColor("#cce29a"));
        DatePicker datePicker2 = new DatePicker(this);
        this.uzfqzduafz = datePicker2;
        datePicker2.setLayoutParams(new LinearLayout.LayoutParams(584, 1942));
        this.uzfqzduafz.setPadding(34, 154, 65, 120);
        linearLayout.addView(this.uzfqzduafz);
        this.uzfqzduafz.setBackgroundColor(Color.parseColor("#2c3c36"));
        SeekBar seekBar = new SeekBar(this);
        this.mvqrgyqurd = seekBar;
        seekBar.setLayoutParams(new LinearLayout.LayoutParams(1649, 1088));
        this.mvqrgyqurd.setPadding(0, 112, 99, 153);
        linearLayout.addView(this.mvqrgyqurd);
        this.mvqrgyqurd.setBackgroundColor(Color.parseColor("#c04e87"));
        EditText editText2 = new EditText(this);
        this.xpeqnpawmt = editText2;
        editText2.setLayoutParams(new LinearLayout.LayoutParams(897, 1581));
        this.xpeqnpawmt.setPadding(113, 122, 59, 56);
        linearLayout.addView(this.xpeqnpawmt);
        this.xpeqnpawmt.setBackgroundColor(Color.parseColor("#9ad281"));
        RelativeLayout relativeLayout = new RelativeLayout(this);
        this.jvcgwfinpd = relativeLayout;
        relativeLayout.setLayoutParams(new LinearLayout.LayoutParams(1887, 1731));
        this.jvcgwfinpd.setPadding(79, 198, 4, 123);
        linearLayout.addView(this.jvcgwfinpd);
        this.jvcgwfinpd.setBackgroundColor(Color.parseColor("#53e1e0"));
        ScrollView scrollView2 = new ScrollView(this);
        this.ilrpbuhiez = scrollView2;
        scrollView2.setLayoutParams(new LinearLayout.LayoutParams(368, 734));
        this.ilrpbuhiez.setPadding(196, 177, 156, 5);
        linearLayout.addView(this.ilrpbuhiez);
        this.ilrpbuhiez.setBackgroundColor(Color.parseColor("#49eeb4"));
        EditText editText3 = new EditText(this);
        this.wvgccvowbq = editText3;
        editText3.setLayoutParams(new LinearLayout.LayoutParams(1764, 498));
        this.wvgccvowbq.setPadding(23, 54, 116, 93);
        linearLayout.addView(this.wvgccvowbq);
        this.wvgccvowbq.setBackgroundColor(Color.parseColor("#d542be"));
        ListView listView = new ListView(this);
        this.tyrrfupsaj = listView;
        listView.setLayoutParams(new LinearLayout.LayoutParams(871, 245));
        this.tyrrfupsaj.setPadding(91, 143, 163, 138);
        linearLayout.addView(this.tyrrfupsaj);
        this.tyrrfupsaj.setBackgroundColor(Color.parseColor("#3ee10d"));
        RelativeLayout relativeLayout2 = new RelativeLayout(this);
        this.fsljnpjewz = relativeLayout2;
        relativeLayout2.setLayoutParams(new LinearLayout.LayoutParams(1388, 1774));
        this.fsljnpjewz.setPadding(105, 62, 176, 117);
        linearLayout.addView(this.fsljnpjewz);
        this.fsljnpjewz.setBackgroundColor(Color.parseColor("#ffaf58"));
        CheckBox checkBox = new CheckBox(this);
        this.gphvriltqv = checkBox;
        checkBox.setLayoutParams(new LinearLayout.LayoutParams(1789, 310));
        this.gphvriltqv.setPadding(5, 32, 135, 99);
        linearLayout.addView(this.gphvriltqv);
        this.gphvriltqv.setBackgroundColor(Color.parseColor("#de51fe"));
        TableLayout tableLayout = new TableLayout(this);
        this.tkbgkazfnz = tableLayout;
        tableLayout.setLayoutParams(new LinearLayout.LayoutParams(726, 1138));
        this.tkbgkazfnz.setPadding(109, 55, 124, 142);
        linearLayout.addView(this.tkbgkazfnz);
        this.tkbgkazfnz.setBackgroundColor(Color.parseColor("#bf8451"));
        TableLayout tableLayout2 = new TableLayout(this);
        this.orzukihvai = tableLayout2;
        tableLayout2.setLayoutParams(new LinearLayout.LayoutParams(1560, 1586));
        this.orzukihvai.setPadding(61, 17, 35, 119);
        linearLayout.addView(this.orzukihvai);
        this.orzukihvai.setBackgroundColor(Color.parseColor("#277e57"));
        TimePicker timePicker = new TimePicker(this);
        this.batepzjbwp = timePicker;
        timePicker.setLayoutParams(new LinearLayout.LayoutParams(1042, 769));
        this.batepzjbwp.setPadding(0, 9, 80, 131);
        linearLayout.addView(this.batepzjbwp);
        this.batepzjbwp.setBackgroundColor(Color.parseColor("#5325ce"));
        TimePicker timePicker2 = new TimePicker(this);
        this.vemyuqloao = timePicker2;
        timePicker2.setLayoutParams(new LinearLayout.LayoutParams(1026, 497));
        this.vemyuqloao.setPadding(17, 105, 187, 159);
        linearLayout.addView(this.vemyuqloao);
        this.vemyuqloao.setBackgroundColor(Color.parseColor("#0f784b"));
        Switch r2 = new Switch(this);
        this.mdhmalyved = r2;
        r2.setLayoutParams(new LinearLayout.LayoutParams(1506, 1562));
        this.mdhmalyved.setPadding(120, 153, 108, 17);
        linearLayout.addView(this.mdhmalyved);
        this.mdhmalyved.setBackgroundColor(Color.parseColor("#d80bb9"));
        SeekBar seekBar2 = new SeekBar(this);
        this.tdozbjkhwr = seekBar2;
        seekBar2.setLayoutParams(new LinearLayout.LayoutParams(870, 1383));
        this.tdozbjkhwr.setPadding(15, 128, 60, 92);
        linearLayout.addView(this.tdozbjkhwr);
        this.tdozbjkhwr.setBackgroundColor(Color.parseColor("#5ff5a6"));
        FrameLayout frameLayout2 = new FrameLayout(this);
        this.ighdehxtev = frameLayout2;
        frameLayout2.setLayoutParams(new LinearLayout.LayoutParams(74, 1478));
        this.ighdehxtev.setPadding(163, 117, 197, 7);
        linearLayout.addView(this.ighdehxtev);
        this.ighdehxtev.setBackgroundColor(Color.parseColor("#bcf0d6"));
        ImageView imageView = new ImageView(this);
        this.cpufmuzwka = imageView;
        imageView.setLayoutParams(new LinearLayout.LayoutParams(1441, 1362));
        this.cpufmuzwka.setPadding(31, 185, 9, 75);
        linearLayout.addView(this.cpufmuzwka);
        this.cpufmuzwka.setBackgroundColor(Color.parseColor("#935c69"));
        Spinner spinner2 = new Spinner(this);
        this.rmxbhjkgcy = spinner2;
        spinner2.setLayoutParams(new LinearLayout.LayoutParams(992, 598));
        this.rmxbhjkgcy.setPadding(156, 52, 61, 112);
        linearLayout.addView(this.rmxbhjkgcy);
        this.rmxbhjkgcy.setBackgroundColor(Color.parseColor("#03d7d7"));
        ToggleButton toggleButton = new ToggleButton(this);
        this.omevxaaank = toggleButton;
        toggleButton.setLayoutParams(new LinearLayout.LayoutParams(1121, 809));
        this.omevxaaank.setPadding(165, 90, 153, 116);
        linearLayout.addView(this.omevxaaank);
        this.omevxaaank.setBackgroundColor(Color.parseColor("#9a9bc3"));
        LinearLayout linearLayout3 = new LinearLayout(this);
        this.qalvtzjsde = linearLayout3;
        linearLayout3.setLayoutParams(new LinearLayout.LayoutParams(1100, 72));
        this.qalvtzjsde.setPadding(38, BDLocation.TypeServerDecryptError, BDLocation.TypeCoarseLocation, 31);
        linearLayout.addView(this.qalvtzjsde);
        this.qalvtzjsde.setBackgroundColor(Color.parseColor("#7a11d6"));
        GridView gridView = new GridView(this);
        this.rbnxzhhydo = gridView;
        gridView.setLayoutParams(new LinearLayout.LayoutParams(682, 685));
        this.rbnxzhhydo.setPadding(36, 154, 50, 165);
        linearLayout.addView(this.rbnxzhhydo);
        this.rbnxzhhydo.setBackgroundColor(Color.parseColor("#ffc270"));
        RatingBar ratingBar2 = new RatingBar(this);
        this.vuuihxsljj = ratingBar2;
        ratingBar2.setLayoutParams(new LinearLayout.LayoutParams(554, 658));
        this.vuuihxsljj.setPadding(88, 193, 26, 144);
        linearLayout.addView(this.vuuihxsljj);
        this.vuuihxsljj.setBackgroundColor(Color.parseColor("#72ab03"));
        DatePicker datePicker3 = new DatePicker(this);
        this.qbdtrgjplk = datePicker3;
        datePicker3.setLayoutParams(new LinearLayout.LayoutParams(812, 202));
        this.qbdtrgjplk.setPadding(157, 177, 66, 169);
        linearLayout.addView(this.qbdtrgjplk);
        this.qbdtrgjplk.setBackgroundColor(Color.parseColor("#9ffdaa"));
        LinearLayout linearLayout4 = new LinearLayout(this);
        this.kbkljfbdvo = linearLayout4;
        linearLayout4.setLayoutParams(new LinearLayout.LayoutParams(132, 965));
        this.kbkljfbdvo.setPadding(112, 135, 19, 100);
        linearLayout.addView(this.kbkljfbdvo);
        this.kbkljfbdvo.setBackgroundColor(Color.parseColor("#b118e8"));
        RatingBar ratingBar3 = new RatingBar(this);
        this.ejkswiwsst = ratingBar3;
        ratingBar3.setLayoutParams(new LinearLayout.LayoutParams(1151, 1941));
        this.ejkswiwsst.setPadding(78, 74, 49, 134);
        linearLayout.addView(this.ejkswiwsst);
        this.ejkswiwsst.setBackgroundColor(Color.parseColor("#260431"));
        ListView listView2 = new ListView(this);
        this.mkkijwsmro = listView2;
        listView2.setLayoutParams(new LinearLayout.LayoutParams(1466, 746));
        this.mkkijwsmro.setPadding(32, 21, 156, 156);
        linearLayout.addView(this.mkkijwsmro);
        this.mkkijwsmro.setBackgroundColor(Color.parseColor("#863ab1"));
        ToggleButton toggleButton2 = new ToggleButton(this);
        this.ryazopvxnm = toggleButton2;
        toggleButton2.setLayoutParams(new LinearLayout.LayoutParams(648, 574));
        this.ryazopvxnm.setPadding(171, 178, 18, 104);
        linearLayout.addView(this.ryazopvxnm);
        this.ryazopvxnm.setBackgroundColor(Color.parseColor("#bb6571"));
        RatingBar ratingBar4 = new RatingBar(this);
        this.bdlnrjzmxm = ratingBar4;
        ratingBar4.setLayoutParams(new LinearLayout.LayoutParams(1194, 1062));
        this.bdlnrjzmxm.setPadding(69, 69, 144, 75);
        linearLayout.addView(this.bdlnrjzmxm);
        this.bdlnrjzmxm.setBackgroundColor(Color.parseColor("#bc4ec8"));
        Button button = new Button(this);
        this.jwvioabwoo = button;
        button.setLayoutParams(new LinearLayout.LayoutParams(354, 990));
        this.jwvioabwoo.setPadding(98, 153, 127, 26);
        linearLayout.addView(this.jwvioabwoo);
        this.jwvioabwoo.setBackgroundColor(Color.parseColor("#c924fa"));
        TimePicker timePicker3 = new TimePicker(this);
        this.iukhoputdr = timePicker3;
        timePicker3.setLayoutParams(new LinearLayout.LayoutParams(1849, 1784));
        this.iukhoputdr.setPadding(19, 113, 60, 102);
        linearLayout.addView(this.iukhoputdr);
        this.iukhoputdr.setBackgroundColor(Color.parseColor("#313ff4"));
        RatingBar ratingBar5 = new RatingBar(this);
        this.bmilxqfffz = ratingBar5;
        ratingBar5.setLayoutParams(new LinearLayout.LayoutParams(1751, 1384));
        this.bmilxqfffz.setPadding(111, 46, 129, 85);
        linearLayout.addView(this.bmilxqfffz);
        this.bmilxqfffz.setBackgroundColor(Color.parseColor("#8b9633"));
        ImageView imageView2 = new ImageView(this);
        this.zhwxwydtjs = imageView2;
        imageView2.setLayoutParams(new LinearLayout.LayoutParams(56, 983));
        this.zhwxwydtjs.setPadding(131, 34, 55, 182);
        linearLayout.addView(this.zhwxwydtjs);
        this.zhwxwydtjs.setBackgroundColor(Color.parseColor("#24186b"));
        DatePicker datePicker4 = new DatePicker(this);
        this.klvkgojxhc = datePicker4;
        datePicker4.setLayoutParams(new LinearLayout.LayoutParams(356, 363));
        this.klvkgojxhc.setPadding(109, 198, 101, 133);
        linearLayout.addView(this.klvkgojxhc);
        this.klvkgojxhc.setBackgroundColor(Color.parseColor("#c10f4a"));
        CheckBox checkBox2 = new CheckBox(this);
        this.nmhfogxtol = checkBox2;
        checkBox2.setLayoutParams(new LinearLayout.LayoutParams(624, 952));
        this.nmhfogxtol.setPadding(86, 133, 195, 156);
        linearLayout.addView(this.nmhfogxtol);
        this.nmhfogxtol.setBackgroundColor(Color.parseColor("#7c02ff"));
        ImageView imageView3 = new ImageView(this);
        this.vkyiqvunar = imageView3;
        imageView3.setLayoutParams(new LinearLayout.LayoutParams(921, 749));
        this.vkyiqvunar.setPadding(109, 156, 96, BDLocation.TypeServerDecryptError);
        linearLayout.addView(this.vkyiqvunar);
        this.vkyiqvunar.setBackgroundColor(Color.parseColor("#498fae"));
        RadioButton radioButton = new RadioButton(this);
        this.bmvkjmgztp = radioButton;
        radioButton.setLayoutParams(new LinearLayout.LayoutParams(824, 517));
        this.bmvkjmgztp.setPadding(56, 101, 107, 155);
        linearLayout.addView(this.bmvkjmgztp);
        this.bmvkjmgztp.setBackgroundColor(Color.parseColor("#591b1b"));
        ScrollView scrollView3 = new ScrollView(this);
        this.wbkxjchjxq = scrollView3;
        scrollView3.setLayoutParams(new LinearLayout.LayoutParams(935, 1984));
        this.wbkxjchjxq.setPadding(197, 105, 158, 35);
        linearLayout.addView(this.wbkxjchjxq);
        this.wbkxjchjxq.setBackgroundColor(Color.parseColor("#d5646e"));
        GridView gridView2 = new GridView(this);
        this.smvrolujfl = gridView2;
        gridView2.setLayoutParams(new LinearLayout.LayoutParams(1673, 1477));
        this.smvrolujfl.setPadding(110, 7, 100, 184);
        linearLayout.addView(this.smvrolujfl);
        this.smvrolujfl.setBackgroundColor(Color.parseColor("#5ed810"));
        Switch r22 = new Switch(this);
        this.xjmcfoshmh = r22;
        r22.setLayoutParams(new LinearLayout.LayoutParams(1153, 1151));
        this.xjmcfoshmh.setPadding(187, 116, 123, 187);
        linearLayout.addView(this.xjmcfoshmh);
        this.xjmcfoshmh.setBackgroundColor(Color.parseColor("#ecba35"));
        TimePicker timePicker4 = new TimePicker(this);
        this.jowelqhbia = timePicker4;
        timePicker4.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.CycleType.TYPE_VISIBILITY, 954));
        this.jowelqhbia.setPadding(25, 184, 101, 11);
        linearLayout.addView(this.jowelqhbia);
        this.jowelqhbia.setBackgroundColor(Color.parseColor("#0d6ab5"));
        EditText editText4 = new EditText(this);
        this.yfygiwchjl = editText4;
        editText4.setLayoutParams(new LinearLayout.LayoutParams(652, 224));
        this.yfygiwchjl.setPadding(47, 73, 41, 63);
        linearLayout.addView(this.yfygiwchjl);
        this.yfygiwchjl.setBackgroundColor(Color.parseColor("#4dc4b8"));
        RatingBar ratingBar6 = new RatingBar(this);
        this.mljlopfdys = ratingBar6;
        ratingBar6.setLayoutParams(new LinearLayout.LayoutParams(910, 28));
        this.mljlopfdys.setPadding(153, 159, 119, 94);
        linearLayout.addView(this.mljlopfdys);
        this.mljlopfdys.setBackgroundColor(Color.parseColor("#f89f13"));
        DatePicker datePicker5 = new DatePicker(this);
        this.wsgpheljfi = datePicker5;
        datePicker5.setLayoutParams(new LinearLayout.LayoutParams(687, 1826));
        this.wsgpheljfi.setPadding(134, 117, 121, PictureConfig.CHOOSE_REQUEST);
        linearLayout.addView(this.wsgpheljfi);
        this.wsgpheljfi.setBackgroundColor(Color.parseColor("#82cfb4"));
        ScrollView scrollView4 = new ScrollView(this);
        this.lrskhfjdts = scrollView4;
        scrollView4.setLayoutParams(new LinearLayout.LayoutParams(1936, 1873));
        this.lrskhfjdts.setPadding(148, 88, 102, 19);
        linearLayout.addView(this.lrskhfjdts);
        this.lrskhfjdts.setBackgroundColor(Color.parseColor("#39a86b"));
        CheckBox checkBox3 = new CheckBox(this);
        this.yjbnwsultt = checkBox3;
        checkBox3.setLayoutParams(new LinearLayout.LayoutParams(372, 655));
        this.yjbnwsultt.setPadding(178, 103, 145, 100);
        linearLayout.addView(this.yjbnwsultt);
        this.yjbnwsultt.setBackgroundColor(Color.parseColor("#adb4c2"));
        GridView gridView3 = new GridView(this);
        this.vorfqemjhl = gridView3;
        gridView3.setLayoutParams(new LinearLayout.LayoutParams(713, 456));
        this.vorfqemjhl.setPadding(101, 182, 87, 145);
        linearLayout.addView(this.vorfqemjhl);
        this.vorfqemjhl.setBackgroundColor(Color.parseColor("#c4895c"));
        EditText editText5 = new EditText(this);
        this.kvnfdhonff = editText5;
        editText5.setLayoutParams(new LinearLayout.LayoutParams(1446, 1050));
        this.kvnfdhonff.setPadding(147, 175, 174, 56);
        linearLayout.addView(this.kvnfdhonff);
        this.kvnfdhonff.setBackgroundColor(Color.parseColor("#867458"));
        LinearLayout linearLayout5 = new LinearLayout(this);
        this.ezlvljlupo = linearLayout5;
        linearLayout5.setLayoutParams(new LinearLayout.LayoutParams(892, 984));
        this.ezlvljlupo.setPadding(21, 30, 145, 30);
        linearLayout.addView(this.ezlvljlupo);
        this.ezlvljlupo.setBackgroundColor(Color.parseColor("#ca58c9"));
        SeekBar seekBar3 = new SeekBar(this);
        this.hzwkwzxeys = seekBar3;
        seekBar3.setLayoutParams(new LinearLayout.LayoutParams(1154, 801));
        this.hzwkwzxeys.setPadding(194, 32, BDLocation.TypeCoarseLocation, 78);
        linearLayout.addView(this.hzwkwzxeys);
        this.hzwkwzxeys.setBackgroundColor(Color.parseColor("#e16d71"));
        FrameLayout frameLayout3 = new FrameLayout(this);
        this.trughzdixi = frameLayout3;
        frameLayout3.setLayoutParams(new LinearLayout.LayoutParams(1057, 1508));
        this.trughzdixi.setPadding(110, 193, 124, 132);
        linearLayout.addView(this.trughzdixi);
        this.trughzdixi.setBackgroundColor(Color.parseColor("#ca3b9a"));
        TimePicker timePicker5 = new TimePicker(this);
        this.ubgkrgtllj = timePicker5;
        timePicker5.setLayoutParams(new LinearLayout.LayoutParams(1031, 1802));
        this.ubgkrgtllj.setPadding(17, 136, 129, 75);
        linearLayout.addView(this.ubgkrgtllj);
        this.ubgkrgtllj.setBackgroundColor(Color.parseColor("#f07d81"));
        Button button2 = new Button(this);
        this.dnvxbrqrbv = button2;
        button2.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.TransitionType.TYPE_AUTO_TRANSITION, 1560));
        this.dnvxbrqrbv.setPadding(108, 57, 149, 175);
        linearLayout.addView(this.dnvxbrqrbv);
        this.dnvxbrqrbv.setBackgroundColor(Color.parseColor("#46eb3b"));
        ListView listView3 = new ListView(this);
        this.pdgxhemdyc = listView3;
        listView3.setLayoutParams(new LinearLayout.LayoutParams(871, 1976));
        this.pdgxhemdyc.setPadding(141, 54, WebSocketProtocol.PAYLOAD_SHORT, 32);
        linearLayout.addView(this.pdgxhemdyc);
        this.pdgxhemdyc.setBackgroundColor(Color.parseColor("#8dcf98"));
        TableLayout tableLayout3 = new TableLayout(this);
        this.ddtawxqjox = tableLayout3;
        tableLayout3.setLayoutParams(new LinearLayout.LayoutParams(1170, 1899));
        this.ddtawxqjox.setPadding(131, 41, 113, 44);
        linearLayout.addView(this.ddtawxqjox);
        this.ddtawxqjox.setBackgroundColor(Color.parseColor("#110f9b"));
        TextView textView2 = new TextView(this);
        this.glcwiiddlq = textView2;
        textView2.setLayoutParams(new LinearLayout.LayoutParams(340, 805));
        this.glcwiiddlq.setPadding(101, 1, 29, 0);
        linearLayout.addView(this.glcwiiddlq);
        this.glcwiiddlq.setBackgroundColor(Color.parseColor("#d9c5e9"));
        GridView gridView4 = new GridView(this);
        this.trmnmenzqs = gridView4;
        gridView4.setLayoutParams(new LinearLayout.LayoutParams(532, 269));
        this.trmnmenzqs.setPadding(76, 136, 110, 67);
        linearLayout.addView(this.trmnmenzqs);
        this.trmnmenzqs.setBackgroundColor(Color.parseColor("#c90561"));
        ProgressBar progressBar2 = new ProgressBar(this);
        this.ubcuhmucif = progressBar2;
        progressBar2.setLayoutParams(new LinearLayout.LayoutParams(1892, 1032));
        this.ubcuhmucif.setPadding(137, 134, 117, 143);
        linearLayout.addView(this.ubcuhmucif);
        this.ubcuhmucif.setBackgroundColor(Color.parseColor("#7518d6"));
        DatePicker datePicker6 = new DatePicker(this);
        this.uxzwggguoj = datePicker6;
        datePicker6.setLayoutParams(new LinearLayout.LayoutParams(260, 1369));
        this.uxzwggguoj.setPadding(1, 85, 142, 100);
        linearLayout.addView(this.uxzwggguoj);
        this.uxzwggguoj.setBackgroundColor(Color.parseColor("#8b5d27"));
        CheckBox checkBox4 = new CheckBox(this);
        this.ejvinnbbgt = checkBox4;
        checkBox4.setLayoutParams(new LinearLayout.LayoutParams(365, 352));
        this.ejvinnbbgt.setPadding(180, 26, 194, 99);
        linearLayout.addView(this.ejvinnbbgt);
        this.ejvinnbbgt.setBackgroundColor(Color.parseColor("#271311"));
        RatingBar ratingBar7 = new RatingBar(this);
        this.ilpqswownf = ratingBar7;
        ratingBar7.setLayoutParams(new LinearLayout.LayoutParams(355, 820));
        this.ilpqswownf.setPadding(4, 11, 36, 76);
        linearLayout.addView(this.ilpqswownf);
        this.ilpqswownf.setBackgroundColor(Color.parseColor("#99c7d1"));
        SeekBar seekBar4 = new SeekBar(this);
        this.eyrhhkmnad = seekBar4;
        seekBar4.setLayoutParams(new LinearLayout.LayoutParams(490, 917));
        this.eyrhhkmnad.setPadding(51, 18, 48, 44);
        linearLayout.addView(this.eyrhhkmnad);
        this.eyrhhkmnad.setBackgroundColor(Color.parseColor("#3df18a"));
        ImageView imageView4 = new ImageView(this);
        this.padfuzqxks = imageView4;
        imageView4.setLayoutParams(new LinearLayout.LayoutParams(850, 1163));
        this.padfuzqxks.setPadding(149, 165, 109, 112);
        linearLayout.addView(this.padfuzqxks);
        this.padfuzqxks.setBackgroundColor(Color.parseColor("#194069"));
        RelativeLayout relativeLayout3 = new RelativeLayout(this);
        this.jzakxvssqa = relativeLayout3;
        relativeLayout3.setLayoutParams(new LinearLayout.LayoutParams(741, 381));
        this.jzakxvssqa.setPadding(156, 97, 76, 14);
        linearLayout.addView(this.jzakxvssqa);
        this.jzakxvssqa.setBackgroundColor(Color.parseColor("#7cf907"));
        ProgressBar progressBar3 = new ProgressBar(this);
        this.mblxcpxstg = progressBar3;
        progressBar3.setLayoutParams(new LinearLayout.LayoutParams(581, 39));
        this.mblxcpxstg.setPadding(89, 2, 137, 190);
        linearLayout.addView(this.mblxcpxstg);
        this.mblxcpxstg.setBackgroundColor(Color.parseColor("#ab5e79"));
        ToggleButton toggleButton3 = new ToggleButton(this);
        this.qgxjrdrxdg = toggleButton3;
        toggleButton3.setLayoutParams(new LinearLayout.LayoutParams(1052, 1875));
        this.qgxjrdrxdg.setPadding(192, 192, 39, 109);
        linearLayout.addView(this.qgxjrdrxdg);
        this.qgxjrdrxdg.setBackgroundColor(Color.parseColor("#3c51fc"));
        RelativeLayout relativeLayout4 = new RelativeLayout(this);
        this.yxzoldvbld = relativeLayout4;
        relativeLayout4.setLayoutParams(new LinearLayout.LayoutParams(404, 394));
        this.yxzoldvbld.setPadding(52, 1, 0, 33);
        linearLayout.addView(this.yxzoldvbld);
        this.yxzoldvbld.setBackgroundColor(Color.parseColor("#4a113e"));
        FrameLayout frameLayout4 = new FrameLayout(this);
        this.ifdnrezmow = frameLayout4;
        frameLayout4.setLayoutParams(new LinearLayout.LayoutParams(125, 1568));
        this.ifdnrezmow.setPadding(42, 86, 10, 175);
        linearLayout.addView(this.ifdnrezmow);
        this.ifdnrezmow.setBackgroundColor(Color.parseColor("#800d6d"));
        TimePicker timePicker6 = new TimePicker(this);
        this.gpozzbviwn = timePicker6;
        timePicker6.setLayoutParams(new LinearLayout.LayoutParams(645, 337));
        this.gpozzbviwn.setPadding(137, 4, 175, 149);
        linearLayout.addView(this.gpozzbviwn);
        this.gpozzbviwn.setBackgroundColor(Color.parseColor("#56c8b0"));
        Switch r23 = new Switch(this);
        this.bxhbcldbhg = r23;
        r23.setLayoutParams(new LinearLayout.LayoutParams(1466, 1668));
        this.bxhbcldbhg.setPadding(62, 144, 107, 52);
        linearLayout.addView(this.bxhbcldbhg);
        this.bxhbcldbhg.setBackgroundColor(Color.parseColor("#00e162"));
        ImageView imageView5 = new ImageView(this);
        this.kcvxvwbgnz = imageView5;
        imageView5.setLayoutParams(new LinearLayout.LayoutParams(468, 1555));
        this.kcvxvwbgnz.setPadding(142, 87, 49, 94);
        linearLayout.addView(this.kcvxvwbgnz);
        this.kcvxvwbgnz.setBackgroundColor(Color.parseColor("#92d93e"));
        GridView gridView5 = new GridView(this);
        this.lfzvynzxgu = gridView5;
        gridView5.setLayoutParams(new LinearLayout.LayoutParams(470, 1212));
        this.lfzvynzxgu.setPadding(83, 72, 143, 31);
        linearLayout.addView(this.lfzvynzxgu);
        this.lfzvynzxgu.setBackgroundColor(Color.parseColor("#b40b4d"));
        DatePicker datePicker7 = new DatePicker(this);
        this.rnpxnpjtgu = datePicker7;
        datePicker7.setLayoutParams(new LinearLayout.LayoutParams(GattClient.STATE_READ_PROTOCOL_TYPE, 416));
        this.rnpxnpjtgu.setPadding(81, 56, 62, 107);
        linearLayout.addView(this.rnpxnpjtgu);
        this.rnpxnpjtgu.setBackgroundColor(Color.parseColor("#3820ea"));
        TextView textView3 = new TextView(this);
        this.ocxffyuijv = textView3;
        textView3.setLayoutParams(new LinearLayout.LayoutParams(727, 349));
        this.ocxffyuijv.setPadding(146, 137, 47, 109);
        linearLayout.addView(this.ocxffyuijv);
        this.ocxffyuijv.setBackgroundColor(Color.parseColor("#9a88e9"));
        TableLayout tableLayout4 = new TableLayout(this);
        this.idpaowshxb = tableLayout4;
        tableLayout4.setLayoutParams(new LinearLayout.LayoutParams(603, 737));
        this.idpaowshxb.setPadding(150, 183, 184, 128);
        linearLayout.addView(this.idpaowshxb);
        this.idpaowshxb.setBackgroundColor(Color.parseColor("#ef6a77"));
        CheckBox checkBox5 = new CheckBox(this);
        this.ctbpejdkog = checkBox5;
        checkBox5.setLayoutParams(new LinearLayout.LayoutParams(1795, 1526));
        this.ctbpejdkog.setPadding(WebSocketProtocol.PAYLOAD_SHORT, 168, 13, 164);
        linearLayout.addView(this.ctbpejdkog);
        this.ctbpejdkog.setBackgroundColor(Color.parseColor("#a6d096"));
        TextView textView4 = new TextView(this);
        this.nzokboevpx = textView4;
        textView4.setLayoutParams(new LinearLayout.LayoutParams(147, 221));
        this.nzokboevpx.setPadding(103, 14, 97, 6);
        linearLayout.addView(this.nzokboevpx);
        this.nzokboevpx.setBackgroundColor(Color.parseColor("#a16d9c"));
        RelativeLayout relativeLayout5 = new RelativeLayout(this);
        this.gdrsnkmzta = relativeLayout5;
        relativeLayout5.setLayoutParams(new LinearLayout.LayoutParams(1283, 1424));
        this.gdrsnkmzta.setPadding(27, 115, 12, 196);
        linearLayout.addView(this.gdrsnkmzta);
        this.gdrsnkmzta.setBackgroundColor(Color.parseColor("#e78039"));
        ToggleButton toggleButton4 = new ToggleButton(this);
        this.vzbmjpqceh = toggleButton4;
        toggleButton4.setLayoutParams(new LinearLayout.LayoutParams(628, 1424));
        this.vzbmjpqceh.setPadding(138, 33, 31, 75);
        linearLayout.addView(this.vzbmjpqceh);
        this.vzbmjpqceh.setBackgroundColor(Color.parseColor("#95948e"));
        TableLayout tableLayout5 = new TableLayout(this);
        this.iyislcajem = tableLayout5;
        tableLayout5.setLayoutParams(new LinearLayout.LayoutParams(739, 1136));
        this.iyislcajem.setPadding(128, 36, 131, 191);
        linearLayout.addView(this.iyislcajem);
        this.iyislcajem.setBackgroundColor(Color.parseColor("#2ba2cc"));
        TableLayout tableLayout6 = new TableLayout(this);
        this.npfzitcsgs = tableLayout6;
        tableLayout6.setLayoutParams(new LinearLayout.LayoutParams(1459, 1828));
        this.npfzitcsgs.setPadding(72, 109, 129, 79);
        linearLayout.addView(this.npfzitcsgs);
        this.npfzitcsgs.setBackgroundColor(Color.parseColor("#0e00d2"));
        RadioButton radioButton2 = new RadioButton(this);
        this.tykqtmcuzb = radioButton2;
        radioButton2.setLayoutParams(new LinearLayout.LayoutParams(993, 1250));
        this.tykqtmcuzb.setPadding(45, 30, 179, 19);
        linearLayout.addView(this.tykqtmcuzb);
        this.tykqtmcuzb.setBackgroundColor(Color.parseColor("#c1aa8f"));
        EditText editText6 = new EditText(this);
        this.dxxpxptyoa = editText6;
        editText6.setLayoutParams(new LinearLayout.LayoutParams(1799, 187));
        this.dxxpxptyoa.setPadding(105, 196, 8, 115);
        linearLayout.addView(this.dxxpxptyoa);
        this.dxxpxptyoa.setBackgroundColor(Color.parseColor("#4ef796"));
    }
}
