package com.device.watch.com.device.watch.vkjjheempy;

import android.app.Activity;
import android.graphics.Color;
import android.os.Bundle;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.CheckBox;
import android.widget.DatePicker;
import android.widget.EditText;
import android.widget.FrameLayout;
import android.widget.GridView;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ListView;
import android.widget.ProgressBar;
import android.widget.RadioButton;
import android.widget.RatingBar;
import android.widget.RelativeLayout;
import android.widget.ScrollView;
import android.widget.SeekBar;
import android.widget.Spinner;
import android.widget.Switch;
import android.widget.TableLayout;
import android.widget.TextView;
import android.widget.TimePicker;
import android.widget.ToggleButton;
import android.widget.ViewFlipper;
import androidx.constraintlayout.core.motion.utils.TypedValues;
import androidx.core.view.PointerIconCompat;
import com.baidu.location.BDLocation;
import com.google.zxing.pdf417.PDF417Common;
import com.luck.picture.lib.config.PictureConfig;

/* loaded from: classes2.dex */
public class UwcxqnfjkhoActivity extends Activity {
    TableLayout aialtuzdcz;
    Switch amghfnlyzv;
    FrameLayout anauwvqkgo;
    LinearLayout avmrmlijxu;
    Button aysmdtqvsg;
    ImageView bbfhcydage;
    LinearLayout bmusroxxue;
    ProgressBar brciaghmer;
    LinearLayout busmpnhlsb;
    TimePicker bykglvthwu;
    CheckBox bzxdesqsfi;
    ImageView cblswgkrco;
    RadioButton cdrxdiadou;
    ViewFlipper cicnukotai;
    SeekBar cosskpttdn;
    ProgressBar crtitqtbeo;
    ViewFlipper dfdvkcfngr;
    Button didvvvcbbi;
    ScrollView dpoyxedhex;
    RadioButton dumfumuzba;
    Spinner eaupycelyd;
    CheckBox eduvyjrows;
    ListView edysooqaai;
    TextView eevhvaaofn;
    ProgressBar efohoxiuco;
    RadioButton ekmgobwqlc;
    RadioButton elkvdmrwco;
    TimePicker enpdnpmifi;
    RatingBar eplqsefhka;
    RadioButton erurzmqbek;
    ToggleButton evnwxesvcc;
    Spinner exqocpcviz;
    FrameLayout eylfxesyhb;
    Button fakdqgmrog;
    EditText fdjqzwdsol;
    TextView fjypsgllmt;
    SeekBar flplsphzkp;
    CheckBox fquddgjgio;
    FrameLayout fqupkvwthi;
    ScrollView fsummlzjbh;
    TextView gbkzwmjwwr;
    ImageView gelnobwcsy;
    DatePicker hhoiokbmwm;
    EditText hzdotablxx;
    RadioButton iykyjbmbjm;
    RadioButton jbfddgpxnh;
    RatingBar jfptprhest;
    RatingBar jfsnmpubjb;
    ImageView jiwlbfgqlw;
    LinearLayout juobuiimmt;
    RelativeLayout kegglnlyxr;
    ViewFlipper kjyrvmjxmn;
    GridView kpeuctxlgp;
    TableLayout krnupmyawj;
    ListView kwvmqboqvg;
    ImageView ldaasbzhuh;
    TimePicker leewmbumrl;
    SeekBar lgxapvcxqw;
    ViewFlipper liwttuxnjt;
    TimePicker lltchcuniu;
    Switch lqzomrzwip;
    SeekBar lxosruybbw;
    RatingBar lznirsmwya;
    SeekBar mmjwwwjpdx;
    ProgressBar mmyrbovorz;
    ViewFlipper mnktsbikxt;
    EditText mtudlbdgbd;
    TableLayout ncdcorqbmt;
    EditText nclgczfvga;
    RadioButton necghzaoei;
    Spinner njkeijodvi;
    LinearLayout nmvquskfyf;
    TextView nqquwghqsj;
    ViewFlipper nvgukspfnr;
    RadioButton nwozpdngjz;
    RelativeLayout oazyjhfwud;
    ImageView omacerogao;
    Switch onvkfunhtp;
    ImageView ouorpeqdho;
    LinearLayout pmyjulazoz;
    GridView prevqduqog;
    TimePicker prqslneleh;
    Button pvmrnompkm;
    ScrollView pznuyumbit;
    TextView qhvdxivujf;
    GridView qivsnwmyjq;
    ImageView qnkocvodac;
    TableLayout qrvybgsgqd;
    GridView qudnxfuwcp;
    FrameLayout qwmzmkmzjg;
    CheckBox qyhoggkqed;
    ScrollView relzuwvyil;
    ListView rjyrizsans;
    ViewFlipper rppfqbuagg;
    RelativeLayout rskalugzxf;
    LinearLayout rsnfjqrokg;
    TimePicker rtdqqlqszv;
    DatePicker rzgcmwbobr;
    Spinner satsetyupk;
    Switch sbcomjxcwu;
    Button scanowlhpv;
    LinearLayout senvzmwmlz;
    GridView sfbgnwwyxl;
    ProgressBar sgzmgzpdpi;
    CheckBox sqnjmaxwzb;
    CheckBox srvwighdpn;
    RadioButton thuoiowmkn;
    Button tjlxokykgu;
    ListView ttnzovbpkk;
    Switch txmguftbqp;
    ScrollView txwyrrmiur;
    RelativeLayout ucuiiojnhm;
    FrameLayout ugutininmg;
    FrameLayout uihhvntbnd;
    Button umjqpyrvys;
    CheckBox usppkzgayt;
    CheckBox utkckdwupn;
    ScrollView utnovmtzen;
    TableLayout utyowpetdy;
    DatePicker uvfxtvenkq;
    FrameLayout uystzzrnhv;
    TableLayout uzrdbawgxu;
    ToggleButton viqcnxivcb;
    ProgressBar vlgggwobzq;
    FrameLayout vuzgllfadf;
    Button wfqgzxwqdy;
    ProgressBar wxytgdmciz;
    TableLayout xbfmrdaxvs;
    LinearLayout xoyopcysvy;
    ListView yavhyecprb;
    Button ybnttjvkak;
    SeekBar ycyclyaaaz;
    Spinner yksmmcyutj;
    CheckBox yqzzveypyj;
    TableLayout ysvekkbpif;
    GridView yxzwyongff;
    ToggleButton zlqlsumdqw;
    SeekBar znhxcypekm;
    LinearLayout zrcrzgeqnq;
    TableLayout zrlxgdqapv;
    CheckBox ztfsbaxmks;
    ListView zvhhyxxcdz;

    @Override // android.app.Activity
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        LinearLayout linearLayout = new LinearLayout(this);
        setContentView(linearLayout);
        linearLayout.setLayoutParams(new ViewGroup.LayoutParams(-1, -1));
        linearLayout.setOrientation(1);
        linearLayout.setBackgroundColor(Color.parseColor("#feddb5"));
        Switch r3 = new Switch(this);
        this.txmguftbqp = r3;
        r3.setLayoutParams(new LinearLayout.LayoutParams(1322, 724));
        this.txmguftbqp.setPadding(17, 195, 131, 115);
        linearLayout.addView(this.txmguftbqp);
        this.txmguftbqp.setBackgroundColor(Color.parseColor("#d44b61"));
        GridView gridView = new GridView(this);
        this.kpeuctxlgp = gridView;
        gridView.setLayoutParams(new LinearLayout.LayoutParams(1051, 225));
        this.kpeuctxlgp.setPadding(38, 63, 32, 122);
        linearLayout.addView(this.kpeuctxlgp);
        this.kpeuctxlgp.setBackgroundColor(Color.parseColor("#80d8cf"));
        LinearLayout linearLayout2 = new LinearLayout(this);
        this.pmyjulazoz = linearLayout2;
        linearLayout2.setLayoutParams(new LinearLayout.LayoutParams(1553, 1629));
        this.pmyjulazoz.setPadding(182, 15, 12, 52);
        linearLayout.addView(this.pmyjulazoz);
        this.pmyjulazoz.setBackgroundColor(Color.parseColor("#f6b43a"));
        SeekBar seekBar = new SeekBar(this);
        this.cosskpttdn = seekBar;
        seekBar.setLayoutParams(new LinearLayout.LayoutParams(1693, 923));
        this.cosskpttdn.setPadding(71, 83, 24, 127);
        linearLayout.addView(this.cosskpttdn);
        this.cosskpttdn.setBackgroundColor(Color.parseColor("#466454"));
        GridView gridView2 = new GridView(this);
        this.prevqduqog = gridView2;
        gridView2.setLayoutParams(new LinearLayout.LayoutParams(380, TypedValues.MotionType.TYPE_DRAW_PATH));
        this.prevqduqog.setPadding(PictureConfig.CHOOSE_REQUEST, 140, 134, 157);
        linearLayout.addView(this.prevqduqog);
        this.prevqduqog.setBackgroundColor(Color.parseColor("#2de7d6"));
        ScrollView scrollView = new ScrollView(this);
        this.utnovmtzen = scrollView;
        scrollView.setLayoutParams(new LinearLayout.LayoutParams(315, 1311));
        this.utnovmtzen.setPadding(109, 137, 157, 197);
        linearLayout.addView(this.utnovmtzen);
        this.utnovmtzen.setBackgroundColor(Color.parseColor("#1291e7"));
        ProgressBar progressBar = new ProgressBar(this);
        this.vlgggwobzq = progressBar;
        progressBar.setLayoutParams(new LinearLayout.LayoutParams(652, 1525));
        this.vlgggwobzq.setPadding(21, 102, 58, 140);
        linearLayout.addView(this.vlgggwobzq);
        this.vlgggwobzq.setBackgroundColor(Color.parseColor("#fc7fde"));
        Switch r32 = new Switch(this);
        this.sbcomjxcwu = r32;
        r32.setLayoutParams(new LinearLayout.LayoutParams(382, 331));
        this.sbcomjxcwu.setPadding(9, 138, 179, 110);
        linearLayout.addView(this.sbcomjxcwu);
        this.sbcomjxcwu.setBackgroundColor(Color.parseColor("#42ef3e"));
        Button button = new Button(this);
        this.wfqgzxwqdy = button;
        button.setLayoutParams(new LinearLayout.LayoutParams(1409, 974));
        this.wfqgzxwqdy.setPadding(150, 197, 142, 99);
        linearLayout.addView(this.wfqgzxwqdy);
        this.wfqgzxwqdy.setBackgroundColor(Color.parseColor("#4f35db"));
        RadioButton radioButton = new RadioButton(this);
        this.nwozpdngjz = radioButton;
        radioButton.setLayoutParams(new LinearLayout.LayoutParams(1103, TypedValues.CycleType.TYPE_EASING));
        this.nwozpdngjz.setPadding(115, 75, 78, 112);
        linearLayout.addView(this.nwozpdngjz);
        this.nwozpdngjz.setBackgroundColor(Color.parseColor("#66df1d"));
        SeekBar seekBar2 = new SeekBar(this);
        this.ycyclyaaaz = seekBar2;
        seekBar2.setLayoutParams(new LinearLayout.LayoutParams(1647, 197));
        this.ycyclyaaaz.setPadding(101, 96, 29, 123);
        linearLayout.addView(this.ycyclyaaaz);
        this.ycyclyaaaz.setBackgroundColor(Color.parseColor("#190592"));
        ImageView imageView = new ImageView(this);
        this.ldaasbzhuh = imageView;
        imageView.setLayoutParams(new LinearLayout.LayoutParams(1979, TypedValues.TransitionType.TYPE_DURATION));
        this.ldaasbzhuh.setPadding(33, 186, 189, 130);
        linearLayout.addView(this.ldaasbzhuh);
        this.ldaasbzhuh.setBackgroundColor(Color.parseColor("#679b09"));
        TableLayout tableLayout = new TableLayout(this);
        this.zrlxgdqapv = tableLayout;
        tableLayout.setLayoutParams(new LinearLayout.LayoutParams(1178, 1377));
        this.zrlxgdqapv.setPadding(20, 69, 106, 121);
        linearLayout.addView(this.zrlxgdqapv);
        this.zrlxgdqapv.setBackgroundColor(Color.parseColor("#2ae7b6"));
        TableLayout tableLayout2 = new TableLayout(this);
        this.xbfmrdaxvs = tableLayout2;
        tableLayout2.setLayoutParams(new LinearLayout.LayoutParams(1152, 1437));
        this.xbfmrdaxvs.setPadding(134, 30, 91, 70);
        linearLayout.addView(this.xbfmrdaxvs);
        this.xbfmrdaxvs.setBackgroundColor(Color.parseColor("#cc191f"));
        RadioButton radioButton2 = new RadioButton(this);
        this.jbfddgpxnh = radioButton2;
        radioButton2.setLayoutParams(new LinearLayout.LayoutParams(1898, 865));
        this.jbfddgpxnh.setPadding(69, 190, 198, 28);
        linearLayout.addView(this.jbfddgpxnh);
        this.jbfddgpxnh.setBackgroundColor(Color.parseColor("#fe02fb"));
        ProgressBar progressBar2 = new ProgressBar(this);
        this.sgzmgzpdpi = progressBar2;
        progressBar2.setLayoutParams(new LinearLayout.LayoutParams(463, 1770));
        this.sgzmgzpdpi.setPadding(197, 121, 17, 16);
        linearLayout.addView(this.sgzmgzpdpi);
        this.sgzmgzpdpi.setBackgroundColor(Color.parseColor("#cbf902"));
        RadioButton radioButton3 = new RadioButton(this);
        this.dumfumuzba = radioButton3;
        radioButton3.setLayoutParams(new LinearLayout.LayoutParams(1001, 221));
        this.dumfumuzba.setPadding(132, 180, 78, 131);
        linearLayout.addView(this.dumfumuzba);
        this.dumfumuzba.setBackgroundColor(Color.parseColor("#c1c344"));
        Button button2 = new Button(this);
        this.fakdqgmrog = button2;
        button2.setLayoutParams(new LinearLayout.LayoutParams(169, 1684));
        this.fakdqgmrog.setPadding(60, 0, 134, 84);
        linearLayout.addView(this.fakdqgmrog);
        this.fakdqgmrog.setBackground(new Mkbhtaooiqh());
        RadioButton radioButton4 = new RadioButton(this);
        this.thuoiowmkn = radioButton4;
        radioButton4.setLayoutParams(new LinearLayout.LayoutParams(1334, 1257));
        this.thuoiowmkn.setPadding(91, 138, 38, 96);
        linearLayout.addView(this.thuoiowmkn);
        this.thuoiowmkn.setBackgroundColor(Color.parseColor("#8436cc"));
        ViewFlipper viewFlipper = new ViewFlipper(this);
        this.kjyrvmjxmn = viewFlipper;
        viewFlipper.setLayoutParams(new LinearLayout.LayoutParams(490, 493));
        this.kjyrvmjxmn.setPadding(119, 174, 105, 132);
        linearLayout.addView(this.kjyrvmjxmn);
        this.kjyrvmjxmn.setBackgroundColor(Color.parseColor("#ce41c1"));
        DatePicker datePicker = new DatePicker(this);
        this.hhoiokbmwm = datePicker;
        datePicker.setLayoutParams(new LinearLayout.LayoutParams(382, 861));
        this.hhoiokbmwm.setPadding(6, 33, 183, 145);
        linearLayout.addView(this.hhoiokbmwm);
        this.hhoiokbmwm.setBackgroundColor(Color.parseColor("#60ccca"));
        LinearLayout linearLayout3 = new LinearLayout(this);
        this.senvzmwmlz = linearLayout3;
        linearLayout3.setLayoutParams(new LinearLayout.LayoutParams(1516, 563));
        this.senvzmwmlz.setPadding(114, 150, 192, 151);
        linearLayout.addView(this.senvzmwmlz);
        this.senvzmwmlz.setBackgroundColor(Color.parseColor("#ddba8d"));
        RatingBar ratingBar = new RatingBar(this);
        this.lznirsmwya = ratingBar;
        ratingBar.setLayoutParams(new LinearLayout.LayoutParams(1121, 792));
        this.lznirsmwya.setPadding(116, 19, 181, 125);
        linearLayout.addView(this.lznirsmwya);
        this.lznirsmwya.setBackgroundColor(Color.parseColor("#689a66"));
        ToggleButton toggleButton = new ToggleButton(this);
        this.zlqlsumdqw = toggleButton;
        toggleButton.setLayoutParams(new LinearLayout.LayoutParams(971, 438));
        this.zlqlsumdqw.setPadding(69, 23, 111, 103);
        linearLayout.addView(this.zlqlsumdqw);
        this.zlqlsumdqw.setBackgroundColor(Color.parseColor("#a64e9b"));
        ScrollView scrollView2 = new ScrollView(this);
        this.fsummlzjbh = scrollView2;
        scrollView2.setLayoutParams(new LinearLayout.LayoutParams(1349, 1922));
        this.fsummlzjbh.setPadding(165, 124, 100, 196);
        linearLayout.addView(this.fsummlzjbh);
        this.fsummlzjbh.setBackgroundColor(Color.parseColor("#85d950"));
        RadioButton radioButton5 = new RadioButton(this);
        this.cdrxdiadou = radioButton5;
        radioButton5.setLayoutParams(new LinearLayout.LayoutParams(925, 1581));
        this.cdrxdiadou.setPadding(157, 185, 26, 57);
        linearLayout.addView(this.cdrxdiadou);
        this.cdrxdiadou.setBackgroundColor(Color.parseColor("#8fb46a"));
        ImageView imageView2 = new ImageView(this);
        this.ouorpeqdho = imageView2;
        imageView2.setLayoutParams(new LinearLayout.LayoutParams(1893, 735));
        this.ouorpeqdho.setPadding(104, 46, 45, 111);
        linearLayout.addView(this.ouorpeqdho);
        this.ouorpeqdho.setBackgroundColor(Color.parseColor("#25b983"));
        TableLayout tableLayout3 = new TableLayout(this);
        this.uzrdbawgxu = tableLayout3;
        tableLayout3.setLayoutParams(new LinearLayout.LayoutParams(1917, 871));
        this.uzrdbawgxu.setPadding(157, 148, 172, 101);
        linearLayout.addView(this.uzrdbawgxu);
        this.uzrdbawgxu.setBackgroundColor(Color.parseColor("#071b33"));
        TextView textView = new TextView(this);
        this.qhvdxivujf = textView;
        textView.setLayoutParams(new LinearLayout.LayoutParams(1113, 811));
        this.qhvdxivujf.setPadding(56, 9, 159, BDLocation.TypeServerDecryptError);
        linearLayout.addView(this.qhvdxivujf);
        this.qhvdxivujf.setBackgroundColor(Color.parseColor("#dd4c4b"));
        Button button3 = new Button(this);
        this.didvvvcbbi = button3;
        button3.setLayoutParams(new LinearLayout.LayoutParams(1734, 896));
        this.didvvvcbbi.setPadding(142, 22, 29, 34);
        linearLayout.addView(this.didvvvcbbi);
        this.didvvvcbbi.setBackgroundColor(Color.parseColor("#064fb0"));
        RadioButton radioButton6 = new RadioButton(this);
        this.erurzmqbek = radioButton6;
        radioButton6.setLayoutParams(new LinearLayout.LayoutParams(800, 1213));
        this.erurzmqbek.setPadding(104, 53, 193, 20);
        linearLayout.addView(this.erurzmqbek);
        this.erurzmqbek.setBackgroundColor(Color.parseColor("#7bad72"));
        LinearLayout linearLayout4 = new LinearLayout(this);
        this.rsnfjqrokg = linearLayout4;
        linearLayout4.setLayoutParams(new LinearLayout.LayoutParams(1207, 122));
        this.rsnfjqrokg.setPadding(119, 98, 173, 69);
        linearLayout.addView(this.rsnfjqrokg);
        this.rsnfjqrokg.setBackgroundColor(Color.parseColor("#35a71b"));
        RelativeLayout relativeLayout = new RelativeLayout(this);
        this.rskalugzxf = relativeLayout;
        relativeLayout.setLayoutParams(new LinearLayout.LayoutParams(487, 775));
        this.rskalugzxf.setPadding(15, 109, 54, 107);
        linearLayout.addView(this.rskalugzxf);
        this.rskalugzxf.setBackgroundColor(Color.parseColor("#442570"));
        Spinner spinner = new Spinner(this);
        this.eaupycelyd = spinner;
        spinner.setLayoutParams(new LinearLayout.LayoutParams(782, 1091));
        this.eaupycelyd.setPadding(79, 177, 70, 105);
        linearLayout.addView(this.eaupycelyd);
        this.eaupycelyd.setBackgroundColor(Color.parseColor("#0b66cd"));
        TableLayout tableLayout4 = new TableLayout(this);
        this.ncdcorqbmt = tableLayout4;
        tableLayout4.setLayoutParams(new LinearLayout.LayoutParams(1871, 1219));
        this.ncdcorqbmt.setPadding(117, 76, 104, 67);
        linearLayout.addView(this.ncdcorqbmt);
        this.ncdcorqbmt.setBackgroundColor(Color.parseColor("#e814bf"));
        Button button4 = new Button(this);
        this.ybnttjvkak = button4;
        button4.setLayoutParams(new LinearLayout.LayoutParams(1581, 852));
        this.ybnttjvkak.setPadding(39, 4, 70, 63);
        linearLayout.addView(this.ybnttjvkak);
        this.ybnttjvkak.setBackgroundColor(Color.parseColor("#a177f9"));
        EditText editText = new EditText(this);
        this.hzdotablxx = editText;
        editText.setLayoutParams(new LinearLayout.LayoutParams(1004, 983));
        this.hzdotablxx.setPadding(132, 10, 38, 168);
        linearLayout.addView(this.hzdotablxx);
        this.hzdotablxx.setBackgroundColor(Color.parseColor("#684f1f"));
        EditText editText2 = new EditText(this);
        this.fdjqzwdsol = editText2;
        editText2.setLayoutParams(new LinearLayout.LayoutParams(9, 1470));
        this.fdjqzwdsol.setPadding(170, 158, 3, 22);
        linearLayout.addView(this.fdjqzwdsol);
        this.fdjqzwdsol.setBackgroundColor(Color.parseColor("#f52769"));
        LinearLayout linearLayout5 = new LinearLayout(this);
        this.busmpnhlsb = linearLayout5;
        linearLayout5.setLayoutParams(new LinearLayout.LayoutParams(897, 1856));
        this.busmpnhlsb.setPadding(25, BDLocation.TypeServerError, 96, 150);
        linearLayout.addView(this.busmpnhlsb);
        this.busmpnhlsb.setBackgroundColor(Color.parseColor("#68a073"));
        Button button5 = new Button(this);
        this.pvmrnompkm = button5;
        button5.setLayoutParams(new LinearLayout.LayoutParams(102, 990));
        this.pvmrnompkm.setPadding(157, 180, 86, 154);
        linearLayout.addView(this.pvmrnompkm);
        this.pvmrnompkm.setBackgroundColor(Color.parseColor("#b29329"));
        Switch r2 = new Switch(this);
        this.amghfnlyzv = r2;
        r2.setLayoutParams(new LinearLayout.LayoutParams(165, 553));
        this.amghfnlyzv.setPadding(177, 124, 14, 190);
        linearLayout.addView(this.amghfnlyzv);
        this.amghfnlyzv.setBackgroundColor(Color.parseColor("#bc16f4"));
        CheckBox checkBox = new CheckBox(this);
        this.ztfsbaxmks = checkBox;
        checkBox.setLayoutParams(new LinearLayout.LayoutParams(1069, 1513));
        this.ztfsbaxmks.setPadding(111, 119, 1, 80);
        linearLayout.addView(this.ztfsbaxmks);
        this.ztfsbaxmks.setBackgroundColor(Color.parseColor("#8a1f4e"));
        TimePicker timePicker = new TimePicker(this);
        this.prqslneleh = timePicker;
        timePicker.setLayoutParams(new LinearLayout.LayoutParams(978, 1747));
        this.prqslneleh.setPadding(157, 48, 85, 146);
        linearLayout.addView(this.prqslneleh);
        this.prqslneleh.setBackgroundColor(Color.parseColor("#9be491"));
        ImageView imageView3 = new ImageView(this);
        this.gelnobwcsy = imageView3;
        imageView3.setLayoutParams(new LinearLayout.LayoutParams(1991, 1104));
        this.gelnobwcsy.setPadding(186, 152, 10, 15);
        linearLayout.addView(this.gelnobwcsy);
        this.gelnobwcsy.setBackgroundColor(Color.parseColor("#7a0a8d"));
        ProgressBar progressBar3 = new ProgressBar(this);
        this.crtitqtbeo = progressBar3;
        progressBar3.setLayoutParams(new LinearLayout.LayoutParams(353, 1805));
        this.crtitqtbeo.setPadding(39, 32, 170, 110);
        linearLayout.addView(this.crtitqtbeo);
        this.crtitqtbeo.setBackgroundColor(Color.parseColor("#e9eb7d"));
        TimePicker timePicker2 = new TimePicker(this);
        this.rtdqqlqszv = timePicker2;
        timePicker2.setLayoutParams(new LinearLayout.LayoutParams(240, 1339));
        this.rtdqqlqszv.setPadding(185, 2, 94, 23);
        linearLayout.addView(this.rtdqqlqszv);
        this.rtdqqlqszv.setBackgroundColor(Color.parseColor("#34ce2f"));
        SeekBar seekBar3 = new SeekBar(this);
        this.flplsphzkp = seekBar3;
        seekBar3.setLayoutParams(new LinearLayout.LayoutParams(1216, 876));
        this.flplsphzkp.setPadding(11, 4, 29, 32);
        linearLayout.addView(this.flplsphzkp);
        this.flplsphzkp.setBackgroundColor(Color.parseColor("#bec086"));
        ListView listView = new ListView(this);
        this.ttnzovbpkk = listView;
        listView.setLayoutParams(new LinearLayout.LayoutParams(1749, 912));
        this.ttnzovbpkk.setPadding(137, 178, 159, 195);
        linearLayout.addView(this.ttnzovbpkk);
        this.ttnzovbpkk.setBackgroundColor(Color.parseColor("#44c35a"));
        ProgressBar progressBar4 = new ProgressBar(this);
        this.efohoxiuco = progressBar4;
        progressBar4.setLayoutParams(new LinearLayout.LayoutParams(1197, 931));
        this.efohoxiuco.setPadding(32, 151, 103, 80);
        linearLayout.addView(this.efohoxiuco);
        this.efohoxiuco.setBackgroundColor(Color.parseColor("#063ec6"));
        SeekBar seekBar4 = new SeekBar(this);
        this.lgxapvcxqw = seekBar4;
        seekBar4.setLayoutParams(new LinearLayout.LayoutParams(1383, 204));
        this.lgxapvcxqw.setPadding(137, 16, BDLocation.TypeCoarseLocation, 113);
        linearLayout.addView(this.lgxapvcxqw);
        this.lgxapvcxqw.setBackgroundColor(Color.parseColor("#96a126"));
        GridView gridView3 = new GridView(this);
        this.yxzwyongff = gridView3;
        gridView3.setLayoutParams(new LinearLayout.LayoutParams(857, 1275));
        this.yxzwyongff.setPadding(149, 77, 53, 103);
        linearLayout.addView(this.yxzwyongff);
        this.yxzwyongff.setBackgroundColor(Color.parseColor("#f2afb2"));
        SeekBar seekBar5 = new SeekBar(this);
        this.lxosruybbw = seekBar5;
        seekBar5.setLayoutParams(new LinearLayout.LayoutParams(1254, 1606));
        this.lxosruybbw.setPadding(123, 54, 100, 88);
        linearLayout.addView(this.lxosruybbw);
        this.lxosruybbw.setBackgroundColor(Color.parseColor("#280faf"));
        RatingBar ratingBar2 = new RatingBar(this);
        this.jfsnmpubjb = ratingBar2;
        ratingBar2.setLayoutParams(new LinearLayout.LayoutParams(6, 1129));
        this.jfsnmpubjb.setPadding(116, 30, 116, 138);
        linearLayout.addView(this.jfsnmpubjb);
        this.jfsnmpubjb.setBackgroundColor(Color.parseColor("#060dd2"));
        Spinner spinner2 = new Spinner(this);
        this.njkeijodvi = spinner2;
        spinner2.setLayoutParams(new LinearLayout.LayoutParams(1063, 978));
        this.njkeijodvi.setPadding(144, 166, 91, 88);
        linearLayout.addView(this.njkeijodvi);
        this.njkeijodvi.setBackgroundColor(Color.parseColor("#b7c8a8"));
        LinearLayout linearLayout6 = new LinearLayout(this);
        this.juobuiimmt = linearLayout6;
        linearLayout6.setLayoutParams(new LinearLayout.LayoutParams(121, 750));
        this.juobuiimmt.setPadding(123, 96, 172, 174);
        linearLayout.addView(this.juobuiimmt);
        this.juobuiimmt.setBackgroundColor(Color.parseColor("#1aecfd"));
        TableLayout tableLayout5 = new TableLayout(this);
        this.krnupmyawj = tableLayout5;
        tableLayout5.setLayoutParams(new LinearLayout.LayoutParams(384, 858));
        this.krnupmyawj.setPadding(40, 111, 5, 100);
        linearLayout.addView(this.krnupmyawj);
        this.krnupmyawj.setBackgroundColor(Color.parseColor("#7441b2"));
        ListView listView2 = new ListView(this);
        this.yavhyecprb = listView2;
        listView2.setLayoutParams(new LinearLayout.LayoutParams(362, 1));
        this.yavhyecprb.setPadding(198, 168, 54, 68);
        linearLayout.addView(this.yavhyecprb);
        this.yavhyecprb.setBackgroundColor(Color.parseColor("#e5f4f4"));
        ViewFlipper viewFlipper2 = new ViewFlipper(this);
        this.mnktsbikxt = viewFlipper2;
        viewFlipper2.setLayoutParams(new LinearLayout.LayoutParams(935, 1606));
        this.mnktsbikxt.setPadding(1, 119, 157, 81);
        linearLayout.addView(this.mnktsbikxt);
        this.mnktsbikxt.setBackgroundColor(Color.parseColor("#0c1cb0"));
        SeekBar seekBar6 = new SeekBar(this);
        this.mmjwwwjpdx = seekBar6;
        seekBar6.setLayoutParams(new LinearLayout.LayoutParams(1520, 741));
        this.mmjwwwjpdx.setPadding(183, 40, 199, 62);
        linearLayout.addView(this.mmjwwwjpdx);
        this.mmjwwwjpdx.setBackgroundColor(Color.parseColor("#a16493"));
        TextView textView2 = new TextView(this);
        this.eevhvaaofn = textView2;
        textView2.setLayoutParams(new LinearLayout.LayoutParams(1559, 1604));
        this.eevhvaaofn.setPadding(91, 128, 8, 14);
        linearLayout.addView(this.eevhvaaofn);
        this.eevhvaaofn.setBackgroundColor(Color.parseColor("#b70ea8"));
        FrameLayout frameLayout = new FrameLayout(this);
        this.qwmzmkmzjg = frameLayout;
        frameLayout.setLayoutParams(new LinearLayout.LayoutParams(1062, 744));
        this.qwmzmkmzjg.setPadding(87, 73, 43, 150);
        linearLayout.addView(this.qwmzmkmzjg);
        this.qwmzmkmzjg.setBackgroundColor(Color.parseColor("#8a9965"));
        LinearLayout linearLayout7 = new LinearLayout(this);
        this.avmrmlijxu = linearLayout7;
        linearLayout7.setLayoutParams(new LinearLayout.LayoutParams(972, 1534));
        this.avmrmlijxu.setPadding(75, 22, 148, 93);
        linearLayout.addView(this.avmrmlijxu);
        this.avmrmlijxu.setBackgroundColor(Color.parseColor("#63aec5"));
        FrameLayout frameLayout2 = new FrameLayout(this);
        this.eylfxesyhb = frameLayout2;
        frameLayout2.setLayoutParams(new LinearLayout.LayoutParams(809, 193));
        this.eylfxesyhb.setPadding(179, 153, 58, 84);
        linearLayout.addView(this.eylfxesyhb);
        this.eylfxesyhb.setBackgroundColor(Color.parseColor("#f328d6"));
        TextView textView3 = new TextView(this);
        this.nqquwghqsj = textView3;
        textView3.setLayoutParams(new LinearLayout.LayoutParams(770, 1882));
        this.nqquwghqsj.setPadding(158, BDLocation.TypeServerError, 186, 63);
        linearLayout.addView(this.nqquwghqsj);
        this.nqquwghqsj.setBackgroundColor(Color.parseColor("#93f964"));
        TimePicker timePicker3 = new TimePicker(this);
        this.lltchcuniu = timePicker3;
        timePicker3.setLayoutParams(new LinearLayout.LayoutParams(1799, PDF417Common.MAX_CODEWORDS_IN_BARCODE));
        this.lltchcuniu.setPadding(105, 196, 47, 88);
        linearLayout.addView(this.lltchcuniu);
        this.lltchcuniu.setBackgroundColor(Color.parseColor("#1d365d"));
        FrameLayout frameLayout3 = new FrameLayout(this);
        this.ugutininmg = frameLayout3;
        frameLayout3.setLayoutParams(new LinearLayout.LayoutParams(1642, 1220));
        this.ugutininmg.setPadding(186, 48, 101, 171);
        linearLayout.addView(this.ugutininmg);
        this.ugutininmg.setBackgroundColor(Color.parseColor("#884f30"));
        FrameLayout frameLayout4 = new FrameLayout(this);
        this.vuzgllfadf = frameLayout4;
        frameLayout4.setLayoutParams(new LinearLayout.LayoutParams(1586, 464));
        this.vuzgllfadf.setPadding(89, 197, 4, 50);
        linearLayout.addView(this.vuzgllfadf);
        this.vuzgllfadf.setBackgroundColor(Color.parseColor("#846233"));
        EditText editText3 = new EditText(this);
        this.nclgczfvga = editText3;
        editText3.setLayoutParams(new LinearLayout.LayoutParams(886, 1348));
        this.nclgczfvga.setPadding(65, 76, 194, 102);
        linearLayout.addView(this.nclgczfvga);
        this.nclgczfvga.setBackgroundColor(Color.parseColor("#18e4d7"));
        TimePicker timePicker4 = new TimePicker(this);
        this.bykglvthwu = timePicker4;
        timePicker4.setLayoutParams(new LinearLayout.LayoutParams(1724, 1590));
        this.bykglvthwu.setPadding(189, 196, 176, 96);
        linearLayout.addView(this.bykglvthwu);
        this.bykglvthwu.setBackgroundColor(Color.parseColor("#0e48a6"));
        CheckBox checkBox2 = new CheckBox(this);
        this.yqzzveypyj = checkBox2;
        checkBox2.setLayoutParams(new LinearLayout.LayoutParams(920, 893));
        this.yqzzveypyj.setPadding(70, 119, 78, 43);
        linearLayout.addView(this.yqzzveypyj);
        this.yqzzveypyj.setBackgroundColor(Color.parseColor("#24c24e"));
        ScrollView scrollView3 = new ScrollView(this);
        this.pznuyumbit = scrollView3;
        scrollView3.setLayoutParams(new LinearLayout.LayoutParams(954, 1697));
        this.pznuyumbit.setPadding(26, 193, 139, 102);
        linearLayout.addView(this.pznuyumbit);
        this.pznuyumbit.setBackgroundColor(Color.parseColor("#0df0c8"));
        Button button6 = new Button(this);
        this.umjqpyrvys = button6;
        button6.setLayoutParams(new LinearLayout.LayoutParams(1384, 1690));
        this.umjqpyrvys.setPadding(199, 94, 180, 155);
        linearLayout.addView(this.umjqpyrvys);
        this.umjqpyrvys.setBackgroundColor(Color.parseColor("#2f5beb"));
        LinearLayout linearLayout8 = new LinearLayout(this);
        this.zrcrzgeqnq = linearLayout8;
        linearLayout8.setLayoutParams(new LinearLayout.LayoutParams(1202, 155));
        this.zrcrzgeqnq.setPadding(173, 110, 109, 190);
        linearLayout.addView(this.zrcrzgeqnq);
        this.zrcrzgeqnq.setBackgroundColor(Color.parseColor("#37861d"));
        TimePicker timePicker5 = new TimePicker(this);
        this.leewmbumrl = timePicker5;
        timePicker5.setLayoutParams(new LinearLayout.LayoutParams(1563, 1106));
        this.leewmbumrl.setPadding(65, 127, 109, 59);
        linearLayout.addView(this.leewmbumrl);
        this.leewmbumrl.setBackgroundColor(Color.parseColor("#fcdbde"));
        LinearLayout linearLayout9 = new LinearLayout(this);
        this.xoyopcysvy = linearLayout9;
        linearLayout9.setLayoutParams(new LinearLayout.LayoutParams(1597, 1397));
        this.xoyopcysvy.setPadding(54, 192, 179, 121);
        linearLayout.addView(this.xoyopcysvy);
        this.xoyopcysvy.setBackgroundColor(Color.parseColor("#1478dc"));
        TimePicker timePicker6 = new TimePicker(this);
        this.enpdnpmifi = timePicker6;
        timePicker6.setLayoutParams(new LinearLayout.LayoutParams(29, 1795));
        this.enpdnpmifi.setPadding(184, 69, 78, 4);
        linearLayout.addView(this.enpdnpmifi);
        this.enpdnpmifi.setBackgroundColor(Color.parseColor("#818987"));
        RatingBar ratingBar3 = new RatingBar(this);
        this.eplqsefhka = ratingBar3;
        ratingBar3.setLayoutParams(new LinearLayout.LayoutParams(1446, 1038));
        this.eplqsefhka.setPadding(BDLocation.TypeNetWorkLocation, PictureConfig.CHOOSE_REQUEST, 10, 186);
        linearLayout.addView(this.eplqsefhka);
        this.eplqsefhka.setBackgroundColor(Color.parseColor("#4d6568"));
        ImageView imageView4 = new ImageView(this);
        this.omacerogao = imageView4;
        imageView4.setLayoutParams(new LinearLayout.LayoutParams(729, 1049));
        this.omacerogao.setPadding(45, 68, 110, 101);
        linearLayout.addView(this.omacerogao);
        this.omacerogao.setBackgroundColor(Color.parseColor("#76dc42"));
        RadioButton radioButton7 = new RadioButton(this);
        this.iykyjbmbjm = radioButton7;
        radioButton7.setLayoutParams(new LinearLayout.LayoutParams(1449, 715));
        this.iykyjbmbjm.setPadding(185, 173, 170, 168);
        linearLayout.addView(this.iykyjbmbjm);
        this.iykyjbmbjm.setBackgroundColor(Color.parseColor("#86c56b"));
        RelativeLayout relativeLayout2 = new RelativeLayout(this);
        this.ucuiiojnhm = relativeLayout2;
        relativeLayout2.setLayoutParams(new LinearLayout.LayoutParams(1629, 135));
        this.ucuiiojnhm.setPadding(22, 24, 53, 25);
        linearLayout.addView(this.ucuiiojnhm);
        this.ucuiiojnhm.setBackgroundColor(Color.parseColor("#19b5a2"));
        GridView gridView4 = new GridView(this);
        this.qudnxfuwcp = gridView4;
        gridView4.setLayoutParams(new LinearLayout.LayoutParams(406, 62));
        this.qudnxfuwcp.setPadding(84, 131, 4, 107);
        linearLayout.addView(this.qudnxfuwcp);
        this.qudnxfuwcp.setBackgroundColor(Color.parseColor("#dac170"));
        Spinner spinner3 = new Spinner(this);
        this.exqocpcviz = spinner3;
        spinner3.setLayoutParams(new LinearLayout.LayoutParams(151, 1579));
        this.exqocpcviz.setPadding(154, 9, 143, 46);
        linearLayout.addView(this.exqocpcviz);
        this.exqocpcviz.setBackgroundColor(Color.parseColor("#47590e"));
        SeekBar seekBar7 = new SeekBar(this);
        this.znhxcypekm = seekBar7;
        seekBar7.setLayoutParams(new LinearLayout.LayoutParams(PictureConfig.CHOOSE_REQUEST, 450));
        this.znhxcypekm.setPadding(43, 164, 117, 141);
        linearLayout.addView(this.znhxcypekm);
        this.znhxcypekm.setBackgroundColor(Color.parseColor("#c1e97b"));
        RelativeLayout relativeLayout3 = new RelativeLayout(this);
        this.oazyjhfwud = relativeLayout3;
        relativeLayout3.setLayoutParams(new LinearLayout.LayoutParams(619, 1038));
        this.oazyjhfwud.setPadding(83, 8, 152, 19);
        linearLayout.addView(this.oazyjhfwud);
        this.oazyjhfwud.setBackgroundColor(Color.parseColor("#a9d4a4"));
        ScrollView scrollView4 = new ScrollView(this);
        this.dpoyxedhex = scrollView4;
        scrollView4.setLayoutParams(new LinearLayout.LayoutParams(1039, 1932));
        this.dpoyxedhex.setPadding(151, 77, 147, 49);
        linearLayout.addView(this.dpoyxedhex);
        this.dpoyxedhex.setBackgroundColor(Color.parseColor("#29e97e"));
        Button button7 = new Button(this);
        this.tjlxokykgu = button7;
        button7.setLayoutParams(new LinearLayout.LayoutParams(1083, 1600));
        this.tjlxokykgu.setPadding(131, 97, 70, 143);
        linearLayout.addView(this.tjlxokykgu);
        this.tjlxokykgu.setBackgroundColor(Color.parseColor("#f97f85"));
        ScrollView scrollView5 = new ScrollView(this);
        this.relzuwvyil = scrollView5;
        scrollView5.setLayoutParams(new LinearLayout.LayoutParams(1699, 570));
        this.relzuwvyil.setPadding(6, 32, 195, 134);
        linearLayout.addView(this.relzuwvyil);
        this.relzuwvyil.setBackgroundColor(Color.parseColor("#af6857"));
        ProgressBar progressBar5 = new ProgressBar(this);
        this.brciaghmer = progressBar5;
        progressBar5.setLayoutParams(new LinearLayout.LayoutParams(1741, 1245));
        this.brciaghmer.setPadding(40, 25, 67, 175);
        linearLayout.addView(this.brciaghmer);
        this.brciaghmer.setBackgroundColor(Color.parseColor("#636cfe"));
        TableLayout tableLayout6 = new TableLayout(this);
        this.qrvybgsgqd = tableLayout6;
        tableLayout6.setLayoutParams(new LinearLayout.LayoutParams(1022, 1990));
        this.qrvybgsgqd.setPadding(4, 159, 186, 75);
        linearLayout.addView(this.qrvybgsgqd);
        this.qrvybgsgqd.setBackgroundColor(Color.parseColor("#903068"));
        Spinner spinner4 = new Spinner(this);
        this.yksmmcyutj = spinner4;
        spinner4.setLayoutParams(new LinearLayout.LayoutParams(554, PointerIconCompat.TYPE_GRABBING));
        this.yksmmcyutj.setPadding(57, 48, 144, 15);
        linearLayout.addView(this.yksmmcyutj);
        this.yksmmcyutj.setBackgroundColor(Color.parseColor("#cf445d"));
        GridView gridView5 = new GridView(this);
        this.sfbgnwwyxl = gridView5;
        gridView5.setLayoutParams(new LinearLayout.LayoutParams(43, 3));
        this.sfbgnwwyxl.setPadding(19, 197, 65, 147);
        linearLayout.addView(this.sfbgnwwyxl);
        this.sfbgnwwyxl.setBackgroundColor(Color.parseColor("#e8cfd7"));
        CheckBox checkBox3 = new CheckBox(this);
        this.fquddgjgio = checkBox3;
        checkBox3.setLayoutParams(new LinearLayout.LayoutParams(442, 1871));
        this.fquddgjgio.setPadding(103, 151, PictureConfig.CHOOSE_REQUEST, 23);
        linearLayout.addView(this.fquddgjgio);
        this.fquddgjgio.setBackgroundColor(Color.parseColor("#828057"));
        LinearLayout linearLayout10 = new LinearLayout(this);
        this.bmusroxxue = linearLayout10;
        linearLayout10.setLayoutParams(new LinearLayout.LayoutParams(194, 1213));
        this.bmusroxxue.setPadding(52, 139, 183, 49);
        linearLayout.addView(this.bmusroxxue);
        this.bmusroxxue.setBackgroundColor(Color.parseColor("#e6c183"));
        ViewFlipper viewFlipper3 = new ViewFlipper(this);
        this.dfdvkcfngr = viewFlipper3;
        viewFlipper3.setLayoutParams(new LinearLayout.LayoutParams(1081, 1132));
        this.dfdvkcfngr.setPadding(157, 114, 43, 150);
        linearLayout.addView(this.dfdvkcfngr);
        this.dfdvkcfngr.setBackgroundColor(Color.parseColor("#6eeda1"));
        TableLayout tableLayout7 = new TableLayout(this);
        this.aialtuzdcz = tableLayout7;
        tableLayout7.setLayoutParams(new LinearLayout.LayoutParams(114, 1739));
        this.aialtuzdcz.setPadding(139, 175, 195, 36);
        linearLayout.addView(this.aialtuzdcz);
        this.aialtuzdcz.setBackgroundColor(Color.parseColor("#b59eab"));
        ViewFlipper viewFlipper4 = new ViewFlipper(this);
        this.cicnukotai = viewFlipper4;
        viewFlipper4.setLayoutParams(new LinearLayout.LayoutParams(838, 1465));
        this.cicnukotai.setPadding(137, 133, 88, 57);
        linearLayout.addView(this.cicnukotai);
        this.cicnukotai.setBackgroundColor(Color.parseColor("#085beb"));
        DatePicker datePicker2 = new DatePicker(this);
        this.uvfxtvenkq = datePicker2;
        datePicker2.setLayoutParams(new LinearLayout.LayoutParams(472, 1135));
        this.uvfxtvenkq.setPadding(88, 157, 96, 66);
        linearLayout.addView(this.uvfxtvenkq);
        this.uvfxtvenkq.setBackgroundColor(Color.parseColor("#e3e038"));
        FrameLayout frameLayout5 = new FrameLayout(this);
        this.anauwvqkgo = frameLayout5;
        frameLayout5.setLayoutParams(new LinearLayout.LayoutParams(431, 115));
        this.anauwvqkgo.setPadding(89, 194, 45, 99);
        linearLayout.addView(this.anauwvqkgo);
        this.anauwvqkgo.setBackgroundColor(Color.parseColor("#6869f9"));
        TextView textView4 = new TextView(this);
        this.gbkzwmjwwr = textView4;
        textView4.setLayoutParams(new LinearLayout.LayoutParams(598, 1603));
        this.gbkzwmjwwr.setPadding(114, 177, 81, 55);
        linearLayout.addView(this.gbkzwmjwwr);
        this.gbkzwmjwwr.setBackgroundColor(Color.parseColor("#658d15"));
        TableLayout tableLayout8 = new TableLayout(this);
        this.ysvekkbpif = tableLayout8;
        tableLayout8.setLayoutParams(new LinearLayout.LayoutParams(1414, 1267));
        this.ysvekkbpif.setPadding(32, 112, 166, 76);
        linearLayout.addView(this.ysvekkbpif);
        this.ysvekkbpif.setBackgroundColor(Color.parseColor("#a12b32"));
        CheckBox checkBox4 = new CheckBox(this);
        this.utkckdwupn = checkBox4;
        checkBox4.setLayoutParams(new LinearLayout.LayoutParams(1917, 1964));
        this.utkckdwupn.setPadding(90, 169, 83, 150);
        linearLayout.addView(this.utkckdwupn);
        this.utkckdwupn.setBackgroundColor(Color.parseColor("#301856"));
        ScrollView scrollView6 = new ScrollView(this);
        this.txwyrrmiur = scrollView6;
        scrollView6.setLayoutParams(new LinearLayout.LayoutParams(816, 1082));
        this.txwyrrmiur.setPadding(135, 123, 50, 197);
        linearLayout.addView(this.txwyrrmiur);
        this.txwyrrmiur.setBackgroundColor(Color.parseColor("#c7c50b"));
        Spinner spinner5 = new Spinner(this);
        this.satsetyupk = spinner5;
        spinner5.setLayoutParams(new LinearLayout.LayoutParams(1635, 1193));
        this.satsetyupk.setPadding(55, 150, 86, 53);
        linearLayout.addView(this.satsetyupk);
        this.satsetyupk.setBackgroundColor(Color.parseColor("#38d2ad"));
        RatingBar ratingBar4 = new RatingBar(this);
        this.jfptprhest = ratingBar4;
        ratingBar4.setLayoutParams(new LinearLayout.LayoutParams(1649, 1012));
        this.jfptprhest.setPadding(173, 17, 178, 25);
        linearLayout.addView(this.jfptprhest);
        this.jfptprhest.setBackgroundColor(Color.parseColor("#1fc699"));
        RadioButton radioButton8 = new RadioButton(this);
        this.elkvdmrwco = radioButton8;
        radioButton8.setLayoutParams(new LinearLayout.LayoutParams(1631, 1220));
        this.elkvdmrwco.setPadding(180, 186, 12, 52);
        linearLayout.addView(this.elkvdmrwco);
        this.elkvdmrwco.setBackgroundColor(Color.parseColor("#e2e95b"));
        ViewFlipper viewFlipper5 = new ViewFlipper(this);
        this.rppfqbuagg = viewFlipper5;
        viewFlipper5.setLayoutParams(new LinearLayout.LayoutParams(1826, 200));
        this.rppfqbuagg.setPadding(16, 49, 80, 5);
        linearLayout.addView(this.rppfqbuagg);
        this.rppfqbuagg.setBackgroundColor(Color.parseColor("#b0559a"));
        FrameLayout frameLayout6 = new FrameLayout(this);
        this.uihhvntbnd = frameLayout6;
        frameLayout6.setLayoutParams(new LinearLayout.LayoutParams(1929, 1870));
        this.uihhvntbnd.setPadding(52, 122, 33, 21);
        linearLayout.addView(this.uihhvntbnd);
        this.uihhvntbnd.setBackgroundColor(Color.parseColor("#cba1c6"));
        ImageView imageView5 = new ImageView(this);
        this.qnkocvodac = imageView5;
        imageView5.setLayoutParams(new LinearLayout.LayoutParams(1324, 1574));
        this.qnkocvodac.setPadding(137, 165, 146, 183);
        linearLayout.addView(this.qnkocvodac);
        this.qnkocvodac.setBackgroundColor(Color.parseColor("#76bc24"));
        CheckBox checkBox5 = new CheckBox(this);
        this.bzxdesqsfi = checkBox5;
        checkBox5.setLayoutParams(new LinearLayout.LayoutParams(11, 1973));
        this.bzxdesqsfi.setPadding(55, 76, 34, 44);
        linearLayout.addView(this.bzxdesqsfi);
        this.bzxdesqsfi.setBackgroundColor(Color.parseColor("#9813b2"));
        CheckBox checkBox6 = new CheckBox(this);
        this.qyhoggkqed = checkBox6;
        checkBox6.setLayoutParams(new LinearLayout.LayoutParams(75, TypedValues.Custom.TYPE_COLOR));
        this.qyhoggkqed.setPadding(45, 72, 53, 9);
        linearLayout.addView(this.qyhoggkqed);
        this.qyhoggkqed.setBackgroundColor(Color.parseColor("#bce313"));
        ToggleButton toggleButton2 = new ToggleButton(this);
        this.evnwxesvcc = toggleButton2;
        toggleButton2.setLayoutParams(new LinearLayout.LayoutParams(1875, 833));
        this.evnwxesvcc.setPadding(99, 40, 31, 63);
        linearLayout.addView(this.evnwxesvcc);
        this.evnwxesvcc.setBackgroundColor(Color.parseColor("#04e523"));
        ToggleButton toggleButton3 = new ToggleButton(this);
        this.viqcnxivcb = toggleButton3;
        toggleButton3.setLayoutParams(new LinearLayout.LayoutParams(1997, 1005));
        this.viqcnxivcb.setPadding(47, 168, 27, 94);
        linearLayout.addView(this.viqcnxivcb);
        this.viqcnxivcb.setBackgroundColor(Color.parseColor("#5aac2d"));
        TextView textView5 = new TextView(this);
        this.fjypsgllmt = textView5;
        textView5.setLayoutParams(new LinearLayout.LayoutParams(1599, 561));
        this.fjypsgllmt.setPadding(189, 10, 154, 165);
        linearLayout.addView(this.fjypsgllmt);
        this.fjypsgllmt.setBackgroundColor(Color.parseColor("#945b0e"));
        ViewFlipper viewFlipper6 = new ViewFlipper(this);
        this.nvgukspfnr = viewFlipper6;
        viewFlipper6.setLayoutParams(new LinearLayout.LayoutParams(1200, 762));
        this.nvgukspfnr.setPadding(144, 11, 111, 17);
        linearLayout.addView(this.nvgukspfnr);
        this.nvgukspfnr.setBackgroundColor(Color.parseColor("#a9feee"));
        LinearLayout linearLayout11 = new LinearLayout(this);
        this.nmvquskfyf = linearLayout11;
        linearLayout11.setLayoutParams(new LinearLayout.LayoutParams(1039, 1041));
        this.nmvquskfyf.setPadding(14, 93, 6, 97);
        linearLayout.addView(this.nmvquskfyf);
        this.nmvquskfyf.setBackgroundColor(Color.parseColor("#691874"));
        CheckBox checkBox7 = new CheckBox(this);
        this.eduvyjrows = checkBox7;
        checkBox7.setLayoutParams(new LinearLayout.LayoutParams(584, 1619));
        this.eduvyjrows.setPadding(80, 36, 100, 156);
        linearLayout.addView(this.eduvyjrows);
        this.eduvyjrows.setBackgroundColor(Color.parseColor("#32d028"));
        ListView listView3 = new ListView(this);
        this.rjyrizsans = listView3;
        listView3.setLayoutParams(new LinearLayout.LayoutParams(1352, 309));
        this.rjyrizsans.setPadding(71, 23, 57, 31);
        linearLayout.addView(this.rjyrizsans);
        this.rjyrizsans.setBackgroundColor(Color.parseColor("#788ef9"));
        ListView listView4 = new ListView(this);
        this.zvhhyxxcdz = listView4;
        listView4.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.Custom.TYPE_STRING, 988));
        this.zvhhyxxcdz.setPadding(42, 38, 34, 53);
        linearLayout.addView(this.zvhhyxxcdz);
        this.zvhhyxxcdz.setBackgroundColor(Color.parseColor("#03b45a"));
        RelativeLayout relativeLayout4 = new RelativeLayout(this);
        this.kegglnlyxr = relativeLayout4;
        relativeLayout4.setLayoutParams(new LinearLayout.LayoutParams(396, 1149));
        this.kegglnlyxr.setPadding(37, 58, 115, 116);
        linearLayout.addView(this.kegglnlyxr);
        this.kegglnlyxr.setBackgroundColor(Color.parseColor("#08b151"));
        Button button8 = new Button(this);
        this.scanowlhpv = button8;
        button8.setLayoutParams(new LinearLayout.LayoutParams(355, 847));
        this.scanowlhpv.setPadding(140, 182, 97, BDLocation.TypeNetWorkLocation);
        linearLayout.addView(this.scanowlhpv);
        this.scanowlhpv.setBackgroundColor(Color.parseColor("#7d7986"));
        FrameLayout frameLayout7 = new FrameLayout(this);
        this.uystzzrnhv = frameLayout7;
        frameLayout7.setLayoutParams(new LinearLayout.LayoutParams(1844, 274));
        this.uystzzrnhv.setPadding(22, 176, 37, 1);
        linearLayout.addView(this.uystzzrnhv);
        this.uystzzrnhv.setBackgroundColor(Color.parseColor("#50b3cc"));
        ListView listView5 = new ListView(this);
        this.kwvmqboqvg = listView5;
        listView5.setLayoutParams(new LinearLayout.LayoutParams(869, 1619));
        this.kwvmqboqvg.setPadding(150, 187, 60, 100);
        linearLayout.addView(this.kwvmqboqvg);
        this.kwvmqboqvg.setBackgroundColor(Color.parseColor("#7ff6a4"));
        Switch r22 = new Switch(this);
        this.lqzomrzwip = r22;
        r22.setLayoutParams(new LinearLayout.LayoutParams(742, 1607));
        this.lqzomrzwip.setPadding(170, 13, PictureConfig.CHOOSE_REQUEST, 191);
        linearLayout.addView(this.lqzomrzwip);
        this.lqzomrzwip.setBackgroundColor(Color.parseColor("#b88c36"));
        CheckBox checkBox8 = new CheckBox(this);
        this.sqnjmaxwzb = checkBox8;
        checkBox8.setLayoutParams(new LinearLayout.LayoutParams(1685, 248));
        this.sqnjmaxwzb.setPadding(159, 0, 152, 77);
        linearLayout.addView(this.sqnjmaxwzb);
        this.sqnjmaxwzb.setBackgroundColor(Color.parseColor("#1888e3"));
        ProgressBar progressBar6 = new ProgressBar(this);
        this.wxytgdmciz = progressBar6;
        progressBar6.setLayoutParams(new LinearLayout.LayoutParams(176, 1352));
        this.wxytgdmciz.setPadding(116, 103, 84, 35);
        linearLayout.addView(this.wxytgdmciz);
        this.wxytgdmciz.setBackgroundColor(Color.parseColor("#8212dc"));
        Switch r23 = new Switch(this);
        this.onvkfunhtp = r23;
        r23.setLayoutParams(new LinearLayout.LayoutParams(47, 1512));
        this.onvkfunhtp.setPadding(187, 152, 147, 190);
        linearLayout.addView(this.onvkfunhtp);
        this.onvkfunhtp.setBackgroundColor(Color.parseColor("#8dc318"));
        DatePicker datePicker3 = new DatePicker(this);
        this.rzgcmwbobr = datePicker3;
        datePicker3.setLayoutParams(new LinearLayout.LayoutParams(1676, 1628));
        this.rzgcmwbobr.setPadding(32, 64, 13, 73);
        linearLayout.addView(this.rzgcmwbobr);
        this.rzgcmwbobr.setBackgroundColor(Color.parseColor("#361307"));
        CheckBox checkBox9 = new CheckBox(this);
        this.srvwighdpn = checkBox9;
        checkBox9.setLayoutParams(new LinearLayout.LayoutParams(754, 1398));
        this.srvwighdpn.setPadding(176, 111, 31, BDLocation.TypeCoarseLocation);
        linearLayout.addView(this.srvwighdpn);
        this.srvwighdpn.setBackgroundColor(Color.parseColor("#ac68b9"));
        ImageView imageView6 = new ImageView(this);
        this.jiwlbfgqlw = imageView6;
        imageView6.setLayoutParams(new LinearLayout.LayoutParams(873, 100));
        this.jiwlbfgqlw.setPadding(3, 169, 82, 164);
        linearLayout.addView(this.jiwlbfgqlw);
        this.jiwlbfgqlw.setBackgroundColor(Color.parseColor("#5e70b9"));
        CheckBox checkBox10 = new CheckBox(this);
        this.usppkzgayt = checkBox10;
        checkBox10.setLayoutParams(new LinearLayout.LayoutParams(492, 1072));
        this.usppkzgayt.setPadding(157, 22, 21, 17);
        linearLayout.addView(this.usppkzgayt);
        this.usppkzgayt.setBackgroundColor(Color.parseColor("#93193e"));
        ListView listView6 = new ListView(this);
        this.edysooqaai = listView6;
        listView6.setLayoutParams(new LinearLayout.LayoutParams(121, 1596));
        this.edysooqaai.setPadding(87, 63, 174, 99);
        linearLayout.addView(this.edysooqaai);
        this.edysooqaai.setBackgroundColor(Color.parseColor("#b67927"));
        ViewFlipper viewFlipper7 = new ViewFlipper(this);
        this.liwttuxnjt = viewFlipper7;
        viewFlipper7.setLayoutParams(new LinearLayout.LayoutParams(1312, TypedValues.TransitionType.TYPE_AUTO_TRANSITION));
        this.liwttuxnjt.setPadding(51, 189, 58, 153);
        linearLayout.addView(this.liwttuxnjt);
        this.liwttuxnjt.setBackgroundColor(Color.parseColor("#a4e9a9"));
        Button button9 = new Button(this);
        this.aysmdtqvsg = button9;
        button9.setLayoutParams(new LinearLayout.LayoutParams(1135, 952));
        this.aysmdtqvsg.setPadding(84, 120, 150, 11);
        linearLayout.addView(this.aysmdtqvsg);
        this.aysmdtqvsg.setBackgroundColor(Color.parseColor("#122897"));
        ProgressBar progressBar7 = new ProgressBar(this);
        this.mmyrbovorz = progressBar7;
        progressBar7.setLayoutParams(new LinearLayout.LayoutParams(320, 1125));
        this.mmyrbovorz.setPadding(60, 97, 142, 23);
        linearLayout.addView(this.mmyrbovorz);
        this.mmyrbovorz.setBackgroundColor(Color.parseColor("#0836c5"));
        ImageView imageView7 = new ImageView(this);
        this.bbfhcydage = imageView7;
        imageView7.setLayoutParams(new LinearLayout.LayoutParams(1085, 1559));
        this.bbfhcydage.setPadding(64, 173, 130, 75);
        linearLayout.addView(this.bbfhcydage);
        this.bbfhcydage.setBackgroundColor(Color.parseColor("#66ca9b"));
        GridView gridView6 = new GridView(this);
        this.qivsnwmyjq = gridView6;
        gridView6.setLayoutParams(new LinearLayout.LayoutParams(1876, 1469));
        this.qivsnwmyjq.setPadding(7, 199, 72, 127);
        linearLayout.addView(this.qivsnwmyjq);
        this.qivsnwmyjq.setBackgroundColor(Color.parseColor("#6e78c3"));
        EditText editText4 = new EditText(this);
        this.mtudlbdgbd = editText4;
        editText4.setLayoutParams(new LinearLayout.LayoutParams(1820, 1315));
        this.mtudlbdgbd.setPadding(65, BDLocation.TypeNetWorkLocation, 116, 137);
        linearLayout.addView(this.mtudlbdgbd);
        this.mtudlbdgbd.setBackgroundColor(Color.parseColor("#157ece"));
        TableLayout tableLayout9 = new TableLayout(this);
        this.utyowpetdy = tableLayout9;
        tableLayout9.setLayoutParams(new LinearLayout.LayoutParams(1138, 1934));
        this.utyowpetdy.setPadding(83, 78, 148, 21);
        linearLayout.addView(this.utyowpetdy);
        this.utyowpetdy.setBackgroundColor(Color.parseColor("#7c9f98"));
        RadioButton radioButton9 = new RadioButton(this);
        this.ekmgobwqlc = radioButton9;
        radioButton9.setLayoutParams(new LinearLayout.LayoutParams(405, 1005));
        this.ekmgobwqlc.setPadding(62, 63, 32, 48);
        linearLayout.addView(this.ekmgobwqlc);
        this.ekmgobwqlc.setBackgroundColor(Color.parseColor("#deffc5"));
        RadioButton radioButton10 = new RadioButton(this);
        this.necghzaoei = radioButton10;
        radioButton10.setLayoutParams(new LinearLayout.LayoutParams(692, 854));
        this.necghzaoei.setPadding(23, 96, 15, 73);
        linearLayout.addView(this.necghzaoei);
        this.necghzaoei.setBackgroundColor(Color.parseColor("#d67862"));
        ImageView imageView8 = new ImageView(this);
        this.cblswgkrco = imageView8;
        imageView8.setLayoutParams(new LinearLayout.LayoutParams(256, 883));
        this.cblswgkrco.setPadding(34, 38, 99, 117);
        linearLayout.addView(this.cblswgkrco);
        this.cblswgkrco.setBackgroundColor(Color.parseColor("#7091c4"));
        FrameLayout frameLayout8 = new FrameLayout(this);
        this.fqupkvwthi = frameLayout8;
        frameLayout8.setLayoutParams(new LinearLayout.LayoutParams(566, 513));
        this.fqupkvwthi.setPadding(105, 23, 118, 196);
        linearLayout.addView(this.fqupkvwthi);
        this.fqupkvwthi.setBackgroundColor(Color.parseColor("#b684a2"));
    }
}
