package com.smartapp.b.evvwvegpbt;

import android.app.Activity;
import android.graphics.Color;
import android.os.Bundle;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.CheckBox;
import android.widget.DatePicker;
import android.widget.EditText;
import android.widget.FrameLayout;
import android.widget.GridView;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ListView;
import android.widget.ProgressBar;
import android.widget.RadioButton;
import android.widget.RatingBar;
import android.widget.RelativeLayout;
import android.widget.ScrollView;
import android.widget.SeekBar;
import android.widget.Spinner;
import android.widget.Switch;
import android.widget.TableLayout;
import android.widget.TextView;
import android.widget.TimePicker;
import android.widget.ToggleButton;
import android.widget.ViewFlipper;
import androidx.constraintlayout.core.motion.utils.TypedValues;
import androidx.core.view.PointerIconCompat;
import com.baidu.location.BDLocation;
import com.google.android.gms.common.ConnectionResult;
import com.luck.picture.lib.config.PictureConfig;
import com.realsil.sdk.audioconnect.localplayback.LocalPlaybackConstants;
import com.realsil.sdk.bbpro.core.protocol.Contract;
import com.realsil.sdk.core.bluetooth.connection.le.GattClient;
import com.realsil.sdk.core.bluetooth.impl.BluetoothClassImpl;
import okhttp3.internal.ws.WebSocketProtocol;

/* loaded from: classes3.dex */
public class ZfwqmkvaaucActivity extends Activity {
    TableLayout adrhzguelm;
    Button adungrscev;
    RelativeLayout aidbpkrike;
    ProgressBar alghqphvrb;
    Switch amfkszqwkb;
    DatePicker arjlrxmuxq;
    ImageView ashdeqkgln;
    ProgressBar awcoskwnbb;
    RadioButton azbhxxvccg;
    SeekBar bajruaftdd;
    DatePicker bavmxvczfk;
    ListView bcltrcqpwi;
    TimePicker bcxutcxpjk;
    ToggleButton birbocinjs;
    GridView bqrwcgjqzd;
    ListView brptwzaufa;
    GridView btpbffwxbg;
    TableLayout bubpreeuyd;
    ListView bwxyrxbmul;
    RelativeLayout bxfrkozxfv;
    RelativeLayout bxvpothrhm;
    TableLayout byxcieverz;
    Button bzmgepoiuy;
    RatingBar cafhymsfxm;
    ViewFlipper catlutmfej;
    RelativeLayout cbjhmnibbe;
    RelativeLayout cflzjkvyab;
    ListView chgnmmwgzo;
    ScrollView ciquuyqabc;
    TimePicker ckzykjltzf;
    ScrollView clhoistpht;
    ToggleButton cqhdlqhejs;
    ProgressBar cqycrmfhjc;
    CheckBox cutbicwxlk;
    ScrollView cvsmfrzhws;
    ScrollView cwtaudkcdw;
    ListView cwuvfcrxcp;
    ImageView cxtdnhfwax;
    ViewFlipper czoroewfur;
    RatingBar dahdbnfnfl;
    ProgressBar dbepcsohag;
    ToggleButton dcgasyzjeh;
    ListView dclpxgpaza;
    ProgressBar deeddippar;
    RelativeLayout dfebjyvita;
    ToggleButton dkmrjgfbck;
    ListView dmckwfydty;
    SeekBar dqhntjvmtv;
    ToggleButton dvhuvevhda;
    EditText dwezmeaexm;
    GridView dwjbkpkope;
    EditText dxishhcmdf;
    ListView dxqvtfndep;
    TimePicker dyevqhozqa;
    Spinner dzlbvqbbey;
    GridView edtdgwprke;
    DatePicker eeiblrgxbn;
    LinearLayout effesezcby;
    TextView epvsumgsrh;
    FrameLayout eqxsomyvvh;
    DatePicker erthlxudtg;
    TimePicker etogpecuod;
    TimePicker exvglzuiqc;
    FrameLayout fawgiwrqnr;
    FrameLayout fdrqfafbxz;
    SeekBar ffejshqpjw;
    TimePicker ffncqobhiy;
    ListView fjhplgrogt;
    RatingBar fkqxzztjwv;
    ViewFlipper fnzdzleqpv;
    FrameLayout fraseewsac;
    Spinner fudcymkltv;
    LinearLayout fvmmzmdlus;
    RelativeLayout fzqmfqmaix;
    Button gbjnpuvyjw;
    Spinner gcdofvwmih;
    ProgressBar gcnysclgoz;
    RadioButton gcqofgbsda;
    EditText ghaxutouwa;
    RatingBar ghqyruoslv;
    TextView gitilwfbec;
    RadioButton glakhdevkl;
    Switch gqzodpjvao;
    LinearLayout gviuukumuw;
    FrameLayout gvneqwgekx;
    FrameLayout gvwkehobyj;
    EditText gwijdnmlfw;
    ViewFlipper gypqerolmc;
    Button hgafdkfwto;
    TimePicker htcziaonnw;
    TextView htspjhlsue;
    SeekBar hykbcttdjc;
    TableLayout hzfqomqggq;
    GridView hzygywxtgx;
    ListView ibfahfznim;
    TimePicker ieyyukxerv;
    ViewFlipper igjnfcyala;
    TextView ihxmilluhz;
    ViewFlipper ijotqpzdwl;
    ViewFlipper iodhqovewr;
    TableLayout ioevrhzhrj;
    DatePicker iqsicjbxtq;
    ImageView jfiupxqicg;
    TextView jjeaaywnqa;
    ImageView jjpbchkxex;
    SeekBar jnpbgnwrof;
    TableLayout jqljwhptjr;
    ImageView jqmsbzwllg;
    Button jtejhnmtsd;
    DatePicker jwwcmjhqyu;
    DatePicker kbnhjvqaoe;
    ToggleButton kbuqzndjww;
    Spinner kecexvmlpl;
    CheckBox keozsonfrp;
    FrameLayout keylssipqb;
    DatePicker khynguycsd;
    RelativeLayout kjpizgtrzy;
    GridView kjsbcdrzor;
    RatingBar kkdnagyqee;
    LinearLayout kpyccwhuzb;
    DatePicker kqqafgizgv;
    FrameLayout kzwrqignzu;
    SeekBar kzxuefbizk;
    FrameLayout lnvnnmengh;
    CheckBox losjoffeif;
    Spinner lrsnvjyfyu;
    ListView lygmeqiksv;
    EditText maymnmvara;
    DatePicker mcwsnhsbbp;
    DatePicker mhizfuiubx;
    RadioButton mkxmhwriic;
    RatingBar mlmvizfmdj;
    ViewFlipper mnlaiydlpi;
    TableLayout mnzfqnkhxf;
    ProgressBar mosartmcrm;
    GridView mtsrpntzfx;
    CheckBox mvxbnbwyfr;
    ViewFlipper mvyzyuhspz;
    TimePicker mwdjqzzron;
    TextView mxfficnrsc;
    TextView mxocwtkiqw;
    DatePicker myddmxmzis;
    GridView mzgjrsxovw;
    ImageView nagcydduky;
    ScrollView nahalvmcmm;
    CheckBox neypezuudl;
    DatePicker nfsrzutmfy;
    ListView ngupbzvtfv;
    FrameLayout ntdmiejggg;
    RadioButton ntpodackcn;
    ImageView nwoutazdwh;
    Spinner nxcgfegewu;
    DatePicker nzaxuuujco;
    Button nzgdinogyp;
    EditText oilicaljpo;
    TimePicker okdqbtadgp;
    ImageView opcnwqgbpa;
    RatingBar oqiqvwxrxj;
    ListView oresgmmyri;
    RatingBar ouqkpsoojh;
    SeekBar owdwpbyfds;
    CheckBox oydzduyzji;
    TextView pdgsnldtot;
    GridView pedswkjdeh;
    LinearLayout phlesostpr;
    ToggleButton pnszuwalzt;
    RadioButton pnwpzwhqcn;
    FrameLayout pphkwsfxec;
    RatingBar ptcqliqbmv;
    TimePicker ptncirbmul;
    ViewFlipper ptoflgropf;
    DatePicker pvvbpmeekz;
    ToggleButton pwvmfxvdnw;
    RelativeLayout pythlrxmgx;
    DatePicker pyulkgxxsj;
    ListView pzdbbwwntn;
    ImageView pzkxqrvjok;
    CheckBox qcizcduftd;
    Switch qgmmvmmgyn;
    LinearLayout qiclyskdwx;
    ImageView qtwunjpnfu;
    Spinner rcezbpkftp;
    Spinner rdfozonqcg;
    RatingBar reqbxbyrko;
    RadioButton rgbbueegqh;
    ToggleButton rmszxfpmci;
    TableLayout rptslivupw;
    RadioButton rsonqqzwcx;
    ViewFlipper rydvorvlme;
    EditText ryutukyjwl;
    ViewFlipper sbapalxrmx;
    RelativeLayout scieoeopif;
    SeekBar sddjeueaku;
    Switch sdgzaodcen;
    ListView spubkwmrho;
    ProgressBar swbsvxjmmw;
    LinearLayout syppbuxuoi;
    ListView thijxrvxsr;
    EditText thpkagztlo;
    ToggleButton tikdiaqvcd;
    TextView tkqeabxsiu;
    SeekBar tnmuvazdsh;
    RatingBar tvmbrveeqm;
    LinearLayout tyaozjjiil;
    ToggleButton ucgdcyovpy;
    FrameLayout udvhuljcus;
    FrameLayout uggsaognuy;
    RadioButton umsvopmxqc;
    RadioButton uojbugswgs;
    TableLayout uozbuvpayw;
    LinearLayout upeudaqpja;
    RadioButton urzcfsrfao;
    TimePicker usepiodjbn;
    GridView usmogbrsqs;
    TimePicker uxraelrkjd;
    FrameLayout uyedbdymxh;
    ViewFlipper vblooracjz;
    TextView vcasqfjymd;
    ScrollView vccwofvsic;
    ScrollView vcveqotwiw;
    ProgressBar vfkmsjzlax;
    TextView vhofzgfpoi;
    LinearLayout vhxjyxzbua;
    RatingBar vlrsfbyunb;
    FrameLayout vptnfnutwm;
    TimePicker vqikzpyhcf;
    LinearLayout vseblnrjpw;
    ViewFlipper vyiwsmkxje;
    ToggleButton wafqxmfidd;
    ToggleButton waiswsaswo;
    RadioButton wassifabtn;
    Spinner wlsqtpbzzo;
    Switch wqeekdvppy;
    Spinner wznzuefoql;
    SeekBar xgsusprgfc;
    SeekBar xkbitfzwia;
    Switch xniesjotld;
    GridView xrbutannrg;
    Spinner xvagunzdnn;
    TableLayout xzfgdqwfah;
    RadioButton yecsscjfvd;
    FrameLayout ygyihueddx;
    ProgressBar ymfvrzhggr;
    FrameLayout ynhtjigrnf;
    ProgressBar yqimluzmkc;
    Button yvbekgxrtk;
    LinearLayout zarxtslkqh;
    Switch zeausgkkay;
    LinearLayout zfxwyjfvrg;
    GridView ziagfeijow;
    DatePicker zjmwrzifvn;
    LinearLayout znljhzwbkk;
    ScrollView zpxzgzntlj;
    LinearLayout zrmfraymnk;
    ProgressBar zrnvsvxref;
    TableLayout zsdpoxwbem;
    ViewFlipper zvfwiydagn;
    TextView zxgrbxxpzj;
    GridView zybhclfnwy;

    @Override // android.app.Activity
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        LinearLayout linearLayout = new LinearLayout(this);
        setContentView(linearLayout);
        linearLayout.setLayoutParams(new ViewGroup.LayoutParams(-1, -1));
        linearLayout.setOrientation(1);
        linearLayout.setBackgroundColor(Color.parseColor("#ad97b5"));
        RatingBar ratingBar = new RatingBar(this);
        this.mlmvizfmdj = ratingBar;
        ratingBar.setLayoutParams(new LinearLayout.LayoutParams(1495, 1212));
        this.mlmvizfmdj.setPadding(4, 64, 76, 42);
        linearLayout.addView(this.mlmvizfmdj);
        this.mlmvizfmdj.setBackgroundColor(Color.parseColor("#66fca4"));
        ImageView imageView = new ImageView(this);
        this.nagcydduky = imageView;
        imageView.setLayoutParams(new LinearLayout.LayoutParams(801, 1491));
        this.nagcydduky.setPadding(112, 54, 171, 176);
        linearLayout.addView(this.nagcydduky);
        this.nagcydduky.setBackgroundColor(Color.parseColor("#dffe4b"));
        TimePicker timePicker = new TimePicker(this);
        this.ptncirbmul = timePicker;
        timePicker.setLayoutParams(new LinearLayout.LayoutParams(1560, 1779));
        this.ptncirbmul.setPadding(22, 54, 156, 128);
        linearLayout.addView(this.ptncirbmul);
        this.ptncirbmul.setBackground(new Cvgddlbgwlg());
        Spinner spinner = new Spinner(this);
        this.kecexvmlpl = spinner;
        spinner.setLayoutParams(new LinearLayout.LayoutParams(1991, 1089));
        this.kecexvmlpl.setPadding(35, 134, 91, 43);
        linearLayout.addView(this.kecexvmlpl);
        this.kecexvmlpl.setBackgroundColor(Color.parseColor("#98ec6c"));
        SeekBar seekBar = new SeekBar(this);
        this.tnmuvazdsh = seekBar;
        seekBar.setLayoutParams(new LinearLayout.LayoutParams(1097, 54));
        this.tnmuvazdsh.setPadding(179, 56, 58, 119);
        linearLayout.addView(this.tnmuvazdsh);
        this.tnmuvazdsh.setBackgroundColor(Color.parseColor("#228384"));
        FrameLayout frameLayout = new FrameLayout(this);
        this.ntdmiejggg = frameLayout;
        frameLayout.setLayoutParams(new LinearLayout.LayoutParams(505, 20));
        this.ntdmiejggg.setPadding(117, 195, 6, 84);
        linearLayout.addView(this.ntdmiejggg);
        this.ntdmiejggg.setBackgroundColor(Color.parseColor("#21b893"));
        TableLayout tableLayout = new TableLayout(this);
        this.rptslivupw = tableLayout;
        tableLayout.setLayoutParams(new LinearLayout.LayoutParams(290, 1679));
        this.rptslivupw.setPadding(178, 39, 50, 88);
        linearLayout.addView(this.rptslivupw);
        this.rptslivupw.setBackgroundColor(Color.parseColor("#19903c"));
        ProgressBar progressBar = new ProgressBar(this);
        this.awcoskwnbb = progressBar;
        progressBar.setLayoutParams(new LinearLayout.LayoutParams(1047, 1286));
        this.awcoskwnbb.setPadding(29, 96, 141, 174);
        linearLayout.addView(this.awcoskwnbb);
        this.awcoskwnbb.setBackgroundColor(Color.parseColor("#68e46b"));
        GridView gridView = new GridView(this);
        this.zybhclfnwy = gridView;
        gridView.setLayoutParams(new LinearLayout.LayoutParams(133, 1317));
        this.zybhclfnwy.setPadding(139, 24, 69, 40);
        linearLayout.addView(this.zybhclfnwy);
        this.zybhclfnwy.setBackgroundColor(Color.parseColor("#8c46a4"));
        RadioButton radioButton = new RadioButton(this);
        this.yecsscjfvd = radioButton;
        radioButton.setLayoutParams(new LinearLayout.LayoutParams(1342, 1438));
        this.yecsscjfvd.setPadding(70, 145, 132, 41);
        linearLayout.addView(this.yecsscjfvd);
        this.yecsscjfvd.setBackgroundColor(Color.parseColor("#6c10b5"));
        ImageView imageView2 = new ImageView(this);
        this.qtwunjpnfu = imageView2;
        imageView2.setLayoutParams(new LinearLayout.LayoutParams(343, 1406));
        this.qtwunjpnfu.setPadding(175, 120, 150, 145);
        linearLayout.addView(this.qtwunjpnfu);
        this.qtwunjpnfu.setBackgroundColor(Color.parseColor("#b2b6fb"));
        ImageView imageView3 = new ImageView(this);
        this.nwoutazdwh = imageView3;
        imageView3.setLayoutParams(new LinearLayout.LayoutParams(855, 1284));
        this.nwoutazdwh.setPadding(47, 29, 155, 154);
        linearLayout.addView(this.nwoutazdwh);
        this.nwoutazdwh.setBackgroundColor(Color.parseColor("#6bbea9"));
        RelativeLayout relativeLayout = new RelativeLayout(this);
        this.cbjhmnibbe = relativeLayout;
        relativeLayout.setLayoutParams(new LinearLayout.LayoutParams(853, 1012));
        this.cbjhmnibbe.setPadding(153, 112, 128, 159);
        linearLayout.addView(this.cbjhmnibbe);
        this.cbjhmnibbe.setBackgroundColor(Color.parseColor("#9caf81"));
        Spinner spinner2 = new Spinner(this);
        this.lrsnvjyfyu = spinner2;
        spinner2.setLayoutParams(new LinearLayout.LayoutParams(1941, 1377));
        this.lrsnvjyfyu.setPadding(BDLocation.TypeServerError, 6, PictureConfig.CHOOSE_REQUEST, 51);
        linearLayout.addView(this.lrsnvjyfyu);
        this.lrsnvjyfyu.setBackgroundColor(Color.parseColor("#6bc14d"));
        GridView gridView2 = new GridView(this);
        this.mtsrpntzfx = gridView2;
        gridView2.setLayoutParams(new LinearLayout.LayoutParams(791, 1296));
        this.mtsrpntzfx.setPadding(158, 129, 42, 143);
        linearLayout.addView(this.mtsrpntzfx);
        this.mtsrpntzfx.setBackgroundColor(Color.parseColor("#b9ff4c"));
        ScrollView scrollView = new ScrollView(this);
        this.cwtaudkcdw = scrollView;
        scrollView.setLayoutParams(new LinearLayout.LayoutParams(1571, 1041));
        this.cwtaudkcdw.setPadding(119, 175, 170, 180);
        linearLayout.addView(this.cwtaudkcdw);
        this.cwtaudkcdw.setBackgroundColor(Color.parseColor("#75a0f3"));
        ImageView imageView4 = new ImageView(this);
        this.jqmsbzwllg = imageView4;
        imageView4.setLayoutParams(new LinearLayout.LayoutParams(109, 1920));
        this.jqmsbzwllg.setPadding(5, 49, 60, 129);
        linearLayout.addView(this.jqmsbzwllg);
        this.jqmsbzwllg.setBackgroundColor(Color.parseColor("#c24058"));
        TimePicker timePicker2 = new TimePicker(this);
        this.usepiodjbn = timePicker2;
        timePicker2.setLayoutParams(new LinearLayout.LayoutParams(969, 1697));
        this.usepiodjbn.setPadding(157, 149, 115, 182);
        linearLayout.addView(this.usepiodjbn);
        this.usepiodjbn.setBackgroundColor(Color.parseColor("#360a93"));
        TimePicker timePicker3 = new TimePicker(this);
        this.ckzykjltzf = timePicker3;
        timePicker3.setLayoutParams(new LinearLayout.LayoutParams(963, 1682));
        this.ckzykjltzf.setPadding(198, 142, 114, 46);
        linearLayout.addView(this.ckzykjltzf);
        this.ckzykjltzf.setBackgroundColor(Color.parseColor("#c0d3af"));
        FrameLayout frameLayout2 = new FrameLayout(this);
        this.keylssipqb = frameLayout2;
        frameLayout2.setLayoutParams(new LinearLayout.LayoutParams(1447, 785));
        this.keylssipqb.setPadding(111, 31, 54, 131);
        linearLayout.addView(this.keylssipqb);
        this.keylssipqb.setBackgroundColor(Color.parseColor("#49e4d6"));
        RatingBar ratingBar2 = new RatingBar(this);
        this.dahdbnfnfl = ratingBar2;
        ratingBar2.setLayoutParams(new LinearLayout.LayoutParams(1168, 1718));
        this.dahdbnfnfl.setPadding(30, 158, 86, 179);
        linearLayout.addView(this.dahdbnfnfl);
        this.dahdbnfnfl.setBackgroundColor(Color.parseColor("#4be272"));
        TimePicker timePicker4 = new TimePicker(this);
        this.vqikzpyhcf = timePicker4;
        timePicker4.setLayoutParams(new LinearLayout.LayoutParams(1287, 1332));
        this.vqikzpyhcf.setPadding(11, 46, 43, 32);
        linearLayout.addView(this.vqikzpyhcf);
        this.vqikzpyhcf.setBackgroundColor(Color.parseColor("#6409c7"));
        ViewFlipper viewFlipper = new ViewFlipper(this);
        this.iodhqovewr = viewFlipper;
        viewFlipper.setLayoutParams(new LinearLayout.LayoutParams(353, 1120));
        this.iodhqovewr.setPadding(176, 198, 177, 29);
        linearLayout.addView(this.iodhqovewr);
        this.iodhqovewr.setBackgroundColor(Color.parseColor("#ba4b75"));
        GridView gridView3 = new GridView(this);
        this.xrbutannrg = gridView3;
        gridView3.setLayoutParams(new LinearLayout.LayoutParams(526, 572));
        this.xrbutannrg.setPadding(76, 166, 64, 140);
        linearLayout.addView(this.xrbutannrg);
        this.xrbutannrg.setBackgroundColor(Color.parseColor("#a987e8"));
        ScrollView scrollView2 = new ScrollView(this);
        this.vccwofvsic = scrollView2;
        scrollView2.setLayoutParams(new LinearLayout.LayoutParams(482, 1748));
        this.vccwofvsic.setPadding(PictureConfig.CHOOSE_REQUEST, 128, 138, 139);
        linearLayout.addView(this.vccwofvsic);
        this.vccwofvsic.setBackgroundColor(Color.parseColor("#cbb171"));
        TimePicker timePicker5 = new TimePicker(this);
        this.mwdjqzzron = timePicker5;
        timePicker5.setLayoutParams(new LinearLayout.LayoutParams(1913, 1823));
        this.mwdjqzzron.setPadding(149, 131, 17, BDLocation.TypeServerError);
        linearLayout.addView(this.mwdjqzzron);
        this.mwdjqzzron.setBackgroundColor(Color.parseColor("#497b84"));
        ListView listView = new ListView(this);
        this.oresgmmyri = listView;
        listView.setLayoutParams(new LinearLayout.LayoutParams(1652, 682));
        this.oresgmmyri.setPadding(BDLocation.TypeServerDecryptError, 140, 76, 9);
        linearLayout.addView(this.oresgmmyri);
        this.oresgmmyri.setBackgroundColor(Color.parseColor("#09b4e1"));
        DatePicker datePicker = new DatePicker(this);
        this.erthlxudtg = datePicker;
        datePicker.setLayoutParams(new LinearLayout.LayoutParams(35, 1333));
        this.erthlxudtg.setPadding(94, 102, 102, 108);
        linearLayout.addView(this.erthlxudtg);
        this.erthlxudtg.setBackgroundColor(Color.parseColor("#5bb630"));
        RadioButton radioButton2 = new RadioButton(this);
        this.umsvopmxqc = radioButton2;
        radioButton2.setLayoutParams(new LinearLayout.LayoutParams(1206, 1896));
        this.umsvopmxqc.setPadding(198, 57, 139, 136);
        linearLayout.addView(this.umsvopmxqc);
        this.umsvopmxqc.setBackgroundColor(Color.parseColor("#d4db85"));
        SeekBar seekBar2 = new SeekBar(this);
        this.sddjeueaku = seekBar2;
        seekBar2.setLayoutParams(new LinearLayout.LayoutParams(380, 40));
        this.sddjeueaku.setPadding(22, 94, 56, 136);
        linearLayout.addView(this.sddjeueaku);
        this.sddjeueaku.setBackgroundColor(Color.parseColor("#547d95"));
        ListView listView2 = new ListView(this);
        this.lygmeqiksv = listView2;
        listView2.setLayoutParams(new LinearLayout.LayoutParams(1551, 1979));
        this.lygmeqiksv.setPadding(13, 193, 174, BDLocation.TypeServerError);
        linearLayout.addView(this.lygmeqiksv);
        this.lygmeqiksv.setBackgroundColor(Color.parseColor("#8bf7cf"));
        ViewFlipper viewFlipper2 = new ViewFlipper(this);
        this.zvfwiydagn = viewFlipper2;
        viewFlipper2.setLayoutParams(new LinearLayout.LayoutParams(LocalPlaybackConstants.BUFFER_A_CAN_USE_FLAG, 515));
        this.zvfwiydagn.setPadding(142, 8, 170, 113);
        linearLayout.addView(this.zvfwiydagn);
        this.zvfwiydagn.setBackgroundColor(Color.parseColor("#403032"));
        RatingBar ratingBar3 = new RatingBar(this);
        this.reqbxbyrko = ratingBar3;
        ratingBar3.setLayoutParams(new LinearLayout.LayoutParams(672, 1583));
        this.reqbxbyrko.setPadding(76, 113, 36, 181);
        linearLayout.addView(this.reqbxbyrko);
        this.reqbxbyrko.setBackgroundColor(Color.parseColor("#d63753"));
        FrameLayout frameLayout3 = new FrameLayout(this);
        this.vptnfnutwm = frameLayout3;
        frameLayout3.setLayoutParams(new LinearLayout.LayoutParams(586, 1028));
        this.vptnfnutwm.setPadding(74, 136, 51, 40);
        linearLayout.addView(this.vptnfnutwm);
        this.vptnfnutwm.setBackgroundColor(Color.parseColor("#8e0616"));
        ImageView imageView5 = new ImageView(this);
        this.ashdeqkgln = imageView5;
        imageView5.setLayoutParams(new LinearLayout.LayoutParams(1205, 1699));
        this.ashdeqkgln.setPadding(134, 78, 41, 109);
        linearLayout.addView(this.ashdeqkgln);
        this.ashdeqkgln.setBackgroundColor(Color.parseColor("#0670f3"));
        LinearLayout linearLayout2 = new LinearLayout(this);
        this.zfxwyjfvrg = linearLayout2;
        linearLayout2.setLayoutParams(new LinearLayout.LayoutParams(1446, 891));
        this.zfxwyjfvrg.setPadding(26, 183, 8, 152);
        linearLayout.addView(this.zfxwyjfvrg);
        this.zfxwyjfvrg.setBackgroundColor(Color.parseColor("#7f3ffd"));
        RadioButton radioButton3 = new RadioButton(this);
        this.uojbugswgs = radioButton3;
        radioButton3.setLayoutParams(new LinearLayout.LayoutParams(1459, 1063));
        this.uojbugswgs.setPadding(46, 154, 177, 25);
        linearLayout.addView(this.uojbugswgs);
        this.uojbugswgs.setBackgroundColor(Color.parseColor("#b9ce76"));
        RatingBar ratingBar4 = new RatingBar(this);
        this.ptcqliqbmv = ratingBar4;
        ratingBar4.setLayoutParams(new LinearLayout.LayoutParams(815, 170));
        this.ptcqliqbmv.setPadding(107, 83, 69, 141);
        linearLayout.addView(this.ptcqliqbmv);
        this.ptcqliqbmv.setBackgroundColor(Color.parseColor("#799f4f"));
        ListView listView3 = new ListView(this);
        this.dclpxgpaza = listView3;
        listView3.setLayoutParams(new LinearLayout.LayoutParams(698, 1213));
        this.dclpxgpaza.setPadding(103, 150, 179, 176);
        linearLayout.addView(this.dclpxgpaza);
        this.dclpxgpaza.setBackgroundColor(Color.parseColor("#de0819"));
        EditText editText = new EditText(this);
        this.oilicaljpo = editText;
        editText.setLayoutParams(new LinearLayout.LayoutParams(251, 1475));
        this.oilicaljpo.setPadding(58, 18, 132, 199);
        linearLayout.addView(this.oilicaljpo);
        this.oilicaljpo.setBackgroundColor(Color.parseColor("#0e558f"));
        RelativeLayout relativeLayout2 = new RelativeLayout(this);
        this.bxvpothrhm = relativeLayout2;
        relativeLayout2.setLayoutParams(new LinearLayout.LayoutParams(499, 268));
        this.bxvpothrhm.setPadding(154, 14, 70, 33);
        linearLayout.addView(this.bxvpothrhm);
        this.bxvpothrhm.setBackgroundColor(Color.parseColor("#620dd2"));
        CheckBox checkBox = new CheckBox(this);
        this.mvxbnbwyfr = checkBox;
        checkBox.setLayoutParams(new LinearLayout.LayoutParams(1095, 942));
        this.mvxbnbwyfr.setPadding(40, 121, 59, 181);
        linearLayout.addView(this.mvxbnbwyfr);
        this.mvxbnbwyfr.setBackgroundColor(Color.parseColor("#63de36"));
        ProgressBar progressBar2 = new ProgressBar(this);
        this.swbsvxjmmw = progressBar2;
        progressBar2.setLayoutParams(new LinearLayout.LayoutParams(BDLocation.TypeNetWorkLocation, 1513));
        this.swbsvxjmmw.setPadding(191, 33, 117, 78);
        linearLayout.addView(this.swbsvxjmmw);
        this.swbsvxjmmw.setBackgroundColor(Color.parseColor("#7628b9"));
        EditText editText2 = new EditText(this);
        this.ryutukyjwl = editText2;
        editText2.setLayoutParams(new LinearLayout.LayoutParams(77, 1056));
        this.ryutukyjwl.setPadding(149, 93, 1, 171);
        linearLayout.addView(this.ryutukyjwl);
        this.ryutukyjwl.setBackgroundColor(Color.parseColor("#45c915"));
        DatePicker datePicker2 = new DatePicker(this);
        this.pvvbpmeekz = datePicker2;
        datePicker2.setLayoutParams(new LinearLayout.LayoutParams(1811, 45));
        this.pvvbpmeekz.setPadding(89, 23, 109, 147);
        linearLayout.addView(this.pvvbpmeekz);
        this.pvvbpmeekz.setBackgroundColor(Color.parseColor("#0f50e9"));
        LinearLayout linearLayout3 = new LinearLayout(this);
        this.zrmfraymnk = linearLayout3;
        linearLayout3.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.MotionType.TYPE_ANIMATE_RELATIVE_TO, 1541));
        this.zrmfraymnk.setPadding(192, 57, 176, 53);
        linearLayout.addView(this.zrmfraymnk);
        this.zrmfraymnk.setBackgroundColor(Color.parseColor("#8618b3"));
        RadioButton radioButton4 = new RadioButton(this);
        this.gcqofgbsda = radioButton4;
        radioButton4.setLayoutParams(new LinearLayout.LayoutParams(303, 1747));
        this.gcqofgbsda.setPadding(189, 105, 52, 29);
        linearLayout.addView(this.gcqofgbsda);
        this.gcqofgbsda.setBackgroundColor(Color.parseColor("#485f91"));
        LinearLayout linearLayout4 = new LinearLayout(this);
        this.vhxjyxzbua = linearLayout4;
        linearLayout4.setLayoutParams(new LinearLayout.LayoutParams(1158, 872));
        this.vhxjyxzbua.setPadding(140, 24, 66, 194);
        linearLayout.addView(this.vhxjyxzbua);
        this.vhxjyxzbua.setBackgroundColor(Color.parseColor("#f93b26"));
        DatePicker datePicker3 = new DatePicker(this);
        this.mhizfuiubx = datePicker3;
        datePicker3.setLayoutParams(new LinearLayout.LayoutParams(1943, 1191));
        this.mhizfuiubx.setPadding(74, 181, 147, 196);
        linearLayout.addView(this.mhizfuiubx);
        this.mhizfuiubx.setBackgroundColor(Color.parseColor("#ee4d54"));
        GridView gridView4 = new GridView(this);
        this.btpbffwxbg = gridView4;
        gridView4.setLayoutParams(new LinearLayout.LayoutParams(621, 1510));
        this.btpbffwxbg.setPadding(123, 87, 31, 122);
        linearLayout.addView(this.btpbffwxbg);
        this.btpbffwxbg.setBackgroundColor(Color.parseColor("#33c8b1"));
        TimePicker timePicker6 = new TimePicker(this);
        this.bcxutcxpjk = timePicker6;
        timePicker6.setLayoutParams(new LinearLayout.LayoutParams(1526, 248));
        this.bcxutcxpjk.setPadding(152, 24, 124, 41);
        linearLayout.addView(this.bcxutcxpjk);
        this.bcxutcxpjk.setBackgroundColor(Color.parseColor("#b0af9d"));
        ProgressBar progressBar3 = new ProgressBar(this);
        this.alghqphvrb = progressBar3;
        progressBar3.setLayoutParams(new LinearLayout.LayoutParams(3, 176));
        this.alghqphvrb.setPadding(PictureConfig.CHOOSE_REQUEST, 86, 172, 145);
        linearLayout.addView(this.alghqphvrb);
        this.alghqphvrb.setBackgroundColor(Color.parseColor("#0ec918"));
        LinearLayout linearLayout5 = new LinearLayout(this);
        this.fvmmzmdlus = linearLayout5;
        linearLayout5.setLayoutParams(new LinearLayout.LayoutParams(1186, 1495));
        this.fvmmzmdlus.setPadding(52, 107, 19, 169);
        linearLayout.addView(this.fvmmzmdlus);
        this.fvmmzmdlus.setBackgroundColor(Color.parseColor("#e6827e"));
        TimePicker timePicker7 = new TimePicker(this);
        this.exvglzuiqc = timePicker7;
        timePicker7.setLayoutParams(new LinearLayout.LayoutParams(578, 70));
        this.exvglzuiqc.setPadding(32, 124, 195, 114);
        linearLayout.addView(this.exvglzuiqc);
        this.exvglzuiqc.setBackgroundColor(Color.parseColor("#6c0f0a"));
        LinearLayout linearLayout6 = new LinearLayout(this);
        this.tyaozjjiil = linearLayout6;
        linearLayout6.setLayoutParams(new LinearLayout.LayoutParams(1995, 519));
        this.tyaozjjiil.setPadding(57, 31, 143, 185);
        linearLayout.addView(this.tyaozjjiil);
        this.tyaozjjiil.setBackgroundColor(Color.parseColor("#af4a45"));
        DatePicker datePicker4 = new DatePicker(this);
        this.zjmwrzifvn = datePicker4;
        datePicker4.setLayoutParams(new LinearLayout.LayoutParams(687, 333));
        this.zjmwrzifvn.setPadding(79, 134, 185, 117);
        linearLayout.addView(this.zjmwrzifvn);
        this.zjmwrzifvn.setBackgroundColor(Color.parseColor("#7f1b9c"));
        EditText editText3 = new EditText(this);
        this.ghaxutouwa = editText3;
        editText3.setLayoutParams(new LinearLayout.LayoutParams(1113, 844));
        this.ghaxutouwa.setPadding(190, BDLocation.TypeNetWorkLocation, 192, 9);
        linearLayout.addView(this.ghaxutouwa);
        this.ghaxutouwa.setBackgroundColor(Color.parseColor("#b49763"));
        TableLayout tableLayout2 = new TableLayout(this);
        this.zsdpoxwbem = tableLayout2;
        tableLayout2.setLayoutParams(new LinearLayout.LayoutParams(1624, 522));
        this.zsdpoxwbem.setPadding(23, 73, 90, 11);
        linearLayout.addView(this.zsdpoxwbem);
        this.zsdpoxwbem.setBackgroundColor(Color.parseColor("#70b05a"));
        ViewFlipper viewFlipper3 = new ViewFlipper(this);
        this.vyiwsmkxje = viewFlipper3;
        viewFlipper3.setLayoutParams(new LinearLayout.LayoutParams(BluetoothClassImpl.Device.PERIPHERAL_NON_KEYBOARD_NON_POINTING, 748));
        this.vyiwsmkxje.setPadding(94, 159, 73, 74);
        linearLayout.addView(this.vyiwsmkxje);
        this.vyiwsmkxje.setBackgroundColor(Color.parseColor("#770ebd"));
        Switch r2 = new Switch(this);
        this.qgmmvmmgyn = r2;
        r2.setLayoutParams(new LinearLayout.LayoutParams(1157, 678));
        this.qgmmvmmgyn.setPadding(156, 172, 61, 62);
        linearLayout.addView(this.qgmmvmmgyn);
        this.qgmmvmmgyn.setBackgroundColor(Color.parseColor("#0c970a"));
        ScrollView scrollView3 = new ScrollView(this);
        this.ciquuyqabc = scrollView3;
        scrollView3.setLayoutParams(new LinearLayout.LayoutParams(733, 50));
        this.ciquuyqabc.setPadding(177, 106, 134, 192);
        linearLayout.addView(this.ciquuyqabc);
        this.ciquuyqabc.setBackgroundColor(Color.parseColor("#e095a3"));
        FrameLayout frameLayout4 = new FrameLayout(this);
        this.gvneqwgekx = frameLayout4;
        frameLayout4.setLayoutParams(new LinearLayout.LayoutParams(473, 361));
        this.gvneqwgekx.setPadding(71, 80, 100, BDLocation.TypeServerDecryptError);
        linearLayout.addView(this.gvneqwgekx);
        this.gvneqwgekx.setBackgroundColor(Color.parseColor("#05a043"));
        RatingBar ratingBar5 = new RatingBar(this);
        this.ghqyruoslv = ratingBar5;
        ratingBar5.setLayoutParams(new LinearLayout.LayoutParams(1768, 934));
        this.ghqyruoslv.setPadding(119, 83, 166, 33);
        linearLayout.addView(this.ghqyruoslv);
        this.ghqyruoslv.setBackgroundColor(Color.parseColor("#e176e0"));
        Switch r22 = new Switch(this);
        this.xniesjotld = r22;
        r22.setLayoutParams(new LinearLayout.LayoutParams(1841, 751));
        this.xniesjotld.setPadding(185, 72, 59, 30);
        linearLayout.addView(this.xniesjotld);
        this.xniesjotld.setBackgroundColor(Color.parseColor("#0976a4"));
        ToggleButton toggleButton = new ToggleButton(this);
        this.wafqxmfidd = toggleButton;
        toggleButton.setLayoutParams(new LinearLayout.LayoutParams(243, 1303));
        this.wafqxmfidd.setPadding(5, 103, 25, 100);
        linearLayout.addView(this.wafqxmfidd);
        this.wafqxmfidd.setBackgroundColor(Color.parseColor("#a4777d"));
        RelativeLayout relativeLayout3 = new RelativeLayout(this);
        this.kjpizgtrzy = relativeLayout3;
        relativeLayout3.setLayoutParams(new LinearLayout.LayoutParams(1891, 582));
        this.kjpizgtrzy.setPadding(47, 185, 8, 60);
        linearLayout.addView(this.kjpizgtrzy);
        this.kjpizgtrzy.setBackgroundColor(Color.parseColor("#4612aa"));
        RatingBar ratingBar6 = new RatingBar(this);
        this.vlrsfbyunb = ratingBar6;
        ratingBar6.setLayoutParams(new LinearLayout.LayoutParams(73, 1058));
        this.vlrsfbyunb.setPadding(20, 27, 137, 132);
        linearLayout.addView(this.vlrsfbyunb);
        this.vlrsfbyunb.setBackgroundColor(Color.parseColor("#10c6c9"));
        Switch r23 = new Switch(this);
        this.amfkszqwkb = r23;
        r23.setLayoutParams(new LinearLayout.LayoutParams(1775, 814));
        this.amfkszqwkb.setPadding(159, 172, 152, 173);
        linearLayout.addView(this.amfkszqwkb);
        this.amfkszqwkb.setBackgroundColor(Color.parseColor("#f22a9d"));
        Spinner spinner3 = new Spinner(this);
        this.dzlbvqbbey = spinner3;
        spinner3.setLayoutParams(new LinearLayout.LayoutParams(1535, PointerIconCompat.TYPE_TOP_RIGHT_DIAGONAL_DOUBLE_ARROW));
        this.dzlbvqbbey.setPadding(55, 33, 75, 155);
        linearLayout.addView(this.dzlbvqbbey);
        this.dzlbvqbbey.setBackgroundColor(Color.parseColor("#b130a0"));
        TimePicker timePicker8 = new TimePicker(this);
        this.okdqbtadgp = timePicker8;
        timePicker8.setLayoutParams(new LinearLayout.LayoutParams(1952, 1657));
        this.okdqbtadgp.setPadding(136, 80, WebSocketProtocol.PAYLOAD_SHORT, 199);
        linearLayout.addView(this.okdqbtadgp);
        this.okdqbtadgp.setBackgroundColor(Color.parseColor("#710da7"));
        CheckBox checkBox2 = new CheckBox(this);
        this.neypezuudl = checkBox2;
        checkBox2.setLayoutParams(new LinearLayout.LayoutParams(660, ConnectionResult.DRIVE_EXTERNAL_STORAGE_REQUIRED));
        this.neypezuudl.setPadding(187, 65, 173, 144);
        linearLayout.addView(this.neypezuudl);
        this.neypezuudl.setBackgroundColor(Color.parseColor("#614669"));
        GridView gridView5 = new GridView(this);
        this.edtdgwprke = gridView5;
        gridView5.setLayoutParams(new LinearLayout.LayoutParams(889, 249));
        this.edtdgwprke.setPadding(69, 57, 158, 40);
        linearLayout.addView(this.edtdgwprke);
        this.edtdgwprke.setBackgroundColor(Color.parseColor("#f60bff"));
        ToggleButton toggleButton2 = new ToggleButton(this);
        this.rmszxfpmci = toggleButton2;
        toggleButton2.setLayoutParams(new LinearLayout.LayoutParams(1555, 1843));
        this.rmszxfpmci.setPadding(152, 97, 57, 35);
        linearLayout.addView(this.rmszxfpmci);
        this.rmszxfpmci.setBackgroundColor(Color.parseColor("#c9f605"));
        ProgressBar progressBar4 = new ProgressBar(this);
        this.deeddippar = progressBar4;
        progressBar4.setLayoutParams(new LinearLayout.LayoutParams(1883, 1701));
        this.deeddippar.setPadding(33, 77, 149, 129);
        linearLayout.addView(this.deeddippar);
        this.deeddippar.setBackgroundColor(Color.parseColor("#bc8083"));
        ListView listView4 = new ListView(this);
        this.thijxrvxsr = listView4;
        listView4.setLayoutParams(new LinearLayout.LayoutParams(958, 1460));
        this.thijxrvxsr.setPadding(30, 143, 111, 164);
        linearLayout.addView(this.thijxrvxsr);
        this.thijxrvxsr.setBackgroundColor(Color.parseColor("#710343"));
        SeekBar seekBar3 = new SeekBar(this);
        this.jnpbgnwrof = seekBar3;
        seekBar3.setLayoutParams(new LinearLayout.LayoutParams(1516, 37));
        this.jnpbgnwrof.setPadding(154, 58, 89, 100);
        linearLayout.addView(this.jnpbgnwrof);
        this.jnpbgnwrof.setBackgroundColor(Color.parseColor("#ffb8b5"));
        TimePicker timePicker9 = new TimePicker(this);
        this.ffncqobhiy = timePicker9;
        timePicker9.setLayoutParams(new LinearLayout.LayoutParams(1748, 470));
        this.ffncqobhiy.setPadding(16, 138, 21, 79);
        linearLayout.addView(this.ffncqobhiy);
        this.ffncqobhiy.setBackgroundColor(Color.parseColor("#cc9f0b"));
        DatePicker datePicker5 = new DatePicker(this);
        this.eeiblrgxbn = datePicker5;
        datePicker5.setLayoutParams(new LinearLayout.LayoutParams(BluetoothClassImpl.Device.PERIPHERAL_POINTING, 1090));
        this.eeiblrgxbn.setPadding(144, 89, 150, 119);
        linearLayout.addView(this.eeiblrgxbn);
        this.eeiblrgxbn.setBackgroundColor(Color.parseColor("#a3e403"));
        RelativeLayout relativeLayout4 = new RelativeLayout(this);
        this.scieoeopif = relativeLayout4;
        relativeLayout4.setLayoutParams(new LinearLayout.LayoutParams(202, 1062));
        this.scieoeopif.setPadding(122, 38, 170, 195);
        linearLayout.addView(this.scieoeopif);
        this.scieoeopif.setBackgroundColor(Color.parseColor("#0a4851"));
        TextView textView = new TextView(this);
        this.ihxmilluhz = textView;
        textView.setLayoutParams(new LinearLayout.LayoutParams(1331, 632));
        this.ihxmilluhz.setPadding(150, 198, 37, 71);
        linearLayout.addView(this.ihxmilluhz);
        this.ihxmilluhz.setBackgroundColor(Color.parseColor("#8848d1"));
        ProgressBar progressBar5 = new ProgressBar(this);
        this.dbepcsohag = progressBar5;
        progressBar5.setLayoutParams(new LinearLayout.LayoutParams(1732, 1886));
        this.dbepcsohag.setPadding(109, 53, 37, BDLocation.TypeServerError);
        linearLayout.addView(this.dbepcsohag);
        this.dbepcsohag.setBackgroundColor(Color.parseColor("#c6caa6"));
        ProgressBar progressBar6 = new ProgressBar(this);
        this.gcnysclgoz = progressBar6;
        progressBar6.setLayoutParams(new LinearLayout.LayoutParams(1915, 1572));
        this.gcnysclgoz.setPadding(143, 127, 109, 70);
        linearLayout.addView(this.gcnysclgoz);
        this.gcnysclgoz.setBackgroundColor(Color.parseColor("#9eaa40"));
        ToggleButton toggleButton3 = new ToggleButton(this);
        this.dkmrjgfbck = toggleButton3;
        toggleButton3.setLayoutParams(new LinearLayout.LayoutParams(172, 399));
        this.dkmrjgfbck.setPadding(105, 63, 56, 197);
        linearLayout.addView(this.dkmrjgfbck);
        this.dkmrjgfbck.setBackgroundColor(Color.parseColor("#324ff0"));
        CheckBox checkBox3 = new CheckBox(this);
        this.cutbicwxlk = checkBox3;
        checkBox3.setLayoutParams(new LinearLayout.LayoutParams(1545, 1127));
        this.cutbicwxlk.setPadding(153, 41, 37, 14);
        linearLayout.addView(this.cutbicwxlk);
        this.cutbicwxlk.setBackgroundColor(Color.parseColor("#5f823d"));
        FrameLayout frameLayout5 = new FrameLayout(this);
        this.ynhtjigrnf = frameLayout5;
        frameLayout5.setLayoutParams(new LinearLayout.LayoutParams(24, 1289));
        this.ynhtjigrnf.setPadding(96, 19, 154, 168);
        linearLayout.addView(this.ynhtjigrnf);
        this.ynhtjigrnf.setBackgroundColor(Color.parseColor("#7824d1"));
        SeekBar seekBar4 = new SeekBar(this);
        this.dqhntjvmtv = seekBar4;
        seekBar4.setLayoutParams(new LinearLayout.LayoutParams(1720, 1825));
        this.dqhntjvmtv.setPadding(164, 23, 166, 77);
        linearLayout.addView(this.dqhntjvmtv);
        this.dqhntjvmtv.setBackgroundColor(Color.parseColor("#f8e884"));
        RatingBar ratingBar7 = new RatingBar(this);
        this.tvmbrveeqm = ratingBar7;
        ratingBar7.setLayoutParams(new LinearLayout.LayoutParams(134, 814));
        this.tvmbrveeqm.setPadding(136, 149, 55, 54);
        linearLayout.addView(this.tvmbrveeqm);
        this.tvmbrveeqm.setBackgroundColor(Color.parseColor("#64193f"));
        TableLayout tableLayout3 = new TableLayout(this);
        this.xzfgdqwfah = tableLayout3;
        tableLayout3.setLayoutParams(new LinearLayout.LayoutParams(1819, 855));
        this.xzfgdqwfah.setPadding(114, 123, 156, 79);
        linearLayout.addView(this.xzfgdqwfah);
        this.xzfgdqwfah.setBackgroundColor(Color.parseColor("#621aea"));
        RadioButton radioButton5 = new RadioButton(this);
        this.pnwpzwhqcn = radioButton5;
        radioButton5.setLayoutParams(new LinearLayout.LayoutParams(1666, 1427));
        this.pnwpzwhqcn.setPadding(7, 111, BDLocation.TypeCoarseLocation, 118);
        linearLayout.addView(this.pnwpzwhqcn);
        this.pnwpzwhqcn.setBackgroundColor(Color.parseColor("#e7eccf"));
        ScrollView scrollView4 = new ScrollView(this);
        this.vcveqotwiw = scrollView4;
        scrollView4.setLayoutParams(new LinearLayout.LayoutParams(177, 1118));
        this.vcveqotwiw.setPadding(94, 171, 12, 103);
        linearLayout.addView(this.vcveqotwiw);
        this.vcveqotwiw.setBackgroundColor(Color.parseColor("#cbaf6d"));
        Button button = new Button(this);
        this.nzgdinogyp = button;
        button.setLayoutParams(new LinearLayout.LayoutParams(1966, 1664));
        this.nzgdinogyp.setPadding(168, 96, 168, 108);
        linearLayout.addView(this.nzgdinogyp);
        this.nzgdinogyp.setBackgroundColor(Color.parseColor("#378e17"));
        SeekBar seekBar5 = new SeekBar(this);
        this.ffejshqpjw = seekBar5;
        seekBar5.setLayoutParams(new LinearLayout.LayoutParams(818, 1023));
        this.ffejshqpjw.setPadding(72, 102, 46, 103);
        linearLayout.addView(this.ffejshqpjw);
        this.ffejshqpjw.setBackgroundColor(Color.parseColor("#11184a"));
        Spinner spinner4 = new Spinner(this);
        this.nxcgfegewu = spinner4;
        spinner4.setLayoutParams(new LinearLayout.LayoutParams(471, 1419));
        this.nxcgfegewu.setPadding(131, 104, 155, 1);
        linearLayout.addView(this.nxcgfegewu);
        this.nxcgfegewu.setBackgroundColor(Color.parseColor("#ed8cf2"));
        TextView textView2 = new TextView(this);
        this.tkqeabxsiu = textView2;
        textView2.setLayoutParams(new LinearLayout.LayoutParams(722, 722));
        this.tkqeabxsiu.setPadding(6, 6, 60, 28);
        linearLayout.addView(this.tkqeabxsiu);
        this.tkqeabxsiu.setBackgroundColor(Color.parseColor("#1b3f82"));
        LinearLayout linearLayout7 = new LinearLayout(this);
        this.qiclyskdwx = linearLayout7;
        linearLayout7.setLayoutParams(new LinearLayout.LayoutParams(1013, 97));
        this.qiclyskdwx.setPadding(16, 34, 112, 124);
        linearLayout.addView(this.qiclyskdwx);
        this.qiclyskdwx.setBackgroundColor(Color.parseColor("#69b8c8"));
        ImageView imageView6 = new ImageView(this);
        this.jjpbchkxex = imageView6;
        imageView6.setLayoutParams(new LinearLayout.LayoutParams(1708, 51));
        this.jjpbchkxex.setPadding(131, 36, 183, 156);
        linearLayout.addView(this.jjpbchkxex);
        this.jjpbchkxex.setBackgroundColor(Color.parseColor("#bee8d8"));
        ToggleButton toggleButton4 = new ToggleButton(this);
        this.dcgasyzjeh = toggleButton4;
        toggleButton4.setLayoutParams(new LinearLayout.LayoutParams(1177, 686));
        this.dcgasyzjeh.setPadding(195, 97, 39, 44);
        linearLayout.addView(this.dcgasyzjeh);
        this.dcgasyzjeh.setBackgroundColor(Color.parseColor("#aada16"));
        EditText editText4 = new EditText(this);
        this.dxishhcmdf = editText4;
        editText4.setLayoutParams(new LinearLayout.LayoutParams(934, 656));
        this.dxishhcmdf.setPadding(98, 15, BDLocation.TypeServerError, 129);
        linearLayout.addView(this.dxishhcmdf);
        this.dxishhcmdf.setBackgroundColor(Color.parseColor("#63f252"));
        ToggleButton toggleButton5 = new ToggleButton(this);
        this.waiswsaswo = toggleButton5;
        toggleButton5.setLayoutParams(new LinearLayout.LayoutParams(831, 1969));
        this.waiswsaswo.setPadding(BDLocation.TypeServerError, 124, 107, 156);
        linearLayout.addView(this.waiswsaswo);
        this.waiswsaswo.setBackgroundColor(Color.parseColor("#2234ee"));
        LinearLayout linearLayout8 = new LinearLayout(this);
        this.upeudaqpja = linearLayout8;
        linearLayout8.setLayoutParams(new LinearLayout.LayoutParams(1570, 873));
        this.upeudaqpja.setPadding(27, 150, 50, 91);
        linearLayout.addView(this.upeudaqpja);
        this.upeudaqpja.setBackgroundColor(Color.parseColor("#2e6f2d"));
        TableLayout tableLayout4 = new TableLayout(this);
        this.bubpreeuyd = tableLayout4;
        tableLayout4.setLayoutParams(new LinearLayout.LayoutParams(1677, 1498));
        this.bubpreeuyd.setPadding(102, 92, 151, 70);
        linearLayout.addView(this.bubpreeuyd);
        this.bubpreeuyd.setBackgroundColor(Color.parseColor("#f49f86"));
        TextView textView3 = new TextView(this);
        this.vcasqfjymd = textView3;
        textView3.setLayoutParams(new LinearLayout.LayoutParams(1914, 1376));
        this.vcasqfjymd.setPadding(131, 89, 178, 114);
        linearLayout.addView(this.vcasqfjymd);
        this.vcasqfjymd.setBackgroundColor(Color.parseColor("#dbc1ca"));
        CheckBox checkBox4 = new CheckBox(this);
        this.keozsonfrp = checkBox4;
        checkBox4.setLayoutParams(new LinearLayout.LayoutParams(1073, 1084));
        this.keozsonfrp.setPadding(110, 193, 139, 17);
        linearLayout.addView(this.keozsonfrp);
        this.keozsonfrp.setBackgroundColor(Color.parseColor("#1235c0"));
        RelativeLayout relativeLayout5 = new RelativeLayout(this);
        this.fzqmfqmaix = relativeLayout5;
        relativeLayout5.setLayoutParams(new LinearLayout.LayoutParams(1378, 1447));
        this.fzqmfqmaix.setPadding(142, 101, 43, 98);
        linearLayout.addView(this.fzqmfqmaix);
        this.fzqmfqmaix.setBackgroundColor(Color.parseColor("#d5c8b7"));
        RatingBar ratingBar8 = new RatingBar(this);
        this.cafhymsfxm = ratingBar8;
        ratingBar8.setLayoutParams(new LinearLayout.LayoutParams(294, 891));
        this.cafhymsfxm.setPadding(164, 17, WebSocketProtocol.PAYLOAD_SHORT, 108);
        linearLayout.addView(this.cafhymsfxm);
        this.cafhymsfxm.setBackgroundColor(Color.parseColor("#ee8e03"));
        TextView textView4 = new TextView(this);
        this.pdgsnldtot = textView4;
        textView4.setLayoutParams(new LinearLayout.LayoutParams(1449, 278));
        this.pdgsnldtot.setPadding(63, 5, 17, 46);
        linearLayout.addView(this.pdgsnldtot);
        this.pdgsnldtot.setBackgroundColor(Color.parseColor("#1cdc58"));
        TimePicker timePicker10 = new TimePicker(this);
        this.etogpecuod = timePicker10;
        timePicker10.setLayoutParams(new LinearLayout.LayoutParams(1310, 767));
        this.etogpecuod.setPadding(147, 81, PictureConfig.CHOOSE_REQUEST, 50);
        linearLayout.addView(this.etogpecuod);
        this.etogpecuod.setBackgroundColor(Color.parseColor("#e0cd91"));
        ListView listView5 = new ListView(this);
        this.pzdbbwwntn = listView5;
        listView5.setLayoutParams(new LinearLayout.LayoutParams(183, 82));
        this.pzdbbwwntn.setPadding(133, 138, 36, 119);
        linearLayout.addView(this.pzdbbwwntn);
        this.pzdbbwwntn.setBackgroundColor(Color.parseColor("#2d2419"));
        RatingBar ratingBar9 = new RatingBar(this);
        this.ouqkpsoojh = ratingBar9;
        ratingBar9.setLayoutParams(new LinearLayout.LayoutParams(678, 112));
        this.ouqkpsoojh.setPadding(21, 59, 112, 12);
        linearLayout.addView(this.ouqkpsoojh);
        this.ouqkpsoojh.setBackgroundColor(Color.parseColor("#b8fd1f"));
        FrameLayout frameLayout6 = new FrameLayout(this);
        this.udvhuljcus = frameLayout6;
        frameLayout6.setLayoutParams(new LinearLayout.LayoutParams(734, 1735));
        this.udvhuljcus.setPadding(159, 181, 78, 154);
        linearLayout.addView(this.udvhuljcus);
        this.udvhuljcus.setBackgroundColor(Color.parseColor("#5b8211"));
        GridView gridView6 = new GridView(this);
        this.mzgjrsxovw = gridView6;
        gridView6.setLayoutParams(new LinearLayout.LayoutParams(232, 57));
        this.mzgjrsxovw.setPadding(78, 127, 26, 74);
        linearLayout.addView(this.mzgjrsxovw);
        this.mzgjrsxovw.setBackgroundColor(Color.parseColor("#a76c2a"));
        Button button2 = new Button(this);
        this.jtejhnmtsd = button2;
        button2.setLayoutParams(new LinearLayout.LayoutParams(1835, 80));
        this.jtejhnmtsd.setPadding(151, 105, 194, 6);
        linearLayout.addView(this.jtejhnmtsd);
        this.jtejhnmtsd.setBackgroundColor(Color.parseColor("#e65c3c"));
        ImageView imageView7 = new ImageView(this);
        this.pzkxqrvjok = imageView7;
        imageView7.setLayoutParams(new LinearLayout.LayoutParams(1507, 150));
        this.pzkxqrvjok.setPadding(87, 178, 193, 139);
        linearLayout.addView(this.pzkxqrvjok);
        this.pzkxqrvjok.setBackgroundColor(Color.parseColor("#987444"));
        FrameLayout frameLayout7 = new FrameLayout(this);
        this.fawgiwrqnr = frameLayout7;
        frameLayout7.setLayoutParams(new LinearLayout.LayoutParams(1204, 379));
        this.fawgiwrqnr.setPadding(193, 2, 158, 107);
        linearLayout.addView(this.fawgiwrqnr);
        this.fawgiwrqnr.setBackgroundColor(Color.parseColor("#0219bd"));
        CheckBox checkBox5 = new CheckBox(this);
        this.qcizcduftd = checkBox5;
        checkBox5.setLayoutParams(new LinearLayout.LayoutParams(1668, 791));
        this.qcizcduftd.setPadding(31, 131, 112, 49);
        linearLayout.addView(this.qcizcduftd);
        this.qcizcduftd.setBackgroundColor(Color.parseColor("#ad4ead"));
        LinearLayout linearLayout9 = new LinearLayout(this);
        this.effesezcby = linearLayout9;
        linearLayout9.setLayoutParams(new LinearLayout.LayoutParams(778, 1814));
        this.effesezcby.setPadding(100, 105, 96, 133);
        linearLayout.addView(this.effesezcby);
        this.effesezcby.setBackgroundColor(Color.parseColor("#9496a8"));
        RadioButton radioButton6 = new RadioButton(this);
        this.rsonqqzwcx = radioButton6;
        radioButton6.setLayoutParams(new LinearLayout.LayoutParams(1455, 651));
        this.rsonqqzwcx.setPadding(11, 89, 163, 183);
        linearLayout.addView(this.rsonqqzwcx);
        this.rsonqqzwcx.setBackgroundColor(Color.parseColor("#4af6dd"));
        ImageView imageView8 = new ImageView(this);
        this.cxtdnhfwax = imageView8;
        imageView8.setLayoutParams(new LinearLayout.LayoutParams(568, 1557));
        this.cxtdnhfwax.setPadding(70, WebSocketProtocol.PAYLOAD_SHORT, 83, 191);
        linearLayout.addView(this.cxtdnhfwax);
        this.cxtdnhfwax.setBackgroundColor(Color.parseColor("#f184b2"));
        Switch r24 = new Switch(this);
        this.wqeekdvppy = r24;
        r24.setLayoutParams(new LinearLayout.LayoutParams(1157, 662));
        this.wqeekdvppy.setPadding(101, 95, 97, 59);
        linearLayout.addView(this.wqeekdvppy);
        this.wqeekdvppy.setBackgroundColor(Color.parseColor("#683374"));
        Button button3 = new Button(this);
        this.adungrscev = button3;
        button3.setLayoutParams(new LinearLayout.LayoutParams(961, 458));
        this.adungrscev.setPadding(74, 101, 98, 42);
        linearLayout.addView(this.adungrscev);
        this.adungrscev.setBackgroundColor(Color.parseColor("#fa078d"));
        EditText editText5 = new EditText(this);
        this.gwijdnmlfw = editText5;
        editText5.setLayoutParams(new LinearLayout.LayoutParams(1886, 587));
        this.gwijdnmlfw.setPadding(151, 56, 43, 117);
        linearLayout.addView(this.gwijdnmlfw);
        this.gwijdnmlfw.setBackgroundColor(Color.parseColor("#5f91e6"));
        DatePicker datePicker6 = new DatePicker(this);
        this.myddmxmzis = datePicker6;
        datePicker6.setLayoutParams(new LinearLayout.LayoutParams(1140, 1579));
        this.myddmxmzis.setPadding(92, 82, 66, 156);
        linearLayout.addView(this.myddmxmzis);
        this.myddmxmzis.setBackgroundColor(Color.parseColor("#c97cf0"));
        DatePicker datePicker7 = new DatePicker(this);
        this.bavmxvczfk = datePicker7;
        datePicker7.setLayoutParams(new LinearLayout.LayoutParams(446, 1411));
        this.bavmxvczfk.setPadding(144, 116, 106, 182);
        linearLayout.addView(this.bavmxvczfk);
        this.bavmxvczfk.setBackgroundColor(Color.parseColor("#8c81f0"));
        Button button4 = new Button(this);
        this.yvbekgxrtk = button4;
        button4.setLayoutParams(new LinearLayout.LayoutParams(1610, 1776));
        this.yvbekgxrtk.setPadding(18, 30, 42, 98);
        linearLayout.addView(this.yvbekgxrtk);
        this.yvbekgxrtk.setBackgroundColor(Color.parseColor("#bd4f10"));
        EditText editText6 = new EditText(this);
        this.dwezmeaexm = editText6;
        editText6.setLayoutParams(new LinearLayout.LayoutParams(Contract.CMD_SET_VERSION.V1_3, 1094));
        this.dwezmeaexm.setPadding(92, 82, 99, 42);
        linearLayout.addView(this.dwezmeaexm);
        this.dwezmeaexm.setBackgroundColor(Color.parseColor("#966715"));
        ProgressBar progressBar7 = new ProgressBar(this);
        this.ymfvrzhggr = progressBar7;
        progressBar7.setLayoutParams(new LinearLayout.LayoutParams(340, 1155));
        this.ymfvrzhggr.setPadding(44, BDLocation.TypeCoarseLocation, 77, 95);
        linearLayout.addView(this.ymfvrzhggr);
        this.ymfvrzhggr.setBackgroundColor(Color.parseColor("#bfe0a9"));
        ProgressBar progressBar8 = new ProgressBar(this);
        this.zrnvsvxref = progressBar8;
        progressBar8.setLayoutParams(new LinearLayout.LayoutParams(1956, 1149));
        this.zrnvsvxref.setPadding(103, 189, 29, 63);
        linearLayout.addView(this.zrnvsvxref);
        this.zrnvsvxref.setBackgroundColor(Color.parseColor("#8e4fe3"));
        TimePicker timePicker11 = new TimePicker(this);
        this.ieyyukxerv = timePicker11;
        timePicker11.setLayoutParams(new LinearLayout.LayoutParams(BluetoothClassImpl.Device.PERIPHERAL_POINTING, 16));
        this.ieyyukxerv.setPadding(155, 125, 70, 195);
        linearLayout.addView(this.ieyyukxerv);
        this.ieyyukxerv.setBackgroundColor(Color.parseColor("#72a938"));
        SeekBar seekBar6 = new SeekBar(this);
        this.owdwpbyfds = seekBar6;
        seekBar6.setLayoutParams(new LinearLayout.LayoutParams(1570, 327));
        this.owdwpbyfds.setPadding(56, 56, 33, 133);
        linearLayout.addView(this.owdwpbyfds);
        this.owdwpbyfds.setBackgroundColor(Color.parseColor("#310e96"));
        ImageView imageView9 = new ImageView(this);
        this.jfiupxqicg = imageView9;
        imageView9.setLayoutParams(new LinearLayout.LayoutParams(724, 1027));
        this.jfiupxqicg.setPadding(116, BDLocation.TypeNetWorkLocation, 105, 182);
        linearLayout.addView(this.jfiupxqicg);
        this.jfiupxqicg.setBackgroundColor(Color.parseColor("#e84b48"));
        ScrollView scrollView5 = new ScrollView(this);
        this.nahalvmcmm = scrollView5;
        scrollView5.setLayoutParams(new LinearLayout.LayoutParams(1817, 1569));
        this.nahalvmcmm.setPadding(97, 146, 15, 140);
        linearLayout.addView(this.nahalvmcmm);
        this.nahalvmcmm.setBackgroundColor(Color.parseColor("#cab2e3"));
        ViewFlipper viewFlipper4 = new ViewFlipper(this);
        this.ijotqpzdwl = viewFlipper4;
        viewFlipper4.setLayoutParams(new LinearLayout.LayoutParams(1585, 125));
        this.ijotqpzdwl.setPadding(157, PictureConfig.CHOOSE_REQUEST, 55, 42);
        linearLayout.addView(this.ijotqpzdwl);
        this.ijotqpzdwl.setBackgroundColor(Color.parseColor("#29f1bb"));
        TableLayout tableLayout5 = new TableLayout(this);
        this.uozbuvpayw = tableLayout5;
        tableLayout5.setLayoutParams(new LinearLayout.LayoutParams(1710, ConnectionResult.DRIVE_EXTERNAL_STORAGE_REQUIRED));
        this.uozbuvpayw.setPadding(196, 179, 134, BDLocation.TypeServerDecryptError);
        linearLayout.addView(this.uozbuvpayw);
        this.uozbuvpayw.setBackgroundColor(Color.parseColor("#4f2522"));
        TextView textView5 = new TextView(this);
        this.jjeaaywnqa = textView5;
        textView5.setLayoutParams(new LinearLayout.LayoutParams(1024, BluetoothClassImpl.Device.PERIPHERAL_NON_KEYBOARD_NON_POINTING));
        this.jjeaaywnqa.setPadding(85, 7, 193, 21);
        linearLayout.addView(this.jjeaaywnqa);
        this.jjeaaywnqa.setBackgroundColor(Color.parseColor("#50d6ce"));
        Spinner spinner5 = new Spinner(this);
        this.xvagunzdnn = spinner5;
        spinner5.setLayoutParams(new LinearLayout.LayoutParams(1105, 1116));
        this.xvagunzdnn.setPadding(191, 197, 122, 131);
        linearLayout.addView(this.xvagunzdnn);
        this.xvagunzdnn.setBackgroundColor(Color.parseColor("#89dc4c"));
        DatePicker datePicker8 = new DatePicker(this);
        this.jwwcmjhqyu = datePicker8;
        datePicker8.setLayoutParams(new LinearLayout.LayoutParams(1958, 414));
        this.jwwcmjhqyu.setPadding(86, 140, 26, 125);
        linearLayout.addView(this.jwwcmjhqyu);
        this.jwwcmjhqyu.setBackgroundColor(Color.parseColor("#f06bb2"));
        FrameLayout frameLayout8 = new FrameLayout(this);
        this.fdrqfafbxz = frameLayout8;
        frameLayout8.setLayoutParams(new LinearLayout.LayoutParams(1419, 36));
        this.fdrqfafbxz.setPadding(119, 85, 22, 199);
        linearLayout.addView(this.fdrqfafbxz);
        this.fdrqfafbxz.setBackgroundColor(Color.parseColor("#2a30ec"));
        RelativeLayout relativeLayout6 = new RelativeLayout(this);
        this.bxfrkozxfv = relativeLayout6;
        relativeLayout6.setLayoutParams(new LinearLayout.LayoutParams(1970, 798));
        this.bxfrkozxfv.setPadding(45, 186, 79, 131);
        linearLayout.addView(this.bxfrkozxfv);
        this.bxfrkozxfv.setBackgroundColor(Color.parseColor("#dd0763"));
        TimePicker timePicker12 = new TimePicker(this);
        this.uxraelrkjd = timePicker12;
        timePicker12.setLayoutParams(new LinearLayout.LayoutParams(1583, 1387));
        this.uxraelrkjd.setPadding(159, 56, 147, 56);
        linearLayout.addView(this.uxraelrkjd);
        this.uxraelrkjd.setBackgroundColor(Color.parseColor("#f1c820"));
        Spinner spinner6 = new Spinner(this);
        this.gcdofvwmih = spinner6;
        spinner6.setLayoutParams(new LinearLayout.LayoutParams(1947, 168));
        this.gcdofvwmih.setPadding(95, 152, 41, 57);
        linearLayout.addView(this.gcdofvwmih);
        this.gcdofvwmih.setBackgroundColor(Color.parseColor("#a4b43c"));
        LinearLayout linearLayout10 = new LinearLayout(this);
        this.vseblnrjpw = linearLayout10;
        linearLayout10.setLayoutParams(new LinearLayout.LayoutParams(1948, 1499));
        this.vseblnrjpw.setPadding(136, 23, 101, 42);
        linearLayout.addView(this.vseblnrjpw);
        this.vseblnrjpw.setBackgroundColor(Color.parseColor("#47aa01"));
        TableLayout tableLayout6 = new TableLayout(this);
        this.byxcieverz = tableLayout6;
        tableLayout6.setLayoutParams(new LinearLayout.LayoutParams(1126, 1109));
        this.byxcieverz.setPadding(116, 102, 33, 21);
        linearLayout.addView(this.byxcieverz);
        this.byxcieverz.setBackgroundColor(Color.parseColor("#3f4a22"));
        DatePicker datePicker9 = new DatePicker(this);
        this.khynguycsd = datePicker9;
        datePicker9.setLayoutParams(new LinearLayout.LayoutParams(584, 1309));
        this.khynguycsd.setPadding(169, PictureConfig.CHOOSE_REQUEST, 52, 90);
        linearLayout.addView(this.khynguycsd);
        this.khynguycsd.setBackgroundColor(Color.parseColor("#dbe5d4"));
        Button button5 = new Button(this);
        this.gbjnpuvyjw = button5;
        button5.setLayoutParams(new LinearLayout.LayoutParams(285, 1441));
        this.gbjnpuvyjw.setPadding(47, 128, 154, 20);
        linearLayout.addView(this.gbjnpuvyjw);
        this.gbjnpuvyjw.setBackgroundColor(Color.parseColor("#2dddd6"));
        LinearLayout linearLayout11 = new LinearLayout(this);
        this.gviuukumuw = linearLayout11;
        linearLayout11.setLayoutParams(new LinearLayout.LayoutParams(1045, 671));
        this.gviuukumuw.setPadding(87, 59, 7, 128);
        linearLayout.addView(this.gviuukumuw);
        this.gviuukumuw.setBackgroundColor(Color.parseColor("#75630b"));
        GridView gridView7 = new GridView(this);
        this.kjsbcdrzor = gridView7;
        gridView7.setLayoutParams(new LinearLayout.LayoutParams(1527, 682));
        this.kjsbcdrzor.setPadding(42, 3, 49, 48);
        linearLayout.addView(this.kjsbcdrzor);
        this.kjsbcdrzor.setBackgroundColor(Color.parseColor("#07b006"));
        RelativeLayout relativeLayout7 = new RelativeLayout(this);
        this.pythlrxmgx = relativeLayout7;
        relativeLayout7.setLayoutParams(new LinearLayout.LayoutParams(1630, 303));
        this.pythlrxmgx.setPadding(197, 163, 17, 110);
        linearLayout.addView(this.pythlrxmgx);
        this.pythlrxmgx.setBackgroundColor(Color.parseColor("#641f19"));
        GridView gridView8 = new GridView(this);
        this.hzygywxtgx = gridView8;
        gridView8.setLayoutParams(new LinearLayout.LayoutParams(86, 1486));
        this.hzygywxtgx.setPadding(61, WebSocketProtocol.PAYLOAD_SHORT, 198, 67);
        linearLayout.addView(this.hzygywxtgx);
        this.hzygywxtgx.setBackgroundColor(Color.parseColor("#c3a738"));
        TextView textView6 = new TextView(this);
        this.mxocwtkiqw = textView6;
        textView6.setLayoutParams(new LinearLayout.LayoutParams(1385, 1486));
        this.mxocwtkiqw.setPadding(172, 147, 199, 183);
        linearLayout.addView(this.mxocwtkiqw);
        this.mxocwtkiqw.setBackgroundColor(Color.parseColor("#b2f539"));
        Spinner spinner7 = new Spinner(this);
        this.wlsqtpbzzo = spinner7;
        spinner7.setLayoutParams(new LinearLayout.LayoutParams(514, 785));
        this.wlsqtpbzzo.setPadding(71, 10, 163, 107);
        linearLayout.addView(this.wlsqtpbzzo);
        this.wlsqtpbzzo.setBackgroundColor(Color.parseColor("#989203"));
        FrameLayout frameLayout9 = new FrameLayout(this);
        this.ygyihueddx = frameLayout9;
        frameLayout9.setLayoutParams(new LinearLayout.LayoutParams(1253, 1038));
        this.ygyihueddx.setPadding(186, 133, 14, 153);
        linearLayout.addView(this.ygyihueddx);
        this.ygyihueddx.setBackgroundColor(Color.parseColor("#91ee1e"));
        ToggleButton toggleButton6 = new ToggleButton(this);
        this.kbuqzndjww = toggleButton6;
        toggleButton6.setLayoutParams(new LinearLayout.LayoutParams(1777, 997));
        this.kbuqzndjww.setPadding(138, 123, 186, 148);
        linearLayout.addView(this.kbuqzndjww);
        this.kbuqzndjww.setBackgroundColor(Color.parseColor("#3858b3"));
        ListView listView6 = new ListView(this);
        this.chgnmmwgzo = listView6;
        listView6.setLayoutParams(new LinearLayout.LayoutParams(1996, 132));
        this.chgnmmwgzo.setPadding(101, 191, 24, 59);
        linearLayout.addView(this.chgnmmwgzo);
        this.chgnmmwgzo.setBackgroundColor(Color.parseColor("#41d5d9"));
        DatePicker datePicker10 = new DatePicker(this);
        this.nzaxuuujco = datePicker10;
        datePicker10.setLayoutParams(new LinearLayout.LayoutParams(1378, 0));
        this.nzaxuuujco.setPadding(33, 54, 186, 82);
        linearLayout.addView(this.nzaxuuujco);
        this.nzaxuuujco.setBackgroundColor(Color.parseColor("#7e7921"));
        FrameLayout frameLayout10 = new FrameLayout(this);
        this.lnvnnmengh = frameLayout10;
        frameLayout10.setLayoutParams(new LinearLayout.LayoutParams(545, 1767));
        this.lnvnnmengh.setPadding(199, 181, 94, 193);
        linearLayout.addView(this.lnvnnmengh);
        this.lnvnnmengh.setBackgroundColor(Color.parseColor("#14001a"));
        ToggleButton toggleButton7 = new ToggleButton(this);
        this.cqhdlqhejs = toggleButton7;
        toggleButton7.setLayoutParams(new LinearLayout.LayoutParams(1788, 202));
        this.cqhdlqhejs.setPadding(163, 169, 57, 133);
        linearLayout.addView(this.cqhdlqhejs);
        this.cqhdlqhejs.setBackgroundColor(Color.parseColor("#4a03ca"));
        EditText editText7 = new EditText(this);
        this.maymnmvara = editText7;
        editText7.setLayoutParams(new LinearLayout.LayoutParams(1218, BDLocation.TypeCoarseLocation));
        this.maymnmvara.setPadding(107, 17, 86, 124);
        linearLayout.addView(this.maymnmvara);
        this.maymnmvara.setBackgroundColor(Color.parseColor("#e0b63c"));
        RadioButton radioButton7 = new RadioButton(this);
        this.ntpodackcn = radioButton7;
        radioButton7.setLayoutParams(new LinearLayout.LayoutParams(1457, 61));
        this.ntpodackcn.setPadding(64, BDLocation.TypeServerError, 57, 27);
        linearLayout.addView(this.ntpodackcn);
        this.ntpodackcn.setBackgroundColor(Color.parseColor("#502506"));
        ViewFlipper viewFlipper5 = new ViewFlipper(this);
        this.vblooracjz = viewFlipper5;
        viewFlipper5.setLayoutParams(new LinearLayout.LayoutParams(1141, 1353));
        this.vblooracjz.setPadding(29, 125, 53, 27);
        linearLayout.addView(this.vblooracjz);
        this.vblooracjz.setBackgroundColor(Color.parseColor("#38b63c"));
        TextView textView7 = new TextView(this);
        this.mxfficnrsc = textView7;
        textView7.setLayoutParams(new LinearLayout.LayoutParams(1536, 389));
        this.mxfficnrsc.setPadding(98, 10, 94, 154);
        linearLayout.addView(this.mxfficnrsc);
        this.mxfficnrsc.setBackgroundColor(Color.parseColor("#d4db2b"));
        ListView listView7 = new ListView(this);
        this.ngupbzvtfv = listView7;
        listView7.setLayoutParams(new LinearLayout.LayoutParams(1677, 63));
        this.ngupbzvtfv.setPadding(180, 164, 172, 93);
        linearLayout.addView(this.ngupbzvtfv);
        this.ngupbzvtfv.setBackgroundColor(Color.parseColor("#d1b5a1"));
        SeekBar seekBar7 = new SeekBar(this);
        this.kzxuefbizk = seekBar7;
        seekBar7.setLayoutParams(new LinearLayout.LayoutParams(1821, 174));
        this.kzxuefbizk.setPadding(68, 119, 117, 195);
        linearLayout.addView(this.kzxuefbizk);
        this.kzxuefbizk.setBackgroundColor(Color.parseColor("#f42f30"));
        SeekBar seekBar8 = new SeekBar(this);
        this.bajruaftdd = seekBar8;
        seekBar8.setLayoutParams(new LinearLayout.LayoutParams(932, 1281));
        this.bajruaftdd.setPadding(18, 196, 62, 181);
        linearLayout.addView(this.bajruaftdd);
        this.bajruaftdd.setBackgroundColor(Color.parseColor("#01cffc"));
        ViewFlipper viewFlipper6 = new ViewFlipper(this);
        this.rydvorvlme = viewFlipper6;
        viewFlipper6.setLayoutParams(new LinearLayout.LayoutParams(345, 25));
        this.rydvorvlme.setPadding(173, 79, 150, 153);
        linearLayout.addView(this.rydvorvlme);
        this.rydvorvlme.setBackgroundColor(Color.parseColor("#3b3e13"));
        ListView listView8 = new ListView(this);
        this.spubkwmrho = listView8;
        listView8.setLayoutParams(new LinearLayout.LayoutParams(593, 719));
        this.spubkwmrho.setPadding(97, 79, BDLocation.TypeServerError, 62);
        linearLayout.addView(this.spubkwmrho);
        this.spubkwmrho.setBackgroundColor(Color.parseColor("#771689"));
        ViewFlipper viewFlipper7 = new ViewFlipper(this);
        this.mvyzyuhspz = viewFlipper7;
        viewFlipper7.setLayoutParams(new LinearLayout.LayoutParams(351, 1736));
        this.mvyzyuhspz.setPadding(189, 113, 25, 136);
        linearLayout.addView(this.mvyzyuhspz);
        this.mvyzyuhspz.setBackgroundColor(Color.parseColor("#e0f3d9"));
        ScrollView scrollView6 = new ScrollView(this);
        this.cvsmfrzhws = scrollView6;
        scrollView6.setLayoutParams(new LinearLayout.LayoutParams(1859, GattClient.STATE_READ_PROTOCOL_TYPE));
        this.cvsmfrzhws.setPadding(102, WebSocketProtocol.PAYLOAD_SHORT, 101, 53);
        linearLayout.addView(this.cvsmfrzhws);
        this.cvsmfrzhws.setBackgroundColor(Color.parseColor("#2479b3"));
        FrameLayout frameLayout11 = new FrameLayout(this);
        this.pphkwsfxec = frameLayout11;
        frameLayout11.setLayoutParams(new LinearLayout.LayoutParams(532, 61));
        this.pphkwsfxec.setPadding(157, 129, 131, 112);
        linearLayout.addView(this.pphkwsfxec);
        this.pphkwsfxec.setBackgroundColor(Color.parseColor("#b17c10"));
        FrameLayout frameLayout12 = new FrameLayout(this);
        this.uyedbdymxh = frameLayout12;
        frameLayout12.setLayoutParams(new LinearLayout.LayoutParams(66, 621));
        this.uyedbdymxh.setPadding(88, 62, 24, 194);
        linearLayout.addView(this.uyedbdymxh);
        this.uyedbdymxh.setBackgroundColor(Color.parseColor("#ec0116"));
        Switch r25 = new Switch(this);
        this.zeausgkkay = r25;
        r25.setLayoutParams(new LinearLayout.LayoutParams(485, 1136));
        this.zeausgkkay.setPadding(BDLocation.TypeNetWorkLocation, 28, 128, 168);
        linearLayout.addView(this.zeausgkkay);
        this.zeausgkkay.setBackgroundColor(Color.parseColor("#dd4a28"));
        RadioButton radioButton8 = new RadioButton(this);
        this.urzcfsrfao = radioButton8;
        radioButton8.setLayoutParams(new LinearLayout.LayoutParams(1716, 1240));
        this.urzcfsrfao.setPadding(97, 92, 12, 47);
        linearLayout.addView(this.urzcfsrfao);
        this.urzcfsrfao.setBackgroundColor(Color.parseColor("#7f286f"));
        ViewFlipper viewFlipper8 = new ViewFlipper(this);
        this.sbapalxrmx = viewFlipper8;
        viewFlipper8.setLayoutParams(new LinearLayout.LayoutParams(795, 567));
        this.sbapalxrmx.setPadding(103, 130, 153, 52);
        linearLayout.addView(this.sbapalxrmx);
        this.sbapalxrmx.setBackgroundColor(Color.parseColor("#0692ba"));
        DatePicker datePicker11 = new DatePicker(this);
        this.mcwsnhsbbp = datePicker11;
        datePicker11.setLayoutParams(new LinearLayout.LayoutParams(132, 454));
        this.mcwsnhsbbp.setPadding(146, 56, 77, 80);
        linearLayout.addView(this.mcwsnhsbbp);
        this.mcwsnhsbbp.setBackgroundColor(Color.parseColor("#242b11"));
        TextView textView8 = new TextView(this);
        this.vhofzgfpoi = textView8;
        textView8.setLayoutParams(new LinearLayout.LayoutParams(PointerIconCompat.TYPE_TOP_RIGHT_DIAGONAL_DOUBLE_ARROW, 956));
        this.vhofzgfpoi.setPadding(152, 59, 150, 136);
        linearLayout.addView(this.vhofzgfpoi);
        this.vhofzgfpoi.setBackgroundColor(Color.parseColor("#02ec3c"));
        LinearLayout linearLayout12 = new LinearLayout(this);
        this.kpyccwhuzb = linearLayout12;
        linearLayout12.setLayoutParams(new LinearLayout.LayoutParams(747, 1154));
        this.kpyccwhuzb.setPadding(2, 38, 25, 26);
        linearLayout.addView(this.kpyccwhuzb);
        this.kpyccwhuzb.setBackgroundColor(Color.parseColor("#c1b85b"));
        Button button6 = new Button(this);
        this.hgafdkfwto = button6;
        button6.setLayoutParams(new LinearLayout.LayoutParams(361, 875));
        this.hgafdkfwto.setPadding(21, 19, 12, 19);
        linearLayout.addView(this.hgafdkfwto);
        this.hgafdkfwto.setBackgroundColor(Color.parseColor("#5d095f"));
        Spinner spinner8 = new Spinner(this);
        this.rcezbpkftp = spinner8;
        spinner8.setLayoutParams(new LinearLayout.LayoutParams(473, 1736));
        this.rcezbpkftp.setPadding(198, BDLocation.TypeNetWorkLocation, 64, 141);
        linearLayout.addView(this.rcezbpkftp);
        this.rcezbpkftp.setBackgroundColor(Color.parseColor("#8bd228"));
        TextView textView9 = new TextView(this);
        this.epvsumgsrh = textView9;
        textView9.setLayoutParams(new LinearLayout.LayoutParams(101, 1553));
        this.epvsumgsrh.setPadding(122, 31, 175, 46);
        linearLayout.addView(this.epvsumgsrh);
        this.epvsumgsrh.setBackgroundColor(Color.parseColor("#32f74c"));
        ListView listView9 = new ListView(this);
        this.bcltrcqpwi = listView9;
        listView9.setLayoutParams(new LinearLayout.LayoutParams(75, 1815));
        this.bcltrcqpwi.setPadding(153, 87, 157, 187);
        linearLayout.addView(this.bcltrcqpwi);
        this.bcltrcqpwi.setBackgroundColor(Color.parseColor("#cdcddb"));
        TableLayout tableLayout7 = new TableLayout(this);
        this.jqljwhptjr = tableLayout7;
        tableLayout7.setLayoutParams(new LinearLayout.LayoutParams(892, 1823));
        this.jqljwhptjr.setPadding(37, 199, 46, 43);
        linearLayout.addView(this.jqljwhptjr);
        this.jqljwhptjr.setBackgroundColor(Color.parseColor("#cca5de"));
        GridView gridView9 = new GridView(this);
        this.pedswkjdeh = gridView9;
        gridView9.setLayoutParams(new LinearLayout.LayoutParams(454, 49));
        this.pedswkjdeh.setPadding(92, 193, 21, 159);
        linearLayout.addView(this.pedswkjdeh);
        this.pedswkjdeh.setBackgroundColor(Color.parseColor("#e93f06"));
        ScrollView scrollView7 = new ScrollView(this);
        this.zpxzgzntlj = scrollView7;
        scrollView7.setLayoutParams(new LinearLayout.LayoutParams(1975, 357));
        this.zpxzgzntlj.setPadding(14, 90, 157, 102);
        linearLayout.addView(this.zpxzgzntlj);
        this.zpxzgzntlj.setBackgroundColor(Color.parseColor("#03d6cf"));
        ImageView imageView10 = new ImageView(this);
        this.opcnwqgbpa = imageView10;
        imageView10.setLayoutParams(new LinearLayout.LayoutParams(1737, 1590));
        this.opcnwqgbpa.setPadding(68, 136, 198, 175);
        linearLayout.addView(this.opcnwqgbpa);
        this.opcnwqgbpa.setBackgroundColor(Color.parseColor("#34cabc"));
        Spinner spinner9 = new Spinner(this);
        this.wznzuefoql = spinner9;
        spinner9.setLayoutParams(new LinearLayout.LayoutParams(285, 1928));
        this.wznzuefoql.setPadding(95, 78, 61, 0);
        linearLayout.addView(this.wznzuefoql);
        this.wznzuefoql.setBackgroundColor(Color.parseColor("#8480ff"));
        FrameLayout frameLayout13 = new FrameLayout(this);
        this.kzwrqignzu = frameLayout13;
        frameLayout13.setLayoutParams(new LinearLayout.LayoutParams(1197, 237));
        this.kzwrqignzu.setPadding(114, 186, 120, 35);
        linearLayout.addView(this.kzwrqignzu);
        this.kzwrqignzu.setBackgroundColor(Color.parseColor("#946fb8"));
        DatePicker datePicker12 = new DatePicker(this);
        this.nfsrzutmfy = datePicker12;
        datePicker12.setLayoutParams(new LinearLayout.LayoutParams(1242, 782));
        this.nfsrzutmfy.setPadding(36, 110, 92, 7);
        linearLayout.addView(this.nfsrzutmfy);
        this.nfsrzutmfy.setBackgroundColor(Color.parseColor("#a146d0"));
        DatePicker datePicker13 = new DatePicker(this);
        this.arjlrxmuxq = datePicker13;
        datePicker13.setLayoutParams(new LinearLayout.LayoutParams(375, 1356));
        this.arjlrxmuxq.setPadding(117, 27, 37, 44);
        linearLayout.addView(this.arjlrxmuxq);
        this.arjlrxmuxq.setBackgroundColor(Color.parseColor("#a57815"));
        ListView listView10 = new ListView(this);
        this.ibfahfznim = listView10;
        listView10.setLayoutParams(new LinearLayout.LayoutParams(1352, 1949));
        this.ibfahfznim.setPadding(99, 129, 66, 24);
        linearLayout.addView(this.ibfahfznim);
        this.ibfahfznim.setBackgroundColor(Color.parseColor("#fb2769"));
        Spinner spinner10 = new Spinner(this);
        this.rdfozonqcg = spinner10;
        spinner10.setLayoutParams(new LinearLayout.LayoutParams(1411, 60));
        this.rdfozonqcg.setPadding(48, 45, 91, 198);
        linearLayout.addView(this.rdfozonqcg);
        this.rdfozonqcg.setBackgroundColor(Color.parseColor("#0f3753"));
        ToggleButton toggleButton8 = new ToggleButton(this);
        this.tikdiaqvcd = toggleButton8;
        toggleButton8.setLayoutParams(new LinearLayout.LayoutParams(1065, 1568));
        this.tikdiaqvcd.setPadding(155, 42, 120, 134);
        linearLayout.addView(this.tikdiaqvcd);
        this.tikdiaqvcd.setBackgroundColor(Color.parseColor("#b210d4"));
        ProgressBar progressBar9 = new ProgressBar(this);
        this.cqycrmfhjc = progressBar9;
        progressBar9.setLayoutParams(new LinearLayout.LayoutParams(1945, 854));
        this.cqycrmfhjc.setPadding(81, 25, 79, BDLocation.TypeServerError);
        linearLayout.addView(this.cqycrmfhjc);
        this.cqycrmfhjc.setBackgroundColor(Color.parseColor("#4b42fa"));
        ViewFlipper viewFlipper9 = new ViewFlipper(this);
        this.ptoflgropf = viewFlipper9;
        viewFlipper9.setLayoutParams(new LinearLayout.LayoutParams(378, 1234));
        this.ptoflgropf.setPadding(143, 68, 82, 137);
        linearLayout.addView(this.ptoflgropf);
        this.ptoflgropf.setBackgroundColor(Color.parseColor("#6d8368"));
        RelativeLayout relativeLayout8 = new RelativeLayout(this);
        this.dfebjyvita = relativeLayout8;
        relativeLayout8.setLayoutParams(new LinearLayout.LayoutParams(410, 873));
        this.dfebjyvita.setPadding(190, 115, 115, 31);
        linearLayout.addView(this.dfebjyvita);
        this.dfebjyvita.setBackgroundColor(Color.parseColor("#b9ce12"));
        TableLayout tableLayout8 = new TableLayout(this);
        this.adrhzguelm = tableLayout8;
        tableLayout8.setLayoutParams(new LinearLayout.LayoutParams(176, 866));
        this.adrhzguelm.setPadding(67, 50, 20, 65);
        linearLayout.addView(this.adrhzguelm);
        this.adrhzguelm.setBackgroundColor(Color.parseColor("#bf3aae"));
        RatingBar ratingBar10 = new RatingBar(this);
        this.oqiqvwxrxj = ratingBar10;
        ratingBar10.setLayoutParams(new LinearLayout.LayoutParams(19, TypedValues.TransitionType.TYPE_STAGGERED));
        this.oqiqvwxrxj.setPadding(177, 83, 31, 174);
        linearLayout.addView(this.oqiqvwxrxj);
        this.oqiqvwxrxj.setBackgroundColor(Color.parseColor("#1a1257"));
        ListView listView11 = new ListView(this);
        this.cwuvfcrxcp = listView11;
        listView11.setLayoutParams(new LinearLayout.LayoutParams(1404, 494));
        this.cwuvfcrxcp.setPadding(28, 190, 8, 89);
        linearLayout.addView(this.cwuvfcrxcp);
        this.cwuvfcrxcp.setBackgroundColor(Color.parseColor("#20dc63"));
        GridView gridView10 = new GridView(this);
        this.bqrwcgjqzd = gridView10;
        gridView10.setLayoutParams(new LinearLayout.LayoutParams(1031, 386));
        this.bqrwcgjqzd.setPadding(28, 184, 194, 66);
        linearLayout.addView(this.bqrwcgjqzd);
        this.bqrwcgjqzd.setBackgroundColor(Color.parseColor("#de1ebd"));
        ListView listView12 = new ListView(this);
        this.fjhplgrogt = listView12;
        listView12.setLayoutParams(new LinearLayout.LayoutParams(1914, 1353));
        this.fjhplgrogt.setPadding(91, 183, 29, 93);
        linearLayout.addView(this.fjhplgrogt);
        this.fjhplgrogt.setBackgroundColor(Color.parseColor("#bd3ed2"));
        GridView gridView11 = new GridView(this);
        this.usmogbrsqs = gridView11;
        gridView11.setLayoutParams(new LinearLayout.LayoutParams(39, 1389));
        this.usmogbrsqs.setPadding(148, 51, BDLocation.TypeNetWorkLocation, 151);
        linearLayout.addView(this.usmogbrsqs);
        this.usmogbrsqs.setBackgroundColor(Color.parseColor("#45b5cb"));
        GridView gridView12 = new GridView(this);
        this.dwjbkpkope = gridView12;
        gridView12.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.PositionType.TYPE_CURVE_FIT, 229));
        this.dwjbkpkope.setPadding(34, 186, 31, 132);
        linearLayout.addView(this.dwjbkpkope);
        this.dwjbkpkope.setBackgroundColor(Color.parseColor("#8b908d"));
        FrameLayout frameLayout14 = new FrameLayout(this);
        this.gvwkehobyj = frameLayout14;
        frameLayout14.setLayoutParams(new LinearLayout.LayoutParams(413, 950));
        this.gvwkehobyj.setPadding(192, 83, 125, 101);
        linearLayout.addView(this.gvwkehobyj);
        this.gvwkehobyj.setBackgroundColor(Color.parseColor("#1ec59c"));
        ListView listView13 = new ListView(this);
        this.bwxyrxbmul = listView13;
        listView13.setLayoutParams(new LinearLayout.LayoutParams(34, 618));
        this.bwxyrxbmul.setPadding(139, 130, 132, BDLocation.TypeServerError);
        linearLayout.addView(this.bwxyrxbmul);
        this.bwxyrxbmul.setBackgroundColor(Color.parseColor("#a94da8"));
        ListView listView14 = new ListView(this);
        this.brptwzaufa = listView14;
        listView14.setLayoutParams(new LinearLayout.LayoutParams(762, 805));
        this.brptwzaufa.setPadding(50, 195, 72, 135);
        linearLayout.addView(this.brptwzaufa);
        this.brptwzaufa.setBackgroundColor(Color.parseColor("#9f10d7"));
        DatePicker datePicker14 = new DatePicker(this);
        this.iqsicjbxtq = datePicker14;
        datePicker14.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.Custom.TYPE_INT, 1614));
        this.iqsicjbxtq.setPadding(6, 72, 171, 136);
        linearLayout.addView(this.iqsicjbxtq);
        this.iqsicjbxtq.setBackgroundColor(Color.parseColor("#28e942"));
        ToggleButton toggleButton9 = new ToggleButton(this);
        this.pwvmfxvdnw = toggleButton9;
        toggleButton9.setLayoutParams(new LinearLayout.LayoutParams(1406, 97));
        this.pwvmfxvdnw.setPadding(19, 86, 175, 110);
        linearLayout.addView(this.pwvmfxvdnw);
        this.pwvmfxvdnw.setBackgroundColor(Color.parseColor("#d54cce"));
        TextView textView10 = new TextView(this);
        this.gitilwfbec = textView10;
        textView10.setLayoutParams(new LinearLayout.LayoutParams(1157, 1771));
        this.gitilwfbec.setPadding(90, 157, 142, 157);
        linearLayout.addView(this.gitilwfbec);
        this.gitilwfbec.setBackgroundColor(Color.parseColor("#0f36fe"));
        RadioButton radioButton9 = new RadioButton(this);
        this.glakhdevkl = radioButton9;
        radioButton9.setLayoutParams(new LinearLayout.LayoutParams(1520, 1575));
        this.glakhdevkl.setPadding(121, 13, 136, 147);
        linearLayout.addView(this.glakhdevkl);
        this.glakhdevkl.setBackgroundColor(Color.parseColor("#314333"));
        CheckBox checkBox6 = new CheckBox(this);
        this.oydzduyzji = checkBox6;
        checkBox6.setLayoutParams(new LinearLayout.LayoutParams(240, 1836));
        this.oydzduyzji.setPadding(10, 163, 40, 123);
        linearLayout.addView(this.oydzduyzji);
        this.oydzduyzji.setBackgroundColor(Color.parseColor("#24426a"));
        SeekBar seekBar9 = new SeekBar(this);
        this.hykbcttdjc = seekBar9;
        seekBar9.setLayoutParams(new LinearLayout.LayoutParams(1696, 1362));
        this.hykbcttdjc.setPadding(116, 51, 196, 139);
        linearLayout.addView(this.hykbcttdjc);
        this.hykbcttdjc.setBackgroundColor(Color.parseColor("#658f1a"));
        ScrollView scrollView8 = new ScrollView(this);
        this.clhoistpht = scrollView8;
        scrollView8.setLayoutParams(new LinearLayout.LayoutParams(749, 1153));
        this.clhoistpht.setPadding(0, 105, 159, 20);
        linearLayout.addView(this.clhoistpht);
        this.clhoistpht.setBackgroundColor(Color.parseColor("#904cba"));
        ProgressBar progressBar10 = new ProgressBar(this);
        this.yqimluzmkc = progressBar10;
        progressBar10.setLayoutParams(new LinearLayout.LayoutParams(379, 1857));
        this.yqimluzmkc.setPadding(35, 104, 20, 48);
        linearLayout.addView(this.yqimluzmkc);
        this.yqimluzmkc.setBackgroundColor(Color.parseColor("#b51d95"));
        ToggleButton toggleButton10 = new ToggleButton(this);
        this.birbocinjs = toggleButton10;
        toggleButton10.setLayoutParams(new LinearLayout.LayoutParams(1628, 760));
        this.birbocinjs.setPadding(164, 132, 73, 42);
        linearLayout.addView(this.birbocinjs);
        this.birbocinjs.setBackgroundColor(Color.parseColor("#89ea32"));
        LinearLayout linearLayout13 = new LinearLayout(this);
        this.syppbuxuoi = linearLayout13;
        linearLayout13.setLayoutParams(new LinearLayout.LayoutParams(53, 132));
        this.syppbuxuoi.setPadding(BDLocation.TypeServerDecryptError, 132, 134, 199);
        linearLayout.addView(this.syppbuxuoi);
        this.syppbuxuoi.setBackgroundColor(Color.parseColor("#319206"));
        DatePicker datePicker15 = new DatePicker(this);
        this.kqqafgizgv = datePicker15;
        datePicker15.setLayoutParams(new LinearLayout.LayoutParams(471, 1922));
        this.kqqafgizgv.setPadding(100, 79, 169, 171);
        linearLayout.addView(this.kqqafgizgv);
        this.kqqafgizgv.setBackgroundColor(Color.parseColor("#2af0cb"));
        FrameLayout frameLayout15 = new FrameLayout(this);
        this.eqxsomyvvh = frameLayout15;
        frameLayout15.setLayoutParams(new LinearLayout.LayoutParams(1886, 176));
        this.eqxsomyvvh.setPadding(13, 104, 168, 125);
        linearLayout.addView(this.eqxsomyvvh);
        this.eqxsomyvvh.setBackgroundColor(Color.parseColor("#b5f33e"));
        ToggleButton toggleButton11 = new ToggleButton(this);
        this.ucgdcyovpy = toggleButton11;
        toggleButton11.setLayoutParams(new LinearLayout.LayoutParams(802, 372));
        this.ucgdcyovpy.setPadding(67, 101, 34, 156);
        linearLayout.addView(this.ucgdcyovpy);
        this.ucgdcyovpy.setBackgroundColor(Color.parseColor("#5cc3e6"));
        ProgressBar progressBar11 = new ProgressBar(this);
        this.vfkmsjzlax = progressBar11;
        progressBar11.setLayoutParams(new LinearLayout.LayoutParams(1441, 983));
        this.vfkmsjzlax.setPadding(53, 33, 154, 130);
        linearLayout.addView(this.vfkmsjzlax);
        this.vfkmsjzlax.setBackgroundColor(Color.parseColor("#c14ddb"));
        FrameLayout frameLayout16 = new FrameLayout(this);
        this.uggsaognuy = frameLayout16;
        frameLayout16.setLayoutParams(new LinearLayout.LayoutParams(1949, 1636));
        this.uggsaognuy.setPadding(158, 26, 33, 94);
        linearLayout.addView(this.uggsaognuy);
        this.uggsaognuy.setBackgroundColor(Color.parseColor("#d99211"));
        TextView textView11 = new TextView(this);
        this.zxgrbxxpzj = textView11;
        textView11.setLayoutParams(new LinearLayout.LayoutParams(1999, 129));
        this.zxgrbxxpzj.setPadding(144, 149, 14, 48);
        linearLayout.addView(this.zxgrbxxpzj);
        this.zxgrbxxpzj.setBackgroundColor(Color.parseColor("#8726fc"));
        LinearLayout linearLayout14 = new LinearLayout(this);
        this.phlesostpr = linearLayout14;
        linearLayout14.setLayoutParams(new LinearLayout.LayoutParams(1999, 1352));
        this.phlesostpr.setPadding(105, 14, 37, 108);
        linearLayout.addView(this.phlesostpr);
        this.phlesostpr.setBackgroundColor(Color.parseColor("#a5f078"));
        LinearLayout linearLayout15 = new LinearLayout(this);
        this.znljhzwbkk = linearLayout15;
        linearLayout15.setLayoutParams(new LinearLayout.LayoutParams(103, 711));
        this.znljhzwbkk.setPadding(52, 53, 178, 81);
        linearLayout.addView(this.znljhzwbkk);
        this.znljhzwbkk.setBackgroundColor(Color.parseColor("#009878"));
        GridView gridView13 = new GridView(this);
        this.ziagfeijow = gridView13;
        gridView13.setLayoutParams(new LinearLayout.LayoutParams(1339, 411));
        this.ziagfeijow.setPadding(69, 106, 17, 123);
        linearLayout.addView(this.ziagfeijow);
        this.ziagfeijow.setBackgroundColor(Color.parseColor("#2a75a5"));
        RadioButton radioButton10 = new RadioButton(this);
        this.rgbbueegqh = radioButton10;
        radioButton10.setLayoutParams(new LinearLayout.LayoutParams(1535, 211));
        this.rgbbueegqh.setPadding(44, 9, PictureConfig.CHOOSE_REQUEST, 164);
        linearLayout.addView(this.rgbbueegqh);
        this.rgbbueegqh.setBackgroundColor(Color.parseColor("#6f66f0"));
        DatePicker datePicker16 = new DatePicker(this);
        this.pyulkgxxsj = datePicker16;
        datePicker16.setLayoutParams(new LinearLayout.LayoutParams(1166, 649));
        this.pyulkgxxsj.setPadding(187, 82, 24, 97);
        linearLayout.addView(this.pyulkgxxsj);
        this.pyulkgxxsj.setBackgroundColor(Color.parseColor("#ceba01"));
        RadioButton radioButton11 = new RadioButton(this);
        this.mkxmhwriic = radioButton11;
        radioButton11.setLayoutParams(new LinearLayout.LayoutParams(58, 515));
        this.mkxmhwriic.setPadding(191, 192, 59, 81);
        linearLayout.addView(this.mkxmhwriic);
        this.mkxmhwriic.setBackgroundColor(Color.parseColor("#5ff17d"));
        TableLayout tableLayout9 = new TableLayout(this);
        this.hzfqomqggq = tableLayout9;
        tableLayout9.setLayoutParams(new LinearLayout.LayoutParams(621, 1758));
        this.hzfqomqggq.setPadding(56, 178, 174, 63);
        linearLayout.addView(this.hzfqomqggq);
        this.hzfqomqggq.setBackgroundColor(Color.parseColor("#096a3a"));
        TimePicker timePicker13 = new TimePicker(this);
        this.htcziaonnw = timePicker13;
        timePicker13.setLayoutParams(new LinearLayout.LayoutParams(1811, 211));
        this.htcziaonnw.setPadding(150, 54, 67, 40);
        linearLayout.addView(this.htcziaonnw);
        this.htcziaonnw.setBackgroundColor(Color.parseColor("#3e2e92"));
        ListView listView15 = new ListView(this);
        this.dxqvtfndep = listView15;
        listView15.setLayoutParams(new LinearLayout.LayoutParams(474, 1147));
        this.dxqvtfndep.setPadding(122, 26, 4, 89);
        linearLayout.addView(this.dxqvtfndep);
        this.dxqvtfndep.setBackgroundColor(Color.parseColor("#25ac25"));
        TextView textView12 = new TextView(this);
        this.htspjhlsue = textView12;
        textView12.setLayoutParams(new LinearLayout.LayoutParams(79, 326));
        this.htspjhlsue.setPadding(109, 125, 0, 151);
        linearLayout.addView(this.htspjhlsue);
        this.htspjhlsue.setBackgroundColor(Color.parseColor("#dbd30e"));
        FrameLayout frameLayout17 = new FrameLayout(this);
        this.fraseewsac = frameLayout17;
        frameLayout17.setLayoutParams(new LinearLayout.LayoutParams(750, 1394));
        this.fraseewsac.setPadding(88, 146, 18, 41);
        linearLayout.addView(this.fraseewsac);
        this.fraseewsac.setBackgroundColor(Color.parseColor("#db1beb"));
        TableLayout tableLayout10 = new TableLayout(this);
        this.mnzfqnkhxf = tableLayout10;
        tableLayout10.setLayoutParams(new LinearLayout.LayoutParams(1854, 78));
        this.mnzfqnkhxf.setPadding(32, 37, 97, 106);
        linearLayout.addView(this.mnzfqnkhxf);
        this.mnzfqnkhxf.setBackgroundColor(Color.parseColor("#80877f"));
        TableLayout tableLayout11 = new TableLayout(this);
        this.ioevrhzhrj = tableLayout11;
        tableLayout11.setLayoutParams(new LinearLayout.LayoutParams(1231, 213));
        this.ioevrhzhrj.setPadding(189, 47, 141, 136);
        linearLayout.addView(this.ioevrhzhrj);
        this.ioevrhzhrj.setBackgroundColor(Color.parseColor("#6f5735"));
        Switch r26 = new Switch(this);
        this.sdgzaodcen = r26;
        r26.setLayoutParams(new LinearLayout.LayoutParams(281, 1232));
        this.sdgzaodcen.setPadding(39, 140, 181, 153);
        linearLayout.addView(this.sdgzaodcen);
        this.sdgzaodcen.setBackgroundColor(Color.parseColor("#187f5a"));
        CheckBox checkBox7 = new CheckBox(this);
        this.losjoffeif = checkBox7;
        checkBox7.setLayoutParams(new LinearLayout.LayoutParams(1498, ConnectionResult.DRIVE_EXTERNAL_STORAGE_REQUIRED));
        this.losjoffeif.setPadding(76, 189, 50, 101);
        linearLayout.addView(this.losjoffeif);
        this.losjoffeif.setBackgroundColor(Color.parseColor("#009233"));
        Spinner spinner11 = new Spinner(this);
        this.fudcymkltv = spinner11;
        spinner11.setLayoutParams(new LinearLayout.LayoutParams(564, 770));
        this.fudcymkltv.setPadding(121, 0, BDLocation.TypeServerError, 63);
        linearLayout.addView(this.fudcymkltv);
        this.fudcymkltv.setBackgroundColor(Color.parseColor("#cc385f"));
        DatePicker datePicker17 = new DatePicker(this);
        this.kbnhjvqaoe = datePicker17;
        datePicker17.setLayoutParams(new LinearLayout.LayoutParams(713, 1421));
        this.kbnhjvqaoe.setPadding(51, 147, 168, 76);
        linearLayout.addView(this.kbnhjvqaoe);
        this.kbnhjvqaoe.setBackgroundColor(Color.parseColor("#577d81"));
        ViewFlipper viewFlipper10 = new ViewFlipper(this);
        this.gypqerolmc = viewFlipper10;
        viewFlipper10.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.PositionType.TYPE_PERCENT_Y, 29));
        this.gypqerolmc.setPadding(170, 120, 164, 69);
        linearLayout.addView(this.gypqerolmc);
        this.gypqerolmc.setBackgroundColor(Color.parseColor("#cf1146"));
        RelativeLayout relativeLayout9 = new RelativeLayout(this);
        this.aidbpkrike = relativeLayout9;
        relativeLayout9.setLayoutParams(new LinearLayout.LayoutParams(1516, 754));
        this.aidbpkrike.setPadding(107, 51, 105, 25);
        linearLayout.addView(this.aidbpkrike);
        this.aidbpkrike.setBackgroundColor(Color.parseColor("#1f2446"));
        LinearLayout linearLayout16 = new LinearLayout(this);
        this.zarxtslkqh = linearLayout16;
        linearLayout16.setLayoutParams(new LinearLayout.LayoutParams(1975, 1148));
        this.zarxtslkqh.setPadding(BDLocation.TypeServerError, 151, 146, 12);
        linearLayout.addView(this.zarxtslkqh);
        this.zarxtslkqh.setBackgroundColor(Color.parseColor("#cbd3bb"));
        ListView listView16 = new ListView(this);
        this.dmckwfydty = listView16;
        listView16.setLayoutParams(new LinearLayout.LayoutParams(82, 1607));
        this.dmckwfydty.setPadding(181, 128, 159, 163);
        linearLayout.addView(this.dmckwfydty);
        this.dmckwfydty.setBackgroundColor(Color.parseColor("#129523"));
        ViewFlipper viewFlipper11 = new ViewFlipper(this);
        this.igjnfcyala = viewFlipper11;
        viewFlipper11.setLayoutParams(new LinearLayout.LayoutParams(889, 1644));
        this.igjnfcyala.setPadding(88, 122, 58, 153);
        linearLayout.addView(this.igjnfcyala);
        this.igjnfcyala.setBackgroundColor(Color.parseColor("#1538fc"));
        RadioButton radioButton12 = new RadioButton(this);
        this.azbhxxvccg = radioButton12;
        radioButton12.setLayoutParams(new LinearLayout.LayoutParams(1744, 793));
        this.azbhxxvccg.setPadding(5, 158, 170, 163);
        linearLayout.addView(this.azbhxxvccg);
        this.azbhxxvccg.setBackgroundColor(Color.parseColor("#c3ecf9"));
        Button button7 = new Button(this);
        this.bzmgepoiuy = button7;
        button7.setLayoutParams(new LinearLayout.LayoutParams(1645, 1546));
        this.bzmgepoiuy.setPadding(68, 166, 21, 190);
        linearLayout.addView(this.bzmgepoiuy);
        this.bzmgepoiuy.setBackgroundColor(Color.parseColor("#567f45"));
        ToggleButton toggleButton12 = new ToggleButton(this);
        this.pnszuwalzt = toggleButton12;
        toggleButton12.setLayoutParams(new LinearLayout.LayoutParams(1575, 1849));
        this.pnszuwalzt.setPadding(136, 86, 191, 51);
        linearLayout.addView(this.pnszuwalzt);
        this.pnszuwalzt.setBackgroundColor(Color.parseColor("#0bf398"));
        RelativeLayout relativeLayout10 = new RelativeLayout(this);
        this.cflzjkvyab = relativeLayout10;
        relativeLayout10.setLayoutParams(new LinearLayout.LayoutParams(1286, 360));
        this.cflzjkvyab.setPadding(150, 195, 169, 9);
        linearLayout.addView(this.cflzjkvyab);
        this.cflzjkvyab.setBackgroundColor(Color.parseColor("#59020b"));
        RatingBar ratingBar11 = new RatingBar(this);
        this.kkdnagyqee = ratingBar11;
        ratingBar11.setLayoutParams(new LinearLayout.LayoutParams(1521, 584));
        this.kkdnagyqee.setPadding(BDLocation.TypeCoarseLocation, 144, 120, 64);
        linearLayout.addView(this.kkdnagyqee);
        this.kkdnagyqee.setBackgroundColor(Color.parseColor("#948c12"));
        ViewFlipper viewFlipper12 = new ViewFlipper(this);
        this.fnzdzleqpv = viewFlipper12;
        viewFlipper12.setLayoutParams(new LinearLayout.LayoutParams(1079, 1801));
        this.fnzdzleqpv.setPadding(29, 100, 172, 173);
        linearLayout.addView(this.fnzdzleqpv);
        this.fnzdzleqpv.setBackgroundColor(Color.parseColor("#311296"));
        ProgressBar progressBar12 = new ProgressBar(this);
        this.mosartmcrm = progressBar12;
        progressBar12.setLayoutParams(new LinearLayout.LayoutParams(1219, 1289));
        this.mosartmcrm.setPadding(86, 24, 50, 120);
        linearLayout.addView(this.mosartmcrm);
        this.mosartmcrm.setBackgroundColor(Color.parseColor("#e046df"));
        TimePicker timePicker14 = new TimePicker(this);
        this.dyevqhozqa = timePicker14;
        timePicker14.setLayoutParams(new LinearLayout.LayoutParams(278, 353));
        this.dyevqhozqa.setPadding(158, 173, 150, 195);
        linearLayout.addView(this.dyevqhozqa);
        this.dyevqhozqa.setBackgroundColor(Color.parseColor("#7ee2f5"));
        ViewFlipper viewFlipper13 = new ViewFlipper(this);
        this.mnlaiydlpi = viewFlipper13;
        viewFlipper13.setLayoutParams(new LinearLayout.LayoutParams(1770, 466));
        this.mnlaiydlpi.setPadding(150, 19, 152, 109);
        linearLayout.addView(this.mnlaiydlpi);
        this.mnlaiydlpi.setBackgroundColor(Color.parseColor("#d84f39"));
        EditText editText8 = new EditText(this);
        this.thpkagztlo = editText8;
        editText8.setLayoutParams(new LinearLayout.LayoutParams(1449, 1015));
        this.thpkagztlo.setPadding(187, 20, 130, 100);
        linearLayout.addView(this.thpkagztlo);
        this.thpkagztlo.setBackgroundColor(Color.parseColor("#d88a09"));
        ViewFlipper viewFlipper14 = new ViewFlipper(this);
        this.catlutmfej = viewFlipper14;
        viewFlipper14.setLayoutParams(new LinearLayout.LayoutParams(737, 1964));
        this.catlutmfej.setPadding(85, 119, 187, 120);
        linearLayout.addView(this.catlutmfej);
        this.catlutmfej.setBackgroundColor(Color.parseColor("#61b3cd"));
        Switch r27 = new Switch(this);
        this.gqzodpjvao = r27;
        r27.setLayoutParams(new LinearLayout.LayoutParams(125, 1571));
        this.gqzodpjvao.setPadding(174, 97, 92, 60);
        linearLayout.addView(this.gqzodpjvao);
        this.gqzodpjvao.setBackgroundColor(Color.parseColor("#78b5b2"));
        RatingBar ratingBar12 = new RatingBar(this);
        this.fkqxzztjwv = ratingBar12;
        ratingBar12.setLayoutParams(new LinearLayout.LayoutParams(1592, 1535));
        this.fkqxzztjwv.setPadding(53, 127, 93, 176);
        linearLayout.addView(this.fkqxzztjwv);
        this.fkqxzztjwv.setBackgroundColor(Color.parseColor("#abcc31"));
        SeekBar seekBar10 = new SeekBar(this);
        this.xgsusprgfc = seekBar10;
        seekBar10.setLayoutParams(new LinearLayout.LayoutParams(1128, 1697));
        this.xgsusprgfc.setPadding(85, 23, 43, 1);
        linearLayout.addView(this.xgsusprgfc);
        this.xgsusprgfc.setBackgroundColor(Color.parseColor("#8510e6"));
        ViewFlipper viewFlipper15 = new ViewFlipper(this);
        this.czoroewfur = viewFlipper15;
        viewFlipper15.setLayoutParams(new LinearLayout.LayoutParams(1213, 1527));
        this.czoroewfur.setPadding(118, 93, 32, 58);
        linearLayout.addView(this.czoroewfur);
        this.czoroewfur.setBackgroundColor(Color.parseColor("#ff2af0"));
        RadioButton radioButton13 = new RadioButton(this);
        this.wassifabtn = radioButton13;
        radioButton13.setLayoutParams(new LinearLayout.LayoutParams(893, 365));
        this.wassifabtn.setPadding(62, 41, BDLocation.TypeServerError, 187);
        linearLayout.addView(this.wassifabtn);
        this.wassifabtn.setBackgroundColor(Color.parseColor("#8d01d8"));
        SeekBar seekBar11 = new SeekBar(this);
        this.xkbitfzwia = seekBar11;
        seekBar11.setLayoutParams(new LinearLayout.LayoutParams(1301, 1923));
        this.xkbitfzwia.setPadding(172, 54, 82, 70);
        linearLayout.addView(this.xkbitfzwia);
        this.xkbitfzwia.setBackgroundColor(Color.parseColor("#5817b3"));
        ToggleButton toggleButton13 = new ToggleButton(this);
        this.dvhuvevhda = toggleButton13;
        toggleButton13.setLayoutParams(new LinearLayout.LayoutParams(1494, 229));
        this.dvhuvevhda.setPadding(3, 174, 18, 35);
        linearLayout.addView(this.dvhuvevhda);
        this.dvhuvevhda.setBackgroundColor(Color.parseColor("#397fd4"));
    }
}
