package com.device.watch.com.device.watch.alupskmqcf;

import android.app.Activity;
import android.graphics.Color;
import android.os.Bundle;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.CheckBox;
import android.widget.DatePicker;
import android.widget.EditText;
import android.widget.FrameLayout;
import android.widget.GridView;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ListView;
import android.widget.ProgressBar;
import android.widget.RadioButton;
import android.widget.RatingBar;
import android.widget.RelativeLayout;
import android.widget.ScrollView;
import android.widget.SeekBar;
import android.widget.Spinner;
import android.widget.Switch;
import android.widget.TableLayout;
import android.widget.TextView;
import android.widget.TimePicker;
import android.widget.ToggleButton;
import android.widget.ViewFlipper;
import androidx.constraintlayout.core.motion.utils.TypedValues;
import androidx.core.view.PointerIconCompat;
import com.baidu.location.BDLocation;
import com.google.zxing.pdf417.PDF417Common;
import com.king.zxing.util.CodeUtils;
import com.luck.picture.lib.config.PictureConfig;
import com.realsil.sdk.bbpro.core.protocol.Contract;
import com.yalantis.ucrop.view.CropImageView;
import okhttp3.internal.ws.WebSocketProtocol;

/* loaded from: classes.dex */
public class YvfeqdvdfjfActivity extends Activity {
    ViewFlipper aitfirihto;
    DatePicker ajyrdwhggk;
    Switch aqhpwnjvhl;
    RatingBar aukwndqjag;
    ViewFlipper awcbusnllz;
    ProgressBar awcshhzklm;
    SeekBar axqfpsernj;
    SeekBar aymqytqxcd;
    TableLayout bayviksddu;
    CheckBox bbbddiwojq;
    GridView bddtzuwrex;
    EditText bdtrrrhpeg;
    LinearLayout bdwpmxesuz;
    FrameLayout behphejxbh;
    Switch bhhvtkixpi;
    Spinner blvktljbkb;
    ToggleButton bnoypohugt;
    EditText brhbszxurm;
    RelativeLayout bzkwjistge;
    CheckBox cikoxzybpu;
    EditText cixifqgyvm;
    ToggleButton cjguoebhhj;
    GridView clogjkfyru;
    GridView cmovecjrmi;
    RatingBar cnydzlbwhh;
    TimePicker cockecxlau;
    RelativeLayout cpffhpwsvx;
    TextView csofwxxdhk;
    RatingBar czgosnyxlq;
    Spinner dbkhzdyhwc;
    ProgressBar ddvnrzppyu;
    ProgressBar delpvsnxzy;
    DatePicker dhdizfgogs;
    FrameLayout dqskyzxjul;
    ViewFlipper dvpyjydxik;
    ImageView eaodpsctux;
    SeekBar ediostrgny;
    GridView eenhcghkwb;
    DatePicker efallnnimv;
    TableLayout ehxczjmjxr;
    ProgressBar eiqupbxkuq;
    ViewFlipper eitfidsylv;
    GridView ekjmztrwbs;
    ListView ekuqclzasl;
    ImageView enwuzlzyzl;
    TimePicker eofhtjrwrq;
    Spinner ezjoovfsbp;
    CheckBox faaakxzpmh;
    Spinner fgdnhjtzys;
    ProgressBar fgtvdhmgqx;
    TextView fihvdlkkpm;
    RatingBar flanitghhh;
    Button flkznuepgx;
    Button flmmfgzake;
    EditText fnsslevxho;
    ScrollView foysznjvoa;
    Button fribvjwzgg;
    TableLayout frymcxcgju;
    TextView gavrckpzrf;
    TableLayout gayystznbr;
    LinearLayout gbpnhuciry;
    ScrollView gqimvbnnaw;
    ViewFlipper greolrdaop;
    DatePicker grgxtxprwi;
    GridView grkfpvpecl;
    TimePicker hapicimrjb;
    CheckBox hbednsamya;
    Button hfhoubsgqh;
    RelativeLayout hgqgqugvmm;
    TimePicker hlqkcebtwu;
    TableLayout hoqeeaxetg;
    TimePicker hqwgbuncfy;
    LinearLayout hsnacyuuxx;
    TextView htulyvfjii;
    CheckBox hyzukxsojc;
    RelativeLayout hzcevzvzhj;
    Spinner iedtdtwvai;
    GridView ijtzxtmdrx;
    LinearLayout iqapdcvioh;
    SeekBar itkmcqhmnc;
    Button ivirstaqju;
    EditText ivkyooomsh;
    LinearLayout izadutdsiu;
    TextView izyiguvqsn;
    ImageView jacyrfqygo;
    RadioButton jberfcfxcs;
    LinearLayout jcfrwxjbuo;
    FrameLayout jdrlyfqxgx;
    RatingBar jhhuhvkcsy;
    CheckBox jjkdsbdnfm;
    LinearLayout jjmastulkd;
    CheckBox jkgufmdyim;
    RelativeLayout jkubdxdjcu;
    Switch jpiqsjplbr;
    ImageView jsatwqixjy;
    GridView jsxypgqqqe;
    Button kfttwpdetw;
    DatePicker kkldipddtg;
    SeekBar kmjifetidf;
    Switch krsvqnvpad;
    RadioButton ktccorqrnp;
    SeekBar kvjhjsqjly;
    ProgressBar kxgoulimma;
    RelativeLayout lazxrddceu;
    Spinner lcojrjjwiw;
    LinearLayout lfckdfrzws;
    RelativeLayout lkhhpuvdlu;
    ScrollView llddyawqbf;
    RatingBar lrgstxcgdh;
    SeekBar ltlylteyeu;
    TextView luxzmlfksu;
    TimePicker lwfwbximde;
    GridView lydlsyubiw;
    RatingBar lzfxobceiy;
    RadioButton lzvzxwkmnx;
    TableLayout meemqcgqmi;
    Switch milabjzmwk;
    CheckBox msfnsbenvx;
    LinearLayout mxciyyvurw;
    FrameLayout myyijtbinn;
    TableLayout mzkvsfnkve;
    TimePicker niysuxwavn;
    ScrollView nnibgmsnep;
    Switch nuiqwkuvrn;
    Button nvnitptlef;
    ProgressBar oamenzpsdm;
    ProgressBar oaqmpovdrn;
    ListView oeknyyacbo;
    ImageView oltbcgsvwx;
    TableLayout otlvsmwpur;
    ImageView ouquzpqhqd;
    RelativeLayout owcpojsoom;
    TimePicker oxvfovasyo;
    FrameLayout oyljhvrcpf;
    ProgressBar peegtkkvwd;
    FrameLayout phggllvjpy;
    ListView pnbxbhowdp;
    ViewFlipper pouzhredag;
    Button pqegwywvjy;
    TimePicker psgihcnhrd;
    SeekBar pwmhbmowwm;
    CheckBox pwxciglrge;
    TimePicker pxmhcrugtj;
    FrameLayout pzkogsqdox;
    RatingBar pzlognkdyn;
    TimePicker qgckqvumyk;
    ViewFlipper qpjzaberuu;
    FrameLayout qqsaajxvtk;
    DatePicker qucqneahou;
    Spinner qxnbnucjev;
    ScrollView qygomagdjs;
    FrameLayout qzjmzaorhg;
    Spinner reixxlyzld;
    Button resrnzalhi;
    LinearLayout rgbtddbgpl;
    DatePicker rgkznqgdws;
    CheckBox rhsgzfxhwe;
    GridView rkuewnoxdh;
    ProgressBar rrnroexhws;
    ScrollView rttmzpmwnr;
    FrameLayout rwednyazfg;
    ListView rwmkgvzqfs;
    ToggleButton rwuyrdpeuw;
    LinearLayout sansaasodu;
    EditText sjohgwmfwk;
    ScrollView sovksgcvwd;
    RatingBar sufyjjtoyy;
    DatePicker swopsfyywc;
    GridView sxwojfabis;
    GridView tawldcheaw;
    RatingBar tjwwiuttyg;
    RadioButton todoccyuqs;
    Switch tpsgmoxupq;
    EditText tqdsgkduvk;
    GridView tqqmewwyys;
    FrameLayout trweudhxhn;
    DatePicker ttlsdwaium;
    ImageView ubsuyadaxj;
    Button ujhsbqdgdq;
    TimePicker ukvqstztaq;
    DatePicker ukzwqltbff;
    GridView uqgfranwjo;
    RadioButton urnzuxiawb;
    GridView usgwbresdw;
    ViewFlipper uthuardwpo;
    TextView uvsrpnvvrd;
    GridView vihwagcvvt;
    EditText vjlnjfzwti;
    CheckBox vslpaeewxe;
    TimePicker vupghpggul;
    RatingBar vvmajehcsb;
    LinearLayout vwnvbvxpha;
    CheckBox vxbplztdgu;
    ToggleButton vxkliogelp;
    ListView vzsqiehgnq;
    RelativeLayout waewjryewl;
    DatePicker wepokohhrp;
    ListView wkaxqkuuob;
    DatePicker wknzgwmpxx;
    ToggleButton wmkfvjqewy;
    RatingBar wtbwbmisev;
    ListView wumtcsgvmm;
    EditText wzcydmarrb;
    GridView xbfazlhfzj;
    CheckBox xdunyrdsfl;
    RelativeLayout xflgpuoswb;
    Button xhcpdxyalv;
    TableLayout xjrjzrdcep;
    ListView xpljmtrocp;
    TextView xrbxfzkwrb;
    TimePicker xshkktipbi;
    TextView xtwlsjijcl;
    RadioButton xyfxoujsny;
    ToggleButton xygymxsnni;
    Spinner ycxdoscawn;
    CheckBox ydcehkvpnr;
    RatingBar yeavwsfeze;
    Switch yefagqwwjl;
    ScrollView ygnscqaqcj;
    DatePicker yjfewezngm;
    ImageView ykqmevxaxl;
    ToggleButton ywrjdbqfvz;
    LinearLayout zaehdwlslv;
    CheckBox zbmzpznpwj;
    Spinner zbnariaerj;
    DatePicker zbpsmbtwpd;
    CheckBox zevlsyvxnz;
    GridView zhpybtcopr;
    ListView zuhmhtgspb;
    ToggleButton zvfiajldkx;
    TextView zzcdcndijp;

    @Override // android.app.Activity
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        LinearLayout linearLayout = new LinearLayout(this);
        setContentView(linearLayout);
        linearLayout.setLayoutParams(new ViewGroup.LayoutParams(-1, -1));
        linearLayout.setOrientation(1);
        linearLayout.setBackgroundColor(Color.parseColor("#bc9a00"));
        Spinner spinner = new Spinner(this);
        this.blvktljbkb = spinner;
        spinner.setLayoutParams(new LinearLayout.LayoutParams(1482, 791));
        this.blvktljbkb.setPadding(166, 91, 111, 142);
        linearLayout.addView(this.blvktljbkb);
        this.blvktljbkb.setBackgroundColor(Color.parseColor("#a7af96"));
        CheckBox checkBox = new CheckBox(this);
        this.msfnsbenvx = checkBox;
        checkBox.setLayoutParams(new LinearLayout.LayoutParams(631, 150));
        this.msfnsbenvx.setPadding(195, 169, 128, 109);
        linearLayout.addView(this.msfnsbenvx);
        this.msfnsbenvx.setBackgroundColor(Color.parseColor("#c1e3f9"));
        GridView gridView = new GridView(this);
        this.cmovecjrmi = gridView;
        gridView.setLayoutParams(new LinearLayout.LayoutParams(1218, 1283));
        this.cmovecjrmi.setPadding(87, 158, 128, 184);
        linearLayout.addView(this.cmovecjrmi);
        this.cmovecjrmi.setBackgroundColor(Color.parseColor("#3876ef"));
        Switch r2 = new Switch(this);
        this.jpiqsjplbr = r2;
        r2.setLayoutParams(new LinearLayout.LayoutParams(1543, 642));
        this.jpiqsjplbr.setPadding(14, 67, 49, 56);
        linearLayout.addView(this.jpiqsjplbr);
        this.jpiqsjplbr.setBackgroundColor(Color.parseColor("#9bb07a"));
        RatingBar ratingBar = new RatingBar(this);
        this.cnydzlbwhh = ratingBar;
        ratingBar.setLayoutParams(new LinearLayout.LayoutParams(3, 821));
        this.cnydzlbwhh.setPadding(16, 55, 90, 141);
        linearLayout.addView(this.cnydzlbwhh);
        this.cnydzlbwhh.setBackgroundColor(Color.parseColor("#0120f0"));
        ProgressBar progressBar = new ProgressBar(this);
        this.ddvnrzppyu = progressBar;
        progressBar.setLayoutParams(new LinearLayout.LayoutParams(1768, 1115));
        this.ddvnrzppyu.setPadding(153, 70, 192, 6);
        linearLayout.addView(this.ddvnrzppyu);
        this.ddvnrzppyu.setBackgroundColor(Color.parseColor("#552c0a"));
        EditText editText = new EditText(this);
        this.brhbszxurm = editText;
        editText.setLayoutParams(new LinearLayout.LayoutParams(1060, 1163));
        this.brhbszxurm.setPadding(28, 95, 48, 42);
        linearLayout.addView(this.brhbszxurm);
        this.brhbszxurm.setBackgroundColor(Color.parseColor("#2b0f96"));
        RatingBar ratingBar2 = new RatingBar(this);
        this.pzlognkdyn = ratingBar2;
        ratingBar2.setLayoutParams(new LinearLayout.LayoutParams(1417, 132));
        this.pzlognkdyn.setPadding(119, 138, 42, 142);
        linearLayout.addView(this.pzlognkdyn);
        this.pzlognkdyn.setBackgroundColor(Color.parseColor("#bb20e2"));
        FrameLayout frameLayout = new FrameLayout(this);
        this.trweudhxhn = frameLayout;
        frameLayout.setLayoutParams(new LinearLayout.LayoutParams(1840, 171));
        this.trweudhxhn.setPadding(BDLocation.TypeServerDecryptError, 139, 152, 140);
        linearLayout.addView(this.trweudhxhn);
        this.trweudhxhn.setBackground(new Yuousvonpem());
        SeekBar seekBar = new SeekBar(this);
        this.aymqytqxcd = seekBar;
        seekBar.setLayoutParams(new LinearLayout.LayoutParams(1881, 978));
        this.aymqytqxcd.setPadding(186, 121, 2, 81);
        linearLayout.addView(this.aymqytqxcd);
        this.aymqytqxcd.setBackgroundColor(Color.parseColor("#576007"));
        FrameLayout frameLayout2 = new FrameLayout(this);
        this.qqsaajxvtk = frameLayout2;
        frameLayout2.setLayoutParams(new LinearLayout.LayoutParams(1851, CropImageView.DEFAULT_IMAGE_TO_CROP_BOUNDS_ANIM_DURATION));
        this.qqsaajxvtk.setPadding(45, 41, 96, 135);
        linearLayout.addView(this.qqsaajxvtk);
        this.qqsaajxvtk.setBackgroundColor(Color.parseColor("#764803"));
        Button button = new Button(this);
        this.xhcpdxyalv = button;
        button.setLayoutParams(new LinearLayout.LayoutParams(576, 1645));
        this.xhcpdxyalv.setPadding(6, 97, 136, 187);
        linearLayout.addView(this.xhcpdxyalv);
        this.xhcpdxyalv.setBackgroundColor(Color.parseColor("#1c0df2"));
        ProgressBar progressBar2 = new ProgressBar(this);
        this.eiqupbxkuq = progressBar2;
        progressBar2.setLayoutParams(new LinearLayout.LayoutParams(129, 1772));
        this.eiqupbxkuq.setPadding(191, 170, 34, 7);
        linearLayout.addView(this.eiqupbxkuq);
        this.eiqupbxkuq.setBackgroundColor(Color.parseColor("#cf7333"));
        ToggleButton toggleButton = new ToggleButton(this);
        this.xygymxsnni = toggleButton;
        toggleButton.setLayoutParams(new LinearLayout.LayoutParams(920, 28));
        this.xygymxsnni.setPadding(85, 3, 78, 64);
        linearLayout.addView(this.xygymxsnni);
        this.xygymxsnni.setBackgroundColor(Color.parseColor("#fe726c"));
        Spinner spinner2 = new Spinner(this);
        this.lcojrjjwiw = spinner2;
        spinner2.setLayoutParams(new LinearLayout.LayoutParams(1732, 842));
        this.lcojrjjwiw.setPadding(130, 175, 50, 33);
        linearLayout.addView(this.lcojrjjwiw);
        this.lcojrjjwiw.setBackgroundColor(Color.parseColor("#6a5187"));
        ImageView imageView = new ImageView(this);
        this.ubsuyadaxj = imageView;
        imageView.setLayoutParams(new LinearLayout.LayoutParams(1903, TypedValues.MotionType.TYPE_PATHMOTION_ARC));
        this.ubsuyadaxj.setPadding(165, BDLocation.TypeNetWorkLocation, 68, BDLocation.TypeServerError);
        linearLayout.addView(this.ubsuyadaxj);
        this.ubsuyadaxj.setBackgroundColor(Color.parseColor("#9479f3"));
        ProgressBar progressBar3 = new ProgressBar(this);
        this.delpvsnxzy = progressBar3;
        progressBar3.setLayoutParams(new LinearLayout.LayoutParams(852, 333));
        this.delpvsnxzy.setPadding(110, 54, 27, 89);
        linearLayout.addView(this.delpvsnxzy);
        this.delpvsnxzy.setBackgroundColor(Color.parseColor("#a0f940"));
        LinearLayout linearLayout2 = new LinearLayout(this);
        this.gbpnhuciry = linearLayout2;
        linearLayout2.setLayoutParams(new LinearLayout.LayoutParams(1158, 320));
        this.gbpnhuciry.setPadding(87, 96, 111, 179);
        linearLayout.addView(this.gbpnhuciry);
        this.gbpnhuciry.setBackgroundColor(Color.parseColor("#548a86"));
        ListView listView = new ListView(this);
        this.wkaxqkuuob = listView;
        listView.setLayoutParams(new LinearLayout.LayoutParams(1171, 1323));
        this.wkaxqkuuob.setPadding(117, 50, 24, 47);
        linearLayout.addView(this.wkaxqkuuob);
        this.wkaxqkuuob.setBackgroundColor(Color.parseColor("#9c2705"));
        TableLayout tableLayout = new TableLayout(this);
        this.otlvsmwpur = tableLayout;
        tableLayout.setLayoutParams(new LinearLayout.LayoutParams(1823, 773));
        this.otlvsmwpur.setPadding(13, 141, 27, 95);
        linearLayout.addView(this.otlvsmwpur);
        this.otlvsmwpur.setBackgroundColor(Color.parseColor("#337158"));
        LinearLayout linearLayout3 = new LinearLayout(this);
        this.bdwpmxesuz = linearLayout3;
        linearLayout3.setLayoutParams(new LinearLayout.LayoutParams(837, 1991));
        this.bdwpmxesuz.setPadding(65, 54, 25, 75);
        linearLayout.addView(this.bdwpmxesuz);
        this.bdwpmxesuz.setBackgroundColor(Color.parseColor("#4189b0"));
        CheckBox checkBox2 = new CheckBox(this);
        this.hbednsamya = checkBox2;
        checkBox2.setLayoutParams(new LinearLayout.LayoutParams(543, 717));
        this.hbednsamya.setPadding(178, BDLocation.TypeServerDecryptError, 106, 179);
        linearLayout.addView(this.hbednsamya);
        this.hbednsamya.setBackgroundColor(Color.parseColor("#3423db"));
        RelativeLayout relativeLayout = new RelativeLayout(this);
        this.bzkwjistge = relativeLayout;
        relativeLayout.setLayoutParams(new LinearLayout.LayoutParams(1391, 30));
        this.bzkwjistge.setPadding(112, 103, 118, 104);
        linearLayout.addView(this.bzkwjistge);
        this.bzkwjistge.setBackgroundColor(Color.parseColor("#abc0b9"));
        RatingBar ratingBar3 = new RatingBar(this);
        this.tjwwiuttyg = ratingBar3;
        ratingBar3.setLayoutParams(new LinearLayout.LayoutParams(302, 864));
        this.tjwwiuttyg.setPadding(37, 152, 131, 164);
        linearLayout.addView(this.tjwwiuttyg);
        this.tjwwiuttyg.setBackgroundColor(Color.parseColor("#cf97c6"));
        SeekBar seekBar2 = new SeekBar(this);
        this.axqfpsernj = seekBar2;
        seekBar2.setLayoutParams(new LinearLayout.LayoutParams(361, 1892));
        this.axqfpsernj.setPadding(17, 133, 114, 12);
        linearLayout.addView(this.axqfpsernj);
        this.axqfpsernj.setBackgroundColor(Color.parseColor("#7240c7"));
        Spinner spinner3 = new Spinner(this);
        this.ycxdoscawn = spinner3;
        spinner3.setLayoutParams(new LinearLayout.LayoutParams(211, 1074));
        this.ycxdoscawn.setPadding(63, 133, 124, 86);
        linearLayout.addView(this.ycxdoscawn);
        this.ycxdoscawn.setBackgroundColor(Color.parseColor("#ba5218"));
        RatingBar ratingBar4 = new RatingBar(this);
        this.flanitghhh = ratingBar4;
        ratingBar4.setLayoutParams(new LinearLayout.LayoutParams(252, 377));
        this.flanitghhh.setPadding(61, 97, 10, 148);
        linearLayout.addView(this.flanitghhh);
        this.flanitghhh.setBackgroundColor(Color.parseColor("#7d7363"));
        Button button2 = new Button(this);
        this.flmmfgzake = button2;
        button2.setLayoutParams(new LinearLayout.LayoutParams(1593, 1743));
        this.flmmfgzake.setPadding(97, 38, 66, 101);
        linearLayout.addView(this.flmmfgzake);
        this.flmmfgzake.setBackgroundColor(Color.parseColor("#c2f800"));
        ListView listView2 = new ListView(this);
        this.ekuqclzasl = listView2;
        listView2.setLayoutParams(new LinearLayout.LayoutParams(1381, 1033));
        this.ekuqclzasl.setPadding(176, 22, 180, 123);
        linearLayout.addView(this.ekuqclzasl);
        this.ekuqclzasl.setBackgroundColor(Color.parseColor("#11aa48"));
        LinearLayout linearLayout4 = new LinearLayout(this);
        this.iqapdcvioh = linearLayout4;
        linearLayout4.setLayoutParams(new LinearLayout.LayoutParams(637, 942));
        this.iqapdcvioh.setPadding(16, 76, 124, 149);
        linearLayout.addView(this.iqapdcvioh);
        this.iqapdcvioh.setBackgroundColor(Color.parseColor("#a0d51c"));
        RelativeLayout relativeLayout2 = new RelativeLayout(this);
        this.lazxrddceu = relativeLayout2;
        relativeLayout2.setLayoutParams(new LinearLayout.LayoutParams(1857, 774));
        this.lazxrddceu.setPadding(173, 147, 194, 115);
        linearLayout.addView(this.lazxrddceu);
        this.lazxrddceu.setBackgroundColor(Color.parseColor("#f0857b"));
        RatingBar ratingBar5 = new RatingBar(this);
        this.czgosnyxlq = ratingBar5;
        ratingBar5.setLayoutParams(new LinearLayout.LayoutParams(1070, 1105));
        this.czgosnyxlq.setPadding(26, 130, 28, 80);
        linearLayout.addView(this.czgosnyxlq);
        this.czgosnyxlq.setBackgroundColor(Color.parseColor("#91c705"));
        TimePicker timePicker = new TimePicker(this);
        this.lwfwbximde = timePicker;
        timePicker.setLayoutParams(new LinearLayout.LayoutParams(992, 590));
        this.lwfwbximde.setPadding(198, 70, 117, 25);
        linearLayout.addView(this.lwfwbximde);
        this.lwfwbximde.setBackgroundColor(Color.parseColor("#e3c081"));
        ToggleButton toggleButton2 = new ToggleButton(this);
        this.bnoypohugt = toggleButton2;
        toggleButton2.setLayoutParams(new LinearLayout.LayoutParams(812, 147));
        this.bnoypohugt.setPadding(30, 196, 62, 112);
        linearLayout.addView(this.bnoypohugt);
        this.bnoypohugt.setBackgroundColor(Color.parseColor("#3844c5"));
        GridView gridView2 = new GridView(this);
        this.rkuewnoxdh = gridView2;
        gridView2.setLayoutParams(new LinearLayout.LayoutParams(1299, 1115));
        this.rkuewnoxdh.setPadding(26, 177, 130, 75);
        linearLayout.addView(this.rkuewnoxdh);
        this.rkuewnoxdh.setBackgroundColor(Color.parseColor("#331e03"));
        ProgressBar progressBar4 = new ProgressBar(this);
        this.rrnroexhws = progressBar4;
        progressBar4.setLayoutParams(new LinearLayout.LayoutParams(570, 1335));
        this.rrnroexhws.setPadding(128, 88, 112, 63);
        linearLayout.addView(this.rrnroexhws);
        this.rrnroexhws.setBackgroundColor(Color.parseColor("#f0786d"));
        RatingBar ratingBar6 = new RatingBar(this);
        this.lrgstxcgdh = ratingBar6;
        ratingBar6.setLayoutParams(new LinearLayout.LayoutParams(94, 140));
        this.lrgstxcgdh.setPadding(174, 127, 113, 20);
        linearLayout.addView(this.lrgstxcgdh);
        this.lrgstxcgdh.setBackgroundColor(Color.parseColor("#fd2b37"));
        Spinner spinner4 = new Spinner(this);
        this.ezjoovfsbp = spinner4;
        spinner4.setLayoutParams(new LinearLayout.LayoutParams(125, 1278));
        this.ezjoovfsbp.setPadding(172, 102, 193, 4);
        linearLayout.addView(this.ezjoovfsbp);
        this.ezjoovfsbp.setBackgroundColor(Color.parseColor("#4815c3"));
        SeekBar seekBar3 = new SeekBar(this);
        this.kmjifetidf = seekBar3;
        seekBar3.setLayoutParams(new LinearLayout.LayoutParams(1287, 1247));
        this.kmjifetidf.setPadding(125, 86, 2, 197);
        linearLayout.addView(this.kmjifetidf);
        this.kmjifetidf.setBackgroundColor(Color.parseColor("#52097e"));
        RadioButton radioButton = new RadioButton(this);
        this.todoccyuqs = radioButton;
        radioButton.setLayoutParams(new LinearLayout.LayoutParams(1627, 1855));
        this.todoccyuqs.setPadding(166, 122, 91, 136);
        linearLayout.addView(this.todoccyuqs);
        this.todoccyuqs.setBackgroundColor(Color.parseColor("#e4a92c"));
        DatePicker datePicker = new DatePicker(this);
        this.dhdizfgogs = datePicker;
        datePicker.setLayoutParams(new LinearLayout.LayoutParams(742, 889));
        this.dhdizfgogs.setPadding(24, 133, 55, 100);
        linearLayout.addView(this.dhdizfgogs);
        this.dhdizfgogs.setBackgroundColor(Color.parseColor("#49c5e3"));
        ToggleButton toggleButton3 = new ToggleButton(this);
        this.ywrjdbqfvz = toggleButton3;
        toggleButton3.setLayoutParams(new LinearLayout.LayoutParams(1581, 383));
        this.ywrjdbqfvz.setPadding(33, 96, 137, 171);
        linearLayout.addView(this.ywrjdbqfvz);
        this.ywrjdbqfvz.setBackgroundColor(Color.parseColor("#14b9eb"));
        GridView gridView3 = new GridView(this);
        this.vihwagcvvt = gridView3;
        gridView3.setLayoutParams(new LinearLayout.LayoutParams(1235, 1883));
        this.vihwagcvvt.setPadding(192, 14, 149, 47);
        linearLayout.addView(this.vihwagcvvt);
        this.vihwagcvvt.setBackgroundColor(Color.parseColor("#543121"));
        CheckBox checkBox3 = new CheckBox(this);
        this.xdunyrdsfl = checkBox3;
        checkBox3.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.AttributesType.TYPE_PIVOT_TARGET, 1658));
        this.xdunyrdsfl.setPadding(30, 110, 106, 178);
        linearLayout.addView(this.xdunyrdsfl);
        this.xdunyrdsfl.setBackgroundColor(Color.parseColor("#6a790a"));
        TimePicker timePicker2 = new TimePicker(this);
        this.oxvfovasyo = timePicker2;
        timePicker2.setLayoutParams(new LinearLayout.LayoutParams(1036, 157));
        this.oxvfovasyo.setPadding(120, 11, 83, BDLocation.TypeNetWorkLocation);
        linearLayout.addView(this.oxvfovasyo);
        this.oxvfovasyo.setBackgroundColor(Color.parseColor("#706e3e"));
        GridView gridView4 = new GridView(this);
        this.usgwbresdw = gridView4;
        gridView4.setLayoutParams(new LinearLayout.LayoutParams(346, 1974));
        this.usgwbresdw.setPadding(0, 76, 100, 19);
        linearLayout.addView(this.usgwbresdw);
        this.usgwbresdw.setBackgroundColor(Color.parseColor("#cd206b"));
        DatePicker datePicker2 = new DatePicker(this);
        this.wepokohhrp = datePicker2;
        datePicker2.setLayoutParams(new LinearLayout.LayoutParams(1453, 1957));
        this.wepokohhrp.setPadding(132, 156, 81, 186);
        linearLayout.addView(this.wepokohhrp);
        this.wepokohhrp.setBackgroundColor(Color.parseColor("#4dbfcc"));
        RadioButton radioButton2 = new RadioButton(this);
        this.jberfcfxcs = radioButton2;
        radioButton2.setLayoutParams(new LinearLayout.LayoutParams(465, 214));
        this.jberfcfxcs.setPadding(151, 165, 19, 190);
        linearLayout.addView(this.jberfcfxcs);
        this.jberfcfxcs.setBackgroundColor(Color.parseColor("#567848"));
        TextView textView = new TextView(this);
        this.zzcdcndijp = textView;
        textView.setLayoutParams(new LinearLayout.LayoutParams(614, 1664));
        this.zzcdcndijp.setPadding(189, 102, 139, 9);
        linearLayout.addView(this.zzcdcndijp);
        this.zzcdcndijp.setBackgroundColor(Color.parseColor("#8fb555"));
        TextView textView2 = new TextView(this);
        this.luxzmlfksu = textView2;
        textView2.setLayoutParams(new LinearLayout.LayoutParams(994, 1955));
        this.luxzmlfksu.setPadding(139, 6, 0, 148);
        linearLayout.addView(this.luxzmlfksu);
        this.luxzmlfksu.setBackgroundColor(Color.parseColor("#df6146"));
        TableLayout tableLayout2 = new TableLayout(this);
        this.meemqcgqmi = tableLayout2;
        tableLayout2.setLayoutParams(new LinearLayout.LayoutParams(1465, 758));
        this.meemqcgqmi.setPadding(155, 52, 165, 69);
        linearLayout.addView(this.meemqcgqmi);
        this.meemqcgqmi.setBackgroundColor(Color.parseColor("#c9fa67"));
        FrameLayout frameLayout3 = new FrameLayout(this);
        this.behphejxbh = frameLayout3;
        frameLayout3.setLayoutParams(new LinearLayout.LayoutParams(977, 1683));
        this.behphejxbh.setPadding(149, 196, 131, 178);
        linearLayout.addView(this.behphejxbh);
        this.behphejxbh.setBackgroundColor(Color.parseColor("#8620ee"));
        TimePicker timePicker3 = new TimePicker(this);
        this.vupghpggul = timePicker3;
        timePicker3.setLayoutParams(new LinearLayout.LayoutParams(1082, 1481));
        this.vupghpggul.setPadding(105, 120, 142, 110);
        linearLayout.addView(this.vupghpggul);
        this.vupghpggul.setBackgroundColor(Color.parseColor("#49147c"));
        ToggleButton toggleButton4 = new ToggleButton(this);
        this.zvfiajldkx = toggleButton4;
        toggleButton4.setLayoutParams(new LinearLayout.LayoutParams(818, 1141));
        this.zvfiajldkx.setPadding(106, BDLocation.TypeNetWorkLocation, 186, 150);
        linearLayout.addView(this.zvfiajldkx);
        this.zvfiajldkx.setBackgroundColor(Color.parseColor("#eb0994"));
        TimePicker timePicker4 = new TimePicker(this);
        this.eofhtjrwrq = timePicker4;
        timePicker4.setLayoutParams(new LinearLayout.LayoutParams(558, 52));
        this.eofhtjrwrq.setPadding(174, 81, 109, 127);
        linearLayout.addView(this.eofhtjrwrq);
        this.eofhtjrwrq.setBackgroundColor(Color.parseColor("#f91f73"));
        TimePicker timePicker5 = new TimePicker(this);
        this.ukvqstztaq = timePicker5;
        timePicker5.setLayoutParams(new LinearLayout.LayoutParams(12, 449));
        this.ukvqstztaq.setPadding(9, 55, 104, 151);
        linearLayout.addView(this.ukvqstztaq);
        this.ukvqstztaq.setBackgroundColor(Color.parseColor("#6ef467"));
        TextView textView3 = new TextView(this);
        this.fihvdlkkpm = textView3;
        textView3.setLayoutParams(new LinearLayout.LayoutParams(13, 1071));
        this.fihvdlkkpm.setPadding(87, 85, 183, 86);
        linearLayout.addView(this.fihvdlkkpm);
        this.fihvdlkkpm.setBackgroundColor(Color.parseColor("#767f02"));
        TextView textView4 = new TextView(this);
        this.xtwlsjijcl = textView4;
        textView4.setLayoutParams(new LinearLayout.LayoutParams(1448, 90));
        this.xtwlsjijcl.setPadding(16, 137, 144, 199);
        linearLayout.addView(this.xtwlsjijcl);
        this.xtwlsjijcl.setBackgroundColor(Color.parseColor("#d4f293"));
        DatePicker datePicker3 = new DatePicker(this);
        this.rgkznqgdws = datePicker3;
        datePicker3.setLayoutParams(new LinearLayout.LayoutParams(576, 344));
        this.rgkznqgdws.setPadding(38, 111, 88, 8);
        linearLayout.addView(this.rgkznqgdws);
        this.rgkznqgdws.setBackgroundColor(Color.parseColor("#fcdf9d"));
        CheckBox checkBox4 = new CheckBox(this);
        this.bbbddiwojq = checkBox4;
        checkBox4.setLayoutParams(new LinearLayout.LayoutParams(31, TypedValues.MotionType.TYPE_PATHMOTION_ARC));
        this.bbbddiwojq.setPadding(107, 0, 104, 179);
        linearLayout.addView(this.bbbddiwojq);
        this.bbbddiwojq.setBackgroundColor(Color.parseColor("#cdc8b5"));
        EditText editText2 = new EditText(this);
        this.vjlnjfzwti = editText2;
        editText2.setLayoutParams(new LinearLayout.LayoutParams(1396, 1802));
        this.vjlnjfzwti.setPadding(7, 1, 173, 0);
        linearLayout.addView(this.vjlnjfzwti);
        this.vjlnjfzwti.setBackgroundColor(Color.parseColor("#4a7d23"));
        Switch r22 = new Switch(this);
        this.tpsgmoxupq = r22;
        r22.setLayoutParams(new LinearLayout.LayoutParams(912, 916));
        this.tpsgmoxupq.setPadding(78, 26, 159, BDLocation.TypeCoarseLocation);
        linearLayout.addView(this.tpsgmoxupq);
        this.tpsgmoxupq.setBackgroundColor(Color.parseColor("#f0b5dc"));
        TimePicker timePicker6 = new TimePicker(this);
        this.qgckqvumyk = timePicker6;
        timePicker6.setLayoutParams(new LinearLayout.LayoutParams(1846, 1864));
        this.qgckqvumyk.setPadding(166, 81, 137, 135);
        linearLayout.addView(this.qgckqvumyk);
        this.qgckqvumyk.setBackgroundColor(Color.parseColor("#13d94c"));
        TimePicker timePicker7 = new TimePicker(this);
        this.cockecxlau = timePicker7;
        timePicker7.setLayoutParams(new LinearLayout.LayoutParams(1432, 76));
        this.cockecxlau.setPadding(46, 3, 71, 151);
        linearLayout.addView(this.cockecxlau);
        this.cockecxlau.setBackgroundColor(Color.parseColor("#c0662d"));
        EditText editText3 = new EditText(this);
        this.bdtrrrhpeg = editText3;
        editText3.setLayoutParams(new LinearLayout.LayoutParams(294, 1601));
        this.bdtrrrhpeg.setPadding(123, 31, 38, 124);
        linearLayout.addView(this.bdtrrrhpeg);
        this.bdtrrrhpeg.setBackgroundColor(Color.parseColor("#554033"));
        GridView gridView5 = new GridView(this);
        this.uqgfranwjo = gridView5;
        gridView5.setLayoutParams(new LinearLayout.LayoutParams(441, TypedValues.MotionType.TYPE_POLAR_RELATIVETO));
        this.uqgfranwjo.setPadding(76, 55, 92, 128);
        linearLayout.addView(this.uqgfranwjo);
        this.uqgfranwjo.setBackgroundColor(Color.parseColor("#bd85ba"));
        DatePicker datePicker4 = new DatePicker(this);
        this.ajyrdwhggk = datePicker4;
        datePicker4.setLayoutParams(new LinearLayout.LayoutParams(53, 1181));
        this.ajyrdwhggk.setPadding(46, 107, 136, 13);
        linearLayout.addView(this.ajyrdwhggk);
        this.ajyrdwhggk.setBackgroundColor(Color.parseColor("#8bbe3a"));
        GridView gridView6 = new GridView(this);
        this.sxwojfabis = gridView6;
        gridView6.setLayoutParams(new LinearLayout.LayoutParams(1844, 25));
        this.sxwojfabis.setPadding(107, 108, 92, 193);
        linearLayout.addView(this.sxwojfabis);
        this.sxwojfabis.setBackgroundColor(Color.parseColor("#f5cd60"));
        ProgressBar progressBar5 = new ProgressBar(this);
        this.peegtkkvwd = progressBar5;
        progressBar5.setLayoutParams(new LinearLayout.LayoutParams(616, 1597));
        this.peegtkkvwd.setPadding(196, 50, 86, 114);
        linearLayout.addView(this.peegtkkvwd);
        this.peegtkkvwd.setBackgroundColor(Color.parseColor("#a0a7ab"));
        TimePicker timePicker8 = new TimePicker(this);
        this.hlqkcebtwu = timePicker8;
        timePicker8.setLayoutParams(new LinearLayout.LayoutParams(1968, 1617));
        this.hlqkcebtwu.setPadding(86, 59, 46, 199);
        linearLayout.addView(this.hlqkcebtwu);
        this.hlqkcebtwu.setBackgroundColor(Color.parseColor("#d30d2d"));
        DatePicker datePicker5 = new DatePicker(this);
        this.yjfewezngm = datePicker5;
        datePicker5.setLayoutParams(new LinearLayout.LayoutParams(787, TypedValues.AttributesType.TYPE_EASING));
        this.yjfewezngm.setPadding(9, 185, 185, 87);
        linearLayout.addView(this.yjfewezngm);
        this.yjfewezngm.setBackgroundColor(Color.parseColor("#8f111b"));
        CheckBox checkBox5 = new CheckBox(this);
        this.jjkdsbdnfm = checkBox5;
        checkBox5.setLayoutParams(new LinearLayout.LayoutParams(337, 1860));
        this.jjkdsbdnfm.setPadding(PictureConfig.CHOOSE_REQUEST, 142, 52, 81);
        linearLayout.addView(this.jjkdsbdnfm);
        this.jjkdsbdnfm.setBackgroundColor(Color.parseColor("#b6da8c"));
        RelativeLayout relativeLayout3 = new RelativeLayout(this);
        this.waewjryewl = relativeLayout3;
        relativeLayout3.setLayoutParams(new LinearLayout.LayoutParams(1966, 196));
        this.waewjryewl.setPadding(4, 127, 164, 25);
        linearLayout.addView(this.waewjryewl);
        this.waewjryewl.setBackgroundColor(Color.parseColor("#e9f657"));
        TableLayout tableLayout3 = new TableLayout(this);
        this.hoqeeaxetg = tableLayout3;
        tableLayout3.setLayoutParams(new LinearLayout.LayoutParams(930, 739));
        this.hoqeeaxetg.setPadding(148, 194, 185, 171);
        linearLayout.addView(this.hoqeeaxetg);
        this.hoqeeaxetg.setBackgroundColor(Color.parseColor("#228f65"));
        LinearLayout linearLayout5 = new LinearLayout(this);
        this.zaehdwlslv = linearLayout5;
        linearLayout5.setLayoutParams(new LinearLayout.LayoutParams(228, 1936));
        this.zaehdwlslv.setPadding(135, 157, 26, 46);
        linearLayout.addView(this.zaehdwlslv);
        this.zaehdwlslv.setBackgroundColor(Color.parseColor("#f62f26"));
        Button button3 = new Button(this);
        this.pqegwywvjy = button3;
        button3.setLayoutParams(new LinearLayout.LayoutParams(989, 1357));
        this.pqegwywvjy.setPadding(74, 108, 4, 24);
        linearLayout.addView(this.pqegwywvjy);
        this.pqegwywvjy.setBackgroundColor(Color.parseColor("#f4dfca"));
        ListView listView3 = new ListView(this);
        this.zuhmhtgspb = listView3;
        listView3.setLayoutParams(new LinearLayout.LayoutParams(1007, 829));
        this.zuhmhtgspb.setPadding(117, 47, 92, 97);
        linearLayout.addView(this.zuhmhtgspb);
        this.zuhmhtgspb.setBackgroundColor(Color.parseColor("#f0190a"));
        ViewFlipper viewFlipper = new ViewFlipper(this);
        this.awcbusnllz = viewFlipper;
        viewFlipper.setLayoutParams(new LinearLayout.LayoutParams(845, 711));
        this.awcbusnllz.setPadding(184, 55, 27, 13);
        linearLayout.addView(this.awcbusnllz);
        this.awcbusnllz.setBackgroundColor(Color.parseColor("#9e4b55"));
        ViewFlipper viewFlipper2 = new ViewFlipper(this);
        this.qpjzaberuu = viewFlipper2;
        viewFlipper2.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.PositionType.TYPE_POSITION_TYPE, 1743));
        this.qpjzaberuu.setPadding(67, 75, 33, 130);
        linearLayout.addView(this.qpjzaberuu);
        this.qpjzaberuu.setBackgroundColor(Color.parseColor("#d9936f"));
        RelativeLayout relativeLayout4 = new RelativeLayout(this);
        this.hgqgqugvmm = relativeLayout4;
        relativeLayout4.setLayoutParams(new LinearLayout.LayoutParams(1844, 1780));
        this.hgqgqugvmm.setPadding(134, 187, 130, 11);
        linearLayout.addView(this.hgqgqugvmm);
        this.hgqgqugvmm.setBackgroundColor(Color.parseColor("#165e8d"));
        CheckBox checkBox6 = new CheckBox(this);
        this.ydcehkvpnr = checkBox6;
        checkBox6.setLayoutParams(new LinearLayout.LayoutParams(1105, 1842));
        this.ydcehkvpnr.setPadding(96, 8, 189, 32);
        linearLayout.addView(this.ydcehkvpnr);
        this.ydcehkvpnr.setBackgroundColor(Color.parseColor("#2a519e"));
        FrameLayout frameLayout4 = new FrameLayout(this);
        this.pzkogsqdox = frameLayout4;
        frameLayout4.setLayoutParams(new LinearLayout.LayoutParams(1743, 445));
        this.pzkogsqdox.setPadding(131, 62, 66, PictureConfig.CHOOSE_REQUEST);
        linearLayout.addView(this.pzkogsqdox);
        this.pzkogsqdox.setBackgroundColor(Color.parseColor("#881f51"));
        GridView gridView7 = new GridView(this);
        this.tqqmewwyys = gridView7;
        gridView7.setLayoutParams(new LinearLayout.LayoutParams(56, 1743));
        this.tqqmewwyys.setPadding(85, 32, 43, 34);
        linearLayout.addView(this.tqqmewwyys);
        this.tqqmewwyys.setBackgroundColor(Color.parseColor("#5d8b18"));
        ViewFlipper viewFlipper3 = new ViewFlipper(this);
        this.aitfirihto = viewFlipper3;
        viewFlipper3.setLayoutParams(new LinearLayout.LayoutParams(804, 1256));
        this.aitfirihto.setPadding(146, 110, 83, 3);
        linearLayout.addView(this.aitfirihto);
        this.aitfirihto.setBackgroundColor(Color.parseColor("#8876d1"));
        ScrollView scrollView = new ScrollView(this);
        this.rttmzpmwnr = scrollView;
        scrollView.setLayoutParams(new LinearLayout.LayoutParams(1639, 920));
        this.rttmzpmwnr.setPadding(150, 109, 59, 192);
        linearLayout.addView(this.rttmzpmwnr);
        this.rttmzpmwnr.setBackgroundColor(Color.parseColor("#c726ef"));
        ScrollView scrollView2 = new ScrollView(this);
        this.sovksgcvwd = scrollView2;
        scrollView2.setLayoutParams(new LinearLayout.LayoutParams(389, 1043));
        this.sovksgcvwd.setPadding(135, 163, 196, 79);
        linearLayout.addView(this.sovksgcvwd);
        this.sovksgcvwd.setBackgroundColor(Color.parseColor("#0d5787"));
        DatePicker datePicker6 = new DatePicker(this);
        this.qucqneahou = datePicker6;
        datePicker6.setLayoutParams(new LinearLayout.LayoutParams(1589, 745));
        this.qucqneahou.setPadding(47, 77, 37, 5);
        linearLayout.addView(this.qucqneahou);
        this.qucqneahou.setBackgroundColor(Color.parseColor("#7754eb"));
        DatePicker datePicker7 = new DatePicker(this);
        this.grgxtxprwi = datePicker7;
        datePicker7.setLayoutParams(new LinearLayout.LayoutParams(1963, 1144));
        this.grgxtxprwi.setPadding(104, 144, 125, BDLocation.TypeCoarseLocation);
        linearLayout.addView(this.grgxtxprwi);
        this.grgxtxprwi.setBackgroundColor(Color.parseColor("#4a5c40"));
        ViewFlipper viewFlipper4 = new ViewFlipper(this);
        this.pouzhredag = viewFlipper4;
        viewFlipper4.setLayoutParams(new LinearLayout.LayoutParams(1529, 1880));
        this.pouzhredag.setPadding(41, 72, 4, 38);
        linearLayout.addView(this.pouzhredag);
        this.pouzhredag.setBackgroundColor(Color.parseColor("#39cc7b"));
        SeekBar seekBar4 = new SeekBar(this);
        this.itkmcqhmnc = seekBar4;
        seekBar4.setLayoutParams(new LinearLayout.LayoutParams(573, 330));
        this.itkmcqhmnc.setPadding(61, 104, 60, BDLocation.TypeServerError);
        linearLayout.addView(this.itkmcqhmnc);
        this.itkmcqhmnc.setBackgroundColor(Color.parseColor("#225731"));
        FrameLayout frameLayout5 = new FrameLayout(this);
        this.dqskyzxjul = frameLayout5;
        frameLayout5.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.AttributesType.TYPE_EASING, 1317));
        this.dqskyzxjul.setPadding(100, 192, 117, 194);
        linearLayout.addView(this.dqskyzxjul);
        this.dqskyzxjul.setBackgroundColor(Color.parseColor("#4b3fe9"));
        ImageView imageView2 = new ImageView(this);
        this.ouquzpqhqd = imageView2;
        imageView2.setLayoutParams(new LinearLayout.LayoutParams(454, 965));
        this.ouquzpqhqd.setPadding(1, 124, 62, 184);
        linearLayout.addView(this.ouquzpqhqd);
        this.ouquzpqhqd.setBackgroundColor(Color.parseColor("#513413"));
        DatePicker datePicker8 = new DatePicker(this);
        this.ttlsdwaium = datePicker8;
        datePicker8.setLayoutParams(new LinearLayout.LayoutParams(44, 1113));
        this.ttlsdwaium.setPadding(42, 150, 79, 43);
        linearLayout.addView(this.ttlsdwaium);
        this.ttlsdwaium.setBackgroundColor(Color.parseColor("#5018c9"));
        Button button4 = new Button(this);
        this.fribvjwzgg = button4;
        button4.setLayoutParams(new LinearLayout.LayoutParams(1795, 16));
        this.fribvjwzgg.setPadding(192, 74, 66, 66);
        linearLayout.addView(this.fribvjwzgg);
        this.fribvjwzgg.setBackgroundColor(Color.parseColor("#522eb3"));
        RelativeLayout relativeLayout5 = new RelativeLayout(this);
        this.owcpojsoom = relativeLayout5;
        relativeLayout5.setLayoutParams(new LinearLayout.LayoutParams(436, 1417));
        this.owcpojsoom.setPadding(27, 66, 153, 3);
        linearLayout.addView(this.owcpojsoom);
        this.owcpojsoom.setBackgroundColor(Color.parseColor("#5e7b24"));
        ToggleButton toggleButton5 = new ToggleButton(this);
        this.cjguoebhhj = toggleButton5;
        toggleButton5.setLayoutParams(new LinearLayout.LayoutParams(915, 557));
        this.cjguoebhhj.setPadding(71, 78, 90, 131);
        linearLayout.addView(this.cjguoebhhj);
        this.cjguoebhhj.setBackgroundColor(Color.parseColor("#fc3d9f"));
        RatingBar ratingBar7 = new RatingBar(this);
        this.vvmajehcsb = ratingBar7;
        ratingBar7.setLayoutParams(new LinearLayout.LayoutParams(325, Contract.CMD_SET_VERSION.V1_2));
        this.vvmajehcsb.setPadding(132, 67, 151, 110);
        linearLayout.addView(this.vvmajehcsb);
        this.vvmajehcsb.setBackgroundColor(Color.parseColor("#f4ae24"));
        ToggleButton toggleButton6 = new ToggleButton(this);
        this.wmkfvjqewy = toggleButton6;
        toggleButton6.setLayoutParams(new LinearLayout.LayoutParams(918, 54));
        this.wmkfvjqewy.setPadding(23, 44, 43, 183);
        linearLayout.addView(this.wmkfvjqewy);
        this.wmkfvjqewy.setBackgroundColor(Color.parseColor("#2b7d45"));
        LinearLayout linearLayout6 = new LinearLayout(this);
        this.jcfrwxjbuo = linearLayout6;
        linearLayout6.setLayoutParams(new LinearLayout.LayoutParams(CodeUtils.DEFAULT_REQ_HEIGHT, 1037));
        this.jcfrwxjbuo.setPadding(143, 177, 118, 13);
        linearLayout.addView(this.jcfrwxjbuo);
        this.jcfrwxjbuo.setBackgroundColor(Color.parseColor("#7ec3ec"));
        Switch r23 = new Switch(this);
        this.krsvqnvpad = r23;
        r23.setLayoutParams(new LinearLayout.LayoutParams(399, 32));
        this.krsvqnvpad.setPadding(42, 11, 0, 33);
        linearLayout.addView(this.krsvqnvpad);
        this.krsvqnvpad.setBackgroundColor(Color.parseColor("#49b6d1"));
        TextView textView5 = new TextView(this);
        this.izyiguvqsn = textView5;
        textView5.setLayoutParams(new LinearLayout.LayoutParams(PointerIconCompat.TYPE_TOP_LEFT_DIAGONAL_DOUBLE_ARROW, 1756));
        this.izyiguvqsn.setPadding(175, 168, 12, 143);
        linearLayout.addView(this.izyiguvqsn);
        this.izyiguvqsn.setBackgroundColor(Color.parseColor("#be5a36"));
        GridView gridView8 = new GridView(this);
        this.tawldcheaw = gridView8;
        gridView8.setLayoutParams(new LinearLayout.LayoutParams(1779, 1435));
        this.tawldcheaw.setPadding(93, 98, 91, 48);
        linearLayout.addView(this.tawldcheaw);
        this.tawldcheaw.setBackgroundColor(Color.parseColor("#66f027"));
        ScrollView scrollView3 = new ScrollView(this);
        this.ygnscqaqcj = scrollView3;
        scrollView3.setLayoutParams(new LinearLayout.LayoutParams(966, 713));
        this.ygnscqaqcj.setPadding(137, 102, 193, 120);
        linearLayout.addView(this.ygnscqaqcj);
        this.ygnscqaqcj.setBackgroundColor(Color.parseColor("#2b78cc"));
        Switch r24 = new Switch(this);
        this.aqhpwnjvhl = r24;
        r24.setLayoutParams(new LinearLayout.LayoutParams(72, 1326));
        this.aqhpwnjvhl.setPadding(110, 132, 189, 34);
        linearLayout.addView(this.aqhpwnjvhl);
        this.aqhpwnjvhl.setBackgroundColor(Color.parseColor("#40e4e3"));
        EditText editText4 = new EditText(this);
        this.sjohgwmfwk = editText4;
        editText4.setLayoutParams(new LinearLayout.LayoutParams(991, 620));
        this.sjohgwmfwk.setPadding(37, 67, 33, 13);
        linearLayout.addView(this.sjohgwmfwk);
        this.sjohgwmfwk.setBackgroundColor(Color.parseColor("#f522e3"));
        Spinner spinner5 = new Spinner(this);
        this.fgdnhjtzys = spinner5;
        spinner5.setLayoutParams(new LinearLayout.LayoutParams(1368, 734));
        this.fgdnhjtzys.setPadding(52, 198, 114, 186);
        linearLayout.addView(this.fgdnhjtzys);
        this.fgdnhjtzys.setBackgroundColor(Color.parseColor("#2cdf87"));
        CheckBox checkBox7 = new CheckBox(this);
        this.faaakxzpmh = checkBox7;
        checkBox7.setLayoutParams(new LinearLayout.LayoutParams(1117, 645));
        this.faaakxzpmh.setPadding(59, 87, 145, 132);
        linearLayout.addView(this.faaakxzpmh);
        this.faaakxzpmh.setBackgroundColor(Color.parseColor("#544719"));
        ProgressBar progressBar6 = new ProgressBar(this);
        this.kxgoulimma = progressBar6;
        progressBar6.setLayoutParams(new LinearLayout.LayoutParams(588, 70));
        this.kxgoulimma.setPadding(154, 158, 14, 196);
        linearLayout.addView(this.kxgoulimma);
        this.kxgoulimma.setBackgroundColor(Color.parseColor("#d47b8b"));
        ProgressBar progressBar7 = new ProgressBar(this);
        this.awcshhzklm = progressBar7;
        progressBar7.setLayoutParams(new LinearLayout.LayoutParams(1675, 908));
        this.awcshhzklm.setPadding(55, 78, 14, 183);
        linearLayout.addView(this.awcshhzklm);
        this.awcshhzklm.setBackgroundColor(Color.parseColor("#a37ac8"));
        Spinner spinner6 = new Spinner(this);
        this.iedtdtwvai = spinner6;
        spinner6.setLayoutParams(new LinearLayout.LayoutParams(1057, 895));
        this.iedtdtwvai.setPadding(172, 164, 139, 22);
        linearLayout.addView(this.iedtdtwvai);
        this.iedtdtwvai.setBackgroundColor(Color.parseColor("#3545a8"));
        TimePicker timePicker9 = new TimePicker(this);
        this.xshkktipbi = timePicker9;
        timePicker9.setLayoutParams(new LinearLayout.LayoutParams(1480, 183));
        this.xshkktipbi.setPadding(62, 70, 89, 9);
        linearLayout.addView(this.xshkktipbi);
        this.xshkktipbi.setBackgroundColor(Color.parseColor("#9f862c"));
        RelativeLayout relativeLayout6 = new RelativeLayout(this);
        this.xflgpuoswb = relativeLayout6;
        relativeLayout6.setLayoutParams(new LinearLayout.LayoutParams(1415, 1544));
        this.xflgpuoswb.setPadding(89, 92, 57, 199);
        linearLayout.addView(this.xflgpuoswb);
        this.xflgpuoswb.setBackgroundColor(Color.parseColor("#76681c"));
        Button button5 = new Button(this);
        this.nvnitptlef = button5;
        button5.setLayoutParams(new LinearLayout.LayoutParams(179, 1218));
        this.nvnitptlef.setPadding(191, 109, 166, 22);
        linearLayout.addView(this.nvnitptlef);
        this.nvnitptlef.setBackgroundColor(Color.parseColor("#1c2fe5"));
        TimePicker timePicker10 = new TimePicker(this);
        this.hapicimrjb = timePicker10;
        timePicker10.setLayoutParams(new LinearLayout.LayoutParams(1533, 685));
        this.hapicimrjb.setPadding(8, 49, 165, 18);
        linearLayout.addView(this.hapicimrjb);
        this.hapicimrjb.setBackgroundColor(Color.parseColor("#7065f9"));
        ImageView imageView3 = new ImageView(this);
        this.jsatwqixjy = imageView3;
        imageView3.setLayoutParams(new LinearLayout.LayoutParams(1871, 7));
        this.jsatwqixjy.setPadding(124, 6, 65, 93);
        linearLayout.addView(this.jsatwqixjy);
        this.jsatwqixjy.setBackgroundColor(Color.parseColor("#6b2c44"));
        EditText editText5 = new EditText(this);
        this.tqdsgkduvk = editText5;
        editText5.setLayoutParams(new LinearLayout.LayoutParams(839, 1235));
        this.tqdsgkduvk.setPadding(132, 50, 84, 27);
        linearLayout.addView(this.tqdsgkduvk);
        this.tqdsgkduvk.setBackgroundColor(Color.parseColor("#d3d596"));
        TimePicker timePicker11 = new TimePicker(this);
        this.pxmhcrugtj = timePicker11;
        timePicker11.setLayoutParams(new LinearLayout.LayoutParams(1645, 1286));
        this.pxmhcrugtj.setPadding(47, 116, 177, 104);
        linearLayout.addView(this.pxmhcrugtj);
        this.pxmhcrugtj.setBackgroundColor(Color.parseColor("#3ce2fd"));
        ImageView imageView4 = new ImageView(this);
        this.jacyrfqygo = imageView4;
        imageView4.setLayoutParams(new LinearLayout.LayoutParams(1625, 1592));
        this.jacyrfqygo.setPadding(177, 159, 181, 128);
        linearLayout.addView(this.jacyrfqygo);
        this.jacyrfqygo.setBackgroundColor(Color.parseColor("#28ff24"));
        ViewFlipper viewFlipper5 = new ViewFlipper(this);
        this.dvpyjydxik = viewFlipper5;
        viewFlipper5.setLayoutParams(new LinearLayout.LayoutParams(1750, 93));
        this.dvpyjydxik.setPadding(190, 60, 78, 17);
        linearLayout.addView(this.dvpyjydxik);
        this.dvpyjydxik.setBackgroundColor(Color.parseColor("#591321"));
        FrameLayout frameLayout6 = new FrameLayout(this);
        this.phggllvjpy = frameLayout6;
        frameLayout6.setLayoutParams(new LinearLayout.LayoutParams(618, 1142));
        this.phggllvjpy.setPadding(92, 11, 131, 119);
        linearLayout.addView(this.phggllvjpy);
        this.phggllvjpy.setBackgroundColor(Color.parseColor("#70e4a4"));
        Spinner spinner7 = new Spinner(this);
        this.reixxlyzld = spinner7;
        spinner7.setLayoutParams(new LinearLayout.LayoutParams(1951, 1488));
        this.reixxlyzld.setPadding(152, 62, 178, 117);
        linearLayout.addView(this.reixxlyzld);
        this.reixxlyzld.setBackgroundColor(Color.parseColor("#474fab"));
        TimePicker timePicker12 = new TimePicker(this);
        this.hqwgbuncfy = timePicker12;
        timePicker12.setLayoutParams(new LinearLayout.LayoutParams(451, 1024));
        this.hqwgbuncfy.setPadding(127, 10, 137, 173);
        linearLayout.addView(this.hqwgbuncfy);
        this.hqwgbuncfy.setBackgroundColor(Color.parseColor("#d7966f"));
        ListView listView4 = new ListView(this);
        this.oeknyyacbo = listView4;
        listView4.setLayoutParams(new LinearLayout.LayoutParams(274, 96));
        this.oeknyyacbo.setPadding(85, 155, 180, 139);
        linearLayout.addView(this.oeknyyacbo);
        this.oeknyyacbo.setBackgroundColor(Color.parseColor("#abdaf8"));
        EditText editText6 = new EditText(this);
        this.fnsslevxho = editText6;
        editText6.setLayoutParams(new LinearLayout.LayoutParams(1357, 1810));
        this.fnsslevxho.setPadding(180, 114, 21, 179);
        linearLayout.addView(this.fnsslevxho);
        this.fnsslevxho.setBackgroundColor(Color.parseColor("#00a1c8"));
        ScrollView scrollView4 = new ScrollView(this);
        this.gqimvbnnaw = scrollView4;
        scrollView4.setLayoutParams(new LinearLayout.LayoutParams(220, 1479));
        this.gqimvbnnaw.setPadding(51, 94, 145, 45);
        linearLayout.addView(this.gqimvbnnaw);
        this.gqimvbnnaw.setBackgroundColor(Color.parseColor("#3eed87"));
        CheckBox checkBox8 = new CheckBox(this);
        this.jkgufmdyim = checkBox8;
        checkBox8.setLayoutParams(new LinearLayout.LayoutParams(1591, 1091));
        this.jkgufmdyim.setPadding(6, 117, 30, 137);
        linearLayout.addView(this.jkgufmdyim);
        this.jkgufmdyim.setBackgroundColor(Color.parseColor("#d429ea"));
        TableLayout tableLayout4 = new TableLayout(this);
        this.bayviksddu = tableLayout4;
        tableLayout4.setLayoutParams(new LinearLayout.LayoutParams(1674, 24));
        this.bayviksddu.setPadding(196, WebSocketProtocol.PAYLOAD_SHORT, 194, 180);
        linearLayout.addView(this.bayviksddu);
        this.bayviksddu.setBackgroundColor(Color.parseColor("#85dc1e"));
        RatingBar ratingBar8 = new RatingBar(this);
        this.lzfxobceiy = ratingBar8;
        ratingBar8.setLayoutParams(new LinearLayout.LayoutParams(1006, 565));
        this.lzfxobceiy.setPadding(124, PictureConfig.CHOOSE_REQUEST, 62, 71);
        linearLayout.addView(this.lzfxobceiy);
        this.lzfxobceiy.setBackgroundColor(Color.parseColor("#196dd8"));
        GridView gridView9 = new GridView(this);
        this.ekjmztrwbs = gridView9;
        gridView9.setLayoutParams(new LinearLayout.LayoutParams(1484, 210));
        this.ekjmztrwbs.setPadding(178, 113, 177, 71);
        linearLayout.addView(this.ekjmztrwbs);
        this.ekjmztrwbs.setBackgroundColor(Color.parseColor("#e2d89c"));
        ListView listView5 = new ListView(this);
        this.xpljmtrocp = listView5;
        listView5.setLayoutParams(new LinearLayout.LayoutParams(916, 146));
        this.xpljmtrocp.setPadding(46, PictureConfig.CHOOSE_REQUEST, 74, 141);
        linearLayout.addView(this.xpljmtrocp);
        this.xpljmtrocp.setBackgroundColor(Color.parseColor("#1c77e1"));
        ScrollView scrollView5 = new ScrollView(this);
        this.qygomagdjs = scrollView5;
        scrollView5.setLayoutParams(new LinearLayout.LayoutParams(931, 332));
        this.qygomagdjs.setPadding(140, 16, 165, 19);
        linearLayout.addView(this.qygomagdjs);
        this.qygomagdjs.setBackgroundColor(Color.parseColor("#57a581"));
        ToggleButton toggleButton7 = new ToggleButton(this);
        this.rwuyrdpeuw = toggleButton7;
        toggleButton7.setLayoutParams(new LinearLayout.LayoutParams(251, 1919));
        this.rwuyrdpeuw.setPadding(70, 140, 101, 40);
        linearLayout.addView(this.rwuyrdpeuw);
        this.rwuyrdpeuw.setBackgroundColor(Color.parseColor("#bc7805"));
        TextView textView6 = new TextView(this);
        this.csofwxxdhk = textView6;
        textView6.setLayoutParams(new LinearLayout.LayoutParams(180, 777));
        this.csofwxxdhk.setPadding(110, 89, 2, 154);
        linearLayout.addView(this.csofwxxdhk);
        this.csofwxxdhk.setBackgroundColor(Color.parseColor("#4511de"));
        Switch r25 = new Switch(this);
        this.milabjzmwk = r25;
        r25.setLayoutParams(new LinearLayout.LayoutParams(1975, 1227));
        this.milabjzmwk.setPadding(153, 99, 145, 135);
        linearLayout.addView(this.milabjzmwk);
        this.milabjzmwk.setBackgroundColor(Color.parseColor("#cd1eb0"));
        TextView textView7 = new TextView(this);
        this.uvsrpnvvrd = textView7;
        textView7.setLayoutParams(new LinearLayout.LayoutParams(Contract.CMD_SET_VERSION.V1_3, 100));
        this.uvsrpnvvrd.setPadding(134, 22, 194, 63);
        linearLayout.addView(this.uvsrpnvvrd);
        this.uvsrpnvvrd.setBackgroundColor(Color.parseColor("#4ec5af"));
        RadioButton radioButton3 = new RadioButton(this);
        this.xyfxoujsny = radioButton3;
        radioButton3.setLayoutParams(new LinearLayout.LayoutParams(896, CodeUtils.DEFAULT_REQ_HEIGHT));
        this.xyfxoujsny.setPadding(84, 92, 191, 17);
        linearLayout.addView(this.xyfxoujsny);
        this.xyfxoujsny.setBackgroundColor(Color.parseColor("#51ef63"));
        DatePicker datePicker9 = new DatePicker(this);
        this.ukzwqltbff = datePicker9;
        datePicker9.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.Custom.TYPE_BOOLEAN, 1332));
        this.ukzwqltbff.setPadding(58, 138, 72, 31);
        linearLayout.addView(this.ukzwqltbff);
        this.ukzwqltbff.setBackgroundColor(Color.parseColor("#0c63ce"));
        TableLayout tableLayout5 = new TableLayout(this);
        this.ehxczjmjxr = tableLayout5;
        tableLayout5.setLayoutParams(new LinearLayout.LayoutParams(1358, 63));
        this.ehxczjmjxr.setPadding(48, 196, 179, 183);
        linearLayout.addView(this.ehxczjmjxr);
        this.ehxczjmjxr.setBackgroundColor(Color.parseColor("#8703ed"));
        GridView gridView10 = new GridView(this);
        this.ijtzxtmdrx = gridView10;
        gridView10.setLayoutParams(new LinearLayout.LayoutParams(846, 1063));
        this.ijtzxtmdrx.setPadding(139, 75, 191, 56);
        linearLayout.addView(this.ijtzxtmdrx);
        this.ijtzxtmdrx.setBackgroundColor(Color.parseColor("#3e3ae9"));
        FrameLayout frameLayout7 = new FrameLayout(this);
        this.jdrlyfqxgx = frameLayout7;
        frameLayout7.setLayoutParams(new LinearLayout.LayoutParams(251, 934));
        this.jdrlyfqxgx.setPadding(79, 194, 9, 22);
        linearLayout.addView(this.jdrlyfqxgx);
        this.jdrlyfqxgx.setBackgroundColor(Color.parseColor("#644a41"));
        FrameLayout frameLayout8 = new FrameLayout(this);
        this.rwednyazfg = frameLayout8;
        frameLayout8.setLayoutParams(new LinearLayout.LayoutParams(688, 1705));
        this.rwednyazfg.setPadding(189, 15, 0, 84);
        linearLayout.addView(this.rwednyazfg);
        this.rwednyazfg.setBackgroundColor(Color.parseColor("#c3fa32"));
        GridView gridView11 = new GridView(this);
        this.jsxypgqqqe = gridView11;
        gridView11.setLayoutParams(new LinearLayout.LayoutParams(597, 1901));
        this.jsxypgqqqe.setPadding(69, 164, 91, 101);
        linearLayout.addView(this.jsxypgqqqe);
        this.jsxypgqqqe.setBackgroundColor(Color.parseColor("#bc9288"));
        Button button6 = new Button(this);
        this.hfhoubsgqh = button6;
        button6.setLayoutParams(new LinearLayout.LayoutParams(1339, 93));
        this.hfhoubsgqh.setPadding(166, 130, 194, 69);
        linearLayout.addView(this.hfhoubsgqh);
        this.hfhoubsgqh.setBackgroundColor(Color.parseColor("#04c067"));
        LinearLayout linearLayout7 = new LinearLayout(this);
        this.vwnvbvxpha = linearLayout7;
        linearLayout7.setLayoutParams(new LinearLayout.LayoutParams(1338, 1603));
        this.vwnvbvxpha.setPadding(88, 191, 81, 170);
        linearLayout.addView(this.vwnvbvxpha);
        this.vwnvbvxpha.setBackgroundColor(Color.parseColor("#e4a404"));
        TextView textView8 = new TextView(this);
        this.xrbxfzkwrb = textView8;
        textView8.setLayoutParams(new LinearLayout.LayoutParams(1503, 673));
        this.xrbxfzkwrb.setPadding(131, 37, 105, 65);
        linearLayout.addView(this.xrbxfzkwrb);
        this.xrbxfzkwrb.setBackgroundColor(Color.parseColor("#4accbf"));
        LinearLayout linearLayout8 = new LinearLayout(this);
        this.izadutdsiu = linearLayout8;
        linearLayout8.setLayoutParams(new LinearLayout.LayoutParams(107, 676));
        this.izadutdsiu.setPadding(41, 150, 8, 151);
        linearLayout.addView(this.izadutdsiu);
        this.izadutdsiu.setBackgroundColor(Color.parseColor("#713777"));
        ImageView imageView5 = new ImageView(this);
        this.oltbcgsvwx = imageView5;
        imageView5.setLayoutParams(new LinearLayout.LayoutParams(894, PointerIconCompat.TYPE_GRABBING));
        this.oltbcgsvwx.setPadding(31, 23, 192, BDLocation.TypeServerError);
        linearLayout.addView(this.oltbcgsvwx);
        this.oltbcgsvwx.setBackgroundColor(Color.parseColor("#ea8930"));
        CheckBox checkBox9 = new CheckBox(this);
        this.vslpaeewxe = checkBox9;
        checkBox9.setLayoutParams(new LinearLayout.LayoutParams(1611, 1716));
        this.vslpaeewxe.setPadding(34, 16, 109, 65);
        linearLayout.addView(this.vslpaeewxe);
        this.vslpaeewxe.setBackgroundColor(Color.parseColor("#5c9b9f"));
        CheckBox checkBox10 = new CheckBox(this);
        this.rhsgzfxhwe = checkBox10;
        checkBox10.setLayoutParams(new LinearLayout.LayoutParams(1564, 1923));
        this.rhsgzfxhwe.setPadding(133, 134, 79, 102);
        linearLayout.addView(this.rhsgzfxhwe);
        this.rhsgzfxhwe.setBackgroundColor(Color.parseColor("#ff3a92"));
        Switch r26 = new Switch(this);
        this.yefagqwwjl = r26;
        r26.setLayoutParams(new LinearLayout.LayoutParams(285, 948));
        this.yefagqwwjl.setPadding(30, 14, 143, 86);
        linearLayout.addView(this.yefagqwwjl);
        this.yefagqwwjl.setBackgroundColor(Color.parseColor("#170058"));
        TableLayout tableLayout6 = new TableLayout(this);
        this.xjrjzrdcep = tableLayout6;
        tableLayout6.setLayoutParams(new LinearLayout.LayoutParams(334, 1407));
        this.xjrjzrdcep.setPadding(105, 5, 118, 179);
        linearLayout.addView(this.xjrjzrdcep);
        this.xjrjzrdcep.setBackgroundColor(Color.parseColor("#7a08ee"));
        ImageView imageView6 = new ImageView(this);
        this.ykqmevxaxl = imageView6;
        imageView6.setLayoutParams(new LinearLayout.LayoutParams(1258, 859));
        this.ykqmevxaxl.setPadding(117, 185, 41, 37);
        linearLayout.addView(this.ykqmevxaxl);
        this.ykqmevxaxl.setBackgroundColor(Color.parseColor("#583c5a"));
        FrameLayout frameLayout9 = new FrameLayout(this);
        this.oyljhvrcpf = frameLayout9;
        frameLayout9.setLayoutParams(new LinearLayout.LayoutParams(76, 295));
        this.oyljhvrcpf.setPadding(43, 198, 57, 186);
        linearLayout.addView(this.oyljhvrcpf);
        this.oyljhvrcpf.setBackgroundColor(Color.parseColor("#2fd7e3"));
        FrameLayout frameLayout10 = new FrameLayout(this);
        this.qzjmzaorhg = frameLayout10;
        frameLayout10.setLayoutParams(new LinearLayout.LayoutParams(25, 1548));
        this.qzjmzaorhg.setPadding(110, 174, 14, 129);
        linearLayout.addView(this.qzjmzaorhg);
        this.qzjmzaorhg.setBackgroundColor(Color.parseColor("#e1abb0"));
        ProgressBar progressBar8 = new ProgressBar(this);
        this.oaqmpovdrn = progressBar8;
        progressBar8.setLayoutParams(new LinearLayout.LayoutParams(1760, 138));
        this.oaqmpovdrn.setPadding(84, 128, 27, 3);
        linearLayout.addView(this.oaqmpovdrn);
        this.oaqmpovdrn.setBackgroundColor(Color.parseColor("#1130bd"));
        Spinner spinner8 = new Spinner(this);
        this.qxnbnucjev = spinner8;
        spinner8.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.Custom.TYPE_FLOAT, 197));
        this.qxnbnucjev.setPadding(51, 28, 100, 181);
        linearLayout.addView(this.qxnbnucjev);
        this.qxnbnucjev.setBackgroundColor(Color.parseColor("#bb36db"));
        ToggleButton toggleButton8 = new ToggleButton(this);
        this.vxkliogelp = toggleButton8;
        toggleButton8.setLayoutParams(new LinearLayout.LayoutParams(1813, 1123));
        this.vxkliogelp.setPadding(159, 1, 91, 141);
        linearLayout.addView(this.vxkliogelp);
        this.vxkliogelp.setBackgroundColor(Color.parseColor("#e22458"));
        TableLayout tableLayout7 = new TableLayout(this);
        this.frymcxcgju = tableLayout7;
        tableLayout7.setLayoutParams(new LinearLayout.LayoutParams(1819, 732));
        this.frymcxcgju.setPadding(25, 34, 186, 144);
        linearLayout.addView(this.frymcxcgju);
        this.frymcxcgju.setBackgroundColor(Color.parseColor("#4d88b1"));
        ScrollView scrollView6 = new ScrollView(this);
        this.foysznjvoa = scrollView6;
        scrollView6.setLayoutParams(new LinearLayout.LayoutParams(1865, 694));
        this.foysznjvoa.setPadding(130, 100, 67, 164);
        linearLayout.addView(this.foysznjvoa);
        this.foysznjvoa.setBackgroundColor(Color.parseColor("#fa0c52"));
        SeekBar seekBar5 = new SeekBar(this);
        this.ediostrgny = seekBar5;
        seekBar5.setLayoutParams(new LinearLayout.LayoutParams(1802, 115));
        this.ediostrgny.setPadding(182, 141, 195, 152);
        linearLayout.addView(this.ediostrgny);
        this.ediostrgny.setBackgroundColor(Color.parseColor("#16b6cf"));
        ViewFlipper viewFlipper6 = new ViewFlipper(this);
        this.greolrdaop = viewFlipper6;
        viewFlipper6.setLayoutParams(new LinearLayout.LayoutParams(1420, 448));
        this.greolrdaop.setPadding(92, 41, 148, WebSocketProtocol.PAYLOAD_SHORT);
        linearLayout.addView(this.greolrdaop);
        this.greolrdaop.setBackgroundColor(Color.parseColor("#f82ebe"));
        LinearLayout linearLayout9 = new LinearLayout(this);
        this.rgbtddbgpl = linearLayout9;
        linearLayout9.setLayoutParams(new LinearLayout.LayoutParams(834, 324));
        this.rgbtddbgpl.setPadding(82, 103, 41, 73);
        linearLayout.addView(this.rgbtddbgpl);
        this.rgbtddbgpl.setBackgroundColor(Color.parseColor("#d34d6e"));
        RatingBar ratingBar9 = new RatingBar(this);
        this.aukwndqjag = ratingBar9;
        ratingBar9.setLayoutParams(new LinearLayout.LayoutParams(1711, 506));
        this.aukwndqjag.setPadding(61, 195, 108, 112);
        linearLayout.addView(this.aukwndqjag);
        this.aukwndqjag.setBackgroundColor(Color.parseColor("#6eb949"));
        RelativeLayout relativeLayout7 = new RelativeLayout(this);
        this.jkubdxdjcu = relativeLayout7;
        relativeLayout7.setLayoutParams(new LinearLayout.LayoutParams(1527, CropImageView.DEFAULT_IMAGE_TO_CROP_BOUNDS_ANIM_DURATION));
        this.jkubdxdjcu.setPadding(151, 95, 27, 158);
        linearLayout.addView(this.jkubdxdjcu);
        this.jkubdxdjcu.setBackgroundColor(Color.parseColor("#e4c92c"));
        ListView listView6 = new ListView(this);
        this.vzsqiehgnq = listView6;
        listView6.setLayoutParams(new LinearLayout.LayoutParams(1638, 5));
        this.vzsqiehgnq.setPadding(170, 108, 80, 12);
        linearLayout.addView(this.vzsqiehgnq);
        this.vzsqiehgnq.setBackgroundColor(Color.parseColor("#cca2a8"));
        ViewFlipper viewFlipper7 = new ViewFlipper(this);
        this.eitfidsylv = viewFlipper7;
        viewFlipper7.setLayoutParams(new LinearLayout.LayoutParams(1659, 802));
        this.eitfidsylv.setPadding(153, 55, 168, 141);
        linearLayout.addView(this.eitfidsylv);
        this.eitfidsylv.setBackgroundColor(Color.parseColor("#d76bc5"));
        RelativeLayout relativeLayout8 = new RelativeLayout(this);
        this.lkhhpuvdlu = relativeLayout8;
        relativeLayout8.setLayoutParams(new LinearLayout.LayoutParams(1224, 1054));
        this.lkhhpuvdlu.setPadding(175, 145, 163, 149);
        linearLayout.addView(this.lkhhpuvdlu);
        this.lkhhpuvdlu.setBackgroundColor(Color.parseColor("#83c764"));
        EditText editText7 = new EditText(this);
        this.ivkyooomsh = editText7;
        editText7.setLayoutParams(new LinearLayout.LayoutParams(216, 551));
        this.ivkyooomsh.setPadding(103, 135, 82, 158);
        linearLayout.addView(this.ivkyooomsh);
        this.ivkyooomsh.setBackgroundColor(Color.parseColor("#efc1e8"));
        ViewFlipper viewFlipper8 = new ViewFlipper(this);
        this.uthuardwpo = viewFlipper8;
        viewFlipper8.setLayoutParams(new LinearLayout.LayoutParams(1882, 1193));
        this.uthuardwpo.setPadding(131, 75, 62, 71);
        linearLayout.addView(this.uthuardwpo);
        this.uthuardwpo.setBackgroundColor(Color.parseColor("#cc922b"));
        SeekBar seekBar6 = new SeekBar(this);
        this.ltlylteyeu = seekBar6;
        seekBar6.setLayoutParams(new LinearLayout.LayoutParams(36, 183));
        this.ltlylteyeu.setPadding(97, 14, 92, 75);
        linearLayout.addView(this.ltlylteyeu);
        this.ltlylteyeu.setBackgroundColor(Color.parseColor("#f3f9cc"));
        GridView gridView12 = new GridView(this);
        this.grkfpvpecl = gridView12;
        gridView12.setLayoutParams(new LinearLayout.LayoutParams(376, 1896));
        this.grkfpvpecl.setPadding(104, 106, 86, 19);
        linearLayout.addView(this.grkfpvpecl);
        this.grkfpvpecl.setBackgroundColor(Color.parseColor("#4edd7d"));
        EditText editText8 = new EditText(this);
        this.wzcydmarrb = editText8;
        editText8.setLayoutParams(new LinearLayout.LayoutParams(139, 1645));
        this.wzcydmarrb.setPadding(88, 120, 69, 128);
        linearLayout.addView(this.wzcydmarrb);
        this.wzcydmarrb.setBackgroundColor(Color.parseColor("#ac101e"));
        RelativeLayout relativeLayout9 = new RelativeLayout(this);
        this.hzcevzvzhj = relativeLayout9;
        relativeLayout9.setLayoutParams(new LinearLayout.LayoutParams(716, 357));
        this.hzcevzvzhj.setPadding(152, 147, 51, 7);
        linearLayout.addView(this.hzcevzvzhj);
        this.hzcevzvzhj.setBackgroundColor(Color.parseColor("#fb6bcf"));
        ListView listView7 = new ListView(this);
        this.wumtcsgvmm = listView7;
        listView7.setLayoutParams(new LinearLayout.LayoutParams(1594, 1633));
        this.wumtcsgvmm.setPadding(130, 151, 164, 2);
        linearLayout.addView(this.wumtcsgvmm);
        this.wumtcsgvmm.setBackgroundColor(Color.parseColor("#aad891"));
        LinearLayout linearLayout10 = new LinearLayout(this);
        this.hsnacyuuxx = linearLayout10;
        linearLayout10.setLayoutParams(new LinearLayout.LayoutParams(470, 642));
        this.hsnacyuuxx.setPadding(194, 26, 91, 113);
        linearLayout.addView(this.hsnacyuuxx);
        this.hsnacyuuxx.setBackgroundColor(Color.parseColor("#e037d4"));
        RatingBar ratingBar10 = new RatingBar(this);
        this.wtbwbmisev = ratingBar10;
        ratingBar10.setLayoutParams(new LinearLayout.LayoutParams(1150, 1492));
        this.wtbwbmisev.setPadding(180, 141, 122, 75);
        linearLayout.addView(this.wtbwbmisev);
        this.wtbwbmisev.setBackgroundColor(Color.parseColor("#c4aabb"));
        LinearLayout linearLayout11 = new LinearLayout(this);
        this.mxciyyvurw = linearLayout11;
        linearLayout11.setLayoutParams(new LinearLayout.LayoutParams(723, 1839));
        this.mxciyyvurw.setPadding(84, 87, 123, 180);
        linearLayout.addView(this.mxciyyvurw);
        this.mxciyyvurw.setBackgroundColor(Color.parseColor("#a43099"));
        CheckBox checkBox11 = new CheckBox(this);
        this.pwxciglrge = checkBox11;
        checkBox11.setLayoutParams(new LinearLayout.LayoutParams(938, 753));
        this.pwxciglrge.setPadding(7, 182, 28, 179);
        linearLayout.addView(this.pwxciglrge);
        this.pwxciglrge.setBackgroundColor(Color.parseColor("#42a3ed"));
        CheckBox checkBox12 = new CheckBox(this);
        this.cikoxzybpu = checkBox12;
        checkBox12.setLayoutParams(new LinearLayout.LayoutParams(1990, 1874));
        this.cikoxzybpu.setPadding(119, 171, 183, 87);
        linearLayout.addView(this.cikoxzybpu);
        this.cikoxzybpu.setBackgroundColor(Color.parseColor("#a640cd"));
        ImageView imageView7 = new ImageView(this);
        this.enwuzlzyzl = imageView7;
        imageView7.setLayoutParams(new LinearLayout.LayoutParams(1935, 1309));
        this.enwuzlzyzl.setPadding(124, 193, 15, 70);
        linearLayout.addView(this.enwuzlzyzl);
        this.enwuzlzyzl.setBackgroundColor(Color.parseColor("#b9b2c2"));
        TimePicker timePicker13 = new TimePicker(this);
        this.psgihcnhrd = timePicker13;
        timePicker13.setLayoutParams(new LinearLayout.LayoutParams(899, 878));
        this.psgihcnhrd.setPadding(95, 122, 134, 11);
        linearLayout.addView(this.psgihcnhrd);
        this.psgihcnhrd.setBackgroundColor(Color.parseColor("#6b8234"));
        LinearLayout linearLayout12 = new LinearLayout(this);
        this.lfckdfrzws = linearLayout12;
        linearLayout12.setLayoutParams(new LinearLayout.LayoutParams(818, 198));
        this.lfckdfrzws.setPadding(17, 191, 114, 51);
        linearLayout.addView(this.lfckdfrzws);
        this.lfckdfrzws.setBackgroundColor(Color.parseColor("#ce5712"));
        ScrollView scrollView7 = new ScrollView(this);
        this.llddyawqbf = scrollView7;
        scrollView7.setLayoutParams(new LinearLayout.LayoutParams(383, 1792));
        this.llddyawqbf.setPadding(32, 113, 192, 52);
        linearLayout.addView(this.llddyawqbf);
        this.llddyawqbf.setBackgroundColor(Color.parseColor("#4fbfee"));
        Button button7 = new Button(this);
        this.kfttwpdetw = button7;
        button7.setLayoutParams(new LinearLayout.LayoutParams(1626, 1686));
        this.kfttwpdetw.setPadding(26, BDLocation.TypeNetWorkLocation, BDLocation.TypeCoarseLocation, 114);
        linearLayout.addView(this.kfttwpdetw);
        this.kfttwpdetw.setBackgroundColor(Color.parseColor("#ebe966"));
        DatePicker datePicker10 = new DatePicker(this);
        this.wknzgwmpxx = datePicker10;
        datePicker10.setLayoutParams(new LinearLayout.LayoutParams(178, 860));
        this.wknzgwmpxx.setPadding(26, 48, 88, 190);
        linearLayout.addView(this.wknzgwmpxx);
        this.wknzgwmpxx.setBackgroundColor(Color.parseColor("#60a7dc"));
        Button button8 = new Button(this);
        this.resrnzalhi = button8;
        button8.setLayoutParams(new LinearLayout.LayoutParams(447, 303));
        this.resrnzalhi.setPadding(1, 100, 124, 4);
        linearLayout.addView(this.resrnzalhi);
        this.resrnzalhi.setBackgroundColor(Color.parseColor("#2f74b3"));
        CheckBox checkBox13 = new CheckBox(this);
        this.vxbplztdgu = checkBox13;
        checkBox13.setLayoutParams(new LinearLayout.LayoutParams(1366, 595));
        this.vxbplztdgu.setPadding(39, BDLocation.TypeNetWorkLocation, 82, 112);
        linearLayout.addView(this.vxbplztdgu);
        this.vxbplztdgu.setBackgroundColor(Color.parseColor("#3fb402"));
        ProgressBar progressBar9 = new ProgressBar(this);
        this.oamenzpsdm = progressBar9;
        progressBar9.setLayoutParams(new LinearLayout.LayoutParams(1389, 1887));
        this.oamenzpsdm.setPadding(15, 151, 140, 134);
        linearLayout.addView(this.oamenzpsdm);
        this.oamenzpsdm.setBackgroundColor(Color.parseColor("#0dd277"));
        RatingBar ratingBar11 = new RatingBar(this);
        this.sufyjjtoyy = ratingBar11;
        ratingBar11.setLayoutParams(new LinearLayout.LayoutParams(1174, 94));
        this.sufyjjtoyy.setPadding(49, 93, 158, 60);
        linearLayout.addView(this.sufyjjtoyy);
        this.sufyjjtoyy.setBackgroundColor(Color.parseColor("#bdb466"));
        ImageView imageView8 = new ImageView(this);
        this.eaodpsctux = imageView8;
        imageView8.setLayoutParams(new LinearLayout.LayoutParams(864, 1084));
        this.eaodpsctux.setPadding(49, 82, 183, 4);
        linearLayout.addView(this.eaodpsctux);
        this.eaodpsctux.setBackgroundColor(Color.parseColor("#d58c6f"));
        Switch r27 = new Switch(this);
        this.bhhvtkixpi = r27;
        r27.setLayoutParams(new LinearLayout.LayoutParams(688, 1074));
        this.bhhvtkixpi.setPadding(101, 60, 180, 19);
        linearLayout.addView(this.bhhvtkixpi);
        this.bhhvtkixpi.setBackgroundColor(Color.parseColor("#ba6529"));
        ListView listView8 = new ListView(this);
        this.pnbxbhowdp = listView8;
        listView8.setLayoutParams(new LinearLayout.LayoutParams(487, 327));
        this.pnbxbhowdp.setPadding(68, 144, 48, 32);
        linearLayout.addView(this.pnbxbhowdp);
        this.pnbxbhowdp.setBackgroundColor(Color.parseColor("#f296b9"));
        RelativeLayout relativeLayout10 = new RelativeLayout(this);
        this.cpffhpwsvx = relativeLayout10;
        relativeLayout10.setLayoutParams(new LinearLayout.LayoutParams(1796, 1181));
        this.cpffhpwsvx.setPadding(43, 116, 151, 59);
        linearLayout.addView(this.cpffhpwsvx);
        this.cpffhpwsvx.setBackgroundColor(Color.parseColor("#9bc40b"));
        DatePicker datePicker11 = new DatePicker(this);
        this.kkldipddtg = datePicker11;
        datePicker11.setLayoutParams(new LinearLayout.LayoutParams(1281, 92));
        this.kkldipddtg.setPadding(66, 28, 153, 140);
        linearLayout.addView(this.kkldipddtg);
        this.kkldipddtg.setBackgroundColor(Color.parseColor("#388dc8"));
        DatePicker datePicker12 = new DatePicker(this);
        this.efallnnimv = datePicker12;
        datePicker12.setLayoutParams(new LinearLayout.LayoutParams(1091, 1142));
        this.efallnnimv.setPadding(84, 128, 123, 11);
        linearLayout.addView(this.efallnnimv);
        this.efallnnimv.setBackgroundColor(Color.parseColor("#665239"));
        RadioButton radioButton4 = new RadioButton(this);
        this.ktccorqrnp = radioButton4;
        radioButton4.setLayoutParams(new LinearLayout.LayoutParams(115, 543));
        this.ktccorqrnp.setPadding(91, 118, 113, 106);
        linearLayout.addView(this.ktccorqrnp);
        this.ktccorqrnp.setBackgroundColor(Color.parseColor("#158a3c"));
        TextView textView9 = new TextView(this);
        this.htulyvfjii = textView9;
        textView9.setLayoutParams(new LinearLayout.LayoutParams(466, 1247));
        this.htulyvfjii.setPadding(194, 113, 24, 148);
        linearLayout.addView(this.htulyvfjii);
        this.htulyvfjii.setBackgroundColor(Color.parseColor("#f98554"));
        EditText editText9 = new EditText(this);
        this.cixifqgyvm = editText9;
        editText9.setLayoutParams(new LinearLayout.LayoutParams(1920, 1919));
        this.cixifqgyvm.setPadding(142, 45, 71, 65);
        linearLayout.addView(this.cixifqgyvm);
        this.cixifqgyvm.setBackgroundColor(Color.parseColor("#3d14d3"));
        ListView listView9 = new ListView(this);
        this.rwmkgvzqfs = listView9;
        listView9.setLayoutParams(new LinearLayout.LayoutParams(485, 1525));
        this.rwmkgvzqfs.setPadding(76, 54, 117, 169);
        linearLayout.addView(this.rwmkgvzqfs);
        this.rwmkgvzqfs.setBackgroundColor(Color.parseColor("#22ba1c"));
        GridView gridView13 = new GridView(this);
        this.eenhcghkwb = gridView13;
        gridView13.setLayoutParams(new LinearLayout.LayoutParams(672, 693));
        this.eenhcghkwb.setPadding(134, 109, 85, 26);
        linearLayout.addView(this.eenhcghkwb);
        this.eenhcghkwb.setBackgroundColor(Color.parseColor("#fec047"));
        Spinner spinner9 = new Spinner(this);
        this.dbkhzdyhwc = spinner9;
        spinner9.setLayoutParams(new LinearLayout.LayoutParams(308, 1342));
        this.dbkhzdyhwc.setPadding(41, 175, 53, 199);
        linearLayout.addView(this.dbkhzdyhwc);
        this.dbkhzdyhwc.setBackgroundColor(Color.parseColor("#844155"));
        GridView gridView14 = new GridView(this);
        this.clogjkfyru = gridView14;
        gridView14.setLayoutParams(new LinearLayout.LayoutParams(1099, 1061));
        this.clogjkfyru.setPadding(46, 153, 94, 189);
        linearLayout.addView(this.clogjkfyru);
        this.clogjkfyru.setBackgroundColor(Color.parseColor("#d9f6c3"));
        LinearLayout linearLayout13 = new LinearLayout(this);
        this.jjmastulkd = linearLayout13;
        linearLayout13.setLayoutParams(new LinearLayout.LayoutParams(506, 1480));
        this.jjmastulkd.setPadding(33, 92, 102, 20);
        linearLayout.addView(this.jjmastulkd);
        this.jjmastulkd.setBackgroundColor(Color.parseColor("#c47955"));
        TextView textView10 = new TextView(this);
        this.gavrckpzrf = textView10;
        textView10.setLayoutParams(new LinearLayout.LayoutParams(1788, 506));
        this.gavrckpzrf.setPadding(134, 41, 41, 143);
        linearLayout.addView(this.gavrckpzrf);
        this.gavrckpzrf.setBackgroundColor(Color.parseColor("#838943"));
        LinearLayout linearLayout14 = new LinearLayout(this);
        this.sansaasodu = linearLayout14;
        linearLayout14.setLayoutParams(new LinearLayout.LayoutParams(1986, 287));
        this.sansaasodu.setPadding(64, 145, 158, 49);
        linearLayout.addView(this.sansaasodu);
        this.sansaasodu.setBackgroundColor(Color.parseColor("#ab352f"));
        CheckBox checkBox14 = new CheckBox(this);
        this.zevlsyvxnz = checkBox14;
        checkBox14.setLayoutParams(new LinearLayout.LayoutParams(575, 1756));
        this.zevlsyvxnz.setPadding(140, 140, 45, 54);
        linearLayout.addView(this.zevlsyvxnz);
        this.zevlsyvxnz.setBackgroundColor(Color.parseColor("#6af7f4"));
        FrameLayout frameLayout11 = new FrameLayout(this);
        this.myyijtbinn = frameLayout11;
        frameLayout11.setLayoutParams(new LinearLayout.LayoutParams(601, 1926));
        this.myyijtbinn.setPadding(131, 155, 21, 35);
        linearLayout.addView(this.myyijtbinn);
        this.myyijtbinn.setBackgroundColor(Color.parseColor("#d0788c"));
        Button button9 = new Button(this);
        this.flkznuepgx = button9;
        button9.setLayoutParams(new LinearLayout.LayoutParams(355, 460));
        this.flkznuepgx.setPadding(165, 165, 51, 114);
        linearLayout.addView(this.flkznuepgx);
        this.flkznuepgx.setBackgroundColor(Color.parseColor("#d4ba99"));
        RadioButton radioButton5 = new RadioButton(this);
        this.lzvzxwkmnx = radioButton5;
        radioButton5.setLayoutParams(new LinearLayout.LayoutParams(1183, 27));
        this.lzvzxwkmnx.setPadding(129, 131, 63, 100);
        linearLayout.addView(this.lzvzxwkmnx);
        this.lzvzxwkmnx.setBackgroundColor(Color.parseColor("#311949"));
        Spinner spinner10 = new Spinner(this);
        this.zbnariaerj = spinner10;
        spinner10.setLayoutParams(new LinearLayout.LayoutParams(1001, 1157));
        this.zbnariaerj.setPadding(BDLocation.TypeNetWorkLocation, 184, 152, 132);
        linearLayout.addView(this.zbnariaerj);
        this.zbnariaerj.setBackgroundColor(Color.parseColor("#5712f7"));
        TimePicker timePicker14 = new TimePicker(this);
        this.niysuxwavn = timePicker14;
        timePicker14.setLayoutParams(new LinearLayout.LayoutParams(1559, 549));
        this.niysuxwavn.setPadding(3, 49, 175, 93);
        linearLayout.addView(this.niysuxwavn);
        this.niysuxwavn.setBackgroundColor(Color.parseColor("#ceb473"));
        ScrollView scrollView8 = new ScrollView(this);
        this.nnibgmsnep = scrollView8;
        scrollView8.setLayoutParams(new LinearLayout.LayoutParams(1859, 1419));
        this.nnibgmsnep.setPadding(180, 13, 9, 41);
        linearLayout.addView(this.nnibgmsnep);
        this.nnibgmsnep.setBackgroundColor(Color.parseColor("#b927d6"));
        SeekBar seekBar7 = new SeekBar(this);
        this.pwmhbmowwm = seekBar7;
        seekBar7.setLayoutParams(new LinearLayout.LayoutParams(1075, 776));
        this.pwmhbmowwm.setPadding(69, 65, 37, 71);
        linearLayout.addView(this.pwmhbmowwm);
        this.pwmhbmowwm.setBackgroundColor(Color.parseColor("#6b03e0"));
        Button button10 = new Button(this);
        this.ivirstaqju = button10;
        button10.setLayoutParams(new LinearLayout.LayoutParams(951, 814));
        this.ivirstaqju.setPadding(56, 138, 61, 103);
        linearLayout.addView(this.ivirstaqju);
        this.ivirstaqju.setBackgroundColor(Color.parseColor("#5f09aa"));
        GridView gridView15 = new GridView(this);
        this.bddtzuwrex = gridView15;
        gridView15.setLayoutParams(new LinearLayout.LayoutParams(1449, 1423));
        this.bddtzuwrex.setPadding(20, 24, 26, 76);
        linearLayout.addView(this.bddtzuwrex);
        this.bddtzuwrex.setBackgroundColor(Color.parseColor("#a12536"));
        RatingBar ratingBar12 = new RatingBar(this);
        this.yeavwsfeze = ratingBar12;
        ratingBar12.setLayoutParams(new LinearLayout.LayoutParams(1819, 391));
        this.yeavwsfeze.setPadding(12, 52, 159, 173);
        linearLayout.addView(this.yeavwsfeze);
        this.yeavwsfeze.setBackgroundColor(Color.parseColor("#fddf21"));
        DatePicker datePicker13 = new DatePicker(this);
        this.zbpsmbtwpd = datePicker13;
        datePicker13.setLayoutParams(new LinearLayout.LayoutParams(769, 1423));
        this.zbpsmbtwpd.setPadding(119, 173, 7, 41);
        linearLayout.addView(this.zbpsmbtwpd);
        this.zbpsmbtwpd.setBackgroundColor(Color.parseColor("#e8d64e"));
        CheckBox checkBox15 = new CheckBox(this);
        this.hyzukxsojc = checkBox15;
        checkBox15.setLayoutParams(new LinearLayout.LayoutParams(1431, 1576));
        this.hyzukxsojc.setPadding(24, 61, 98, 190);
        linearLayout.addView(this.hyzukxsojc);
        this.hyzukxsojc.setBackgroundColor(Color.parseColor("#ba0bdd"));
        TableLayout tableLayout8 = new TableLayout(this);
        this.gayystznbr = tableLayout8;
        tableLayout8.setLayoutParams(new LinearLayout.LayoutParams(1381, 1369));
        this.gayystznbr.setPadding(46, 27, 26, 77);
        linearLayout.addView(this.gayystznbr);
        this.gayystznbr.setBackgroundColor(Color.parseColor("#475cb1"));
        GridView gridView16 = new GridView(this);
        this.lydlsyubiw = gridView16;
        gridView16.setLayoutParams(new LinearLayout.LayoutParams(214, 95));
        this.lydlsyubiw.setPadding(199, 37, 60, 77);
        linearLayout.addView(this.lydlsyubiw);
        this.lydlsyubiw.setBackgroundColor(Color.parseColor("#cb6f0c"));
        Button button11 = new Button(this);
        this.ujhsbqdgdq = button11;
        button11.setLayoutParams(new LinearLayout.LayoutParams(1536, 247));
        this.ujhsbqdgdq.setPadding(166, 109, 50, 17);
        linearLayout.addView(this.ujhsbqdgdq);
        this.ujhsbqdgdq.setBackgroundColor(Color.parseColor("#94710c"));
        ProgressBar progressBar10 = new ProgressBar(this);
        this.fgtvdhmgqx = progressBar10;
        progressBar10.setLayoutParams(new LinearLayout.LayoutParams(101, 1778));
        this.fgtvdhmgqx.setPadding(44, 76, 157, 136);
        linearLayout.addView(this.fgtvdhmgqx);
        this.fgtvdhmgqx.setBackgroundColor(Color.parseColor("#1e8620"));
        RadioButton radioButton6 = new RadioButton(this);
        this.urnzuxiawb = radioButton6;
        radioButton6.setLayoutParams(new LinearLayout.LayoutParams(912, 1325));
        this.urnzuxiawb.setPadding(12, BDLocation.TypeServerError, WebSocketProtocol.PAYLOAD_SHORT, 136);
        linearLayout.addView(this.urnzuxiawb);
        this.urnzuxiawb.setBackgroundColor(Color.parseColor("#eb07e8"));
        CheckBox checkBox16 = new CheckBox(this);
        this.zbmzpznpwj = checkBox16;
        checkBox16.setLayoutParams(new LinearLayout.LayoutParams(1443, 418));
        this.zbmzpznpwj.setPadding(23, 149, 141, 55);
        linearLayout.addView(this.zbmzpznpwj);
        this.zbmzpznpwj.setBackgroundColor(Color.parseColor("#4042f9"));
        GridView gridView17 = new GridView(this);
        this.xbfazlhfzj = gridView17;
        gridView17.setLayoutParams(new LinearLayout.LayoutParams(357, 648));
        this.xbfazlhfzj.setPadding(86, 154, 18, 79);
        linearLayout.addView(this.xbfazlhfzj);
        this.xbfazlhfzj.setBackgroundColor(Color.parseColor("#67755e"));
        GridView gridView18 = new GridView(this);
        this.zhpybtcopr = gridView18;
        gridView18.setLayoutParams(new LinearLayout.LayoutParams(1777, 1531));
        this.zhpybtcopr.setPadding(198, 172, 41, 157);
        linearLayout.addView(this.zhpybtcopr);
        this.zhpybtcopr.setBackgroundColor(Color.parseColor("#3fa911"));
        TableLayout tableLayout9 = new TableLayout(this);
        this.mzkvsfnkve = tableLayout9;
        tableLayout9.setLayoutParams(new LinearLayout.LayoutParams(1392, 1712));
        this.mzkvsfnkve.setPadding(190, 39, 67, 21);
        linearLayout.addView(this.mzkvsfnkve);
        this.mzkvsfnkve.setBackgroundColor(Color.parseColor("#6d063e"));
        Switch r28 = new Switch(this);
        this.nuiqwkuvrn = r28;
        r28.setLayoutParams(new LinearLayout.LayoutParams(256, PDF417Common.NUMBER_OF_CODEWORDS));
        this.nuiqwkuvrn.setPadding(181, 174, 199, 92);
        linearLayout.addView(this.nuiqwkuvrn);
        this.nuiqwkuvrn.setBackgroundColor(Color.parseColor("#f74397"));
        SeekBar seekBar8 = new SeekBar(this);
        this.kvjhjsqjly = seekBar8;
        seekBar8.setLayoutParams(new LinearLayout.LayoutParams(1574, 1944));
        this.kvjhjsqjly.setPadding(103, 1, 55, 59);
        linearLayout.addView(this.kvjhjsqjly);
        this.kvjhjsqjly.setBackgroundColor(Color.parseColor("#c662a2"));
        RatingBar ratingBar13 = new RatingBar(this);
        this.jhhuhvkcsy = ratingBar13;
        ratingBar13.setLayoutParams(new LinearLayout.LayoutParams(1718, 1747));
        this.jhhuhvkcsy.setPadding(55, 190, 150, 196);
        linearLayout.addView(this.jhhuhvkcsy);
        this.jhhuhvkcsy.setBackgroundColor(Color.parseColor("#5c27f3"));
        DatePicker datePicker14 = new DatePicker(this);
        this.swopsfyywc = datePicker14;
        datePicker14.setLayoutParams(new LinearLayout.LayoutParams(1979, 1532));
        this.swopsfyywc.setPadding(63, 70, 63, 28);
        linearLayout.addView(this.swopsfyywc);
        this.swopsfyywc.setBackgroundColor(Color.parseColor("#932817"));
    }
}
