package com.smartapp.b.rvlwkphkxd;

import android.app.Activity;
import android.graphics.Color;
import android.os.Bundle;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.CheckBox;
import android.widget.DatePicker;
import android.widget.EditText;
import android.widget.FrameLayout;
import android.widget.GridView;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ListView;
import android.widget.ProgressBar;
import android.widget.RadioButton;
import android.widget.RatingBar;
import android.widget.RelativeLayout;
import android.widget.ScrollView;
import android.widget.SeekBar;
import android.widget.Spinner;
import android.widget.Switch;
import android.widget.TableLayout;
import android.widget.TextView;
import android.widget.TimePicker;
import android.widget.ToggleButton;
import android.widget.ViewFlipper;
import androidx.constraintlayout.core.motion.utils.TypedValues;
import com.baidu.location.BDLocation;
import com.google.zxing.pdf417.PDF417Common;
import com.king.zxing.util.CodeUtils;
import com.luck.picture.lib.config.PictureConfig;
import com.qcwireless.qcwatch.ui.home.healthy.vm.HealthyViewModel;
import com.realsil.sdk.audioconnect.localplayback.LocalPlaybackConstants;
import com.realsil.sdk.core.bluetooth.connection.le.GattClient;
import okhttp3.internal.ws.WebSocketProtocol;

/* loaded from: classes4.dex */
public class GgteuldbamrActivity extends Activity {
    RadioButton aahwnkubro;
    Switch adjzmbuxyg;
    RadioButton afrdqpdpst;
    TableLayout aimddlkyid;
    LinearLayout aiqlnwgtkf;
    TimePicker amfaelosqa;
    ProgressBar anldpbmujb;
    Button anxmsxlppv;
    LinearLayout apbvcomrvn;
    GridView arpkbumegn;
    SeekBar atacdevnqr;
    TimePicker autlgrrvdr;
    ViewFlipper avjptovvmk;
    TextView awfxmlcoeu;
    CheckBox baziiklcmv;
    ScrollView bbfcpoycaq;
    GridView bjzvgtdvts;
    ListView bklbrkqbfd;
    RatingBar cekcxibdyh;
    DatePicker cigxvruepo;
    Button cirauyaxqr;
    ListView cjzgeymvez;
    ViewFlipper clhrbnarvx;
    Button clvvqqorzz;
    ToggleButton cnzxmmepnu;
    DatePicker cqvfkyoltz;
    TableLayout cxfqmahpma;
    TextView cyegxjzzaf;
    ScrollView dcmabkulbz;
    EditText detpndqmga;
    SeekBar dicallybgl;
    ViewFlipper dldyvkovtq;
    RadioButton dmdgncjubk;
    RadioButton dvmrfducib;
    GridView eaddqvaqnb;
    ViewFlipper eaxovnwecx;
    Button ebljnhtnnr;
    TimePicker edptrihxtf;
    TableLayout eeijxykskg;
    Switch eijzljrvzj;
    RatingBar ejqutqbakw;
    ToggleButton eoqukontaz;
    LinearLayout eqyquzwhoy;
    RatingBar ewuqjuyrin;
    SeekBar fdvpevnjzh;
    ToggleButton ffbulnwrqk;
    TimePicker ffsdzwtkdz;
    TextView fgcmifxpku;
    ProgressBar fnfemoyfzj;
    Button fnzaaxpfyj;
    GridView ftwqcnxkoz;
    ToggleButton fuqhghidxz;
    RadioButton fvohkmejdv;
    RatingBar fylsbrfwso;
    DatePicker fyqbwavpxu;
    ImageView gaqwpcqnxm;
    TimePicker gblxkoaxol;
    GridView gpgsttcjsa;
    TextView gprwyvcjht;
    RadioButton gqspvkjnkt;
    ToggleButton gunesvntbh;
    ProgressBar gyjkhboabo;
    LinearLayout heeupyxlsf;
    TimePicker hjvoemkmrf;
    ToggleButton howttndfaw;
    Spinner hsgdxdwhts;
    TextView hsnjqutukm;
    ViewFlipper hykrkxyndu;
    DatePicker hzkxtrnhxc;
    Spinner iedilswsuj;
    DatePicker ieypjcaoxn;
    LinearLayout igahjrtxep;
    ImageView igvqfcxvdf;
    ViewFlipper igyaupwezt;
    RadioButton ikavqlgaea;
    Button ipzrwupbin;
    FrameLayout iuujmxpsqc;
    ImageView ixvhwyicqy;
    CheckBox jagoycvacm;
    ViewFlipper jbogmdtpzk;
    RadioButton jdfxoeuiht;
    ListView jmydeduaom;
    ViewFlipper jnpvggpcob;
    Spinner jodsevynso;
    Spinner jpskkxrwck;
    ViewFlipper jqapjropxi;
    Switch jtkclanqxc;
    ProgressBar jtuuzzdtmk;
    RatingBar judvlhunwz;
    FrameLayout kbbqkqluen;
    TimePicker kddfmzxmmi;
    ScrollView kjgjrrdxul;
    SeekBar kjkktzyctu;
    SeekBar kswcejepgs;
    ViewFlipper kuywsjrvaq;
    SeekBar kwkpfmpzla;
    TextView kyrhjwxvhx;
    RatingBar kzakyicngb;
    RatingBar kzzodzgteh;
    Switch lbuwwngehh;
    RatingBar lizgexzwjc;
    TimePicker llavggzfoj;
    GridView lliyzbvcxr;
    Switch lovpedflok;
    ImageView lpxyhxscrf;
    ScrollView lrvtotrysc;
    Switch lvgtnopafu;
    DatePicker lwbimtawop;
    ListView lwfdwvzkuv;
    FrameLayout lwnsivazwp;
    Switch mcpiapvsxk;
    RadioButton mfdwecyubb;
    ViewFlipper miqowfuoxl;
    EditText mkdrqznuvs;
    TimePicker mlxmmqqtss;
    ImageView mojpeodrfp;
    CheckBox mqnnuozdmj;
    RadioButton mqpmzpukhc;
    ScrollView muhjjomcly;
    ScrollView mwbmwwedgt;
    DatePicker naeqowbsqu;
    TimePicker nafwbeojkq;
    TableLayout nnacauelcz;
    CheckBox nnjzbquktv;
    FrameLayout ntxnhpsnzc;
    GridView nufrsczori;
    FrameLayout nzfsugawpx;
    FrameLayout ogbxigkoor;
    ImageView oiyqxqzafd;
    ToggleButton olpzvbsxeu;
    CheckBox oqismhebvr;
    DatePicker oqmtibkppr;
    LinearLayout osbdtkhpxg;
    RadioButton otihpouqot;
    DatePicker ovhtfywnvs;
    TableLayout ozpamnpnlr;
    ImageView pfsugjahel;
    ScrollView pfzcpihyaa;
    FrameLayout pgzoimvhdn;
    ViewFlipper pjnphpfmkz;
    SeekBar pjteixzipn;
    DatePicker pkomkduvef;
    ViewFlipper plcjbxyvws;
    EditText pqspejgqrt;
    FrameLayout ptddlmxcqn;
    RelativeLayout pxghodftek;
    TableLayout qcsynwqaea;
    RelativeLayout qcwqcqeqqw;
    CheckBox qcxxthciir;
    ProgressBar qnqfkeeqqk;
    LinearLayout qrfkekyuhx;
    Button quxjervghe;
    RatingBar raqmbcaieg;
    Spinner rhqzznygdz;
    TimePicker rnugiiiukp;
    EditText rnvisdmfrg;
    RatingBar rorovcndtm;
    Switch rsocbnfexk;
    ScrollView ruvgtyftul;
    Spinner sbjyxpthtt;
    Switch sdqzthdmhl;
    ToggleButton sedihfdene;
    ViewFlipper sfcuhzlayo;
    SeekBar sfdalcayeh;
    ImageView sgrknudlxw;
    EditText siqoevpvez;
    ScrollView smgyxfqgbv;
    ToggleButton smpnyzjgsz;
    TimePicker snikrozgdi;
    CheckBox sntgghumrq;
    ScrollView snwrlgkiba;
    RadioButton sphvqvuvya;
    RelativeLayout srvjcyajyj;
    FrameLayout ssnxowpjed;
    ScrollView sstswxdlnh;
    Spinner swaqgqhato;
    RatingBar swcuueuiil;
    CheckBox szjkytzcxa;
    GridView teddsmnzag;
    ScrollView tolxxfwppg;
    LinearLayout tuntbsagbz;
    EditText twdpxufort;
    ProgressBar uclmabmewh;
    ToggleButton ugdnsfhciz;
    SeekBar ukrzyvvvpl;
    TextView umysrlvgou;
    SeekBar updgeeweel;
    RelativeLayout uqniedbkaj;
    GridView urybzfooqn;
    ProgressBar uurtoqijyh;
    ToggleButton uvvpnyezcd;
    TimePicker uywsepgzbi;
    TableLayout vckzjzcjiz;
    EditText veodjmbkrm;
    ProgressBar vnlgiqdexw;
    RelativeLayout vnogvcnhuo;
    ProgressBar vpdgpjrmgt;
    LinearLayout vwhanknotp;
    ImageView vxaetzgboc;
    LinearLayout vxailqosow;
    ImageView vxluhhjgai;
    TextView vymxavypzu;
    TableLayout wmmfgxmhri;
    CheckBox wrlkzowmfo;
    FrameLayout wtscenxuxj;
    ImageView wxsqktjqgc;
    ListView xgkmewapfh;
    ScrollView xqqkiphfaa;
    ScrollView xsbygnobbo;
    CheckBox xtfcbcnmos;
    ProgressBar xwrzmmwlwm;
    FrameLayout xxchkobxrw;
    TextView xzhvkyklln;
    ImageView ycbztkyeyc;
    ToggleButton ydedtpwhlz;
    ToggleButton ykmkeuyyjy;
    CheckBox ynpxxhphju;
    DatePicker yoepwgwnkb;
    TimePicker yoperxacdu;
    ViewFlipper yoxtypuexv;
    TableLayout yshedsfozw;
    Button yslkqxaxwh;
    Spinner ysziwygtxj;
    GridView ywhktutecf;
    RatingBar yyrssxgouy;
    ScrollView yyupleximr;
    TextView zabzlnejsn;
    RelativeLayout zakuuiurgj;
    ToggleButton zaletsdbgs;
    GridView zgzeydjzci;
    ProgressBar zhodwdzsir;
    DatePicker zhskatgcvl;
    ListView zpbwgnvmfm;
    CheckBox zpwsiiymqg;
    CheckBox ztqfqopxol;
    RelativeLayout ztvyoqoroj;
    Button zwypftkokw;
    ProgressBar zyjbmbvsxu;
    FrameLayout zyqfhjgjzl;

    @Override // android.app.Activity
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        LinearLayout linearLayout = new LinearLayout(this);
        setContentView(linearLayout);
        linearLayout.setLayoutParams(new ViewGroup.LayoutParams(-1, -1));
        linearLayout.setOrientation(1);
        linearLayout.setBackgroundColor(Color.parseColor("#be9a97"));
        ViewFlipper viewFlipper = new ViewFlipper(this);
        this.plcjbxyvws = viewFlipper;
        viewFlipper.setLayoutParams(new LinearLayout.LayoutParams(357, 1595));
        this.plcjbxyvws.setPadding(150, BDLocation.TypeCoarseLocation, 71, 54);
        linearLayout.addView(this.plcjbxyvws);
        this.plcjbxyvws.setBackgroundColor(Color.parseColor("#bbe467"));
        ScrollView scrollView = new ScrollView(this);
        this.kjgjrrdxul = scrollView;
        scrollView.setLayoutParams(new LinearLayout.LayoutParams(1949, 674));
        this.kjgjrrdxul.setPadding(18, 136, 180, 89);
        linearLayout.addView(this.kjgjrrdxul);
        this.kjgjrrdxul.setBackgroundColor(Color.parseColor("#746e32"));
        TextView textView = new TextView(this);
        this.cyegxjzzaf = textView;
        textView.setLayoutParams(new LinearLayout.LayoutParams(776, 520));
        this.cyegxjzzaf.setPadding(168, 22, 197, 91);
        linearLayout.addView(this.cyegxjzzaf);
        this.cyegxjzzaf.setBackgroundColor(Color.parseColor("#1e964a"));
        SeekBar seekBar = new SeekBar(this);
        this.dicallybgl = seekBar;
        seekBar.setLayoutParams(new LinearLayout.LayoutParams(1236, 1032));
        this.dicallybgl.setPadding(14, 118, 174, 16);
        linearLayout.addView(this.dicallybgl);
        this.dicallybgl.setBackgroundColor(Color.parseColor("#ee7816"));
        Spinner spinner = new Spinner(this);
        this.jpskkxrwck = spinner;
        spinner.setLayoutParams(new LinearLayout.LayoutParams(762, 1033));
        this.jpskkxrwck.setPadding(BDLocation.TypeNetWorkLocation, 54, 136, 94);
        linearLayout.addView(this.jpskkxrwck);
        this.jpskkxrwck.setBackgroundColor(Color.parseColor("#dfebbd"));
        LinearLayout linearLayout2 = new LinearLayout(this);
        this.vwhanknotp = linearLayout2;
        linearLayout2.setLayoutParams(new LinearLayout.LayoutParams(918, 916));
        this.vwhanknotp.setPadding(16, 184, 106, 65);
        linearLayout.addView(this.vwhanknotp);
        this.vwhanknotp.setBackgroundColor(Color.parseColor("#8ccf0e"));
        ToggleButton toggleButton = new ToggleButton(this);
        this.ykmkeuyyjy = toggleButton;
        toggleButton.setLayoutParams(new LinearLayout.LayoutParams(PictureConfig.REQUEST_CAMERA, 1315));
        this.ykmkeuyyjy.setPadding(186, 107, 54, 73);
        linearLayout.addView(this.ykmkeuyyjy);
        this.ykmkeuyyjy.setBackgroundColor(Color.parseColor("#e6afaf"));
        ProgressBar progressBar = new ProgressBar(this);
        this.zhodwdzsir = progressBar;
        progressBar.setLayoutParams(new LinearLayout.LayoutParams(1814, 1651));
        this.zhodwdzsir.setPadding(143, 63, 8, 50);
        linearLayout.addView(this.zhodwdzsir);
        this.zhodwdzsir.setBackgroundColor(Color.parseColor("#520beb"));
        Spinner spinner2 = new Spinner(this);
        this.hsgdxdwhts = spinner2;
        spinner2.setLayoutParams(new LinearLayout.LayoutParams(1513, 143));
        this.hsgdxdwhts.setPadding(122, 27, 32, 111);
        linearLayout.addView(this.hsgdxdwhts);
        this.hsgdxdwhts.setBackground(new Quflkogcgmw());
        EditText editText = new EditText(this);
        this.detpndqmga = editText;
        editText.setLayoutParams(new LinearLayout.LayoutParams(1368, 664));
        this.detpndqmga.setPadding(7, 86, 66, 75);
        linearLayout.addView(this.detpndqmga);
        this.detpndqmga.setBackgroundColor(Color.parseColor("#d41611"));
        RadioButton radioButton = new RadioButton(this);
        this.sphvqvuvya = radioButton;
        radioButton.setLayoutParams(new LinearLayout.LayoutParams(222, 992));
        this.sphvqvuvya.setPadding(115, 96, 52, 90);
        linearLayout.addView(this.sphvqvuvya);
        this.sphvqvuvya.setBackgroundColor(Color.parseColor("#aa5ca0"));
        EditText editText2 = new EditText(this);
        this.mkdrqznuvs = editText2;
        editText2.setLayoutParams(new LinearLayout.LayoutParams(1314, 1647));
        this.mkdrqznuvs.setPadding(45, 13, 163, 146);
        linearLayout.addView(this.mkdrqznuvs);
        this.mkdrqznuvs.setBackgroundColor(Color.parseColor("#d44901"));
        ToggleButton toggleButton2 = new ToggleButton(this);
        this.ugdnsfhciz = toggleButton2;
        toggleButton2.setLayoutParams(new LinearLayout.LayoutParams(1509, 1115));
        this.ugdnsfhciz.setPadding(91, 156, 75, 14);
        linearLayout.addView(this.ugdnsfhciz);
        this.ugdnsfhciz.setBackgroundColor(Color.parseColor("#adf1c6"));
        RadioButton radioButton2 = new RadioButton(this);
        this.dmdgncjubk = radioButton2;
        radioButton2.setLayoutParams(new LinearLayout.LayoutParams(1231, 1178));
        this.dmdgncjubk.setPadding(72, 15, 129, 46);
        linearLayout.addView(this.dmdgncjubk);
        this.dmdgncjubk.setBackgroundColor(Color.parseColor("#5229f7"));
        EditText editText3 = new EditText(this);
        this.rnvisdmfrg = editText3;
        editText3.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.TransitionType.TYPE_STAGGERED, 1072));
        this.rnvisdmfrg.setPadding(76, 142, 143, 164);
        linearLayout.addView(this.rnvisdmfrg);
        this.rnvisdmfrg.setBackgroundColor(Color.parseColor("#11a8d5"));
        ProgressBar progressBar2 = new ProgressBar(this);
        this.anldpbmujb = progressBar2;
        progressBar2.setLayoutParams(new LinearLayout.LayoutParams(287, 914));
        this.anldpbmujb.setPadding(99, 27, 118, 9);
        linearLayout.addView(this.anldpbmujb);
        this.anldpbmujb.setBackgroundColor(Color.parseColor("#a11e81"));
        GridView gridView = new GridView(this);
        this.ywhktutecf = gridView;
        gridView.setLayoutParams(new LinearLayout.LayoutParams(1933, 1469));
        this.ywhktutecf.setPadding(151, 50, 147, 68);
        linearLayout.addView(this.ywhktutecf);
        this.ywhktutecf.setBackgroundColor(Color.parseColor("#34edac"));
        LinearLayout linearLayout3 = new LinearLayout(this);
        this.apbvcomrvn = linearLayout3;
        linearLayout3.setLayoutParams(new LinearLayout.LayoutParams(1713, 1356));
        this.apbvcomrvn.setPadding(97, 116, 182, 135);
        linearLayout.addView(this.apbvcomrvn);
        this.apbvcomrvn.setBackgroundColor(Color.parseColor("#270bfc"));
        RadioButton radioButton3 = new RadioButton(this);
        this.fvohkmejdv = radioButton3;
        radioButton3.setLayoutParams(new LinearLayout.LayoutParams(1807, 493));
        this.fvohkmejdv.setPadding(130, 8, 116, 86);
        linearLayout.addView(this.fvohkmejdv);
        this.fvohkmejdv.setBackgroundColor(Color.parseColor("#e4cefb"));
        ProgressBar progressBar3 = new ProgressBar(this);
        this.vnlgiqdexw = progressBar3;
        progressBar3.setLayoutParams(new LinearLayout.LayoutParams(1287, 487));
        this.vnlgiqdexw.setPadding(48, 141, 93, 140);
        linearLayout.addView(this.vnlgiqdexw);
        this.vnlgiqdexw.setBackgroundColor(Color.parseColor("#3b55e0"));
        SeekBar seekBar2 = new SeekBar(this);
        this.pjteixzipn = seekBar2;
        seekBar2.setLayoutParams(new LinearLayout.LayoutParams(1124, 1442));
        this.pjteixzipn.setPadding(3, 71, 127, 124);
        linearLayout.addView(this.pjteixzipn);
        this.pjteixzipn.setBackgroundColor(Color.parseColor("#2e23b4"));
        DatePicker datePicker = new DatePicker(this);
        this.hzkxtrnhxc = datePicker;
        datePicker.setLayoutParams(new LinearLayout.LayoutParams(1782, 1610));
        this.hzkxtrnhxc.setPadding(127, 148, 146, 105);
        linearLayout.addView(this.hzkxtrnhxc);
        this.hzkxtrnhxc.setBackgroundColor(Color.parseColor("#014d05"));
        DatePicker datePicker2 = new DatePicker(this);
        this.oqmtibkppr = datePicker2;
        datePicker2.setLayoutParams(new LinearLayout.LayoutParams(616, 1178));
        this.oqmtibkppr.setPadding(28, 75, 53, 138);
        linearLayout.addView(this.oqmtibkppr);
        this.oqmtibkppr.setBackgroundColor(Color.parseColor("#42bf30"));
        TextView textView2 = new TextView(this);
        this.awfxmlcoeu = textView2;
        textView2.setLayoutParams(new LinearLayout.LayoutParams(724, 1978));
        this.awfxmlcoeu.setPadding(40, 146, 142, 38);
        linearLayout.addView(this.awfxmlcoeu);
        this.awfxmlcoeu.setBackgroundColor(Color.parseColor("#59dd3b"));
        CheckBox checkBox = new CheckBox(this);
        this.xtfcbcnmos = checkBox;
        checkBox.setLayoutParams(new LinearLayout.LayoutParams(330, 1053));
        this.xtfcbcnmos.setPadding(14, 106, 17, 184);
        linearLayout.addView(this.xtfcbcnmos);
        this.xtfcbcnmos.setBackgroundColor(Color.parseColor("#e4ed14"));
        TimePicker timePicker = new TimePicker(this);
        this.autlgrrvdr = timePicker;
        timePicker.setLayoutParams(new LinearLayout.LayoutParams(1592, 1697));
        this.autlgrrvdr.setPadding(192, 16, 102, 199);
        linearLayout.addView(this.autlgrrvdr);
        this.autlgrrvdr.setBackgroundColor(Color.parseColor("#05256d"));
        ViewFlipper viewFlipper2 = new ViewFlipper(this);
        this.kuywsjrvaq = viewFlipper2;
        viewFlipper2.setLayoutParams(new LinearLayout.LayoutParams(1949, 1451));
        this.kuywsjrvaq.setPadding(103, 185, 93, 21);
        linearLayout.addView(this.kuywsjrvaq);
        this.kuywsjrvaq.setBackgroundColor(Color.parseColor("#55513e"));
        ListView listView = new ListView(this);
        this.jmydeduaom = listView;
        listView.setLayoutParams(new LinearLayout.LayoutParams(1326, 966));
        this.jmydeduaom.setPadding(74, 66, 165, 90);
        linearLayout.addView(this.jmydeduaom);
        this.jmydeduaom.setBackgroundColor(Color.parseColor("#ed9132"));
        TimePicker timePicker2 = new TimePicker(this);
        this.nafwbeojkq = timePicker2;
        timePicker2.setLayoutParams(new LinearLayout.LayoutParams(546, 1329));
        this.nafwbeojkq.setPadding(69, 66, 136, 12);
        linearLayout.addView(this.nafwbeojkq);
        this.nafwbeojkq.setBackgroundColor(Color.parseColor("#64ccc9"));
        TimePicker timePicker3 = new TimePicker(this);
        this.rnugiiiukp = timePicker3;
        timePicker3.setLayoutParams(new LinearLayout.LayoutParams(482, 587));
        this.rnugiiiukp.setPadding(96, 190, 92, 94);
        linearLayout.addView(this.rnugiiiukp);
        this.rnugiiiukp.setBackgroundColor(Color.parseColor("#7ff727"));
        Button button = new Button(this);
        this.quxjervghe = button;
        button.setLayoutParams(new LinearLayout.LayoutParams(1584, 436));
        this.quxjervghe.setPadding(128, 136, 27, 82);
        linearLayout.addView(this.quxjervghe);
        this.quxjervghe.setBackgroundColor(Color.parseColor("#09864f"));
        FrameLayout frameLayout = new FrameLayout(this);
        this.ntxnhpsnzc = frameLayout;
        frameLayout.setLayoutParams(new LinearLayout.LayoutParams(PDF417Common.NUMBER_OF_CODEWORDS, 1272));
        this.ntxnhpsnzc.setPadding(27, 164, 91, 92);
        linearLayout.addView(this.ntxnhpsnzc);
        this.ntxnhpsnzc.setBackgroundColor(Color.parseColor("#51b113"));
        FrameLayout frameLayout2 = new FrameLayout(this);
        this.nzfsugawpx = frameLayout2;
        frameLayout2.setLayoutParams(new LinearLayout.LayoutParams(1165, 1586));
        this.nzfsugawpx.setPadding(140, 144, 88, 44);
        linearLayout.addView(this.nzfsugawpx);
        this.nzfsugawpx.setBackgroundColor(Color.parseColor("#c806f6"));
        Button button2 = new Button(this);
        this.clvvqqorzz = button2;
        button2.setLayoutParams(new LinearLayout.LayoutParams(828, 1284));
        this.clvvqqorzz.setPadding(191, 174, 46, 72);
        linearLayout.addView(this.clvvqqorzz);
        this.clvvqqorzz.setBackgroundColor(Color.parseColor("#95c0b1"));
        ToggleButton toggleButton3 = new ToggleButton(this);
        this.sedihfdene = toggleButton3;
        toggleButton3.setLayoutParams(new LinearLayout.LayoutParams(1699, 1671));
        this.sedihfdene.setPadding(150, 40, 147, 132);
        linearLayout.addView(this.sedihfdene);
        this.sedihfdene.setBackgroundColor(Color.parseColor("#c60cb9"));
        RadioButton radioButton4 = new RadioButton(this);
        this.mfdwecyubb = radioButton4;
        radioButton4.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.CycleType.TYPE_EASING, 1003));
        this.mfdwecyubb.setPadding(137, BDLocation.TypeServerError, BDLocation.TypeNetWorkLocation, 95);
        linearLayout.addView(this.mfdwecyubb);
        this.mfdwecyubb.setBackgroundColor(Color.parseColor("#38c5c2"));
        TableLayout tableLayout = new TableLayout(this);
        this.aimddlkyid = tableLayout;
        tableLayout.setLayoutParams(new LinearLayout.LayoutParams(941, 708));
        this.aimddlkyid.setPadding(91, BDLocation.TypeServerDecryptError, 154, 195);
        linearLayout.addView(this.aimddlkyid);
        this.aimddlkyid.setBackgroundColor(Color.parseColor("#09007a"));
        TextView textView3 = new TextView(this);
        this.gprwyvcjht = textView3;
        textView3.setLayoutParams(new LinearLayout.LayoutParams(1407, 135));
        this.gprwyvcjht.setPadding(56, 119, 124, 33);
        linearLayout.addView(this.gprwyvcjht);
        this.gprwyvcjht.setBackgroundColor(Color.parseColor("#bc4f5e"));
        LinearLayout linearLayout4 = new LinearLayout(this);
        this.osbdtkhpxg = linearLayout4;
        linearLayout4.setLayoutParams(new LinearLayout.LayoutParams(1719, 1512));
        this.osbdtkhpxg.setPadding(20, 96, 45, 31);
        linearLayout.addView(this.osbdtkhpxg);
        this.osbdtkhpxg.setBackgroundColor(Color.parseColor("#c94edf"));
        Switch r2 = new Switch(this);
        this.lbuwwngehh = r2;
        r2.setLayoutParams(new LinearLayout.LayoutParams(226, 1914));
        this.lbuwwngehh.setPadding(0, 76, 25, 71);
        linearLayout.addView(this.lbuwwngehh);
        this.lbuwwngehh.setBackgroundColor(Color.parseColor("#2b98de"));
        ToggleButton toggleButton4 = new ToggleButton(this);
        this.fuqhghidxz = toggleButton4;
        toggleButton4.setLayoutParams(new LinearLayout.LayoutParams(1090, 362));
        this.fuqhghidxz.setPadding(125, 16, 86, 109);
        linearLayout.addView(this.fuqhghidxz);
        this.fuqhghidxz.setBackgroundColor(Color.parseColor("#775056"));
        CheckBox checkBox2 = new CheckBox(this);
        this.oqismhebvr = checkBox2;
        checkBox2.setLayoutParams(new LinearLayout.LayoutParams(1318, 960));
        this.oqismhebvr.setPadding(170, 137, 193, 60);
        linearLayout.addView(this.oqismhebvr);
        this.oqismhebvr.setBackgroundColor(Color.parseColor("#6cebf5"));
        CheckBox checkBox3 = new CheckBox(this);
        this.ynpxxhphju = checkBox3;
        checkBox3.setLayoutParams(new LinearLayout.LayoutParams(718, 1899));
        this.ynpxxhphju.setPadding(138, 120, 138, 158);
        linearLayout.addView(this.ynpxxhphju);
        this.ynpxxhphju.setBackgroundColor(Color.parseColor("#13bf0e"));
        Switch r22 = new Switch(this);
        this.mcpiapvsxk = r22;
        r22.setLayoutParams(new LinearLayout.LayoutParams(1684, 736));
        this.mcpiapvsxk.setPadding(134, 10, 108, BDLocation.TypeServerError);
        linearLayout.addView(this.mcpiapvsxk);
        this.mcpiapvsxk.setBackgroundColor(Color.parseColor("#e48dd8"));
        RelativeLayout relativeLayout = new RelativeLayout(this);
        this.srvjcyajyj = relativeLayout;
        relativeLayout.setLayoutParams(new LinearLayout.LayoutParams(479, 983));
        this.srvjcyajyj.setPadding(194, 42, 87, 29);
        linearLayout.addView(this.srvjcyajyj);
        this.srvjcyajyj.setBackgroundColor(Color.parseColor("#68ad02"));
        Switch r23 = new Switch(this);
        this.lovpedflok = r23;
        r23.setLayoutParams(new LinearLayout.LayoutParams(1114, 1595));
        this.lovpedflok.setPadding(195, 36, 102, 14);
        linearLayout.addView(this.lovpedflok);
        this.lovpedflok.setBackgroundColor(Color.parseColor("#da4af9"));
        Switch r24 = new Switch(this);
        this.rsocbnfexk = r24;
        r24.setLayoutParams(new LinearLayout.LayoutParams(633, 1108));
        this.rsocbnfexk.setPadding(141, 55, 85, 6);
        linearLayout.addView(this.rsocbnfexk);
        this.rsocbnfexk.setBackgroundColor(Color.parseColor("#adefcf"));
        CheckBox checkBox4 = new CheckBox(this);
        this.jagoycvacm = checkBox4;
        checkBox4.setLayoutParams(new LinearLayout.LayoutParams(1332, 650));
        this.jagoycvacm.setPadding(122, 16, 3, 83);
        linearLayout.addView(this.jagoycvacm);
        this.jagoycvacm.setBackgroundColor(Color.parseColor("#47df7d"));
        ImageView imageView = new ImageView(this);
        this.ycbztkyeyc = imageView;
        imageView.setLayoutParams(new LinearLayout.LayoutParams(1029, 624));
        this.ycbztkyeyc.setPadding(46, 142, 118, 127);
        linearLayout.addView(this.ycbztkyeyc);
        this.ycbztkyeyc.setBackgroundColor(Color.parseColor("#54aec2"));
        RatingBar ratingBar = new RatingBar(this);
        this.cekcxibdyh = ratingBar;
        ratingBar.setLayoutParams(new LinearLayout.LayoutParams(852, 530));
        this.cekcxibdyh.setPadding(191, 199, 69, 177);
        linearLayout.addView(this.cekcxibdyh);
        this.cekcxibdyh.setBackgroundColor(Color.parseColor("#10f944"));
        ToggleButton toggleButton5 = new ToggleButton(this);
        this.olpzvbsxeu = toggleButton5;
        toggleButton5.setLayoutParams(new LinearLayout.LayoutParams(1418, 245));
        this.olpzvbsxeu.setPadding(BDLocation.TypeNetWorkLocation, 118, BDLocation.TypeServerError, 65);
        linearLayout.addView(this.olpzvbsxeu);
        this.olpzvbsxeu.setBackgroundColor(Color.parseColor("#3c5843"));
        Button button3 = new Button(this);
        this.ipzrwupbin = button3;
        button3.setLayoutParams(new LinearLayout.LayoutParams(GattClient.STATE_READ_DEVICE_INFO, 1618));
        this.ipzrwupbin.setPadding(176, 77, BDLocation.TypeNetWorkLocation, 134);
        linearLayout.addView(this.ipzrwupbin);
        this.ipzrwupbin.setBackgroundColor(Color.parseColor("#1f5324"));
        LinearLayout linearLayout5 = new LinearLayout(this);
        this.vxailqosow = linearLayout5;
        linearLayout5.setLayoutParams(new LinearLayout.LayoutParams(1925, 391));
        this.vxailqosow.setPadding(118, 134, 53, 46);
        linearLayout.addView(this.vxailqosow);
        this.vxailqosow.setBackgroundColor(Color.parseColor("#a4097f"));
        GridView gridView2 = new GridView(this);
        this.gpgsttcjsa = gridView2;
        gridView2.setLayoutParams(new LinearLayout.LayoutParams(589, 946));
        this.gpgsttcjsa.setPadding(92, 113, 102, 81);
        linearLayout.addView(this.gpgsttcjsa);
        this.gpgsttcjsa.setBackgroundColor(Color.parseColor("#f92159"));
        SeekBar seekBar3 = new SeekBar(this);
        this.atacdevnqr = seekBar3;
        seekBar3.setLayoutParams(new LinearLayout.LayoutParams(530, 1411));
        this.atacdevnqr.setPadding(125, 186, 89, 154);
        linearLayout.addView(this.atacdevnqr);
        this.atacdevnqr.setBackgroundColor(Color.parseColor("#d69d39"));
        DatePicker datePicker3 = new DatePicker(this);
        this.naeqowbsqu = datePicker3;
        datePicker3.setLayoutParams(new LinearLayout.LayoutParams(546, 293));
        this.naeqowbsqu.setPadding(85, 74, 70, 68);
        linearLayout.addView(this.naeqowbsqu);
        this.naeqowbsqu.setBackgroundColor(Color.parseColor("#01759b"));
        ImageView imageView2 = new ImageView(this);
        this.oiyqxqzafd = imageView2;
        imageView2.setLayoutParams(new LinearLayout.LayoutParams(1649, 992));
        this.oiyqxqzafd.setPadding(145, BDLocation.TypeServerError, 21, 29);
        linearLayout.addView(this.oiyqxqzafd);
        this.oiyqxqzafd.setBackgroundColor(Color.parseColor("#ba0944"));
        GridView gridView3 = new GridView(this);
        this.ftwqcnxkoz = gridView3;
        gridView3.setLayoutParams(new LinearLayout.LayoutParams(976, 1062));
        this.ftwqcnxkoz.setPadding(31, 26, 156, 98);
        linearLayout.addView(this.ftwqcnxkoz);
        this.ftwqcnxkoz.setBackgroundColor(Color.parseColor("#a61e37"));
        SeekBar seekBar4 = new SeekBar(this);
        this.kjkktzyctu = seekBar4;
        seekBar4.setLayoutParams(new LinearLayout.LayoutParams(643, 1328));
        this.kjkktzyctu.setPadding(198, 37, 77, 86);
        linearLayout.addView(this.kjkktzyctu);
        this.kjkktzyctu.setBackgroundColor(Color.parseColor("#ce49ce"));
        TimePicker timePicker4 = new TimePicker(this);
        this.snikrozgdi = timePicker4;
        timePicker4.setLayoutParams(new LinearLayout.LayoutParams(1299, 1325));
        this.snikrozgdi.setPadding(136, 182, 197, 40);
        linearLayout.addView(this.snikrozgdi);
        this.snikrozgdi.setBackgroundColor(Color.parseColor("#3c6469"));
        ViewFlipper viewFlipper3 = new ViewFlipper(this);
        this.pjnphpfmkz = viewFlipper3;
        viewFlipper3.setLayoutParams(new LinearLayout.LayoutParams(123, 1214));
        this.pjnphpfmkz.setPadding(4, 155, 159, 137);
        linearLayout.addView(this.pjnphpfmkz);
        this.pjnphpfmkz.setBackgroundColor(Color.parseColor("#1a65a9"));
        TimePicker timePicker5 = new TimePicker(this);
        this.kddfmzxmmi = timePicker5;
        timePicker5.setLayoutParams(new LinearLayout.LayoutParams(230, 1097));
        this.kddfmzxmmi.setPadding(55, 178, BDLocation.TypeCoarseLocation, 46);
        linearLayout.addView(this.kddfmzxmmi);
        this.kddfmzxmmi.setBackgroundColor(Color.parseColor("#db7c97"));
        Switch r25 = new Switch(this);
        this.eijzljrvzj = r25;
        r25.setLayoutParams(new LinearLayout.LayoutParams(846, 1377));
        this.eijzljrvzj.setPadding(2, 76, 156, 88);
        linearLayout.addView(this.eijzljrvzj);
        this.eijzljrvzj.setBackgroundColor(Color.parseColor("#8fcdee"));
        ImageView imageView3 = new ImageView(this);
        this.mojpeodrfp = imageView3;
        imageView3.setLayoutParams(new LinearLayout.LayoutParams(1000, 134));
        this.mojpeodrfp.setPadding(30, 31, WebSocketProtocol.PAYLOAD_SHORT, 22);
        linearLayout.addView(this.mojpeodrfp);
        this.mojpeodrfp.setBackgroundColor(Color.parseColor("#42856c"));
        DatePicker datePicker4 = new DatePicker(this);
        this.cqvfkyoltz = datePicker4;
        datePicker4.setLayoutParams(new LinearLayout.LayoutParams(1459, 678));
        this.cqvfkyoltz.setPadding(163, 183, 38, 124);
        linearLayout.addView(this.cqvfkyoltz);
        this.cqvfkyoltz.setBackgroundColor(Color.parseColor("#313342"));
        TimePicker timePicker6 = new TimePicker(this);
        this.uywsepgzbi = timePicker6;
        timePicker6.setLayoutParams(new LinearLayout.LayoutParams(1449, 1591));
        this.uywsepgzbi.setPadding(185, 120, 187, 27);
        linearLayout.addView(this.uywsepgzbi);
        this.uywsepgzbi.setBackgroundColor(Color.parseColor("#b63e23"));
        GridView gridView4 = new GridView(this);
        this.zgzeydjzci = gridView4;
        gridView4.setLayoutParams(new LinearLayout.LayoutParams(116, 1176));
        this.zgzeydjzci.setPadding(93, BDLocation.TypeNetWorkLocation, 24, 20);
        linearLayout.addView(this.zgzeydjzci);
        this.zgzeydjzci.setBackgroundColor(Color.parseColor("#c221ee"));
        RatingBar ratingBar2 = new RatingBar(this);
        this.judvlhunwz = ratingBar2;
        ratingBar2.setLayoutParams(new LinearLayout.LayoutParams(1082, 924));
        this.judvlhunwz.setPadding(53, 151, 99, BDLocation.TypeServerDecryptError);
        linearLayout.addView(this.judvlhunwz);
        this.judvlhunwz.setBackgroundColor(Color.parseColor("#99f157"));
        ScrollView scrollView2 = new ScrollView(this);
        this.xqqkiphfaa = scrollView2;
        scrollView2.setLayoutParams(new LinearLayout.LayoutParams(1900, 1178));
        this.xqqkiphfaa.setPadding(142, 36, 170, 3);
        linearLayout.addView(this.xqqkiphfaa);
        this.xqqkiphfaa.setBackgroundColor(Color.parseColor("#feb2dc"));
        ToggleButton toggleButton6 = new ToggleButton(this);
        this.ydedtpwhlz = toggleButton6;
        toggleButton6.setLayoutParams(new LinearLayout.LayoutParams(1425, 492));
        this.ydedtpwhlz.setPadding(129, 11, 63, 122);
        linearLayout.addView(this.ydedtpwhlz);
        this.ydedtpwhlz.setBackgroundColor(Color.parseColor("#ced777"));
        TableLayout tableLayout2 = new TableLayout(this);
        this.ozpamnpnlr = tableLayout2;
        tableLayout2.setLayoutParams(new LinearLayout.LayoutParams(744, 250));
        this.ozpamnpnlr.setPadding(WebSocketProtocol.PAYLOAD_SHORT, 114, 115, 12);
        linearLayout.addView(this.ozpamnpnlr);
        this.ozpamnpnlr.setBackgroundColor(Color.parseColor("#6513de"));
        Spinner spinner3 = new Spinner(this);
        this.sbjyxpthtt = spinner3;
        spinner3.setLayoutParams(new LinearLayout.LayoutParams(755, 1930));
        this.sbjyxpthtt.setPadding(57, 108, 199, 46);
        linearLayout.addView(this.sbjyxpthtt);
        this.sbjyxpthtt.setBackgroundColor(Color.parseColor("#3e25dc"));
        TimePicker timePicker7 = new TimePicker(this);
        this.mlxmmqqtss = timePicker7;
        timePicker7.setLayoutParams(new LinearLayout.LayoutParams(311, 766));
        this.mlxmmqqtss.setPadding(1, 9, 5, 64);
        linearLayout.addView(this.mlxmmqqtss);
        this.mlxmmqqtss.setBackgroundColor(Color.parseColor("#4b3dbe"));
        SeekBar seekBar5 = new SeekBar(this);
        this.kswcejepgs = seekBar5;
        seekBar5.setLayoutParams(new LinearLayout.LayoutParams(264, 882));
        this.kswcejepgs.setPadding(47, 59, 62, 128);
        linearLayout.addView(this.kswcejepgs);
        this.kswcejepgs.setBackgroundColor(Color.parseColor("#89944e"));
        ListView listView2 = new ListView(this);
        this.lwfdwvzkuv = listView2;
        listView2.setLayoutParams(new LinearLayout.LayoutParams(1003, 265));
        this.lwfdwvzkuv.setPadding(186, 95, 141, 133);
        linearLayout.addView(this.lwfdwvzkuv);
        this.lwfdwvzkuv.setBackgroundColor(Color.parseColor("#57294b"));
        ProgressBar progressBar4 = new ProgressBar(this);
        this.qnqfkeeqqk = progressBar4;
        progressBar4.setLayoutParams(new LinearLayout.LayoutParams(587, 812));
        this.qnqfkeeqqk.setPadding(120, 189, 153, 158);
        linearLayout.addView(this.qnqfkeeqqk);
        this.qnqfkeeqqk.setBackgroundColor(Color.parseColor("#3f72d0"));
        ToggleButton toggleButton7 = new ToggleButton(this);
        this.cnzxmmepnu = toggleButton7;
        toggleButton7.setLayoutParams(new LinearLayout.LayoutParams(1414, 822));
        this.cnzxmmepnu.setPadding(113, 21, 97, 143);
        linearLayout.addView(this.cnzxmmepnu);
        this.cnzxmmepnu.setBackgroundColor(Color.parseColor("#ab5855"));
        DatePicker datePicker5 = new DatePicker(this);
        this.ovhtfywnvs = datePicker5;
        datePicker5.setLayoutParams(new LinearLayout.LayoutParams(104, 454));
        this.ovhtfywnvs.setPadding(134, 16, 32, 184);
        linearLayout.addView(this.ovhtfywnvs);
        this.ovhtfywnvs.setBackgroundColor(Color.parseColor("#679043"));
        CheckBox checkBox5 = new CheckBox(this);
        this.mqnnuozdmj = checkBox5;
        checkBox5.setLayoutParams(new LinearLayout.LayoutParams(237, 554));
        this.mqnnuozdmj.setPadding(119, 71, BDLocation.TypeCoarseLocation, 18);
        linearLayout.addView(this.mqnnuozdmj);
        this.mqnnuozdmj.setBackgroundColor(Color.parseColor("#3b781e"));
        RelativeLayout relativeLayout2 = new RelativeLayout(this);
        this.vnogvcnhuo = relativeLayout2;
        relativeLayout2.setLayoutParams(new LinearLayout.LayoutParams(526, 1165));
        this.vnogvcnhuo.setPadding(89, 123, 12, 198);
        linearLayout.addView(this.vnogvcnhuo);
        this.vnogvcnhuo.setBackgroundColor(Color.parseColor("#46979a"));
        DatePicker datePicker6 = new DatePicker(this);
        this.cigxvruepo = datePicker6;
        datePicker6.setLayoutParams(new LinearLayout.LayoutParams(825, 933));
        this.cigxvruepo.setPadding(109, 193, 158, 116);
        linearLayout.addView(this.cigxvruepo);
        this.cigxvruepo.setBackgroundColor(Color.parseColor("#596972"));
        ImageView imageView4 = new ImageView(this);
        this.wxsqktjqgc = imageView4;
        imageView4.setLayoutParams(new LinearLayout.LayoutParams(155, 1955));
        this.wxsqktjqgc.setPadding(93, 40, 192, 125);
        linearLayout.addView(this.wxsqktjqgc);
        this.wxsqktjqgc.setBackgroundColor(Color.parseColor("#0e95a0"));
        TextView textView4 = new TextView(this);
        this.umysrlvgou = textView4;
        textView4.setLayoutParams(new LinearLayout.LayoutParams(418, 1360));
        this.umysrlvgou.setPadding(49, 138, 143, 166);
        linearLayout.addView(this.umysrlvgou);
        this.umysrlvgou.setBackgroundColor(Color.parseColor("#aac50b"));
        ScrollView scrollView3 = new ScrollView(this);
        this.tolxxfwppg = scrollView3;
        scrollView3.setLayoutParams(new LinearLayout.LayoutParams(195, 312));
        this.tolxxfwppg.setPadding(104, 36, 57, 58);
        linearLayout.addView(this.tolxxfwppg);
        this.tolxxfwppg.setBackgroundColor(Color.parseColor("#f1b0e9"));
        LinearLayout linearLayout6 = new LinearLayout(this);
        this.eqyquzwhoy = linearLayout6;
        linearLayout6.setLayoutParams(new LinearLayout.LayoutParams(851, 1278));
        this.eqyquzwhoy.setPadding(114, 99, 184, 50);
        linearLayout.addView(this.eqyquzwhoy);
        this.eqyquzwhoy.setBackgroundColor(Color.parseColor("#59797e"));
        RatingBar ratingBar3 = new RatingBar(this);
        this.ewuqjuyrin = ratingBar3;
        ratingBar3.setLayoutParams(new LinearLayout.LayoutParams(553, 20));
        this.ewuqjuyrin.setPadding(49, 68, 87, 196);
        linearLayout.addView(this.ewuqjuyrin);
        this.ewuqjuyrin.setBackgroundColor(Color.parseColor("#b22c3e"));
        GridView gridView5 = new GridView(this);
        this.bjzvgtdvts = gridView5;
        gridView5.setLayoutParams(new LinearLayout.LayoutParams(1625, 1678));
        this.bjzvgtdvts.setPadding(23, 127, 25, 149);
        linearLayout.addView(this.bjzvgtdvts);
        this.bjzvgtdvts.setBackgroundColor(Color.parseColor("#0fb893"));
        ScrollView scrollView4 = new ScrollView(this);
        this.dcmabkulbz = scrollView4;
        scrollView4.setLayoutParams(new LinearLayout.LayoutParams(629, 346));
        this.dcmabkulbz.setPadding(147, 41, 138, 4);
        linearLayout.addView(this.dcmabkulbz);
        this.dcmabkulbz.setBackgroundColor(Color.parseColor("#50d945"));
        ScrollView scrollView5 = new ScrollView(this);
        this.smgyxfqgbv = scrollView5;
        scrollView5.setLayoutParams(new LinearLayout.LayoutParams(628, 1061));
        this.smgyxfqgbv.setPadding(85, 19, 14, 125);
        linearLayout.addView(this.smgyxfqgbv);
        this.smgyxfqgbv.setBackgroundColor(Color.parseColor("#fba6ea"));
        TableLayout tableLayout3 = new TableLayout(this);
        this.cxfqmahpma = tableLayout3;
        tableLayout3.setLayoutParams(new LinearLayout.LayoutParams(77, 950));
        this.cxfqmahpma.setPadding(8, 83, 182, 151);
        linearLayout.addView(this.cxfqmahpma);
        this.cxfqmahpma.setBackgroundColor(Color.parseColor("#26930f"));
        ToggleButton toggleButton8 = new ToggleButton(this);
        this.ffbulnwrqk = toggleButton8;
        toggleButton8.setLayoutParams(new LinearLayout.LayoutParams(757, 327));
        this.ffbulnwrqk.setPadding(70, 190, 122, 170);
        linearLayout.addView(this.ffbulnwrqk);
        this.ffbulnwrqk.setBackgroundColor(Color.parseColor("#62d769"));
        TimePicker timePicker8 = new TimePicker(this);
        this.yoperxacdu = timePicker8;
        timePicker8.setLayoutParams(new LinearLayout.LayoutParams(1181, 45));
        this.yoperxacdu.setPadding(23, 128, 72, 177);
        linearLayout.addView(this.yoperxacdu);
        this.yoperxacdu.setBackgroundColor(Color.parseColor("#067dec"));
        FrameLayout frameLayout3 = new FrameLayout(this);
        this.ssnxowpjed = frameLayout3;
        frameLayout3.setLayoutParams(new LinearLayout.LayoutParams(336, 622));
        this.ssnxowpjed.setPadding(163, 41, 59, BDLocation.TypeCoarseLocation);
        linearLayout.addView(this.ssnxowpjed);
        this.ssnxowpjed.setBackgroundColor(Color.parseColor("#867ec5"));
        ScrollView scrollView6 = new ScrollView(this);
        this.pfzcpihyaa = scrollView6;
        scrollView6.setLayoutParams(new LinearLayout.LayoutParams(CodeUtils.DEFAULT_REQ_WIDTH, 802));
        this.pfzcpihyaa.setPadding(15, 93, 112, 34);
        linearLayout.addView(this.pfzcpihyaa);
        this.pfzcpihyaa.setBackgroundColor(Color.parseColor("#036450"));
        SeekBar seekBar6 = new SeekBar(this);
        this.sfdalcayeh = seekBar6;
        seekBar6.setLayoutParams(new LinearLayout.LayoutParams(616, 1168));
        this.sfdalcayeh.setPadding(132, 135, 178, 130);
        linearLayout.addView(this.sfdalcayeh);
        this.sfdalcayeh.setBackgroundColor(Color.parseColor("#eea44b"));
        TimePicker timePicker9 = new TimePicker(this);
        this.llavggzfoj = timePicker9;
        timePicker9.setLayoutParams(new LinearLayout.LayoutParams(1076, 526));
        this.llavggzfoj.setPadding(10, 154, 37, 171);
        linearLayout.addView(this.llavggzfoj);
        this.llavggzfoj.setBackgroundColor(Color.parseColor("#ca9544"));
        ToggleButton toggleButton9 = new ToggleButton(this);
        this.smpnyzjgsz = toggleButton9;
        toggleButton9.setLayoutParams(new LinearLayout.LayoutParams(1702, 1820));
        this.smpnyzjgsz.setPadding(131, 84, 64, 199);
        linearLayout.addView(this.smpnyzjgsz);
        this.smpnyzjgsz.setBackgroundColor(Color.parseColor("#308dbc"));
        TextView textView5 = new TextView(this);
        this.fgcmifxpku = textView5;
        textView5.setLayoutParams(new LinearLayout.LayoutParams(698, 294));
        this.fgcmifxpku.setPadding(107, 145, 180, 168);
        linearLayout.addView(this.fgcmifxpku);
        this.fgcmifxpku.setBackgroundColor(Color.parseColor("#d4fad4"));
        CheckBox checkBox6 = new CheckBox(this);
        this.baziiklcmv = checkBox6;
        checkBox6.setLayoutParams(new LinearLayout.LayoutParams(386, 1516));
        this.baziiklcmv.setPadding(5, 48, BDLocation.TypeServerDecryptError, 79);
        linearLayout.addView(this.baziiklcmv);
        this.baziiklcmv.setBackgroundColor(Color.parseColor("#e249cf"));
        ScrollView scrollView7 = new ScrollView(this);
        this.yyupleximr = scrollView7;
        scrollView7.setLayoutParams(new LinearLayout.LayoutParams(357, 1959));
        this.yyupleximr.setPadding(185, 61, 186, 103);
        linearLayout.addView(this.yyupleximr);
        this.yyupleximr.setBackgroundColor(Color.parseColor("#26efe9"));
        RadioButton radioButton5 = new RadioButton(this);
        this.dvmrfducib = radioButton5;
        radioButton5.setLayoutParams(new LinearLayout.LayoutParams(840, 515));
        this.dvmrfducib.setPadding(122, 52, 78, 4);
        linearLayout.addView(this.dvmrfducib);
        this.dvmrfducib.setBackgroundColor(Color.parseColor("#04dee6"));
        ToggleButton toggleButton10 = new ToggleButton(this);
        this.howttndfaw = toggleButton10;
        toggleButton10.setLayoutParams(new LinearLayout.LayoutParams(1511, 523));
        this.howttndfaw.setPadding(131, 142, 158, 198);
        linearLayout.addView(this.howttndfaw);
        this.howttndfaw.setBackgroundColor(Color.parseColor("#028d2a"));
        RatingBar ratingBar4 = new RatingBar(this);
        this.swcuueuiil = ratingBar4;
        ratingBar4.setLayoutParams(new LinearLayout.LayoutParams(709, 734));
        this.swcuueuiil.setPadding(136, 146, 133, 84);
        linearLayout.addView(this.swcuueuiil);
        this.swcuueuiil.setBackgroundColor(Color.parseColor("#0f1143"));
        RadioButton radioButton6 = new RadioButton(this);
        this.aahwnkubro = radioButton6;
        radioButton6.setLayoutParams(new LinearLayout.LayoutParams(1480, 1445));
        this.aahwnkubro.setPadding(50, BDLocation.TypeServerDecryptError, 73, 143);
        linearLayout.addView(this.aahwnkubro);
        this.aahwnkubro.setBackgroundColor(Color.parseColor("#925853"));
        LinearLayout linearLayout7 = new LinearLayout(this);
        this.heeupyxlsf = linearLayout7;
        linearLayout7.setLayoutParams(new LinearLayout.LayoutParams(169, 1429));
        this.heeupyxlsf.setPadding(77, 136, 136, 101);
        linearLayout.addView(this.heeupyxlsf);
        this.heeupyxlsf.setBackgroundColor(Color.parseColor("#150ece"));
        ToggleButton toggleButton11 = new ToggleButton(this);
        this.uvvpnyezcd = toggleButton11;
        toggleButton11.setLayoutParams(new LinearLayout.LayoutParams(287, 911));
        this.uvvpnyezcd.setPadding(107, 195, 158, 46);
        linearLayout.addView(this.uvvpnyezcd);
        this.uvvpnyezcd.setBackgroundColor(Color.parseColor("#93d658"));
        LinearLayout linearLayout8 = new LinearLayout(this);
        this.tuntbsagbz = linearLayout8;
        linearLayout8.setLayoutParams(new LinearLayout.LayoutParams(1379, 1162));
        this.tuntbsagbz.setPadding(171, 20, 172, 198);
        linearLayout.addView(this.tuntbsagbz);
        this.tuntbsagbz.setBackgroundColor(Color.parseColor("#646f17"));
        SeekBar seekBar7 = new SeekBar(this);
        this.ukrzyvvvpl = seekBar7;
        seekBar7.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.CycleType.TYPE_WAVE_PERIOD, 18));
        this.ukrzyvvvpl.setPadding(155, 23, 35, 32);
        linearLayout.addView(this.ukrzyvvvpl);
        this.ukrzyvvvpl.setBackgroundColor(Color.parseColor("#7f51e9"));
        GridView gridView6 = new GridView(this);
        this.teddsmnzag = gridView6;
        gridView6.setLayoutParams(new LinearLayout.LayoutParams(1593, 583));
        this.teddsmnzag.setPadding(185, 47, 46, 67);
        linearLayout.addView(this.teddsmnzag);
        this.teddsmnzag.setBackgroundColor(Color.parseColor("#ed09f2"));
        DatePicker datePicker7 = new DatePicker(this);
        this.fyqbwavpxu = datePicker7;
        datePicker7.setLayoutParams(new LinearLayout.LayoutParams(1084, 1164));
        this.fyqbwavpxu.setPadding(130, 66, 30, 140);
        linearLayout.addView(this.fyqbwavpxu);
        this.fyqbwavpxu.setBackgroundColor(Color.parseColor("#11172a"));
        TimePicker timePicker10 = new TimePicker(this);
        this.ffsdzwtkdz = timePicker10;
        timePicker10.setLayoutParams(new LinearLayout.LayoutParams(1614, 1603));
        this.ffsdzwtkdz.setPadding(81, 61, 152, 56);
        linearLayout.addView(this.ffsdzwtkdz);
        this.ffsdzwtkdz.setBackgroundColor(Color.parseColor("#b18710"));
        CheckBox checkBox7 = new CheckBox(this);
        this.szjkytzcxa = checkBox7;
        checkBox7.setLayoutParams(new LinearLayout.LayoutParams(1516, 714));
        this.szjkytzcxa.setPadding(97, 44, 74, 13);
        linearLayout.addView(this.szjkytzcxa);
        this.szjkytzcxa.setBackgroundColor(Color.parseColor("#3031f6"));
        Button button4 = new Button(this);
        this.anxmsxlppv = button4;
        button4.setLayoutParams(new LinearLayout.LayoutParams(154, 332));
        this.anxmsxlppv.setPadding(5, 74, 83, 36);
        linearLayout.addView(this.anxmsxlppv);
        this.anxmsxlppv.setBackgroundColor(Color.parseColor("#fb0e5a"));
        GridView gridView7 = new GridView(this);
        this.eaddqvaqnb = gridView7;
        gridView7.setLayoutParams(new LinearLayout.LayoutParams(1303, 1679));
        this.eaddqvaqnb.setPadding(140, 8, 72, 52);
        linearLayout.addView(this.eaddqvaqnb);
        this.eaddqvaqnb.setBackgroundColor(Color.parseColor("#6f5cc1"));
        ViewFlipper viewFlipper4 = new ViewFlipper(this);
        this.yoxtypuexv = viewFlipper4;
        viewFlipper4.setLayoutParams(new LinearLayout.LayoutParams(1926, 1357));
        this.yoxtypuexv.setPadding(106, 181, 27, 110);
        linearLayout.addView(this.yoxtypuexv);
        this.yoxtypuexv.setBackgroundColor(Color.parseColor("#6a32ed"));
        ListView listView3 = new ListView(this);
        this.bklbrkqbfd = listView3;
        listView3.setLayoutParams(new LinearLayout.LayoutParams(336, 777));
        this.bklbrkqbfd.setPadding(65, 154, 182, 112);
        linearLayout.addView(this.bklbrkqbfd);
        this.bklbrkqbfd.setBackgroundColor(Color.parseColor("#5c8052"));
        Switch r26 = new Switch(this);
        this.jtkclanqxc = r26;
        r26.setLayoutParams(new LinearLayout.LayoutParams(1197, 1688));
        this.jtkclanqxc.setPadding(14, 55, 14, 81);
        linearLayout.addView(this.jtkclanqxc);
        this.jtkclanqxc.setBackgroundColor(Color.parseColor("#1c23c6"));
        ScrollView scrollView8 = new ScrollView(this);
        this.snwrlgkiba = scrollView8;
        scrollView8.setLayoutParams(new LinearLayout.LayoutParams(458, 369));
        this.snwrlgkiba.setPadding(183, 54, 132, 81);
        linearLayout.addView(this.snwrlgkiba);
        this.snwrlgkiba.setBackgroundColor(Color.parseColor("#4b8e67"));
        TableLayout tableLayout4 = new TableLayout(this);
        this.nnacauelcz = tableLayout4;
        tableLayout4.setLayoutParams(new LinearLayout.LayoutParams(1165, 1179));
        this.nnacauelcz.setPadding(98, 139, 62, 66);
        linearLayout.addView(this.nnacauelcz);
        this.nnacauelcz.setBackgroundColor(Color.parseColor("#d70059"));
        Spinner spinner4 = new Spinner(this);
        this.rhqzznygdz = spinner4;
        spinner4.setLayoutParams(new LinearLayout.LayoutParams(844, 458));
        this.rhqzznygdz.setPadding(8, 118, 171, 191);
        linearLayout.addView(this.rhqzznygdz);
        this.rhqzznygdz.setBackgroundColor(Color.parseColor("#83a654"));
        ImageView imageView5 = new ImageView(this);
        this.lpxyhxscrf = imageView5;
        imageView5.setLayoutParams(new LinearLayout.LayoutParams(1012, 1710));
        this.lpxyhxscrf.setPadding(193, 14, 35, 199);
        linearLayout.addView(this.lpxyhxscrf);
        this.lpxyhxscrf.setBackgroundColor(Color.parseColor("#5b764d"));
        Button button5 = new Button(this);
        this.zwypftkokw = button5;
        button5.setLayoutParams(new LinearLayout.LayoutParams(1390, 1328));
        this.zwypftkokw.setPadding(9, 195, 109, 6);
        linearLayout.addView(this.zwypftkokw);
        this.zwypftkokw.setBackgroundColor(Color.parseColor("#299b40"));
        ImageView imageView6 = new ImageView(this);
        this.igvqfcxvdf = imageView6;
        imageView6.setLayoutParams(new LinearLayout.LayoutParams(1540, 1233));
        this.igvqfcxvdf.setPadding(23, 159, 163, 25);
        linearLayout.addView(this.igvqfcxvdf);
        this.igvqfcxvdf.setBackgroundColor(Color.parseColor("#e61285"));
        GridView gridView8 = new GridView(this);
        this.urybzfooqn = gridView8;
        gridView8.setLayoutParams(new LinearLayout.LayoutParams(1962, 1097));
        this.urybzfooqn.setPadding(54, 137, 177, 92);
        linearLayout.addView(this.urybzfooqn);
        this.urybzfooqn.setBackgroundColor(Color.parseColor("#6820c4"));
        ViewFlipper viewFlipper5 = new ViewFlipper(this);
        this.igyaupwezt = viewFlipper5;
        viewFlipper5.setLayoutParams(new LinearLayout.LayoutParams(1953, 817));
        this.igyaupwezt.setPadding(163, 111, 75, 50);
        linearLayout.addView(this.igyaupwezt);
        this.igyaupwezt.setBackgroundColor(Color.parseColor("#8946a0"));
        SeekBar seekBar8 = new SeekBar(this);
        this.kwkpfmpzla = seekBar8;
        seekBar8.setLayoutParams(new LinearLayout.LayoutParams(1645, 1941));
        this.kwkpfmpzla.setPadding(143, 94, 132, 176);
        linearLayout.addView(this.kwkpfmpzla);
        this.kwkpfmpzla.setBackgroundColor(Color.parseColor("#eda22c"));
        TableLayout tableLayout5 = new TableLayout(this);
        this.yshedsfozw = tableLayout5;
        tableLayout5.setLayoutParams(new LinearLayout.LayoutParams(1039, 114));
        this.yshedsfozw.setPadding(94, 192, 43, 22);
        linearLayout.addView(this.yshedsfozw);
        this.yshedsfozw.setBackgroundColor(Color.parseColor("#dc9467"));
        RadioButton radioButton7 = new RadioButton(this);
        this.mqpmzpukhc = radioButton7;
        radioButton7.setLayoutParams(new LinearLayout.LayoutParams(1124, BDLocation.TypeNetWorkLocation));
        this.mqpmzpukhc.setPadding(14, 43, 121, 123);
        linearLayout.addView(this.mqpmzpukhc);
        this.mqpmzpukhc.setBackgroundColor(Color.parseColor("#ace0aa"));
        TextView textView6 = new TextView(this);
        this.zabzlnejsn = textView6;
        textView6.setLayoutParams(new LinearLayout.LayoutParams(1925, 357));
        this.zabzlnejsn.setPadding(123, 17, 22, 148);
        linearLayout.addView(this.zabzlnejsn);
        this.zabzlnejsn.setBackgroundColor(Color.parseColor("#e088bc"));
        FrameLayout frameLayout4 = new FrameLayout(this);
        this.xxchkobxrw = frameLayout4;
        frameLayout4.setLayoutParams(new LinearLayout.LayoutParams(369, 1598));
        this.xxchkobxrw.setPadding(142, 24, 195, 97);
        linearLayout.addView(this.xxchkobxrw);
        this.xxchkobxrw.setBackgroundColor(Color.parseColor("#83d965"));
        ScrollView scrollView9 = new ScrollView(this);
        this.ruvgtyftul = scrollView9;
        scrollView9.setLayoutParams(new LinearLayout.LayoutParams(1052, 1410));
        this.ruvgtyftul.setPadding(WebSocketProtocol.PAYLOAD_SHORT, 158, 57, 52);
        linearLayout.addView(this.ruvgtyftul);
        this.ruvgtyftul.setBackgroundColor(Color.parseColor("#87e665"));
        TimePicker timePicker11 = new TimePicker(this);
        this.edptrihxtf = timePicker11;
        timePicker11.setLayoutParams(new LinearLayout.LayoutParams(180, 1741));
        this.edptrihxtf.setPadding(118, 74, 22, 79);
        linearLayout.addView(this.edptrihxtf);
        this.edptrihxtf.setBackgroundColor(Color.parseColor("#b20142"));
        RatingBar ratingBar5 = new RatingBar(this);
        this.fylsbrfwso = ratingBar5;
        ratingBar5.setLayoutParams(new LinearLayout.LayoutParams(721, 1790));
        this.fylsbrfwso.setPadding(166, 43, 168, 145);
        linearLayout.addView(this.fylsbrfwso);
        this.fylsbrfwso.setBackgroundColor(Color.parseColor("#2d8a29"));
        ViewFlipper viewFlipper6 = new ViewFlipper(this);
        this.eaxovnwecx = viewFlipper6;
        viewFlipper6.setLayoutParams(new LinearLayout.LayoutParams(594, 1829));
        this.eaxovnwecx.setPadding(173, 103, 178, 181);
        linearLayout.addView(this.eaxovnwecx);
        this.eaxovnwecx.setBackgroundColor(Color.parseColor("#74d618"));
        ImageView imageView7 = new ImageView(this);
        this.sgrknudlxw = imageView7;
        imageView7.setLayoutParams(new LinearLayout.LayoutParams(1023, 1733));
        this.sgrknudlxw.setPadding(131, 89, 12, 23);
        linearLayout.addView(this.sgrknudlxw);
        this.sgrknudlxw.setBackgroundColor(Color.parseColor("#5827d8"));
        RelativeLayout relativeLayout3 = new RelativeLayout(this);
        this.qcwqcqeqqw = relativeLayout3;
        relativeLayout3.setLayoutParams(new LinearLayout.LayoutParams(1601, 858));
        this.qcwqcqeqqw.setPadding(173, 110, 16, 83);
        linearLayout.addView(this.qcwqcqeqqw);
        this.qcwqcqeqqw.setBackgroundColor(Color.parseColor("#d078be"));
        ViewFlipper viewFlipper7 = new ViewFlipper(this);
        this.dldyvkovtq = viewFlipper7;
        viewFlipper7.setLayoutParams(new LinearLayout.LayoutParams(1399, 239));
        this.dldyvkovtq.setPadding(185, WebSocketProtocol.PAYLOAD_SHORT, 112, 92);
        linearLayout.addView(this.dldyvkovtq);
        this.dldyvkovtq.setBackgroundColor(Color.parseColor("#e9b8bb"));
        EditText editText4 = new EditText(this);
        this.siqoevpvez = editText4;
        editText4.setLayoutParams(new LinearLayout.LayoutParams(1162, 375));
        this.siqoevpvez.setPadding(0, 82, PictureConfig.CHOOSE_REQUEST, 103);
        linearLayout.addView(this.siqoevpvez);
        this.siqoevpvez.setBackgroundColor(Color.parseColor("#858124"));
        TextView textView7 = new TextView(this);
        this.xzhvkyklln = textView7;
        textView7.setLayoutParams(new LinearLayout.LayoutParams(1769, 237));
        this.xzhvkyklln.setPadding(83, 56, 95, 74);
        linearLayout.addView(this.xzhvkyklln);
        this.xzhvkyklln.setBackgroundColor(Color.parseColor("#0ecdf7"));
        RelativeLayout relativeLayout4 = new RelativeLayout(this);
        this.ztvyoqoroj = relativeLayout4;
        relativeLayout4.setLayoutParams(new LinearLayout.LayoutParams(663, 578));
        this.ztvyoqoroj.setPadding(30, 127, 82, 93);
        linearLayout.addView(this.ztvyoqoroj);
        this.ztvyoqoroj.setBackgroundColor(Color.parseColor("#949541"));
        TextView textView8 = new TextView(this);
        this.vymxavypzu = textView8;
        textView8.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.PositionType.TYPE_PERCENT_HEIGHT, 1371));
        this.vymxavypzu.setPadding(65, 128, 81, 186);
        linearLayout.addView(this.vymxavypzu);
        this.vymxavypzu.setBackgroundColor(Color.parseColor("#d44de3"));
        LinearLayout linearLayout9 = new LinearLayout(this);
        this.igahjrtxep = linearLayout9;
        linearLayout9.setLayoutParams(new LinearLayout.LayoutParams(340, 493));
        this.igahjrtxep.setPadding(198, 179, BDLocation.TypeNetWorkLocation, 28);
        linearLayout.addView(this.igahjrtxep);
        this.igahjrtxep.setBackgroundColor(Color.parseColor("#6c7702"));
        Switch r27 = new Switch(this);
        this.sdqzthdmhl = r27;
        r27.setLayoutParams(new LinearLayout.LayoutParams(619, 1054));
        this.sdqzthdmhl.setPadding(132, 25, 4, 66);
        linearLayout.addView(this.sdqzthdmhl);
        this.sdqzthdmhl.setBackgroundColor(Color.parseColor("#7736db"));
        ImageView imageView8 = new ImageView(this);
        this.pfsugjahel = imageView8;
        imageView8.setLayoutParams(new LinearLayout.LayoutParams(894, 130));
        this.pfsugjahel.setPadding(25, 44, 84, 37);
        linearLayout.addView(this.pfsugjahel);
        this.pfsugjahel.setBackgroundColor(Color.parseColor("#f365d8"));
        ProgressBar progressBar5 = new ProgressBar(this);
        this.uurtoqijyh = progressBar5;
        progressBar5.setLayoutParams(new LinearLayout.LayoutParams(1655, 166));
        this.uurtoqijyh.setPadding(13, 81, 67, 134);
        linearLayout.addView(this.uurtoqijyh);
        this.uurtoqijyh.setBackgroundColor(Color.parseColor("#e7812a"));
        DatePicker datePicker8 = new DatePicker(this);
        this.pkomkduvef = datePicker8;
        datePicker8.setLayoutParams(new LinearLayout.LayoutParams(711, 293));
        this.pkomkduvef.setPadding(115, 95, 116, 190);
        linearLayout.addView(this.pkomkduvef);
        this.pkomkduvef.setBackgroundColor(Color.parseColor("#26e424"));
        FrameLayout frameLayout5 = new FrameLayout(this);
        this.ptddlmxcqn = frameLayout5;
        frameLayout5.setLayoutParams(new LinearLayout.LayoutParams(582, 13));
        this.ptddlmxcqn.setPadding(147, 30, 19, 72);
        linearLayout.addView(this.ptddlmxcqn);
        this.ptddlmxcqn.setBackgroundColor(Color.parseColor("#6d9c16"));
        Button button6 = new Button(this);
        this.cirauyaxqr = button6;
        button6.setLayoutParams(new LinearLayout.LayoutParams(1585, 1908));
        this.cirauyaxqr.setPadding(2, 61, 192, 90);
        linearLayout.addView(this.cirauyaxqr);
        this.cirauyaxqr.setBackgroundColor(Color.parseColor("#bcba7b"));
        ImageView imageView9 = new ImageView(this);
        this.vxluhhjgai = imageView9;
        imageView9.setLayoutParams(new LinearLayout.LayoutParams(580, 1892));
        this.vxluhhjgai.setPadding(130, 129, 130, 91);
        linearLayout.addView(this.vxluhhjgai);
        this.vxluhhjgai.setBackgroundColor(Color.parseColor("#7ecb4f"));
        FrameLayout frameLayout6 = new FrameLayout(this);
        this.iuujmxpsqc = frameLayout6;
        frameLayout6.setLayoutParams(new LinearLayout.LayoutParams(767, 648));
        this.iuujmxpsqc.setPadding(45, 94, 110, 185);
        linearLayout.addView(this.iuujmxpsqc);
        this.iuujmxpsqc.setBackgroundColor(Color.parseColor("#af3e66"));
        TimePicker timePicker12 = new TimePicker(this);
        this.amfaelosqa = timePicker12;
        timePicker12.setLayoutParams(new LinearLayout.LayoutParams(253, 1931));
        this.amfaelosqa.setPadding(5, 85, 95, 138);
        linearLayout.addView(this.amfaelosqa);
        this.amfaelosqa.setBackgroundColor(Color.parseColor("#839010"));
        ToggleButton toggleButton12 = new ToggleButton(this);
        this.gunesvntbh = toggleButton12;
        toggleButton12.setLayoutParams(new LinearLayout.LayoutParams(136, 1364));
        this.gunesvntbh.setPadding(7, 114, 8, 20);
        linearLayout.addView(this.gunesvntbh);
        this.gunesvntbh.setBackgroundColor(Color.parseColor("#95531c"));
        FrameLayout frameLayout7 = new FrameLayout(this);
        this.wtscenxuxj = frameLayout7;
        frameLayout7.setLayoutParams(new LinearLayout.LayoutParams(1696, 1912));
        this.wtscenxuxj.setPadding(61, 31, 189, 44);
        linearLayout.addView(this.wtscenxuxj);
        this.wtscenxuxj.setBackgroundColor(Color.parseColor("#7252e0"));
        DatePicker datePicker9 = new DatePicker(this);
        this.ieypjcaoxn = datePicker9;
        datePicker9.setLayoutParams(new LinearLayout.LayoutParams(244, 756));
        this.ieypjcaoxn.setPadding(34, 129, 113, 152);
        linearLayout.addView(this.ieypjcaoxn);
        this.ieypjcaoxn.setBackgroundColor(Color.parseColor("#0fc35d"));
        DatePicker datePicker10 = new DatePicker(this);
        this.zhskatgcvl = datePicker10;
        datePicker10.setLayoutParams(new LinearLayout.LayoutParams(1312, 1709));
        this.zhskatgcvl.setPadding(176, 134, 33, 34);
        linearLayout.addView(this.zhskatgcvl);
        this.zhskatgcvl.setBackgroundColor(Color.parseColor("#6738b7"));
        SeekBar seekBar9 = new SeekBar(this);
        this.fdvpevnjzh = seekBar9;
        seekBar9.setLayoutParams(new LinearLayout.LayoutParams(77, 1742));
        this.fdvpevnjzh.setPadding(45, 33, 125, 26);
        linearLayout.addView(this.fdvpevnjzh);
        this.fdvpevnjzh.setBackgroundColor(Color.parseColor("#691963"));
        ScrollView scrollView10 = new ScrollView(this);
        this.bbfcpoycaq = scrollView10;
        scrollView10.setLayoutParams(new LinearLayout.LayoutParams(175, 1750));
        this.bbfcpoycaq.setPadding(148, 51, 15, 110);
        linearLayout.addView(this.bbfcpoycaq);
        this.bbfcpoycaq.setBackgroundColor(Color.parseColor("#4b9bf2"));
        EditText editText5 = new EditText(this);
        this.veodjmbkrm = editText5;
        editText5.setLayoutParams(new LinearLayout.LayoutParams(335, 1507));
        this.veodjmbkrm.setPadding(71, 134, 173, 24);
        linearLayout.addView(this.veodjmbkrm);
        this.veodjmbkrm.setBackgroundColor(Color.parseColor("#a11442"));
        RelativeLayout relativeLayout5 = new RelativeLayout(this);
        this.uqniedbkaj = relativeLayout5;
        relativeLayout5.setLayoutParams(new LinearLayout.LayoutParams(178, 1543));
        this.uqniedbkaj.setPadding(42, 136, 154, 12);
        linearLayout.addView(this.uqniedbkaj);
        this.uqniedbkaj.setBackgroundColor(Color.parseColor("#64d3e6"));
        ViewFlipper viewFlipper8 = new ViewFlipper(this);
        this.miqowfuoxl = viewFlipper8;
        viewFlipper8.setLayoutParams(new LinearLayout.LayoutParams(1721, 654));
        this.miqowfuoxl.setPadding(42, 106, 193, 173);
        linearLayout.addView(this.miqowfuoxl);
        this.miqowfuoxl.setBackgroundColor(Color.parseColor("#1a4c40"));
        GridView gridView9 = new GridView(this);
        this.arpkbumegn = gridView9;
        gridView9.setLayoutParams(new LinearLayout.LayoutParams(192, 224));
        this.arpkbumegn.setPadding(108, 19, 146, 179);
        linearLayout.addView(this.arpkbumegn);
        this.arpkbumegn.setBackgroundColor(Color.parseColor("#b521ef"));
        ScrollView scrollView11 = new ScrollView(this);
        this.sstswxdlnh = scrollView11;
        scrollView11.setLayoutParams(new LinearLayout.LayoutParams(123, 1297));
        this.sstswxdlnh.setPadding(106, 125, 61, 139);
        linearLayout.addView(this.sstswxdlnh);
        this.sstswxdlnh.setBackgroundColor(Color.parseColor("#167805"));
        ScrollView scrollView12 = new ScrollView(this);
        this.muhjjomcly = scrollView12;
        scrollView12.setLayoutParams(new LinearLayout.LayoutParams(227, 843));
        this.muhjjomcly.setPadding(87, 91, 115, 195);
        linearLayout.addView(this.muhjjomcly);
        this.muhjjomcly.setBackgroundColor(Color.parseColor("#6a31b3"));
        RatingBar ratingBar6 = new RatingBar(this);
        this.rorovcndtm = ratingBar6;
        ratingBar6.setLayoutParams(new LinearLayout.LayoutParams(1879, 1213));
        this.rorovcndtm.setPadding(116, 45, 118, 193);
        linearLayout.addView(this.rorovcndtm);
        this.rorovcndtm.setBackgroundColor(Color.parseColor("#2270ca"));
        Spinner spinner5 = new Spinner(this);
        this.jodsevynso = spinner5;
        spinner5.setLayoutParams(new LinearLayout.LayoutParams(102, GattClient.STATE_READ_DEVICE_INFO));
        this.jodsevynso.setPadding(131, 128, 21, 183);
        linearLayout.addView(this.jodsevynso);
        this.jodsevynso.setBackgroundColor(Color.parseColor("#c50ba2"));
        Button button7 = new Button(this);
        this.yslkqxaxwh = button7;
        button7.setLayoutParams(new LinearLayout.LayoutParams(417, 282));
        this.yslkqxaxwh.setPadding(168, 30, 58, 38);
        linearLayout.addView(this.yslkqxaxwh);
        this.yslkqxaxwh.setBackgroundColor(Color.parseColor("#ae29d5"));
        SeekBar seekBar10 = new SeekBar(this);
        this.updgeeweel = seekBar10;
        seekBar10.setLayoutParams(new LinearLayout.LayoutParams(629, 1134));
        this.updgeeweel.setPadding(6, 30, 159, 36);
        linearLayout.addView(this.updgeeweel);
        this.updgeeweel.setBackgroundColor(Color.parseColor("#ca75ab"));
        RelativeLayout relativeLayout6 = new RelativeLayout(this);
        this.zakuuiurgj = relativeLayout6;
        relativeLayout6.setLayoutParams(new LinearLayout.LayoutParams(1871, 1497));
        this.zakuuiurgj.setPadding(31, 193, 115, 26);
        linearLayout.addView(this.zakuuiurgj);
        this.zakuuiurgj.setBackgroundColor(Color.parseColor("#9da14d"));
        Switch r28 = new Switch(this);
        this.adjzmbuxyg = r28;
        r28.setLayoutParams(new LinearLayout.LayoutParams(1521, 90));
        this.adjzmbuxyg.setPadding(62, 122, 148, 135);
        linearLayout.addView(this.adjzmbuxyg);
        this.adjzmbuxyg.setBackgroundColor(Color.parseColor("#d4b4d7"));
        ViewFlipper viewFlipper9 = new ViewFlipper(this);
        this.sfcuhzlayo = viewFlipper9;
        viewFlipper9.setLayoutParams(new LinearLayout.LayoutParams(42, 232));
        this.sfcuhzlayo.setPadding(166, 168, 189, 58);
        linearLayout.addView(this.sfcuhzlayo);
        this.sfcuhzlayo.setBackgroundColor(Color.parseColor("#d1b944"));
        ProgressBar progressBar6 = new ProgressBar(this);
        this.fnfemoyfzj = progressBar6;
        progressBar6.setLayoutParams(new LinearLayout.LayoutParams(1563, 674));
        this.fnfemoyfzj.setPadding(173, 66, 151, 0);
        linearLayout.addView(this.fnfemoyfzj);
        this.fnfemoyfzj.setBackgroundColor(Color.parseColor("#2127b3"));
        RadioButton radioButton8 = new RadioButton(this);
        this.otihpouqot = radioButton8;
        radioButton8.setLayoutParams(new LinearLayout.LayoutParams(1884, 1933));
        this.otihpouqot.setPadding(90, 150, 149, 44);
        linearLayout.addView(this.otihpouqot);
        this.otihpouqot.setBackgroundColor(Color.parseColor("#8de54d"));
        Button button8 = new Button(this);
        this.ebljnhtnnr = button8;
        button8.setLayoutParams(new LinearLayout.LayoutParams(404, 289));
        this.ebljnhtnnr.setPadding(154, 39, 127, 132);
        linearLayout.addView(this.ebljnhtnnr);
        this.ebljnhtnnr.setBackgroundColor(Color.parseColor("#e35a6a"));
        ListView listView4 = new ListView(this);
        this.zpbwgnvmfm = listView4;
        listView4.setLayoutParams(new LinearLayout.LayoutParams(1952, 1704));
        this.zpbwgnvmfm.setPadding(99, 146, 88, 101);
        linearLayout.addView(this.zpbwgnvmfm);
        this.zpbwgnvmfm.setBackgroundColor(Color.parseColor("#fd3705"));
        ProgressBar progressBar7 = new ProgressBar(this);
        this.jtuuzzdtmk = progressBar7;
        progressBar7.setLayoutParams(new LinearLayout.LayoutParams(1668, 1628));
        this.jtuuzzdtmk.setPadding(87, 52, 140, 21);
        linearLayout.addView(this.jtuuzzdtmk);
        this.jtuuzzdtmk.setBackgroundColor(Color.parseColor("#381fbc"));
        RatingBar ratingBar7 = new RatingBar(this);
        this.raqmbcaieg = ratingBar7;
        ratingBar7.setLayoutParams(new LinearLayout.LayoutParams(581, 1012));
        this.raqmbcaieg.setPadding(130, 27, 106, 9);
        linearLayout.addView(this.raqmbcaieg);
        this.raqmbcaieg.setBackgroundColor(Color.parseColor("#3cbbd6"));
        TableLayout tableLayout6 = new TableLayout(this);
        this.eeijxykskg = tableLayout6;
        tableLayout6.setLayoutParams(new LinearLayout.LayoutParams(1632, 1203));
        this.eeijxykskg.setPadding(30, 71, 137, 155);
        linearLayout.addView(this.eeijxykskg);
        this.eeijxykskg.setBackgroundColor(Color.parseColor("#af4afc"));
        ViewFlipper viewFlipper10 = new ViewFlipper(this);
        this.hykrkxyndu = viewFlipper10;
        viewFlipper10.setLayoutParams(new LinearLayout.LayoutParams(620, 309));
        this.hykrkxyndu.setPadding(155, 92, 69, 34);
        linearLayout.addView(this.hykrkxyndu);
        this.hykrkxyndu.setBackgroundColor(Color.parseColor("#6388e5"));
        ScrollView scrollView13 = new ScrollView(this);
        this.xsbygnobbo = scrollView13;
        scrollView13.setLayoutParams(new LinearLayout.LayoutParams(1699, 1263));
        this.xsbygnobbo.setPadding(164, 190, 176, 173);
        linearLayout.addView(this.xsbygnobbo);
        this.xsbygnobbo.setBackgroundColor(Color.parseColor("#c91501"));
        ListView listView5 = new ListView(this);
        this.cjzgeymvez = listView5;
        listView5.setLayoutParams(new LinearLayout.LayoutParams(566, 778));
        this.cjzgeymvez.setPadding(148, BDLocation.TypeCoarseLocation, 110, 37);
        linearLayout.addView(this.cjzgeymvez);
        this.cjzgeymvez.setBackgroundColor(Color.parseColor("#e188fd"));
        RadioButton radioButton9 = new RadioButton(this);
        this.ikavqlgaea = radioButton9;
        radioButton9.setLayoutParams(new LinearLayout.LayoutParams(1495, 1811));
        this.ikavqlgaea.setPadding(71, 186, 122, 111);
        linearLayout.addView(this.ikavqlgaea);
        this.ikavqlgaea.setBackgroundColor(Color.parseColor("#af5c3e"));
        TextView textView9 = new TextView(this);
        this.kyrhjwxvhx = textView9;
        textView9.setLayoutParams(new LinearLayout.LayoutParams(952, 1642));
        this.kyrhjwxvhx.setPadding(124, 117, 181, 187);
        linearLayout.addView(this.kyrhjwxvhx);
        this.kyrhjwxvhx.setBackgroundColor(Color.parseColor("#bf5648"));
        RatingBar ratingBar8 = new RatingBar(this);
        this.ejqutqbakw = ratingBar8;
        ratingBar8.setLayoutParams(new LinearLayout.LayoutParams(1929, TypedValues.AttributesType.TYPE_PIVOT_TARGET));
        this.ejqutqbakw.setPadding(112, 198, 5, 172);
        linearLayout.addView(this.ejqutqbakw);
        this.ejqutqbakw.setBackgroundColor(Color.parseColor("#c3439c"));
        TableLayout tableLayout7 = new TableLayout(this);
        this.qcsynwqaea = tableLayout7;
        tableLayout7.setLayoutParams(new LinearLayout.LayoutParams(312, 649));
        this.qcsynwqaea.setPadding(94, 44, 58, 76);
        linearLayout.addView(this.qcsynwqaea);
        this.qcsynwqaea.setBackgroundColor(Color.parseColor("#ce211d"));
        CheckBox checkBox8 = new CheckBox(this);
        this.nnjzbquktv = checkBox8;
        checkBox8.setLayoutParams(new LinearLayout.LayoutParams(1881, 1077));
        this.nnjzbquktv.setPadding(154, 110, PictureConfig.CHOOSE_REQUEST, 52);
        linearLayout.addView(this.nnjzbquktv);
        this.nnjzbquktv.setBackgroundColor(Color.parseColor("#069176"));
        DatePicker datePicker11 = new DatePicker(this);
        this.yoepwgwnkb = datePicker11;
        datePicker11.setLayoutParams(new LinearLayout.LayoutParams(1774, 1411));
        this.yoepwgwnkb.setPadding(156, WebSocketProtocol.PAYLOAD_SHORT, 177, 93);
        linearLayout.addView(this.yoepwgwnkb);
        this.yoepwgwnkb.setBackgroundColor(Color.parseColor("#a76f40"));
        ProgressBar progressBar8 = new ProgressBar(this);
        this.zyjbmbvsxu = progressBar8;
        progressBar8.setLayoutParams(new LinearLayout.LayoutParams(1208, 1964));
        this.zyjbmbvsxu.setPadding(9, 43, 83, 198);
        linearLayout.addView(this.zyjbmbvsxu);
        this.zyjbmbvsxu.setBackgroundColor(Color.parseColor("#32da61"));
        FrameLayout frameLayout8 = new FrameLayout(this);
        this.kbbqkqluen = frameLayout8;
        frameLayout8.setLayoutParams(new LinearLayout.LayoutParams(1780, 735));
        this.kbbqkqluen.setPadding(125, 151, 23, 178);
        linearLayout.addView(this.kbbqkqluen);
        this.kbbqkqluen.setBackgroundColor(Color.parseColor("#6eea02"));
        Spinner spinner6 = new Spinner(this);
        this.swaqgqhato = spinner6;
        spinner6.setLayoutParams(new LinearLayout.LayoutParams(1897, 1501));
        this.swaqgqhato.setPadding(37, 117, 184, 116);
        linearLayout.addView(this.swaqgqhato);
        this.swaqgqhato.setBackgroundColor(Color.parseColor("#14446f"));
        LinearLayout linearLayout10 = new LinearLayout(this);
        this.qrfkekyuhx = linearLayout10;
        linearLayout10.setLayoutParams(new LinearLayout.LayoutParams(790, 732));
        this.qrfkekyuhx.setPadding(56, 77, 75, 35);
        linearLayout.addView(this.qrfkekyuhx);
        this.qrfkekyuhx.setBackgroundColor(Color.parseColor("#e2e70c"));
        ImageView imageView10 = new ImageView(this);
        this.gaqwpcqnxm = imageView10;
        imageView10.setLayoutParams(new LinearLayout.LayoutParams(1761, 894));
        this.gaqwpcqnxm.setPadding(181, 110, 132, 21);
        linearLayout.addView(this.gaqwpcqnxm);
        this.gaqwpcqnxm.setBackgroundColor(Color.parseColor("#ae880d"));
        ViewFlipper viewFlipper11 = new ViewFlipper(this);
        this.avjptovvmk = viewFlipper11;
        viewFlipper11.setLayoutParams(new LinearLayout.LayoutParams(1139, 197));
        this.avjptovvmk.setPadding(23, 136, 94, 1);
        linearLayout.addView(this.avjptovvmk);
        this.avjptovvmk.setBackgroundColor(Color.parseColor("#e4565b"));
        ScrollView scrollView14 = new ScrollView(this);
        this.mwbmwwedgt = scrollView14;
        scrollView14.setLayoutParams(new LinearLayout.LayoutParams(1512, 1262));
        this.mwbmwwedgt.setPadding(93, 196, 25, 101);
        linearLayout.addView(this.mwbmwwedgt);
        this.mwbmwwedgt.setBackgroundColor(Color.parseColor("#4fed08"));
        FrameLayout frameLayout9 = new FrameLayout(this);
        this.pgzoimvhdn = frameLayout9;
        frameLayout9.setLayoutParams(new LinearLayout.LayoutParams(586, 1199));
        this.pgzoimvhdn.setPadding(54, 170, 180, 176);
        linearLayout.addView(this.pgzoimvhdn);
        this.pgzoimvhdn.setBackgroundColor(Color.parseColor("#e33a5c"));
        ScrollView scrollView15 = new ScrollView(this);
        this.lrvtotrysc = scrollView15;
        scrollView15.setLayoutParams(new LinearLayout.LayoutParams(1446, 263));
        this.lrvtotrysc.setPadding(145, 38, 35, 94);
        linearLayout.addView(this.lrvtotrysc);
        this.lrvtotrysc.setBackgroundColor(Color.parseColor("#733855"));
        Spinner spinner7 = new Spinner(this);
        this.ysziwygtxj = spinner7;
        spinner7.setLayoutParams(new LinearLayout.LayoutParams(319, 1416));
        this.ysziwygtxj.setPadding(26, 87, 58, 166);
        linearLayout.addView(this.ysziwygtxj);
        this.ysziwygtxj.setBackgroundColor(Color.parseColor("#a2c2fc"));
        ViewFlipper viewFlipper12 = new ViewFlipper(this);
        this.jnpvggpcob = viewFlipper12;
        viewFlipper12.setLayoutParams(new LinearLayout.LayoutParams(1703, 1483));
        this.jnpvggpcob.setPadding(176, 116, 55, 41);
        linearLayout.addView(this.jnpvggpcob);
        this.jnpvggpcob.setBackgroundColor(Color.parseColor("#9b5af4"));
        ToggleButton toggleButton13 = new ToggleButton(this);
        this.zaletsdbgs = toggleButton13;
        toggleButton13.setLayoutParams(new LinearLayout.LayoutParams(1925, 217));
        this.zaletsdbgs.setPadding(147, 28, 199, 105);
        linearLayout.addView(this.zaletsdbgs);
        this.zaletsdbgs.setBackgroundColor(Color.parseColor("#f3b3f9"));
        TableLayout tableLayout8 = new TableLayout(this);
        this.vckzjzcjiz = tableLayout8;
        tableLayout8.setLayoutParams(new LinearLayout.LayoutParams(920, 202));
        this.vckzjzcjiz.setPadding(130, 106, 95, 147);
        linearLayout.addView(this.vckzjzcjiz);
        this.vckzjzcjiz.setBackgroundColor(Color.parseColor("#355d14"));
        ProgressBar progressBar9 = new ProgressBar(this);
        this.xwrzmmwlwm = progressBar9;
        progressBar9.setLayoutParams(new LinearLayout.LayoutParams(1458, 1460));
        this.xwrzmmwlwm.setPadding(50, 42, 131, 35);
        linearLayout.addView(this.xwrzmmwlwm);
        this.xwrzmmwlwm.setBackgroundColor(Color.parseColor("#9f9f8c"));
        RatingBar ratingBar9 = new RatingBar(this);
        this.yyrssxgouy = ratingBar9;
        ratingBar9.setLayoutParams(new LinearLayout.LayoutParams(1880, 1849));
        this.yyrssxgouy.setPadding(35, 141, 29, 195);
        linearLayout.addView(this.yyrssxgouy);
        this.yyrssxgouy.setBackgroundColor(Color.parseColor("#b815c5"));
        CheckBox checkBox9 = new CheckBox(this);
        this.sntgghumrq = checkBox9;
        checkBox9.setLayoutParams(new LinearLayout.LayoutParams(1726, 453));
        this.sntgghumrq.setPadding(100, 44, 27, 16);
        linearLayout.addView(this.sntgghumrq);
        this.sntgghumrq.setBackgroundColor(Color.parseColor("#a28a13"));
        RatingBar ratingBar10 = new RatingBar(this);
        this.kzzodzgteh = ratingBar10;
        ratingBar10.setLayoutParams(new LinearLayout.LayoutParams(73, 154));
        this.kzzodzgteh.setPadding(94, 74, 148, 81);
        linearLayout.addView(this.kzzodzgteh);
        this.kzzodzgteh.setBackgroundColor(Color.parseColor("#e2b90c"));
        RelativeLayout relativeLayout7 = new RelativeLayout(this);
        this.pxghodftek = relativeLayout7;
        relativeLayout7.setLayoutParams(new LinearLayout.LayoutParams(1797, 579));
        this.pxghodftek.setPadding(198, 35, 92, 157);
        linearLayout.addView(this.pxghodftek);
        this.pxghodftek.setBackgroundColor(Color.parseColor("#95ea09"));
        EditText editText6 = new EditText(this);
        this.twdpxufort = editText6;
        editText6.setLayoutParams(new LinearLayout.LayoutParams(1469, 218));
        this.twdpxufort.setPadding(148, 60, 27, 80);
        linearLayout.addView(this.twdpxufort);
        this.twdpxufort.setBackgroundColor(Color.parseColor("#c4aca6"));
        GridView gridView10 = new GridView(this);
        this.lliyzbvcxr = gridView10;
        gridView10.setLayoutParams(new LinearLayout.LayoutParams(417, 46));
        this.lliyzbvcxr.setPadding(56, 135, 84, 97);
        linearLayout.addView(this.lliyzbvcxr);
        this.lliyzbvcxr.setBackgroundColor(Color.parseColor("#1836e3"));
        TableLayout tableLayout9 = new TableLayout(this);
        this.wmmfgxmhri = tableLayout9;
        tableLayout9.setLayoutParams(new LinearLayout.LayoutParams(1002, 1276));
        this.wmmfgxmhri.setPadding(179, 102, 106, 3);
        linearLayout.addView(this.wmmfgxmhri);
        this.wmmfgxmhri.setBackgroundColor(Color.parseColor("#4a523d"));
        Spinner spinner8 = new Spinner(this);
        this.iedilswsuj = spinner8;
        spinner8.setLayoutParams(new LinearLayout.LayoutParams(1505, BDLocation.TypeNetWorkLocation));
        this.iedilswsuj.setPadding(83, 112, 77, 46);
        linearLayout.addView(this.iedilswsuj);
        this.iedilswsuj.setBackgroundColor(Color.parseColor("#091907"));
        ViewFlipper viewFlipper13 = new ViewFlipper(this);
        this.jqapjropxi = viewFlipper13;
        viewFlipper13.setLayoutParams(new LinearLayout.LayoutParams(614, LocalPlaybackConstants.BUFFER_B_CAN_USE_FLAG));
        this.jqapjropxi.setPadding(BDLocation.TypeCoarseLocation, 19, 83, 10);
        linearLayout.addView(this.jqapjropxi);
        this.jqapjropxi.setBackgroundColor(Color.parseColor("#e293e3"));
        DatePicker datePicker12 = new DatePicker(this);
        this.lwbimtawop = datePicker12;
        datePicker12.setLayoutParams(new LinearLayout.LayoutParams(1958, 1056));
        this.lwbimtawop.setPadding(75, 111, 26, 16);
        linearLayout.addView(this.lwbimtawop);
        this.lwbimtawop.setBackgroundColor(Color.parseColor("#b3ab22"));
        GridView gridView11 = new GridView(this);
        this.nufrsczori = gridView11;
        gridView11.setLayoutParams(new LinearLayout.LayoutParams(412, 275));
        this.nufrsczori.setPadding(182, 180, 186, 165);
        linearLayout.addView(this.nufrsczori);
        this.nufrsczori.setBackgroundColor(Color.parseColor("#8e5e72"));
        FrameLayout frameLayout10 = new FrameLayout(this);
        this.zyqfhjgjzl = frameLayout10;
        frameLayout10.setLayoutParams(new LinearLayout.LayoutParams(1105, 122));
        this.zyqfhjgjzl.setPadding(30, 41, 73, 123);
        linearLayout.addView(this.zyqfhjgjzl);
        this.zyqfhjgjzl.setBackgroundColor(Color.parseColor("#e5d64d"));
        LinearLayout linearLayout11 = new LinearLayout(this);
        this.aiqlnwgtkf = linearLayout11;
        linearLayout11.setLayoutParams(new LinearLayout.LayoutParams(119, 1972));
        this.aiqlnwgtkf.setPadding(117, 121, 86, 53);
        linearLayout.addView(this.aiqlnwgtkf);
        this.aiqlnwgtkf.setBackgroundColor(Color.parseColor("#5a9294"));
        CheckBox checkBox10 = new CheckBox(this);
        this.qcxxthciir = checkBox10;
        checkBox10.setLayoutParams(new LinearLayout.LayoutParams(1526, 582));
        this.qcxxthciir.setPadding(164, 35, 48, 64);
        linearLayout.addView(this.qcxxthciir);
        this.qcxxthciir.setBackgroundColor(Color.parseColor("#d0651e"));
        RatingBar ratingBar11 = new RatingBar(this);
        this.kzakyicngb = ratingBar11;
        ratingBar11.setLayoutParams(new LinearLayout.LayoutParams(82, 1810));
        this.kzakyicngb.setPadding(100, 21, 183, 129);
        linearLayout.addView(this.kzakyicngb);
        this.kzakyicngb.setBackgroundColor(Color.parseColor("#76df45"));
        EditText editText7 = new EditText(this);
        this.pqspejgqrt = editText7;
        editText7.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.AttributesType.TYPE_EASING, 1529));
        this.pqspejgqrt.setPadding(53, 157, BDLocation.TypeCoarseLocation, 7);
        linearLayout.addView(this.pqspejgqrt);
        this.pqspejgqrt.setBackgroundColor(Color.parseColor("#7bcd39"));
        RadioButton radioButton10 = new RadioButton(this);
        this.afrdqpdpst = radioButton10;
        radioButton10.setLayoutParams(new LinearLayout.LayoutParams(574, 1413));
        this.afrdqpdpst.setPadding(152, 108, 63, 197);
        linearLayout.addView(this.afrdqpdpst);
        this.afrdqpdpst.setBackgroundColor(Color.parseColor("#f79f04"));
        CheckBox checkBox11 = new CheckBox(this);
        this.ztqfqopxol = checkBox11;
        checkBox11.setLayoutParams(new LinearLayout.LayoutParams(1068, 1981));
        this.ztqfqopxol.setPadding(143, 33, 189, 44);
        linearLayout.addView(this.ztqfqopxol);
        this.ztqfqopxol.setBackgroundColor(Color.parseColor("#b60a92"));
        TimePicker timePicker13 = new TimePicker(this);
        this.gblxkoaxol = timePicker13;
        timePicker13.setLayoutParams(new LinearLayout.LayoutParams(93, 1005));
        this.gblxkoaxol.setPadding(52, 87, 170, 60);
        linearLayout.addView(this.gblxkoaxol);
        this.gblxkoaxol.setBackgroundColor(Color.parseColor("#818ea9"));
        ViewFlipper viewFlipper14 = new ViewFlipper(this);
        this.clhrbnarvx = viewFlipper14;
        viewFlipper14.setLayoutParams(new LinearLayout.LayoutParams(1071, 745));
        this.clhrbnarvx.setPadding(54, 163, 172, 13);
        linearLayout.addView(this.clhrbnarvx);
        this.clhrbnarvx.setBackgroundColor(Color.parseColor("#3b1b5c"));
        ToggleButton toggleButton14 = new ToggleButton(this);
        this.eoqukontaz = toggleButton14;
        toggleButton14.setLayoutParams(new LinearLayout.LayoutParams(864, 407));
        this.eoqukontaz.setPadding(BDLocation.TypeServerError, 22, 166, 102);
        linearLayout.addView(this.eoqukontaz);
        this.eoqukontaz.setBackgroundColor(Color.parseColor("#ca83ea"));
        Switch r29 = new Switch(this);
        this.lvgtnopafu = r29;
        r29.setLayoutParams(new LinearLayout.LayoutParams(561, 223));
        this.lvgtnopafu.setPadding(2, 18, 5, 112);
        linearLayout.addView(this.lvgtnopafu);
        this.lvgtnopafu.setBackgroundColor(Color.parseColor("#9ce187"));
        ProgressBar progressBar10 = new ProgressBar(this);
        this.uclmabmewh = progressBar10;
        progressBar10.setLayoutParams(new LinearLayout.LayoutParams(685, TypedValues.Custom.TYPE_BOOLEAN));
        this.uclmabmewh.setPadding(137, 59, 12, 120);
        linearLayout.addView(this.uclmabmewh);
        this.uclmabmewh.setBackgroundColor(Color.parseColor("#3f57ba"));
        ListView listView6 = new ListView(this);
        this.xgkmewapfh = listView6;
        listView6.setLayoutParams(new LinearLayout.LayoutParams(1617, 1159));
        this.xgkmewapfh.setPadding(69, 124, 136, 168);
        linearLayout.addView(this.xgkmewapfh);
        this.xgkmewapfh.setBackgroundColor(Color.parseColor("#cf131a"));
        ProgressBar progressBar11 = new ProgressBar(this);
        this.vpdgpjrmgt = progressBar11;
        progressBar11.setLayoutParams(new LinearLayout.LayoutParams(1692, 1470));
        this.vpdgpjrmgt.setPadding(111, 20, 37, 122);
        linearLayout.addView(this.vpdgpjrmgt);
        this.vpdgpjrmgt.setBackgroundColor(Color.parseColor("#b15a6b"));
        Button button9 = new Button(this);
        this.fnzaaxpfyj = button9;
        button9.setLayoutParams(new LinearLayout.LayoutParams(1022, 1671));
        this.fnzaaxpfyj.setPadding(2, 60, 80, 152);
        linearLayout.addView(this.fnzaaxpfyj);
        this.fnzaaxpfyj.setBackgroundColor(Color.parseColor("#1c47a5"));
        CheckBox checkBox12 = new CheckBox(this);
        this.zpwsiiymqg = checkBox12;
        checkBox12.setLayoutParams(new LinearLayout.LayoutParams(470, 1301));
        this.zpwsiiymqg.setPadding(139, 136, 87, 106);
        linearLayout.addView(this.zpwsiiymqg);
        this.zpwsiiymqg.setBackgroundColor(Color.parseColor("#34e027"));
        ImageView imageView11 = new ImageView(this);
        this.vxaetzgboc = imageView11;
        imageView11.setLayoutParams(new LinearLayout.LayoutParams(59, 1214));
        this.vxaetzgboc.setPadding(64, 191, 43, 133);
        linearLayout.addView(this.vxaetzgboc);
        this.vxaetzgboc.setBackgroundColor(Color.parseColor("#8af668"));
        FrameLayout frameLayout11 = new FrameLayout(this);
        this.ogbxigkoor = frameLayout11;
        frameLayout11.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.PositionType.TYPE_TRANSITION_EASING, 1374));
        this.ogbxigkoor.setPadding(117, 95, 142, 77);
        linearLayout.addView(this.ogbxigkoor);
        this.ogbxigkoor.setBackgroundColor(Color.parseColor("#1f1c77"));
        FrameLayout frameLayout12 = new FrameLayout(this);
        this.lwnsivazwp = frameLayout12;
        frameLayout12.setLayoutParams(new LinearLayout.LayoutParams(1293, 1811));
        this.lwnsivazwp.setPadding(WebSocketProtocol.PAYLOAD_SHORT, 193, 176, 183);
        linearLayout.addView(this.lwnsivazwp);
        this.lwnsivazwp.setBackgroundColor(Color.parseColor("#5a5445"));
        ViewFlipper viewFlipper15 = new ViewFlipper(this);
        this.jbogmdtpzk = viewFlipper15;
        viewFlipper15.setLayoutParams(new LinearLayout.LayoutParams(1127, HealthyViewModel.Type_Sync_TimeOut));
        this.jbogmdtpzk.setPadding(14, 141, 100, 133);
        linearLayout.addView(this.jbogmdtpzk);
        this.jbogmdtpzk.setBackgroundColor(Color.parseColor("#8b1f25"));
        RadioButton radioButton11 = new RadioButton(this);
        this.jdfxoeuiht = radioButton11;
        radioButton11.setLayoutParams(new LinearLayout.LayoutParams(89, 1448));
        this.jdfxoeuiht.setPadding(54, 18, 152, 95);
        linearLayout.addView(this.jdfxoeuiht);
        this.jdfxoeuiht.setBackgroundColor(Color.parseColor("#d172f5"));
        ProgressBar progressBar12 = new ProgressBar(this);
        this.gyjkhboabo = progressBar12;
        progressBar12.setLayoutParams(new LinearLayout.LayoutParams(1260, 1658));
        this.gyjkhboabo.setPadding(25, 54, 26, 194);
        linearLayout.addView(this.gyjkhboabo);
        this.gyjkhboabo.setBackgroundColor(Color.parseColor("#74ef70"));
        RadioButton radioButton12 = new RadioButton(this);
        this.gqspvkjnkt = radioButton12;
        radioButton12.setLayoutParams(new LinearLayout.LayoutParams(1047, 1612));
        this.gqspvkjnkt.setPadding(131, 166, 6, 128);
        linearLayout.addView(this.gqspvkjnkt);
        this.gqspvkjnkt.setBackgroundColor(Color.parseColor("#d0e575"));
        TextView textView10 = new TextView(this);
        this.hsnjqutukm = textView10;
        textView10.setLayoutParams(new LinearLayout.LayoutParams(740, 1221));
        this.hsnjqutukm.setPadding(1, 2, 181, 108);
        linearLayout.addView(this.hsnjqutukm);
        this.hsnjqutukm.setBackgroundColor(Color.parseColor("#c6481e"));
        CheckBox checkBox13 = new CheckBox(this);
        this.wrlkzowmfo = checkBox13;
        checkBox13.setLayoutParams(new LinearLayout.LayoutParams(226, 147));
        this.wrlkzowmfo.setPadding(163, 47, 112, 121);
        linearLayout.addView(this.wrlkzowmfo);
        this.wrlkzowmfo.setBackgroundColor(Color.parseColor("#5df891"));
        TimePicker timePicker14 = new TimePicker(this);
        this.hjvoemkmrf = timePicker14;
        timePicker14.setLayoutParams(new LinearLayout.LayoutParams(LocalPlaybackConstants.BUFFER_B_CAN_USE_FLAG, 661));
        this.hjvoemkmrf.setPadding(29, 137, 10, 134);
        linearLayout.addView(this.hjvoemkmrf);
        this.hjvoemkmrf.setBackgroundColor(Color.parseColor("#322644"));
        ImageView imageView12 = new ImageView(this);
        this.ixvhwyicqy = imageView12;
        imageView12.setLayoutParams(new LinearLayout.LayoutParams(678, 478));
        this.ixvhwyicqy.setPadding(118, 156, 29, 88);
        linearLayout.addView(this.ixvhwyicqy);
        this.ixvhwyicqy.setBackgroundColor(Color.parseColor("#39a425"));
        RatingBar ratingBar12 = new RatingBar(this);
        this.lizgexzwjc = ratingBar12;
        ratingBar12.setLayoutParams(new LinearLayout.LayoutParams(428, 1439));
        this.lizgexzwjc.setPadding(40, 70, 187, 100);
        linearLayout.addView(this.lizgexzwjc);
        this.lizgexzwjc.setBackgroundColor(Color.parseColor("#6c4efa"));
    }
}
