package com.smartapp.b.qjepjnbvlz;

import android.app.Activity;
import android.graphics.Color;
import android.os.Bundle;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.CheckBox;
import android.widget.DatePicker;
import android.widget.EditText;
import android.widget.FrameLayout;
import android.widget.GridView;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ListView;
import android.widget.ProgressBar;
import android.widget.RadioButton;
import android.widget.RatingBar;
import android.widget.RelativeLayout;
import android.widget.ScrollView;
import android.widget.SeekBar;
import android.widget.Spinner;
import android.widget.Switch;
import android.widget.TableLayout;
import android.widget.TextView;
import android.widget.TimePicker;
import android.widget.ToggleButton;
import android.widget.ViewFlipper;
import androidx.constraintlayout.core.motion.utils.TypedValues;
import androidx.core.view.PointerIconCompat;
import com.baidu.location.BDLocation;
import com.google.zxing.pdf417.PDF417Common;
import com.haibin.calendarview.BuildConfig;
import com.luck.picture.lib.config.PictureConfig;
import com.realsil.sdk.core.bluetooth.connection.le.GattClient;
import com.yalantis.ucrop.view.CropImageView;
import okhttp3.internal.ws.WebSocketProtocol;
import org.java_websocket.WebSocketImpl;

/* loaded from: classes4.dex */
public class KzsxbdkidcyActivity extends Activity {
    TimePicker acgcmctmbo;
    ScrollView acqfvbzqzu;
    RelativeLayout agpxyydmrv;
    TableLayout agwftrwuql;
    RelativeLayout ajxafpgixs;
    CheckBox ammvdrjons;
    FrameLayout aqanvtnxas;
    TableLayout arexcdkvhk;
    GridView asytczufnb;
    RelativeLayout auqwoemrzz;
    Switch bhdonwrmme;
    CheckBox bsheyuqysb;
    ToggleButton cbwkwewgme;
    RelativeLayout ccptgqwtql;
    ListView cdmrtflzim;
    GridView cfqzzumlmc;
    TableLayout cjnjmnglww;
    DatePicker cldzuxghmm;
    TimePicker cotnduldwz;
    SeekBar ctbzlozdqx;
    ScrollView cvistxncol;
    TextView cwmgywpmjx;
    ScrollView dalaatwaxj;
    Spinner ddyntbdxql;
    GridView dmgazxvbim;
    RelativeLayout donvpqviga;
    TableLayout dorrruhhow;
    Switch dtwbbmrqch;
    RatingBar duawvcprmj;
    RadioButton eacvhibtiw;
    Spinner edarezbpic;
    TableLayout eezozkytxr;
    Button efxiqqjvtb;
    ScrollView eihroixcoj;
    Button eitwcozyib;
    ToggleButton ejmsvmexyz;
    ScrollView emhhdrzffn;
    RadioButton emzprhfdpk;
    LinearLayout eotmjazyaq;
    ProgressBar eottvahzvh;
    GridView eveclqqrvk;
    SeekBar ezwnxbyluk;
    TableLayout fayedeozno;
    ProgressBar fcjlozokah;
    TimePicker fermrotpoj;
    CheckBox fgqknevmxe;
    Button fmyzfgjkew;
    Button fojcueynah;
    CheckBox fuirlxtfxr;
    ToggleButton futgwkicaa;
    ListView fwymuxktpn;
    RelativeLayout gdrujzorwv;
    TableLayout gebneckyio;
    ProgressBar geqmuqzhff;
    GridView gmiyfmktsc;
    LinearLayout gqcteetpwe;
    Switch grvsfxvjgy;
    ImageView gtxkcmpjsr;
    RatingBar gugtgxbzds;
    GridView gzowsbvryp;
    CheckBox hakchmqkjy;
    ProgressBar hcjcqkyfmx;
    Switch hddkamivto;
    ProgressBar hhocgkdpbd;
    EditText hioksmlduu;
    GridView hmupsitmhq;
    RelativeLayout hpwmmrzcbs;
    ImageView htdvbchfvu;
    RadioButton htwgkaorxn;
    ImageView ibcqjzflxl;
    RatingBar icmqfigeil;
    ProgressBar idcdyuhbia;
    Spinner ihopvicpkf;
    GridView imvxrwnsli;
    EditText imzebllfeg;
    ViewFlipper irlsguhlkx;
    ListView iroikmwwsx;
    ToggleButton iwqqrnteqn;
    RadioButton jabuyzrqzt;
    ToggleButton jbpklfszhd;
    ImageView jcbeelbzpu;
    EditText jdsylipvtu;
    ToggleButton jgghhwkyee;
    RatingBar jhtsspunzw;
    SeekBar jhtyammyub;
    Spinner jlexfzrusy;
    LinearLayout jmkoioyzyt;
    CheckBox jtcgzvknin;
    RadioButton jteidqhjdp;
    CheckBox jwtktlyvqv;
    TableLayout kfndafvueq;
    Button klpgsowlie;
    CheckBox koewdubmle;
    ScrollView kzsgqvseho;
    LinearLayout labjmfqscl;
    FrameLayout lcjhlfywdm;
    ProgressBar lcwvojopoq;
    ToggleButton lejhdnshyw;
    DatePicker libpvphlpj;
    ImageView ljdfoxzosz;
    TimePicker lmwuxxxqsk;
    RatingBar lzdyzadibe;
    EditText lzjigwhgla;
    RadioButton mfkywpnhht;
    ViewFlipper mjpsloxgha;
    ImageView mncizknwvd;
    TextView mqisstmyhk;
    TextView mrxdqagdpc;
    TextView mtfwtvtkrx;
    ListView mzoquqgyku;
    RadioButton naalpghflr;
    ViewFlipper nccppgrqlm;
    ScrollView ndrdoacoqf;
    Switch neitibpcci;
    ListView noeytxxexe;
    TimePicker noguqmgneo;
    Spinner nqafjcsvdh;
    TableLayout nrtfmbjocr;
    ToggleButton nwdkqbvbab;
    RatingBar nwlyfhijrm;
    FrameLayout ofqavlpsbo;
    TextView ojyivegoqj;
    TextView olbienompi;
    Switch olywneksfm;
    CheckBox oppzfxtkef;
    GridView oriputzmki;
    RatingBar otucbfowcl;
    FrameLayout phhpuworfw;
    TextView pldvykidnr;
    LinearLayout pquzoxeawt;
    ImageView prukczrdfp;
    ToggleButton puelvsulsg;
    RelativeLayout pzotlqicwm;
    GridView qgmftqdxqj;
    DatePicker qifkwrxhmy;
    TimePicker qimrpnlbrj;
    Spinner qlsxijtaly;
    CheckBox qnnelbedxv;
    Switch qoehfcczya;
    ScrollView qpbgetjnnx;
    EditText qqbrskvdqr;
    GridView qwtcgklnjy;
    ImageView raqcwlutrn;
    FrameLayout rdgnnelutb;
    LinearLayout regopruaqh;
    TextView rgnlcuamzj;
    LinearLayout rgzdmnnhyv;
    RadioButton rjcayuswhy;
    ProgressBar rkhjtllpgd;
    RelativeLayout rpqvvmpswq;
    ToggleButton rpwnkcxtfh;
    EditText rqcmrkqjns;
    ProgressBar rsljcqrnuv;
    TimePicker rvbyonceqy;
    CheckBox rymseikhhu;
    ListView sboexxbrxs;
    Button sjiqofoime;
    CheckBox spypaplbww;
    GridView sszclukqdb;
    ListView stxhsbwwqs;
    ViewFlipper svelteevtd;
    EditText sytwylzhgt;
    ProgressBar tbjahfbqwo;
    Button tfynzomxws;
    DatePicker tgqgqjjsdk;
    TimePicker tjcbyyzacd;
    ToggleButton tjtbgzihan;
    ScrollView tlbcdjelpa;
    ToggleButton tnxbsviois;
    LinearLayout tsjccdqwxq;
    ListView tzgwbvgnwo;
    ViewFlipper ueyhmdwqzi;
    Button ugdfoeavsn;
    LinearLayout ukgbxtcxwh;
    GridView uncealdahz;
    ViewFlipper usflwrrsdg;
    Switch uvfbtmmwva;
    RelativeLayout uxpephlvuk;
    RadioButton vhdozdeojg;
    TimePicker vjxvmgalsw;
    ToggleButton vnoiiwrxdz;
    SeekBar vowatujsfs;
    TimePicker vqomtsiuzz;
    TimePicker vrubqzokse;
    FrameLayout vyahxjrqti;
    ToggleButton vykehrkmmn;
    CheckBox vyydwuiomj;
    ProgressBar wfiqqwynrm;
    DatePicker whgauhlona;
    RelativeLayout wjliksamup;
    ProgressBar wnjogerhuk;
    SeekBar wxlmbglieu;
    Spinner xbxnygjdnn;
    Button xddjyvacpg;
    ProgressBar xmcckesmwy;
    ViewFlipper xmwfrwjiqy;
    TableLayout xszcizbkvc;
    GridView xvjnnwlszr;
    TableLayout ydcxwknkcg;
    ImageView yjotuzeyzo;
    Switch ylvwwyqism;
    TextView ynyzqxapys;
    ProgressBar ysvgevpvcq;
    TableLayout ytlwjrsrvi;
    ProgressBar ywofeugqzs;
    LinearLayout yymetmiedl;
    EditText yyvldfdcpe;
    TimePicker zcglkmsvqi;
    EditText zezsdvcktt;
    ListView zhoofmiemo;
    Button ziwggqzhvl;
    RadioButton zjhkczjwgq;
    ProgressBar zkehqzvtng;
    RatingBar zonlqxldwk;
    GridView zpdnlbgocj;
    TimePicker zphcufjtsv;
    RelativeLayout zvtcbipokn;
    DatePicker zxkxjcungv;
    TableLayout zxwhiyikep;

    @Override // android.app.Activity
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        LinearLayout linearLayout = new LinearLayout(this);
        setContentView(linearLayout);
        linearLayout.setLayoutParams(new ViewGroup.LayoutParams(-1, -1));
        linearLayout.setOrientation(1);
        linearLayout.setBackgroundColor(Color.parseColor("#514f72"));
        ImageView imageView = new ImageView(this);
        this.gtxkcmpjsr = imageView;
        imageView.setLayoutParams(new LinearLayout.LayoutParams(1139, 1268));
        this.gtxkcmpjsr.setPadding(179, 37, BDLocation.TypeNetWorkLocation, 128);
        linearLayout.addView(this.gtxkcmpjsr);
        this.gtxkcmpjsr.setBackgroundColor(Color.parseColor("#da0c72"));
        ScrollView scrollView = new ScrollView(this);
        this.kzsgqvseho = scrollView;
        scrollView.setLayoutParams(new LinearLayout.LayoutParams(1529, 405));
        this.kzsgqvseho.setPadding(81, 0, 184, 119);
        linearLayout.addView(this.kzsgqvseho);
        this.kzsgqvseho.setBackgroundColor(Color.parseColor("#6d73af"));
        GridView gridView = new GridView(this);
        this.gzowsbvryp = gridView;
        gridView.setLayoutParams(new LinearLayout.LayoutParams(36, TypedValues.CycleType.TYPE_EASING));
        this.gzowsbvryp.setPadding(BDLocation.TypeServerDecryptError, 171, 97, 20);
        linearLayout.addView(this.gzowsbvryp);
        this.gzowsbvryp.setBackgroundColor(Color.parseColor("#2c4e49"));
        SeekBar seekBar = new SeekBar(this);
        this.wxlmbglieu = seekBar;
        seekBar.setLayoutParams(new LinearLayout.LayoutParams(1426, 1961));
        this.wxlmbglieu.setPadding(58, 187, 191, 90);
        linearLayout.addView(this.wxlmbglieu);
        this.wxlmbglieu.setBackgroundColor(Color.parseColor("#cc04aa"));
        ProgressBar progressBar = new ProgressBar(this);
        this.hcjcqkyfmx = progressBar;
        progressBar.setLayoutParams(new LinearLayout.LayoutParams(774, 1028));
        this.hcjcqkyfmx.setPadding(132, 121, 171, 44);
        linearLayout.addView(this.hcjcqkyfmx);
        this.hcjcqkyfmx.setBackgroundColor(Color.parseColor("#712e23"));
        RadioButton radioButton = new RadioButton(this);
        this.vhdozdeojg = radioButton;
        radioButton.setLayoutParams(new LinearLayout.LayoutParams(791, 1096));
        this.vhdozdeojg.setPadding(123, 26, 7, 131);
        linearLayout.addView(this.vhdozdeojg);
        this.vhdozdeojg.setBackgroundColor(Color.parseColor("#f5a8f2"));
        TableLayout tableLayout = new TableLayout(this);
        this.kfndafvueq = tableLayout;
        tableLayout.setLayoutParams(new LinearLayout.LayoutParams(1885, 1886));
        this.kfndafvueq.setPadding(194, 72, 54, 152);
        linearLayout.addView(this.kfndafvueq);
        this.kfndafvueq.setBackgroundColor(Color.parseColor("#106cbb"));
        Switch r2 = new Switch(this);
        this.olywneksfm = r2;
        r2.setLayoutParams(new LinearLayout.LayoutParams(1074, 1392));
        this.olywneksfm.setPadding(118, 2, 128, 8);
        linearLayout.addView(this.olywneksfm);
        this.olywneksfm.setBackgroundColor(Color.parseColor("#9029df"));
        TableLayout tableLayout2 = new TableLayout(this);
        this.arexcdkvhk = tableLayout2;
        tableLayout2.setLayoutParams(new LinearLayout.LayoutParams(1965, 568));
        this.arexcdkvhk.setPadding(171, 68, 146, 119);
        linearLayout.addView(this.arexcdkvhk);
        this.arexcdkvhk.setBackgroundColor(Color.parseColor("#d9f7b5"));
        FrameLayout frameLayout = new FrameLayout(this);
        this.phhpuworfw = frameLayout;
        frameLayout.setLayoutParams(new LinearLayout.LayoutParams(1138, 1085));
        this.phhpuworfw.setPadding(59, 180, 83, 43);
        linearLayout.addView(this.phhpuworfw);
        this.phhpuworfw.setBackgroundColor(Color.parseColor("#95eb42"));
        SeekBar seekBar2 = new SeekBar(this);
        this.jhtyammyub = seekBar2;
        seekBar2.setLayoutParams(new LinearLayout.LayoutParams(46, 1394));
        this.jhtyammyub.setPadding(58, 185, 177, 86);
        linearLayout.addView(this.jhtyammyub);
        this.jhtyammyub.setBackgroundColor(Color.parseColor("#a14dab"));
        LinearLayout linearLayout2 = new LinearLayout(this);
        this.labjmfqscl = linearLayout2;
        linearLayout2.setLayoutParams(new LinearLayout.LayoutParams(104, CropImageView.DEFAULT_IMAGE_TO_CROP_BOUNDS_ANIM_DURATION));
        this.labjmfqscl.setPadding(70, 65, 50, 39);
        linearLayout.addView(this.labjmfqscl);
        this.labjmfqscl.setBackgroundColor(Color.parseColor("#368f18"));
        LinearLayout linearLayout3 = new LinearLayout(this);
        this.gqcteetpwe = linearLayout3;
        linearLayout3.setLayoutParams(new LinearLayout.LayoutParams(890, 21));
        this.gqcteetpwe.setPadding(51, 102, 192, 142);
        linearLayout.addView(this.gqcteetpwe);
        this.gqcteetpwe.setBackground(new Fajfqpzfcjk());
        ToggleButton toggleButton = new ToggleButton(this);
        this.tnxbsviois = toggleButton;
        toggleButton.setLayoutParams(new LinearLayout.LayoutParams(366, 1353));
        this.tnxbsviois.setPadding(58, 79, 3, 6);
        linearLayout.addView(this.tnxbsviois);
        this.tnxbsviois.setBackgroundColor(Color.parseColor("#ce62e9"));
        GridView gridView2 = new GridView(this);
        this.eveclqqrvk = gridView2;
        gridView2.setLayoutParams(new LinearLayout.LayoutParams(1432, 464));
        this.eveclqqrvk.setPadding(117, 166, 68, 95);
        linearLayout.addView(this.eveclqqrvk);
        this.eveclqqrvk.setBackgroundColor(Color.parseColor("#6c0422"));
        RadioButton radioButton2 = new RadioButton(this);
        this.mfkywpnhht = radioButton2;
        radioButton2.setLayoutParams(new LinearLayout.LayoutParams(234, 1866));
        this.mfkywpnhht.setPadding(153, 106, 61, 54);
        linearLayout.addView(this.mfkywpnhht);
        this.mfkywpnhht.setBackgroundColor(Color.parseColor("#83816f"));
        RadioButton radioButton3 = new RadioButton(this);
        this.jabuyzrqzt = radioButton3;
        radioButton3.setLayoutParams(new LinearLayout.LayoutParams(1958, 639));
        this.jabuyzrqzt.setPadding(155, 58, 45, 54);
        linearLayout.addView(this.jabuyzrqzt);
        this.jabuyzrqzt.setBackgroundColor(Color.parseColor("#490d82"));
        RadioButton radioButton4 = new RadioButton(this);
        this.jteidqhjdp = radioButton4;
        radioButton4.setLayoutParams(new LinearLayout.LayoutParams(1720, 937));
        this.jteidqhjdp.setPadding(70, 116, 3, 20);
        linearLayout.addView(this.jteidqhjdp);
        this.jteidqhjdp.setBackgroundColor(Color.parseColor("#df12b4"));
        TimePicker timePicker = new TimePicker(this);
        this.cotnduldwz = timePicker;
        timePicker.setLayoutParams(new LinearLayout.LayoutParams(1579, 1890));
        this.cotnduldwz.setPadding(145, 5, 56, 19);
        linearLayout.addView(this.cotnduldwz);
        this.cotnduldwz.setBackgroundColor(Color.parseColor("#e0e600"));
        ScrollView scrollView2 = new ScrollView(this);
        this.eihroixcoj = scrollView2;
        scrollView2.setLayoutParams(new LinearLayout.LayoutParams(926, 1042));
        this.eihroixcoj.setPadding(174, 100, 20, 12);
        linearLayout.addView(this.eihroixcoj);
        this.eihroixcoj.setBackgroundColor(Color.parseColor("#8c98b9"));
        EditText editText = new EditText(this);
        this.yyvldfdcpe = editText;
        editText.setLayoutParams(new LinearLayout.LayoutParams(1454, 1615));
        this.yyvldfdcpe.setPadding(141, 106, 94, 15);
        linearLayout.addView(this.yyvldfdcpe);
        this.yyvldfdcpe.setBackgroundColor(Color.parseColor("#c11ec9"));
        RelativeLayout relativeLayout = new RelativeLayout(this);
        this.donvpqviga = relativeLayout;
        relativeLayout.setLayoutParams(new LinearLayout.LayoutParams(1605, 682));
        this.donvpqviga.setPadding(119, 72, 133, 26);
        linearLayout.addView(this.donvpqviga);
        this.donvpqviga.setBackgroundColor(Color.parseColor("#da816c"));
        EditText editText2 = new EditText(this);
        this.imzebllfeg = editText2;
        editText2.setLayoutParams(new LinearLayout.LayoutParams(743, 924));
        this.imzebllfeg.setPadding(79, 197, 187, 116);
        linearLayout.addView(this.imzebllfeg);
        this.imzebllfeg.setBackgroundColor(Color.parseColor("#40462a"));
        TableLayout tableLayout3 = new TableLayout(this);
        this.fayedeozno = tableLayout3;
        tableLayout3.setLayoutParams(new LinearLayout.LayoutParams(293, 1939));
        this.fayedeozno.setPadding(140, 90, 58, 53);
        linearLayout.addView(this.fayedeozno);
        this.fayedeozno.setBackgroundColor(Color.parseColor("#668b5f"));
        GridView gridView3 = new GridView(this);
        this.xvjnnwlszr = gridView3;
        gridView3.setLayoutParams(new LinearLayout.LayoutParams(1074, 1299));
        this.xvjnnwlszr.setPadding(58, 13, 166, 125);
        linearLayout.addView(this.xvjnnwlszr);
        this.xvjnnwlszr.setBackgroundColor(Color.parseColor("#a95b11"));
        TableLayout tableLayout4 = new TableLayout(this);
        this.gebneckyio = tableLayout4;
        tableLayout4.setLayoutParams(new LinearLayout.LayoutParams(1482, 1348));
        this.gebneckyio.setPadding(119, 30, 8, 7);
        linearLayout.addView(this.gebneckyio);
        this.gebneckyio.setBackgroundColor(Color.parseColor("#6fbee7"));
        FrameLayout frameLayout2 = new FrameLayout(this);
        this.rdgnnelutb = frameLayout2;
        frameLayout2.setLayoutParams(new LinearLayout.LayoutParams(251, 1645));
        this.rdgnnelutb.setPadding(9, BDLocation.TypeServerDecryptError, 124, 16);
        linearLayout.addView(this.rdgnnelutb);
        this.rdgnnelutb.setBackgroundColor(Color.parseColor("#f6018b"));
        TextView textView = new TextView(this);
        this.rgnlcuamzj = textView;
        textView.setLayoutParams(new LinearLayout.LayoutParams(899, TypedValues.Custom.TYPE_INT));
        this.rgnlcuamzj.setPadding(157, 121, 138, 129);
        linearLayout.addView(this.rgnlcuamzj);
        this.rgnlcuamzj.setBackgroundColor(Color.parseColor("#210777"));
        ProgressBar progressBar2 = new ProgressBar(this);
        this.ywofeugqzs = progressBar2;
        progressBar2.setLayoutParams(new LinearLayout.LayoutParams(1376, 747));
        this.ywofeugqzs.setPadding(100, 54, 73, 198);
        linearLayout.addView(this.ywofeugqzs);
        this.ywofeugqzs.setBackgroundColor(Color.parseColor("#3ea048"));
        ImageView imageView2 = new ImageView(this);
        this.mncizknwvd = imageView2;
        imageView2.setLayoutParams(new LinearLayout.LayoutParams(446, 623));
        this.mncizknwvd.setPadding(182, 67, 2, 137);
        linearLayout.addView(this.mncizknwvd);
        this.mncizknwvd.setBackgroundColor(Color.parseColor("#eb8667"));
        DatePicker datePicker = new DatePicker(this);
        this.qifkwrxhmy = datePicker;
        datePicker.setLayoutParams(new LinearLayout.LayoutParams(450, 23));
        this.qifkwrxhmy.setPadding(33, 102, 192, 23);
        linearLayout.addView(this.qifkwrxhmy);
        this.qifkwrxhmy.setBackgroundColor(Color.parseColor("#069cf3"));
        Spinner spinner = new Spinner(this);
        this.qlsxijtaly = spinner;
        spinner.setLayoutParams(new LinearLayout.LayoutParams(894, 350));
        this.qlsxijtaly.setPadding(83, 156, 140, 94);
        linearLayout.addView(this.qlsxijtaly);
        this.qlsxijtaly.setBackgroundColor(Color.parseColor("#f6920c"));
        LinearLayout linearLayout4 = new LinearLayout(this);
        this.regopruaqh = linearLayout4;
        linearLayout4.setLayoutParams(new LinearLayout.LayoutParams(1941, 1318));
        this.regopruaqh.setPadding(27, 184, 94, 57);
        linearLayout.addView(this.regopruaqh);
        this.regopruaqh.setBackgroundColor(Color.parseColor("#a00631"));
        TextView textView2 = new TextView(this);
        this.mtfwtvtkrx = textView2;
        textView2.setLayoutParams(new LinearLayout.LayoutParams(693, 1106));
        this.mtfwtvtkrx.setPadding(119, 153, 63, BDLocation.TypeNetWorkLocation);
        linearLayout.addView(this.mtfwtvtkrx);
        this.mtfwtvtkrx.setBackgroundColor(Color.parseColor("#2489ac"));
        GridView gridView4 = new GridView(this);
        this.imvxrwnsli = gridView4;
        gridView4.setLayoutParams(new LinearLayout.LayoutParams(1196, 1303));
        this.imvxrwnsli.setPadding(143, 158, 131, 65);
        linearLayout.addView(this.imvxrwnsli);
        this.imvxrwnsli.setBackgroundColor(Color.parseColor("#625614"));
        EditText editText3 = new EditText(this);
        this.jdsylipvtu = editText3;
        editText3.setLayoutParams(new LinearLayout.LayoutParams(1131, 1751));
        this.jdsylipvtu.setPadding(79, 182, 156, 5);
        linearLayout.addView(this.jdsylipvtu);
        this.jdsylipvtu.setBackgroundColor(Color.parseColor("#5aa2d7"));
        TimePicker timePicker2 = new TimePicker(this);
        this.rvbyonceqy = timePicker2;
        timePicker2.setLayoutParams(new LinearLayout.LayoutParams(767, 1123));
        this.rvbyonceqy.setPadding(122, 24, 185, 119);
        linearLayout.addView(this.rvbyonceqy);
        this.rvbyonceqy.setBackgroundColor(Color.parseColor("#2e78b5"));
        RelativeLayout relativeLayout2 = new RelativeLayout(this);
        this.ajxafpgixs = relativeLayout2;
        relativeLayout2.setLayoutParams(new LinearLayout.LayoutParams(1638, 1348));
        this.ajxafpgixs.setPadding(90, 100, 30, 38);
        linearLayout.addView(this.ajxafpgixs);
        this.ajxafpgixs.setBackgroundColor(Color.parseColor("#79b2e8"));
        ToggleButton toggleButton2 = new ToggleButton(this);
        this.vykehrkmmn = toggleButton2;
        toggleButton2.setLayoutParams(new LinearLayout.LayoutParams(886, 1645));
        this.vykehrkmmn.setPadding(29, 164, 108, 157);
        linearLayout.addView(this.vykehrkmmn);
        this.vykehrkmmn.setBackgroundColor(Color.parseColor("#409a58"));
        Button button = new Button(this);
        this.fojcueynah = button;
        button.setLayoutParams(new LinearLayout.LayoutParams(1856, 360));
        this.fojcueynah.setPadding(131, 75, 192, PictureConfig.CHOOSE_REQUEST);
        linearLayout.addView(this.fojcueynah);
        this.fojcueynah.setBackgroundColor(Color.parseColor("#366121"));
        GridView gridView5 = new GridView(this);
        this.asytczufnb = gridView5;
        gridView5.setLayoutParams(new LinearLayout.LayoutParams(491, 1234));
        this.asytczufnb.setPadding(BDLocation.TypeServerDecryptError, 192, 33, 110);
        linearLayout.addView(this.asytczufnb);
        this.asytczufnb.setBackgroundColor(Color.parseColor("#aebdfd"));
        ToggleButton toggleButton3 = new ToggleButton(this);
        this.ejmsvmexyz = toggleButton3;
        toggleButton3.setLayoutParams(new LinearLayout.LayoutParams(309, 1389));
        this.ejmsvmexyz.setPadding(67, 152, 19, 40);
        linearLayout.addView(this.ejmsvmexyz);
        this.ejmsvmexyz.setBackgroundColor(Color.parseColor("#d1911d"));
        CheckBox checkBox = new CheckBox(this);
        this.koewdubmle = checkBox;
        checkBox.setLayoutParams(new LinearLayout.LayoutParams(1836, 601));
        this.koewdubmle.setPadding(158, 141, 112, 82);
        linearLayout.addView(this.koewdubmle);
        this.koewdubmle.setBackgroundColor(Color.parseColor("#3d3585"));
        TextView textView3 = new TextView(this);
        this.ynyzqxapys = textView3;
        textView3.setLayoutParams(new LinearLayout.LayoutParams(1506, 1431));
        this.ynyzqxapys.setPadding(64, 70, 134, 20);
        linearLayout.addView(this.ynyzqxapys);
        this.ynyzqxapys.setBackgroundColor(Color.parseColor("#396bbf"));
        ViewFlipper viewFlipper = new ViewFlipper(this);
        this.nccppgrqlm = viewFlipper;
        viewFlipper.setLayoutParams(new LinearLayout.LayoutParams(455, 691));
        this.nccppgrqlm.setPadding(45, 181, 147, 23);
        linearLayout.addView(this.nccppgrqlm);
        this.nccppgrqlm.setBackgroundColor(Color.parseColor("#637373"));
        Spinner spinner2 = new Spinner(this);
        this.xbxnygjdnn = spinner2;
        spinner2.setLayoutParams(new LinearLayout.LayoutParams(1368, 741));
        this.xbxnygjdnn.setPadding(1, 191, 124, 38);
        linearLayout.addView(this.xbxnygjdnn);
        this.xbxnygjdnn.setBackgroundColor(Color.parseColor("#e3c51d"));
        ProgressBar progressBar3 = new ProgressBar(this);
        this.ysvgevpvcq = progressBar3;
        progressBar3.setLayoutParams(new LinearLayout.LayoutParams(413, 1707));
        this.ysvgevpvcq.setPadding(81, 172, 69, 56);
        linearLayout.addView(this.ysvgevpvcq);
        this.ysvgevpvcq.setBackgroundColor(Color.parseColor("#8f8f91"));
        Switch r22 = new Switch(this);
        this.neitibpcci = r22;
        r22.setLayoutParams(new LinearLayout.LayoutParams(1224, 1133));
        this.neitibpcci.setPadding(199, 83, 83, 180);
        linearLayout.addView(this.neitibpcci);
        this.neitibpcci.setBackgroundColor(Color.parseColor("#261fbe"));
        ProgressBar progressBar4 = new ProgressBar(this);
        this.zkehqzvtng = progressBar4;
        progressBar4.setLayoutParams(new LinearLayout.LayoutParams(368, 389));
        this.zkehqzvtng.setPadding(148, 193, 85, 8);
        linearLayout.addView(this.zkehqzvtng);
        this.zkehqzvtng.setBackgroundColor(Color.parseColor("#635744"));
        ListView listView = new ListView(this);
        this.noeytxxexe = listView;
        listView.setLayoutParams(new LinearLayout.LayoutParams(1989, 1154));
        this.noeytxxexe.setPadding(70, 46, 80, 47);
        linearLayout.addView(this.noeytxxexe);
        this.noeytxxexe.setBackgroundColor(Color.parseColor("#c08336"));
        TableLayout tableLayout5 = new TableLayout(this);
        this.eezozkytxr = tableLayout5;
        tableLayout5.setLayoutParams(new LinearLayout.LayoutParams(934, 882));
        this.eezozkytxr.setPadding(114, 109, 64, 134);
        linearLayout.addView(this.eezozkytxr);
        this.eezozkytxr.setBackgroundColor(Color.parseColor("#cf60b3"));
        ToggleButton toggleButton4 = new ToggleButton(this);
        this.tjtbgzihan = toggleButton4;
        toggleButton4.setLayoutParams(new LinearLayout.LayoutParams(950, 576));
        this.tjtbgzihan.setPadding(59, 150, 12, 35);
        linearLayout.addView(this.tjtbgzihan);
        this.tjtbgzihan.setBackgroundColor(Color.parseColor("#2dc539"));
        TimePicker timePicker3 = new TimePicker(this);
        this.qimrpnlbrj = timePicker3;
        timePicker3.setLayoutParams(new LinearLayout.LayoutParams(740, 952));
        this.qimrpnlbrj.setPadding(8, 33, 75, 154);
        linearLayout.addView(this.qimrpnlbrj);
        this.qimrpnlbrj.setBackgroundColor(Color.parseColor("#0ff469"));
        LinearLayout linearLayout5 = new LinearLayout(this);
        this.rgzdmnnhyv = linearLayout5;
        linearLayout5.setLayoutParams(new LinearLayout.LayoutParams(1089, 1709));
        this.rgzdmnnhyv.setPadding(165, 32, 154, 4);
        linearLayout.addView(this.rgzdmnnhyv);
        this.rgzdmnnhyv.setBackgroundColor(Color.parseColor("#ee94df"));
        Button button2 = new Button(this);
        this.ugdfoeavsn = button2;
        button2.setLayoutParams(new LinearLayout.LayoutParams(404, 684));
        this.ugdfoeavsn.setPadding(192, 114, 15, 77);
        linearLayout.addView(this.ugdfoeavsn);
        this.ugdfoeavsn.setBackgroundColor(Color.parseColor("#d17738"));
        RelativeLayout relativeLayout3 = new RelativeLayout(this);
        this.wjliksamup = relativeLayout3;
        relativeLayout3.setLayoutParams(new LinearLayout.LayoutParams(177, 153));
        this.wjliksamup.setPadding(13, 89, 87, 25);
        linearLayout.addView(this.wjliksamup);
        this.wjliksamup.setBackgroundColor(Color.parseColor("#78ddec"));
        TableLayout tableLayout6 = new TableLayout(this);
        this.cjnjmnglww = tableLayout6;
        tableLayout6.setLayoutParams(new LinearLayout.LayoutParams(1904, 1307));
        this.cjnjmnglww.setPadding(68, BDLocation.TypeServerError, 155, 195);
        linearLayout.addView(this.cjnjmnglww);
        this.cjnjmnglww.setBackgroundColor(Color.parseColor("#9a1a0a"));
        EditText editText4 = new EditText(this);
        this.qqbrskvdqr = editText4;
        editText4.setLayoutParams(new LinearLayout.LayoutParams(354, 1437));
        this.qqbrskvdqr.setPadding(22, 81, 137, 195);
        linearLayout.addView(this.qqbrskvdqr);
        this.qqbrskvdqr.setBackgroundColor(Color.parseColor("#3ca20a"));
        GridView gridView6 = new GridView(this);
        this.sszclukqdb = gridView6;
        gridView6.setLayoutParams(new LinearLayout.LayoutParams(469, 1595));
        this.sszclukqdb.setPadding(55, 103, 87, 27);
        linearLayout.addView(this.sszclukqdb);
        this.sszclukqdb.setBackgroundColor(Color.parseColor("#454f5c"));
        RatingBar ratingBar = new RatingBar(this);
        this.gugtgxbzds = ratingBar;
        ratingBar.setLayoutParams(new LinearLayout.LayoutParams(1424, 1134));
        this.gugtgxbzds.setPadding(29, 104, 178, 21);
        linearLayout.addView(this.gugtgxbzds);
        this.gugtgxbzds.setBackgroundColor(Color.parseColor("#b87eff"));
        RatingBar ratingBar2 = new RatingBar(this);
        this.lzdyzadibe = ratingBar2;
        ratingBar2.setLayoutParams(new LinearLayout.LayoutParams(BDLocation.TypeServerDecryptError, 781));
        this.lzdyzadibe.setPadding(BDLocation.TypeCoarseLocation, 159, 52, 52);
        linearLayout.addView(this.lzdyzadibe);
        this.lzdyzadibe.setBackgroundColor(Color.parseColor("#9d2f5a"));
        RelativeLayout relativeLayout4 = new RelativeLayout(this);
        this.auqwoemrzz = relativeLayout4;
        relativeLayout4.setLayoutParams(new LinearLayout.LayoutParams(1404, 1322));
        this.auqwoemrzz.setPadding(195, 196, 91, 5);
        linearLayout.addView(this.auqwoemrzz);
        this.auqwoemrzz.setBackgroundColor(Color.parseColor("#5b1b4a"));
        ProgressBar progressBar5 = new ProgressBar(this);
        this.idcdyuhbia = progressBar5;
        progressBar5.setLayoutParams(new LinearLayout.LayoutParams(391, 1469));
        this.idcdyuhbia.setPadding(175, 137, 149, 88);
        linearLayout.addView(this.idcdyuhbia);
        this.idcdyuhbia.setBackgroundColor(Color.parseColor("#9f9c94"));
        Button button3 = new Button(this);
        this.klpgsowlie = button3;
        button3.setLayoutParams(new LinearLayout.LayoutParams(712, 1304));
        this.klpgsowlie.setPadding(103, 63, 129, 80);
        linearLayout.addView(this.klpgsowlie);
        this.klpgsowlie.setBackgroundColor(Color.parseColor("#34165e"));
        Button button4 = new Button(this);
        this.xddjyvacpg = button4;
        button4.setLayoutParams(new LinearLayout.LayoutParams(1863, 1615));
        this.xddjyvacpg.setPadding(174, 173, 194, 107);
        linearLayout.addView(this.xddjyvacpg);
        this.xddjyvacpg.setBackgroundColor(Color.parseColor("#7af134"));
        RelativeLayout relativeLayout5 = new RelativeLayout(this);
        this.hpwmmrzcbs = relativeLayout5;
        relativeLayout5.setLayoutParams(new LinearLayout.LayoutParams(1447, 1402));
        this.hpwmmrzcbs.setPadding(133, 28, PictureConfig.CHOOSE_REQUEST, 119);
        linearLayout.addView(this.hpwmmrzcbs);
        this.hpwmmrzcbs.setBackgroundColor(Color.parseColor("#5ba111"));
        TimePicker timePicker4 = new TimePicker(this);
        this.vqomtsiuzz = timePicker4;
        timePicker4.setLayoutParams(new LinearLayout.LayoutParams(1143, 882));
        this.vqomtsiuzz.setPadding(17, 186, 184, 27);
        linearLayout.addView(this.vqomtsiuzz);
        this.vqomtsiuzz.setBackgroundColor(Color.parseColor("#643eb6"));
        RelativeLayout relativeLayout6 = new RelativeLayout(this);
        this.zvtcbipokn = relativeLayout6;
        relativeLayout6.setLayoutParams(new LinearLayout.LayoutParams(1902, 1981));
        this.zvtcbipokn.setPadding(170, 121, 68, 55);
        linearLayout.addView(this.zvtcbipokn);
        this.zvtcbipokn.setBackgroundColor(Color.parseColor("#5b57e2"));
        CheckBox checkBox2 = new CheckBox(this);
        this.jwtktlyvqv = checkBox2;
        checkBox2.setLayoutParams(new LinearLayout.LayoutParams(1069, 1343));
        this.jwtktlyvqv.setPadding(8, 124, 114, 145);
        linearLayout.addView(this.jwtktlyvqv);
        this.jwtktlyvqv.setBackgroundColor(Color.parseColor("#30c595"));
        Switch r23 = new Switch(this);
        this.hddkamivto = r23;
        r23.setLayoutParams(new LinearLayout.LayoutParams(1110, 310));
        this.hddkamivto.setPadding(86, 6, 147, 195);
        linearLayout.addView(this.hddkamivto);
        this.hddkamivto.setBackgroundColor(Color.parseColor("#ae2a86"));
        FrameLayout frameLayout3 = new FrameLayout(this);
        this.lcjhlfywdm = frameLayout3;
        frameLayout3.setLayoutParams(new LinearLayout.LayoutParams(979, 1801));
        this.lcjhlfywdm.setPadding(24, 54, 140, 5);
        linearLayout.addView(this.lcjhlfywdm);
        this.lcjhlfywdm.setBackgroundColor(Color.parseColor("#95d4e7"));
        Button button5 = new Button(this);
        this.fmyzfgjkew = button5;
        button5.setLayoutParams(new LinearLayout.LayoutParams(1800, 102));
        this.fmyzfgjkew.setPadding(106, 155, 6, 43);
        linearLayout.addView(this.fmyzfgjkew);
        this.fmyzfgjkew.setBackgroundColor(Color.parseColor("#2d4f52"));
        ProgressBar progressBar6 = new ProgressBar(this);
        this.rkhjtllpgd = progressBar6;
        progressBar6.setLayoutParams(new LinearLayout.LayoutParams(1441, 1197));
        this.rkhjtllpgd.setPadding(190, 111, 35, PictureConfig.CHOOSE_REQUEST);
        linearLayout.addView(this.rkhjtllpgd);
        this.rkhjtllpgd.setBackgroundColor(Color.parseColor("#5afc4c"));
        ScrollView scrollView3 = new ScrollView(this);
        this.cvistxncol = scrollView3;
        scrollView3.setLayoutParams(new LinearLayout.LayoutParams(1792, 1013));
        this.cvistxncol.setPadding(152, 132, 20, 168);
        linearLayout.addView(this.cvistxncol);
        this.cvistxncol.setBackgroundColor(Color.parseColor("#f147af"));
        CheckBox checkBox3 = new CheckBox(this);
        this.spypaplbww = checkBox3;
        checkBox3.setLayoutParams(new LinearLayout.LayoutParams(951, 994));
        this.spypaplbww.setPadding(5, 88, 168, 68);
        linearLayout.addView(this.spypaplbww);
        this.spypaplbww.setBackgroundColor(Color.parseColor("#802ca0"));
        ScrollView scrollView4 = new ScrollView(this);
        this.dalaatwaxj = scrollView4;
        scrollView4.setLayoutParams(new LinearLayout.LayoutParams(1900, 297));
        this.dalaatwaxj.setPadding(38, 54, 62, 92);
        linearLayout.addView(this.dalaatwaxj);
        this.dalaatwaxj.setBackgroundColor(Color.parseColor("#c588c3"));
        TimePicker timePicker5 = new TimePicker(this);
        this.vrubqzokse = timePicker5;
        timePicker5.setLayoutParams(new LinearLayout.LayoutParams(1233, 377));
        this.vrubqzokse.setPadding(44, 3, 154, 132);
        linearLayout.addView(this.vrubqzokse);
        this.vrubqzokse.setBackgroundColor(Color.parseColor("#55492b"));
        ListView listView2 = new ListView(this);
        this.fwymuxktpn = listView2;
        listView2.setLayoutParams(new LinearLayout.LayoutParams(1003, 1455));
        this.fwymuxktpn.setPadding(164, 10, 46, 77);
        linearLayout.addView(this.fwymuxktpn);
        this.fwymuxktpn.setBackgroundColor(Color.parseColor("#d1b965"));
        CheckBox checkBox4 = new CheckBox(this);
        this.vyydwuiomj = checkBox4;
        checkBox4.setLayoutParams(new LinearLayout.LayoutParams(1522, 397));
        this.vyydwuiomj.setPadding(193, 133, 168, 8);
        linearLayout.addView(this.vyydwuiomj);
        this.vyydwuiomj.setBackgroundColor(Color.parseColor("#b6d153"));
        ProgressBar progressBar7 = new ProgressBar(this);
        this.geqmuqzhff = progressBar7;
        progressBar7.setLayoutParams(new LinearLayout.LayoutParams(430, 814));
        this.geqmuqzhff.setPadding(146, 7, 176, 65);
        linearLayout.addView(this.geqmuqzhff);
        this.geqmuqzhff.setBackgroundColor(Color.parseColor("#0eee25"));
        DatePicker datePicker2 = new DatePicker(this);
        this.libpvphlpj = datePicker2;
        datePicker2.setLayoutParams(new LinearLayout.LayoutParams(331, TypedValues.CycleType.TYPE_VISIBILITY));
        this.libpvphlpj.setPadding(65, 163, 61, 130);
        linearLayout.addView(this.libpvphlpj);
        this.libpvphlpj.setBackgroundColor(Color.parseColor("#70afb4"));
        ScrollView scrollView5 = new ScrollView(this);
        this.tlbcdjelpa = scrollView5;
        scrollView5.setLayoutParams(new LinearLayout.LayoutParams(603, 506));
        this.tlbcdjelpa.setPadding(59, 27, 69, 185);
        linearLayout.addView(this.tlbcdjelpa);
        this.tlbcdjelpa.setBackgroundColor(Color.parseColor("#612c37"));
        ToggleButton toggleButton5 = new ToggleButton(this);
        this.lejhdnshyw = toggleButton5;
        toggleButton5.setLayoutParams(new LinearLayout.LayoutParams(209, 1544));
        this.lejhdnshyw.setPadding(118, 118, 170, 16);
        linearLayout.addView(this.lejhdnshyw);
        this.lejhdnshyw.setBackgroundColor(Color.parseColor("#634ad3"));
        EditText editText5 = new EditText(this);
        this.zezsdvcktt = editText5;
        editText5.setLayoutParams(new LinearLayout.LayoutParams(1221, 750));
        this.zezsdvcktt.setPadding(5, BDLocation.TypeServerDecryptError, 124, 113);
        linearLayout.addView(this.zezsdvcktt);
        this.zezsdvcktt.setBackgroundColor(Color.parseColor("#be93f0"));
        Button button6 = new Button(this);
        this.sjiqofoime = button6;
        button6.setLayoutParams(new LinearLayout.LayoutParams(971, 872));
        this.sjiqofoime.setPadding(96, 105, 112, 115);
        linearLayout.addView(this.sjiqofoime);
        this.sjiqofoime.setBackgroundColor(Color.parseColor("#6b9a0c"));
        ListView listView3 = new ListView(this);
        this.zhoofmiemo = listView3;
        listView3.setLayoutParams(new LinearLayout.LayoutParams(374, 1983));
        this.zhoofmiemo.setPadding(31, 99, 39, 164);
        linearLayout.addView(this.zhoofmiemo);
        this.zhoofmiemo.setBackgroundColor(Color.parseColor("#5921e9"));
        Button button7 = new Button(this);
        this.tfynzomxws = button7;
        button7.setLayoutParams(new LinearLayout.LayoutParams(273, 228));
        this.tfynzomxws.setPadding(22, 145, 59, 140);
        linearLayout.addView(this.tfynzomxws);
        this.tfynzomxws.setBackgroundColor(Color.parseColor("#b04390"));
        ToggleButton toggleButton6 = new ToggleButton(this);
        this.jgghhwkyee = toggleButton6;
        toggleButton6.setLayoutParams(new LinearLayout.LayoutParams(774, 142));
        this.jgghhwkyee.setPadding(34, 97, 165, 147);
        linearLayout.addView(this.jgghhwkyee);
        this.jgghhwkyee.setBackgroundColor(Color.parseColor("#9f5a35"));
        TextView textView4 = new TextView(this);
        this.ojyivegoqj = textView4;
        textView4.setLayoutParams(new LinearLayout.LayoutParams(95, 73));
        this.ojyivegoqj.setPadding(10, 35, 170, 136);
        linearLayout.addView(this.ojyivegoqj);
        this.ojyivegoqj.setBackgroundColor(Color.parseColor("#80022d"));
        ViewFlipper viewFlipper2 = new ViewFlipper(this);
        this.svelteevtd = viewFlipper2;
        viewFlipper2.setLayoutParams(new LinearLayout.LayoutParams(113, 725));
        this.svelteevtd.setPadding(50, 71, 67, 46);
        linearLayout.addView(this.svelteevtd);
        this.svelteevtd.setBackgroundColor(Color.parseColor("#361a80"));
        ToggleButton toggleButton7 = new ToggleButton(this);
        this.vnoiiwrxdz = toggleButton7;
        toggleButton7.setLayoutParams(new LinearLayout.LayoutParams(1777, 191));
        this.vnoiiwrxdz.setPadding(97, 168, 130, 108);
        linearLayout.addView(this.vnoiiwrxdz);
        this.vnoiiwrxdz.setBackgroundColor(Color.parseColor("#12971f"));
        Spinner spinner3 = new Spinner(this);
        this.ddyntbdxql = spinner3;
        spinner3.setLayoutParams(new LinearLayout.LayoutParams(678, 215));
        this.ddyntbdxql.setPadding(90, 193, 34, 169);
        linearLayout.addView(this.ddyntbdxql);
        this.ddyntbdxql.setBackgroundColor(Color.parseColor("#3f79b8"));
        LinearLayout linearLayout6 = new LinearLayout(this);
        this.yymetmiedl = linearLayout6;
        linearLayout6.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.Custom.TYPE_FLOAT, 1943));
        this.yymetmiedl.setPadding(25, 50, 47, 105);
        linearLayout.addView(this.yymetmiedl);
        this.yymetmiedl.setBackgroundColor(Color.parseColor("#49fdb6"));
        ImageView imageView3 = new ImageView(this);
        this.ibcqjzflxl = imageView3;
        imageView3.setLayoutParams(new LinearLayout.LayoutParams(147, 499));
        this.ibcqjzflxl.setPadding(148, 24, 36, 119);
        linearLayout.addView(this.ibcqjzflxl);
        this.ibcqjzflxl.setBackgroundColor(Color.parseColor("#52761b"));
        FrameLayout frameLayout4 = new FrameLayout(this);
        this.vyahxjrqti = frameLayout4;
        frameLayout4.setLayoutParams(new LinearLayout.LayoutParams(461, 794));
        this.vyahxjrqti.setPadding(145, 151, 180, 55);
        linearLayout.addView(this.vyahxjrqti);
        this.vyahxjrqti.setBackgroundColor(Color.parseColor("#398635"));
        RelativeLayout relativeLayout7 = new RelativeLayout(this);
        this.gdrujzorwv = relativeLayout7;
        relativeLayout7.setLayoutParams(new LinearLayout.LayoutParams(363, 1744));
        this.gdrujzorwv.setPadding(39, 156, 151, BDLocation.TypeServerError);
        linearLayout.addView(this.gdrujzorwv);
        this.gdrujzorwv.setBackgroundColor(Color.parseColor("#add505"));
        RatingBar ratingBar3 = new RatingBar(this);
        this.zonlqxldwk = ratingBar3;
        ratingBar3.setLayoutParams(new LinearLayout.LayoutParams(1850, GattClient.STATE_PREPARED));
        this.zonlqxldwk.setPadding(149, 19, 118, 172);
        linearLayout.addView(this.zonlqxldwk);
        this.zonlqxldwk.setBackgroundColor(Color.parseColor("#a2897d"));
        TimePicker timePicker6 = new TimePicker(this);
        this.tjcbyyzacd = timePicker6;
        timePicker6.setLayoutParams(new LinearLayout.LayoutParams(945, 721));
        this.tjcbyyzacd.setPadding(168, 178, 186, 44);
        linearLayout.addView(this.tjcbyyzacd);
        this.tjcbyyzacd.setBackgroundColor(Color.parseColor("#6698fe"));
        LinearLayout linearLayout7 = new LinearLayout(this);
        this.pquzoxeawt = linearLayout7;
        linearLayout7.setLayoutParams(new LinearLayout.LayoutParams(1251, 1748));
        this.pquzoxeawt.setPadding(137, 89, 157, 84);
        linearLayout.addView(this.pquzoxeawt);
        this.pquzoxeawt.setBackgroundColor(Color.parseColor("#966581"));
        GridView gridView7 = new GridView(this);
        this.uncealdahz = gridView7;
        gridView7.setLayoutParams(new LinearLayout.LayoutParams(202, 1474));
        this.uncealdahz.setPadding(107, 175, 156, 80);
        linearLayout.addView(this.uncealdahz);
        this.uncealdahz.setBackgroundColor(Color.parseColor("#2f2d14"));
        ProgressBar progressBar8 = new ProgressBar(this);
        this.fcjlozokah = progressBar8;
        progressBar8.setLayoutParams(new LinearLayout.LayoutParams(156, 802));
        this.fcjlozokah.setPadding(137, 98, 68, 41);
        linearLayout.addView(this.fcjlozokah);
        this.fcjlozokah.setBackgroundColor(Color.parseColor("#72ace1"));
        LinearLayout linearLayout8 = new LinearLayout(this);
        this.jmkoioyzyt = linearLayout8;
        linearLayout8.setLayoutParams(new LinearLayout.LayoutParams(1887, 279));
        this.jmkoioyzyt.setPadding(119, 58, 144, 143);
        linearLayout.addView(this.jmkoioyzyt);
        this.jmkoioyzyt.setBackgroundColor(Color.parseColor("#7bd2dc"));
        GridView gridView8 = new GridView(this);
        this.oriputzmki = gridView8;
        gridView8.setLayoutParams(new LinearLayout.LayoutParams(1904, 732));
        this.oriputzmki.setPadding(136, 138, 165, PictureConfig.CHOOSE_REQUEST);
        linearLayout.addView(this.oriputzmki);
        this.oriputzmki.setBackgroundColor(Color.parseColor("#894ede"));
        RadioButton radioButton5 = new RadioButton(this);
        this.emzprhfdpk = radioButton5;
        radioButton5.setLayoutParams(new LinearLayout.LayoutParams(25, 1314));
        this.emzprhfdpk.setPadding(197, 92, 76, 1);
        linearLayout.addView(this.emzprhfdpk);
        this.emzprhfdpk.setBackgroundColor(Color.parseColor("#bd7123"));
        Button button8 = new Button(this);
        this.efxiqqjvtb = button8;
        button8.setLayoutParams(new LinearLayout.LayoutParams(313, 1759));
        this.efxiqqjvtb.setPadding(191, 129, 118, 88);
        linearLayout.addView(this.efxiqqjvtb);
        this.efxiqqjvtb.setBackgroundColor(Color.parseColor("#ea2ffd"));
        Button button9 = new Button(this);
        this.eitwcozyib = button9;
        button9.setLayoutParams(new LinearLayout.LayoutParams(772, 460));
        this.eitwcozyib.setPadding(10, 122, 134, 30);
        linearLayout.addView(this.eitwcozyib);
        this.eitwcozyib.setBackgroundColor(Color.parseColor("#3bda7a"));
        ScrollView scrollView6 = new ScrollView(this);
        this.acqfvbzqzu = scrollView6;
        scrollView6.setLayoutParams(new LinearLayout.LayoutParams(1890, 1890));
        this.acqfvbzqzu.setPadding(2, WebSocketProtocol.PAYLOAD_SHORT, 135, 4);
        linearLayout.addView(this.acqfvbzqzu);
        this.acqfvbzqzu.setBackgroundColor(Color.parseColor("#387c7d"));
        TimePicker timePicker7 = new TimePicker(this);
        this.lmwuxxxqsk = timePicker7;
        timePicker7.setLayoutParams(new LinearLayout.LayoutParams(750, 793));
        this.lmwuxxxqsk.setPadding(130, 64, 166, 67);
        linearLayout.addView(this.lmwuxxxqsk);
        this.lmwuxxxqsk.setBackgroundColor(Color.parseColor("#4dcead"));
        TimePicker timePicker8 = new TimePicker(this);
        this.acgcmctmbo = timePicker8;
        timePicker8.setLayoutParams(new LinearLayout.LayoutParams(1453, 1158));
        this.acgcmctmbo.setPadding(143, PictureConfig.CHOOSE_REQUEST, 114, 80);
        linearLayout.addView(this.acgcmctmbo);
        this.acgcmctmbo.setBackgroundColor(Color.parseColor("#f5f53e"));
        ToggleButton toggleButton8 = new ToggleButton(this);
        this.jbpklfszhd = toggleButton8;
        toggleButton8.setLayoutParams(new LinearLayout.LayoutParams(1798, 1447));
        this.jbpklfszhd.setPadding(147, 22, 79, 42);
        linearLayout.addView(this.jbpklfszhd);
        this.jbpklfszhd.setBackgroundColor(Color.parseColor("#273eb8"));
        ListView listView4 = new ListView(this);
        this.mzoquqgyku = listView4;
        listView4.setLayoutParams(new LinearLayout.LayoutParams(679, 229));
        this.mzoquqgyku.setPadding(110, 103, 98, 6);
        linearLayout.addView(this.mzoquqgyku);
        this.mzoquqgyku.setBackgroundColor(Color.parseColor("#246fdc"));
        RelativeLayout relativeLayout8 = new RelativeLayout(this);
        this.agpxyydmrv = relativeLayout8;
        relativeLayout8.setLayoutParams(new LinearLayout.LayoutParams(1661, 1902));
        this.agpxyydmrv.setPadding(144, 94, 7, 148);
        linearLayout.addView(this.agpxyydmrv);
        this.agpxyydmrv.setBackgroundColor(Color.parseColor("#de292f"));
        RadioButton radioButton6 = new RadioButton(this);
        this.eacvhibtiw = radioButton6;
        radioButton6.setLayoutParams(new LinearLayout.LayoutParams(1558, 1653));
        this.eacvhibtiw.setPadding(115, 31, 61, 25);
        linearLayout.addView(this.eacvhibtiw);
        this.eacvhibtiw.setBackgroundColor(Color.parseColor("#41fbc4"));
        EditText editText6 = new EditText(this);
        this.sytwylzhgt = editText6;
        editText6.setLayoutParams(new LinearLayout.LayoutParams(377, 80));
        this.sytwylzhgt.setPadding(116, 154, 51, 145);
        linearLayout.addView(this.sytwylzhgt);
        this.sytwylzhgt.setBackgroundColor(Color.parseColor("#3f3edb"));
        RelativeLayout relativeLayout9 = new RelativeLayout(this);
        this.rpqvvmpswq = relativeLayout9;
        relativeLayout9.setLayoutParams(new LinearLayout.LayoutParams(1628, 469));
        this.rpqvvmpswq.setPadding(16, 98, 107, 80);
        linearLayout.addView(this.rpqvvmpswq);
        this.rpqvvmpswq.setBackgroundColor(Color.parseColor("#7198f9"));
        Switch r24 = new Switch(this);
        this.uvfbtmmwva = r24;
        r24.setLayoutParams(new LinearLayout.LayoutParams(1597, 25));
        this.uvfbtmmwva.setPadding(99, 49, 92, 181);
        linearLayout.addView(this.uvfbtmmwva);
        this.uvfbtmmwva.setBackgroundColor(Color.parseColor("#fa3172"));
        Switch r25 = new Switch(this);
        this.grvsfxvjgy = r25;
        r25.setLayoutParams(new LinearLayout.LayoutParams(146, 366));
        this.grvsfxvjgy.setPadding(132, 157, 190, 99);
        linearLayout.addView(this.grvsfxvjgy);
        this.grvsfxvjgy.setBackgroundColor(Color.parseColor("#6f68aa"));
        ScrollView scrollView7 = new ScrollView(this);
        this.qpbgetjnnx = scrollView7;
        scrollView7.setLayoutParams(new LinearLayout.LayoutParams(947, 111));
        this.qpbgetjnnx.setPadding(158, 145, 77, 51);
        linearLayout.addView(this.qpbgetjnnx);
        this.qpbgetjnnx.setBackgroundColor(Color.parseColor("#2c3fa0"));
        DatePicker datePicker3 = new DatePicker(this);
        this.zxkxjcungv = datePicker3;
        datePicker3.setLayoutParams(new LinearLayout.LayoutParams(783, 834));
        this.zxkxjcungv.setPadding(24, 34, 32, 26);
        linearLayout.addView(this.zxkxjcungv);
        this.zxkxjcungv.setBackgroundColor(Color.parseColor("#decf1e"));
        ToggleButton toggleButton9 = new ToggleButton(this);
        this.futgwkicaa = toggleButton9;
        toggleButton9.setLayoutParams(new LinearLayout.LayoutParams(131, 401));
        this.futgwkicaa.setPadding(156, 180, 139, 180);
        linearLayout.addView(this.futgwkicaa);
        this.futgwkicaa.setBackgroundColor(Color.parseColor("#db7d59"));
        TextView textView5 = new TextView(this);
        this.olbienompi = textView5;
        textView5.setLayoutParams(new LinearLayout.LayoutParams(94, 1422));
        this.olbienompi.setPadding(181, 113, 88, 108);
        linearLayout.addView(this.olbienompi);
        this.olbienompi.setBackgroundColor(Color.parseColor("#914917"));
        RelativeLayout relativeLayout10 = new RelativeLayout(this);
        this.uxpephlvuk = relativeLayout10;
        relativeLayout10.setLayoutParams(new LinearLayout.LayoutParams(761, 139));
        this.uxpephlvuk.setPadding(18, 118, 141, 16);
        linearLayout.addView(this.uxpephlvuk);
        this.uxpephlvuk.setBackgroundColor(Color.parseColor("#b3e882"));
        Switch r26 = new Switch(this);
        this.dtwbbmrqch = r26;
        r26.setLayoutParams(new LinearLayout.LayoutParams(1404, 1194));
        this.dtwbbmrqch.setPadding(199, BDLocation.TypeServerDecryptError, 94, 44);
        linearLayout.addView(this.dtwbbmrqch);
        this.dtwbbmrqch.setBackgroundColor(Color.parseColor("#2f9286"));
        CheckBox checkBox5 = new CheckBox(this);
        this.hakchmqkjy = checkBox5;
        checkBox5.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.MotionType.TYPE_QUANTIZE_INTERPOLATOR_ID, 1758));
        this.hakchmqkjy.setPadding(124, 4, 34, 42);
        linearLayout.addView(this.hakchmqkjy);
        this.hakchmqkjy.setBackgroundColor(Color.parseColor("#d0813f"));
        ToggleButton toggleButton10 = new ToggleButton(this);
        this.iwqqrnteqn = toggleButton10;
        toggleButton10.setLayoutParams(new LinearLayout.LayoutParams(632, 294));
        this.iwqqrnteqn.setPadding(94, 48, 195, 20);
        linearLayout.addView(this.iwqqrnteqn);
        this.iwqqrnteqn.setBackgroundColor(Color.parseColor("#0fbb2a"));
        TimePicker timePicker9 = new TimePicker(this);
        this.zphcufjtsv = timePicker9;
        timePicker9.setLayoutParams(new LinearLayout.LayoutParams(1186, 843));
        this.zphcufjtsv.setPadding(74, 134, 166, 63);
        linearLayout.addView(this.zphcufjtsv);
        this.zphcufjtsv.setBackgroundColor(Color.parseColor("#b1b40b"));
        RadioButton radioButton7 = new RadioButton(this);
        this.rjcayuswhy = radioButton7;
        radioButton7.setLayoutParams(new LinearLayout.LayoutParams(914, 494));
        this.rjcayuswhy.setPadding(120, 175, 59, 69);
        linearLayout.addView(this.rjcayuswhy);
        this.rjcayuswhy.setBackgroundColor(Color.parseColor("#9ac30e"));
        Switch r27 = new Switch(this);
        this.bhdonwrmme = r27;
        r27.setLayoutParams(new LinearLayout.LayoutParams(1686, 1671));
        this.bhdonwrmme.setPadding(44, 156, 78, WebSocketProtocol.PAYLOAD_SHORT);
        linearLayout.addView(this.bhdonwrmme);
        this.bhdonwrmme.setBackgroundColor(Color.parseColor("#e8af41"));
        ToggleButton toggleButton11 = new ToggleButton(this);
        this.puelvsulsg = toggleButton11;
        toggleButton11.setLayoutParams(new LinearLayout.LayoutParams(478, 581));
        this.puelvsulsg.setPadding(153, 5, 99, 91);
        linearLayout.addView(this.puelvsulsg);
        this.puelvsulsg.setBackgroundColor(Color.parseColor("#2af4bc"));
        ListView listView5 = new ListView(this);
        this.cdmrtflzim = listView5;
        listView5.setLayoutParams(new LinearLayout.LayoutParams(1187, 1479));
        this.cdmrtflzim.setPadding(95, 51, 184, 144);
        linearLayout.addView(this.cdmrtflzim);
        this.cdmrtflzim.setBackgroundColor(Color.parseColor("#5efa16"));
        GridView gridView9 = new GridView(this);
        this.qwtcgklnjy = gridView9;
        gridView9.setLayoutParams(new LinearLayout.LayoutParams(526, 204));
        this.qwtcgklnjy.setPadding(140, 154, 43, 68);
        linearLayout.addView(this.qwtcgklnjy);
        this.qwtcgklnjy.setBackgroundColor(Color.parseColor("#c71778"));
        ListView listView6 = new ListView(this);
        this.iroikmwwsx = listView6;
        listView6.setLayoutParams(new LinearLayout.LayoutParams(734, 1460));
        this.iroikmwwsx.setPadding(31, 63, 140, 143);
        linearLayout.addView(this.iroikmwwsx);
        this.iroikmwwsx.setBackgroundColor(Color.parseColor("#420fce"));
        ProgressBar progressBar9 = new ProgressBar(this);
        this.lcwvojopoq = progressBar9;
        progressBar9.setLayoutParams(new LinearLayout.LayoutParams(716, 475));
        this.lcwvojopoq.setPadding(BDLocation.TypeCoarseLocation, 34, 166, 40);
        linearLayout.addView(this.lcwvojopoq);
        this.lcwvojopoq.setBackgroundColor(Color.parseColor("#acf26f"));
        Spinner spinner4 = new Spinner(this);
        this.jlexfzrusy = spinner4;
        spinner4.setLayoutParams(new LinearLayout.LayoutParams(1184, 1654));
        this.jlexfzrusy.setPadding(28, 81, 110, 33);
        linearLayout.addView(this.jlexfzrusy);
        this.jlexfzrusy.setBackgroundColor(Color.parseColor("#7d4045"));
        TimePicker timePicker10 = new TimePicker(this);
        this.vjxvmgalsw = timePicker10;
        timePicker10.setLayoutParams(new LinearLayout.LayoutParams(78, 1861));
        this.vjxvmgalsw.setPadding(84, 57, 22, 41);
        linearLayout.addView(this.vjxvmgalsw);
        this.vjxvmgalsw.setBackgroundColor(Color.parseColor("#faf2d6"));
        ScrollView scrollView8 = new ScrollView(this);
        this.ndrdoacoqf = scrollView8;
        scrollView8.setLayoutParams(new LinearLayout.LayoutParams(1811, 1597));
        this.ndrdoacoqf.setPadding(WebSocketProtocol.PAYLOAD_SHORT, 145, 155, 29);
        linearLayout.addView(this.ndrdoacoqf);
        this.ndrdoacoqf.setBackgroundColor(Color.parseColor("#829abc"));
        CheckBox checkBox6 = new CheckBox(this);
        this.qnnelbedxv = checkBox6;
        checkBox6.setLayoutParams(new LinearLayout.LayoutParams(1520, 919));
        this.qnnelbedxv.setPadding(108, 61, 145, 19);
        linearLayout.addView(this.qnnelbedxv);
        this.qnnelbedxv.setBackgroundColor(Color.parseColor("#f9e2bd"));
        CheckBox checkBox7 = new CheckBox(this);
        this.fuirlxtfxr = checkBox7;
        checkBox7.setLayoutParams(new LinearLayout.LayoutParams(737, 193));
        this.fuirlxtfxr.setPadding(185, 171, 152, 91);
        linearLayout.addView(this.fuirlxtfxr);
        this.fuirlxtfxr.setBackgroundColor(Color.parseColor("#df3c93"));
        DatePicker datePicker4 = new DatePicker(this);
        this.whgauhlona = datePicker4;
        datePicker4.setLayoutParams(new LinearLayout.LayoutParams(879, 664));
        this.whgauhlona.setPadding(2, 14, 63, 187);
        linearLayout.addView(this.whgauhlona);
        this.whgauhlona.setBackgroundColor(Color.parseColor("#c11693"));
        TextView textView6 = new TextView(this);
        this.cwmgywpmjx = textView6;
        textView6.setLayoutParams(new LinearLayout.LayoutParams(728, 1143));
        this.cwmgywpmjx.setPadding(17, 29, 7, 79);
        linearLayout.addView(this.cwmgywpmjx);
        this.cwmgywpmjx.setBackgroundColor(Color.parseColor("#3a285f"));
        ImageView imageView4 = new ImageView(this);
        this.raqcwlutrn = imageView4;
        imageView4.setLayoutParams(new LinearLayout.LayoutParams(264, 856));
        this.raqcwlutrn.setPadding(134, 71, 106, 91);
        linearLayout.addView(this.raqcwlutrn);
        this.raqcwlutrn.setBackgroundColor(Color.parseColor("#36bc8c"));
        CheckBox checkBox8 = new CheckBox(this);
        this.fgqknevmxe = checkBox8;
        checkBox8.setLayoutParams(new LinearLayout.LayoutParams(969, 670));
        this.fgqknevmxe.setPadding(183, 142, 154, 150);
        linearLayout.addView(this.fgqknevmxe);
        this.fgqknevmxe.setBackgroundColor(Color.parseColor("#2abd2d"));
        GridView gridView10 = new GridView(this);
        this.qgmftqdxqj = gridView10;
        gridView10.setLayoutParams(new LinearLayout.LayoutParams(62, 772));
        this.qgmftqdxqj.setPadding(40, 165, 77, 83);
        linearLayout.addView(this.qgmftqdxqj);
        this.qgmftqdxqj.setBackgroundColor(Color.parseColor("#3a17cf"));
        RadioButton radioButton8 = new RadioButton(this);
        this.zjhkczjwgq = radioButton8;
        radioButton8.setLayoutParams(new LinearLayout.LayoutParams(1957, 1196));
        this.zjhkczjwgq.setPadding(20, 71, 5, 14);
        linearLayout.addView(this.zjhkczjwgq);
        this.zjhkczjwgq.setBackgroundColor(Color.parseColor("#a9dbb5"));
        TableLayout tableLayout7 = new TableLayout(this);
        this.dorrruhhow = tableLayout7;
        tableLayout7.setLayoutParams(new LinearLayout.LayoutParams(PDF417Common.NUMBER_OF_CODEWORDS, 1999));
        this.dorrruhhow.setPadding(129, 69, 15, 136);
        linearLayout.addView(this.dorrruhhow);
        this.dorrruhhow.setBackgroundColor(Color.parseColor("#86640c"));
        ToggleButton toggleButton12 = new ToggleButton(this);
        this.cbwkwewgme = toggleButton12;
        toggleButton12.setLayoutParams(new LinearLayout.LayoutParams(687, 325));
        this.cbwkwewgme.setPadding(186, 196, BDLocation.TypeNetWorkLocation, 32);
        linearLayout.addView(this.cbwkwewgme);
        this.cbwkwewgme.setBackgroundColor(Color.parseColor("#4866d8"));
        ToggleButton toggleButton13 = new ToggleButton(this);
        this.rpwnkcxtfh = toggleButton13;
        toggleButton13.setLayoutParams(new LinearLayout.LayoutParams(985, 1657));
        this.rpwnkcxtfh.setPadding(WebSocketProtocol.PAYLOAD_SHORT, 105, 94, 7);
        linearLayout.addView(this.rpwnkcxtfh);
        this.rpwnkcxtfh.setBackgroundColor(Color.parseColor("#c743a5"));
        TableLayout tableLayout8 = new TableLayout(this);
        this.agwftrwuql = tableLayout8;
        tableLayout8.setLayoutParams(new LinearLayout.LayoutParams(1438, BuildConfig.VERSION_CODE));
        this.agwftrwuql.setPadding(86, 114, 189, 95);
        linearLayout.addView(this.agwftrwuql);
        this.agwftrwuql.setBackgroundColor(Color.parseColor("#3d5757"));
        ImageView imageView5 = new ImageView(this);
        this.yjotuzeyzo = imageView5;
        imageView5.setLayoutParams(new LinearLayout.LayoutParams(554, 234));
        this.yjotuzeyzo.setPadding(149, 34, 92, 9);
        linearLayout.addView(this.yjotuzeyzo);
        this.yjotuzeyzo.setBackgroundColor(Color.parseColor("#477876"));
        CheckBox checkBox9 = new CheckBox(this);
        this.jtcgzvknin = checkBox9;
        checkBox9.setLayoutParams(new LinearLayout.LayoutParams(1528, 461));
        this.jtcgzvknin.setPadding(153, 33, 84, 49);
        linearLayout.addView(this.jtcgzvknin);
        this.jtcgzvknin.setBackgroundColor(Color.parseColor("#a0f693"));
        ImageView imageView6 = new ImageView(this);
        this.htdvbchfvu = imageView6;
        imageView6.setLayoutParams(new LinearLayout.LayoutParams(1565, 1286));
        this.htdvbchfvu.setPadding(198, 142, 150, 103);
        linearLayout.addView(this.htdvbchfvu);
        this.htdvbchfvu.setBackgroundColor(Color.parseColor("#11543f"));
        Button button10 = new Button(this);
        this.ziwggqzhvl = button10;
        button10.setLayoutParams(new LinearLayout.LayoutParams(985, 723));
        this.ziwggqzhvl.setPadding(194, 138, 154, 140);
        linearLayout.addView(this.ziwggqzhvl);
        this.ziwggqzhvl.setBackgroundColor(Color.parseColor("#b8784e"));
        ImageView imageView7 = new ImageView(this);
        this.ljdfoxzosz = imageView7;
        imageView7.setLayoutParams(new LinearLayout.LayoutParams(1726, 1657));
        this.ljdfoxzosz.setPadding(108, 170, 112, 93);
        linearLayout.addView(this.ljdfoxzosz);
        this.ljdfoxzosz.setBackgroundColor(Color.parseColor("#ba5f62"));
        ViewFlipper viewFlipper3 = new ViewFlipper(this);
        this.irlsguhlkx = viewFlipper3;
        viewFlipper3.setLayoutParams(new LinearLayout.LayoutParams(1114, 1439));
        this.irlsguhlkx.setPadding(174, BDLocation.TypeNetWorkLocation, 55, 136);
        linearLayout.addView(this.irlsguhlkx);
        this.irlsguhlkx.setBackgroundColor(Color.parseColor("#d37926"));
        RelativeLayout relativeLayout11 = new RelativeLayout(this);
        this.pzotlqicwm = relativeLayout11;
        relativeLayout11.setLayoutParams(new LinearLayout.LayoutParams(921, 635));
        this.pzotlqicwm.setPadding(106, BDLocation.TypeCoarseLocation, 147, 122);
        linearLayout.addView(this.pzotlqicwm);
        this.pzotlqicwm.setBackgroundColor(Color.parseColor("#730c00"));
        RatingBar ratingBar4 = new RatingBar(this);
        this.icmqfigeil = ratingBar4;
        ratingBar4.setLayoutParams(new LinearLayout.LayoutParams(667, 1972));
        this.icmqfigeil.setPadding(98, 98, 43, BDLocation.TypeServerDecryptError);
        linearLayout.addView(this.icmqfigeil);
        this.icmqfigeil.setBackgroundColor(Color.parseColor("#6b1237"));
        ProgressBar progressBar10 = new ProgressBar(this);
        this.tbjahfbqwo = progressBar10;
        progressBar10.setLayoutParams(new LinearLayout.LayoutParams(1180, 428));
        this.tbjahfbqwo.setPadding(104, 121, 143, 173);
        linearLayout.addView(this.tbjahfbqwo);
        this.tbjahfbqwo.setBackgroundColor(Color.parseColor("#111039"));
        TextView textView7 = new TextView(this);
        this.mqisstmyhk = textView7;
        textView7.setLayoutParams(new LinearLayout.LayoutParams(458, 801));
        this.mqisstmyhk.setPadding(12, 110, 145, 62);
        linearLayout.addView(this.mqisstmyhk);
        this.mqisstmyhk.setBackgroundColor(Color.parseColor("#8cfbaa"));
        ListView listView7 = new ListView(this);
        this.sboexxbrxs = listView7;
        listView7.setLayoutParams(new LinearLayout.LayoutParams(1561, 1368));
        this.sboexxbrxs.setPadding(12, 9, 34, 1);
        linearLayout.addView(this.sboexxbrxs);
        this.sboexxbrxs.setBackgroundColor(Color.parseColor("#3c1839"));
        FrameLayout frameLayout5 = new FrameLayout(this);
        this.ofqavlpsbo = frameLayout5;
        frameLayout5.setLayoutParams(new LinearLayout.LayoutParams(1258, 589));
        this.ofqavlpsbo.setPadding(94, 46, 157, 35);
        linearLayout.addView(this.ofqavlpsbo);
        this.ofqavlpsbo.setBackgroundColor(Color.parseColor("#e315c7"));
        ViewFlipper viewFlipper4 = new ViewFlipper(this);
        this.usflwrrsdg = viewFlipper4;
        viewFlipper4.setLayoutParams(new LinearLayout.LayoutParams(18, 1090));
        this.usflwrrsdg.setPadding(137, 184, 72, 176);
        linearLayout.addView(this.usflwrrsdg);
        this.usflwrrsdg.setBackgroundColor(Color.parseColor("#f2de02"));
        RadioButton radioButton9 = new RadioButton(this);
        this.htwgkaorxn = radioButton9;
        radioButton9.setLayoutParams(new LinearLayout.LayoutParams(1710, 1803));
        this.htwgkaorxn.setPadding(123, 6, 94, 169);
        linearLayout.addView(this.htwgkaorxn);
        this.htwgkaorxn.setBackgroundColor(Color.parseColor("#072035"));
        ViewFlipper viewFlipper5 = new ViewFlipper(this);
        this.xmwfrwjiqy = viewFlipper5;
        viewFlipper5.setLayoutParams(new LinearLayout.LayoutParams(1547, 635));
        this.xmwfrwjiqy.setPadding(20, 54, 50, 82);
        linearLayout.addView(this.xmwfrwjiqy);
        this.xmwfrwjiqy.setBackgroundColor(Color.parseColor("#82ddc7"));
        ImageView imageView8 = new ImageView(this);
        this.jcbeelbzpu = imageView8;
        imageView8.setLayoutParams(new LinearLayout.LayoutParams(1915, 1558));
        this.jcbeelbzpu.setPadding(48, 146, 165, 149);
        linearLayout.addView(this.jcbeelbzpu);
        this.jcbeelbzpu.setBackgroundColor(Color.parseColor("#5b6728"));
        TableLayout tableLayout9 = new TableLayout(this);
        this.nrtfmbjocr = tableLayout9;
        tableLayout9.setLayoutParams(new LinearLayout.LayoutParams(1308, 1531));
        this.nrtfmbjocr.setPadding(195, 197, 32, 5);
        linearLayout.addView(this.nrtfmbjocr);
        this.nrtfmbjocr.setBackgroundColor(Color.parseColor("#a310e2"));
        SeekBar seekBar3 = new SeekBar(this);
        this.ezwnxbyluk = seekBar3;
        seekBar3.setLayoutParams(new LinearLayout.LayoutParams(186, 1300));
        this.ezwnxbyluk.setPadding(5, 122, 77, 18);
        linearLayout.addView(this.ezwnxbyluk);
        this.ezwnxbyluk.setBackgroundColor(Color.parseColor("#0ba0a3"));
        GridView gridView11 = new GridView(this);
        this.dmgazxvbim = gridView11;
        gridView11.setLayoutParams(new LinearLayout.LayoutParams(764, 549));
        this.dmgazxvbim.setPadding(173, 170, 183, 173);
        linearLayout.addView(this.dmgazxvbim);
        this.dmgazxvbim.setBackgroundColor(Color.parseColor("#5de1d9"));
        DatePicker datePicker5 = new DatePicker(this);
        this.cldzuxghmm = datePicker5;
        datePicker5.setLayoutParams(new LinearLayout.LayoutParams(1333, 22));
        this.cldzuxghmm.setPadding(186, 104, 34, 176);
        linearLayout.addView(this.cldzuxghmm);
        this.cldzuxghmm.setBackgroundColor(Color.parseColor("#48edd3"));
        RadioButton radioButton10 = new RadioButton(this);
        this.naalpghflr = radioButton10;
        radioButton10.setLayoutParams(new LinearLayout.LayoutParams(88, 1061));
        this.naalpghflr.setPadding(141, 115, 109, 12);
        linearLayout.addView(this.naalpghflr);
        this.naalpghflr.setBackgroundColor(Color.parseColor("#85ecde"));
        TimePicker timePicker11 = new TimePicker(this);
        this.noguqmgneo = timePicker11;
        timePicker11.setLayoutParams(new LinearLayout.LayoutParams(374, 676));
        this.noguqmgneo.setPadding(67, 23, 131, 191);
        linearLayout.addView(this.noguqmgneo);
        this.noguqmgneo.setBackgroundColor(Color.parseColor("#87c097"));
        TimePicker timePicker12 = new TimePicker(this);
        this.fermrotpoj = timePicker12;
        timePicker12.setLayoutParams(new LinearLayout.LayoutParams(1531, 1044));
        this.fermrotpoj.setPadding(40, 176, 104, 33);
        linearLayout.addView(this.fermrotpoj);
        this.fermrotpoj.setBackgroundColor(Color.parseColor("#cd6479"));
        TableLayout tableLayout10 = new TableLayout(this);
        this.xszcizbkvc = tableLayout10;
        tableLayout10.setLayoutParams(new LinearLayout.LayoutParams(WebSocketImpl.DEFAULT_WSS_PORT, 1156));
        this.xszcizbkvc.setPadding(166, 172, 168, 195);
        linearLayout.addView(this.xszcizbkvc);
        this.xszcizbkvc.setBackgroundColor(Color.parseColor("#9fa775"));
        LinearLayout linearLayout9 = new LinearLayout(this);
        this.eotmjazyaq = linearLayout9;
        linearLayout9.setLayoutParams(new LinearLayout.LayoutParams(372, 434));
        this.eotmjazyaq.setPadding(58, 61, 123, 140);
        linearLayout.addView(this.eotmjazyaq);
        this.eotmjazyaq.setBackgroundColor(Color.parseColor("#89bfdf"));
        ListView listView8 = new ListView(this);
        this.stxhsbwwqs = listView8;
        listView8.setLayoutParams(new LinearLayout.LayoutParams(1541, 355));
        this.stxhsbwwqs.setPadding(184, 120, 156, 16);
        linearLayout.addView(this.stxhsbwwqs);
        this.stxhsbwwqs.setBackgroundColor(Color.parseColor("#ddff3c"));
        GridView gridView12 = new GridView(this);
        this.cfqzzumlmc = gridView12;
        gridView12.setLayoutParams(new LinearLayout.LayoutParams(228, 1161));
        this.cfqzzumlmc.setPadding(117, 109, 65, 110);
        linearLayout.addView(this.cfqzzumlmc);
        this.cfqzzumlmc.setBackgroundColor(Color.parseColor("#e38c51"));
        SeekBar seekBar4 = new SeekBar(this);
        this.ctbzlozdqx = seekBar4;
        seekBar4.setLayoutParams(new LinearLayout.LayoutParams(709, 1049));
        this.ctbzlozdqx.setPadding(123, 82, 29, 30);
        linearLayout.addView(this.ctbzlozdqx);
        this.ctbzlozdqx.setBackgroundColor(Color.parseColor("#c97eb8"));
        TableLayout tableLayout11 = new TableLayout(this);
        this.zxwhiyikep = tableLayout11;
        tableLayout11.setLayoutParams(new LinearLayout.LayoutParams(1086, 575));
        this.zxwhiyikep.setPadding(3, 6, 112, 60);
        linearLayout.addView(this.zxwhiyikep);
        this.zxwhiyikep.setBackgroundColor(Color.parseColor("#0c6621"));
        ProgressBar progressBar11 = new ProgressBar(this);
        this.xmcckesmwy = progressBar11;
        progressBar11.setLayoutParams(new LinearLayout.LayoutParams(1774, 104));
        this.xmcckesmwy.setPadding(132, 16, 0, 141);
        linearLayout.addView(this.xmcckesmwy);
        this.xmcckesmwy.setBackgroundColor(Color.parseColor("#0147e6"));
        ProgressBar progressBar12 = new ProgressBar(this);
        this.wfiqqwynrm = progressBar12;
        progressBar12.setLayoutParams(new LinearLayout.LayoutParams(229, 1267));
        this.wfiqqwynrm.setPadding(16, 122, 40, 52);
        linearLayout.addView(this.wfiqqwynrm);
        this.wfiqqwynrm.setBackgroundColor(Color.parseColor("#905d3c"));
        ImageView imageView9 = new ImageView(this);
        this.prukczrdfp = imageView9;
        imageView9.setLayoutParams(new LinearLayout.LayoutParams(1319, 1372));
        this.prukczrdfp.setPadding(134, 158, 6, 72);
        linearLayout.addView(this.prukczrdfp);
        this.prukczrdfp.setBackgroundColor(Color.parseColor("#811dc0"));
        ProgressBar progressBar13 = new ProgressBar(this);
        this.hhocgkdpbd = progressBar13;
        progressBar13.setLayoutParams(new LinearLayout.LayoutParams(1474, PointerIconCompat.TYPE_GRABBING));
        this.hhocgkdpbd.setPadding(10, 179, 19, 117);
        linearLayout.addView(this.hhocgkdpbd);
        this.hhocgkdpbd.setBackgroundColor(Color.parseColor("#578f6c"));
        TextView textView8 = new TextView(this);
        this.mrxdqagdpc = textView8;
        textView8.setLayoutParams(new LinearLayout.LayoutParams(1782, 682));
        this.mrxdqagdpc.setPadding(48, 131, 195, 197);
        linearLayout.addView(this.mrxdqagdpc);
        this.mrxdqagdpc.setBackgroundColor(Color.parseColor("#998983"));
        TableLayout tableLayout12 = new TableLayout(this);
        this.ytlwjrsrvi = tableLayout12;
        tableLayout12.setLayoutParams(new LinearLayout.LayoutParams(636, 1681));
        this.ytlwjrsrvi.setPadding(169, 189, 35, 18);
        linearLayout.addView(this.ytlwjrsrvi);
        this.ytlwjrsrvi.setBackgroundColor(Color.parseColor("#c7ddf3"));
        EditText editText7 = new EditText(this);
        this.rqcmrkqjns = editText7;
        editText7.setLayoutParams(new LinearLayout.LayoutParams(1527, 1252));
        this.rqcmrkqjns.setPadding(101, 114, 154, 137);
        linearLayout.addView(this.rqcmrkqjns);
        this.rqcmrkqjns.setBackgroundColor(Color.parseColor("#b6048b"));
        ScrollView scrollView9 = new ScrollView(this);
        this.emhhdrzffn = scrollView9;
        scrollView9.setLayoutParams(new LinearLayout.LayoutParams(1838, 667));
        this.emhhdrzffn.setPadding(192, 134, 80, 182);
        linearLayout.addView(this.emhhdrzffn);
        this.emhhdrzffn.setBackgroundColor(Color.parseColor("#26c554"));
        CheckBox checkBox10 = new CheckBox(this);
        this.rymseikhhu = checkBox10;
        checkBox10.setLayoutParams(new LinearLayout.LayoutParams(627, 1090));
        this.rymseikhhu.setPadding(152, 165, 98, 47);
        linearLayout.addView(this.rymseikhhu);
        this.rymseikhhu.setBackgroundColor(Color.parseColor("#632414"));
        SeekBar seekBar5 = new SeekBar(this);
        this.vowatujsfs = seekBar5;
        seekBar5.setLayoutParams(new LinearLayout.LayoutParams(230, 1571));
        this.vowatujsfs.setPadding(82, 176, 191, 175);
        linearLayout.addView(this.vowatujsfs);
        this.vowatujsfs.setBackgroundColor(Color.parseColor("#ddf58b"));
        RatingBar ratingBar5 = new RatingBar(this);
        this.otucbfowcl = ratingBar5;
        ratingBar5.setLayoutParams(new LinearLayout.LayoutParams(426, 1176));
        this.otucbfowcl.setPadding(28, 43, 141, 49);
        linearLayout.addView(this.otucbfowcl);
        this.otucbfowcl.setBackgroundColor(Color.parseColor("#126e8c"));
        ProgressBar progressBar14 = new ProgressBar(this);
        this.eottvahzvh = progressBar14;
        progressBar14.setLayoutParams(new LinearLayout.LayoutParams(336, 1513));
        this.eottvahzvh.setPadding(158, 11, 108, 86);
        linearLayout.addView(this.eottvahzvh);
        this.eottvahzvh.setBackgroundColor(Color.parseColor("#250b6c"));
        CheckBox checkBox11 = new CheckBox(this);
        this.oppzfxtkef = checkBox11;
        checkBox11.setLayoutParams(new LinearLayout.LayoutParams(90, 917));
        this.oppzfxtkef.setPadding(163, BDLocation.TypeServerDecryptError, 116, 196);
        linearLayout.addView(this.oppzfxtkef);
        this.oppzfxtkef.setBackgroundColor(Color.parseColor("#c9ab21"));
        TableLayout tableLayout13 = new TableLayout(this);
        this.ydcxwknkcg = tableLayout13;
        tableLayout13.setLayoutParams(new LinearLayout.LayoutParams(1296, 456));
        this.ydcxwknkcg.setPadding(148, 158, 26, 35);
        linearLayout.addView(this.ydcxwknkcg);
        this.ydcxwknkcg.setBackgroundColor(Color.parseColor("#c46e8d"));
        FrameLayout frameLayout6 = new FrameLayout(this);
        this.aqanvtnxas = frameLayout6;
        frameLayout6.setLayoutParams(new LinearLayout.LayoutParams(1510, 1137));
        this.aqanvtnxas.setPadding(PictureConfig.CHOOSE_REQUEST, 35, 149, 38);
        linearLayout.addView(this.aqanvtnxas);
        this.aqanvtnxas.setBackgroundColor(Color.parseColor("#bd10a4"));
        CheckBox checkBox12 = new CheckBox(this);
        this.ammvdrjons = checkBox12;
        checkBox12.setLayoutParams(new LinearLayout.LayoutParams(1270, 1494));
        this.ammvdrjons.setPadding(174, 135, 86, 28);
        linearLayout.addView(this.ammvdrjons);
        this.ammvdrjons.setBackgroundColor(Color.parseColor("#7f08c1"));
        ProgressBar progressBar15 = new ProgressBar(this);
        this.wnjogerhuk = progressBar15;
        progressBar15.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.TransitionType.TYPE_INTERPOLATOR, 1757));
        this.wnjogerhuk.setPadding(11, 19, 13, BDLocation.TypeServerDecryptError);
        linearLayout.addView(this.wnjogerhuk);
        this.wnjogerhuk.setBackgroundColor(Color.parseColor("#116f08"));
        ListView listView9 = new ListView(this);
        this.tzgwbvgnwo = listView9;
        listView9.setLayoutParams(new LinearLayout.LayoutParams(1992, 1312));
        this.tzgwbvgnwo.setPadding(113, 181, 65, 166);
        linearLayout.addView(this.tzgwbvgnwo);
        this.tzgwbvgnwo.setBackgroundColor(Color.parseColor("#87b710"));
        RatingBar ratingBar6 = new RatingBar(this);
        this.nwlyfhijrm = ratingBar6;
        ratingBar6.setLayoutParams(new LinearLayout.LayoutParams(993, 694));
        this.nwlyfhijrm.setPadding(38, 47, 95, 41);
        linearLayout.addView(this.nwlyfhijrm);
        this.nwlyfhijrm.setBackgroundColor(Color.parseColor("#26f586"));
        EditText editText8 = new EditText(this);
        this.hioksmlduu = editText8;
        editText8.setLayoutParams(new LinearLayout.LayoutParams(1788, 1841));
        this.hioksmlduu.setPadding(10, 163, 75, BDLocation.TypeNetWorkLocation);
        linearLayout.addView(this.hioksmlduu);
        this.hioksmlduu.setBackgroundColor(Color.parseColor("#720ef0"));
        RatingBar ratingBar7 = new RatingBar(this);
        this.jhtsspunzw = ratingBar7;
        ratingBar7.setLayoutParams(new LinearLayout.LayoutParams(109, 1232));
        this.jhtsspunzw.setPadding(83, 6, 68, 145);
        linearLayout.addView(this.jhtsspunzw);
        this.jhtsspunzw.setBackgroundColor(Color.parseColor("#7401a5"));
        EditText editText9 = new EditText(this);
        this.lzjigwhgla = editText9;
        editText9.setLayoutParams(new LinearLayout.LayoutParams(315, 491));
        this.lzjigwhgla.setPadding(66, 78, 73, 183);
        linearLayout.addView(this.lzjigwhgla);
        this.lzjigwhgla.setBackgroundColor(Color.parseColor("#2510a0"));
        RatingBar ratingBar8 = new RatingBar(this);
        this.duawvcprmj = ratingBar8;
        ratingBar8.setLayoutParams(new LinearLayout.LayoutParams(1023, 1005));
        this.duawvcprmj.setPadding(108, 169, 50, BDLocation.TypeNetWorkLocation);
        linearLayout.addView(this.duawvcprmj);
        this.duawvcprmj.setBackgroundColor(Color.parseColor("#fcc432"));
        TimePicker timePicker13 = new TimePicker(this);
        this.zcglkmsvqi = timePicker13;
        timePicker13.setLayoutParams(new LinearLayout.LayoutParams(1777, 1002));
        this.zcglkmsvqi.setPadding(171, 20, 1, 27);
        linearLayout.addView(this.zcglkmsvqi);
        this.zcglkmsvqi.setBackgroundColor(Color.parseColor("#c46669"));
        Switch r28 = new Switch(this);
        this.qoehfcczya = r28;
        r28.setLayoutParams(new LinearLayout.LayoutParams(1747, 1431));
        this.qoehfcczya.setPadding(19, 181, 102, 129);
        linearLayout.addView(this.qoehfcczya);
        this.qoehfcczya.setBackgroundColor(Color.parseColor("#d98a6f"));
        DatePicker datePicker6 = new DatePicker(this);
        this.tgqgqjjsdk = datePicker6;
        datePicker6.setLayoutParams(new LinearLayout.LayoutParams(1688, 695));
        this.tgqgqjjsdk.setPadding(97, 125, 137, 165);
        linearLayout.addView(this.tgqgqjjsdk);
        this.tgqgqjjsdk.setBackgroundColor(Color.parseColor("#f9c385"));
        RelativeLayout relativeLayout12 = new RelativeLayout(this);
        this.ccptgqwtql = relativeLayout12;
        relativeLayout12.setLayoutParams(new LinearLayout.LayoutParams(1911, 688));
        this.ccptgqwtql.setPadding(94, 174, 154, 53);
        linearLayout.addView(this.ccptgqwtql);
        this.ccptgqwtql.setBackgroundColor(Color.parseColor("#f99997"));
        Spinner spinner5 = new Spinner(this);
        this.edarezbpic = spinner5;
        spinner5.setLayoutParams(new LinearLayout.LayoutParams(1569, BDLocation.TypeServerDecryptError));
        this.edarezbpic.setPadding(35, 101, 36, 131);
        linearLayout.addView(this.edarezbpic);
        this.edarezbpic.setBackgroundColor(Color.parseColor("#3497b1"));
        ViewFlipper viewFlipper6 = new ViewFlipper(this);
        this.ueyhmdwqzi = viewFlipper6;
        viewFlipper6.setLayoutParams(new LinearLayout.LayoutParams(58, 183));
        this.ueyhmdwqzi.setPadding(101, 108, 72, 153);
        linearLayout.addView(this.ueyhmdwqzi);
        this.ueyhmdwqzi.setBackgroundColor(Color.parseColor("#876c7d"));
        GridView gridView13 = new GridView(this);
        this.hmupsitmhq = gridView13;
        gridView13.setLayoutParams(new LinearLayout.LayoutParams(827, 1205));
        this.hmupsitmhq.setPadding(88, 119, 93, 40);
        linearLayout.addView(this.hmupsitmhq);
        this.hmupsitmhq.setBackgroundColor(Color.parseColor("#3a31a8"));
        LinearLayout linearLayout10 = new LinearLayout(this);
        this.ukgbxtcxwh = linearLayout10;
        linearLayout10.setLayoutParams(new LinearLayout.LayoutParams(1373, 1477));
        this.ukgbxtcxwh.setPadding(136, 152, 45, 148);
        linearLayout.addView(this.ukgbxtcxwh);
        this.ukgbxtcxwh.setBackgroundColor(Color.parseColor("#77a586"));
        TextView textView9 = new TextView(this);
        this.pldvykidnr = textView9;
        textView9.setLayoutParams(new LinearLayout.LayoutParams(74, 1606));
        this.pldvykidnr.setPadding(26, 50, 171, 24);
        linearLayout.addView(this.pldvykidnr);
        this.pldvykidnr.setBackgroundColor(Color.parseColor("#4cc9ef"));
        GridView gridView14 = new GridView(this);
        this.zpdnlbgocj = gridView14;
        gridView14.setLayoutParams(new LinearLayout.LayoutParams(1270, 1034));
        this.zpdnlbgocj.setPadding(98, 71, 119, BDLocation.TypeCoarseLocation);
        linearLayout.addView(this.zpdnlbgocj);
        this.zpdnlbgocj.setBackgroundColor(Color.parseColor("#0bb40d"));
        GridView gridView15 = new GridView(this);
        this.gmiyfmktsc = gridView15;
        gridView15.setLayoutParams(new LinearLayout.LayoutParams(770, 963));
        this.gmiyfmktsc.setPadding(175, 94, 36, 80);
        linearLayout.addView(this.gmiyfmktsc);
        this.gmiyfmktsc.setBackgroundColor(Color.parseColor("#ae929c"));
        CheckBox checkBox13 = new CheckBox(this);
        this.bsheyuqysb = checkBox13;
        checkBox13.setLayoutParams(new LinearLayout.LayoutParams(1560, 1859));
        this.bsheyuqysb.setPadding(185, 196, 56, 40);
        linearLayout.addView(this.bsheyuqysb);
        this.bsheyuqysb.setBackgroundColor(Color.parseColor("#026ead"));
        Switch r29 = new Switch(this);
        this.ylvwwyqism = r29;
        r29.setLayoutParams(new LinearLayout.LayoutParams(1067, 1175));
        this.ylvwwyqism.setPadding(92, 14, 106, 144);
        linearLayout.addView(this.ylvwwyqism);
        this.ylvwwyqism.setBackgroundColor(Color.parseColor("#961df0"));
        Spinner spinner6 = new Spinner(this);
        this.nqafjcsvdh = spinner6;
        spinner6.setLayoutParams(new LinearLayout.LayoutParams(141, 1686));
        this.nqafjcsvdh.setPadding(101, 72, 10, 127);
        linearLayout.addView(this.nqafjcsvdh);
        this.nqafjcsvdh.setBackgroundColor(Color.parseColor("#e1656c"));
        Spinner spinner7 = new Spinner(this);
        this.ihopvicpkf = spinner7;
        spinner7.setLayoutParams(new LinearLayout.LayoutParams(1099, 770));
        this.ihopvicpkf.setPadding(64, 86, 98, 75);
        linearLayout.addView(this.ihopvicpkf);
        this.ihopvicpkf.setBackgroundColor(Color.parseColor("#00af96"));
        ViewFlipper viewFlipper7 = new ViewFlipper(this);
        this.mjpsloxgha = viewFlipper7;
        viewFlipper7.setLayoutParams(new LinearLayout.LayoutParams(765, 227));
        this.mjpsloxgha.setPadding(53, 109, 10, 190);
        linearLayout.addView(this.mjpsloxgha);
        this.mjpsloxgha.setBackgroundColor(Color.parseColor("#81b4ef"));
        ToggleButton toggleButton14 = new ToggleButton(this);
        this.nwdkqbvbab = toggleButton14;
        toggleButton14.setLayoutParams(new LinearLayout.LayoutParams(1599, 1619));
        this.nwdkqbvbab.setPadding(32, 124, 136, 181);
        linearLayout.addView(this.nwdkqbvbab);
        this.nwdkqbvbab.setBackgroundColor(Color.parseColor("#f7ddb2"));
        LinearLayout linearLayout11 = new LinearLayout(this);
        this.tsjccdqwxq = linearLayout11;
        linearLayout11.setLayoutParams(new LinearLayout.LayoutParams(1461, 835));
        this.tsjccdqwxq.setPadding(125, 189, 94, 60);
        linearLayout.addView(this.tsjccdqwxq);
        this.tsjccdqwxq.setBackgroundColor(Color.parseColor("#78f3ff"));
        ProgressBar progressBar16 = new ProgressBar(this);
        this.rsljcqrnuv = progressBar16;
        progressBar16.setLayoutParams(new LinearLayout.LayoutParams(515, 369));
        this.rsljcqrnuv.setPadding(30, 66, 101, 90);
        linearLayout.addView(this.rsljcqrnuv);
        this.rsljcqrnuv.setBackgroundColor(Color.parseColor("#2bb623"));
    }
}
