package com.smartapp.b.osqnasdvhc;

import android.app.Activity;
import android.graphics.Color;
import android.os.Bundle;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.CheckBox;
import android.widget.DatePicker;
import android.widget.EditText;
import android.widget.FrameLayout;
import android.widget.GridView;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ListView;
import android.widget.ProgressBar;
import android.widget.RadioButton;
import android.widget.RatingBar;
import android.widget.RelativeLayout;
import android.widget.ScrollView;
import android.widget.SeekBar;
import android.widget.Spinner;
import android.widget.Switch;
import android.widget.TableLayout;
import android.widget.TextView;
import android.widget.TimePicker;
import android.widget.ToggleButton;
import android.widget.ViewFlipper;
import androidx.constraintlayout.core.motion.utils.TypedValues;
import com.baidu.location.BDLocation;
import com.luck.picture.lib.config.PictureConfig;
import com.qcwireless.qcwatch.ui.base.imagepicker.cropper.CropImage;
import com.qcwireless.qcwatch.ui.home.healthy.vm.HealthyViewModel;
import com.realsil.sdk.audioconnect.localplayback.LocalPlaybackConstants;
import com.realsil.sdk.core.bluetooth.connection.le.GattClient;
import com.realsil.sdk.core.bluetooth.impl.BluetoothClassImpl;
import okhttp3.internal.ws.WebSocketProtocol;

/* loaded from: classes4.dex */
public class MdeopyjwwzuActivity extends Activity {
    ViewFlipper abnuspjyef;
    FrameLayout adrpcluulx;
    TimePicker affntesqoh;
    EditText aflzzujggb;
    TimePicker ajvowmvchn;
    Spinner akqinxpflc;
    TableLayout asrpmzynct;
    ToggleButton bciyanegrs;
    GridView bdmagglbdp;
    FrameLayout bdqngmdcag;
    TimePicker bhqcgwwhmk;
    TextView brnfpqgzwx;
    EditText bryfmtmcws;
    ViewFlipper bsekdzoldw;
    TimePicker btuxforfmi;
    TableLayout buyghlvrkt;
    ProgressBar bxjrnrojzv;
    ProgressBar cdnaarynrj;
    ToggleButton ciuoogwlqn;
    RelativeLayout cjuozaizjj;
    TableLayout ckckmupsej;
    RatingBar cqlxjacfcg;
    ToggleButton cslezddvtj;
    TextView cwbgegvphp;
    TableLayout daqmcseqys;
    RadioButton ddoqokezhn;
    Spinner dehezplsbj;
    TimePicker dewwsuoaad;
    ListView dilmdtrqrm;
    ListView dlxwdtoztd;
    GridView doxshjyvfg;
    LinearLayout dqrwytkcqk;
    Spinner duujekshqq;
    RelativeLayout dwgtwjdgho;
    ProgressBar dwpktizczp;
    ProgressBar dxwzjrwdtn;
    Spinner egsybkdlpo;
    Button emlkkmxjrj;
    TableLayout evrkxczjab;
    Spinner eytdfyexgp;
    RatingBar fkstxjibtz;
    Button fomsciarea;
    TimePicker fshtfnnouc;
    RadioButton ftqqppdsls;
    RelativeLayout ftvltqttae;
    FrameLayout fvsyzrhvbi;
    TableLayout fywrmqtnej;
    ProgressBar gafhkaunnm;
    EditText gaxqbmnmrx;
    FrameLayout gayytrzral;
    ScrollView giruoozpgk;
    CheckBox gjadalcwed;
    ToggleButton gkcsxphlqb;
    CheckBox gmvjdjexcn;
    ViewFlipper gnqfwocghw;
    LinearLayout goupyikuzj;
    ImageView gqnfadupru;
    DatePicker gqpcwxwdcx;
    Switch gquinlbqut;
    SeekBar gyizlpayks;
    EditText hdfmyantmb;
    Spinner hkzfzlduse;
    FrameLayout hsejllgxbp;
    ImageView hsrvausdqm;
    TimePicker hsuoumereo;
    ProgressBar hwwwgelkte;
    Spinner hxbuyiulwp;
    LinearLayout hxdbvrzujo;
    ListView hxmbdunzxq;
    Switch ibvbxzxave;
    ListView ihrlnoapnp;
    Spinner ijfemlrzzl;
    GridView ijzbaljpdq;
    RadioButton ilmqdugrsy;
    RelativeLayout inkagzbgmb;
    FrameLayout ipbxlvhhru;
    LinearLayout iplcbartdz;
    ListView isdvkygeja;
    ProgressBar ismoatgmrl;
    CheckBox ivlllbxkip;
    EditText iwntjjflay;
    TimePicker iwqvfknutm;
    TextView ixovjadsrl;
    GridView jdavlghqul;
    RatingBar jdvdsdnzgu;
    ProgressBar jibnuqnbta;
    ProgressBar jirzbxqiou;
    TableLayout jjcmrcfqio;
    TimePicker jjkuzfweyx;
    TextView jkfwhiqyzj;
    LinearLayout jkvfiwhukd;
    EditText jlayutzxwa;
    RatingBar jmkwahawwm;
    GridView jolrdkoodt;
    DatePicker jowqtruaem;
    DatePicker jrxlincsit;
    Switch jrydcnhhnt;
    ProgressBar jwzalmlona;
    Button jytlryymjr;
    GridView kaakvpepqr;
    Button kbjofyyiil;
    RelativeLayout kchrokffws;
    TableLayout kemapufjop;
    GridView khcwtajpcq;
    Button kkioikahzq;
    ToggleButton kmyqmnsziv;
    ViewFlipper kpxltahpax;
    EditText kuroddqwmk;
    ViewFlipper kxzhbgrmig;
    ImageView kzipnqqeuz;
    Button ldsldpmury;
    RatingBar lginuodspd;
    LinearLayout lgplpltzyn;
    Button lkzetpdcug;
    ListView lpiabclhhx;
    ScrollView lsbvelguxx;
    Spinner lunqhttjla;
    CheckBox lykibvuaxp;
    RatingBar mfbzeocmjx;
    ToggleButton mntevdvbte;
    ProgressBar moifgkbudc;
    ToggleButton mqbywjpbdn;
    EditText mqwlalautt;
    LinearLayout mtxjzefpad;
    ListView mvbbbggzdr;
    Switch mwiwghedlh;
    ToggleButton mwkqhgjvdf;
    SeekBar mwvggupibz;
    TextView mygpgpqfix;
    Spinner njzjzlgpyd;
    TimePicker nkeyhlvrsf;
    DatePicker nqcfqngjot;
    TableLayout nqpkexlxhp;
    Spinner nrxhjwwifj;
    LinearLayout nxnbfcojgl;
    LinearLayout oblpbqgxfd;
    ProgressBar ocnhkryvtx;
    Spinner ohlxsgxkou;
    DatePicker oobspcwewn;
    ImageView oomjcjvwyj;
    RelativeLayout osoywuvorl;
    TableLayout oupuaummfs;
    ImageView ouwuzxzbqi;
    FrameLayout oziwkhzqnd;
    DatePicker pabheshqkh;
    RadioButton pdnlskhphh;
    Spinner pmlrztvlzz;
    SeekBar pmvtuguupe;
    TableLayout ppnxagqvel;
    DatePicker pqrgfpjknf;
    CheckBox pywedpogye;
    TableLayout qayvwnqtjz;
    Switch qcgnnfpmlm;
    Spinner qftjtzcjzf;
    ListView qgmksfvngj;
    TimePicker qkluojlpti;
    DatePicker qmzwollubk;
    RatingBar qnfxzzmgys;
    RadioButton qowhkcwfgo;
    ListView qrkovjkkjd;
    Button quwqkwgkvx;
    Spinner qvlflgtqfp;
    FrameLayout qvvrowpzxe;
    TableLayout rgbcvddoqg;
    ImageView rhatprdygi;
    ImageView ripvbqcxoc;
    EditText rjbbonicvw;
    LinearLayout rwfooitjyf;
    ViewFlipper ryruejplyt;
    ViewFlipper rzzwpuqewt;
    RadioButton saxwukpkxl;
    Switch sfewgdyjgu;
    TableLayout sgjxovwbrn;
    EditText sjgovbufdi;
    Button srolmylmsv;
    ImageView sxcfyfgcgi;
    TextView sxmzoiuuaa;
    Spinner szkbafaacm;
    CheckBox temafyilks;
    ToggleButton tiakcfjnmo;
    ScrollView tkhdqwbtto;
    FrameLayout ucikpbgtwz;
    ListView ucplbiercz;
    Spinner uvocdmmqcm;
    GridView uwvbqizdza;
    CheckBox vfmtkuodqe;
    ListView vjcxnypvqd;
    TableLayout vppcayemfr;
    ImageView vpwhdjrhts;
    RadioButton vqdshlmhcg;
    TableLayout vrnromkygw;
    TextView vsezypbwag;
    ListView vvbjezrgxf;
    ImageView vvtdhlqyss;
    EditText wadpjlryhm;
    RelativeLayout wcnnzmuwhh;
    TableLayout wehaekifrh;
    Switch weivjujkzp;
    RatingBar wepwjsgaaf;
    ScrollView wftdvyckbi;
    RadioButton whdqztkhun;
    DatePicker wijjpkfkoz;
    ProgressBar wkszaqqplg;
    TextView wlngryvsna;
    RelativeLayout wnepwzalkx;
    RadioButton wpbnmgncsq;
    CheckBox wstdjdvfoe;
    Spinner wupzjclvoe;
    FrameLayout wvhzgzdjnf;
    FrameLayout wvwoliagub;
    ScrollView wwuhtfyoff;
    Switch xcimvydjtv;
    Button xfawavamwp;
    TableLayout xiwgpgvoao;
    DatePicker xmonytggsr;
    Button xnjneaufhi;
    ListView xurgwepqbl;
    ImageView xvbxlddikn;
    SeekBar xvejqzbrpa;
    Spinner ydwvyoblic;
    ToggleButton yfvdcynquj;
    GridView ykimwtxrrr;
    Switch ykxfpxfyqn;
    LinearLayout yngvqsnjse;
    Button yovbqtlfnk;
    EditText yrodghztje;
    CheckBox yrwriomlzw;
    ScrollView yugmllhtqh;
    ProgressBar ywdmvuedck;
    RadioButton ywvqiiyhjv;
    TimePicker yxorsttnvm;
    LinearLayout yzxgzusfli;
    ProgressBar zdvlnmsvdp;
    RatingBar zgqjdigtei;
    DatePicker zhqmrwglzb;
    TableLayout zlsdupqigi;
    SeekBar zqahcfvmak;
    ToggleButton zusazrplae;
    Spinner zuudzkibbx;
    RelativeLayout zztbgtikep;

    @Override // android.app.Activity
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        LinearLayout linearLayout = new LinearLayout(this);
        setContentView(linearLayout);
        linearLayout.setLayoutParams(new ViewGroup.LayoutParams(-1, -1));
        linearLayout.setOrientation(1);
        linearLayout.setBackgroundColor(Color.parseColor("#ee493b"));
        TableLayout tableLayout = new TableLayout(this);
        this.rgbcvddoqg = tableLayout;
        tableLayout.setLayoutParams(new LinearLayout.LayoutParams(1225, 588));
        this.rgbcvddoqg.setPadding(8, 121, PictureConfig.CHOOSE_REQUEST, 9);
        linearLayout.addView(this.rgbcvddoqg);
        this.rgbcvddoqg.setBackgroundColor(Color.parseColor("#548fb8"));
        EditText editText = new EditText(this);
        this.yrodghztje = editText;
        editText.setLayoutParams(new LinearLayout.LayoutParams(549, 1553));
        this.yrodghztje.setPadding(83, 113, 70, 20);
        linearLayout.addView(this.yrodghztje);
        this.yrodghztje.setBackgroundColor(Color.parseColor("#3a0b1f"));
        ViewFlipper viewFlipper = new ViewFlipper(this);
        this.gnqfwocghw = viewFlipper;
        viewFlipper.setLayoutParams(new LinearLayout.LayoutParams(86, 1795));
        this.gnqfwocghw.setPadding(151, 149, 1, 0);
        linearLayout.addView(this.gnqfwocghw);
        this.gnqfwocghw.setBackgroundColor(Color.parseColor("#103f64"));
        TableLayout tableLayout2 = new TableLayout(this);
        this.vppcayemfr = tableLayout2;
        tableLayout2.setLayoutParams(new LinearLayout.LayoutParams(1989, 654));
        this.vppcayemfr.setPadding(197, 71, 112, 61);
        linearLayout.addView(this.vppcayemfr);
        this.vppcayemfr.setBackgroundColor(Color.parseColor("#c5b6cb"));
        TimePicker timePicker = new TimePicker(this);
        this.jjkuzfweyx = timePicker;
        timePicker.setLayoutParams(new LinearLayout.LayoutParams(2, 1863));
        this.jjkuzfweyx.setPadding(119, 121, 4, 49);
        linearLayout.addView(this.jjkuzfweyx);
        this.jjkuzfweyx.setBackgroundColor(Color.parseColor("#45c145"));
        Spinner spinner = new Spinner(this);
        this.wupzjclvoe = spinner;
        spinner.setLayoutParams(new LinearLayout.LayoutParams(1829, 82));
        this.wupzjclvoe.setPadding(106, 70, 194, 86);
        linearLayout.addView(this.wupzjclvoe);
        this.wupzjclvoe.setBackgroundColor(Color.parseColor("#e4c1b3"));
        ProgressBar progressBar = new ProgressBar(this);
        this.ismoatgmrl = progressBar;
        progressBar.setLayoutParams(new LinearLayout.LayoutParams(1187, 406));
        this.ismoatgmrl.setPadding(155, 118, 30, 66);
        linearLayout.addView(this.ismoatgmrl);
        this.ismoatgmrl.setBackgroundColor(Color.parseColor("#21a010"));
        Button button = new Button(this);
        this.srolmylmsv = button;
        button.setLayoutParams(new LinearLayout.LayoutParams(1945, 1448));
        this.srolmylmsv.setPadding(71, 91, 29, 185);
        linearLayout.addView(this.srolmylmsv);
        this.srolmylmsv.setBackgroundColor(Color.parseColor("#84f844"));
        TableLayout tableLayout3 = new TableLayout(this);
        this.ckckmupsej = tableLayout3;
        tableLayout3.setLayoutParams(new LinearLayout.LayoutParams(174, 1578));
        this.ckckmupsej.setPadding(2, 117, 1, 26);
        linearLayout.addView(this.ckckmupsej);
        this.ckckmupsej.setBackgroundColor(Color.parseColor("#17739d"));
        CheckBox checkBox = new CheckBox(this);
        this.gmvjdjexcn = checkBox;
        checkBox.setLayoutParams(new LinearLayout.LayoutParams(587, 1112));
        this.gmvjdjexcn.setPadding(130, 134, 53, 28);
        linearLayout.addView(this.gmvjdjexcn);
        this.gmvjdjexcn.setBackgroundColor(Color.parseColor("#e86a26"));
        DatePicker datePicker = new DatePicker(this);
        this.nqcfqngjot = datePicker;
        datePicker.setLayoutParams(new LinearLayout.LayoutParams(446, 1238));
        this.nqcfqngjot.setPadding(53, 19, 127, 35);
        linearLayout.addView(this.nqcfqngjot);
        this.nqcfqngjot.setBackgroundColor(Color.parseColor("#23876a"));
        EditText editText2 = new EditText(this);
        this.sjgovbufdi = editText2;
        editText2.setLayoutParams(new LinearLayout.LayoutParams(899, 544));
        this.sjgovbufdi.setPadding(46, 16, 85, 156);
        linearLayout.addView(this.sjgovbufdi);
        this.sjgovbufdi.setBackgroundColor(Color.parseColor("#8f5ed4"));
        RelativeLayout relativeLayout = new RelativeLayout(this);
        this.wcnnzmuwhh = relativeLayout;
        relativeLayout.setLayoutParams(new LinearLayout.LayoutParams(1323, 1558));
        this.wcnnzmuwhh.setPadding(133, 71, 31, 194);
        linearLayout.addView(this.wcnnzmuwhh);
        this.wcnnzmuwhh.setBackgroundColor(Color.parseColor("#ed47a2"));
        EditText editText3 = new EditText(this);
        this.iwntjjflay = editText3;
        editText3.setLayoutParams(new LinearLayout.LayoutParams(1678, 1691));
        this.iwntjjflay.setPadding(28, 44, 196, 60);
        linearLayout.addView(this.iwntjjflay);
        this.iwntjjflay.setBackgroundColor(Color.parseColor("#237b34"));
        ListView listView = new ListView(this);
        this.lpiabclhhx = listView;
        listView.setLayoutParams(new LinearLayout.LayoutParams(659, 1601));
        this.lpiabclhhx.setPadding(127, 192, 41, 124);
        linearLayout.addView(this.lpiabclhhx);
        this.lpiabclhhx.setBackgroundColor(Color.parseColor("#c1c135"));
        EditText editText4 = new EditText(this);
        this.rjbbonicvw = editText4;
        editText4.setLayoutParams(new LinearLayout.LayoutParams(1001, 1676));
        this.rjbbonicvw.setPadding(108, 193, 132, 37);
        linearLayout.addView(this.rjbbonicvw);
        this.rjbbonicvw.setBackgroundColor(Color.parseColor("#f5e4a3"));
        TableLayout tableLayout4 = new TableLayout(this);
        this.asrpmzynct = tableLayout4;
        tableLayout4.setLayoutParams(new LinearLayout.LayoutParams(1429, 1033));
        this.asrpmzynct.setPadding(41, 107, 6, 145);
        linearLayout.addView(this.asrpmzynct);
        this.asrpmzynct.setBackgroundColor(Color.parseColor("#358cdb"));
        TimePicker timePicker2 = new TimePicker(this);
        this.qkluojlpti = timePicker2;
        timePicker2.setLayoutParams(new LinearLayout.LayoutParams(1747, 1234));
        this.qkluojlpti.setPadding(179, 189, 182, 6);
        linearLayout.addView(this.qkluojlpti);
        this.qkluojlpti.setBackground(new Ruzkrkxyaip());
        CheckBox checkBox2 = new CheckBox(this);
        this.temafyilks = checkBox2;
        checkBox2.setLayoutParams(new LinearLayout.LayoutParams(517, 753));
        this.temafyilks.setPadding(115, 194, 34, 157);
        linearLayout.addView(this.temafyilks);
        this.temafyilks.setBackgroundColor(Color.parseColor("#76ee8f"));
        TableLayout tableLayout5 = new TableLayout(this);
        this.sgjxovwbrn = tableLayout5;
        tableLayout5.setLayoutParams(new LinearLayout.LayoutParams(105, GattClient.STATE_PREPARE_CONNECTING));
        this.sgjxovwbrn.setPadding(149, 154, 184, 89);
        linearLayout.addView(this.sgjxovwbrn);
        this.sgjxovwbrn.setBackgroundColor(Color.parseColor("#abffce"));
        GridView gridView = new GridView(this);
        this.khcwtajpcq = gridView;
        gridView.setLayoutParams(new LinearLayout.LayoutParams(1564, 1076));
        this.khcwtajpcq.setPadding(9, 195, 118, 83);
        linearLayout.addView(this.khcwtajpcq);
        this.khcwtajpcq.setBackgroundColor(Color.parseColor("#e83964"));
        LinearLayout linearLayout2 = new LinearLayout(this);
        this.yngvqsnjse = linearLayout2;
        linearLayout2.setLayoutParams(new LinearLayout.LayoutParams(1708, 158));
        this.yngvqsnjse.setPadding(17, 53, 39, 76);
        linearLayout.addView(this.yngvqsnjse);
        this.yngvqsnjse.setBackgroundColor(Color.parseColor("#85ad70"));
        CheckBox checkBox3 = new CheckBox(this);
        this.lykibvuaxp = checkBox3;
        checkBox3.setLayoutParams(new LinearLayout.LayoutParams(1220, 1958));
        this.lykibvuaxp.setPadding(135, 1, 66, 84);
        linearLayout.addView(this.lykibvuaxp);
        this.lykibvuaxp.setBackgroundColor(Color.parseColor("#ba5558"));
        TableLayout tableLayout6 = new TableLayout(this);
        this.jjcmrcfqio = tableLayout6;
        tableLayout6.setLayoutParams(new LinearLayout.LayoutParams(231, 1563));
        this.jjcmrcfqio.setPadding(100, 139, 157, 25);
        linearLayout.addView(this.jjcmrcfqio);
        this.jjcmrcfqio.setBackgroundColor(Color.parseColor("#ffdcf6"));
        LinearLayout linearLayout3 = new LinearLayout(this);
        this.jkvfiwhukd = linearLayout3;
        linearLayout3.setLayoutParams(new LinearLayout.LayoutParams(1172, 1460));
        this.jkvfiwhukd.setPadding(176, 184, 51, 117);
        linearLayout.addView(this.jkvfiwhukd);
        this.jkvfiwhukd.setBackgroundColor(Color.parseColor("#8d74f0"));
        RelativeLayout relativeLayout2 = new RelativeLayout(this);
        this.osoywuvorl = relativeLayout2;
        relativeLayout2.setLayoutParams(new LinearLayout.LayoutParams(1291, 1120));
        this.osoywuvorl.setPadding(196, 176, 142, 122);
        linearLayout.addView(this.osoywuvorl);
        this.osoywuvorl.setBackgroundColor(Color.parseColor("#c909f4"));
        RatingBar ratingBar = new RatingBar(this);
        this.wepwjsgaaf = ratingBar;
        ratingBar.setLayoutParams(new LinearLayout.LayoutParams(758, 1139));
        this.wepwjsgaaf.setPadding(10, 154, 30, 154);
        linearLayout.addView(this.wepwjsgaaf);
        this.wepwjsgaaf.setBackgroundColor(Color.parseColor("#48bc49"));
        ToggleButton toggleButton = new ToggleButton(this);
        this.kmyqmnsziv = toggleButton;
        toggleButton.setLayoutParams(new LinearLayout.LayoutParams(140, 1031));
        this.kmyqmnsziv.setPadding(157, 71, 191, 48);
        linearLayout.addView(this.kmyqmnsziv);
        this.kmyqmnsziv.setBackgroundColor(Color.parseColor("#ced9f2"));
        DatePicker datePicker2 = new DatePicker(this);
        this.xmonytggsr = datePicker2;
        datePicker2.setLayoutParams(new LinearLayout.LayoutParams(1208, 405));
        this.xmonytggsr.setPadding(140, 77, 97, 157);
        linearLayout.addView(this.xmonytggsr);
        this.xmonytggsr.setBackgroundColor(Color.parseColor("#69a873"));
        RadioButton radioButton = new RadioButton(this);
        this.whdqztkhun = radioButton;
        radioButton.setLayoutParams(new LinearLayout.LayoutParams(1663, 7));
        this.whdqztkhun.setPadding(147, 146, 57, 31);
        linearLayout.addView(this.whdqztkhun);
        this.whdqztkhun.setBackgroundColor(Color.parseColor("#c8416d"));
        Spinner spinner2 = new Spinner(this);
        this.duujekshqq = spinner2;
        spinner2.setLayoutParams(new LinearLayout.LayoutParams(GattClient.STATE_PREPARE_PAIRING_REQUEST, 51));
        this.duujekshqq.setPadding(122, 90, 14, 109);
        linearLayout.addView(this.duujekshqq);
        this.duujekshqq.setBackgroundColor(Color.parseColor("#220e3d"));
        ImageView imageView = new ImageView(this);
        this.sxcfyfgcgi = imageView;
        imageView.setLayoutParams(new LinearLayout.LayoutParams(346, 286));
        this.sxcfyfgcgi.setPadding(6, 118, 6, 128);
        linearLayout.addView(this.sxcfyfgcgi);
        this.sxcfyfgcgi.setBackgroundColor(Color.parseColor("#6d4116"));
        Button button2 = new Button(this);
        this.ldsldpmury = button2;
        button2.setLayoutParams(new LinearLayout.LayoutParams(1858, 835));
        this.ldsldpmury.setPadding(181, 146, 48, 190);
        linearLayout.addView(this.ldsldpmury);
        this.ldsldpmury.setBackgroundColor(Color.parseColor("#01781a"));
        ListView listView2 = new ListView(this);
        this.isdvkygeja = listView2;
        listView2.setLayoutParams(new LinearLayout.LayoutParams(968, 550));
        this.isdvkygeja.setPadding(92, 27, 99, 145);
        linearLayout.addView(this.isdvkygeja);
        this.isdvkygeja.setBackgroundColor(Color.parseColor("#d15b61"));
        LinearLayout linearLayout4 = new LinearLayout(this);
        this.mtxjzefpad = linearLayout4;
        linearLayout4.setLayoutParams(new LinearLayout.LayoutParams(830, BDLocation.TypeServerDecryptError));
        this.mtxjzefpad.setPadding(156, BDLocation.TypeServerDecryptError, 76, 127);
        linearLayout.addView(this.mtxjzefpad);
        this.mtxjzefpad.setBackgroundColor(Color.parseColor("#fb558a"));
        Spinner spinner3 = new Spinner(this);
        this.lunqhttjla = spinner3;
        spinner3.setLayoutParams(new LinearLayout.LayoutParams(1779, 1187));
        this.lunqhttjla.setPadding(155, BDLocation.TypeCoarseLocation, WebSocketProtocol.PAYLOAD_SHORT, 69);
        linearLayout.addView(this.lunqhttjla);
        this.lunqhttjla.setBackgroundColor(Color.parseColor("#c3c633"));
        RadioButton radioButton2 = new RadioButton(this);
        this.qowhkcwfgo = radioButton2;
        radioButton2.setLayoutParams(new LinearLayout.LayoutParams(1949, 153));
        this.qowhkcwfgo.setPadding(150, 31, 2, 53);
        linearLayout.addView(this.qowhkcwfgo);
        this.qowhkcwfgo.setBackgroundColor(Color.parseColor("#8c8821"));
        RadioButton radioButton3 = new RadioButton(this);
        this.ilmqdugrsy = radioButton3;
        radioButton3.setLayoutParams(new LinearLayout.LayoutParams(1192, 786));
        this.ilmqdugrsy.setPadding(84, 114, 46, 41);
        linearLayout.addView(this.ilmqdugrsy);
        this.ilmqdugrsy.setBackgroundColor(Color.parseColor("#7182ca"));
        Spinner spinner4 = new Spinner(this);
        this.szkbafaacm = spinner4;
        spinner4.setLayoutParams(new LinearLayout.LayoutParams(853, 1851));
        this.szkbafaacm.setPadding(38, 9, BDLocation.TypeServerDecryptError, 51);
        linearLayout.addView(this.szkbafaacm);
        this.szkbafaacm.setBackgroundColor(Color.parseColor("#59def3"));
        SeekBar seekBar = new SeekBar(this);
        this.xvejqzbrpa = seekBar;
        seekBar.setLayoutParams(new LinearLayout.LayoutParams(1784, 1931));
        this.xvejqzbrpa.setPadding(146, 196, 14, 91);
        linearLayout.addView(this.xvejqzbrpa);
        this.xvejqzbrpa.setBackgroundColor(Color.parseColor("#0e27b6"));
        ImageView imageView2 = new ImageView(this);
        this.ouwuzxzbqi = imageView2;
        imageView2.setLayoutParams(new LinearLayout.LayoutParams(1968, 788));
        this.ouwuzxzbqi.setPadding(175, 195, 40, 76);
        linearLayout.addView(this.ouwuzxzbqi);
        this.ouwuzxzbqi.setBackgroundColor(Color.parseColor("#692a86"));
        SeekBar seekBar2 = new SeekBar(this);
        this.mwvggupibz = seekBar2;
        seekBar2.setLayoutParams(new LinearLayout.LayoutParams(322, 1326));
        this.mwvggupibz.setPadding(41, 191, 106, 84);
        linearLayout.addView(this.mwvggupibz);
        this.mwvggupibz.setBackgroundColor(Color.parseColor("#286f62"));
        Spinner spinner5 = new Spinner(this);
        this.uvocdmmqcm = spinner5;
        spinner5.setLayoutParams(new LinearLayout.LayoutParams(615, 218));
        this.uvocdmmqcm.setPadding(158, 47, 1, 174);
        linearLayout.addView(this.uvocdmmqcm);
        this.uvocdmmqcm.setBackgroundColor(Color.parseColor("#394d8a"));
        Spinner spinner6 = new Spinner(this);
        this.ijfemlrzzl = spinner6;
        spinner6.setLayoutParams(new LinearLayout.LayoutParams(1898, 936));
        this.ijfemlrzzl.setPadding(17, 82, 145, 189);
        linearLayout.addView(this.ijfemlrzzl);
        this.ijfemlrzzl.setBackgroundColor(Color.parseColor("#53fbd9"));
        ToggleButton toggleButton2 = new ToggleButton(this);
        this.yfvdcynquj = toggleButton2;
        toggleButton2.setLayoutParams(new LinearLayout.LayoutParams(695, 781));
        this.yfvdcynquj.setPadding(179, 85, 52, 31);
        linearLayout.addView(this.yfvdcynquj);
        this.yfvdcynquj.setBackgroundColor(Color.parseColor("#99f5ad"));
        ProgressBar progressBar2 = new ProgressBar(this);
        this.dxwzjrwdtn = progressBar2;
        progressBar2.setLayoutParams(new LinearLayout.LayoutParams(1429, 1117));
        this.dxwzjrwdtn.setPadding(97, 113, 122, 164);
        linearLayout.addView(this.dxwzjrwdtn);
        this.dxwzjrwdtn.setBackgroundColor(Color.parseColor("#433b5c"));
        ProgressBar progressBar3 = new ProgressBar(this);
        this.jwzalmlona = progressBar3;
        progressBar3.setLayoutParams(new LinearLayout.LayoutParams(1789, 1209));
        this.jwzalmlona.setPadding(8, 52, 155, 90);
        linearLayout.addView(this.jwzalmlona);
        this.jwzalmlona.setBackgroundColor(Color.parseColor("#0a83b5"));
        Button button3 = new Button(this);
        this.kbjofyyiil = button3;
        button3.setLayoutParams(new LinearLayout.LayoutParams(1803, 1998));
        this.kbjofyyiil.setPadding(77, 136, 0, 175);
        linearLayout.addView(this.kbjofyyiil);
        this.kbjofyyiil.setBackgroundColor(Color.parseColor("#f39a99"));
        Switch r2 = new Switch(this);
        this.jrydcnhhnt = r2;
        r2.setLayoutParams(new LinearLayout.LayoutParams(1353, 834));
        this.jrydcnhhnt.setPadding(1, 125, 176, 114);
        linearLayout.addView(this.jrydcnhhnt);
        this.jrydcnhhnt.setBackgroundColor(Color.parseColor("#a04679"));
        TimePicker timePicker3 = new TimePicker(this);
        this.iwqvfknutm = timePicker3;
        timePicker3.setLayoutParams(new LinearLayout.LayoutParams(1124, 195));
        this.iwqvfknutm.setPadding(17, 80, 142, 190);
        linearLayout.addView(this.iwqvfknutm);
        this.iwqvfknutm.setBackgroundColor(Color.parseColor("#08484d"));
        Switch r22 = new Switch(this);
        this.qcgnnfpmlm = r22;
        r22.setLayoutParams(new LinearLayout.LayoutParams(255, TypedValues.CycleType.TYPE_CUSTOM_WAVE_SHAPE));
        this.qcgnnfpmlm.setPadding(35, 118, 89, 36);
        linearLayout.addView(this.qcgnnfpmlm);
        this.qcgnnfpmlm.setBackgroundColor(Color.parseColor("#2a646a"));
        ImageView imageView3 = new ImageView(this);
        this.gqnfadupru = imageView3;
        imageView3.setLayoutParams(new LinearLayout.LayoutParams(1420, 1809));
        this.gqnfadupru.setPadding(4, 56, 12, 140);
        linearLayout.addView(this.gqnfadupru);
        this.gqnfadupru.setBackgroundColor(Color.parseColor("#019258"));
        Button button4 = new Button(this);
        this.lkzetpdcug = button4;
        button4.setLayoutParams(new LinearLayout.LayoutParams(1906, 141));
        this.lkzetpdcug.setPadding(142, 75, 5, 64);
        linearLayout.addView(this.lkzetpdcug);
        this.lkzetpdcug.setBackgroundColor(Color.parseColor("#ee06f4"));
        TableLayout tableLayout7 = new TableLayout(this);
        this.fywrmqtnej = tableLayout7;
        tableLayout7.setLayoutParams(new LinearLayout.LayoutParams(96, 1956));
        this.fywrmqtnej.setPadding(79, 115, 41, 37);
        linearLayout.addView(this.fywrmqtnej);
        this.fywrmqtnej.setBackgroundColor(Color.parseColor("#cd22c6"));
        ScrollView scrollView = new ScrollView(this);
        this.wwuhtfyoff = scrollView;
        scrollView.setLayoutParams(new LinearLayout.LayoutParams(1544, 826));
        this.wwuhtfyoff.setPadding(124, 101, 36, 7);
        linearLayout.addView(this.wwuhtfyoff);
        this.wwuhtfyoff.setBackgroundColor(Color.parseColor("#845cba"));
        Spinner spinner7 = new Spinner(this);
        this.akqinxpflc = spinner7;
        spinner7.setLayoutParams(new LinearLayout.LayoutParams(320, 723));
        this.akqinxpflc.setPadding(196, 103, BDLocation.TypeCoarseLocation, 56);
        linearLayout.addView(this.akqinxpflc);
        this.akqinxpflc.setBackgroundColor(Color.parseColor("#428e21"));
        EditText editText5 = new EditText(this);
        this.aflzzujggb = editText5;
        editText5.setLayoutParams(new LinearLayout.LayoutParams(1690, 1482));
        this.aflzzujggb.setPadding(152, 157, 92, 148);
        linearLayout.addView(this.aflzzujggb);
        this.aflzzujggb.setBackgroundColor(Color.parseColor("#106d60"));
        SeekBar seekBar3 = new SeekBar(this);
        this.zqahcfvmak = seekBar3;
        seekBar3.setLayoutParams(new LinearLayout.LayoutParams(1179, 1330));
        this.zqahcfvmak.setPadding(71, 123, 116, 84);
        linearLayout.addView(this.zqahcfvmak);
        this.zqahcfvmak.setBackgroundColor(Color.parseColor("#841374"));
        GridView gridView2 = new GridView(this);
        this.ijzbaljpdq = gridView2;
        gridView2.setLayoutParams(new LinearLayout.LayoutParams(1457, 1475));
        this.ijzbaljpdq.setPadding(144, 49, 23, 134);
        linearLayout.addView(this.ijzbaljpdq);
        this.ijzbaljpdq.setBackgroundColor(Color.parseColor("#8e8900"));
        Spinner spinner8 = new Spinner(this);
        this.dehezplsbj = spinner8;
        spinner8.setLayoutParams(new LinearLayout.LayoutParams(1991, 74));
        this.dehezplsbj.setPadding(153, 30, 44, 37);
        linearLayout.addView(this.dehezplsbj);
        this.dehezplsbj.setBackgroundColor(Color.parseColor("#1e7e5a"));
        TableLayout tableLayout8 = new TableLayout(this);
        this.buyghlvrkt = tableLayout8;
        tableLayout8.setLayoutParams(new LinearLayout.LayoutParams(843, 1509));
        this.buyghlvrkt.setPadding(132, 149, 47, 99);
        linearLayout.addView(this.buyghlvrkt);
        this.buyghlvrkt.setBackgroundColor(Color.parseColor("#abec7a"));
        Spinner spinner9 = new Spinner(this);
        this.zuudzkibbx = spinner9;
        spinner9.setLayoutParams(new LinearLayout.LayoutParams(1143, 33));
        this.zuudzkibbx.setPadding(168, 5, 0, 88);
        linearLayout.addView(this.zuudzkibbx);
        this.zuudzkibbx.setBackgroundColor(Color.parseColor("#7841b5"));
        ToggleButton toggleButton3 = new ToggleButton(this);
        this.cslezddvtj = toggleButton3;
        toggleButton3.setLayoutParams(new LinearLayout.LayoutParams(804, 1610));
        this.cslezddvtj.setPadding(85, 177, 35, 141);
        linearLayout.addView(this.cslezddvtj);
        this.cslezddvtj.setBackgroundColor(Color.parseColor("#d5ae22"));
        ImageView imageView4 = new ImageView(this);
        this.ripvbqcxoc = imageView4;
        imageView4.setLayoutParams(new LinearLayout.LayoutParams(1026, 375));
        this.ripvbqcxoc.setPadding(1, 53, 122, 121);
        linearLayout.addView(this.ripvbqcxoc);
        this.ripvbqcxoc.setBackgroundColor(Color.parseColor("#66719e"));
        Button button5 = new Button(this);
        this.quwqkwgkvx = button5;
        button5.setLayoutParams(new LinearLayout.LayoutParams(782, 616));
        this.quwqkwgkvx.setPadding(151, 56, 159, 143);
        linearLayout.addView(this.quwqkwgkvx);
        this.quwqkwgkvx.setBackgroundColor(Color.parseColor("#fb1731"));
        TableLayout tableLayout9 = new TableLayout(this);
        this.daqmcseqys = tableLayout9;
        tableLayout9.setLayoutParams(new LinearLayout.LayoutParams(1347, 389));
        this.daqmcseqys.setPadding(135, 179, 159, 194);
        linearLayout.addView(this.daqmcseqys);
        this.daqmcseqys.setBackgroundColor(Color.parseColor("#54495f"));
        ProgressBar progressBar4 = new ProgressBar(this);
        this.jibnuqnbta = progressBar4;
        progressBar4.setLayoutParams(new LinearLayout.LayoutParams(218, 1948));
        this.jibnuqnbta.setPadding(136, 69, 25, 87);
        linearLayout.addView(this.jibnuqnbta);
        this.jibnuqnbta.setBackgroundColor(Color.parseColor("#d68a13"));
        DatePicker datePicker3 = new DatePicker(this);
        this.pabheshqkh = datePicker3;
        datePicker3.setLayoutParams(new LinearLayout.LayoutParams(373, 1311));
        this.pabheshqkh.setPadding(170, 97, 4, 198);
        linearLayout.addView(this.pabheshqkh);
        this.pabheshqkh.setBackgroundColor(Color.parseColor("#a8bd76"));
        EditText editText6 = new EditText(this);
        this.hdfmyantmb = editText6;
        editText6.setLayoutParams(new LinearLayout.LayoutParams(236, 288));
        this.hdfmyantmb.setPadding(104, 94, 111, 148);
        linearLayout.addView(this.hdfmyantmb);
        this.hdfmyantmb.setBackgroundColor(Color.parseColor("#03d8b5"));
        DatePicker datePicker4 = new DatePicker(this);
        this.qmzwollubk = datePicker4;
        datePicker4.setLayoutParams(new LinearLayout.LayoutParams(579, 961));
        this.qmzwollubk.setPadding(34, 59, 106, 192);
        linearLayout.addView(this.qmzwollubk);
        this.qmzwollubk.setBackgroundColor(Color.parseColor("#631149"));
        RatingBar ratingBar2 = new RatingBar(this);
        this.mfbzeocmjx = ratingBar2;
        ratingBar2.setLayoutParams(new LinearLayout.LayoutParams(1836, 1492));
        this.mfbzeocmjx.setPadding(7, 148, 66, 135);
        linearLayout.addView(this.mfbzeocmjx);
        this.mfbzeocmjx.setBackgroundColor(Color.parseColor("#de3085"));
        LinearLayout linearLayout5 = new LinearLayout(this);
        this.nxnbfcojgl = linearLayout5;
        linearLayout5.setLayoutParams(new LinearLayout.LayoutParams(847, 1317));
        this.nxnbfcojgl.setPadding(34, 20, 83, 103);
        linearLayout.addView(this.nxnbfcojgl);
        this.nxnbfcojgl.setBackgroundColor(Color.parseColor("#940e16"));
        RatingBar ratingBar3 = new RatingBar(this);
        this.zgqjdigtei = ratingBar3;
        ratingBar3.setLayoutParams(new LinearLayout.LayoutParams(1745, 1063));
        this.zgqjdigtei.setPadding(187, BDLocation.TypeCoarseLocation, 166, 21);
        linearLayout.addView(this.zgqjdigtei);
        this.zgqjdigtei.setBackgroundColor(Color.parseColor("#b6881e"));
        ProgressBar progressBar5 = new ProgressBar(this);
        this.ywdmvuedck = progressBar5;
        progressBar5.setLayoutParams(new LinearLayout.LayoutParams(1976, 26));
        this.ywdmvuedck.setPadding(158, 68, 83, 12);
        linearLayout.addView(this.ywdmvuedck);
        this.ywdmvuedck.setBackgroundColor(Color.parseColor("#6a97f4"));
        ListView listView3 = new ListView(this);
        this.mvbbbggzdr = listView3;
        listView3.setLayoutParams(new LinearLayout.LayoutParams(788, 1822));
        this.mvbbbggzdr.setPadding(48, 62, 185, 147);
        linearLayout.addView(this.mvbbbggzdr);
        this.mvbbbggzdr.setBackgroundColor(Color.parseColor("#e95adc"));
        DatePicker datePicker5 = new DatePicker(this);
        this.jrxlincsit = datePicker5;
        datePicker5.setLayoutParams(new LinearLayout.LayoutParams(1219, 1580));
        this.jrxlincsit.setPadding(133, 21, 0, 80);
        linearLayout.addView(this.jrxlincsit);
        this.jrxlincsit.setBackgroundColor(Color.parseColor("#4217fd"));
        ToggleButton toggleButton4 = new ToggleButton(this);
        this.tiakcfjnmo = toggleButton4;
        toggleButton4.setLayoutParams(new LinearLayout.LayoutParams(468, 266));
        this.tiakcfjnmo.setPadding(134, PictureConfig.CHOOSE_REQUEST, 152, 199);
        linearLayout.addView(this.tiakcfjnmo);
        this.tiakcfjnmo.setBackgroundColor(Color.parseColor("#847d23"));
        FrameLayout frameLayout = new FrameLayout(this);
        this.ucikpbgtwz = frameLayout;
        frameLayout.setLayoutParams(new LinearLayout.LayoutParams(1171, BDLocation.TypeNetWorkLocation));
        this.ucikpbgtwz.setPadding(144, 168, 35, 138);
        linearLayout.addView(this.ucikpbgtwz);
        this.ucikpbgtwz.setBackgroundColor(Color.parseColor("#1594c4"));
        TableLayout tableLayout10 = new TableLayout(this);
        this.evrkxczjab = tableLayout10;
        tableLayout10.setLayoutParams(new LinearLayout.LayoutParams(988, 1637));
        this.evrkxczjab.setPadding(72, 58, 30, 99);
        linearLayout.addView(this.evrkxczjab);
        this.evrkxczjab.setBackgroundColor(Color.parseColor("#7c8dbe"));
        TimePicker timePicker4 = new TimePicker(this);
        this.ajvowmvchn = timePicker4;
        timePicker4.setLayoutParams(new LinearLayout.LayoutParams(1681, 1048));
        this.ajvowmvchn.setPadding(1, 18, 110, 13);
        linearLayout.addView(this.ajvowmvchn);
        this.ajvowmvchn.setBackgroundColor(Color.parseColor("#f3fc08"));
        RatingBar ratingBar4 = new RatingBar(this);
        this.jmkwahawwm = ratingBar4;
        ratingBar4.setLayoutParams(new LinearLayout.LayoutParams(1711, 1620));
        this.jmkwahawwm.setPadding(95, 90, 181, 20);
        linearLayout.addView(this.jmkwahawwm);
        this.jmkwahawwm.setBackgroundColor(Color.parseColor("#214bb3"));
        ListView listView4 = new ListView(this);
        this.vvbjezrgxf = listView4;
        listView4.setLayoutParams(new LinearLayout.LayoutParams(1398, 187));
        this.vvbjezrgxf.setPadding(118, 43, 108, 101);
        linearLayout.addView(this.vvbjezrgxf);
        this.vvbjezrgxf.setBackgroundColor(Color.parseColor("#31f6b7"));
        TimePicker timePicker5 = new TimePicker(this);
        this.fshtfnnouc = timePicker5;
        timePicker5.setLayoutParams(new LinearLayout.LayoutParams(1774, 613));
        this.fshtfnnouc.setPadding(52, 152, 148, 190);
        linearLayout.addView(this.fshtfnnouc);
        this.fshtfnnouc.setBackgroundColor(Color.parseColor("#49204a"));
        RadioButton radioButton4 = new RadioButton(this);
        this.wpbnmgncsq = radioButton4;
        radioButton4.setLayoutParams(new LinearLayout.LayoutParams(1676, 509));
        this.wpbnmgncsq.setPadding(20, 148, 5, 154);
        linearLayout.addView(this.wpbnmgncsq);
        this.wpbnmgncsq.setBackgroundColor(Color.parseColor("#da4461"));
        LinearLayout linearLayout6 = new LinearLayout(this);
        this.iplcbartdz = linearLayout6;
        linearLayout6.setLayoutParams(new LinearLayout.LayoutParams(108, 1729));
        this.iplcbartdz.setPadding(124, 73, 8, 72);
        linearLayout.addView(this.iplcbartdz);
        this.iplcbartdz.setBackgroundColor(Color.parseColor("#dfb55a"));
        TextView textView = new TextView(this);
        this.vsezypbwag = textView;
        textView.setLayoutParams(new LinearLayout.LayoutParams(514, 252));
        this.vsezypbwag.setPadding(181, BDLocation.TypeCoarseLocation, 152, BDLocation.TypeNetWorkLocation);
        linearLayout.addView(this.vsezypbwag);
        this.vsezypbwag.setBackgroundColor(Color.parseColor("#6fa3cc"));
        TableLayout tableLayout11 = new TableLayout(this);
        this.zlsdupqigi = tableLayout11;
        tableLayout11.setLayoutParams(new LinearLayout.LayoutParams(1105, 1865));
        this.zlsdupqigi.setPadding(121, 31, 27, 77);
        linearLayout.addView(this.zlsdupqigi);
        this.zlsdupqigi.setBackgroundColor(Color.parseColor("#0d0775"));
        ListView listView5 = new ListView(this);
        this.ihrlnoapnp = listView5;
        listView5.setLayoutParams(new LinearLayout.LayoutParams(1653, 1662));
        this.ihrlnoapnp.setPadding(139, 75, BDLocation.TypeServerError, 9);
        linearLayout.addView(this.ihrlnoapnp);
        this.ihrlnoapnp.setBackgroundColor(Color.parseColor("#7134b7"));
        TextView textView2 = new TextView(this);
        this.brnfpqgzwx = textView2;
        textView2.setLayoutParams(new LinearLayout.LayoutParams(1525, 1371));
        this.brnfpqgzwx.setPadding(80, 50, 192, 39);
        linearLayout.addView(this.brnfpqgzwx);
        this.brnfpqgzwx.setBackgroundColor(Color.parseColor("#4477cf"));
        DatePicker datePicker6 = new DatePicker(this);
        this.jowqtruaem = datePicker6;
        datePicker6.setLayoutParams(new LinearLayout.LayoutParams(1368, 1158));
        this.jowqtruaem.setPadding(12, 148, 143, 178);
        linearLayout.addView(this.jowqtruaem);
        this.jowqtruaem.setBackgroundColor(Color.parseColor("#4326b4"));
        ViewFlipper viewFlipper2 = new ViewFlipper(this);
        this.abnuspjyef = viewFlipper2;
        viewFlipper2.setLayoutParams(new LinearLayout.LayoutParams(177, 989));
        this.abnuspjyef.setPadding(14, BDLocation.TypeServerError, 141, 156);
        linearLayout.addView(this.abnuspjyef);
        this.abnuspjyef.setBackgroundColor(Color.parseColor("#356942"));
        TableLayout tableLayout12 = new TableLayout(this);
        this.vrnromkygw = tableLayout12;
        tableLayout12.setLayoutParams(new LinearLayout.LayoutParams(14, 1087));
        this.vrnromkygw.setPadding(117, 92, 110, 102);
        linearLayout.addView(this.vrnromkygw);
        this.vrnromkygw.setBackgroundColor(Color.parseColor("#d49045"));
        FrameLayout frameLayout2 = new FrameLayout(this);
        this.fvsyzrhvbi = frameLayout2;
        frameLayout2.setLayoutParams(new LinearLayout.LayoutParams(82, 1231));
        this.fvsyzrhvbi.setPadding(179, 147, 89, 3);
        linearLayout.addView(this.fvsyzrhvbi);
        this.fvsyzrhvbi.setBackgroundColor(Color.parseColor("#7437f3"));
        ListView listView6 = new ListView(this);
        this.vjcxnypvqd = listView6;
        listView6.setLayoutParams(new LinearLayout.LayoutParams(CropImage.CROP_IMAGE_ACTIVITY_REQUEST_CODE, 878));
        this.vjcxnypvqd.setPadding(143, 23, 60, 10);
        linearLayout.addView(this.vjcxnypvqd);
        this.vjcxnypvqd.setBackgroundColor(Color.parseColor("#146e9e"));
        ScrollView scrollView2 = new ScrollView(this);
        this.lsbvelguxx = scrollView2;
        scrollView2.setLayoutParams(new LinearLayout.LayoutParams(1446, 411));
        this.lsbvelguxx.setPadding(169, 31, 36, 191);
        linearLayout.addView(this.lsbvelguxx);
        this.lsbvelguxx.setBackgroundColor(Color.parseColor("#24e84f"));
        LinearLayout linearLayout7 = new LinearLayout(this);
        this.goupyikuzj = linearLayout7;
        linearLayout7.setLayoutParams(new LinearLayout.LayoutParams(1479, 146));
        this.goupyikuzj.setPadding(21, 193, 147, 149);
        linearLayout.addView(this.goupyikuzj);
        this.goupyikuzj.setBackgroundColor(Color.parseColor("#57b11f"));
        ImageView imageView5 = new ImageView(this);
        this.oomjcjvwyj = imageView5;
        imageView5.setLayoutParams(new LinearLayout.LayoutParams(734, 887));
        this.oomjcjvwyj.setPadding(186, 92, 163, 178);
        linearLayout.addView(this.oomjcjvwyj);
        this.oomjcjvwyj.setBackgroundColor(Color.parseColor("#37b7ac"));
        ListView listView7 = new ListView(this);
        this.dilmdtrqrm = listView7;
        listView7.setLayoutParams(new LinearLayout.LayoutParams(795, 454));
        this.dilmdtrqrm.setPadding(132, 50, 135, WebSocketProtocol.PAYLOAD_SHORT);
        linearLayout.addView(this.dilmdtrqrm);
        this.dilmdtrqrm.setBackgroundColor(Color.parseColor("#70c04f"));
        RelativeLayout relativeLayout3 = new RelativeLayout(this);
        this.kchrokffws = relativeLayout3;
        relativeLayout3.setLayoutParams(new LinearLayout.LayoutParams(1802, BDLocation.TypeNetWorkLocation));
        this.kchrokffws.setPadding(29, 190, 50, 153);
        linearLayout.addView(this.kchrokffws);
        this.kchrokffws.setBackgroundColor(Color.parseColor("#96a8de"));
        TextView textView3 = new TextView(this);
        this.cwbgegvphp = textView3;
        textView3.setLayoutParams(new LinearLayout.LayoutParams(1491, 429));
        this.cwbgegvphp.setPadding(82, 1, 199, 137);
        linearLayout.addView(this.cwbgegvphp);
        this.cwbgegvphp.setBackgroundColor(Color.parseColor("#32119f"));
        RelativeLayout relativeLayout4 = new RelativeLayout(this);
        this.wnepwzalkx = relativeLayout4;
        relativeLayout4.setLayoutParams(new LinearLayout.LayoutParams(1377, 1584));
        this.wnepwzalkx.setPadding(26, PictureConfig.CHOOSE_REQUEST, 24, 13);
        linearLayout.addView(this.wnepwzalkx);
        this.wnepwzalkx.setBackgroundColor(Color.parseColor("#d3aa22"));
        TableLayout tableLayout13 = new TableLayout(this);
        this.nqpkexlxhp = tableLayout13;
        tableLayout13.setLayoutParams(new LinearLayout.LayoutParams(27, 1107));
        this.nqpkexlxhp.setPadding(40, 154, 27, 73);
        linearLayout.addView(this.nqpkexlxhp);
        this.nqpkexlxhp.setBackgroundColor(Color.parseColor("#42c0f1"));
        ProgressBar progressBar6 = new ProgressBar(this);
        this.hwwwgelkte = progressBar6;
        progressBar6.setLayoutParams(new LinearLayout.LayoutParams(1655, 1960));
        this.hwwwgelkte.setPadding(65, 189, 103, 158);
        linearLayout.addView(this.hwwwgelkte);
        this.hwwwgelkte.setBackgroundColor(Color.parseColor("#fe19ed"));
        ScrollView scrollView3 = new ScrollView(this);
        this.wftdvyckbi = scrollView3;
        scrollView3.setLayoutParams(new LinearLayout.LayoutParams(1395, 529));
        this.wftdvyckbi.setPadding(178, 115, 84, 45);
        linearLayout.addView(this.wftdvyckbi);
        this.wftdvyckbi.setBackgroundColor(Color.parseColor("#c31ec8"));
        EditText editText7 = new EditText(this);
        this.mqwlalautt = editText7;
        editText7.setLayoutParams(new LinearLayout.LayoutParams(1686, 1653));
        this.mqwlalautt.setPadding(112, 147, 145, 153);
        linearLayout.addView(this.mqwlalautt);
        this.mqwlalautt.setBackgroundColor(Color.parseColor("#7ed004"));
        ProgressBar progressBar7 = new ProgressBar(this);
        this.zdvlnmsvdp = progressBar7;
        progressBar7.setLayoutParams(new LinearLayout.LayoutParams(1595, 1991));
        this.zdvlnmsvdp.setPadding(74, 1, 176, 6);
        linearLayout.addView(this.zdvlnmsvdp);
        this.zdvlnmsvdp.setBackgroundColor(Color.parseColor("#62965f"));
        ProgressBar progressBar8 = new ProgressBar(this);
        this.ocnhkryvtx = progressBar8;
        progressBar8.setLayoutParams(new LinearLayout.LayoutParams(86, PictureConfig.REQUEST_GO_SETTING));
        this.ocnhkryvtx.setPadding(99, 19, 189, 58);
        linearLayout.addView(this.ocnhkryvtx);
        this.ocnhkryvtx.setBackgroundColor(Color.parseColor("#113e64"));
        ImageView imageView6 = new ImageView(this);
        this.rhatprdygi = imageView6;
        imageView6.setLayoutParams(new LinearLayout.LayoutParams(1080, 546));
        this.rhatprdygi.setPadding(17, 86, 84, 62);
        linearLayout.addView(this.rhatprdygi);
        this.rhatprdygi.setBackgroundColor(Color.parseColor("#45a036"));
        DatePicker datePicker7 = new DatePicker(this);
        this.wijjpkfkoz = datePicker7;
        datePicker7.setLayoutParams(new LinearLayout.LayoutParams(1781, 1746));
        this.wijjpkfkoz.setPadding(10, 145, 145, 89);
        linearLayout.addView(this.wijjpkfkoz);
        this.wijjpkfkoz.setBackgroundColor(Color.parseColor("#b29bfb"));
        ListView listView8 = new ListView(this);
        this.hxmbdunzxq = listView8;
        listView8.setLayoutParams(new LinearLayout.LayoutParams(1022, 487));
        this.hxmbdunzxq.setPadding(190, 125, 89, 33);
        linearLayout.addView(this.hxmbdunzxq);
        this.hxmbdunzxq.setBackgroundColor(Color.parseColor("#2c6ad3"));
        GridView gridView3 = new GridView(this);
        this.uwvbqizdza = gridView3;
        gridView3.setLayoutParams(new LinearLayout.LayoutParams(289, 12));
        this.uwvbqizdza.setPadding(136, 103, 166, 71);
        linearLayout.addView(this.uwvbqizdza);
        this.uwvbqizdza.setBackgroundColor(Color.parseColor("#b9c36b"));
        ImageView imageView7 = new ImageView(this);
        this.kzipnqqeuz = imageView7;
        imageView7.setLayoutParams(new LinearLayout.LayoutParams(20, 981));
        this.kzipnqqeuz.setPadding(181, 122, 88, 198);
        linearLayout.addView(this.kzipnqqeuz);
        this.kzipnqqeuz.setBackgroundColor(Color.parseColor("#629106"));
        TimePicker timePicker6 = new TimePicker(this);
        this.yxorsttnvm = timePicker6;
        timePicker6.setLayoutParams(new LinearLayout.LayoutParams(1033, 1665));
        this.yxorsttnvm.setPadding(118, 13, 184, 112);
        linearLayout.addView(this.yxorsttnvm);
        this.yxorsttnvm.setBackgroundColor(Color.parseColor("#ae5032"));
        TableLayout tableLayout14 = new TableLayout(this);
        this.xiwgpgvoao = tableLayout14;
        tableLayout14.setLayoutParams(new LinearLayout.LayoutParams(1076, 1574));
        this.xiwgpgvoao.setPadding(106, 149, 79, 78);
        linearLayout.addView(this.xiwgpgvoao);
        this.xiwgpgvoao.setBackgroundColor(Color.parseColor("#b33b49"));
        Spinner spinner10 = new Spinner(this);
        this.qvlflgtqfp = spinner10;
        spinner10.setLayoutParams(new LinearLayout.LayoutParams(1872, TypedValues.MotionType.TYPE_PATHMOTION_ARC));
        this.qvlflgtqfp.setPadding(109, 32, 27, 177);
        linearLayout.addView(this.qvlflgtqfp);
        this.qvlflgtqfp.setBackgroundColor(Color.parseColor("#bf9d83"));
        TableLayout tableLayout15 = new TableLayout(this);
        this.kemapufjop = tableLayout15;
        tableLayout15.setLayoutParams(new LinearLayout.LayoutParams(953, 1628));
        this.kemapufjop.setPadding(116, 135, 178, 50);
        linearLayout.addView(this.kemapufjop);
        this.kemapufjop.setBackgroundColor(Color.parseColor("#207f86"));
        Button button6 = new Button(this);
        this.xfawavamwp = button6;
        button6.setLayoutParams(new LinearLayout.LayoutParams(1819, 671));
        this.xfawavamwp.setPadding(122, 198, 199, 51);
        linearLayout.addView(this.xfawavamwp);
        this.xfawavamwp.setBackgroundColor(Color.parseColor("#e5bf8a"));
        ProgressBar progressBar9 = new ProgressBar(this);
        this.dwpktizczp = progressBar9;
        progressBar9.setLayoutParams(new LinearLayout.LayoutParams(1903, 583));
        this.dwpktizczp.setPadding(148, 123, 123, 39);
        linearLayout.addView(this.dwpktizczp);
        this.dwpktizczp.setBackgroundColor(Color.parseColor("#6d6500"));
        RelativeLayout relativeLayout5 = new RelativeLayout(this);
        this.zztbgtikep = relativeLayout5;
        relativeLayout5.setLayoutParams(new LinearLayout.LayoutParams(1967, 1410));
        this.zztbgtikep.setPadding(55, 103, 134, 85);
        linearLayout.addView(this.zztbgtikep);
        this.zztbgtikep.setBackgroundColor(Color.parseColor("#4e08a3"));
        EditText editText8 = new EditText(this);
        this.gaxqbmnmrx = editText8;
        editText8.setLayoutParams(new LinearLayout.LayoutParams(1799, 1468));
        this.gaxqbmnmrx.setPadding(100, 60, 179, 76);
        linearLayout.addView(this.gaxqbmnmrx);
        this.gaxqbmnmrx.setBackgroundColor(Color.parseColor("#97f43e"));
        ToggleButton toggleButton5 = new ToggleButton(this);
        this.zusazrplae = toggleButton5;
        toggleButton5.setLayoutParams(new LinearLayout.LayoutParams(468, 1030));
        this.zusazrplae.setPadding(50, 45, 34, 28);
        linearLayout.addView(this.zusazrplae);
        this.zusazrplae.setBackgroundColor(Color.parseColor("#7b8a6c"));
        FrameLayout frameLayout3 = new FrameLayout(this);
        this.ipbxlvhhru = frameLayout3;
        frameLayout3.setLayoutParams(new LinearLayout.LayoutParams(433, 1245));
        this.ipbxlvhhru.setPadding(49, 164, 110, 81);
        linearLayout.addView(this.ipbxlvhhru);
        this.ipbxlvhhru.setBackgroundColor(Color.parseColor("#df8e73"));
        TableLayout tableLayout16 = new TableLayout(this);
        this.oupuaummfs = tableLayout16;
        tableLayout16.setLayoutParams(new LinearLayout.LayoutParams(1493, LocalPlaybackConstants.BUFFER_A_CAN_USE_FLAG));
        this.oupuaummfs.setPadding(78, 11, 104, 124);
        linearLayout.addView(this.oupuaummfs);
        this.oupuaummfs.setBackgroundColor(Color.parseColor("#1534ba"));
        FrameLayout frameLayout4 = new FrameLayout(this);
        this.gayytrzral = frameLayout4;
        frameLayout4.setLayoutParams(new LinearLayout.LayoutParams(1, 1191));
        this.gayytrzral.setPadding(137, 113, 44, 145);
        linearLayout.addView(this.gayytrzral);
        this.gayytrzral.setBackgroundColor(Color.parseColor("#9e7597"));
        CheckBox checkBox4 = new CheckBox(this);
        this.ivlllbxkip = checkBox4;
        checkBox4.setLayoutParams(new LinearLayout.LayoutParams(1822, 1667));
        this.ivlllbxkip.setPadding(116, 151, 24, 191);
        linearLayout.addView(this.ivlllbxkip);
        this.ivlllbxkip.setBackgroundColor(Color.parseColor("#686174"));
        ToggleButton toggleButton6 = new ToggleButton(this);
        this.bciyanegrs = toggleButton6;
        toggleButton6.setLayoutParams(new LinearLayout.LayoutParams(124, 1853));
        this.bciyanegrs.setPadding(WebSocketProtocol.PAYLOAD_SHORT, BDLocation.TypeCoarseLocation, 52, 55);
        linearLayout.addView(this.bciyanegrs);
        this.bciyanegrs.setBackgroundColor(Color.parseColor("#2681d0"));
        EditText editText9 = new EditText(this);
        this.wadpjlryhm = editText9;
        editText9.setLayoutParams(new LinearLayout.LayoutParams(45, 1671));
        this.wadpjlryhm.setPadding(109, 179, 74, 100);
        linearLayout.addView(this.wadpjlryhm);
        this.wadpjlryhm.setBackgroundColor(Color.parseColor("#5a09f5"));
        TextView textView4 = new TextView(this);
        this.wlngryvsna = textView4;
        textView4.setLayoutParams(new LinearLayout.LayoutParams(360, 1536));
        this.wlngryvsna.setPadding(137, 181, 15, 187);
        linearLayout.addView(this.wlngryvsna);
        this.wlngryvsna.setBackgroundColor(Color.parseColor("#74186b"));
        EditText editText10 = new EditText(this);
        this.jlayutzxwa = editText10;
        editText10.setLayoutParams(new LinearLayout.LayoutParams(34, 913));
        this.jlayutzxwa.setPadding(165, 22, 27, 175);
        linearLayout.addView(this.jlayutzxwa);
        this.jlayutzxwa.setBackgroundColor(Color.parseColor("#a05104"));
        Spinner spinner11 = new Spinner(this);
        this.pmlrztvlzz = spinner11;
        spinner11.setLayoutParams(new LinearLayout.LayoutParams(1440, 1258));
        this.pmlrztvlzz.setPadding(1, 143, 196, 180);
        linearLayout.addView(this.pmlrztvlzz);
        this.pmlrztvlzz.setBackgroundColor(Color.parseColor("#0bf423"));
        RadioButton radioButton5 = new RadioButton(this);
        this.pdnlskhphh = radioButton5;
        radioButton5.setLayoutParams(new LinearLayout.LayoutParams(1088, 1536));
        this.pdnlskhphh.setPadding(2, 54, 135, 118);
        linearLayout.addView(this.pdnlskhphh);
        this.pdnlskhphh.setBackgroundColor(Color.parseColor("#5eecd2"));
        RatingBar ratingBar5 = new RatingBar(this);
        this.qnfxzzmgys = ratingBar5;
        ratingBar5.setLayoutParams(new LinearLayout.LayoutParams(1182, 1629));
        this.qnfxzzmgys.setPadding(107, 111, 94, 54);
        linearLayout.addView(this.qnfxzzmgys);
        this.qnfxzzmgys.setBackgroundColor(Color.parseColor("#6668a1"));
        ToggleButton toggleButton7 = new ToggleButton(this);
        this.mqbywjpbdn = toggleButton7;
        toggleButton7.setLayoutParams(new LinearLayout.LayoutParams(1626, 476));
        this.mqbywjpbdn.setPadding(100, 96, 38, 121);
        linearLayout.addView(this.mqbywjpbdn);
        this.mqbywjpbdn.setBackgroundColor(Color.parseColor("#632bdc"));
        ImageView imageView8 = new ImageView(this);
        this.vpwhdjrhts = imageView8;
        imageView8.setLayoutParams(new LinearLayout.LayoutParams(895, 1255));
        this.vpwhdjrhts.setPadding(119, 192, 64, 125);
        linearLayout.addView(this.vpwhdjrhts);
        this.vpwhdjrhts.setBackgroundColor(Color.parseColor("#d36dc8"));
        Button button7 = new Button(this);
        this.xnjneaufhi = button7;
        button7.setLayoutParams(new LinearLayout.LayoutParams(1431, 823));
        this.xnjneaufhi.setPadding(100, 125, 104, 32);
        linearLayout.addView(this.xnjneaufhi);
        this.xnjneaufhi.setBackgroundColor(Color.parseColor("#bf9c37"));
        RadioButton radioButton6 = new RadioButton(this);
        this.ftqqppdsls = radioButton6;
        radioButton6.setLayoutParams(new LinearLayout.LayoutParams(579, 879));
        this.ftqqppdsls.setPadding(18, 32, 170, 78);
        linearLayout.addView(this.ftqqppdsls);
        this.ftqqppdsls.setBackgroundColor(Color.parseColor("#989d0d"));
        ImageView imageView9 = new ImageView(this);
        this.vvtdhlqyss = imageView9;
        imageView9.setLayoutParams(new LinearLayout.LayoutParams(1855, 590));
        this.vvtdhlqyss.setPadding(149, 70, 145, 111);
        linearLayout.addView(this.vvtdhlqyss);
        this.vvtdhlqyss.setBackgroundColor(Color.parseColor("#162a7b"));
        Switch r23 = new Switch(this);
        this.mwiwghedlh = r23;
        r23.setLayoutParams(new LinearLayout.LayoutParams(1115, 1128));
        this.mwiwghedlh.setPadding(175, 28, 66, 107);
        linearLayout.addView(this.mwiwghedlh);
        this.mwiwghedlh.setBackgroundColor(Color.parseColor("#ddf9fe"));
        Switch r24 = new Switch(this);
        this.gquinlbqut = r24;
        r24.setLayoutParams(new LinearLayout.LayoutParams(61, 551));
        this.gquinlbqut.setPadding(110, 110, 142, 196);
        linearLayout.addView(this.gquinlbqut);
        this.gquinlbqut.setBackgroundColor(Color.parseColor("#6e316e"));
        TextView textView5 = new TextView(this);
        this.mygpgpqfix = textView5;
        textView5.setLayoutParams(new LinearLayout.LayoutParams(1354, 1643));
        this.mygpgpqfix.setPadding(69, 102, 133, 158);
        linearLayout.addView(this.mygpgpqfix);
        this.mygpgpqfix.setBackgroundColor(Color.parseColor("#c67f35"));
        LinearLayout linearLayout8 = new LinearLayout(this);
        this.lgplpltzyn = linearLayout8;
        linearLayout8.setLayoutParams(new LinearLayout.LayoutParams(1275, 1380));
        this.lgplpltzyn.setPadding(127, 181, 94, 21);
        linearLayout.addView(this.lgplpltzyn);
        this.lgplpltzyn.setBackgroundColor(Color.parseColor("#aacd99"));
        CheckBox checkBox5 = new CheckBox(this);
        this.yrwriomlzw = checkBox5;
        checkBox5.setLayoutParams(new LinearLayout.LayoutParams(133, 1776));
        this.yrwriomlzw.setPadding(157, 72, 123, 4);
        linearLayout.addView(this.yrwriomlzw);
        this.yrwriomlzw.setBackgroundColor(Color.parseColor("#f3fc2b"));
        ProgressBar progressBar10 = new ProgressBar(this);
        this.moifgkbudc = progressBar10;
        progressBar10.setLayoutParams(new LinearLayout.LayoutParams(682, 525));
        this.moifgkbudc.setPadding(16, 106, 114, 173);
        linearLayout.addView(this.moifgkbudc);
        this.moifgkbudc.setBackgroundColor(Color.parseColor("#bddb3a"));
        ImageView imageView10 = new ImageView(this);
        this.xvbxlddikn = imageView10;
        imageView10.setLayoutParams(new LinearLayout.LayoutParams(1971, 1572));
        this.xvbxlddikn.setPadding(50, 129, 143, 98);
        linearLayout.addView(this.xvbxlddikn);
        this.xvbxlddikn.setBackgroundColor(Color.parseColor("#ca2e80"));
        Spinner spinner12 = new Spinner(this);
        this.eytdfyexgp = spinner12;
        spinner12.setLayoutParams(new LinearLayout.LayoutParams(552, 680));
        this.eytdfyexgp.setPadding(150, 71, 190, 119);
        linearLayout.addView(this.eytdfyexgp);
        this.eytdfyexgp.setBackgroundColor(Color.parseColor("#2ea143"));
        ListView listView9 = new ListView(this);
        this.qgmksfvngj = listView9;
        listView9.setLayoutParams(new LinearLayout.LayoutParams(1183, 323));
        this.qgmksfvngj.setPadding(143, 62, 198, 74);
        linearLayout.addView(this.qgmksfvngj);
        this.qgmksfvngj.setBackgroundColor(Color.parseColor("#a3c43c"));
        CheckBox checkBox6 = new CheckBox(this);
        this.gjadalcwed = checkBox6;
        checkBox6.setLayoutParams(new LinearLayout.LayoutParams(HealthyViewModel.Type_Sync_TimeOut, 675));
        this.gjadalcwed.setPadding(158, 159, 87, 104);
        linearLayout.addView(this.gjadalcwed);
        this.gjadalcwed.setBackgroundColor(Color.parseColor("#65b90c"));
        FrameLayout frameLayout5 = new FrameLayout(this);
        this.adrpcluulx = frameLayout5;
        frameLayout5.setLayoutParams(new LinearLayout.LayoutParams(962, 62));
        this.adrpcluulx.setPadding(13, 97, 180, 101);
        linearLayout.addView(this.adrpcluulx);
        this.adrpcluulx.setBackgroundColor(Color.parseColor("#4fd66a"));
        LinearLayout linearLayout9 = new LinearLayout(this);
        this.oblpbqgxfd = linearLayout9;
        linearLayout9.setLayoutParams(new LinearLayout.LayoutParams(350, 1751));
        this.oblpbqgxfd.setPadding(96, 82, 59, 88);
        linearLayout.addView(this.oblpbqgxfd);
        this.oblpbqgxfd.setBackgroundColor(Color.parseColor("#870265"));
        ImageView imageView11 = new ImageView(this);
        this.hsrvausdqm = imageView11;
        imageView11.setLayoutParams(new LinearLayout.LayoutParams(890, 1396));
        this.hsrvausdqm.setPadding(59, 20, 186, 80);
        linearLayout.addView(this.hsrvausdqm);
        this.hsrvausdqm.setBackgroundColor(Color.parseColor("#42e95f"));
        RadioButton radioButton7 = new RadioButton(this);
        this.ddoqokezhn = radioButton7;
        radioButton7.setLayoutParams(new LinearLayout.LayoutParams(721, 1222));
        this.ddoqokezhn.setPadding(6, 38, 157, 159);
        linearLayout.addView(this.ddoqokezhn);
        this.ddoqokezhn.setBackgroundColor(Color.parseColor("#3643cb"));
        ViewFlipper viewFlipper3 = new ViewFlipper(this);
        this.rzzwpuqewt = viewFlipper3;
        viewFlipper3.setLayoutParams(new LinearLayout.LayoutParams(550, 1916));
        this.rzzwpuqewt.setPadding(181, 29, 75, 18);
        linearLayout.addView(this.rzzwpuqewt);
        this.rzzwpuqewt.setBackgroundColor(Color.parseColor("#83d117"));
        TextView textView6 = new TextView(this);
        this.sxmzoiuuaa = textView6;
        textView6.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.CycleType.TYPE_WAVE_OFFSET, 1084));
        this.sxmzoiuuaa.setPadding(75, 78, 111, 67);
        linearLayout.addView(this.sxmzoiuuaa);
        this.sxmzoiuuaa.setBackgroundColor(Color.parseColor("#5a63c7"));
        Spinner spinner13 = new Spinner(this);
        this.hxbuyiulwp = spinner13;
        spinner13.setLayoutParams(new LinearLayout.LayoutParams(455, 855));
        this.hxbuyiulwp.setPadding(22, 66, 34, 36);
        linearLayout.addView(this.hxbuyiulwp);
        this.hxbuyiulwp.setBackgroundColor(Color.parseColor("#3ffe8e"));
        ProgressBar progressBar11 = new ProgressBar(this);
        this.jirzbxqiou = progressBar11;
        progressBar11.setLayoutParams(new LinearLayout.LayoutParams(1469, 1856));
        this.jirzbxqiou.setPadding(29, 142, 151, 31);
        linearLayout.addView(this.jirzbxqiou);
        this.jirzbxqiou.setBackgroundColor(Color.parseColor("#ce81f6"));
        GridView gridView4 = new GridView(this);
        this.ykimwtxrrr = gridView4;
        gridView4.setLayoutParams(new LinearLayout.LayoutParams(193, 1297));
        this.ykimwtxrrr.setPadding(46, 92, 79, 62);
        linearLayout.addView(this.ykimwtxrrr);
        this.ykimwtxrrr.setBackgroundColor(Color.parseColor("#5099d8"));
        RatingBar ratingBar6 = new RatingBar(this);
        this.jdvdsdnzgu = ratingBar6;
        ratingBar6.setLayoutParams(new LinearLayout.LayoutParams(1838, 146));
        this.jdvdsdnzgu.setPadding(156, 27, 147, 180);
        linearLayout.addView(this.jdvdsdnzgu);
        this.jdvdsdnzgu.setBackgroundColor(Color.parseColor("#76c702"));
        EditText editText11 = new EditText(this);
        this.kuroddqwmk = editText11;
        editText11.setLayoutParams(new LinearLayout.LayoutParams(1833, 1039));
        this.kuroddqwmk.setPadding(29, 47, 64, 143);
        linearLayout.addView(this.kuroddqwmk);
        this.kuroddqwmk.setBackgroundColor(Color.parseColor("#e78913"));
        SeekBar seekBar4 = new SeekBar(this);
        this.gyizlpayks = seekBar4;
        seekBar4.setLayoutParams(new LinearLayout.LayoutParams(600, 1869));
        this.gyizlpayks.setPadding(82, 29, 157, 115);
        linearLayout.addView(this.gyizlpayks);
        this.gyizlpayks.setBackgroundColor(Color.parseColor("#ef9915"));
        TableLayout tableLayout17 = new TableLayout(this);
        this.ppnxagqvel = tableLayout17;
        tableLayout17.setLayoutParams(new LinearLayout.LayoutParams(1782, 641));
        this.ppnxagqvel.setPadding(WebSocketProtocol.PAYLOAD_SHORT, 119, 193, 132);
        linearLayout.addView(this.ppnxagqvel);
        this.ppnxagqvel.setBackgroundColor(Color.parseColor("#df2247"));
        ViewFlipper viewFlipper4 = new ViewFlipper(this);
        this.kxzhbgrmig = viewFlipper4;
        viewFlipper4.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.PositionType.TYPE_PERCENT_Y, 374));
        this.kxzhbgrmig.setPadding(BDLocation.TypeNetWorkLocation, 95, 192, 71);
        linearLayout.addView(this.kxzhbgrmig);
        this.kxzhbgrmig.setBackgroundColor(Color.parseColor("#862d05"));
        CheckBox checkBox7 = new CheckBox(this);
        this.vfmtkuodqe = checkBox7;
        checkBox7.setLayoutParams(new LinearLayout.LayoutParams(1521, 320));
        this.vfmtkuodqe.setPadding(134, 123, 149, 69);
        linearLayout.addView(this.vfmtkuodqe);
        this.vfmtkuodqe.setBackgroundColor(Color.parseColor("#a51c1e"));
        ProgressBar progressBar12 = new ProgressBar(this);
        this.bxjrnrojzv = progressBar12;
        progressBar12.setLayoutParams(new LinearLayout.LayoutParams(73, 1370));
        this.bxjrnrojzv.setPadding(152, 52, 121, 70);
        linearLayout.addView(this.bxjrnrojzv);
        this.bxjrnrojzv.setBackgroundColor(Color.parseColor("#5ff491"));
        TimePicker timePicker7 = new TimePicker(this);
        this.dewwsuoaad = timePicker7;
        timePicker7.setLayoutParams(new LinearLayout.LayoutParams(869, 32));
        this.dewwsuoaad.setPadding(180, 92, 170, 142);
        linearLayout.addView(this.dewwsuoaad);
        this.dewwsuoaad.setBackgroundColor(Color.parseColor("#b44a24"));
        TimePicker timePicker8 = new TimePicker(this);
        this.bhqcgwwhmk = timePicker8;
        timePicker8.setLayoutParams(new LinearLayout.LayoutParams(1687, 1905));
        this.bhqcgwwhmk.setPadding(175, 139, 176, 15);
        linearLayout.addView(this.bhqcgwwhmk);
        this.bhqcgwwhmk.setBackgroundColor(Color.parseColor("#008648"));
        ViewFlipper viewFlipper5 = new ViewFlipper(this);
        this.kpxltahpax = viewFlipper5;
        viewFlipper5.setLayoutParams(new LinearLayout.LayoutParams(1215, 893));
        this.kpxltahpax.setPadding(191, 173, 193, 43);
        linearLayout.addView(this.kpxltahpax);
        this.kpxltahpax.setBackgroundColor(Color.parseColor("#31928d"));
        RelativeLayout relativeLayout6 = new RelativeLayout(this);
        this.ftvltqttae = relativeLayout6;
        relativeLayout6.setLayoutParams(new LinearLayout.LayoutParams(587, 288));
        this.ftvltqttae.setPadding(55, 99, 166, 148);
        linearLayout.addView(this.ftvltqttae);
        this.ftvltqttae.setBackgroundColor(Color.parseColor("#f533cd"));
        TableLayout tableLayout18 = new TableLayout(this);
        this.wehaekifrh = tableLayout18;
        tableLayout18.setLayoutParams(new LinearLayout.LayoutParams(1536, 256));
        this.wehaekifrh.setPadding(11, 75, 77, 97);
        linearLayout.addView(this.wehaekifrh);
        this.wehaekifrh.setBackgroundColor(Color.parseColor("#f81af4"));
        FrameLayout frameLayout6 = new FrameLayout(this);
        this.wvwoliagub = frameLayout6;
        frameLayout6.setLayoutParams(new LinearLayout.LayoutParams(1917, TypedValues.MotionType.TYPE_POLAR_RELATIVETO));
        this.wvwoliagub.setPadding(19, 94, 29, 175);
        linearLayout.addView(this.wvwoliagub);
        this.wvwoliagub.setBackgroundColor(Color.parseColor("#efcdc5"));
        LinearLayout linearLayout10 = new LinearLayout(this);
        this.dqrwytkcqk = linearLayout10;
        linearLayout10.setLayoutParams(new LinearLayout.LayoutParams(487, 1562));
        this.dqrwytkcqk.setPadding(197, 101, 192, 3);
        linearLayout.addView(this.dqrwytkcqk);
        this.dqrwytkcqk.setBackgroundColor(Color.parseColor("#53ab87"));
        Spinner spinner14 = new Spinner(this);
        this.qftjtzcjzf = spinner14;
        spinner14.setLayoutParams(new LinearLayout.LayoutParams(471, 1948));
        this.qftjtzcjzf.setPadding(178, 88, 99, 136);
        linearLayout.addView(this.qftjtzcjzf);
        this.qftjtzcjzf.setBackgroundColor(Color.parseColor("#14638a"));
        Switch r25 = new Switch(this);
        this.ykxfpxfyqn = r25;
        r25.setLayoutParams(new LinearLayout.LayoutParams(1992, 1303));
        this.ykxfpxfyqn.setPadding(58, 196, 178, 145);
        linearLayout.addView(this.ykxfpxfyqn);
        this.ykxfpxfyqn.setBackgroundColor(Color.parseColor("#0d1c91"));
        DatePicker datePicker8 = new DatePicker(this);
        this.zhqmrwglzb = datePicker8;
        datePicker8.setLayoutParams(new LinearLayout.LayoutParams(1254, 1360));
        this.zhqmrwglzb.setPadding(164, 128, 31, 156);
        linearLayout.addView(this.zhqmrwglzb);
        this.zhqmrwglzb.setBackgroundColor(Color.parseColor("#d635c4"));
        Spinner spinner15 = new Spinner(this);
        this.egsybkdlpo = spinner15;
        spinner15.setLayoutParams(new LinearLayout.LayoutParams(761, 1371));
        this.egsybkdlpo.setPadding(165, 147, 90, 8);
        linearLayout.addView(this.egsybkdlpo);
        this.egsybkdlpo.setBackgroundColor(Color.parseColor("#ad37ad"));
        Button button8 = new Button(this);
        this.fomsciarea = button8;
        button8.setLayoutParams(new LinearLayout.LayoutParams(183, 1145));
        this.fomsciarea.setPadding(41, 156, 75, 38);
        linearLayout.addView(this.fomsciarea);
        this.fomsciarea.setBackgroundColor(Color.parseColor("#a2b1b4"));
        RelativeLayout relativeLayout7 = new RelativeLayout(this);
        this.cjuozaizjj = relativeLayout7;
        relativeLayout7.setLayoutParams(new LinearLayout.LayoutParams(719, 1478));
        this.cjuozaizjj.setPadding(15, 78, 179, 176);
        linearLayout.addView(this.cjuozaizjj);
        this.cjuozaizjj.setBackgroundColor(Color.parseColor("#7864a6"));
        RelativeLayout relativeLayout8 = new RelativeLayout(this);
        this.inkagzbgmb = relativeLayout8;
        relativeLayout8.setLayoutParams(new LinearLayout.LayoutParams(603, 778));
        this.inkagzbgmb.setPadding(198, 191, 65, 0);
        linearLayout.addView(this.inkagzbgmb);
        this.inkagzbgmb.setBackgroundColor(Color.parseColor("#39fbb8"));
        TextView textView7 = new TextView(this);
        this.ixovjadsrl = textView7;
        textView7.setLayoutParams(new LinearLayout.LayoutParams(1846, 1602));
        this.ixovjadsrl.setPadding(101, 77, 81, 16);
        linearLayout.addView(this.ixovjadsrl);
        this.ixovjadsrl.setBackgroundColor(Color.parseColor("#d5134f"));
        TimePicker timePicker9 = new TimePicker(this);
        this.hsuoumereo = timePicker9;
        timePicker9.setLayoutParams(new LinearLayout.LayoutParams(20, 626));
        this.hsuoumereo.setPadding(136, 29, 191, 113);
        linearLayout.addView(this.hsuoumereo);
        this.hsuoumereo.setBackgroundColor(Color.parseColor("#28ceb0"));
        ToggleButton toggleButton8 = new ToggleButton(this);
        this.gkcsxphlqb = toggleButton8;
        toggleButton8.setLayoutParams(new LinearLayout.LayoutParams(1367, 274));
        this.gkcsxphlqb.setPadding(174, 81, 186, 130);
        linearLayout.addView(this.gkcsxphlqb);
        this.gkcsxphlqb.setBackgroundColor(Color.parseColor("#a80f25"));
        RatingBar ratingBar7 = new RatingBar(this);
        this.fkstxjibtz = ratingBar7;
        ratingBar7.setLayoutParams(new LinearLayout.LayoutParams(1894, 714));
        this.fkstxjibtz.setPadding(159, 20, 68, 119);
        linearLayout.addView(this.fkstxjibtz);
        this.fkstxjibtz.setBackgroundColor(Color.parseColor("#be395b"));
        CheckBox checkBox8 = new CheckBox(this);
        this.wstdjdvfoe = checkBox8;
        checkBox8.setLayoutParams(new LinearLayout.LayoutParams(1872, 547));
        this.wstdjdvfoe.setPadding(195, 196, WebSocketProtocol.PAYLOAD_SHORT, 44);
        linearLayout.addView(this.wstdjdvfoe);
        this.wstdjdvfoe.setBackgroundColor(Color.parseColor("#a75e88"));
        Button button9 = new Button(this);
        this.yovbqtlfnk = button9;
        button9.setLayoutParams(new LinearLayout.LayoutParams(871, 916));
        this.yovbqtlfnk.setPadding(61, 92, BDLocation.TypeNetWorkLocation, 21);
        linearLayout.addView(this.yovbqtlfnk);
        this.yovbqtlfnk.setBackgroundColor(Color.parseColor("#c43c7f"));
        FrameLayout frameLayout7 = new FrameLayout(this);
        this.oziwkhzqnd = frameLayout7;
        frameLayout7.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.MotionType.TYPE_POLAR_RELATIVETO, 190));
        this.oziwkhzqnd.setPadding(70, 91, 80, 3);
        linearLayout.addView(this.oziwkhzqnd);
        this.oziwkhzqnd.setBackgroundColor(Color.parseColor("#5576df"));
        Button button10 = new Button(this);
        this.kkioikahzq = button10;
        button10.setLayoutParams(new LinearLayout.LayoutParams(384, 1660));
        this.kkioikahzq.setPadding(165, 118, 41, 37);
        linearLayout.addView(this.kkioikahzq);
        this.kkioikahzq.setBackgroundColor(Color.parseColor("#2caf05"));
        Spinner spinner16 = new Spinner(this);
        this.ohlxsgxkou = spinner16;
        spinner16.setLayoutParams(new LinearLayout.LayoutParams(1578, 1539));
        this.ohlxsgxkou.setPadding(60, 54, 123, 128);
        linearLayout.addView(this.ohlxsgxkou);
        this.ohlxsgxkou.setBackgroundColor(Color.parseColor("#054969"));
        ListView listView10 = new ListView(this);
        this.dlxwdtoztd = listView10;
        listView10.setLayoutParams(new LinearLayout.LayoutParams(43, 490));
        this.dlxwdtoztd.setPadding(174, 159, 106, 125);
        linearLayout.addView(this.dlxwdtoztd);
        this.dlxwdtoztd.setBackgroundColor(Color.parseColor("#0cbfd7"));
        Spinner spinner17 = new Spinner(this);
        this.hkzfzlduse = spinner17;
        spinner17.setLayoutParams(new LinearLayout.LayoutParams(894, 1773));
        this.hkzfzlduse.setPadding(99, 30, 190, WebSocketProtocol.PAYLOAD_SHORT);
        linearLayout.addView(this.hkzfzlduse);
        this.hkzfzlduse.setBackgroundColor(Color.parseColor("#119a87"));
        Switch r26 = new Switch(this);
        this.ibvbxzxave = r26;
        r26.setLayoutParams(new LinearLayout.LayoutParams(1411, 716));
        this.ibvbxzxave.setPadding(165, 44, 91, 108);
        linearLayout.addView(this.ibvbxzxave);
        this.ibvbxzxave.setBackgroundColor(Color.parseColor("#68c4d6"));
        FrameLayout frameLayout8 = new FrameLayout(this);
        this.wvhzgzdjnf = frameLayout8;
        frameLayout8.setLayoutParams(new LinearLayout.LayoutParams(115, 723));
        this.wvhzgzdjnf.setPadding(157, 132, 185, 193);
        linearLayout.addView(this.wvhzgzdjnf);
        this.wvhzgzdjnf.setBackgroundColor(Color.parseColor("#47dded"));
        ProgressBar progressBar13 = new ProgressBar(this);
        this.cdnaarynrj = progressBar13;
        progressBar13.setLayoutParams(new LinearLayout.LayoutParams(855, 1070));
        this.cdnaarynrj.setPadding(87, 190, 164, 157);
        linearLayout.addView(this.cdnaarynrj);
        this.cdnaarynrj.setBackgroundColor(Color.parseColor("#c76b58"));
        ToggleButton toggleButton9 = new ToggleButton(this);
        this.mntevdvbte = toggleButton9;
        toggleButton9.setLayoutParams(new LinearLayout.LayoutParams(816, 1028));
        this.mntevdvbte.setPadding(60, 55, 102, 47);
        linearLayout.addView(this.mntevdvbte);
        this.mntevdvbte.setBackgroundColor(Color.parseColor("#26b771"));
        ScrollView scrollView4 = new ScrollView(this);
        this.yugmllhtqh = scrollView4;
        scrollView4.setLayoutParams(new LinearLayout.LayoutParams(1512, 1093));
        this.yugmllhtqh.setPadding(109, 15, 33, 66);
        linearLayout.addView(this.yugmllhtqh);
        this.yugmllhtqh.setBackgroundColor(Color.parseColor("#f73731"));
        ListView listView11 = new ListView(this);
        this.ucplbiercz = listView11;
        listView11.setLayoutParams(new LinearLayout.LayoutParams(1134, 1369));
        this.ucplbiercz.setPadding(36, 149, 170, 129);
        linearLayout.addView(this.ucplbiercz);
        this.ucplbiercz.setBackgroundColor(Color.parseColor("#c95872"));
        ScrollView scrollView5 = new ScrollView(this);
        this.giruoozpgk = scrollView5;
        scrollView5.setLayoutParams(new LinearLayout.LayoutParams(1640, 1710));
        this.giruoozpgk.setPadding(54, 105, 0, 192);
        linearLayout.addView(this.giruoozpgk);
        this.giruoozpgk.setBackgroundColor(Color.parseColor("#829c43"));
        ToggleButton toggleButton10 = new ToggleButton(this);
        this.mwkqhgjvdf = toggleButton10;
        toggleButton10.setLayoutParams(new LinearLayout.LayoutParams(985, 453));
        this.mwkqhgjvdf.setPadding(109, 127, 43, 57);
        linearLayout.addView(this.mwkqhgjvdf);
        this.mwkqhgjvdf.setBackgroundColor(Color.parseColor("#e5cdf9"));
        DatePicker datePicker9 = new DatePicker(this);
        this.pqrgfpjknf = datePicker9;
        datePicker9.setLayoutParams(new LinearLayout.LayoutParams(1337, 354));
        this.pqrgfpjknf.setPadding(146, 60, 191, 64);
        linearLayout.addView(this.pqrgfpjknf);
        this.pqrgfpjknf.setBackgroundColor(Color.parseColor("#03e6c3"));
        EditText editText12 = new EditText(this);
        this.bryfmtmcws = editText12;
        editText12.setLayoutParams(new LinearLayout.LayoutParams(1308, 1926));
        this.bryfmtmcws.setPadding(119, 0, 136, 27);
        linearLayout.addView(this.bryfmtmcws);
        this.bryfmtmcws.setBackgroundColor(Color.parseColor("#974070"));
        RatingBar ratingBar8 = new RatingBar(this);
        this.cqlxjacfcg = ratingBar8;
        ratingBar8.setLayoutParams(new LinearLayout.LayoutParams(68, 1635));
        this.cqlxjacfcg.setPadding(90, 24, 192, 154);
        linearLayout.addView(this.cqlxjacfcg);
        this.cqlxjacfcg.setBackgroundColor(Color.parseColor("#92acf3"));
        DatePicker datePicker10 = new DatePicker(this);
        this.gqpcwxwdcx = datePicker10;
        datePicker10.setLayoutParams(new LinearLayout.LayoutParams(1705, 676));
        this.gqpcwxwdcx.setPadding(117, 149, 4, 175);
        linearLayout.addView(this.gqpcwxwdcx);
        this.gqpcwxwdcx.setBackgroundColor(Color.parseColor("#60d6dc"));
        TextView textView8 = new TextView(this);
        this.jkfwhiqyzj = textView8;
        textView8.setLayoutParams(new LinearLayout.LayoutParams(464, 1695));
        this.jkfwhiqyzj.setPadding(18, 189, 149, 139);
        linearLayout.addView(this.jkfwhiqyzj);
        this.jkfwhiqyzj.setBackgroundColor(Color.parseColor("#2a4785"));
        LinearLayout linearLayout11 = new LinearLayout(this);
        this.rwfooitjyf = linearLayout11;
        linearLayout11.setLayoutParams(new LinearLayout.LayoutParams(1775, 1072));
        this.rwfooitjyf.setPadding(11, 93, 35, 125);
        linearLayout.addView(this.rwfooitjyf);
        this.rwfooitjyf.setBackgroundColor(Color.parseColor("#f80a5f"));
        Button button11 = new Button(this);
        this.emlkkmxjrj = button11;
        button11.setLayoutParams(new LinearLayout.LayoutParams(263, 1370));
        this.emlkkmxjrj.setPadding(71, 17, 53, 118);
        linearLayout.addView(this.emlkkmxjrj);
        this.emlkkmxjrj.setBackgroundColor(Color.parseColor("#a650c8"));
        Spinner spinner18 = new Spinner(this);
        this.njzjzlgpyd = spinner18;
        spinner18.setLayoutParams(new LinearLayout.LayoutParams(883, 597));
        this.njzjzlgpyd.setPadding(48, 41, 3, 102);
        linearLayout.addView(this.njzjzlgpyd);
        this.njzjzlgpyd.setBackgroundColor(Color.parseColor("#7c3dbc"));
        RadioButton radioButton8 = new RadioButton(this);
        this.vqdshlmhcg = radioButton8;
        radioButton8.setLayoutParams(new LinearLayout.LayoutParams(421, 1639));
        this.vqdshlmhcg.setPadding(33, 137, 13, 45);
        linearLayout.addView(this.vqdshlmhcg);
        this.vqdshlmhcg.setBackgroundColor(Color.parseColor("#18ef7c"));
        FrameLayout frameLayout9 = new FrameLayout(this);
        this.hsejllgxbp = frameLayout9;
        frameLayout9.setLayoutParams(new LinearLayout.LayoutParams(1769, 1592));
        this.hsejllgxbp.setPadding(181, 171, 189, 152);
        linearLayout.addView(this.hsejllgxbp);
        this.hsejllgxbp.setBackgroundColor(Color.parseColor("#b751fe"));
        LinearLayout linearLayout12 = new LinearLayout(this);
        this.hxdbvrzujo = linearLayout12;
        linearLayout12.setLayoutParams(new LinearLayout.LayoutParams(569, 1343));
        this.hxdbvrzujo.setPadding(59, 76, 120, 25);
        linearLayout.addView(this.hxdbvrzujo);
        this.hxdbvrzujo.setBackgroundColor(Color.parseColor("#31a23c"));
        TimePicker timePicker10 = new TimePicker(this);
        this.affntesqoh = timePicker10;
        timePicker10.setLayoutParams(new LinearLayout.LayoutParams(984, 362));
        this.affntesqoh.setPadding(141, BDLocation.TypeServerDecryptError, 171, 80);
        linearLayout.addView(this.affntesqoh);
        this.affntesqoh.setBackgroundColor(Color.parseColor("#2c0f60"));
        RelativeLayout relativeLayout9 = new RelativeLayout(this);
        this.dwgtwjdgho = relativeLayout9;
        relativeLayout9.setLayoutParams(new LinearLayout.LayoutParams(1139, 70));
        this.dwgtwjdgho.setPadding(119, 118, 33, 164);
        linearLayout.addView(this.dwgtwjdgho);
        this.dwgtwjdgho.setBackgroundColor(Color.parseColor("#1c7091"));
        ListView listView12 = new ListView(this);
        this.xurgwepqbl = listView12;
        listView12.setLayoutParams(new LinearLayout.LayoutParams(1914, 1556));
        this.xurgwepqbl.setPadding(67, 115, 113, 88);
        linearLayout.addView(this.xurgwepqbl);
        this.xurgwepqbl.setBackgroundColor(Color.parseColor("#84480e"));
        Spinner spinner19 = new Spinner(this);
        this.nrxhjwwifj = spinner19;
        spinner19.setLayoutParams(new LinearLayout.LayoutParams(660, 828));
        this.nrxhjwwifj.setPadding(19, 1, 12, 108);
        linearLayout.addView(this.nrxhjwwifj);
        this.nrxhjwwifj.setBackgroundColor(Color.parseColor("#faf6e5"));
        RadioButton radioButton9 = new RadioButton(this);
        this.saxwukpkxl = radioButton9;
        radioButton9.setLayoutParams(new LinearLayout.LayoutParams(473, CropImage.PICK_IMAGE_PERMISSIONS_REQUEST_CODE));
        this.saxwukpkxl.setPadding(56, 7, 108, 34);
        linearLayout.addView(this.saxwukpkxl);
        this.saxwukpkxl.setBackgroundColor(Color.parseColor("#f48579"));
        LinearLayout linearLayout13 = new LinearLayout(this);
        this.yzxgzusfli = linearLayout13;
        linearLayout13.setLayoutParams(new LinearLayout.LayoutParams(1906, 1528));
        this.yzxgzusfli.setPadding(103, 133, 121, 41);
        linearLayout.addView(this.yzxgzusfli);
        this.yzxgzusfli.setBackgroundColor(Color.parseColor("#e73fc4"));
        FrameLayout frameLayout10 = new FrameLayout(this);
        this.qvvrowpzxe = frameLayout10;
        frameLayout10.setLayoutParams(new LinearLayout.LayoutParams(1588, 726));
        this.qvvrowpzxe.setPadding(131, 122, 22, 186);
        linearLayout.addView(this.qvvrowpzxe);
        this.qvvrowpzxe.setBackgroundColor(Color.parseColor("#05ddb5"));
        Spinner spinner20 = new Spinner(this);
        this.ydwvyoblic = spinner20;
        spinner20.setLayoutParams(new LinearLayout.LayoutParams(514, 1693));
        this.ydwvyoblic.setPadding(189, 24, 122, PictureConfig.CHOOSE_REQUEST);
        linearLayout.addView(this.ydwvyoblic);
        this.ydwvyoblic.setBackgroundColor(Color.parseColor("#b6721b"));
        RatingBar ratingBar9 = new RatingBar(this);
        this.lginuodspd = ratingBar9;
        ratingBar9.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.PositionType.TYPE_PERCENT_HEIGHT, 1491));
        this.lginuodspd.setPadding(184, 121, 105, 86);
        linearLayout.addView(this.lginuodspd);
        this.lginuodspd.setBackgroundColor(Color.parseColor("#6748e6"));
        ProgressBar progressBar14 = new ProgressBar(this);
        this.wkszaqqplg = progressBar14;
        progressBar14.setLayoutParams(new LinearLayout.LayoutParams(109, 1767));
        this.wkszaqqplg.setPadding(96, 76, 112, 1);
        linearLayout.addView(this.wkszaqqplg);
        this.wkszaqqplg.setBackgroundColor(Color.parseColor("#637eae"));
        DatePicker datePicker11 = new DatePicker(this);
        this.oobspcwewn = datePicker11;
        datePicker11.setLayoutParams(new LinearLayout.LayoutParams(808, 1745));
        this.oobspcwewn.setPadding(74, 10, 168, 128);
        linearLayout.addView(this.oobspcwewn);
        this.oobspcwewn.setBackgroundColor(Color.parseColor("#3a78ce"));
        Button button12 = new Button(this);
        this.jytlryymjr = button12;
        button12.setLayoutParams(new LinearLayout.LayoutParams(1996, 78));
        this.jytlryymjr.setPadding(46, 119, 130, 157);
        linearLayout.addView(this.jytlryymjr);
        this.jytlryymjr.setBackgroundColor(Color.parseColor("#9ac948"));
        TimePicker timePicker11 = new TimePicker(this);
        this.nkeyhlvrsf = timePicker11;
        timePicker11.setLayoutParams(new LinearLayout.LayoutParams(1863, 461));
        this.nkeyhlvrsf.setPadding(33, 70, 90, 177);
        linearLayout.addView(this.nkeyhlvrsf);
        this.nkeyhlvrsf.setBackgroundColor(Color.parseColor("#974a20"));
        CheckBox checkBox9 = new CheckBox(this);
        this.pywedpogye = checkBox9;
        checkBox9.setLayoutParams(new LinearLayout.LayoutParams(1356, BluetoothClassImpl.Device.PERIPHERAL_NON_KEYBOARD_NON_POINTING));
        this.pywedpogye.setPadding(23, 116, 95, 87);
        linearLayout.addView(this.pywedpogye);
        this.pywedpogye.setBackgroundColor(Color.parseColor("#cdf5fd"));
        GridView gridView5 = new GridView(this);
        this.doxshjyvfg = gridView5;
        gridView5.setLayoutParams(new LinearLayout.LayoutParams(761, 1530));
        this.doxshjyvfg.setPadding(61, 80, 191, 61);
        linearLayout.addView(this.doxshjyvfg);
        this.doxshjyvfg.setBackgroundColor(Color.parseColor("#3aabfe"));
        ScrollView scrollView6 = new ScrollView(this);
        this.tkhdqwbtto = scrollView6;
        scrollView6.setLayoutParams(new LinearLayout.LayoutParams(1628, 410));
        this.tkhdqwbtto.setPadding(157, 198, 136, 73);
        linearLayout.addView(this.tkhdqwbtto);
        this.tkhdqwbtto.setBackgroundColor(Color.parseColor("#889b0f"));
        ProgressBar progressBar15 = new ProgressBar(this);
        this.gafhkaunnm = progressBar15;
        progressBar15.setLayoutParams(new LinearLayout.LayoutParams(295, 1641));
        this.gafhkaunnm.setPadding(90, 46, 9, 197);
        linearLayout.addView(this.gafhkaunnm);
        this.gafhkaunnm.setBackgroundColor(Color.parseColor("#2ba1ee"));
        Switch r27 = new Switch(this);
        this.weivjujkzp = r27;
        r27.setLayoutParams(new LinearLayout.LayoutParams(922, 1934));
        this.weivjujkzp.setPadding(178, 21, 15, 190);
        linearLayout.addView(this.weivjujkzp);
        this.weivjujkzp.setBackgroundColor(Color.parseColor("#ab5cb2"));
        GridView gridView6 = new GridView(this);
        this.jdavlghqul = gridView6;
        gridView6.setLayoutParams(new LinearLayout.LayoutParams(200, 1060));
        this.jdavlghqul.setPadding(123, 46, 36, 95);
        linearLayout.addView(this.jdavlghqul);
        this.jdavlghqul.setBackgroundColor(Color.parseColor("#e8d8e7"));
        GridView gridView7 = new GridView(this);
        this.kaakvpepqr = gridView7;
        gridView7.setLayoutParams(new LinearLayout.LayoutParams(874, 1788));
        this.kaakvpepqr.setPadding(45, 85, 75, 85);
        linearLayout.addView(this.kaakvpepqr);
        this.kaakvpepqr.setBackgroundColor(Color.parseColor("#558e76"));
        Switch r28 = new Switch(this);
        this.sfewgdyjgu = r28;
        r28.setLayoutParams(new LinearLayout.LayoutParams(1049, 1773));
        this.sfewgdyjgu.setPadding(55, 25, 87, 198);
        linearLayout.addView(this.sfewgdyjgu);
        this.sfewgdyjgu.setBackgroundColor(Color.parseColor("#70db5f"));
        ViewFlipper viewFlipper6 = new ViewFlipper(this);
        this.bsekdzoldw = viewFlipper6;
        viewFlipper6.setLayoutParams(new LinearLayout.LayoutParams(864, 28));
        this.bsekdzoldw.setPadding(62, 140, 83, 131);
        linearLayout.addView(this.bsekdzoldw);
        this.bsekdzoldw.setBackgroundColor(Color.parseColor("#b33731"));
        ListView listView13 = new ListView(this);
        this.qrkovjkkjd = listView13;
        listView13.setLayoutParams(new LinearLayout.LayoutParams(230, 98));
        this.qrkovjkkjd.setPadding(7, 82, 42, 55);
        linearLayout.addView(this.qrkovjkkjd);
        this.qrkovjkkjd.setBackgroundColor(Color.parseColor("#6912df"));
        ViewFlipper viewFlipper7 = new ViewFlipper(this);
        this.ryruejplyt = viewFlipper7;
        viewFlipper7.setLayoutParams(new LinearLayout.LayoutParams(1777, 1));
        this.ryruejplyt.setPadding(14, 3, 158, 3);
        linearLayout.addView(this.ryruejplyt);
        this.ryruejplyt.setBackgroundColor(Color.parseColor("#69dc50"));
        ToggleButton toggleButton11 = new ToggleButton(this);
        this.ciuoogwlqn = toggleButton11;
        toggleButton11.setLayoutParams(new LinearLayout.LayoutParams(1871, 762));
        this.ciuoogwlqn.setPadding(135, 14, 103, 184);
        linearLayout.addView(this.ciuoogwlqn);
        this.ciuoogwlqn.setBackgroundColor(Color.parseColor("#fafc16"));
        SeekBar seekBar5 = new SeekBar(this);
        this.pmvtuguupe = seekBar5;
        seekBar5.setLayoutParams(new LinearLayout.LayoutParams(695, 1863));
        this.pmvtuguupe.setPadding(41, 123, 170, 8);
        linearLayout.addView(this.pmvtuguupe);
        this.pmvtuguupe.setBackgroundColor(Color.parseColor("#1a21c6"));
        RadioButton radioButton10 = new RadioButton(this);
        this.ywvqiiyhjv = radioButton10;
        radioButton10.setLayoutParams(new LinearLayout.LayoutParams(660, 1575));
        this.ywvqiiyhjv.setPadding(17, 140, 138, 25);
        linearLayout.addView(this.ywvqiiyhjv);
        this.ywvqiiyhjv.setBackgroundColor(Color.parseColor("#f19d3b"));
        TimePicker timePicker12 = new TimePicker(this);
        this.btuxforfmi = timePicker12;
        timePicker12.setLayoutParams(new LinearLayout.LayoutParams(1595, 1044));
        this.btuxforfmi.setPadding(140, 64, 179, 48);
        linearLayout.addView(this.btuxforfmi);
        this.btuxforfmi.setBackgroundColor(Color.parseColor("#d83bff"));
        FrameLayout frameLayout11 = new FrameLayout(this);
        this.bdqngmdcag = frameLayout11;
        frameLayout11.setLayoutParams(new LinearLayout.LayoutParams(1002, 1845));
        this.bdqngmdcag.setPadding(198, 52, 145, 86);
        linearLayout.addView(this.bdqngmdcag);
        this.bdqngmdcag.setBackgroundColor(Color.parseColor("#d7d833"));
        Switch r29 = new Switch(this);
        this.xcimvydjtv = r29;
        r29.setLayoutParams(new LinearLayout.LayoutParams(1801, 1416));
        this.xcimvydjtv.setPadding(151, 56, 120, 153);
        linearLayout.addView(this.xcimvydjtv);
        this.xcimvydjtv.setBackgroundColor(Color.parseColor("#5e3fbb"));
        TableLayout tableLayout19 = new TableLayout(this);
        this.qayvwnqtjz = tableLayout19;
        tableLayout19.setLayoutParams(new LinearLayout.LayoutParams(133, 1992));
        this.qayvwnqtjz.setPadding(158, 11, 37, BDLocation.TypeServerDecryptError);
        linearLayout.addView(this.qayvwnqtjz);
        this.qayvwnqtjz.setBackgroundColor(Color.parseColor("#9bddf5"));
        GridView gridView8 = new GridView(this);
        this.bdmagglbdp = gridView8;
        gridView8.setLayoutParams(new LinearLayout.LayoutParams(703, 1583));
        this.bdmagglbdp.setPadding(13, 155, 138, WebSocketProtocol.PAYLOAD_SHORT);
        linearLayout.addView(this.bdmagglbdp);
        this.bdmagglbdp.setBackgroundColor(Color.parseColor("#a50f86"));
        GridView gridView9 = new GridView(this);
        this.jolrdkoodt = gridView9;
        gridView9.setLayoutParams(new LinearLayout.LayoutParams(173, 449));
        this.jolrdkoodt.setPadding(3, 20, 152, 171);
        linearLayout.addView(this.jolrdkoodt);
        this.jolrdkoodt.setBackgroundColor(Color.parseColor("#5fa803"));
    }
}
