package com.smartapp.b.osqnasdvhc;

import android.app.Activity;
import android.graphics.Color;
import android.os.Bundle;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.CheckBox;
import android.widget.DatePicker;
import android.widget.FrameLayout;
import android.widget.GridView;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ListView;
import android.widget.ProgressBar;
import android.widget.RadioButton;
import android.widget.RatingBar;
import android.widget.RelativeLayout;
import android.widget.ScrollView;
import android.widget.SeekBar;
import android.widget.Spinner;
import android.widget.Switch;
import android.widget.TableLayout;
import android.widget.TextView;
import android.widget.TimePicker;
import android.widget.ToggleButton;
import android.widget.ViewFlipper;
import androidx.constraintlayout.core.motion.utils.TypedValues;
import androidx.core.app.FrameMetricsAggregator;
import com.baidu.location.BDLocation;
import com.luck.picture.lib.config.PictureConfig;
import com.qcwireless.qcwatch.ui.base.imagepicker.cropper.CropImage;
import com.realsil.sdk.core.bluetooth.connection.legacy.BluetoothSpp;
import com.realsil.sdk.core.bluetooth.impl.BluetoothClassImpl;

/* loaded from: classes4.dex */
public class YceggxqgabwActivity extends Activity {
    RelativeLayout adylmrwehk;
    RadioButton atdbraouyn;
    ScrollView atupaexdjj;
    ToggleButton avvovswmby;
    ScrollView bdcoczwulr;
    LinearLayout ccbyqjjcoc;
    ImageView cfdvwozmom;
    ProgressBar cosyhinlfv;
    RadioButton czllcwnezs;
    ImageView dhtnncauzj;
    ViewFlipper djcygliswx;
    ImageView dmrfsrvltk;
    ViewFlipper dnzkisxwsk;
    RelativeLayout dohjulbzhi;
    Switch eaqbvughoq;
    ImageView egkigyjbdl;
    TextView errjwjelfc;
    FrameLayout euvtwruzqm;
    CheckBox ewwkntlbdv;
    DatePicker fcatgyelye;
    TableLayout fwlfhphihm;
    Switch ghrdyicivk;
    CheckBox gibiilzwem;
    RadioButton gnzqcqgjsz;
    ImageView hmarvmzolz;
    RadioButton hrzoisqzev;
    Spinner hukgratkhf;
    TimePicker hyhsetvqxg;
    GridView ilcxviwgmd;
    ToggleButton iustxnyeex;
    RelativeLayout iyaeptdhsr;
    ListView jbfmchprdq;
    ScrollView jkbroivsfs;
    GridView jxqrhjmuxw;
    ScrollView kcyhjyzyfc;
    TimePicker ktuszojmdl;
    Switch kwmyqsgbzf;
    RatingBar kykqgmwjlt;
    ListView lhavgwxchc;
    RelativeLayout lytzirsxea;
    TextView mccfxtqlei;
    Switch mjbvruakql;
    ListView omwzevwdwn;
    ListView opcyiasmpc;
    Spinner oqssxnrlhv;
    RatingBar oratozmlgk;
    Button owazlcacnw;
    ToggleButton pfpocrihea;
    Switch pyudicldfh;
    TextView qabppcrmlv;
    Spinner qatvcopwvt;
    ViewFlipper qdqntacoba;
    Spinner qgnozbelhk;
    DatePicker qlbgsxlcug;
    Spinner qviazolszz;
    ListView qysjymyddh;
    TableLayout reffsybegm;
    TextView robcrhhkzc;
    ViewFlipper sylpxdizlf;
    FrameLayout tannbfzurw;
    LinearLayout tbmnevwmns;
    TextView txhvtzmjty;
    Spinner ukzpjzrcba;
    RelativeLayout veteqvhsbm;
    GridView vnflvchzsw;
    SeekBar vtvuylcdip;
    ProgressBar whkohfyvva;
    RatingBar wlrcqoheuu;
    Spinner wlrjzubaxq;
    TimePicker ybutwmzvuj;
    GridView ywrttrsdyw;
    DatePicker yxbnkvnzax;
    Switch zcffkumlct;
    SeekBar zddtwhbpgm;
    ImageView zdtmkjyxzm;

    @Override // android.app.Activity
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        LinearLayout linearLayout = new LinearLayout(this);
        setContentView(linearLayout);
        linearLayout.setLayoutParams(new ViewGroup.LayoutParams(-1, -1));
        linearLayout.setOrientation(1);
        linearLayout.setBackgroundColor(Color.parseColor("#575e48"));
        ProgressBar progressBar = new ProgressBar(this);
        this.whkohfyvva = progressBar;
        progressBar.setLayoutParams(new LinearLayout.LayoutParams(100, 1925));
        this.whkohfyvva.setPadding(94, 128, 97, 192);
        linearLayout.addView(this.whkohfyvva);
        this.whkohfyvva.setBackgroundColor(Color.parseColor("#d7422d"));
        TimePicker timePicker = new TimePicker(this);
        this.ybutwmzvuj = timePicker;
        timePicker.setLayoutParams(new LinearLayout.LayoutParams(1513, 1954));
        this.ybutwmzvuj.setPadding(130, 170, 48, 110);
        linearLayout.addView(this.ybutwmzvuj);
        this.ybutwmzvuj.setBackgroundColor(Color.parseColor("#cf43e5"));
        ScrollView scrollView = new ScrollView(this);
        this.kcyhjyzyfc = scrollView;
        scrollView.setLayoutParams(new LinearLayout.LayoutParams(294, 49));
        this.kcyhjyzyfc.setPadding(2, 39, 197, 185);
        linearLayout.addView(this.kcyhjyzyfc);
        this.kcyhjyzyfc.setBackgroundColor(Color.parseColor("#cb760a"));
        ListView listView = new ListView(this);
        this.qysjymyddh = listView;
        listView.setLayoutParams(new LinearLayout.LayoutParams(415, 828));
        this.qysjymyddh.setPadding(30, 183, 80, 16);
        linearLayout.addView(this.qysjymyddh);
        this.qysjymyddh.setBackgroundColor(Color.parseColor("#1737ec"));
        RelativeLayout relativeLayout = new RelativeLayout(this);
        this.iyaeptdhsr = relativeLayout;
        relativeLayout.setLayoutParams(new LinearLayout.LayoutParams(766, 1705));
        this.iyaeptdhsr.setPadding(83, 166, 53, 178);
        linearLayout.addView(this.iyaeptdhsr);
        this.iyaeptdhsr.setBackgroundColor(Color.parseColor("#641874"));
        Switch r3 = new Switch(this);
        this.mjbvruakql = r3;
        r3.setLayoutParams(new LinearLayout.LayoutParams(1659, 1272));
        this.mjbvruakql.setPadding(36, 154, BDLocation.TypeServerDecryptError, 184);
        linearLayout.addView(this.mjbvruakql);
        this.mjbvruakql.setBackgroundColor(Color.parseColor("#688536"));
        ImageView imageView = new ImageView(this);
        this.zdtmkjyxzm = imageView;
        imageView.setLayoutParams(new LinearLayout.LayoutParams(46, 191));
        this.zdtmkjyxzm.setPadding(30, 83, 14, 37);
        linearLayout.addView(this.zdtmkjyxzm);
        this.zdtmkjyxzm.setBackground(new Zuadvmydiyj());
        ImageView imageView2 = new ImageView(this);
        this.dmrfsrvltk = imageView2;
        imageView2.setLayoutParams(new LinearLayout.LayoutParams(1570, 1597));
        this.dmrfsrvltk.setPadding(134, 179, 105, 122);
        linearLayout.addView(this.dmrfsrvltk);
        this.dmrfsrvltk.setBackgroundColor(Color.parseColor("#a5b0e3"));
        RadioButton radioButton = new RadioButton(this);
        this.czllcwnezs = radioButton;
        radioButton.setLayoutParams(new LinearLayout.LayoutParams(30, 217));
        this.czllcwnezs.setPadding(180, 1, 42, 141);
        linearLayout.addView(this.czllcwnezs);
        this.czllcwnezs.setBackgroundColor(Color.parseColor("#a25ed9"));
        LinearLayout linearLayout2 = new LinearLayout(this);
        this.tbmnevwmns = linearLayout2;
        linearLayout2.setLayoutParams(new LinearLayout.LayoutParams(1963, TypedValues.PositionType.TYPE_PERCENT_WIDTH));
        this.tbmnevwmns.setPadding(89, 147, 147, 77);
        linearLayout.addView(this.tbmnevwmns);
        this.tbmnevwmns.setBackgroundColor(Color.parseColor("#3c7edf"));
        CheckBox checkBox = new CheckBox(this);
        this.ewwkntlbdv = checkBox;
        checkBox.setLayoutParams(new LinearLayout.LayoutParams(68, 88));
        this.ewwkntlbdv.setPadding(137, 70, 104, 7);
        linearLayout.addView(this.ewwkntlbdv);
        this.ewwkntlbdv.setBackgroundColor(Color.parseColor("#1df656"));
        RelativeLayout relativeLayout2 = new RelativeLayout(this);
        this.lytzirsxea = relativeLayout2;
        relativeLayout2.setLayoutParams(new LinearLayout.LayoutParams(1962, 770));
        this.lytzirsxea.setPadding(22, 151, 88, 165);
        linearLayout.addView(this.lytzirsxea);
        this.lytzirsxea.setBackgroundColor(Color.parseColor("#3e01c5"));
        SeekBar seekBar = new SeekBar(this);
        this.vtvuylcdip = seekBar;
        seekBar.setLayoutParams(new LinearLayout.LayoutParams(656, 248));
        this.vtvuylcdip.setPadding(135, 106, 35, 106);
        linearLayout.addView(this.vtvuylcdip);
        this.vtvuylcdip.setBackgroundColor(Color.parseColor("#e09d08"));
        ImageView imageView3 = new ImageView(this);
        this.cfdvwozmom = imageView3;
        imageView3.setLayoutParams(new LinearLayout.LayoutParams(1421, 1904));
        this.cfdvwozmom.setPadding(19, 101, 145, 52);
        linearLayout.addView(this.cfdvwozmom);
        this.cfdvwozmom.setBackgroundColor(Color.parseColor("#5ee39c"));
        ListView listView2 = new ListView(this);
        this.omwzevwdwn = listView2;
        listView2.setLayoutParams(new LinearLayout.LayoutParams(1378, 1994));
        this.omwzevwdwn.setPadding(148, 103, 53, 14);
        linearLayout.addView(this.omwzevwdwn);
        this.omwzevwdwn.setBackgroundColor(Color.parseColor("#9f2c41"));
        RatingBar ratingBar = new RatingBar(this);
        this.wlrcqoheuu = ratingBar;
        ratingBar.setLayoutParams(new LinearLayout.LayoutParams(1170, 1553));
        this.wlrcqoheuu.setPadding(0, 147, 0, 136);
        linearLayout.addView(this.wlrcqoheuu);
        this.wlrcqoheuu.setBackgroundColor(Color.parseColor("#704572"));
        ToggleButton toggleButton = new ToggleButton(this);
        this.pfpocrihea = toggleButton;
        toggleButton.setLayoutParams(new LinearLayout.LayoutParams(1273, 1497));
        this.pfpocrihea.setPadding(41, PictureConfig.CHOOSE_REQUEST, 97, 44);
        linearLayout.addView(this.pfpocrihea);
        this.pfpocrihea.setBackgroundColor(Color.parseColor("#6896e5"));
        RatingBar ratingBar2 = new RatingBar(this);
        this.kykqgmwjlt = ratingBar2;
        ratingBar2.setLayoutParams(new LinearLayout.LayoutParams(749, 1676));
        this.kykqgmwjlt.setPadding(52, 12, 130, 127);
        linearLayout.addView(this.kykqgmwjlt);
        this.kykqgmwjlt.setBackgroundColor(Color.parseColor("#080ac9"));
        DatePicker datePicker = new DatePicker(this);
        this.fcatgyelye = datePicker;
        datePicker.setLayoutParams(new LinearLayout.LayoutParams(1161, 25));
        this.fcatgyelye.setPadding(151, 157, 13, 65);
        linearLayout.addView(this.fcatgyelye);
        this.fcatgyelye.setBackgroundColor(Color.parseColor("#efecd4"));
        ListView listView3 = new ListView(this);
        this.opcyiasmpc = listView3;
        listView3.setLayoutParams(new LinearLayout.LayoutParams(736, 99));
        this.opcyiasmpc.setPadding(93, 131, 109, 34);
        linearLayout.addView(this.opcyiasmpc);
        this.opcyiasmpc.setBackgroundColor(Color.parseColor("#5fb949"));
        GridView gridView = new GridView(this);
        this.jxqrhjmuxw = gridView;
        gridView.setLayoutParams(new LinearLayout.LayoutParams(374, 586));
        this.jxqrhjmuxw.setPadding(68, 99, 17, 51);
        linearLayout.addView(this.jxqrhjmuxw);
        this.jxqrhjmuxw.setBackgroundColor(Color.parseColor("#1243f9"));
        ViewFlipper viewFlipper = new ViewFlipper(this);
        this.qdqntacoba = viewFlipper;
        viewFlipper.setLayoutParams(new LinearLayout.LayoutParams(1986, 1697));
        this.qdqntacoba.setPadding(70, 5, 59, 109);
        linearLayout.addView(this.qdqntacoba);
        this.qdqntacoba.setBackgroundColor(Color.parseColor("#3b5b2c"));
        Spinner spinner = new Spinner(this);
        this.ukzpjzrcba = spinner;
        spinner.setLayoutParams(new LinearLayout.LayoutParams(407, 1877));
        this.ukzpjzrcba.setPadding(52, 58, 127, 153);
        linearLayout.addView(this.ukzpjzrcba);
        this.ukzpjzrcba.setBackgroundColor(Color.parseColor("#f25c30"));
        TableLayout tableLayout = new TableLayout(this);
        this.reffsybegm = tableLayout;
        tableLayout.setLayoutParams(new LinearLayout.LayoutParams(841, 1821));
        this.reffsybegm.setPadding(199, 145, 14, 19);
        linearLayout.addView(this.reffsybegm);
        this.reffsybegm.setBackgroundColor(Color.parseColor("#b122bf"));
        GridView gridView2 = new GridView(this);
        this.ywrttrsdyw = gridView2;
        gridView2.setLayoutParams(new LinearLayout.LayoutParams(1940, TypedValues.PositionType.TYPE_CURVE_FIT));
        this.ywrttrsdyw.setPadding(153, 196, 81, 141);
        linearLayout.addView(this.ywrttrsdyw);
        this.ywrttrsdyw.setBackgroundColor(Color.parseColor("#3b5594"));
        RelativeLayout relativeLayout3 = new RelativeLayout(this);
        this.dohjulbzhi = relativeLayout3;
        relativeLayout3.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.TransitionType.TYPE_AUTO_TRANSITION, 1543));
        this.dohjulbzhi.setPadding(65, 178, 194, 141);
        linearLayout.addView(this.dohjulbzhi);
        this.dohjulbzhi.setBackgroundColor(Color.parseColor("#c3002f"));
        TextView textView = new TextView(this);
        this.qabppcrmlv = textView;
        textView.setLayoutParams(new LinearLayout.LayoutParams(1385, 1580));
        this.qabppcrmlv.setPadding(132, 113, 142, 156);
        linearLayout.addView(this.qabppcrmlv);
        this.qabppcrmlv.setBackgroundColor(Color.parseColor("#af198a"));
        TextView textView2 = new TextView(this);
        this.errjwjelfc = textView2;
        textView2.setLayoutParams(new LinearLayout.LayoutParams(195, 1849));
        this.errjwjelfc.setPadding(143, 114, 135, 35);
        linearLayout.addView(this.errjwjelfc);
        this.errjwjelfc.setBackgroundColor(Color.parseColor("#eee5c4"));
        RadioButton radioButton2 = new RadioButton(this);
        this.hrzoisqzev = radioButton2;
        radioButton2.setLayoutParams(new LinearLayout.LayoutParams(1426, 1133));
        this.hrzoisqzev.setPadding(170, 193, 14, 35);
        linearLayout.addView(this.hrzoisqzev);
        this.hrzoisqzev.setBackgroundColor(Color.parseColor("#108a30"));
        Spinner spinner2 = new Spinner(this);
        this.oqssxnrlhv = spinner2;
        spinner2.setLayoutParams(new LinearLayout.LayoutParams(1454, 807));
        this.oqssxnrlhv.setPadding(47, 120, 29, 121);
        linearLayout.addView(this.oqssxnrlhv);
        this.oqssxnrlhv.setBackgroundColor(Color.parseColor("#20c0a4"));
        GridView gridView3 = new GridView(this);
        this.vnflvchzsw = gridView3;
        gridView3.setLayoutParams(new LinearLayout.LayoutParams(781, 400));
        this.vnflvchzsw.setPadding(153, 150, 34, 106);
        linearLayout.addView(this.vnflvchzsw);
        this.vnflvchzsw.setBackgroundColor(Color.parseColor("#d3b97e"));
        ListView listView4 = new ListView(this);
        this.jbfmchprdq = listView4;
        listView4.setLayoutParams(new LinearLayout.LayoutParams(451, 238));
        this.jbfmchprdq.setPadding(112, 121, 54, 90);
        linearLayout.addView(this.jbfmchprdq);
        this.jbfmchprdq.setBackgroundColor(Color.parseColor("#0d4a22"));
        ImageView imageView4 = new ImageView(this);
        this.egkigyjbdl = imageView4;
        imageView4.setLayoutParams(new LinearLayout.LayoutParams(636, 622));
        this.egkigyjbdl.setPadding(113, 134, 70, 196);
        linearLayout.addView(this.egkigyjbdl);
        this.egkigyjbdl.setBackgroundColor(Color.parseColor("#c40b32"));
        Button button = new Button(this);
        this.owazlcacnw = button;
        button.setLayoutParams(new LinearLayout.LayoutParams(1073, 1062));
        this.owazlcacnw.setPadding(138, 105, 185, 118);
        linearLayout.addView(this.owazlcacnw);
        this.owazlcacnw.setBackgroundColor(Color.parseColor("#f6fb79"));
        FrameLayout frameLayout = new FrameLayout(this);
        this.euvtwruzqm = frameLayout;
        frameLayout.setLayoutParams(new LinearLayout.LayoutParams(1456, 1214));
        this.euvtwruzqm.setPadding(124, 158, 183, 171);
        linearLayout.addView(this.euvtwruzqm);
        this.euvtwruzqm.setBackgroundColor(Color.parseColor("#a1bc62"));
        TimePicker timePicker2 = new TimePicker(this);
        this.ktuszojmdl = timePicker2;
        timePicker2.setLayoutParams(new LinearLayout.LayoutParams(670, TypedValues.TransitionType.TYPE_STAGGERED));
        this.ktuszojmdl.setPadding(34, 106, 194, 197);
        linearLayout.addView(this.ktuszojmdl);
        this.ktuszojmdl.setBackgroundColor(Color.parseColor("#87aa3c"));
        DatePicker datePicker2 = new DatePicker(this);
        this.qlbgsxlcug = datePicker2;
        datePicker2.setLayoutParams(new LinearLayout.LayoutParams(1808, 1918));
        this.qlbgsxlcug.setPadding(190, 46, 189, BDLocation.TypeServerError);
        linearLayout.addView(this.qlbgsxlcug);
        this.qlbgsxlcug.setBackgroundColor(Color.parseColor("#88ed1f"));
        Switch r2 = new Switch(this);
        this.ghrdyicivk = r2;
        r2.setLayoutParams(new LinearLayout.LayoutParams(927, 365));
        this.ghrdyicivk.setPadding(180, 90, 35, 20);
        linearLayout.addView(this.ghrdyicivk);
        this.ghrdyicivk.setBackgroundColor(Color.parseColor("#70d886"));
        ToggleButton toggleButton2 = new ToggleButton(this);
        this.iustxnyeex = toggleButton2;
        toggleButton2.setLayoutParams(new LinearLayout.LayoutParams(BluetoothClassImpl.Device.PERIPHERAL_POINTING, 1623));
        this.iustxnyeex.setPadding(198, 130, 154, 55);
        linearLayout.addView(this.iustxnyeex);
        this.iustxnyeex.setBackgroundColor(Color.parseColor("#a9e71a"));
        CheckBox checkBox2 = new CheckBox(this);
        this.gibiilzwem = checkBox2;
        checkBox2.setLayoutParams(new LinearLayout.LayoutParams(1883, 830));
        this.gibiilzwem.setPadding(143, 48, 30, 46);
        linearLayout.addView(this.gibiilzwem);
        this.gibiilzwem.setBackgroundColor(Color.parseColor("#735c6a"));
        GridView gridView4 = new GridView(this);
        this.ilcxviwgmd = gridView4;
        gridView4.setLayoutParams(new LinearLayout.LayoutParams(CropImage.CROP_IMAGE_ACTIVITY_REQUEST_CODE, 1404));
        this.ilcxviwgmd.setPadding(28, 85, 138, 92);
        linearLayout.addView(this.ilcxviwgmd);
        this.ilcxviwgmd.setBackgroundColor(Color.parseColor("#658ec7"));
        Spinner spinner3 = new Spinner(this);
        this.qgnozbelhk = spinner3;
        spinner3.setLayoutParams(new LinearLayout.LayoutParams(1148, TypedValues.CycleType.TYPE_ALPHA));
        this.qgnozbelhk.setPadding(84, 61, 57, 115);
        linearLayout.addView(this.qgnozbelhk);
        this.qgnozbelhk.setBackgroundColor(Color.parseColor("#6663bb"));
        ViewFlipper viewFlipper2 = new ViewFlipper(this);
        this.sylpxdizlf = viewFlipper2;
        viewFlipper2.setLayoutParams(new LinearLayout.LayoutParams(939, 138));
        this.sylpxdizlf.setPadding(185, 119, 3, 44);
        linearLayout.addView(this.sylpxdizlf);
        this.sylpxdizlf.setBackgroundColor(Color.parseColor("#4d79a7"));
        SeekBar seekBar2 = new SeekBar(this);
        this.zddtwhbpgm = seekBar2;
        seekBar2.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.MotionType.TYPE_ANIMATE_CIRCLEANGLE_TO, 872));
        this.zddtwhbpgm.setPadding(192, 6, 194, 4);
        linearLayout.addView(this.zddtwhbpgm);
        this.zddtwhbpgm.setBackgroundColor(Color.parseColor("#002b57"));
        TextView textView3 = new TextView(this);
        this.txhvtzmjty = textView3;
        textView3.setLayoutParams(new LinearLayout.LayoutParams(268, 1976));
        this.txhvtzmjty.setPadding(59, BDLocation.TypeServerError, 99, 51);
        linearLayout.addView(this.txhvtzmjty);
        this.txhvtzmjty.setBackgroundColor(Color.parseColor("#2f3e93"));
        Spinner spinner4 = new Spinner(this);
        this.qviazolszz = spinner4;
        spinner4.setLayoutParams(new LinearLayout.LayoutParams(479, 320));
        this.qviazolszz.setPadding(22, 87, BDLocation.TypeNetWorkLocation, 155);
        linearLayout.addView(this.qviazolszz);
        this.qviazolszz.setBackgroundColor(Color.parseColor("#9ced58"));
        Spinner spinner5 = new Spinner(this);
        this.wlrjzubaxq = spinner5;
        spinner5.setLayoutParams(new LinearLayout.LayoutParams(1357, 855));
        this.wlrjzubaxq.setPadding(143, 136, 69, 138);
        linearLayout.addView(this.wlrjzubaxq);
        this.wlrjzubaxq.setBackgroundColor(Color.parseColor("#b623b6"));
        RelativeLayout relativeLayout4 = new RelativeLayout(this);
        this.adylmrwehk = relativeLayout4;
        relativeLayout4.setLayoutParams(new LinearLayout.LayoutParams(157, 1466));
        this.adylmrwehk.setPadding(55, 24, 1, 21);
        linearLayout.addView(this.adylmrwehk);
        this.adylmrwehk.setBackgroundColor(Color.parseColor("#412494"));
        ScrollView scrollView2 = new ScrollView(this);
        this.atupaexdjj = scrollView2;
        scrollView2.setLayoutParams(new LinearLayout.LayoutParams(FrameMetricsAggregator.EVERY_DURATION, 1905));
        this.atupaexdjj.setPadding(62, 143, 124, 3);
        linearLayout.addView(this.atupaexdjj);
        this.atupaexdjj.setBackgroundColor(Color.parseColor("#079e7d"));
        Spinner spinner6 = new Spinner(this);
        this.qatvcopwvt = spinner6;
        spinner6.setLayoutParams(new LinearLayout.LayoutParams(1740, 1516));
        this.qatvcopwvt.setPadding(115, 131, 72, 18);
        linearLayout.addView(this.qatvcopwvt);
        this.qatvcopwvt.setBackgroundColor(Color.parseColor("#195949"));
        LinearLayout linearLayout3 = new LinearLayout(this);
        this.ccbyqjjcoc = linearLayout3;
        linearLayout3.setLayoutParams(new LinearLayout.LayoutParams(1012, 1404));
        this.ccbyqjjcoc.setPadding(89, 33, 54, 169);
        linearLayout.addView(this.ccbyqjjcoc);
        this.ccbyqjjcoc.setBackgroundColor(Color.parseColor("#f6bb27"));
        ViewFlipper viewFlipper3 = new ViewFlipper(this);
        this.dnzkisxwsk = viewFlipper3;
        viewFlipper3.setLayoutParams(new LinearLayout.LayoutParams(1486, 1513));
        this.dnzkisxwsk.setPadding(38, 10, 147, 178);
        linearLayout.addView(this.dnzkisxwsk);
        this.dnzkisxwsk.setBackgroundColor(Color.parseColor("#72d337"));
        FrameLayout frameLayout2 = new FrameLayout(this);
        this.tannbfzurw = frameLayout2;
        frameLayout2.setLayoutParams(new LinearLayout.LayoutParams(1026, 1783));
        this.tannbfzurw.setPadding(61, 168, 11, 35);
        linearLayout.addView(this.tannbfzurw);
        this.tannbfzurw.setBackgroundColor(Color.parseColor("#e0c366"));
        ImageView imageView5 = new ImageView(this);
        this.dhtnncauzj = imageView5;
        imageView5.setLayoutParams(new LinearLayout.LayoutParams(1930, 1005));
        this.dhtnncauzj.setPadding(36, 4, 163, 177);
        linearLayout.addView(this.dhtnncauzj);
        this.dhtnncauzj.setBackgroundColor(Color.parseColor("#4192c7"));
        TableLayout tableLayout2 = new TableLayout(this);
        this.fwlfhphihm = tableLayout2;
        tableLayout2.setLayoutParams(new LinearLayout.LayoutParams(1678, 1499));
        this.fwlfhphihm.setPadding(73, 13, 156, 80);
        linearLayout.addView(this.fwlfhphihm);
        this.fwlfhphihm.setBackgroundColor(Color.parseColor("#167712"));
        ScrollView scrollView3 = new ScrollView(this);
        this.jkbroivsfs = scrollView3;
        scrollView3.setLayoutParams(new LinearLayout.LayoutParams(774, 925));
        this.jkbroivsfs.setPadding(70, 111, 3, 18);
        linearLayout.addView(this.jkbroivsfs);
        this.jkbroivsfs.setBackgroundColor(Color.parseColor("#08e290"));
        DatePicker datePicker3 = new DatePicker(this);
        this.yxbnkvnzax = datePicker3;
        datePicker3.setLayoutParams(new LinearLayout.LayoutParams(1586, 1130));
        this.yxbnkvnzax.setPadding(139, 45, 158, 27);
        linearLayout.addView(this.yxbnkvnzax);
        this.yxbnkvnzax.setBackgroundColor(Color.parseColor("#e11b89"));
        ProgressBar progressBar2 = new ProgressBar(this);
        this.cosyhinlfv = progressBar2;
        progressBar2.setLayoutParams(new LinearLayout.LayoutParams(1134, 75));
        this.cosyhinlfv.setPadding(19, 13, 32, 38);
        linearLayout.addView(this.cosyhinlfv);
        this.cosyhinlfv.setBackgroundColor(Color.parseColor("#657497"));
        Switch r22 = new Switch(this);
        this.eaqbvughoq = r22;
        r22.setLayoutParams(new LinearLayout.LayoutParams(1720, 1761));
        this.eaqbvughoq.setPadding(175, 136, 21, 175);
        linearLayout.addView(this.eaqbvughoq);
        this.eaqbvughoq.setBackgroundColor(Color.parseColor("#eb4bcc"));
        ToggleButton toggleButton3 = new ToggleButton(this);
        this.avvovswmby = toggleButton3;
        toggleButton3.setLayoutParams(new LinearLayout.LayoutParams(427, 463));
        this.avvovswmby.setPadding(64, 98, 41, 181);
        linearLayout.addView(this.avvovswmby);
        this.avvovswmby.setBackgroundColor(Color.parseColor("#ce5493"));
        ImageView imageView6 = new ImageView(this);
        this.hmarvmzolz = imageView6;
        imageView6.setLayoutParams(new LinearLayout.LayoutParams(1342, 168));
        this.hmarvmzolz.setPadding(105, 36, 34, 3);
        linearLayout.addView(this.hmarvmzolz);
        this.hmarvmzolz.setBackgroundColor(Color.parseColor("#a2d2f0"));
        Switch r23 = new Switch(this);
        this.kwmyqsgbzf = r23;
        r23.setLayoutParams(new LinearLayout.LayoutParams(1645, 110));
        this.kwmyqsgbzf.setPadding(169, 83, 13, 66);
        linearLayout.addView(this.kwmyqsgbzf);
        this.kwmyqsgbzf.setBackgroundColor(Color.parseColor("#6e841f"));
        Switch r24 = new Switch(this);
        this.pyudicldfh = r24;
        r24.setLayoutParams(new LinearLayout.LayoutParams(800, 223));
        this.pyudicldfh.setPadding(174, 116, 62, 37);
        linearLayout.addView(this.pyudicldfh);
        this.pyudicldfh.setBackgroundColor(Color.parseColor("#12e74f"));
        TextView textView4 = new TextView(this);
        this.mccfxtqlei = textView4;
        textView4.setLayoutParams(new LinearLayout.LayoutParams(1922, 389));
        this.mccfxtqlei.setPadding(70, 120, 9, 130);
        linearLayout.addView(this.mccfxtqlei);
        this.mccfxtqlei.setBackgroundColor(Color.parseColor("#898b34"));
        RadioButton radioButton3 = new RadioButton(this);
        this.atdbraouyn = radioButton3;
        radioButton3.setLayoutParams(new LinearLayout.LayoutParams(930, 1474));
        this.atdbraouyn.setPadding(144, 30, 28, 81);
        linearLayout.addView(this.atdbraouyn);
        this.atdbraouyn.setBackgroundColor(Color.parseColor("#cf33f7"));
        ListView listView5 = new ListView(this);
        this.lhavgwxchc = listView5;
        listView5.setLayoutParams(new LinearLayout.LayoutParams(749, 1789));
        this.lhavgwxchc.setPadding(71, 185, 23, 196);
        linearLayout.addView(this.lhavgwxchc);
        this.lhavgwxchc.setBackgroundColor(Color.parseColor("#910e05"));
        RelativeLayout relativeLayout5 = new RelativeLayout(this);
        this.veteqvhsbm = relativeLayout5;
        relativeLayout5.setLayoutParams(new LinearLayout.LayoutParams(1876, 1860));
        this.veteqvhsbm.setPadding(31, 111, 140, 2);
        linearLayout.addView(this.veteqvhsbm);
        this.veteqvhsbm.setBackgroundColor(Color.parseColor("#e80ee6"));
        Spinner spinner7 = new Spinner(this);
        this.hukgratkhf = spinner7;
        spinner7.setLayoutParams(new LinearLayout.LayoutParams(1088, 631));
        this.hukgratkhf.setPadding(1, BDLocation.TypeServerDecryptError, 96, 89);
        linearLayout.addView(this.hukgratkhf);
        this.hukgratkhf.setBackgroundColor(Color.parseColor("#2487e7"));
        RadioButton radioButton4 = new RadioButton(this);
        this.gnzqcqgjsz = radioButton4;
        radioButton4.setLayoutParams(new LinearLayout.LayoutParams(1756, 6));
        this.gnzqcqgjsz.setPadding(2, 176, 155, 134);
        linearLayout.addView(this.gnzqcqgjsz);
        this.gnzqcqgjsz.setBackgroundColor(Color.parseColor("#5824d9"));
        ScrollView scrollView4 = new ScrollView(this);
        this.bdcoczwulr = scrollView4;
        scrollView4.setLayoutParams(new LinearLayout.LayoutParams(243, BluetoothSpp.STATE_DISCONNECTING));
        this.bdcoczwulr.setPadding(80, 2, 148, 51);
        linearLayout.addView(this.bdcoczwulr);
        this.bdcoczwulr.setBackgroundColor(Color.parseColor("#681910"));
        Switch r25 = new Switch(this);
        this.zcffkumlct = r25;
        r25.setLayoutParams(new LinearLayout.LayoutParams(496, 400));
        this.zcffkumlct.setPadding(124, 35, 52, 109);
        linearLayout.addView(this.zcffkumlct);
        this.zcffkumlct.setBackgroundColor(Color.parseColor("#993c1d"));
        RatingBar ratingBar3 = new RatingBar(this);
        this.oratozmlgk = ratingBar3;
        ratingBar3.setLayoutParams(new LinearLayout.LayoutParams(220, 1757));
        this.oratozmlgk.setPadding(84, 62, 133, 56);
        linearLayout.addView(this.oratozmlgk);
        this.oratozmlgk.setBackgroundColor(Color.parseColor("#79e01e"));
        ViewFlipper viewFlipper4 = new ViewFlipper(this);
        this.djcygliswx = viewFlipper4;
        viewFlipper4.setLayoutParams(new LinearLayout.LayoutParams(1993, 981));
        this.djcygliswx.setPadding(72, 180, 155, 153);
        linearLayout.addView(this.djcygliswx);
        this.djcygliswx.setBackgroundColor(Color.parseColor("#fa9d7a"));
        TextView textView5 = new TextView(this);
        this.robcrhhkzc = textView5;
        textView5.setLayoutParams(new LinearLayout.LayoutParams(1397, 1982));
        this.robcrhhkzc.setPadding(125, 10, 168, 191);
        linearLayout.addView(this.robcrhhkzc);
        this.robcrhhkzc.setBackgroundColor(Color.parseColor("#f1e648"));
        TimePicker timePicker3 = new TimePicker(this);
        this.hyhsetvqxg = timePicker3;
        timePicker3.setLayoutParams(new LinearLayout.LayoutParams(626, 50));
        this.hyhsetvqxg.setPadding(182, 107, 134, 78);
        linearLayout.addView(this.hyhsetvqxg);
        this.hyhsetvqxg.setBackgroundColor(Color.parseColor("#6eefe6"));
    }
}
