package com.smartapp.b.srmrsubdci;

import android.app.Activity;
import android.graphics.Color;
import android.os.Bundle;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.CheckBox;
import android.widget.DatePicker;
import android.widget.EditText;
import android.widget.FrameLayout;
import android.widget.GridView;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ListView;
import android.widget.ProgressBar;
import android.widget.RadioButton;
import android.widget.RatingBar;
import android.widget.RelativeLayout;
import android.widget.ScrollView;
import android.widget.SeekBar;
import android.widget.Spinner;
import android.widget.Switch;
import android.widget.TableLayout;
import android.widget.TextView;
import android.widget.TimePicker;
import android.widget.ToggleButton;
import android.widget.ViewFlipper;
import androidx.constraintlayout.core.motion.utils.TypedValues;
import androidx.core.app.FrameMetricsAggregator;
import androidx.core.view.PointerIconCompat;
import com.baidu.location.BDLocation;
import com.google.zxing.pdf417.PDF417Common;
import com.king.zxing.util.CodeUtils;
import com.luck.picture.lib.config.PictureConfig;
import com.realsil.sdk.audioconnect.localplayback.LocalPlaybackConstants;
import com.realsil.sdk.bbpro.core.protocol.Contract;
import com.realsil.sdk.core.bluetooth.connection.le.GattClient;
import com.realsil.sdk.core.bluetooth.connection.legacy.BluetoothSpp;
import com.yalantis.ucrop.view.CropImageView;
import okhttp3.internal.ws.WebSocketProtocol;

/* loaded from: classes4.dex */
public class SthvwbicqyrActivity extends Activity {
    RatingBar ahquqzqdsd;
    DatePicker ajlmzttawq;
    Spinner amxblcsfsr;
    RelativeLayout anoagkepls;
    RadioButton anujyrupqq;
    TableLayout aoagrqtcvu;
    ViewFlipper azadfoqpra;
    RatingBar bcrdeqvdei;
    DatePicker bkkwhhdqay;
    ToggleButton bownezjsvh;
    SeekBar bpzsaukbet;
    ImageView brbboryaic;
    RatingBar bzjxncseyg;
    DatePicker ceenuwahll;
    ImageView cgwqdhvfmf;
    ViewFlipper chfgohsdrt;
    TextView chjspxngmg;
    CheckBox cifpckemrh;
    TableLayout cvgrdbnzpo;
    ViewFlipper cvvjesejpl;
    TextView cyilvavmwq;
    ViewFlipper cyswhgmerj;
    RatingBar cyzrhffxbf;
    ToggleButton dfttcdsoxm;
    RelativeLayout dipxrlhxsg;
    LinearLayout dkqjlfnhzj;
    ScrollView dkqmrlvmqp;
    ViewFlipper dmoucweaao;
    SeekBar dptzkvbuod;
    LinearLayout dqkomrdbut;
    TimePicker dwgnlpuzun;
    ListView dxgxisvofa;
    Switch dzrezyhywm;
    SeekBar efehgvrtky;
    RatingBar efgdzscbfl;
    GridView egohcfzsae;
    RelativeLayout eikchwrbaa;
    RelativeLayout einobjfzen;
    TextView elpihlnrib;
    SeekBar erpcrmmmpk;
    DatePicker esyqyndddd;
    ProgressBar evfbxzdxkm;
    GridView exckvmuaka;
    ListView ezjgsmunib;
    TableLayout fddpgxqryy;
    ToggleButton fdimwwmjuf;
    TimePicker ffrfxgjefz;
    EditText ftslhvlool;
    ImageView fvslazskyp;
    RadioButton fwwejacjyu;
    LinearLayout fxdjjhzzfx;
    TextView fxpqiljbde;
    ToggleButton gaeqxswfxh;
    ViewFlipper gawdkiimuo;
    TimePicker giwmqxqdyy;
    DatePicker godlanlkqx;
    SeekBar grmclsfpdm;
    ToggleButton gwdfpgqgbo;
    TimePicker gxklctwwec;
    RadioButton hcdorddxcu;
    Spinner hiwjsqlyfs;
    CheckBox hkaetnrpue;
    SeekBar hmrbfrgrhz;
    TableLayout hoknpjyblb;
    Spinner huxpvzailo;
    ToggleButton hzhaoqjdlp;
    CheckBox iaanaivlnm;
    EditText iaeyrnuplu;
    TableLayout ibvwxvsouz;
    CheckBox icvfboprdd;
    TableLayout ieoqbifttv;
    TextView ihdukloecd;
    RelativeLayout ipkokypsik;
    ViewFlipper iqhoehtjcd;
    ImageView itflmevjtl;
    CheckBox ivvwrfjizx;
    ListView jbzoshbzop;
    ImageView jdlcylnerc;
    LinearLayout jdyynvkshp;
    RelativeLayout jinqmubykn;
    ViewFlipper jiskcjkbom;
    RadioButton jkumnacjrs;
    FrameLayout joewqdzpky;
    ViewFlipper jtdeibctzy;
    Button jusafcyqvu;
    Spinner jxmthxaqoj;
    ToggleButton kextdytxiy;
    TextView kjknyraimt;
    FrameLayout kmaolhccji;
    ViewFlipper kopjcolbwb;
    FrameLayout krqgijfsup;
    TextView kwugmkmdvs;
    TableLayout kyxwsymupr;
    ProgressBar lajfqftoar;
    ProgressBar lfamqceljg;
    TextView lfldbpwbju;
    EditText ltwsbfktsx;
    GridView lwcqctoqne;
    ScrollView lxnfhxqsvm;
    Spinner lylpfqjwae;
    Spinner lyyhfblqhw;
    LinearLayout mbnyodsrth;
    ListView mcnrxnnhfb;
    EditText mftspbimpk;
    CheckBox mhljwamxon;
    GridView mmslrteygl;
    Button mospoawnjx;
    ToggleButton mpfbopdvnz;
    TimePicker mpqfcbebjq;
    Button nbzglaiiwd;
    RelativeLayout nduxdgqysp;
    LinearLayout neirlxajfh;
    SeekBar nhmkrozhso;
    RatingBar niqjgqzuca;
    RelativeLayout nlqcusyyej;
    ViewFlipper nofhtwitoz;
    TableLayout npbxuahhzd;
    TimePicker nrlhsamqer;
    GridView ntblqcinny;
    ScrollView nwyszwizle;
    LinearLayout nxjfkgcqsw;
    LinearLayout nygdohzapd;
    ImageView nykdmoxcwr;
    ListView nysjlrxzlf;
    RelativeLayout oaffbazqhs;
    CheckBox oquudmswjr;
    TimePicker ouaxivpcvs;
    SeekBar ovpupcrbeo;
    RatingBar ovrpgwtarg;
    TableLayout oyipomvcvd;
    EditText ozhawboyzu;
    TableLayout pdpmuokbqh;
    TableLayout pfmdzykrkb;
    SeekBar pgwyktwclz;
    EditText picnmgvqfp;
    LinearLayout pixnefughi;
    RelativeLayout pjljqbbdxy;
    DatePicker pkbgscphiz;
    Button plakotnqjy;
    SeekBar pnlkrfmmmu;
    LinearLayout pnusqtojjl;
    LinearLayout pqdgodoxqx;
    Button pscuadrinl;
    ViewFlipper pxcrtamzxb;
    ScrollView pzcnwaspni;
    RatingBar qaluhyyofv;
    ViewFlipper qhapusdela;
    ListView qjfwlsbpup;
    GridView qljaixmamk;
    RadioButton qlznrxaeut;
    Spinner qqwyavhdoo;
    EditText qwrahhztxw;
    GridView qxzpbbobxk;
    TableLayout qzvaohsljp;
    ImageView rewlildxcc;
    ProgressBar rffhdhoumo;
    TextView riphxvrgrv;
    TableLayout rjqyslxstg;
    TableLayout rlnvejjlqj;
    ScrollView rphepmusac;
    RatingBar rrryaihitf;
    FrameLayout rsvidvvsim;
    TimePicker rtxzdjchie;
    ViewFlipper rwvplurmmq;
    TimePicker sdugtpzdpm;
    GridView sgcwmmgpdb;
    CheckBox shxiausyxv;
    ListView siftphhayq;
    SeekBar sjspuytnxv;
    RatingBar skcsxygroq;
    EditText snzteuawcj;
    ProgressBar soxxnzrpcu;
    DatePicker sqmjnlcxbp;
    FrameLayout sswdkxuolr;
    Button sucqrpjszb;
    TextView suutiygtpu;
    Button suzwmlakjk;
    ViewFlipper swjzqfdxfu;
    RelativeLayout tcttlnajnf;
    TextView teuuygedhj;
    Button tilmqyvizs;
    ListView tntbqzjyou;
    CheckBox tqiogupdnu;
    Switch trsgeglapm;
    GridView tskyogixcp;
    ScrollView tstiwnfusc;
    ToggleButton tswfjphjfe;
    CheckBox ttuzkjcnno;
    Button uatdoblwod;
    DatePicker ubhxcukbjt;
    SeekBar ubvucfzkcv;
    ToggleButton ucvytoxkvn;
    Spinner uczpgvkowy;
    FrameLayout uezadhpzyc;
    EditText ufypbhxvym;
    TimePicker ulwupszebj;
    TimePicker umrpmzzter;
    ToggleButton unvomiksnc;
    ProgressBar upnlpobumk;
    ScrollView urbwbizeev;
    RatingBar urwaorqowj;
    RadioButton urzqoziycn;
    RadioButton utfdmdmnwl;
    RatingBar uthnohcyql;
    ProgressBar uuhvufnoxy;
    Switch uveuokdzte;
    DatePicker uvumnsfguf;
    ProgressBar uwbtpuibub;
    TimePicker uyqbylpmsl;
    Switch vddilondqc;
    GridView veqquxuatj;
    RatingBar vfyvsnkojv;
    DatePicker vgfubwkrdl;
    FrameLayout vjhstasuzg;
    CheckBox vlhcvmgbwa;
    EditText vmvrbaprwa;
    RelativeLayout vnvptjnona;
    EditText vvyirynvzi;
    ScrollView vwznthofas;
    ListView vxdckbsrrz;
    DatePicker vzuypwifch;
    Button wamoegposd;
    ScrollView whwjuetvtq;
    SeekBar wmlqgydahu;
    LinearLayout wmnfojezel;
    ListView wnjcycsmvg;
    DatePicker wnwbztxact;
    GridView wouumgbuwu;
    CheckBox wvtscsqvfu;
    Switch wwhaoujlxi;
    LinearLayout wzbviucijg;
    ScrollView xcaqsrkfew;
    FrameLayout xcwfjbunku;
    Switch xfjzxailsw;
    CheckBox xhywvwrmnj;
    Button xiuelcdfln;
    EditText xktzkwcond;
    TableLayout xpvcwimqca;
    Switch xycppvyixz;
    ListView xzudvfdbpa;
    ListView xzwfxpzskj;
    SeekBar ybdlwcqvcm;
    DatePicker ycafyrjjtr;
    SeekBar ygtftvbaie;
    Spinner yhkplceeqr;
    RatingBar ylnalgcshb;
    Spinner ylvupmvzlr;
    Spinner ymxbdutmay;
    SeekBar yrgijcwhqr;
    ListView yuankpwzrc;
    EditText zdrmcjpypd;
    ToggleButton zlfmuphasq;
    ViewFlipper zrnytcjtsp;
    RatingBar zveebezrul;

    @Override // android.app.Activity
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        LinearLayout linearLayout = new LinearLayout(this);
        setContentView(linearLayout);
        linearLayout.setLayoutParams(new ViewGroup.LayoutParams(-1, -1));
        linearLayout.setOrientation(1);
        linearLayout.setBackgroundColor(Color.parseColor("#6c6108"));
        EditText editText = new EditText(this);
        this.snzteuawcj = editText;
        editText.setLayoutParams(new LinearLayout.LayoutParams(1093, 186));
        this.snzteuawcj.setPadding(107, 86, 140, 5);
        linearLayout.addView(this.snzteuawcj);
        this.snzteuawcj.setBackgroundColor(Color.parseColor("#e158fa"));
        TableLayout tableLayout = new TableLayout(this);
        this.fddpgxqryy = tableLayout;
        tableLayout.setLayoutParams(new LinearLayout.LayoutParams(1029, 82));
        this.fddpgxqryy.setPadding(32, 129, 27, 38);
        linearLayout.addView(this.fddpgxqryy);
        this.fddpgxqryy.setBackgroundColor(Color.parseColor("#7fc4ff"));
        GridView gridView = new GridView(this);
        this.mmslrteygl = gridView;
        gridView.setLayoutParams(new LinearLayout.LayoutParams(1057, 1381));
        this.mmslrteygl.setPadding(148, 4, 55, 146);
        linearLayout.addView(this.mmslrteygl);
        this.mmslrteygl.setBackgroundColor(Color.parseColor("#81faed"));
        RadioButton radioButton = new RadioButton(this);
        this.qlznrxaeut = radioButton;
        radioButton.setLayoutParams(new LinearLayout.LayoutParams(1323, 1273));
        this.qlznrxaeut.setPadding(110, 69, 140, 144);
        linearLayout.addView(this.qlznrxaeut);
        this.qlznrxaeut.setBackgroundColor(Color.parseColor("#d24d69"));
        RatingBar ratingBar = new RatingBar(this);
        this.skcsxygroq = ratingBar;
        ratingBar.setLayoutParams(new LinearLayout.LayoutParams(875, 206));
        this.skcsxygroq.setPadding(88, 168, 165, 8);
        linearLayout.addView(this.skcsxygroq);
        this.skcsxygroq.setBackgroundColor(Color.parseColor("#627cfc"));
        CheckBox checkBox = new CheckBox(this);
        this.tqiogupdnu = checkBox;
        checkBox.setLayoutParams(new LinearLayout.LayoutParams(195, 1511));
        this.tqiogupdnu.setPadding(75, 141, 26, 11);
        linearLayout.addView(this.tqiogupdnu);
        this.tqiogupdnu.setBackgroundColor(Color.parseColor("#58934f"));
        DatePicker datePicker = new DatePicker(this);
        this.esyqyndddd = datePicker;
        datePicker.setLayoutParams(new LinearLayout.LayoutParams(1239, 1199));
        this.esyqyndddd.setPadding(94, 118, 186, 45);
        linearLayout.addView(this.esyqyndddd);
        this.esyqyndddd.setBackgroundColor(Color.parseColor("#89837a"));
        EditText editText2 = new EditText(this);
        this.mftspbimpk = editText2;
        editText2.setLayoutParams(new LinearLayout.LayoutParams(1263, 751));
        this.mftspbimpk.setPadding(59, 26, 171, 35);
        linearLayout.addView(this.mftspbimpk);
        this.mftspbimpk.setBackgroundColor(Color.parseColor("#fcbabb"));
        SeekBar seekBar = new SeekBar(this);
        this.grmclsfpdm = seekBar;
        seekBar.setLayoutParams(new LinearLayout.LayoutParams(436, 357));
        this.grmclsfpdm.setPadding(157, 7, 140, 192);
        linearLayout.addView(this.grmclsfpdm);
        this.grmclsfpdm.setBackgroundColor(Color.parseColor("#7ca46c"));
        Spinner spinner = new Spinner(this);
        this.lyyhfblqhw = spinner;
        spinner.setLayoutParams(new LinearLayout.LayoutParams(1596, 663));
        this.lyyhfblqhw.setPadding(154, 83, 133, 163);
        linearLayout.addView(this.lyyhfblqhw);
        this.lyyhfblqhw.setBackground(new Lriphgjrqil());
        GridView gridView2 = new GridView(this);
        this.egohcfzsae = gridView2;
        gridView2.setLayoutParams(new LinearLayout.LayoutParams(416, 1581));
        this.egohcfzsae.setPadding(138, 110, 3, 11);
        linearLayout.addView(this.egohcfzsae);
        this.egohcfzsae.setBackgroundColor(Color.parseColor("#4ebe8a"));
        TimePicker timePicker = new TimePicker(this);
        this.mpqfcbebjq = timePicker;
        timePicker.setLayoutParams(new LinearLayout.LayoutParams(815, 1832));
        this.mpqfcbebjq.setPadding(47, 152, 31, 29);
        linearLayout.addView(this.mpqfcbebjq);
        this.mpqfcbebjq.setBackgroundColor(Color.parseColor("#ebb0c5"));
        GridView gridView3 = new GridView(this);
        this.wouumgbuwu = gridView3;
        gridView3.setLayoutParams(new LinearLayout.LayoutParams(1434, 405));
        this.wouumgbuwu.setPadding(86, 19, 77, 58);
        linearLayout.addView(this.wouumgbuwu);
        this.wouumgbuwu.setBackgroundColor(Color.parseColor("#627167"));
        Switch r3 = new Switch(this);
        this.dzrezyhywm = r3;
        r3.setLayoutParams(new LinearLayout.LayoutParams(1156, 1839));
        this.dzrezyhywm.setPadding(130, 2, 100, 33);
        linearLayout.addView(this.dzrezyhywm);
        this.dzrezyhywm.setBackgroundColor(Color.parseColor("#859e6c"));
        ViewFlipper viewFlipper = new ViewFlipper(this);
        this.pxcrtamzxb = viewFlipper;
        viewFlipper.setLayoutParams(new LinearLayout.LayoutParams(1165, 1699));
        this.pxcrtamzxb.setPadding(9, 118, 17, 155);
        linearLayout.addView(this.pxcrtamzxb);
        this.pxcrtamzxb.setBackgroundColor(Color.parseColor("#3089f0"));
        ImageView imageView = new ImageView(this);
        this.cgwqdhvfmf = imageView;
        imageView.setLayoutParams(new LinearLayout.LayoutParams(1816, 215));
        this.cgwqdhvfmf.setPadding(40, 12, 137, 155);
        linearLayout.addView(this.cgwqdhvfmf);
        this.cgwqdhvfmf.setBackgroundColor(Color.parseColor("#b5ea45"));
        TimePicker timePicker2 = new TimePicker(this);
        this.uyqbylpmsl = timePicker2;
        timePicker2.setLayoutParams(new LinearLayout.LayoutParams(291, 1050));
        this.uyqbylpmsl.setPadding(171, 73, 89, 163);
        linearLayout.addView(this.uyqbylpmsl);
        this.uyqbylpmsl.setBackgroundColor(Color.parseColor("#597f46"));
        TableLayout tableLayout2 = new TableLayout(this);
        this.pfmdzykrkb = tableLayout2;
        tableLayout2.setLayoutParams(new LinearLayout.LayoutParams(345, 1763));
        this.pfmdzykrkb.setPadding(28, 158, 132, 153);
        linearLayout.addView(this.pfmdzykrkb);
        this.pfmdzykrkb.setBackgroundColor(Color.parseColor("#9b988d"));
        SeekBar seekBar2 = new SeekBar(this);
        this.hmrbfrgrhz = seekBar2;
        seekBar2.setLayoutParams(new LinearLayout.LayoutParams(1967, 1198));
        this.hmrbfrgrhz.setPadding(159, 0, 193, 175);
        linearLayout.addView(this.hmrbfrgrhz);
        this.hmrbfrgrhz.setBackgroundColor(Color.parseColor("#2c40b2"));
        ViewFlipper viewFlipper2 = new ViewFlipper(this);
        this.dmoucweaao = viewFlipper2;
        viewFlipper2.setLayoutParams(new LinearLayout.LayoutParams(1938, 487));
        this.dmoucweaao.setPadding(199, 55, 151, 57);
        linearLayout.addView(this.dmoucweaao);
        this.dmoucweaao.setBackgroundColor(Color.parseColor("#188a5e"));
        SeekBar seekBar3 = new SeekBar(this);
        this.ubvucfzkcv = seekBar3;
        seekBar3.setLayoutParams(new LinearLayout.LayoutParams(1778, 1170));
        this.ubvucfzkcv.setPadding(64, 46, 165, 114);
        linearLayout.addView(this.ubvucfzkcv);
        this.ubvucfzkcv.setBackgroundColor(Color.parseColor("#d9bca3"));
        CheckBox checkBox2 = new CheckBox(this);
        this.icvfboprdd = checkBox2;
        checkBox2.setLayoutParams(new LinearLayout.LayoutParams(165, 315));
        this.icvfboprdd.setPadding(137, 194, 58, 15);
        linearLayout.addView(this.icvfboprdd);
        this.icvfboprdd.setBackgroundColor(Color.parseColor("#893dad"));
        RadioButton radioButton2 = new RadioButton(this);
        this.jkumnacjrs = radioButton2;
        radioButton2.setLayoutParams(new LinearLayout.LayoutParams(338, 1537));
        this.jkumnacjrs.setPadding(125, 4, WebSocketProtocol.PAYLOAD_SHORT, 84);
        linearLayout.addView(this.jkumnacjrs);
        this.jkumnacjrs.setBackgroundColor(Color.parseColor("#e1ac0a"));
        ViewFlipper viewFlipper3 = new ViewFlipper(this);
        this.iqhoehtjcd = viewFlipper3;
        viewFlipper3.setLayoutParams(new LinearLayout.LayoutParams(1952, 8));
        this.iqhoehtjcd.setPadding(70, 186, 3, 85);
        linearLayout.addView(this.iqhoehtjcd);
        this.iqhoehtjcd.setBackgroundColor(Color.parseColor("#818a5c"));
        CheckBox checkBox3 = new CheckBox(this);
        this.cifpckemrh = checkBox3;
        checkBox3.setLayoutParams(new LinearLayout.LayoutParams(339, 226));
        this.cifpckemrh.setPadding(85, 51, 76, 76);
        linearLayout.addView(this.cifpckemrh);
        this.cifpckemrh.setBackgroundColor(Color.parseColor("#c11e8d"));
        ScrollView scrollView = new ScrollView(this);
        this.urbwbizeev = scrollView;
        scrollView.setLayoutParams(new LinearLayout.LayoutParams(1930, 1254));
        this.urbwbizeev.setPadding(145, 23, 192, 98);
        linearLayout.addView(this.urbwbizeev);
        this.urbwbizeev.setBackgroundColor(Color.parseColor("#e72024"));
        RelativeLayout relativeLayout = new RelativeLayout(this);
        this.jinqmubykn = relativeLayout;
        relativeLayout.setLayoutParams(new LinearLayout.LayoutParams(832, 115));
        this.jinqmubykn.setPadding(170, 29, 43, 112);
        linearLayout.addView(this.jinqmubykn);
        this.jinqmubykn.setBackgroundColor(Color.parseColor("#1250d2"));
        ViewFlipper viewFlipper4 = new ViewFlipper(this);
        this.cvvjesejpl = viewFlipper4;
        viewFlipper4.setLayoutParams(new LinearLayout.LayoutParams(614, 997));
        this.cvvjesejpl.setPadding(154, 95, 186, 84);
        linearLayout.addView(this.cvvjesejpl);
        this.cvvjesejpl.setBackgroundColor(Color.parseColor("#f4dadf"));
        EditText editText3 = new EditText(this);
        this.ftslhvlool = editText3;
        editText3.setLayoutParams(new LinearLayout.LayoutParams(561, 751));
        this.ftslhvlool.setPadding(112, 24, 193, 65);
        linearLayout.addView(this.ftslhvlool);
        this.ftslhvlool.setBackgroundColor(Color.parseColor("#30785e"));
        TimePicker timePicker3 = new TimePicker(this);
        this.ouaxivpcvs = timePicker3;
        timePicker3.setLayoutParams(new LinearLayout.LayoutParams(1214, 1393));
        this.ouaxivpcvs.setPadding(1, 135, 34, 22);
        linearLayout.addView(this.ouaxivpcvs);
        this.ouaxivpcvs.setBackgroundColor(Color.parseColor("#5950e6"));
        CheckBox checkBox4 = new CheckBox(this);
        this.oquudmswjr = checkBox4;
        checkBox4.setLayoutParams(new LinearLayout.LayoutParams(1622, 761));
        this.oquudmswjr.setPadding(117, 100, 156, 33);
        linearLayout.addView(this.oquudmswjr);
        this.oquudmswjr.setBackgroundColor(Color.parseColor("#479da0"));
        SeekBar seekBar4 = new SeekBar(this);
        this.efehgvrtky = seekBar4;
        seekBar4.setLayoutParams(new LinearLayout.LayoutParams(1623, 908));
        this.efehgvrtky.setPadding(75, 47, 70, 4);
        linearLayout.addView(this.efehgvrtky);
        this.efehgvrtky.setBackgroundColor(Color.parseColor("#dbcbea"));
        GridView gridView4 = new GridView(this);
        this.veqquxuatj = gridView4;
        gridView4.setLayoutParams(new LinearLayout.LayoutParams(1801, 1248));
        this.veqquxuatj.setPadding(41, 169, 55, 196);
        linearLayout.addView(this.veqquxuatj);
        this.veqquxuatj.setBackgroundColor(Color.parseColor("#3d9409"));
        Button button = new Button(this);
        this.pscuadrinl = button;
        button.setLayoutParams(new LinearLayout.LayoutParams(BDLocation.TypeServerDecryptError, 1225));
        this.pscuadrinl.setPadding(35, 186, 100, 75);
        linearLayout.addView(this.pscuadrinl);
        this.pscuadrinl.setBackgroundColor(Color.parseColor("#7450c5"));
        RatingBar ratingBar2 = new RatingBar(this);
        this.qaluhyyofv = ratingBar2;
        ratingBar2.setLayoutParams(new LinearLayout.LayoutParams(1359, 328));
        this.qaluhyyofv.setPadding(134, 122, 157, 91);
        linearLayout.addView(this.qaluhyyofv);
        this.qaluhyyofv.setBackgroundColor(Color.parseColor("#e6cfc5"));
        Switch r32 = new Switch(this);
        this.xfjzxailsw = r32;
        r32.setLayoutParams(new LinearLayout.LayoutParams(1399, 1308));
        this.xfjzxailsw.setPadding(81, 100, 140, 2);
        linearLayout.addView(this.xfjzxailsw);
        this.xfjzxailsw.setBackgroundColor(Color.parseColor("#8a3a6b"));
        Spinner spinner2 = new Spinner(this);
        this.uczpgvkowy = spinner2;
        spinner2.setLayoutParams(new LinearLayout.LayoutParams(1894, 136));
        this.uczpgvkowy.setPadding(64, 93, 131, 76);
        linearLayout.addView(this.uczpgvkowy);
        this.uczpgvkowy.setBackgroundColor(Color.parseColor("#77ae86"));
        TableLayout tableLayout3 = new TableLayout(this);
        this.hoknpjyblb = tableLayout3;
        tableLayout3.setLayoutParams(new LinearLayout.LayoutParams(1195, 1308));
        this.hoknpjyblb.setPadding(6, 131, 65, 195);
        linearLayout.addView(this.hoknpjyblb);
        this.hoknpjyblb.setBackgroundColor(Color.parseColor("#30306a"));
        TimePicker timePicker4 = new TimePicker(this);
        this.nrlhsamqer = timePicker4;
        timePicker4.setLayoutParams(new LinearLayout.LayoutParams(310, 855));
        this.nrlhsamqer.setPadding(181, 194, 57, 196);
        linearLayout.addView(this.nrlhsamqer);
        this.nrlhsamqer.setBackgroundColor(Color.parseColor("#3f34ed"));
        GridView gridView5 = new GridView(this);
        this.qxzpbbobxk = gridView5;
        gridView5.setLayoutParams(new LinearLayout.LayoutParams(1977, 1));
        this.qxzpbbobxk.setPadding(132, 152, 127, 67);
        linearLayout.addView(this.qxzpbbobxk);
        this.qxzpbbobxk.setBackgroundColor(Color.parseColor("#e7bfd6"));
        ProgressBar progressBar = new ProgressBar(this);
        this.evfbxzdxkm = progressBar;
        progressBar.setLayoutParams(new LinearLayout.LayoutParams(563, PictureConfig.REQUEST_GO_SETTING));
        this.evfbxzdxkm.setPadding(165, 16, 72, 102);
        linearLayout.addView(this.evfbxzdxkm);
        this.evfbxzdxkm.setBackgroundColor(Color.parseColor("#1f54eb"));
        RatingBar ratingBar3 = new RatingBar(this);
        this.cyzrhffxbf = ratingBar3;
        ratingBar3.setLayoutParams(new LinearLayout.LayoutParams(603, 215));
        this.cyzrhffxbf.setPadding(16, 52, 85, 143);
        linearLayout.addView(this.cyzrhffxbf);
        this.cyzrhffxbf.setBackgroundColor(Color.parseColor("#00275a"));
        TextView textView = new TextView(this);
        this.cyilvavmwq = textView;
        textView.setLayoutParams(new LinearLayout.LayoutParams(103, 1434));
        this.cyilvavmwq.setPadding(97, 107, 20, 130);
        linearLayout.addView(this.cyilvavmwq);
        this.cyilvavmwq.setBackgroundColor(Color.parseColor("#563f3d"));
        ListView listView = new ListView(this);
        this.qjfwlsbpup = listView;
        listView.setLayoutParams(new LinearLayout.LayoutParams(1522, 633));
        this.qjfwlsbpup.setPadding(98, 91, 67, 86);
        linearLayout.addView(this.qjfwlsbpup);
        this.qjfwlsbpup.setBackgroundColor(Color.parseColor("#58d508"));
        TableLayout tableLayout4 = new TableLayout(this);
        this.kyxwsymupr = tableLayout4;
        tableLayout4.setLayoutParams(new LinearLayout.LayoutParams(1051, 152));
        this.kyxwsymupr.setPadding(22, 65, 113, 112);
        linearLayout.addView(this.kyxwsymupr);
        this.kyxwsymupr.setBackgroundColor(Color.parseColor("#57f9f2"));
        TimePicker timePicker5 = new TimePicker(this);
        this.ulwupszebj = timePicker5;
        timePicker5.setLayoutParams(new LinearLayout.LayoutParams(296, 599));
        this.ulwupszebj.setPadding(59, 68, 147, BDLocation.TypeServerDecryptError);
        linearLayout.addView(this.ulwupszebj);
        this.ulwupszebj.setBackgroundColor(Color.parseColor("#0592cf"));
        CheckBox checkBox5 = new CheckBox(this);
        this.ttuzkjcnno = checkBox5;
        checkBox5.setLayoutParams(new LinearLayout.LayoutParams(270, 648));
        this.ttuzkjcnno.setPadding(97, 113, 32, 146);
        linearLayout.addView(this.ttuzkjcnno);
        this.ttuzkjcnno.setBackgroundColor(Color.parseColor("#52a6d0"));
        RelativeLayout relativeLayout2 = new RelativeLayout(this);
        this.pjljqbbdxy = relativeLayout2;
        relativeLayout2.setLayoutParams(new LinearLayout.LayoutParams(915, 674));
        this.pjljqbbdxy.setPadding(68, 64, 122, 103);
        linearLayout.addView(this.pjljqbbdxy);
        this.pjljqbbdxy.setBackgroundColor(Color.parseColor("#8dc739"));
        TableLayout tableLayout5 = new TableLayout(this);
        this.qzvaohsljp = tableLayout5;
        tableLayout5.setLayoutParams(new LinearLayout.LayoutParams(1227, 779));
        this.qzvaohsljp.setPadding(171, 19, 42, 14);
        linearLayout.addView(this.qzvaohsljp);
        this.qzvaohsljp.setBackgroundColor(Color.parseColor("#831361"));
        LinearLayout linearLayout2 = new LinearLayout(this);
        this.pixnefughi = linearLayout2;
        linearLayout2.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.MotionType.TYPE_QUANTIZE_INTERPOLATOR_TYPE, 1707));
        this.pixnefughi.setPadding(124, 103, 191, 11);
        linearLayout.addView(this.pixnefughi);
        this.pixnefughi.setBackgroundColor(Color.parseColor("#0e4579"));
        Button button2 = new Button(this);
        this.jusafcyqvu = button2;
        button2.setLayoutParams(new LinearLayout.LayoutParams(1493, 677));
        this.jusafcyqvu.setPadding(94, 180, 42, 170);
        linearLayout.addView(this.jusafcyqvu);
        this.jusafcyqvu.setBackgroundColor(Color.parseColor("#19581f"));
        TableLayout tableLayout6 = new TableLayout(this);
        this.xpvcwimqca = tableLayout6;
        tableLayout6.setLayoutParams(new LinearLayout.LayoutParams(1697, 312));
        this.xpvcwimqca.setPadding(113, 79, 137, 148);
        linearLayout.addView(this.xpvcwimqca);
        this.xpvcwimqca.setBackgroundColor(Color.parseColor("#1d51d4"));
        Button button3 = new Button(this);
        this.plakotnqjy = button3;
        button3.setLayoutParams(new LinearLayout.LayoutParams(861, 556));
        this.plakotnqjy.setPadding(140, 184, 46, 39);
        linearLayout.addView(this.plakotnqjy);
        this.plakotnqjy.setBackgroundColor(Color.parseColor("#7083ba"));
        TableLayout tableLayout7 = new TableLayout(this);
        this.pdpmuokbqh = tableLayout7;
        tableLayout7.setLayoutParams(new LinearLayout.LayoutParams(BDLocation.TypeNetWorkLocation, 1984));
        this.pdpmuokbqh.setPadding(PictureConfig.CHOOSE_REQUEST, 102, 147, 190);
        linearLayout.addView(this.pdpmuokbqh);
        this.pdpmuokbqh.setBackgroundColor(Color.parseColor("#4343ab"));
        SeekBar seekBar5 = new SeekBar(this);
        this.erpcrmmmpk = seekBar5;
        seekBar5.setLayoutParams(new LinearLayout.LayoutParams(1337, 839));
        this.erpcrmmmpk.setPadding(77, 46, 117, 120);
        linearLayout.addView(this.erpcrmmmpk);
        this.erpcrmmmpk.setBackgroundColor(Color.parseColor("#be6de9"));
        TextView textView2 = new TextView(this);
        this.lfldbpwbju = textView2;
        textView2.setLayoutParams(new LinearLayout.LayoutParams(352, 1355));
        this.lfldbpwbju.setPadding(32, 123, 59, 67);
        linearLayout.addView(this.lfldbpwbju);
        this.lfldbpwbju.setBackgroundColor(Color.parseColor("#b9f19b"));
        LinearLayout linearLayout3 = new LinearLayout(this);
        this.mbnyodsrth = linearLayout3;
        linearLayout3.setLayoutParams(new LinearLayout.LayoutParams(1565, 785));
        this.mbnyodsrth.setPadding(168, 24, 49, 152);
        linearLayout.addView(this.mbnyodsrth);
        this.mbnyodsrth.setBackgroundColor(Color.parseColor("#3b8120"));
        ToggleButton toggleButton = new ToggleButton(this);
        this.dfttcdsoxm = toggleButton;
        toggleButton.setLayoutParams(new LinearLayout.LayoutParams(37, 899));
        this.dfttcdsoxm.setPadding(34, 89, 141, 138);
        linearLayout.addView(this.dfttcdsoxm);
        this.dfttcdsoxm.setBackgroundColor(Color.parseColor("#79bbe8"));
        TableLayout tableLayout8 = new TableLayout(this);
        this.oyipomvcvd = tableLayout8;
        tableLayout8.setLayoutParams(new LinearLayout.LayoutParams(1493, 1140));
        this.oyipomvcvd.setPadding(104, 113, 13, 176);
        linearLayout.addView(this.oyipomvcvd);
        this.oyipomvcvd.setBackgroundColor(Color.parseColor("#bf8422"));
        LinearLayout linearLayout4 = new LinearLayout(this);
        this.dqkomrdbut = linearLayout4;
        linearLayout4.setLayoutParams(new LinearLayout.LayoutParams(962, 1750));
        this.dqkomrdbut.setPadding(81, 124, 187, BDLocation.TypeNetWorkLocation);
        linearLayout.addView(this.dqkomrdbut);
        this.dqkomrdbut.setBackgroundColor(Color.parseColor("#1c9861"));
        TableLayout tableLayout9 = new TableLayout(this);
        this.cvgrdbnzpo = tableLayout9;
        tableLayout9.setLayoutParams(new LinearLayout.LayoutParams(279, 815));
        this.cvgrdbnzpo.setPadding(71, 37, 78, 143);
        linearLayout.addView(this.cvgrdbnzpo);
        this.cvgrdbnzpo.setBackgroundColor(Color.parseColor("#6e7f0d"));
        FrameLayout frameLayout = new FrameLayout(this);
        this.rsvidvvsim = frameLayout;
        frameLayout.setLayoutParams(new LinearLayout.LayoutParams(34, 1794));
        this.rsvidvvsim.setPadding(189, 51, 127, 60);
        linearLayout.addView(this.rsvidvvsim);
        this.rsvidvvsim.setBackgroundColor(Color.parseColor("#b4e19a"));
        ScrollView scrollView2 = new ScrollView(this);
        this.pzcnwaspni = scrollView2;
        scrollView2.setLayoutParams(new LinearLayout.LayoutParams(20, 1985));
        this.pzcnwaspni.setPadding(45, 53, 197, 96);
        linearLayout.addView(this.pzcnwaspni);
        this.pzcnwaspni.setBackgroundColor(Color.parseColor("#498b25"));
        GridView gridView6 = new GridView(this);
        this.qljaixmamk = gridView6;
        gridView6.setLayoutParams(new LinearLayout.LayoutParams(476, 1495));
        this.qljaixmamk.setPadding(35, 197, 197, 4);
        linearLayout.addView(this.qljaixmamk);
        this.qljaixmamk.setBackgroundColor(Color.parseColor("#a416c0"));
        ToggleButton toggleButton2 = new ToggleButton(this);
        this.bownezjsvh = toggleButton2;
        toggleButton2.setLayoutParams(new LinearLayout.LayoutParams(118, 1196));
        this.bownezjsvh.setPadding(1, BDLocation.TypeNetWorkLocation, 177, 16);
        linearLayout.addView(this.bownezjsvh);
        this.bownezjsvh.setBackgroundColor(Color.parseColor("#11d24a"));
        FrameLayout frameLayout2 = new FrameLayout(this);
        this.krqgijfsup = frameLayout2;
        frameLayout2.setLayoutParams(new LinearLayout.LayoutParams(653, 122));
        this.krqgijfsup.setPadding(198, 69, 12, 17);
        linearLayout.addView(this.krqgijfsup);
        this.krqgijfsup.setBackgroundColor(Color.parseColor("#1de2f9"));
        EditText editText4 = new EditText(this);
        this.vmvrbaprwa = editText4;
        editText4.setLayoutParams(new LinearLayout.LayoutParams(Contract.CMD_SET_VERSION.V1_2, 484));
        this.vmvrbaprwa.setPadding(PictureConfig.CHOOSE_REQUEST, 29, 8, 102);
        linearLayout.addView(this.vmvrbaprwa);
        this.vmvrbaprwa.setBackgroundColor(Color.parseColor("#912ce3"));
        RelativeLayout relativeLayout3 = new RelativeLayout(this);
        this.vnvptjnona = relativeLayout3;
        relativeLayout3.setLayoutParams(new LinearLayout.LayoutParams(1136, 1149));
        this.vnvptjnona.setPadding(6, 47, 124, 121);
        linearLayout.addView(this.vnvptjnona);
        this.vnvptjnona.setBackgroundColor(Color.parseColor("#a00a34"));
        ImageView imageView2 = new ImageView(this);
        this.jdlcylnerc = imageView2;
        imageView2.setLayoutParams(new LinearLayout.LayoutParams(150, 270));
        this.jdlcylnerc.setPadding(172, 45, 142, 170);
        linearLayout.addView(this.jdlcylnerc);
        this.jdlcylnerc.setBackgroundColor(Color.parseColor("#1e1e37"));
        CheckBox checkBox6 = new CheckBox(this);
        this.ivvwrfjizx = checkBox6;
        checkBox6.setLayoutParams(new LinearLayout.LayoutParams(1416, 936));
        this.ivvwrfjizx.setPadding(171, 9, BDLocation.TypeCoarseLocation, 103);
        linearLayout.addView(this.ivvwrfjizx);
        this.ivvwrfjizx.setBackgroundColor(Color.parseColor("#145515"));
        LinearLayout linearLayout5 = new LinearLayout(this);
        this.wmnfojezel = linearLayout5;
        linearLayout5.setLayoutParams(new LinearLayout.LayoutParams(GattClient.STATE_READ_DEVICE_INFO, 945));
        this.wmnfojezel.setPadding(29, 18, 66, 175);
        linearLayout.addView(this.wmnfojezel);
        this.wmnfojezel.setBackgroundColor(Color.parseColor("#f32e3f"));
        TimePicker timePicker6 = new TimePicker(this);
        this.sdugtpzdpm = timePicker6;
        timePicker6.setLayoutParams(new LinearLayout.LayoutParams(483, 1076));
        this.sdugtpzdpm.setPadding(153, 99, 36, 142);
        linearLayout.addView(this.sdugtpzdpm);
        this.sdugtpzdpm.setBackgroundColor(Color.parseColor("#98a7e9"));
        RatingBar ratingBar4 = new RatingBar(this);
        this.efgdzscbfl = ratingBar4;
        ratingBar4.setLayoutParams(new LinearLayout.LayoutParams(658, 777));
        this.efgdzscbfl.setPadding(136, 43, 87, 154);
        linearLayout.addView(this.efgdzscbfl);
        this.efgdzscbfl.setBackgroundColor(Color.parseColor("#042713"));
        ViewFlipper viewFlipper5 = new ViewFlipper(this);
        this.chfgohsdrt = viewFlipper5;
        viewFlipper5.setLayoutParams(new LinearLayout.LayoutParams(1063, 1467));
        this.chfgohsdrt.setPadding(181, 32, 191, 35);
        linearLayout.addView(this.chfgohsdrt);
        this.chfgohsdrt.setBackgroundColor(Color.parseColor("#6871c1"));
        SeekBar seekBar6 = new SeekBar(this);
        this.bpzsaukbet = seekBar6;
        seekBar6.setLayoutParams(new LinearLayout.LayoutParams(1497, 1120));
        this.bpzsaukbet.setPadding(54, 69, 63, 89);
        linearLayout.addView(this.bpzsaukbet);
        this.bpzsaukbet.setBackgroundColor(Color.parseColor("#dde293"));
        DatePicker datePicker2 = new DatePicker(this);
        this.ajlmzttawq = datePicker2;
        datePicker2.setLayoutParams(new LinearLayout.LayoutParams(727, 1338));
        this.ajlmzttawq.setPadding(20, 163, 129, 191);
        linearLayout.addView(this.ajlmzttawq);
        this.ajlmzttawq.setBackgroundColor(Color.parseColor("#4750c5"));
        Button button4 = new Button(this);
        this.mospoawnjx = button4;
        button4.setLayoutParams(new LinearLayout.LayoutParams(1510, 1156));
        this.mospoawnjx.setPadding(101, 124, 64, 22);
        linearLayout.addView(this.mospoawnjx);
        this.mospoawnjx.setBackgroundColor(Color.parseColor("#43afcd"));
        RatingBar ratingBar5 = new RatingBar(this);
        this.rrryaihitf = ratingBar5;
        ratingBar5.setLayoutParams(new LinearLayout.LayoutParams(718, 1184));
        this.rrryaihitf.setPadding(10, 147, 109, 139);
        linearLayout.addView(this.rrryaihitf);
        this.rrryaihitf.setBackgroundColor(Color.parseColor("#56e9d4"));
        RatingBar ratingBar6 = new RatingBar(this);
        this.ahquqzqdsd = ratingBar6;
        ratingBar6.setLayoutParams(new LinearLayout.LayoutParams(1401, 1380));
        this.ahquqzqdsd.setPadding(96, 104, 194, 122);
        linearLayout.addView(this.ahquqzqdsd);
        this.ahquqzqdsd.setBackgroundColor(Color.parseColor("#7e8b2b"));
        ImageView imageView3 = new ImageView(this);
        this.brbboryaic = imageView3;
        imageView3.setLayoutParams(new LinearLayout.LayoutParams(1137, 1341));
        this.brbboryaic.setPadding(175, 32, 14, 43);
        linearLayout.addView(this.brbboryaic);
        this.brbboryaic.setBackgroundColor(Color.parseColor("#f7452a"));
        TimePicker timePicker7 = new TimePicker(this);
        this.gxklctwwec = timePicker7;
        timePicker7.setLayoutParams(new LinearLayout.LayoutParams(1693, 1683));
        this.gxklctwwec.setPadding(42, 146, 133, 114);
        linearLayout.addView(this.gxklctwwec);
        this.gxklctwwec.setBackgroundColor(Color.parseColor("#71dd43"));
        RelativeLayout relativeLayout4 = new RelativeLayout(this);
        this.tcttlnajnf = relativeLayout4;
        relativeLayout4.setLayoutParams(new LinearLayout.LayoutParams(576, 996));
        this.tcttlnajnf.setPadding(26, 29, 179, 93);
        linearLayout.addView(this.tcttlnajnf);
        this.tcttlnajnf.setBackgroundColor(Color.parseColor("#19b97d"));
        ScrollView scrollView3 = new ScrollView(this);
        this.lxnfhxqsvm = scrollView3;
        scrollView3.setLayoutParams(new LinearLayout.LayoutParams(822, 453));
        this.lxnfhxqsvm.setPadding(67, 69, 166, 134);
        linearLayout.addView(this.lxnfhxqsvm);
        this.lxnfhxqsvm.setBackgroundColor(Color.parseColor("#35000e"));
        ToggleButton toggleButton3 = new ToggleButton(this);
        this.fdimwwmjuf = toggleButton3;
        toggleButton3.setLayoutParams(new LinearLayout.LayoutParams(1283, 1434));
        this.fdimwwmjuf.setPadding(49, 124, 182, 88);
        linearLayout.addView(this.fdimwwmjuf);
        this.fdimwwmjuf.setBackgroundColor(Color.parseColor("#c2d789"));
        ScrollView scrollView4 = new ScrollView(this);
        this.nwyszwizle = scrollView4;
        scrollView4.setLayoutParams(new LinearLayout.LayoutParams(834, 430));
        this.nwyszwizle.setPadding(79, 22, 26, 181);
        linearLayout.addView(this.nwyszwizle);
        this.nwyszwizle.setBackgroundColor(Color.parseColor("#9cbcbe"));
        ToggleButton toggleButton4 = new ToggleButton(this);
        this.ucvytoxkvn = toggleButton4;
        toggleButton4.setLayoutParams(new LinearLayout.LayoutParams(80, 1925));
        this.ucvytoxkvn.setPadding(196, 86, 0, 118);
        linearLayout.addView(this.ucvytoxkvn);
        this.ucvytoxkvn.setBackgroundColor(Color.parseColor("#ec23ee"));
        TextView textView3 = new TextView(this);
        this.ihdukloecd = textView3;
        textView3.setLayoutParams(new LinearLayout.LayoutParams(1371, 1766));
        this.ihdukloecd.setPadding(36, 172, 96, 59);
        linearLayout.addView(this.ihdukloecd);
        this.ihdukloecd.setBackgroundColor(Color.parseColor("#cba989"));
        TextView textView4 = new TextView(this);
        this.teuuygedhj = textView4;
        textView4.setLayoutParams(new LinearLayout.LayoutParams(1218, 1534));
        this.teuuygedhj.setPadding(176, 9, 21, 194);
        linearLayout.addView(this.teuuygedhj);
        this.teuuygedhj.setBackgroundColor(Color.parseColor("#0f88f4"));
        EditText editText5 = new EditText(this);
        this.zdrmcjpypd = editText5;
        editText5.setLayoutParams(new LinearLayout.LayoutParams(722, GattClient.STATE_PREPARE_CONNECTING));
        this.zdrmcjpypd.setPadding(163, 170, 185, 60);
        linearLayout.addView(this.zdrmcjpypd);
        this.zdrmcjpypd.setBackgroundColor(Color.parseColor("#a990ab"));
        RadioButton radioButton3 = new RadioButton(this);
        this.hcdorddxcu = radioButton3;
        radioButton3.setLayoutParams(new LinearLayout.LayoutParams(450, 1328));
        this.hcdorddxcu.setPadding(81, 32, 12, 98);
        linearLayout.addView(this.hcdorddxcu);
        this.hcdorddxcu.setBackgroundColor(Color.parseColor("#1de224"));
        DatePicker datePicker3 = new DatePicker(this);
        this.wnwbztxact = datePicker3;
        datePicker3.setLayoutParams(new LinearLayout.LayoutParams(1988, 1038));
        this.wnwbztxact.setPadding(37, 137, 154, 79);
        linearLayout.addView(this.wnwbztxact);
        this.wnwbztxact.setBackgroundColor(Color.parseColor("#d1a3e4"));
        GridView gridView7 = new GridView(this);
        this.exckvmuaka = gridView7;
        gridView7.setLayoutParams(new LinearLayout.LayoutParams(1889, 1719));
        this.exckvmuaka.setPadding(190, BDLocation.TypeServerError, 134, 127);
        linearLayout.addView(this.exckvmuaka);
        this.exckvmuaka.setBackgroundColor(Color.parseColor("#c26535"));
        ViewFlipper viewFlipper6 = new ViewFlipper(this);
        this.gawdkiimuo = viewFlipper6;
        viewFlipper6.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.CycleType.TYPE_WAVE_PERIOD, 87));
        this.gawdkiimuo.setPadding(149, 118, 95, 45);
        linearLayout.addView(this.gawdkiimuo);
        this.gawdkiimuo.setBackgroundColor(Color.parseColor("#f3650e"));
        Switch r33 = new Switch(this);
        this.uveuokdzte = r33;
        r33.setLayoutParams(new LinearLayout.LayoutParams(1226, 1059));
        this.uveuokdzte.setPadding(136, 116, 157, 145);
        linearLayout.addView(this.uveuokdzte);
        this.uveuokdzte.setBackgroundColor(Color.parseColor("#89c808"));
        RatingBar ratingBar7 = new RatingBar(this);
        this.uthnohcyql = ratingBar7;
        ratingBar7.setLayoutParams(new LinearLayout.LayoutParams(1341, 1106));
        this.uthnohcyql.setPadding(139, 179, 184, 192);
        linearLayout.addView(this.uthnohcyql);
        this.uthnohcyql.setBackgroundColor(Color.parseColor("#b130f5"));
        ScrollView scrollView5 = new ScrollView(this);
        this.vwznthofas = scrollView5;
        scrollView5.setLayoutParams(new LinearLayout.LayoutParams(1091, 1459));
        this.vwznthofas.setPadding(169, 104, 94, 141);
        linearLayout.addView(this.vwznthofas);
        this.vwznthofas.setBackgroundColor(Color.parseColor("#01ff5b"));
        TableLayout tableLayout10 = new TableLayout(this);
        this.rlnvejjlqj = tableLayout10;
        tableLayout10.setLayoutParams(new LinearLayout.LayoutParams(1758, 1073));
        this.rlnvejjlqj.setPadding(63, 102, 30, PictureConfig.CHOOSE_REQUEST);
        linearLayout.addView(this.rlnvejjlqj);
        this.rlnvejjlqj.setBackgroundColor(Color.parseColor("#cb9ba4"));
        TableLayout tableLayout11 = new TableLayout(this);
        this.ibvwxvsouz = tableLayout11;
        tableLayout11.setLayoutParams(new LinearLayout.LayoutParams(683, 523));
        this.ibvwxvsouz.setPadding(175, 101, 54, 7);
        linearLayout.addView(this.ibvwxvsouz);
        this.ibvwxvsouz.setBackgroundColor(Color.parseColor("#13ecd4"));
        RadioButton radioButton4 = new RadioButton(this);
        this.anujyrupqq = radioButton4;
        radioButton4.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.TransitionType.TYPE_AUTO_TRANSITION, 216));
        this.anujyrupqq.setPadding(48, 28, 69, 130);
        linearLayout.addView(this.anujyrupqq);
        this.anujyrupqq.setBackgroundColor(Color.parseColor("#53bd9c"));
        ListView listView2 = new ListView(this);
        this.xzudvfdbpa = listView2;
        listView2.setLayoutParams(new LinearLayout.LayoutParams(1755, 1663));
        this.xzudvfdbpa.setPadding(BDLocation.TypeNetWorkLocation, 94, 102, 137);
        linearLayout.addView(this.xzudvfdbpa);
        this.xzudvfdbpa.setBackgroundColor(Color.parseColor("#420f45"));
        DatePicker datePicker4 = new DatePicker(this);
        this.vzuypwifch = datePicker4;
        datePicker4.setLayoutParams(new LinearLayout.LayoutParams(1265, 652));
        this.vzuypwifch.setPadding(45, 10, 27, 184);
        linearLayout.addView(this.vzuypwifch);
        this.vzuypwifch.setBackgroundColor(Color.parseColor("#41e330"));
        ScrollView scrollView6 = new ScrollView(this);
        this.whwjuetvtq = scrollView6;
        scrollView6.setLayoutParams(new LinearLayout.LayoutParams(792, 1542));
        this.whwjuetvtq.setPadding(103, 83, 178, 146);
        linearLayout.addView(this.whwjuetvtq);
        this.whwjuetvtq.setBackgroundColor(Color.parseColor("#74f210"));
        Spinner spinner3 = new Spinner(this);
        this.ymxbdutmay = spinner3;
        spinner3.setLayoutParams(new LinearLayout.LayoutParams(986, 1813));
        this.ymxbdutmay.setPadding(131, 62, 94, 171);
        linearLayout.addView(this.ymxbdutmay);
        this.ymxbdutmay.setBackgroundColor(Color.parseColor("#c061b3"));
        DatePicker datePicker5 = new DatePicker(this);
        this.bkkwhhdqay = datePicker5;
        datePicker5.setLayoutParams(new LinearLayout.LayoutParams(974, 856));
        this.bkkwhhdqay.setPadding(157, 67, 36, 168);
        linearLayout.addView(this.bkkwhhdqay);
        this.bkkwhhdqay.setBackgroundColor(Color.parseColor("#15348e"));
        ListView listView3 = new ListView(this);
        this.yuankpwzrc = listView3;
        listView3.setLayoutParams(new LinearLayout.LayoutParams(GattClient.STATE_READ_PROTOCOL_TYPE, 1292));
        this.yuankpwzrc.setPadding(49, 147, 16, 199);
        linearLayout.addView(this.yuankpwzrc);
        this.yuankpwzrc.setBackgroundColor(Color.parseColor("#918f7f"));
        LinearLayout linearLayout6 = new LinearLayout(this);
        this.nxjfkgcqsw = linearLayout6;
        linearLayout6.setLayoutParams(new LinearLayout.LayoutParams(1702, 1697));
        this.nxjfkgcqsw.setPadding(175, 184, 108, 152);
        linearLayout.addView(this.nxjfkgcqsw);
        this.nxjfkgcqsw.setBackgroundColor(Color.parseColor("#b984f8"));
        ToggleButton toggleButton5 = new ToggleButton(this);
        this.gaeqxswfxh = toggleButton5;
        toggleButton5.setLayoutParams(new LinearLayout.LayoutParams(1509, 14));
        this.gaeqxswfxh.setPadding(122, 139, 85, 145);
        linearLayout.addView(this.gaeqxswfxh);
        this.gaeqxswfxh.setBackgroundColor(Color.parseColor("#912da4"));
        RatingBar ratingBar8 = new RatingBar(this);
        this.vfyvsnkojv = ratingBar8;
        ratingBar8.setLayoutParams(new LinearLayout.LayoutParams(1791, TypedValues.AttributesType.TYPE_PATH_ROTATE));
        this.vfyvsnkojv.setPadding(93, 144, 154, 65);
        linearLayout.addView(this.vfyvsnkojv);
        this.vfyvsnkojv.setBackgroundColor(Color.parseColor("#f0472b"));
        RatingBar ratingBar9 = new RatingBar(this);
        this.niqjgqzuca = ratingBar9;
        ratingBar9.setLayoutParams(new LinearLayout.LayoutParams(PointerIconCompat.TYPE_ZOOM_OUT, 1976));
        this.niqjgqzuca.setPadding(10, 156, 74, 68);
        linearLayout.addView(this.niqjgqzuca);
        this.niqjgqzuca.setBackgroundColor(Color.parseColor("#931a54"));
        EditText editText6 = new EditText(this);
        this.iaeyrnuplu = editText6;
        editText6.setLayoutParams(new LinearLayout.LayoutParams(1047, TypedValues.CycleType.TYPE_WAVE_PHASE));
        this.iaeyrnuplu.setPadding(47, 166, 168, 45);
        linearLayout.addView(this.iaeyrnuplu);
        this.iaeyrnuplu.setBackgroundColor(Color.parseColor("#5e1904"));
        Button button5 = new Button(this);
        this.wamoegposd = button5;
        button5.setLayoutParams(new LinearLayout.LayoutParams(399, 42));
        this.wamoegposd.setPadding(190, 92, 142, 186);
        linearLayout.addView(this.wamoegposd);
        this.wamoegposd.setBackgroundColor(Color.parseColor("#ec0f35"));
        TableLayout tableLayout12 = new TableLayout(this);
        this.aoagrqtcvu = tableLayout12;
        tableLayout12.setLayoutParams(new LinearLayout.LayoutParams(1409, 1657));
        this.aoagrqtcvu.setPadding(81, 125, 36, 40);
        linearLayout.addView(this.aoagrqtcvu);
        this.aoagrqtcvu.setBackgroundColor(Color.parseColor("#4fc6e5"));
        DatePicker datePicker6 = new DatePicker(this);
        this.ceenuwahll = datePicker6;
        datePicker6.setLayoutParams(new LinearLayout.LayoutParams(554, 1941));
        this.ceenuwahll.setPadding(199, 45, 107, 31);
        linearLayout.addView(this.ceenuwahll);
        this.ceenuwahll.setBackgroundColor(Color.parseColor("#745033"));
        TimePicker timePicker8 = new TimePicker(this);
        this.giwmqxqdyy = timePicker8;
        timePicker8.setLayoutParams(new LinearLayout.LayoutParams(1487, 1517));
        this.giwmqxqdyy.setPadding(94, 22, 75, 0);
        linearLayout.addView(this.giwmqxqdyy);
        this.giwmqxqdyy.setBackgroundColor(Color.parseColor("#0e5832"));
        Spinner spinner4 = new Spinner(this);
        this.ylvupmvzlr = spinner4;
        spinner4.setLayoutParams(new LinearLayout.LayoutParams(465, 61));
        this.ylvupmvzlr.setPadding(110, 42, 141, 194);
        linearLayout.addView(this.ylvupmvzlr);
        this.ylvupmvzlr.setBackgroundColor(Color.parseColor("#62f76a"));
        Spinner spinner5 = new Spinner(this);
        this.jxmthxaqoj = spinner5;
        spinner5.setLayoutParams(new LinearLayout.LayoutParams(488, 1036));
        this.jxmthxaqoj.setPadding(79, 190, 173, 156);
        linearLayout.addView(this.jxmthxaqoj);
        this.jxmthxaqoj.setBackgroundColor(Color.parseColor("#36639e"));
        LinearLayout linearLayout7 = new LinearLayout(this);
        this.pnusqtojjl = linearLayout7;
        linearLayout7.setLayoutParams(new LinearLayout.LayoutParams(146, 1672));
        this.pnusqtojjl.setPadding(120, 153, 48, 44);
        linearLayout.addView(this.pnusqtojjl);
        this.pnusqtojjl.setBackgroundColor(Color.parseColor("#6e37e8"));
        SeekBar seekBar7 = new SeekBar(this);
        this.yrgijcwhqr = seekBar7;
        seekBar7.setLayoutParams(new LinearLayout.LayoutParams(305, 1658));
        this.yrgijcwhqr.setPadding(140, 26, 86, 166);
        linearLayout.addView(this.yrgijcwhqr);
        this.yrgijcwhqr.setBackgroundColor(Color.parseColor("#306d10"));
        ProgressBar progressBar2 = new ProgressBar(this);
        this.rffhdhoumo = progressBar2;
        progressBar2.setLayoutParams(new LinearLayout.LayoutParams(1207, 29));
        this.rffhdhoumo.setPadding(129, 23, 132, 111);
        linearLayout.addView(this.rffhdhoumo);
        this.rffhdhoumo.setBackgroundColor(Color.parseColor("#570e68"));
        FrameLayout frameLayout3 = new FrameLayout(this);
        this.xcwfjbunku = frameLayout3;
        frameLayout3.setLayoutParams(new LinearLayout.LayoutParams(647, 482));
        this.xcwfjbunku.setPadding(111, 51, 194, 57);
        linearLayout.addView(this.xcwfjbunku);
        this.xcwfjbunku.setBackgroundColor(Color.parseColor("#34b2d8"));
        ListView listView4 = new ListView(this);
        this.vxdckbsrrz = listView4;
        listView4.setLayoutParams(new LinearLayout.LayoutParams(1793, 1959));
        this.vxdckbsrrz.setPadding(59, 128, 60, 185);
        linearLayout.addView(this.vxdckbsrrz);
        this.vxdckbsrrz.setBackgroundColor(Color.parseColor("#5a4cc7"));
        SeekBar seekBar8 = new SeekBar(this);
        this.pgwyktwclz = seekBar8;
        seekBar8.setLayoutParams(new LinearLayout.LayoutParams(882, 957));
        this.pgwyktwclz.setPadding(175, 131, 94, 172);
        linearLayout.addView(this.pgwyktwclz);
        this.pgwyktwclz.setBackgroundColor(Color.parseColor("#0886de"));
        DatePicker datePicker7 = new DatePicker(this);
        this.uvumnsfguf = datePicker7;
        datePicker7.setLayoutParams(new LinearLayout.LayoutParams(894, 1696));
        this.uvumnsfguf.setPadding(32, 21, 185, 0);
        linearLayout.addView(this.uvumnsfguf);
        this.uvumnsfguf.setBackgroundColor(Color.parseColor("#cc021b"));
        RelativeLayout relativeLayout5 = new RelativeLayout(this);
        this.anoagkepls = relativeLayout5;
        relativeLayout5.setLayoutParams(new LinearLayout.LayoutParams(1730, 1641));
        this.anoagkepls.setPadding(90, 93, 12, 133);
        linearLayout.addView(this.anoagkepls);
        this.anoagkepls.setBackgroundColor(Color.parseColor("#620a90"));
        Switch r34 = new Switch(this);
        this.trsgeglapm = r34;
        r34.setLayoutParams(new LinearLayout.LayoutParams(1026, 871));
        this.trsgeglapm.setPadding(BDLocation.TypeServerDecryptError, 172, 129, 4);
        linearLayout.addView(this.trsgeglapm);
        this.trsgeglapm.setBackgroundColor(Color.parseColor("#b8eae8"));
        ListView listView5 = new ListView(this);
        this.dxgxisvofa = listView5;
        listView5.setLayoutParams(new LinearLayout.LayoutParams(1572, 1156));
        this.dxgxisvofa.setPadding(184, 2, 22, 175);
        linearLayout.addView(this.dxgxisvofa);
        this.dxgxisvofa.setBackgroundColor(Color.parseColor("#6a43d7"));
        ToggleButton toggleButton6 = new ToggleButton(this);
        this.mpfbopdvnz = toggleButton6;
        toggleButton6.setLayoutParams(new LinearLayout.LayoutParams(783, 1643));
        this.mpfbopdvnz.setPadding(168, 77, 77, 8);
        linearLayout.addView(this.mpfbopdvnz);
        this.mpfbopdvnz.setBackgroundColor(Color.parseColor("#7bb90c"));
        TextView textView5 = new TextView(this);
        this.kjknyraimt = textView5;
        textView5.setLayoutParams(new LinearLayout.LayoutParams(828, 479));
        this.kjknyraimt.setPadding(182, 15, 129, 190);
        linearLayout.addView(this.kjknyraimt);
        this.kjknyraimt.setBackgroundColor(Color.parseColor("#d10f8b"));
        RelativeLayout relativeLayout6 = new RelativeLayout(this);
        this.eikchwrbaa = relativeLayout6;
        relativeLayout6.setLayoutParams(new LinearLayout.LayoutParams(448, 1391));
        this.eikchwrbaa.setPadding(163, 63, 5, 121);
        linearLayout.addView(this.eikchwrbaa);
        this.eikchwrbaa.setBackgroundColor(Color.parseColor("#2e38f2"));
        GridView gridView8 = new GridView(this);
        this.lwcqctoqne = gridView8;
        gridView8.setLayoutParams(new LinearLayout.LayoutParams(1755, 1644));
        this.lwcqctoqne.setPadding(71, 105, 98, 127);
        linearLayout.addView(this.lwcqctoqne);
        this.lwcqctoqne.setBackgroundColor(Color.parseColor("#fef3f5"));
        RelativeLayout relativeLayout7 = new RelativeLayout(this);
        this.einobjfzen = relativeLayout7;
        relativeLayout7.setLayoutParams(new LinearLayout.LayoutParams(248, 164));
        this.einobjfzen.setPadding(139, 24, 133, 94);
        linearLayout.addView(this.einobjfzen);
        this.einobjfzen.setBackgroundColor(Color.parseColor("#38d4e2"));
        RelativeLayout relativeLayout8 = new RelativeLayout(this);
        this.oaffbazqhs = relativeLayout8;
        relativeLayout8.setLayoutParams(new LinearLayout.LayoutParams(1161, 897));
        this.oaffbazqhs.setPadding(34, 26, 171, 81);
        linearLayout.addView(this.oaffbazqhs);
        this.oaffbazqhs.setBackgroundColor(Color.parseColor("#58c07d"));
        TextView textView6 = new TextView(this);
        this.chjspxngmg = textView6;
        textView6.setLayoutParams(new LinearLayout.LayoutParams(1222, 1138));
        this.chjspxngmg.setPadding(21, 43, 50, 7);
        linearLayout.addView(this.chjspxngmg);
        this.chjspxngmg.setBackgroundColor(Color.parseColor("#e23876"));
        FrameLayout frameLayout4 = new FrameLayout(this);
        this.uezadhpzyc = frameLayout4;
        frameLayout4.setLayoutParams(new LinearLayout.LayoutParams(1227, 1971));
        this.uezadhpzyc.setPadding(74, 170, 93, 39);
        linearLayout.addView(this.uezadhpzyc);
        this.uezadhpzyc.setBackgroundColor(Color.parseColor("#7b5f50"));
        LinearLayout linearLayout8 = new LinearLayout(this);
        this.pqdgodoxqx = linearLayout8;
        linearLayout8.setLayoutParams(new LinearLayout.LayoutParams(419, 48));
        this.pqdgodoxqx.setPadding(199, 184, 100, 96);
        linearLayout.addView(this.pqdgodoxqx);
        this.pqdgodoxqx.setBackgroundColor(Color.parseColor("#3da7b1"));
        ImageView imageView4 = new ImageView(this);
        this.itflmevjtl = imageView4;
        imageView4.setLayoutParams(new LinearLayout.LayoutParams(29, 220));
        this.itflmevjtl.setPadding(175, 47, 38, 84);
        linearLayout.addView(this.itflmevjtl);
        this.itflmevjtl.setBackgroundColor(Color.parseColor("#5ededd"));
        RadioButton radioButton5 = new RadioButton(this);
        this.fwwejacjyu = radioButton5;
        radioButton5.setLayoutParams(new LinearLayout.LayoutParams(273, 1368));
        this.fwwejacjyu.setPadding(153, 120, 172, 195);
        linearLayout.addView(this.fwwejacjyu);
        this.fwwejacjyu.setBackgroundColor(Color.parseColor("#ec6a41"));
        ViewFlipper viewFlipper7 = new ViewFlipper(this);
        this.qhapusdela = viewFlipper7;
        viewFlipper7.setLayoutParams(new LinearLayout.LayoutParams(758, 1750));
        this.qhapusdela.setPadding(9, 78, 67, 5);
        linearLayout.addView(this.qhapusdela);
        this.qhapusdela.setBackgroundColor(Color.parseColor("#4381f9"));
        EditText editText7 = new EditText(this);
        this.ozhawboyzu = editText7;
        editText7.setLayoutParams(new LinearLayout.LayoutParams(1548, 1413));
        this.ozhawboyzu.setPadding(173, 102, 141, 58);
        linearLayout.addView(this.ozhawboyzu);
        this.ozhawboyzu.setBackgroundColor(Color.parseColor("#0cba0d"));
        Spinner spinner6 = new Spinner(this);
        this.huxpvzailo = spinner6;
        spinner6.setLayoutParams(new LinearLayout.LayoutParams(1530, 430));
        this.huxpvzailo.setPadding(196, 144, 77, 51);
        linearLayout.addView(this.huxpvzailo);
        this.huxpvzailo.setBackgroundColor(Color.parseColor("#7665e6"));
        GridView gridView9 = new GridView(this);
        this.sgcwmmgpdb = gridView9;
        gridView9.setLayoutParams(new LinearLayout.LayoutParams(1275, 469));
        this.sgcwmmgpdb.setPadding(110, 64, 62, 19);
        linearLayout.addView(this.sgcwmmgpdb);
        this.sgcwmmgpdb.setBackgroundColor(Color.parseColor("#b0c122"));
        SeekBar seekBar9 = new SeekBar(this);
        this.nhmkrozhso = seekBar9;
        seekBar9.setLayoutParams(new LinearLayout.LayoutParams(290, 1043));
        this.nhmkrozhso.setPadding(43, 150, 47, 16);
        linearLayout.addView(this.nhmkrozhso);
        this.nhmkrozhso.setBackgroundColor(Color.parseColor("#0c4bbc"));
        Switch r35 = new Switch(this);
        this.vddilondqc = r35;
        r35.setLayoutParams(new LinearLayout.LayoutParams(463, 1655));
        this.vddilondqc.setPadding(58, PictureConfig.CHOOSE_REQUEST, 149, 90);
        linearLayout.addView(this.vddilondqc);
        this.vddilondqc.setBackgroundColor(Color.parseColor("#6d8afc"));
        TextView textView7 = new TextView(this);
        this.elpihlnrib = textView7;
        textView7.setLayoutParams(new LinearLayout.LayoutParams(CropImageView.DEFAULT_IMAGE_TO_CROP_BOUNDS_ANIM_DURATION, 1365));
        this.elpihlnrib.setPadding(185, 199, 60, 22);
        linearLayout.addView(this.elpihlnrib);
        this.elpihlnrib.setBackgroundColor(Color.parseColor("#108d15"));
        SeekBar seekBar10 = new SeekBar(this);
        this.dptzkvbuod = seekBar10;
        seekBar10.setLayoutParams(new LinearLayout.LayoutParams(1009, 974));
        this.dptzkvbuod.setPadding(90, 141, 3, 60);
        linearLayout.addView(this.dptzkvbuod);
        this.dptzkvbuod.setBackgroundColor(Color.parseColor("#49f1de"));
        ViewFlipper viewFlipper8 = new ViewFlipper(this);
        this.rwvplurmmq = viewFlipper8;
        viewFlipper8.setLayoutParams(new LinearLayout.LayoutParams(CodeUtils.DEFAULT_REQ_HEIGHT, 1255));
        this.rwvplurmmq.setPadding(97, 117, 68, 91);
        linearLayout.addView(this.rwvplurmmq);
        this.rwvplurmmq.setBackgroundColor(Color.parseColor("#c52e3c"));
        Spinner spinner7 = new Spinner(this);
        this.yhkplceeqr = spinner7;
        spinner7.setLayoutParams(new LinearLayout.LayoutParams(1590, 1086));
        this.yhkplceeqr.setPadding(48, 20, 86, 118);
        linearLayout.addView(this.yhkplceeqr);
        this.yhkplceeqr.setBackgroundColor(Color.parseColor("#b26afe"));
        ViewFlipper viewFlipper9 = new ViewFlipper(this);
        this.swjzqfdxfu = viewFlipper9;
        viewFlipper9.setLayoutParams(new LinearLayout.LayoutParams(1887, 1326));
        this.swjzqfdxfu.setPadding(52, 44, BDLocation.TypeServerError, 56);
        linearLayout.addView(this.swjzqfdxfu);
        this.swjzqfdxfu.setBackgroundColor(Color.parseColor("#bab4b7"));
        ViewFlipper viewFlipper10 = new ViewFlipper(this);
        this.nofhtwitoz = viewFlipper10;
        viewFlipper10.setLayoutParams(new LinearLayout.LayoutParams(1693, 1979));
        this.nofhtwitoz.setPadding(63, 144, 177, 171);
        linearLayout.addView(this.nofhtwitoz);
        this.nofhtwitoz.setBackgroundColor(Color.parseColor("#bb0cb2"));
        Switch r36 = new Switch(this);
        this.xycppvyixz = r36;
        r36.setLayoutParams(new LinearLayout.LayoutParams(1381, 1920));
        this.xycppvyixz.setPadding(81, 131, 191, 118);
        linearLayout.addView(this.xycppvyixz);
        this.xycppvyixz.setBackgroundColor(Color.parseColor("#9c5fbc"));
        EditText editText8 = new EditText(this);
        this.vvyirynvzi = editText8;
        editText8.setLayoutParams(new LinearLayout.LayoutParams(958, 765));
        this.vvyirynvzi.setPadding(189, 135, 60, 180);
        linearLayout.addView(this.vvyirynvzi);
        this.vvyirynvzi.setBackgroundColor(Color.parseColor("#b6450d"));
        ProgressBar progressBar3 = new ProgressBar(this);
        this.soxxnzrpcu = progressBar3;
        progressBar3.setLayoutParams(new LinearLayout.LayoutParams(79, 438));
        this.soxxnzrpcu.setPadding(157, 97, 25, 80);
        linearLayout.addView(this.soxxnzrpcu);
        this.soxxnzrpcu.setBackgroundColor(Color.parseColor("#2642cd"));
        RadioButton radioButton6 = new RadioButton(this);
        this.urzqoziycn = radioButton6;
        radioButton6.setLayoutParams(new LinearLayout.LayoutParams(1883, 591));
        this.urzqoziycn.setPadding(163, 18, 64, 110);
        linearLayout.addView(this.urzqoziycn);
        this.urzqoziycn.setBackgroundColor(Color.parseColor("#e125ca"));
        ListView listView6 = new ListView(this);
        this.mcnrxnnhfb = listView6;
        listView6.setLayoutParams(new LinearLayout.LayoutParams(1748, TypedValues.PositionType.TYPE_PERCENT_Y));
        this.mcnrxnnhfb.setPadding(116, 74, 99, 189);
        linearLayout.addView(this.mcnrxnnhfb);
        this.mcnrxnnhfb.setBackgroundColor(Color.parseColor("#a1ee28"));
        RadioButton radioButton7 = new RadioButton(this);
        this.utfdmdmnwl = radioButton7;
        radioButton7.setLayoutParams(new LinearLayout.LayoutParams(1730, 715));
        this.utfdmdmnwl.setPadding(177, 102, 106, 40);
        linearLayout.addView(this.utfdmdmnwl);
        this.utfdmdmnwl.setBackgroundColor(Color.parseColor("#294151"));
        CheckBox checkBox7 = new CheckBox(this);
        this.xhywvwrmnj = checkBox7;
        checkBox7.setLayoutParams(new LinearLayout.LayoutParams(1638, 1452));
        this.xhywvwrmnj.setPadding(172, 9, 197, 140);
        linearLayout.addView(this.xhywvwrmnj);
        this.xhywvwrmnj.setBackgroundColor(Color.parseColor("#e13e37"));
        Button button6 = new Button(this);
        this.suzwmlakjk = button6;
        button6.setLayoutParams(new LinearLayout.LayoutParams(231, 1920));
        this.suzwmlakjk.setPadding(85, 158, 7, 195);
        linearLayout.addView(this.suzwmlakjk);
        this.suzwmlakjk.setBackgroundColor(Color.parseColor("#c51d00"));
        RatingBar ratingBar10 = new RatingBar(this);
        this.bzjxncseyg = ratingBar10;
        ratingBar10.setLayoutParams(new LinearLayout.LayoutParams(1664, 1766));
        this.bzjxncseyg.setPadding(88, PictureConfig.CHOOSE_REQUEST, BDLocation.TypeServerDecryptError, 158);
        linearLayout.addView(this.bzjxncseyg);
        this.bzjxncseyg.setBackgroundColor(Color.parseColor("#51c8d0"));
        EditText editText9 = new EditText(this);
        this.xktzkwcond = editText9;
        editText9.setLayoutParams(new LinearLayout.LayoutParams(301, 1789));
        this.xktzkwcond.setPadding(60, 187, 157, 41);
        linearLayout.addView(this.xktzkwcond);
        this.xktzkwcond.setBackgroundColor(Color.parseColor("#6ce912"));
        ViewFlipper viewFlipper11 = new ViewFlipper(this);
        this.jiskcjkbom = viewFlipper11;
        viewFlipper11.setLayoutParams(new LinearLayout.LayoutParams(1192, PictureConfig.CHOOSE_REQUEST));
        this.jiskcjkbom.setPadding(33, 163, 103, 136);
        linearLayout.addView(this.jiskcjkbom);
        this.jiskcjkbom.setBackgroundColor(Color.parseColor("#82eca5"));
        ProgressBar progressBar4 = new ProgressBar(this);
        this.upnlpobumk = progressBar4;
        progressBar4.setLayoutParams(new LinearLayout.LayoutParams(172, 1061));
        this.upnlpobumk.setPadding(62, 141, 191, 103);
        linearLayout.addView(this.upnlpobumk);
        this.upnlpobumk.setBackgroundColor(Color.parseColor("#617d72"));
        ToggleButton toggleButton7 = new ToggleButton(this);
        this.kextdytxiy = toggleButton7;
        toggleButton7.setLayoutParams(new LinearLayout.LayoutParams(846, 1327));
        this.kextdytxiy.setPadding(149, BDLocation.TypeServerDecryptError, 89, 14);
        linearLayout.addView(this.kextdytxiy);
        this.kextdytxiy.setBackgroundColor(Color.parseColor("#1b3001"));
        ToggleButton toggleButton8 = new ToggleButton(this);
        this.unvomiksnc = toggleButton8;
        toggleButton8.setLayoutParams(new LinearLayout.LayoutParams(1787, 1641));
        this.unvomiksnc.setPadding(92, 96, 159, 75);
        linearLayout.addView(this.unvomiksnc);
        this.unvomiksnc.setBackgroundColor(Color.parseColor("#04d0c7"));
        Button button7 = new Button(this);
        this.uatdoblwod = button7;
        button7.setLayoutParams(new LinearLayout.LayoutParams(458, 1812));
        this.uatdoblwod.setPadding(58, 83, 90, 98);
        linearLayout.addView(this.uatdoblwod);
        this.uatdoblwod.setBackgroundColor(Color.parseColor("#4453ac"));
        ViewFlipper viewFlipper12 = new ViewFlipper(this);
        this.cyswhgmerj = viewFlipper12;
        viewFlipper12.setLayoutParams(new LinearLayout.LayoutParams(1318, 1665));
        this.cyswhgmerj.setPadding(PictureConfig.CHOOSE_REQUEST, 24, 108, 55);
        linearLayout.addView(this.cyswhgmerj);
        this.cyswhgmerj.setBackgroundColor(Color.parseColor("#c6c22c"));
        SeekBar seekBar11 = new SeekBar(this);
        this.sjspuytnxv = seekBar11;
        seekBar11.setLayoutParams(new LinearLayout.LayoutParams(1728, 113));
        this.sjspuytnxv.setPadding(83, 173, 60, 59);
        linearLayout.addView(this.sjspuytnxv);
        this.sjspuytnxv.setBackgroundColor(Color.parseColor("#09f0ad"));
        RatingBar ratingBar11 = new RatingBar(this);
        this.ovrpgwtarg = ratingBar11;
        ratingBar11.setLayoutParams(new LinearLayout.LayoutParams(1287, 292));
        this.ovrpgwtarg.setPadding(66, 61, 20, 140);
        linearLayout.addView(this.ovrpgwtarg);
        this.ovrpgwtarg.setBackgroundColor(Color.parseColor("#b9bb19"));
        CheckBox checkBox8 = new CheckBox(this);
        this.mhljwamxon = checkBox8;
        checkBox8.setLayoutParams(new LinearLayout.LayoutParams(573, 593));
        this.mhljwamxon.setPadding(176, 64, 146, 95);
        linearLayout.addView(this.mhljwamxon);
        this.mhljwamxon.setBackgroundColor(Color.parseColor("#e708e4"));
        ImageView imageView5 = new ImageView(this);
        this.fvslazskyp = imageView5;
        imageView5.setLayoutParams(new LinearLayout.LayoutParams(1904, 1228));
        this.fvslazskyp.setPadding(144, 136, 138, 105);
        linearLayout.addView(this.fvslazskyp);
        this.fvslazskyp.setBackgroundColor(Color.parseColor("#af3b5f"));
        LinearLayout linearLayout9 = new LinearLayout(this);
        this.neirlxajfh = linearLayout9;
        linearLayout9.setLayoutParams(new LinearLayout.LayoutParams(1770, 13));
        this.neirlxajfh.setPadding(152, 151, 141, 147);
        linearLayout.addView(this.neirlxajfh);
        this.neirlxajfh.setBackgroundColor(Color.parseColor("#ef1f8f"));
        FrameLayout frameLayout5 = new FrameLayout(this);
        this.kmaolhccji = frameLayout5;
        frameLayout5.setLayoutParams(new LinearLayout.LayoutParams(62, 356));
        this.kmaolhccji.setPadding(117, 29, 192, 187);
        linearLayout.addView(this.kmaolhccji);
        this.kmaolhccji.setBackgroundColor(Color.parseColor("#c39938"));
        RatingBar ratingBar12 = new RatingBar(this);
        this.zveebezrul = ratingBar12;
        ratingBar12.setLayoutParams(new LinearLayout.LayoutParams(1879, 1281));
        this.zveebezrul.setPadding(10, 150, 107, 198);
        linearLayout.addView(this.zveebezrul);
        this.zveebezrul.setBackgroundColor(Color.parseColor("#f8ace9"));
        ViewFlipper viewFlipper13 = new ViewFlipper(this);
        this.zrnytcjtsp = viewFlipper13;
        viewFlipper13.setLayoutParams(new LinearLayout.LayoutParams(950, 1738));
        this.zrnytcjtsp.setPadding(8, 8, 76, 19);
        linearLayout.addView(this.zrnytcjtsp);
        this.zrnytcjtsp.setBackgroundColor(Color.parseColor("#9f1d6a"));
        ListView listView7 = new ListView(this);
        this.siftphhayq = listView7;
        listView7.setLayoutParams(new LinearLayout.LayoutParams(95, 1182));
        this.siftphhayq.setPadding(WebSocketProtocol.PAYLOAD_SHORT, 42, 16, 114);
        linearLayout.addView(this.siftphhayq);
        this.siftphhayq.setBackgroundColor(Color.parseColor("#6ccf76"));
        ViewFlipper viewFlipper14 = new ViewFlipper(this);
        this.kopjcolbwb = viewFlipper14;
        viewFlipper14.setLayoutParams(new LinearLayout.LayoutParams(697, 1838));
        this.kopjcolbwb.setPadding(157, 73, 38, 171);
        linearLayout.addView(this.kopjcolbwb);
        this.kopjcolbwb.setBackgroundColor(Color.parseColor("#414d2b"));
        Spinner spinner8 = new Spinner(this);
        this.hiwjsqlyfs = spinner8;
        spinner8.setLayoutParams(new LinearLayout.LayoutParams(1977, TypedValues.CycleType.TYPE_VISIBILITY));
        this.hiwjsqlyfs.setPadding(63, 181, 144, 12);
        linearLayout.addView(this.hiwjsqlyfs);
        this.hiwjsqlyfs.setBackgroundColor(Color.parseColor("#3c46b4"));
        ScrollView scrollView7 = new ScrollView(this);
        this.xcaqsrkfew = scrollView7;
        scrollView7.setLayoutParams(new LinearLayout.LayoutParams(787, 1169));
        this.xcaqsrkfew.setPadding(180, 137, 166, 73);
        linearLayout.addView(this.xcaqsrkfew);
        this.xcaqsrkfew.setBackgroundColor(Color.parseColor("#2b074d"));
        GridView gridView10 = new GridView(this);
        this.ntblqcinny = gridView10;
        gridView10.setLayoutParams(new LinearLayout.LayoutParams(1284, 882));
        this.ntblqcinny.setPadding(18, 79, 153, 95);
        linearLayout.addView(this.ntblqcinny);
        this.ntblqcinny.setBackgroundColor(Color.parseColor("#89fe5f"));
        RelativeLayout relativeLayout9 = new RelativeLayout(this);
        this.ipkokypsik = relativeLayout9;
        relativeLayout9.setLayoutParams(new LinearLayout.LayoutParams(1638, 1815));
        this.ipkokypsik.setPadding(168, 178, 169, 164);
        linearLayout.addView(this.ipkokypsik);
        this.ipkokypsik.setBackgroundColor(Color.parseColor("#7797b8"));
        SeekBar seekBar12 = new SeekBar(this);
        this.wmlqgydahu = seekBar12;
        seekBar12.setLayoutParams(new LinearLayout.LayoutParams(857, 369));
        this.wmlqgydahu.setPadding(119, 191, 68, 181);
        linearLayout.addView(this.wmlqgydahu);
        this.wmlqgydahu.setBackgroundColor(Color.parseColor("#2e6460"));
        ListView listView8 = new ListView(this);
        this.tntbqzjyou = listView8;
        listView8.setLayoutParams(new LinearLayout.LayoutParams(306, 1574));
        this.tntbqzjyou.setPadding(5, 91, 116, 131);
        linearLayout.addView(this.tntbqzjyou);
        this.tntbqzjyou.setBackgroundColor(Color.parseColor("#3868f9"));
        ScrollView scrollView8 = new ScrollView(this);
        this.tstiwnfusc = scrollView8;
        scrollView8.setLayoutParams(new LinearLayout.LayoutParams(491, 1367));
        this.tstiwnfusc.setPadding(62, BDLocation.TypeCoarseLocation, 43, 191);
        linearLayout.addView(this.tstiwnfusc);
        this.tstiwnfusc.setBackgroundColor(Color.parseColor("#3303b9"));
        TextView textView8 = new TextView(this);
        this.kwugmkmdvs = textView8;
        textView8.setLayoutParams(new LinearLayout.LayoutParams(FrameMetricsAggregator.EVERY_DURATION, 245));
        this.kwugmkmdvs.setPadding(175, 195, 165, 25);
        linearLayout.addView(this.kwugmkmdvs);
        this.kwugmkmdvs.setBackgroundColor(Color.parseColor("#a74aae"));
        ProgressBar progressBar5 = new ProgressBar(this);
        this.uuhvufnoxy = progressBar5;
        progressBar5.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.Custom.TYPE_DIMENSION, 1835));
        this.uuhvufnoxy.setPadding(193, 13, 42, 96);
        linearLayout.addView(this.uuhvufnoxy);
        this.uuhvufnoxy.setBackgroundColor(Color.parseColor("#186c48"));
        ScrollView scrollView9 = new ScrollView(this);
        this.rphepmusac = scrollView9;
        scrollView9.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.TransitionType.TYPE_AUTO_TRANSITION, 383));
        this.rphepmusac.setPadding(48, 50, 80, 68);
        linearLayout.addView(this.rphepmusac);
        this.rphepmusac.setBackgroundColor(Color.parseColor("#a73c5a"));
        ToggleButton toggleButton9 = new ToggleButton(this);
        this.hzhaoqjdlp = toggleButton9;
        toggleButton9.setLayoutParams(new LinearLayout.LayoutParams(184, 58));
        this.hzhaoqjdlp.setPadding(119, 86, 41, 183);
        linearLayout.addView(this.hzhaoqjdlp);
        this.hzhaoqjdlp.setBackgroundColor(Color.parseColor("#bbeb41"));
        Button button8 = new Button(this);
        this.nbzglaiiwd = button8;
        button8.setLayoutParams(new LinearLayout.LayoutParams(1392, 767));
        this.nbzglaiiwd.setPadding(BDLocation.TypeNetWorkLocation, 179, 158, 81);
        linearLayout.addView(this.nbzglaiiwd);
        this.nbzglaiiwd.setBackgroundColor(Color.parseColor("#4657fe"));
        LinearLayout linearLayout10 = new LinearLayout(this);
        this.fxdjjhzzfx = linearLayout10;
        linearLayout10.setLayoutParams(new LinearLayout.LayoutParams(1132, 1471));
        this.fxdjjhzzfx.setPadding(197, 72, 184, 195);
        linearLayout.addView(this.fxdjjhzzfx);
        this.fxdjjhzzfx.setBackgroundColor(Color.parseColor("#583951"));
        CheckBox checkBox9 = new CheckBox(this);
        this.shxiausyxv = checkBox9;
        checkBox9.setLayoutParams(new LinearLayout.LayoutParams(375, 1554));
        this.shxiausyxv.setPadding(23, 85, 86, 11);
        linearLayout.addView(this.shxiausyxv);
        this.shxiausyxv.setBackgroundColor(Color.parseColor("#db4b7d"));
        ProgressBar progressBar6 = new ProgressBar(this);
        this.lajfqftoar = progressBar6;
        progressBar6.setLayoutParams(new LinearLayout.LayoutParams(623, 1113));
        this.lajfqftoar.setPadding(150, 42, 96, 45);
        linearLayout.addView(this.lajfqftoar);
        this.lajfqftoar.setBackgroundColor(Color.parseColor("#ddb0f7"));
        ToggleButton toggleButton10 = new ToggleButton(this);
        this.zlfmuphasq = toggleButton10;
        toggleButton10.setLayoutParams(new LinearLayout.LayoutParams(197, 360));
        this.zlfmuphasq.setPadding(70, 190, 31, 2);
        linearLayout.addView(this.zlfmuphasq);
        this.zlfmuphasq.setBackgroundColor(Color.parseColor("#83335d"));
        TextView textView9 = new TextView(this);
        this.fxpqiljbde = textView9;
        textView9.setLayoutParams(new LinearLayout.LayoutParams(1847, 1353));
        this.fxpqiljbde.setPadding(75, 44, 47, 26);
        linearLayout.addView(this.fxpqiljbde);
        this.fxpqiljbde.setBackgroundColor(Color.parseColor("#5fdaf2"));
        Spinner spinner9 = new Spinner(this);
        this.amxblcsfsr = spinner9;
        spinner9.setLayoutParams(new LinearLayout.LayoutParams(308, 1571));
        this.amxblcsfsr.setPadding(BDLocation.TypeServerError, 175, 187, 180);
        linearLayout.addView(this.amxblcsfsr);
        this.amxblcsfsr.setBackgroundColor(Color.parseColor("#626e64"));
        RatingBar ratingBar13 = new RatingBar(this);
        this.bcrdeqvdei = ratingBar13;
        ratingBar13.setLayoutParams(new LinearLayout.LayoutParams(67, BDLocation.TypeNetWorkLocation));
        this.bcrdeqvdei.setPadding(34, 7, 195, 46);
        linearLayout.addView(this.bcrdeqvdei);
        this.bcrdeqvdei.setBackgroundColor(Color.parseColor("#b248df"));
        LinearLayout linearLayout11 = new LinearLayout(this);
        this.jdyynvkshp = linearLayout11;
        linearLayout11.setLayoutParams(new LinearLayout.LayoutParams(936, 807));
        this.jdyynvkshp.setPadding(164, 156, 140, BDLocation.TypeCoarseLocation);
        linearLayout.addView(this.jdyynvkshp);
        this.jdyynvkshp.setBackgroundColor(Color.parseColor("#61acd5"));
        ToggleButton toggleButton11 = new ToggleButton(this);
        this.tswfjphjfe = toggleButton11;
        toggleButton11.setLayoutParams(new LinearLayout.LayoutParams(93, 631));
        this.tswfjphjfe.setPadding(153, 80, 108, 195);
        linearLayout.addView(this.tswfjphjfe);
        this.tswfjphjfe.setBackgroundColor(Color.parseColor("#b4d12d"));
        DatePicker datePicker8 = new DatePicker(this);
        this.ycafyrjjtr = datePicker8;
        datePicker8.setLayoutParams(new LinearLayout.LayoutParams(1, 1961));
        this.ycafyrjjtr.setPadding(9, 66, 88, 71);
        linearLayout.addView(this.ycafyrjjtr);
        this.ycafyrjjtr.setBackgroundColor(Color.parseColor("#b3e570"));
        EditText editText10 = new EditText(this);
        this.qwrahhztxw = editText10;
        editText10.setLayoutParams(new LinearLayout.LayoutParams(663, 1600));
        this.qwrahhztxw.setPadding(66, 117, PictureConfig.CHOOSE_REQUEST, 41);
        linearLayout.addView(this.qwrahhztxw);
        this.qwrahhztxw.setBackgroundColor(Color.parseColor("#970569"));
        Button button9 = new Button(this);
        this.tilmqyvizs = button9;
        button9.setLayoutParams(new LinearLayout.LayoutParams(262, 817));
        this.tilmqyvizs.setPadding(100, 159, 143, BDLocation.TypeServerDecryptError);
        linearLayout.addView(this.tilmqyvizs);
        this.tilmqyvizs.setBackgroundColor(Color.parseColor("#aa9ecf"));
        ListView listView9 = new ListView(this);
        this.xzwfxpzskj = listView9;
        listView9.setLayoutParams(new LinearLayout.LayoutParams(849, GattClient.STATE_PREPARE_PAIRING_REQUEST));
        this.xzwfxpzskj.setPadding(168, 198, 89, 100);
        linearLayout.addView(this.xzwfxpzskj);
        this.xzwfxpzskj.setBackgroundColor(Color.parseColor("#d62d1b"));
        Button button10 = new Button(this);
        this.sucqrpjszb = button10;
        button10.setLayoutParams(new LinearLayout.LayoutParams(1418, 1480));
        this.sucqrpjszb.setPadding(181, 110, 34, 23);
        linearLayout.addView(this.sucqrpjszb);
        this.sucqrpjszb.setBackgroundColor(Color.parseColor("#48196b"));
        TableLayout tableLayout13 = new TableLayout(this);
        this.ieoqbifttv = tableLayout13;
        tableLayout13.setLayoutParams(new LinearLayout.LayoutParams(BluetoothSpp.STATE_DISCONNECTING, 1235));
        this.ieoqbifttv.setPadding(87, 102, 73, 97);
        linearLayout.addView(this.ieoqbifttv);
        this.ieoqbifttv.setBackgroundColor(Color.parseColor("#02ef0d"));
        EditText editText11 = new EditText(this);
        this.ltwsbfktsx = editText11;
        editText11.setLayoutParams(new LinearLayout.LayoutParams(1321, 748));
        this.ltwsbfktsx.setPadding(125, 41, 173, 36);
        linearLayout.addView(this.ltwsbfktsx);
        this.ltwsbfktsx.setBackgroundColor(Color.parseColor("#b305dc"));
        Switch r37 = new Switch(this);
        this.wwhaoujlxi = r37;
        r37.setLayoutParams(new LinearLayout.LayoutParams(854, 1205));
        this.wwhaoujlxi.setPadding(22, 48, 75, 18);
        linearLayout.addView(this.wwhaoujlxi);
        this.wwhaoujlxi.setBackgroundColor(Color.parseColor("#ea9211"));
        FrameLayout frameLayout6 = new FrameLayout(this);
        this.joewqdzpky = frameLayout6;
        frameLayout6.setLayoutParams(new LinearLayout.LayoutParams(827, 664));
        this.joewqdzpky.setPadding(81, 149, 69, 187);
        linearLayout.addView(this.joewqdzpky);
        this.joewqdzpky.setBackgroundColor(Color.parseColor("#aa2aca"));
        SeekBar seekBar13 = new SeekBar(this);
        this.ybdlwcqvcm = seekBar13;
        seekBar13.setLayoutParams(new LinearLayout.LayoutParams(64, 56));
        this.ybdlwcqvcm.setPadding(79, 139, 51, 54);
        linearLayout.addView(this.ybdlwcqvcm);
        this.ybdlwcqvcm.setBackgroundColor(Color.parseColor("#db7a49"));
        ImageView imageView6 = new ImageView(this);
        this.nykdmoxcwr = imageView6;
        imageView6.setLayoutParams(new LinearLayout.LayoutParams(1951, 620));
        this.nykdmoxcwr.setPadding(134, 194, 145, 141);
        linearLayout.addView(this.nykdmoxcwr);
        this.nykdmoxcwr.setBackgroundColor(Color.parseColor("#79fcaf"));
        DatePicker datePicker9 = new DatePicker(this);
        this.godlanlkqx = datePicker9;
        datePicker9.setLayoutParams(new LinearLayout.LayoutParams(225, 544));
        this.godlanlkqx.setPadding(164, 55, 13, 82);
        linearLayout.addView(this.godlanlkqx);
        this.godlanlkqx.setBackgroundColor(Color.parseColor("#a08326"));
        ProgressBar progressBar7 = new ProgressBar(this);
        this.lfamqceljg = progressBar7;
        progressBar7.setLayoutParams(new LinearLayout.LayoutParams(1167, 43));
        this.lfamqceljg.setPadding(165, 81, 4, 103);
        linearLayout.addView(this.lfamqceljg);
        this.lfamqceljg.setBackgroundColor(Color.parseColor("#3c9cba"));
        RelativeLayout relativeLayout10 = new RelativeLayout(this);
        this.dipxrlhxsg = relativeLayout10;
        relativeLayout10.setLayoutParams(new LinearLayout.LayoutParams(283, 1405));
        this.dipxrlhxsg.setPadding(154, 143, 199, 36);
        linearLayout.addView(this.dipxrlhxsg);
        this.dipxrlhxsg.setBackgroundColor(Color.parseColor("#880264"));
        DatePicker datePicker10 = new DatePicker(this);
        this.sqmjnlcxbp = datePicker10;
        datePicker10.setLayoutParams(new LinearLayout.LayoutParams(977, 1769));
        this.sqmjnlcxbp.setPadding(159, 53, 71, 9);
        linearLayout.addView(this.sqmjnlcxbp);
        this.sqmjnlcxbp.setBackgroundColor(Color.parseColor("#9e5d9d"));
        TimePicker timePicker9 = new TimePicker(this);
        this.dwgnlpuzun = timePicker9;
        timePicker9.setLayoutParams(new LinearLayout.LayoutParams(1477, 1140));
        this.dwgnlpuzun.setPadding(1, 158, 66, 35);
        linearLayout.addView(this.dwgnlpuzun);
        this.dwgnlpuzun.setBackgroundColor(Color.parseColor("#5c4916"));
        Spinner spinner10 = new Spinner(this);
        this.qqwyavhdoo = spinner10;
        spinner10.setLayoutParams(new LinearLayout.LayoutParams(1186, 1146));
        this.qqwyavhdoo.setPadding(97, 27, 65, 59);
        linearLayout.addView(this.qqwyavhdoo);
        this.qqwyavhdoo.setBackgroundColor(Color.parseColor("#ea8546"));
        LinearLayout linearLayout12 = new LinearLayout(this);
        this.nygdohzapd = linearLayout12;
        linearLayout12.setLayoutParams(new LinearLayout.LayoutParams(308, 1406));
        this.nygdohzapd.setPadding(104, 58, 153, 1);
        linearLayout.addView(this.nygdohzapd);
        this.nygdohzapd.setBackgroundColor(Color.parseColor("#37036e"));
        SeekBar seekBar14 = new SeekBar(this);
        this.ovpupcrbeo = seekBar14;
        seekBar14.setLayoutParams(new LinearLayout.LayoutParams(1611, 646));
        this.ovpupcrbeo.setPadding(96, 107, 74, 87);
        linearLayout.addView(this.ovpupcrbeo);
        this.ovpupcrbeo.setBackgroundColor(Color.parseColor("#664714"));
        TimePicker timePicker10 = new TimePicker(this);
        this.ffrfxgjefz = timePicker10;
        timePicker10.setLayoutParams(new LinearLayout.LayoutParams(1189, LocalPlaybackConstants.BUFFER_A_CAN_USE_FLAG));
        this.ffrfxgjefz.setPadding(68, 164, 143, 105);
        linearLayout.addView(this.ffrfxgjefz);
        this.ffrfxgjefz.setBackgroundColor(Color.parseColor("#e51b3f"));
        ImageView imageView7 = new ImageView(this);
        this.rewlildxcc = imageView7;
        imageView7.setLayoutParams(new LinearLayout.LayoutParams(1007, 472));
        this.rewlildxcc.setPadding(100, 13, 74, 122);
        linearLayout.addView(this.rewlildxcc);
        this.rewlildxcc.setBackgroundColor(Color.parseColor("#a552e3"));
        SeekBar seekBar15 = new SeekBar(this);
        this.pnlkrfmmmu = seekBar15;
        seekBar15.setLayoutParams(new LinearLayout.LayoutParams(64, 121));
        this.pnlkrfmmmu.setPadding(56, 14, 179, 10);
        linearLayout.addView(this.pnlkrfmmmu);
        this.pnlkrfmmmu.setBackgroundColor(Color.parseColor("#6616f1"));
        EditText editText12 = new EditText(this);
        this.ufypbhxvym = editText12;
        editText12.setLayoutParams(new LinearLayout.LayoutParams(345, 475));
        this.ufypbhxvym.setPadding(144, 125, 85, 107);
        linearLayout.addView(this.ufypbhxvym);
        this.ufypbhxvym.setBackgroundColor(Color.parseColor("#5c5c6b"));
        Button button11 = new Button(this);
        this.xiuelcdfln = button11;
        button11.setLayoutParams(new LinearLayout.LayoutParams(229, 994));
        this.xiuelcdfln.setPadding(157, 141, 181, 42);
        linearLayout.addView(this.xiuelcdfln);
        this.xiuelcdfln.setBackgroundColor(Color.parseColor("#ef0ff2"));
        ViewFlipper viewFlipper15 = new ViewFlipper(this);
        this.jtdeibctzy = viewFlipper15;
        viewFlipper15.setLayoutParams(new LinearLayout.LayoutParams(1121, 1964));
        this.jtdeibctzy.setPadding(143, 120, 81, 115);
        linearLayout.addView(this.jtdeibctzy);
        this.jtdeibctzy.setBackgroundColor(Color.parseColor("#5f225b"));
        ListView listView10 = new ListView(this);
        this.nysjlrxzlf = listView10;
        listView10.setLayoutParams(new LinearLayout.LayoutParams(945, 1612));
        this.nysjlrxzlf.setPadding(130, 45, 17, 141);
        linearLayout.addView(this.nysjlrxzlf);
        this.nysjlrxzlf.setBackgroundColor(Color.parseColor("#2fdecb"));
        ViewFlipper viewFlipper16 = new ViewFlipper(this);
        this.azadfoqpra = viewFlipper16;
        viewFlipper16.setLayoutParams(new LinearLayout.LayoutParams(1207, 1915));
        this.azadfoqpra.setPadding(118, 22, 52, 148);
        linearLayout.addView(this.azadfoqpra);
        this.azadfoqpra.setBackgroundColor(Color.parseColor("#39cd4a"));
        CheckBox checkBox10 = new CheckBox(this);
        this.vlhcvmgbwa = checkBox10;
        checkBox10.setLayoutParams(new LinearLayout.LayoutParams(520, 1526));
        this.vlhcvmgbwa.setPadding(115, 96, 58, 52);
        linearLayout.addView(this.vlhcvmgbwa);
        this.vlhcvmgbwa.setBackgroundColor(Color.parseColor("#9c3efc"));
        RatingBar ratingBar14 = new RatingBar(this);
        this.urwaorqowj = ratingBar14;
        ratingBar14.setLayoutParams(new LinearLayout.LayoutParams(1701, 698));
        this.urwaorqowj.setPadding(159, 94, 65, 123);
        linearLayout.addView(this.urwaorqowj);
        this.urwaorqowj.setBackgroundColor(Color.parseColor("#ea5e29"));
        ListView listView11 = new ListView(this);
        this.jbzoshbzop = listView11;
        listView11.setLayoutParams(new LinearLayout.LayoutParams(1275, TypedValues.Custom.TYPE_INT));
        this.jbzoshbzop.setPadding(13, 144, 127, 151);
        linearLayout.addView(this.jbzoshbzop);
        this.jbzoshbzop.setBackgroundColor(Color.parseColor("#6cc696"));
        GridView gridView11 = new GridView(this);
        this.tskyogixcp = gridView11;
        gridView11.setLayoutParams(new LinearLayout.LayoutParams(PDF417Common.MAX_CODEWORDS_IN_BARCODE, 29));
        this.tskyogixcp.setPadding(66, 101, 11, 86);
        linearLayout.addView(this.tskyogixcp);
        this.tskyogixcp.setBackgroundColor(Color.parseColor("#5b4441"));
        TextView textView10 = new TextView(this);
        this.riphxvrgrv = textView10;
        textView10.setLayoutParams(new LinearLayout.LayoutParams(1282, 1674));
        this.riphxvrgrv.setPadding(22, 1, 56, 133);
        linearLayout.addView(this.riphxvrgrv);
        this.riphxvrgrv.setBackgroundColor(Color.parseColor("#0ce8e3"));
        FrameLayout frameLayout7 = new FrameLayout(this);
        this.sswdkxuolr = frameLayout7;
        frameLayout7.setLayoutParams(new LinearLayout.LayoutParams(6, PointerIconCompat.TYPE_TOP_LEFT_DIAGONAL_DOUBLE_ARROW));
        this.sswdkxuolr.setPadding(101, 16, 183, 159);
        linearLayout.addView(this.sswdkxuolr);
        this.sswdkxuolr.setBackgroundColor(Color.parseColor("#cd6f58"));
        TableLayout tableLayout14 = new TableLayout(this);
        this.rjqyslxstg = tableLayout14;
        tableLayout14.setLayoutParams(new LinearLayout.LayoutParams(1425, GattClient.STATE_PREPARED));
        this.rjqyslxstg.setPadding(32, 25, 0, 118);
        linearLayout.addView(this.rjqyslxstg);
        this.rjqyslxstg.setBackgroundColor(Color.parseColor("#8dd292"));
        SeekBar seekBar16 = new SeekBar(this);
        this.ygtftvbaie = seekBar16;
        seekBar16.setLayoutParams(new LinearLayout.LayoutParams(1615, 70));
        this.ygtftvbaie.setPadding(28, 182, 61, 176);
        linearLayout.addView(this.ygtftvbaie);
        this.ygtftvbaie.setBackgroundColor(Color.parseColor("#9484ac"));
        TimePicker timePicker11 = new TimePicker(this);
        this.umrpmzzter = timePicker11;
        timePicker11.setLayoutParams(new LinearLayout.LayoutParams(662, 1740));
        this.umrpmzzter.setPadding(198, 168, 51, 96);
        linearLayout.addView(this.umrpmzzter);
        this.umrpmzzter.setBackgroundColor(Color.parseColor("#9398ef"));
        CheckBox checkBox11 = new CheckBox(this);
        this.hkaetnrpue = checkBox11;
        checkBox11.setLayoutParams(new LinearLayout.LayoutParams(350, 1774));
        this.hkaetnrpue.setPadding(BDLocation.TypeCoarseLocation, 192, 86, 85);
        linearLayout.addView(this.hkaetnrpue);
        this.hkaetnrpue.setBackgroundColor(Color.parseColor("#01772b"));
        DatePicker datePicker11 = new DatePicker(this);
        this.ubhxcukbjt = datePicker11;
        datePicker11.setLayoutParams(new LinearLayout.LayoutParams(296, 1835));
        this.ubhxcukbjt.setPadding(155, 56, 71, 152);
        linearLayout.addView(this.ubhxcukbjt);
        this.ubhxcukbjt.setBackgroundColor(Color.parseColor("#124cd0"));
        TextView textView11 = new TextView(this);
        this.suutiygtpu = textView11;
        textView11.setLayoutParams(new LinearLayout.LayoutParams(1856, 716));
        this.suutiygtpu.setPadding(99, 153, 53, 94);
        linearLayout.addView(this.suutiygtpu);
        this.suutiygtpu.setBackgroundColor(Color.parseColor("#20aee5"));
        ToggleButton toggleButton12 = new ToggleButton(this);
        this.gwdfpgqgbo = toggleButton12;
        toggleButton12.setLayoutParams(new LinearLayout.LayoutParams(216, 808));
        this.gwdfpgqgbo.setPadding(9, 54, 110, 53);
        linearLayout.addView(this.gwdfpgqgbo);
        this.gwdfpgqgbo.setBackgroundColor(Color.parseColor("#67c9ed"));
        ScrollView scrollView10 = new ScrollView(this);
        this.dkqmrlvmqp = scrollView10;
        scrollView10.setLayoutParams(new LinearLayout.LayoutParams(586, 1966));
        this.dkqmrlvmqp.setPadding(96, BDLocation.TypeServerError, 193, 3);
        linearLayout.addView(this.dkqmrlvmqp);
        this.dkqmrlvmqp.setBackgroundColor(Color.parseColor("#53f605"));
        TimePicker timePicker12 = new TimePicker(this);
        this.rtxzdjchie = timePicker12;
        timePicker12.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.TransitionType.TYPE_STAGGERED, TypedValues.Custom.TYPE_INT));
        this.rtxzdjchie.setPadding(39, 168, 113, 114);
        linearLayout.addView(this.rtxzdjchie);
        this.rtxzdjchie.setBackgroundColor(Color.parseColor("#413be6"));
        EditText editText13 = new EditText(this);
        this.picnmgvqfp = editText13;
        editText13.setLayoutParams(new LinearLayout.LayoutParams(894, 868));
        this.picnmgvqfp.setPadding(150, 80, 128, 87);
        linearLayout.addView(this.picnmgvqfp);
        this.picnmgvqfp.setBackgroundColor(Color.parseColor("#1517ac"));
        ListView listView12 = new ListView(this);
        this.ezjgsmunib = listView12;
        listView12.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.TransitionType.TYPE_DURATION, 941));
        this.ezjgsmunib.setPadding(112, 190, 101, 33);
        linearLayout.addView(this.ezjgsmunib);
        this.ezjgsmunib.setBackgroundColor(Color.parseColor("#ab0199"));
        RatingBar ratingBar15 = new RatingBar(this);
        this.ylnalgcshb = ratingBar15;
        ratingBar15.setLayoutParams(new LinearLayout.LayoutParams(582, 1263));
        this.ylnalgcshb.setPadding(100, 6, 99, 190);
        linearLayout.addView(this.ylnalgcshb);
        this.ylnalgcshb.setBackgroundColor(Color.parseColor("#7a83e6"));
        FrameLayout frameLayout8 = new FrameLayout(this);
        this.vjhstasuzg = frameLayout8;
        frameLayout8.setLayoutParams(new LinearLayout.LayoutParams(1428, 1000));
        this.vjhstasuzg.setPadding(105, 171, 49, 1);
        linearLayout.addView(this.vjhstasuzg);
        this.vjhstasuzg.setBackgroundColor(Color.parseColor("#ee9223"));
        Spinner spinner11 = new Spinner(this);
        this.lylpfqjwae = spinner11;
        spinner11.setLayoutParams(new LinearLayout.LayoutParams(1574, TypedValues.TransitionType.TYPE_TRANSITION_FLAGS));
        this.lylpfqjwae.setPadding(13, 93, 95, 159);
        linearLayout.addView(this.lylpfqjwae);
        this.lylpfqjwae.setBackgroundColor(Color.parseColor("#bb8283"));
        TableLayout tableLayout15 = new TableLayout(this);
        this.npbxuahhzd = tableLayout15;
        tableLayout15.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.Custom.TYPE_INT, 1656));
        this.npbxuahhzd.setPadding(177, 73, 132, 41);
        linearLayout.addView(this.npbxuahhzd);
        this.npbxuahhzd.setBackgroundColor(Color.parseColor("#bcb578"));
        DatePicker datePicker12 = new DatePicker(this);
        this.vgfubwkrdl = datePicker12;
        datePicker12.setLayoutParams(new LinearLayout.LayoutParams(1388, 742));
        this.vgfubwkrdl.setPadding(132, 168, 137, 3);
        linearLayout.addView(this.vgfubwkrdl);
        this.vgfubwkrdl.setBackgroundColor(Color.parseColor("#2395c0"));
        DatePicker datePicker13 = new DatePicker(this);
        this.pkbgscphiz = datePicker13;
        datePicker13.setLayoutParams(new LinearLayout.LayoutParams(1951, 1845));
        this.pkbgscphiz.setPadding(57, 184, 49, 83);
        linearLayout.addView(this.pkbgscphiz);
        this.pkbgscphiz.setBackgroundColor(Color.parseColor("#38fad7"));
        RelativeLayout relativeLayout11 = new RelativeLayout(this);
        this.nlqcusyyej = relativeLayout11;
        relativeLayout11.setLayoutParams(new LinearLayout.LayoutParams(753, 464));
        this.nlqcusyyej.setPadding(31, 136, 184, 141);
        linearLayout.addView(this.nlqcusyyej);
        this.nlqcusyyej.setBackgroundColor(Color.parseColor("#387e71"));
        LinearLayout linearLayout13 = new LinearLayout(this);
        this.wzbviucijg = linearLayout13;
        linearLayout13.setLayoutParams(new LinearLayout.LayoutParams(164, 247));
        this.wzbviucijg.setPadding(37, 96, 173, 2);
        linearLayout.addView(this.wzbviucijg);
        this.wzbviucijg.setBackgroundColor(Color.parseColor("#5aedaf"));
        ProgressBar progressBar8 = new ProgressBar(this);
        this.uwbtpuibub = progressBar8;
        progressBar8.setLayoutParams(new LinearLayout.LayoutParams(776, 649));
        this.uwbtpuibub.setPadding(127, 54, 174, 121);
        linearLayout.addView(this.uwbtpuibub);
        this.uwbtpuibub.setBackgroundColor(Color.parseColor("#10a1ae"));
        ListView listView13 = new ListView(this);
        this.wnjcycsmvg = listView13;
        listView13.setLayoutParams(new LinearLayout.LayoutParams(841, 1400));
        this.wnjcycsmvg.setPadding(16, 99, 151, 165);
        linearLayout.addView(this.wnjcycsmvg);
        this.wnjcycsmvg.setBackgroundColor(Color.parseColor("#671248"));
        CheckBox checkBox12 = new CheckBox(this);
        this.iaanaivlnm = checkBox12;
        checkBox12.setLayoutParams(new LinearLayout.LayoutParams(1757, 367));
        this.iaanaivlnm.setPadding(77, 196, 142, 117);
        linearLayout.addView(this.iaanaivlnm);
        this.iaanaivlnm.setBackgroundColor(Color.parseColor("#a3d41b"));
        LinearLayout linearLayout14 = new LinearLayout(this);
        this.dkqjlfnhzj = linearLayout14;
        linearLayout14.setLayoutParams(new LinearLayout.LayoutParams(1936, 1942));
        this.dkqjlfnhzj.setPadding(11, 85, 189, 90);
        linearLayout.addView(this.dkqjlfnhzj);
        this.dkqjlfnhzj.setBackgroundColor(Color.parseColor("#320a3a"));
        RelativeLayout relativeLayout12 = new RelativeLayout(this);
        this.nduxdgqysp = relativeLayout12;
        relativeLayout12.setLayoutParams(new LinearLayout.LayoutParams(950, 1502));
        this.nduxdgqysp.setPadding(133, 152, 165, 180);
        linearLayout.addView(this.nduxdgqysp);
        this.nduxdgqysp.setBackgroundColor(Color.parseColor("#9ccc16"));
        CheckBox checkBox13 = new CheckBox(this);
        this.wvtscsqvfu = checkBox13;
        checkBox13.setLayoutParams(new LinearLayout.LayoutParams(1221, 816));
        this.wvtscsqvfu.setPadding(93, 77, 60, 21);
        linearLayout.addView(this.wvtscsqvfu);
        this.wvtscsqvfu.setBackgroundColor(Color.parseColor("#438c97"));
    }
}
