package com.smartapp.b.ikftpuzemf;

import android.app.Activity;
import android.graphics.Color;
import android.os.Bundle;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.CheckBox;
import android.widget.DatePicker;
import android.widget.EditText;
import android.widget.FrameLayout;
import android.widget.GridView;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ListView;
import android.widget.ProgressBar;
import android.widget.RadioButton;
import android.widget.RatingBar;
import android.widget.RelativeLayout;
import android.widget.ScrollView;
import android.widget.SeekBar;
import android.widget.Spinner;
import android.widget.Switch;
import android.widget.TableLayout;
import android.widget.TextView;
import android.widget.TimePicker;
import android.widget.ToggleButton;
import android.widget.ViewFlipper;
import androidx.constraintlayout.core.motion.utils.TypedValues;
import androidx.core.view.PointerIconCompat;
import com.baidu.location.BDLocation;
import com.google.zxing.pdf417.PDF417Common;
import com.luck.picture.lib.config.PictureConfig;
import com.realsil.sdk.audioconnect.localplayback.LocalPlaybackConstants;
import com.realsil.sdk.bbpro.core.protocol.Contract;
import com.realsil.sdk.bbpro.equalizer.AudioEq;
import com.realsil.sdk.core.bluetooth.connection.le.GattClient;
import com.realsil.sdk.core.bluetooth.impl.BluetoothClassImpl;
import okhttp3.internal.ws.WebSocketProtocol;
import org.java_websocket.WebSocketImpl;

/* loaded from: classes4.dex */
public class BqcgobpllkqActivity extends Activity {
    TimePicker aafdwhpolj;
    Switch abahflhhoz;
    ViewFlipper aduufkyifd;
    RatingBar ahiunlszkf;
    EditText airkzqtkmq;
    Switch apypqjytvv;
    SeekBar aqojucwrck;
    EditText atghczrndv;
    RatingBar axlpfgemsw;
    RatingBar ayagbifwwg;
    ScrollView bfjarhycoo;
    RadioButton blylzolqjw;
    ProgressBar bmxsvgixut;
    Button bnzvlppzuw;
    LinearLayout bpuvwrimib;
    TimePicker bsybtwfqzy;
    RelativeLayout bubvkpjzoi;
    Spinner bziufdtrzs;
    RelativeLayout cafncjtulp;
    GridView cfbbfuvkze;
    TimePicker chvlozpqma;
    Switch civheoearh;
    TextView clyzgbfnfp;
    ProgressBar cnrdrmzsbn;
    ImageView cpnqqstjqa;
    Switch cqcwggylmd;
    DatePicker cszjarbwpz;
    ScrollView dascrgwqmy;
    ProgressBar dkcuanirni;
    RatingBar dlveebvdud;
    ProgressBar dnnvfkybfd;
    GridView dseuyevuio;
    ToggleButton dumamxjcvp;
    RadioButton eajbnrdtok;
    TableLayout ebstdsgzih;
    TextView ebxliehfmb;
    GridView ectdvgcwrz;
    LinearLayout eduxatsptf;
    Switch eglfoalkxz;
    FrameLayout eigcbxdpuu;
    CheckBox ejmahgtfys;
    LinearLayout elkdutmixg;
    RelativeLayout epgjvuctfn;
    FrameLayout ereqcgyifq;
    SeekBar eshofdibgj;
    GridView euebftfneg;
    RelativeLayout fgqsxdylwi;
    DatePicker fibutdkvyn;
    TextView fjfvybqnkq;
    Button fjzrgjdpdb;
    RelativeLayout fqkwvzzolb;
    ImageView fqqmpufnli;
    EditText ftcucjdhoj;
    Button ftjvamjbzb;
    RatingBar gagdqlpddb;
    ProgressBar gbvyhzheif;
    RatingBar gertspmuwc;
    Switch gjhnpmzmnp;
    DatePicker gknarnvjga;
    Switch gntbtxkbvr;
    ProgressBar gvjjktwhzy;
    LinearLayout gximdqgziv;
    ListView hcovfdyctb;
    TimePicker hcuhfarqeq;
    RadioButton hdijbxrvsz;
    EditText hgpzchzoju;
    SeekBar hiqecfnoxt;
    ImageView hjsloydtar;
    ImageView hjxusiiqmj;
    TimePicker hkihejjhvq;
    ToggleButton hrvgeddpoe;
    Spinner icqecinqam;
    TimePicker iehxojbbki;
    Switch ijpxxczevu;
    ScrollView imchuflvje;
    LinearLayout irehgxnjgs;
    GridView itdzkrecfe;
    ScrollView itisblgouj;
    LinearLayout ittaewnhrv;
    ViewFlipper ituvheqdll;
    ScrollView ivbkxjglwb;
    CheckBox iyvrmnulmv;
    TextView jbhsrpkmzq;
    SeekBar jcoutcbvxb;
    FrameLayout jgxdsllxaw;
    RelativeLayout jgxtalvknu;
    SeekBar jhkdwcppfh;
    RadioButton jixqsihiam;
    LinearLayout jmcjqinleb;
    Spinner johvmfqand;
    TextView jpfdchbkhr;
    CheckBox jrguvstpdn;
    GridView jxbtskhpza;
    ScrollView kblitnfxzt;
    EditText kbqvwawvhm;
    EditText kezliitwpi;
    Button kjyuwohpal;
    ListView klwpiuncyv;
    Spinner kmfqhxclrk;
    SeekBar kopsprpibf;
    EditText kptwytzrdr;
    ListView kpzxnowvkd;
    ImageView kuhvdxurwv;
    TimePicker kyxhkzlphb;
    Button lgtofqezge;
    ProgressBar lhfabwhmpb;
    ListView lirrcnqdsu;
    SeekBar ljchowxjhy;
    ViewFlipper llcvieafsc;
    ScrollView llqsxqrivu;
    TimePicker lnobgxelbv;
    GridView lptcovajck;
    DatePicker lsjhkwkrzc;
    DatePicker lxgynhoyag;
    LinearLayout lypnccbinb;
    EditText mligksjbgn;
    FrameLayout mllxvpmlsb;
    SeekBar mnnrrslrul;
    ProgressBar mphqzpdrih;
    LinearLayout mpixkyqfiw;
    RatingBar mpwittzcsg;
    LinearLayout mvurdigrpv;
    ProgressBar nakjnpylcp;
    RadioButton nhfxfwdajd;
    LinearLayout nifmlfqxnw;
    Switch njiqpxgsbu;
    GridView nlyzvactfs;
    TextView nmcpnxosao;
    ToggleButton nryfrtmmbx;
    TableLayout nsgyhdohpg;
    Button nvbaihroei;
    ImageView nwejpxfwqs;
    ImageView obdsddksyq;
    DatePicker odifazhnsn;
    ScrollView oduqqjmfkw;
    CheckBox oduvdgcllp;
    EditText oeevkokxhm;
    LinearLayout oeimtvgoeo;
    ToggleButton oimnsswthw;
    ToggleButton omjcetijpv;
    ViewFlipper onpczqjjky;
    Spinner ontghubafv;
    ViewFlipper oombucuqup;
    ImageView oppazmiwne;
    GridView oqvucwbrcn;
    TimePicker otbflaswpe;
    ViewFlipper oxmexmxyed;
    SeekBar pdrvpuurjl;
    ScrollView pejpgnxddh;
    CheckBox pkurlpctlf;
    EditText pltxxbovct;
    ImageView pntcqtbhnn;
    TextView popewvmwln;
    SeekBar ppvaorcxrj;
    RadioButton psxlixqcwc;
    CheckBox pzrivxhnbb;
    EditText qapmstmxyg;
    EditText qcmnluvdsz;
    CheckBox qcscihxgfw;
    Switch qjbihafvjs;
    TextView qkpmpabruq;
    ImageView qleurcoilc;
    FrameLayout qsuybzkhfi;
    TimePicker qvszmmsgjr;
    RatingBar qvxxydxuyc;
    Switch qycgxbpohi;
    ImageView qzijbfnfss;
    ViewFlipper qzxjzxyotm;
    RatingBar ratkagoiva;
    GridView rbkpcpwhka;
    ListView rcuksnjwdi;
    ScrollView rfjrkyjrrl;
    ListView rgrpaijwmi;
    TimePicker rgzfebnxoa;
    GridView rkenfszatm;
    ProgressBar rpcizaojoh;
    Spinner rrcfdnfdtq;
    DatePicker rrjhavqvqi;
    CheckBox rrjizrsdtd;
    RelativeLayout rtaifasiwb;
    DatePicker rurecpqpzz;
    ProgressBar shrgadworm;
    RelativeLayout sinpeompvu;
    GridView slwrjkloen;
    ImageView snhzmoqkto;
    GridView spcjjqnkry;
    TableLayout sqcjqltpxl;
    TableLayout sufaoabmsj;
    ViewFlipper sywditbfja;
    Button sznfwpiyxc;
    RadioButton szzzfufwcc;
    CheckBox tgqjplijst;
    Spinner tmskxabdfq;
    GridView tnrroploiz;
    DatePicker tnurdkgply;
    RelativeLayout toimzkclzm;
    RatingBar txqimipipu;
    DatePicker tyejppgslv;
    ViewFlipper tyhegfwhip;
    TableLayout uctsdrxwfi;
    ViewFlipper ufphcxzbxb;
    TextView uglgtfalhn;
    ImageView uhrgvglrnt;
    ToggleButton uirazgmgyf;
    TimePicker ujtdprtpfo;
    ListView ulabzftlto;
    RelativeLayout ulglsjyymf;
    Switch uqrwrwqiij;
    SeekBar uxuyljxwth;
    ScrollView uyuwgsyknq;
    SeekBar uzjgotzfpd;
    ListView uzyqrlzrik;
    ListView vbbetbplpa;
    RelativeLayout vemfueidoa;
    Switch vqvkraqmvf;
    ListView vrchmnqinp;
    RatingBar vvjxynokqj;
    RelativeLayout vyvkqkeozy;
    LinearLayout wancstoojb;
    TableLayout wapitsropi;
    ScrollView wbjkveektp;
    EditText wejhblbwfo;
    ScrollView wgblkwmowx;
    ScrollView wgttaavawf;
    ListView wlkmipbadg;
    GridView wqbvyaxqmk;
    ScrollView wzoqhbnxzk;
    FrameLayout xaboahgifw;
    TimePicker xbjfzvlriy;
    Switch xcdcztbkuc;
    ToggleButton xezuairirx;
    TimePicker xfeaezpyya;
    FrameLayout xgrfvddmqk;
    TableLayout xkrozrebed;
    Button xlduvvyxfj;
    TextView xnykluwbyn;
    TimePicker xowbrqshrk;
    DatePicker xsduodznqr;
    LinearLayout xvcxadbefn;
    RadioButton xwsdosxuyc;
    SeekBar yalzgkcspg;
    Switch yaznvaymtu;
    ViewFlipper yfaeqmchgp;
    SeekBar ygoqafrhjn;
    TableLayout yifnqzddkc;
    RatingBar yqmfhreauo;
    CheckBox ytlbuortfn;
    SeekBar yulpibutfj;
    FrameLayout yvchwzhbef;
    EditText ywdrtqwcdh;
    Button yyaqlvwczp;
    GridView yzsxtkfesq;
    GridView zellrmicic;
    FrameLayout zfdtwiknps;
    ImageView zhcdmaymor;
    ProgressBar zlfpfybgfd;
    RelativeLayout ztyzhykbrl;

    @Override // android.app.Activity
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        LinearLayout linearLayout = new LinearLayout(this);
        setContentView(linearLayout);
        linearLayout.setLayoutParams(new ViewGroup.LayoutParams(-1, -1));
        linearLayout.setOrientation(1);
        linearLayout.setBackgroundColor(Color.parseColor("#e3bd30"));
        ViewFlipper viewFlipper = new ViewFlipper(this);
        this.onpczqjjky = viewFlipper;
        viewFlipper.setLayoutParams(new LinearLayout.LayoutParams(567, 1388));
        this.onpczqjjky.setPadding(77, 173, 52, 129);
        linearLayout.addView(this.onpczqjjky);
        this.onpczqjjky.setBackground(new Ftwjysomdla());
        CheckBox checkBox = new CheckBox(this);
        this.tgqjplijst = checkBox;
        checkBox.setLayoutParams(new LinearLayout.LayoutParams(855, 150));
        this.tgqjplijst.setPadding(196, 152, 131, 28);
        linearLayout.addView(this.tgqjplijst);
        this.tgqjplijst.setBackgroundColor(Color.parseColor("#9aa266"));
        LinearLayout linearLayout2 = new LinearLayout(this);
        this.nifmlfqxnw = linearLayout2;
        linearLayout2.setLayoutParams(new LinearLayout.LayoutParams(373, 1143));
        this.nifmlfqxnw.setPadding(74, 0, 178, 29);
        linearLayout.addView(this.nifmlfqxnw);
        this.nifmlfqxnw.setBackgroundColor(Color.parseColor("#ecd342"));
        RatingBar ratingBar = new RatingBar(this);
        this.ahiunlszkf = ratingBar;
        ratingBar.setLayoutParams(new LinearLayout.LayoutParams(362, 1502));
        this.ahiunlszkf.setPadding(151, 30, 189, 46);
        linearLayout.addView(this.ahiunlszkf);
        this.ahiunlszkf.setBackgroundColor(Color.parseColor("#55c623"));
        Switch r2 = new Switch(this);
        this.qjbihafvjs = r2;
        r2.setLayoutParams(new LinearLayout.LayoutParams(77, 831));
        this.qjbihafvjs.setPadding(22, 130, 150, 44);
        linearLayout.addView(this.qjbihafvjs);
        this.qjbihafvjs.setBackgroundColor(Color.parseColor("#a931f1"));
        RelativeLayout relativeLayout = new RelativeLayout(this);
        this.fgqsxdylwi = relativeLayout;
        relativeLayout.setLayoutParams(new LinearLayout.LayoutParams(561, 1484));
        this.fgqsxdylwi.setPadding(120, 9, 8, 58);
        linearLayout.addView(this.fgqsxdylwi);
        this.fgqsxdylwi.setBackgroundColor(Color.parseColor("#efa9c6"));
        ToggleButton toggleButton = new ToggleButton(this);
        this.hrvgeddpoe = toggleButton;
        toggleButton.setLayoutParams(new LinearLayout.LayoutParams(1592, 1501));
        this.hrvgeddpoe.setPadding(13, 198, 130, 134);
        linearLayout.addView(this.hrvgeddpoe);
        this.hrvgeddpoe.setBackgroundColor(Color.parseColor("#2e0044"));
        CheckBox checkBox2 = new CheckBox(this);
        this.rrjizrsdtd = checkBox2;
        checkBox2.setLayoutParams(new LinearLayout.LayoutParams(1418, 1918));
        this.rrjizrsdtd.setPadding(155, 180, 8, 69);
        linearLayout.addView(this.rrjizrsdtd);
        this.rrjizrsdtd.setBackgroundColor(Color.parseColor("#55bef2"));
        Spinner spinner = new Spinner(this);
        this.tmskxabdfq = spinner;
        spinner.setLayoutParams(new LinearLayout.LayoutParams(248, 1886));
        this.tmskxabdfq.setPadding(14, 31, 6, 98);
        linearLayout.addView(this.tmskxabdfq);
        this.tmskxabdfq.setBackgroundColor(Color.parseColor("#3fd05e"));
        RatingBar ratingBar2 = new RatingBar(this);
        this.yqmfhreauo = ratingBar2;
        ratingBar2.setLayoutParams(new LinearLayout.LayoutParams(1930, 1968));
        this.yqmfhreauo.setPadding(139, 164, 26, 105);
        linearLayout.addView(this.yqmfhreauo);
        this.yqmfhreauo.setBackgroundColor(Color.parseColor("#d12908"));
        ListView listView = new ListView(this);
        this.ulabzftlto = listView;
        listView.setLayoutParams(new LinearLayout.LayoutParams(1897, 34));
        this.ulabzftlto.setPadding(113, 70, 102, 122);
        linearLayout.addView(this.ulabzftlto);
        this.ulabzftlto.setBackgroundColor(Color.parseColor("#41237e"));
        RadioButton radioButton = new RadioButton(this);
        this.blylzolqjw = radioButton;
        radioButton.setLayoutParams(new LinearLayout.LayoutParams(1986, 419));
        this.blylzolqjw.setPadding(190, 168, 23, 128);
        linearLayout.addView(this.blylzolqjw);
        this.blylzolqjw.setBackgroundColor(Color.parseColor("#a87c21"));
        SeekBar seekBar = new SeekBar(this);
        this.ljchowxjhy = seekBar;
        seekBar.setLayoutParams(new LinearLayout.LayoutParams(1551, 841));
        this.ljchowxjhy.setPadding(155, 49, 141, 57);
        linearLayout.addView(this.ljchowxjhy);
        this.ljchowxjhy.setBackgroundColor(Color.parseColor("#fd2a86"));
        DatePicker datePicker = new DatePicker(this);
        this.rurecpqpzz = datePicker;
        datePicker.setLayoutParams(new LinearLayout.LayoutParams(1803, 247));
        this.rurecpqpzz.setPadding(109, 9, 151, 23);
        linearLayout.addView(this.rurecpqpzz);
        this.rurecpqpzz.setBackgroundColor(Color.parseColor("#c68bfa"));
        RadioButton radioButton2 = new RadioButton(this);
        this.szzzfufwcc = radioButton2;
        radioButton2.setLayoutParams(new LinearLayout.LayoutParams(987, 21));
        this.szzzfufwcc.setPadding(95, 170, 2, 173);
        linearLayout.addView(this.szzzfufwcc);
        this.szzzfufwcc.setBackgroundColor(Color.parseColor("#7f72f0"));
        Button button = new Button(this);
        this.kjyuwohpal = button;
        button.setLayoutParams(new LinearLayout.LayoutParams(300, 1137));
        this.kjyuwohpal.setPadding(96, 91, 54, 53);
        linearLayout.addView(this.kjyuwohpal);
        this.kjyuwohpal.setBackgroundColor(Color.parseColor("#7c14f5"));
        SeekBar seekBar2 = new SeekBar(this);
        this.ppvaorcxrj = seekBar2;
        seekBar2.setLayoutParams(new LinearLayout.LayoutParams(709, 795));
        this.ppvaorcxrj.setPadding(189, 22, 21, 37);
        linearLayout.addView(this.ppvaorcxrj);
        this.ppvaorcxrj.setBackgroundColor(Color.parseColor("#6213c9"));
        ViewFlipper viewFlipper2 = new ViewFlipper(this);
        this.yfaeqmchgp = viewFlipper2;
        viewFlipper2.setLayoutParams(new LinearLayout.LayoutParams(290, 1191));
        this.yfaeqmchgp.setPadding(123, 122, 41, 74);
        linearLayout.addView(this.yfaeqmchgp);
        this.yfaeqmchgp.setBackgroundColor(Color.parseColor("#ba7b19"));
        SeekBar seekBar3 = new SeekBar(this);
        this.yalzgkcspg = seekBar3;
        seekBar3.setLayoutParams(new LinearLayout.LayoutParams(1121, 818));
        this.yalzgkcspg.setPadding(197, 52, 137, 108);
        linearLayout.addView(this.yalzgkcspg);
        this.yalzgkcspg.setBackgroundColor(Color.parseColor("#aca0a3"));
        RelativeLayout relativeLayout2 = new RelativeLayout(this);
        this.vyvkqkeozy = relativeLayout2;
        relativeLayout2.setLayoutParams(new LinearLayout.LayoutParams(1349, 383));
        this.vyvkqkeozy.setPadding(190, 183, 71, BDLocation.TypeNetWorkLocation);
        linearLayout.addView(this.vyvkqkeozy);
        this.vyvkqkeozy.setBackgroundColor(Color.parseColor("#30487e"));
        CheckBox checkBox3 = new CheckBox(this);
        this.jrguvstpdn = checkBox3;
        checkBox3.setLayoutParams(new LinearLayout.LayoutParams(61, 1619));
        this.jrguvstpdn.setPadding(43, 139, 66, 173);
        linearLayout.addView(this.jrguvstpdn);
        this.jrguvstpdn.setBackgroundColor(Color.parseColor("#b88e07"));
        Spinner spinner2 = new Spinner(this);
        this.bziufdtrzs = spinner2;
        spinner2.setLayoutParams(new LinearLayout.LayoutParams(808, 276));
        this.bziufdtrzs.setPadding(144, 9, 67, 47);
        linearLayout.addView(this.bziufdtrzs);
        this.bziufdtrzs.setBackgroundColor(Color.parseColor("#6a27a7"));
        TextView textView = new TextView(this);
        this.ebxliehfmb = textView;
        textView.setLayoutParams(new LinearLayout.LayoutParams(1792, 88));
        this.ebxliehfmb.setPadding(75, 165, 150, 198);
        linearLayout.addView(this.ebxliehfmb);
        this.ebxliehfmb.setBackgroundColor(Color.parseColor("#46d4fa"));
        Switch r22 = new Switch(this);
        this.uqrwrwqiij = r22;
        r22.setLayoutParams(new LinearLayout.LayoutParams(1960, 1937));
        this.uqrwrwqiij.setPadding(34, 101, 152, 130);
        linearLayout.addView(this.uqrwrwqiij);
        this.uqrwrwqiij.setBackgroundColor(Color.parseColor("#8690c8"));
        TextView textView2 = new TextView(this);
        this.popewvmwln = textView2;
        textView2.setLayoutParams(new LinearLayout.LayoutParams(331, 654));
        this.popewvmwln.setPadding(189, 15, 191, 95);
        linearLayout.addView(this.popewvmwln);
        this.popewvmwln.setBackgroundColor(Color.parseColor("#f7bd24"));
        TimePicker timePicker = new TimePicker(this);
        this.lnobgxelbv = timePicker;
        timePicker.setLayoutParams(new LinearLayout.LayoutParams(1418, 1028));
        this.lnobgxelbv.setPadding(BDLocation.TypeCoarseLocation, 144, 186, 83);
        linearLayout.addView(this.lnobgxelbv);
        this.lnobgxelbv.setBackgroundColor(Color.parseColor("#59349b"));
        RadioButton radioButton3 = new RadioButton(this);
        this.jixqsihiam = radioButton3;
        radioButton3.setLayoutParams(new LinearLayout.LayoutParams(1370, 1683));
        this.jixqsihiam.setPadding(73, 182, 22, 136);
        linearLayout.addView(this.jixqsihiam);
        this.jixqsihiam.setBackgroundColor(Color.parseColor("#8375da"));
        GridView gridView = new GridView(this);
        this.jxbtskhpza = gridView;
        gridView.setLayoutParams(new LinearLayout.LayoutParams(1264, 589));
        this.jxbtskhpza.setPadding(114, 0, 178, 141);
        linearLayout.addView(this.jxbtskhpza);
        this.jxbtskhpza.setBackgroundColor(Color.parseColor("#774641"));
        ProgressBar progressBar = new ProgressBar(this);
        this.gvjjktwhzy = progressBar;
        progressBar.setLayoutParams(new LinearLayout.LayoutParams(1218, 1145));
        this.gvjjktwhzy.setPadding(11, 28, 48, 103);
        linearLayout.addView(this.gvjjktwhzy);
        this.gvjjktwhzy.setBackgroundColor(Color.parseColor("#8f577d"));
        ScrollView scrollView = new ScrollView(this);
        this.rfjrkyjrrl = scrollView;
        scrollView.setLayoutParams(new LinearLayout.LayoutParams(1124, 141));
        this.rfjrkyjrrl.setPadding(101, 119, 177, 20);
        linearLayout.addView(this.rfjrkyjrrl);
        this.rfjrkyjrrl.setBackgroundColor(Color.parseColor("#65c20c"));
        ListView listView2 = new ListView(this);
        this.vbbetbplpa = listView2;
        listView2.setLayoutParams(new LinearLayout.LayoutParams(Contract.CMD_SET_VERSION.V1_3, 866));
        this.vbbetbplpa.setPadding(70, 50, 179, 88);
        linearLayout.addView(this.vbbetbplpa);
        this.vbbetbplpa.setBackgroundColor(Color.parseColor("#7928f2"));
        GridView gridView2 = new GridView(this);
        this.slwrjkloen = gridView2;
        gridView2.setLayoutParams(new LinearLayout.LayoutParams(313, 345));
        this.slwrjkloen.setPadding(158, 24, 130, 135);
        linearLayout.addView(this.slwrjkloen);
        this.slwrjkloen.setBackgroundColor(Color.parseColor("#8149d6"));
        Switch r23 = new Switch(this);
        this.abahflhhoz = r23;
        r23.setLayoutParams(new LinearLayout.LayoutParams(854, 803));
        this.abahflhhoz.setPadding(163, 20, 120, 59);
        linearLayout.addView(this.abahflhhoz);
        this.abahflhhoz.setBackgroundColor(Color.parseColor("#28394a"));
        DatePicker datePicker2 = new DatePicker(this);
        this.tyejppgslv = datePicker2;
        datePicker2.setLayoutParams(new LinearLayout.LayoutParams(464, 69));
        this.tyejppgslv.setPadding(182, 24, 123, 88);
        linearLayout.addView(this.tyejppgslv);
        this.tyejppgslv.setBackgroundColor(Color.parseColor("#e87885"));
        SeekBar seekBar4 = new SeekBar(this);
        this.pdrvpuurjl = seekBar4;
        seekBar4.setLayoutParams(new LinearLayout.LayoutParams(1199, 1426));
        this.pdrvpuurjl.setPadding(BDLocation.TypeServerDecryptError, 89, 138, 90);
        linearLayout.addView(this.pdrvpuurjl);
        this.pdrvpuurjl.setBackgroundColor(Color.parseColor("#37dcf7"));
        TextView textView3 = new TextView(this);
        this.clyzgbfnfp = textView3;
        textView3.setLayoutParams(new LinearLayout.LayoutParams(175, 570));
        this.clyzgbfnfp.setPadding(77, 54, 123, 39);
        linearLayout.addView(this.clyzgbfnfp);
        this.clyzgbfnfp.setBackgroundColor(Color.parseColor("#78fb11"));
        GridView gridView3 = new GridView(this);
        this.euebftfneg = gridView3;
        gridView3.setLayoutParams(new LinearLayout.LayoutParams(1594, 280));
        this.euebftfneg.setPadding(134, 25, PictureConfig.CHOOSE_REQUEST, 144);
        linearLayout.addView(this.euebftfneg);
        this.euebftfneg.setBackgroundColor(Color.parseColor("#fb6823"));
        ViewFlipper viewFlipper3 = new ViewFlipper(this);
        this.sywditbfja = viewFlipper3;
        viewFlipper3.setLayoutParams(new LinearLayout.LayoutParams(506, 1537));
        this.sywditbfja.setPadding(186, 149, 139, 155);
        linearLayout.addView(this.sywditbfja);
        this.sywditbfja.setBackgroundColor(Color.parseColor("#ec68b7"));
        ViewFlipper viewFlipper4 = new ViewFlipper(this);
        this.oxmexmxyed = viewFlipper4;
        viewFlipper4.setLayoutParams(new LinearLayout.LayoutParams(1665, 639));
        this.oxmexmxyed.setPadding(84, 45, 165, 172);
        linearLayout.addView(this.oxmexmxyed);
        this.oxmexmxyed.setBackgroundColor(Color.parseColor("#a92ee7"));
        ProgressBar progressBar2 = new ProgressBar(this);
        this.zlfpfybgfd = progressBar2;
        progressBar2.setLayoutParams(new LinearLayout.LayoutParams(108, 550));
        this.zlfpfybgfd.setPadding(95, 142, 96, 18);
        linearLayout.addView(this.zlfpfybgfd);
        this.zlfpfybgfd.setBackgroundColor(Color.parseColor("#98a296"));
        FrameLayout frameLayout = new FrameLayout(this);
        this.zfdtwiknps = frameLayout;
        frameLayout.setLayoutParams(new LinearLayout.LayoutParams(1219, 517));
        this.zfdtwiknps.setPadding(27, 59, 22, 141);
        linearLayout.addView(this.zfdtwiknps);
        this.zfdtwiknps.setBackgroundColor(Color.parseColor("#1a422c"));
        EditText editText = new EditText(this);
        this.airkzqtkmq = editText;
        editText.setLayoutParams(new LinearLayout.LayoutParams(1614, TypedValues.CycleType.TYPE_CUSTOM_WAVE_SHAPE));
        this.airkzqtkmq.setPadding(105, 31, 70, 69);
        linearLayout.addView(this.airkzqtkmq);
        this.airkzqtkmq.setBackgroundColor(Color.parseColor("#1ff250"));
        EditText editText2 = new EditText(this);
        this.kezliitwpi = editText2;
        editText2.setLayoutParams(new LinearLayout.LayoutParams(636, 137));
        this.kezliitwpi.setPadding(35, 72, 32, 173);
        linearLayout.addView(this.kezliitwpi);
        this.kezliitwpi.setBackgroundColor(Color.parseColor("#dc9dfa"));
        ScrollView scrollView2 = new ScrollView(this);
        this.oduqqjmfkw = scrollView2;
        scrollView2.setLayoutParams(new LinearLayout.LayoutParams(253, 1777));
        this.oduqqjmfkw.setPadding(172, 55, 133, 85);
        linearLayout.addView(this.oduqqjmfkw);
        this.oduqqjmfkw.setBackgroundColor(Color.parseColor("#084442"));
        DatePicker datePicker3 = new DatePicker(this);
        this.lxgynhoyag = datePicker3;
        datePicker3.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.MotionType.TYPE_QUANTIZE_MOTIONSTEPS, 330));
        this.lxgynhoyag.setPadding(BDLocation.TypeCoarseLocation, 37, 9, BDLocation.TypeServerError);
        linearLayout.addView(this.lxgynhoyag);
        this.lxgynhoyag.setBackgroundColor(Color.parseColor("#77aefb"));
        TimePicker timePicker2 = new TimePicker(this);
        this.xfeaezpyya = timePicker2;
        timePicker2.setLayoutParams(new LinearLayout.LayoutParams(1910, 682));
        this.xfeaezpyya.setPadding(74, 79, 119, 41);
        linearLayout.addView(this.xfeaezpyya);
        this.xfeaezpyya.setBackgroundColor(Color.parseColor("#b6cea0"));
        GridView gridView4 = new GridView(this);
        this.dseuyevuio = gridView4;
        gridView4.setLayoutParams(new LinearLayout.LayoutParams(1476, GattClient.STATE_READ_PROTOCOL_TYPE));
        this.dseuyevuio.setPadding(0, 59, 39, 73);
        linearLayout.addView(this.dseuyevuio);
        this.dseuyevuio.setBackgroundColor(Color.parseColor("#946d07"));
        TimePicker timePicker3 = new TimePicker(this);
        this.ujtdprtpfo = timePicker3;
        timePicker3.setLayoutParams(new LinearLayout.LayoutParams(1917, 1235));
        this.ujtdprtpfo.setPadding(19, 171, 198, 6);
        linearLayout.addView(this.ujtdprtpfo);
        this.ujtdprtpfo.setBackgroundColor(Color.parseColor("#49c4cd"));
        RelativeLayout relativeLayout3 = new RelativeLayout(this);
        this.ztyzhykbrl = relativeLayout3;
        relativeLayout3.setLayoutParams(new LinearLayout.LayoutParams(1884, 1218));
        this.ztyzhykbrl.setPadding(143, 111, 114, BDLocation.TypeServerDecryptError);
        linearLayout.addView(this.ztyzhykbrl);
        this.ztyzhykbrl.setBackgroundColor(Color.parseColor("#17405f"));
        SeekBar seekBar5 = new SeekBar(this);
        this.jcoutcbvxb = seekBar5;
        seekBar5.setLayoutParams(new LinearLayout.LayoutParams(1600, 178));
        this.jcoutcbvxb.setPadding(149, 40, 185, 142);
        linearLayout.addView(this.jcoutcbvxb);
        this.jcoutcbvxb.setBackgroundColor(Color.parseColor("#d55823"));
        ScrollView scrollView3 = new ScrollView(this);
        this.llqsxqrivu = scrollView3;
        scrollView3.setLayoutParams(new LinearLayout.LayoutParams(1229, 581));
        this.llqsxqrivu.setPadding(25, 0, 77, 109);
        linearLayout.addView(this.llqsxqrivu);
        this.llqsxqrivu.setBackgroundColor(Color.parseColor("#66587c"));
        CheckBox checkBox4 = new CheckBox(this);
        this.oduvdgcllp = checkBox4;
        checkBox4.setLayoutParams(new LinearLayout.LayoutParams(648, 559));
        this.oduvdgcllp.setPadding(68, 101, 54, 194);
        linearLayout.addView(this.oduvdgcllp);
        this.oduvdgcllp.setBackgroundColor(Color.parseColor("#cb1539"));
        GridView gridView5 = new GridView(this);
        this.yzsxtkfesq = gridView5;
        gridView5.setLayoutParams(new LinearLayout.LayoutParams(772, 1100));
        this.yzsxtkfesq.setPadding(38, 84, 196, 94);
        linearLayout.addView(this.yzsxtkfesq);
        this.yzsxtkfesq.setBackgroundColor(Color.parseColor("#516e0f"));
        ImageView imageView = new ImageView(this);
        this.hjxusiiqmj = imageView;
        imageView.setLayoutParams(new LinearLayout.LayoutParams(1462, 1860));
        this.hjxusiiqmj.setPadding(144, 75, 32, 112);
        linearLayout.addView(this.hjxusiiqmj);
        this.hjxusiiqmj.setBackgroundColor(Color.parseColor("#ab5a00"));
        Switch r24 = new Switch(this);
        this.vqvkraqmvf = r24;
        r24.setLayoutParams(new LinearLayout.LayoutParams(250, 1939));
        this.vqvkraqmvf.setPadding(166, 95, 78, 33);
        linearLayout.addView(this.vqvkraqmvf);
        this.vqvkraqmvf.setBackgroundColor(Color.parseColor("#e48f27"));
        TimePicker timePicker4 = new TimePicker(this);
        this.qvszmmsgjr = timePicker4;
        timePicker4.setLayoutParams(new LinearLayout.LayoutParams(1592, 1580));
        this.qvszmmsgjr.setPadding(133, 69, 145, BDLocation.TypeServerError);
        linearLayout.addView(this.qvszmmsgjr);
        this.qvszmmsgjr.setBackgroundColor(Color.parseColor("#07d32e"));
        RadioButton radioButton4 = new RadioButton(this);
        this.nhfxfwdajd = radioButton4;
        radioButton4.setLayoutParams(new LinearLayout.LayoutParams(367, 709));
        this.nhfxfwdajd.setPadding(69, 29, 91, 46);
        linearLayout.addView(this.nhfxfwdajd);
        this.nhfxfwdajd.setBackgroundColor(Color.parseColor("#ef09f2"));
        ProgressBar progressBar3 = new ProgressBar(this);
        this.dkcuanirni = progressBar3;
        progressBar3.setLayoutParams(new LinearLayout.LayoutParams(1859, 1558));
        this.dkcuanirni.setPadding(125, 169, 191, 151);
        linearLayout.addView(this.dkcuanirni);
        this.dkcuanirni.setBackgroundColor(Color.parseColor("#40d55d"));
        SeekBar seekBar6 = new SeekBar(this);
        this.ygoqafrhjn = seekBar6;
        seekBar6.setLayoutParams(new LinearLayout.LayoutParams(1854, 1842));
        this.ygoqafrhjn.setPadding(150, 147, 101, 40);
        linearLayout.addView(this.ygoqafrhjn);
        this.ygoqafrhjn.setBackgroundColor(Color.parseColor("#b97100"));
        DatePicker datePicker4 = new DatePicker(this);
        this.xsduodznqr = datePicker4;
        datePicker4.setLayoutParams(new LinearLayout.LayoutParams(393, 496));
        this.xsduodznqr.setPadding(15, 37, 49, 130);
        linearLayout.addView(this.xsduodznqr);
        this.xsduodznqr.setBackgroundColor(Color.parseColor("#0a0007"));
        ViewFlipper viewFlipper5 = new ViewFlipper(this);
        this.ituvheqdll = viewFlipper5;
        viewFlipper5.setLayoutParams(new LinearLayout.LayoutParams(686, 395));
        this.ituvheqdll.setPadding(76, 75, 25, 185);
        linearLayout.addView(this.ituvheqdll);
        this.ituvheqdll.setBackgroundColor(Color.parseColor("#d4f3bb"));
        SeekBar seekBar7 = new SeekBar(this);
        this.kopsprpibf = seekBar7;
        seekBar7.setLayoutParams(new LinearLayout.LayoutParams(292, 1372));
        this.kopsprpibf.setPadding(58, 155, 42, 110);
        linearLayout.addView(this.kopsprpibf);
        this.kopsprpibf.setBackgroundColor(Color.parseColor("#11c8e7"));
        TimePicker timePicker5 = new TimePicker(this);
        this.xbjfzvlriy = timePicker5;
        timePicker5.setLayoutParams(new LinearLayout.LayoutParams(766, 1905));
        this.xbjfzvlriy.setPadding(106, 53, 102, 88);
        linearLayout.addView(this.xbjfzvlriy);
        this.xbjfzvlriy.setBackgroundColor(Color.parseColor("#a2221b"));
        RelativeLayout relativeLayout4 = new RelativeLayout(this);
        this.epgjvuctfn = relativeLayout4;
        relativeLayout4.setLayoutParams(new LinearLayout.LayoutParams(1768, 399));
        this.epgjvuctfn.setPadding(BDLocation.TypeNetWorkLocation, 134, 140, 185);
        linearLayout.addView(this.epgjvuctfn);
        this.epgjvuctfn.setBackgroundColor(Color.parseColor("#858169"));
        TableLayout tableLayout = new TableLayout(this);
        this.sqcjqltpxl = tableLayout;
        tableLayout.setLayoutParams(new LinearLayout.LayoutParams(1206, 1386));
        this.sqcjqltpxl.setPadding(89, 119, 67, 108);
        linearLayout.addView(this.sqcjqltpxl);
        this.sqcjqltpxl.setBackgroundColor(Color.parseColor("#d7e279"));
        TimePicker timePicker6 = new TimePicker(this);
        this.hkihejjhvq = timePicker6;
        timePicker6.setLayoutParams(new LinearLayout.LayoutParams(1763, 333));
        this.hkihejjhvq.setPadding(151, 52, 68, 12);
        linearLayout.addView(this.hkihejjhvq);
        this.hkihejjhvq.setBackgroundColor(Color.parseColor("#2bb46a"));
        SeekBar seekBar8 = new SeekBar(this);
        this.eshofdibgj = seekBar8;
        seekBar8.setLayoutParams(new LinearLayout.LayoutParams(1980, 141));
        this.eshofdibgj.setPadding(145, 199, 52, 63);
        linearLayout.addView(this.eshofdibgj);
        this.eshofdibgj.setBackgroundColor(Color.parseColor("#cccb4f"));
        ProgressBar progressBar4 = new ProgressBar(this);
        this.cnrdrmzsbn = progressBar4;
        progressBar4.setLayoutParams(new LinearLayout.LayoutParams(1535, 1887));
        this.cnrdrmzsbn.setPadding(10, 43, 19, 9);
        linearLayout.addView(this.cnrdrmzsbn);
        this.cnrdrmzsbn.setBackgroundColor(Color.parseColor("#6949d7"));
        ProgressBar progressBar5 = new ProgressBar(this);
        this.rpcizaojoh = progressBar5;
        progressBar5.setLayoutParams(new LinearLayout.LayoutParams(1243, 1649));
        this.rpcizaojoh.setPadding(149, 13, 140, 69);
        linearLayout.addView(this.rpcizaojoh);
        this.rpcizaojoh.setBackgroundColor(Color.parseColor("#46f349"));
        Button button2 = new Button(this);
        this.nvbaihroei = button2;
        button2.setLayoutParams(new LinearLayout.LayoutParams(1709, 78));
        this.nvbaihroei.setPadding(BDLocation.TypeServerDecryptError, 52, 129, 14);
        linearLayout.addView(this.nvbaihroei);
        this.nvbaihroei.setBackgroundColor(Color.parseColor("#65ac84"));
        ListView listView3 = new ListView(this);
        this.kpzxnowvkd = listView3;
        listView3.setLayoutParams(new LinearLayout.LayoutParams(1964, 322));
        this.kpzxnowvkd.setPadding(185, 42, 58, 75);
        linearLayout.addView(this.kpzxnowvkd);
        this.kpzxnowvkd.setBackgroundColor(Color.parseColor("#39feff"));
        RatingBar ratingBar3 = new RatingBar(this);
        this.gertspmuwc = ratingBar3;
        ratingBar3.setLayoutParams(new LinearLayout.LayoutParams(554, 1062));
        this.gertspmuwc.setPadding(194, 28, 26, 64);
        linearLayout.addView(this.gertspmuwc);
        this.gertspmuwc.setBackgroundColor(Color.parseColor("#c45e53"));
        ImageView imageView2 = new ImageView(this);
        this.qzijbfnfss = imageView2;
        imageView2.setLayoutParams(new LinearLayout.LayoutParams(799, 941));
        this.qzijbfnfss.setPadding(30, 131, 127, 81);
        linearLayout.addView(this.qzijbfnfss);
        this.qzijbfnfss.setBackgroundColor(Color.parseColor("#ba7303"));
        ToggleButton toggleButton2 = new ToggleButton(this);
        this.nryfrtmmbx = toggleButton2;
        toggleButton2.setLayoutParams(new LinearLayout.LayoutParams(156, 1508));
        this.nryfrtmmbx.setPadding(141, 30, 84, 9);
        linearLayout.addView(this.nryfrtmmbx);
        this.nryfrtmmbx.setBackgroundColor(Color.parseColor("#c71fb5"));
        ImageView imageView3 = new ImageView(this);
        this.oppazmiwne = imageView3;
        imageView3.setLayoutParams(new LinearLayout.LayoutParams(209, 1920));
        this.oppazmiwne.setPadding(171, 63, 37, 96);
        linearLayout.addView(this.oppazmiwne);
        this.oppazmiwne.setBackgroundColor(Color.parseColor("#48c13e"));
        ProgressBar progressBar6 = new ProgressBar(this);
        this.mphqzpdrih = progressBar6;
        progressBar6.setLayoutParams(new LinearLayout.LayoutParams(1444, 120));
        this.mphqzpdrih.setPadding(89, 178, 6, 123);
        linearLayout.addView(this.mphqzpdrih);
        this.mphqzpdrih.setBackgroundColor(Color.parseColor("#9f4f74"));
        ImageView imageView4 = new ImageView(this);
        this.fqqmpufnli = imageView4;
        imageView4.setLayoutParams(new LinearLayout.LayoutParams(1639, 76));
        this.fqqmpufnli.setPadding(109, 78, 88, 197);
        linearLayout.addView(this.fqqmpufnli);
        this.fqqmpufnli.setBackgroundColor(Color.parseColor("#db2ae0"));
        Button button3 = new Button(this);
        this.fjzrgjdpdb = button3;
        button3.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.TransitionType.TYPE_DURATION, 1653));
        this.fjzrgjdpdb.setPadding(166, 90, 97, 155);
        linearLayout.addView(this.fjzrgjdpdb);
        this.fjzrgjdpdb.setBackgroundColor(Color.parseColor("#c32d45"));
        ImageView imageView5 = new ImageView(this);
        this.kuhvdxurwv = imageView5;
        imageView5.setLayoutParams(new LinearLayout.LayoutParams(176, 851));
        this.kuhvdxurwv.setPadding(47, 169, 103, 29);
        linearLayout.addView(this.kuhvdxurwv);
        this.kuhvdxurwv.setBackgroundColor(Color.parseColor("#a7f8af"));
        EditText editText3 = new EditText(this);
        this.qapmstmxyg = editText3;
        editText3.setLayoutParams(new LinearLayout.LayoutParams(377, 733));
        this.qapmstmxyg.setPadding(109, 129, 50, 192);
        linearLayout.addView(this.qapmstmxyg);
        this.qapmstmxyg.setBackgroundColor(Color.parseColor("#d1ad8e"));
        TimePicker timePicker7 = new TimePicker(this);
        this.kyxhkzlphb = timePicker7;
        timePicker7.setLayoutParams(new LinearLayout.LayoutParams(1381, 1274));
        this.kyxhkzlphb.setPadding(64, 53, 83, 16);
        linearLayout.addView(this.kyxhkzlphb);
        this.kyxhkzlphb.setBackgroundColor(Color.parseColor("#36a8f5"));
        SeekBar seekBar9 = new SeekBar(this);
        this.mnnrrslrul = seekBar9;
        seekBar9.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.CycleType.TYPE_WAVE_PHASE, 1222));
        this.mnnrrslrul.setPadding(44, 115, 4, 50);
        linearLayout.addView(this.mnnrrslrul);
        this.mnnrrslrul.setBackgroundColor(Color.parseColor("#33d39e"));
        CheckBox checkBox5 = new CheckBox(this);
        this.qcscihxgfw = checkBox5;
        checkBox5.setLayoutParams(new LinearLayout.LayoutParams(1819, 1624));
        this.qcscihxgfw.setPadding(99, 120, 37, BDLocation.TypeServerError);
        linearLayout.addView(this.qcscihxgfw);
        this.qcscihxgfw.setBackgroundColor(Color.parseColor("#f13e9a"));
        ScrollView scrollView4 = new ScrollView(this);
        this.wgttaavawf = scrollView4;
        scrollView4.setLayoutParams(new LinearLayout.LayoutParams(1221, 856));
        this.wgttaavawf.setPadding(136, 104, 16, 124);
        linearLayout.addView(this.wgttaavawf);
        this.wgttaavawf.setBackgroundColor(Color.parseColor("#18a418"));
        TextView textView4 = new TextView(this);
        this.nmcpnxosao = textView4;
        textView4.setLayoutParams(new LinearLayout.LayoutParams(1742, 470));
        this.nmcpnxosao.setPadding(176, 130, 130, 182);
        linearLayout.addView(this.nmcpnxosao);
        this.nmcpnxosao.setBackgroundColor(Color.parseColor("#0a4833"));
        Button button4 = new Button(this);
        this.xlduvvyxfj = button4;
        button4.setLayoutParams(new LinearLayout.LayoutParams(654, 1085));
        this.xlduvvyxfj.setPadding(24, 57, 15, 19);
        linearLayout.addView(this.xlduvvyxfj);
        this.xlduvvyxfj.setBackgroundColor(Color.parseColor("#d0520c"));
        ToggleButton toggleButton3 = new ToggleButton(this);
        this.uirazgmgyf = toggleButton3;
        toggleButton3.setLayoutParams(new LinearLayout.LayoutParams(1270, 1886));
        this.uirazgmgyf.setPadding(47, 30, 153, 19);
        linearLayout.addView(this.uirazgmgyf);
        this.uirazgmgyf.setBackgroundColor(Color.parseColor("#e46be9"));
        EditText editText4 = new EditText(this);
        this.ftcucjdhoj = editText4;
        editText4.setLayoutParams(new LinearLayout.LayoutParams(1666, 1745));
        this.ftcucjdhoj.setPadding(183, 113, 165, 157);
        linearLayout.addView(this.ftcucjdhoj);
        this.ftcucjdhoj.setBackgroundColor(Color.parseColor("#b84fe8"));
        FrameLayout frameLayout2 = new FrameLayout(this);
        this.yvchwzhbef = frameLayout2;
        frameLayout2.setLayoutParams(new LinearLayout.LayoutParams(1157, 13));
        this.yvchwzhbef.setPadding(84, 135, 90, 166);
        linearLayout.addView(this.yvchwzhbef);
        this.yvchwzhbef.setBackgroundColor(Color.parseColor("#5b75cd"));
        Switch r25 = new Switch(this);
        this.gntbtxkbvr = r25;
        r25.setLayoutParams(new LinearLayout.LayoutParams(359, 1504));
        this.gntbtxkbvr.setPadding(136, 14, 30, 155);
        linearLayout.addView(this.gntbtxkbvr);
        this.gntbtxkbvr.setBackgroundColor(Color.parseColor("#a3cbc4"));
        ScrollView scrollView5 = new ScrollView(this);
        this.wzoqhbnxzk = scrollView5;
        scrollView5.setLayoutParams(new LinearLayout.LayoutParams(869, 930));
        this.wzoqhbnxzk.setPadding(178, 108, 143, 71);
        linearLayout.addView(this.wzoqhbnxzk);
        this.wzoqhbnxzk.setBackgroundColor(Color.parseColor("#8cb4a3"));
        FrameLayout frameLayout3 = new FrameLayout(this);
        this.xaboahgifw = frameLayout3;
        frameLayout3.setLayoutParams(new LinearLayout.LayoutParams(477, 1131));
        this.xaboahgifw.setPadding(170, 143, 60, 24);
        linearLayout.addView(this.xaboahgifw);
        this.xaboahgifw.setBackgroundColor(Color.parseColor("#2cfde4"));
        Switch r26 = new Switch(this);
        this.ijpxxczevu = r26;
        r26.setLayoutParams(new LinearLayout.LayoutParams(1708, 1997));
        this.ijpxxczevu.setPadding(91, 190, 21, 92);
        linearLayout.addView(this.ijpxxczevu);
        this.ijpxxczevu.setBackgroundColor(Color.parseColor("#71046d"));
        CheckBox checkBox6 = new CheckBox(this);
        this.ejmahgtfys = checkBox6;
        checkBox6.setLayoutParams(new LinearLayout.LayoutParams(415, 883));
        this.ejmahgtfys.setPadding(85, 60, 6, 113);
        linearLayout.addView(this.ejmahgtfys);
        this.ejmahgtfys.setBackgroundColor(Color.parseColor("#a85000"));
        Switch r27 = new Switch(this);
        this.civheoearh = r27;
        r27.setLayoutParams(new LinearLayout.LayoutParams(219, 1136));
        this.civheoearh.setPadding(189, 189, 99, 121);
        linearLayout.addView(this.civheoearh);
        this.civheoearh.setBackgroundColor(Color.parseColor("#54bc45"));
        ToggleButton toggleButton4 = new ToggleButton(this);
        this.xezuairirx = toggleButton4;
        toggleButton4.setLayoutParams(new LinearLayout.LayoutParams(689, 109));
        this.xezuairirx.setPadding(26, 122, 128, 155);
        linearLayout.addView(this.xezuairirx);
        this.xezuairirx.setBackgroundColor(Color.parseColor("#e12e20"));
        LinearLayout linearLayout3 = new LinearLayout(this);
        this.wancstoojb = linearLayout3;
        linearLayout3.setLayoutParams(new LinearLayout.LayoutParams(521, 1538));
        this.wancstoojb.setPadding(117, 63, 81, 110);
        linearLayout.addView(this.wancstoojb);
        this.wancstoojb.setBackgroundColor(Color.parseColor("#937f9e"));
        Switch r28 = new Switch(this);
        this.eglfoalkxz = r28;
        r28.setLayoutParams(new LinearLayout.LayoutParams(1, 765));
        this.eglfoalkxz.setPadding(165, 156, 72, BDLocation.TypeCoarseLocation);
        linearLayout.addView(this.eglfoalkxz);
        this.eglfoalkxz.setBackgroundColor(Color.parseColor("#697bad"));
        RelativeLayout relativeLayout5 = new RelativeLayout(this);
        this.ulglsjyymf = relativeLayout5;
        relativeLayout5.setLayoutParams(new LinearLayout.LayoutParams(363, 1960));
        this.ulglsjyymf.setPadding(70, 49, 144, 29);
        linearLayout.addView(this.ulglsjyymf);
        this.ulglsjyymf.setBackgroundColor(Color.parseColor("#467478"));
        TimePicker timePicker8 = new TimePicker(this);
        this.xowbrqshrk = timePicker8;
        timePicker8.setLayoutParams(new LinearLayout.LayoutParams(793, 1996));
        this.xowbrqshrk.setPadding(61, 52, 182, 139);
        linearLayout.addView(this.xowbrqshrk);
        this.xowbrqshrk.setBackgroundColor(Color.parseColor("#028c94"));
        GridView gridView6 = new GridView(this);
        this.rkenfszatm = gridView6;
        gridView6.setLayoutParams(new LinearLayout.LayoutParams(1358, 1931));
        this.rkenfszatm.setPadding(42, 197, 119, 170);
        linearLayout.addView(this.rkenfszatm);
        this.rkenfszatm.setBackgroundColor(Color.parseColor("#d3d8b8"));
        EditText editText5 = new EditText(this);
        this.kptwytzrdr = editText5;
        editText5.setLayoutParams(new LinearLayout.LayoutParams(554, 1283));
        this.kptwytzrdr.setPadding(121, 112, 34, 120);
        linearLayout.addView(this.kptwytzrdr);
        this.kptwytzrdr.setBackgroundColor(Color.parseColor("#c2eaca"));
        ListView listView4 = new ListView(this);
        this.lirrcnqdsu = listView4;
        listView4.setLayoutParams(new LinearLayout.LayoutParams(1449, TypedValues.Custom.TYPE_COLOR));
        this.lirrcnqdsu.setPadding(165, 163, 146, 42);
        linearLayout.addView(this.lirrcnqdsu);
        this.lirrcnqdsu.setBackgroundColor(Color.parseColor("#ed2059"));
        GridView gridView7 = new GridView(this);
        this.oqvucwbrcn = gridView7;
        gridView7.setLayoutParams(new LinearLayout.LayoutParams(1633, 990));
        this.oqvucwbrcn.setPadding(131, 182, 88, 94);
        linearLayout.addView(this.oqvucwbrcn);
        this.oqvucwbrcn.setBackgroundColor(Color.parseColor("#9268fc"));
        GridView gridView8 = new GridView(this);
        this.lptcovajck = gridView8;
        gridView8.setLayoutParams(new LinearLayout.LayoutParams(1727, 1205));
        this.lptcovajck.setPadding(72, 152, 187, 101);
        linearLayout.addView(this.lptcovajck);
        this.lptcovajck.setBackgroundColor(Color.parseColor("#8c21d5"));
        LinearLayout linearLayout4 = new LinearLayout(this);
        this.mpixkyqfiw = linearLayout4;
        linearLayout4.setLayoutParams(new LinearLayout.LayoutParams(1941, 218));
        this.mpixkyqfiw.setPadding(199, 194, 149, 22);
        linearLayout.addView(this.mpixkyqfiw);
        this.mpixkyqfiw.setBackgroundColor(Color.parseColor("#2f1ff8"));
        RelativeLayout relativeLayout6 = new RelativeLayout(this);
        this.sinpeompvu = relativeLayout6;
        relativeLayout6.setLayoutParams(new LinearLayout.LayoutParams(41, TypedValues.CycleType.TYPE_WAVE_PERIOD));
        this.sinpeompvu.setPadding(66, 123, 60, 85);
        linearLayout.addView(this.sinpeompvu);
        this.sinpeompvu.setBackgroundColor(Color.parseColor("#00f3ee"));
        ImageView imageView6 = new ImageView(this);
        this.zhcdmaymor = imageView6;
        imageView6.setLayoutParams(new LinearLayout.LayoutParams(1781, 1432));
        this.zhcdmaymor.setPadding(148, 10, 2, 73);
        linearLayout.addView(this.zhcdmaymor);
        this.zhcdmaymor.setBackgroundColor(Color.parseColor("#747183"));
        FrameLayout frameLayout4 = new FrameLayout(this);
        this.eigcbxdpuu = frameLayout4;
        frameLayout4.setLayoutParams(new LinearLayout.LayoutParams(1615, 974));
        this.eigcbxdpuu.setPadding(7, 91, 41, 181);
        linearLayout.addView(this.eigcbxdpuu);
        this.eigcbxdpuu.setBackgroundColor(Color.parseColor("#6e8a79"));
        Spinner spinner3 = new Spinner(this);
        this.rrcfdnfdtq = spinner3;
        spinner3.setLayoutParams(new LinearLayout.LayoutParams(1148, 648));
        this.rrcfdnfdtq.setPadding(56, 65, WebSocketProtocol.PAYLOAD_SHORT, 94);
        linearLayout.addView(this.rrcfdnfdtq);
        this.rrcfdnfdtq.setBackgroundColor(Color.parseColor("#4d3865"));
        RelativeLayout relativeLayout7 = new RelativeLayout(this);
        this.fqkwvzzolb = relativeLayout7;
        relativeLayout7.setLayoutParams(new LinearLayout.LayoutParams(1566, 378));
        this.fqkwvzzolb.setPadding(76, 139, 154, 67);
        linearLayout.addView(this.fqkwvzzolb);
        this.fqkwvzzolb.setBackgroundColor(Color.parseColor("#f733d5"));
        TableLayout tableLayout2 = new TableLayout(this);
        this.wapitsropi = tableLayout2;
        tableLayout2.setLayoutParams(new LinearLayout.LayoutParams(31, TypedValues.MotionType.TYPE_PATHMOTION_ARC));
        this.wapitsropi.setPadding(62, 90, 183, 106);
        linearLayout.addView(this.wapitsropi);
        this.wapitsropi.setBackgroundColor(Color.parseColor("#f9dad6"));
        DatePicker datePicker5 = new DatePicker(this);
        this.rrjhavqvqi = datePicker5;
        datePicker5.setLayoutParams(new LinearLayout.LayoutParams(1233, 1778));
        this.rrjhavqvqi.setPadding(BDLocation.TypeCoarseLocation, 95, 197, 54);
        linearLayout.addView(this.rrjhavqvqi);
        this.rrjhavqvqi.setBackgroundColor(Color.parseColor("#a2b28c"));
        ImageView imageView7 = new ImageView(this);
        this.snhzmoqkto = imageView7;
        imageView7.setLayoutParams(new LinearLayout.LayoutParams(1836, 851));
        this.snhzmoqkto.setPadding(34, 129, 121, 159);
        linearLayout.addView(this.snhzmoqkto);
        this.snhzmoqkto.setBackgroundColor(Color.parseColor("#85a099"));
        Switch r29 = new Switch(this);
        this.apypqjytvv = r29;
        r29.setLayoutParams(new LinearLayout.LayoutParams(460, 28));
        this.apypqjytvv.setPadding(75, 12, 78, 81);
        linearLayout.addView(this.apypqjytvv);
        this.apypqjytvv.setBackgroundColor(Color.parseColor("#3eee53"));
        Switch r210 = new Switch(this);
        this.xcdcztbkuc = r210;
        r210.setLayoutParams(new LinearLayout.LayoutParams(60, PointerIconCompat.TYPE_ZOOM_IN));
        this.xcdcztbkuc.setPadding(106, 15, 180, 175);
        linearLayout.addView(this.xcdcztbkuc);
        this.xcdcztbkuc.setBackgroundColor(Color.parseColor("#413f2d"));
        ImageView imageView8 = new ImageView(this);
        this.pntcqtbhnn = imageView8;
        imageView8.setLayoutParams(new LinearLayout.LayoutParams(1834, 688));
        this.pntcqtbhnn.setPadding(25, 164, 130, 16);
        linearLayout.addView(this.pntcqtbhnn);
        this.pntcqtbhnn.setBackgroundColor(Color.parseColor("#df2895"));
        DatePicker datePicker6 = new DatePicker(this);
        this.tnurdkgply = datePicker6;
        datePicker6.setLayoutParams(new LinearLayout.LayoutParams(193, 335));
        this.tnurdkgply.setPadding(174, 107, 145, 110);
        linearLayout.addView(this.tnurdkgply);
        this.tnurdkgply.setBackgroundColor(Color.parseColor("#1ffccb"));
        TableLayout tableLayout3 = new TableLayout(this);
        this.ebstdsgzih = tableLayout3;
        tableLayout3.setLayoutParams(new LinearLayout.LayoutParams(389, 1850));
        this.ebstdsgzih.setPadding(54, 185, 198, 55);
        linearLayout.addView(this.ebstdsgzih);
        this.ebstdsgzih.setBackgroundColor(Color.parseColor("#3d03fe"));
        GridView gridView9 = new GridView(this);
        this.ectdvgcwrz = gridView9;
        gridView9.setLayoutParams(new LinearLayout.LayoutParams(GattClient.STATE_PREPARE_CONNECTING, 749));
        this.ectdvgcwrz.setPadding(31, 146, 19, 51);
        linearLayout.addView(this.ectdvgcwrz);
        this.ectdvgcwrz.setBackgroundColor(Color.parseColor("#32322e"));
        ToggleButton toggleButton5 = new ToggleButton(this);
        this.oimnsswthw = toggleButton5;
        toggleButton5.setLayoutParams(new LinearLayout.LayoutParams(1261, 1765));
        this.oimnsswthw.setPadding(65, 182, 43, 166);
        linearLayout.addView(this.oimnsswthw);
        this.oimnsswthw.setBackgroundColor(Color.parseColor("#05ded4"));
        RadioButton radioButton5 = new RadioButton(this);
        this.psxlixqcwc = radioButton5;
        radioButton5.setLayoutParams(new LinearLayout.LayoutParams(1605, 435));
        this.psxlixqcwc.setPadding(2, 72, 152, 56);
        linearLayout.addView(this.psxlixqcwc);
        this.psxlixqcwc.setBackgroundColor(Color.parseColor("#3e9f8f"));
        FrameLayout frameLayout5 = new FrameLayout(this);
        this.ereqcgyifq = frameLayout5;
        frameLayout5.setLayoutParams(new LinearLayout.LayoutParams(1406, TypedValues.TransitionType.TYPE_INTERPOLATOR));
        this.ereqcgyifq.setPadding(44, 2, 52, 48);
        linearLayout.addView(this.ereqcgyifq);
        this.ereqcgyifq.setBackgroundColor(Color.parseColor("#9fedf4"));
        ImageView imageView9 = new ImageView(this);
        this.qleurcoilc = imageView9;
        imageView9.setLayoutParams(new LinearLayout.LayoutParams(1083, 1007));
        this.qleurcoilc.setPadding(69, 157, 176, 95);
        linearLayout.addView(this.qleurcoilc);
        this.qleurcoilc.setBackgroundColor(Color.parseColor("#64dc30"));
        ListView listView5 = new ListView(this);
        this.klwpiuncyv = listView5;
        listView5.setLayoutParams(new LinearLayout.LayoutParams(1309, 639));
        this.klwpiuncyv.setPadding(25, 101, 4, 31);
        linearLayout.addView(this.klwpiuncyv);
        this.klwpiuncyv.setBackgroundColor(Color.parseColor("#4fa37f"));
        EditText editText6 = new EditText(this);
        this.ywdrtqwcdh = editText6;
        editText6.setLayoutParams(new LinearLayout.LayoutParams(580, 1155));
        this.ywdrtqwcdh.setPadding(87, 10, 52, 172);
        linearLayout.addView(this.ywdrtqwcdh);
        this.ywdrtqwcdh.setBackgroundColor(Color.parseColor("#4858be"));
        ScrollView scrollView6 = new ScrollView(this);
        this.kblitnfxzt = scrollView6;
        scrollView6.setLayoutParams(new LinearLayout.LayoutParams(1178, 1424));
        this.kblitnfxzt.setPadding(142, 18, 99, 170);
        linearLayout.addView(this.kblitnfxzt);
        this.kblitnfxzt.setBackgroundColor(Color.parseColor("#d86068"));
        ToggleButton toggleButton6 = new ToggleButton(this);
        this.dumamxjcvp = toggleButton6;
        toggleButton6.setLayoutParams(new LinearLayout.LayoutParams(628, 68));
        this.dumamxjcvp.setPadding(114, 34, 191, 70);
        linearLayout.addView(this.dumamxjcvp);
        this.dumamxjcvp.setBackgroundColor(Color.parseColor("#57665c"));
        ListView listView6 = new ListView(this);
        this.hcovfdyctb = listView6;
        listView6.setLayoutParams(new LinearLayout.LayoutParams(1790, 666));
        this.hcovfdyctb.setPadding(24, 27, 80, 169);
        linearLayout.addView(this.hcovfdyctb);
        this.hcovfdyctb.setBackgroundColor(Color.parseColor("#9e0349"));
        GridView gridView10 = new GridView(this);
        this.wqbvyaxqmk = gridView10;
        gridView10.setLayoutParams(new LinearLayout.LayoutParams(1562, 1814));
        this.wqbvyaxqmk.setPadding(131, 138, 55, WebSocketProtocol.PAYLOAD_SHORT);
        linearLayout.addView(this.wqbvyaxqmk);
        this.wqbvyaxqmk.setBackgroundColor(Color.parseColor("#2d7df9"));
        DatePicker datePicker7 = new DatePicker(this);
        this.cszjarbwpz = datePicker7;
        datePicker7.setLayoutParams(new LinearLayout.LayoutParams(253, 1284));
        this.cszjarbwpz.setPadding(146, 80, 79, 84);
        linearLayout.addView(this.cszjarbwpz);
        this.cszjarbwpz.setBackgroundColor(Color.parseColor("#83db76"));
        TimePicker timePicker9 = new TimePicker(this);
        this.otbflaswpe = timePicker9;
        timePicker9.setLayoutParams(new LinearLayout.LayoutParams(574, 1858));
        this.otbflaswpe.setPadding(23, 145, 3, 182);
        linearLayout.addView(this.otbflaswpe);
        this.otbflaswpe.setBackgroundColor(Color.parseColor("#01bc67"));
        ImageView imageView10 = new ImageView(this);
        this.uhrgvglrnt = imageView10;
        imageView10.setLayoutParams(new LinearLayout.LayoutParams(1955, 470));
        this.uhrgvglrnt.setPadding(181, 73, 108, 192);
        linearLayout.addView(this.uhrgvglrnt);
        this.uhrgvglrnt.setBackgroundColor(Color.parseColor("#9a8dc9"));
        ImageView imageView11 = new ImageView(this);
        this.nwejpxfwqs = imageView11;
        imageView11.setLayoutParams(new LinearLayout.LayoutParams(178, 433));
        this.nwejpxfwqs.setPadding(70, 9, 156, 123);
        linearLayout.addView(this.nwejpxfwqs);
        this.nwejpxfwqs.setBackgroundColor(Color.parseColor("#81b394"));
        EditText editText7 = new EditText(this);
        this.mligksjbgn = editText7;
        editText7.setLayoutParams(new LinearLayout.LayoutParams(1177, 250));
        this.mligksjbgn.setPadding(16, 96, 172, 66);
        linearLayout.addView(this.mligksjbgn);
        this.mligksjbgn.setBackgroundColor(Color.parseColor("#bc19e3"));
        Switch r211 = new Switch(this);
        this.gjhnpmzmnp = r211;
        r211.setLayoutParams(new LinearLayout.LayoutParams(451, 1631));
        this.gjhnpmzmnp.setPadding(83, 13, 23, 37);
        linearLayout.addView(this.gjhnpmzmnp);
        this.gjhnpmzmnp.setBackgroundColor(Color.parseColor("#b254a0"));
        ViewFlipper viewFlipper6 = new ViewFlipper(this);
        this.oombucuqup = viewFlipper6;
        viewFlipper6.setLayoutParams(new LinearLayout.LayoutParams(1536, 14));
        this.oombucuqup.setPadding(104, 113, 138, 2);
        linearLayout.addView(this.oombucuqup);
        this.oombucuqup.setBackgroundColor(Color.parseColor("#d278a4"));
        Switch r212 = new Switch(this);
        this.cqcwggylmd = r212;
        r212.setLayoutParams(new LinearLayout.LayoutParams(1336, 1097));
        this.cqcwggylmd.setPadding(64, 66, 8, 147);
        linearLayout.addView(this.cqcwggylmd);
        this.cqcwggylmd.setBackgroundColor(Color.parseColor("#6a72ab"));
        CheckBox checkBox7 = new CheckBox(this);
        this.ytlbuortfn = checkBox7;
        checkBox7.setLayoutParams(new LinearLayout.LayoutParams(1348, 800));
        this.ytlbuortfn.setPadding(0, 147, 22, 57);
        linearLayout.addView(this.ytlbuortfn);
        this.ytlbuortfn.setBackgroundColor(Color.parseColor("#8ebe8e"));
        ViewFlipper viewFlipper7 = new ViewFlipper(this);
        this.ufphcxzbxb = viewFlipper7;
        viewFlipper7.setLayoutParams(new LinearLayout.LayoutParams(PDF417Common.MAX_CODEWORDS_IN_BARCODE, 1120));
        this.ufphcxzbxb.setPadding(149, 119, 79, 40);
        linearLayout.addView(this.ufphcxzbxb);
        this.ufphcxzbxb.setBackgroundColor(Color.parseColor("#2d7698"));
        ImageView imageView12 = new ImageView(this);
        this.obdsddksyq = imageView12;
        imageView12.setLayoutParams(new LinearLayout.LayoutParams(233, 624));
        this.obdsddksyq.setPadding(193, 133, 5, 4);
        linearLayout.addView(this.obdsddksyq);
        this.obdsddksyq.setBackgroundColor(Color.parseColor("#727916"));
        TableLayout tableLayout4 = new TableLayout(this);
        this.yifnqzddkc = tableLayout4;
        tableLayout4.setLayoutParams(new LinearLayout.LayoutParams(1415, TypedValues.CycleType.TYPE_EASING));
        this.yifnqzddkc.setPadding(169, 165, 174, 65);
        linearLayout.addView(this.yifnqzddkc);
        this.yifnqzddkc.setBackgroundColor(Color.parseColor("#bc51cf"));
        EditText editText8 = new EditText(this);
        this.atghczrndv = editText8;
        editText8.setLayoutParams(new LinearLayout.LayoutParams(GattClient.STATE_PREPARED, BDLocation.TypeServerDecryptError));
        this.atghczrndv.setPadding(81, 81, 15, 24);
        linearLayout.addView(this.atghczrndv);
        this.atghczrndv.setBackgroundColor(Color.parseColor("#4e383e"));
        ScrollView scrollView7 = new ScrollView(this);
        this.wgblkwmowx = scrollView7;
        scrollView7.setLayoutParams(new LinearLayout.LayoutParams(AudioEq.SW_EQ_DATA_LENGTH, TypedValues.Custom.TYPE_REFERENCE));
        this.wgblkwmowx.setPadding(5, 112, 127, 117);
        linearLayout.addView(this.wgblkwmowx);
        this.wgblkwmowx.setBackgroundColor(Color.parseColor("#de482a"));
        ProgressBar progressBar7 = new ProgressBar(this);
        this.gbvyhzheif = progressBar7;
        progressBar7.setLayoutParams(new LinearLayout.LayoutParams(192, 1675));
        this.gbvyhzheif.setPadding(62, 141, 18, 45);
        linearLayout.addView(this.gbvyhzheif);
        this.gbvyhzheif.setBackgroundColor(Color.parseColor("#481a96"));
        GridView gridView11 = new GridView(this);
        this.spcjjqnkry = gridView11;
        gridView11.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.Custom.TYPE_REFERENCE, GattClient.STATE_PENDDING_DISCOVERY_SERVICE));
        this.spcjjqnkry.setPadding(127, 157, 25, 124);
        linearLayout.addView(this.spcjjqnkry);
        this.spcjjqnkry.setBackgroundColor(Color.parseColor("#f37b6e"));
        ScrollView scrollView8 = new ScrollView(this);
        this.pejpgnxddh = scrollView8;
        scrollView8.setLayoutParams(new LinearLayout.LayoutParams(399, 1424));
        this.pejpgnxddh.setPadding(18, 174, 83, 180);
        linearLayout.addView(this.pejpgnxddh);
        this.pejpgnxddh.setBackgroundColor(Color.parseColor("#67e2e0"));
        ScrollView scrollView9 = new ScrollView(this);
        this.uyuwgsyknq = scrollView9;
        scrollView9.setLayoutParams(new LinearLayout.LayoutParams(1470, 1348));
        this.uyuwgsyknq.setPadding(139, 50, 42, 49);
        linearLayout.addView(this.uyuwgsyknq);
        this.uyuwgsyknq.setBackgroundColor(Color.parseColor("#d92e7a"));
        ViewFlipper viewFlipper8 = new ViewFlipper(this);
        this.aduufkyifd = viewFlipper8;
        viewFlipper8.setLayoutParams(new LinearLayout.LayoutParams(489, 363));
        this.aduufkyifd.setPadding(120, 115, 76, 1);
        linearLayout.addView(this.aduufkyifd);
        this.aduufkyifd.setBackgroundColor(Color.parseColor("#6ab491"));
        DatePicker datePicker8 = new DatePicker(this);
        this.fibutdkvyn = datePicker8;
        datePicker8.setLayoutParams(new LinearLayout.LayoutParams(1502, 1417));
        this.fibutdkvyn.setPadding(114, 10, 157, 33);
        linearLayout.addView(this.fibutdkvyn);
        this.fibutdkvyn.setBackgroundColor(Color.parseColor("#d5f461"));
        FrameLayout frameLayout6 = new FrameLayout(this);
        this.qsuybzkhfi = frameLayout6;
        frameLayout6.setLayoutParams(new LinearLayout.LayoutParams(1366, 630));
        this.qsuybzkhfi.setPadding(60, 57, 54, 131);
        linearLayout.addView(this.qsuybzkhfi);
        this.qsuybzkhfi.setBackgroundColor(Color.parseColor("#1f4074"));
        EditText editText9 = new EditText(this);
        this.pltxxbovct = editText9;
        editText9.setLayoutParams(new LinearLayout.LayoutParams(1926, 1410));
        this.pltxxbovct.setPadding(46, BDLocation.TypeServerError, 60, 10);
        linearLayout.addView(this.pltxxbovct);
        this.pltxxbovct.setBackgroundColor(Color.parseColor("#17e0d4"));
        TextView textView5 = new TextView(this);
        this.jbhsrpkmzq = textView5;
        textView5.setLayoutParams(new LinearLayout.LayoutParams(1992, 414));
        this.jbhsrpkmzq.setPadding(29, 98, 111, 111);
        linearLayout.addView(this.jbhsrpkmzq);
        this.jbhsrpkmzq.setBackgroundColor(Color.parseColor("#94dc13"));
        LinearLayout linearLayout5 = new LinearLayout(this);
        this.gximdqgziv = linearLayout5;
        linearLayout5.setLayoutParams(new LinearLayout.LayoutParams(1837, 622));
        this.gximdqgziv.setPadding(106, 87, 173, 46);
        linearLayout.addView(this.gximdqgziv);
        this.gximdqgziv.setBackgroundColor(Color.parseColor("#ab57c7"));
        TableLayout tableLayout5 = new TableLayout(this);
        this.xkrozrebed = tableLayout5;
        tableLayout5.setLayoutParams(new LinearLayout.LayoutParams(970, 626));
        this.xkrozrebed.setPadding(173, 140, 122, 169);
        linearLayout.addView(this.xkrozrebed);
        this.xkrozrebed.setBackgroundColor(Color.parseColor("#f26434"));
        FrameLayout frameLayout7 = new FrameLayout(this);
        this.mllxvpmlsb = frameLayout7;
        frameLayout7.setLayoutParams(new LinearLayout.LayoutParams(20, WebSocketImpl.DEFAULT_WSS_PORT));
        this.mllxvpmlsb.setPadding(197, 40, 95, 62);
        linearLayout.addView(this.mllxvpmlsb);
        this.mllxvpmlsb.setBackgroundColor(Color.parseColor("#aae61f"));
        ProgressBar progressBar8 = new ProgressBar(this);
        this.bmxsvgixut = progressBar8;
        progressBar8.setLayoutParams(new LinearLayout.LayoutParams(LocalPlaybackConstants.BUFFER_A_CAN_USE_FLAG, 1362));
        this.bmxsvgixut.setPadding(150, 169, 53, 163);
        linearLayout.addView(this.bmxsvgixut);
        this.bmxsvgixut.setBackgroundColor(Color.parseColor("#2fb2bc"));
        TimePicker timePicker10 = new TimePicker(this);
        this.rgzfebnxoa = timePicker10;
        timePicker10.setLayoutParams(new LinearLayout.LayoutParams(980, 1787));
        this.rgzfebnxoa.setPadding(7, 124, 93, 159);
        linearLayout.addView(this.rgzfebnxoa);
        this.rgzfebnxoa.setBackgroundColor(Color.parseColor("#482775"));
        DatePicker datePicker9 = new DatePicker(this);
        this.lsjhkwkrzc = datePicker9;
        datePicker9.setLayoutParams(new LinearLayout.LayoutParams(140, 1777));
        this.lsjhkwkrzc.setPadding(141, 186, 109, 196);
        linearLayout.addView(this.lsjhkwkrzc);
        this.lsjhkwkrzc.setBackgroundColor(Color.parseColor("#ae60e3"));
        LinearLayout linearLayout6 = new LinearLayout(this);
        this.lypnccbinb = linearLayout6;
        linearLayout6.setLayoutParams(new LinearLayout.LayoutParams(1154, 83));
        this.lypnccbinb.setPadding(128, 30, 104, 97);
        linearLayout.addView(this.lypnccbinb);
        this.lypnccbinb.setBackgroundColor(Color.parseColor("#7ba713"));
        ImageView imageView13 = new ImageView(this);
        this.cpnqqstjqa = imageView13;
        imageView13.setLayoutParams(new LinearLayout.LayoutParams(1030, 195));
        this.cpnqqstjqa.setPadding(129, 140, 115, 84);
        linearLayout.addView(this.cpnqqstjqa);
        this.cpnqqstjqa.setBackgroundColor(Color.parseColor("#edee7f"));
        ToggleButton toggleButton7 = new ToggleButton(this);
        this.omjcetijpv = toggleButton7;
        toggleButton7.setLayoutParams(new LinearLayout.LayoutParams(637, 615));
        this.omjcetijpv.setPadding(79, 35, 48, 187);
        linearLayout.addView(this.omjcetijpv);
        this.omjcetijpv.setBackgroundColor(Color.parseColor("#6961ec"));
        LinearLayout linearLayout7 = new LinearLayout(this);
        this.eduxatsptf = linearLayout7;
        linearLayout7.setLayoutParams(new LinearLayout.LayoutParams(305, 1184));
        this.eduxatsptf.setPadding(44, 52, 153, 19);
        linearLayout.addView(this.eduxatsptf);
        this.eduxatsptf.setBackgroundColor(Color.parseColor("#f8413e"));
        GridView gridView12 = new GridView(this);
        this.cfbbfuvkze = gridView12;
        gridView12.setLayoutParams(new LinearLayout.LayoutParams(1261, 432));
        this.cfbbfuvkze.setPadding(103, 147, 19, 185);
        linearLayout.addView(this.cfbbfuvkze);
        this.cfbbfuvkze.setBackgroundColor(Color.parseColor("#3358ba"));
        LinearLayout linearLayout8 = new LinearLayout(this);
        this.ittaewnhrv = linearLayout8;
        linearLayout8.setLayoutParams(new LinearLayout.LayoutParams(283, 17));
        this.ittaewnhrv.setPadding(183, 67, 155, 46);
        linearLayout.addView(this.ittaewnhrv);
        this.ittaewnhrv.setBackgroundColor(Color.parseColor("#9abe07"));
        ScrollView scrollView10 = new ScrollView(this);
        this.imchuflvje = scrollView10;
        scrollView10.setLayoutParams(new LinearLayout.LayoutParams(1604, 679));
        this.imchuflvje.setPadding(82, 62, 170, 119);
        linearLayout.addView(this.imchuflvje);
        this.imchuflvje.setBackgroundColor(Color.parseColor("#570091"));
        ScrollView scrollView11 = new ScrollView(this);
        this.ivbkxjglwb = scrollView11;
        scrollView11.setLayoutParams(new LinearLayout.LayoutParams(1148, 1886));
        this.ivbkxjglwb.setPadding(121, 178, 9, 146);
        linearLayout.addView(this.ivbkxjglwb);
        this.ivbkxjglwb.setBackgroundColor(Color.parseColor("#49dae9"));
        GridView gridView13 = new GridView(this);
        this.zellrmicic = gridView13;
        gridView13.setLayoutParams(new LinearLayout.LayoutParams(1824, 568));
        this.zellrmicic.setPadding(113, BDLocation.TypeCoarseLocation, 105, 148);
        linearLayout.addView(this.zellrmicic);
        this.zellrmicic.setBackgroundColor(Color.parseColor("#2581c9"));
        TableLayout tableLayout6 = new TableLayout(this);
        this.uctsdrxwfi = tableLayout6;
        tableLayout6.setLayoutParams(new LinearLayout.LayoutParams(469, 855));
        this.uctsdrxwfi.setPadding(191, 175, 19, 175);
        linearLayout.addView(this.uctsdrxwfi);
        this.uctsdrxwfi.setBackgroundColor(Color.parseColor("#18a499"));
        Spinner spinner4 = new Spinner(this);
        this.kmfqhxclrk = spinner4;
        spinner4.setLayoutParams(new LinearLayout.LayoutParams(1941, 1009));
        this.kmfqhxclrk.setPadding(88, 95, WebSocketProtocol.PAYLOAD_SHORT, 57);
        linearLayout.addView(this.kmfqhxclrk);
        this.kmfqhxclrk.setBackgroundColor(Color.parseColor("#d88662"));
        LinearLayout linearLayout9 = new LinearLayout(this);
        this.bpuvwrimib = linearLayout9;
        linearLayout9.setLayoutParams(new LinearLayout.LayoutParams(97, 1256));
        this.bpuvwrimib.setPadding(91, 23, 2, 174);
        linearLayout.addView(this.bpuvwrimib);
        this.bpuvwrimib.setBackgroundColor(Color.parseColor("#5db583"));
        RatingBar ratingBar4 = new RatingBar(this);
        this.axlpfgemsw = ratingBar4;
        ratingBar4.setLayoutParams(new LinearLayout.LayoutParams(1478, 1728));
        this.axlpfgemsw.setPadding(101, 120, 16, 39);
        linearLayout.addView(this.axlpfgemsw);
        this.axlpfgemsw.setBackgroundColor(Color.parseColor("#1c18ee"));
        EditText editText10 = new EditText(this);
        this.wejhblbwfo = editText10;
        editText10.setLayoutParams(new LinearLayout.LayoutParams(981, 1331));
        this.wejhblbwfo.setPadding(88, 187, 28, PictureConfig.CHOOSE_REQUEST);
        linearLayout.addView(this.wejhblbwfo);
        this.wejhblbwfo.setBackgroundColor(Color.parseColor("#0ce2b9"));
        TimePicker timePicker11 = new TimePicker(this);
        this.iehxojbbki = timePicker11;
        timePicker11.setLayoutParams(new LinearLayout.LayoutParams(1980, 345));
        this.iehxojbbki.setPadding(112, 46, 104, 157);
        linearLayout.addView(this.iehxojbbki);
        this.iehxojbbki.setBackgroundColor(Color.parseColor("#ea1afa"));
        LinearLayout linearLayout10 = new LinearLayout(this);
        this.jmcjqinleb = linearLayout10;
        linearLayout10.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.TransitionType.TYPE_STAGGERED, 267));
        this.jmcjqinleb.setPadding(35, 12, 110, 86);
        linearLayout.addView(this.jmcjqinleb);
        this.jmcjqinleb.setBackgroundColor(Color.parseColor("#d10a21"));
        RatingBar ratingBar5 = new RatingBar(this);
        this.ratkagoiva = ratingBar5;
        ratingBar5.setLayoutParams(new LinearLayout.LayoutParams(587, 1038));
        this.ratkagoiva.setPadding(83, 43, 122, 56);
        linearLayout.addView(this.ratkagoiva);
        this.ratkagoiva.setBackgroundColor(Color.parseColor("#571e14"));
        RelativeLayout relativeLayout8 = new RelativeLayout(this);
        this.jgxtalvknu = relativeLayout8;
        relativeLayout8.setLayoutParams(new LinearLayout.LayoutParams(449, 1572));
        this.jgxtalvknu.setPadding(19, 184, 186, PictureConfig.CHOOSE_REQUEST);
        linearLayout.addView(this.jgxtalvknu);
        this.jgxtalvknu.setBackgroundColor(Color.parseColor("#c412d3"));
        Button button5 = new Button(this);
        this.bnzvlppzuw = button5;
        button5.setLayoutParams(new LinearLayout.LayoutParams(1491, 1237));
        this.bnzvlppzuw.setPadding(90, 149, 75, 170);
        linearLayout.addView(this.bnzvlppzuw);
        this.bnzvlppzuw.setBackgroundColor(Color.parseColor("#7464c6"));
        Switch r213 = new Switch(this);
        this.njiqpxgsbu = r213;
        r213.setLayoutParams(new LinearLayout.LayoutParams(1524, 885));
        this.njiqpxgsbu.setPadding(55, 27, 18, 143);
        linearLayout.addView(this.njiqpxgsbu);
        this.njiqpxgsbu.setBackgroundColor(Color.parseColor("#e11758"));
        SeekBar seekBar10 = new SeekBar(this);
        this.aqojucwrck = seekBar10;
        seekBar10.setLayoutParams(new LinearLayout.LayoutParams(555, 775));
        this.aqojucwrck.setPadding(163, 163, 123, 133);
        linearLayout.addView(this.aqojucwrck);
        this.aqojucwrck.setBackgroundColor(Color.parseColor("#1b680f"));
        Button button6 = new Button(this);
        this.yyaqlvwczp = button6;
        button6.setLayoutParams(new LinearLayout.LayoutParams(90, 454));
        this.yyaqlvwczp.setPadding(165, 23, 105, 92);
        linearLayout.addView(this.yyaqlvwczp);
        this.yyaqlvwczp.setBackgroundColor(Color.parseColor("#53117f"));
        RatingBar ratingBar6 = new RatingBar(this);
        this.vvjxynokqj = ratingBar6;
        ratingBar6.setLayoutParams(new LinearLayout.LayoutParams(1462, 1164));
        this.vvjxynokqj.setPadding(157, 198, 107, 133);
        linearLayout.addView(this.vvjxynokqj);
        this.vvjxynokqj.setBackgroundColor(Color.parseColor("#a696c2"));
        RatingBar ratingBar7 = new RatingBar(this);
        this.mpwittzcsg = ratingBar7;
        ratingBar7.setLayoutParams(new LinearLayout.LayoutParams(90, 963));
        this.mpwittzcsg.setPadding(88, 101, 120, 63);
        linearLayout.addView(this.mpwittzcsg);
        this.mpwittzcsg.setBackgroundColor(Color.parseColor("#b773c4"));
        LinearLayout linearLayout11 = new LinearLayout(this);
        this.oeimtvgoeo = linearLayout11;
        linearLayout11.setLayoutParams(new LinearLayout.LayoutParams(1616, 1920));
        this.oeimtvgoeo.setPadding(187, 185, 39, 42);
        linearLayout.addView(this.oeimtvgoeo);
        this.oeimtvgoeo.setBackgroundColor(Color.parseColor("#a65c50"));
        TimePicker timePicker12 = new TimePicker(this);
        this.hcuhfarqeq = timePicker12;
        timePicker12.setLayoutParams(new LinearLayout.LayoutParams(22, 1543));
        this.hcuhfarqeq.setPadding(119, 18, 109, 136);
        linearLayout.addView(this.hcuhfarqeq);
        this.hcuhfarqeq.setBackgroundColor(Color.parseColor("#655c30"));
        DatePicker datePicker10 = new DatePicker(this);
        this.gknarnvjga = datePicker10;
        datePicker10.setLayoutParams(new LinearLayout.LayoutParams(688, 626));
        this.gknarnvjga.setPadding(137, 114, 180, 44);
        linearLayout.addView(this.gknarnvjga);
        this.gknarnvjga.setBackgroundColor(Color.parseColor("#fda4a1"));
        TextView textView6 = new TextView(this);
        this.xnykluwbyn = textView6;
        textView6.setLayoutParams(new LinearLayout.LayoutParams(56, 915));
        this.xnykluwbyn.setPadding(76, 195, 180, 138);
        linearLayout.addView(this.xnykluwbyn);
        this.xnykluwbyn.setBackgroundColor(Color.parseColor("#2cf891"));
        TimePicker timePicker13 = new TimePicker(this);
        this.chvlozpqma = timePicker13;
        timePicker13.setLayoutParams(new LinearLayout.LayoutParams(1063, 1872));
        this.chvlozpqma.setPadding(20, 31, 57, 29);
        linearLayout.addView(this.chvlozpqma);
        this.chvlozpqma.setBackgroundColor(Color.parseColor("#2bab3a"));
        RadioButton radioButton6 = new RadioButton(this);
        this.xwsdosxuyc = radioButton6;
        radioButton6.setLayoutParams(new LinearLayout.LayoutParams(1702, 1797));
        this.xwsdosxuyc.setPadding(145, 114, 49, 8);
        linearLayout.addView(this.xwsdosxuyc);
        this.xwsdosxuyc.setBackgroundColor(Color.parseColor("#3fbbec"));
        RelativeLayout relativeLayout9 = new RelativeLayout(this);
        this.bubvkpjzoi = relativeLayout9;
        relativeLayout9.setLayoutParams(new LinearLayout.LayoutParams(398, 268));
        this.bubvkpjzoi.setPadding(157, 170, 40, 171);
        linearLayout.addView(this.bubvkpjzoi);
        this.bubvkpjzoi.setBackgroundColor(Color.parseColor("#62846d"));
        Switch r214 = new Switch(this);
        this.yaznvaymtu = r214;
        r214.setLayoutParams(new LinearLayout.LayoutParams(145, 642));
        this.yaznvaymtu.setPadding(195, 64, 146, 55);
        linearLayout.addView(this.yaznvaymtu);
        this.yaznvaymtu.setBackgroundColor(Color.parseColor("#e9ba38"));
        EditText editText11 = new EditText(this);
        this.kbqvwawvhm = editText11;
        editText11.setLayoutParams(new LinearLayout.LayoutParams(635, 1947));
        this.kbqvwawvhm.setPadding(149, 183, PictureConfig.CHOOSE_REQUEST, 140);
        linearLayout.addView(this.kbqvwawvhm);
        this.kbqvwawvhm.setBackgroundColor(Color.parseColor("#000e46"));
        ProgressBar progressBar9 = new ProgressBar(this);
        this.dnnvfkybfd = progressBar9;
        progressBar9.setLayoutParams(new LinearLayout.LayoutParams(0, 1213));
        this.dnnvfkybfd.setPadding(1, 49, BDLocation.TypeCoarseLocation, 71);
        linearLayout.addView(this.dnnvfkybfd);
        this.dnnvfkybfd.setBackgroundColor(Color.parseColor("#337ddd"));
        Button button7 = new Button(this);
        this.sznfwpiyxc = button7;
        button7.setLayoutParams(new LinearLayout.LayoutParams(1179, 465));
        this.sznfwpiyxc.setPadding(129, 121, 171, 49);
        linearLayout.addView(this.sznfwpiyxc);
        this.sznfwpiyxc.setBackgroundColor(Color.parseColor("#fe6d62"));
        EditText editText12 = new EditText(this);
        this.qcmnluvdsz = editText12;
        editText12.setLayoutParams(new LinearLayout.LayoutParams(408, 1645));
        this.qcmnluvdsz.setPadding(197, 4, 69, 34);
        linearLayout.addView(this.qcmnluvdsz);
        this.qcmnluvdsz.setBackgroundColor(Color.parseColor("#695d91"));
        RadioButton radioButton7 = new RadioButton(this);
        this.hdijbxrvsz = radioButton7;
        radioButton7.setLayoutParams(new LinearLayout.LayoutParams(375, 39));
        this.hdijbxrvsz.setPadding(134, 1, 21, 45);
        linearLayout.addView(this.hdijbxrvsz);
        this.hdijbxrvsz.setBackgroundColor(Color.parseColor("#63de01"));
        ListView listView7 = new ListView(this);
        this.rcuksnjwdi = listView7;
        listView7.setLayoutParams(new LinearLayout.LayoutParams(838, TypedValues.PositionType.TYPE_CURVE_FIT));
        this.rcuksnjwdi.setPadding(56, 56, 110, 164);
        linearLayout.addView(this.rcuksnjwdi);
        this.rcuksnjwdi.setBackgroundColor(Color.parseColor("#1c8d3f"));
        ProgressBar progressBar10 = new ProgressBar(this);
        this.nakjnpylcp = progressBar10;
        progressBar10.setLayoutParams(new LinearLayout.LayoutParams(177, 1222));
        this.nakjnpylcp.setPadding(60, 40, 114, 99);
        linearLayout.addView(this.nakjnpylcp);
        this.nakjnpylcp.setBackgroundColor(Color.parseColor("#7bd928"));
        ScrollView scrollView12 = new ScrollView(this);
        this.bfjarhycoo = scrollView12;
        scrollView12.setLayoutParams(new LinearLayout.LayoutParams(81, 739));
        this.bfjarhycoo.setPadding(56, 17, 65, 66);
        linearLayout.addView(this.bfjarhycoo);
        this.bfjarhycoo.setBackgroundColor(Color.parseColor("#970ff3"));
        ProgressBar progressBar11 = new ProgressBar(this);
        this.lhfabwhmpb = progressBar11;
        progressBar11.setLayoutParams(new LinearLayout.LayoutParams(1415, 1034));
        this.lhfabwhmpb.setPadding(133, 88, 86, 148);
        linearLayout.addView(this.lhfabwhmpb);
        this.lhfabwhmpb.setBackgroundColor(Color.parseColor("#625d6b"));
        ScrollView scrollView13 = new ScrollView(this);
        this.itisblgouj = scrollView13;
        scrollView13.setLayoutParams(new LinearLayout.LayoutParams(1131, BluetoothClassImpl.Device.PERIPHERAL_POINTING));
        this.itisblgouj.setPadding(149, 41, 110, 20);
        linearLayout.addView(this.itisblgouj);
        this.itisblgouj.setBackgroundColor(Color.parseColor("#1a7429"));
        LinearLayout linearLayout12 = new LinearLayout(this);
        this.elkdutmixg = linearLayout12;
        linearLayout12.setLayoutParams(new LinearLayout.LayoutParams(910, 1905));
        this.elkdutmixg.setPadding(110, 0, 46, 143);
        linearLayout.addView(this.elkdutmixg);
        this.elkdutmixg.setBackgroundColor(Color.parseColor("#20bdcc"));
        FrameLayout frameLayout8 = new FrameLayout(this);
        this.jgxdsllxaw = frameLayout8;
        frameLayout8.setLayoutParams(new LinearLayout.LayoutParams(1968, 1649));
        this.jgxdsllxaw.setPadding(46, BDLocation.TypeCoarseLocation, 129, 108);
        linearLayout.addView(this.jgxdsllxaw);
        this.jgxdsllxaw.setBackgroundColor(Color.parseColor("#5fd57d"));
        GridView gridView14 = new GridView(this);
        this.itdzkrecfe = gridView14;
        gridView14.setLayoutParams(new LinearLayout.LayoutParams(790, 1001));
        this.itdzkrecfe.setPadding(3, 189, 3, 47);
        linearLayout.addView(this.itdzkrecfe);
        this.itdzkrecfe.setBackgroundColor(Color.parseColor("#bb7ea6"));
        ListView listView8 = new ListView(this);
        this.wlkmipbadg = listView8;
        listView8.setLayoutParams(new LinearLayout.LayoutParams(100, 231));
        this.wlkmipbadg.setPadding(143, 134, 148, 93);
        linearLayout.addView(this.wlkmipbadg);
        this.wlkmipbadg.setBackgroundColor(Color.parseColor("#a873f9"));
        SeekBar seekBar11 = new SeekBar(this);
        this.yulpibutfj = seekBar11;
        seekBar11.setLayoutParams(new LinearLayout.LayoutParams(1835, 1302));
        this.yulpibutfj.setPadding(46, 106, 181, 65);
        linearLayout.addView(this.yulpibutfj);
        this.yulpibutfj.setBackgroundColor(Color.parseColor("#f8b7ec"));
        Button button8 = new Button(this);
        this.lgtofqezge = button8;
        button8.setLayoutParams(new LinearLayout.LayoutParams(1832, 260));
        this.lgtofqezge.setPadding(12, 180, 144, 93);
        linearLayout.addView(this.lgtofqezge);
        this.lgtofqezge.setBackgroundColor(Color.parseColor("#d59a2b"));
        TimePicker timePicker14 = new TimePicker(this);
        this.aafdwhpolj = timePicker14;
        timePicker14.setLayoutParams(new LinearLayout.LayoutParams(97, 74));
        this.aafdwhpolj.setPadding(15, 26, 183, 4);
        linearLayout.addView(this.aafdwhpolj);
        this.aafdwhpolj.setBackgroundColor(Color.parseColor("#0c0b6c"));
        ViewFlipper viewFlipper9 = new ViewFlipper(this);
        this.tyhegfwhip = viewFlipper9;
        viewFlipper9.setLayoutParams(new LinearLayout.LayoutParams(132, 686));
        this.tyhegfwhip.setPadding(198, 79, 100, 180);
        linearLayout.addView(this.tyhegfwhip);
        this.tyhegfwhip.setBackgroundColor(Color.parseColor("#592f2c"));
        CheckBox checkBox8 = new CheckBox(this);
        this.iyvrmnulmv = checkBox8;
        checkBox8.setLayoutParams(new LinearLayout.LayoutParams(309, 1339));
        this.iyvrmnulmv.setPadding(20, 153, 168, 1);
        linearLayout.addView(this.iyvrmnulmv);
        this.iyvrmnulmv.setBackgroundColor(Color.parseColor("#d294d5"));
        TextView textView7 = new TextView(this);
        this.qkpmpabruq = textView7;
        textView7.setLayoutParams(new LinearLayout.LayoutParams(732, 1866));
        this.qkpmpabruq.setPadding(123, 149, 83, 67);
        linearLayout.addView(this.qkpmpabruq);
        this.qkpmpabruq.setBackgroundColor(Color.parseColor("#b0fa0d"));
        SeekBar seekBar12 = new SeekBar(this);
        this.hiqecfnoxt = seekBar12;
        seekBar12.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.TransitionType.TYPE_STAGGERED, 674));
        this.hiqecfnoxt.setPadding(97, 143, 175, 17);
        linearLayout.addView(this.hiqecfnoxt);
        this.hiqecfnoxt.setBackgroundColor(Color.parseColor("#e7c62a"));
        ListView listView9 = new ListView(this);
        this.vrchmnqinp = listView9;
        listView9.setLayoutParams(new LinearLayout.LayoutParams(926, 754));
        this.vrchmnqinp.setPadding(185, 127, 145, 47);
        linearLayout.addView(this.vrchmnqinp);
        this.vrchmnqinp.setBackgroundColor(Color.parseColor("#2932aa"));
        ScrollView scrollView14 = new ScrollView(this);
        this.wbjkveektp = scrollView14;
        scrollView14.setLayoutParams(new LinearLayout.LayoutParams(1896, 311));
        this.wbjkveektp.setPadding(143, 150, 133, 98);
        linearLayout.addView(this.wbjkveektp);
        this.wbjkveektp.setBackgroundColor(Color.parseColor("#d4dd37"));
        ViewFlipper viewFlipper10 = new ViewFlipper(this);
        this.llcvieafsc = viewFlipper10;
        viewFlipper10.setLayoutParams(new LinearLayout.LayoutParams(945, 944));
        this.llcvieafsc.setPadding(43, 14, 36, 4);
        linearLayout.addView(this.llcvieafsc);
        this.llcvieafsc.setBackgroundColor(Color.parseColor("#2839d4"));
        LinearLayout linearLayout13 = new LinearLayout(this);
        this.irehgxnjgs = linearLayout13;
        linearLayout13.setLayoutParams(new LinearLayout.LayoutParams(676, 1094));
        this.irehgxnjgs.setPadding(79, 63, 125, 146);
        linearLayout.addView(this.irehgxnjgs);
        this.irehgxnjgs.setBackgroundColor(Color.parseColor("#44be5f"));
        SeekBar seekBar13 = new SeekBar(this);
        this.jhkdwcppfh = seekBar13;
        seekBar13.setLayoutParams(new LinearLayout.LayoutParams(1046, 1169));
        this.jhkdwcppfh.setPadding(64, 14, 78, 66);
        linearLayout.addView(this.jhkdwcppfh);
        this.jhkdwcppfh.setBackgroundColor(Color.parseColor("#610bf6"));
        ScrollView scrollView15 = new ScrollView(this);
        this.dascrgwqmy = scrollView15;
        scrollView15.setLayoutParams(new LinearLayout.LayoutParams(1374, 1246));
        this.dascrgwqmy.setPadding(54, 185, 53, 90);
        linearLayout.addView(this.dascrgwqmy);
        this.dascrgwqmy.setBackgroundColor(Color.parseColor("#8f6a28"));
        SeekBar seekBar14 = new SeekBar(this);
        this.uxuyljxwth = seekBar14;
        seekBar14.setLayoutParams(new LinearLayout.LayoutParams(649, 916));
        this.uxuyljxwth.setPadding(49, 119, 64, 76);
        linearLayout.addView(this.uxuyljxwth);
        this.uxuyljxwth.setBackgroundColor(Color.parseColor("#6dd497"));
        FrameLayout frameLayout9 = new FrameLayout(this);
        this.xgrfvddmqk = frameLayout9;
        frameLayout9.setLayoutParams(new LinearLayout.LayoutParams(1444, 717));
        this.xgrfvddmqk.setPadding(154, 51, 149, 21);
        linearLayout.addView(this.xgrfvddmqk);
        this.xgrfvddmqk.setBackgroundColor(Color.parseColor("#c3b944"));
        ProgressBar progressBar12 = new ProgressBar(this);
        this.shrgadworm = progressBar12;
        progressBar12.setLayoutParams(new LinearLayout.LayoutParams(1951, 1113));
        this.shrgadworm.setPadding(98, 151, 63, 13);
        linearLayout.addView(this.shrgadworm);
        this.shrgadworm.setBackgroundColor(Color.parseColor("#000240"));
        TextView textView8 = new TextView(this);
        this.jpfdchbkhr = textView8;
        textView8.setLayoutParams(new LinearLayout.LayoutParams(1939, 389));
        this.jpfdchbkhr.setPadding(186, 109, 166, 112);
        linearLayout.addView(this.jpfdchbkhr);
        this.jpfdchbkhr.setBackgroundColor(Color.parseColor("#ffb4d6"));
        RatingBar ratingBar8 = new RatingBar(this);
        this.dlveebvdud = ratingBar8;
        ratingBar8.setLayoutParams(new LinearLayout.LayoutParams(1144, 147));
        this.dlveebvdud.setPadding(111, BDLocation.TypeNetWorkLocation, 33, 74);
        linearLayout.addView(this.dlveebvdud);
        this.dlveebvdud.setBackgroundColor(Color.parseColor("#0e08ed"));
        RadioButton radioButton8 = new RadioButton(this);
        this.eajbnrdtok = radioButton8;
        radioButton8.setLayoutParams(new LinearLayout.LayoutParams(1726, 1851));
        this.eajbnrdtok.setPadding(105, 140, 67, 176);
        linearLayout.addView(this.eajbnrdtok);
        this.eajbnrdtok.setBackgroundColor(Color.parseColor("#539418"));
        EditText editText13 = new EditText(this);
        this.hgpzchzoju = editText13;
        editText13.setLayoutParams(new LinearLayout.LayoutParams(109, 359));
        this.hgpzchzoju.setPadding(144, 114, 135, 75);
        linearLayout.addView(this.hgpzchzoju);
        this.hgpzchzoju.setBackgroundColor(Color.parseColor("#bf7dc0"));
        GridView gridView15 = new GridView(this);
        this.tnrroploiz = gridView15;
        gridView15.setLayoutParams(new LinearLayout.LayoutParams(867, 1940));
        this.tnrroploiz.setPadding(74, 68, 26, 184);
        linearLayout.addView(this.tnrroploiz);
        this.tnrroploiz.setBackgroundColor(Color.parseColor("#bb5fc8"));
        LinearLayout linearLayout14 = new LinearLayout(this);
        this.mvurdigrpv = linearLayout14;
        linearLayout14.setLayoutParams(new LinearLayout.LayoutParams(177, 155));
        this.mvurdigrpv.setPadding(148, 56, 83, 146);
        linearLayout.addView(this.mvurdigrpv);
        this.mvurdigrpv.setBackgroundColor(Color.parseColor("#ef23eb"));
        CheckBox checkBox9 = new CheckBox(this);
        this.pzrivxhnbb = checkBox9;
        checkBox9.setLayoutParams(new LinearLayout.LayoutParams(171, 775));
        this.pzrivxhnbb.setPadding(3, 20, 122, 193);
        linearLayout.addView(this.pzrivxhnbb);
        this.pzrivxhnbb.setBackgroundColor(Color.parseColor("#f764d9"));
        GridView gridView16 = new GridView(this);
        this.rbkpcpwhka = gridView16;
        gridView16.setLayoutParams(new LinearLayout.LayoutParams(675, 1768));
        this.rbkpcpwhka.setPadding(47, 58, 98, 131);
        linearLayout.addView(this.rbkpcpwhka);
        this.rbkpcpwhka.setBackgroundColor(Color.parseColor("#c932db"));
        TimePicker timePicker15 = new TimePicker(this);
        this.bsybtwfqzy = timePicker15;
        timePicker15.setLayoutParams(new LinearLayout.LayoutParams(1161, TypedValues.AttributesType.TYPE_PIVOT_TARGET));
        this.bsybtwfqzy.setPadding(13, 62, 20, 40);
        linearLayout.addView(this.bsybtwfqzy);
        this.bsybtwfqzy.setBackgroundColor(Color.parseColor("#a4521c"));
        RatingBar ratingBar9 = new RatingBar(this);
        this.ayagbifwwg = ratingBar9;
        ratingBar9.setLayoutParams(new LinearLayout.LayoutParams(1913, 569));
        this.ayagbifwwg.setPadding(190, 28, 146, 147);
        linearLayout.addView(this.ayagbifwwg);
        this.ayagbifwwg.setBackgroundColor(Color.parseColor("#cfff91"));
        RatingBar ratingBar10 = new RatingBar(this);
        this.gagdqlpddb = ratingBar10;
        ratingBar10.setLayoutParams(new LinearLayout.LayoutParams(168, 1029));
        this.gagdqlpddb.setPadding(185, 45, 61, 20);
        linearLayout.addView(this.gagdqlpddb);
        this.gagdqlpddb.setBackgroundColor(Color.parseColor("#a9067e"));
        TableLayout tableLayout7 = new TableLayout(this);
        this.sufaoabmsj = tableLayout7;
        tableLayout7.setLayoutParams(new LinearLayout.LayoutParams(1461, 1674));
        this.sufaoabmsj.setPadding(1, 96, 164, 58);
        linearLayout.addView(this.sufaoabmsj);
        this.sufaoabmsj.setBackgroundColor(Color.parseColor("#199ba8"));
        Switch r215 = new Switch(this);
        this.qycgxbpohi = r215;
        r215.setLayoutParams(new LinearLayout.LayoutParams(896, 889));
        this.qycgxbpohi.setPadding(130, 70, 57, 14);
        linearLayout.addView(this.qycgxbpohi);
        this.qycgxbpohi.setBackgroundColor(Color.parseColor("#9f5904"));
        ViewFlipper viewFlipper11 = new ViewFlipper(this);
        this.qzxjzxyotm = viewFlipper11;
        viewFlipper11.setLayoutParams(new LinearLayout.LayoutParams(18, 75));
        this.qzxjzxyotm.setPadding(199, 22, BDLocation.TypeServerDecryptError, 10);
        linearLayout.addView(this.qzxjzxyotm);
        this.qzxjzxyotm.setBackgroundColor(Color.parseColor("#f4454a"));
        ListView listView10 = new ListView(this);
        this.uzyqrlzrik = listView10;
        listView10.setLayoutParams(new LinearLayout.LayoutParams(721, 1355));
        this.uzyqrlzrik.setPadding(120, 159, 168, 183);
        linearLayout.addView(this.uzyqrlzrik);
        this.uzyqrlzrik.setBackgroundColor(Color.parseColor("#abef5e"));
        RatingBar ratingBar11 = new RatingBar(this);
        this.qvxxydxuyc = ratingBar11;
        ratingBar11.setLayoutParams(new LinearLayout.LayoutParams(838, 1291));
        this.qvxxydxuyc.setPadding(139, 133, 88, 46);
        linearLayout.addView(this.qvxxydxuyc);
        this.qvxxydxuyc.setBackgroundColor(Color.parseColor("#d4ed4f"));
        TableLayout tableLayout8 = new TableLayout(this);
        this.nsgyhdohpg = tableLayout8;
        tableLayout8.setLayoutParams(new LinearLayout.LayoutParams(565, 1275));
        this.nsgyhdohpg.setPadding(50, 100, 84, 102);
        linearLayout.addView(this.nsgyhdohpg);
        this.nsgyhdohpg.setBackgroundColor(Color.parseColor("#0293fd"));
        RelativeLayout relativeLayout10 = new RelativeLayout(this);
        this.toimzkclzm = relativeLayout10;
        relativeLayout10.setLayoutParams(new LinearLayout.LayoutParams(1264, 1214));
        this.toimzkclzm.setPadding(172, 96, 37, 108);
        linearLayout.addView(this.toimzkclzm);
        this.toimzkclzm.setBackgroundColor(Color.parseColor("#4c14f8"));
        TextView textView9 = new TextView(this);
        this.fjfvybqnkq = textView9;
        textView9.setLayoutParams(new LinearLayout.LayoutParams(289, 1166));
        this.fjfvybqnkq.setPadding(186, 45, 159, 97);
        linearLayout.addView(this.fjfvybqnkq);
        this.fjfvybqnkq.setBackgroundColor(Color.parseColor("#89da6f"));
        CheckBox checkBox10 = new CheckBox(this);
        this.pkurlpctlf = checkBox10;
        checkBox10.setLayoutParams(new LinearLayout.LayoutParams(1434, 728));
        this.pkurlpctlf.setPadding(31, 131, 57, 132);
        linearLayout.addView(this.pkurlpctlf);
        this.pkurlpctlf.setBackgroundColor(Color.parseColor("#5361d6"));
        Spinner spinner5 = new Spinner(this);
        this.icqecinqam = spinner5;
        spinner5.setLayoutParams(new LinearLayout.LayoutParams(1843, 10));
        this.icqecinqam.setPadding(116, 114, 96, 31);
        linearLayout.addView(this.icqecinqam);
        this.icqecinqam.setBackgroundColor(Color.parseColor("#f35dd8"));
        SeekBar seekBar15 = new SeekBar(this);
        this.uzjgotzfpd = seekBar15;
        seekBar15.setLayoutParams(new LinearLayout.LayoutParams(1831, 96));
        this.uzjgotzfpd.setPadding(118, 100, 199, 175);
        linearLayout.addView(this.uzjgotzfpd);
        this.uzjgotzfpd.setBackgroundColor(Color.parseColor("#609abe"));
        RatingBar ratingBar12 = new RatingBar(this);
        this.txqimipipu = ratingBar12;
        ratingBar12.setLayoutParams(new LinearLayout.LayoutParams(979, 933));
        this.txqimipipu.setPadding(133, 88, 157, 61);
        linearLayout.addView(this.txqimipipu);
        this.txqimipipu.setBackgroundColor(Color.parseColor("#4bdd71"));
        TextView textView10 = new TextView(this);
        this.uglgtfalhn = textView10;
        textView10.setLayoutParams(new LinearLayout.LayoutParams(1796, 238));
        this.uglgtfalhn.setPadding(115, 187, 51, 58);
        linearLayout.addView(this.uglgtfalhn);
        this.uglgtfalhn.setBackgroundColor(Color.parseColor("#f64b85"));
        GridView gridView17 = new GridView(this);
        this.nlyzvactfs = gridView17;
        gridView17.setLayoutParams(new LinearLayout.LayoutParams(356, 267));
        this.nlyzvactfs.setPadding(199, 50, 8, 191);
        linearLayout.addView(this.nlyzvactfs);
        this.nlyzvactfs.setBackgroundColor(Color.parseColor("#536a3e"));
        RelativeLayout relativeLayout11 = new RelativeLayout(this);
        this.vemfueidoa = relativeLayout11;
        relativeLayout11.setLayoutParams(new LinearLayout.LayoutParams(1066, 142));
        this.vemfueidoa.setPadding(124, 59, 19, 153);
        linearLayout.addView(this.vemfueidoa);
        this.vemfueidoa.setBackgroundColor(Color.parseColor("#cc90ae"));
        DatePicker datePicker11 = new DatePicker(this);
        this.odifazhnsn = datePicker11;
        datePicker11.setLayoutParams(new LinearLayout.LayoutParams(499, 1605));
        this.odifazhnsn.setPadding(82, 74, 109, 2);
        linearLayout.addView(this.odifazhnsn);
        this.odifazhnsn.setBackgroundColor(Color.parseColor("#dcd05b"));
        LinearLayout linearLayout15 = new LinearLayout(this);
        this.xvcxadbefn = linearLayout15;
        linearLayout15.setLayoutParams(new LinearLayout.LayoutParams(392, 332));
        this.xvcxadbefn.setPadding(BDLocation.TypeServerError, 175, 33, 133);
        linearLayout.addView(this.xvcxadbefn);
        this.xvcxadbefn.setBackgroundColor(Color.parseColor("#7fde64"));
        Spinner spinner6 = new Spinner(this);
        this.ontghubafv = spinner6;
        spinner6.setLayoutParams(new LinearLayout.LayoutParams(1718, 1346));
        this.ontghubafv.setPadding(BDLocation.TypeServerDecryptError, 45, 121, 185);
        linearLayout.addView(this.ontghubafv);
        this.ontghubafv.setBackgroundColor(Color.parseColor("#8ff7a2"));
        RelativeLayout relativeLayout12 = new RelativeLayout(this);
        this.cafncjtulp = relativeLayout12;
        relativeLayout12.setLayoutParams(new LinearLayout.LayoutParams(588, 390));
        this.cafncjtulp.setPadding(69, 190, 166, 94);
        linearLayout.addView(this.cafncjtulp);
        this.cafncjtulp.setBackgroundColor(Color.parseColor("#b57c1b"));
        Button button9 = new Button(this);
        this.ftjvamjbzb = button9;
        button9.setLayoutParams(new LinearLayout.LayoutParams(45, TypedValues.CycleType.TYPE_ALPHA));
        this.ftjvamjbzb.setPadding(86, 59, 180, 190);
        linearLayout.addView(this.ftjvamjbzb);
        this.ftjvamjbzb.setBackgroundColor(Color.parseColor("#3c34f0"));
        ListView listView11 = new ListView(this);
        this.rgrpaijwmi = listView11;
        listView11.setLayoutParams(new LinearLayout.LayoutParams(1258, 253));
        this.rgrpaijwmi.setPadding(194, 56, 39, 122);
        linearLayout.addView(this.rgrpaijwmi);
        this.rgrpaijwmi.setBackgroundColor(Color.parseColor("#4d7a73"));
        Spinner spinner7 = new Spinner(this);
        this.johvmfqand = spinner7;
        spinner7.setLayoutParams(new LinearLayout.LayoutParams(1330, 663));
        this.johvmfqand.setPadding(158, 165, 158, 93);
        linearLayout.addView(this.johvmfqand);
        this.johvmfqand.setBackgroundColor(Color.parseColor("#3a306f"));
        EditText editText14 = new EditText(this);
        this.oeevkokxhm = editText14;
        editText14.setLayoutParams(new LinearLayout.LayoutParams(1201, 693));
        this.oeevkokxhm.setPadding(82, 120, 131, 109);
        linearLayout.addView(this.oeevkokxhm);
        this.oeevkokxhm.setBackgroundColor(Color.parseColor("#bfe2f5"));
        ImageView imageView14 = new ImageView(this);
        this.hjsloydtar = imageView14;
        imageView14.setLayoutParams(new LinearLayout.LayoutParams(155, 1156));
        this.hjsloydtar.setPadding(83, 22, 28, 53);
        linearLayout.addView(this.hjsloydtar);
        this.hjsloydtar.setBackgroundColor(Color.parseColor("#3831ff"));
        RelativeLayout relativeLayout13 = new RelativeLayout(this);
        this.rtaifasiwb = relativeLayout13;
        relativeLayout13.setLayoutParams(new LinearLayout.LayoutParams(1132, 769));
        this.rtaifasiwb.setPadding(52, 185, BDLocation.TypeNetWorkLocation, 192);
        linearLayout.addView(this.rtaifasiwb);
        this.rtaifasiwb.setBackgroundColor(Color.parseColor("#874cd3"));
    }
}
