package com.smartapp.b.picagahowd;

import android.app.Activity;
import android.graphics.Color;
import android.os.Bundle;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.CheckBox;
import android.widget.DatePicker;
import android.widget.EditText;
import android.widget.FrameLayout;
import android.widget.GridView;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ListView;
import android.widget.ProgressBar;
import android.widget.RadioButton;
import android.widget.RatingBar;
import android.widget.RelativeLayout;
import android.widget.ScrollView;
import android.widget.SeekBar;
import android.widget.Spinner;
import android.widget.Switch;
import android.widget.TableLayout;
import android.widget.TextView;
import android.widget.TimePicker;
import android.widget.ToggleButton;
import android.widget.ViewFlipper;
import androidx.constraintlayout.core.motion.utils.TypedValues;
import androidx.core.view.PointerIconCompat;
import com.baidu.location.BDLocation;
import com.google.zxing.pdf417.PDF417Common;
import com.luck.picture.lib.config.PictureConfig;
import com.qcwireless.qcwatch.ui.base.imagepicker.cropper.CropImage;
import com.realsil.sdk.audioconnect.localplayback.LocalPlaybackConstants;
import com.realsil.sdk.core.bluetooth.connection.le.GattClient;
import okhttp3.internal.ws.WebSocketProtocol;

/* loaded from: classes4.dex */
public class VqncwpcqsyxActivity extends Activity {
    ToggleButton abefqjlacs;
    RadioButton agdzwjiiqa;
    SeekBar agfwvvxyoy;
    ScrollView aivqdfldlb;
    ProgressBar apfuoxokax;
    ListView atsadywtnm;
    DatePicker awckmunoka;
    ImageView axjlylwhtm;
    DatePicker aygwmvcvos;
    Button azwsvhiwwx;
    ImageView bdsmfcxfom;
    RelativeLayout bencmjntzf;
    RelativeLayout bibayqeudy;
    Button binzphditv;
    Spinner bnsajwfhmg;
    TextView bsgtxqejqu;
    ProgressBar btisymvssx;
    DatePicker btnhrbrgjz;
    Switch buxaydxdyu;
    RadioButton bvgwxjcsio;
    ProgressBar ccgatkwkzn;
    Switch cephufvuem;
    TimePicker cepwzpsrvk;
    TableLayout cfbyfiuaex;
    SeekBar cfpddnetwy;
    FrameLayout cjwtodaijy;
    ImageView ckhreksdkt;
    ImageView ckrfjebvvk;
    ImageView clylgykkqj;
    ImageView cqfyyhlsth;
    RatingBar csvrjmpeud;
    RelativeLayout ctnxxagebq;
    ViewFlipper cutyvoyueb;
    DatePicker cxsyjceufs;
    EditText datptvtdro;
    RelativeLayout dcvdcddqks;
    FrameLayout dcwpznhqnq;
    EditText ddakzdpysc;
    DatePicker dfpuihrgab;
    GridView dglxculgjq;
    RelativeLayout djhyibnvke;
    LinearLayout dponmyufso;
    ImageView dqpmmjertr;
    FrameLayout drfhdyueya;
    TimePicker drojyljtvt;
    RatingBar dsimnqhjbe;
    RadioButton dunlhvnlmh;
    DatePicker dwhhikohnn;
    Button eeabapqkhk;
    Spinner eemmdtguin;
    DatePicker eeujweoxth;
    ListView enimhcixlk;
    ViewFlipper eotxnheade;
    ToggleButton esklcalqkw;
    CheckBox ezqnxaidva;
    Button fbtzixkhjn;
    LinearLayout fdyxxwlhyi;
    TimePicker fmrbbiuauj;
    TimePicker fpbysbxfmb;
    ImageView fwdksdsuwq;
    Button gbfhqemtno;
    ImageView gdnijialhb;
    ViewFlipper ggpylvdcqr;
    TextView glsgpgkdkn;
    LinearLayout gptzusmrev;
    Button grxegscoyk;
    GridView gtzkgxyijo;
    Switch guamdxokgy;
    RelativeLayout gvwspgkhlz;
    CheckBox gypzdbfunt;
    ScrollView hhgzqmdkhi;
    ScrollView hkcgqlpwtl;
    LinearLayout hlkdtufzwm;
    RatingBar hmulndolko;
    Spinner hutvghrfhy;
    CheckBox hvpvqxtdyd;
    ProgressBar hxijpurcwy;
    ListView ibrmdgdyvf;
    RelativeLayout ifcqqmblom;
    RelativeLayout igubfvrtxo;
    RadioButton ihmkifkbes;
    RatingBar ihzkjkewzf;
    Button iiodkuczut;
    Spinner iiopjnobtb;
    ScrollView ijkqosqkhw;
    DatePicker ircffmetgf;
    Button iswmzzbnth;
    ToggleButton iucbzxyqft;
    EditText iukoqhydob;
    ImageView jdjzftnoaq;
    DatePicker jolgbzrjul;
    Button jptyleqwja;
    CheckBox jsadsvnlpa;
    ScrollView jtvuwebync;
    ScrollView jvgfubipjd;
    ListView jygmtrwpyt;
    ViewFlipper jzfyfymhbt;
    ImageView kbcfbtpzfd;
    Button kdxcoldixm;
    Switch kmolehhzah;
    GridView koyiypecdr;
    GridView kqylfzvhpu;
    Spinner ksjixkxmiv;
    CheckBox ktqqtakmxi;
    ListView kxfgvrwdsy;
    RatingBar kymxhzabft;
    LinearLayout kzktuxrdod;
    RatingBar ldmfsmnmam;
    RatingBar lfjgdrqmjh;
    Switch lggizvbktk;
    Button lirnzuonfl;
    LinearLayout lmcjojrabe;
    ListView lmetkvabng;
    LinearLayout lyaxclcihv;
    LinearLayout mawaqsnnrt;
    RatingBar mbcflzdmha;
    Switch mezscneajs;
    TimePicker mhzyelofbe;
    TableLayout mibrzvxael;
    DatePicker miiugmlhhr;
    ListView mlnmxktmih;
    TextView mnegqvfdai;
    RadioButton mtpjdpslzc;
    RadioButton mvexrtbzcf;
    LinearLayout mxdjemcefr;
    RatingBar nltwysvedk;
    RelativeLayout nmyxzvprjz;
    CheckBox nnwcgzwhbs;
    SeekBar nspdmwmyrm;
    TableLayout ntxxqloric;
    ProgressBar nyiuayilaz;
    ScrollView oanranzoqx;
    FrameLayout ocgungigsz;
    ProgressBar odlfokzrka;
    Button oehazubdao;
    RadioButton ofgdzkcyxx;
    TimePicker ojtzhczydr;
    ScrollView omgcgznzyu;
    SeekBar oqxxpvyxfd;
    TextView orcqpcklpw;
    EditText orilpeshzb;
    LinearLayout orzapxpcoj;
    Button osxvddbbgb;
    RadioButton ouutoqxiay;
    RatingBar oxwbkyinnb;
    TimePicker pabiohbsrj;
    TableLayout piqlirxgqw;
    RatingBar plavqjnsku;
    Switch pmibeyjzsl;
    ScrollView prbjgzjgce;
    ScrollView psxnzqvjwd;
    TableLayout ptcvnyrcgp;
    SeekBar qiscxrfomi;
    ListView qjxnadqtwx;
    RelativeLayout qnrdsbwivc;
    EditText qvsgjazdpy;
    ViewFlipper qymuqoxwid;
    ProgressBar qyrdcollnf;
    DatePicker rfnzyusboi;
    LinearLayout rgoojdvhdh;
    TextView rjqmcnyutm;
    TextView rlimxmscnx;
    FrameLayout rmpkrwirkg;
    RadioButton roxcupaqhf;
    ScrollView rxasqqiqlq;
    RadioButton saloqruzxq;
    Spinner scimhflimf;
    Spinner sdtrhvbdau;
    LinearLayout sgfjebakqw;
    ProgressBar srwwbxlogy;
    ImageView tcsmiznzzw;
    Switch tidyjfhjaf;
    ImageView titsiohcfn;
    ListView tjorajcbus;
    Spinner tmukjanvxt;
    CheckBox tralzwygzz;
    Button tsnvsjekjr;
    TextView tsoatnoasa;
    Button tzwqcgnbyz;
    TimePicker uffkkoctcl;
    DatePicker uhxvjdubyl;
    CheckBox utfrzzhopz;
    DatePicker uuvnymidtv;
    ProgressBar uuxqqyqukk;
    Spinner vamtwamxny;
    SeekBar vkdedykyca;
    LinearLayout vljtqopsyy;
    FrameLayout vnwvfwfwct;
    TableLayout voavbpyuth;
    RadioButton voexosjauw;
    RatingBar vvfbicxyug;
    CheckBox vxpbabhcab;
    RadioButton vxsjytmxws;
    LinearLayout vzcohqbjfd;
    ToggleButton wgoscurcwd;
    FrameLayout whprlbfcbr;
    Switch wluqsonfgk;
    ListView wmxvlaxygn;
    EditText worgtbfkwv;
    ToggleButton wouqojddtu;
    CheckBox wpmmvramtp;
    RadioButton wpsxsheoyr;
    CheckBox wrsxtbcsxn;
    RelativeLayout wwyxgagtio;
    FrameLayout wzwojgkhqo;
    CheckBox xcpgdpqkik;
    GridView xczorxykms;
    ImageView xdezzvyivq;
    SeekBar xecxegrnkd;
    Spinner xehruupjil;
    Button xesifqgmbv;
    FrameLayout ximqzgroib;
    ScrollView xjbfqyxwyz;
    SeekBar xozqwfugkf;
    SeekBar xtmfkbfdwq;
    RadioButton xubtpivcrw;
    RatingBar xzodtyvznx;
    DatePicker yaxynefejm;
    TableLayout ydlqetuikd;
    LinearLayout yenmdtolht;
    ProgressBar yisijadpwh;
    ToggleButton ykbwnutogp;
    EditText ykudeowibo;
    ViewFlipper ymzznnelbw;
    ScrollView ytfwkxendw;
    Spinner yvaxftbjra;
    EditText zaxkxvzjoe;
    RadioButton zaztexizio;
    EditText zbktziunsu;
    ImageView zietyokeey;
    RadioButton zlbecuafas;

    @Override // android.app.Activity
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        LinearLayout linearLayout = new LinearLayout(this);
        setContentView(linearLayout);
        linearLayout.setLayoutParams(new ViewGroup.LayoutParams(-1, -1));
        linearLayout.setOrientation(1);
        linearLayout.setBackgroundColor(Color.parseColor("#ae1146"));
        DatePicker datePicker = new DatePicker(this);
        this.rfnzyusboi = datePicker;
        datePicker.setLayoutParams(new LinearLayout.LayoutParams(630, 980));
        this.rfnzyusboi.setPadding(68, 40, 77, 82);
        linearLayout.addView(this.rfnzyusboi);
        this.rfnzyusboi.setBackgroundColor(Color.parseColor("#483104"));
        ImageView imageView = new ImageView(this);
        this.tcsmiznzzw = imageView;
        imageView.setLayoutParams(new LinearLayout.LayoutParams(1710, 645));
        this.tcsmiznzzw.setPadding(179, 67, 180, 53);
        linearLayout.addView(this.tcsmiznzzw);
        this.tcsmiznzzw.setBackgroundColor(Color.parseColor("#2c0331"));
        TextView textView = new TextView(this);
        this.glsgpgkdkn = textView;
        textView.setLayoutParams(new LinearLayout.LayoutParams(31, 1482));
        this.glsgpgkdkn.setPadding(149, 52, 181, 32);
        linearLayout.addView(this.glsgpgkdkn);
        this.glsgpgkdkn.setBackgroundColor(Color.parseColor("#b5ba75"));
        LinearLayout linearLayout2 = new LinearLayout(this);
        this.lmcjojrabe = linearLayout2;
        linearLayout2.setLayoutParams(new LinearLayout.LayoutParams(435, 398));
        this.lmcjojrabe.setPadding(194, 20, PictureConfig.CHOOSE_REQUEST, 65);
        linearLayout.addView(this.lmcjojrabe);
        this.lmcjojrabe.setBackgroundColor(Color.parseColor("#e79635"));
        ProgressBar progressBar = new ProgressBar(this);
        this.ccgatkwkzn = progressBar;
        progressBar.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.MotionType.TYPE_QUANTIZE_INTERPOLATOR_TYPE, 1096));
        this.ccgatkwkzn.setPadding(111, 89, 79, 148);
        linearLayout.addView(this.ccgatkwkzn);
        this.ccgatkwkzn.setBackgroundColor(Color.parseColor("#b2e4b2"));
        ViewFlipper viewFlipper = new ViewFlipper(this);
        this.cutyvoyueb = viewFlipper;
        viewFlipper.setLayoutParams(new LinearLayout.LayoutParams(305, 390));
        this.cutyvoyueb.setPadding(125, 96, 30, 15);
        linearLayout.addView(this.cutyvoyueb);
        this.cutyvoyueb.setBackgroundColor(Color.parseColor("#50a8c0"));
        DatePicker datePicker2 = new DatePicker(this);
        this.uhxvjdubyl = datePicker2;
        datePicker2.setLayoutParams(new LinearLayout.LayoutParams(875, 1855));
        this.uhxvjdubyl.setPadding(106, 105, 15, 47);
        linearLayout.addView(this.uhxvjdubyl);
        this.uhxvjdubyl.setBackgroundColor(Color.parseColor("#6da579"));
        TextView textView2 = new TextView(this);
        this.rjqmcnyutm = textView2;
        textView2.setLayoutParams(new LinearLayout.LayoutParams(1347, 731));
        this.rjqmcnyutm.setPadding(BDLocation.TypeServerError, 77, 23, 57);
        linearLayout.addView(this.rjqmcnyutm);
        this.rjqmcnyutm.setBackgroundColor(Color.parseColor("#3076c7"));
        DatePicker datePicker3 = new DatePicker(this);
        this.eeujweoxth = datePicker3;
        datePicker3.setLayoutParams(new LinearLayout.LayoutParams(243, 1287));
        this.eeujweoxth.setPadding(33, 158, 156, 151);
        linearLayout.addView(this.eeujweoxth);
        this.eeujweoxth.setBackgroundColor(Color.parseColor("#847406"));
        TableLayout tableLayout = new TableLayout(this);
        this.ntxxqloric = tableLayout;
        tableLayout.setLayoutParams(new LinearLayout.LayoutParams(1813, 738));
        this.ntxxqloric.setPadding(85, 100, 15, 110);
        linearLayout.addView(this.ntxxqloric);
        this.ntxxqloric.setBackgroundColor(Color.parseColor("#9159cb"));
        Button button = new Button(this);
        this.eeabapqkhk = button;
        button.setLayoutParams(new LinearLayout.LayoutParams(217, 1350));
        this.eeabapqkhk.setPadding(155, 79, 175, 146);
        linearLayout.addView(this.eeabapqkhk);
        this.eeabapqkhk.setBackgroundColor(Color.parseColor("#bd8d46"));
        ScrollView scrollView = new ScrollView(this);
        this.xjbfqyxwyz = scrollView;
        scrollView.setLayoutParams(new LinearLayout.LayoutParams(215, 141));
        this.xjbfqyxwyz.setPadding(140, 159, 48, 78);
        linearLayout.addView(this.xjbfqyxwyz);
        this.xjbfqyxwyz.setBackgroundColor(Color.parseColor("#e70c11"));
        RadioButton radioButton = new RadioButton(this);
        this.bvgwxjcsio = radioButton;
        radioButton.setLayoutParams(new LinearLayout.LayoutParams(1339, 1369));
        this.bvgwxjcsio.setPadding(190, 44, 42, 19);
        linearLayout.addView(this.bvgwxjcsio);
        this.bvgwxjcsio.setBackgroundColor(Color.parseColor("#e3944d"));
        RadioButton radioButton2 = new RadioButton(this);
        this.voexosjauw = radioButton2;
        radioButton2.setLayoutParams(new LinearLayout.LayoutParams(136, 39));
        this.voexosjauw.setPadding(28, 130, 133, 50);
        linearLayout.addView(this.voexosjauw);
        this.voexosjauw.setBackground(new Lmpikjigpey());
        RelativeLayout relativeLayout = new RelativeLayout(this);
        this.gvwspgkhlz = relativeLayout;
        relativeLayout.setLayoutParams(new LinearLayout.LayoutParams(1290, 869));
        this.gvwspgkhlz.setPadding(BDLocation.TypeCoarseLocation, 109, 60, 182);
        linearLayout.addView(this.gvwspgkhlz);
        this.gvwspgkhlz.setBackgroundColor(Color.parseColor("#bee0b3"));
        FrameLayout frameLayout = new FrameLayout(this);
        this.rmpkrwirkg = frameLayout;
        frameLayout.setLayoutParams(new LinearLayout.LayoutParams(840, 799));
        this.rmpkrwirkg.setPadding(84, 7, 19, 168);
        linearLayout.addView(this.rmpkrwirkg);
        this.rmpkrwirkg.setBackgroundColor(Color.parseColor("#476827"));
        TableLayout tableLayout2 = new TableLayout(this);
        this.cfbyfiuaex = tableLayout2;
        tableLayout2.setLayoutParams(new LinearLayout.LayoutParams(1811, TypedValues.AttributesType.TYPE_EASING));
        this.cfbyfiuaex.setPadding(155, 62, 116, 143);
        linearLayout.addView(this.cfbyfiuaex);
        this.cfbyfiuaex.setBackgroundColor(Color.parseColor("#d2c6c7"));
        ProgressBar progressBar2 = new ProgressBar(this);
        this.uuxqqyqukk = progressBar2;
        progressBar2.setLayoutParams(new LinearLayout.LayoutParams(169, 1549));
        this.uuxqqyqukk.setPadding(193, 52, 63, 46);
        linearLayout.addView(this.uuxqqyqukk);
        this.uuxqqyqukk.setBackgroundColor(Color.parseColor("#e208a1"));
        LinearLayout linearLayout3 = new LinearLayout(this);
        this.hlkdtufzwm = linearLayout3;
        linearLayout3.setLayoutParams(new LinearLayout.LayoutParams(1886, 1974));
        this.hlkdtufzwm.setPadding(171, 119, 52, 182);
        linearLayout.addView(this.hlkdtufzwm);
        this.hlkdtufzwm.setBackgroundColor(Color.parseColor("#1934d8"));
        ImageView imageView2 = new ImageView(this);
        this.gdnijialhb = imageView2;
        imageView2.setLayoutParams(new LinearLayout.LayoutParams(1444, TypedValues.PositionType.TYPE_PERCENT_Y));
        this.gdnijialhb.setPadding(104, 88, 49, 104);
        linearLayout.addView(this.gdnijialhb);
        this.gdnijialhb.setBackgroundColor(Color.parseColor("#34991e"));
        LinearLayout linearLayout4 = new LinearLayout(this);
        this.gptzusmrev = linearLayout4;
        linearLayout4.setLayoutParams(new LinearLayout.LayoutParams(428, 1859));
        this.gptzusmrev.setPadding(108, 8, 32, 107);
        linearLayout.addView(this.gptzusmrev);
        this.gptzusmrev.setBackgroundColor(Color.parseColor("#aa776f"));
        RelativeLayout relativeLayout2 = new RelativeLayout(this);
        this.nmyxzvprjz = relativeLayout2;
        relativeLayout2.setLayoutParams(new LinearLayout.LayoutParams(466, 1853));
        this.nmyxzvprjz.setPadding(132, 55, 54, 131);
        linearLayout.addView(this.nmyxzvprjz);
        this.nmyxzvprjz.setBackgroundColor(Color.parseColor("#17160c"));
        RadioButton radioButton3 = new RadioButton(this);
        this.ouutoqxiay = radioButton3;
        radioButton3.setLayoutParams(new LinearLayout.LayoutParams(1616, 1661));
        this.ouutoqxiay.setPadding(38, 26, 119, 137);
        linearLayout.addView(this.ouutoqxiay);
        this.ouutoqxiay.setBackgroundColor(Color.parseColor("#c3257d"));
        LinearLayout linearLayout5 = new LinearLayout(this);
        this.lyaxclcihv = linearLayout5;
        linearLayout5.setLayoutParams(new LinearLayout.LayoutParams(658, 726));
        this.lyaxclcihv.setPadding(39, 32, 101, 101);
        linearLayout.addView(this.lyaxclcihv);
        this.lyaxclcihv.setBackgroundColor(Color.parseColor("#10f13a"));
        LinearLayout linearLayout6 = new LinearLayout(this);
        this.orzapxpcoj = linearLayout6;
        linearLayout6.setLayoutParams(new LinearLayout.LayoutParams(191, 619));
        this.orzapxpcoj.setPadding(144, 80, 199, 21);
        linearLayout.addView(this.orzapxpcoj);
        this.orzapxpcoj.setBackgroundColor(Color.parseColor("#57a404"));
        ScrollView scrollView2 = new ScrollView(this);
        this.omgcgznzyu = scrollView2;
        scrollView2.setLayoutParams(new LinearLayout.LayoutParams(975, 1871));
        this.omgcgznzyu.setPadding(90, 169, 95, 81);
        linearLayout.addView(this.omgcgznzyu);
        this.omgcgznzyu.setBackgroundColor(Color.parseColor("#a72e9d"));
        ListView listView = new ListView(this);
        this.wmxvlaxygn = listView;
        listView.setLayoutParams(new LinearLayout.LayoutParams(496, 1565));
        this.wmxvlaxygn.setPadding(22, 182, 61, 117);
        linearLayout.addView(this.wmxvlaxygn);
        this.wmxvlaxygn.setBackgroundColor(Color.parseColor("#b932d0"));
        Spinner spinner = new Spinner(this);
        this.scimhflimf = spinner;
        spinner.setLayoutParams(new LinearLayout.LayoutParams(556, 652));
        this.scimhflimf.setPadding(121, 109, 0, BDLocation.TypeNetWorkLocation);
        linearLayout.addView(this.scimhflimf);
        this.scimhflimf.setBackgroundColor(Color.parseColor("#3f0c33"));
        GridView gridView = new GridView(this);
        this.xczorxykms = gridView;
        gridView.setLayoutParams(new LinearLayout.LayoutParams(1229, 635));
        this.xczorxykms.setPadding(51, 149, 27, 169);
        linearLayout.addView(this.xczorxykms);
        this.xczorxykms.setBackgroundColor(Color.parseColor("#23e081"));
        EditText editText = new EditText(this);
        this.iukoqhydob = editText;
        editText.setLayoutParams(new LinearLayout.LayoutParams(1801, 1149));
        this.iukoqhydob.setPadding(33, 121, 69, 52);
        linearLayout.addView(this.iukoqhydob);
        this.iukoqhydob.setBackgroundColor(Color.parseColor("#330173"));
        ToggleButton toggleButton = new ToggleButton(this);
        this.abefqjlacs = toggleButton;
        toggleButton.setLayoutParams(new LinearLayout.LayoutParams(1633, 265));
        this.abefqjlacs.setPadding(112, 75, 73, 179);
        linearLayout.addView(this.abefqjlacs);
        this.abefqjlacs.setBackgroundColor(Color.parseColor("#2e752e"));
        TimePicker timePicker = new TimePicker(this);
        this.pabiohbsrj = timePicker;
        timePicker.setLayoutParams(new LinearLayout.LayoutParams(1212, 1849));
        this.pabiohbsrj.setPadding(10, 65, 100, 153);
        linearLayout.addView(this.pabiohbsrj);
        this.pabiohbsrj.setBackgroundColor(Color.parseColor("#0410f2"));
        CheckBox checkBox = new CheckBox(this);
        this.wrsxtbcsxn = checkBox;
        checkBox.setLayoutParams(new LinearLayout.LayoutParams(121, 1428));
        this.wrsxtbcsxn.setPadding(68, 45, 54, 81);
        linearLayout.addView(this.wrsxtbcsxn);
        this.wrsxtbcsxn.setBackgroundColor(Color.parseColor("#727d67"));
        ImageView imageView3 = new ImageView(this);
        this.fwdksdsuwq = imageView3;
        imageView3.setLayoutParams(new LinearLayout.LayoutParams(74, 1683));
        this.fwdksdsuwq.setPadding(5, 181, 48, 136);
        linearLayout.addView(this.fwdksdsuwq);
        this.fwdksdsuwq.setBackgroundColor(Color.parseColor("#e16608"));
        RatingBar ratingBar = new RatingBar(this);
        this.plavqjnsku = ratingBar;
        ratingBar.setLayoutParams(new LinearLayout.LayoutParams(1140, 405));
        this.plavqjnsku.setPadding(195, 16, 12, 88);
        linearLayout.addView(this.plavqjnsku);
        this.plavqjnsku.setBackgroundColor(Color.parseColor("#3b622f"));
        EditText editText2 = new EditText(this);
        this.datptvtdro = editText2;
        editText2.setLayoutParams(new LinearLayout.LayoutParams(1851, 1239));
        this.datptvtdro.setPadding(7, 129, 75, 23);
        linearLayout.addView(this.datptvtdro);
        this.datptvtdro.setBackgroundColor(Color.parseColor("#34c61a"));
        Switch r2 = new Switch(this);
        this.buxaydxdyu = r2;
        r2.setLayoutParams(new LinearLayout.LayoutParams(228, 1052));
        this.buxaydxdyu.setPadding(152, 18, 64, 114);
        linearLayout.addView(this.buxaydxdyu);
        this.buxaydxdyu.setBackgroundColor(Color.parseColor("#f3434a"));
        CheckBox checkBox2 = new CheckBox(this);
        this.vxpbabhcab = checkBox2;
        checkBox2.setLayoutParams(new LinearLayout.LayoutParams(1418, 460));
        this.vxpbabhcab.setPadding(149, 111, 42, 121);
        linearLayout.addView(this.vxpbabhcab);
        this.vxpbabhcab.setBackgroundColor(Color.parseColor("#9791f5"));
        ToggleButton toggleButton2 = new ToggleButton(this);
        this.wgoscurcwd = toggleButton2;
        toggleButton2.setLayoutParams(new LinearLayout.LayoutParams(667, 213));
        this.wgoscurcwd.setPadding(19, 173, 104, 136);
        linearLayout.addView(this.wgoscurcwd);
        this.wgoscurcwd.setBackgroundColor(Color.parseColor("#a380a3"));
        Switch r22 = new Switch(this);
        this.guamdxokgy = r22;
        r22.setLayoutParams(new LinearLayout.LayoutParams(164, 211));
        this.guamdxokgy.setPadding(46, 181, 125, 38);
        linearLayout.addView(this.guamdxokgy);
        this.guamdxokgy.setBackgroundColor(Color.parseColor("#d150ca"));
        ImageView imageView4 = new ImageView(this);
        this.bdsmfcxfom = imageView4;
        imageView4.setLayoutParams(new LinearLayout.LayoutParams(78, 645));
        this.bdsmfcxfom.setPadding(93, 114, 91, 62);
        linearLayout.addView(this.bdsmfcxfom);
        this.bdsmfcxfom.setBackgroundColor(Color.parseColor("#6c3fd8"));
        ImageView imageView5 = new ImageView(this);
        this.jdjzftnoaq = imageView5;
        imageView5.setLayoutParams(new LinearLayout.LayoutParams(565, TypedValues.Custom.TYPE_FLOAT));
        this.jdjzftnoaq.setPadding(109, 52, 149, 105);
        linearLayout.addView(this.jdjzftnoaq);
        this.jdjzftnoaq.setBackgroundColor(Color.parseColor("#8ee20e"));
        ImageView imageView6 = new ImageView(this);
        this.titsiohcfn = imageView6;
        imageView6.setLayoutParams(new LinearLayout.LayoutParams(1862, 827));
        this.titsiohcfn.setPadding(7, 168, 77, 77);
        linearLayout.addView(this.titsiohcfn);
        this.titsiohcfn.setBackgroundColor(Color.parseColor("#4d681e"));
        RatingBar ratingBar2 = new RatingBar(this);
        this.mbcflzdmha = ratingBar2;
        ratingBar2.setLayoutParams(new LinearLayout.LayoutParams(1470, 1864));
        this.mbcflzdmha.setPadding(133, 46, 13, 28);
        linearLayout.addView(this.mbcflzdmha);
        this.mbcflzdmha.setBackgroundColor(Color.parseColor("#aaa547"));
        ListView listView2 = new ListView(this);
        this.jygmtrwpyt = listView2;
        listView2.setLayoutParams(new LinearLayout.LayoutParams(1051, 1890));
        this.jygmtrwpyt.setPadding(71, 77, 178, 59);
        linearLayout.addView(this.jygmtrwpyt);
        this.jygmtrwpyt.setBackgroundColor(Color.parseColor("#7ea610"));
        RadioButton radioButton4 = new RadioButton(this);
        this.ihmkifkbes = radioButton4;
        radioButton4.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.MotionType.TYPE_QUANTIZE_MOTIONSTEPS, 25));
        this.ihmkifkbes.setPadding(60, 166, 154, 164);
        linearLayout.addView(this.ihmkifkbes);
        this.ihmkifkbes.setBackgroundColor(Color.parseColor("#b1210b"));
        DatePicker datePicker4 = new DatePicker(this);
        this.miiugmlhhr = datePicker4;
        datePicker4.setLayoutParams(new LinearLayout.LayoutParams(1464, PointerIconCompat.TYPE_GRABBING));
        this.miiugmlhhr.setPadding(196, 163, 31, 75);
        linearLayout.addView(this.miiugmlhhr);
        this.miiugmlhhr.setBackgroundColor(Color.parseColor("#27cd1a"));
        LinearLayout linearLayout7 = new LinearLayout(this);
        this.fdyxxwlhyi = linearLayout7;
        linearLayout7.setLayoutParams(new LinearLayout.LayoutParams(1764, 1697));
        this.fdyxxwlhyi.setPadding(169, 18, 196, 146);
        linearLayout.addView(this.fdyxxwlhyi);
        this.fdyxxwlhyi.setBackgroundColor(Color.parseColor("#c734d2"));
        ToggleButton toggleButton3 = new ToggleButton(this);
        this.ykbwnutogp = toggleButton3;
        toggleButton3.setLayoutParams(new LinearLayout.LayoutParams(1450, 840));
        this.ykbwnutogp.setPadding(21, 75, 148, 130);
        linearLayout.addView(this.ykbwnutogp);
        this.ykbwnutogp.setBackgroundColor(Color.parseColor("#d0e5e3"));
        Button button2 = new Button(this);
        this.oehazubdao = button2;
        button2.setLayoutParams(new LinearLayout.LayoutParams(1564, 307));
        this.oehazubdao.setPadding(71, 138, 99, 199);
        linearLayout.addView(this.oehazubdao);
        this.oehazubdao.setBackgroundColor(Color.parseColor("#a25254"));
        ListView listView3 = new ListView(this);
        this.kxfgvrwdsy = listView3;
        listView3.setLayoutParams(new LinearLayout.LayoutParams(866, 1596));
        this.kxfgvrwdsy.setPadding(143, 19, 69, 182);
        linearLayout.addView(this.kxfgvrwdsy);
        this.kxfgvrwdsy.setBackgroundColor(Color.parseColor("#2ff608"));
        Switch r23 = new Switch(this);
        this.pmibeyjzsl = r23;
        r23.setLayoutParams(new LinearLayout.LayoutParams(368, 1962));
        this.pmibeyjzsl.setPadding(56, BDLocation.TypeNetWorkLocation, 156, 165);
        linearLayout.addView(this.pmibeyjzsl);
        this.pmibeyjzsl.setBackgroundColor(Color.parseColor("#d8f4ea"));
        LinearLayout linearLayout8 = new LinearLayout(this);
        this.yenmdtolht = linearLayout8;
        linearLayout8.setLayoutParams(new LinearLayout.LayoutParams(287, 1546));
        this.yenmdtolht.setPadding(196, 106, 69, 47);
        linearLayout.addView(this.yenmdtolht);
        this.yenmdtolht.setBackgroundColor(Color.parseColor("#888fda"));
        ScrollView scrollView3 = new ScrollView(this);
        this.jtvuwebync = scrollView3;
        scrollView3.setLayoutParams(new LinearLayout.LayoutParams(1516, 622));
        this.jtvuwebync.setPadding(43, 138, 170, 107);
        linearLayout.addView(this.jtvuwebync);
        this.jtvuwebync.setBackgroundColor(Color.parseColor("#d12e3f"));
        DatePicker datePicker5 = new DatePicker(this);
        this.aygwmvcvos = datePicker5;
        datePicker5.setLayoutParams(new LinearLayout.LayoutParams(1269, 77));
        this.aygwmvcvos.setPadding(181, 129, 170, 105);
        linearLayout.addView(this.aygwmvcvos);
        this.aygwmvcvos.setBackgroundColor(Color.parseColor("#2f9e85"));
        LinearLayout linearLayout9 = new LinearLayout(this);
        this.mxdjemcefr = linearLayout9;
        linearLayout9.setLayoutParams(new LinearLayout.LayoutParams(283, 783));
        this.mxdjemcefr.setPadding(183, 123, 37, 8);
        linearLayout.addView(this.mxdjemcefr);
        this.mxdjemcefr.setBackgroundColor(Color.parseColor("#4c4fb0"));
        RatingBar ratingBar3 = new RatingBar(this);
        this.ldmfsmnmam = ratingBar3;
        ratingBar3.setLayoutParams(new LinearLayout.LayoutParams(1657, 1259));
        this.ldmfsmnmam.setPadding(58, 3, 133, 150);
        linearLayout.addView(this.ldmfsmnmam);
        this.ldmfsmnmam.setBackgroundColor(Color.parseColor("#104540"));
        RatingBar ratingBar4 = new RatingBar(this);
        this.vvfbicxyug = ratingBar4;
        ratingBar4.setLayoutParams(new LinearLayout.LayoutParams(1243, 471));
        this.vvfbicxyug.setPadding(14, 83, 62, 30);
        linearLayout.addView(this.vvfbicxyug);
        this.vvfbicxyug.setBackgroundColor(Color.parseColor("#3a886e"));
        TableLayout tableLayout3 = new TableLayout(this);
        this.voavbpyuth = tableLayout3;
        tableLayout3.setLayoutParams(new LinearLayout.LayoutParams(1267, 3));
        this.voavbpyuth.setPadding(133, 52, 87, 127);
        linearLayout.addView(this.voavbpyuth);
        this.voavbpyuth.setBackgroundColor(Color.parseColor("#be6a07"));
        ImageView imageView7 = new ImageView(this);
        this.kbcfbtpzfd = imageView7;
        imageView7.setLayoutParams(new LinearLayout.LayoutParams(749, 1978));
        this.kbcfbtpzfd.setPadding(123, 190, 130, 135);
        linearLayout.addView(this.kbcfbtpzfd);
        this.kbcfbtpzfd.setBackgroundColor(Color.parseColor("#040245"));
        DatePicker datePicker6 = new DatePicker(this);
        this.btnhrbrgjz = datePicker6;
        datePicker6.setLayoutParams(new LinearLayout.LayoutParams(411, 1407));
        this.btnhrbrgjz.setPadding(84, 140, 125, 131);
        linearLayout.addView(this.btnhrbrgjz);
        this.btnhrbrgjz.setBackgroundColor(Color.parseColor("#381869"));
        RadioButton radioButton5 = new RadioButton(this);
        this.mtpjdpslzc = radioButton5;
        radioButton5.setLayoutParams(new LinearLayout.LayoutParams(580, 1608));
        this.mtpjdpslzc.setPadding(53, 183, 3, 105);
        linearLayout.addView(this.mtpjdpslzc);
        this.mtpjdpslzc.setBackgroundColor(Color.parseColor("#50ace3"));
        LinearLayout linearLayout10 = new LinearLayout(this);
        this.vljtqopsyy = linearLayout10;
        linearLayout10.setLayoutParams(new LinearLayout.LayoutParams(1917, 1393));
        this.vljtqopsyy.setPadding(36, 12, 190, 125);
        linearLayout.addView(this.vljtqopsyy);
        this.vljtqopsyy.setBackgroundColor(Color.parseColor("#a982a9"));
        TableLayout tableLayout4 = new TableLayout(this);
        this.ydlqetuikd = tableLayout4;
        tableLayout4.setLayoutParams(new LinearLayout.LayoutParams(1682, 1240));
        this.ydlqetuikd.setPadding(171, 11, 99, 21);
        linearLayout.addView(this.ydlqetuikd);
        this.ydlqetuikd.setBackgroundColor(Color.parseColor("#3fecb4"));
        RadioButton radioButton6 = new RadioButton(this);
        this.wpsxsheoyr = radioButton6;
        radioButton6.setLayoutParams(new LinearLayout.LayoutParams(1590, 169));
        this.wpsxsheoyr.setPadding(15, 190, 88, 65);
        linearLayout.addView(this.wpsxsheoyr);
        this.wpsxsheoyr.setBackgroundColor(Color.parseColor("#3037e6"));
        ImageView imageView8 = new ImageView(this);
        this.xdezzvyivq = imageView8;
        imageView8.setLayoutParams(new LinearLayout.LayoutParams(495, 253));
        this.xdezzvyivq.setPadding(191, 91, 186, 154);
        linearLayout.addView(this.xdezzvyivq);
        this.xdezzvyivq.setBackgroundColor(Color.parseColor("#5a0e9c"));
        FrameLayout frameLayout2 = new FrameLayout(this);
        this.ocgungigsz = frameLayout2;
        frameLayout2.setLayoutParams(new LinearLayout.LayoutParams(310, 172));
        this.ocgungigsz.setPadding(159, 95, 135, 29);
        linearLayout.addView(this.ocgungigsz);
        this.ocgungigsz.setBackgroundColor(Color.parseColor("#035906"));
        CheckBox checkBox3 = new CheckBox(this);
        this.tralzwygzz = checkBox3;
        checkBox3.setLayoutParams(new LinearLayout.LayoutParams(306, 276));
        this.tralzwygzz.setPadding(59, 145, 43, 77);
        linearLayout.addView(this.tralzwygzz);
        this.tralzwygzz.setBackgroundColor(Color.parseColor("#641cd9"));
        LinearLayout linearLayout11 = new LinearLayout(this);
        this.vzcohqbjfd = linearLayout11;
        linearLayout11.setLayoutParams(new LinearLayout.LayoutParams(1885, 1260));
        this.vzcohqbjfd.setPadding(113, 199, 87, 59);
        linearLayout.addView(this.vzcohqbjfd);
        this.vzcohqbjfd.setBackgroundColor(Color.parseColor("#946f3a"));
        ListView listView4 = new ListView(this);
        this.enimhcixlk = listView4;
        listView4.setLayoutParams(new LinearLayout.LayoutParams(1846, 1602));
        this.enimhcixlk.setPadding(151, 9, 4, 83);
        linearLayout.addView(this.enimhcixlk);
        this.enimhcixlk.setBackgroundColor(Color.parseColor("#8ebabc"));
        CheckBox checkBox4 = new CheckBox(this);
        this.xcpgdpqkik = checkBox4;
        checkBox4.setLayoutParams(new LinearLayout.LayoutParams(1710, 934));
        this.xcpgdpqkik.setPadding(43, 119, 53, PictureConfig.CHOOSE_REQUEST);
        linearLayout.addView(this.xcpgdpqkik);
        this.xcpgdpqkik.setBackgroundColor(Color.parseColor("#45f4d3"));
        Button button3 = new Button(this);
        this.tzwqcgnbyz = button3;
        button3.setLayoutParams(new LinearLayout.LayoutParams(87, 761));
        this.tzwqcgnbyz.setPadding(122, 80, 84, 163);
        linearLayout.addView(this.tzwqcgnbyz);
        this.tzwqcgnbyz.setBackgroundColor(Color.parseColor("#3a9f16"));
        DatePicker datePicker7 = new DatePicker(this);
        this.ircffmetgf = datePicker7;
        datePicker7.setLayoutParams(new LinearLayout.LayoutParams(1919, 110));
        this.ircffmetgf.setPadding(7, 88, 99, 109);
        linearLayout.addView(this.ircffmetgf);
        this.ircffmetgf.setBackgroundColor(Color.parseColor("#41ca3f"));
        ViewFlipper viewFlipper2 = new ViewFlipper(this);
        this.ymzznnelbw = viewFlipper2;
        viewFlipper2.setLayoutParams(new LinearLayout.LayoutParams(1283, 1283));
        this.ymzznnelbw.setPadding(61, 46, 3, 183);
        linearLayout.addView(this.ymzznnelbw);
        this.ymzznnelbw.setBackgroundColor(Color.parseColor("#2336ec"));
        ScrollView scrollView4 = new ScrollView(this);
        this.psxnzqvjwd = scrollView4;
        scrollView4.setLayoutParams(new LinearLayout.LayoutParams(1207, 787));
        this.psxnzqvjwd.setPadding(191, 113, 2, 196);
        linearLayout.addView(this.psxnzqvjwd);
        this.psxnzqvjwd.setBackgroundColor(Color.parseColor("#fb60aa"));
        GridView gridView2 = new GridView(this);
        this.koyiypecdr = gridView2;
        gridView2.setLayoutParams(new LinearLayout.LayoutParams(218, 595));
        this.koyiypecdr.setPadding(172, 110, 189, 171);
        linearLayout.addView(this.koyiypecdr);
        this.koyiypecdr.setBackgroundColor(Color.parseColor("#3d7715"));
        SeekBar seekBar = new SeekBar(this);
        this.vkdedykyca = seekBar;
        seekBar.setLayoutParams(new LinearLayout.LayoutParams(15, 1151));
        this.vkdedykyca.setPadding(88, 136, 54, 170);
        linearLayout.addView(this.vkdedykyca);
        this.vkdedykyca.setBackgroundColor(Color.parseColor("#623e86"));
        EditText editText3 = new EditText(this);
        this.ykudeowibo = editText3;
        editText3.setLayoutParams(new LinearLayout.LayoutParams(383, 1065));
        this.ykudeowibo.setPadding(109, 123, BDLocation.TypeCoarseLocation, 131);
        linearLayout.addView(this.ykudeowibo);
        this.ykudeowibo.setBackgroundColor(Color.parseColor("#6b7ed3"));
        RelativeLayout relativeLayout3 = new RelativeLayout(this);
        this.bibayqeudy = relativeLayout3;
        relativeLayout3.setLayoutParams(new LinearLayout.LayoutParams(1714, 1175));
        this.bibayqeudy.setPadding(176, 54, 150, 194);
        linearLayout.addView(this.bibayqeudy);
        this.bibayqeudy.setBackgroundColor(Color.parseColor("#b8b321"));
        Button button4 = new Button(this);
        this.lirnzuonfl = button4;
        button4.setLayoutParams(new LinearLayout.LayoutParams(277, 1774));
        this.lirnzuonfl.setPadding(23, 84, 90, 120);
        linearLayout.addView(this.lirnzuonfl);
        this.lirnzuonfl.setBackgroundColor(Color.parseColor("#9b674a"));
        Switch r24 = new Switch(this);
        this.tidyjfhjaf = r24;
        r24.setLayoutParams(new LinearLayout.LayoutParams(1470, 1014));
        this.tidyjfhjaf.setPadding(56, 134, 41, 7);
        linearLayout.addView(this.tidyjfhjaf);
        this.tidyjfhjaf.setBackgroundColor(Color.parseColor("#d10e6e"));
        DatePicker datePicker8 = new DatePicker(this);
        this.yaxynefejm = datePicker8;
        datePicker8.setLayoutParams(new LinearLayout.LayoutParams(1267, 1651));
        this.yaxynefejm.setPadding(13, 24, 76, 114);
        linearLayout.addView(this.yaxynefejm);
        this.yaxynefejm.setBackgroundColor(Color.parseColor("#beefb8"));
        TextView textView3 = new TextView(this);
        this.orcqpcklpw = textView3;
        textView3.setLayoutParams(new LinearLayout.LayoutParams(1089, 1956));
        this.orcqpcklpw.setPadding(179, 134, 123, 176);
        linearLayout.addView(this.orcqpcklpw);
        this.orcqpcklpw.setBackgroundColor(Color.parseColor("#baefed"));
        TextView textView4 = new TextView(this);
        this.mnegqvfdai = textView4;
        textView4.setLayoutParams(new LinearLayout.LayoutParams(1329, 1252));
        this.mnegqvfdai.setPadding(105, 49, 186, 181);
        linearLayout.addView(this.mnegqvfdai);
        this.mnegqvfdai.setBackgroundColor(Color.parseColor("#e1ceb2"));
        ImageView imageView9 = new ImageView(this);
        this.clylgykkqj = imageView9;
        imageView9.setLayoutParams(new LinearLayout.LayoutParams(1710, 84));
        this.clylgykkqj.setPadding(197, 122, WebSocketProtocol.PAYLOAD_SHORT, 14);
        linearLayout.addView(this.clylgykkqj);
        this.clylgykkqj.setBackgroundColor(Color.parseColor("#dc71f9"));
        ViewFlipper viewFlipper3 = new ViewFlipper(this);
        this.qymuqoxwid = viewFlipper3;
        viewFlipper3.setLayoutParams(new LinearLayout.LayoutParams(122, 1305));
        this.qymuqoxwid.setPadding(50, 139, 82, 47);
        linearLayout.addView(this.qymuqoxwid);
        this.qymuqoxwid.setBackgroundColor(Color.parseColor("#bb8b12"));
        ScrollView scrollView5 = new ScrollView(this);
        this.ijkqosqkhw = scrollView5;
        scrollView5.setLayoutParams(new LinearLayout.LayoutParams(550, 815));
        this.ijkqosqkhw.setPadding(189, 70, BDLocation.TypeServerDecryptError, 154);
        linearLayout.addView(this.ijkqosqkhw);
        this.ijkqosqkhw.setBackgroundColor(Color.parseColor("#d08722"));
        RatingBar ratingBar5 = new RatingBar(this);
        this.dsimnqhjbe = ratingBar5;
        ratingBar5.setLayoutParams(new LinearLayout.LayoutParams(24, 994));
        this.dsimnqhjbe.setPadding(127, 156, 33, 94);
        linearLayout.addView(this.dsimnqhjbe);
        this.dsimnqhjbe.setBackgroundColor(Color.parseColor("#b83105"));
        Button button5 = new Button(this);
        this.fbtzixkhjn = button5;
        button5.setLayoutParams(new LinearLayout.LayoutParams(1536, 1869));
        this.fbtzixkhjn.setPadding(109, 28, 198, 58);
        linearLayout.addView(this.fbtzixkhjn);
        this.fbtzixkhjn.setBackgroundColor(Color.parseColor("#7d24ea"));
        ImageView imageView10 = new ImageView(this);
        this.axjlylwhtm = imageView10;
        imageView10.setLayoutParams(new LinearLayout.LayoutParams(524, 297));
        this.axjlylwhtm.setPadding(186, 52, 170, 29);
        linearLayout.addView(this.axjlylwhtm);
        this.axjlylwhtm.setBackgroundColor(Color.parseColor("#cb0d26"));
        CheckBox checkBox5 = new CheckBox(this);
        this.wpmmvramtp = checkBox5;
        checkBox5.setLayoutParams(new LinearLayout.LayoutParams(1826, 684));
        this.wpmmvramtp.setPadding(5, 168, 134, 124);
        linearLayout.addView(this.wpmmvramtp);
        this.wpmmvramtp.setBackgroundColor(Color.parseColor("#a75355"));
        Spinner spinner2 = new Spinner(this);
        this.yvaxftbjra = spinner2;
        spinner2.setLayoutParams(new LinearLayout.LayoutParams(196, 1347));
        this.yvaxftbjra.setPadding(6, 53, 96, 175);
        linearLayout.addView(this.yvaxftbjra);
        this.yvaxftbjra.setBackgroundColor(Color.parseColor("#b39145"));
        RadioButton radioButton7 = new RadioButton(this);
        this.saloqruzxq = radioButton7;
        radioButton7.setLayoutParams(new LinearLayout.LayoutParams(1109, 357));
        this.saloqruzxq.setPadding(76, 122, 84, 56);
        linearLayout.addView(this.saloqruzxq);
        this.saloqruzxq.setBackgroundColor(Color.parseColor("#73b5ef"));
        SeekBar seekBar2 = new SeekBar(this);
        this.nspdmwmyrm = seekBar2;
        seekBar2.setLayoutParams(new LinearLayout.LayoutParams(179, 1134));
        this.nspdmwmyrm.setPadding(2, 35, 103, 145);
        linearLayout.addView(this.nspdmwmyrm);
        this.nspdmwmyrm.setBackgroundColor(Color.parseColor("#5934cc"));
        ScrollView scrollView6 = new ScrollView(this);
        this.hhgzqmdkhi = scrollView6;
        scrollView6.setLayoutParams(new LinearLayout.LayoutParams(198, 1964));
        this.hhgzqmdkhi.setPadding(0, 59, 191, 105);
        linearLayout.addView(this.hhgzqmdkhi);
        this.hhgzqmdkhi.setBackgroundColor(Color.parseColor("#0b15a6"));
        GridView gridView3 = new GridView(this);
        this.kqylfzvhpu = gridView3;
        gridView3.setLayoutParams(new LinearLayout.LayoutParams(221, 354));
        this.kqylfzvhpu.setPadding(5, 44, 15, 179);
        linearLayout.addView(this.kqylfzvhpu);
        this.kqylfzvhpu.setBackgroundColor(Color.parseColor("#997eb0"));
        RelativeLayout relativeLayout4 = new RelativeLayout(this);
        this.djhyibnvke = relativeLayout4;
        relativeLayout4.setLayoutParams(new LinearLayout.LayoutParams(496, 495));
        this.djhyibnvke.setPadding(121, 189, 111, 163);
        linearLayout.addView(this.djhyibnvke);
        this.djhyibnvke.setBackgroundColor(Color.parseColor("#e6e8f4"));
        Spinner spinner3 = new Spinner(this);
        this.tmukjanvxt = spinner3;
        spinner3.setLayoutParams(new LinearLayout.LayoutParams(776, 18));
        this.tmukjanvxt.setPadding(113, 96, BDLocation.TypeNetWorkLocation, 62);
        linearLayout.addView(this.tmukjanvxt);
        this.tmukjanvxt.setBackgroundColor(Color.parseColor("#cfbdff"));
        ToggleButton toggleButton4 = new ToggleButton(this);
        this.iucbzxyqft = toggleButton4;
        toggleButton4.setLayoutParams(new LinearLayout.LayoutParams(1652, 181));
        this.iucbzxyqft.setPadding(43, 109, 31, 197);
        linearLayout.addView(this.iucbzxyqft);
        this.iucbzxyqft.setBackgroundColor(Color.parseColor("#799a17"));
        CheckBox checkBox6 = new CheckBox(this);
        this.ezqnxaidva = checkBox6;
        checkBox6.setLayoutParams(new LinearLayout.LayoutParams(477, 843));
        this.ezqnxaidva.setPadding(169, 112, 169, 46);
        linearLayout.addView(this.ezqnxaidva);
        this.ezqnxaidva.setBackgroundColor(Color.parseColor("#1330d8"));
        EditText editText4 = new EditText(this);
        this.worgtbfkwv = editText4;
        editText4.setLayoutParams(new LinearLayout.LayoutParams(866, 1456));
        this.worgtbfkwv.setPadding(33, 131, 98, 7);
        linearLayout.addView(this.worgtbfkwv);
        this.worgtbfkwv.setBackgroundColor(Color.parseColor("#b2451f"));
        ScrollView scrollView7 = new ScrollView(this);
        this.hkcgqlpwtl = scrollView7;
        scrollView7.setLayoutParams(new LinearLayout.LayoutParams(1478, 67));
        this.hkcgqlpwtl.setPadding(154, 9, 99, 119);
        linearLayout.addView(this.hkcgqlpwtl);
        this.hkcgqlpwtl.setBackgroundColor(Color.parseColor("#bf7521"));
        RadioButton radioButton8 = new RadioButton(this);
        this.mvexrtbzcf = radioButton8;
        radioButton8.setLayoutParams(new LinearLayout.LayoutParams(1933, 362));
        this.mvexrtbzcf.setPadding(108, 95, 192, 171);
        linearLayout.addView(this.mvexrtbzcf);
        this.mvexrtbzcf.setBackgroundColor(Color.parseColor("#bc4aa7"));
        GridView gridView4 = new GridView(this);
        this.gtzkgxyijo = gridView4;
        gridView4.setLayoutParams(new LinearLayout.LayoutParams(143, 314));
        this.gtzkgxyijo.setPadding(110, 104, 174, 26);
        linearLayout.addView(this.gtzkgxyijo);
        this.gtzkgxyijo.setBackgroundColor(Color.parseColor("#dcc24d"));
        RatingBar ratingBar6 = new RatingBar(this);
        this.xzodtyvznx = ratingBar6;
        ratingBar6.setLayoutParams(new LinearLayout.LayoutParams(1772, 569));
        this.xzodtyvznx.setPadding(26, 189, 39, 54);
        linearLayout.addView(this.xzodtyvznx);
        this.xzodtyvznx.setBackgroundColor(Color.parseColor("#27f4ae"));
        ProgressBar progressBar3 = new ProgressBar(this);
        this.odlfokzrka = progressBar3;
        progressBar3.setLayoutParams(new LinearLayout.LayoutParams(485, 106));
        this.odlfokzrka.setPadding(181, 94, 37, 136);
        linearLayout.addView(this.odlfokzrka);
        this.odlfokzrka.setBackgroundColor(Color.parseColor("#66cce0"));
        EditText editText5 = new EditText(this);
        this.zbktziunsu = editText5;
        editText5.setLayoutParams(new LinearLayout.LayoutParams(20, 493));
        this.zbktziunsu.setPadding(96, 25, 123, 191);
        linearLayout.addView(this.zbktziunsu);
        this.zbktziunsu.setBackgroundColor(Color.parseColor("#fc2b8d"));
        FrameLayout frameLayout3 = new FrameLayout(this);
        this.dcwpznhqnq = frameLayout3;
        frameLayout3.setLayoutParams(new LinearLayout.LayoutParams(1978, 1529));
        this.dcwpznhqnq.setPadding(27, 36, 65, 156);
        linearLayout.addView(this.dcwpznhqnq);
        this.dcwpznhqnq.setBackgroundColor(Color.parseColor("#9c8176"));
        RatingBar ratingBar7 = new RatingBar(this);
        this.hmulndolko = ratingBar7;
        ratingBar7.setLayoutParams(new LinearLayout.LayoutParams(1839, 383));
        this.hmulndolko.setPadding(113, 178, 94, 157);
        linearLayout.addView(this.hmulndolko);
        this.hmulndolko.setBackgroundColor(Color.parseColor("#199f11"));
        ListView listView5 = new ListView(this);
        this.mlnmxktmih = listView5;
        listView5.setLayoutParams(new LinearLayout.LayoutParams(1152, 949));
        this.mlnmxktmih.setPadding(142, 159, 193, 4);
        linearLayout.addView(this.mlnmxktmih);
        this.mlnmxktmih.setBackgroundColor(Color.parseColor("#3bc99a"));
        LinearLayout linearLayout12 = new LinearLayout(this);
        this.rgoojdvhdh = linearLayout12;
        linearLayout12.setLayoutParams(new LinearLayout.LayoutParams(1753, 1651));
        this.rgoojdvhdh.setPadding(180, 89, 17, 179);
        linearLayout.addView(this.rgoojdvhdh);
        this.rgoojdvhdh.setBackgroundColor(Color.parseColor("#8895b3"));
        TextView textView5 = new TextView(this);
        this.bsgtxqejqu = textView5;
        textView5.setLayoutParams(new LinearLayout.LayoutParams(42, 421));
        this.bsgtxqejqu.setPadding(125, 140, 91, 7);
        linearLayout.addView(this.bsgtxqejqu);
        this.bsgtxqejqu.setBackgroundColor(Color.parseColor("#891f6e"));
        ListView listView6 = new ListView(this);
        this.qjxnadqtwx = listView6;
        listView6.setLayoutParams(new LinearLayout.LayoutParams(1630, 1462));
        this.qjxnadqtwx.setPadding(91, 97, 170, 15);
        linearLayout.addView(this.qjxnadqtwx);
        this.qjxnadqtwx.setBackgroundColor(Color.parseColor("#f47f83"));
        EditText editText6 = new EditText(this);
        this.orilpeshzb = editText6;
        editText6.setLayoutParams(new LinearLayout.LayoutParams(1391, 1853));
        this.orilpeshzb.setPadding(187, 91, 65, 111);
        linearLayout.addView(this.orilpeshzb);
        this.orilpeshzb.setBackgroundColor(Color.parseColor("#55d35f"));
        Spinner spinner4 = new Spinner(this);
        this.vamtwamxny = spinner4;
        spinner4.setLayoutParams(new LinearLayout.LayoutParams(1374, 255));
        this.vamtwamxny.setPadding(159, 95, 108, 69);
        linearLayout.addView(this.vamtwamxny);
        this.vamtwamxny.setBackgroundColor(Color.parseColor("#8f8296"));
        ImageView imageView11 = new ImageView(this);
        this.ckhreksdkt = imageView11;
        imageView11.setLayoutParams(new LinearLayout.LayoutParams(679, 89));
        this.ckhreksdkt.setPadding(50, 55, 62, 191);
        linearLayout.addView(this.ckhreksdkt);
        this.ckhreksdkt.setBackgroundColor(Color.parseColor("#5776be"));
        TimePicker timePicker2 = new TimePicker(this);
        this.fpbysbxfmb = timePicker2;
        timePicker2.setLayoutParams(new LinearLayout.LayoutParams(793, 1568));
        this.fpbysbxfmb.setPadding(182, 121, 36, BDLocation.TypeServerError);
        linearLayout.addView(this.fpbysbxfmb);
        this.fpbysbxfmb.setBackgroundColor(Color.parseColor("#64697e"));
        ProgressBar progressBar4 = new ProgressBar(this);
        this.apfuoxokax = progressBar4;
        progressBar4.setLayoutParams(new LinearLayout.LayoutParams(1708, 1231));
        this.apfuoxokax.setPadding(185, 34, 63, 148);
        linearLayout.addView(this.apfuoxokax);
        this.apfuoxokax.setBackgroundColor(Color.parseColor("#66be00"));
        LinearLayout linearLayout13 = new LinearLayout(this);
        this.mawaqsnnrt = linearLayout13;
        linearLayout13.setLayoutParams(new LinearLayout.LayoutParams(404, 1172));
        this.mawaqsnnrt.setPadding(78, 26, BDLocation.TypeServerError, 30);
        linearLayout.addView(this.mawaqsnnrt);
        this.mawaqsnnrt.setBackgroundColor(Color.parseColor("#e1ed00"));
        ViewFlipper viewFlipper4 = new ViewFlipper(this);
        this.eotxnheade = viewFlipper4;
        viewFlipper4.setLayoutParams(new LinearLayout.LayoutParams(746, 32));
        this.eotxnheade.setPadding(175, 52, 114, 183);
        linearLayout.addView(this.eotxnheade);
        this.eotxnheade.setBackgroundColor(Color.parseColor("#9e309b"));
        SeekBar seekBar3 = new SeekBar(this);
        this.qiscxrfomi = seekBar3;
        seekBar3.setLayoutParams(new LinearLayout.LayoutParams(1843, 978));
        this.qiscxrfomi.setPadding(24, 84, 69, 145);
        linearLayout.addView(this.qiscxrfomi);
        this.qiscxrfomi.setBackgroundColor(Color.parseColor("#b10adb"));
        Switch r25 = new Switch(this);
        this.wluqsonfgk = r25;
        r25.setLayoutParams(new LinearLayout.LayoutParams(1504, 150));
        this.wluqsonfgk.setPadding(198, 164, 163, 111);
        linearLayout.addView(this.wluqsonfgk);
        this.wluqsonfgk.setBackgroundColor(Color.parseColor("#be1028"));
        CheckBox checkBox7 = new CheckBox(this);
        this.utfrzzhopz = checkBox7;
        checkBox7.setLayoutParams(new LinearLayout.LayoutParams(1213, 1767));
        this.utfrzzhopz.setPadding(150, 75, 73, 28);
        linearLayout.addView(this.utfrzzhopz);
        this.utfrzzhopz.setBackgroundColor(Color.parseColor("#54a4e1"));
        Button button6 = new Button(this);
        this.grxegscoyk = button6;
        button6.setLayoutParams(new LinearLayout.LayoutParams(1342, 1350));
        this.grxegscoyk.setPadding(34, 147, 26, BDLocation.TypeServerDecryptError);
        linearLayout.addView(this.grxegscoyk);
        this.grxegscoyk.setBackgroundColor(Color.parseColor("#e738e8"));
        Switch r26 = new Switch(this);
        this.lggizvbktk = r26;
        r26.setLayoutParams(new LinearLayout.LayoutParams(268, 1198));
        this.lggizvbktk.setPadding(13, 159, 110, 168);
        linearLayout.addView(this.lggizvbktk);
        this.lggizvbktk.setBackgroundColor(Color.parseColor("#2dcad2"));
        Spinner spinner5 = new Spinner(this);
        this.eemmdtguin = spinner5;
        spinner5.setLayoutParams(new LinearLayout.LayoutParams(1270, 734));
        this.eemmdtguin.setPadding(0, 182, 87, 140);
        linearLayout.addView(this.eemmdtguin);
        this.eemmdtguin.setBackgroundColor(Color.parseColor("#acd962"));
        ScrollView scrollView8 = new ScrollView(this);
        this.oanranzoqx = scrollView8;
        scrollView8.setLayoutParams(new LinearLayout.LayoutParams(427, 1210));
        this.oanranzoqx.setPadding(173, 168, 28, 120);
        linearLayout.addView(this.oanranzoqx);
        this.oanranzoqx.setBackgroundColor(Color.parseColor("#969365"));
        RelativeLayout relativeLayout5 = new RelativeLayout(this);
        this.igubfvrtxo = relativeLayout5;
        relativeLayout5.setLayoutParams(new LinearLayout.LayoutParams(476, 39));
        this.igubfvrtxo.setPadding(192, 12, 151, 20);
        linearLayout.addView(this.igubfvrtxo);
        this.igubfvrtxo.setBackgroundColor(Color.parseColor("#9c7609"));
        Spinner spinner6 = new Spinner(this);
        this.ksjixkxmiv = spinner6;
        spinner6.setLayoutParams(new LinearLayout.LayoutParams(1494, 553));
        this.ksjixkxmiv.setPadding(21, 26, 99, 136);
        linearLayout.addView(this.ksjixkxmiv);
        this.ksjixkxmiv.setBackgroundColor(Color.parseColor("#1654d6"));
        CheckBox checkBox8 = new CheckBox(this);
        this.hvpvqxtdyd = checkBox8;
        checkBox8.setLayoutParams(new LinearLayout.LayoutParams(1078, 898));
        this.hvpvqxtdyd.setPadding(155, 59, 93, 109);
        linearLayout.addView(this.hvpvqxtdyd);
        this.hvpvqxtdyd.setBackgroundColor(Color.parseColor("#f82b01"));
        ProgressBar progressBar5 = new ProgressBar(this);
        this.yisijadpwh = progressBar5;
        progressBar5.setLayoutParams(new LinearLayout.LayoutParams(1902, 1553));
        this.yisijadpwh.setPadding(80, 57, 107, 151);
        linearLayout.addView(this.yisijadpwh);
        this.yisijadpwh.setBackgroundColor(Color.parseColor("#b71630"));
        RatingBar ratingBar8 = new RatingBar(this);
        this.oxwbkyinnb = ratingBar8;
        ratingBar8.setLayoutParams(new LinearLayout.LayoutParams(GattClient.STATE_READ_IMAGE_INFO, TypedValues.TransitionType.TYPE_FROM));
        this.oxwbkyinnb.setPadding(70, 117, 130, 137);
        linearLayout.addView(this.oxwbkyinnb);
        this.oxwbkyinnb.setBackgroundColor(Color.parseColor("#48f85c"));
        DatePicker datePicker9 = new DatePicker(this);
        this.dwhhikohnn = datePicker9;
        datePicker9.setLayoutParams(new LinearLayout.LayoutParams(692, 309));
        this.dwhhikohnn.setPadding(19, 197, 194, 77);
        linearLayout.addView(this.dwhhikohnn);
        this.dwhhikohnn.setBackgroundColor(Color.parseColor("#d7c850"));
        Spinner spinner7 = new Spinner(this);
        this.xehruupjil = spinner7;
        spinner7.setLayoutParams(new LinearLayout.LayoutParams(1883, 1006));
        this.xehruupjil.setPadding(62, BDLocation.TypeCoarseLocation, 150, 46);
        linearLayout.addView(this.xehruupjil);
        this.xehruupjil.setBackgroundColor(Color.parseColor("#b26074"));
        DatePicker datePicker10 = new DatePicker(this);
        this.uuvnymidtv = datePicker10;
        datePicker10.setLayoutParams(new LinearLayout.LayoutParams(1337, 352));
        this.uuvnymidtv.setPadding(84, 158, 62, 108);
        linearLayout.addView(this.uuvnymidtv);
        this.uuvnymidtv.setBackgroundColor(Color.parseColor("#30fb64"));
        ScrollView scrollView9 = new ScrollView(this);
        this.aivqdfldlb = scrollView9;
        scrollView9.setLayoutParams(new LinearLayout.LayoutParams(1259, 1813));
        this.aivqdfldlb.setPadding(99, 159, 86, 156);
        linearLayout.addView(this.aivqdfldlb);
        this.aivqdfldlb.setBackgroundColor(Color.parseColor("#0acac4"));
        ScrollView scrollView10 = new ScrollView(this);
        this.prbjgzjgce = scrollView10;
        scrollView10.setLayoutParams(new LinearLayout.LayoutParams(1061, 1351));
        this.prbjgzjgce.setPadding(197, 144, 16, 26);
        linearLayout.addView(this.prbjgzjgce);
        this.prbjgzjgce.setBackgroundColor(Color.parseColor("#93a9ed"));
        Switch r27 = new Switch(this);
        this.kmolehhzah = r27;
        r27.setLayoutParams(new LinearLayout.LayoutParams(PictureConfig.REQUEST_CAMERA, 1565));
        this.kmolehhzah.setPadding(6, 125, 147, 187);
        linearLayout.addView(this.kmolehhzah);
        this.kmolehhzah.setBackgroundColor(Color.parseColor("#f6b743"));
        Spinner spinner8 = new Spinner(this);
        this.sdtrhvbdau = spinner8;
        spinner8.setLayoutParams(new LinearLayout.LayoutParams(1581, 1881));
        this.sdtrhvbdau.setPadding(8, 119, 48, 115);
        linearLayout.addView(this.sdtrhvbdau);
        this.sdtrhvbdau.setBackgroundColor(Color.parseColor("#ffc84b"));
        EditText editText7 = new EditText(this);
        this.ddakzdpysc = editText7;
        editText7.setLayoutParams(new LinearLayout.LayoutParams(1311, 1034));
        this.ddakzdpysc.setPadding(35, 153, 34, 80);
        linearLayout.addView(this.ddakzdpysc);
        this.ddakzdpysc.setBackgroundColor(Color.parseColor("#3de04c"));
        ScrollView scrollView11 = new ScrollView(this);
        this.jvgfubipjd = scrollView11;
        scrollView11.setLayoutParams(new LinearLayout.LayoutParams(668, 657));
        this.jvgfubipjd.setPadding(50, 25, 156, 66);
        linearLayout.addView(this.jvgfubipjd);
        this.jvgfubipjd.setBackgroundColor(Color.parseColor("#0ac91c"));
        ImageView imageView12 = new ImageView(this);
        this.ckrfjebvvk = imageView12;
        imageView12.setLayoutParams(new LinearLayout.LayoutParams(1590, 1162));
        this.ckrfjebvvk.setPadding(48, 121, 135, 144);
        linearLayout.addView(this.ckrfjebvvk);
        this.ckrfjebvvk.setBackgroundColor(Color.parseColor("#aea4d2"));
        ScrollView scrollView12 = new ScrollView(this);
        this.ytfwkxendw = scrollView12;
        scrollView12.setLayoutParams(new LinearLayout.LayoutParams(1468, 1714));
        this.ytfwkxendw.setPadding(33, 113, 193, 7);
        linearLayout.addView(this.ytfwkxendw);
        this.ytfwkxendw.setBackgroundColor(Color.parseColor("#bbae5a"));
        Button button7 = new Button(this);
        this.gbfhqemtno = button7;
        button7.setLayoutParams(new LinearLayout.LayoutParams(435, 343));
        this.gbfhqemtno.setPadding(84, 179, 130, BDLocation.TypeServerDecryptError);
        linearLayout.addView(this.gbfhqemtno);
        this.gbfhqemtno.setBackgroundColor(Color.parseColor("#84e168"));
        EditText editText8 = new EditText(this);
        this.zaxkxvzjoe = editText8;
        editText8.setLayoutParams(new LinearLayout.LayoutParams(1978, 1528));
        this.zaxkxvzjoe.setPadding(174, 33, 40, 9);
        linearLayout.addView(this.zaxkxvzjoe);
        this.zaxkxvzjoe.setBackgroundColor(Color.parseColor("#f0ca4f"));
        Button button8 = new Button(this);
        this.xesifqgmbv = button8;
        button8.setLayoutParams(new LinearLayout.LayoutParams(1855, 1442));
        this.xesifqgmbv.setPadding(82, 134, 59, 15);
        linearLayout.addView(this.xesifqgmbv);
        this.xesifqgmbv.setBackgroundColor(Color.parseColor("#d2ef7c"));
        Spinner spinner9 = new Spinner(this);
        this.iiopjnobtb = spinner9;
        spinner9.setLayoutParams(new LinearLayout.LayoutParams(486, 1420));
        this.iiopjnobtb.setPadding(44, 198, 75, 68);
        linearLayout.addView(this.iiopjnobtb);
        this.iiopjnobtb.setBackgroundColor(Color.parseColor("#d00c8f"));
        LinearLayout linearLayout14 = new LinearLayout(this);
        this.dponmyufso = linearLayout14;
        linearLayout14.setLayoutParams(new LinearLayout.LayoutParams(1985, 1800));
        this.dponmyufso.setPadding(12, 155, 158, 140);
        linearLayout.addView(this.dponmyufso);
        this.dponmyufso.setBackgroundColor(Color.parseColor("#3022cd"));
        RadioButton radioButton9 = new RadioButton(this);
        this.xubtpivcrw = radioButton9;
        radioButton9.setLayoutParams(new LinearLayout.LayoutParams(561, 1343));
        this.xubtpivcrw.setPadding(40, 95, 102, 178);
        linearLayout.addView(this.xubtpivcrw);
        this.xubtpivcrw.setBackgroundColor(Color.parseColor("#0d028c"));
        CheckBox checkBox9 = new CheckBox(this);
        this.ktqqtakmxi = checkBox9;
        checkBox9.setLayoutParams(new LinearLayout.LayoutParams(467, 1215));
        this.ktqqtakmxi.setPadding(185, 8, 80, 69);
        linearLayout.addView(this.ktqqtakmxi);
        this.ktqqtakmxi.setBackgroundColor(Color.parseColor("#02804a"));
        ToggleButton toggleButton5 = new ToggleButton(this);
        this.wouqojddtu = toggleButton5;
        toggleButton5.setLayoutParams(new LinearLayout.LayoutParams(174, 1980));
        this.wouqojddtu.setPadding(31, 76, 48, 101);
        linearLayout.addView(this.wouqojddtu);
        this.wouqojddtu.setBackgroundColor(Color.parseColor("#42c7f5"));
        ImageView imageView13 = new ImageView(this);
        this.zietyokeey = imageView13;
        imageView13.setLayoutParams(new LinearLayout.LayoutParams(LocalPlaybackConstants.BUFFER_A_CAN_USE_FLAG, 104));
        this.zietyokeey.setPadding(8, 130, 184, 98);
        linearLayout.addView(this.zietyokeey);
        this.zietyokeey.setBackgroundColor(Color.parseColor("#5e8119"));
        CheckBox checkBox10 = new CheckBox(this);
        this.jsadsvnlpa = checkBox10;
        checkBox10.setLayoutParams(new LinearLayout.LayoutParams(1314, 41));
        this.jsadsvnlpa.setPadding(147, BDLocation.TypeServerDecryptError, 0, 81);
        linearLayout.addView(this.jsadsvnlpa);
        this.jsadsvnlpa.setBackgroundColor(Color.parseColor("#ce72c1"));
        Spinner spinner10 = new Spinner(this);
        this.hutvghrfhy = spinner10;
        spinner10.setLayoutParams(new LinearLayout.LayoutParams(922, 1166));
        this.hutvghrfhy.setPadding(59, 129, 63, PictureConfig.CHOOSE_REQUEST);
        linearLayout.addView(this.hutvghrfhy);
        this.hutvghrfhy.setBackgroundColor(Color.parseColor("#f6ee09"));
        RadioButton radioButton10 = new RadioButton(this);
        this.zaztexizio = radioButton10;
        radioButton10.setLayoutParams(new LinearLayout.LayoutParams(357, 261));
        this.zaztexizio.setPadding(15, 84, 32, 14);
        linearLayout.addView(this.zaztexizio);
        this.zaztexizio.setBackgroundColor(Color.parseColor("#93984c"));
        ProgressBar progressBar6 = new ProgressBar(this);
        this.srwwbxlogy = progressBar6;
        progressBar6.setLayoutParams(new LinearLayout.LayoutParams(1485, 1300));
        this.srwwbxlogy.setPadding(6, 31, 113, 23);
        linearLayout.addView(this.srwwbxlogy);
        this.srwwbxlogy.setBackgroundColor(Color.parseColor("#4e2cc9"));
        FrameLayout frameLayout4 = new FrameLayout(this);
        this.cjwtodaijy = frameLayout4;
        frameLayout4.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.MotionType.TYPE_PATHMOTION_ARC, 1513));
        this.cjwtodaijy.setPadding(111, 114, 6, 130);
        linearLayout.addView(this.cjwtodaijy);
        this.cjwtodaijy.setBackgroundColor(Color.parseColor("#cf24de"));
        ProgressBar progressBar7 = new ProgressBar(this);
        this.btisymvssx = progressBar7;
        progressBar7.setLayoutParams(new LinearLayout.LayoutParams(1950, 1161));
        this.btisymvssx.setPadding(110, 40, 91, 65);
        linearLayout.addView(this.btisymvssx);
        this.btisymvssx.setBackgroundColor(Color.parseColor("#234886"));
        SeekBar seekBar4 = new SeekBar(this);
        this.cfpddnetwy = seekBar4;
        seekBar4.setLayoutParams(new LinearLayout.LayoutParams(1420, 1194));
        this.cfpddnetwy.setPadding(138, 76, 183, 177);
        linearLayout.addView(this.cfpddnetwy);
        this.cfpddnetwy.setBackgroundColor(Color.parseColor("#be359c"));
        TimePicker timePicker3 = new TimePicker(this);
        this.cepwzpsrvk = timePicker3;
        timePicker3.setLayoutParams(new LinearLayout.LayoutParams(240, 1254));
        this.cepwzpsrvk.setPadding(91, 130, 180, 0);
        linearLayout.addView(this.cepwzpsrvk);
        this.cepwzpsrvk.setBackgroundColor(Color.parseColor("#687d71"));
        RelativeLayout relativeLayout6 = new RelativeLayout(this);
        this.ifcqqmblom = relativeLayout6;
        relativeLayout6.setLayoutParams(new LinearLayout.LayoutParams(1577, 564));
        this.ifcqqmblom.setPadding(104, 30, 106, BDLocation.TypeCoarseLocation);
        linearLayout.addView(this.ifcqqmblom);
        this.ifcqqmblom.setBackgroundColor(Color.parseColor("#9b2088"));
        RelativeLayout relativeLayout7 = new RelativeLayout(this);
        this.ctnxxagebq = relativeLayout7;
        relativeLayout7.setLayoutParams(new LinearLayout.LayoutParams(1737, 1228));
        this.ctnxxagebq.setPadding(38, 44, 173, 142);
        linearLayout.addView(this.ctnxxagebq);
        this.ctnxxagebq.setBackgroundColor(Color.parseColor("#beb3b0"));
        FrameLayout frameLayout5 = new FrameLayout(this);
        this.ximqzgroib = frameLayout5;
        frameLayout5.setLayoutParams(new LinearLayout.LayoutParams(1381, 1023));
        this.ximqzgroib.setPadding(189, 60, 84, 124);
        linearLayout.addView(this.ximqzgroib);
        this.ximqzgroib.setBackgroundColor(Color.parseColor("#ecc7b0"));
        RadioButton radioButton11 = new RadioButton(this);
        this.dunlhvnlmh = radioButton11;
        radioButton11.setLayoutParams(new LinearLayout.LayoutParams(321, 1673));
        this.dunlhvnlmh.setPadding(108, 41, 137, 103);
        linearLayout.addView(this.dunlhvnlmh);
        this.dunlhvnlmh.setBackgroundColor(Color.parseColor("#655198"));
        ProgressBar progressBar8 = new ProgressBar(this);
        this.nyiuayilaz = progressBar8;
        progressBar8.setLayoutParams(new LinearLayout.LayoutParams(1858, 285));
        this.nyiuayilaz.setPadding(181, 86, 31, 150);
        linearLayout.addView(this.nyiuayilaz);
        this.nyiuayilaz.setBackgroundColor(Color.parseColor("#8b1fdd"));
        DatePicker datePicker11 = new DatePicker(this);
        this.awckmunoka = datePicker11;
        datePicker11.setLayoutParams(new LinearLayout.LayoutParams(1060, 1683));
        this.awckmunoka.setPadding(2, 101, 13, 88);
        linearLayout.addView(this.awckmunoka);
        this.awckmunoka.setBackgroundColor(Color.parseColor("#7058d8"));
        DatePicker datePicker12 = new DatePicker(this);
        this.jolgbzrjul = datePicker12;
        datePicker12.setLayoutParams(new LinearLayout.LayoutParams(1490, 776));
        this.jolgbzrjul.setPadding(182, 68, 18, 168);
        linearLayout.addView(this.jolgbzrjul);
        this.jolgbzrjul.setBackgroundColor(Color.parseColor("#4fa08b"));
        RatingBar ratingBar9 = new RatingBar(this);
        this.csvrjmpeud = ratingBar9;
        ratingBar9.setLayoutParams(new LinearLayout.LayoutParams(1484, 779));
        this.csvrjmpeud.setPadding(32, 125, 105, 112);
        linearLayout.addView(this.csvrjmpeud);
        this.csvrjmpeud.setBackgroundColor(Color.parseColor("#26b269"));
        RadioButton radioButton12 = new RadioButton(this);
        this.zlbecuafas = radioButton12;
        radioButton12.setLayoutParams(new LinearLayout.LayoutParams(1035, 1367));
        this.zlbecuafas.setPadding(81, 57, 149, 112);
        linearLayout.addView(this.zlbecuafas);
        this.zlbecuafas.setBackgroundColor(Color.parseColor("#12aecb"));
        FrameLayout frameLayout6 = new FrameLayout(this);
        this.wzwojgkhqo = frameLayout6;
        frameLayout6.setLayoutParams(new LinearLayout.LayoutParams(GattClient.STATE_PENDDING_DISCOVERY_SERVICE, 1993));
        this.wzwojgkhqo.setPadding(143, 34, 102, 89);
        linearLayout.addView(this.wzwojgkhqo);
        this.wzwojgkhqo.setBackgroundColor(Color.parseColor("#158eac"));
        Spinner spinner11 = new Spinner(this);
        this.bnsajwfhmg = spinner11;
        spinner11.setLayoutParams(new LinearLayout.LayoutParams(932, 1624));
        this.bnsajwfhmg.setPadding(122, 75, 10, 99);
        linearLayout.addView(this.bnsajwfhmg);
        this.bnsajwfhmg.setBackgroundColor(Color.parseColor("#f04bc3"));
        RatingBar ratingBar10 = new RatingBar(this);
        this.ihzkjkewzf = ratingBar10;
        ratingBar10.setLayoutParams(new LinearLayout.LayoutParams(1929, 1589));
        this.ihzkjkewzf.setPadding(11, 157, 184, 15);
        linearLayout.addView(this.ihzkjkewzf);
        this.ihzkjkewzf.setBackgroundColor(Color.parseColor("#25c967"));
        TimePicker timePicker4 = new TimePicker(this);
        this.fmrbbiuauj = timePicker4;
        timePicker4.setLayoutParams(new LinearLayout.LayoutParams(117, 1574));
        this.fmrbbiuauj.setPadding(76, 64, 125, 25);
        linearLayout.addView(this.fmrbbiuauj);
        this.fmrbbiuauj.setBackgroundColor(Color.parseColor("#e8675a"));
        Button button9 = new Button(this);
        this.azwsvhiwwx = button9;
        button9.setLayoutParams(new LinearLayout.LayoutParams(400, 506));
        this.azwsvhiwwx.setPadding(170, 154, 34, 70);
        linearLayout.addView(this.azwsvhiwwx);
        this.azwsvhiwwx.setBackgroundColor(Color.parseColor("#56f02b"));
        DatePicker datePicker13 = new DatePicker(this);
        this.cxsyjceufs = datePicker13;
        datePicker13.setLayoutParams(new LinearLayout.LayoutParams(1836, 1587));
        this.cxsyjceufs.setPadding(31, 152, 29, 30);
        linearLayout.addView(this.cxsyjceufs);
        this.cxsyjceufs.setBackgroundColor(Color.parseColor("#b0eb17"));
        RelativeLayout relativeLayout8 = new RelativeLayout(this);
        this.dcvdcddqks = relativeLayout8;
        relativeLayout8.setLayoutParams(new LinearLayout.LayoutParams(465, 451));
        this.dcvdcddqks.setPadding(116, 72, 133, WebSocketProtocol.PAYLOAD_SHORT);
        linearLayout.addView(this.dcvdcddqks);
        this.dcvdcddqks.setBackgroundColor(Color.parseColor("#be85b7"));
        ProgressBar progressBar9 = new ProgressBar(this);
        this.qyrdcollnf = progressBar9;
        progressBar9.setLayoutParams(new LinearLayout.LayoutParams(1059, 1645));
        this.qyrdcollnf.setPadding(BDLocation.TypeServerDecryptError, 136, 66, 5);
        linearLayout.addView(this.qyrdcollnf);
        this.qyrdcollnf.setBackgroundColor(Color.parseColor("#cf058d"));
        TimePicker timePicker5 = new TimePicker(this);
        this.uffkkoctcl = timePicker5;
        timePicker5.setLayoutParams(new LinearLayout.LayoutParams(68, 225));
        this.uffkkoctcl.setPadding(65, 22, 129, 153);
        linearLayout.addView(this.uffkkoctcl);
        this.uffkkoctcl.setBackgroundColor(Color.parseColor("#c45d71"));
        TimePicker timePicker6 = new TimePicker(this);
        this.drojyljtvt = timePicker6;
        timePicker6.setLayoutParams(new LinearLayout.LayoutParams(1708, 1884));
        this.drojyljtvt.setPadding(106, 108, 46, 62);
        linearLayout.addView(this.drojyljtvt);
        this.drojyljtvt.setBackgroundColor(Color.parseColor("#89615a"));
        SeekBar seekBar5 = new SeekBar(this);
        this.xtmfkbfdwq = seekBar5;
        seekBar5.setLayoutParams(new LinearLayout.LayoutParams(655, PDF417Common.NUMBER_OF_CODEWORDS));
        this.xtmfkbfdwq.setPadding(55, 87, BDLocation.TypeServerDecryptError, 195);
        linearLayout.addView(this.xtmfkbfdwq);
        this.xtmfkbfdwq.setBackgroundColor(Color.parseColor("#d63e0d"));
        ListView listView7 = new ListView(this);
        this.ibrmdgdyvf = listView7;
        listView7.setLayoutParams(new LinearLayout.LayoutParams(710, 1552));
        this.ibrmdgdyvf.setPadding(50, 67, 77, 80);
        linearLayout.addView(this.ibrmdgdyvf);
        this.ibrmdgdyvf.setBackgroundColor(Color.parseColor("#53bf24"));
        RelativeLayout relativeLayout9 = new RelativeLayout(this);
        this.wwyxgagtio = relativeLayout9;
        relativeLayout9.setLayoutParams(new LinearLayout.LayoutParams(334, 698));
        this.wwyxgagtio.setPadding(18, 181, 190, 183);
        linearLayout.addView(this.wwyxgagtio);
        this.wwyxgagtio.setBackgroundColor(Color.parseColor("#de9e86"));
        EditText editText9 = new EditText(this);
        this.qvsgjazdpy = editText9;
        editText9.setLayoutParams(new LinearLayout.LayoutParams(997, 214));
        this.qvsgjazdpy.setPadding(1, 117, 5, 190);
        linearLayout.addView(this.qvsgjazdpy);
        this.qvsgjazdpy.setBackgroundColor(Color.parseColor("#aaa827"));
        Button button10 = new Button(this);
        this.iswmzzbnth = button10;
        button10.setLayoutParams(new LinearLayout.LayoutParams(556, 795));
        this.iswmzzbnth.setPadding(2, 55, 138, 23);
        linearLayout.addView(this.iswmzzbnth);
        this.iswmzzbnth.setBackgroundColor(Color.parseColor("#c487d9"));
        DatePicker datePicker14 = new DatePicker(this);
        this.dfpuihrgab = datePicker14;
        datePicker14.setLayoutParams(new LinearLayout.LayoutParams(1854, TypedValues.CycleType.TYPE_VISIBILITY));
        this.dfpuihrgab.setPadding(23, 47, 143, 45);
        linearLayout.addView(this.dfpuihrgab);
        this.dfpuihrgab.setBackgroundColor(Color.parseColor("#61831e"));
        RelativeLayout relativeLayout10 = new RelativeLayout(this);
        this.bencmjntzf = relativeLayout10;
        relativeLayout10.setLayoutParams(new LinearLayout.LayoutParams(1480, 1600));
        this.bencmjntzf.setPadding(65, 14, 121, 155);
        linearLayout.addView(this.bencmjntzf);
        this.bencmjntzf.setBackgroundColor(Color.parseColor("#5be789"));
        Switch r28 = new Switch(this);
        this.mezscneajs = r28;
        r28.setLayoutParams(new LinearLayout.LayoutParams(281, 389));
        this.mezscneajs.setPadding(73, 20, 180, 154);
        linearLayout.addView(this.mezscneajs);
        this.mezscneajs.setBackgroundColor(Color.parseColor("#c37531"));
        SeekBar seekBar6 = new SeekBar(this);
        this.xozqwfugkf = seekBar6;
        seekBar6.setLayoutParams(new LinearLayout.LayoutParams(1617, 364));
        this.xozqwfugkf.setPadding(139, 50, 29, 143);
        linearLayout.addView(this.xozqwfugkf);
        this.xozqwfugkf.setBackgroundColor(Color.parseColor("#8f47d9"));
        ProgressBar progressBar10 = new ProgressBar(this);
        this.hxijpurcwy = progressBar10;
        progressBar10.setLayoutParams(new LinearLayout.LayoutParams(719, 71));
        this.hxijpurcwy.setPadding(105, 91, 90, 135);
        linearLayout.addView(this.hxijpurcwy);
        this.hxijpurcwy.setBackgroundColor(Color.parseColor("#6cff9f"));
        RelativeLayout relativeLayout11 = new RelativeLayout(this);
        this.qnrdsbwivc = relativeLayout11;
        relativeLayout11.setLayoutParams(new LinearLayout.LayoutParams(1771, 398));
        this.qnrdsbwivc.setPadding(5, 144, 180, 16);
        linearLayout.addView(this.qnrdsbwivc);
        this.qnrdsbwivc.setBackgroundColor(Color.parseColor("#dd9492"));
        ViewFlipper viewFlipper5 = new ViewFlipper(this);
        this.jzfyfymhbt = viewFlipper5;
        viewFlipper5.setLayoutParams(new LinearLayout.LayoutParams(250, 717));
        this.jzfyfymhbt.setPadding(72, 151, 189, 29);
        linearLayout.addView(this.jzfyfymhbt);
        this.jzfyfymhbt.setBackgroundColor(Color.parseColor("#a7d0b5"));
        FrameLayout frameLayout7 = new FrameLayout(this);
        this.vnwvfwfwct = frameLayout7;
        frameLayout7.setLayoutParams(new LinearLayout.LayoutParams(1240, 559));
        this.vnwvfwfwct.setPadding(191, 54, 197, 142);
        linearLayout.addView(this.vnwvfwfwct);
        this.vnwvfwfwct.setBackgroundColor(Color.parseColor("#e6ab08"));
        TableLayout tableLayout5 = new TableLayout(this);
        this.ptcvnyrcgp = tableLayout5;
        tableLayout5.setLayoutParams(new LinearLayout.LayoutParams(1688, 1091));
        this.ptcvnyrcgp.setPadding(117, 16, 183, 114);
        linearLayout.addView(this.ptcvnyrcgp);
        this.ptcvnyrcgp.setBackgroundColor(Color.parseColor("#4d2144"));
        ImageView imageView14 = new ImageView(this);
        this.cqfyyhlsth = imageView14;
        imageView14.setLayoutParams(new LinearLayout.LayoutParams(592, 1601));
        this.cqfyyhlsth.setPadding(114, 180, 73, 178);
        linearLayout.addView(this.cqfyyhlsth);
        this.cqfyyhlsth.setBackgroundColor(Color.parseColor("#3f1318"));
        RadioButton radioButton13 = new RadioButton(this);
        this.agdzwjiiqa = radioButton13;
        radioButton13.setLayoutParams(new LinearLayout.LayoutParams(1737, 256));
        this.agdzwjiiqa.setPadding(179, 150, 73, 51);
        linearLayout.addView(this.agdzwjiiqa);
        this.agdzwjiiqa.setBackgroundColor(Color.parseColor("#457a3a"));
        GridView gridView5 = new GridView(this);
        this.dglxculgjq = gridView5;
        gridView5.setLayoutParams(new LinearLayout.LayoutParams(1082, 1136));
        this.dglxculgjq.setPadding(11, 75, 139, 39);
        linearLayout.addView(this.dglxculgjq);
        this.dglxculgjq.setBackgroundColor(Color.parseColor("#eb1e33"));
        Button button11 = new Button(this);
        this.kdxcoldixm = button11;
        button11.setLayoutParams(new LinearLayout.LayoutParams(1341, 360));
        this.kdxcoldixm.setPadding(23, 189, 56, 193);
        linearLayout.addView(this.kdxcoldixm);
        this.kdxcoldixm.setBackgroundColor(Color.parseColor("#e3ea72"));
        FrameLayout frameLayout8 = new FrameLayout(this);
        this.drfhdyueya = frameLayout8;
        frameLayout8.setLayoutParams(new LinearLayout.LayoutParams(417, 1443));
        this.drfhdyueya.setPadding(87, 1, 49, 148);
        linearLayout.addView(this.drfhdyueya);
        this.drfhdyueya.setBackgroundColor(Color.parseColor("#33aa71"));
        CheckBox checkBox11 = new CheckBox(this);
        this.gypzdbfunt = checkBox11;
        checkBox11.setLayoutParams(new LinearLayout.LayoutParams(1735, 1540));
        this.gypzdbfunt.setPadding(56, 48, 154, 39);
        linearLayout.addView(this.gypzdbfunt);
        this.gypzdbfunt.setBackgroundColor(Color.parseColor("#5b8dac"));
        SeekBar seekBar7 = new SeekBar(this);
        this.oqxxpvyxfd = seekBar7;
        seekBar7.setLayoutParams(new LinearLayout.LayoutParams(1665, 907));
        this.oqxxpvyxfd.setPadding(30, 73, 138, 39);
        linearLayout.addView(this.oqxxpvyxfd);
        this.oqxxpvyxfd.setBackgroundColor(Color.parseColor("#8c2031"));
        SeekBar seekBar8 = new SeekBar(this);
        this.xecxegrnkd = seekBar8;
        seekBar8.setLayoutParams(new LinearLayout.LayoutParams(1805, 666));
        this.xecxegrnkd.setPadding(38, 17, 102, 96);
        linearLayout.addView(this.xecxegrnkd);
        this.xecxegrnkd.setBackgroundColor(Color.parseColor("#6d966b"));
        ListView listView8 = new ListView(this);
        this.lmetkvabng = listView8;
        listView8.setLayoutParams(new LinearLayout.LayoutParams(1800, 1825));
        this.lmetkvabng.setPadding(9, 101, 6, 185);
        linearLayout.addView(this.lmetkvabng);
        this.lmetkvabng.setBackgroundColor(Color.parseColor("#f7423b"));
        Button button12 = new Button(this);
        this.jptyleqwja = button12;
        button12.setLayoutParams(new LinearLayout.LayoutParams(246, 1738));
        this.jptyleqwja.setPadding(28, 38, 40, PictureConfig.CHOOSE_REQUEST);
        linearLayout.addView(this.jptyleqwja);
        this.jptyleqwja.setBackgroundColor(Color.parseColor("#d5bb5f"));
        ToggleButton toggleButton6 = new ToggleButton(this);
        this.esklcalqkw = toggleButton6;
        toggleButton6.setLayoutParams(new LinearLayout.LayoutParams(615, 570));
        this.esklcalqkw.setPadding(108, 143, 1, 176);
        linearLayout.addView(this.esklcalqkw);
        this.esklcalqkw.setBackgroundColor(Color.parseColor("#097494"));
        RadioButton radioButton14 = new RadioButton(this);
        this.ofgdzkcyxx = radioButton14;
        radioButton14.setLayoutParams(new LinearLayout.LayoutParams(GattClient.STATE_READ_DEVICE_INFO, 1165));
        this.ofgdzkcyxx.setPadding(191, 148, 51, 179);
        linearLayout.addView(this.ofgdzkcyxx);
        this.ofgdzkcyxx.setBackgroundColor(Color.parseColor("#afdc14"));
        Switch r29 = new Switch(this);
        this.cephufvuem = r29;
        r29.setLayoutParams(new LinearLayout.LayoutParams(1166, 581));
        this.cephufvuem.setPadding(165, 18, 57, 134);
        linearLayout.addView(this.cephufvuem);
        this.cephufvuem.setBackgroundColor(Color.parseColor("#54d1da"));
        TextView textView6 = new TextView(this);
        this.rlimxmscnx = textView6;
        textView6.setLayoutParams(new LinearLayout.LayoutParams(1368, 1767));
        this.rlimxmscnx.setPadding(197, 118, 158, 55);
        linearLayout.addView(this.rlimxmscnx);
        this.rlimxmscnx.setBackgroundColor(Color.parseColor("#1c60c0"));
        ListView listView9 = new ListView(this);
        this.atsadywtnm = listView9;
        listView9.setLayoutParams(new LinearLayout.LayoutParams(916, 298));
        this.atsadywtnm.setPadding(3, 44, 28, 54);
        linearLayout.addView(this.atsadywtnm);
        this.atsadywtnm.setBackgroundColor(Color.parseColor("#9bb84a"));
        ViewFlipper viewFlipper6 = new ViewFlipper(this);
        this.ggpylvdcqr = viewFlipper6;
        viewFlipper6.setLayoutParams(new LinearLayout.LayoutParams(1065, 181));
        this.ggpylvdcqr.setPadding(BDLocation.TypeServerError, 110, 57, 69);
        linearLayout.addView(this.ggpylvdcqr);
        this.ggpylvdcqr.setBackgroundColor(Color.parseColor("#0a2941"));
        TextView textView7 = new TextView(this);
        this.tsoatnoasa = textView7;
        textView7.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.MotionType.TYPE_ANIMATE_RELATIVE_TO, 1131));
        this.tsoatnoasa.setPadding(113, 189, 20, 182);
        linearLayout.addView(this.tsoatnoasa);
        this.tsoatnoasa.setBackgroundColor(Color.parseColor("#e1d267"));
        ListView listView10 = new ListView(this);
        this.tjorajcbus = listView10;
        listView10.setLayoutParams(new LinearLayout.LayoutParams(1277, 1134));
        this.tjorajcbus.setPadding(72, 49, 109, 66);
        linearLayout.addView(this.tjorajcbus);
        this.tjorajcbus.setBackgroundColor(Color.parseColor("#5b051f"));
        TableLayout tableLayout6 = new TableLayout(this);
        this.mibrzvxael = tableLayout6;
        tableLayout6.setLayoutParams(new LinearLayout.LayoutParams(1970, 1206));
        this.mibrzvxael.setPadding(154, 104, 171, 100);
        linearLayout.addView(this.mibrzvxael);
        this.mibrzvxael.setBackgroundColor(Color.parseColor("#cb8b7c"));
        FrameLayout frameLayout9 = new FrameLayout(this);
        this.whprlbfcbr = frameLayout9;
        frameLayout9.setLayoutParams(new LinearLayout.LayoutParams(1815, 452));
        this.whprlbfcbr.setPadding(92, 85, 0, 33);
        linearLayout.addView(this.whprlbfcbr);
        this.whprlbfcbr.setBackgroundColor(Color.parseColor("#582221"));
        Button button13 = new Button(this);
        this.binzphditv = button13;
        button13.setLayoutParams(new LinearLayout.LayoutParams(1134, 1823));
        this.binzphditv.setPadding(99, 32, 104, 148);
        linearLayout.addView(this.binzphditv);
        this.binzphditv.setBackgroundColor(Color.parseColor("#912d77"));
        TableLayout tableLayout7 = new TableLayout(this);
        this.piqlirxgqw = tableLayout7;
        tableLayout7.setLayoutParams(new LinearLayout.LayoutParams(360, 418));
        this.piqlirxgqw.setPadding(195, 197, 191, 114);
        linearLayout.addView(this.piqlirxgqw);
        this.piqlirxgqw.setBackgroundColor(Color.parseColor("#fe5aca"));
        TimePicker timePicker7 = new TimePicker(this);
        this.mhzyelofbe = timePicker7;
        timePicker7.setLayoutParams(new LinearLayout.LayoutParams(732, CropImage.PICK_IMAGE_PERMISSIONS_REQUEST_CODE));
        this.mhzyelofbe.setPadding(92, 195, 0, 103);
        linearLayout.addView(this.mhzyelofbe);
        this.mhzyelofbe.setBackgroundColor(Color.parseColor("#8c2d8e"));
        LinearLayout linearLayout15 = new LinearLayout(this);
        this.sgfjebakqw = linearLayout15;
        linearLayout15.setLayoutParams(new LinearLayout.LayoutParams(1095, 846));
        this.sgfjebakqw.setPadding(156, 34, 195, 3);
        linearLayout.addView(this.sgfjebakqw);
        this.sgfjebakqw.setBackgroundColor(Color.parseColor("#5a16f1"));
        CheckBox checkBox12 = new CheckBox(this);
        this.nnwcgzwhbs = checkBox12;
        checkBox12.setLayoutParams(new LinearLayout.LayoutParams(1530, 1612));
        this.nnwcgzwhbs.setPadding(119, BDLocation.TypeNetWorkLocation, 62, 12);
        linearLayout.addView(this.nnwcgzwhbs);
        this.nnwcgzwhbs.setBackgroundColor(Color.parseColor("#4a2311"));
        ScrollView scrollView13 = new ScrollView(this);
        this.rxasqqiqlq = scrollView13;
        scrollView13.setLayoutParams(new LinearLayout.LayoutParams(1370, 200));
        this.rxasqqiqlq.setPadding(67, 170, 101, 1);
        linearLayout.addView(this.rxasqqiqlq);
        this.rxasqqiqlq.setBackgroundColor(Color.parseColor("#85b40f"));
        Button button14 = new Button(this);
        this.tsnvsjekjr = button14;
        button14.setLayoutParams(new LinearLayout.LayoutParams(1289, 351));
        this.tsnvsjekjr.setPadding(24, 99, 117, 81);
        linearLayout.addView(this.tsnvsjekjr);
        this.tsnvsjekjr.setBackgroundColor(Color.parseColor("#4e190a"));
        RadioButton radioButton15 = new RadioButton(this);
        this.roxcupaqhf = radioButton15;
        radioButton15.setLayoutParams(new LinearLayout.LayoutParams(331, 728));
        this.roxcupaqhf.setPadding(108, 131, 186, 174);
        linearLayout.addView(this.roxcupaqhf);
        this.roxcupaqhf.setBackgroundColor(Color.parseColor("#31d3c3"));
        RatingBar ratingBar11 = new RatingBar(this);
        this.lfjgdrqmjh = ratingBar11;
        ratingBar11.setLayoutParams(new LinearLayout.LayoutParams(123, 94));
        this.lfjgdrqmjh.setPadding(132, 143, 185, 74);
        linearLayout.addView(this.lfjgdrqmjh);
        this.lfjgdrqmjh.setBackgroundColor(Color.parseColor("#5afe77"));
        RatingBar ratingBar12 = new RatingBar(this);
        this.nltwysvedk = ratingBar12;
        ratingBar12.setLayoutParams(new LinearLayout.LayoutParams(805, 34));
        this.nltwysvedk.setPadding(198, 143, 176, 155);
        linearLayout.addView(this.nltwysvedk);
        this.nltwysvedk.setBackgroundColor(Color.parseColor("#01de29"));
        SeekBar seekBar9 = new SeekBar(this);
        this.agfwvvxyoy = seekBar9;
        seekBar9.setLayoutParams(new LinearLayout.LayoutParams(5, 195));
        this.agfwvvxyoy.setPadding(187, BDLocation.TypeNetWorkLocation, 123, 6);
        linearLayout.addView(this.agfwvvxyoy);
        this.agfwvvxyoy.setBackgroundColor(Color.parseColor("#da8ec2"));
        ImageView imageView15 = new ImageView(this);
        this.dqpmmjertr = imageView15;
        imageView15.setLayoutParams(new LinearLayout.LayoutParams(1172, 1395));
        this.dqpmmjertr.setPadding(49, 193, BDLocation.TypeCoarseLocation, 14);
        linearLayout.addView(this.dqpmmjertr);
        this.dqpmmjertr.setBackgroundColor(Color.parseColor("#93ce13"));
        RatingBar ratingBar13 = new RatingBar(this);
        this.kymxhzabft = ratingBar13;
        ratingBar13.setLayoutParams(new LinearLayout.LayoutParams(1963, 944));
        this.kymxhzabft.setPadding(150, 90, 194, 112);
        linearLayout.addView(this.kymxhzabft);
        this.kymxhzabft.setBackgroundColor(Color.parseColor("#f04bb6"));
        Button button15 = new Button(this);
        this.iiodkuczut = button15;
        button15.setLayoutParams(new LinearLayout.LayoutParams(617, 804));
        this.iiodkuczut.setPadding(137, 69, 67, 4);
        linearLayout.addView(this.iiodkuczut);
        this.iiodkuczut.setBackgroundColor(Color.parseColor("#d853cd"));
        Button button16 = new Button(this);
        this.osxvddbbgb = button16;
        button16.setLayoutParams(new LinearLayout.LayoutParams(40, 450));
        this.osxvddbbgb.setPadding(42, 44, 26, 154);
        linearLayout.addView(this.osxvddbbgb);
        this.osxvddbbgb.setBackgroundColor(Color.parseColor("#c8982a"));
        LinearLayout linearLayout16 = new LinearLayout(this);
        this.kzktuxrdod = linearLayout16;
        linearLayout16.setLayoutParams(new LinearLayout.LayoutParams(1044, 1925));
        this.kzktuxrdod.setPadding(194, 3, 189, 111);
        linearLayout.addView(this.kzktuxrdod);
        this.kzktuxrdod.setBackgroundColor(Color.parseColor("#379eab"));
        RadioButton radioButton16 = new RadioButton(this);
        this.vxsjytmxws = radioButton16;
        radioButton16.setLayoutParams(new LinearLayout.LayoutParams(915, 14));
        this.vxsjytmxws.setPadding(PictureConfig.CHOOSE_REQUEST, 171, 122, 10);
        linearLayout.addView(this.vxsjytmxws);
        this.vxsjytmxws.setBackgroundColor(Color.parseColor("#cc7f60"));
        TimePicker timePicker8 = new TimePicker(this);
        this.ojtzhczydr = timePicker8;
        timePicker8.setLayoutParams(new LinearLayout.LayoutParams(697, 833));
        this.ojtzhczydr.setPadding(178, 75, 134, 128);
        linearLayout.addView(this.ojtzhczydr);
        this.ojtzhczydr.setBackgroundColor(Color.parseColor("#7189dd"));
    }
}
