package com.device.watch.com.device.watch.ieebeyvula;

import android.app.Activity;
import android.graphics.Color;
import android.os.Bundle;
import android.view.ViewGroup;
import android.widget.CheckBox;
import android.widget.DatePicker;
import android.widget.EditText;
import android.widget.FrameLayout;
import android.widget.GridView;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ListView;
import android.widget.ProgressBar;
import android.widget.RadioButton;
import android.widget.RatingBar;
import android.widget.RelativeLayout;
import android.widget.ScrollView;
import android.widget.SeekBar;
import android.widget.Switch;
import android.widget.TableLayout;
import android.widget.TextView;
import android.widget.TimePicker;
import android.widget.ToggleButton;
import android.widget.ViewFlipper;
import com.baidu.location.BDLocation;
import com.google.android.gms.common.ConnectionResult;
import com.luck.picture.lib.config.PictureConfig;
import com.realsil.sdk.core.bluetooth.connection.le.GattClient;
import okhttp3.internal.ws.WebSocketProtocol;

/* loaded from: classes.dex */
public class LzmisyjvsybActivity extends Activity {
    FrameLayout ameramtgys;
    Switch atjgdgfkse;
    CheckBox ayyubqjhiq;
    ToggleButton bfpxsjhlgw;
    RelativeLayout bjtovvuuwr;
    TextView cajszystmw;
    TimePicker camvqziqge;
    CheckBox cdirjunoic;
    RadioButton cqqgftfbbv;
    SeekBar decqmjrjls;
    TextView desfrewddp;
    RatingBar dikugoasws;
    Switch dudijvanhk;
    RatingBar eamkuvlxoo;
    ToggleButton fetsvbwbds;
    RatingBar fkmqwfvasd;
    TimePicker fxrohhhesl;
    TimePicker gekzagzopy;
    ProgressBar geyoobesew;
    ImageView hjkrqymzvg;
    SeekBar hlebnvqqpr;
    TextView huzgafzlmj;
    CheckBox jmugdmpkls;
    ProgressBar jomrzlrlas;
    ListView jroztfarlv;
    FrameLayout kcnbupoigu;
    DatePicker kdxocaunlw;
    TimePicker krrynuasii;
    ToggleButton lbqtncvwuz;
    TextView lglwcwsbve;
    RadioButton mgqdwodflb;
    CheckBox mnxbrmtnhl;
    EditText nrzsfajonl;
    LinearLayout ntwgzavsnl;
    TableLayout nvykstjyac;
    TimePicker otyyjykmvg;
    RelativeLayout ozgoihpley;
    ProgressBar pgcklgmhsm;
    TimePicker pkiladglbd;
    ScrollView qzcmcszaxv;
    ProgressBar rlzvbqhrur;
    EditText sejyfigncr;
    ListView szpfaqvndr;
    RatingBar tqzwrmrgcr;
    TextView tunnuirrif;
    ScrollView tvmbmffgmc;
    GridView txmpxsrcuj;
    TableLayout uitcdgvdfy;
    ImageView uljrdknjrr;
    ViewFlipper uyufwzhikq;
    EditText uyxfxlgzjs;
    CheckBox vkbsimiqwd;
    TimePicker vlbekvjxsh;
    EditText wtwwqfcfwr;
    LinearLayout xllkjzcplo;
    ScrollView xuovisclik;
    ListView xveivsljfa;
    CheckBox yjvrdoqugu;
    CheckBox zxviuzcnlj;

    @Override // android.app.Activity
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        LinearLayout linearLayout = new LinearLayout(this);
        setContentView(linearLayout);
        linearLayout.setLayoutParams(new ViewGroup.LayoutParams(-1, -1));
        linearLayout.setOrientation(1);
        linearLayout.setBackgroundColor(Color.parseColor("#fa2ce8"));
        RelativeLayout relativeLayout = new RelativeLayout(this);
        this.ozgoihpley = relativeLayout;
        relativeLayout.setLayoutParams(new LinearLayout.LayoutParams(1582, 232));
        this.ozgoihpley.setPadding(130, 159, 150, 61);
        linearLayout.addView(this.ozgoihpley);
        this.ozgoihpley.setBackgroundColor(Color.parseColor("#0f2c90"));
        SeekBar seekBar = new SeekBar(this);
        this.hlebnvqqpr = seekBar;
        seekBar.setLayoutParams(new LinearLayout.LayoutParams(362, 1584));
        this.hlebnvqqpr.setPadding(189, 196, 124, 8);
        linearLayout.addView(this.hlebnvqqpr);
        this.hlebnvqqpr.setBackgroundColor(Color.parseColor("#a866f6"));
        TextView textView = new TextView(this);
        this.tunnuirrif = textView;
        textView.setLayoutParams(new LinearLayout.LayoutParams(12, 1));
        this.tunnuirrif.setPadding(180, 172, 152, 86);
        linearLayout.addView(this.tunnuirrif);
        this.tunnuirrif.setBackgroundColor(Color.parseColor("#5bbbe5"));
        ListView listView = new ListView(this);
        this.jroztfarlv = listView;
        listView.setLayoutParams(new LinearLayout.LayoutParams(GattClient.STATE_PREPARE_CONNECTING, 645));
        this.jroztfarlv.setPadding(136, 180, 80, 66);
        linearLayout.addView(this.jroztfarlv);
        this.jroztfarlv.setBackgroundColor(Color.parseColor("#99d395"));
        TableLayout tableLayout = new TableLayout(this);
        this.uitcdgvdfy = tableLayout;
        tableLayout.setLayoutParams(new LinearLayout.LayoutParams(1767, 461));
        this.uitcdgvdfy.setPadding(21, 78, 143, 169);
        linearLayout.addView(this.uitcdgvdfy);
        this.uitcdgvdfy.setBackgroundColor(Color.parseColor("#147fab"));
        CheckBox checkBox = new CheckBox(this);
        this.cdirjunoic = checkBox;
        checkBox.setLayoutParams(new LinearLayout.LayoutParams(290, 774));
        this.cdirjunoic.setPadding(127, 94, 73, 43);
        linearLayout.addView(this.cdirjunoic);
        this.cdirjunoic.setBackgroundColor(Color.parseColor("#f52c13"));
        CheckBox checkBox2 = new CheckBox(this);
        this.ayyubqjhiq = checkBox2;
        checkBox2.setLayoutParams(new LinearLayout.LayoutParams(404, 1853));
        this.ayyubqjhiq.setPadding(85, 51, 83, 96);
        linearLayout.addView(this.ayyubqjhiq);
        this.ayyubqjhiq.setBackground(new Duuxijdndbn());
        RadioButton radioButton = new RadioButton(this);
        this.mgqdwodflb = radioButton;
        radioButton.setLayoutParams(new LinearLayout.LayoutParams(76, 1036));
        this.mgqdwodflb.setPadding(28, 124, 138, 109);
        linearLayout.addView(this.mgqdwodflb);
        this.mgqdwodflb.setBackgroundColor(Color.parseColor("#a73d97"));
        ScrollView scrollView = new ScrollView(this);
        this.qzcmcszaxv = scrollView;
        scrollView.setLayoutParams(new LinearLayout.LayoutParams(801, 430));
        this.qzcmcszaxv.setPadding(14, 16, 43, 56);
        linearLayout.addView(this.qzcmcszaxv);
        this.qzcmcszaxv.setBackgroundColor(Color.parseColor("#5491c9"));
        RatingBar ratingBar = new RatingBar(this);
        this.eamkuvlxoo = ratingBar;
        ratingBar.setLayoutParams(new LinearLayout.LayoutParams(1407, 477));
        this.eamkuvlxoo.setPadding(194, 100, 67, 64);
        linearLayout.addView(this.eamkuvlxoo);
        this.eamkuvlxoo.setBackgroundColor(Color.parseColor("#7ef76a"));
        RelativeLayout relativeLayout2 = new RelativeLayout(this);
        this.bjtovvuuwr = relativeLayout2;
        relativeLayout2.setLayoutParams(new LinearLayout.LayoutParams(1146, 969));
        this.bjtovvuuwr.setPadding(137, 147, 171, 56);
        linearLayout.addView(this.bjtovvuuwr);
        this.bjtovvuuwr.setBackgroundColor(Color.parseColor("#7cc949"));
        Switch r3 = new Switch(this);
        this.atjgdgfkse = r3;
        r3.setLayoutParams(new LinearLayout.LayoutParams(1773, 460));
        this.atjgdgfkse.setPadding(WebSocketProtocol.PAYLOAD_SHORT, 52, 178, 125);
        linearLayout.addView(this.atjgdgfkse);
        this.atjgdgfkse.setBackgroundColor(Color.parseColor("#a5e1aa"));
        EditText editText = new EditText(this);
        this.sejyfigncr = editText;
        editText.setLayoutParams(new LinearLayout.LayoutParams(1418, 1532));
        this.sejyfigncr.setPadding(140, 4, 182, 166);
        linearLayout.addView(this.sejyfigncr);
        this.sejyfigncr.setBackgroundColor(Color.parseColor("#f9bd35"));
        RatingBar ratingBar2 = new RatingBar(this);
        this.fkmqwfvasd = ratingBar2;
        ratingBar2.setLayoutParams(new LinearLayout.LayoutParams(1067, 759));
        this.fkmqwfvasd.setPadding(173, 17, 85, 55);
        linearLayout.addView(this.fkmqwfvasd);
        this.fkmqwfvasd.setBackgroundColor(Color.parseColor("#91d06b"));
        TimePicker timePicker = new TimePicker(this);
        this.vlbekvjxsh = timePicker;
        timePicker.setLayoutParams(new LinearLayout.LayoutParams(204, 1652));
        this.vlbekvjxsh.setPadding(8, 177, 197, 35);
        linearLayout.addView(this.vlbekvjxsh);
        this.vlbekvjxsh.setBackgroundColor(Color.parseColor("#3153b4"));
        ProgressBar progressBar = new ProgressBar(this);
        this.jomrzlrlas = progressBar;
        progressBar.setLayoutParams(new LinearLayout.LayoutParams(683, 1693));
        this.jomrzlrlas.setPadding(125, 89, 196, 128);
        linearLayout.addView(this.jomrzlrlas);
        this.jomrzlrlas.setBackgroundColor(Color.parseColor("#72fce1"));
        TimePicker timePicker2 = new TimePicker(this);
        this.otyyjykmvg = timePicker2;
        timePicker2.setLayoutParams(new LinearLayout.LayoutParams(869, 1762));
        this.otyyjykmvg.setPadding(111, 2, 12, 83);
        linearLayout.addView(this.otyyjykmvg);
        this.otyyjykmvg.setBackgroundColor(Color.parseColor("#65f5c9"));
        RadioButton radioButton2 = new RadioButton(this);
        this.cqqgftfbbv = radioButton2;
        radioButton2.setLayoutParams(new LinearLayout.LayoutParams(246, 225));
        this.cqqgftfbbv.setPadding(77, 158, 55, 131);
        linearLayout.addView(this.cqqgftfbbv);
        this.cqqgftfbbv.setBackgroundColor(Color.parseColor("#cd5456"));
        ImageView imageView = new ImageView(this);
        this.uljrdknjrr = imageView;
        imageView.setLayoutParams(new LinearLayout.LayoutParams(821, 970));
        this.uljrdknjrr.setPadding(141, 1, 67, 52);
        linearLayout.addView(this.uljrdknjrr);
        this.uljrdknjrr.setBackgroundColor(Color.parseColor("#20b96f"));
        GridView gridView = new GridView(this);
        this.txmpxsrcuj = gridView;
        gridView.setLayoutParams(new LinearLayout.LayoutParams(1618, 1894));
        this.txmpxsrcuj.setPadding(8, 27, 11, 33);
        linearLayout.addView(this.txmpxsrcuj);
        this.txmpxsrcuj.setBackgroundColor(Color.parseColor("#9d63f9"));
        ToggleButton toggleButton = new ToggleButton(this);
        this.bfpxsjhlgw = toggleButton;
        toggleButton.setLayoutParams(new LinearLayout.LayoutParams(261, 319));
        this.bfpxsjhlgw.setPadding(140, 154, BDLocation.TypeServerDecryptError, 44);
        linearLayout.addView(this.bfpxsjhlgw);
        this.bfpxsjhlgw.setBackgroundColor(Color.parseColor("#6c35db"));
        CheckBox checkBox3 = new CheckBox(this);
        this.zxviuzcnlj = checkBox3;
        checkBox3.setLayoutParams(new LinearLayout.LayoutParams(156, 1858));
        this.zxviuzcnlj.setPadding(112, 157, 13, 50);
        linearLayout.addView(this.zxviuzcnlj);
        this.zxviuzcnlj.setBackgroundColor(Color.parseColor("#487bb0"));
        LinearLayout linearLayout2 = new LinearLayout(this);
        this.ntwgzavsnl = linearLayout2;
        linearLayout2.setLayoutParams(new LinearLayout.LayoutParams(1592, 680));
        this.ntwgzavsnl.setPadding(BDLocation.TypeServerDecryptError, 12, 44, 143);
        linearLayout.addView(this.ntwgzavsnl);
        this.ntwgzavsnl.setBackgroundColor(Color.parseColor("#70a05b"));
        EditText editText2 = new EditText(this);
        this.nrzsfajonl = editText2;
        editText2.setLayoutParams(new LinearLayout.LayoutParams(1485, 684));
        this.nrzsfajonl.setPadding(WebSocketProtocol.PAYLOAD_SHORT, 148, 36, 73);
        linearLayout.addView(this.nrzsfajonl);
        this.nrzsfajonl.setBackgroundColor(Color.parseColor("#6520b1"));
        ScrollView scrollView2 = new ScrollView(this);
        this.xuovisclik = scrollView2;
        scrollView2.setLayoutParams(new LinearLayout.LayoutParams(1501, 239));
        this.xuovisclik.setPadding(171, 23, 195, 159);
        linearLayout.addView(this.xuovisclik);
        this.xuovisclik.setBackgroundColor(Color.parseColor("#69bcc2"));
        Switch r2 = new Switch(this);
        this.dudijvanhk = r2;
        r2.setLayoutParams(new LinearLayout.LayoutParams(407, 1727));
        this.dudijvanhk.setPadding(175, 56, 177, 129);
        linearLayout.addView(this.dudijvanhk);
        this.dudijvanhk.setBackgroundColor(Color.parseColor("#6a99a5"));
        TimePicker timePicker3 = new TimePicker(this);
        this.pkiladglbd = timePicker3;
        timePicker3.setLayoutParams(new LinearLayout.LayoutParams(1321, PictureConfig.REQUEST_CAMERA));
        this.pkiladglbd.setPadding(196, 44, 8, 19);
        linearLayout.addView(this.pkiladglbd);
        this.pkiladglbd.setBackgroundColor(Color.parseColor("#5121aa"));
        TextView textView2 = new TextView(this);
        this.huzgafzlmj = textView2;
        textView2.setLayoutParams(new LinearLayout.LayoutParams(1224, 709));
        this.huzgafzlmj.setPadding(39, 5, 105, 187);
        linearLayout.addView(this.huzgafzlmj);
        this.huzgafzlmj.setBackgroundColor(Color.parseColor("#c812ab"));
        TimePicker timePicker4 = new TimePicker(this);
        this.camvqziqge = timePicker4;
        timePicker4.setLayoutParams(new LinearLayout.LayoutParams(80, 1552));
        this.camvqziqge.setPadding(12, 41, 3, 129);
        linearLayout.addView(this.camvqziqge);
        this.camvqziqge.setBackgroundColor(Color.parseColor("#7ba038"));
        CheckBox checkBox4 = new CheckBox(this);
        this.jmugdmpkls = checkBox4;
        checkBox4.setLayoutParams(new LinearLayout.LayoutParams(1845, 1213));
        this.jmugdmpkls.setPadding(136, 168, 192, 149);
        linearLayout.addView(this.jmugdmpkls);
        this.jmugdmpkls.setBackgroundColor(Color.parseColor("#677468"));
        TextView textView3 = new TextView(this);
        this.cajszystmw = textView3;
        textView3.setLayoutParams(new LinearLayout.LayoutParams(556, 1398));
        this.cajszystmw.setPadding(108, 163, 125, 68);
        linearLayout.addView(this.cajszystmw);
        this.cajszystmw.setBackgroundColor(Color.parseColor("#989d83"));
        ImageView imageView2 = new ImageView(this);
        this.hjkrqymzvg = imageView2;
        imageView2.setLayoutParams(new LinearLayout.LayoutParams(1471, 518));
        this.hjkrqymzvg.setPadding(2, BDLocation.TypeNetWorkLocation, 70, 157);
        linearLayout.addView(this.hjkrqymzvg);
        this.hjkrqymzvg.setBackgroundColor(Color.parseColor("#ea9143"));
        EditText editText3 = new EditText(this);
        this.uyxfxlgzjs = editText3;
        editText3.setLayoutParams(new LinearLayout.LayoutParams(723, 207));
        this.uyxfxlgzjs.setPadding(15, 83, 36, 0);
        linearLayout.addView(this.uyxfxlgzjs);
        this.uyxfxlgzjs.setBackgroundColor(Color.parseColor("#969a11"));
        ListView listView2 = new ListView(this);
        this.szpfaqvndr = listView2;
        listView2.setLayoutParams(new LinearLayout.LayoutParams(1007, 482));
        this.szpfaqvndr.setPadding(76, 79, 196, 165);
        linearLayout.addView(this.szpfaqvndr);
        this.szpfaqvndr.setBackgroundColor(Color.parseColor("#ba3504"));
        CheckBox checkBox5 = new CheckBox(this);
        this.mnxbrmtnhl = checkBox5;
        checkBox5.setLayoutParams(new LinearLayout.LayoutParams(1748, 1392));
        this.mnxbrmtnhl.setPadding(137, 122, 54, 185);
        linearLayout.addView(this.mnxbrmtnhl);
        this.mnxbrmtnhl.setBackgroundColor(Color.parseColor("#7cbda6"));
        CheckBox checkBox6 = new CheckBox(this);
        this.yjvrdoqugu = checkBox6;
        checkBox6.setLayoutParams(new LinearLayout.LayoutParams(ConnectionResult.DRIVE_EXTERNAL_STORAGE_REQUIRED, 100));
        this.yjvrdoqugu.setPadding(104, 79, 22, 181);
        linearLayout.addView(this.yjvrdoqugu);
        this.yjvrdoqugu.setBackgroundColor(Color.parseColor("#741184"));
        SeekBar seekBar2 = new SeekBar(this);
        this.decqmjrjls = seekBar2;
        seekBar2.setLayoutParams(new LinearLayout.LayoutParams(809, 1659));
        this.decqmjrjls.setPadding(170, 133, 83, 0);
        linearLayout.addView(this.decqmjrjls);
        this.decqmjrjls.setBackgroundColor(Color.parseColor("#68ada3"));
        ProgressBar progressBar2 = new ProgressBar(this);
        this.geyoobesew = progressBar2;
        progressBar2.setLayoutParams(new LinearLayout.LayoutParams(1891, 1091));
        this.geyoobesew.setPadding(185, 190, 106, 5);
        linearLayout.addView(this.geyoobesew);
        this.geyoobesew.setBackgroundColor(Color.parseColor("#cbcd43"));
        EditText editText4 = new EditText(this);
        this.wtwwqfcfwr = editText4;
        editText4.setLayoutParams(new LinearLayout.LayoutParams(341, 456));
        this.wtwwqfcfwr.setPadding(99, 91, 198, 47);
        linearLayout.addView(this.wtwwqfcfwr);
        this.wtwwqfcfwr.setBackgroundColor(Color.parseColor("#ec2b00"));
        TextView textView4 = new TextView(this);
        this.desfrewddp = textView4;
        textView4.setLayoutParams(new LinearLayout.LayoutParams(1820, 1590));
        this.desfrewddp.setPadding(95, 11, 142, 48);
        linearLayout.addView(this.desfrewddp);
        this.desfrewddp.setBackgroundColor(Color.parseColor("#01fd65"));
        ProgressBar progressBar3 = new ProgressBar(this);
        this.rlzvbqhrur = progressBar3;
        progressBar3.setLayoutParams(new LinearLayout.LayoutParams(213, 1008));
        this.rlzvbqhrur.setPadding(190, 26, 179, 121);
        linearLayout.addView(this.rlzvbqhrur);
        this.rlzvbqhrur.setBackgroundColor(Color.parseColor("#de00f5"));
        ToggleButton toggleButton2 = new ToggleButton(this);
        this.fetsvbwbds = toggleButton2;
        toggleButton2.setLayoutParams(new LinearLayout.LayoutParams(506, 311));
        this.fetsvbwbds.setPadding(48, 135, 180, 67);
        linearLayout.addView(this.fetsvbwbds);
        this.fetsvbwbds.setBackgroundColor(Color.parseColor("#82cd4d"));
        ToggleButton toggleButton3 = new ToggleButton(this);
        this.lbqtncvwuz = toggleButton3;
        toggleButton3.setLayoutParams(new LinearLayout.LayoutParams(1873, 1981));
        this.lbqtncvwuz.setPadding(9, 118, 104, 67);
        linearLayout.addView(this.lbqtncvwuz);
        this.lbqtncvwuz.setBackgroundColor(Color.parseColor("#672ae9"));
        CheckBox checkBox7 = new CheckBox(this);
        this.vkbsimiqwd = checkBox7;
        checkBox7.setLayoutParams(new LinearLayout.LayoutParams(1674, 960));
        this.vkbsimiqwd.setPadding(159, 149, 192, 92);
        linearLayout.addView(this.vkbsimiqwd);
        this.vkbsimiqwd.setBackgroundColor(Color.parseColor("#3a76d5"));
        DatePicker datePicker = new DatePicker(this);
        this.kdxocaunlw = datePicker;
        datePicker.setLayoutParams(new LinearLayout.LayoutParams(1371, 1836));
        this.kdxocaunlw.setPadding(178, 163, 39, 134);
        linearLayout.addView(this.kdxocaunlw);
        this.kdxocaunlw.setBackgroundColor(Color.parseColor("#351309"));
        TimePicker timePicker5 = new TimePicker(this);
        this.krrynuasii = timePicker5;
        timePicker5.setLayoutParams(new LinearLayout.LayoutParams(1873, 1361));
        this.krrynuasii.setPadding(BDLocation.TypeServerError, 195, 87, 172);
        linearLayout.addView(this.krrynuasii);
        this.krrynuasii.setBackgroundColor(Color.parseColor("#4cddb1"));
        RatingBar ratingBar3 = new RatingBar(this);
        this.tqzwrmrgcr = ratingBar3;
        ratingBar3.setLayoutParams(new LinearLayout.LayoutParams(429, ConnectionResult.DRIVE_EXTERNAL_STORAGE_REQUIRED));
        this.tqzwrmrgcr.setPadding(82, 199, 73, 75);
        linearLayout.addView(this.tqzwrmrgcr);
        this.tqzwrmrgcr.setBackgroundColor(Color.parseColor("#b9432a"));
        FrameLayout frameLayout = new FrameLayout(this);
        this.kcnbupoigu = frameLayout;
        frameLayout.setLayoutParams(new LinearLayout.LayoutParams(1409, 1993));
        this.kcnbupoigu.setPadding(159, 175, 112, 14);
        linearLayout.addView(this.kcnbupoigu);
        this.kcnbupoigu.setBackgroundColor(Color.parseColor("#abe827"));
        TimePicker timePicker6 = new TimePicker(this);
        this.fxrohhhesl = timePicker6;
        timePicker6.setLayoutParams(new LinearLayout.LayoutParams(478, 141));
        this.fxrohhhesl.setPadding(45, 97, 75, 6);
        linearLayout.addView(this.fxrohhhesl);
        this.fxrohhhesl.setBackgroundColor(Color.parseColor("#cb2a93"));
        LinearLayout linearLayout3 = new LinearLayout(this);
        this.xllkjzcplo = linearLayout3;
        linearLayout3.setLayoutParams(new LinearLayout.LayoutParams(1715, 1961));
        this.xllkjzcplo.setPadding(87, 27, 94, 134);
        linearLayout.addView(this.xllkjzcplo);
        this.xllkjzcplo.setBackgroundColor(Color.parseColor("#feb2d6"));
        FrameLayout frameLayout2 = new FrameLayout(this);
        this.ameramtgys = frameLayout2;
        frameLayout2.setLayoutParams(new LinearLayout.LayoutParams(1692, 674));
        this.ameramtgys.setPadding(142, 197, 19, 141);
        linearLayout.addView(this.ameramtgys);
        this.ameramtgys.setBackgroundColor(Color.parseColor("#765ff8"));
        ProgressBar progressBar4 = new ProgressBar(this);
        this.pgcklgmhsm = progressBar4;
        progressBar4.setLayoutParams(new LinearLayout.LayoutParams(445, 261));
        this.pgcklgmhsm.setPadding(128, 139, 122, 68);
        linearLayout.addView(this.pgcklgmhsm);
        this.pgcklgmhsm.setBackgroundColor(Color.parseColor("#14139f"));
        TextView textView5 = new TextView(this);
        this.lglwcwsbve = textView5;
        textView5.setLayoutParams(new LinearLayout.LayoutParams(1714, 863));
        this.lglwcwsbve.setPadding(38, 54, 122, 183);
        linearLayout.addView(this.lglwcwsbve);
        this.lglwcwsbve.setBackgroundColor(Color.parseColor("#eb2885"));
        TimePicker timePicker7 = new TimePicker(this);
        this.gekzagzopy = timePicker7;
        timePicker7.setLayoutParams(new LinearLayout.LayoutParams(60, 1443));
        this.gekzagzopy.setPadding(62, 122, 179, 135);
        linearLayout.addView(this.gekzagzopy);
        this.gekzagzopy.setBackgroundColor(Color.parseColor("#992266"));
        ScrollView scrollView3 = new ScrollView(this);
        this.tvmbmffgmc = scrollView3;
        scrollView3.setLayoutParams(new LinearLayout.LayoutParams(450, 1164));
        this.tvmbmffgmc.setPadding(157, 131, 51, 5);
        linearLayout.addView(this.tvmbmffgmc);
        this.tvmbmffgmc.setBackgroundColor(Color.parseColor("#14b5a1"));
        RatingBar ratingBar4 = new RatingBar(this);
        this.dikugoasws = ratingBar4;
        ratingBar4.setLayoutParams(new LinearLayout.LayoutParams(506, 1434));
        this.dikugoasws.setPadding(31, 25, 49, 43);
        linearLayout.addView(this.dikugoasws);
        this.dikugoasws.setBackgroundColor(Color.parseColor("#3a457c"));
        TableLayout tableLayout2 = new TableLayout(this);
        this.nvykstjyac = tableLayout2;
        tableLayout2.setLayoutParams(new LinearLayout.LayoutParams(394, 433));
        this.nvykstjyac.setPadding(127, 139, 113, 45);
        linearLayout.addView(this.nvykstjyac);
        this.nvykstjyac.setBackgroundColor(Color.parseColor("#63dad7"));
        ViewFlipper viewFlipper = new ViewFlipper(this);
        this.uyufwzhikq = viewFlipper;
        viewFlipper.setLayoutParams(new LinearLayout.LayoutParams(615, 1957));
        this.uyufwzhikq.setPadding(92, 177, 4, 92);
        linearLayout.addView(this.uyufwzhikq);
        this.uyufwzhikq.setBackgroundColor(Color.parseColor("#f1ff1a"));
        ListView listView3 = new ListView(this);
        this.xveivsljfa = listView3;
        listView3.setLayoutParams(new LinearLayout.LayoutParams(2, 793));
        this.xveivsljfa.setPadding(159, 98, 91, 154);
        linearLayout.addView(this.xveivsljfa);
        this.xveivsljfa.setBackgroundColor(Color.parseColor("#ef1c75"));
    }
}
