package com.smartapp.a.xapnbegdlu;

import android.app.Activity;
import android.graphics.Color;
import android.os.Bundle;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.CheckBox;
import android.widget.DatePicker;
import android.widget.EditText;
import android.widget.FrameLayout;
import android.widget.GridView;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ListView;
import android.widget.ProgressBar;
import android.widget.RadioButton;
import android.widget.RatingBar;
import android.widget.RelativeLayout;
import android.widget.ScrollView;
import android.widget.SeekBar;
import android.widget.Spinner;
import android.widget.Switch;
import android.widget.TableLayout;
import android.widget.TextView;
import android.widget.TimePicker;
import android.widget.ToggleButton;
import android.widget.ViewFlipper;
import androidx.constraintlayout.core.motion.utils.TypedValues;
import androidx.core.view.PointerIconCompat;
import com.baidu.location.BDLocation;
import com.luck.picture.lib.config.PictureConfig;
import com.qcwireless.qcwatch.ui.home.healthy.vm.HealthyViewModel;
import com.realsil.sdk.bbpro.equalizer.AudioEq;
import okhttp3.internal.ws.WebSocketProtocol;

/* loaded from: classes3.dex */
public class FyhedoxgnneActivity extends Activity {
    Button adljtlfobk;
    RadioButton bdefshcytv;
    ViewFlipper bjnqilwhpg;
    ImageView bwokooadbf;
    ScrollView chjgdzoptd;
    CheckBox couoetbgtm;
    ProgressBar cphjizrwgn;
    DatePicker cyzidorxjs;
    ProgressBar doknaaifka;
    Spinner edsrhzjdqk;
    ImageView eobrhbugxr;
    ProgressBar eoextbbutc;
    TextView etoyrbcpnr;
    Button evvhwkxgjz;
    Button exnzdpbsjr;
    CheckBox ftnwuepbli;
    ViewFlipper fujujxsyka;
    SeekBar gcphsgpzrs;
    LinearLayout gzksjtdryg;
    ListView hlevnmdlid;
    ProgressBar hmzpxxnvew;
    ScrollView htemgduocb;
    ListView intejgbfct;
    TableLayout isffbtogah;
    TimePicker jxokxsqjkx;
    RatingBar jybecngtwq;
    DatePicker jziyxclucu;
    ScrollView kinqhnvcbp;
    ImageView kohngbzsni;
    GridView ktqvnzldbv;
    LinearLayout kuvjhpcnlq;
    ProgressBar kwmnobmdew;
    SeekBar kzixznsivb;
    ListView lhfgjdosfv;
    TimePicker lnujspncva;
    TimePicker lufanfaodn;
    FrameLayout mebvlkroso;
    Button mugzhbxodl;
    ProgressBar mvauywttau;
    Spinner ndhgqvhgpk;
    RelativeLayout otmnrimhbp;
    Switch pbtapyippv;
    Switch pdhlhbbirt;
    TextView pdkdpnrbvh;
    TimePicker pmrrgdgcxo;
    TableLayout psgmobsyku;
    ProgressBar putlyqaspa;
    RelativeLayout qfyvthkdac;
    GridView qntovulrde;
    Switch qwciylinve;
    RelativeLayout rbwsjhzeth;
    GridView rfvcgzmowu;
    LinearLayout rrrxjtadev;
    ToggleButton rxwngswotl;
    GridView szuypufatv;
    Switch tbzepvamkp;
    ToggleButton tgcippioqx;
    ViewFlipper tmkqvtthle;
    TableLayout tuxskwvvju;
    TimePicker txcpwdlukr;
    EditText utrbdqvwei;
    TimePicker uydhrbkswl;
    TableLayout viloinyemn;
    ViewFlipper vpqyjwhrpz;
    TableLayout vsrlilequz;
    ScrollView vvrjoxwbsb;
    FrameLayout vxedgphbld;
    GridView wbmvsxovoc;
    FrameLayout wbngmnrvqh;
    Spinner wedumetkam;
    ImageView wteokyslvv;
    RadioButton wzjzisucba;
    Spinner xyvrjispkv;
    SeekBar ykmispqotn;
    Button yuebnltxzb;
    LinearLayout zdrvwezfxj;
    GridView zebztbxjkf;
    TimePicker zjmjzdlasd;
    ProgressBar zmtfjhasgb;
    GridView zxqccodzog;
    ListView zyldsesywt;

    @Override // android.app.Activity
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        LinearLayout linearLayout = new LinearLayout(this);
        setContentView(linearLayout);
        linearLayout.setLayoutParams(new ViewGroup.LayoutParams(-1, -1));
        linearLayout.setOrientation(1);
        linearLayout.setBackgroundColor(Color.parseColor("#dcfc51"));
        ImageView imageView = new ImageView(this);
        this.bwokooadbf = imageView;
        imageView.setLayoutParams(new LinearLayout.LayoutParams(1673, 1545));
        this.bwokooadbf.setPadding(27, 11, 72, 159);
        linearLayout.addView(this.bwokooadbf);
        this.bwokooadbf.setBackgroundColor(Color.parseColor("#594c6a"));
        FrameLayout frameLayout = new FrameLayout(this);
        this.mebvlkroso = frameLayout;
        frameLayout.setLayoutParams(new LinearLayout.LayoutParams(647, 1502));
        this.mebvlkroso.setPadding(6, 13, 141, 33);
        linearLayout.addView(this.mebvlkroso);
        this.mebvlkroso.setBackgroundColor(Color.parseColor("#317b63"));
        ProgressBar progressBar = new ProgressBar(this);
        this.hmzpxxnvew = progressBar;
        progressBar.setLayoutParams(new LinearLayout.LayoutParams(407, 894));
        this.hmzpxxnvew.setPadding(140, 74, 71, 177);
        linearLayout.addView(this.hmzpxxnvew);
        this.hmzpxxnvew.setBackgroundColor(Color.parseColor("#f2f484"));
        FrameLayout frameLayout2 = new FrameLayout(this);
        this.vxedgphbld = frameLayout2;
        frameLayout2.setLayoutParams(new LinearLayout.LayoutParams(496, AudioEq.PARSE_EQ_DATA_LENGTH));
        this.vxedgphbld.setPadding(150, 23, 110, 184);
        linearLayout.addView(this.vxedgphbld);
        this.vxedgphbld.setBackgroundColor(Color.parseColor("#6f1608"));
        EditText editText = new EditText(this);
        this.utrbdqvwei = editText;
        editText.setLayoutParams(new LinearLayout.LayoutParams(1840, 1476));
        this.utrbdqvwei.setPadding(164, 192, 41, 119);
        linearLayout.addView(this.utrbdqvwei);
        this.utrbdqvwei.setBackgroundColor(Color.parseColor("#a2b454"));
        Switch r3 = new Switch(this);
        this.tbzepvamkp = r3;
        r3.setLayoutParams(new LinearLayout.LayoutParams(1749, TypedValues.TransitionType.TYPE_TRANSITION_FLAGS));
        this.tbzepvamkp.setPadding(174, 101, 33, 3);
        linearLayout.addView(this.tbzepvamkp);
        this.tbzepvamkp.setBackgroundColor(Color.parseColor("#92bada"));
        RelativeLayout relativeLayout = new RelativeLayout(this);
        this.rbwsjhzeth = relativeLayout;
        relativeLayout.setLayoutParams(new LinearLayout.LayoutParams(1504, 346));
        this.rbwsjhzeth.setPadding(40, 193, PictureConfig.CHOOSE_REQUEST, 128);
        linearLayout.addView(this.rbwsjhzeth);
        this.rbwsjhzeth.setBackgroundColor(Color.parseColor("#8a4e54"));
        Button button = new Button(this);
        this.mugzhbxodl = button;
        button.setLayoutParams(new LinearLayout.LayoutParams(1613, 433));
        this.mugzhbxodl.setPadding(157, 177, 21, 87);
        linearLayout.addView(this.mugzhbxodl);
        this.mugzhbxodl.setBackgroundColor(Color.parseColor("#797464"));
        ViewFlipper viewFlipper = new ViewFlipper(this);
        this.bjnqilwhpg = viewFlipper;
        viewFlipper.setLayoutParams(new LinearLayout.LayoutParams(1382, 1308));
        this.bjnqilwhpg.setPadding(43, 183, 176, 61);
        linearLayout.addView(this.bjnqilwhpg);
        this.bjnqilwhpg.setBackgroundColor(Color.parseColor("#a70c2e"));
        ViewFlipper viewFlipper2 = new ViewFlipper(this);
        this.tmkqvtthle = viewFlipper2;
        viewFlipper2.setLayoutParams(new LinearLayout.LayoutParams(590, 1085));
        this.tmkqvtthle.setPadding(150, 74, 84, 98);
        linearLayout.addView(this.tmkqvtthle);
        this.tmkqvtthle.setBackgroundColor(Color.parseColor("#cee261"));
        TableLayout tableLayout = new TableLayout(this);
        this.tuxskwvvju = tableLayout;
        tableLayout.setLayoutParams(new LinearLayout.LayoutParams(1730, 253));
        this.tuxskwvvju.setPadding(65, 179, 59, 82);
        linearLayout.addView(this.tuxskwvvju);
        this.tuxskwvvju.setBackgroundColor(Color.parseColor("#67f31f"));
        Spinner spinner = new Spinner(this);
        this.wedumetkam = spinner;
        spinner.setLayoutParams(new LinearLayout.LayoutParams(146, 1312));
        this.wedumetkam.setPadding(159, 197, 28, 140);
        linearLayout.addView(this.wedumetkam);
        this.wedumetkam.setBackgroundColor(Color.parseColor("#b718de"));
        ProgressBar progressBar2 = new ProgressBar(this);
        this.eoextbbutc = progressBar2;
        progressBar2.setLayoutParams(new LinearLayout.LayoutParams(869, 205));
        this.eoextbbutc.setPadding(191, 40, 80, 116);
        linearLayout.addView(this.eoextbbutc);
        this.eoextbbutc.setBackgroundColor(Color.parseColor("#c88ab9"));
        RelativeLayout relativeLayout2 = new RelativeLayout(this);
        this.qfyvthkdac = relativeLayout2;
        relativeLayout2.setLayoutParams(new LinearLayout.LayoutParams(1779, 1727));
        this.qfyvthkdac.setPadding(78, 139, 138, 31);
        linearLayout.addView(this.qfyvthkdac);
        this.qfyvthkdac.setBackgroundColor(Color.parseColor("#797544"));
        ImageView imageView2 = new ImageView(this);
        this.kohngbzsni = imageView2;
        imageView2.setLayoutParams(new LinearLayout.LayoutParams(389, 595));
        this.kohngbzsni.setPadding(118, 109, 15, 172);
        linearLayout.addView(this.kohngbzsni);
        this.kohngbzsni.setBackgroundColor(Color.parseColor("#725215"));
        SeekBar seekBar = new SeekBar(this);
        this.kzixznsivb = seekBar;
        seekBar.setLayoutParams(new LinearLayout.LayoutParams(1392, 1686));
        this.kzixznsivb.setPadding(75, 128, 38, 105);
        linearLayout.addView(this.kzixznsivb);
        this.kzixznsivb.setBackgroundColor(Color.parseColor("#0f427e"));
        Button button2 = new Button(this);
        this.evvhwkxgjz = button2;
        button2.setLayoutParams(new LinearLayout.LayoutParams(1735, 1906));
        this.evvhwkxgjz.setPadding(54, 122, 26, 89);
        linearLayout.addView(this.evvhwkxgjz);
        this.evvhwkxgjz.setBackgroundColor(Color.parseColor("#abcf3d"));
        ProgressBar progressBar3 = new ProgressBar(this);
        this.doknaaifka = progressBar3;
        progressBar3.setLayoutParams(new LinearLayout.LayoutParams(151, 1661));
        this.doknaaifka.setPadding(193, 97, 66, 184);
        linearLayout.addView(this.doknaaifka);
        this.doknaaifka.setBackgroundColor(Color.parseColor("#a778fb"));
        ProgressBar progressBar4 = new ProgressBar(this);
        this.putlyqaspa = progressBar4;
        progressBar4.setLayoutParams(new LinearLayout.LayoutParams(1284, 695));
        this.putlyqaspa.setPadding(83, 177, 18, 7);
        linearLayout.addView(this.putlyqaspa);
        this.putlyqaspa.setBackground(new Tufsbbqbczh());
        TimePicker timePicker = new TimePicker(this);
        this.pmrrgdgcxo = timePicker;
        timePicker.setLayoutParams(new LinearLayout.LayoutParams(730, 1588));
        this.pmrrgdgcxo.setPadding(133, 136, 29, 180);
        linearLayout.addView(this.pmrrgdgcxo);
        this.pmrrgdgcxo.setBackgroundColor(Color.parseColor("#459eaa"));
        ListView listView = new ListView(this);
        this.intejgbfct = listView;
        listView.setLayoutParams(new LinearLayout.LayoutParams(591, 1541));
        this.intejgbfct.setPadding(183, 142, 28, 96);
        linearLayout.addView(this.intejgbfct);
        this.intejgbfct.setBackgroundColor(Color.parseColor("#8c85a4"));
        ViewFlipper viewFlipper3 = new ViewFlipper(this);
        this.vpqyjwhrpz = viewFlipper3;
        viewFlipper3.setLayoutParams(new LinearLayout.LayoutParams(HealthyViewModel.Type_Sync_TimeOut, 143));
        this.vpqyjwhrpz.setPadding(141, 135, 133, 127);
        linearLayout.addView(this.vpqyjwhrpz);
        this.vpqyjwhrpz.setBackgroundColor(Color.parseColor("#634522"));
        Spinner spinner2 = new Spinner(this);
        this.ndhgqvhgpk = spinner2;
        spinner2.setLayoutParams(new LinearLayout.LayoutParams(859, 1632));
        this.ndhgqvhgpk.setPadding(116, 1, 79, 9);
        linearLayout.addView(this.ndhgqvhgpk);
        this.ndhgqvhgpk.setBackgroundColor(Color.parseColor("#861119"));
        Switch r32 = new Switch(this);
        this.pbtapyippv = r32;
        r32.setLayoutParams(new LinearLayout.LayoutParams(275, 664));
        this.pbtapyippv.setPadding(183, 8, 15, 137);
        linearLayout.addView(this.pbtapyippv);
        this.pbtapyippv.setBackgroundColor(Color.parseColor("#c2e033"));
        TextView textView = new TextView(this);
        this.pdkdpnrbvh = textView;
        textView.setLayoutParams(new LinearLayout.LayoutParams(1186, 1598));
        this.pdkdpnrbvh.setPadding(8, 140, 90, 18);
        linearLayout.addView(this.pdkdpnrbvh);
        this.pdkdpnrbvh.setBackgroundColor(Color.parseColor("#1a59ce"));
        LinearLayout linearLayout2 = new LinearLayout(this);
        this.gzksjtdryg = linearLayout2;
        linearLayout2.setLayoutParams(new LinearLayout.LayoutParams(1529, 70));
        this.gzksjtdryg.setPadding(197, 93, 113, 104);
        linearLayout.addView(this.gzksjtdryg);
        this.gzksjtdryg.setBackgroundColor(Color.parseColor("#fc5d3e"));
        ListView listView2 = new ListView(this);
        this.lhfgjdosfv = listView2;
        listView2.setLayoutParams(new LinearLayout.LayoutParams(1856, 165));
        this.lhfgjdosfv.setPadding(31, 156, 20, 175);
        linearLayout.addView(this.lhfgjdosfv);
        this.lhfgjdosfv.setBackgroundColor(Color.parseColor("#0873a8"));
        GridView gridView = new GridView(this);
        this.rfvcgzmowu = gridView;
        gridView.setLayoutParams(new LinearLayout.LayoutParams(1352, 1482));
        this.rfvcgzmowu.setPadding(191, BDLocation.TypeServerError, 166, 187);
        linearLayout.addView(this.rfvcgzmowu);
        this.rfvcgzmowu.setBackgroundColor(Color.parseColor("#d5c4e7"));
        DatePicker datePicker = new DatePicker(this);
        this.cyzidorxjs = datePicker;
        datePicker.setLayoutParams(new LinearLayout.LayoutParams(53, 1937));
        this.cyzidorxjs.setPadding(114, 73, 48, 133);
        linearLayout.addView(this.cyzidorxjs);
        this.cyzidorxjs.setBackgroundColor(Color.parseColor("#f00f26"));
        TableLayout tableLayout2 = new TableLayout(this);
        this.isffbtogah = tableLayout2;
        tableLayout2.setLayoutParams(new LinearLayout.LayoutParams(321, TypedValues.TransitionType.TYPE_TO));
        this.isffbtogah.setPadding(196, 141, 154, 142);
        linearLayout.addView(this.isffbtogah);
        this.isffbtogah.setBackgroundColor(Color.parseColor("#3cb462"));
        TableLayout tableLayout3 = new TableLayout(this);
        this.psgmobsyku = tableLayout3;
        tableLayout3.setLayoutParams(new LinearLayout.LayoutParams(1875, 1516));
        this.psgmobsyku.setPadding(153, 125, 3, 186);
        linearLayout.addView(this.psgmobsyku);
        this.psgmobsyku.setBackgroundColor(Color.parseColor("#6528f5"));
        SeekBar seekBar2 = new SeekBar(this);
        this.gcphsgpzrs = seekBar2;
        seekBar2.setLayoutParams(new LinearLayout.LayoutParams(374, 329));
        this.gcphsgpzrs.setPadding(183, 123, 186, 10);
        linearLayout.addView(this.gcphsgpzrs);
        this.gcphsgpzrs.setBackgroundColor(Color.parseColor("#9a8523"));
        ProgressBar progressBar5 = new ProgressBar(this);
        this.zmtfjhasgb = progressBar5;
        progressBar5.setLayoutParams(new LinearLayout.LayoutParams(1325, 22));
        this.zmtfjhasgb.setPadding(152, 74, 108, 103);
        linearLayout.addView(this.zmtfjhasgb);
        this.zmtfjhasgb.setBackgroundColor(Color.parseColor("#ef5d9c"));
        TableLayout tableLayout4 = new TableLayout(this);
        this.viloinyemn = tableLayout4;
        tableLayout4.setLayoutParams(new LinearLayout.LayoutParams(716, 1927));
        this.viloinyemn.setPadding(44, 50, 101, 8);
        linearLayout.addView(this.viloinyemn);
        this.viloinyemn.setBackgroundColor(Color.parseColor("#9d52da"));
        Switch r2 = new Switch(this);
        this.qwciylinve = r2;
        r2.setLayoutParams(new LinearLayout.LayoutParams(1162, 1581));
        this.qwciylinve.setPadding(115, 79, 139, 55);
        linearLayout.addView(this.qwciylinve);
        this.qwciylinve.setBackgroundColor(Color.parseColor("#ba8640"));
        FrameLayout frameLayout3 = new FrameLayout(this);
        this.wbngmnrvqh = frameLayout3;
        frameLayout3.setLayoutParams(new LinearLayout.LayoutParams(859, 916));
        this.wbngmnrvqh.setPadding(BDLocation.TypeNetWorkLocation, 125, 69, 30);
        linearLayout.addView(this.wbngmnrvqh);
        this.wbngmnrvqh.setBackgroundColor(Color.parseColor("#49ca5f"));
        Switch r22 = new Switch(this);
        this.pdhlhbbirt = r22;
        r22.setLayoutParams(new LinearLayout.LayoutParams(1281, 1269));
        this.pdhlhbbirt.setPadding(179, 171, 164, 192);
        linearLayout.addView(this.pdhlhbbirt);
        this.pdhlhbbirt.setBackgroundColor(Color.parseColor("#4d9a7e"));
        RadioButton radioButton = new RadioButton(this);
        this.bdefshcytv = radioButton;
        radioButton.setLayoutParams(new LinearLayout.LayoutParams(1737, 1553));
        this.bdefshcytv.setPadding(158, 144, 103, 174);
        linearLayout.addView(this.bdefshcytv);
        this.bdefshcytv.setBackgroundColor(Color.parseColor("#8b8f57"));
        LinearLayout linearLayout3 = new LinearLayout(this);
        this.kuvjhpcnlq = linearLayout3;
        linearLayout3.setLayoutParams(new LinearLayout.LayoutParams(PointerIconCompat.TYPE_GRAB, 1279));
        this.kuvjhpcnlq.setPadding(159, 94, BDLocation.TypeNetWorkLocation, 144);
        linearLayout.addView(this.kuvjhpcnlq);
        this.kuvjhpcnlq.setBackgroundColor(Color.parseColor("#0730b7"));
        TimePicker timePicker2 = new TimePicker(this);
        this.lufanfaodn = timePicker2;
        timePicker2.setLayoutParams(new LinearLayout.LayoutParams(1780, 1035));
        this.lufanfaodn.setPadding(181, 114, 104, 52);
        linearLayout.addView(this.lufanfaodn);
        this.lufanfaodn.setBackgroundColor(Color.parseColor("#2684a4"));
        ProgressBar progressBar6 = new ProgressBar(this);
        this.mvauywttau = progressBar6;
        progressBar6.setLayoutParams(new LinearLayout.LayoutParams(1974, 1445));
        this.mvauywttau.setPadding(108, 173, 124, 152);
        linearLayout.addView(this.mvauywttau);
        this.mvauywttau.setBackgroundColor(Color.parseColor("#d79ae7"));
        DatePicker datePicker2 = new DatePicker(this);
        this.jziyxclucu = datePicker2;
        datePicker2.setLayoutParams(new LinearLayout.LayoutParams(390, 1866));
        this.jziyxclucu.setPadding(108, 67, 79, 23);
        linearLayout.addView(this.jziyxclucu);
        this.jziyxclucu.setBackgroundColor(Color.parseColor("#d63486"));
        ImageView imageView3 = new ImageView(this);
        this.eobrhbugxr = imageView3;
        imageView3.setLayoutParams(new LinearLayout.LayoutParams(301, 1802));
        this.eobrhbugxr.setPadding(174, 46, 99, 195);
        linearLayout.addView(this.eobrhbugxr);
        this.eobrhbugxr.setBackgroundColor(Color.parseColor("#97cad9"));
        ProgressBar progressBar7 = new ProgressBar(this);
        this.kwmnobmdew = progressBar7;
        progressBar7.setLayoutParams(new LinearLayout.LayoutParams(94, 846));
        this.kwmnobmdew.setPadding(BDLocation.TypeServerError, 77, 70, 143);
        linearLayout.addView(this.kwmnobmdew);
        this.kwmnobmdew.setBackgroundColor(Color.parseColor("#1536d9"));
        TimePicker timePicker3 = new TimePicker(this);
        this.zjmjzdlasd = timePicker3;
        timePicker3.setLayoutParams(new LinearLayout.LayoutParams(1552, 381));
        this.zjmjzdlasd.setPadding(21, WebSocketProtocol.PAYLOAD_SHORT, 170, 166);
        linearLayout.addView(this.zjmjzdlasd);
        this.zjmjzdlasd.setBackgroundColor(Color.parseColor("#baec84"));
        ImageView imageView4 = new ImageView(this);
        this.wteokyslvv = imageView4;
        imageView4.setLayoutParams(new LinearLayout.LayoutParams(670, 1091));
        this.wteokyslvv.setPadding(159, 198, 121, 164);
        linearLayout.addView(this.wteokyslvv);
        this.wteokyslvv.setBackgroundColor(Color.parseColor("#2c6955"));
        CheckBox checkBox = new CheckBox(this);
        this.ftnwuepbli = checkBox;
        checkBox.setLayoutParams(new LinearLayout.LayoutParams(1122, 1381));
        this.ftnwuepbli.setPadding(50, 57, 125, 23);
        linearLayout.addView(this.ftnwuepbli);
        this.ftnwuepbli.setBackgroundColor(Color.parseColor("#8e395e"));
        ScrollView scrollView = new ScrollView(this);
        this.kinqhnvcbp = scrollView;
        scrollView.setLayoutParams(new LinearLayout.LayoutParams(1240, 412));
        this.kinqhnvcbp.setPadding(54, 146, WebSocketProtocol.PAYLOAD_SHORT, 147);
        linearLayout.addView(this.kinqhnvcbp);
        this.kinqhnvcbp.setBackgroundColor(Color.parseColor("#9759f5"));
        GridView gridView2 = new GridView(this);
        this.wbmvsxovoc = gridView2;
        gridView2.setLayoutParams(new LinearLayout.LayoutParams(326, 1925));
        this.wbmvsxovoc.setPadding(16, 105, 84, 97);
        linearLayout.addView(this.wbmvsxovoc);
        this.wbmvsxovoc.setBackgroundColor(Color.parseColor("#0d7949"));
        TimePicker timePicker4 = new TimePicker(this);
        this.jxokxsqjkx = timePicker4;
        timePicker4.setLayoutParams(new LinearLayout.LayoutParams(753, 714));
        this.jxokxsqjkx.setPadding(153, 172, 20, 123);
        linearLayout.addView(this.jxokxsqjkx);
        this.jxokxsqjkx.setBackgroundColor(Color.parseColor("#47f183"));
        GridView gridView3 = new GridView(this);
        this.qntovulrde = gridView3;
        gridView3.setLayoutParams(new LinearLayout.LayoutParams(1314, 1864));
        this.qntovulrde.setPadding(172, 59, 111, 109);
        linearLayout.addView(this.qntovulrde);
        this.qntovulrde.setBackgroundColor(Color.parseColor("#484684"));
        LinearLayout linearLayout4 = new LinearLayout(this);
        this.zdrvwezfxj = linearLayout4;
        linearLayout4.setLayoutParams(new LinearLayout.LayoutParams(1935, 645));
        this.zdrvwezfxj.setPadding(5, 28, PictureConfig.CHOOSE_REQUEST, 83);
        linearLayout.addView(this.zdrvwezfxj);
        this.zdrvwezfxj.setBackgroundColor(Color.parseColor("#25ae2c"));
        GridView gridView4 = new GridView(this);
        this.szuypufatv = gridView4;
        gridView4.setLayoutParams(new LinearLayout.LayoutParams(1086, 964));
        this.szuypufatv.setPadding(198, 184, 135, 186);
        linearLayout.addView(this.szuypufatv);
        this.szuypufatv.setBackgroundColor(Color.parseColor("#717e9d"));
        ScrollView scrollView2 = new ScrollView(this);
        this.chjgdzoptd = scrollView2;
        scrollView2.setLayoutParams(new LinearLayout.LayoutParams(1323, 48));
        this.chjgdzoptd.setPadding(131, 177, 148, 60);
        linearLayout.addView(this.chjgdzoptd);
        this.chjgdzoptd.setBackgroundColor(Color.parseColor("#5b1469"));
        Button button3 = new Button(this);
        this.adljtlfobk = button3;
        button3.setLayoutParams(new LinearLayout.LayoutParams(914, 282));
        this.adljtlfobk.setPadding(94, 137, 116, 196);
        linearLayout.addView(this.adljtlfobk);
        this.adljtlfobk.setBackgroundColor(Color.parseColor("#28c765"));
        GridView gridView5 = new GridView(this);
        this.zxqccodzog = gridView5;
        gridView5.setLayoutParams(new LinearLayout.LayoutParams(1216, 376));
        this.zxqccodzog.setPadding(69, 135, 71, 35);
        linearLayout.addView(this.zxqccodzog);
        this.zxqccodzog.setBackgroundColor(Color.parseColor("#5bf890"));
        ProgressBar progressBar8 = new ProgressBar(this);
        this.cphjizrwgn = progressBar8;
        progressBar8.setLayoutParams(new LinearLayout.LayoutParams(892, 723));
        this.cphjizrwgn.setPadding(32, 184, 194, 183);
        linearLayout.addView(this.cphjizrwgn);
        this.cphjizrwgn.setBackgroundColor(Color.parseColor("#30c9f6"));
        ListView listView3 = new ListView(this);
        this.hlevnmdlid = listView3;
        listView3.setLayoutParams(new LinearLayout.LayoutParams(347, 1172));
        this.hlevnmdlid.setPadding(63, 176, BDLocation.TypeServerError, 95);
        linearLayout.addView(this.hlevnmdlid);
        this.hlevnmdlid.setBackgroundColor(Color.parseColor("#a6b2a1"));
        ToggleButton toggleButton = new ToggleButton(this);
        this.rxwngswotl = toggleButton;
        toggleButton.setLayoutParams(new LinearLayout.LayoutParams(648, 723));
        this.rxwngswotl.setPadding(176, 108, 26, 116);
        linearLayout.addView(this.rxwngswotl);
        this.rxwngswotl.setBackgroundColor(Color.parseColor("#8568ba"));
        ScrollView scrollView3 = new ScrollView(this);
        this.vvrjoxwbsb = scrollView3;
        scrollView3.setLayoutParams(new LinearLayout.LayoutParams(137, 1076));
        this.vvrjoxwbsb.setPadding(96, 166, 92, 29);
        linearLayout.addView(this.vvrjoxwbsb);
        this.vvrjoxwbsb.setBackgroundColor(Color.parseColor("#329e56"));
        TimePicker timePicker5 = new TimePicker(this);
        this.lnujspncva = timePicker5;
        timePicker5.setLayoutParams(new LinearLayout.LayoutParams(1062, 664));
        this.lnujspncva.setPadding(184, 132, 56, 184);
        linearLayout.addView(this.lnujspncva);
        this.lnujspncva.setBackgroundColor(Color.parseColor("#f88eb5"));
        TimePicker timePicker6 = new TimePicker(this);
        this.txcpwdlukr = timePicker6;
        timePicker6.setLayoutParams(new LinearLayout.LayoutParams(716, 1653));
        this.txcpwdlukr.setPadding(87, 37, 91, 170);
        linearLayout.addView(this.txcpwdlukr);
        this.txcpwdlukr.setBackgroundColor(Color.parseColor("#bb415e"));
        TextView textView2 = new TextView(this);
        this.etoyrbcpnr = textView2;
        textView2.setLayoutParams(new LinearLayout.LayoutParams(456, 810));
        this.etoyrbcpnr.setPadding(54, 49, 144, 43);
        linearLayout.addView(this.etoyrbcpnr);
        this.etoyrbcpnr.setBackgroundColor(Color.parseColor("#8c179b"));
        GridView gridView6 = new GridView(this);
        this.ktqvnzldbv = gridView6;
        gridView6.setLayoutParams(new LinearLayout.LayoutParams(471, 1898));
        this.ktqvnzldbv.setPadding(166, 45, 120, 120);
        linearLayout.addView(this.ktqvnzldbv);
        this.ktqvnzldbv.setBackgroundColor(Color.parseColor("#6c98dc"));
        Button button4 = new Button(this);
        this.yuebnltxzb = button4;
        button4.setLayoutParams(new LinearLayout.LayoutParams(481, 1771));
        this.yuebnltxzb.setPadding(135, BDLocation.TypeCoarseLocation, 48, 125);
        linearLayout.addView(this.yuebnltxzb);
        this.yuebnltxzb.setBackgroundColor(Color.parseColor("#c7936a"));
        Spinner spinner3 = new Spinner(this);
        this.edsrhzjdqk = spinner3;
        spinner3.setLayoutParams(new LinearLayout.LayoutParams(478, 1699));
        this.edsrhzjdqk.setPadding(147, 12, 5, 78);
        linearLayout.addView(this.edsrhzjdqk);
        this.edsrhzjdqk.setBackgroundColor(Color.parseColor("#ac9145"));
        RatingBar ratingBar = new RatingBar(this);
        this.jybecngtwq = ratingBar;
        ratingBar.setLayoutParams(new LinearLayout.LayoutParams(1736, 1910));
        this.jybecngtwq.setPadding(112, 140, 74, 25);
        linearLayout.addView(this.jybecngtwq);
        this.jybecngtwq.setBackgroundColor(Color.parseColor("#9ed801"));
        ToggleButton toggleButton2 = new ToggleButton(this);
        this.tgcippioqx = toggleButton2;
        toggleButton2.setLayoutParams(new LinearLayout.LayoutParams(1576, 1176));
        this.tgcippioqx.setPadding(139, 70, 73, 123);
        linearLayout.addView(this.tgcippioqx);
        this.tgcippioqx.setBackgroundColor(Color.parseColor("#dc0f07"));
        TableLayout tableLayout5 = new TableLayout(this);
        this.vsrlilequz = tableLayout5;
        tableLayout5.setLayoutParams(new LinearLayout.LayoutParams(1140, 1123));
        this.vsrlilequz.setPadding(BDLocation.TypeServerError, 190, 191, 5);
        linearLayout.addView(this.vsrlilequz);
        this.vsrlilequz.setBackgroundColor(Color.parseColor("#d9f353"));
        Spinner spinner4 = new Spinner(this);
        this.xyvrjispkv = spinner4;
        spinner4.setLayoutParams(new LinearLayout.LayoutParams(125, 237));
        this.xyvrjispkv.setPadding(14, 104, 122, 106);
        linearLayout.addView(this.xyvrjispkv);
        this.xyvrjispkv.setBackgroundColor(Color.parseColor("#8f9f53"));
        ListView listView4 = new ListView(this);
        this.zyldsesywt = listView4;
        listView4.setLayoutParams(new LinearLayout.LayoutParams(1743, 496));
        this.zyldsesywt.setPadding(183, 135, 174, 183);
        linearLayout.addView(this.zyldsesywt);
        this.zyldsesywt.setBackgroundColor(Color.parseColor("#0d502c"));
        LinearLayout linearLayout5 = new LinearLayout(this);
        this.rrrxjtadev = linearLayout5;
        linearLayout5.setLayoutParams(new LinearLayout.LayoutParams(1273, TypedValues.AttributesType.TYPE_PIVOT_TARGET));
        this.rrrxjtadev.setPadding(142, 135, 29, 198);
        linearLayout.addView(this.rrrxjtadev);
        this.rrrxjtadev.setBackgroundColor(Color.parseColor("#18ff61"));
        CheckBox checkBox2 = new CheckBox(this);
        this.couoetbgtm = checkBox2;
        checkBox2.setLayoutParams(new LinearLayout.LayoutParams(1812, 136));
        this.couoetbgtm.setPadding(98, 11, 4, 127);
        linearLayout.addView(this.couoetbgtm);
        this.couoetbgtm.setBackgroundColor(Color.parseColor("#bfc00e"));
        ViewFlipper viewFlipper4 = new ViewFlipper(this);
        this.fujujxsyka = viewFlipper4;
        viewFlipper4.setLayoutParams(new LinearLayout.LayoutParams(TypedValues.PositionType.TYPE_PERCENT_WIDTH, 515));
        this.fujujxsyka.setPadding(176, 180, 169, 69);
        linearLayout.addView(this.fujujxsyka);
        this.fujujxsyka.setBackgroundColor(Color.parseColor("#cad7f5"));
        ScrollView scrollView4 = new ScrollView(this);
        this.htemgduocb = scrollView4;
        scrollView4.setLayoutParams(new LinearLayout.LayoutParams(1, 1023));
        this.htemgduocb.setPadding(134, 191, 145, 154);
        linearLayout.addView(this.htemgduocb);
        this.htemgduocb.setBackgroundColor(Color.parseColor("#732bd2"));
        SeekBar seekBar3 = new SeekBar(this);
        this.ykmispqotn = seekBar3;
        seekBar3.setLayoutParams(new LinearLayout.LayoutParams(1352, 1932));
        this.ykmispqotn.setPadding(170, 25, 56, 136);
        linearLayout.addView(this.ykmispqotn);
        this.ykmispqotn.setBackgroundColor(Color.parseColor("#03b1a8"));
        RelativeLayout relativeLayout3 = new RelativeLayout(this);
        this.otmnrimhbp = relativeLayout3;
        relativeLayout3.setLayoutParams(new LinearLayout.LayoutParams(1157, 1154));
        this.otmnrimhbp.setPadding(33, 194, 90, 44);
        linearLayout.addView(this.otmnrimhbp);
        this.otmnrimhbp.setBackgroundColor(Color.parseColor("#435ee7"));
        RadioButton radioButton2 = new RadioButton(this);
        this.wzjzisucba = radioButton2;
        radioButton2.setLayoutParams(new LinearLayout.LayoutParams(570, 1780));
        this.wzjzisucba.setPadding(196, 84, 150, 112);
        linearLayout.addView(this.wzjzisucba);
        this.wzjzisucba.setBackgroundColor(Color.parseColor("#c0a576"));
        TimePicker timePicker7 = new TimePicker(this);
        this.uydhrbkswl = timePicker7;
        timePicker7.setLayoutParams(new LinearLayout.LayoutParams(1492, 42));
        this.uydhrbkswl.setPadding(181, 183, BDLocation.TypeServerDecryptError, 76);
        linearLayout.addView(this.uydhrbkswl);
        this.uydhrbkswl.setBackgroundColor(Color.parseColor("#74a913"));
        GridView gridView7 = new GridView(this);
        this.zebztbxjkf = gridView7;
        gridView7.setLayoutParams(new LinearLayout.LayoutParams(306, 49));
        this.zebztbxjkf.setPadding(120, 90, 169, 16);
        linearLayout.addView(this.zebztbxjkf);
        this.zebztbxjkf.setBackgroundColor(Color.parseColor("#560cf9"));
        Button button5 = new Button(this);
        this.exnzdpbsjr = button5;
        button5.setLayoutParams(new LinearLayout.LayoutParams(15, 568));
        this.exnzdpbsjr.setPadding(133, 15, 8, 138);
        linearLayout.addView(this.exnzdpbsjr);
        this.exnzdpbsjr.setBackgroundColor(Color.parseColor("#c3d33d"));
    }
}
